-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    strptime("end_of_month", '%Y-%m')::DATE AS end_of_month,
    "outstanding_loans_amt",
    "outstanding_loans_amt_mom",
    "outstanding_loans_amt_yoy",
    "outstanding_loans_cofin_gf_amt",
    "outstanding_loans_cofin_gf",
    "outstanding_loans_cofin_ps_amt",
    "outstanding_loans_cofin_ps",
    "delinquency_ratio",
    "delinquency_ratio_6mth",
    "resch_loan_ratio",
    "new_loans_app_received",
    "new_loans_app_received_mom",
    "new_loans_drawn_amt",
    "new_loans_drawn_amt_mom",
    "new_loans_drawn",
    "new_loans_drawn_mom",
    "new_loans_approved_amt",
    "new_loans_approved_amt_mom",
    "new_loans_approved",
    "new_loans_approved_mom",
    "new_loans_approved_avg_size",
    "new_loans_approved_lv_ratio",
    "new_loans_approved_contra_life",
    "new_loans_approved_cofin_amt",
    "new_loans_approved_cofin",
    "new_loans_approved_pt_amt_pri",
    "new_loans_approved_pt_amt_sec",
    "new_loans_approved_pt_amt_refin",
    "new_loans_approved_pt_primkt",
    "new_loans_approved_pt_secmkt",
    "new_loans_approved_pt_refin",
    "new_loans_approved_undrawn_amt",
    "new_loans_approved_undrawn",
    "ir_new_loans_approved_hibor",
    "ir_new_loans_approved_blr",
    "ir_new_loans_approved_fixed",
    "ir_new_loans_approved_other",
    "loan_wo_amt",
    "loan_wo_12mth_amt",
    "loan_wo_12mth_pa_outstand_loans"
FROM "hkma-residential-mortgage-survey"
