-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "end_of_date",
    "cu_weakside",
    "cu_strongside",
    "disc_win_base_rate",
    "hibor_overnight",
    "hibor_fixing_1m",
    "twi",
    "opening_balance",
    "closing_balance",
    "market_activities",
    "interest_payment",
    CAST("discount_window_reversal" AS BIGINT) AS discount_window_reversal,
    "discount_window_activities",
    "intraday_movements_of_aggregate_balance_at_0930",
    "intraday_movements_of_aggregate_balance_at_1000",
    "intraday_movements_of_aggregate_balance_at_1100",
    "intraday_movements_of_aggregate_balance_at_1200",
    "intraday_movements_of_aggregate_balance_at_1500",
    "intraday_movements_of_aggregate_balance_at_1600",
    "forex_trans_t1",
    "other_market_activities_t1",
    CAST("reversal_of_discount_window_t1" AS BIGINT) AS reversal_of_discount_window_t1,
    "interest_payment_issuance_efbn_t1",
    "forecast_aggregate_bal_t1",
    "forex_trans_t2",
    "other_market_activities_t2",
    CAST("reversal_of_discount_window_t2" AS BIGINT) AS reversal_of_discount_window_t2,
    "interest_payment_issuance_efbn_t2",
    "forecast_aggregate_bal_t2",
    "forex_trans_t3",
    "other_market_activities_t3",
    CAST("reversal_of_discount_window_t3" AS BIGINT) AS reversal_of_discount_window_t3,
    "interest_payment_issuance_efbn_t3",
    "forecast_aggregate_bal_t3",
    "forex_trans_t4",
    "other_market_activities_t4",
    CAST("reversal_of_discount_window_t4" AS BIGINT) AS reversal_of_discount_window_t4,
    "interest_payment_issuance_efbn_t4",
    "forecast_aggregate_bal_t4",
    "forex_trans_u",
    "other_market_activities_u",
    CAST("reversal_of_discount_window_u" AS BIGINT) AS reversal_of_discount_window_u,
    CAST("interest_payment_issuance_efbn_u" AS BIGINT) AS interest_payment_issuance_efbn_u,
    "forecast_aggregate_bal_u"
FROM "hkma-daily-interbank-liquidity"
