-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("time_period" AS BIGINT) AS time_period,
    "time_identifier",
    "geographic_level",
    "country_code",
    "country_name",
    "region_code",
    "region_name",
    "old_la_code",
    "new_la_code",
    "la_name",
    "version",
    CAST("education_investment_area_flag" AS BIGINT) AS education_investment_area_flag,
    CAST("priority_area_flag" AS BIGINT) AS priority_area_flag,
    "establishment_type_group",
    CAST("school_count" AS BIGINT) AS school_count,
    CAST("pupil_count" AS BIGINT) AS pupil_count,
    CAST("attainment8_sum" AS DOUBLE) AS attainment8_sum,
    CAST("attainment8_average" AS DOUBLE) AS attainment8_average,
    CAST("engmath_entering_total" AS BIGINT) AS engmath_entering_total,
    CAST("engmath_entering_percent" AS DOUBLE) AS engmath_entering_percent,
    CAST("engmath_95_total" AS BIGINT) AS engmath_95_total,
    CAST("engmath_95_percent" AS DOUBLE) AS engmath_95_percent,
    CAST("engmath_94_total" AS BIGINT) AS engmath_94_total,
    CAST("engmath_94_percent" AS DOUBLE) AS engmath_94_percent,
    CAST("ebacc_entering_total" AS BIGINT) AS ebacc_entering_total,
    CAST("ebacc_entering_percent" AS DOUBLE) AS ebacc_entering_percent,
    CAST("ebacc_95_total" AS BIGINT) AS ebacc_95_total,
    CAST("ebacc_95_percent" AS DOUBLE) AS ebacc_95_percent,
    CAST("ebacc_94_total" AS BIGINT) AS ebacc_94_total,
    CAST("ebacc_94_percent" AS DOUBLE) AS ebacc_94_percent,
    CAST("ebacc_aps_sum" AS DOUBLE) AS ebacc_aps_sum,
    CAST("ebacc_aps_average" AS DOUBLE) AS ebacc_aps_average,
    "progress8_pupil_count",
    "progress8_sum",
    "progress8_average",
    "progress8_lower_95_ci",
    "progress8_upper_95_ci",
    "progress8eng_sum",
    "progress8eng_average",
    "progress8eng_lower_95_ci",
    "progress8eng_upper_95_ci",
    "progress8mat_sum",
    "progress8mat_average",
    "progress8mat_lower_95_ci",
    "progress8mat_upper_95_ci",
    "progress8ebacc_sum",
    "progress8ebacc_average",
    "progress8ebacc_lower_95_ci",
    "progress8ebacc_upper_95_ci",
    "progress8open_sum",
    "progress8open_average",
    "progress8open_lower_95_ci",
    "progress8open_upper_95_ci",
    CAST("gcse_entering_total" AS BIGINT) AS gcse_entering_total,
    CAST("gcse_entering_percent" AS DOUBLE) AS gcse_entering_percent,
    CAST("gcse_91_total" AS BIGINT) AS gcse_91_total,
    CAST("gcse_91_percent" AS DOUBLE) AS gcse_91_percent,
    CAST("ebacceng_entering_total" AS BIGINT) AS ebacceng_entering_total,
    CAST("ebacceng_entering_percent" AS DOUBLE) AS ebacceng_entering_percent,
    CAST("ebaccmat_entering_total" AS BIGINT) AS ebaccmat_entering_total,
    CAST("ebaccmat_entering_percent" AS DOUBLE) AS ebaccmat_entering_percent,
    CAST("ebaccsci_entering_total" AS BIGINT) AS ebaccsci_entering_total,
    CAST("ebaccsci_entering_percent" AS DOUBLE) AS ebaccsci_entering_percent,
    CAST("ebacchum_entering_total" AS BIGINT) AS ebacchum_entering_total,
    CAST("ebacchum_entering_percent" AS DOUBLE) AS ebacchum_entering_percent,
    CAST("ebacclan_entering_total" AS BIGINT) AS ebacclan_entering_total,
    CAST("ebacclan_entering_percent" AS DOUBLE) AS ebacclan_entering_percent,
    CAST("ebacceng_95_total" AS BIGINT) AS ebacceng_95_total,
    CAST("ebacceng_95_percent" AS DOUBLE) AS ebacceng_95_percent,
    CAST("ebaccmat_95_total" AS BIGINT) AS ebaccmat_95_total,
    CAST("ebaccmat_95_percent" AS DOUBLE) AS ebaccmat_95_percent,
    "ebaccsci_95_total",
    "ebaccsci_95_percent",
    "ebacchum_95_total",
    "ebacchum_95_percent",
    "ebacclan_95_total",
    "ebacclan_95_percent",
    CAST("ebacceng_94_total" AS BIGINT) AS ebacceng_94_total,
    CAST("ebacceng_94_percent" AS DOUBLE) AS ebacceng_94_percent,
    CAST("ebaccmat_94_total" AS BIGINT) AS ebaccmat_94_total,
    CAST("ebaccmat_94_percent" AS DOUBLE) AS ebaccmat_94_percent,
    "ebaccsci_94_total",
    "ebaccsci_94_percent",
    "ebacchum_94_total",
    "ebacchum_94_percent",
    "ebacclan_94_total",
    "ebacclan_94_percent",
    CAST("ebacceng_aps_sum" AS BIGINT) AS ebacceng_aps_sum,
    CAST("ebacceng_aps_average" AS DOUBLE) AS ebacceng_aps_average,
    CAST("ebaccmat_aps_sum" AS BIGINT) AS ebaccmat_aps_sum,
    CAST("ebaccmat_aps_average" AS DOUBLE) AS ebaccmat_aps_average,
    "ebaccsci_aps_sum",
    "ebaccsci_aps_average",
    "ebacchum_aps_sum",
    "ebacchum_aps_average",
    "ebacclan_aps_sum",
    "ebacclan_aps_average",
    CAST("attainment8eng_sum" AS BIGINT) AS attainment8eng_sum,
    CAST("attainment8eng_average" AS DOUBLE) AS attainment8eng_average,
    CAST("attainment8mat_sum" AS BIGINT) AS attainment8mat_sum,
    CAST("attainment8mat_average" AS DOUBLE) AS attainment8mat_average,
    CAST("attainment8ebacc_sum" AS DOUBLE) AS attainment8ebacc_sum,
    CAST("attainment8ebacc_average" AS DOUBLE) AS attainment8ebacc_average,
    CAST("attainment8open_sum" AS DOUBLE) AS attainment8open_sum,
    CAST("attainment8open_average" AS DOUBLE) AS attainment8open_average,
    CAST("attainment8open_gcse_sum" AS DOUBLE) AS attainment8open_gcse_sum,
    CAST("attainment8open_gcse_average" AS DOUBLE) AS attainment8open_gcse_average,
    CAST("attainment8open_nongcse_sum" AS DOUBLE) AS attainment8open_nongcse_sum,
    CAST("attainment8open_nongcse_average" AS DOUBLE) AS attainment8open_nongcse_average,
    CAST("attainment8ebacc_slotfill_total" AS BIGINT) AS attainment8ebacc_slotfill_total,
    CAST("attainment8ebacc_slotfill_average" AS DOUBLE) AS attainment8ebacc_slotfill_average,
    CAST("attainment8open_slotfill_total" AS BIGINT) AS attainment8open_slotfill_total,
    CAST("attainment8open_slotfill_average" AS DOUBLE) AS attainment8open_slotfill_average,
    CAST("ebacc_entering_0pillar_total" AS BIGINT) AS ebacc_entering_0pillar_total,
    CAST("ebacc_entering_0pillar_percent" AS DOUBLE) AS ebacc_entering_0pillar_percent,
    CAST("ebacc_entering_1pillar_total" AS BIGINT) AS ebacc_entering_1pillar_total,
    CAST("ebacc_entering_1pillar_percent" AS DOUBLE) AS ebacc_entering_1pillar_percent,
    CAST("ebacc_entering_2pillar_total" AS BIGINT) AS ebacc_entering_2pillar_total,
    CAST("ebacc_entering_2pillar_percent" AS DOUBLE) AS ebacc_entering_2pillar_percent,
    CAST("ebacc_entering_3pillar_total" AS BIGINT) AS ebacc_entering_3pillar_total,
    CAST("ebacc_entering_3pillar_percent" AS DOUBLE) AS ebacc_entering_3pillar_percent,
    CAST("ebacc_entering_4pillar_total" AS BIGINT) AS ebacc_entering_4pillar_total,
    CAST("ebacc_entering_4pillar_percent" AS DOUBLE) AS ebacc_entering_4pillar_percent,
    "ebaccsci_combpath_entering_total",
    "ebaccsci_combpath_entering_percent",
    "ebaccsci_indpath_entering_total",
    "ebaccsci_indpath_entering_percent",
    CAST("sci_triple_entering_total" AS BIGINT) AS sci_triple_entering_total,
    CAST("sci_triple_entering_percent" AS DOUBLE) AS sci_triple_entering_percent,
    CAST("geoghist_entering_total" AS BIGINT) AS geoghist_entering_total,
    CAST("geoghist_entering_percent" AS DOUBLE) AS geoghist_entering_percent,
    CAST("lan_multiple_entering_total" AS BIGINT) AS lan_multiple_entering_total,
    CAST("lan_multiple_entering_percent" AS DOUBLE) AS lan_multiple_entering_percent,
    CAST("art_subject_entering_total" AS BIGINT) AS art_subject_entering_total,
    CAST("art_subject_entering_percent" AS DOUBLE) AS art_subject_entering_percent,
    CAST("music_qual_entering_total" AS BIGINT) AS music_qual_entering_total,
    CAST("music_qual_entering_percent" AS DOUBLE) AS music_qual_entering_percent,
    CAST("art_qual_entering_total" AS BIGINT) AS art_qual_entering_total,
    CAST("art_qual_entering_percent" AS DOUBLE) AS art_qual_entering_percent,
    CAST("ebacceng_91_total" AS BIGINT) AS ebacceng_91_total,
    CAST("ebacceng_91_percent" AS DOUBLE) AS ebacceng_91_percent,
    CAST("ebaccmat_91_total" AS BIGINT) AS ebaccmat_91_total,
    CAST("ebaccmat_91_percent" AS DOUBLE) AS ebaccmat_91_percent,
    "ebaccsci_91_total",
    "ebaccsci_91_percent",
    "ebacchum_91_total",
    "ebacchum_91_percent",
    "ebacclan_91_total",
    "ebacclan_91_percent",
    CAST("ebacc_91_total" AS BIGINT) AS ebacc_91_total,
    CAST("ebacc_91_percent" AS DOUBLE) AS ebacc_91_percent,
    CAST("gcse_five_engmath_total" AS BIGINT) AS gcse_five_engmath_total,
    CAST("gcse_five_engmath_percent" AS DOUBLE) AS gcse_five_engmath_percent,
    "progress8_pupil_percent",
    "progress8_adjusted_total",
    "progress8_adjusted_percent",
    "progress8original_sum",
    "progress8original_average",
    "progress8original_lower_95_ci",
    "progress8original_upper_95_ci",
    "valueaddedsci_pupil_count",
    "valueaddedsci_pupil_percent",
    "valueaddedsci_sum",
    "valueaddedsci_average",
    "valueaddedsci_lower_95_ci",
    "valueaddedsci_upper_95_ci",
    "valueaddedhum_pupil_count",
    "valueaddedhum_pupil_percent",
    "valueaddedhum_sum",
    "valueaddedhum_average",
    "valueaddedhum_lower_95_ci",
    "valueaddedhum_upper_95_ci",
    "valueaddedlan_pupil_count",
    "valueaddedlan_pupil_percent",
    "valueaddedlan_sum",
    "valueaddedlan_average",
    "valueaddedlan_lower_95_ci",
    "valueaddedlan_upper_95_ci",
    CAST("qual_entries_sum" AS DOUBLE) AS qual_entries_sum,
    CAST("qual_entries_average" AS DOUBLE) AS qual_entries_average,
    CAST("gcse_entries_sum" AS BIGINT) AS gcse_entries_sum,
    CAST("gcse_entries_average" AS DOUBLE) AS gcse_entries_average,
    "qual_entries_without_discounting_sum",
    "qual_entries_without_discounting_average"
FROM "dfe-18e39901-b47f-4a75-9c4b-d529e590d916"
