-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("time_period" AS BIGINT) AS time_period,
    "time_identifier",
    "geographic_level",
    "country_code",
    "country_name",
    CAST("alphaind" AS BIGINT) AS alphaind,
    "version",
    CAST("old_la_code" AS BIGINT) AS old_la_code,
    "new_la_code",
    "la_name",
    CAST("school_laestab" AS BIGINT) AS school_laestab,
    CAST("estab" AS BIGINT) AS estab,
    CAST("school_urn" AS BIGINT) AS school_urn,
    "school_name",
    "full_address",
    "address1",
    "address2",
    "address3",
    "telnum",
    "pcon_code",
    "pcon_name",
    CAST("urn_ac" AS BIGINT) AS urn_ac,
    "school_name_ac",
    "open_ac",
    "nftype",
    CAST("iclose" AS BIGINT) AS iclose,
    "reldenom",
    "agerange",
    CAST("tab15" AS BIGINT) AS tab15,
    CAST("tab1618" AS BIGINT) AS tab1618,
    "totpups",
    "tpupyear",
    "telig",
    "belig",
    "gelig",
    "pbelig",
    "pgelig",
    "tks1average",
    "tks1group_l",
    "ptks1group_l",
    "tks1group_m",
    "ptks1group_m",
    "tks1group_h",
    "ptks1group_h",
    "tks1group_na",
    "ptks1group_na",
    "tfsm6cla1a",
    "ptfsm6cla1a",
    "tnotfsm6cla1a",
    "ptnotfsm6cla1a",
    "tealgrp2",
    "ptealgrp2",
    "tmobn",
    "ptmobn",
    "tealgrp1",
    "ptealgrp1",
    "tealgrp3",
    "ptealgrp3",
    "tsenele",
    "psenele",
    "tsenelk",
    "psenelk",
    "tsenelek",
    "psenelek",
    "telig_3yr",
    "telig_23",
    "ptfsm6cla1a_23",
    "ptnotfsm6cla1a_23"
FROM "dfe-019afee4-ba17-73cb-85e0-f88c101bb734"
