-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("time_period" AS BIGINT) AS time_period,
    "time_identifier",
    "geographic_level",
    "country_code",
    "country_name",
    "region_name",
    "region_code",
    CAST("school_urn" AS BIGINT) AS school_urn,
    CAST("old_la_code" AS BIGINT) AS old_la_code,
    "new_la_code",
    "la_name",
    CAST("estab" AS BIGINT) AS estab,
    "school_name",
    CAST("school_laestab" AS BIGINT) AS school_laestab,
    "phase_type_grouping",
    "trust",
    "open_date",
    "sex_of_school_description",
    "establishment_type",
    "middle_school",
    "all_through",
    "hospital_school",
    "religious_denomination",
    "admissions_policy",
    "district_administrative_code",
    "district_administrative_name",
    "pcon_code",
    "pcon_name",
    "ward_code",
    "ward_name",
    "urban_rural",
    "school_postcode",
    "academy_flag",
    "school_size",
    "school_time",
    "attendance_pattern",
    "sex",
    "breakdown_topic",
    "breakdown",
    "pupil_count",
    "pupil_percent"
FROM "dfe-019e7403-4523-7749-b530-159f451dd83c"
