-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("time_period" AS BIGINT) AS time_period,
    "time_identifier",
    "geographic_level",
    "country_code",
    "country_name",
    "version",
    CAST("old_la_code" AS BIGINT) AS old_la_code,
    "new_la_code",
    "la_name",
    "school_name",
    CAST("school_urn" AS BIGINT) AS school_urn,
    CAST("school_laestab" AS BIGINT) AS school_laestab,
    "disadvantage_status",
    "exam_cohort",
    "end1618_student_count",
    "aps_per_entry",
    "aps_per_entry_grade",
    "aps_per_entry_student_count",
    "retained_percent",
    "retained_assessed_percent",
    "retained_student_count",
    "retained_2nd_year_percent",
    "retained_2nd_year_student_count",
    "value_added",
    "value_added_upper_ci",
    "value_added_lower_ci",
    "progress_banding",
    "best_three_alevels_aps",
    "best_three_alevels_grade",
    "best_three_alevels_student_count",
    "aab_percent",
    "aab_student_count",
    "level_3_maths_percent",
    "level_3_maths_student_count",
    "vocational_percent",
    "vocational_student_count",
    "maths_progress",
    "maths_progress_entries_percent",
    "maths_progress_inscope_count",
    "english_progress",
    "english_progress_entries_percent",
    "english_progress_inscope_count"
FROM "dfe-019c2960-81e3-70c2-8d65-72c3718ae4fd"
