-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("time_period" AS BIGINT) AS time_period,
    "time_identifier",
    "geographic_level",
    "country_code",
    "country_name",
    "region_name",
    "region_code",
    "old_la_code",
    "la_name",
    "new_la_code",
    "pcon_code",
    "pcon_name",
    "phase_type_grouping",
    "sen_provision",
    "sen_primary_need",
    CAST("total_pupil_count" AS BIGINT) AS total_pupil_count,
    CAST("nc_early_years_pupil_count" AS BIGINT) AS nc_early_years_pupil_count,
    CAST("nc_reception_pupil_count" AS BIGINT) AS nc_reception_pupil_count,
    CAST("nc_year_1_pupil_count" AS BIGINT) AS nc_year_1_pupil_count,
    CAST("nc_year_2_pupil_count" AS BIGINT) AS nc_year_2_pupil_count,
    CAST("nc_year_3_pupil_count" AS BIGINT) AS nc_year_3_pupil_count,
    CAST("nc_year_4_pupil_count" AS BIGINT) AS nc_year_4_pupil_count,
    CAST("nc_year_5_pupil_count" AS BIGINT) AS nc_year_5_pupil_count,
    CAST("nc_year_6_pupil_count" AS BIGINT) AS nc_year_6_pupil_count,
    CAST("nc_year_7_pupil_count" AS BIGINT) AS nc_year_7_pupil_count,
    CAST("nc_year_8_pupil_count" AS BIGINT) AS nc_year_8_pupil_count,
    CAST("nc_year_9_pupil_count" AS BIGINT) AS nc_year_9_pupil_count,
    CAST("nc_year_10_pupil_count" AS BIGINT) AS nc_year_10_pupil_count,
    CAST("nc_year_11_pupil_count" AS BIGINT) AS nc_year_11_pupil_count,
    CAST("nc_year_12_pupil_count" AS BIGINT) AS nc_year_12_pupil_count,
    CAST("nc_year_13_pupil_count" AS BIGINT) AS nc_year_13_pupil_count,
    CAST("nc_year_14_pupil_count" AS BIGINT) AS nc_year_14_pupil_count,
    CAST("nc_not_followed_pupil_count" AS BIGINT) AS nc_not_followed_pupil_count,
    CAST("nc_early_years_pupil_percent" AS DOUBLE) AS nc_early_years_pupil_percent,
    CAST("nc_reception_pupil_percent" AS DOUBLE) AS nc_reception_pupil_percent,
    CAST("nc_year_1_pupil_percent" AS DOUBLE) AS nc_year_1_pupil_percent,
    CAST("nc_year_2_pupil_percent" AS DOUBLE) AS nc_year_2_pupil_percent,
    CAST("nc_year_3_pupil_percent" AS DOUBLE) AS nc_year_3_pupil_percent,
    CAST("nc_year_4_pupil_percent" AS DOUBLE) AS nc_year_4_pupil_percent,
    CAST("nc_year_5_pupil_percent" AS DOUBLE) AS nc_year_5_pupil_percent,
    CAST("nc_year_6_pupil_percent" AS DOUBLE) AS nc_year_6_pupil_percent,
    CAST("nc_year_7_pupil_percent" AS DOUBLE) AS nc_year_7_pupil_percent,
    CAST("nc_year_8_pupil_percent" AS DOUBLE) AS nc_year_8_pupil_percent,
    CAST("nc_year_9_pupil_percent" AS DOUBLE) AS nc_year_9_pupil_percent,
    CAST("nc_year_10_pupil_percent" AS DOUBLE) AS nc_year_10_pupil_percent,
    CAST("nc_year_11_pupil_percent" AS DOUBLE) AS nc_year_11_pupil_percent,
    CAST("nc_year_12_pupil_percent" AS DOUBLE) AS nc_year_12_pupil_percent,
    CAST("nc_year_13_pupil_percent" AS DOUBLE) AS nc_year_13_pupil_percent,
    CAST("nc_year_14_pupil_percent" AS DOUBLE) AS nc_year_14_pupil_percent,
    CAST("nc_not_followed_pupil_percent" AS DOUBLE) AS nc_not_followed_pupil_percent
FROM "dfe-019df85e-5c5f-7007-abfd-d3067e63007d"
