-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("time_period" AS BIGINT) AS time_period,
    "time_identifier",
    "geographic_level",
    "country_code",
    "country_name",
    "version",
    "establishment_type_group",
    "school_cohort_size",
    "education_phase",
    "school_religious_character",
    "sex",
    "subject",
    "establishment_count",
    "eligible_pupil_count",
    "expected_standard_pupil_count",
    "higher_standard_pupil_count",
    "not_meeting_pupil_count",
    "working_below_pupil_count",
    "absent_pupil_count",
    "progress_measure_eligible_pupil_count",
    "progress_measure_total_score",
    "unable_to_access_arrived_pupil_count",
    "unable_to_access_pupil_count",
    "scaled_scores_eligible_pupil_count",
    "scaled_scores_total",
    "working_towards_pupil_count",
    "pre_ks_std_6_pupil_count",
    "pre_ks_std_5_pupil_count",
    "pre_ks_std_4_pupil_count",
    "pre_ks_std_3_pupil_count",
    "pre_ks_std_2_pupil_count",
    "pre_ks_std_1_pupil_count",
    "growing_dev_of_expected_std_pupil_count",
    "early_dev_of_expected_std_pupil_count",
    "foundations_of_expected_std_pupil_count",
    "engagement_model_or_below_pre_ks_std_pupil_count",
    "below_interim_pre_ks_std_pupil_count",
    "disapplied_pupil_count",
    "expected_standard_pupil_percent",
    "higher_standard_pupil_percent",
    "not_meeting_pupil_percent",
    "working_below_pupil_percent",
    "absent_pupil_percent",
    "unable_to_access_arrived_pupil_percent",
    "unable_to_access_pupil_percent",
    "average_scaled_score",
    "progress_measure_score",
    "progress_measure_lower_conf_interval",
    "progress_measure_upper_conf_interval",
    "working_towards_pupil_percent",
    "pre_ks_std_6_pupil_percent",
    "pre_ks_std_5_pupil_percent",
    "pre_ks_std_4_pupil_percent",
    "pre_ks_std_3_pupil_percent",
    "pre_ks_std_2_pupil_percent",
    "pre_ks_std_1_pupil_percent",
    "growing_dev_of_expected_std_pupil_percent",
    "early_dev_of_expected_std_pupil_percent",
    "foundations_of_expected_std_pupil_percent",
    "engagement_model_or_below_pre_ks_std_pupil_percent",
    "below_interim_pre_ks_std_pupil_percent",
    "disapplied_pupil_percent"
FROM "dfe-0e2f9901-af3b-9f77-9e7d-3a93fd7c015e"
