-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("time_period" AS BIGINT) AS time_period,
    "time_identifier",
    "geographic_level",
    "country_code",
    "country_name",
    "version",
    "establishment_type_group",
    "sex",
    "disadvantage_status",
    "fsm_status",
    "ethnicity_major",
    "ethnicity_minor",
    "first_language",
    "month_of_birth",
    "sen_provision",
    "sen_primary_need",
    CAST("establishment_count" AS BIGINT) AS establishment_count,
    "rwm_eligible_pupil_count",
    "rwm_expected_standard_pupil_count",
    "rm_nw_expected_standard_pupil_count",
    "rw_nm_expected_standard_pupil_count",
    "wm_nr_expected_standard_pupil_count",
    "two_subjects_expected_standard_pupil_count",
    "r_nwm_expected_standard_pupil_count",
    "w_nrm_expected_standard_pupil_count",
    "m_nrw_expected_standard_pupil_count",
    "one_subject_expected_standard_pupil_count",
    "rwm_not_expected_standard_pupil_count",
    "non_assessed_pupil_count",
    "at_least_one_below_test_standard_pupil_count",
    "other_combinations_pupil_count",
    "rwm_expected_standard_pupil_percent",
    "rm_nw_expected_standard_pupil_percent",
    "rw_nm_expected_standard_pupil_percent",
    "wm_nr_expected_standard_pupil_percent",
    "two_subjects_expected_standard_pupil_percent",
    "r_nwm_expected_standard_pupil_percent",
    "w_nrm_expected_standard_pupil_percent",
    "m_nrw_expected_standard_pupil_percent",
    "one_subject_expected_standard_pupil_percent",
    "rwm_not_expected_standard_pupil_percent",
    "non_assessed_pupil_percent",
    "at_least_one_below_test_standard_pupil_percent",
    "other_combinations_pupil_percent"
FROM "dfe-22339901-6f3a-7272-8576-03b26377d4ee"
