-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("time_period" AS BIGINT) AS time_period,
    "time_identifier",
    "geographic_level",
    "country_code",
    "country_name",
    "region_name",
    "region_code",
    "old_la_code",
    "la_name",
    "new_la_code",
    "pcon_code",
    "pcon_name",
    "phase_type_grouping",
    "sen_provision",
    "sen_primary_need",
    "sex",
    CAST("age_total_pupil_count" AS BIGINT) AS age_total_pupil_count,
    CAST("age_2_and_under_pupil_count" AS BIGINT) AS age_2_and_under_pupil_count,
    CAST("age_3_term_summer_pupil_count" AS BIGINT) AS age_3_term_summer_pupil_count,
    CAST("age_3_term_spring_pupil_count" AS BIGINT) AS age_3_term_spring_pupil_count,
    CAST("age_3_term_autumn_pupil_count" AS BIGINT) AS age_3_term_autumn_pupil_count,
    CAST("age_4_term_summer_pupil_count" AS BIGINT) AS age_4_term_summer_pupil_count,
    CAST("age_4_term_spring_pupil_count" AS BIGINT) AS age_4_term_spring_pupil_count,
    CAST("age_4_term_autumn_pupil_count" AS BIGINT) AS age_4_term_autumn_pupil_count,
    CAST("age_5_pupil_count" AS BIGINT) AS age_5_pupil_count,
    CAST("age_6_pupil_count" AS BIGINT) AS age_6_pupil_count,
    CAST("age_7_pupil_count" AS BIGINT) AS age_7_pupil_count,
    CAST("age_8_pupil_count" AS BIGINT) AS age_8_pupil_count,
    CAST("age_9_pupil_count" AS BIGINT) AS age_9_pupil_count,
    CAST("age_10_pupil_count" AS BIGINT) AS age_10_pupil_count,
    CAST("age_11_pupil_count" AS BIGINT) AS age_11_pupil_count,
    CAST("age_12_pupil_count" AS BIGINT) AS age_12_pupil_count,
    CAST("age_13_pupil_count" AS BIGINT) AS age_13_pupil_count,
    CAST("age_14_pupil_count" AS BIGINT) AS age_14_pupil_count,
    CAST("age_15_pupil_count" AS BIGINT) AS age_15_pupil_count,
    CAST("age_16_pupil_count" AS BIGINT) AS age_16_pupil_count,
    CAST("age_17_pupil_count" AS BIGINT) AS age_17_pupil_count,
    CAST("age_18_pupil_count" AS BIGINT) AS age_18_pupil_count,
    CAST("age_19_and_over_pupil_count" AS BIGINT) AS age_19_and_over_pupil_count,
    CAST("age_total_pupil_percent" AS DOUBLE) AS age_total_pupil_percent,
    CAST("age_2_and_under_pupil_percent" AS DOUBLE) AS age_2_and_under_pupil_percent,
    CAST("age_3_term_summer_pupil_percent" AS DOUBLE) AS age_3_term_summer_pupil_percent,
    CAST("age_3_term_spring_pupil_percent" AS DOUBLE) AS age_3_term_spring_pupil_percent,
    CAST("age_3_term_autumn_pupil_percent" AS DOUBLE) AS age_3_term_autumn_pupil_percent,
    CAST("age_4_term_summer_pupil_percent" AS DOUBLE) AS age_4_term_summer_pupil_percent,
    CAST("age_4_term_spring_pupil_percent" AS DOUBLE) AS age_4_term_spring_pupil_percent,
    CAST("age_4_term_autumn_pupil_percent" AS DOUBLE) AS age_4_term_autumn_pupil_percent,
    CAST("age_5_pupil_percent" AS DOUBLE) AS age_5_pupil_percent,
    CAST("age_6_pupil_percent" AS DOUBLE) AS age_6_pupil_percent,
    CAST("age_7_pupil_percent" AS DOUBLE) AS age_7_pupil_percent,
    CAST("age_8_pupil_percent" AS DOUBLE) AS age_8_pupil_percent,
    CAST("age_9_pupil_percent" AS DOUBLE) AS age_9_pupil_percent,
    CAST("age_10_pupil_percent" AS DOUBLE) AS age_10_pupil_percent,
    CAST("age_11_pupil_percent" AS DOUBLE) AS age_11_pupil_percent,
    CAST("age_12_pupil_percent" AS DOUBLE) AS age_12_pupil_percent,
    CAST("age_13_pupil_percent" AS DOUBLE) AS age_13_pupil_percent,
    CAST("age_14_pupil_percent" AS DOUBLE) AS age_14_pupil_percent,
    CAST("age_15_pupil_percent" AS DOUBLE) AS age_15_pupil_percent,
    CAST("age_16_pupil_percent" AS DOUBLE) AS age_16_pupil_percent,
    CAST("age_17_pupil_percent" AS DOUBLE) AS age_17_pupil_percent,
    CAST("age_18_pupil_percent" AS DOUBLE) AS age_18_pupil_percent,
    CAST("age_19_and_over_pupil_percent" AS DOUBLE) AS age_19_and_over_pupil_percent
FROM "dfe-019df85d-2e6c-7411-942d-5fc8366e636c"
