-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "record_id",
    CAST("site" AS BIGINT) AS site,
    "state_territory",
    "source",
    "county_fips",
    "counties_served",
    CAST("population_served" AS BIGINT) AS population_served,
    "sample_id",
    strptime("sample_collect_date", '%Y-%m-%d')::DATE AS sample_collect_date,
    "sample_type",
    "sample_matrix",
    "sample_location",
    CAST("flow_rate" AS DOUBLE) AS flow_rate,
    "concentration_method",
    "pasteurized",
    "pcr_type",
    "extraction_method",
    CAST("major_lab_method" AS BIGINT) AS major_lab_method,
    "inhibition_detect",
    "inhibition_adjust",
    "ntc_amplify",
    "pcr_target",
    "pcr_gene_target_agg",
    CAST("pcr_target_avg_conc" AS DOUBLE) AS pcr_target_avg_conc,
    "pcr_target_units",
    CAST("lod_sewage" AS DOUBLE) AS lod_sewage,
    "pcr_target_detect",
    CAST("pcr_target_avg_conc_lin" AS DOUBLE) AS pcr_target_avg_conc_lin,
    CAST("pcr_target_flowpop_lin" AS DOUBLE) AS pcr_target_flowpop_lin,
    CAST("pcr_target_mic_lin" AS DOUBLE) AS pcr_target_mic_lin,
    "hum_frac_target_mic",
    CAST("hum_frac_mic_conc" AS DOUBLE) AS hum_frac_mic_conc,
    "hum_frac_mic_unit",
    CAST("rec_eff_percent" AS DOUBLE) AS rec_eff_percent,
    "rec_eff_target_name",
    "rec_eff_spike_matrix",
    CAST("rec_eff_spike_conc" AS DOUBLE) AS rec_eff_spike_conc,
    "date_updated"
FROM "cdc-xpxn-rzgz"
