-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("Record Number" AS BIGINT) AS record_number,
    "Reference Type" AS reference_type,
    "Author" AS author,
    CAST("Year" AS BIGINT) AS year,
    "Title" AS title,
    "Secondary Author" AS secondary_author,
    "Secondary Title" AS secondary_title,
    "Publisher" AS publisher,
    CAST("Volume" AS BIGINT) AS volume,
    "Number of Volumes" AS number_of_volumes,
    "Number" AS number,
    "Pages" AS pages,
    "Section" AS section,
    "Tertiary Author" AS tertiary_author,
    "Tertiary Title" AS tertiary_title,
    "Edition" AS edition,
    "Date" AS date,
    "Type of Work" AS type_of_work,
    "Subsidiary Author" AS subsidiary_author,
    "Short Title" AS short_title,
    "Alternate Title" AS alternate_title,
    "ISBN/ISSN" AS isbn_issn,
    "Original Publication" AS original_publication,
    "Reprint Edition" AS reprint_edition,
    "Reviewed Item" AS reviewed_item,
    "Custom 1" AS custom_1,
    "Custom 2" AS custom_2,
    "Custom 3" AS custom_3,
    "Custom 4" AS custom_4,
    "Custom 5" AS custom_5,
    "Custom 6" AS custom_6,
    "Custom 7" AS custom_7,
    "Custom 8" AS custom_8,
    CAST("Accession Number" AS BIGINT) AS accession_number,
    "Call Number" AS call_number,
    "Label" AS label,
    "Keywords" AS keywords,
    "Abstract" AS abstract,
    "Notes" AS notes,
    "Research Notes" AS research_notes,
    "URL" AS url,
    "Author Address" AS author_address,
    "Figure" AS figure,
    "Caption" AS caption,
    "Access Date" AS access_date,
    "Translated Author" AS translated_author,
    "Translated Title" AS translated_title,
    "Name of Database" AS name_of_database,
    "Database Provider" AS database_provider,
    "Language" AS language,
    "Publisher location" AS publisher_location,
    "DOI" AS doi
FROM "cdc-biid-68vb"
