-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    strptime("Week Ending Date", '%Y-%m-%d')::DATE AS week_ending_date,
    "Geographic aggregation" AS geographic_aggregation,
    CAST("Number of Inpatient Beds" AS DOUBLE) AS number_of_inpatient_beds,
    CAST("Number of Adult Inpatient Beds" AS DOUBLE) AS number_of_adult_inpatient_beds,
    CAST("Number of Pediatric Inpatient beds" AS BIGINT) AS number_of_pediatric_inpatient_beds,
    CAST("Number of Inpatient Beds Occupied" AS DOUBLE) AS number_of_inpatient_beds_occupied,
    CAST("Number of Adult Inpatient Beds Occupied" AS DOUBLE) AS number_of_adult_inpatient_beds_occupied,
    CAST("Number of Pediatric Inpatient Beds Occupied" AS DOUBLE) AS number_of_pediatric_inpatient_beds_occupied,
    CAST("Number of ICU Beds" AS BIGINT) AS number_of_icu_beds,
    CAST("Number of Adult ICU Beds" AS BIGINT) AS number_of_adult_icu_beds,
    CAST("Number of Pediatric ICU Beds" AS BIGINT) AS number_of_pediatric_icu_beds,
    CAST("Number of ICU Beds Occupied" AS DOUBLE) AS number_of_icu_beds_occupied,
    CAST("Number of Adult ICU Beds Occupied" AS DOUBLE) AS number_of_adult_icu_beds_occupied,
    CAST("Number of Pediatric ICU Beds Occupied" AS DOUBLE) AS number_of_pediatric_icu_beds_occupied,
    CAST("Number of Adult Patients Hospitalized with COVID-19" AS DOUBLE) AS number_of_adult_patients_hospitalized_with_covid_19,
    CAST("Number of Pediatric Patients Hospitalized with COVID-19" AS DOUBLE) AS number_of_pediatric_patients_hospitalized_with_covid_19,
    CAST("Total Patients Hospitalized with COVID-19" AS BIGINT) AS total_patients_hospitalized_with_covid_19,
    CAST("Number of  Adult Patients Hospitalized with Influenza" AS BIGINT) AS number_of_adult_patients_hospitalized_with_influenza,
    CAST("Number of Pedatric Patients Hospitalized with Influenza" AS BIGINT) AS number_of_pedatric_patients_hospitalized_with_influenza,
    CAST("Total Patients Hospitalized with Influenza" AS DOUBLE) AS total_patients_hospitalized_with_influenza,
    CAST("Number of Adult Patients Hospitalized with RSV" AS BIGINT) AS number_of_adult_patients_hospitalized_with_rsv,
    CAST("Number of Pediatric Patients Hospitalized with RSV" AS BIGINT) AS number_of_pediatric_patients_hospitalized_with_rsv,
    CAST("Total Patients Hospitalized with RSV" AS BIGINT) AS total_patients_hospitalized_with_rsv,
    CAST("Number of Adult ICU Patients Hospitalized with COVID-19" AS BIGINT) AS number_of_adult_icu_patients_hospitalized_with_covid_19,
    CAST("Number of Pediatric ICU Patients Hospitalized with COVID-19" AS DOUBLE) AS number_of_pediatric_icu_patients_hospitalized_with_covid_19,
    CAST("Total ICU Patients Hospitalized with COVID-19" AS BIGINT) AS total_icu_patients_hospitalized_with_covid_19,
    CAST("Number of Adult ICU Patients Hospitalized with Influenza" AS BIGINT) AS number_of_adult_icu_patients_hospitalized_with_influenza,
    CAST("Number of Pediatric ICU Patients Hospitalized with Influenza" AS BIGINT) AS number_of_pediatric_icu_patients_hospitalized_with_influenza,
    CAST("Total ICU Patients Hospitalized with Influenza" AS DOUBLE) AS total_icu_patients_hospitalized_with_influenza,
    CAST("Number of Adult ICU Patients Hospitalized with RSV" AS BIGINT) AS number_of_adult_icu_patients_hospitalized_with_rsv,
    CAST("Number of Pediatric ICU Patients Hospitalized with RSV" AS BIGINT) AS number_of_pediatric_icu_patients_hospitalized_with_rsv,
    CAST("Total ICU Patients Hospitalized with RSV" AS BIGINT) AS total_icu_patients_hospitalized_with_rsv,
    CAST("Number of Pediatric COVID-19 Admissions, 0-4 years" AS BIGINT) AS number_of_pediatric_covid_19_admissions_0_4_years,
    CAST("Number of Pediatric COVID-19 Admissions, 5-17 years" AS BIGINT) AS number_of_pediatric_covid_19_admissions_5_17_years,
    CAST("Total Pediatric COVID-19 Admissions" AS BIGINT) AS total_pediatric_covid_19_admissions,
    CAST("Number of Adult COVID-19 Admissions, 18-49 years" AS BIGINT) AS number_of_adult_covid_19_admissions_18_49_years,
    CAST("Number of Adult COVID-19 Admissions, 50-64 years" AS BIGINT) AS number_of_adult_covid_19_admissions_50_64_years,
    CAST("Number of Adult COVID-19 Admissions, 65-74 years" AS BIGINT) AS number_of_adult_covid_19_admissions_65_74_years,
    CAST("Number of Adult COVID-19 Admissions, 75+ years" AS BIGINT) AS number_of_adult_covid_19_admissions_75_years,
    CAST("Total Adult COVID-19 Admissions" AS BIGINT) AS total_adult_covid_19_admissions,
    CAST("Number of COVID-19 Admissions, unknown age" AS BIGINT) AS number_of_covid_19_admissions_unknown_age,
    CAST("Total COVID-19 Admissions" AS BIGINT) AS total_covid_19_admissions,
    CAST("Number of Pediatric Influenza Admissions, 0-4 years" AS BIGINT) AS number_of_pediatric_influenza_admissions_0_4_years,
    CAST("Number of Pediatric Influenza Admissions, 5-17 years" AS BIGINT) AS number_of_pediatric_influenza_admissions_5_17_years,
    CAST("Total Pediatric Influenza Admissions" AS BIGINT) AS total_pediatric_influenza_admissions,
    CAST("Number of Adult Influenza Admissions, 18-49 years" AS BIGINT) AS number_of_adult_influenza_admissions_18_49_years,
    CAST("Number of Adult Influenza Admissions, 50-64 years" AS BIGINT) AS number_of_adult_influenza_admissions_50_64_years,
    CAST("Number of Adult Influenza Admissions, 65-74 years" AS BIGINT) AS number_of_adult_influenza_admissions_65_74_years,
    CAST("Number of Adult Influenza Admissions, 75+ years" AS BIGINT) AS number_of_adult_influenza_admissions_75_years,
    CAST("Total Adult Influenza Admissions" AS BIGINT) AS total_adult_influenza_admissions,
    CAST("Number of Influenza Admissions, unknown age" AS BIGINT) AS number_of_influenza_admissions_unknown_age,
    CAST("Total Influenza Admissions" AS BIGINT) AS total_influenza_admissions,
    CAST("Number of Pediatric RSV Admissions, 0-4 years" AS BIGINT) AS number_of_pediatric_rsv_admissions_0_4_years,
    CAST("Number of Pediatric RSV Admissions, 5-17 years" AS BIGINT) AS number_of_pediatric_rsv_admissions_5_17_years,
    CAST("Total Pediatric RSV Admissions" AS BIGINT) AS total_pediatric_rsv_admissions,
    CAST("Number of Adult RSV Admissions, 18-49 years" AS BIGINT) AS number_of_adult_rsv_admissions_18_49_years,
    CAST("Number of Adult RSV Admissions, 50-64 years" AS BIGINT) AS number_of_adult_rsv_admissions_50_64_years,
    CAST("Number of Adult RSV Admissions, 65-74 years" AS BIGINT) AS number_of_adult_rsv_admissions_65_74_years,
    CAST("Number of Adult RSV Admissions, 75+ years" AS BIGINT) AS number_of_adult_rsv_admissions_75_years,
    CAST("Total Adult RSV Admissions" AS BIGINT) AS total_adult_rsv_admissions,
    CAST("Number of RSV Admissions, unknown age" AS BIGINT) AS number_of_rsv_admissions_unknown_age,
    CAST("Total RSV Admissions" AS BIGINT) AS total_rsv_admissions,
    CAST("Percent Inpatient Beds Occupied" AS DOUBLE) AS percent_inpatient_beds_occupied,
    CAST("Percent Inpatient Beds Occupied by COVID-19 Patients" AS DOUBLE) AS percent_inpatient_beds_occupied_by_covid_19_patients,
    CAST("Percent Inpatient Beds Occupied by Influenza Patients" AS DOUBLE) AS percent_inpatient_beds_occupied_by_influenza_patients,
    CAST("Percent Inpatient Beds Occupied by RSV Patients" AS DOUBLE) AS percent_inpatient_beds_occupied_by_rsv_patients,
    CAST("Percent ICU Beds Occupied" AS DOUBLE) AS percent_icu_beds_occupied,
    CAST("Percent ICU Beds Occupied by COVID-19 Patients" AS DOUBLE) AS percent_icu_beds_occupied_by_covid_19_patients,
    CAST("Percent ICU Beds Occupied by Influenza Patients" AS DOUBLE) AS percent_icu_beds_occupied_by_influenza_patients,
    CAST("Percent ICU Beds Occupied by RSV Patients" AS DOUBLE) AS percent_icu_beds_occupied_by_rsv_patients,
    CAST("Percent Adult COVID-19 Admissions" AS DOUBLE) AS percent_adult_covid_19_admissions,
    CAST("Percent Pediatric COVID-19 Admissions" AS DOUBLE) AS percent_pediatric_covid_19_admissions,
    CAST("Percent Adult Influenza Admissions" AS DOUBLE) AS percent_adult_influenza_admissions,
    CAST("Percent Pediatric Influenza Admissions" AS DOUBLE) AS percent_pediatric_influenza_admissions,
    CAST("Percent Adult RSV Admissions" AS DOUBLE) AS percent_adult_rsv_admissions,
    CAST("Percent Pediatric RSV Admissions" AS DOUBLE) AS percent_pediatric_rsv_admissions,
    CAST("Number Hospitals Reporting Number of Inpatient Beds" AS BIGINT) AS number_hospitals_reporting_number_of_inpatient_beds,
    CAST("Number Hospitals Reporting Number of Inpatient Beds Occupied" AS BIGINT) AS number_hospitals_reporting_number_of_inpatient_beds_occupied,
    CAST("Number Hospitals Reporting Number of ICU Beds" AS BIGINT) AS number_hospitals_reporting_number_of_icu_beds,
    CAST("Number Hospitals Reporting Number of ICU Beds Occupied" AS BIGINT) AS number_hospitals_reporting_number_of_icu_beds_occupied,
    CAST("Number Hospitals Reporting Total Patients Hospitalized with COVID-19" AS BIGINT) AS hosp_reporting_total_pts_hosp_with_covid_19,
    CAST("Number Hospitals Reporting TotalPatients Hospitalized with Influenza" AS BIGINT) AS hosp_reporting_totalpts_hosp_with_flu,
    CAST("Number Hospitals Reporting Total Patients Hospitalized with RSV" AS BIGINT) AS number_hospitals_reporting_total_patients_hospitalized_with_rsv,
    CAST("Number Hospitals Reporting ICU Patients Hospitalized with COVID-19" AS BIGINT) AS hosp_reporting_icu_pts_hosp_with_covid_19,
    CAST("Number Hospitals Reporting ICU Patients Hospitalized with Influenza" AS BIGINT) AS hosp_reporting_icu_pts_hosp_with_flu,
    CAST("Number Hospitals Reporting ICU Patients Hospitalized with RSV" AS BIGINT) AS number_hospitals_reporting_icu_patients_hospitalized_with_rsv,
    CAST("Number Hospitals Reporting Pediatric COVID-19 Admissions" AS BIGINT) AS number_hospitals_reporting_pediatric_covid_19_admissions,
    CAST("Number Hospitals Reporting Adult COVID-19 Admissions" AS BIGINT) AS number_hospitals_reporting_adult_covid_19_admissions,
    CAST("Number Hospitals Reporting COVID-19 Admissions" AS BIGINT) AS number_hospitals_reporting_covid_19_admissions,
    CAST("Number Hospitals Reporting Pediatric Influenza Admissions" AS BIGINT) AS number_hospitals_reporting_pediatric_influenza_admissions,
    CAST("Number Hospitals Reporting Adult Influenza Admissions" AS BIGINT) AS number_hospitals_reporting_adult_influenza_admissions,
    CAST("Number Hospitals Reporting  Influenza Admissions" AS BIGINT) AS number_hospitals_reporting_influenza_admissions,
    CAST("Number Hospitals Reporting Pediatric RSV Admissions" AS BIGINT) AS number_hospitals_reporting_pediatric_rsv_admissions,
    CAST("Number Hospitals Reporting Adult RSV Admissions" AS BIGINT) AS number_hospitals_reporting_adult_rsv_admissions,
    CAST("Number Hospitals Reporting RSV Admissions" AS BIGINT) AS number_hospitals_reporting_rsv_admissions,
    CAST("Number Hospitals Reporting Percent Inpatient Beds Occupied" AS BIGINT) AS number_hospitals_reporting_percent_inpatient_beds_occupied,
    CAST("Number Hospitals Reporting Percent ICU Beds Occupied" AS BIGINT) AS number_hospitals_reporting_percent_icu_beds_occupied,
    CAST("Number Hospitals Reporting Percent Inpatient Beds Occupied by COVID-19 Patients" AS BIGINT) AS hosp_reporting_pct_inpt_beds_occ_by_covid_19_pts,
    CAST("Number Hospitals Reporting Percent Inpatient Beds Occupied by Influenza Patients" AS BIGINT) AS hosp_reporting_pct_inpt_beds_occ_by_flu_pts,
    CAST("Number Hospitals Reporting Percent Inpatient Beds Occupied by RSV Patients" AS BIGINT) AS hosp_reporting_pct_inpt_beds_occ_by_rsv_pts,
    CAST("Number Hospitals Reporting Percent ICU Beds Occupied by COVID-19 Patients" AS BIGINT) AS hosp_reporting_pct_icu_beds_occ_by_covid_19_pts,
    CAST("Number Hospitals Reporting Percent ICU Beds Occupied by Influenza Patients" AS BIGINT) AS hosp_reporting_pct_icu_beds_occ_by_flu_pts,
    CAST("Number Hospitals Reporting Percent ICU Beds Occupied by RSV Patients" AS BIGINT) AS hosp_reporting_pct_icu_beds_occ_by_rsv_pts,
    CAST("Percent Hospitals Reporting Number of Inpatient Beds" AS DOUBLE) AS percent_hospitals_reporting_number_of_inpatient_beds,
    CAST("Percent Hospitals Reporting Number of Inpatient Beds Occupied" AS DOUBLE) AS percent_hospitals_reporting_number_of_inpatient_beds_occupied,
    CAST("Percent Hospitals Reporting Number of ICU Beds" AS DOUBLE) AS percent_hospitals_reporting_number_of_icu_beds,
    CAST("Percent Hospitals Reporting Number of ICU Beds Occupied" AS DOUBLE) AS percent_hospitals_reporting_number_of_icu_beds_occupied,
    CAST("Percent Hospitals Reporting Total Patients Hospitalized with COVID-19" AS DOUBLE) AS pct_hospitals_reporting_total_pts_hosp_with_covid_19,
    CAST("Percent Hospitals Reporting TotalPatients Hospitalized with Influenza" AS DOUBLE) AS pct_hospitals_reporting_totalpts_hosp_with_flu,
    CAST("Percent Hospitals Reporting Total Patients Hospitalized with RSV" AS DOUBLE) AS percent_hospitals_reporting_total_patients_hospitalized_with_rsv,
    CAST("Percent Hospitals Reporting ICU Patients Hospitalized with COVID-19" AS DOUBLE) AS pct_hospitals_reporting_icu_pts_hosp_with_covid_19,
    CAST("Percent Hospitals Reporting ICU Patients Hospitalized with Influenza" AS DOUBLE) AS pct_hospitals_reporting_icu_pts_hosp_with_flu,
    CAST("Percent Hospitals Reporting ICU Patients Hospitalized with RSV" AS DOUBLE) AS percent_hospitals_reporting_icu_patients_hospitalized_with_rsv,
    CAST("Percent Hospitals Reporting Pediatric COVID-19 Admissions" AS DOUBLE) AS percent_hospitals_reporting_pediatric_covid_19_admissions,
    CAST("Percent Hospitals Reporting Adult COVID-19 Admissions" AS DOUBLE) AS percent_hospitals_reporting_adult_covid_19_admissions,
    CAST("Percent Hospitals Reporting COVID-19 Admissions" AS DOUBLE) AS percent_hospitals_reporting_covid_19_admissions,
    CAST("Percent Hospitals Reporting Pediatric Influenza Admissions" AS DOUBLE) AS percent_hospitals_reporting_pediatric_influenza_admissions,
    CAST("Percent Hospitals Reporting Adult Influenza Admissions" AS DOUBLE) AS percent_hospitals_reporting_adult_influenza_admissions,
    CAST("Percent Hospitals Reporting  Influenza Admissions" AS DOUBLE) AS percent_hospitals_reporting_influenza_admissions,
    CAST("Percent Hospitals Reporting Pediatric RSV Admissions" AS DOUBLE) AS percent_hospitals_reporting_pediatric_rsv_admissions,
    CAST("Percent Hospitals Reporting Adult RSV Admissions" AS DOUBLE) AS percent_hospitals_reporting_adult_rsv_admissions,
    CAST("Percent Hospitals Reporting RSV Admissions" AS DOUBLE) AS percent_hospitals_reporting_rsv_admissions,
    CAST("Percent Hospitals Reporting Percent Inpatient Beds Occupied" AS DOUBLE) AS percent_hospitals_reporting_percent_inpatient_beds_occupied,
    CAST("Percent Hospitals Reporting Percent ICU Beds Occupied" AS DOUBLE) AS percent_hospitals_reporting_percent_icu_beds_occupied,
    CAST("Percent Hospitals Reporting Percent Inpatient Beds Occupied by COVID-19 Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_inpt_beds_occ_by_covid_19_pts,
    CAST("Percent Hospitals Reporting Percent Inpatient Beds Occupied by Influenza Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_inpt_beds_occ_by_flu_pts,
    CAST("Percent Hospitals Reporting Percent Inpatient Beds Occupied by RSV Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_inpt_beds_occ_by_rsv_pts,
    CAST("Percent Hospitals Reporting Percent ICU Beds Occupied by COVID-19 Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_icu_beds_occ_by_covid_19_pts,
    CAST("Percent Hospitals Reporting Percent ICU Beds Occupied by Influenza Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_icu_beds_occ_by_flu_pts,
    CAST("Percent Hospitals Reporting Percent ICU Beds Occupied by RSV Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_icu_beds_occ_by_rsv_pts,
    CAST("Absolute Change in the Percent Hospitals Reporting Number of Inpatient Beds from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_number_o_c408270e,
    CAST("Absolute Change in the Percent Hospitals Reporting Number of Inpatient Beds Occupied from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_number_o_5cc69b45,
    CAST("Absolute Change in the Percent Hospitals Reporting Number of ICU Beds from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_number_o_237366e6,
    CAST("Absolute Change in the Percent Hospitals Reporting Number of ICU Beds Occupied from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_number_o_b9630fcc,
    CAST("Absolute Change in the Percent Hospitals Reporting Total Patients Hospitalized with COVID-19 from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_total_pt_415af7de,
    CAST("Absolute Change in the Percent Hospitals Reporting TotalPatients Hospitalized with Influenza from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_totalpts_841b6664,
    CAST("Absolute Change in the Percent Hospitals Reporting Total Patients Hospitalized with RSV from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_total_pt_c737992a,
    CAST("Absolute Change in the Percent Hospitals Reporting ICU Patients Hospitalized with COVID-19 from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_icu_pts_a12b0c41,
    CAST("Absolute Change in the Percent Hospitals Reporting ICU Patients Hospitalized with Influenza from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_icu_pts_93185fe8,
    CAST("Absolute Change in the Percent Hospitals Reporting ICU Patients Hospitalized with RSV from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_icu_pts_247a05d7,
    CAST("Absolute Change in the Percent Hospitals Reporting Pediatric COVID-19 Admissions from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_ped_covi_22970b21,
    CAST("Absolute Change in the Percent Hospitals Reporting Adult COVID-19 Admissions from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_adult_co_7d62790f,
    CAST("Absolute Change in the Percent Hospitals Reporting COVID-19 Admissions from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_covid_19_f43e43e2,
    CAST("Absolute Change in the Percent Hospitals Reporting Pediatric Influenza Admissions from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_ped_flu_d6964421,
    CAST("Absolute Change in the Percent Hospitals Reporting Adult Influenza Admissions from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_adult_fl_6479980e,
    CAST("Absolute Change in the Percent Hospitals Reporting  Influenza Admissions from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_flu_admi_8ede46a8,
    CAST("Absolute Change in the Percent Hospitals Reporting Pediatric RSV Admissions from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_ped_rsv_54c0e791,
    CAST("Absolute Change in the Percent Hospitals Reporting Adult RSV Admissions from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_adult_rs_2e9edba6,
    CAST("Absolute Change in the Percent Hospitals Reporting RSV Admissions from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_rsv_admi_af46cf8d,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_inpt_5ac932c0,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent ICU Beds Occupied from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_icu_be6a01fc,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied by COVID-19 Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_inpt_0f92f3d0,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied by Influenza Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_inpt_835b9d97,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied by RSV Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_inpt_f24fcfb2,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent ICU Beds Occupied by COVID-19 Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_icu_b79bd9e0,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent ICU Beds Occupied by Influenza Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_icu_0550448e,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent ICU Beds Occupied by RSV Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_icu_98ff3344,
    CAST("Number of Pediatric COVID-19 Admissions, 0-4 years, per 100,000 population" AS DOUBLE) AS number_of_ped_covid_19_admissions_0_4_years_per_100_000_68b80585,
    CAST("Number of Pediatric COVID-19 Admissions, 5-17 years, per 100,000 population" AS DOUBLE) AS number_of_ped_covid_19_admissions_5_17_years_per_100_00_13822159,
    CAST("Total Number of Pediatric COVID-19 Admissions per 100,000 population" AS DOUBLE) AS total_number_of_ped_covid_19_admissions_per_100_000_population,
    CAST("Number of Adult COVID-19 Admissions, 18-49 years, per 100,000 population" AS DOUBLE) AS number_of_adult_covid_19_admissions_18_49_years_per_100_771e8c85,
    CAST("Number of Adult COVID-19 Admissions, 50-64 years, per 100,000 population" AS DOUBLE) AS number_of_adult_covid_19_admissions_50_64_years_per_100_13e08b8c,
    CAST("Number of Adult COVID-19 Admissions, 65-74 years, per 100,000 population" AS DOUBLE) AS number_of_adult_covid_19_admissions_65_74_years_per_100_a89892a1,
    CAST("Number of Adult COVID-19 Admissions, 75+ years, per 100,000 population" AS DOUBLE) AS number_of_adult_covid_19_admissions_75_years_per_100_00_1b1c9d2d,
    CAST("Total Number of Adult COVID-19 Admissions per 100,000 population" AS DOUBLE) AS total_number_of_adult_covid_19_admissions_per_100_000_population,
    CAST("Total number of COVID-19 Admissions per 100,000 population" AS DOUBLE) AS total_number_of_covid_19_admissions_per_100_000_population,
    CAST("Number of Pediatric Influenza Admissions, 0-4 years, per 100,000 population" AS DOUBLE) AS number_of_ped_flu_admissions_0_4_years_per_100_000_population,
    CAST("Number of Pediatric Influenza Admissions, 5-17 years, per 100,000 population" AS DOUBLE) AS number_of_ped_flu_admissions_5_17_years_per_100_000_population,
    CAST("Total Number of Pediatric Influenza Admissions per 100,000 population" AS DOUBLE) AS total_number_of_ped_flu_admissions_per_100_000_population,
    CAST("Number of Adult Influenza Admissions, 18-49 years, per 100,000 population" AS DOUBLE) AS number_of_adult_flu_admissions_18_49_years_per_100_000_afb6952f,
    CAST("Number of Adult Influenza Admissions, 50-64 years, per 100,000 population" AS DOUBLE) AS number_of_adult_flu_admissions_50_64_years_per_100_000_71b9a262,
    CAST("Number of Adult Influenza Admissions, 65-74 years, per 100,000 population" AS DOUBLE) AS number_of_adult_flu_admissions_65_74_years_per_100_000_58797406,
    CAST("Number of Adult Influenza Admissions, 75+ years, per 100,000 population" AS DOUBLE) AS number_of_adult_flu_admissions_75_years_per_100_000_population,
    CAST("Total Number of Adult Influenza Admissions per 100,000 population" AS DOUBLE) AS total_number_of_adult_flu_admissions_per_100_000_population,
    CAST("Total number of Influenza Admissions per 100,000 population" AS DOUBLE) AS total_number_of_influenza_admissions_per_100_000_population,
    CAST("Number of Pediatric RSV Admissions, 0-4 years, per 100,000 population" AS DOUBLE) AS number_of_ped_rsv_admissions_0_4_years_per_100_000_population,
    CAST("Number of Pediatric RSV Admissions, 5-17 years, per 100,000 population" AS DOUBLE) AS number_of_ped_rsv_admissions_5_17_years_per_100_000_population,
    CAST("Total Number of Pediatric RSV Admissions per 100,000 population" AS DOUBLE) AS total_number_of_pediatric_rsv_admissions_per_100_000_population,
    CAST("Number of Adult RSV Admissions, 18-49 years, per 100,000 population" AS DOUBLE) AS number_of_adult_rsv_admissions_18_49_years_per_100_000_433a6a78,
    CAST("Number of Adult RSV Admissions, 50-64 years, per 100,000 population" AS DOUBLE) AS number_of_adult_rsv_admissions_50_64_years_per_100_000_c796caa7,
    CAST("Number of Adult RSV Admissions, 65-74 years, per 100,000 population" AS DOUBLE) AS number_of_adult_rsv_admissions_65_74_years_per_100_000_55705877,
    CAST("Number of Adult RSV Admissions, 75+ years, per 100,000 population" AS DOUBLE) AS number_of_adult_rsv_admissions_75_years_per_100_000_population,
    CAST("Total Number of Adult RSV Admissions per 100,000 population" AS DOUBLE) AS total_number_of_adult_rsv_admissions_per_100_000_population,
    CAST("Total number of RSV Admissions per 100,000 population" AS DOUBLE) AS total_number_of_rsv_admissions_per_100_000_population,
    CAST("Percent Hospitals Reporting Total New COVID-19 Admissions Above 80%" AS BIGINT) AS pct_hospitals_reporting_total_new_covid_19_admissions_above_80,
    CAST("Percent Hospitals Reporting Total New COVID-19 Admissions Above 90%" AS BIGINT) AS pct_hospitals_reporting_total_new_covid_19_admissions_above_90,
    CAST("Percent Hospitals Reporting Total New Influenza Admissions Above 80%" AS BIGINT) AS pct_hospitals_reporting_total_new_flu_admissions_above_80,
    CAST("Percent Hospitals Reporting Total New Influenza Admissions Above 90%" AS BIGINT) AS pct_hospitals_reporting_total_new_flu_admissions_above_90,
    CAST("Percent Hospitals Reporting Total New RSV Admissions Above 80%" AS BIGINT) AS percent_hospitals_reporting_total_new_rsv_admissions_above_80,
    CAST("Percent Hospitals Reporting Total New RSV Admissions Above 90%" AS BIGINT) AS percent_hospitals_reporting_total_new_rsv_admissions_above_90,
    CAST("Percent Adult Inpatient Beds Occupied" AS DOUBLE) AS percent_adult_inpatient_beds_occupied,
    CAST("Percent Pediatric Inpatient Beds Occupied" AS DOUBLE) AS percent_pediatric_inpatient_beds_occupied,
    CAST("Percent Adult ICU Beds Occupied" AS DOUBLE) AS percent_adult_icu_beds_occupied,
    CAST("Percent Pediatric ICU Beds Occupied" AS DOUBLE) AS percent_pediatric_icu_beds_occupied,
    CAST("Percent Adult Inpatient Beds Occupied by COVID-19 Patients" AS DOUBLE) AS percent_adult_inpatient_beds_occupied_by_covid_19_patients,
    CAST("Percent Pediatric Inpatient Beds Occupied by COVID-19 Patients" AS DOUBLE) AS percent_pediatric_inpatient_beds_occupied_by_covid_19_patients,
    CAST("Percent Adult ICU Beds Occupied by COVID-19 Patients" AS DOUBLE) AS percent_adult_icu_beds_occupied_by_covid_19_patients,
    CAST("Percent Pediatric ICU Beds Occupied by COVID-19 Patients" AS DOUBLE) AS percent_pediatric_icu_beds_occupied_by_covid_19_patients,
    CAST("Percent Adult Inpatient Beds Occupied by Influenza Patients" AS DOUBLE) AS percent_adult_inpatient_beds_occupied_by_influenza_patients,
    CAST("Percent Pediatric Inpatient Beds Occupied by Influenza Patients" AS DOUBLE) AS percent_pediatric_inpatient_beds_occupied_by_influenza_patients,
    CAST("Percent Adult ICU Beds Occupied by Influenza Patients" AS DOUBLE) AS percent_adult_icu_beds_occupied_by_influenza_patients,
    CAST("Percent Pediatric ICU Beds Occupied by Influenza Patients" AS DOUBLE) AS percent_pediatric_icu_beds_occupied_by_influenza_patients,
    CAST("Percent Adult Inpatient Beds Occupied by RSV Patients" AS DOUBLE) AS percent_adult_inpatient_beds_occupied_by_rsv_patients,
    CAST("Percent Pediatric Inpatient Beds Occupied by RSV Patients" AS DOUBLE) AS percent_pediatric_inpatient_beds_occupied_by_rsv_patients,
    CAST("Percent Adult ICU Beds Occupied by RSV Patients" AS DOUBLE) AS percent_adult_icu_beds_occupied_by_rsv_patients,
    CAST("Percent Pediatric ICU Beds Occupied by RSV Patients" AS DOUBLE) AS percent_pediatric_icu_beds_occupied_by_rsv_patients,
    CAST("Percent Hospitalized Patients with COVID-19 in the ICU" AS DOUBLE) AS percent_hospitalized_patients_with_covid_19_in_the_icu,
    CAST("Percent Hospitalized Adult Patients with COVID-19 in the ICU" AS DOUBLE) AS percent_hospitalized_adult_patients_with_covid_19_in_the_icu,
    CAST("Percent Hospitalized Pediatric Patients with COVID-19 in the ICU" AS DOUBLE) AS percent_hospitalized_pediatric_patients_with_covid_19_in_the_icu,
    CAST("Percent Hospitalized Patients with Influenza in the ICU" AS DOUBLE) AS percent_hospitalized_patients_with_influenza_in_the_icu,
    CAST("Percent Hospitalized Adult Patients with Influenza in the ICU" AS DOUBLE) AS percent_hospitalized_adult_patients_with_influenza_in_the_icu,
    CAST("Percent Hospitalized Pediatric Patients with Influenza in the ICU" AS DOUBLE) AS pct_hosp_ped_pts_with_flu_in_the_icu,
    CAST("Percent Hospitalized Patients with RSV in the ICU" AS DOUBLE) AS percent_hospitalized_patients_with_rsv_in_the_icu,
    CAST("Percent Hospitalized Adult Patients with RSV in the ICU" AS DOUBLE) AS percent_hospitalized_adult_patients_with_rsv_in_the_icu,
    CAST("Percent Hospitalized Pediatric Patients with RSV in the ICU" AS DOUBLE) AS percent_hospitalized_pediatric_patients_with_rsv_in_the_icu,
    CAST("Percent Change in the Number of Pediatric COVID-19 Admissions, 0-4 years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_ped_covid_19_admissions_0_4_b62ad6fe,
    CAST("Percent Change in the Number of Pediatric COVID-19 Admissions, 5-17 years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_ped_covid_19_admissions_5_1_5499adea,
    CAST("Percent Change in the Total Pediatric COVID-19 Admissions from Prior Week" AS DOUBLE) AS pct_change_in_the_total_ped_covid_19_admissions_from_prior_week,
    CAST("Percent Change in the Number of Adult COVID-19 Admissions, 18-49 years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_adult_covid_19_admissions_1_73f3537a,
    CAST("Percent Change in the Number of Adult COVID-19 Admissions, 50-64 years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_adult_covid_19_admissions_5_e35ed4dc,
    CAST("Percent Change in the Number of Adult COVID-19 Admissions, 65-74 years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_adult_covid_19_admissions_6_ef6e2f1c,
    CAST("Percent Change in the Number of Adult COVID-19 Admissions, 75+ years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_adult_covid_19_admissions_7_6cf26042,
    CAST("Percent Change in the Total Adult COVID-19 Admissions from Prior Week" AS DOUBLE) AS pct_change_in_the_total_adult_covid_19_admissions_from_c278af4e,
    CAST("Percent Change in the Total COVID-19 Admissions from Prior Week" AS DOUBLE) AS percent_change_in_the_total_covid_19_admissions_from_prior_week,
    CAST("Percent Change in the Number of Pediatric Influenza Admissions, 0-4 years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_ped_flu_admissions_0_4_year_0985efcc,
    CAST("Percent Change in the Number of Pediatric Influenza Admissions, 5-17 years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_ped_flu_admissions_5_17_yea_ff479e90,
    CAST("Percent Change in the Total Pediatric Influenza Admissions from Prior Week" AS DOUBLE) AS pct_change_in_the_total_ped_flu_admissions_from_prior_week,
    CAST("Percent Change in the Number of Adult Influenza Admissions, 18-49 years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_adult_flu_admissions_18_49_7ac08eb6,
    CAST("Percent Change in the Number of Adult Influenza Admissions, 50-64 years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_adult_flu_admissions_50_64_7aae03c8,
    CAST("Percent Change in the Number of Adult Influenza Admissions, 65-74 years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_adult_flu_admissions_65_74_8cfcb1ab,
    CAST("Percent Change in the Number of Adult Influenza Admissions, 75+ years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_adult_flu_admissions_75_yea_c15acd63,
    CAST("Percent Change in the Total Adult Influenza Admissions from Prior Week" AS DOUBLE) AS pct_change_in_the_total_adult_flu_admissions_from_prior_week,
    CAST("Percent Change in the Total Influenza Admissions from Prior Week" AS DOUBLE) AS percent_change_in_the_total_influenza_admissions_from_prior_week,
    CAST("Percent Change in the Number of Pediatric RSV Admissions, 0-4 years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_ped_rsv_admissions_0_4_year_82e1fffd,
    CAST("Percent Change in the Number of Pediatric RSV Admissions, 5-17 years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_ped_rsv_admissions_5_17_yea_bf31ca49,
    CAST("Percent Change in the Total Pediatric RSV Admissions from Prior Week" AS DOUBLE) AS pct_change_in_the_total_ped_rsv_admissions_from_prior_week,
    CAST("Percent Change in the Number of Adult RSV Admissions, 18-49 years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_adult_rsv_admissions_18_49_3ee9d1cc,
    CAST("Percent Change in the Number of Adult RSV Admissions, 50-64 years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_adult_rsv_admissions_50_64_eba90282,
    CAST("Percent Change in the Number of Adult RSV Admissions, 65-74 years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_adult_rsv_admissions_65_74_9a0acb5c,
    CAST("Percent Change in the Number of Adult RSV Admissions, 75+ years from Prior Week" AS DOUBLE) AS pct_change_in_the_number_of_adult_rsv_admissions_75_yea_e6de160f,
    CAST("Percent Change in the Total Adult RSV Admissions from Prior Week" AS DOUBLE) AS percent_change_in_the_total_adult_rsv_admissions_from_prior_week,
    CAST("Percent Change in the Total RSV Admissions from Prior Week" AS DOUBLE) AS percent_change_in_the_total_rsv_admissions_from_prior_week,
    CAST("Number Hospitals Reporting Percent Adult Inpatient Beds Occupied" AS BIGINT) AS number_hospitals_reporting_percent_adult_inpatient_beds_occupied,
    CAST("Number Hospitals Reporting Percent Pediatric Inpatient Beds Occupied" AS BIGINT) AS hosp_reporting_pct_ped_inpt_beds_occ,
    CAST("Number Hospitals Reporting Percent Adult ICU Beds Occupied" AS BIGINT) AS number_hospitals_reporting_percent_adult_icu_beds_occupied,
    CAST("Number Hospitals Reporting Percent Pediatric ICU Beds Occupied" AS BIGINT) AS number_hospitals_reporting_percent_pediatric_icu_beds_occupied,
    CAST("Number Hospitals Reporting Percent Adult Inpatient Beds Occupied by COVID-19 Patients" AS BIGINT) AS hosp_reporting_pct_adult_inpt_beds_occ_by_covid_19_pts,
    CAST("Number Hospitals Reporting Percent Pediatric Inpatient Beds Occupied by COVID-19 Patients" AS BIGINT) AS hosp_reporting_pct_ped_inpt_beds_occ_by_covid_19_pts,
    CAST("Number Hospitals Reporting Percent Adult ICU Beds Occupied by COVID-19 Patients" AS BIGINT) AS hosp_reporting_pct_adult_icu_beds_occ_by_covid_19_pts,
    CAST("Number Hospitals Reporting Percent Pediatric ICU Beds Occupied by COVID-19 Patients" AS BIGINT) AS hosp_reporting_pct_ped_icu_beds_occ_by_covid_19_pts,
    CAST("Number Hospitals Reporting Percent Adult Inpatient Beds Occupied by Influenza Patients" AS BIGINT) AS hosp_reporting_pct_adult_inpt_beds_occ_by_flu_pts,
    CAST("Number Hospitals Reporting Percent Pediatric Inpatient Beds Occupied by Influenza Patients" AS BIGINT) AS hosp_reporting_pct_ped_inpt_beds_occ_by_flu_pts,
    CAST("Number Hospitals Reporting Percent Adult ICU Beds Occupied by Influenza Patients" AS BIGINT) AS hosp_reporting_pct_adult_icu_beds_occ_by_flu_pts,
    CAST("Number Hospitals Reporting Percent Pediatric ICU Beds Occupied by Influenza Patients" AS BIGINT) AS hosp_reporting_pct_ped_icu_beds_occ_by_flu_pts,
    CAST("Number Hospitals Reporting Percent Adult Inpatient Beds Occupied by RSV Patients" AS BIGINT) AS hosp_reporting_pct_adult_inpt_beds_occ_by_rsv_pts,
    CAST("Number Hospitals Reporting Percent Pediatric Inpatient Beds Occupied by RSV Patients" AS BIGINT) AS hosp_reporting_pct_ped_inpt_beds_occ_by_rsv_pts,
    CAST("Number Hospitals Reporting Percent Adult ICU Beds Occupied by RSV Patients" AS BIGINT) AS hosp_reporting_pct_adult_icu_beds_occ_by_rsv_pts,
    CAST("Number Hospitals Reporting Percent Pediatric ICU Beds Occupied by RSV Patients" AS BIGINT) AS hosp_reporting_pct_ped_icu_beds_occ_by_rsv_pts,
    CAST("Number Hospitals Reporting Percent Hospitalized Patients with COVID-19 in the ICU" AS BIGINT) AS hosp_reporting_pct_hosp_pts_with_covid_19_in_the_icu,
    CAST("Number Hospitals Reporting Percent Hospitalized Adult Patients with COVID-19 in the ICU" AS BIGINT) AS hosp_reporting_pct_hosp_adult_pts_with_covid_19_in_the_icu,
    CAST("Number Hospitals Reporting Percent Hospitalized Pediatric Patients with COVID-19 in the ICU" AS BIGINT) AS hosp_reporting_pct_hosp_ped_pts_with_covid_19_in_the_icu,
    CAST("Number Hospitals Reporting Percent Hospitalized Patients with Influenza in the ICU" AS BIGINT) AS hosp_reporting_pct_hosp_pts_with_flu_in_the_icu,
    CAST("Number Hospitals Reporting Percent Hospitalized Adult Patients with Influenza in the ICU" AS BIGINT) AS hosp_reporting_pct_hosp_adult_pts_with_flu_in_the_icu,
    CAST("Number Hospitals Reporting Percent Hospitalized Pediatric Patients with Influenza in the ICU" AS BIGINT) AS hosp_reporting_pct_hosp_ped_pts_with_flu_in_the_icu,
    CAST("Number Hospitals Reporting Percent Hospitalized Patients with RSV in the ICU" AS BIGINT) AS hosp_reporting_pct_hosp_pts_with_rsv_in_the_icu,
    CAST("Number Hospitals Reporting Percent Hospitalized Adult Patients with RSV in the ICU" AS BIGINT) AS hosp_reporting_pct_hosp_adult_pts_with_rsv_in_the_icu,
    CAST("Number Hospitals Reporting Percent Hospitalized Pediatric Patients with RSV in the ICU" AS BIGINT) AS hosp_reporting_pct_hosp_ped_pts_with_rsv_in_the_icu,
    CAST("Percent Hospitals Reporting Percent Adult Inpatient Beds Occupied" AS DOUBLE) AS pct_hospitals_reporting_pct_adult_inpt_beds_occ,
    CAST("Percent Hospitals Reporting Percent Pediatric Inpatient Beds Occupied" AS DOUBLE) AS pct_hospitals_reporting_pct_ped_inpt_beds_occ,
    CAST("Percent Hospitals Reporting Percent Adult ICU Beds Occupied" AS DOUBLE) AS percent_hospitals_reporting_percent_adult_icu_beds_occupied,
    CAST("Percent Hospitals Reporting Percent Pediatric ICU Beds Occupied" AS DOUBLE) AS percent_hospitals_reporting_percent_pediatric_icu_beds_occupied,
    CAST("Percent Hospitals Reporting Percent Adult Inpatient Beds Occupied by COVID-19 Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_adult_inpt_beds_occ_by_covid_19_pts,
    CAST("Percent Hospitals Reporting Percent Pediatric Inpatient Beds Occupied by COVID-19 Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_ped_inpt_beds_occ_by_covid_19_pts,
    CAST("Percent Hospitals Reporting Percent Adult ICU Beds Occupied by COVID-19 Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_adult_icu_beds_occ_by_covid_19_pts,
    CAST("Percent Hospitals Reporting Percent Pediatric ICU Beds Occupied by COVID-19 Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_ped_icu_beds_occ_by_covid_19_pts,
    CAST("Percent Hospitals Reporting Percent Adult Inpatient Beds Occupied by Influenza Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_adult_inpt_beds_occ_by_flu_pts,
    CAST("Percent Hospitals Reporting Percent Pediatric Inpatient Beds Occupied by Influenza Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_ped_inpt_beds_occ_by_flu_pts,
    CAST("Percent Hospitals Reporting Percent Adult ICU Beds Occupied by Influenza Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_adult_icu_beds_occ_by_flu_pts,
    CAST("Percent Hospitals Reporting Percent Pediatric ICU Beds Occupied by Influenza Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_ped_icu_beds_occ_by_flu_pts,
    CAST("Percent Hospitals Reporting Percent Adult Inpatient Beds Occupied by RSV Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_adult_inpt_beds_occ_by_rsv_pts,
    CAST("Percent Hospitals Reporting Percent Pediatric Inpatient Beds Occupied by RSV Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_ped_inpt_beds_occ_by_rsv_pts,
    CAST("Percent Hospitals Reporting Percent Adult ICU Beds Occupied by RSV Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_adult_icu_beds_occ_by_rsv_pts,
    CAST("Percent Hospitals Reporting Percent Pediatric ICU Beds Occupied by RSV Patients" AS DOUBLE) AS pct_hospitals_reporting_pct_ped_icu_beds_occ_by_rsv_pts,
    CAST("Percent Hospitals Reporting Percent Hospitalized Patients with COVID-19 in the ICU" AS DOUBLE) AS pct_hospitals_reporting_pct_hosp_pts_with_covid_19_in_the_icu,
    CAST("Percent Hospitals Reporting Percent Hospitalized Adult Patients with COVID-19 in the ICU" AS DOUBLE) AS pct_hospitals_reporting_pct_hosp_adult_pts_with_covid_1_ee3206ef,
    CAST("Percent Hospitals Reporting Percent Hospitalized Pediatric Patients with COVID-19 in the ICU" AS DOUBLE) AS pct_hospitals_reporting_pct_hosp_ped_pts_with_covid_19_b7f1def4,
    CAST("Percent Hospitals Reporting Percent Hospitalized Patients with Influenza in the ICU" AS DOUBLE) AS pct_hospitals_reporting_pct_hosp_pts_with_flu_in_the_icu,
    CAST("Percent Hospitals Reporting Percent Hospitalized Adult Patients with Influenza in the ICU" AS DOUBLE) AS pct_hospitals_reporting_pct_hosp_adult_pts_with_flu_in_the_icu,
    CAST("Percent Hospitals Reporting Percent Hospitalized Pediatric Patients with Influenza in the ICU" AS DOUBLE) AS pct_hospitals_reporting_pct_hosp_ped_pts_with_flu_in_the_icu,
    CAST("Percent Hospitals Reporting Percent Hospitalized Patients with RSV in the ICU" AS DOUBLE) AS pct_hospitals_reporting_pct_hosp_pts_with_rsv_in_the_icu,
    CAST("Percent Hospitals Reporting Percent Hospitalized Adult Patients with RSV in the ICU" AS DOUBLE) AS pct_hospitals_reporting_pct_hosp_adult_pts_with_rsv_in_the_icu,
    CAST("Percent Hospitals Reporting Percent Hospitalized Pediatric Patients with RSV in the ICU" AS DOUBLE) AS pct_hospitals_reporting_pct_hosp_ped_pts_with_rsv_in_the_icu,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Adult Inpatient Beds Occupied from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_adul_e03e93dc,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Pediatric Inpatient Beds Occupied from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_ped_6ee33a34,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Adult ICU Beds Occupied from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_adul_5e1066b7,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Pediatric ICU Beds Occupied from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_ped_4f3ee013,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Adult Inpatient Beds Occupied by COVID-19 Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_adul_b032d65a,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Pediatric Inpatient Beds Occupied by COVID-19 Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_ped_37e45198,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Adult ICU Beds Occupied by COVID-19 Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_adul_856c2838,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Pediatric ICU Beds Occupied by COVID-19 Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_ped_c67a94a1,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Adult Inpatient Beds Occupied by Influenza Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_adul_fbcc66fa,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Pediatric Inpatient Beds Occupied by Influenza Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_ped_745393e6,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Adult ICU Beds Occupied by Influenza Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_adul_e10ef0e6,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Pediatric ICU Beds Occupied by Influenza Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_ped_3390eb95,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Adult Inpatient Beds Occupied by RSV Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_adul_4473d8b2,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Pediatric Inpatient Beds Occupied by RSV Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_ped_e6c4a2c1,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Adult ICU Beds Occupied by RSV Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_adul_7e291d28,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Pediatric ICU Beds Occupied by RSV Patients from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_ped_65da2fdc,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Hospitalized Patients with COVID-19 in the ICU from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_hosp_cde003bf,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Hospitalized Adult Patients with COVID-19 in the ICU from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_hosp_201dec09,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Hospitalized Pediatric Patients with COVID-19 in the ICU from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_hosp_09cb5bdf,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Hospitalized Patients with Influenza in the ICU from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_hosp_751c15b4,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Hospitalized Adult Patients with Influenza in the ICU from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_hosp_9719a171,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Hospitalized Pediatric Patients with Influenza in the ICU from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_hosp_699dd590,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Hospitalized Patients with RSV in the ICU from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_hosp_64c50352,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Hospitalized Adult Patients with RSV in the ICU from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_hosp_e64f0e39,
    CAST("Absolute Change in the Percent Hospitals Reporting Percent Hospitalized Pediatric Patients with RSV in the ICU from Prior Week" AS DOUBLE) AS absolute_change_in_the_pct_hospitals_reporting_pct_hosp_4ffd1e00,
    "Respiratory Virus Season" AS respiratory_virus_season,
    CAST("Cumulative Seasonal Total Confirmed New COVID-19 Admissions" AS BIGINT) AS cumulative_seasonal_total_confirmed_new_covid_19_admissions,
    CAST("Cumulative Seasonal Total Confirmed New Influenza Admissions" AS BIGINT) AS cumulative_seasonal_total_confirmed_new_influenza_admissions,
    CAST("Cumulative Seasonal Total Confirmed New RSV Admissions" AS BIGINT) AS cumulative_seasonal_total_confirmed_new_rsv_admissions,
    CAST("Cumulative Seasonal Total Confirmed New Respiratory Admissions (COVID-19, Influenza, and RSV)" AS BIGINT) AS cum_seasonal_total_conf_new_respiratory_admissions_covi_54a27ead
FROM "cdc-mpgq-jmmr"
