-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "StateAbbr" AS stateabbr,
    "StateDesc" AS statedesc,
    "CountyName" AS countyname,
    "CountyFIPS" AS countyfips,
    CAST("TotalPopulation" AS BIGINT) AS totalpopulation,
    CAST("ACCESS2_CrudePrev" AS DOUBLE) AS access2_crudeprev,
    "ACCESS2_Crude95CI" AS access2_crude95ci,
    CAST("ACCESS2_AdjPrev" AS DOUBLE) AS access2_adjprev,
    "ACCESS2_Adj95CI" AS access2_adj95ci,
    CAST("ARTHRITIS_CrudePrev" AS DOUBLE) AS arthritis_crudeprev,
    "ARTHRITIS_Crude95CI" AS arthritis_crude95ci,
    CAST("ARTHRITIS_AdjPrev" AS DOUBLE) AS arthritis_adjprev,
    "ARTHRITIS_Adj95CI" AS arthritis_adj95ci,
    CAST("BINGE_CrudePrev" AS DOUBLE) AS binge_crudeprev,
    "BINGE_Crude95CI" AS binge_crude95ci,
    CAST("BINGE_AdjPrev" AS DOUBLE) AS binge_adjprev,
    "BINGE_Adj95CI" AS binge_adj95ci,
    CAST("BPHIGH_CrudePrev" AS DOUBLE) AS bphigh_crudeprev,
    "BPHIGH_Crude95CI" AS bphigh_crude95ci,
    CAST("BPHIGH_AdjPrev" AS DOUBLE) AS bphigh_adjprev,
    "BPHIGH_Adj95CI" AS bphigh_adj95ci,
    CAST("BPMED_CrudePrev" AS DOUBLE) AS bpmed_crudeprev,
    "BPMED_Crude95CI" AS bpmed_crude95ci,
    CAST("BPMED_AdjPrev" AS DOUBLE) AS bpmed_adjprev,
    "BPMED_Adj95CI" AS bpmed_adj95ci,
    CAST("CANCER_CrudePrev" AS DOUBLE) AS cancer_crudeprev,
    "CANCER_Crude95CI" AS cancer_crude95ci,
    CAST("CANCER_AdjPrev" AS DOUBLE) AS cancer_adjprev,
    "CANCER_Adj95CI" AS cancer_adj95ci,
    CAST("CASTHMA_CrudePrev" AS DOUBLE) AS casthma_crudeprev,
    "CASTHMA_Crude95CI" AS casthma_crude95ci,
    CAST("CASTHMA_AdjPrev" AS DOUBLE) AS casthma_adjprev,
    "CASTHMA_Adj95CI" AS casthma_adj95ci,
    CAST("CERVICAL_CrudePrev" AS DOUBLE) AS cervical_crudeprev,
    "CERVICAL_Crude95CI" AS cervical_crude95ci,
    CAST("CERVICAL_AdjPrev" AS DOUBLE) AS cervical_adjprev,
    "CERVICAL_Adj95CI" AS cervical_adj95ci,
    CAST("CHD_CrudePrev" AS DOUBLE) AS chd_crudeprev,
    "CHD_Crude95CI" AS chd_crude95ci,
    CAST("CHD_AdjPrev" AS DOUBLE) AS chd_adjprev,
    "CHD_Adj95CI" AS chd_adj95ci,
    CAST("CHECKUP_CrudePrev" AS DOUBLE) AS checkup_crudeprev,
    "CHECKUP_Crude95CI" AS checkup_crude95ci,
    CAST("CHECKUP_AdjPrev" AS DOUBLE) AS checkup_adjprev,
    "CHECKUP_Adj95CI" AS checkup_adj95ci,
    CAST("CHOLSCREEN_CrudePrev" AS DOUBLE) AS cholscreen_crudeprev,
    "CHOLSCREEN_Crude95CI" AS cholscreen_crude95ci,
    CAST("CHOLSCREEN_AdjPrev" AS DOUBLE) AS cholscreen_adjprev,
    "CHOLSCREEN_Adj95CI" AS cholscreen_adj95ci,
    CAST("COLON_SCREEN_CrudePrev" AS DOUBLE) AS colon_screen_crudeprev,
    "COLON_SCREEN_Crude95CI" AS colon_screen_crude95ci,
    CAST("COLON_SCREEN_AdjPrev" AS DOUBLE) AS colon_screen_adjprev,
    "COLON_SCREEN_Adj95CI" AS colon_screen_adj95ci,
    CAST("COPD_CrudePrev" AS DOUBLE) AS copd_crudeprev,
    "COPD_Crude95CI" AS copd_crude95ci,
    CAST("COPD_AdjPrev" AS DOUBLE) AS copd_adjprev,
    "COPD_Adj95CI" AS copd_adj95ci,
    CAST("COREM_CrudePrev" AS DOUBLE) AS corem_crudeprev,
    "COREM_Crude95CI" AS corem_crude95ci,
    CAST("COREM_AdjPrev" AS DOUBLE) AS corem_adjprev,
    "COREM_Adj95CI" AS corem_adj95ci,
    CAST("COREW_CrudePrev" AS DOUBLE) AS corew_crudeprev,
    "COREW_Crude95CI" AS corew_crude95ci,
    CAST("COREW_AdjPrev" AS DOUBLE) AS corew_adjprev,
    "COREW_Adj95CI" AS corew_adj95ci,
    CAST("CSMOKING_CrudePrev" AS DOUBLE) AS csmoking_crudeprev,
    "CSMOKING_Crude95CI" AS csmoking_crude95ci,
    CAST("CSMOKING_AdjPrev" AS DOUBLE) AS csmoking_adjprev,
    "CSMOKING_Adj95CI" AS csmoking_adj95ci,
    CAST("DENTAL_CrudePrev" AS DOUBLE) AS dental_crudeprev,
    "DENTAL_Crude95CI" AS dental_crude95ci,
    CAST("DENTAL_AdjPrev" AS DOUBLE) AS dental_adjprev,
    "DENTAL_Adj95CI" AS dental_adj95ci,
    CAST("DEPRESSION_CrudePrev" AS DOUBLE) AS depression_crudeprev,
    "DEPRESSION_Crude95CI" AS depression_crude95ci,
    CAST("DEPRESSION_AdjPrev" AS DOUBLE) AS depression_adjprev,
    "DEPRESSION_Adj95CI" AS depression_adj95ci,
    CAST("DIABETES_CrudePrev" AS DOUBLE) AS diabetes_crudeprev,
    "DIABETES_Crude95CI" AS diabetes_crude95ci,
    CAST("DIABETES_AdjPrev" AS DOUBLE) AS diabetes_adjprev,
    "DIABETES_Adj95CI" AS diabetes_adj95ci,
    CAST("GHLTH_CrudePrev" AS DOUBLE) AS ghlth_crudeprev,
    "GHLTH_Crude95CI" AS ghlth_crude95ci,
    CAST("GHLTH_AdjPrev" AS DOUBLE) AS ghlth_adjprev,
    "GHLTH_Adj95CI" AS ghlth_adj95ci,
    CAST("HIGHCHOL_CrudePrev" AS DOUBLE) AS highchol_crudeprev,
    "HIGHCHOL_Crude95CI" AS highchol_crude95ci,
    CAST("HIGHCHOL_AdjPrev" AS DOUBLE) AS highchol_adjprev,
    "HIGHCHOL_Adj95CI" AS highchol_adj95ci,
    CAST("KIDNEY_CrudePrev" AS DOUBLE) AS kidney_crudeprev,
    "KIDNEY_Crude95CI" AS kidney_crude95ci,
    CAST("KIDNEY_AdjPrev" AS DOUBLE) AS kidney_adjprev,
    "KIDNEY_Adj95CI" AS kidney_adj95ci,
    CAST("LPA_CrudePrev" AS DOUBLE) AS lpa_crudeprev,
    "LPA_Crude95CI" AS lpa_crude95ci,
    CAST("LPA_AdjPrev" AS DOUBLE) AS lpa_adjprev,
    "LPA_Adj95CI" AS lpa_adj95ci,
    CAST("MAMMOUSE_CrudePrev" AS DOUBLE) AS mammouse_crudeprev,
    "MAMMOUSE_Crude95CI" AS mammouse_crude95ci,
    CAST("MAMMOUSE_AdjPrev" AS DOUBLE) AS mammouse_adjprev,
    "MAMMOUSE_Adj95CI" AS mammouse_adj95ci,
    CAST("MHLTH_CrudePrev" AS DOUBLE) AS mhlth_crudeprev,
    "MHLTH_Crude95CI" AS mhlth_crude95ci,
    CAST("MHLTH_AdjPrev" AS DOUBLE) AS mhlth_adjprev,
    "MHLTH_Adj95CI" AS mhlth_adj95ci,
    CAST("OBESITY_CrudePrev" AS DOUBLE) AS obesity_crudeprev,
    "OBESITY_Crude95CI" AS obesity_crude95ci,
    CAST("OBESITY_AdjPrev" AS DOUBLE) AS obesity_adjprev,
    "OBESITY_Adj95CI" AS obesity_adj95ci,
    CAST("PHLTH_CrudePrev" AS DOUBLE) AS phlth_crudeprev,
    "PHLTH_Crude95CI" AS phlth_crude95ci,
    CAST("PHLTH_AdjPrev" AS DOUBLE) AS phlth_adjprev,
    "PHLTH_Adj95CI" AS phlth_adj95ci,
    CAST("SLEEP_CrudePrev" AS DOUBLE) AS sleep_crudeprev,
    "SLEEP_Crude95CI" AS sleep_crude95ci,
    CAST("SLEEP_AdjPrev" AS DOUBLE) AS sleep_adjprev,
    "SLEEP_Adj95CI" AS sleep_adj95ci,
    CAST("STROKE_CrudePrev" AS DOUBLE) AS stroke_crudeprev,
    "STROKE_Crude95CI" AS stroke_crude95ci,
    CAST("STROKE_AdjPrev" AS DOUBLE) AS stroke_adjprev,
    "STROKE_Adj95CI" AS stroke_adj95ci,
    CAST("TEETHLOST_CrudePrev" AS DOUBLE) AS teethlost_crudeprev,
    "TEETHLOST_Crude95CI" AS teethlost_crude95ci,
    CAST("TEETHLOST_AdjPrev" AS DOUBLE) AS teethlost_adjprev,
    "TEETHLOST_Adj95CI" AS teethlost_adj95ci,
    "Geolocation" AS geolocation
FROM "cdc-xyst-f73f"
