-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "UniqueID" AS uniqueid,
    "EventName" AS eventname,
    "EventType" AS eventtype,
    "State" AS state,
    "DistrictName" AS districtname,
    "DistrictNCESID" AS districtncesid,
    "SchoolName" AS schoolname,
    "SchoolNCESID" AS schoolncesid,
    "Type" AS type,
    CAST("Year" AS BIGINT) AS year,
    "DateClosure" AS dateclosure,
    "DateReopened" AS datereopened,
    CAST("Epi_week" AS BIGINT) AS epi_week,
    CAST("ConfirmedCase" AS BOOLEAN) AS confirmedcase,
    CAST("LCStudent" AS BOOLEAN) AS lcstudent,
    CAST("LCStaff" AS BOOLEAN) AS lcstaff,
    CAST("LCHHMStudent" AS BOOLEAN) AS lchhmstudent,
    CAST("LCHHMStaff" AS BOOLEAN) AS lchhmstaff,
    CAST("LCVisitor" AS BOOLEAN) AS lcvisitor,
    CAST("SuspectedCase" AS BOOLEAN) AS suspectedcase,
    CAST("SCStudent" AS BOOLEAN) AS scstudent,
    CAST("SCStaff" AS BOOLEAN) AS scstaff,
    CAST("SCHHMStudent" AS BOOLEAN) AS schhmstudent,
    CAST("SCHHMStaff" AS BOOLEAN) AS schhmstaff,
    CAST("SCVisitor" AS BOOLEAN) AS scvisitor,
    CAST("AbsentStudents" AS BOOLEAN) AS absentstudents,
    CAST("AbsentStaff" AS BOOLEAN) AS absentstaff,
    CAST("Cluster" AS BOOLEAN) AS cluster,
    CAST("Widespread" AS BOOLEAN) AS widespread,
    CAST("Clean" AS BOOLEAN) AS clean,
    CAST("Mandate" AS BOOLEAN) AS mandate,
    CAST("Recommendation" AS BOOLEAN) AS recommendation,
    CAST("TSCOVID" AS BOOLEAN) AS tscovid,
    CAST("MentalHealth" AS BOOLEAN) AS mentalhealth,
    CAST("Vaccination" AS BOOLEAN) AS vaccination,
    CAST("Side_effects_of_vaccination" AS BOOLEAN) AS side_effects_of_vaccination,
    CAST("OtherReason" AS BOOLEAN) AS otherreason,
    "Specify_other_reason" AS specify_other_reason
FROM "cdc-jnru-aqxk"
