-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "State" AS state,
    "summarySeason" AS summaryseason,
    CAST("Number of Employees" AS BIGINT) AS number_of_employees,
    CAST("Total Number of Employees Vaccinated" AS BIGINT) AS total_number_of_employees_vaccinated,
    CAST("Number of Licensed Practitioners" AS BIGINT) AS number_of_licensed_practitioners,
    CAST("Total Number of Non-Employee Licensed Vaccinated" AS BIGINT) AS total_number_of_non_employee_licensed_vaccinated,
    CAST("Number of Volunteers" AS BIGINT) AS number_of_volunteers,
    CAST("Total Number of Non-Employee Credentialed Vaccinated" AS BIGINT) AS total_number_of_non_employee_credentialed_vaccinated,
    CAST("Number of Other Personnel" AS BIGINT) AS number_of_other_personnel,
    CAST("Total Number of Non-Employee Other Vaccinated" AS BIGINT) AS total_number_of_non_employee_other_vaccinated,
    CAST("Number of Employees Declined" AS BIGINT) AS number_of_employees_declined,
    CAST("Number of Employees Unknown" AS BIGINT) AS number_of_employees_unknown,
    CAST("Number of Employees with Med Contra" AS BIGINT) AS number_of_employees_with_med_contra,
    CAST("Number of Non-Employee Licensed Declined" AS BIGINT) AS number_of_non_employee_licensed_declined,
    CAST("Number of Non-Employee Licensed with Med Contra" AS BIGINT) AS number_of_non_employee_licensed_with_med_contra,
    CAST("Number of Non-Employee Licensed Unknown" AS BIGINT) AS number_of_non_employee_licensed_unknown,
    CAST("numNonEmpCDec" AS BIGINT) AS numnonempcdec,
    CAST("numNonEmpCMed" AS BIGINT) AS numnonempcmed,
    CAST("numNonEmpCUnk" AS BIGINT) AS numnonempcunk,
    CAST("Number of Non-Employee Other Declined" AS BIGINT) AS number_of_non_employee_other_declined,
    CAST("Number of Non-Employee Other with Med Contra" AS BIGINT) AS number_of_non_employee_other_with_med_contra,
    CAST("Number of Non-Employee Other Unknown" AS BIGINT) AS number_of_non_employee_other_unknown,
    CAST("Percentage of Employees Vaccinated" AS DOUBLE) AS percentage_of_employees_vaccinated,
    CAST("Percentage of Non-Employee Licensed Vaccinated" AS DOUBLE) AS percentage_of_non_employee_licensed_vaccinated,
    CAST("Percentage of Non-Employee Credentialed Vaccinated" AS DOUBLE) AS percentage_of_non_employee_credentialed_vaccinated,
    CAST("Percentage of Non-Employee Other Vaccinated" AS DOUBLE) AS percentage_of_non_employee_other_vaccinated,
    CAST("pctEmpDecUnk" AS DOUBLE) AS pctempdecunk,
    CAST("pctNonEmpLDecUnk" AS DOUBLE) AS pctnonempldecunk,
    CAST("pctNonEmpCDecUnk" AS DOUBLE) AS pctnonempcdecunk,
    CAST("pctNonEmpODecUnk" AS DOUBLE) AS pctnonempodecunk,
    CAST("pctEmpMed" AS DOUBLE) AS pctempmed,
    CAST("pctNonEmpLMed" AS DOUBLE) AS pctnonemplmed,
    CAST("pctNonEmpCMed" AS DOUBLE) AS pctnonempcmed,
    CAST("pctNonEmpOMed" AS DOUBLE) AS pctnonempomed,
    CAST("stateNumEmpTotal" AS BIGINT) AS statenumemptotal,
    CAST("stateNumVaccTotal" AS BIGINT) AS statenumvacctotal,
    CAST("Total Percentage of Working Vaccinated" AS DOUBLE) AS total_percentage_of_working_vaccinated,
    CAST("Facility in State" AS BIGINT) AS facility_in_state,
    CAST("Event Year" AS BIGINT) AS event_year,
    CAST("geographyID" AS BIGINT) AS geographyid,
    CAST("Employee Lower Confiden" AS BIGINT) AS employee_lower_confiden,
    CAST("Employee Upr Confidence" AS BIGINT) AS employee_upr_confidence,
    CAST("Non-Employee Licensed Lower Confiden" AS BIGINT) AS non_employee_licensed_lower_confiden,
    CAST("Non-Employee Licensed Upr Confidence" AS BIGINT) AS non_employee_licensed_upr_confidence,
    CAST("Non-Employee Other Lower Confiden" AS BIGINT) AS non_employee_other_lower_confiden,
    CAST("Non-Employee Other Upr Confidence" AS BIGINT) AS non_employee_other_upr_confidence,
    CAST("Total Number Working (Non-Employee and Employee) Upr Confidence" AS BIGINT) AS total_number_working_non_employee_and_employee_upr_confidence,
    CAST("Total Number Working (Non-Employee and Employee) Lower Confiden" AS BIGINT) AS total_number_working_non_employee_and_employee_lower_confiden,
    CAST("Facility Type" AS BIGINT) AS facility_type,
    "factype"
FROM "cdc-89x6-rgq5"
