-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "ZCTA5" AS zcta5,
    CAST("TotalPopulation" AS BIGINT) AS totalpopulation,
    CAST("TotalPop18plus" AS BIGINT) AS totalpop18plus,
    CAST("ACCESS2_CrudePrev" AS DOUBLE) AS access2_crudeprev,
    "ACCESS2_Crude95CI" AS access2_crude95ci,
    CAST("ARTHRITIS_CrudePrev" AS DOUBLE) AS arthritis_crudeprev,
    "ARTHRITIS_Crude95CI" AS arthritis_crude95ci,
    CAST("BINGE_CrudePrev" AS DOUBLE) AS binge_crudeprev,
    "BINGE_Crude95CI" AS binge_crude95ci,
    CAST("BPHIGH_CrudePrev" AS DOUBLE) AS bphigh_crudeprev,
    "BPHIGH_Crude95CI" AS bphigh_crude95ci,
    CAST("BPMED_CrudePrev" AS DOUBLE) AS bpmed_crudeprev,
    "BPMED_Crude95CI" AS bpmed_crude95ci,
    CAST("CANCER_CrudePrev" AS DOUBLE) AS cancer_crudeprev,
    "CANCER_Crude95CI" AS cancer_crude95ci,
    CAST("CASTHMA_CrudePrev" AS DOUBLE) AS casthma_crudeprev,
    "CASTHMA_Crude95CI" AS casthma_crude95ci,
    CAST("CHD_CrudePrev" AS DOUBLE) AS chd_crudeprev,
    "CHD_Crude95CI" AS chd_crude95ci,
    CAST("CHECKUP_CrudePrev" AS DOUBLE) AS checkup_crudeprev,
    "CHECKUP_Crude95CI" AS checkup_crude95ci,
    CAST("CHOLSCREEN_CrudePrev" AS DOUBLE) AS cholscreen_crudeprev,
    "CHOLSCREEN_Crude95CI" AS cholscreen_crude95ci,
    CAST("COLON_SCREEN_CrudePrev" AS DOUBLE) AS colon_screen_crudeprev,
    "COLON_SCREEN_Crude95CI" AS colon_screen_crude95ci,
    CAST("COPD_CrudePrev" AS DOUBLE) AS copd_crudeprev,
    "COPD_Crude95CI" AS copd_crude95ci,
    CAST("CSMOKING_CrudePrev" AS DOUBLE) AS csmoking_crudeprev,
    "CSMOKING_Crude95CI" AS csmoking_crude95ci,
    CAST("DENTAL_CrudePrev" AS DOUBLE) AS dental_crudeprev,
    "DENTAL_Crude95CI" AS dental_crude95ci,
    CAST("DEPRESSION_CrudePrev" AS DOUBLE) AS depression_crudeprev,
    "DEPRESSION_Crude95CI" AS depression_crude95ci,
    CAST("DIABETES_CrudePrev" AS DOUBLE) AS diabetes_crudeprev,
    "DIABETES_Crude95CI" AS diabetes_crude95ci,
    CAST("GHLTH_CrudePrev" AS DOUBLE) AS ghlth_crudeprev,
    "GHLTH_Crude95CI" AS ghlth_crude95ci,
    CAST("HIGHCHOL_CrudePrev" AS DOUBLE) AS highchol_crudeprev,
    "HIGHCHOL_Crude95CI" AS highchol_crude95ci,
    CAST("LPA_CrudePrev" AS DOUBLE) AS lpa_crudeprev,
    "LPA_Crude95CI" AS lpa_crude95ci,
    CAST("MAMMOUSE_CrudePrev" AS DOUBLE) AS mammouse_crudeprev,
    "MAMMOUSE_Crude95CI" AS mammouse_crude95ci,
    CAST("MHLTH_CrudePrev" AS DOUBLE) AS mhlth_crudeprev,
    "MHLTH_Crude95CI" AS mhlth_crude95ci,
    CAST("OBESITY_CrudePrev" AS DOUBLE) AS obesity_crudeprev,
    "OBESITY_Crude95CI" AS obesity_crude95ci,
    CAST("PHLTH_CrudePrev" AS DOUBLE) AS phlth_crudeprev,
    "PHLTH_Crude95CI" AS phlth_crude95ci,
    CAST("SLEEP_CrudePrev" AS DOUBLE) AS sleep_crudeprev,
    "SLEEP_Crude95CI" AS sleep_crude95ci,
    CAST("STROKE_CrudePrev" AS DOUBLE) AS stroke_crudeprev,
    "STROKE_Crude95CI" AS stroke_crude95ci,
    CAST("TEETHLOST_CrudePrev" AS DOUBLE) AS teethlost_crudeprev,
    "TEETHLOST_Crude95CI" AS teethlost_crude95ci,
    CAST("HEARING_CrudePrev" AS DOUBLE) AS hearing_crudeprev,
    "HEARING_Crude95CI" AS hearing_crude95ci,
    CAST("VISION_CrudePrev" AS DOUBLE) AS vision_crudeprev,
    "VISION_Crude95CI" AS vision_crude95ci,
    CAST("COGNITION_CrudePrev" AS DOUBLE) AS cognition_crudeprev,
    "COGNITION_Crude95CI" AS cognition_crude95ci,
    CAST("MOBILITY_CrudePrev" AS DOUBLE) AS mobility_crudeprev,
    "MOBILITY_Crude95CI" AS mobility_crude95ci,
    CAST("SELFCARE_CrudePrev" AS DOUBLE) AS selfcare_crudeprev,
    "SELFCARE_Crude95CI" AS selfcare_crude95ci,
    CAST("INDEPLIVE_CrudePrev" AS DOUBLE) AS indeplive_crudeprev,
    "INDEPLIVE_Crude95CI" AS indeplive_crude95ci,
    CAST("DISABILITY_CrudePrev" AS DOUBLE) AS disability_crudeprev,
    "DISABILITY_Crude95CI" AS disability_crude95ci,
    CAST("LONELINESS_CrudePrev" AS DOUBLE) AS loneliness_crudeprev,
    "LONELINESS_Crude95CI" AS loneliness_crude95ci,
    CAST("FOODSTAMP_CrudePrev" AS DOUBLE) AS foodstamp_crudeprev,
    "FOODSTAMP_Crude95CI" AS foodstamp_crude95ci,
    CAST("FOODINSECU_CrudePrev" AS DOUBLE) AS foodinsecu_crudeprev,
    "FOODINSECU_Crude95CI" AS foodinsecu_crude95ci,
    CAST("HOUSINSECU_CrudePrev" AS DOUBLE) AS housinsecu_crudeprev,
    "HOUSINSECU_Crude95CI" AS housinsecu_crude95ci,
    CAST("SHUTUTILITY_CrudePrev" AS DOUBLE) AS shututility_crudeprev,
    "SHUTUTILITY_Crude95CI" AS shututility_crude95ci,
    CAST("LACKTRPT_CrudePrev" AS DOUBLE) AS lacktrpt_crudeprev,
    "LACKTRPT_Crude95CI" AS lacktrpt_crude95ci,
    CAST("EMOTIONSPT_CrudePrev" AS DOUBLE) AS emotionspt_crudeprev,
    "EMOTIONSPT_Crude95CI" AS emotionspt_crude95ci,
    "Geolocation" AS geolocation
FROM "cdc-kee5-23sr"
