-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No compact row identity was verified from the raw profile; rows are published as source observations and may include multiple cuts, measures, or suppressions from separate CKAN resources.
SELECT
    "resource_id",
    "resource_name",
    "Quarter" AS quarter,
    "HBT" AS hbt,
    "Specialty" AS specialty,
    CAST("NumberOfReferrals" AS BIGINT) AS numberofreferrals,
    "NumberOfReferralsQF" AS numberofreferralsqf,
    CAST("ReferralsPerOneHundredThousandPopulation" AS DOUBLE) AS referralsperonehundredthousandpopulation,
    "ReferralsPerOneHundredThousandPopulationQF" AS referralsperonehundredthousandpopulationqf,
    CAST("Month" AS BIGINT) AS month,
    CAST("PatientsSeen" AS BIGINT) AS patientsseen,
    "PatientsSeenQF" AS patientsseenqf,
    CAST("NumberWhoWaitedZeroToFourWeeks" AS BIGINT) AS numberwhowaitedzerotofourweeks,
    "NumberWhoWaitedZeroToFourWeeksQF" AS numberwhowaitedzerotofourweeksqf,
    CAST("NumberWhoWaitedFiveToEightWeeks" AS BIGINT) AS numberwhowaitedfivetoeightweeks,
    "NumberWhoWaitedFiveToEightWeeksQF" AS numberwhowaitedfivetoeightweeksqf,
    CAST("NumberWhoWaitedNineToTwelveWeeks" AS BIGINT) AS numberwhowaitedninetotwelveweeks,
    "NumberWhoWaitedNineToTwelveWeeksQF" AS numberwhowaitedninetotwelveweeksqf,
    CAST("NumberWhoWaitedThirteenToSixteenWeeks" AS BIGINT) AS numberwhowaitedthirteentosixteenweeks,
    "NumberWhoWaitedThirteenToSixteenWeeksQF" AS numberwhowaitedthirteentosixteenweeksqf,
    CAST("NumberWhoWaitedFourPlusWeeks" AS BIGINT) AS numberwhowaitedfourplusweeks,
    "NumberWhoWaitedFourPlusWeeksQF" AS numberwhowaitedfourplusweeksqf,
    CAST("NumberWhoWaitedSixteenPlusWeeks" AS BIGINT) AS numberwhowaitedsixteenplusweeks,
    "NumberWhoWaitedSixteenPlusWeeksQF" AS numberwhowaitedsixteenplusweeksqf,
    CAST("NumberWhoWaitedZeroToFourWeeksPc" AS DOUBLE) AS numberwhowaitedzerotofourweekspc,
    "NumberWhoWaitedZeroToFourWeeksPcQF" AS numberwhowaitedzerotofourweekspcqf,
    CAST("NumberWhoWaitedFiveToEightWeeksPc" AS DOUBLE) AS numberwhowaitedfivetoeightweekspc,
    "NumberWhoWaitedFiveToEightWeeksPcQF" AS numberwhowaitedfivetoeightweekspcqf,
    CAST("NumberWhoWaitedNineToTwelveWeeksPc" AS DOUBLE) AS numberwhowaitedninetotwelveweekspc,
    "NumberWhoWaitedNineToTwelveWeeksPcQF" AS numberwhowaitedninetotwelveweekspcqf,
    CAST("NumberWhoWaitedThirteenToSixteenWeeksPc" AS DOUBLE) AS numberwhowaitedthirteentosixteenweekspc,
    "NumberWhoWaitedThirteenToSixteenWeeksPcQF" AS numberwhowaitedthirteentosixteenweekspcqf,
    CAST("NumberWhoWaitedFourPlusWeeksPc" AS DOUBLE) AS numberwhowaitedfourplusweekspc,
    "NumberWhoWaitedFourPlusWeeksPcQF" AS numberwhowaitedfourplusweekspcqf,
    CAST("NumberWhoWaitedSixteenPlusWeeksPc" AS DOUBLE) AS numberwhowaitedsixteenplusweekspc,
    "NumberWhoWaitedSixteenPlusWeeksPcQF" AS numberwhowaitedsixteenplusweekspcqf,
    "MedianWaitWeeks" AS medianwaitweeks,
    "MedianWaitWeeksQF" AS medianwaitweeksqf,
    "NinetiethPercentileWaitWeeks" AS ninetiethpercentilewaitweeks,
    "NinetiethPercentileWaitWeeksQF" AS ninetiethpercentilewaitweeksqf,
    "HSCP" AS hscp,
    CAST("PatientsWaiting" AS BIGINT) AS patientswaiting,
    "PatientsWaitingQF" AS patientswaitingqf,
    CAST("NumberWaitingZeroToFourWeeks" AS BIGINT) AS numberwaitingzerotofourweeks,
    "NumberWaitingZeroToFourWeeksQF" AS numberwaitingzerotofourweeksqf,
    CAST("NumberWaitingFiveToEightWeeks" AS BIGINT) AS numberwaitingfivetoeightweeks,
    "NumberWaitingFiveToEightWeeksQF" AS numberwaitingfivetoeightweeksqf,
    CAST("NumberWaitingNineToTwelveWeeks" AS BIGINT) AS numberwaitingninetotwelveweeks,
    "NumberWaitingNineToTwelveWeeksQF" AS numberwaitingninetotwelveweeksqf,
    CAST("NumberWaitingThirteenToSixteenWeeks" AS BIGINT) AS numberwaitingthirteentosixteenweeks,
    "NumberWaitingThirteenToSixteenWeeksQF" AS numberwaitingthirteentosixteenweeksqf,
    CAST("NumberWaitingFourPlusWeeks" AS BIGINT) AS numberwaitingfourplusweeks,
    "NumberWaitingFourPlusWeeksQF" AS numberwaitingfourplusweeksqf,
    CAST("NumberWaitingSixteenPlusWeeks" AS BIGINT) AS numberwaitingsixteenplusweeks,
    "NumberWaitingSixteenPlusWeeksQF" AS numberwaitingsixteenplusweeksqf,
    CAST("NumberWaitingZeroToFourWeeksPc" AS DOUBLE) AS numberwaitingzerotofourweekspc,
    "NumberWaitingZeroToFourWeeksPcQF" AS numberwaitingzerotofourweekspcqf,
    CAST("NumberWaitingFiveToEightWeeksPc" AS DOUBLE) AS numberwaitingfivetoeightweekspc,
    "NumberWaitingFiveToEightWeeksPcQF" AS numberwaitingfivetoeightweekspcqf,
    CAST("NumberWaitingNineToTwelveWeeksPc" AS DOUBLE) AS numberwaitingninetotwelveweekspc,
    "NumberWaitingNineToTwelveWeeksPcQF" AS numberwaitingninetotwelveweekspcqf,
    CAST("NumberWaitingThirteenToSixteenWeeksPc" AS DOUBLE) AS numberwaitingthirteentosixteenweekspc,
    "NumberWaitingThirteenToSixteenWeeksPcQF" AS numberwaitingthirteentosixteenweekspcqf,
    CAST("NumberWaitingFourPlusWeeksPc" AS DOUBLE) AS numberwaitingfourplusweekspc,
    "NumberWaitingFourPlusWeeksPcQF" AS numberwaitingfourplusweekspcqf,
    CAST("NumberWaitingSixteenPlusWeeksPc" AS DOUBLE) AS numberwaitingsixteenplusweekspc,
    "NumberWaitingSixteenPlusWeeksPcQF" AS numberwaitingsixteenplusweekspcqf,
    CAST("DNAIndicator" AS BIGINT) AS dnaindicator,
    "DNAIndicatorQF" AS dnaindicatorqf,
    CAST("DNARate" AS DOUBLE) AS dnarate,
    "DNARateQF" AS dnarateqf,
    CAST("AcceptedAppointments" AS BIGINT) AS acceptedappointments,
    "AcceptedAppointmentsQF" AS acceptedappointmentsqf,
    CAST("CancelledByServiceIndicator" AS BIGINT) AS cancelledbyserviceindicator,
    "CancelledByServiceIndicatorQF" AS cancelledbyserviceindicatorqf,
    CAST("CancellationByServiceRate" AS DOUBLE) AS cancellationbyservicerate,
    "CancellationByServiceRateQF" AS cancellationbyservicerateqf,
    CAST("CNAIndicator" AS BIGINT) AS cnaindicator,
    "CNAIndicatorQF" AS cnaindicatorqf,
    CAST("CNARate" AS DOUBLE) AS cnarate,
    "CNARateQF" AS cnarateqf,
    "ReferralSource" AS referralsource,
    CAST("RemovalsFromList" AS BIGINT) AS removalsfromlist,
    "RemovalsFromListQF" AS removalsfromlistqf,
    CAST("RemovalsFromListAttended" AS BIGINT) AS removalsfromlistattended,
    "RemovalsFromListAttendedQF" AS removalsfromlistattendedqf,
    CAST("RemovalsFromListReferredBackToGP" AS BIGINT) AS removalsfromlistreferredbacktogp,
    "RemovalsFromListReferredBackToGPQF" AS removalsfromlistreferredbacktogpqf,
    CAST("RemovalsFromListTransferred" AS BIGINT) AS removalsfromlisttransferred,
    "RemovalsFromListTransferredQF" AS removalsfromlisttransferredqf,
    CAST("RemovalsFromListTreatmentNoLongerRequired" AS BIGINT) AS removalsfromlisttreatmentnolongerrequired,
    "RemovalsFromListTreatmentNoLongerRequiredQF" AS removalsfromlisttreatmentnolongerrequiredqf,
    CAST("RemovalsFromListOtherReasons" AS BIGINT) AS removalsfromlistotherreasons,
    "RemovalsFromListOtherReasonsQF" AS removalsfromlistotherreasonsqf,
    CAST("NumberOnList" AS BIGINT) AS numberonlist,
    "NumberOnListQF" AS numberonlistqf,
    CAST("AvailableForTreatment" AS BIGINT) AS availablefortreatment,
    "AvailableForTreatmentQF" AS availablefortreatmentqf,
    CAST("UnavailableForTreatment" AS BIGINT) AS unavailablefortreatment,
    "UnavailableForTreatmentQF" AS unavailablefortreatmentqf,
    CAST("UnavailableForTreatmentMedical" AS BIGINT) AS unavailablefortreatmentmedical,
    "UnavailableForTreatmentMedicalQF" AS unavailablefortreatmentmedicalqf,
    CAST("UnavailableForTreatmentPatientAdvised" AS BIGINT) AS unavailablefortreatmentpatientadvised,
    "UnavailableForTreatmentPatientAdvisedQF" AS unavailablefortreatmentpatientadvisedqf,
    CAST("UnavailableForTreatmentPatientRequested" AS BIGINT) AS unavailablefortreatmentpatientrequested,
    "UnavailableForTreatmentPatientRequestedQF" AS unavailablefortreatmentpatientrequestedqf,
    CAST("UnavailableForTreatmentOther" AS BIGINT) AS unavailablefortreatmentother,
    "UnavailableForTreatmentOtherQF" AS unavailablefortreatmentotherqf
FROM "public-health-scotland-allied-health-professionals-musculoskeletal-waiting-times"
