-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No compact row identity was verified from the raw profile; rows are published as source observations and may include multiple cuts, measures, or suppressions from separate CKAN resources.
SELECT
    "resource_id",
    "resource_name",
    "Country" AS country,
    "CancerSiteICD10Code" AS cancersiteicd10code,
    "CancerSite" AS cancersite,
    "Sex" AS sex,
    "SexQF" AS sexqf,
    "Year" AS year,
    CAST("IncidencesAgeUnder5" AS BIGINT) AS incidencesageunder5,
    CAST("IncidencesAge5To9" AS BIGINT) AS incidencesage5to9,
    CAST("IncidencesAge10To14" AS BIGINT) AS incidencesage10to14,
    CAST("IncidencesAge15To19" AS BIGINT) AS incidencesage15to19,
    CAST("IncidencesAge20To24" AS BIGINT) AS incidencesage20to24,
    CAST("IncidencesAge25To29" AS BIGINT) AS incidencesage25to29,
    CAST("IncidencesAge30To34" AS BIGINT) AS incidencesage30to34,
    CAST("IncidencesAge35To39" AS BIGINT) AS incidencesage35to39,
    CAST("IncidencesAge40To44" AS BIGINT) AS incidencesage40to44,
    CAST("IncidencesAge45To49" AS BIGINT) AS incidencesage45to49,
    CAST("IncidencesAge50To54" AS BIGINT) AS incidencesage50to54,
    CAST("IncidencesAge55To59" AS BIGINT) AS incidencesage55to59,
    CAST("IncidencesAge60To64" AS BIGINT) AS incidencesage60to64,
    CAST("IncidencesAge65To69" AS BIGINT) AS incidencesage65to69,
    CAST("IncidencesAge70To74" AS BIGINT) AS incidencesage70to74,
    CAST("IncidencesAge75To79" AS BIGINT) AS incidencesage75to79,
    CAST("IncidencesAge80To84" AS BIGINT) AS incidencesage80to84,
    CAST("IncidencesAge85To89" AS BIGINT) AS incidencesage85to89,
    CAST("IncidencesAge90AndOver" AS BIGINT) AS incidencesage90andover,
    CAST("IncidencesAllAges" AS BIGINT) AS incidencesallages,
    CAST("IncidenceRateAgeUnder5" AS DOUBLE) AS incidencerateageunder5,
    CAST("IncidenceRateAge5To9" AS DOUBLE) AS incidencerateage5to9,
    CAST("IncidenceRateAge10To14" AS DOUBLE) AS incidencerateage10to14,
    CAST("IncidenceRateAge15To19" AS DOUBLE) AS incidencerateage15to19,
    CAST("IncidenceRateAge20To24" AS DOUBLE) AS incidencerateage20to24,
    CAST("IncidenceRateAge25To29" AS DOUBLE) AS incidencerateage25to29,
    CAST("IncidenceRateAge30To34" AS DOUBLE) AS incidencerateage30to34,
    CAST("IncidenceRateAge35To39" AS DOUBLE) AS incidencerateage35to39,
    CAST("IncidenceRateAge40To44" AS DOUBLE) AS incidencerateage40to44,
    CAST("IncidenceRateAge45To49" AS DOUBLE) AS incidencerateage45to49,
    CAST("IncidenceRateAge50To54" AS DOUBLE) AS incidencerateage50to54,
    CAST("IncidenceRateAge55To59" AS DOUBLE) AS incidencerateage55to59,
    CAST("IncidenceRateAge60To64" AS DOUBLE) AS incidencerateage60to64,
    CAST("IncidenceRateAge65To69" AS DOUBLE) AS incidencerateage65to69,
    CAST("IncidenceRateAge70To74" AS DOUBLE) AS incidencerateage70to74,
    CAST("IncidenceRateAge75To79" AS DOUBLE) AS incidencerateage75to79,
    CAST("IncidenceRateAge80To84" AS DOUBLE) AS incidencerateage80to84,
    CAST("IncidenceRateAge85To89" AS DOUBLE) AS incidencerateage85to89,
    CAST("IncidenceRateAge90AndOver" AS DOUBLE) AS incidencerateage90andover,
    CAST("CrudeRate" AS DOUBLE) AS cruderate,
    CAST("CrudeRateLower95pcConfidenceInterval" AS DOUBLE) AS cruderatelower95pcconfidenceinterval,
    CAST("CrudeRateUpper95pcConfidenceInterval" AS DOUBLE) AS cruderateupper95pcconfidenceinterval,
    CAST("EASR" AS DOUBLE) AS easr,
    "EASRLower95pcConfidenceInterval" AS easrlower95pcconfidenceinterval,
    "EASRLower95pcConfidenceIntervalQF" AS easrlower95pcconfidenceintervalqf,
    "EASRUpper95pcConfidenceInterval" AS easrupper95pcconfidenceinterval,
    "EASRUpper95pcConfidenceIntervalQF" AS easrupper95pcconfidenceintervalqf,
    CAST("WASR" AS DOUBLE) AS wasr,
    "WASRLower95pcConfidenceInterval" AS wasrlower95pcconfidenceinterval,
    "WASRLower95pcConfidenceIntervalQF" AS wasrlower95pcconfidenceintervalqf,
    "WASRUpper95pcConfidenceInterval" AS wasrupper95pcconfidenceinterval,
    "WASRUpper95pcConfidenceIntervalQF" AS wasrupper95pcconfidenceintervalqf,
    "StandardisedIncidenceRatio" AS standardisedincidenceratio,
    "StandardisedIncidenceRatioQF" AS standardisedincidenceratioqf,
    "Region" AS region,
    CAST("SIRLower95pcConfidenceInterval" AS DOUBLE) AS sirlower95pcconfidenceinterval,
    CAST("SIRUpper95pcConfidenceInterval" AS DOUBLE) AS sirupper95pcconfidenceinterval,
    "HB" AS hb,
    CAST("IncidencesAge85AndOver" AS BIGINT) AS incidencesage85andover,
    CAST("IncidenceRateAge85AndOver" AS DOUBLE) AS incidencerateage85andover
FROM "public-health-scotland-annual-cancer-incidence"
