-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No compact row identity was verified from the raw profile; rows are published as source observations and may include multiple cuts, measures, or suppressions from separate CKAN resources.
SELECT
    "resource_id",
    "resource_name",
    strptime("MonthEnding", '%Y%m%d')::DATE AS monthending,
    "HBT" AS hbt,
    "HBTQF" AS hbtqf,
    "PatientType" AS patienttype,
    "WaitType" AS waittype,
    "Specialty" AS specialty,
    "SpecialtyQF" AS specialtyqf,
    CAST("LessThan4WeekWait" AS BIGINT) AS lessthan4weekwait,
    "LessThan4WeekWaitQF" AS lessthan4weekwaitqf,
    CAST("4To8WeekWait" AS BIGINT) AS 4to8weekwait,
    "4To8WeekWaitQF" AS 4to8weekwaitqf,
    CAST("8To12WeekWait" AS BIGINT) AS 8to12weekwait,
    "8To12WeekWaitQF" AS 8to12weekwaitqf,
    CAST("12To16WeekWait" AS BIGINT) AS 12to16weekwait,
    "12To16WeekWaitQF" AS 12to16weekwaitqf,
    CAST("16To20WeekWait" AS BIGINT) AS 16to20weekwait,
    "16To20WeekWaitQF" AS 16to20weekwaitqf,
    CAST("20To24WeekWait" AS BIGINT) AS 20to24weekwait,
    "20To24WeekWaitQF" AS 20to24weekwaitqf,
    CAST("24To28WeekWait" AS BIGINT) AS 24to28weekwait,
    "24To28WeekWaitQF" AS 24to28weekwaitqf,
    CAST("28To32WeekWait" AS BIGINT) AS 28to32weekwait,
    "28To32WeekWaitQF" AS 28to32weekwaitqf,
    CAST("32To36WeekWait" AS BIGINT) AS 32to36weekwait,
    "32To36WeekWaitQF" AS 32to36weekwaitqf,
    CAST("36To40WeekWait" AS BIGINT) AS 36to40weekwait,
    "36To40WeekWaitQF" AS 36to40weekwaitqf,
    CAST("40To44WeekWait" AS BIGINT) AS 40to44weekwait,
    "40To44WeekWaitQF" AS 40to44weekwaitqf,
    CAST("44To48WeekWait" AS BIGINT) AS 44to48weekwait,
    "44To48WeekWaitQF" AS 44to48weekwaitqf,
    CAST("48To52WeekWait" AS BIGINT) AS 48to52weekwait,
    "48To52WeekWaitQF" AS 48to52weekwaitqf,
    CAST("52To65WeekWait" AS BIGINT) AS 52to65weekwait,
    "52To65WeekWaitQF" AS 52to65weekwaitqf,
    CAST("65To78WeekWait" AS BIGINT) AS 65to78weekwait,
    "65To78WeekWaitQF" AS 65to78weekwaitqf,
    CAST("78To91WeekWait" AS BIGINT) AS 78to91weekwait,
    "78To91WeekWaitQF" AS 78to91weekwaitqf,
    CAST("91To104WeekWait" AS BIGINT) AS 91to104weekwait,
    "91To104WeekWaitQF" AS 91to104weekwaitqf,
    CAST("104To117WeekWait" AS BIGINT) AS 104to117weekwait,
    "104To117WeekWaitQF" AS 104to117weekwaitqf,
    CAST("117To130WeekWait" AS BIGINT) AS 117to130weekwait,
    "117To130WeekWaitQF" AS 117to130weekwaitqf,
    CAST("130To143WeekWait" AS BIGINT) AS 130to143weekwait,
    "130To143WeekWaitQF" AS 130to143weekwaitqf,
    CAST("143To156WeekWait" AS BIGINT) AS 143to156weekwait,
    "143To156WeekWaitQF" AS 143to156weekwaitqf,
    CAST("Over156WeekWait" AS BIGINT) AS over156weekwait,
    "Over156WeekWaitQF" AS over156weekwaitqf,
    CAST("Waits" AS BIGINT) AS waits,
    "WaitsQF" AS waitsqf,
    CAST("WaitsOver12Weeks" AS BIGINT) AS waitsover12weeks,
    "WaitsOver12WeeksQF" AS waitsover12weeksqf,
    CAST("WaitsOver52Weeks" AS BIGINT) AS waitsover52weeks,
    "WaitsOver52WeeksQF" AS waitsover52weeksqf,
    CAST("WaitsOver78Weeks" AS BIGINT) AS waitsover78weeks,
    "WaitsOver78WeeksQF" AS waitsover78weeksqf,
    CAST("WaitsOver104Weeks" AS BIGINT) AS waitsover104weeks,
    "WaitsOver104WeeksQF" AS waitsover104weeksqf,
    CAST("Median" AS BIGINT) AS median,
    "MedianQF" AS medianqf,
    CAST("90thPercentile" AS BIGINT) AS 90thpercentile,
    "90thPercentileQF" AS 90thpercentileqf,
    CAST("QuarterEnding" AS BIGINT) AS quarterending,
    CAST("NumberSeen" AS BIGINT) AS numberseen,
    "NumberSeenQF" AS numberseenqf,
    CAST("WaitedOver12Weeks" AS BIGINT) AS waitedover12weeks,
    "WaitedOver12WeeksQF" AS waitedover12weeksqf,
    CAST("NumberWaiting" AS BIGINT) AS numberwaiting,
    "NumberWaitingQF" AS numberwaitingqf,
    CAST("NumberWaitingOver12Weeks" AS BIGINT) AS numberwaitingover12weeks,
    "NumberWaitingOver12WeeksQF" AS numberwaitingover12weeksqf,
    strptime("MonthEnd", '%Y%m%d')::DATE AS monthend,
    CAST("AcceptedAppointments" AS BIGINT) AS acceptedappointments,
    "AcceptedAppointmentsQF" AS acceptedappointmentsqf,
    CAST("DidNotAttendRatePc" AS DOUBLE) AS didnotattendratepc,
    "DidNotAttendRatePcQF" AS didnotattendratepcqf,
    CAST("CouldNotAttendRatePc" AS DOUBLE) AS couldnotattendratepc,
    "CouldNotAttendRatePcQF" AS couldnotattendratepcqf,
    CAST("CancellationByServiceRatePc" AS DOUBLE) AS cancellationbyserviceratepc,
    "CancellationByServiceRatePcQF" AS cancellationbyserviceratepcqf,
    CAST("Additions" AS BIGINT) AS additions,
    "AdditionsQF" AS additionsqf,
    CAST("Removals" AS BIGINT) AS removals,
    "RemovalsQF" AS removalsqf,
    CAST("Attended" AS BIGINT) AS attended,
    "AttendedQF" AS attendedqf,
    CAST("ReferredBackToGP" AS BIGINT) AS referredbacktogp,
    "ReferredBackToGPQF" AS referredbacktogpqf,
    CAST("Transferred" AS BIGINT) AS transferred,
    "TransferredQF" AS transferredqf,
    CAST("TreatmentNoLongerRequired" AS BIGINT) AS treatmentnolongerrequired,
    "TreatmentNoLongerRequiredQF" AS treatmentnolongerrequiredqf,
    CAST("OtherReasons" AS BIGINT) AS otherreasons,
    "OtherReasonsQF" AS otherreasonsqf,
    CAST("Available" AS BIGINT) AS available,
    "AvailableQF" AS availableqf,
    CAST("Unavailable" AS BIGINT) AS unavailable,
    "UnavailableQF" AS unavailableqf,
    CAST("MedicalTotal" AS BIGINT) AS medicaltotal,
    "MedicalTotalQF" AS medicaltotalqf,
    CAST("MedicalOtherMedicalCondition" AS BIGINT) AS medicalothermedicalcondition,
    "MedicalOtherMedicalConditionQF" AS medicalothermedicalconditionqf,
    CAST("MedicalIndefinitelyUnavailable" AS BIGINT) AS medicalindefinitelyunavailable,
    "MedicalIndefinitelyUnavailableQF" AS medicalindefinitelyunavailableqf,
    CAST("MedicalOther" AS BIGINT) AS medicalother,
    "MedicalOtherQF" AS medicalotherqf,
    CAST("PatientAdvisedTotal" AS BIGINT) AS patientadvisedtotal,
    "PatientAdvisedTotalQF" AS patientadvisedtotalqf,
    CAST("PatientAdvisedHoliday" AS BIGINT) AS patientadvisedholiday,
    "PatientAdvisedHolidayQF" AS patientadvisedholidayqf,
    CAST("PatientAdvisedPersonalCommitment" AS BIGINT) AS patientadvisedpersonalcommitment,
    "PatientAdvisedPersonalCommitmentQF" AS patientadvisedpersonalcommitmentqf,
    CAST("PatientAdvisedWorkCommitment" AS BIGINT) AS patientadvisedworkcommitment,
    "PatientAdvisedWorkCommitmentQF" AS patientadvisedworkcommitmentqf,
    CAST("PatientAdvisedCarerCommitment" AS BIGINT) AS patientadvisedcarercommitment,
    "PatientAdvisedCarerCommitmentQF" AS patientadvisedcarercommitmentqf,
    CAST("PatientAdvisedAcademicCommitment" AS BIGINT) AS patientadvisedacademiccommitment,
    "PatientAdvisedAcademicCommitmentQF" AS patientadvisedacademiccommitmentqf,
    CAST("PatientAdvisedJuryDuty" AS BIGINT) AS patientadvisedjuryduty,
    "PatientAdvisedJuryDutyQF" AS patientadvisedjurydutyqf,
    CAST("PatientAdvisedWeather" AS BIGINT) AS patientadvisedweather,
    "PatientAdvisedWeatherQF" AS patientadvisedweatherqf,
    CAST("PatientAdvisedIndefinitelyUnavailable" AS BIGINT) AS patientadvisedindefinitelyunavailable,
    "PatientAdvisedIndefinitelyUnavailableQF" AS patientadvisedindefinitelyunavailableqf,
    CAST("PatientAdvisedOther" AS BIGINT) AS patientadvisedother,
    "PatientAdvisedOtherQF" AS patientadvisedotherqf,
    CAST("PatientRequestedTotal" AS BIGINT) AS patientrequestedtotal,
    "PatientRequestedTotalQF" AS patientrequestedtotalqf,
    CAST("PatientRequestedNamedConsultant" AS BIGINT) AS patientrequestednamedconsultant,
    "PatientRequestedNamedConsultantQF" AS patientrequestednamedconsultantqf,
    CAST("PatientRequestedTreatedLocalHealthBoard" AS BIGINT) AS patientrequestedtreatedlocalhealthboard,
    "PatientRequestedTreatedLocalHealthBoardQF" AS patientrequestedtreatedlocalhealthboardqf,
    CAST("SuspensionExceptionalCircumstances" AS BIGINT) AS suspensionexceptionalcircumstances,
    "SuspensionExceptionalCircumstancesQF" AS suspensionexceptionalcircumstancesqf,
    CAST("PatientTransferClockAdjustment" AS BIGINT) AS patienttransferclockadjustment,
    "PatientTransferClockAdjustmentQF" AS patienttransferclockadjustmentqf,
    CAST("PFBUnavailability" AS BIGINT) AS pfbunavailability,
    "PFBUnavailabilityQF" AS pfbunavailabilityqf,
    "HBR" AS hbr,
    "HBRQF" AS hbrqf
FROM "public-health-scotland-stage-of-treatment-waiting-times"
