-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No compact row identity was verified from the raw profile; rows are published as source observations and may include multiple cuts, measures, or suppressions from separate CKAN resources.
SELECT
    "resource_id",
    "resource_name",
    CAST("Month" AS BIGINT) AS month,
    "Country" AS country,
    "HBT" AS hbt,
    "DepartmentType" AS departmenttype,
    "Age" AS age,
    "AgeQF" AS ageqf,
    "Sex" AS sex,
    "SexQF" AS sexqf,
    CAST("Deprivation" AS BIGINT) AS deprivation,
    "DeprivationQF" AS deprivationqf,
    CAST("NumberOfAttendances" AS BIGINT) AS numberofattendances,
    "TreatmentLocation" AS treatmentlocation,
    "AttendanceCategory" AS attendancecategory,
    CAST("NumberOfAttendancesAll" AS BIGINT) AS numberofattendancesall,
    CAST("NumberWithin4HoursAll" AS BIGINT) AS numberwithin4hoursall,
    CAST("NumberOver4HoursAll" AS BIGINT) AS numberover4hoursall,
    CAST("PercentageWithin4HoursAll" AS DOUBLE) AS percentagewithin4hoursall,
    CAST("NumberOfAttendancesEpisode" AS BIGINT) AS numberofattendancesepisode,
    "NumberOfAttendancesEpisodeQF" AS numberofattendancesepisodeqf,
    CAST("NumberWithin4HoursEpisode" AS BIGINT) AS numberwithin4hoursepisode,
    "NumberWithin4HoursEpisodeQF" AS numberwithin4hoursepisodeqf,
    CAST("NumberOver4HoursEpisode" AS BIGINT) AS numberover4hoursepisode,
    "NumberOver4HoursEpisodeQF" AS numberover4hoursepisodeqf,
    CAST("PercentageWithin4HoursEpisode" AS DOUBLE) AS percentagewithin4hoursepisode,
    "PercentageWithin4HoursEpisodeQF" AS percentagewithin4hoursepisodeqf,
    CAST("NumberOver8HoursEpisode" AS BIGINT) AS numberover8hoursepisode,
    "NumberOver8HoursEpisodeQF" AS numberover8hoursepisodeqf,
    CAST("PercentageOver8HoursEpisode" AS DOUBLE) AS percentageover8hoursepisode,
    "PercentageOver8HoursEpisodeQF" AS percentageover8hoursepisodeqf,
    CAST("NumberOver12HoursEpisode" AS BIGINT) AS numberover12hoursepisode,
    "NumberOver12HoursEpisodeQF" AS numberover12hoursepisodeqf,
    CAST("PercentageOver12HoursEpisode" AS DOUBLE) AS percentageover12hoursepisode,
    "PercentageOver12HoursEpisodeQF" AS percentageover12hoursepisodeqf,
    "Referral" AS referral,
    "ReferralQF" AS referralqf,
    "Discharge" AS discharge,
    "DischargeQF" AS dischargeqf,
    "Day" AS day,
    "Week" AS week,
    "Hour" AS hour,
    "InOut" AS inout,
    CAST("YearEnd" AS BIGINT) AS yearend,
    CAST("OneAttendance" AS BIGINT) AS oneattendance,
    CAST("TwoAttendances" AS BIGINT) AS twoattendances,
    CAST("ThreeAttendances" AS BIGINT) AS threeattendances,
    CAST("FourAttendances" AS BIGINT) AS fourattendances,
    CAST("FivePlusAttendances" AS BIGINT) AS fiveplusattendances,
    CAST("NumberOfAttendancesAggregate" AS BIGINT) AS numberofattendancesaggregate,
    CAST("NumberMeetingTargetAggregate" AS BIGINT) AS numbermeetingtargetaggregate,
    CAST("NumberMeetingTargetEpisode" AS BIGINT) AS numbermeetingtargetepisode,
    "NumberMeetingTargetEpisodeQF" AS numbermeetingtargetepisodeqf,
    CAST("DischargeDestinationAdmissionToSame" AS BIGINT) AS dischargedestinationadmissiontosame,
    "DischargeDestinationAdmissionToSameQF" AS dischargedestinationadmissiontosameqf,
    CAST("DischargeDestinationOtherSpecialty" AS BIGINT) AS dischargedestinationotherspecialty,
    "DischargeDestinationOtherSpecialtyQF" AS dischargedestinationotherspecialtyqf,
    CAST("DischargeDestinationResidence" AS BIGINT) AS dischargedestinationresidence,
    "DischargeDestinationResidenceQF" AS dischargedestinationresidenceqf,
    CAST("DischargeDestinationTransfer" AS BIGINT) AS dischargedestinationtransfer,
    "DischargeDestinationTransferQF" AS dischargedestinationtransferqf,
    CAST("DischargeDestinationUnknown" AS BIGINT) AS dischargedestinationunknown,
    "DischargeDestinationUnknownQF" AS dischargedestinationunknownqf,
    CAST("AttendanceGreater8hrs" AS BIGINT) AS attendancegreater8hrs,
    "AttendanceGreater8hrsQF" AS attendancegreater8hrsqf,
    CAST("AttendanceGreater12hrs" AS BIGINT) AS attendancegreater12hrs,
    "AttendanceGreater12hrsQF" AS attendancegreater12hrsqf
FROM "public-health-scotland-monthly-accident-and-emergency-activity-and-waiting-times"
