-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No compact row identity was verified from the raw profile; rows are published as source observations and may include multiple cuts, measures, or suppressions from separate CKAN resources.
SELECT
    "resource_id",
    "resource_name",
    "Country" AS country,
    "CancerSiteICD10Code" AS cancersiteicd10code,
    "CancerSite" AS cancersite,
    "Sex" AS sex,
    "SexQF" AS sexqf,
    "Year" AS year,
    CAST("DeathsAgeUnder5" AS BIGINT) AS deathsageunder5,
    CAST("DeathsAge5To9" AS BIGINT) AS deathsage5to9,
    CAST("DeathsAge10To14" AS BIGINT) AS deathsage10to14,
    CAST("DeathsAge15To19" AS BIGINT) AS deathsage15to19,
    CAST("DeathsAge20To24" AS BIGINT) AS deathsage20to24,
    CAST("DeathsAge25To29" AS BIGINT) AS deathsage25to29,
    CAST("DeathsAge30To34" AS BIGINT) AS deathsage30to34,
    CAST("DeathsAge35To39" AS BIGINT) AS deathsage35to39,
    CAST("DeathsAge40To44" AS BIGINT) AS deathsage40to44,
    CAST("DeathsAge45To49" AS BIGINT) AS deathsage45to49,
    CAST("DeathsAge50To54" AS BIGINT) AS deathsage50to54,
    CAST("DeathsAge55To59" AS BIGINT) AS deathsage55to59,
    CAST("DeathsAge60To64" AS BIGINT) AS deathsage60to64,
    CAST("DeathsAge65To69" AS BIGINT) AS deathsage65to69,
    CAST("DeathsAge70To74" AS BIGINT) AS deathsage70to74,
    CAST("DeathsAge75To79" AS BIGINT) AS deathsage75to79,
    CAST("DeathsAge80To84" AS BIGINT) AS deathsage80to84,
    CAST("DeathsAge85To89" AS BIGINT) AS deathsage85to89,
    CAST("DeathsAge90AndOver" AS BIGINT) AS deathsage90andover,
    CAST("DeathsAllAges" AS BIGINT) AS deathsallages,
    CAST("MortalityRateAgeUnder5" AS DOUBLE) AS mortalityrateageunder5,
    CAST("MortalityRateAge5To9" AS DOUBLE) AS mortalityrateage5to9,
    CAST("MortalityRateAge10To14" AS DOUBLE) AS mortalityrateage10to14,
    CAST("MortalityRateAge15To19" AS DOUBLE) AS mortalityrateage15to19,
    CAST("MortalityRateAge20To24" AS DOUBLE) AS mortalityrateage20to24,
    CAST("MortalityRateAge25To29" AS DOUBLE) AS mortalityrateage25to29,
    CAST("MortalityRateAge30To34" AS DOUBLE) AS mortalityrateage30to34,
    CAST("MortalityRateAge35To39" AS DOUBLE) AS mortalityrateage35to39,
    CAST("MortalityRateAge40To44" AS DOUBLE) AS mortalityrateage40to44,
    CAST("MortalityRateAge45To49" AS DOUBLE) AS mortalityrateage45to49,
    CAST("MortalityRateAge50To54" AS DOUBLE) AS mortalityrateage50to54,
    CAST("MortalityRateAge55To59" AS DOUBLE) AS mortalityrateage55to59,
    CAST("MortalityRateAge60To64" AS DOUBLE) AS mortalityrateage60to64,
    CAST("MortalityRateAge65To69" AS DOUBLE) AS mortalityrateage65to69,
    CAST("MortalityRateAge70To74" AS DOUBLE) AS mortalityrateage70to74,
    CAST("MortalityRateAge75To79" AS DOUBLE) AS mortalityrateage75to79,
    CAST("MortalityRateAge80To84" AS DOUBLE) AS mortalityrateage80to84,
    CAST("MortalityRateAge85To89" AS DOUBLE) AS mortalityrateage85to89,
    CAST("MortalityRateAge90AndOver" AS DOUBLE) AS mortalityrateage90andover,
    CAST("CrudeRate" AS DOUBLE) AS cruderate,
    CAST("CrudeRateLower95pcConfidenceInterval" AS DOUBLE) AS cruderatelower95pcconfidenceinterval,
    CAST("CrudeRateUpper95pcConfidenceInterval" AS DOUBLE) AS cruderateupper95pcconfidenceinterval,
    CAST("EASR" AS DOUBLE) AS easr,
    CAST("EASRLower95pcConfidenceInterval" AS DOUBLE) AS easrlower95pcconfidenceinterval,
    "EASRLower95pcConfidenceIntervalQF" AS easrlower95pcconfidenceintervalqf,
    CAST("EASRUpper95pcConfidenceInterval" AS DOUBLE) AS easrupper95pcconfidenceinterval,
    "EASRUpper95pcConfidenceIntervalQF" AS easrupper95pcconfidenceintervalqf,
    CAST("WASR" AS DOUBLE) AS wasr,
    CAST("WASRLower95pcConfidenceInterval" AS DOUBLE) AS wasrlower95pcconfidenceinterval,
    "WASRLower95pcConfidenceIntervalQF" AS wasrlower95pcconfidenceintervalqf,
    CAST("WASRUpper95pcConfidenceInterval" AS DOUBLE) AS wasrupper95pcconfidenceinterval,
    "WASRUpper95pcConfidenceIntervalQF" AS wasrupper95pcconfidenceintervalqf,
    CAST("StandardisedMortalityRatio" AS DOUBLE) AS standardisedmortalityratio,
    "StandardisedMortalityRatioQF" AS standardisedmortalityratioqf,
    "Region" AS region,
    CAST("SMRLower95pcConfidenceInterval" AS DOUBLE) AS smrlower95pcconfidenceinterval,
    CAST("SMRUpper95pcConfidenceInterval" AS DOUBLE) AS smrupper95pcconfidenceinterval,
    "HB" AS hb,
    "CA" AS ca
FROM "public-health-scotland-cancer-mortality"
