-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No compact row identity was verified from the raw profile; rows are published as source observations and may include multiple cuts, measures, or suppressions from separate CKAN resources.
SELECT
    "resource_id",
    "resource_name",
    "HBR" AS hbr,
    "SchoolYear" AS schoolyear,
    CAST("PopulationEstAge5" AS BIGINT) AS populationestage5,
    CAST("TotalReviews" AS BIGINT) AS totalreviews,
    CAST("ValidReviews" AS BIGINT) AS validreviews,
    "CA" AS ca,
    "HBRQF" AS hbrqf,
    CAST("EpiUnderweight" AS BIGINT) AS epiunderweight,
    CAST("LCIEpiUnderweight" AS DOUBLE) AS lciepiunderweight,
    CAST("UCIEpiUnderweight" AS DOUBLE) AS uciepiunderweight,
    CAST("EpiHealthyWeight" AS BIGINT) AS epihealthyweight,
    CAST("LCIEpiHealthyWeight" AS DOUBLE) AS lciepihealthyweight,
    CAST("UCIEpiHealthyWeight" AS DOUBLE) AS uciepihealthyweight,
    CAST("EpiOverweight" AS BIGINT) AS epioverweight,
    CAST("LCIEpiOverweight" AS DOUBLE) AS lciepioverweight,
    CAST("UCIEpiOverweight" AS DOUBLE) AS uciepioverweight,
    CAST("EpiObese" AS BIGINT) AS epiobese,
    CAST("LCIEpiObese" AS DOUBLE) AS lciepiobese,
    CAST("UCIEpiObese" AS DOUBLE) AS uciepiobese,
    CAST("EpiOverweightAndObese" AS BIGINT) AS epioverweightandobese,
    CAST("LCIEpiOverweightAndObese" AS DOUBLE) AS lciepioverweightandobese,
    CAST("UCIEpiOverweightAndObese" AS DOUBLE) AS uciepioverweightandobese,
    "Sex" AS sex,
    "SIMD" AS simd,
    "SIMDQF" AS simdqf,
    "SIMDVersion" AS simdversion,
    CAST("ClinUnderweight" AS BIGINT) AS clinunderweight,
    CAST("LCIClinUnderweight" AS DOUBLE) AS lciclinunderweight,
    CAST("UCIClinUnderweight" AS DOUBLE) AS uciclinunderweight,
    CAST("ClinHealthyWeight" AS BIGINT) AS clinhealthyweight,
    CAST("LCIClinHealthyWeight" AS DOUBLE) AS lciclinhealthyweight,
    CAST("UCIClinHealthyWeight" AS DOUBLE) AS uciclinhealthyweight,
    CAST("ClinOverweight" AS BIGINT) AS clinoverweight,
    CAST("LCIClinOverweight" AS DOUBLE) AS lciclinoverweight,
    CAST("UCIClinOverweight" AS DOUBLE) AS uciclinoverweight,
    CAST("ClinObese" AS BIGINT) AS clinobese,
    CAST("LCIClinObese" AS DOUBLE) AS lciclinobese,
    CAST("UCIClinObese" AS DOUBLE) AS uciclinobese,
    CAST("ClinSeverelyObese" AS BIGINT) AS clinseverelyobese,
    CAST("LCIClinSeverelyObese" AS DOUBLE) AS lciclinseverelyobese,
    CAST("UCIClinSeverelyObese" AS DOUBLE) AS uciclinseverelyobese,
    CAST("ClinOverweightObeseAndSeverelyObese" AS BIGINT) AS clinoverweightobeseandseverelyobese,
    CAST("LCIClinOverweightObeseAndSeverelyObese" AS DOUBLE) AS lciclinoverweightobeseandseverelyobese,
    CAST("UCIClinOverweightObeseAndSeverelyObese" AS DOUBLE) AS uciclinoverweightobeseandseverelyobese,
    CAST("ClinObeseAndSeverelyObese" AS BIGINT) AS clinobeseandseverelyobese,
    CAST("LCIClinObeseAndSeverelyObese" AS DOUBLE) AS lciclinobeseandseverelyobese,
    CAST("UCIClinObeseAndSeverelyObese" AS DOUBLE) AS uciclinobeseandseverelyobese,
    "EthnicityGroup" AS ethnicitygroup
FROM "public-health-scotland-primary-1-body-mass-index-bmi-statistics"
