-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No compact row identity was verified from the raw profile; rows are published as source observations and may include multiple cuts, measures, or suppressions from separate CKAN resources.
SELECT
    "resource_id",
    "resource_name",
    "Country" AS country,
    "TimePeriod" AS timeperiod,
    strptime("TimePeriodStart", '%Y%m%d')::DATE AS timeperiodstart,
    strptime("TimePeriodEnd", '%Y%m%d')::DATE AS timeperiodend,
    "ScreeningChanges2020" AS screeningchanges2020,
    "PregnancyType" AS pregnancytype,
    CAST("TotalAB" AS BIGINT) AS totalab,
    CAST("ABU14WeeksEligibleCombined" AS BIGINT) AS abu14weekseligiblecombined,
    CAST("ABU14WeeksAnyCombinedResult" AS BIGINT) AS abu14weeksanycombinedresult,
    "ABU14WeeksCombinedResultForDSAndESPS" AS abu14weekscombinedresultfordsandesps,
    "ABU14WeeksCombinedResultForDSAndESPSQF" AS abu14weekscombinedresultfordsandespsqf,
    CAST("ABU14WeeksCombinedResultForDSOnly" AS BIGINT) AS abu14weekscombinedresultfordsonly,
    "ABU14WeeksCombinedResultESPSOnly" AS abu14weekscombinedresultespsonly,
    "ABU14WeeksCombinedResultESPSOnlyQF" AS abu14weekscombinedresultespsonlyqf,
    CAST("ABU20WeeksEligibleForFLScreening" AS BIGINT) AS abu20weekseligibleforflscreening,
    CAST("ABU20WeeksAnyCombinedResult" AS BIGINT) AS abu20weeksanycombinedresult,
    CAST("ABU20WeeksCombinedResultForDSOnly" AS BIGINT) AS abu20weekscombinedresultfordsonly,
    "ABU20WeeksCombinedResultForESPSOnly" AS abu20weekscombinedresultforespsonly,
    "ABU20WeeksCombinedResultForESPSOnlyQF" AS abu20weekscombinedresultforespsonlyqf,
    "ABU20WeeksCombinedResultForDSAndESPS" AS abu20weekscombinedresultfordsandesps,
    "ABU20WeeksCombinedResultForDSAndESPSQF" AS abu20weekscombinedresultfordsandespsqf,
    CAST("ABU20WeeksQuadrupleResultForDS" AS BIGINT) AS abu20weeksquadrupleresultfords,
    CAST("ABU20WeeksAnyCombinedOrQuadrupleResult" AS BIGINT) AS abu20weeksanycombinedorquadrupleresult,
    "FirstLineTestType" AS firstlinetesttype,
    "ConditionTested" AS conditiontested,
    "NumberOfScreeningResultsABU20Weeks" AS numberofscreeningresultsabu20weeks,
    "NumberOfScreeningResultsABU20WeeksQF" AS numberofscreeningresultsabu20weeksqf,
    "NumberOfHigherChanceResultsDS" AS numberofhigherchanceresultsds,
    "NumberOfHigherChanceResultsDSQF" AS numberofhigherchanceresultsdsqf,
    "NumberOfHigherChanceResultsESPS" AS numberofhigherchanceresultsesps,
    "NumberOfHigherChanceResultsESPSQF" AS numberofhigherchanceresultsespsqf,
    "NumberOfHigherChanceResultsDSAndESPS" AS numberofhigherchanceresultsdsandesps,
    "NumberOfHigherChanceResultsDSAndESPSQF" AS numberofhigherchanceresultsdsandespsqf,
    "NumberOfNoHigherChanceResults" AS numberofnohigherchanceresults,
    "NumberOfNoHigherChanceResultsQF" AS numberofnohigherchanceresultsqf,
    CAST("HigherChanceDSOnly" AS BIGINT) AS higherchancedsonly,
    "HigherChanceDSOnlyWithNIPT" AS higherchancedsonlywithnipt,
    "HigherChanceDSOnlyWithNIPTQF" AS higherchancedsonlywithniptqf,
    "HigherChanceESPSOnly" AS higherchanceespsonly,
    "HigherChanceESPSOnlyQF" AS higherchanceespsonlyqf,
    "HigherChanceESPSOnlyWithNIPT" AS higherchanceespsonlywithnipt,
    "HigherChanceESPSOnlyWithNIPTQF" AS higherchanceespsonlywithniptqf,
    "HigherChanceDualDSandESPS" AS higherchancedualdsandesps,
    "HigherChanceDualDSandESPSQF" AS higherchancedualdsandespsqf,
    "HigherChanceDualDSandESPSWithNIPT" AS higherchancedualdsandespswithnipt,
    "HigherChanceDualDSandESPSWithNIPTQF" AS higherchancedualdsandespswithniptqf,
    "SecondLineTestType" AS secondlinetesttype,
    "FirstLineHigherChanceResult" AS firstlinehigherchanceresult,
    "NumberOfWomenWithNIPTResult" AS numberofwomenwithniptresult,
    "NumberOfWomenWithNIPTResultQF" AS numberofwomenwithniptresultqf,
    "NumberOfHighChanceNIPTResultsDS" AS numberofhighchanceniptresultsds,
    "NumberOfHighChanceNIPTResultsDSQF" AS numberofhighchanceniptresultsdsqf,
    "NumberOfHighChanceNIPTResultsES" AS numberofhighchanceniptresultses,
    "NumberOfHighChanceNIPTResultsESQF" AS numberofhighchanceniptresultsesqf,
    "NumberOfHighChanceNIPTResultsPS" AS numberofhighchanceniptresultsps,
    "NumberOfHighChanceNIPTResultsPSQF" AS numberofhighchanceniptresultspsqf,
    "NumberOfHighChanceNIPTResultsMoreThanOneCondition" AS numberofhighchanceniptresultsmorethanonecondition,
    "NumberOfHighChanceNIPTResultsMoreThanOneConditionQF" AS numberofhighchanceniptresultsmorethanoneconditionqf,
    "NumberOfNoHighChanceNIPTResults" AS numberofnohighchanceniptresults,
    "NumberOfNoHighChanceNIPTResultsQF" AS numberofnohighchanceniptresultsqf,
    "NumberOfTestFailureNIPTResults" AS numberoftestfailureniptresults,
    "NumberOfTestFailureNIPTResultsQF" AS numberoftestfailureniptresultsqf
FROM "public-health-scotland-pregnancy-screening-for-down-s-syndrome-edwards-syndrome-and-patau-s-syndrome-in-scotland"
