-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "resource_id",
    "resource_name",
    "FinancialYear" AS financialyear,
    "HB" AS hb,
    CAST("PracticeCode" AS BIGINT) AS practicecode,
    "PracticeType" AS practicetype,
    "PracticeListSize" AS practicelistsize,
    "PracticeListSizeQF" AS practicelistsizeqf,
    CAST("GlobalSum" AS BIGINT) AS globalsum,
    "IncomeAndExpensesGuarantee" AS incomeandexpensesguarantee,
    "IncomeAndExpensesGuaranteeQF" AS incomeandexpensesguaranteeqf,
    "DirectEnhancedServices" AS directenhancedservices,
    "DirectEnhancedServicesQF" AS directenhancedservicesqf,
    "NationalEnhancedServices" AS nationalenhancedservices,
    "NationalEnhancedServicesQF" AS nationalenhancedservicesqf,
    "LocalEnhancedServices" AS localenhancedservices,
    "LocalEnhancedServicesQF" AS localenhancedservicesqf,
    "Professionalism" AS professionalism,
    "ProfessionalismQF" AS professionalismqf,
    "Premises" AS premises,
    "PremisesQF" AS premisesqf,
    "Seniority" AS seniority,
    "SeniorityQF" AS seniorityqf,
    "OtherPayments" AS otherpayments,
    "OtherPaymentsQF" AS otherpaymentsqf,
    "OptedOutServices" AS optedoutservices,
    "OptedOutServicesQF" AS optedoutservicesqf,
    "17CPayments" AS "17cpayments",
    "17CPaymentsQF" AS "17cpaymentsqf",
    "2CPayments" AS "2cpayments",
    "2CPaymentsQF" AS "2cpaymentsqf",
    CAST("TotalPayments" AS BIGINT) AS totalpayments,
    "DispensingDoctorPayments" AS dispensingdoctorpayments,
    "DispensingDoctorPaymentsQF" AS dispensingdoctorpaymentsqf,
    "CorrectionFactor" AS correctionfactor,
    "CorrectionFactorQF" AS correctionfactorqf,
    "QualityAndOutcomesFramework" AS qualityandoutcomesframework,
    "QualityAndOutcomesFrameworkQF" AS qualityandoutcomesframeworkqf,
    "QualityTransitionalArrangements" AS qualitytransitionalarrangements,
    "QualityTransitionalArrangementsQF" AS qualitytransitionalarrangementsqf,
    "QualityPayments" AS qualitypayments,
    "QualityPaymentsQF" AS qualitypaymentsqf,
    "CovidSupportPayments" AS covidsupportpayments,
    "CovidSupportPaymentsQF" AS covidsupportpaymentsqf,
    "EnhancedServiceEstimate" AS enhancedserviceestimate,
    "EnhancedServiceEstimateQF" AS enhancedserviceestimateqf,
    "TotalQualityArrangements" AS totalqualityarrangements,
    "TotalQualityArrangementsQF" AS totalqualityarrangementsqf
FROM "public-health-scotland-nhsscotland-payments-to-general-practice"
