-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No compact row identity was verified from the raw profile; rows are published as source observations and may include multiple cuts, measures, or suppressions from separate CKAN resources.
SELECT
    "resource_id",
    "resource_name",
    "FinancialYear" AS financialyear,
    "FinancialYearQF" AS financialyearqf,
    "AppointmentType" AS appointmenttype,
    "AppointmentTypeQF" AS appointmenttypeqf,
    "CA" AS ca,
    "CAQF" AS caqf,
    "Age" AS age,
    "AgeQF" AS ageqf,
    "Sex" AS sex,
    "SexQF" AS sexqf,
    CAST("Attendances" AS BIGINT) AS attendances,
    "AttendancesQF" AS attendancesqf,
    CAST("AttendancesRate" AS DOUBLE) AS attendancesrate,
    "AttendancesRateQF" AS attendancesrateqf,
    CAST("NewReturn" AS DOUBLE) AS newreturn,
    "NewReturnQF" AS newreturnqf,
    CAST("DNA" AS BIGINT) AS dna,
    "DNAQF" AS dnaqf,
    CAST("DNARate" AS DOUBLE) AS dnarate,
    "DNARateQF" AS dnarateqf,
    CAST("Patients" AS BIGINT) AS patients,
    "PatientsQF" AS patientsqf,
    CAST("PatientsRate" AS DOUBLE) AS patientsrate,
    "PatientsRateQF" AS patientsrateqf,
    "SIMD" AS simd,
    "SIMDQF" AS simdqf,
    "Specialty" AS specialty,
    "SpecialtyQF" AS specialtyqf,
    "SpecialtyName" AS specialtyname,
    "SpecialtyNameQF" AS specialtynameqf,
    "SpecialtyGrouping" AS specialtygrouping,
    "SpecialtyGroupingQF" AS specialtygroupingqf,
    "HB" AS hb,
    "HBQF" AS hbqf,
    "Location" AS location,
    "LocationQF" AS locationqf,
    "LocationName" AS locationname,
    "Address1" AS address1,
    "Address2" AS address2,
    "Address3" AS address3,
    "Address4" AS address4,
    "Postcode" AS postcode,
    strptime("StartDate", '%Y%m%d')::DATE AS startdate,
    strptime("EndDate", '%Y%m%d')::DATE AS enddate,
    "HSCP" AS hscp,
    "HSCPQF" AS hscpqf,
    "DataZone" AS datazone,
    "DataZoneQF" AS datazoneqf,
    "IntZone" AS intzone,
    "IntZoneQF" AS intzoneqf
FROM "public-health-scotland-annual-outpatient-activity"
