-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("Fiscal Year" AS BIGINT) AS fiscal_year,
    "Facility ID" AS facility_id,
    "Facility Name" AS facility_name,
    "Address" AS address,
    "City/Town" AS city_town,
    "State" AS state,
    "ZIP Code" AS zip_code,
    "County/Parish" AS county_parish,
    CAST("HAI-1 Achievement Threshold" AS DOUBLE) AS hai_1_achievement_threshold,
    CAST("HAI-1 Benchmark" AS DOUBLE) AS hai_1_benchmark,
    "HAI-1 Baseline Rate" AS hai_1_baseline_rate,
    "HAI-1 Performance Rate" AS hai_1_performance_rate,
    "HAI-1 Achievement Points" AS hai_1_achievement_points,
    "HAI-1 Improvement Points" AS hai_1_improvement_points,
    "HAI-1 Measure Score" AS hai_1_measure_score,
    CAST("HAI-2 Achievement Threshold" AS DOUBLE) AS hai_2_achievement_threshold,
    CAST("HAI-2 Benchmark" AS DOUBLE) AS hai_2_benchmark,
    "HAI-2 Baseline Rate" AS hai_2_baseline_rate,
    "HAI-2 Performance Rate" AS hai_2_performance_rate,
    "HAI-2 Achievement Points" AS hai_2_achievement_points,
    "HAI-2 Improvement Points" AS hai_2_improvement_points,
    "HAI-2 Measure Score" AS hai_2_measure_score,
    "Combined SSI Measure Score" AS combined_ssi_measure_score,
    CAST("HAI-3 Achievement Threshold" AS DOUBLE) AS hai_3_achievement_threshold,
    CAST("HAI-3 Benchmark" AS DOUBLE) AS hai_3_benchmark,
    "HAI-3 Baseline Rate" AS hai_3_baseline_rate,
    "HAI-3 Performance Rate" AS hai_3_performance_rate,
    "HAI-3 Achievement Points" AS hai_3_achievement_points,
    "HAI-3 Improvement Points" AS hai_3_improvement_points,
    "HAI-3 Measure Score" AS hai_3_measure_score,
    CAST("HAI-4 Achievement Threshold" AS DOUBLE) AS hai_4_achievement_threshold,
    CAST("HAI-4 Benchmark" AS DOUBLE) AS hai_4_benchmark,
    "HAI-4 Baseline Rate" AS hai_4_baseline_rate,
    "HAI-4 Performance Rate" AS hai_4_performance_rate,
    "HAI-4 Achievement Points" AS hai_4_achievement_points,
    "HAI-4 Improvement Points" AS hai_4_improvement_points,
    "HAI-4 Measure Score" AS hai_4_measure_score,
    CAST("HAI-5 Achievement Threshold" AS DOUBLE) AS hai_5_achievement_threshold,
    CAST("HAI-5 Benchmark" AS DOUBLE) AS hai_5_benchmark,
    "HAI-5 Baseline Rate" AS hai_5_baseline_rate,
    "HAI-5 Performance Rate" AS hai_5_performance_rate,
    "HAI-5 Achievement Points" AS hai_5_achievement_points,
    "HAI-5 Improvement Points" AS hai_5_improvement_points,
    "HAI-5 Measure Score" AS hai_5_measure_score,
    CAST("HAI-6 Achievement Threshold" AS DOUBLE) AS hai_6_achievement_threshold,
    CAST("HAI-6 Benchmark" AS DOUBLE) AS hai_6_benchmark,
    "HAI-6 Baseline Rate" AS hai_6_baseline_rate,
    "HAI-6 Performance Rate" AS hai_6_performance_rate,
    "HAI-6 Achievement Points" AS hai_6_achievement_points,
    "HAI-6 Improvement Points" AS hai_6_improvement_points,
    "HAI-6 Measure Score" AS hai_6_measure_score,
    CAST("SEP-1 Achievement Threshold" AS DOUBLE) AS sep_1_achievement_threshold,
    CAST("SEP-1 Benchmark" AS DOUBLE) AS sep_1_benchmark,
    "SEP-1 Baseline Rate" AS sep_1_baseline_rate,
    "SEP-1 Performance Rate" AS sep_1_performance_rate,
    "SEP-1 Achievement Points" AS sep_1_achievement_points,
    "SEP-1 Improvement Points" AS sep_1_improvement_points,
    "SEP-1 Measure Score" AS sep_1_measure_score
FROM "cms-dgmq-aat3"
