-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "ACO_ID" AS aco_id,
    "ACO_Name" AS aco_name,
    "Agree_Type" AS agree_type,
    CAST("Agreement_Period_Num" AS BIGINT) AS agreement_period_num,
    "Current_Start_Date" AS current_start_date,
    "Current_Track" AS current_track,
    "Risk_Model" AS risk_model,
    "Assign_Type" AS assign_type,
    CAST("SNF_Waiver" AS BIGINT) AS snf_waiver,
    CAST("N_AB" AS BIGINT) AS n_ab,
    CAST("Sav_rate" AS DOUBLE) AS sav_rate,
    CAST("MinSavPerc" AS DOUBLE) AS minsavperc,
    CAST("BnchmkMinExp" AS BIGINT) AS bnchmkminexp,
    CAST("GenSaveLoss" AS BIGINT) AS gensaveloss,
    "DisAdj" AS disadj,
    CAST("Impact_Mid_Year_Termination" AS BIGINT) AS impact_mid_year_termination,
    CAST("EarnSaveLoss" AS BIGINT) AS earnsaveloss,
    CAST("DisAffQual" AS BIGINT) AS disaffqual,
    CAST("Met_QPS" AS BIGINT) AS met_qps,
    "Met_AltQPS" AS met_altqps,
    CAST("Met_40pctl" AS BIGINT) AS met_40pctl,
    CAST("Met_Incentive" AS BIGINT) AS met_incentive,
    CAST("Met_FirstYear" AS BIGINT) AS met_firstyear,
    CAST("Report_WI" AS BIGINT) AS report_wi,
    CAST("Report_eCQM_CQM_MedicareCQM" AS BIGINT) AS report_ecqm_cqm_medicarecqm,
    CAST("Met_SSP_quality_reporting_requirements" AS BIGINT) AS met_ssp_quality_reporting_requirements,
    CAST("QualScore" AS DOUBLE) AS qualscore,
    CAST("Recvd40p" AS BIGINT) AS recvd40p,
    CAST("AIP" AS BIGINT) AS aip,
    "AIPBalance" AS aipbalance,
    "AIPRecoup" AS aiprecoup,
    "AIPOwe" AS aipowe,
    CAST("RegAdj" AS BIGINT) AS regadj,
    "PriorSavAdj" AS priorsavadj,
    "FinalAdjCat" AS finaladjcat,
    CAST("UpdatedBnchmk" AS BIGINT) AS updatedbnchmk,
    "Guardrail" AS guardrail,
    CAST("HistBnchmk" AS BIGINT) AS histbnchmk,
    CAST("ABtotBnchmk" AS BIGINT) AS abtotbnchmk,
    CAST("ABtotExp" AS BIGINT) AS abtotexp,
    CAST("FinalShareRate" AS DOUBLE) AS finalsharerate,
    CAST("ReducedSS" AS BIGINT) AS reducedss,
    "FinalLossRate" AS finallossrate,
    "Rev_Exp_Cat" AS rev_exp_cat,
    "Per_Capita_Exp_ALL_ESRD_BY1" AS per_capita_exp_all_esrd_by1,
    CAST("Per_Capita_Exp_ALL_DIS_BY1" AS BIGINT) AS per_capita_exp_all_dis_by1,
    CAST("Per_Capita_Exp_ALL_AGDU_BY1" AS BIGINT) AS per_capita_exp_all_agdu_by1,
    CAST("Per_Capita_Exp_ALL_AGND_BY1" AS BIGINT) AS per_capita_exp_all_agnd_by1,
    "Per_Capita_Exp_ALL_ESRD_BY2" AS per_capita_exp_all_esrd_by2,
    CAST("Per_Capita_Exp_ALL_DIS_BY2" AS BIGINT) AS per_capita_exp_all_dis_by2,
    CAST("Per_Capita_Exp_ALL_AGDU_BY2" AS BIGINT) AS per_capita_exp_all_agdu_by2,
    CAST("Per_Capita_Exp_ALL_AGND_BY2" AS BIGINT) AS per_capita_exp_all_agnd_by2,
    "Per_Capita_Exp_ALL_ESRD_BY3" AS per_capita_exp_all_esrd_by3,
    CAST("Per_Capita_Exp_ALL_DIS_BY3" AS BIGINT) AS per_capita_exp_all_dis_by3,
    CAST("Per_Capita_Exp_ALL_AGDU_BY3" AS BIGINT) AS per_capita_exp_all_agdu_by3,
    CAST("Per_Capita_Exp_ALL_AGND_BY3" AS BIGINT) AS per_capita_exp_all_agnd_by3,
    "Per_Capita_Exp_ALL_ESRD_PY" AS per_capita_exp_all_esrd_py,
    CAST("Per_Capita_Exp_ALL_DIS_PY" AS BIGINT) AS per_capita_exp_all_dis_py,
    CAST("Per_Capita_Exp_ALL_AGDU_PY" AS BIGINT) AS per_capita_exp_all_agdu_py,
    CAST("Per_Capita_Exp_ALL_AGND_PY" AS BIGINT) AS per_capita_exp_all_agnd_py,
    CAST("Per_Capita_Exp_TOTAL_PY" AS BIGINT) AS per_capita_exp_total_py,
    "CMS_HCC_RiskScore_ESRD_BY1" AS cms_hcc_riskscore_esrd_by1,
    CAST("CMS_HCC_RiskScore_DIS_BY1" AS DOUBLE) AS cms_hcc_riskscore_dis_by1,
    CAST("CMS_HCC_RiskScore_AGDU_BY1" AS DOUBLE) AS cms_hcc_riskscore_agdu_by1,
    CAST("CMS_HCC_RiskScore_AGND_BY1" AS DOUBLE) AS cms_hcc_riskscore_agnd_by1,
    "CMS_HCC_RiskScore_ESRD_BY2" AS cms_hcc_riskscore_esrd_by2,
    CAST("CMS_HCC_RiskScore_DIS_BY2" AS DOUBLE) AS cms_hcc_riskscore_dis_by2,
    CAST("CMS_HCC_RiskScore_AGDU_BY2" AS DOUBLE) AS cms_hcc_riskscore_agdu_by2,
    CAST("CMS_HCC_RiskScore_AGND_BY2" AS DOUBLE) AS cms_hcc_riskscore_agnd_by2,
    "CMS_HCC_RiskScore_ESRD_BY3" AS cms_hcc_riskscore_esrd_by3,
    CAST("CMS_HCC_RiskScore_DIS_BY3" AS DOUBLE) AS cms_hcc_riskscore_dis_by3,
    CAST("CMS_HCC_RiskScore_AGDU_BY3" AS DOUBLE) AS cms_hcc_riskscore_agdu_by3,
    CAST("CMS_HCC_RiskScore_AGND_BY3" AS DOUBLE) AS cms_hcc_riskscore_agnd_by3,
    "CMS_HCC_RiskScore_ESRD_PY" AS cms_hcc_riskscore_esrd_py,
    CAST("CMS_HCC_RiskScore_DIS_PY" AS DOUBLE) AS cms_hcc_riskscore_dis_py,
    CAST("CMS_HCC_RiskScore_AGDU_PY" AS DOUBLE) AS cms_hcc_riskscore_agdu_py,
    CAST("CMS_HCC_RiskScore_AGND_PY" AS DOUBLE) AS cms_hcc_riskscore_agnd_py,
    "Demog_RiskScore_ESRD_PY" AS demog_riskscore_esrd_py,
    CAST("Demog_RiskScore_DIS_PY" AS DOUBLE) AS demog_riskscore_dis_py,
    CAST("Demog_RiskScore_AGDU_PY" AS DOUBLE) AS demog_riskscore_agdu_py,
    CAST("Demog_RiskScore_AGND_PY" AS DOUBLE) AS demog_riskscore_agnd_py,
    "Demog_RiskScore_ESRD_BY3" AS demog_riskscore_esrd_by3,
    "Demog_RiskScore_DIS_BY3" AS demog_riskscore_dis_by3,
    "Demog_RiskScore_AGDU_BY3" AS demog_riskscore_agdu_by3,
    "Demog_RiskScore_AGND_BY3" AS demog_riskscore_agnd_by3,
    "RR_weight_ESRD_PY" AS rr_weight_esrd_py,
    CAST("RR_weight_DIS_PY" AS DOUBLE) AS rr_weight_dis_py,
    CAST("RR_weight_AGDU_PY" AS DOUBLE) AS rr_weight_agdu_py,
    CAST("RR_weight_AGND_PY" AS DOUBLE) AS rr_weight_agnd_py,
    "N_AB_Year_ESRD_BY3" AS n_ab_year_esrd_by3,
    CAST("N_AB_Year_DIS_BY3" AS BIGINT) AS n_ab_year_dis_by3,
    CAST("N_AB_Year_AGED_Dual_BY3" AS BIGINT) AS n_ab_year_aged_dual_by3,
    CAST("N_AB_Year_AGED_NonDual_BY3" AS BIGINT) AS n_ab_year_aged_nondual_by3,
    CAST("N_AB_Year_PY" AS BIGINT) AS n_ab_year_py,
    "N_AB_Year_ESRD_PY" AS n_ab_year_esrd_py,
    "N_AB_Year_DIS_PY" AS n_ab_year_dis_py,
    "N_AB_Year_AGED_Dual_PY" AS n_ab_year_aged_dual_py,
    "N_AB_Year_AGED_NonDual_PY" AS n_ab_year_aged_nondual_py,
    CAST("N_AB_Year_Dual_PY" AS BIGINT) AS n_ab_year_dual_py,
    CAST("N_AB_Year_NonDual_PY" AS BIGINT) AS n_ab_year_nondual_py,
    "N_Ben_VA_Only" AS n_ben_va_only,
    "N_Ben_CBA_Only" AS n_ben_cba_only,
    "N_Ben_CBA_and_VA" AS n_ben_cba_and_va,
    CAST("N_Ben_Age_0_64" AS BIGINT) AS n_ben_age_0_64,
    CAST("N_Ben_Age_65_74" AS BIGINT) AS n_ben_age_65_74,
    CAST("N_Ben_Age_75_84" AS BIGINT) AS n_ben_age_75_84,
    CAST("N_Ben_Age_85plus" AS BIGINT) AS n_ben_age_85plus,
    CAST("N_Ben_Female" AS BIGINT) AS n_ben_female,
    CAST("N_Ben_Male" AS BIGINT) AS n_ben_male,
    CAST("N_Ben_Race_White" AS BIGINT) AS n_ben_race_white,
    "N_Ben_Race_Black" AS n_ben_race_black,
    "N_Ben_Race_Asian" AS n_ben_race_asian,
    "N_Ben_Race_Hisp" AS n_ben_race_hisp,
    "N_Ben_Race_Native" AS n_ben_race_native,
    "N_Ben_Race_Other" AS n_ben_race_other,
    "N_Ben_Race_Unknown" AS n_ben_race_unknown,
    CAST("CapAnn_INP_All" AS BIGINT) AS capann_inp_all,
    CAST("CapAnn_INP_S_trm" AS BIGINT) AS capann_inp_s_trm,
    "CapAnn_INP_L_trm" AS capann_inp_l_trm,
    "CapAnn_INP_Rehab" AS capann_inp_rehab,
    "CapAnn_INP_Psych" AS capann_inp_psych,
    CAST("CapAnn_HSP" AS BIGINT) AS capann_hsp,
    CAST("CapAnn_SNF" AS BIGINT) AS capann_snf,
    CAST("CapAnn_OPD" AS BIGINT) AS capann_opd,
    CAST("CapAnn_PB" AS BIGINT) AS capann_pb,
    CAST("CapAnn_AmbPay" AS BIGINT) AS capann_ambpay,
    CAST("CapAnn_HHA" AS BIGINT) AS capann_hha,
    CAST("CapAnn_DME" AS BIGINT) AS capann_dme,
    CAST("ADM" AS BIGINT) AS adm,
    "ADM_S_Trm" AS adm_s_trm,
    "ADM_L_Trm" AS adm_l_trm,
    "ADM_Rehab" AS adm_rehab,
    "ADM_Psych" AS adm_psych,
    CAST("P_EDV_Vis" AS BIGINT) AS p_edv_vis,
    CAST("P_EDV_Vis_HOSP" AS BIGINT) AS p_edv_vis_hosp,
    CAST("P_CT_VIS" AS BIGINT) AS p_ct_vis,
    CAST("P_MRI_VIS" AS BIGINT) AS p_mri_vis,
    CAST("P_EM_Total" AS BIGINT) AS p_em_total,
    CAST("P_EM_PCP_Vis" AS BIGINT) AS p_em_pcp_vis,
    CAST("P_EM_SP_Vis" AS BIGINT) AS p_em_sp_vis,
    "P_Nurse_Vis" AS p_nurse_vis,
    "P_FQHC_RHC_Vis" AS p_fqhc_rhc_vis,
    CAST("P_SNF_ADM" AS BIGINT) AS p_snf_adm,
    CAST("SNF_LOS" AS BIGINT) AS snf_los,
    CAST("SNF_PayperStay" AS BIGINT) AS snf_payperstay,
    CAST("N_CAH" AS BIGINT) AS n_cah,
    CAST("N_FQHC" AS BIGINT) AS n_fqhc,
    CAST("N_RHC" AS BIGINT) AS n_rhc,
    CAST("N_ETA" AS BIGINT) AS n_eta,
    CAST("N_Hosp" AS BIGINT) AS n_hosp,
    CAST("N_Fac_Other" AS BIGINT) AS n_fac_other,
    CAST("N_PCP" AS BIGINT) AS n_pcp,
    CAST("N_Spec" AS BIGINT) AS n_spec,
    CAST("N_NP" AS BIGINT) AS n_np,
    CAST("N_PA" AS BIGINT) AS n_pa,
    CAST("N_CNS" AS BIGINT) AS n_cns,
    CAST("Perc_Dual" AS DOUBLE) AS perc_dual,
    "Perc_LTI" AS perc_lti,
    "CAHPS_1" AS cahps_1,
    "CAHPS_2" AS cahps_2,
    "CAHPS_3" AS cahps_3,
    "CAHPS_4" AS cahps_4,
    "CAHPS_5" AS cahps_5,
    "CAHPS_6" AS cahps_6,
    "CAHPS_7" AS cahps_7,
    "CAHPS_11" AS cahps_11,
    "CAHPS_9" AS cahps_9,
    "CAHPS_8" AS cahps_8,
    "Measure_479" AS measure_479,
    "Measure_484" AS measure_484,
    "QualityID_318" AS qualityid_318,
    "QualityID_110" AS qualityid_110,
    "QualityID_226" AS qualityid_226,
    "QualityID_134_WI" AS qualityid_134_wi,
    "QualityID_134_eCQM" AS qualityid_134_ecqm,
    "QualityID_134_MIPSCQM" AS qualityid_134_mipscqm,
    "QualityID_134_MedicareCQM" AS qualityid_134_medicarecqm,
    "QualityID_113" AS qualityid_113,
    "QualityID_112" AS qualityid_112,
    "QualityID_438" AS qualityid_438,
    "QualityID_370" AS qualityid_370,
    "QualityID_001_WI" AS qualityid_001_wi,
    "QualityID_001_eCQM" AS qualityid_001_ecqm,
    "QualityID_001_MIPSCQM" AS qualityid_001_mipscqm,
    "QualityID_001_MedicareCQM" AS qualityid_001_medicarecqm,
    "QualityID_236_WI" AS qualityid_236_wi,
    "QualityID_236_eCQM" AS qualityid_236_ecqm,
    "QualityID_236_MIPSCQM" AS qualityid_236_mipscqm,
    "QualityID_236_MedicareCQM" AS qualityid_236_medicarecqm
FROM "cms-73b2ce14-351d-40ac-90ba-ec9e1f5ba80c"
