-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No stable row identifier was verified in the raw profile; treat rows as source snapshot records, not entity-deduplicated facts.
SELECT
    "HBIPS-2 Measure Description" AS hbips_2_measure_description,
    CAST("N HBIPS-2 Overall Rate Per 1000" AS DOUBLE) AS n_hbips_2_overall_rate_per_1000,
    CAST("N HBIPS-2 Overall Num" AS DOUBLE) AS n_hbips_2_overall_num,
    CAST("N HBIPS-2 Overall Den" AS BIGINT) AS n_hbips_2_overall_den,
    "HBIPS-3 Measure Description" AS hbips_3_measure_description,
    CAST("N HBIPS-3 Overall Rate Per 1000" AS DOUBLE) AS n_hbips_3_overall_rate_per_1000,
    CAST("N HBIPS-3 Overall Num" AS DOUBLE) AS n_hbips_3_overall_num,
    CAST("N HBIPS-3 Overall Den" AS BIGINT) AS n_hbips_3_overall_den,
    "SMD Measure Description" AS smd_measure_description,
    CAST("N SMD %" AS BIGINT) AS n_smd,
    CAST("SMD Top 10%" AS BIGINT) AS smd_top_10,
    "SUB-2/-2a Measure Description" AS sub_2_2a_measure_description,
    CAST("N SUB-2 %" AS BIGINT) AS n_sub_2,
    CAST("SUB-2 Top 10%" AS BIGINT) AS sub_2_top_10,
    CAST("N SUB-2a %" AS BIGINT) AS n_sub_2a,
    CAST("SUB-2a Top 10%" AS BIGINT) AS sub_2a_top_10,
    "SUB-3/-3a Measure Description" AS sub_3_3a_measure_description,
    CAST("N SUB-3 %" AS BIGINT) AS n_sub_3,
    CAST("SUB-3 Top 10%" AS BIGINT) AS sub_3_top_10,
    CAST("N SUB-3a %" AS BIGINT) AS n_sub_3a,
    CAST("SUB-3a Top 10%" AS BIGINT) AS sub_3a_top_10,
    "TOB-3/-3a Measure Description" AS tob_3_3a_measure_description,
    CAST("N TOB-3 %" AS BIGINT) AS n_tob_3,
    CAST("TOB-3 Top 10%" AS BIGINT) AS tob_3_top_10,
    CAST("N TOB-3a %" AS BIGINT) AS n_tob_3a,
    CAST("TOB-3a Top 10%" AS BIGINT) AS tob_3a_top_10,
    "TR-1 Measure Description" AS tr_1_measure_description,
    CAST("N TR-1 %" AS BIGINT) AS n_tr_1,
    CAST("TR-1 Top 10%" AS BIGINT) AS tr_1_top_10,
    "Start Date" AS start_date,
    strptime("End Date", '%m/%d/%Y')::DATE AS end_date,
    "FAPH Measure Description" AS faph_measure_description,
    CAST("N FAPH-30 %" AS DOUBLE) AS n_faph_30,
    CAST("FAPH-30 Top 10%" AS BIGINT) AS faph_30_top_10,
    CAST("N FAPH-7 %" AS DOUBLE) AS n_faph_7,
    CAST("FAPH-7 Top 10%" AS DOUBLE) AS faph_7_top_10,
    "FAPH Measure Start Date" AS faph_measure_start_date,
    strptime("FAPH Measure End Date", '%m/%d/%Y')::DATE AS faph_measure_end_date,
    "MedCont Measure Description" AS medcont_measure_description,
    CAST("MedCont %" AS BIGINT) AS medcont,
    CAST("MedCont Top 10%" AS DOUBLE) AS medcont_top_10,
    "N MedCont Measure Start Date" AS n_medcont_measure_start_date,
    strptime("N MedCont Measure End Date", '%m/%d/%Y')::DATE AS n_medcont_measure_end_date,
    "READM-30-IPF Measure Desc" AS readm_30_ipf_measure_desc,
    CAST("READM-30-IPF National Rate" AS DOUBLE) AS readm_30_ipf_national_rate,
    CAST("N READM-30-IPF # IPFs Worse" AS BIGINT) AS n_readm_30_ipf_ipfs_worse,
    CAST("N READM-30-IPF # IPFs Same" AS BIGINT) AS n_readm_30_ipf_ipfs_same,
    CAST("N READM-30-IPF # IPFs Better" AS BIGINT) AS n_readm_30_ipf_ipfs_better,
    CAST("N READM-30-IPF # IPFs Too Few" AS BIGINT) AS n_readm_30_ipf_ipfs_too_few,
    "READM-30-IPF Start Date" AS readm_30_ipf_start_date,
    strptime("READM-30-IPF End Date", '%m/%d/%Y')::DATE AS readm_30_ipf_end_date,
    "IMM-2 Measure Description" AS imm_2_measure_description,
    CAST("N IMM-2 %" AS BIGINT) AS n_imm_2,
    CAST("IMM-2 Top 10%" AS BIGINT) AS imm_2_top_10,
    "Flu Season Start Date" AS flu_season_start_date,
    strptime("Flu Season End Date", '%m/%d/%Y')::DATE AS flu_season_end_date
FROM "cms-s5xg-sys6"
