-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "ESCO_name" AS esco_name,
    "Performance_period" AS performance_period,
    "ESCO_effective_date" AS esco_effective_date,
    "ESCO_end_date" AS esco_end_date,
    "LDO_indicator" AS ldo_indicator,
    "Prvdr_type_participant_non_owner" AS prvdr_type_participant_non_owner,
    CAST("Prvdr_type_participant_owner" AS BIGINT) AS prvdr_type_participant_owner,
    "Prvdr_type_provider_or_supplier" AS prvdr_type_provider_or_supplier,
    CAST("Num_prvdrs" AS BIGINT) AS num_prvdrs,
    CAST("N_dial_fac_attached" AS BIGINT) AS n_dial_fac_attached,
    CAST("Aligned_bene" AS BIGINT) AS aligned_bene,
    CAST("Age_grp_0_64" AS BIGINT) AS age_grp_0_64,
    CAST("Age_grp_65_74" AS BIGINT) AS age_grp_65_74,
    CAST("Age_grp_75_84" AS BIGINT) AS age_grp_75_84,
    CAST("Age_grp_85_plus" AS BIGINT) AS age_grp_85_plus,
    CAST("Male" AS BIGINT) AS male,
    CAST("Female" AS BIGINT) AS female,
    CAST("ICH_CAHPS_nephrologists_communication_and_caring" AS DOUBLE) AS ich_cahps_nephrologists_communication_and_caring,
    CAST("ICH_CAHPS_providing_information_to_patients" AS DOUBLE) AS ich_cahps_providing_information_to_patients,
    CAST("ICH_CAHPS_rating_of_dialysis_center" AS DOUBLE) AS ich_cahps_rating_of_dialysis_center,
    CAST("ICH_CAHPS_dialysis_center_care_and_operations" AS DOUBLE) AS ich_cahps_dialysis_center_care_and_operations,
    CAST("ICH_CAHPS_rating_of_dialysis_center_staff" AS DOUBLE) AS ich_cahps_rating_of_dialysis_center_staff,
    CAST("ICH_CAHPS_rating_of_kidney_doctors" AS DOUBLE) AS ich_cahps_rating_of_kidney_doctors,
    CAST("Advance_care_plan" AS DOUBLE) AS advance_care_plan,
    CAST("Depression_screen_rate" AS DOUBLE) AS depression_screen_rate,
    CAST("Diabetes_care_eye_exam" AS DOUBLE) AS diabetes_care_eye_exam,
    CAST("Diabetes_care_foot_exam" AS DOUBLE) AS diabetes_care_foot_exam,
    CAST("Falls_plan_of_care" AS DOUBLE) AS falls_plan_of_care,
    CAST("Falls_risk_assessment" AS DOUBLE) AS falls_risk_assessment,
    CAST("Falls_screening" AS DOUBLE) AS falls_screening,
    CAST("Influenza_immunization" AS DOUBLE) AS influenza_immunization,
    CAST("Medication_reconciliation" AS DOUBLE) AS medication_reconciliation,
    CAST("Pneumococcal_vaccination_status" AS DOUBLE) AS pneumococcal_vaccination_status,
    CAST("Tobacco_use_rate" AS DOUBLE) AS tobacco_use_rate,
    CAST("Standardized_mortality_ratio" AS DOUBLE) AS standardized_mortality_ratio,
    CAST("T_PPPW" AS DOUBLE) AS t_pppw,
    CAST("T_SWR" AS DOUBLE) AS t_swr,
    "Overall_TQS" AS overall_tqs,
    CAST("PBPY_exp_ESRD_only_BY1" AS DOUBLE) AS pbpy_exp_esrd_only_by1,
    CAST("PBPY_exp_age_dua_BY1" AS DOUBLE) AS pbpy_exp_age_dua_by1,
    CAST("PBPY_exp_age_non_dua_BY1" AS DOUBLE) AS pbpy_exp_age_non_dua_by1,
    CAST("PBPY_exp_disable_dua_BY1" AS DOUBLE) AS pbpy_exp_disable_dua_by1,
    CAST("PBPY_exp_disable_no_dua_BY1" AS DOUBLE) AS pbpy_exp_disable_no_dua_by1,
    CAST("PBPY_exp_ESRD_only_BY2" AS DOUBLE) AS pbpy_exp_esrd_only_by2,
    CAST("PBPY_exp_age_dua_BY2" AS DOUBLE) AS pbpy_exp_age_dua_by2,
    CAST("PBPY_exp_age_non_dua_BY2" AS DOUBLE) AS pbpy_exp_age_non_dua_by2,
    CAST("PBPY_exp_disable_dua_BY2" AS DOUBLE) AS pbpy_exp_disable_dua_by2,
    CAST("PBPY_exp_disable_no_dua_BY2" AS DOUBLE) AS pbpy_exp_disable_no_dua_by2,
    CAST("PBPY_exp_ESRD_only_BY3" AS DOUBLE) AS pbpy_exp_esrd_only_by3,
    CAST("PBPY_exp_age_dua_BY3" AS DOUBLE) AS pbpy_exp_age_dua_by3,
    CAST("PBPY_exp_age_non_dua_BY3" AS DOUBLE) AS pbpy_exp_age_non_dua_by3,
    CAST("PBPY_exp_disable_dua_BY3" AS DOUBLE) AS pbpy_exp_disable_dua_by3,
    CAST("PBPY_exp_disable_no_dua_BY3" AS DOUBLE) AS pbpy_exp_disable_no_dua_by3,
    CAST("Histbnchmk_ESRD_only_PY" AS DOUBLE) AS histbnchmk_esrd_only_py,
    CAST("Histbnchmk_age_dua_PY" AS DOUBLE) AS histbnchmk_age_dua_py,
    CAST("Histbnchmk_age_non_dua_PY" AS DOUBLE) AS histbnchmk_age_non_dua_py,
    CAST("Histbnchmk_disable_dua_PY" AS DOUBLE) AS histbnchmk_disable_dua_py,
    CAST("Histbnchmk_disable_non_dua_PY" AS DOUBLE) AS histbnchmk_disable_non_dua_py,
    CAST("Risk_rt_ESRD_only_PY" AS DOUBLE) AS risk_rt_esrd_only_py,
    CAST("Risk_rt_age_dua_PY" AS DOUBLE) AS risk_rt_age_dua_py,
    CAST("Risk_rt_age_non_dua_PY" AS DOUBLE) AS risk_rt_age_non_dua_py,
    CAST("Risk_rt_disable_dua_PY" AS DOUBLE) AS risk_rt_disable_dua_py,
    CAST("Risk_rt_disable_non_dua_PY" AS DOUBLE) AS risk_rt_disable_non_dua_py,
    CAST("Tol_benchmrk_exp_PY" AS DOUBLE) AS tol_benchmrk_exp_py,
    CAST("PBPY_exp_ESRD_only_PY" AS DOUBLE) AS pbpy_exp_esrd_only_py,
    CAST("PBPY_exp_age_dua_PY" AS DOUBLE) AS pbpy_exp_age_dua_py,
    CAST("PBPY_exp_age_non_dua_PY" AS DOUBLE) AS pbpy_exp_age_non_dua_py,
    CAST("PBPY_exp_disable_dua_PY" AS DOUBLE) AS pbpy_exp_disable_dua_py,
    CAST("PBPY_exp_disable_non_dua_PY" AS DOUBLE) AS pbpy_exp_disable_non_dua_py,
    CAST("Bene_yrs_ESRD_only_PY" AS DOUBLE) AS bene_yrs_esrd_only_py,
    CAST("Bene_yrs_age_dua_PY" AS DOUBLE) AS bene_yrs_age_dua_py,
    CAST("Bene_yrs_age_non_dua_PY" AS DOUBLE) AS bene_yrs_age_non_dua_py,
    CAST("Bene_yrs_disable_dua_PY" AS DOUBLE) AS bene_yrs_disable_dua_py,
    CAST("Bene_yrs_disable_non_dua_PY" AS DOUBLE) AS bene_yrs_disable_non_dua_py,
    CAST("Tol_bene_exp_PY" AS DOUBLE) AS tol_bene_exp_py,
    CAST("Align_bene_yrs" AS DOUBLE) AS align_bene_yrs,
    CAST("Min_sav_rate" AS DOUBLE) AS min_sav_rate,
    CAST("Min_los_rate" AS DOUBLE) AS min_los_rate,
    CAST("Min_savig_amt" AS DOUBLE) AS min_savig_amt,
    "Min_losses_amt" AS min_losses_amt,
    "Met_qscore" AS met_qscore,
    "Gen_sav" AS gen_sav,
    "Sav_rate" AS sav_rate
FROM "cms-7bd74bf4-e396-43a6-af12-42ffb31ee00b"
