-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("YEAR" AS BIGINT) AS year,
    "STATE" AS state,
    "BENE_GEO_CD" AS bene_geo_cd,
    CAST("BENES_MA_CNT" AS BIGINT) AS benes_ma_cnt,
    CAST("BENE_AVG_AGE" AS BIGINT) AS bene_avg_age,
    CAST("BENE_FEML_PCT" AS DOUBLE) AS bene_feml_pct,
    CAST("BENE_MALE_PCT" AS DOUBLE) AS bene_male_pct,
    "BENE_RACE_WHT_PCT" AS bene_race_wht_pct,
    "BENE_RACE_BLACK_PCT" AS bene_race_black_pct,
    "BENE_RACE_HSPNC_PCT" AS bene_race_hspnc_pct,
    "BENE_RACE_OTHR_PCT" AS bene_race_othr_pct,
    "BENE_DUAL_PCT" AS bene_dual_pct,
    CAST("BENES_IP_STAY_CNT" AS BIGINT) AS benes_ip_stay_cnt,
    CAST("BENES_IP_PCT" AS DOUBLE) AS benes_ip_pct,
    CAST("IP_STAYS_PER_1000_BENES" AS DOUBLE) AS ip_stays_per_1000_benes,
    CAST("IP_DAYS_PER_1000_BENES" AS DOUBLE) AS ip_days_per_1000_benes,
    "BENES_IRF_CNT" AS benes_irf_cnt,
    "BENES_IRF_PCT" AS benes_irf_pct,
    "IRF_STAYS_PER_1000_BENES" AS irf_stays_per_1000_benes,
    "IRF_DAYS_PER_1000_BENES" AS irf_days_per_1000_benes,
    "BENES_LTC_CNT" AS benes_ltc_cnt,
    "BENES_LTC_PCT" AS benes_ltc_pct,
    "LTC_STAYS_PER_1000_BENES" AS ltc_stays_per_1000_benes,
    "LTC_DAYS_PER_1000_BENES" AS ltc_days_per_1000_benes,
    "BENES_SNF_CNT" AS benes_snf_cnt,
    "BENES_SNF_PCT" AS benes_snf_pct,
    "SNF_STAYS_PER_1000_BENES" AS snf_stays_per_1000_benes,
    "SNF_DAYS_PER_1000_BENES" AS snf_days_per_1000_benes,
    CAST("BENES_EM_CNT" AS BIGINT) AS benes_em_cnt,
    CAST("BENES_EM_PCT" AS DOUBLE) AS benes_em_pct,
    CAST("EM_EVENTS_PER_1000_BENES" AS DOUBLE) AS em_events_per_1000_benes,
    CAST("BENES_PRCDRS_CNT" AS BIGINT) AS benes_prcdrs_cnt,
    CAST("BENES_PRCDRS_PCT" AS DOUBLE) AS benes_prcdrs_pct,
    CAST("PRCDRS_EVENTS_PER_1000_BENES" AS DOUBLE) AS prcdrs_events_per_1000_benes,
    CAST("BENES_TESTS_CNT" AS BIGINT) AS benes_tests_cnt,
    CAST("BENES_TESTS_PCT" AS DOUBLE) AS benes_tests_pct,
    CAST("TESTS_EVENTS_PER_1000_BENES" AS DOUBLE) AS tests_events_per_1000_benes,
    CAST("BENES_IMGNG_CNT" AS BIGINT) AS benes_imgng_cnt,
    CAST("BENES_IMGNG_PCT" AS DOUBLE) AS benes_imgng_pct,
    CAST("IMGNG_EVENTS_PER_1000_BENES" AS DOUBLE) AS imgng_events_per_1000_benes,
    CAST("BENES_DME_CNT" AS BIGINT) AS benes_dme_cnt,
    CAST("BENES_DME_PCT" AS DOUBLE) AS benes_dme_pct,
    CAST("DME_EVENTS_PER_1000_BENES" AS DOUBLE) AS dme_events_per_1000_benes,
    CAST("BENES_AMBLNC_CNT" AS BIGINT) AS benes_amblnc_cnt,
    CAST("BENES_AMBLNC_PCT" AS DOUBLE) AS benes_amblnc_pct,
    CAST("AMBLNC_EVENTS_PER_1000_BENES" AS DOUBLE) AS amblnc_events_per_1000_benes,
    CAST("BENES_TRTMNT_CNT" AS BIGINT) AS benes_trtmnt_cnt,
    CAST("BENES_TRTMNT_PCT" AS DOUBLE) AS benes_trtmnt_pct,
    CAST("TRTMNT_EVENTS_PER_1000_BENES" AS DOUBLE) AS trtmnt_events_per_1000_benes,
    "BENES_OP_DLYS_CNT" AS benes_op_dlys_cnt,
    "BENES_OP_DLYS_PCT" AS benes_op_dlys_pct,
    "OP_DLYS_VISITS_PER_1000_BENES" AS op_dlys_visits_per_1000_benes,
    "BENES_FQHC_RHC_CNT" AS benes_fqhc_rhc_cnt,
    "BENES_FQHC_RHC_PCT" AS benes_fqhc_rhc_pct,
    "FQHC_RHC_VISITS_PER_1000_BENES" AS fqhc_rhc_visits_per_1000_benes,
    CAST("BENES_OP_CNT" AS BIGINT) AS benes_op_cnt,
    CAST("BENES_OP_PCT" AS DOUBLE) AS benes_op_pct,
    CAST("OP_VISITS_PER_1000_BENES" AS DOUBLE) AS op_visits_per_1000_benes,
    CAST("BENES_ER_VISITS_CNT" AS BIGINT) AS benes_er_visits_cnt,
    CAST("BENES_ER_VISITS_PCT" AS DOUBLE) AS benes_er_visits_pct,
    CAST("ER_VISITS_PER_1000_BENES" AS DOUBLE) AS er_visits_per_1000_benes
FROM "cms-8e989bc0-2260-49a7-9c6d-8e9e10af7cea"
