-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No stable row identifier was verified in the raw profile; treat rows as source snapshot records, not entity-deduplicated facts.
SELECT
    CAST("Fiscal Year" AS BIGINT) AS fiscal_year,
    "Facility ID" AS facility_id,
    "Facility Name" AS facility_name,
    "Address" AS address,
    "City/Town" AS city_town,
    "State" AS state,
    "ZIP Code" AS zip_code,
    "County/Parish" AS county_parish,
    "Communication With Nurses Floor" AS communication_with_nurses_floor,
    "Communication With Nurses Achievement Threshold" AS communication_with_nurses_achievement_threshold,
    "Communication With Nurses Benchmark" AS communication_with_nurses_benchmark,
    "Communication With Nurses Baseline Rate" AS communication_with_nurses_baseline_rate,
    "Communication With Nurses Performance Rate" AS communication_with_nurses_performance_rate,
    "Communication With Nurses Achievement Points" AS communication_with_nurses_achievement_points,
    "Communication With Nurses Improvement Points" AS communication_with_nurses_improvement_points,
    "Communication With Nurses Dimension Score" AS communication_with_nurses_dimension_score,
    "Communication With Doctors Floor" AS communication_with_doctors_floor,
    "Communication With Doctors Achievement Threshold" AS communication_with_doctors_achievement_threshold,
    "Communication With Doctors Benchmark" AS communication_with_doctors_benchmark,
    "Communication With Doctors Baseline Rate" AS communication_with_doctors_baseline_rate,
    "Communication With Doctors Performance Rate" AS communication_with_doctors_performance_rate,
    "Communication With Doctors Achievement Points" AS communication_with_doctors_achievement_points,
    "Communication With Doctors Improvement Points" AS communication_with_doctors_improvement_points,
    "Communication With Doctors Dimension Score" AS communication_with_doctors_dimension_score,
    "Responsiveness Of Hospital Staff Floor" AS responsiveness_of_hospital_staff_floor,
    "Responsiveness Of Hospital Staff Achievement Threshold" AS responsiveness_of_hospital_staff_achievement_threshold,
    "Responsiveness Of Hospital Staff Benchmark" AS responsiveness_of_hospital_staff_benchmark,
    "Responsiveness Of Hospital Staff Baseline Rate" AS responsiveness_of_hospital_staff_baseline_rate,
    "Responsiveness Of Hospital Staff Performance Rate" AS responsiveness_of_hospital_staff_performance_rate,
    "Responsiveness Of Hospital Staff Achievement Points" AS responsiveness_of_hospital_staff_achievement_points,
    "Responsiveness Of Hospital Staff Improvement Points" AS responsiveness_of_hospital_staff_improvement_points,
    "Responsiveness Of Hospital Staff Dimension Score" AS responsiveness_of_hospital_staff_dimension_score,
    "Care Transition Floor" AS care_transition_floor,
    "Care Transition Achievement Threshold" AS care_transition_achievement_threshold,
    "Care Transition Benchmark" AS care_transition_benchmark,
    "Care Transition Baseline Rate" AS care_transition_baseline_rate,
    "Care Transition Performance Rate" AS care_transition_performance_rate,
    "Care Transition Achievement Points" AS care_transition_achievement_points,
    "Care Transition Improvement Points" AS care_transition_improvement_points,
    "Care Transition Dimension Score" AS care_transition_dimension_score,
    "Communication About Medicines Floor" AS communication_about_medicines_floor,
    "Communication About Medicines Achievement Threshold" AS communication_about_medicines_achievement_threshold,
    "Communication About Medicines Benchmark" AS communication_about_medicines_benchmark,
    "Communication About Medicines Baseline Rate" AS communication_about_medicines_baseline_rate,
    "Communication About Medicines Performance Rate" AS communication_about_medicines_performance_rate,
    "Communication About Medicines Achievement Points" AS communication_about_medicines_achievement_points,
    "Communication About Medicines Improvement Points" AS communication_about_medicines_improvement_points,
    "Communication About Medicines Dimension Score" AS communication_about_medicines_dimension_score,
    "Cleanliness And Quietness Of Hospital Environment Floor" AS cleanliness_and_quietness_of_hospital_environment_floor,
    "Cleanliness And Quietness Of Hospital Environment Achievement Threshold" AS cleanliness_and_quietness_of_hospital_environment_achievement_threshold,
    "Cleanliness And Quietness Of Hospital Environment Benchmark" AS cleanliness_and_quietness_of_hospital_environment_benchmark,
    "Cleanliness And Quietness Of Hospital Environment Baseline Rate" AS cleanliness_and_quietness_of_hospital_environment_baseline_rate,
    "Cleanliness And Quietness Of Hospital Environment Performance Rate" AS cleanliness_and_quietness_of_hospital_environment_performance_rate,
    "Cleanliness And Quietness Of Hospital Environment Achievement Points" AS cleanliness_and_quietness_of_hospital_environment_achievement_points,
    "Cleanliness And Quietness Of Hospital Environment Improvement Points" AS cleanliness_and_quietness_of_hospital_environment_improvement_points,
    "Cleanliness And Quietness Of Hospital Environment Dimension Score" AS cleanliness_and_quietness_of_hospital_environment_dimension_score,
    "Discharge Information Floor" AS discharge_information_floor,
    "Discharge Information Achievement Threshold" AS discharge_information_achievement_threshold,
    "Discharge Information Benchmark" AS discharge_information_benchmark,
    "Discharge Information Baseline Rate" AS discharge_information_baseline_rate,
    "Discharge Information Performance Rate" AS discharge_information_performance_rate,
    "Discharge Information Achievement Points" AS discharge_information_achievement_points,
    "Discharge Information Improvement Points" AS discharge_information_improvement_points,
    "Discharge Information Dimension Score" AS discharge_information_dimension_score,
    "Overall Rating Of Hospital Floor" AS overall_rating_of_hospital_floor,
    "Overall Rating Of Hospital Achievement Threshold" AS overall_rating_of_hospital_achievement_threshold,
    "Overall Rating Of Hospital Benchmark" AS overall_rating_of_hospital_benchmark,
    "Overall Rating Of Hospital Baseline Rate" AS overall_rating_of_hospital_baseline_rate,
    "Overall Rating Of Hospital Performance Rate" AS overall_rating_of_hospital_performance_rate,
    "Overall Rating Of Hospital Achievement Points" AS overall_rating_of_hospital_achievement_points,
    "Overall Rating Of Hospital Improvement Points" AS overall_rating_of_hospital_improvement_points,
    "Overall Rating Of Hospital Dimension Score" AS overall_rating_of_hospital_dimension_score,
    "Hcahps Base Score" AS hcahps_base_score,
    "Hcahps Consistency Score" AS hcahps_consistency_score
FROM "cms-avtz-f2ge"
