-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "State" AS state,
    "CMS Certification Number (CCN)" AS cms_certification_number_ccn,
    "Provider Name" AS provider_name,
    "Address" AS address,
    "City/Town" AS city_town,
    "ZIP Code" AS zip_code,
    "Telephone Number" AS telephone_number,
    "Type of Ownership" AS type_of_ownership,
    "Offers Nursing Care Services" AS offers_nursing_care_services,
    "Offers Physical Therapy Services" AS offers_physical_therapy_services,
    "Offers Occupational Therapy Services" AS offers_occupational_therapy_services,
    "Offers Speech Pathology Services" AS offers_speech_pathology_services,
    "Offers Medical Social Services" AS offers_medical_social_services,
    "Offers Home Health Aide Services" AS offers_home_health_aide_services,
    "Certification Date" AS certification_date,
    "Quality of patient care star rating" AS quality_of_patient_care_star_rating,
    "Footnote for quality of patient care star rating" AS footnote_for_quality_of_patient_care_star_rating,
    "Numerator for how often the home health team began their patients' care in a timely manner" AS numerator_for_how_often_the_home_health_team_began_their_patients_care_in_a_timely_manner,
    "Denominator for how often the home health team began their patients' care in a timely manner" AS denominator_for_how_often_the_home_health_team_began_their_patients_care_in_a_timely_manner,
    "How often the home health team began their patients' care in a timely manner" AS how_often_the_home_health_team_began_their_patients_care_in_a_timely_manner,
    "Footnote for how often the home health team began their patients' care in a timely manner" AS footnote_for_how_often_the_home_health_team_began_their_patients_care_in_a_timely_manner,
    "Numerator for how often the home health team determined whether patients received a flu shot for the current flu season" AS numerator_for_how_often_the_home_health_team_determined_whether_patients_received_a_flu_shot_for_the_current_flu_season,
    "Denominator for how often the home health team determined whether patients received a flu shot for the current flu season" AS denominator_for_how_often_the_home_health_team_determined_whether_patients_received_a_flu_shot_for_the_current_flu_season,
    "How often the home health team determined whether patients received a flu shot for the current flu season" AS how_often_the_home_health_team_determined_whether_patients_received_a_flu_shot_for_the_current_flu_season,
    "Footnote for how often the home health team determined whether patients received a flu shot for the current flu season" AS footnote_for_how_often_the_home_health_team_determined_whether_patients_received_a_flu_shot_for_the_current_flu_season,
    "Numerator for how often patients got better at walking or moving around" AS numerator_for_how_often_patients_got_better_at_walking_or_moving_around,
    "Denominator for how often patients got better at walking or moving around" AS denominator_for_how_often_patients_got_better_at_walking_or_moving_around,
    "How often patients got better at walking or moving around" AS how_often_patients_got_better_at_walking_or_moving_around,
    "Footnote for how often patients got better at walking or moving around" AS footnote_for_how_often_patients_got_better_at_walking_or_moving_around,
    "Numerator for how often patients got better at getting in and out of bed" AS numerator_for_how_often_patients_got_better_at_getting_in_and_out_of_bed,
    "Denominator for how often patients got better at getting in and out of bed" AS denominator_for_how_often_patients_got_better_at_getting_in_and_out_of_bed,
    "How often patients got better at getting in and out of bed" AS how_often_patients_got_better_at_getting_in_and_out_of_bed,
    "Footnote for how often patients got better at getting in and out of bed" AS footnote_for_how_often_patients_got_better_at_getting_in_and_out_of_bed,
    "Numerator for how often patients got better at bathing" AS numerator_for_how_often_patients_got_better_at_bathing,
    "Denominator for how often patients got better at bathing" AS denominator_for_how_often_patients_got_better_at_bathing,
    "How often patients got better at bathing" AS how_often_patients_got_better_at_bathing,
    "Footnote for how often patients got better at bathing" AS footnote_for_how_often_patients_got_better_at_bathing,
    "Numerator for how often patients' breathing improved" AS numerator_for_how_often_patients_breathing_improved,
    "Denominator for how often patients' breathing improved" AS denominator_for_how_often_patients_breathing_improved,
    "How often patients' breathing improved" AS how_often_patients_breathing_improved,
    "Footnote for how often patients' breathing improved" AS footnote_for_how_often_patients_breathing_improved,
    "Numerator for how often patients got better at taking their drugs correctly by mouth" AS numerator_for_how_often_patients_got_better_at_taking_their_drugs_correctly_by_mouth,
    "Denominator for how often patients got better at taking their drugs correctly by mouth" AS denominator_for_how_often_patients_got_better_at_taking_their_drugs_correctly_by_mouth,
    "How often patients got better at taking their drugs correctly by mouth" AS how_often_patients_got_better_at_taking_their_drugs_correctly_by_mouth,
    "Footnote for how often patients got better at taking their drugs correctly by mouth" AS footnote_for_how_often_patients_got_better_at_taking_their_drugs_correctly_by_mouth,
    "Numerator for Changes in skin integrity post-acute care: pressure ulcer/injury" AS numerator_for_changes_in_skin_integrity_post_acute_care_pressure_ulcer_injury,
    "Denominator for Changes in skin integrity post-acute care: pressure ulcer/injury" AS denominator_for_changes_in_skin_integrity_post_acute_care_pressure_ulcer_injury,
    "Changes in skin integrity post-acute care: pressure ulcer/injury" AS changes_in_skin_integrity_post_acute_care_pressure_ulcer_injury,
    "Footnote Changes in skin integrity post-acute care: pressure ulcer/injury" AS footnote_changes_in_skin_integrity_post_acute_care_pressure_ulcer_injury,
    "Numerator for how often physician-recommended actions to address medication issues were completely timely" AS numerator_for_how_often_physician_recommended_actions_to_address_medication_issues_were_completely_timely,
    "Denominator for how often physician-recommended actions to address medication issues were completely timely" AS denominator_for_how_often_physician_recommended_actions_to_address_medication_issues_were_completely_timely,
    "How often physician-recommended actions to address medication issues were completely timely" AS how_often_physician_recommended_actions_to_address_medication_issues_were_completely_timely,
    "Footnote for how often physician-recommended actions to address medication issues were completely timely" AS footnote_for_how_often_physician_recommended_actions_to_address_medication_issues_were_completely_timely,
    "Numerator for Percent of Residents Experiencing One or More Falls with Major Injury" AS numerator_for_percent_of_residents_experiencing_one_or_more_falls_with_major_injury,
    "Denominator for Percent of Residents Experiencing One or More Falls with Major Injury" AS denominator_for_percent_of_residents_experiencing_one_or_more_falls_with_major_injury,
    "Percent of Residents Experiencing One or More Falls with Major Injury" AS percent_of_residents_experiencing_one_or_more_falls_with_major_injury,
    "Footnote for Percent of Residents Experiencing One or More Falls with Major Injury" AS footnote_for_percent_of_residents_experiencing_one_or_more_falls_with_major_injury,
    "Numerator for Discharge Function Score" AS numerator_for_discharge_function_score,
    "Denominator for Discharge Function Score" AS denominator_for_discharge_function_score,
    "Discharge Function Score" AS discharge_function_score,
    "Footnote for Discharge Function Score" AS footnote_for_discharge_function_score,
    "Numerator for Transfer of Health Information to the Provider" AS numerator_for_transfer_of_health_information_to_the_provider,
    "Denominator for Transfer of Health Information to the Provider" AS denominator_for_transfer_of_health_information_to_the_provider,
    "Transfer of Health Information to the Provider" AS transfer_of_health_information_to_the_provider,
    "Footnote for Transfer of Health Information to the Provider" AS footnote_for_transfer_of_health_information_to_the_provider,
    "Numerator for Transfer of Health Information to the Patient" AS numerator_for_transfer_of_health_information_to_the_patient,
    "Denominator for Transfer of Health Information to the Patient" AS denominator_for_transfer_of_health_information_to_the_patient,
    "Transfer of Health Information to the Patient" AS transfer_of_health_information_to_the_patient,
    "Footnote for Transfer of Health Information to the Patient" AS footnote_for_transfer_of_health_information_to_the_patient,
    "DTC Numerator" AS dtc_numerator,
    "DTC Denominator" AS dtc_denominator,
    "DTC Observed Rate" AS dtc_observed_rate,
    "DTC Risk-Standardized Rate" AS dtc_risk_standardized_rate,
    "DTC Risk-Standardized Rate (Lower Limit)" AS dtc_risk_standardized_rate_lower_limit,
    "DTC Risk-Standardized Rate (Upper Limit)" AS dtc_risk_standardized_rate_upper_limit,
    "DTC Performance Categorization" AS dtc_performance_categorization,
    "Footnote for DTC Risk-Standardized Rate" AS footnote_for_dtc_risk_standardized_rate,
    "PPR Numerator" AS ppr_numerator,
    "PPR Denominator" AS ppr_denominator,
    "PPR Observed Rate" AS ppr_observed_rate,
    "PPR Risk-Standardized Rate" AS ppr_risk_standardized_rate,
    "PPR Risk-Standardized Rate (Lower Limit)" AS ppr_risk_standardized_rate_lower_limit,
    "PPR Risk-Standardized Rate (Upper Limit)" AS ppr_risk_standardized_rate_upper_limit,
    "PPR Performance Categorization" AS ppr_performance_categorization,
    "Footnote for PPR Risk-Standardized Rate" AS footnote_for_ppr_risk_standardized_rate,
    "PPH Numerator" AS pph_numerator,
    "PPH Denominator" AS pph_denominator,
    "PPH Observed Rate" AS pph_observed_rate,
    "PPH Risk-Standardized Rate" AS pph_risk_standardized_rate,
    "PPH Risk-Standardized Rate (Lower Limit)" AS pph_risk_standardized_rate_lower_limit,
    "PPH Risk-Standardized Rate (Upper Limit)" AS pph_risk_standardized_rate_upper_limit,
    "PPH Performance Categorization" AS pph_performance_categorization,
    "Footnote for PPH Risk-Standardized Rate" AS footnote_for_pph_risk_standardized_rate,
    "How much Medicare spends on an episode of care at this agency, compared to Medicare spending across all agencies nationally" AS how_much_medicare_spends_on_an_episode_of_care_at_this_agency_compared_to_medicare_spending_across_all_agencies_nationally,
    "Footnote for how much Medicare spends on an episode of care at this agency, compared to Medicare spending across all agencies nationally" AS footnote_for_how_much_medicare_spends_on_an_episode_of_care_at_this_agency_compared_to_medicare_spending_across_all_agencies_nationally,
    "No. of episodes to calc how much Medicare spends per episode of care at agency, compared to spending at all agencies (national)" AS no_of_episodes_to_calc_how_much_medicare_spends_per_episode_of_care_at_agency_compared_to_spending_at_all_agencies_national
FROM "cms-6jpm-sxkc"
