-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "State" AS state,
    CAST("Survival- Better Than Expected (STATE)" AS BIGINT) AS survival_better_than_expected_state,
    CAST("Survival- As Expected (STATE)" AS BIGINT) AS survival_as_expected_state,
    CAST("Survival- Worse Than Expected (STATE)" AS BIGINT) AS survival_worse_than_expected_state,
    CAST("Hospitalizations- Better Than Expected (STATE)" AS BIGINT) AS hospitalizations_better_than_expected_state,
    CAST("Hospitalizations- As Expected (STATE)" AS BIGINT) AS hospitalizations_as_expected_state,
    CAST("Hospitalizations- Worse Than Expected (STATE)" AS BIGINT) AS hospitalizations_worse_than_expected_state,
    CAST("Hospital Readmission - Better Than Expected (STATE)" AS BIGINT) AS hospital_readmission_better_than_expected_state,
    CAST("Hospital Readmission - As Expected (STATE)" AS BIGINT) AS hospital_readmission_as_expected_state,
    CAST("Hospital  Readmission - Worse Than Expected (STATE)" AS BIGINT) AS hospital_readmission_worse_than_expected_state,
    CAST("Transfusions- Better than expected (STATE)" AS BIGINT) AS transfusions_better_than_expected_state,
    CAST("Transfusions- As expected (STATE)" AS BIGINT) AS transfusions_as_expected_state,
    CAST("Transfusions- Worse than expected (STATE)" AS BIGINT) AS transfusions_worse_than_expected_state,
    CAST("Infection- Better than expected (STATE)" AS DOUBLE) AS infection_better_than_expected_state,
    CAST("Infection- As expected (STATE)" AS DOUBLE) AS infection_as_expected_state,
    CAST("Infection- Worse than expected (STATE)" AS DOUBLE) AS infection_worse_than_expected_state,
    "Percentage of adult HD patients with Kt/V>=1.2" AS percentage_of_adult_hd_patients_with_kt_v_1_2,
    "Percentage Of Adult PD Patients With Kt/V>=1.7" AS percentage_of_adult_pd_patients_with_kt_v_1_7,
    "Percentage Of Pediatric HD Patients With Kt/V>=1.2" AS percentage_of_pediatric_hd_patients_with_kt_v_1_2,
    "Percentage Of Pediatric PD Patients With Kt/V>=1.8" AS percentage_of_pediatric_pd_patients_with_kt_v_1_8,
    "Percentage Of Pediatric HD Patients With nPCR In Use" AS percentage_of_pediatric_hd_patients_with_npcr_in_use,
    CAST("Fistula Rate - Better Than Expected (STATE)" AS BIGINT) AS fistula_rate_better_than_expected_state,
    CAST("Fistula Rate - As Expected (STATE)" AS BIGINT) AS fistula_rate_as_expected_state,
    CAST("Fistula Rate - Worse Than Expected (STATE)" AS BIGINT) AS fistula_rate_worse_than_expected_state,
    "Percentage Of Adult Patients With Long Term Catheter In Use" AS percentage_of_adult_patients_with_long_term_catheter_in_use,
    "Percentage Of Adult Patients With Hypercalcemia (Serum Calcium Greater Than 10.2 Mg/dL)" AS percentage_of_adult_patients_with_hypercalcemia_serum_calcium_greater_than_10_2_mg_dl,
    "Percentage Of Adult Patients With Serum Phosphorus Less Than 3.5 Mg/dL" AS percentage_of_adult_patients_with_serum_phosphorus_less_than_3_5_mg_dl,
    "Percentage Of Adult Patients With Serum Phosphorus Between 3.5-4.5 Mg/dL" AS percentage_of_adult_patients_with_serum_phosphorus_between_3_5_4_5_mg_dl,
    "Percentage Of Adult Patients With Serum Phosphorus Between 4.6-5.5 Mg/dL" AS percentage_of_adult_patients_with_serum_phosphorus_between_4_6_5_5_mg_dl,
    "Percentage Of Adult Patients With Serum Phosphorus Between 5.6-7.0 Mg/dL" AS percentage_of_adult_patients_with_serum_phosphorus_between_5_6_7_0_mg_dl,
    "Percentage Of Adult Patients With Serum Phosphorus Greater Than 7.0 Mg/dL" AS percentage_of_adult_patients_with_serum_phosphorus_greater_than_7_0_mg_dl,
    CAST("Incident Patients Transplant Waitlisting- Better Than Expected (STATE)" AS BIGINT) AS incident_patients_transplant_waitlisting_better_than_expected_state,
    CAST("Incident Patients Transplant Waitlisting - As Expected (STATE)" AS BIGINT) AS incident_patients_transplant_waitlisting_as_expected_state,
    CAST("Incident Patients Transplant Waitlisting - Worse Than Expected (STATE)" AS BIGINT) AS incident_patients_transplant_waitlisting_worse_than_expected_state,
    CAST("Prevalent Patients Transplant Waitlisting- Better Than Expected (STATE)" AS BIGINT) AS prevalent_patients_transplant_waitlisting_better_than_expected_state,
    CAST("Prevalent Patients Transplant Waitlisting - As Expected (STATE)" AS BIGINT) AS prevalent_patients_transplant_waitlisting_as_expected_state,
    CAST("Prevalent Patients Transplant Waitlisting - Worse Than Expected (STATE)" AS BIGINT) AS prevalent_patients_transplant_waitlisting_worse_than_expected_state,
    "Healthcare worker COVID-19 vaccination adherence percentage (STATE)" AS healthcare_worker_covid_19_vaccination_adherence_percentage_state,
    "Percentage Of Patients With Hgb<10 g/dL (STATE)" AS percentage_of_patients_with_hgb_10_g_dl_state,
    "Percentage of patients with Hgb>12 g/dL (STATE)" AS percentage_of_patients_with_hgb_12_g_dl_state,
    CAST("SEDR - Better Than Expected (STATE)" AS BIGINT) AS sedr_better_than_expected_state,
    CAST("SEDR - As Expected (STATE)" AS BIGINT) AS sedr_as_expected_state,
    CAST("SEDR - Worse Than Expected (STATE)" AS BIGINT) AS sedr_worse_than_expected_state,
    CAST("ED30 - Better Than Expected (STATE)" AS BIGINT) AS ed30_better_than_expected_state,
    CAST("ED30 - As Expected (STATE)" AS BIGINT) AS ed30_as_expected_state,
    CAST("ED30 - Worse Than Expected (STATE)" AS BIGINT) AS ed30_worse_than_expected_state,
    CAST("N FOR SMSR CATEGORY 1: SMSR-Better than expected (State)" AS BIGINT) AS n_for_smsr_category_1_smsr_better_than_expected_state,
    CAST("N FOR SMSR CATEGORY 2: SMSR-As Expected (State)" AS BIGINT) AS n_for_smsr_category_2_smsr_as_expected_state,
    CAST("N FOR SMSR CATEGORY 3: SMSR-Worse than expected (State)" AS BIGINT) AS n_for_smsr_category_3_smsr_worse_than_expected_state
FROM "cms-2fpu-cgbb"
