-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "Facility ID" AS facility_id,
    "Facility Name" AS facility_name,
    "Address" AS address,
    "City/Town" AS city_town,
    "State" AS state,
    "ZIP Code" AS zip_code,
    "County/Parish" AS county_parish,
    "HBIPS-2 Measure Description" AS hbips_2_measure_description,
    "HBIPS-2 Overall Rate Per 1000" AS hbips_2_overall_rate_per_1000,
    "HBIPS-2 Overall Num" AS hbips_2_overall_num,
    "HBIPS-2 Overall Den" AS hbips_2_overall_den,
    "HBIPS-2 Overall Footnote" AS hbips_2_overall_footnote,
    "HBIPS-3 Measure Description" AS hbips_3_measure_description,
    "HBIPS-3 Overall Rate Per 1000" AS hbips_3_overall_rate_per_1000,
    "HBIPS-3 Overall Num" AS hbips_3_overall_num,
    "HBIPS-3 Overall Den" AS hbips_3_overall_den,
    "HBIPS-3 Overall Footnote" AS hbips_3_overall_footnote,
    "SMD Measure Description" AS smd_measure_description,
    "SMD %" AS smd,
    "SMD Denominator" AS smd_denominator,
    "SMD Footnote" AS smd_footnote,
    "SUB-2/-2a Measure Description" AS sub_2_2a_measure_description,
    "SUB-2 %" AS sub_2,
    "SUB-2 Denominator" AS sub_2_denominator,
    "SUB-2 Footnote" AS sub_2_footnote,
    "SUB-2a %" AS sub_2a,
    "SUB-2a Denominator" AS sub_2a_denominator,
    "SUB-2a Footnote" AS sub_2a_footnote,
    "SUB-3/-3a Measure Description" AS sub_3_3a_measure_description,
    "SUB-3 %" AS sub_3,
    "SUB-3 Denominator" AS sub_3_denominator,
    "SUB-3 Footnote" AS sub_3_footnote,
    "SUB-3a %" AS sub_3a,
    "SUB-3a Denominator" AS sub_3a_denominator,
    "SUB-3a Footnote" AS sub_3a_footnote,
    "TOB-3/-3a Measure Description" AS tob_3_3a_measure_description,
    "TOB-3 %" AS tob_3,
    "TOB-3 Denominator" AS tob_3_denominator,
    "TOB-3 Footnote" AS tob_3_footnote,
    "TOB-3a %" AS tob_3a,
    "TOB-3a Denominator" AS tob_3a_denominator,
    "TOB-3a Footnote" AS tob_3a_footnote,
    "TR-1 Measure Description" AS tr_1_measure_description,
    "TR-1 %" AS tr_1,
    "TR-1 Denominator" AS tr_1_denominator,
    "TR-1 Footnote" AS tr_1_footnote,
    "Start Date" AS start_date,
    strptime("End Date", '%m/%d/%Y')::DATE AS end_date,
    "FAPH Measure Description" AS faph_measure_description,
    "FAPH-30 %" AS faph_30,
    "FAPH-30 Denominator" AS faph_30_denominator,
    "FAPH-30 Footnote" AS faph_30_footnote,
    "FAPH-7 %" AS faph_7,
    "FAPH-7 Denominator" AS faph_7_denominator,
    "FAPH-7 Footnote" AS faph_7_footnote,
    "FAPH Measure Start Date" AS faph_measure_start_date,
    strptime("FAPH Measure End Date", '%m/%d/%Y')::DATE AS faph_measure_end_date,
    "MedCont Measure Desc" AS medcont_measure_desc,
    "MedCont %" AS medcont,
    "MedCont Denominator" AS medcont_denominator,
    "MedCont Footnote" AS medcont_footnote,
    "MedCont Measure Start Date" AS medcont_measure_start_date,
    strptime("MedCont Measure End Date", '%m/%d/%Y')::DATE AS medcont_measure_end_date,
    "READM-30-IPF Measure Desc" AS readm_30_ipf_measure_desc,
    "READM-30-IPF Category" AS readm_30_ipf_category,
    "READM-30-IPF Denominator" AS readm_30_ipf_denominator,
    "READM-30-IPF Rate" AS readm_30_ipf_rate,
    "READM-30-IPF Lower Estimate" AS readm_30_ipf_lower_estimate,
    "READM-30-IPF Higher Estimate" AS readm_30_ipf_higher_estimate,
    "READM-30-IPF Footnote" AS readm_30_ipf_footnote,
    "READM-30-IPF Start Date" AS readm_30_ipf_start_date,
    strptime("READM-30-IPF End Date", '%m/%d/%Y')::DATE AS readm_30_ipf_end_date,
    "IMM-2 Measure Description" AS imm_2_measure_description,
    "IMM-2 %" AS imm_2,
    "IMM-2 Denominator" AS imm_2_denominator,
    "IMM-2 Footnote" AS imm_2_footnote,
    "Flu Season Start Date" AS flu_season_start_date,
    strptime("Flu Season End Date", '%m/%d/%Y')::DATE AS flu_season_end_date
FROM "cms-q9vs-r7wp"
