-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "State or Nation" AS state_or_nation,
    CAST("Overall Rating" AS DOUBLE) AS overall_rating,
    CAST("Health Inspection Rating" AS DOUBLE) AS health_inspection_rating,
    "QM Rating" AS qm_rating,
    CAST("Staffing Rating" AS DOUBLE) AS staffing_rating,
    CAST("Cycle 1 Total Number of Health Deficiencies" AS DOUBLE) AS cycle_1_total_number_of_health_deficiencies,
    CAST("Cycle 1 Total Number of Fire Safety Deficiencies" AS DOUBLE) AS cycle_1_total_number_of_fire_safety_deficiencies,
    CAST("Cycle 2 Total Number of Health Deficiencies" AS DOUBLE) AS cycle_2_total_number_of_health_deficiencies,
    CAST("Cycle 2 Total Number of Fire Safety Deficiencies" AS DOUBLE) AS cycle_2_total_number_of_fire_safety_deficiencies,
    CAST("Cycle 3 Total Number of Health Deficiencies" AS DOUBLE) AS cycle_3_total_number_of_health_deficiencies,
    CAST("Cycle 3 Total Number of Fire Safety Deficiencies" AS DOUBLE) AS cycle_3_total_number_of_fire_safety_deficiencies,
    CAST("Average Number of Residents per Day" AS DOUBLE) AS average_number_of_residents_per_day,
    CAST("Reported Nurse Aide Staffing Hours per Resident per Day" AS DOUBLE) AS reported_nurse_aide_staffing_hours_per_resident_per_day,
    CAST("Reported LPN Staffing Hours per Resident per Day" AS DOUBLE) AS reported_lpn_staffing_hours_per_resident_per_day,
    CAST("Reported RN Staffing Hours per Resident per Day" AS DOUBLE) AS reported_rn_staffing_hours_per_resident_per_day,
    CAST("Reported Licensed Staffing Hours per Resident per Day" AS DOUBLE) AS reported_licensed_staffing_hours_per_resident_per_day,
    CAST("Reported Total Nurse Staffing Hours per Resident per Day" AS DOUBLE) AS reported_total_nurse_staffing_hours_per_resident_per_day,
    CAST("Total number of nurse staff hours per resident per day on the weekend" AS DOUBLE) AS total_num_nurse_staff_hours_res_day_on_weekend,
    CAST("Registered Nurse hours per resident per day on the weekend" AS DOUBLE) AS registered_nurse_hours_per_resident_per_day_on_the_weekend,
    CAST("Reported Physical Therapist Staffing Hours per Resident Per Day" AS DOUBLE) AS reported_physical_therapist_staffing_hours_per_resident_per_day,
    CAST("Total nursing staff turnover" AS DOUBLE) AS total_nursing_staff_turnover,
    CAST("Registered Nurse turnover" AS DOUBLE) AS registered_nurse_turnover,
    "Number of administrators who have left the nursing home" AS number_of_administrators_who_have_left_the_nursing_home,
    CAST("Nursing Case-Mix Index" AS DOUBLE) AS nursing_case_mix_index,
    CAST("Case-Mix RN Staffing Hours per Resident per Day" AS DOUBLE) AS case_mix_rn_staffing_hours_per_resident_per_day,
    CAST("Case-Mix Total Nurse Staffing Hours per Resident per Day" AS DOUBLE) AS case_mix_total_nurse_staffing_hours_per_resident_per_day,
    CAST("Case-Mix Weekend Total Nurse Staffing Hours per Resident per Day" AS DOUBLE) AS case_mix_weekend_total_nurse_staffing_hours_per_resident_per_day,
    CAST("Number of Fines" AS DOUBLE) AS number_of_fines,
    CAST("Fine Amount in Dollars" AS BIGINT) AS fine_amount_in_dollars,
    "Percentage of long stay residents whose need for help with daily activities has increased" AS pct_long_stay_residents_whose_nee_daily_activities_has_increased,
    "Percentage of long stay residents who lose too much weight" AS percentage_of_long_stay_residents_who_lose_too_much_weight,
    "Percentage of long stay residents with a catheter inserted and left in their bladder" AS pct_long_stay_residents_a_cath_inserted_left_their_bladder,
    "Percentage of long stay residents with a urinary tract infection" AS percentage_of_long_stay_residents_with_a_urinary_tract_infection,
    "Percentage of long stay residents who have depressive symptoms" AS percentage_of_long_stay_residents_who_have_depressive_symptoms,
    "Percentage of long stay residents who were physically restrained" AS percentage_of_long_stay_residents_who_were_physically_restrained,
    "Percentage of long stay residents experiencing one or more falls with major injury" AS pct_long_stay_residents_experiencing_one_more_falls_major_injury,
    "Percentage of long stay residents assessed and appropriately given the pneumococcal vaccine" AS pct_long_stay_residents_appropriately_given_pneumococcal_vaccine,
    "Percentage of long stay residents who received an antipsychotic medication" AS pct_long_stay_residents_who_received_an_antipsychotic_medication,
    CAST("Percentage of short stay residents assessed and appropriately given the pneumococcal vaccine" AS DOUBLE) AS pct_short_stay_resident_appropriately_given_pneumococcal_vaccine,
    CAST("Percentage of short stay residents who newly received an antipsychotic medication" AS DOUBLE) AS pct_short_stay_residents_wh_received_an_antipsychotic_medication,
    "Percentage of long stay residents whose ability to walk independently worsened" AS pct_long_stay_residents_whos_ability_walk_independently_worsened,
    "Percentage of long stay residents who received an antianxiety or hypnotic medication" AS pct_long_stay_residents_who_r_an_antianxiety_hypnotic_medication,
    "Percentage of long stay residents assessed and appropriately given the seasonal influenza vaccine" AS pct_long_stay_residents_assesse_given_seasonal_influenza_vaccine,
    CAST("Percentage of short stay residents who were assessed and appropriately given the seasonal influenza vaccine" AS DOUBLE) AS pct_short_stay_residents_who_we_given_seasonal_influenza_vaccine,
    "Percentage of long stay residents with pressure ulcers" AS percentage_of_long_stay_residents_with_pressure_ulcers,
    "Percentage of long stay residents with new or worsened bowel or bladder incontinence" AS pct_long_stay_residents_new_worsened_bowel_bladder_incontinence,
    "Percentage of short stay residents who were rehospitalized after a nursing home admission" AS pct_short_stay_residents_who_were_rehospit_a_nurs_home_admission,
    "Percentage of short stay residents who had an outpatient emergency department visit" AS pct_short_stay_residents_who_had_an_outpatient_ed_dept_visit,
    "Number of hospitalizations per 1000 long-stay resident days" AS number_of_hospitalizations_per_1000_long_stay_resident_days,
    "Number of outpatient emergency department visits per 1000 long-stay resident days" AS num_outpatient_ed_dept_visits_1000_long_stay_res_days,
    "Processing Date" AS processing_date
FROM "cms-xcdc-v8bm"
