-- hand-authored to cover accepted CMS dataset added after the initial compile.
-- Faithful pass-through of the current CMS bulk CSV header; all raw values are strings.
SELECT
    "provider key" AS provider_key,
    "practice state or us territory" AS practice_state_or_us_territory,
    "practice size" AS practice_size,
    "clinician type" AS clinician_type,
    "clinician specialty" AS clinician_specialty,
    "years in medicare" AS years_in_medicare,
    "npi" AS npi,
    "non-reporting" AS non_reporting,
    "participation option" AS participation_option,
    "reporting option" AS reporting_option,
    "mips value pathway id" AS mips_value_pathway_id,
    "mips value pathway title" AS mips_value_pathway_title,
    "medicare patients" AS medicare_patients,
    "allowed charges" AS allowed_charges,
    "services" AS services,
    "opted into mips" AS opted_into_mips,
    "small practice status" AS small_practice_status,
    "rural status" AS rural_status,
    "health professional shortage area status" AS health_professional_shortage_area_status,
    "ambulatory surgical center-based status" AS ambulatory_surgical_center_based_status,
    "hospital-based status" AS hospital_based_status,
    "non-patient facing status" AS non_patient_facing_status,
    "facility-based status" AS facility_based_status,
    "received facility score" AS received_facility_score,
    "dual eligibility ratio" AS dual_eligibility_ratio,
    "safety-net status" AS safety_net_status,
    "extreme uncontrollable circumstance (euc)" AS extreme_uncontrollable_circumstance_euc,
    "final score" AS final_score,
    "payment adjustment percentage" AS payment_adjustment_percentage,
    "complex patient bonus" AS complex_patient_bonus,
    "quality category score" AS quality_category_score,
    "quality improvement score" AS quality_improvement_score,
    "quality category weight" AS quality_category_weight,
    "quality reweighting (euc)" AS quality_reweighting_euc,
    "small practice bonus" AS small_practice_bonus,
    "quality measure id 1" AS quality_measure_id_1,
    "quality measure collection type 1" AS quality_measure_collection_type_1,
    "quality measure score 1" AS quality_measure_score_1,
    "quality measure id 2" AS quality_measure_id_2,
    "quality measure collection type 2" AS quality_measure_collection_type_2,
    "quality measure score 2" AS quality_measure_score_2,
    "quality measure id 3" AS quality_measure_id_3,
    "quality measure collection type 3" AS quality_measure_collection_type_3,
    "quality measure score 3" AS quality_measure_score_3,
    "quality measure id 4" AS quality_measure_id_4,
    "quality measure collection type 4" AS quality_measure_collection_type_4,
    "quality measure score 4" AS quality_measure_score_4,
    "quality measure id 5" AS quality_measure_id_5,
    "quality measure collection type 5" AS quality_measure_collection_type_5,
    "quality measure score 5" AS quality_measure_score_5,
    "quality measure id 6" AS quality_measure_id_6,
    "quality measure collection type 6" AS quality_measure_collection_type_6,
    "quality measure score 6" AS quality_measure_score_6,
    "quality measure id 7" AS quality_measure_id_7,
    "quality measure collection type 7" AS quality_measure_collection_type_7,
    "quality measure score 7" AS quality_measure_score_7,
    "quality measure id 8" AS quality_measure_id_8,
    "quality measure collection type 8" AS quality_measure_collection_type_8,
    "quality measure score 8" AS quality_measure_score_8,
    "quality measure id 9" AS quality_measure_id_9,
    "quality measure collection type 9" AS quality_measure_collection_type_9,
    "quality measure score 9" AS quality_measure_score_9,
    "quality measure id 10" AS quality_measure_id_10,
    "quality measure collection type 10" AS quality_measure_collection_type_10,
    "quality measure score 10" AS quality_measure_score_10,
    "quality measure id 11" AS quality_measure_id_11,
    "quality measure collection type 11" AS quality_measure_collection_type_11,
    "quality measure score 11" AS quality_measure_score_11,
    "quality measure id 12" AS quality_measure_id_12,
    "quality measure collection type 12" AS quality_measure_collection_type_12,
    "quality measure score 12" AS quality_measure_score_12,
    "promoting interoperability (pi) category score" AS promoting_interoperability_pi_category_score,
    "promoting interoperability (pi) category weight" AS promoting_interoperability_pi_category_weight,
    "pi reweighting (euc)" AS pi_reweighting_euc,
    "pi reweighting (hardship exception)" AS pi_reweighting_hardship_exception,
    "pi reweighting (special status or clinician type)" AS pi_reweighting_special_status_or_clinician_type,
    "cehrt id" AS cehrt_id,
    "pi measure id 1" AS pi_measure_id_1,
    "pi measure type 1" AS pi_measure_type_1,
    "pi measure score 1" AS pi_measure_score_1,
    "pi measure id 2" AS pi_measure_id_2,
    "pi measure type 2" AS pi_measure_type_2,
    "pi measure score 2" AS pi_measure_score_2,
    "pi measure id 3" AS pi_measure_id_3,
    "pi measure type 3" AS pi_measure_type_3,
    "pi measure score 3" AS pi_measure_score_3,
    "pi measure id 4" AS pi_measure_id_4,
    "pi measure type 4" AS pi_measure_type_4,
    "pi measure score 4" AS pi_measure_score_4,
    "pi measure id 5" AS pi_measure_id_5,
    "pi measure type 5" AS pi_measure_type_5,
    "pi measure score 5" AS pi_measure_score_5,
    "pi measure id 6" AS pi_measure_id_6,
    "pi measure type 6" AS pi_measure_type_6,
    "pi measure score 6" AS pi_measure_score_6,
    "pi measure id 7" AS pi_measure_id_7,
    "pi measure type 7" AS pi_measure_type_7,
    "pi measure score 7" AS pi_measure_score_7,
    "pi measure id 8" AS pi_measure_id_8,
    "pi measure type 8" AS pi_measure_type_8,
    "pi measure score 8" AS pi_measure_score_8,
    "pi measure id 9" AS pi_measure_id_9,
    "pi measure type 9" AS pi_measure_type_9,
    "pi measure score 9" AS pi_measure_score_9,
    "pi measure id 10" AS pi_measure_id_10,
    "pi measure type 10" AS pi_measure_type_10,
    "pi measure score 10" AS pi_measure_score_10,
    "pi measure id 11" AS pi_measure_id_11,
    "pi measure type 11" AS pi_measure_type_11,
    "pi measure score 11" AS pi_measure_score_11,
    "pi measure id 12" AS pi_measure_id_12,
    "pi measure type 12" AS pi_measure_type_12,
    "pi measure score 12" AS pi_measure_score_12,
    "pi measure id 13" AS pi_measure_id_13,
    "pi measure type 13" AS pi_measure_type_13,
    "pi measure score 13" AS pi_measure_score_13,
    "pi measure id 14" AS pi_measure_id_14,
    "pi measure type 14" AS pi_measure_type_14,
    "pi measure score 14" AS pi_measure_score_14,
    "pi measure id 15" AS pi_measure_id_15,
    "pi measure type 15" AS pi_measure_type_15,
    "pi measure score 15" AS pi_measure_score_15,
    "pi measure id 16" AS pi_measure_id_16,
    "pi measure type 16" AS pi_measure_type_16,
    "pi measure score 16" AS pi_measure_score_16,
    "pi measure id 17" AS pi_measure_id_17,
    "pi measure type 17" AS pi_measure_type_17,
    "pi measure score 17" AS pi_measure_score_17,
    "pi measure id 18" AS pi_measure_id_18,
    "pi measure type 18" AS pi_measure_type_18,
    "pi measure score 18" AS pi_measure_score_18,
    "pi measure id 19" AS pi_measure_id_19,
    "pi measure type 19" AS pi_measure_type_19,
    "pi measure score 19" AS pi_measure_score_19,
    "pi measure id 20" AS pi_measure_id_20,
    "pi measure type 20" AS pi_measure_type_20,
    "pi measure score 20" AS pi_measure_score_20,
    "pi measure id 21" AS pi_measure_id_21,
    "pi measure type 21" AS pi_measure_type_21,
    "pi measure score 21" AS pi_measure_score_21,
    "improvement activities (ia) category score" AS improvement_activities_ia_category_score,
    "improvement activities (ia) category weight" AS improvement_activities_ia_category_weight,
    "ia reweighting (euc)" AS ia_reweighting_euc,
    "ia credit" AS ia_credit,
    "ia measure id 1" AS ia_measure_id_1,
    "ia measure score 1" AS ia_measure_score_1,
    "ia measure id 2" AS ia_measure_id_2,
    "ia measure score 2" AS ia_measure_score_2,
    "ia measure id 3" AS ia_measure_id_3,
    "ia measure score 3" AS ia_measure_score_3,
    "ia measure id 4" AS ia_measure_id_4,
    "ia measure score 4" AS ia_measure_score_4,
    "cost category score" AS cost_category_score,
    "cost improvement score" AS cost_improvement_score,
    "cost category weight" AS cost_category_weight,
    "cost reweighting (euc)" AS cost_reweighting_euc,
    "cost measure id 1" AS cost_measure_id_1,
    "cost measure achievement points 1" AS cost_measure_achievement_points_1,
    "cost measure id 2" AS cost_measure_id_2,
    "cost measure achievement points 2" AS cost_measure_achievement_points_2,
    "cost measure id 3" AS cost_measure_id_3,
    "cost measure achievement points 3" AS cost_measure_achievement_points_3,
    "cost measure id 4" AS cost_measure_id_4,
    "cost measure achievement points 4" AS cost_measure_achievement_points_4,
    "cost measure id 5" AS cost_measure_id_5,
    "cost measure achievement points 5" AS cost_measure_achievement_points_5,
    "cost measure id 6" AS cost_measure_id_6,
    "cost measure achievement points 6" AS cost_measure_achievement_points_6,
    "cost measure id 7" AS cost_measure_id_7,
    "cost measure achievement points 7" AS cost_measure_achievement_points_7,
    "cost measure id 8" AS cost_measure_id_8,
    "cost measure achievement points 8" AS cost_measure_achievement_points_8,
    "cost measure id 9" AS cost_measure_id_9,
    "cost measure achievement points 9" AS cost_measure_achievement_points_9,
    "cost measure id 10" AS cost_measure_id_10,
    "cost measure achievement points 10" AS cost_measure_achievement_points_10,
    "cost measure id 11" AS cost_measure_id_11,
    "cost measure achievement points 11" AS cost_measure_achievement_points_11,
    "cost measure id 12" AS cost_measure_id_12,
    "cost measure achievement points 12" AS cost_measure_achievement_points_12,
    "cost measure id 13" AS cost_measure_id_13,
    "cost measure achievement points 13" AS cost_measure_achievement_points_13,
    "cost measure id 14" AS cost_measure_id_14,
    "cost measure achievement points 14" AS cost_measure_achievement_points_14,
    "cost measure id 15" AS cost_measure_id_15,
    "cost measure achievement points 15" AS cost_measure_achievement_points_15,
    "cost measure id 16" AS cost_measure_id_16,
    "cost measure achievement points 16" AS cost_measure_achievement_points_16,
    "cost measure id 17" AS cost_measure_id_17,
    "cost measure achievement points 17" AS cost_measure_achievement_points_17,
    "cost measure id 18" AS cost_measure_id_18,
    "cost measure achievement points 18" AS cost_measure_achievement_points_18,
    "cost measure id 19" AS cost_measure_id_19,
    "cost measure achievement points 19" AS cost_measure_achievement_points_19,
    "cost measure id 20" AS cost_measure_id_20,
    "cost measure achievement points 20" AS cost_measure_achievement_points_20,
    "cost measure id 21" AS cost_measure_id_21,
    "cost measure achievement points 21" AS cost_measure_achievement_points_21,
    "cost measure id 22" AS cost_measure_id_22,
    "cost measure achievement points 22" AS cost_measure_achievement_points_22,
    "cost measure id 23" AS cost_measure_id_23,
    "cost measure achievement points 23" AS cost_measure_achievement_points_23,
    "cost measure id 24" AS cost_measure_id_24,
    "cost measure achievement points 24" AS cost_measure_achievement_points_24,
    "cost measure id 25" AS cost_measure_id_25,
    "cost measure achievement points 25" AS cost_measure_achievement_points_25,
    "cost measure id 26" AS cost_measure_id_26,
    "cost measure achievement points 26" AS cost_measure_achievement_points_26,
    "cost measure id 27" AS cost_measure_id_27,
    "cost measure achievement points 27" AS cost_measure_achievement_points_27,
    "cost measure id 28" AS cost_measure_id_28,
    "cost measure achievement points 28" AS cost_measure_achievement_points_28
FROM "cms-7adb8b1b-b85c-4ed3-b314-064776e50180"
