-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "Rndrng_Prvdr_CCN" AS rndrng_prvdr_ccn,
    "Rndrng_Prvdr_Org_Name" AS rndrng_prvdr_org_name,
    "Rndrng_Prvdr_St" AS rndrng_prvdr_st,
    "Rndrng_Prvdr_City" AS rndrng_prvdr_city,
    "Rndrng_Prvdr_Zip5" AS rndrng_prvdr_zip5,
    "Rndrng_Prvdr_State_Abrvtn" AS rndrng_prvdr_state_abrvtn,
    "Rndrng_Prvdr_State_FIPS" AS rndrng_prvdr_state_fips,
    CAST("Rndrng_Prvdr_RUCA" AS DOUBLE) AS rndrng_prvdr_ruca,
    "Rndrng_Prvdr_RUCA_Desc" AS rndrng_prvdr_ruca_desc,
    CAST("Tot_Benes" AS BIGINT) AS tot_benes,
    CAST("Tot_Submtd_Cvrd_Chrg" AS BIGINT) AS tot_submtd_cvrd_chrg,
    CAST("Tot_Pymt_Amt" AS BIGINT) AS tot_pymt_amt,
    CAST("Tot_Mdcr_Pymt_Amt" AS BIGINT) AS tot_mdcr_pymt_amt,
    CAST("Tot_Dschrgs" AS BIGINT) AS tot_dschrgs,
    CAST("Tot_Cvrd_Days" AS BIGINT) AS tot_cvrd_days,
    CAST("Tot_Days" AS BIGINT) AS tot_days,
    CAST("Bene_Avg_Age" AS DOUBLE) AS bene_avg_age,
    "Bene_Age_LT_65_Cnt" AS bene_age_lt_65_cnt,
    "Bene_Age_65_74_Cnt" AS bene_age_65_74_cnt,
    "Bene_Age_75_84_Cnt" AS bene_age_75_84_cnt,
    "Bene_Age_GT_84_Cnt" AS bene_age_gt_84_cnt,
    "Bene_Feml_Cnt" AS bene_feml_cnt,
    "Bene_Male_Cnt" AS bene_male_cnt,
    "Bene_Race_Wht_Cnt" AS bene_race_wht_cnt,
    "Bene_Race_Black_Cnt" AS bene_race_black_cnt,
    "Bene_Race_API_Cnt" AS bene_race_api_cnt,
    "Bene_Race_Hspnc_Cnt" AS bene_race_hspnc_cnt,
    "Bene_Race_NatInd_Cnt" AS bene_race_natind_cnt,
    "Bene_Race_Othr_Cnt" AS bene_race_othr_cnt,
    "Bene_Dual_Cnt" AS bene_dual_cnt,
    "Bene_Ndual_Cnt" AS bene_ndual_cnt,
    CAST("Bene_CC_BH_ADHD_OthCD_V1_Pct" AS DOUBLE) AS bene_cc_bh_adhd_othcd_v1_pct,
    CAST("Bene_CC_BH_Alcohol_Drug_V1_Pct" AS DOUBLE) AS bene_cc_bh_alcohol_drug_v1_pct,
    CAST("Bene_CC_BH_Tobacco_V1_Pct" AS DOUBLE) AS bene_cc_bh_tobacco_v1_pct,
    CAST("Bene_CC_BH_Alz_NonAlzdem_V2_Pct" AS DOUBLE) AS bene_cc_bh_alz_nonalzdem_v2_pct,
    CAST("Bene_CC_BH_Anxiety_V1_Pct" AS DOUBLE) AS bene_cc_bh_anxiety_v1_pct,
    CAST("Bene_CC_BH_Bipolar_V1_Pct" AS DOUBLE) AS bene_cc_bh_bipolar_v1_pct,
    CAST("Bene_CC_BH_Mood_V2_Pct" AS DOUBLE) AS bene_cc_bh_mood_v2_pct,
    CAST("Bene_CC_BH_Depress_V1_Pct" AS DOUBLE) AS bene_cc_bh_depress_v1_pct,
    CAST("Bene_CC_BH_PD_V1_Pct" AS DOUBLE) AS bene_cc_bh_pd_v1_pct,
    CAST("Bene_CC_BH_PTSD_V1_Pct" AS DOUBLE) AS bene_cc_bh_ptsd_v1_pct,
    CAST("Bene_CC_BH_Schizo_OthPsy_V1_Pct" AS DOUBLE) AS bene_cc_bh_schizo_othpsy_v1_pct,
    CAST("Bene_CC_PH_Asthma_V2_Pct" AS DOUBLE) AS bene_cc_ph_asthma_v2_pct,
    CAST("Bene_CC_PH_Afib_V2_Pct" AS DOUBLE) AS bene_cc_ph_afib_v2_pct,
    CAST("Bene_CC_PH_Cancer6_V2_Pct" AS DOUBLE) AS bene_cc_ph_cancer6_v2_pct,
    CAST("Bene_CC_PH_CKD_V2_Pct" AS DOUBLE) AS bene_cc_ph_ckd_v2_pct,
    CAST("Bene_CC_PH_COPD_V2_Pct" AS DOUBLE) AS bene_cc_ph_copd_v2_pct,
    CAST("Bene_CC_PH_Diabetes_V2_Pct" AS DOUBLE) AS bene_cc_ph_diabetes_v2_pct,
    CAST("Bene_CC_PH_HF_NonIHD_V2_Pct" AS DOUBLE) AS bene_cc_ph_hf_nonihd_v2_pct,
    CAST("Bene_CC_PH_Hyperlipidemia_V2_Pct" AS DOUBLE) AS bene_cc_ph_hyperlipidemia_v2_pct,
    CAST("Bene_CC_PH_Hypertension_V2_Pct" AS DOUBLE) AS bene_cc_ph_hypertension_v2_pct,
    CAST("Bene_CC_PH_IschemicHeart_V2_Pct" AS DOUBLE) AS bene_cc_ph_ischemicheart_v2_pct,
    CAST("Bene_CC_PH_Osteoporosis_V2_Pct" AS DOUBLE) AS bene_cc_ph_osteoporosis_v2_pct,
    CAST("Bene_CC_PH_Parkinson_V2_Pct" AS DOUBLE) AS bene_cc_ph_parkinson_v2_pct,
    CAST("Bene_CC_PH_Arthritis_V2_Pct" AS DOUBLE) AS bene_cc_ph_arthritis_v2_pct,
    CAST("Bene_CC_PH_Stroke_TIA_V2_Pct" AS DOUBLE) AS bene_cc_ph_stroke_tia_v2_pct,
    CAST("Bene_Avg_Risk_Scre" AS DOUBLE) AS bene_avg_risk_scre
FROM "cms-ee6fb1a5-39b9-46b3-a980-a7284551a732"
