-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("Rndrng_NPI" AS BIGINT) AS rndrng_npi,
    "Rndrng_Prvdr_Last_Org_Name" AS rndrng_prvdr_last_org_name,
    "Rndrng_Prvdr_First_Name" AS rndrng_prvdr_first_name,
    "Rndrng_Prvdr_MI" AS rndrng_prvdr_mi,
    "Rndrng_Prvdr_Crdntls" AS rndrng_prvdr_crdntls,
    "Rndrng_Prvdr_Ent_Cd" AS rndrng_prvdr_ent_cd,
    "Rndrng_Prvdr_St1" AS rndrng_prvdr_st1,
    "Rndrng_Prvdr_St2" AS rndrng_prvdr_st2,
    "Rndrng_Prvdr_City" AS rndrng_prvdr_city,
    "Rndrng_Prvdr_State_Abrvtn" AS rndrng_prvdr_state_abrvtn,
    "Rndrng_Prvdr_State_FIPS" AS rndrng_prvdr_state_fips,
    "Rndrng_Prvdr_Zip5" AS rndrng_prvdr_zip5,
    "Rndrng_Prvdr_RUCA" AS rndrng_prvdr_ruca,
    "Rndrng_Prvdr_RUCA_Desc" AS rndrng_prvdr_ruca_desc,
    "Rndrng_Prvdr_Cntry" AS rndrng_prvdr_cntry,
    "Rndrng_Prvdr_Type" AS rndrng_prvdr_type,
    "Rndrng_Prvdr_Mdcr_Prtcptg_Ind" AS rndrng_prvdr_mdcr_prtcptg_ind,
    CAST("Tot_HCPCS_Cds" AS BIGINT) AS tot_hcpcs_cds,
    CAST("Tot_Benes" AS BIGINT) AS tot_benes,
    CAST("Tot_Srvcs" AS DOUBLE) AS tot_srvcs,
    CAST("Tot_Sbmtd_Chrg" AS DOUBLE) AS tot_sbmtd_chrg,
    CAST("Tot_Mdcr_Alowd_Amt" AS DOUBLE) AS tot_mdcr_alowd_amt,
    CAST("Tot_Mdcr_Pymt_Amt" AS DOUBLE) AS tot_mdcr_pymt_amt,
    CAST("Tot_Mdcr_Stdzd_Amt" AS DOUBLE) AS tot_mdcr_stdzd_amt,
    "Drug_Sprsn_Ind" AS drug_sprsn_ind,
    "Drug_Tot_HCPCS_Cds" AS drug_tot_hcpcs_cds,
    "Drug_Tot_Benes" AS drug_tot_benes,
    "Drug_Tot_Srvcs" AS drug_tot_srvcs,
    "Drug_Sbmtd_Chrg" AS drug_sbmtd_chrg,
    "Drug_Mdcr_Alowd_Amt" AS drug_mdcr_alowd_amt,
    "Drug_Mdcr_Pymt_Amt" AS drug_mdcr_pymt_amt,
    "Drug_Mdcr_Stdzd_Amt" AS drug_mdcr_stdzd_amt,
    "Med_Sprsn_Ind" AS med_sprsn_ind,
    "Med_Tot_HCPCS_Cds" AS med_tot_hcpcs_cds,
    "Med_Tot_Benes" AS med_tot_benes,
    "Med_Tot_Srvcs" AS med_tot_srvcs,
    "Med_Sbmtd_Chrg" AS med_sbmtd_chrg,
    "Med_Mdcr_Alowd_Amt" AS med_mdcr_alowd_amt,
    "Med_Mdcr_Pymt_Amt" AS med_mdcr_pymt_amt,
    "Med_Mdcr_Stdzd_Amt" AS med_mdcr_stdzd_amt,
    CAST("Bene_Avg_Age" AS BIGINT) AS bene_avg_age,
    "Bene_Age_LT_65_Cnt" AS bene_age_lt_65_cnt,
    "Bene_Age_65_74_Cnt" AS bene_age_65_74_cnt,
    "Bene_Age_75_84_Cnt" AS bene_age_75_84_cnt,
    "Bene_Age_GT_84_Cnt" AS bene_age_gt_84_cnt,
    "Bene_Feml_Cnt" AS bene_feml_cnt,
    "Bene_Male_Cnt" AS bene_male_cnt,
    "Bene_Race_Wht_Cnt" AS bene_race_wht_cnt,
    "Bene_Race_Black_Cnt" AS bene_race_black_cnt,
    "Bene_Race_API_Cnt" AS bene_race_api_cnt,
    "Bene_Race_Hspnc_Cnt" AS bene_race_hspnc_cnt,
    "Bene_Race_NatInd_Cnt" AS bene_race_natind_cnt,
    "Bene_Race_Othr_Cnt" AS bene_race_othr_cnt,
    "Bene_Dual_Cnt" AS bene_dual_cnt,
    "Bene_Ndual_Cnt" AS bene_ndual_cnt,
    "Bene_CC_BH_ADHD_OthCD_V1_Pct" AS bene_cc_bh_adhd_othcd_v1_pct,
    "Bene_CC_BH_Alcohol_Drug_V1_Pct" AS bene_cc_bh_alcohol_drug_v1_pct,
    "Bene_CC_BH_Tobacco_V1_Pct" AS bene_cc_bh_tobacco_v1_pct,
    "Bene_CC_BH_Alz_NonAlzdem_V2_Pct" AS bene_cc_bh_alz_nonalzdem_v2_pct,
    "Bene_CC_BH_Anxiety_V1_Pct" AS bene_cc_bh_anxiety_v1_pct,
    "Bene_CC_BH_Bipolar_V1_Pct" AS bene_cc_bh_bipolar_v1_pct,
    "Bene_CC_BH_Mood_V2_Pct" AS bene_cc_bh_mood_v2_pct,
    "Bene_CC_BH_Depress_V1_Pct" AS bene_cc_bh_depress_v1_pct,
    "Bene_CC_BH_PD_V1_Pct" AS bene_cc_bh_pd_v1_pct,
    "Bene_CC_BH_PTSD_V1_Pct" AS bene_cc_bh_ptsd_v1_pct,
    "Bene_CC_BH_Schizo_OthPsy_V1_Pct" AS bene_cc_bh_schizo_othpsy_v1_pct,
    "Bene_CC_PH_Asthma_V2_Pct" AS bene_cc_ph_asthma_v2_pct,
    "Bene_CC_PH_Afib_V2_Pct" AS bene_cc_ph_afib_v2_pct,
    "Bene_CC_PH_Cancer6_V2_Pct" AS bene_cc_ph_cancer6_v2_pct,
    "Bene_CC_PH_CKD_V2_Pct" AS bene_cc_ph_ckd_v2_pct,
    "Bene_CC_PH_COPD_V2_Pct" AS bene_cc_ph_copd_v2_pct,
    "Bene_CC_PH_Diabetes_V2_Pct" AS bene_cc_ph_diabetes_v2_pct,
    "Bene_CC_PH_HF_NonIHD_V2_Pct" AS bene_cc_ph_hf_nonihd_v2_pct,
    "Bene_CC_PH_Hyperlipidemia_V2_Pct" AS bene_cc_ph_hyperlipidemia_v2_pct,
    "Bene_CC_PH_Hypertension_V2_Pct" AS bene_cc_ph_hypertension_v2_pct,
    "Bene_CC_PH_IschemicHeart_V2_Pct" AS bene_cc_ph_ischemicheart_v2_pct,
    "Bene_CC_PH_Osteoporosis_V2_Pct" AS bene_cc_ph_osteoporosis_v2_pct,
    "Bene_CC_PH_Parkinson_V2_Pct" AS bene_cc_ph_parkinson_v2_pct,
    "Bene_CC_PH_Arthritis_V2_Pct" AS bene_cc_ph_arthritis_v2_pct,
    "Bene_CC_PH_Stroke_TIA_V2_Pct" AS bene_cc_ph_stroke_tia_v2_pct,
    CAST("Bene_Avg_Risk_Scre" AS DOUBLE) AS bene_avg_risk_scre
FROM "cms-8889d81e-2ee7-448f-8713-f071038289b5"
