-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "Chain" AS chain,
    "Chain ID" AS chain_id,
    CAST("Number of facilities" AS BIGINT) AS number_of_facilities,
    CAST("Number of states and territories with operations" AS BIGINT) AS number_of_states_and_territories_with_operations,
    CAST("Number of Special Focus Facilities (SFF)" AS BIGINT) AS number_of_special_focus_facilities_sff,
    CAST("Number of SFF candidates" AS BIGINT) AS number_of_sff_candidates,
    CAST("Number of facilities with an abuse icon" AS BIGINT) AS number_of_facilities_with_an_abuse_icon,
    CAST("Percentage of facilities with an abuse icon" AS DOUBLE) AS percentage_of_facilities_with_an_abuse_icon,
    CAST("Percent of facilities classified as for-profit" AS DOUBLE) AS percent_of_facilities_classified_as_for_profit,
    CAST("Percent of facilities classified as non-profit" AS DOUBLE) AS percent_of_facilities_classified_as_non_profit,
    CAST("Percent of facilities classified as government-owned" AS DOUBLE) AS percent_of_facilities_classified_as_government_owned,
    CAST("Average overall 5-star rating" AS DOUBLE) AS average_overall_5_star_rating,
    CAST("Average health inspection rating" AS DOUBLE) AS average_health_inspection_rating,
    CAST("Average staffing rating" AS DOUBLE) AS average_staffing_rating,
    CAST("Average quality rating" AS DOUBLE) AS average_quality_rating,
    "Average total nurse hours per resident day" AS average_total_nurse_hours_per_resident_day,
    "Average total weekend nurse hours per resident day" AS average_total_weekend_nurse_hours_per_resident_day,
    "Average total Registered Nurse hours per resident day" AS average_total_registered_nurse_hours_per_resident_day,
    "Average total nursing staff turnover percentage" AS average_total_nursing_staff_turnover_percentage,
    "Average Registered Nurse turnover percentage" AS average_registered_nurse_turnover_percentage,
    "Average number of administrators who have left the nursing home" AS average_number_of_administrators_who_have_left_the_nursing_home,
    CAST("Total number of fines" AS BIGINT) AS total_number_of_fines,
    CAST("Average number of fines" AS DOUBLE) AS average_number_of_fines,
    CAST("Total amount of fines in dollars" AS BIGINT) AS total_amount_of_fines_in_dollars,
    CAST("Average amount of fines in dollars" AS DOUBLE) AS average_amount_of_fines_in_dollars,
    CAST("Total number of payment denials" AS BIGINT) AS total_number_of_payment_denials,
    CAST("Average number of payment denials" AS DOUBLE) AS average_number_of_payment_denials,
    "Average percentage of short-stay residents who were re-hospitalized after a nursing home admission" AS average_percentage_of_short_stay_residents_who_were_re_hospitalized_after_a_nursing_home_admission,
    "Average percentage of short-stay residents who have had an outpatient emergency department visit" AS average_percentage_of_short_stay_residents_who_have_had_an_outpatient_emergency_department_visit,
    "Average percentage of short-stay residents who newly received an antipsychotic medication" AS average_percentage_of_short_stay_residents_who_newly_received_an_antipsychotic_medication,
    "Average percentage of short-stay residents with pressure ulcers or pressure injuries that are new or worsened" AS average_percentage_of_short_stay_residents_with_pressure_ulcers_or_pressure_injuries_that_are_new_or_worsened,
    "Average percentage of short-stay residents who are at or above an expected ability to care for themselves and move around at discharge" AS average_percentage_of_short_stay_residents_who_are_at_or_above_an_expected_ability_to_care_for_themselves_and_move_around_at_discharge,
    "Average percentage of short-stay residents who were assessed and appropriately given the seasonal influenza vaccine" AS average_percentage_of_short_stay_residents_who_were_assessed_and_appropriately_given_the_seasonal_influenza_vaccine,
    CAST("Average percentage of short-stay residents who were assessed and appropriately given the  pneumococcal vaccine" AS DOUBLE) AS average_percentage_of_short_stay_residents_who_were_assessed_and_appropriately_given_the_pneumococcal_vaccine,
    "Average number of hospitalizations per 1,000 long-stay resident days" AS average_number_of_hospitalizations_per_1_000_long_stay_resident_days,
    "Average number of outpatient emergency department visits per 1,000 long-stay resident days" AS average_number_of_outpatient_emergency_department_visits_per_1_000_long_stay_resident_days,
    "Average percentage of long-stay residents who received an antipsychotic medication" AS average_percentage_of_long_stay_residents_who_received_an_antipsychotic_medication,
    "Average percentage of long-stay residents experiencing one or more falls with major injury" AS average_percentage_of_long_stay_residents_experiencing_one_or_more_falls_with_major_injury,
    "Average percentage of long-stay residents with pressure ulcers" AS average_percentage_of_long_stay_residents_with_pressure_ulcers,
    "Average percentage of long-stay residents with a urinary tract infection" AS average_percentage_of_long_stay_residents_with_a_urinary_tract_infection,
    "Average percentage of long-stay residents who have or had a catheter inserted and left in their bladder" AS average_percentage_of_long_stay_residents_who_have_or_had_a_catheter_inserted_and_left_in_their_bladder,
    "Average percentage of long-stay residents whose ability to move independently worsened" AS average_percentage_of_long_stay_residents_whose_ability_to_move_independently_worsened,
    "Average percentage of long-stay residents whose need for help with activities of daily living has increased" AS average_percentage_of_long_stay_residents_whose_need_for_help_with_activities_of_daily_living_has_increased,
    "Average percentage of long-stay residents who were assessed and appropriately given the seasonal influenza vaccine" AS average_percentage_of_long_stay_residents_who_were_assessed_and_appropriately_given_the_seasonal_influenza_vaccine,
    "Average percentage of long-stay residents who were assessed and appropriately given the  pneumococcal vaccine" AS average_percentage_of_long_stay_residents_who_were_assessed_and_appropriately_given_the_pneumococcal_vaccine,
    "Average percentage of long-stay residents who were physically restrained" AS average_percentage_of_long_stay_residents_who_were_physically_restrained,
    "Average percentage of long-stay residents with new or worsened bowel or bladder incontinence" AS average_percentage_of_long_stay_residents_with_new_or_worsened_bowel_or_bladder_incontinence,
    "Average percentage of long-stay residents who lose too much weight" AS average_percentage_of_long_stay_residents_who_lose_too_much_weight,
    "Average percentage of long-stay residents who have symptoms of depression" AS average_percentage_of_long_stay_residents_who_have_symptoms_of_depression,
    "Average percentage of long-stay residents who used antianxiety or hypnotic medication" AS average_percentage_of_long_stay_residents_who_used_antianxiety_or_hypnotic_medication,
    "Average rate of potentially preventable hospital readmissions 30 days after discharge from a SNF" AS average_rate_of_potentially_preventable_hospital_readmissions_30_days_after_discharge_from_a_snf
FROM "cms-97ecfad1-d3f1-4d42-b774-d74661d830bc"
