-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No stable row identifier was verified in the raw profile; treat rows as source snapshot records, not entity-deduplicated facts.
SELECT
    "COUNTRY" AS country,
    CAST("Transfusion Rate (US)" AS DOUBLE) AS transfusion_rate_us,
    CAST("Transfusions - Better than expected (US)" AS BIGINT) AS transfusions_better_than_expected_us,
    CAST("Transfusions - As expected (US)" AS BIGINT) AS transfusions_as_expected_us,
    CAST("Transfusions - Worse than expected (US)" AS BIGINT) AS transfusions_worse_than_expected_us,
    CAST("Percentage of adult HD patients with Kt/V>=1.2" AS DOUBLE) AS percentage_of_adult_hd_patients_with_kt_v_1_2,
    CAST("Percentage Of Adult PD Patients With Kt/V>=1.7" AS DOUBLE) AS percentage_of_adult_pd_patients_with_kt_v_1_7,
    CAST("Percentage Of Pediatric HD Patients With Kt/V>=1.2" AS DOUBLE) AS percentage_of_pediatric_hd_patients_with_kt_v_1_2,
    CAST("Percentage Of Pediatric PD Patients With Kt/V>=1.8" AS DOUBLE) AS percentage_of_pediatric_pd_patients_with_kt_v_1_8,
    CAST("Percentage Of Pediatric HD Patients With nPCR" AS DOUBLE) AS percentage_of_pediatric_hd_patients_with_npcr,
    CAST("Fistula Rate (US)" AS DOUBLE) AS fistula_rate_us,
    CAST("Fistula Rate - Better Than Expected (US)" AS BIGINT) AS fistula_rate_better_than_expected_us,
    CAST("Fistula Rate - As Expected (US)" AS BIGINT) AS fistula_rate_as_expected_us,
    CAST("Fistula Rate - Worse Than Expected (US)" AS BIGINT) AS fistula_rate_worse_than_expected_us,
    CAST("Percentage Of Adult Patients With Long Term Catheter In Use" AS DOUBLE) AS percentage_of_adult_patients_with_long_term_catheter_in_use,
    CAST("Percentage Of Adult Patients With Hypercalcemia (Serum Calcium Greater Than 10.2 Mg/dL)" AS DOUBLE) AS percentage_of_adult_patients_with_hypercalcemia_serum_calcium_greater_than_10_2_mg_dl,
    CAST("Percentage Of Adult Patients With Serum Phosphorus Less Than 3.5 Mg/dL" AS DOUBLE) AS percentage_of_adult_patients_with_serum_phosphorus_less_than_3_5_mg_dl,
    CAST("Percentage Of Adult Patients With Serum Phosphorus Between 3.5-4.5 Mg/dL" AS DOUBLE) AS percentage_of_adult_patients_with_serum_phosphorus_between_3_5_4_5_mg_dl,
    CAST("Percentage Of Adult Patients With Serum Phosphorus Between 4.6-5.5 Mg/dL" AS DOUBLE) AS percentage_of_adult_patients_with_serum_phosphorus_between_4_6_5_5_mg_dl,
    CAST("Percentage Of Adult Patients With Serum Phosphorus Between 5.6-7.0 Mg/dL" AS DOUBLE) AS percentage_of_adult_patients_with_serum_phosphorus_between_5_6_7_0_mg_dl,
    CAST("Percentage Of Adult Patients With Serum Phosphorus Greater Than 7.0 Mg/dL" AS DOUBLE) AS percentage_of_adult_patients_with_serum_phosphorus_greater_than_7_0_mg_dl,
    CAST("Hospitalization Rate (US)" AS DOUBLE) AS hospitalization_rate_us,
    CAST("Hospitalizations - Better Than Expected (US)" AS BIGINT) AS hospitalizations_better_than_expected_us,
    CAST("Hospitalizations - As Expected (US)" AS BIGINT) AS hospitalizations_as_expected_us,
    CAST("Hospitalizations - Worse Than Expected (US)" AS BIGINT) AS hospitalizations_worse_than_expected_us,
    CAST("Readmission Rate (US)" AS DOUBLE) AS readmission_rate_us,
    CAST("Hospital Readmission - Better Than Expected (US)" AS BIGINT) AS hospital_readmission_better_than_expected_us,
    CAST("Hospital Readmission - As Expected (US)" AS BIGINT) AS hospital_readmission_as_expected_us,
    CAST("Hospital  Readmission - Worse Than Expected (US)" AS BIGINT) AS hospital_readmission_worse_than_expected_us,
    CAST("Mortality Rate (US)" AS DOUBLE) AS mortality_rate_us,
    CAST("Survival - Better Than Expected (US)" AS BIGINT) AS survival_better_than_expected_us,
    CAST("Survival - As Expected (US)" AS BIGINT) AS survival_as_expected_us,
    CAST("Survival - Worse Than Expected (US)" AS BIGINT) AS survival_worse_than_expected_us,
    CAST("First Year Standardized Kidney Transplant Waitlist Ratio (US)" AS DOUBLE) AS first_year_standardized_kidney_transplant_waitlist_ratio_us,
    CAST("Incident Patients Transplant Waitlisting - Better Than Expected (US)" AS BIGINT) AS incident_patients_transplant_waitlisting_better_than_expected_us,
    CAST("Incident Patients Transplant Waitlisting - As Expected (US)" AS BIGINT) AS incident_patients_transplant_waitlisting_as_expected_us,
    CAST("Incident Patients Transplant Waitlisting - Worse Than Expected (US)" AS BIGINT) AS incident_patients_transplant_waitlisting_worse_than_expected_us,
    CAST("Percentage of Prevalent Patients Waitlisted for Kidney Transplant (US)" AS DOUBLE) AS percentage_of_prevalent_patients_waitlisted_for_kidney_transplant_us,
    CAST("Prevalent Patients Transplant Waitlisting- Better Than Expected (US)" AS BIGINT) AS prevalent_patients_transplant_waitlisting_better_than_expected_us,
    CAST("Prevalent Patients Transplant Waitlisting - As Expected (US)" AS BIGINT) AS prevalent_patients_transplant_waitlisting_as_expected_us,
    CAST("Prevalent Patients Transplant Waitlisting - Worse Than Expected (US)" AS BIGINT) AS prevalent_patients_transplant_waitlisting_worse_than_expected_us,
    CAST("Healthcare worker COVID-19 vaccination adherence percentage (US)" AS DOUBLE) AS healthcare_worker_covid_19_vaccination_adherence_percentage_us,
    CAST("Percentage Of Patients With Hgb<10 g/dL (US)" AS DOUBLE) AS percentage_of_patients_with_hgb_10_g_dl_us,
    CAST("Percentage of patients with Hgb>12 g/dL (US)" AS DOUBLE) AS percentage_of_patients_with_hgb_12_g_dl_us,
    CAST("Infection - Better than expected (US)" AS BIGINT) AS infection_better_than_expected_us,
    CAST("Infection - As expected (US)" AS BIGINT) AS infection_as_expected_us,
    CAST("Infection - Worse than expected (US)" AS BIGINT) AS infection_worse_than_expected_us,
    CAST("Standardized ED visits ratio (US)" AS DOUBLE) AS standardized_ed_visits_ratio_us,
    CAST("SEDR - Better Than Expected (US)" AS BIGINT) AS sedr_better_than_expected_us,
    CAST("SEDR - As Expected (US)" AS BIGINT) AS sedr_as_expected_us,
    CAST("SEDR - Worse Than Expected (US)" AS BIGINT) AS sedr_worse_than_expected_us,
    CAST("Standardized ED visits within 30 days of hospital discharge ratio (US)" AS DOUBLE) AS standardized_ed_visits_within_30_days_of_hospital_discharge_ratio_us,
    CAST("ED30 - Better Than Expected (US)" AS BIGINT) AS ed30_better_than_expected_us,
    CAST("ED30 - As Expected (US)" AS BIGINT) AS ed30_as_expected_us,
    CAST("ED30 - Worse Than Expected (US)" AS BIGINT) AS ed30_worse_than_expected_us,
    CAST("Standardized Modality Switch Ratio" AS DOUBLE) AS standardized_modality_switch_ratio,
    CAST("N FOR SMSR CATEGORY 1: SMSR-Better than expected (US)" AS BIGINT) AS n_for_smsr_category_1_smsr_better_than_expected_us,
    CAST("N FOR SMSR CATEGORY 2: SMSR-As Expected (US)" AS BIGINT) AS n_for_smsr_category_2_smsr_as_expected_us,
    CAST("N FOR SMSR CATEGORY 3: SMSR-Worse than expected (US)" AS BIGINT) AS n_for_smsr_category_3_smsr_worse_than_expected_us
FROM "cms-2rkq-ygai"
