-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: A very wide sparse table: each `indicator` populates only its own handful of dimension columns; the rest are NULL by construction.
-- caution: `year` mixes calendar years, fiscal-year labels and multi-year ranges.
-- caution: Long-format indicator table: a dimension column is NULL when the row is not disaggregated along that dimension (the row is a total over it). Never aggregate `value` across rows without pinning every dimension column — totals and their components coexist.
SELECT
    "year",
    "indicator",
    "period",
    "value",
    "unit",
    "state",
    "sub_indicator",
    "month",
    "wetland_area_type",
    "river_length",
    "sub_basin",
    "river",
    "soil",
    "land_degradation",
    "land_cover",
    "land_use_category",
    "ramsar_site",
    "phylum",
    "risk_category",
    "risk_status",
    "carbon_pool",
    "cities",
    "emission_source",
    "area",
    "monitoring_station",
    "minerals_metal",
    "minerals_category",
    "fuel_mineral_sub_cate",
    "metalic_mineral_sub_cate",
    "nonmetalic_minerl_sub_cate",
    "ore",
    "type_of_coal",
    "fuel_type",
    "zone",
    "source_power_generation",
    "land_use_sub_category",
    "source_irrigation",
    "cultivated_area",
    "foodgrains",
    "commodity",
    "pesticides_insecticides",
    "species",
    "livestock_marine_products",
    "sector",
    "basin",
    "ozone_depleting_substance",
    "hazardous_waste",
    "region",
    "causes",
    "NFHS_round" AS nfhs_round,
    "source_drinking_water",
    "towns",
    "slums",
    "lenght_of_road",
    "movement_by_road_transport",
    "revenue_realised",
    "vehicles_registered",
    "scheme",
    "subsidy_scheme",
    "broad_discipline",
    "major_discipline"
FROM "mospi-envstats-getenvstatsrecords"
