-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Long-format indicator table: a dimension column is NULL when the row is not disaggregated along that dimension (the row is a total over it). Never aggregate `value` across rows without pinning every dimension column — totals and their components coexist.
SELECT
    "state",
    "indicator",
    "household_classification",
    "Land_Possessed_hectares_" AS land_possessed_hectares,
    "visit_name",
    "value",
    "Social_Group" AS social_group,
    "household_employment",
    "household_sub_employment",
    "sub_indicator",
    "season",
    "operational_holding",
    "major_disposal",
    "Level_Of_Satisfaction" AS level_of_satisfaction,
    "Subsatisfactory_name" AS subsatisfactory_name,
    "agency",
    "resource",
    "sub_resource",
    "major_procurement",
    "sub_major_procurement",
    "agency_procurement",
    "seed_procurements",
    "sub_seed_procurements",
    "expenditure_recipt",
    "business_type",
    "productive_assets",
    "expenses_recipt",
    "crop_production",
    "expenses_imputed",
    "receipts_type",
    "loan_outstanding",
    "ownership_holding",
    "ownership_holding_area",
    "terms_lease",
    "gender",
    "livestock_owned",
    "stock",
    "possession",
    "possession_holding",
    "crop",
    "harvested",
    "sub_harvested",
    "crop_agency",
    "crop_satisfaction",
    "crop_procurement",
    "quality_seeds",
    "insurance_awareness",
    "crop_insurance",
    "crop_loss",
    "crop_experienced"
FROM "mospi-nss77-getnss77records"
