-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: The raw file has no scan-verified non-null row key; treat rows as source observations and avoid assuming row identity beyond the full record.
SELECT
    CAST("CD_YEAR" AS BIGINT) AS cd_year,
    CAST("CD_REFNIS" AS BIGINT) AS cd_refnis,
    "TX_REFNIS_DESCR_FR" AS tx_refnis_descr_fr,
    "TX_REFNIS_DESCR_NL" AS tx_refnis_descr_nl,
    CAST("MS_EMPL_TOT" AS BIGINT) AS ms_empl_tot,
    CAST("MS_ETAB_COUNT" AS BIGINT) AS ms_etab_count,
    "MS_Empl_Density" AS ms_empl_density,
    "MS_Uloc_Density" AS ms_uloc_density,
    CAST("MS_class_ratio_N_Empl_Ouvrier" AS BIGINT) AS ms_class_ratio_n_empl_ouvrier,
    "TX_class_ratio_N_Empl_Ouvrier" AS tx_class_ratio_n_empl_ouvrier,
    CAST("MS_class_ratio_N_Empl_Employe" AS BIGINT) AS ms_class_ratio_n_empl_employe,
    "TX_class_ratio_N_Empl_Employe" AS tx_class_ratio_n_empl_employe,
    CAST("MS_class_ratio_N_Empl_Fnctnair" AS BIGINT) AS ms_class_ratio_n_empl_fnctnair,
    "TX_class_ratio_N_Empl_Fnctnair" AS tx_class_ratio_n_empl_fnctnair,
    CAST("MS_class_ratio_N_Empl_MNE" AS BIGINT) AS ms_class_ratio_n_empl_mne,
    "TX_class_ratio_N_Empl_MNE" AS tx_class_ratio_n_empl_mne,
    CAST("MS_class_ratio_NACE_A" AS BIGINT) AS ms_class_ratio_nace_a,
    "TX_class_ratio_NACE_A" AS tx_class_ratio_nace_a,
    CAST("MS_class_ratio_NACE_B" AS BIGINT) AS ms_class_ratio_nace_b,
    "TX_class_ratio_NACE_B" AS tx_class_ratio_nace_b,
    CAST("MS_class_ratio_NACE_C" AS BIGINT) AS ms_class_ratio_nace_c,
    "TX_class_ratio_NACE_C" AS tx_class_ratio_nace_c,
    CAST("MS_class_ratio_NACE_D" AS BIGINT) AS ms_class_ratio_nace_d,
    "TX_class_ratio_NACE_D" AS tx_class_ratio_nace_d,
    CAST("MS_class_ratio_NACE_E" AS BIGINT) AS ms_class_ratio_nace_e,
    "TX_class_ratio_NACE_E" AS tx_class_ratio_nace_e,
    CAST("MS_class_ratio_NACE_F" AS BIGINT) AS ms_class_ratio_nace_f,
    "TX_class_ratio_NACE_F" AS tx_class_ratio_nace_f,
    CAST("MS_class_ratio_NACE_G" AS BIGINT) AS ms_class_ratio_nace_g,
    "TX_class_ratio_NACE_G" AS tx_class_ratio_nace_g,
    CAST("MS_class_ratio_NACE_H" AS BIGINT) AS ms_class_ratio_nace_h,
    "TX_class_ratio_NACE_H" AS tx_class_ratio_nace_h,
    CAST("MS_class_ratio_NACE_I" AS BIGINT) AS ms_class_ratio_nace_i,
    "TX_class_ratio_NACE_I" AS tx_class_ratio_nace_i,
    CAST("MS_class_ratio_NACE_J" AS BIGINT) AS ms_class_ratio_nace_j,
    "TX_class_ratio_NACE_J" AS tx_class_ratio_nace_j,
    CAST("MS_class_ratio_NACE_K" AS BIGINT) AS ms_class_ratio_nace_k,
    "TX_class_ratio_NACE_K" AS tx_class_ratio_nace_k,
    CAST("MS_class_ratio_NACE_L" AS BIGINT) AS ms_class_ratio_nace_l,
    "TX_class_ratio_NACE_L" AS tx_class_ratio_nace_l,
    CAST("MS_class_ratio_NACE_M" AS BIGINT) AS ms_class_ratio_nace_m,
    "TX_class_ratio_NACE_M" AS tx_class_ratio_nace_m,
    CAST("MS_class_ratio_NACE_N" AS BIGINT) AS ms_class_ratio_nace_n,
    "TX_class_ratio_NACE_N" AS tx_class_ratio_nace_n,
    CAST("MS_class_ratio_NACE_O" AS BIGINT) AS ms_class_ratio_nace_o,
    "TX_class_ratio_NACE_O" AS tx_class_ratio_nace_o,
    CAST("MS_class_ratio_NACE_P" AS BIGINT) AS ms_class_ratio_nace_p,
    "TX_class_ratio_NACE_P" AS tx_class_ratio_nace_p,
    CAST("MS_class_ratio_NACE_Q" AS BIGINT) AS ms_class_ratio_nace_q,
    "TX_class_ratio_NACE_Q" AS tx_class_ratio_nace_q,
    CAST("MS_class_ratio_NACE_R" AS BIGINT) AS ms_class_ratio_nace_r,
    "TX_class_ratio_NACE_R" AS tx_class_ratio_nace_r,
    CAST("MS_class_ratio_NACE_S" AS BIGINT) AS ms_class_ratio_nace_s,
    "TX_class_ratio_NACE_S" AS tx_class_ratio_nace_s,
    CAST("MS_class_ratio_NACE_T" AS BIGINT) AS ms_class_ratio_nace_t,
    "TX_class_ratio_NACE_T" AS tx_class_ratio_nace_t,
    CAST("MS_class_ratio_NACE_U" AS BIGINT) AS ms_class_ratio_nace_u,
    "TX_class_ratio_NACE_U" AS tx_class_ratio_nace_u
FROM "statbel-nodeid5487"
