-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: The raw file has no scan-verified non-null row key; treat rows as source observations and avoid assuming row identity beyond the full record.
SELECT
    CAST("DT_YEAR_COLLISION" AS BIGINT) AS dt_year_collision,
    "DT_MONTH_COLLISION" AS dt_month_collision,
    "TX_MONTH_COLLISION_FR" AS tx_month_collision_fr,
    "TX_MONTH_COLLISION_NL" AS tx_month_collision_nl,
    "CD_DAY_NIGHT" AS cd_day_night,
    "TX_DAY_NIGHT_FR" AS tx_day_night_fr,
    "TX_DAY_NIGHT_NL" AS tx_day_night_nl,
    "FL_WEEKEND" AS fl_weekend,
    "CD_VEHICLE_SEGMENT_A" AS cd_vehicle_segment_a,
    "TX_VEHICLE_SEGMENT_A_FR" AS tx_vehicle_segment_a_fr,
    "TX_VEHICLE_SEGMENT_A_NL" AS tx_vehicle_segment_a_nl,
    "CD_VEHICLE_SEGMENT_B" AS cd_vehicle_segment_b,
    "TX_VEHICLE_SEGMENT_B_FR" AS tx_vehicle_segment_b_fr,
    "TX_VEHICLE_SEGMENT_B_NL" AS tx_vehicle_segment_b_nl,
    CAST("MS_VEHICLE_AGE_AT_COLLISION_YR" AS BIGINT) AS ms_vehicle_age_at_collision_yr,
    "TX_VEHICLE_CLASS_AGE_AT_COLL_YR" AS tx_vehicle_class_age_at_coll_yr,
    "CD_FUEL_TYPE" AS cd_fuel_type,
    "TX_FUEL_TYPE_FR" AS tx_fuel_type_fr,
    "TX_FUEL_TYPE_NL" AS tx_fuel_type_nl,
    CAST("CD_CYLINDER_CLASS_A" AS BIGINT) AS cd_cylinder_class_a,
    "TX_CYLINDER_CLASS_A" AS tx_cylinder_class_a,
    CAST("CD_CYLINDER_CLASS_B" AS BIGINT) AS cd_cylinder_class_b,
    "TX_CYLINDER_CLASS_B" AS tx_cylinder_class_b,
    CAST("CD_OWNER_TYPE" AS BIGINT) AS cd_owner_type,
    "TX_OWNER_TYPE_FR" AS tx_owner_type_fr,
    "TX_OWNER_TYPE_NL" AS tx_owner_type_nl,
    CAST("FL_VEHICLE" AS BIGINT) AS fl_vehicle,
    CAST("FL_CITY_CAR" AS BIGINT) AS fl_city_car,
    CAST("FL_COMPACT_CAR" AS BIGINT) AS fl_compact_car,
    CAST("FL_BERLINE" AS BIGINT) AS fl_berline,
    CAST("FL_SUV" AS BIGINT) AS fl_suv,
    CAST("FL_MONOSPACE" AS BIGINT) AS fl_monospace,
    CAST("FL_PICK_UP" AS BIGINT) AS fl_pick_up,
    CAST("FL_TRUCK_BUS" AS BIGINT) AS fl_truck_bus,
    CAST("FL_MOTO_CYCLO" AS BIGINT) AS fl_moto_cyclo,
    CAST("FL_SPORT" AS BIGINT) AS fl_sport,
    CAST("FL_UKN" AS BIGINT) AS fl_ukn,
    CAST("CD_PROV_COLLISION" AS BIGINT) AS cd_prov_collision,
    "TX_PROV_COLLISION_FR" AS tx_prov_collision_fr,
    "TX_PROV_COLLISION_NL" AS tx_prov_collision_nl,
    "TX_REGION_COLLISON_FR" AS tx_region_collison_fr,
    "TX_REGION_COLLISON_NL" AS tx_region_collison_nl,
    "CD_WEATHER" AS cd_weather,
    "TX_WEATHER_FR" AS tx_weather_fr,
    "TX_WEATHER_NL" AS tx_weather_nl,
    "CD_ROAD_CONDITION" AS cd_road_condition,
    "TX_ROAD_CONDITION_FR" AS tx_road_condition_fr,
    "TX_ROAD_CONDITION_NL" AS tx_road_condition_nl,
    CAST("CD_BUILD_UP_AREA" AS BIGINT) AS cd_build_up_area,
    "TX_BUILD_UP_AREA_FR" AS tx_build_up_area_fr,
    "TX_BUILD_UP_AREA_NL" AS tx_build_up_area_nl,
    CAST("CD_LIGHT_CONDITION" AS BIGINT) AS cd_light_condition,
    "TX_LIGHT_CONDITION_FR" AS tx_light_condition_fr,
    "TX_LIGHT_CONDITION_NL" AS tx_light_condition_nl,
    CAST("CD_ROAD_TYPE" AS BIGINT) AS cd_road_type,
    "TX_ROAD_TYPE_FR" AS tx_road_type_fr,
    "TX_ROAD_TYPE_NL" AS tx_road_type_nl,
    CAST("CD_ACCIDENT_CLASS" AS BIGINT) AS cd_accident_class,
    "TX_ACCIDENT_CLASS_FR" AS tx_accident_class_fr,
    "TX_ACCIDENT_CLASS_NL" AS tx_accident_class_nl,
    "CD_COLLISION_TYPE" AS cd_collision_type,
    "TX_COLLISON_TYPE_FR" AS tx_collison_type_fr,
    "TX_COLLISON_TYPE_NL" AS tx_collison_type_nl
FROM "statbel-nodeid4025"
