ENTITY_IDS = [
    "arboviroses/chikungunya",
    "arboviroses/dengue",
    "arboviroses/febre-amarela-humanos-primatas-nao-humanos",
    "arboviroses/zikavirus",
    "assistencia-a-saude/hospitais-e-leitos",
    "assistencia-a-saude/registro-de-ocupacao-hospitalar-covid-19",
    "assistencia-a-saude/unidade-basicas-de-saude",
    "atencao-primaria/cadastro-vinculado-programa-previne-brasil",
    "atencao-primaria/enani-2019",
    "atencao-primaria/indicador-desempenho-programa-previne-brasil",
    "atencao-primaria/pmmb",
    "atencao-primaria/pmmb-profissionais-ativos",
    "atencao-primaria/pmmb-serie-historica",
    "ciencia-tecnologia/dgits-contribuicoes-consultas-publicas",
    "ciencia-tecnologia/dgits-controle-demandas-conitec",
    "ciencia-tecnologia/dgits-controle-pcdt",
    "ciencia-tecnologia/dgits-tecnologias-diretrizes",
    "cnes/estabelecimentos",
    "cnes/tipounidades",
    "daf/estoque-medicamentos-bnafar-horus",
    "economia-da-saude/bps",
    "economia-da-saude/sistema-de-apuracao-e-gestao-de-custos-do-sus-apurasus",
    "educacao-em-saude/pvc",
    "macrorregiao-e-regiao-de-saude/municipio",
    "outros-temas/ced",
    "plataformabr/projetos",
    "prevencao-e-promocao/distribuicao_epi_insumo",
    "saude-indigena/acompanhamento-obra-infraestrutura-saude",
    "saude-indigena/indicadores-enfrentamento-monitoramento-covid19-indigenas",
    "saude-indigena/planilha-de-fornecimento-e-monitoramento-da-qualidade-da-agua-acesso-a-agua",
    "saude-indigena/planilha-registros-habilitacao-recebimento-incentivo",
    "saude-indigena/sasi-sus-gerenciamento-de-residuos-solidos",
    "saude-indigena/sasisus-esgotamento-sanitario",
    "saude-indigena/sesai-atendimentos",
    "saude-indigena/sesai-recursos-humanos",
    "saude-indigena/siasi-acompanhamento-gestacional",
    "saude-indigena/siasi-modulo-morbidades",
    "saude-indigena/siasi-modulo-saude-bucal-ficha3",
    "saude-indigena/siasi-modulo-saude-bucal-ficha4",
    "saude-indigena/siasi-modulo-saude-bucal-ficha7",
    "saude-indigena/sistema-de-atencao-a-saude-indigena-modulo-de-vigilancia-alimentar-e-nutricional",
    "sisagua/cadastro-carro-pipa-populacao",
    "sisagua/cadastro-carro-pipa-procedencia",
    "sisagua/controle-mensal-amostras-fora-do-padrao",
    "sisagua/controle-mensal-demais-parametros",
    "sisagua/controle-mensal-infraestrutura-operacional",
    "sisagua/controle-mensal-parametros-basicos",
    "sisagua/controle-mensal-plano-amostragem",
    "sisagua/controle-semestral",
    "sisagua/pontos-de-captacao",
    "sisagua/populacao-abastecida",
    "sisagua/tratamento-de-agua",
    "sisagua/vigilancia-cianobacterias-e-cianotoxinas",
    "sisagua/vigilancia-demais-parametros",
    "sisagua/vigilancia-parametros-basicos",
    "sisvan/estado-nutricional",
    "vacinacao/doses-aplicadas-pni",
    "vacinacao/esavi",
    "vacinacao/sistema-de-informacao-de-insumos-estrategicos",
    "vigilancia-e-meio-ambiente/mpox",
    "vigilancia-e-meio-ambiente/notificacoes-de-sindrome-gripal-leve",
    "vigilancia-e-meio-ambiente/sistema-de-informacao-sobre-mortalidade",
    "vigilancia-e-meio-ambiente/sistema-de-informacao-sobre-nascidos-vivos",
    "vigilancia-e-meio-ambiente/srag",
]

PERIOD_PATHS = {
    "vacinacao/doses-aplicadas-pni": [
        "/vacinacao/doses-aplicadas-pni-2020",
        "/vacinacao/doses-aplicadas-pni-2021",
        "/vacinacao/doses-aplicadas-pni-2022",
        "/vacinacao/doses-aplicadas-pni-2023",
        "/vacinacao/doses-aplicadas-pni-2024",
        "/vacinacao/doses-aplicadas-pni-2025",
        "/vacinacao/doses-aplicadas-pni-2026",
    ],
    "vigilancia-e-meio-ambiente/notificacoes-de-sindrome-gripal-leve": [
        "/vigilancia-e-meio-ambiente/notificacoes-de-sindrome-gripal-leve-2020",
        "/vigilancia-e-meio-ambiente/notificacoes-de-sindrome-gripal-leve-2021",
        "/vigilancia-e-meio-ambiente/notificacoes-de-sindrome-gripal-leve-2022",
        "/vigilancia-e-meio-ambiente/notificacoes-de-sindrome-gripal-leve-2023",
        "/vigilancia-e-meio-ambiente/notificacoes-de-sindrome-gripal-leve-2024",
    ],
    "vigilancia-e-meio-ambiente/srag": [
        "/vigilancia-e-meio-ambiente/srag-2009-2012",
        "/vigilancia-e-meio-ambiente/srag-2013-2018",
        "/vigilancia-e-meio-ambiente/srag-2019-2026",
    ],
}

SPECIAL_PATHS = {
    "prevencao-e-promocao/distribuicao_epi_insumo": "/prevencao-e-promocao/distribuicao_epi_insumo",
}

LIMIT_BY_ENTITY = {
    "atencao-primaria/enani-2019": 10,
}
