ENTITY_IDS = [
    "assistencia-a-saude-hospitais-e-leitos",
    "assistencia-a-saude-registro-de-ocupacao-hospitalar-covid-19",
    "assistencia-a-saude-unidade-basicas-de-saude",
    "atencao-primaria-cadastro-vinculado-programa-previne-brasil",
    "atencao-primaria-indicador-desempenho-programa-previne-brasil",
    "atencao-primaria-pmmb",
    "atencao-primaria-pmmb-profissionais-ativos",
    "atencao-primaria-pmmb-serie-historica",
    "ciencia-tecnologia-dgits-contribuicoes-consultas-publicas",
    "ciencia-tecnologia-dgits-controle-demandas-conitec",
    "ciencia-tecnologia-dgits-controle-pcdt",
    "ciencia-tecnologia-dgits-tecnologias-diretrizes",
    "cnes-tipounidades",
    "daf-estoque-medicamentos-bnafar-horus",
    "economia-da-saude-sistema-de-apuracao-e-gestao-de-custos-do-sus-apurasus",
    "macrorregiao-e-regiao-de-saude-municipio",
    "outros-temas-ced",
    "plataformabr-projetos",
    "prevencao-e-promocao-distribuicao-epi-insumo",
    "saude-indigena-acompanhamento-obra-infraestrutura-saude",
    "saude-indigena-indicadores-enfrentamento-monitoramento-covid19-indigenas",
    "saude-indigena-planilha-de-fornecimento-e-monitoramento-da-qualidade-da-agua-acesso-a-agua",
    "saude-indigena-planilha-registros-habilitacao-recebimento-incentivo",
    "saude-indigena-sasi-sus-gerenciamento-de-residuos-solidos",
    "saude-indigena-sasisus-esgotamento-sanitario",
    "saude-indigena-sesai-atendimentos",
    "saude-indigena-sesai-recursos-humanos",
    "saude-indigena-siasi-acompanhamento-gestacional",
    "saude-indigena-siasi-modulo-morbidades",
    "saude-indigena-siasi-modulo-saude-bucal-ficha3",
    "saude-indigena-siasi-modulo-saude-bucal-ficha4",
    "saude-indigena-siasi-modulo-saude-bucal-ficha7",
    "saude-indigena-sistema-de-atencao-a-saude-indigena-modulo-de-vigilancia-alimentar-e-nutricional",
    "sisagua-cadastro-carro-pipa-populacao",
    "sisagua-cadastro-carro-pipa-procedencia",
    "sisagua-controle-mensal-amostras-fora-do-padrao",
    "sisagua-controle-mensal-demais-parametros",
    "sisagua-controle-mensal-infraestrutura-operacional",
    "sisagua-controle-mensal-parametros-basicos",
    "sisagua-controle-mensal-plano-amostragem",
    "sisagua-controle-semestral",
    "sisagua-pontos-de-captacao",
    "sisagua-populacao-abastecida",
    "sisagua-tratamento-de-agua",
    "sisagua-vigilancia-cianobacterias-e-cianotoxinas",
    "sisagua-vigilancia-demais-parametros",
    "sisagua-vigilancia-parametros-basicos",
]

SOURCE_PREFIXES = [
    "macrorregiao-e-regiao-de-saude",
    "assistencia-a-saude",
    "ciencia-tecnologia",
    "economia-da-saude",
    "atencao-primaria",
    "prevencao-e-promocao",
    "saude-indigena",
    "outros-temas",
    "plataformabr",
    "sisagua",
    "cnes",
    "daf",
]

SPECIAL_PATHS = {
    "prevencao-e-promocao-distribuicao-epi-insumo": "/prevencao-e-promocao/distribuicao_epi_insumo",
}
