-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: This is an OECD SDMX cube. Filter to the intended measure, geography, unit, frequency, and other dimensions before aggregating observations.
SELECT
    "ref_area",
    "freq",
    "measure",
    "incentive",
    "instrument",
    "activity",
    "unit_measure",
    "intro_leg",
    "source_leg",
    "add_source_leg",
    "entry_force_leg",
    "sunset_clause_leg",
    "repeal_leg",
    "reduced_rate_inc",
    "degree_exemp_inc",
    "qualify_inc",
    "duration_type_inc",
    "duration_max_inc",
    "tax_treatment_inc",
    "qualify_exp",
    "qualify_spec_exp",
    "allow_credit_rate_exp",
    "allow_app_detail_exp",
    "carryover_exp",
    "refund_exp",
    "sector_cond",
    "sector_list_design",
    "sez_loc",
    "geo_loc",
    "own_leg",
    "new_firm",
    "cond_inv",
    "cap_inv",
    "emp_inv",
    "req_inv",
    "cond_out",
    "div_inc_out",
    "emp_job_out",
    "cap_str_out",
    "loc_source_sme_int_out",
    "exp_dev_out",
    "env_perf_out",
    "rd_out",
    "bus_grwth_out",
    "area_tar",
    "emp_job_tar",
    "env_imp_tar",
    "exp_pro_tar",
    "job_quality_tar",
    "soc_inc_gndr_tar",
    "loc_link_tar",
    "obs_status",
    "time_period",
    "value"
FROM "oecd-oecd.ctp.tps:dsd-itid@df-itid-leg"
