-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: This is an OECD SDMX cube. Filter to the intended measure, geography, unit, frequency, and other dimensions before aggregating observations.
SELECT
    "freq",
    "adjustment",
    "ref_area",
    "counterpart_area",
    "ref_sector",
    "counterpart_sector",
    "consolidation",
    "accounting_entry",
    "sto",
    "instr_asset",
    "maturity",
    "expenditure",
    "unit_measure",
    "currency_denom",
    "valuation",
    "prices",
    "transformation",
    "cust_breakdown",
    "table_identifier",
    "obs_status",
    "conf_status",
    "comment_obs",
    "embargo_date",
    "ref_period_detail",
    "repyearstart",
    "repyearend",
    "time_format",
    "time_per_collect",
    "cust_breakdown_lb",
    "ref_year_price",
    "decimals",
    "title",
    "title_compl",
    "unit_mult",
    "last_update",
    "compiling_org",
    "comment_dset",
    "obs_edp_wbb",
    "coll_period",
    "comment_ts",
    "gfs_ecofunc",
    "gfs_taxcat",
    "pre_break_value",
    "data_comp",
    "currency",
    "diss_org",
    "time_period",
    "value"
FROM "oecd-oecd.sdd.nad:dsd-nasec10-idc@df-table9b-idc"
