-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: An N-number can appear multiple times across historical deregistration records; use the full grain when counting deregistration rows.
SELECT
    "N-NUMBER" AS n_number,
    "SERIAL-NUMBER" AS serial_number,
    "MFR-MDL-CODE" AS mfr_mdl_code,
    "STATUS-CODE" AS status_code,
    "NAME" AS name,
    "STREET-MAIL" AS street_mail,
    "STREET2-MAIL" AS street2_mail,
    "CITY-MAIL" AS city_mail,
    "STATE-ABBREV-MAIL" AS state_abbrev_mail,
    "ZIP-CODE-MAIL" AS zip_code_mail,
    "ENG-MFR-MDL" AS eng_mfr_mdl,
    "YEAR-MFR" AS year_mfr,
    "CERTIFICATION" AS certification,
    "REGION" AS region,
    "COUNTY-MAIL" AS county_mail,
    "COUNTRY-MAIL" AS country_mail,
    "AIR-WORTH-DATE" AS air_worth_date,
    "CANCEL-DATE" AS cancel_date,
    CAST("MODE-S-CODE" AS BIGINT) AS mode_s_code,
    "INDICATOR-GROUP" AS indicator_group,
    "EXP-COUNTRY" AS exp_country,
    "LAST-ACT-DATE" AS last_act_date,
    "CERT-ISSUE-DATE" AS cert_issue_date,
    "STREET-PHYSICAL" AS street_physical,
    "STREET2-PHYSICAL" AS street2_physical,
    "CITY-PHYSICAL" AS city_physical,
    "STATE-ABBREV-PHYSICAL" AS state_abbrev_physical,
    "ZIP-CODE-PHYSICAL" AS zip_code_physical,
    "COUNTY-PHYSICAL" AS county_physical,
    "COUNTRY-PHYSICAL" AS country_physical,
    "OTHER-NAMES(1)" AS other_names_1,
    "OTHER-NAMES(2)" AS other_names_2,
    "OTHER-NAMES(3)" AS other_names_3,
    "OTHER-NAMES(4)" AS other_names_4,
    "OTHER-NAMES(5)" AS other_names_5,
    "KIT MFR" AS kit_mfr,
    "KIT MODEL" AS kit_model,
    "MODE S CODE HEX" AS mode_s_code_hex
FROM "faa-dereg"
