SELECT
    TRIM("CERTIFICATE-NUMBER") AS certificate_number,
    TRIM("OWNERSHIP") AS ownership,
    TRY_STRPTIME(NULLIF(TRIM("CERTIFICATE-DATE"), ''), '%Y%m%d')::DATE AS certificate_date,
    TRY_STRPTIME(NULLIF(TRIM("EXPIRATION-DATE"), ''), '%Y%m%d')::DATE AS expiration_date,
    TRIM("EXPIRATION-FLAG") AS expiration_flag,
    TRY_CAST(NULLIF(TRIM("CERTIFICATE-ISSUE-COUNT"), '') AS INTEGER) AS certificate_issue_count,
    TRIM("NAME") AS name,
    TRIM("STREET") AS street,
    TRIM("STREET2") AS street2,
    TRIM("CITY") AS city,
    TRIM("STATE-ABBREV") AS state,
    TRIM("ZIP-CODE") AS zip_code,
    TRY_CAST(NULLIF(TRIM("OTHER-NAMES-COUNT"), '') AS INTEGER) AS other_names_count,
    TRIM("OTHER-NAMES-1") AS other_names_1,
    TRIM("OTHER-NAMES-2") AS other_names_2,
    TRIM("OTHER-NAMES-3") AS other_names_3,
    TRIM("OTHER-NAMES-4") AS other_names_4,
    TRIM("OTHER-NAMES-5") AS other_names_5,
    TRIM("OTHER-NAMES-6") AS other_names_6,
    TRIM("OTHER-NAMES-7") AS other_names_7,
    TRIM("OTHER-NAMES-8") AS other_names_8,
    TRIM("OTHER-NAMES-9") AS other_names_9,
    TRIM("OTHER-NAMES-10") AS other_names_10,
    TRIM("OTHER-NAMES-11") AS other_names_11,
    TRIM("OTHER-NAMES-12") AS other_names_12,
    TRIM("OTHER-NAMES-13") AS other_names_13,
    TRIM("OTHER-NAMES-14") AS other_names_14,
    TRIM("OTHER-NAMES-15") AS other_names_15,
    TRIM("OTHER-NAMES-16") AS other_names_16,
    TRIM("OTHER-NAMES-17") AS other_names_17,
    TRIM("OTHER-NAMES-18") AS other_names_18,
    TRIM("OTHER-NAMES-19") AS other_names_19,
    TRIM("OTHER-NAMES-20") AS other_names_20,
    TRIM("OTHER-NAMES-21") AS other_names_21,
    TRIM("OTHER-NAMES-22") AS other_names_22,
    TRIM("OTHER-NAMES-23") AS other_names_23,
    TRIM("OTHER-NAMES-24") AS other_names_24,
    TRIM("OTHER-NAMES-25") AS other_names_25
FROM "faa-dealer"
WHERE TRIM("CERTIFICATE-NUMBER") <> ''
