SELECT * REPLACE (CAST(OBS_VALUE AS DOUBLE) AS OBS_VALUE)
FROM "australian-bureau-of-statistics-abs-su-table-2023"
WHERE OBS_VALUE IS NOT NULL
  AND TRIM(CAST(OBS_VALUE AS VARCHAR)) <> ''
  AND TRY_CAST(OBS_VALUE AS DOUBLE) IS NOT NULL
