SELECT * REPLACE (CAST(OBS_VALUE AS DOUBLE) AS OBS_VALUE)
FROM "australian-bureau-of-statistics-abs-seifa2021-sa2"
WHERE OBS_VALUE IS NOT NULL
  AND TRIM(CAST(OBS_VALUE AS VARCHAR)) <> ''
  AND TRY_CAST(OBS_VALUE AS DOUBLE) IS NOT NULL
