SELECT
    country,
    glacier_name,
    TRY_CAST(glacier_id AS BIGINT) AS glacier_id,
    begin_outline_id,
    end_outline_id,
    TRY_CAST(id AS BIGINT) AS id,
    TRY_CAST(begin_date AS DATE) AS begin_date,
    begin_date_unc,
    TRY_CAST(end_date AS DATE) AS end_date,
    end_date_unc,
    TRY_CAST(area AS DOUBLE) AS area,
    TRY_CAST(elevation_change AS DOUBLE) AS elevation_change,
    TRY_CAST(elevation_change_unc AS DOUBLE) AS elevation_change_unc,
    TRY_CAST(volume_change AS DOUBLE) AS volume_change,
    TRY_CAST(volume_change_unc AS DOUBLE) AS volume_change_unc,
    begin_platform,
    begin_method,
    end_platform,
    end_method,
    investigators,
    agencies,
    "references" AS reference_ids,
    remarks
FROM "wgms-fog-change"
