SELECT
    country,
    glacier_name,
    TRY_CAST(glacier_id AS BIGINT) AS glacier_id,
    outline_id,
    TRY_CAST(id AS BIGINT) AS id,
    TRY_CAST(date AS DATE) AS date,
    date_unc,
    TRY_CAST(highest_elevation AS DOUBLE) AS highest_elevation,
    TRY_CAST(lowest_elevation AS DOUBLE) AS lowest_elevation,
    TRY_CAST(mean_elevation AS DOUBLE) AS mean_elevation,
    TRY_CAST(elevation_unc AS DOUBLE) AS elevation_unc,
    TRY_CAST(area AS DOUBLE) AS area,
    TRY_CAST(area_unc AS DOUBLE) AS area_unc,
    TRY_CAST(length AS DOUBLE) AS length,
    TRY_CAST(length_unc AS DOUBLE) AS length_unc,
    terminus_type,
    platform,
    method,
    investigators,
    agencies,
    "references" AS reference_ids,
    remarks
FROM "wgms-fog-state"
