-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "feature_id",
    "WXO_CITY_CODE" AS wxo_city_code,
    "VIRTUAL_STATION_NAME_E" AS virtual_station_name_e,
    "VIRTUAL_STATION_NAME_F" AS virtual_station_name_f,
    "VIRTUAL_CLIMATE_ID" AS virtual_climate_id,
    "LOCAL_MONTH" AS local_month,
    "LOCAL_DAY" AS local_day,
    "RECORD_HIGH_MAX_TEMP" AS record_high_max_temp,
    "RECORD_HIGH_MAX_TEMP_YR" AS record_high_max_temp_yr,
    "PREV_RECORD_HIGH_MAX_TEMP" AS prev_record_high_max_temp,
    "PREV_RECORD_HIGH_MAX_TEMP_YR" AS prev_record_high_max_temp_yr,
    "RECORD_LOW_MAX_TEMP" AS record_low_max_temp,
    "RECORD_LOW_MAX_TEMP_YR" AS record_low_max_temp_yr,
    "PREV_RECORD_LOW_MAX_TEMP" AS prev_record_low_max_temp,
    "PREV_RECORD_LOW_MAX_TEMP_YR" AS prev_record_low_max_temp_yr,
    "RECORD_LOW_MIN_TEMP" AS record_low_min_temp,
    "RECORD_LOW_MIN_TEMP_YR" AS record_low_min_temp_yr,
    "PREV_RECORD_LOW_MIN_TEMP" AS prev_record_low_min_temp,
    "PREV_RECORD_LOW_MIN_TEMP_YR" AS prev_record_low_min_temp_yr,
    "RECORD_HIGH_MIN_TEMP" AS record_high_min_temp,
    "RECORD_HIGH_MIN_TEMP_YR" AS record_high_min_temp_yr,
    "PREV_RECORD_HIGH_MIN_TEMP" AS prev_record_high_min_temp,
    "PREV_RECORD_HIGH_MIN_TEMP_YR" AS prev_record_high_min_temp_yr,
    "FIRST_HIGH_MAX_TEMP" AS first_high_max_temp,
    "FIRST_HIGH_MAX_TEMP_YEAR" AS first_high_max_temp_year,
    "SECOND_HIGH_MAX_TEMP" AS second_high_max_temp,
    "SECOND_HIGH_MAX_TEMP_YEAR" AS second_high_max_temp_year,
    "THIRD_HIGH_MAX_TEMP" AS third_high_max_temp,
    "THIRD_HIGH_MAX_TEMP_YEAR" AS third_high_max_temp_year,
    "FOURTH_HIGH_MAX_TEMP" AS fourth_high_max_temp,
    "FOURTH_HIGH_MAX_TEMP_YEAR" AS fourth_high_max_temp_year,
    "FIFTH_HIGH_MAX_TEMP" AS fifth_high_max_temp,
    "FIFTH_HIGH_MAX_TEMP_YEAR" AS fifth_high_max_temp_year,
    "FIRST_LOW_MAX_TEMP" AS first_low_max_temp,
    "FIRST_LOW_MAX_TEMP_YEAR" AS first_low_max_temp_year,
    "SECOND_LOW_MAX_TEMP" AS second_low_max_temp,
    "SECOND_LOW_MAX_TEMP_YEAR" AS second_low_max_temp_year,
    "THIRD_LOW_MAX_TEMP" AS third_low_max_temp,
    "THIRD_LOW_MAX_TEMP_YEAR" AS third_low_max_temp_year,
    "FOURTH_LOW_MAX_TEMP" AS fourth_low_max_temp,
    "FOURTH_LOW_MAX_TEMP_YEAR" AS fourth_low_max_temp_year,
    "FIFTH_LOW_MAX_TEMP" AS fifth_low_max_temp,
    "FIFTH_LOW_MAX_TEMP_YEAR" AS fifth_low_max_temp_year,
    "FIRST_HIGH_MIN_TEMP" AS first_high_min_temp,
    "FIRST_HIGH_MIN_TEMP_YEAR" AS first_high_min_temp_year,
    "SECOND_HIGH_MIN_TEMP" AS second_high_min_temp,
    "SECOND_HIGH_MIN_TEMP_YEAR" AS second_high_min_temp_year,
    "THIRD_HIGH_MIN_TEMP" AS third_high_min_temp,
    "THIRD_HIGH_MIN_TEMP_YEAR" AS third_high_min_temp_year,
    "FOURTH_HIGH_MIN_TEMP" AS fourth_high_min_temp,
    "FOURTH_HIGH_MIN_TEMP_YEAR" AS fourth_high_min_temp_year,
    "FIFTH_HIGH_MIN_TEMP" AS fifth_high_min_temp,
    "FIFTH_HIGH_MIN_TEMP_YEAR" AS fifth_high_min_temp_year,
    "FIRST_LOW_MIN_TEMP" AS first_low_min_temp,
    "FIRST_LOW_MIN_TEMP_YEAR" AS first_low_min_temp_year,
    "SECOND_LOW_MIN_TEMP" AS second_low_min_temp,
    "SECOND_LOW_MIN_TEMP_YEAR" AS second_low_min_temp_year,
    "THIRD_LOW_MIN_TEMP" AS third_low_min_temp,
    "THIRD_LOW_MIN_TEMP_YEAR" AS third_low_min_temp_year,
    "FOURTH_LOW_MIN_TEMP" AS fourth_low_min_temp,
    "FOURTH_LOW_MIN_TEMP_YEAR" AS fourth_low_min_temp_year,
    "FIFTH_LOW_MIN_TEMP" AS fifth_low_min_temp,
    "FIFTH_LOW_MIN_TEMP_YEAR" AS fifth_low_min_temp_year,
    "PROVINCE_CODE" AS province_code,
    "MIN_TEMP_RECORD_BEGIN" AS min_temp_record_begin,
    "MIN_TEMP_RECORD_END" AS min_temp_record_end,
    "MAX_TEMP_RECORD_BEGIN" AS max_temp_record_begin,
    "MAX_TEMP_RECORD_END" AS max_temp_record_end,
    "IDENTIFIER" AS identifier,
    "LAST_UPDATED" AS last_updated,
    "geometry_type",
    "longitude",
    "latitude"
FROM "environment-and-climate-change-canada-ltce-temperature"
