# Auto-generated: BSP PX-Web entity union (rank-accepted matrices).
# ENTITY_META maps the collect entity id -> PX-Web matrix id (ma) + database path,
# the two identifiers the fetch needs to drive varval.asp / Saveshow.asp.

ENTITY_META = {
    'bankstatistics-kbs-bs-kb': {'ma': 'BS_KB', 'path': '../Database/bankstatistics/kbs/'},
    'bankstatistics-kbs-ccr-kb': {'ma': 'ccr_kb', 'path': '../Database/bankstatistics/kbs/'},
    'bankstatistics-kbs-cl-kb': {'ma': 'cl_kb', 'path': '../Database/bankstatistics/kbs/'},
    'bankstatistics-kbs-is-kb': {'ma': 'IS_KB', 'path': '../Database/bankstatistics/kbs/'},
    'bankstatistics-kbs-lophc-kb': {'ma': 'lophc_kb', 'path': '../Database/bankstatistics/kbs/'},
    'bankstatistics-kbs-lophc94-kb': {'ma': 'lophc94_kb', 'path': '../Database/bankstatistics/kbs/'},
    'bankstatistics-kbs-mvl-kb': {'ma': 'mvl_kb', 'path': '../Database/bankstatistics/kbs/'},
    'bankstatistics-kbs-pi-kb': {'ma': 'PI_KB', 'path': '../Database/bankstatistics/kbs/'},
    'bankstatistics-philbanksystem-bs-pbs': {'ma': 'BS_PBS', 'path': '../Database/bankstatistics/philbanksystem/'},
    'bankstatistics-philbanksystem-ccr-pbs': {'ma': 'ccr_pbs', 'path': '../Database/bankstatistics/philbanksystem/'},
    'bankstatistics-philbanksystem-cl-pbs': {'ma': 'cl_pbs', 'path': '../Database/bankstatistics/philbanksystem/'},
    'bankstatistics-philbanksystem-is-pbs': {'ma': 'IS_PBS', 'path': '../Database/bankstatistics/philbanksystem/'},
    'bankstatistics-philbanksystem-lophc-pbs': {'ma': 'lophc_pbs', 'path': '../Database/bankstatistics/philbanksystem/'},
    'bankstatistics-philbanksystem-lophc94-pbs': {'ma': 'lophc94_pbs', 'path': '../Database/bankstatistics/philbanksystem/'},
    'bankstatistics-philbanksystem-mvl-pbs': {'ma': 'mvl_pbs', 'path': '../Database/bankstatistics/philbanksystem/'},
    'bankstatistics-philbanksystem-pbs-rel1': {'ma': 'pbs_REL1', 'path': '../Database/bankstatistics/philbanksystem/'},
    'bankstatistics-philbanksystem-pi-pbs': {'ma': 'PI_PBS', 'path': '../Database/bankstatistics/philbanksystem/'},
    'bankstatistics-philbanksystem-trust-pbs': {'ma': 'trust_pbs', 'path': '../Database/bankstatistics/philbanksystem/'},
    'bankstatistics-rbs-bs-rb': {'ma': 'BS_RB', 'path': '../Database/bankstatistics/rbs/'},
    'bankstatistics-rcbs-bs-rcb': {'ma': 'BS_RCB', 'path': '../Database/bankstatistics/rcbs/'},
    'bankstatistics-tbs-bs-tb': {'ma': 'BS_TB', 'path': '../Database/bankstatistics/tbs/'},
    'bankstatistics-tbs-is-tb': {'ma': 'IS_TB', 'path': '../Database/bankstatistics/tbs/'},
    'bankstatistics-tbs-pi-tb': {'ma': 'PI_TB', 'path': '../Database/bankstatistics/tbs/'},
    'bankstatistics-ubs-bs-ub': {'ma': 'BS_UB', 'path': '../Database/bankstatistics/ubs/'},
    'bankstatistics-ubs-ccr-ub': {'ma': 'ccr_ub', 'path': '../Database/bankstatistics/ubs/'},
    'bankstatistics-ubs-cl-ub': {'ma': 'cl_ub', 'path': '../Database/bankstatistics/ubs/'},
    'bankstatistics-ubs-is-ub': {'ma': 'IS_UB', 'path': '../Database/bankstatistics/ubs/'},
    'bankstatistics-ubs-lophc-ub': {'ma': 'lophc_ub', 'path': '../Database/bankstatistics/ubs/'},
    'bankstatistics-ubs-lophc94-ub': {'ma': 'lophc94_ub', 'path': '../Database/bankstatistics/ubs/'},
    'bankstatistics-ubs-mvl-ub': {'ma': 'mvl_ub', 'path': '../Database/bankstatistics/ubs/'},
    'bankstatistics-ubs-pi-ub': {'ma': 'PI_UB', 'path': '../Database/bankstatistics/ubs/'},
    'bankstatistics-ukbs-bs-ukb': {'ma': 'BS_UKB', 'path': '../Database/bankstatistics/ukbs/'},
    'bankstatistics-ukbs-ccr-ukb': {'ma': 'ccr_ukb', 'path': '../Database/bankstatistics/ukbs/'},
    'bankstatistics-ukbs-cl-ukb': {'ma': 'cl_ukb', 'path': '../Database/bankstatistics/ukbs/'},
    'bankstatistics-ukbs-is-ukb': {'ma': 'IS_UKB', 'path': '../Database/bankstatistics/ukbs/'},
    'bankstatistics-ukbs-lophc-ukb': {'ma': 'lophc_ukb', 'path': '../Database/bankstatistics/ukbs/'},
    'bankstatistics-ukbs-lophc94-ukb': {'ma': 'lophc94_ukb', 'path': '../Database/bankstatistics/ukbs/'},
    'bankstatistics-ukbs-mvl-ukb': {'ma': 'mvl_ukb', 'path': '../Database/bankstatistics/ukbs/'},
    'bankstatistics-ukbs-pi-ukb': {'ma': 'PI_UKB', 'path': '../Database/bankstatistics/ukbs/'},
    'bankstatistics-ukbs-trust-ukb': {'ma': 'trust_ukb', 'path': '../Database/bankstatistics/ukbs/'},
    'bankstatistics-ukbs-ukb-csie': {'ma': 'ukb_CSIE', 'path': '../Database/bankstatistics/ukbs/'},
    'bankstatistics-ukbs-ukb-rel': {'ma': 'ukb_REL', 'path': '../Database/bankstatistics/ukbs/'},
    'spei-bop1-a-1-bopm-bop-position-a': {'ma': 'A.1.bopm_BOP Position_a', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a-1-bopm-bop-position-m': {'ma': 'A.1.bopm_BOP Position_m', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-capital-a': {'ma': 'A1bop6_capital_a', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-capital-m': {'ma': 'A1bop6_capital_m', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-capital-q': {'ma': 'A1bop6_capital_q', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-di-a': {'ma': 'A1bop6_di_a', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-di-m': {'ma': 'A1bop6_di_m', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-di-q': {'ma': 'A1bop6_di_q', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-fd-a': {'ma': 'A1bop6_fd_a', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-fd-m': {'ma': 'A1bop6_fd_m', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-fd-q': {'ma': 'A1bop6_fd_q', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-goods-a': {'ma': 'A1bop6_goods_a', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-goods-m': {'ma': 'A1bop6_goods_m', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-goods-q': {'ma': 'A1bop6_goods_q', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-main-a': {'ma': 'A1bop6_main_a', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-main-m': {'ma': 'A1bop6_main_m', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-main-q': {'ma': 'A1bop6_main_q', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-obop-a': {'ma': 'A1bop6_obop_a', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-obop-m': {'ma': 'A1bop6_obop_m', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-obop-q': {'ma': 'A1bop6_obop_q', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-oi-a': {'ma': 'A1bop6_oi_a', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-oi-m': {'ma': 'A1bop6_oi_m', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-oi-q': {'ma': 'A1bop6_oi_q', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-pi-a': {'ma': 'A1bop6_pi_a', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-pi-m': {'ma': 'A1bop6_pi_m', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-pi-q': {'ma': 'A1bop6_pi_q', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-primary-income-a': {'ma': 'A1bop6_primary income_a', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-primary-income-m': {'ma': 'A1bop6_primary income_m', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-primary-income-q': {'ma': 'A1bop6_primary income_q', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-secondary-income-a': {'ma': 'A1bop6_secondary income_a', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-secondary-income-m': {'ma': 'A1bop6_secondary income_m', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-secondary-income-q': {'ma': 'A1bop6_secondary income_q', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-services-a': {'ma': 'A1bop6_services_a', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-services-m': {'ma': 'A1bop6_services_m', 'path': '../Database/spei/bop1/'},
    'spei-bop1-a1bop6-services-q': {'ma': 'A1bop6_services_q', 'path': '../Database/spei/bop1/'},
    'spei-ext-accts-a-8-international-reserves': {'ma': 'A.8_International Reserves', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-bop2-boppos': {'ma': 'BOP2_BOPPos', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-bop2-ca': {'ma': 'BOP2_CA', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-bop2-ctransfers': {'ma': 'BOP2_CTransfers', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-bop2-dinvestents': {'ma': 'BOP2_DInvestents', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-bop2-fderivatives': {'ma': 'BOP2_FDerivatives', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-bop2-goods': {'ma': 'BOP2_Goods', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-bop2-income': {'ma': 'BOP2_Income', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-bop2-oinvestments': {'ma': 'BOP2_OInvestments', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-bop2-pinvestments': {'ma': 'BOP2_PInvestments', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-bop2-services': {'ma': 'BOP2_Services', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-bop3-investments': {'ma': 'BOP3_Investments', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-bop3-services': {'ma': 'BOP3_Services', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-eer': {'ma': 'EER', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-er': {'ma': 'ER', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-iip1-assets': {'ma': 'IIP1_Assets', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-iip1-liabilities': {'ma': 'IIP1_Liabilities', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-pesocross': {'ma': 'PESOCROSS', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-pesocross-annual': {'ma': 'pesocross_annual', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-pesocross-monthly': {'ma': 'pesocross_monthly', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-pesoexchangerates-daily': {'ma': 'pesoexchangerates_daily', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-pesoexrates-daily2': {'ma': 'pesoexrates_daily2', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-pesous': {'ma': 'PesoUS', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-sfir': {'ma': 'SFIR', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-uscross': {'ma': 'USCROSS', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-uscross-anave': {'ma': 'uscross_anave', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-accts-uscross-monthly': {'ma': 'uscross_monthly', 'path': '../Database/spei/ext_accts/'},
    'spei-ext-trade-a-4-d-trade-indices-annual': {'ma': 'A.4.D Trade Indices_annual', 'path': '../Database/spei/ext_trade/'},
    'spei-ext-trade-a-4-d-trade-indices-monthly': {'ma': 'A.4.D Trade Indices_monthly', 'path': '../Database/spei/ext_trade/'},
    'spei-ext-trade-a4a-exports-a': {'ma': 'A4A_Exports_a', 'path': '../Database/spei/ext_trade/'},
    'spei-ext-trade-a4a-exports-m': {'ma': 'A4A_Exports_m', 'path': '../Database/spei/ext_trade/'},
    'spei-ext-trade-a4a-exports-q': {'ma': 'A4A_Exports_q', 'path': '../Database/spei/ext_trade/'},
    'spei-ext-trade-a4b-imports-a': {'ma': 'A4B_Imports_a', 'path': '../Database/spei/ext_trade/'},
    'spei-ext-trade-a4b-imports-m': {'ma': 'A4B_Imports_m', 'path': '../Database/spei/ext_trade/'},
    'spei-ext-trade-a4b-imports-q': {'ma': 'A4B_Imports_q', 'path': '../Database/spei/ext_trade/'},
    'spei-ext-trade-a4c-dot-a': {'ma': 'A4C_DOT_a', 'path': '../Database/spei/ext_trade/'},
    'spei-ext-trade-a4c-dot-m': {'ma': 'A4C_DOT_m', 'path': '../Database/spei/ext_trade/'},
    'spei-ext-trade-a4c-dot-q': {'ma': 'A4C_DOT_q', 'path': '../Database/spei/ext_trade/'},
    'spei-extdebt-a9b-total-external-debt-annual': {'ma': 'A9B_Total_External_Debt_Annual', 'path': '../Database/spei/extdebt/'},
    'spei-extdebt-a9c-selected-external-debt-ratios': {'ma': 'A9C_Selected_External_Debt_Ratios', 'path': '../Database/spei/extdebt/'},
    'spei-extdebt-extdebt': {'ma': 'ExtDebt', 'path': '../Database/spei/extdebt/'},
    'spei-extdebt-extdebt-2005': {'ma': 'ExtDebt_2005', 'path': '../Database/spei/extdebt/'},
    'spei-extdebt-sddsextdebt': {'ma': 'SDDSExtDebt', 'path': '../Database/spei/extdebt/'},
    'spei-fcdu-a10a-fcdu-assetsliab-new-pc-axis': {'ma': 'A10A_FCDU AssetsLiab_new_PC Axis', 'path': '../Database/spei/fcdu/'},
    'spei-fcdu-a10b-fcdu-loans-pc-axis': {'ma': 'A10B_FCDU Loans_PC Axis', 'path': '../Database/spei/fcdu/'},
    'spei-fin-sys-accts-bsprates': {'ma': 'BSPRates', 'path': '../Database/spei/fin_sys_accts/'},
    'spei-fin-sys-accts-bsprates-daily': {'ma': 'BSPRates_Daily', 'path': '../Database/spei/fin_sys_accts/'},
    'spei-fin-sys-accts-fof': {'ma': 'FOF', 'path': '../Database/spei/fin_sys_accts/'},
    'spei-fin-sys-accts-ibcl': {'ma': 'IBCL', 'path': '../Database/spei/fin_sys_accts/'},
    'spei-fin-sys-accts-ibcl-m': {'ma': 'IBCL_M', 'path': '../Database/spei/fin_sys_accts/'},
    'spei-fin-sys-accts-la': {'ma': 'LA', 'path': '../Database/spei/fin_sys_accts/'},
    'spei-fin-sys-accts-lo-ukbs': {'ma': 'LO_UKBs', 'path': '../Database/spei/fin_sys_accts/'},
    'spei-fin-sys-accts-nfi': {'ma': 'NFI', 'path': '../Database/spei/fin_sys_accts/'},
    'spei-fin-sys-accts-npl': {'ma': 'NPL', 'path': '../Database/spei/fin_sys_accts/'},
    'spei-fin-sys-accts-rel-exp': {'ma': 'REL_EXP', 'path': '../Database/spei/fin_sys_accts/'},
    'spei-fin-sys-accts-sdam': {'ma': 'SDAM', 'path': '../Database/spei/fin_sys_accts/'},
    'spei-fin-sys-accts-sdatenor': {'ma': 'SDATenor', 'path': '../Database/spei/fin_sys_accts/'},
    'spei-fin-sys-accts-sdir2': {'ma': 'SDIR2', 'path': '../Database/spei/fin_sys_accts/'},
    'spei-fin-sys-accts-timedep': {'ma': 'TimeDep', 'path': '../Database/spei/fin_sys_accts/'},
    'spei-fin-sys-accts-tot-res': {'ma': 'TOT_RES', 'path': '../Database/spei/fin_sys_accts/'},
    'spei-fin-sys-accts-ukbloans-frp1': {'ma': 'UKBLoans_FRP1', 'path': '../Database/spei/fin_sys_accts/'},
    'spei-fiscal-accts-cpsfp': {'ma': 'CPSFP', 'path': '../Database/spei/fiscal_accts/'},
    'spei-fiscal-accts-ngcor': {'ma': 'NGCOR', 'path': '../Database/spei/fiscal_accts/'},
    'spei-iip-a5iip6-assets-q': {'ma': 'A5iip6_assets_q', 'path': '../Database/spei/iip/'},
    'spei-iip-a5iip6-liabilities-q': {'ma': 'A5iip6_liabilities_q', 'path': '../Database/spei/iip/'},
    'spei-iip-a5iip6-main-q': {'ma': 'A5iip6_main_q', 'path': '../Database/spei/iip/'},
    'spei-inc-exp-accts-gni-exco': {'ma': 'GNI_ExCo', 'path': '../Database/spei/inc_exp_accts/'},
    'spei-inc-exp-accts-gni-excu': {'ma': 'GNI_ExCu', 'path': '../Database/spei/inc_exp_accts/'},
    'spei-inc-exp-accts-gni-inco': {'ma': 'GNI_InCo', 'path': '../Database/spei/inc_exp_accts/'},
    'spei-inc-exp-accts-gni-incu': {'ma': 'GNI_InCu', 'path': '../Database/spei/inc_exp_accts/'},
    'spei-investments-a-11-a-foreign-direct-investment-bpm6-annual': {'ma': 'A.11.A Foreign Direct Investment BPM6 Annual', 'path': '../Database/spei/investments/'},
    'spei-investments-a-11-a-foreign-direct-investment-bpm6-monthly': {'ma': 'A.11.A Foreign Direct Investment BPM6 Monthly', 'path': '../Database/spei/investments/'},
    'spei-investments-a-11-a-foreign-direct-investment-bpm6-quarterly': {'ma': 'A.11.A Foreign Direct Investment BPM6 Quarterly', 'path': '../Database/spei/investments/'},
    'spei-investments-a-11-b-psic1994-fdi-by-industry-bpm6-annual': {'ma': 'A.11.B.PSIC1994 FDI by Industry BPM6 Annual', 'path': '../Database/spei/investments/'},
    'spei-investments-a-11-b-psic1994-fdi-by-industry-bpm6-monthly': {'ma': 'A.11.B.PSIC1994 FDI by Industry BPM6 Monthly', 'path': '../Database/spei/investments/'},
    'spei-investments-a-11-b-psic1994-fdi-by-industry-bpm6-quarterly': {'ma': 'A.11.B.PSIC1994 FDI by Industry BPM6 Quarterly', 'path': '../Database/spei/investments/'},
    'spei-investments-a-11-b-psic2009-fdi-by-industry-bpm6-annual': {'ma': 'A.11.B.PSIC2009 FDI by Industry BPM6 Annual', 'path': '../Database/spei/investments/'},
    'spei-investments-a-11-b-psic2009-fdi-by-industry-bpm6-monthly': {'ma': 'A.11.B.PSIC2009 FDI by Industry BPM6 Monthly', 'path': '../Database/spei/investments/'},
    'spei-investments-a-11-b-psic2009-fdi-by-industry-bpm6-quarterly': {'ma': 'A.11.B.PSIC2009 FDI by Industry BPM6 Quarterly', 'path': '../Database/spei/investments/'},
    'spei-investments-a-11-d-net-fdi-by-country-of-origin-bpm6-annual': {'ma': 'A.11.D Net FDI by Country of Origin BPM6 Annual', 'path': '../Database/spei/investments/'},
    'spei-investments-a-11-d-net-fdi-by-country-of-origin-bpm6-monthly': {'ma': 'A.11.D Net FDI by Country of Origin BPM6 Monthly', 'path': '../Database/spei/investments/'},
    'spei-investments-a-11-d-net-fdi-by-country-of-origin-bpm6-quarterly': {'ma': 'A.11.D Net FDI by Country of Origin BPM6 Quarterly', 'path': '../Database/spei/investments/'},
    'spei-investments-a12-net-foreign-portfolio-flat-file-a': {'ma': 'A12_Net_Foreign_Portfolio_Flat File_a', 'path': '../Database/spei/investments/'},
    'spei-investments-a12-net-foreign-portfolio-flat-file-m': {'ma': 'A12_Net_Foreign_Portfolio_Flat File_m', 'path': '../Database/spei/investments/'},
    'spei-investments-a12-net-foreign-portfolio-flat-file-q': {'ma': 'A12_Net_Foreign_Portfolio_Flat File_q', 'path': '../Database/spei/investments/'},
    'spei-mon-accts-bspal': {'ma': 'BSPAL', 'path': '../Database/spei/mon_accts/'},
    'spei-mon-accts-bspiea': {'ma': 'BSPIEA', 'path': '../Database/spei/mon_accts/'},
    'spei-mon-accts-bspiem': {'ma': 'BSPIEM', 'path': '../Database/spei/mon_accts/'},
    'spei-mon-accts-cbs': {'ma': 'CBS', 'path': '../Database/spei/mon_accts/'},
    'spei-mon-accts-dcs-srf': {'ma': 'DCS_SRF', 'path': '../Database/spei/mon_accts/'},
    'spei-of-a14a-of-remittances-a': {'ma': 'A14A_OF Remittances_a', 'path': '../Database/spei/of/'},
    'spei-of-a14a-of-remittances-m': {'ma': 'A14A_OF Remittances_m', 'path': '../Database/spei/of/'},
    'spei-of-a14a-of-remittances-q': {'ma': 'A14A_OF Remittances_q', 'path': '../Database/spei/of/'},
    'spei-of-a14b-of-remittances-a': {'ma': 'A14B_OF Remittances_a', 'path': '../Database/spei/of/'},
    'spei-of-a14b-of-remittances-m': {'ma': 'A14B_OF Remittances_m', 'path': '../Database/spei/of/'},
    'spei-of-a14b-of-remittances-q': {'ma': 'A14B_OF Remittances_q', 'path': '../Database/spei/of/'},
    'spei-other-real-sec-accts-labor': {'ma': 'Labor', 'path': '../Database/spei/other_real_sec_accts/'},
    'spei-other-real-sec-accts-ppi-2000': {'ma': 'PPI_2000', 'path': '../Database/spei/other_real_sec_accts/'},
    'spei-other-real-sec-accts-ppim2000': {'ma': 'PPIm2000', 'path': '../Database/spei/other_real_sec_accts/'},
    'spei-other-real-sec-accts-psmc': {'ma': 'PSMC', 'path': '../Database/spei/other_real_sec_accts/'},
    'spei-other-real-sec-accts-psmt': {'ma': 'PSMT', 'path': '../Database/spei/other_real_sec_accts/'},
    'spei-other-real-sec-accts-vapi': {'ma': 'VAPI', 'path': '../Database/spei/other_real_sec_accts/'},
    'spei-other-real-sec-accts-vopi': {'ma': 'VOPI', 'path': '../Database/spei/other_real_sec_accts/'},
    'spei-other-real-sec-accts-wage2006': {'ma': 'Wage2006', 'path': '../Database/spei/other_real_sec_accts/'},
    'spei-prices-cpi2006-e1': {'ma': 'CPI2006_E1', 'path': '../Database/spei/prices/'},
    'spei-prices-cpi2006-e2': {'ma': 'CPI2006_E2', 'path': '../Database/spei/prices/'},
    'spei-prices-cpi2006-e3': {'ma': 'CPI2006_E3', 'path': '../Database/spei/prices/'},
    'spei-prices-rpi2000-e5': {'ma': 'RPI2000_E5', 'path': '../Database/spei/prices/'},
    'spei-prices-rrepi': {'ma': 'RREPI', 'path': '../Database/spei/prices/'},
    'spei-prices-wpi1998-e4': {'ma': 'WPI1998_E4', 'path': '../Database/spei/prices/'},
    'spei-surveys-bes': {'ma': 'BES', 'path': '../Database/spei/surveys/'},
    'spei-surveys-bes-tab1': {'ma': 'BES_Tab1', 'path': '../Database/spei/surveys/'},
    'spei-surveys-bes-tab7': {'ma': 'BES_Tab7', 'path': '../Database/spei/surveys/'},
    'spei-surveys-ces-tab1': {'ma': 'CES_Tab1', 'path': '../Database/spei/surveys/'},
    'spei-surveys-ces-tab3': {'ma': 'CES_Tab3', 'path': '../Database/spei/surveys/'},
    'spei-surveys-ces-tab5': {'ma': 'CES_Tab5', 'path': '../Database/spei/surveys/'},
}

ENTITY_IDS = list(ENTITY_META)
