-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Stop-level records for a single published jurisdiction; available fields, raw_* columns, and local coding systems vary by jurisdiction, so compare like columns carefully across tables.
SELECT
    "_source_entity_id" AS source_entity_id,
    "_source_file" AS source_file,
    "_source_member" AS source_member,
    "_row_number" AS row_number,
    CAST("raw_row_number" AS BIGINT) AS raw_row_number,
    CAST("date" AS VARCHAR) AS date,
    "location",
    "lat",
    "lng",
    "county_name",
    "subject_age",
    "subject_race",
    "subject_sex",
    "officer_id_hash",
    "officer_age",
    "officer_race",
    "department_id",
    "type",
    "violation",
    "arrest_made",
    "citation_issued",
    "outcome",
    "contraband_found",
    "contraband_drugs",
    "contraband_weapons",
    "contraband_alcohol",
    "contraband_other",
    CAST("search_conducted" AS BOOLEAN) AS search_conducted,
    CAST("search_person" AS BOOLEAN) AS search_person,
    CAST("search_vehicle" AS BOOLEAN) AS search_vehicle,
    "reason_for_stop",
    "raw_contact_type",
    "raw_sex",
    "raw_race",
    "raw_sectionnum",
    "raw_offensecode",
    "raw_contrabanddesc",
    "raw_officer_race"
FROM "stanford-open-policing-project-sc-statewide"
