-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Stop-level records for a single published jurisdiction; available fields, raw_* columns, and local coding systems vary by jurisdiction, so compare like columns carefully across tables.
SELECT
    "_source_entity_id" AS source_entity_id,
    "_source_file" AS source_file,
    "_source_member" AS source_member,
    "_row_number" AS row_number,
    CAST("raw_row_number" AS BIGINT) AS raw_row_number,
    strptime("date", '%Y-%m-%d')::DATE AS date,
    "time",
    "location",
    CAST("lat" AS DOUBLE) AS lat,
    CAST("lng" AS DOUBLE) AS lng,
    "county_name",
    "district",
    "precinct",
    CAST("region" AS BIGINT) AS region,
    "subject_race",
    "subject_sex",
    "officer_id_hash",
    "type",
    "violation",
    CAST("citation_issued" AS BOOLEAN) AS citation_issued,
    CAST("warning_issued" AS BOOLEAN) AS warning_issued,
    "outcome",
    CAST("contraband_found" AS BOOLEAN) AS contraband_found,
    CAST("contraband_drugs" AS BOOLEAN) AS contraband_drugs,
    CAST("contraband_weapons" AS BOOLEAN) AS contraband_weapons,
    CAST("search_conducted" AS BOOLEAN) AS search_conducted,
    CAST("search_vehicle" AS BOOLEAN) AS search_vehicle,
    "search_basis",
    "vehicle_color",
    "vehicle_make",
    "vehicle_model",
    "vehicle_type",
    CAST("vehicle_year" AS BIGINT) AS vehicle_year,
    "raw_HA_RACE_SEX" AS raw_ha_race_sex,
    CAST("raw_HA_SEARCH_PC_boolean" AS BOOLEAN) AS raw_ha_search_pc_boolean,
    CAST("raw_HA_SEARCH_CONCENT_boolean" AS BOOLEAN) AS raw_ha_search_concent_boolean,
    CAST("raw_HA_INCIDTO_ARREST_boolean" AS BOOLEAN) AS raw_ha_incidto_arrest_boolean,
    CAST("raw_HA_VEHICLE_INVENT_boolean" AS BOOLEAN) AS raw_ha_vehicle_invent_boolean
FROM "stanford-open-policing-project-tx-statewide"
