-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Rows are discrete bottle samples across many cruises, depths, regions, and measured parameters; filter by measurement flag and parameter columns before aggregating values.
-- caution: Missing source measurements have been normalized from GLODAP sentinel codes to nulls, so nulls generally mean a parameter was not observed or not reported for that sample.
SELECT
    "expocode",
    "cruise",
    "v22023_cruise",
    "station",
    "cast",
    "year",
    "month",
    "day",
    "hour",
    "minute",
    "latitude",
    "longitude",
    "bottomdepth",
    "maxsampdepth",
    "bottle",
    "pressure",
    "depth",
    "temperature",
    "temperaturef",
    "temperatureqc",
    "theta",
    "constemperature",
    "salinity",
    "salinityf",
    "salinityqc",
    "abssalinity",
    "sigma0",
    "sigma1",
    "sigma2",
    "sigma3",
    "sigma4",
    "gamma",
    "oxygen",
    "oxygenf",
    "oxygenqc",
    "aou",
    "aouf",
    "nitrate",
    "nitratef",
    "nitrateqc",
    "nitrite",
    "nitritef",
    "silicate",
    "silicatef",
    "silicateqc",
    "phosphate",
    "phosphatef",
    "phosphateqc",
    "tco2",
    "tco2f",
    "tco2qc",
    "tco2calc",
    "talk",
    "talkf",
    "talkqc",
    "talkcalc",
    "phts25p0",
    "phts25p0f",
    "phtsinsitutp",
    "phtsinsitutpf",
    "ph_tmp",
    "ph_scale",
    "phts25p0_calc",
    "cfc11",
    "pcfc11",
    "cfc11f",
    "cfc11qc",
    "cfc12",
    "pcfc12",
    "cfc12f",
    "cfc12qc",
    "cfc113",
    "pcfc113",
    "cfc113f",
    "cfc113qc",
    "ccl4",
    "pccl4",
    "ccl4f",
    "ccl4qc",
    "sf6",
    "psf6",
    "sf6f",
    "sf6qc",
    "c13" AS "carbon_13",
    "c13f" AS "carbon_13_flag",
    "c13qc" AS "carbon_13_qc",
    "c14" AS "carbon_14",
    "c14f" AS "carbon_14_flag",
    "c14err" AS "carbon_14_error",
    "h3",
    "h3f",
    "h3err",
    "he3",
    "he3f",
    "he3err",
    "he",
    "hef",
    "heerr",
    "neon",
    "neonf",
    "neonerr",
    "o18",
    "o18f",
    "toc",
    "tocf",
    "doc",
    "docf",
    "don",
    "donf",
    "tdn",
    "tdnf",
    "chla",
    "chlaf",
    "fco2",
    "fco2f",
    "fco2temp",
    "fco2calc",
    "doi",
    "region"
FROM "glodap-bottle-data"
