-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("STATE" AS BIGINT) AS state,
    CAST("COUNTY" AS BIGINT) AS county,
    CAST("MONTH" AS BIGINT) AS month,
    CAST("DAY" AS BIGINT) AS day,
    CAST("HOUR" AS BIGINT) AS hour,
    CAST("MINUTE" AS BIGINT) AS minute,
    CAST("VE_FORMS" AS BIGINT) AS ve_forms,
    CAST("ROAD_FNC" AS BIGINT) AS road_fnc,
    CAST("HARM_EV" AS BIGINT) AS harm_ev,
    CAST("MAN_COLL" AS BIGINT) AS man_coll,
    CAST("SCH_BUS" AS BIGINT) AS sch_bus,
    CAST("VEH_NO" AS BIGINT) AS veh_no,
    CAST("MAKE" AS BIGINT) AS make,
    CAST("BODY_TYP" AS BIGINT) AS body_typ,
    CAST("MOD_YEAR" AS BIGINT) AS mod_year,
    CAST("ROLLOVER" AS BIGINT) AS rollover,
    CAST("TOW_VEH" AS BIGINT) AS tow_veh,
    CAST("SPEC_USE" AS BIGINT) AS spec_use,
    CAST("EMER_USE" AS BIGINT) AS emer_use,
    CAST("IMPACT1" AS BIGINT) AS impact1,
    CAST("IMPACT2" AS BIGINT) AS impact2,
    CAST("IMPACTS" AS BIGINT) AS impacts,
    CAST("FIRE_EXP" AS BIGINT) AS fire_exp,
    CAST("WGTCD_TR" AS BIGINT) AS wgtcd_tr,
    CAST("PER_NO" AS BIGINT) AS per_no,
    CAST("AGE" AS BIGINT) AS age,
    CAST("SEX" AS BIGINT) AS sex,
    CAST("PER_TYP" AS BIGINT) AS per_typ,
    CAST("SEAT_POS" AS BIGINT) AS seat_pos,
    CAST("MAN_REST" AS BIGINT) AS man_rest,
    CAST("AUT_REST" AS BIGINT) AS aut_rest,
    CAST("LOCATION" AS BIGINT) AS location,
    CAST("EJECTION" AS BIGINT) AS ejection,
    CAST("EXTRICAT" AS BIGINT) AS extricat,
    CAST("DRINKING" AS BIGINT) AS drinking,
    CAST("TEST_RES" AS BIGINT) AS test_res,
    CAST("INJ_SEV" AS BIGINT) AS inj_sev,
    CAST("HOSPITAL" AS BIGINT) AS hospital,
    CAST("DEATH_MO" AS BIGINT) AS death_mo,
    CAST("DEATH_DA" AS BIGINT) AS death_da,
    CAST("DEATH_YR" AS BIGINT) AS death_yr,
    CAST("DEATH_HR" AS BIGINT) AS death_hr,
    CAST("DEATH_MN" AS BIGINT) AS death_mn,
    CAST("LAG_HRS" AS BIGINT) AS lag_hrs,
    CAST("LAG_MINS" AS BIGINT) AS lag_mins,
    CAST("P_CF1" AS BIGINT) AS p_cf1,
    CAST("P_CF2" AS BIGINT) AS p_cf2,
    CAST("P_CF3" AS BIGINT) AS p_cf3,
    CAST("ST_CASE" AS BIGINT) AS st_case,
    "MAK_MOD" AS mak_mod,
    CAST("VIN_WGT" AS BIGINT) AS vin_wgt,
    CAST("WHLBS_SH" AS BIGINT) AS whlbs_sh,
    CAST("WHLBS_LG" AS BIGINT) AS whlbs_lg,
    CAST("MCYCL_DS" AS BIGINT) AS mcycl_ds,
    CAST("DEATH_TM" AS BIGINT) AS death_tm,
    "VINA_MOD" AS vina_mod,
    "SER_TR" AS ser_tr,
    CAST("N_MOT_NO" AS BIGINT) AS n_mot_no,
    "VIN_BT" AS vin_bt,
    CAST("ALC_DET" AS BIGINT) AS alc_det,
    CAST("TOXCLGY" AS BIGINT) AS toxclgy,
    CAST("WORK_INJ" AS BIGINT) AS work_inj,
    "CERT_NO" AS cert_no,
    CAST("REST_USE" AS BIGINT) AS rest_use,
    CAST("AIR_BAG" AS BIGINT) AS air_bag,
    CAST("EJ_PATH" AS BIGINT) AS ej_path,
    CAST("DRUGS" AS BIGINT) AS drugs,
    CAST("DRUG_DET" AS BIGINT) AS drug_det,
    CAST("DRUGTEST" AS BIGINT) AS drugtest,
    CAST("DRUG_RES" AS BIGINT) AS drug_res,
    CAST("ALC_RES" AS BIGINT) AS alc_res,
    CAST("DRUGTST1" AS BIGINT) AS drugtst1,
    CAST("DRUGRES1" AS BIGINT) AS drugres1,
    CAST("DRUGTST2" AS BIGINT) AS drugtst2,
    CAST("DRUGRES2" AS BIGINT) AS drugres2,
    CAST("DRUGTST3" AS BIGINT) AS drugtst3,
    CAST("DRUGRES3" AS BIGINT) AS drugres3,
    CAST("ATST_TYP" AS BIGINT) AS atst_typ,
    CAST("RACE" AS BIGINT) AS race,
    CAST("HISPANIC" AS BIGINT) AS hispanic,
    CAST("DOA" AS BIGINT) AS doa,
    CAST("ALC_STATUS" AS BIGINT) AS alc_status,
    CAST("DSTATUS" AS BIGINT) AS dstatus,
    "VINTYPE" AS vintype,
    "VINMAKE" AS vinmake,
    CAST("VINMODYR" AS BIGINT) AS vinmodyr,
    CAST("VIN_LNGT" AS BIGINT) AS vin_lngt,
    "FUELCODE" AS fuelcode,
    CAST("REST_MIS" AS BIGINT) AS rest_mis,
    CAST("P_SF1" AS BIGINT) AS p_sf1,
    CAST("P_SF2" AS BIGINT) AS p_sf2,
    CAST("P_SF3" AS BIGINT) AS p_sf3,
    CAST("STR_VEH" AS BIGINT) AS str_veh,
    "CARBUR" AS carbur,
    "CYLINDER" AS cylinder,
    "DISPLACE" AS displace,
    CAST("MCYCL_CY" AS BIGINT) AS mcycl_cy,
    "TIRE_SZE" AS tire_sze,
    "TON_RAT" AS ton_rat,
    "TRK_WT" AS trk_wt,
    "TRKWTVAR" AS trkwtvar,
    "MCYCL_WT" AS mcycl_wt,
    "VIN_REST" AS vin_rest,
    CAST("WHLDRWHL" AS BIGINT) AS whldrwhl,
    "STATENAME" AS statename,
    CAST("DAYNAME" AS BIGINT) AS dayname,
    "MONTHNAME" AS monthname,
    "HOURNAME" AS hourname,
    "MINUTENAME" AS minutename,
    CAST("RUR_URB" AS BIGINT) AS rur_urb,
    "RUR_URBNAME" AS rur_urbname,
    CAST("FUNC_SYS" AS BIGINT) AS func_sys,
    "FUNC_SYSNAME" AS func_sysname,
    "HARM_EVNAME" AS harm_evname,
    "MAN_COLLNAME" AS man_collname,
    "SCH_BUSNAME" AS sch_busname,
    "MAKENAME" AS makename,
    "BODY_TYPNAME" AS body_typname,
    "MOD_YEARNAME" AS mod_yearname,
    "TOW_VEHNAME" AS tow_vehname,
    "SPEC_USENAME" AS spec_usename,
    "EMER_USENAME" AS emer_usename,
    "ROLLOVERNAME" AS rollovername,
    "IMPACT1NAME" AS impact1name,
    "FIRE_EXPNAME" AS fire_expname,
    "AGENAME" AS agename,
    "SEXNAME" AS sexname,
    "PER_TYPNAME" AS per_typname,
    "INJ_SEVNAME" AS inj_sevname,
    "SEAT_POSNAME" AS seat_posname,
    "REST_USENAME" AS rest_usename,
    "REST_MISNAME" AS rest_misname,
    "AIR_BAGNAME" AS air_bagname,
    "EJECTIONNAME" AS ejectionname,
    "EJ_PATHNAME" AS ej_pathname,
    "EXTRICATNAME" AS extricatname,
    "DRINKINGNAME" AS drinkingname,
    "ALC_DETNAME" AS alc_detname,
    "ALC_STATUSNAME" AS alc_statusname,
    "ATST_TYPNAME" AS atst_typname,
    "ALC_RESNAME" AS alc_resname,
    "DRUGSNAME" AS drugsname,
    "DRUG_DETNAME" AS drug_detname,
    "DSTATUSNAME" AS dstatusname,
    "DRUGTST1NAME" AS drugtst1name,
    "DRUGTST2NAME" AS drugtst2name,
    "DRUGTST3NAME" AS drugtst3name,
    "DRUGRES1NAME" AS drugres1name,
    "DRUGRES2NAME" AS drugres2name,
    "DRUGRES3NAME" AS drugres3name,
    "HOSPITALNAME" AS hospitalname,
    "DOANAME" AS doaname,
    "DEATH_DANAME" AS death_daname,
    "DEATH_MONAME" AS death_moname,
    "DEATH_YRNAME" AS death_yrname,
    "DEATH_HRNAME" AS death_hrname,
    "DEATH_MNNAME" AS death_mnname,
    "DEATH_TMNAME" AS death_tmname,
    "LAG_HRSNAME" AS lag_hrsname,
    "LAG_MINSNAME" AS lag_minsname,
    "P_SF1NAME" AS p_sf1name,
    "P_SF2NAME" AS p_sf2name,
    "P_SF3NAME" AS p_sf3name,
    "WORK_INJNAME" AS work_injname,
    "HISPANICNAME" AS hispanicname,
    "RACENAME" AS racename,
    "LOCATIONNAME" AS locationname,
    "MAK_MODNAME" AS mak_modname,
    CAST("HELM_USE" AS BIGINT) AS helm_use,
    "HELM_USENAME" AS helm_usename,
    CAST("HELM_MIS" AS BIGINT) AS helm_mis,
    "HELM_MISNAME" AS helm_misname,
    CAST("VPICMAKE" AS BIGINT) AS vpicmake,
    "VPICMAKENAME" AS vpicmakename,
    CAST("VPICMODEL" AS BIGINT) AS vpicmodel,
    "VPICMODELNAME" AS vpicmodelname,
    CAST("VPICBODYCLASS" AS BIGINT) AS vpicbodyclass,
    "VPICBODYCLASSNAME" AS vpicbodyclassname,
    CAST("ICFINALBODY" AS BIGINT) AS icfinalbody,
    "ICFINALBODYNAME" AS icfinalbodyname,
    CAST("GVWR_FROM" AS BIGINT) AS gvwr_from,
    "GVWR_FROMNAME" AS gvwr_fromname,
    CAST("GVWR_TO" AS BIGINT) AS gvwr_to,
    "GVWR_TONAME" AS gvwr_toname,
    "DEVTYPENAME" AS devtypename,
    "DEVMOTORNAME" AS devmotorname,
    CAST("DEVTYPE" AS BIGINT) AS devtype,
    CAST("DEVMOTOR" AS BIGINT) AS devmotor,
    "case_year"
FROM "nhtsa-fars-person"
