-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: vPIC decode rows describe VIN decode results joined to FARS vehicles; do not aggregate as one row per crash.
SELECT
    CAST("STATE" AS BIGINT) AS state,
    "STATENAME" AS statename,
    CAST("ST_CASE" AS BIGINT) AS st_case,
    CAST("VEH_NO" AS BIGINT) AS veh_no,
    "VEHICLEDESCRIPTOR" AS vehicledescriptor,
    CAST("VINDECODEDON" AS TIMESTAMP) AS vindecodedon,
    "VINDECODEERROR" AS vindecodeerror,
    CAST("VEHICLETYPEID" AS BIGINT) AS vehicletypeid,
    "VEHICLETYPE" AS vehicletype,
    CAST("MANUFACTURERFULLNAMEID" AS BIGINT) AS manufacturerfullnameid,
    "MANUFACTURERFULLNAME" AS manufacturerfullname,
    CAST("MAKEID" AS BIGINT) AS makeid,
    "MAKE" AS make,
    CAST("MODELID" AS BIGINT) AS modelid,
    "MODEL" AS model,
    CAST("MODELYEAR" AS BIGINT) AS modelyear,
    "SERIES" AS series,
    "TRIM" AS trim,
    "SERIES2" AS series2,
    "TRIM2" AS trim2,
    CAST("PLANTCOUNTRYID" AS BIGINT) AS plantcountryid,
    "PLANTCOUNTRY" AS plantcountry,
    "PLANTSTATE" AS plantstate,
    "PLANTCITY" AS plantcity,
    "PLANTCOMPANYNAME" AS plantcompanyname,
    CAST("DESTINATIONMARKETID" AS BIGINT) AS destinationmarketid,
    "DESTINATIONMARKET" AS destinationmarket,
    CAST("BASEPRICE" AS DOUBLE) AS baseprice,
    "NOTE" AS note,
    CAST("BODYCLASSID" AS BIGINT) AS bodyclassid,
    "BODYCLASS" AS bodyclass,
    CAST("DOORSCOUNT" AS BIGINT) AS doorscount,
    CAST("WINDOWS" AS BIGINT) AS windows,
    CAST("WHEELBASETYPEID" AS BIGINT) AS wheelbasetypeid,
    "WHEELBASETYPE" AS wheelbasetype,
    CAST("TRACKWIDTHIN" AS DOUBLE) AS trackwidthin,
    CAST("GROSSVEHICLEWEIGHTRATINGFROMID" AS BIGINT) AS grossvehicleweightratingfromid,
    "GROSSVEHICLEWEIGHTRATINGFROM" AS grossvehicleweightratingfrom,
    CAST("GROSSVEHICLEWEIGHTRATINGTOID" AS BIGINT) AS grossvehicleweightratingtoid,
    "GROSSVEHICLEWEIGHTRATINGTO" AS grossvehicleweightratingto,
    CAST("GROSSCOMBWEIGHTRATINGFROMID" AS BIGINT) AS grosscombweightratingfromid,
    "GROSSCOMBWEIGHTRATINGFROM" AS grosscombweightratingfrom,
    "GROSSCOMBWEIGHTRATINGTOID" AS grosscombweightratingtoid,
    "GROSSCOMBWEIGHTRATINGTO" AS grosscombweightratingto,
    CAST("CURBWEIGHTLB" AS BIGINT) AS curbweightlb,
    CAST("WHEELBASEIN_FROM" AS DOUBLE) AS wheelbasein_from,
    CAST("WHEELBASEIN_TO" AS DOUBLE) AS wheelbasein_to,
    CAST("WHEELSCOUNT" AS BIGINT) AS wheelscount,
    CAST("WHEELSIZEFRONTIN" AS BIGINT) AS wheelsizefrontin,
    CAST("WHEELSIZEREARIN" AS BIGINT) AS wheelsizerearin,
    CAST("TRUCKBODYCABTYPEID" AS BIGINT) AS truckbodycabtypeid,
    "TRUCKBODYCABTYPE" AS truckbodycabtype,
    CAST("TRUCKBEDTYPEID" AS BIGINT) AS truckbedtypeid,
    "TRUCKBEDTYPE" AS truckbedtype,
    CAST("TRUCKBEDLENGTHIN" AS BIGINT) AS truckbedlengthin,
    CAST("BUSTYPEID" AS BIGINT) AS bustypeid,
    "BUSTYPE" AS bustype,
    CAST("BUSFLOORCONFIGURATIONTYPEID" AS BIGINT) AS busfloorconfigurationtypeid,
    "BUSFLOORCONFIGURATIONTYPE" AS busfloorconfigurationtype,
    CAST("BUSLENGTHFT" AS BIGINT) AS buslengthft,
    "OTHERBUSINFO" AS otherbusinfo,
    CAST("CUSTOMMOTORCYCLETYPEID" AS BIGINT) AS custommotorcycletypeid,
    "CUSTOMMOTORCYCLETYPE" AS custommotorcycletype,
    CAST("MOTORCYCLESUSPENSIONTYPEID" AS BIGINT) AS motorcyclesuspensiontypeid,
    "MOTORCYCLESUSPENSIONTYPE" AS motorcyclesuspensiontype,
    CAST("MOTORCYCLECHASSISTYPEID" AS BIGINT) AS motorcyclechassistypeid,
    "MOTORCYCLECHASSISTYPE" AS motorcyclechassistype,
    "OTHERMOTORCYCLEINFO" AS othermotorcycleinfo,
    CAST("STEERINGLOCATIONID" AS BIGINT) AS steeringlocationid,
    "STEERINGLOCATION" AS steeringlocation,
    CAST("ENTERTAINMENTSYSTEMID" AS BIGINT) AS entertainmentsystemid,
    "ENTERTAINMENTSYSTEM" AS entertainmentsystem,
    CAST("SEATSCOUNT" AS BIGINT) AS seatscount,
    CAST("SEATROWSCOUNT" AS BIGINT) AS seatrowscount,
    CAST("TRANSMISSIONSPEEDS" AS BIGINT) AS transmissionspeeds,
    CAST("TRANSMISSIONSTYLEID" AS BIGINT) AS transmissionstyleid,
    "TRANSMISSIONSTYLE" AS transmissionstyle,
    CAST("DRIVETYPEID" AS BIGINT) AS drivetypeid,
    "DRIVETYPE" AS drivetype,
    CAST("AXLESCOUNT" AS BIGINT) AS axlescount,
    CAST("AXLECONFIGURATIONID" AS BIGINT) AS axleconfigurationid,
    "AXLECONFIGURATION" AS axleconfiguration,
    CAST("BRAKESYSTEMTYPEID" AS BIGINT) AS brakesystemtypeid,
    "BRAKESYSTEMTYPE" AS brakesystemtype,
    "BRAKESYSTEMDESC" AS brakesystemdesc,
    CAST("EVDRIVEUNITID" AS BIGINT) AS evdriveunitid,
    "EVDRIVEUNIT" AS evdriveunit,
    CAST("BATTERYKWH_FROM" AS DOUBLE) AS batterykwh_from,
    CAST("BATTERYKWH_TO" AS DOUBLE) AS batterykwh_to,
    CAST("BATTERYV_FROM" AS BIGINT) AS batteryv_from,
    CAST("BATTERYV_TO" AS BIGINT) AS batteryv_to,
    CAST("BATTERYA_FROM" AS BIGINT) AS batterya_from,
    "BATTERYA_TO" AS batterya_to,
    CAST("BATTERYPACKSPERVEHICLE" AS BIGINT) AS batterypackspervehicle,
    CAST("BATTERYMODULESPERPACK" AS BIGINT) AS batterymodulesperpack,
    CAST("BATTERYCELLSPERMODULE" AS BIGINT) AS batterycellspermodule,
    CAST("BATTERYTYPEID" AS BIGINT) AS batterytypeid,
    "BATTERYTYPE" AS batterytype,
    "OTHERBATTERYINFO" AS otherbatteryinfo,
    CAST("CHARGERLEVELID" AS BIGINT) AS chargerlevelid,
    "CHARGERLEVEL" AS chargerlevel,
    CAST("CHARGERPOWERKW" AS BIGINT) AS chargerpowerkw,
    "ENGINEMANUFACTURER" AS enginemanufacturer,
    "ENGINEMODEL" AS enginemodel,
    CAST("ENGINECONFIGURATIONID" AS BIGINT) AS engineconfigurationid,
    "ENGINECONFIGURATION" AS engineconfiguration,
    CAST("ENGINEPOWERKW" AS DOUBLE) AS enginepowerkw,
    CAST("ENGINESTROKECYCLES" AS BIGINT) AS enginestrokecycles,
    CAST("ENGINECYLINDERSCOUNT" AS BIGINT) AS enginecylinderscount,
    CAST("ENGINEBRAKEHP_FROM" AS DOUBLE) AS enginebrakehp_from,
    CAST("ENGINEBRAKEHP_TO" AS DOUBLE) AS enginebrakehp_to,
    CAST("ENGINECOOLINGTYPEID" AS BIGINT) AS enginecoolingtypeid,
    "ENGINECOOLINGTYPE" AS enginecoolingtype,
    CAST("DISPLACEMENTCI" AS DOUBLE) AS displacementci,
    CAST("DISPLACEMENTCC" AS DOUBLE) AS displacementcc,
    CAST("DISPLACEMENTL" AS DOUBLE) AS displacementl,
    CAST("FUELTYPEPRIMARYID" AS BIGINT) AS fueltypeprimaryid,
    "FUELTYPEPRIMARY" AS fueltypeprimary,
    CAST("FUELTYPESECONDARYID" AS BIGINT) AS fueltypesecondaryid,
    "FUELTYPESECONDARY" AS fueltypesecondary,
    CAST("FUELDELIVERYINJECTIONTYPEID" AS BIGINT) AS fueldeliveryinjectiontypeid,
    "FUELDELIVERYINJECTIONTYPE" AS fueldeliveryinjectiontype,
    CAST("ENGINEVALVETRAINDESIGNID" AS BIGINT) AS enginevalvetraindesignid,
    "ENGINEVALVETRAINDESIGN" AS enginevalvetraindesign,
    CAST("ENGINEELECTRIFICATIONLEVELID" AS BIGINT) AS engineelectrificationlevelid,
    "ENGINEELECTRIFICATIONLEVEL" AS engineelectrificationlevel,
    CAST("ENGINETURBOID" AS BIGINT) AS engineturboid,
    "ENGINETURBO" AS engineturbo,
    CAST("TOPSPEEDMPH" AS BIGINT) AS topspeedmph,
    "OTHERENGINEINFO" AS otherengineinfo,
    CAST("SEATBELTTYPEID" AS BIGINT) AS seatbelttypeid,
    "SEATBELTTYPE" AS seatbelttype,
    CAST("PRETENSIONERID" AS BIGINT) AS pretensionerid,
    "PRETENSIONER" AS pretensioner,
    CAST("AIRBAGLOCFRONTID" AS BIGINT) AS airbaglocfrontid,
    "AIRBAGLOCFRONT" AS airbaglocfront,
    CAST("AIRBAGLOCKNEEID" AS BIGINT) AS airbaglockneeid,
    "AIRBAGLOCKNEE" AS airbaglocknee,
    CAST("AIRBAGLOCSIDEID" AS BIGINT) AS airbaglocsideid,
    "AIRBAGLOCSIDE" AS airbaglocside,
    CAST("AIRBAGLOCCURTAINID" AS BIGINT) AS airbagloccurtainid,
    "AIRBAGLOCCURTAIN" AS airbagloccurtain,
    CAST("AIRBAGLOCSEATCUSHIONID" AS BIGINT) AS airbaglocseatcushionid,
    "AIRBAGLOCSEATCUSHION" AS airbaglocseatcushion,
    "OTHERRESTRAINTSYSTEMINFO" AS otherrestraintsysteminfo,
    CAST("FORWARDCOLLISIONWARNINGID" AS BIGINT) AS forwardcollisionwarningid,
    "FORWARDCOLLISIONWARNING" AS forwardcollisionwarning,
    CAST("DYNAMICBRAKESUPPORTID" AS BIGINT) AS dynamicbrakesupportid,
    "DYNAMICBRAKESUPPORT" AS dynamicbrakesupport,
    CAST("CRASHIMMINENTBRAKINGID" AS BIGINT) AS crashimminentbrakingid,
    "CRASHIMMINENTBRAKING" AS crashimminentbraking,
    CAST("PEDESTRIANAUTOEMERGENCYBRAKINGID" AS BIGINT) AS pedestrianautoemergencybrakingid,
    "PEDESTRIANAUTOEMERGENCYBRAKING" AS pedestrianautoemergencybraking,
    CAST("BLINDSPOTWARNINGID" AS BIGINT) AS blindspotwarningid,
    "BLINDSPOTWARNING" AS blindspotwarning,
    CAST("BLINDSPOTINTERVENTIONID" AS BIGINT) AS blindspotinterventionid,
    "BLINDSPOTINTERVENTION" AS blindspotintervention,
    CAST("LANEDEPARTUREWARNINGID" AS BIGINT) AS lanedeparturewarningid,
    "LANEDEPARTUREWARNING" AS lanedeparturewarning,
    CAST("LANEKEEPINGASSISTANCEID" AS BIGINT) AS lanekeepingassistanceid,
    "LANEKEEPINGASSISTANCE" AS lanekeepingassistance,
    CAST("LANECENTERINGASSISTANCEID" AS BIGINT) AS lanecenteringassistanceid,
    "LANECENTERINGASSISTANCE" AS lanecenteringassistance,
    CAST("BACKUPCAMERAID" AS BIGINT) AS backupcameraid,
    "BACKUPCAMERA" AS backupcamera,
    CAST("REARCROSSTRAFFICALERTID" AS BIGINT) AS rearcrosstrafficalertid,
    "REARCROSSTRAFFICALERT" AS rearcrosstrafficalert,
    CAST("REARAUTOMATICEMERGENCYBRAKINGID" AS BIGINT) AS rearautomaticemergencybrakingid,
    "REARAUTOMATICEMERGENCYBRAKING" AS rearautomaticemergencybraking,
    CAST("PARKASSISTID" AS BIGINT) AS parkassistid,
    "PARKASSIST" AS parkassist,
    CAST("DAYTIMERUNNINGLIGHTID" AS BIGINT) AS daytimerunninglightid,
    "DAYTIMERUNNINGLIGHT" AS daytimerunninglight,
    CAST("HEADLAMPLIGHTSOURCEID" AS BIGINT) AS headlamplightsourceid,
    "HEADLAMPLIGHTSOURCE" AS headlamplightsource,
    CAST("SEMIAUTOHEADLAMPBEAMSWITCHINGID" AS BIGINT) AS semiautoheadlampbeamswitchingid,
    "SEMIAUTOHEADLAMPBEAMSWITCHING" AS semiautoheadlampbeamswitching,
    CAST("ADAPTIVEDRIVINGBEAMID" AS BIGINT) AS adaptivedrivingbeamid,
    "ADAPTIVEDRIVINGBEAM" AS adaptivedrivingbeam,
    CAST("ADAPTIVECRUISECONTROLID" AS BIGINT) AS adaptivecruisecontrolid,
    "ADAPTIVECRUISECONTROL" AS adaptivecruisecontrol,
    CAST("ANTILOCKBRAKESYSTEMID" AS BIGINT) AS antilockbrakesystemid,
    "ANTILOCKBRAKESYSTEM" AS antilockbrakesystem,
    CAST("ELECTRONICSTABILITYCONTROLID" AS BIGINT) AS electronicstabilitycontrolid,
    "ELECTRONICSTABILITYCONTROL" AS electronicstabilitycontrol,
    CAST("TPMSID" AS BIGINT) AS tpmsid,
    "TPMS" AS tpms,
    CAST("AUTOMATICCRASHNOTIFICATIONID" AS BIGINT) AS automaticcrashnotificationid,
    "AUTOMATICCRASHNOTIFICATION" AS automaticcrashnotification,
    CAST("EVENTDATARECORDERID" AS BIGINT) AS eventdatarecorderid,
    "EVENTDATARECORDER" AS eventdatarecorder,
    CAST("TRACTIONCONTROLID" AS BIGINT) AS tractioncontrolid,
    "TRACTIONCONTROL" AS tractioncontrol,
    CAST("AUTOPEDESTRIANALERTINGSOUNDID" AS BIGINT) AS autopedestrianalertingsoundid,
    "AUTOPEDESTRIANALERTINGSOUND" AS autopedestrianalertingsound,
    CAST("KEYLESSIGNITIONID" AS BIGINT) AS keylessignitionid,
    "KEYLESSIGNITION" AS keylessignition,
    CAST("SAEAUTOMATIONLEVEL_FROM" AS BIGINT) AS saeautomationlevel_from,
    "SAEAUTOMATIONLEVEL_TO" AS saeautomationlevel_to,
    CAST("AUTOREVERSESYSTEMID" AS BIGINT) AS autoreversesystemid,
    "AUTOREVERSESYSTEM" AS autoreversesystem,
    "ACTIVESAFETYSYSNOTE" AS activesafetysysnote,
    "NONLANDUSEID" AS nonlanduseid,
    "NONLANDUSE" AS nonlanduse,
    "case_year"
FROM "nhtsa-fars-vpicdecode"
