-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("STATE" AS BIGINT) AS state,
    CAST("VE_FORMS" AS BIGINT) AS ve_forms,
    CAST("HARM_EV" AS BIGINT) AS harm_ev,
    CAST("MAN_COLL" AS BIGINT) AS man_coll,
    CAST("HIT_RUN" AS BIGINT) AS hit_run,
    CAST("VEH_NO" AS BIGINT) AS veh_no,
    CAST("MAKE" AS BIGINT) AS make,
    CAST("MODEL" AS BIGINT) AS model,
    CAST("BODY_TYP" AS BIGINT) AS body_typ,
    CAST("MOD_YEAR" AS BIGINT) AS mod_year,
    CAST("REG_STAT" AS BIGINT) AS reg_stat,
    CAST("ROLLOVER" AS BIGINT) AS rollover,
    CAST("J_KNIFE" AS BIGINT) AS j_knife,
    CAST("TRAV_SP" AS BIGINT) AS trav_sp,
    CAST("TOW_VEH" AS BIGINT) AS tow_veh,
    CAST("SPEC_USE" AS BIGINT) AS spec_use,
    CAST("EMER_USE" AS BIGINT) AS emer_use,
    CAST("IMPACT1" AS BIGINT) AS impact1,
    CAST("IMPACT2" AS BIGINT) AS impact2,
    CAST("DEFORMED" AS BIGINT) AS deformed,
    CAST("IMPACTS" AS BIGINT) AS impacts,
    CAST("TOWAWAY" AS BIGINT) AS towaway,
    CAST("FIRE_EXP" AS BIGINT) AS fire_exp,
    CAST("OCUPANTS" AS BIGINT) AS ocupants,
    CAST("DEATHS" AS BIGINT) AS deaths,
    CAST("VEH_CF1" AS BIGINT) AS veh_cf1,
    CAST("VEH_CF2" AS BIGINT) AS veh_cf2,
    CAST("M_HARM" AS BIGINT) AS m_harm,
    CAST("CHAS_TR" AS BIGINT) AS chas_tr,
    CAST("WGTCD_TR" AS BIGINT) AS wgtcd_tr,
    CAST("VIN_LNGT" AS BIGINT) AS vin_lngt,
    "VIN_1" AS vin_1,
    "VIN_2" AS vin_2,
    "VIN_3" AS vin_3,
    "VIN_4" AS vin_4,
    "VIN_5" AS vin_5,
    "VIN_6" AS vin_6,
    "VIN_7" AS vin_7,
    "VIN_8" AS vin_8,
    "VIN_9" AS vin_9,
    "VIN_10" AS vin_10,
    "FLDCD_TR" AS fldcd_tr,
    "MCYCL_TY" AS mcycl_ty,
    CAST("DR_PRES" AS BIGINT) AS dr_pres,
    CAST("DR_DRINK" AS BIGINT) AS dr_drink,
    CAST("L_STATE" AS BIGINT) AS l_state,
    CAST("L_STATUS" AS BIGINT) AS l_status,
    CAST("L_RESTRI" AS BIGINT) AS l_restri,
    CAST("DR_TRAIN" AS BIGINT) AS dr_train,
    CAST("VIOL_CHG" AS BIGINT) AS viol_chg,
    CAST("PREV_ACC" AS BIGINT) AS prev_acc,
    CAST("PREV_SUS" AS BIGINT) AS prev_sus,
    CAST("PREV_DWI" AS BIGINT) AS prev_dwi,
    CAST("PREV_SPD" AS BIGINT) AS prev_spd,
    CAST("PREV_OTH" AS BIGINT) AS prev_oth,
    CAST("LAST_MO" AS BIGINT) AS last_mo,
    CAST("LAST_YR" AS BIGINT) AS last_yr,
    CAST("FIRST_MO" AS BIGINT) AS first_mo,
    CAST("FIRST_YR" AS BIGINT) AS first_yr,
    CAST("DR_CF1" AS BIGINT) AS dr_cf1,
    CAST("DR_CF2" AS BIGINT) AS dr_cf2,
    CAST("DR_CF3" AS BIGINT) AS dr_cf3,
    CAST("ST_CASE" AS BIGINT) AS st_case,
    CAST("MAK_MOD" AS BIGINT) AS mak_mod,
    CAST("VIN_WGT" AS BIGINT) AS vin_wgt,
    CAST("WHLBS_SH" AS BIGINT) AS whlbs_sh,
    CAST("WHLBS_LG" AS BIGINT) AS whlbs_lg,
    CAST("MCYCL_DS" AS BIGINT) AS mcycl_ds,
    "VINA_MOD" AS vina_mod,
    "SER_TR" AS ser_tr,
    "VIN" AS vin,
    CAST("HAZ_CARG" AS BIGINT) AS haz_carg,
    CAST("VEH_MAN" AS BIGINT) AS veh_man,
    CAST("L_CL_VEH" AS BIGINT) AS l_cl_veh,
    "VIN_BT" AS vin_bt,
    CAST("L_COMPL" AS BIGINT) AS l_compl,
    CAST("DR_ZIP" AS BIGINT) AS dr_zip,
    CAST("OWNER" AS BIGINT) AS owner,
    CAST("V_CONFIG" AS BIGINT) AS v_config,
    CAST("AXLES" AS BIGINT) AS axles,
    CAST("CARGO_BT" AS BIGINT) AS cargo_bt,
    CAST("AVOID" AS BIGINT) AS avoid,
    CAST("CDL_STAT" AS BIGINT) AS cdl_stat,
    CAST("L_ENDORS" AS BIGINT) AS l_endors,
    CAST("MONTH" AS BIGINT) AS month,
    CAST("UNDERIDE" AS BIGINT) AS underide,
    "VIN_11" AS vin_11,
    "VIN_12" AS vin_12,
    CAST("VIOLCHG1" AS BIGINT) AS violchg1,
    CAST("VIOLCHG2" AS BIGINT) AS violchg2,
    CAST("VIOLCHG3" AS BIGINT) AS violchg3,
    CAST("DR_CF4" AS BIGINT) AS dr_cf4,
    CAST("DR_WGT" AS BIGINT) AS dr_wgt,
    CAST("DR_HGT" AS BIGINT) AS dr_hgt,
    "MCARR_ID" AS mcarr_id,
    CAST("BUS_USE" AS BIGINT) AS bus_use,
    CAST("GVWR" AS BIGINT) AS gvwr,
    CAST("SEQ1" AS BIGINT) AS seq1,
    CAST("SEQ2" AS BIGINT) AS seq2,
    CAST("SEQ3" AS BIGINT) AS seq3,
    CAST("SEQ4" AS BIGINT) AS seq4,
    CAST("SEQ5" AS BIGINT) AS seq5,
    CAST("SEQ6" AS BIGINT) AS seq6,
    CAST("L_TYPE" AS BIGINT) AS l_type,
    CAST("UNITTYPE" AS BIGINT) AS unittype,
    CAST("HAZ_INV" AS BIGINT) AS haz_inv,
    CAST("HAZ_PLAC" AS BIGINT) AS haz_plac,
    CAST("HAZ_CNO" AS BIGINT) AS haz_cno,
    CAST("HAZ_REL" AS BIGINT) AS haz_rel,
    CAST("MCARR_I1" AS BIGINT) AS mcarr_i1,
    CAST("HAZ_ID" AS BIGINT) AS haz_id,
    "MCARR_I2" AS mcarr_i2,
    CAST("NUMOCCS" AS BIGINT) AS numoccs,
    CAST("ROLINLOC" AS BIGINT) AS rolinloc,
    CAST("TOWED" AS BIGINT) AS towed,
    CAST("SPEEDREL" AS BIGINT) AS speedrel,
    CAST("D_VISION1" AS BIGINT) AS d_vision1,
    CAST("D_VISION2" AS BIGINT) AS d_vision2,
    CAST("D_VISION3" AS BIGINT) AS d_vision3,
    CAST("DAY" AS BIGINT) AS day,
    CAST("HOUR" AS BIGINT) AS hour,
    CAST("MINUTE" AS BIGINT) AS minute,
    "VINTYPE" AS vintype,
    "VINMAKE" AS vinmake,
    CAST("VINMODYR" AS BIGINT) AS vinmodyr,
    "FUELCODE" AS fuelcode,
    CAST("VEH_SC1" AS BIGINT) AS veh_sc1,
    CAST("VEH_SC2" AS BIGINT) AS veh_sc2,
    CAST("DR_SF1" AS BIGINT) AS dr_sf1,
    CAST("DR_SF2" AS BIGINT) AS dr_sf2,
    CAST("DR_SF3" AS BIGINT) AS dr_sf3,
    CAST("DR_SF4" AS BIGINT) AS dr_sf4,
    CAST("VTRAFWAY" AS BIGINT) AS vtrafway,
    CAST("VNUM_LAN" AS BIGINT) AS vnum_lan,
    CAST("VSPD_LIM" AS BIGINT) AS vspd_lim,
    CAST("VALIGN" AS BIGINT) AS valign,
    CAST("VPROFILE" AS BIGINT) AS vprofile,
    CAST("VPAVETYP" AS BIGINT) AS vpavetyp,
    CAST("VSURCOND" AS BIGINT) AS vsurcond,
    CAST("VTRAFCON" AS BIGINT) AS vtrafcon,
    CAST("VTCONT_F" AS BIGINT) AS vtcont_f,
    CAST("P_CRASH1" AS BIGINT) AS p_crash1,
    CAST("P_CRASH2" AS BIGINT) AS p_crash2,
    CAST("P_CRASH3" AS BIGINT) AS p_crash3,
    CAST("PCRASH4" AS BIGINT) AS pcrash4,
    CAST("PCRASH5" AS BIGINT) AS pcrash5,
    CAST("ACC_TYPE" AS BIGINT) AS acc_type,
    "CARBUR" AS carbur,
    "CYLINDER" AS cylinder,
    "DISPLACE" AS displace,
    CAST("MCYCL_CY" AS BIGINT) AS mcycl_cy,
    "MCYCL_WT" AS mcycl_wt,
    "TIRE_SZE" AS tire_sze,
    "TON_RAT" AS ton_rat,
    "TRK_WT" AS trk_wt,
    "TRKWTVAR" AS trkwtvar,
    "VIN_REST" AS vin_rest,
    CAST("WHLDRWHL" AS BIGINT) AS whldrwhl,
    "STATENAME" AS statename,
    "NUMOCCSNAME" AS numoccsname,
    CAST("DAYNAME" AS BIGINT) AS dayname,
    "MONTHNAME" AS monthname,
    "HOURNAME" AS hourname,
    "MINUTENAME" AS minutename,
    "HARM_EVNAME" AS harm_evname,
    "MAN_COLLNAME" AS man_collname,
    "UNITTYPENAME" AS unittypename,
    "HIT_RUNNAME" AS hit_runname,
    "REG_STATNAME" AS reg_statname,
    "OWNERNAME" AS ownername,
    "MAKENAME" AS makename,
    "MAK_MODNAME" AS mak_modname,
    "BODY_TYPNAME" AS body_typname,
    "MOD_YEARNAME" AS mod_yearname,
    "VINNAME" AS vinname,
    "TOW_VEHNAME" AS tow_vehname,
    "J_KNIFENAME" AS j_knifename,
    "MCARR_I1NAME" AS mcarr_i1name,
    "MCARR_I2NAME" AS mcarr_i2name,
    "MCARR_IDNAME" AS mcarr_idname,
    "GVWRNAME" AS gvwrname,
    "V_CONFIGNAME" AS v_configname,
    "CARGO_BTNAME" AS cargo_btname,
    "HAZ_INVNAME" AS haz_invname,
    "HAZ_PLACNAME" AS haz_placname,
    "HAZ_IDNAME" AS haz_idname,
    "HAZ_CNONAME" AS haz_cnoname,
    "HAZ_RELNAME" AS haz_relname,
    "BUS_USENAME" AS bus_usename,
    "SPEC_USENAME" AS spec_usename,
    "EMER_USENAME" AS emer_usename,
    "TRAV_SPNAME" AS trav_spname,
    "UNDERIDENAME" AS underidename,
    "ROLLOVERNAME" AS rollovername,
    "ROLINLOCNAME" AS rolinlocname,
    "IMPACT1NAME" AS impact1name,
    "DEFORMEDNAME" AS deformedname,
    "TOWEDNAME" AS towedname,
    "M_HARMNAME" AS m_harmname,
    "VEH_SC1NAME" AS veh_sc1name,
    "VEH_SC2NAME" AS veh_sc2name,
    "FIRE_EXPNAME" AS fire_expname,
    "DR_PRESNAME" AS dr_presname,
    "L_STATENAME" AS l_statename,
    "DR_ZIPNAME" AS dr_zipname,
    "L_STATUSNAME" AS l_statusname,
    "L_TYPENAME" AS l_typename,
    "CDL_STATNAME" AS cdl_statname,
    "L_ENDORSNAME" AS l_endorsname,
    "L_COMPLNAME" AS l_complname,
    "L_RESTRINAME" AS l_restriname,
    "DR_HGTNAME" AS dr_hgtname,
    "DR_WGTNAME" AS dr_wgtname,
    "PREV_ACCNAME" AS prev_accname,
    "PREV_SUSNAME" AS prev_susname,
    "PREV_DWINAME" AS prev_dwiname,
    "PREV_SPDNAME" AS prev_spdname,
    "PREV_OTHNAME" AS prev_othname,
    "FIRST_MONAME" AS first_moname,
    "FIRST_YRNAME" AS first_yrname,
    "LAST_MONAME" AS last_moname,
    "LAST_YRNAME" AS last_yrname,
    "SPEEDRELNAME" AS speedrelname,
    "DR_SF1NAME" AS dr_sf1name,
    "DR_SF2NAME" AS dr_sf2name,
    "DR_SF3NAME" AS dr_sf3name,
    "DR_SF4NAME" AS dr_sf4name,
    "VTRAFWAYNAME" AS vtrafwayname,
    "VNUM_LANNAME" AS vnum_lanname,
    "VSPD_LIMNAME" AS vspd_limname,
    "VALIGNNAME" AS valignname,
    "VPROFILENAME" AS vprofilename,
    "VPAVETYPNAME" AS vpavetypname,
    "VSURCONDNAME" AS vsurcondname,
    "VTRAFCONNAME" AS vtrafconname,
    "VTCONT_FNAME" AS vtcont_fname,
    "P_CRASH1NAME" AS p_crash1name,
    "P_CRASH2NAME" AS p_crash2name,
    "P_CRASH3NAME" AS p_crash3name,
    "PCRASH4NAME" AS pcrash4name,
    "PCRASH5NAME" AS pcrash5name,
    "ACC_TYPENAME" AS acc_typename,
    "DR_DRINKNAME" AS dr_drinkname,
    "TRLR1VIN" AS trlr1vin,
    "TRLR1VINNAME" AS trlr1vinname,
    "TRLR2VIN" AS trlr2vin,
    "TRLR2VINNAME" AS trlr2vinname,
    "TRLR3VIN" AS trlr3vin,
    "TRLR3VINNAME" AS trlr3vinname,
    CAST("PREV_SUS1" AS BIGINT) AS prev_sus1,
    "PREV_SUS1NAME" AS prev_sus1name,
    CAST("PREV_SUS2" AS BIGINT) AS prev_sus2,
    "PREV_SUS2NAME" AS prev_sus2name,
    CAST("PREV_SUS3" AS BIGINT) AS prev_sus3,
    "PREV_SUS3NAME" AS prev_sus3name,
    CAST("VPICMAKE" AS BIGINT) AS vpicmake,
    "VPICMAKENAME" AS vpicmakename,
    CAST("VPICMODEL" AS BIGINT) AS vpicmodel,
    "VPICMODELNAME" AS vpicmodelname,
    CAST("VPICBODYCLASS" AS BIGINT) AS vpicbodyclass,
    "VPICBODYCLASSNAME" AS vpicbodyclassname,
    CAST("ICFINALBODY" AS BIGINT) AS icfinalbody,
    "ICFINALBODYNAME" AS icfinalbodyname,
    CAST("GVWR_FROM" AS BIGINT) AS gvwr_from,
    "GVWR_FROMNAME" AS gvwr_fromname,
    CAST("GVWR_TO" AS BIGINT) AS gvwr_to,
    "GVWR_TONAME" AS gvwr_toname,
    CAST("TRLR1GVWR" AS BIGINT) AS trlr1gvwr,
    "TRLR1GVWRNAME" AS trlr1gvwrname,
    CAST("TRLR2GVWR" AS BIGINT) AS trlr2gvwr,
    "TRLR2GVWRNAME" AS trlr2gvwrname,
    CAST("TRLR3GVWR" AS BIGINT) AS trlr3gvwr,
    "TRLR3GVWRNAME" AS trlr3gvwrname,
    CAST("UNDEROVERRIDE" AS BIGINT) AS underoverride,
    "UNDEROVERRIDENAME" AS underoverridename,
    CAST("ACC_CONFIG" AS BIGINT) AS acc_config,
    "ACC_CONFIGNAME" AS acc_configname,
    "case_year"
FROM "nhtsa-fars-vehicle"
