-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("STATE" AS BIGINT) AS state,
    CAST("COUNTY" AS BIGINT) AS county,
    CAST("MONTH" AS BIGINT) AS month,
    CAST("DAY" AS BIGINT) AS day,
    CAST("YEAR" AS BIGINT) AS year,
    CAST("HOUR" AS BIGINT) AS hour,
    CAST("MINUTE" AS BIGINT) AS minute,
    CAST("VE_FORMS" AS BIGINT) AS ve_forms,
    CAST("PERSONS" AS BIGINT) AS persons,
    CAST("VEHICLES" AS BIGINT) AS vehicles,
    CAST("LAND_USE" AS BIGINT) AS land_use,
    CAST("CL_TWAY" AS BIGINT) AS cl_tway,
    CAST("ROAD_FNC" AS BIGINT) AS road_fnc,
    CAST("TA_1_CL" AS BIGINT) AS ta_1_cl,
    CAST("SP_JUR" AS BIGINT) AS sp_jur,
    CAST("HARM_EV" AS BIGINT) AS harm_ev,
    CAST("MAN_COLL" AS BIGINT) AS man_coll,
    CAST("REL_JUNC" AS BIGINT) AS rel_junc,
    CAST("REL_ROAD" AS BIGINT) AS rel_road,
    CAST("ROAD_FLO" AS BIGINT) AS road_flo,
    CAST("NO_LANES" AS BIGINT) AS no_lanes,
    CAST("SP_LIMIT" AS BIGINT) AS sp_limit,
    CAST("ALIGNMNT" AS BIGINT) AS alignmnt,
    CAST("PROFILE" AS BIGINT) AS profile,
    CAST("PAVE_TYP" AS BIGINT) AS pave_typ,
    CAST("SUR_COND" AS BIGINT) AS sur_cond,
    CAST("TRA_CONT" AS BIGINT) AS tra_cont,
    CAST("LGT_COND" AS BIGINT) AS lgt_cond,
    CAST("WEATHER" AS BIGINT) AS weather,
    CAST("HIT_RUN" AS BIGINT) AS hit_run,
    CAST("C_M_ZONE" AS BIGINT) AS c_m_zone,
    CAST("NOT_HOUR" AS BIGINT) AS not_hour,
    CAST("NOT_MIN" AS BIGINT) AS not_min,
    CAST("ARR_HOUR" AS BIGINT) AS arr_hour,
    CAST("ARR_MIN" AS BIGINT) AS arr_min,
    CAST("SCH_BUS" AS BIGINT) AS sch_bus,
    CAST("CF1" AS BIGINT) AS cf1,
    CAST("CF2" AS BIGINT) AS cf2,
    CAST("CF3" AS BIGINT) AS cf3,
    CAST("FATALS" AS BIGINT) AS fatals,
    CAST("DAY_WEEK" AS BIGINT) AS day_week,
    CAST("DRUNK_DR" AS BIGINT) AS drunk_dr,
    CAST("ST_CASE" AS BIGINT) AS st_case,
    CAST("CITY" AS BIGINT) AS city,
    "RAIL" AS rail,
    CAST("FED_AID" AS BIGINT) AS fed_aid,
    CAST("TWAY_FLO" AS BIGINT) AS tway_flo,
    CAST("T_CONT_F" AS BIGINT) AS t_cont_f,
    CAST("MILEPT" AS BIGINT) AS milept,
    "TWAY_ID" AS tway_id,
    CAST("ROUTE" AS BIGINT) AS route,
    CAST("TRAF_FLO" AS BIGINT) AS traf_flo,
    CAST("HOSP_HR" AS BIGINT) AS hosp_hr,
    CAST("HOSP_MN" AS BIGINT) AS hosp_mn,
    CAST("PEDS" AS BIGINT) AS peds,
    CAST("NHS" AS BIGINT) AS nhs,
    CAST("LATITUDE" AS DOUBLE) AS latitude,
    "LONGITUD" AS longitud,
    "TWAY_ID2" AS tway_id2,
    CAST("VE_TOTAL" AS BIGINT) AS ve_total,
    CAST("WEATHER1" AS BIGINT) AS weather1,
    CAST("WEATHER2" AS BIGINT) AS weather2,
    CAST("WRK_ZONE" AS BIGINT) AS wrk_zone,
    CAST("RELJCT1" AS BIGINT) AS reljct1,
    CAST("RELJCT2" AS BIGINT) AS reljct2,
    CAST("TYP_INT" AS BIGINT) AS typ_int,
    CAST("PVH_INVL" AS BIGINT) AS pvh_invl,
    CAST("PERNOTMVIT" AS BIGINT) AS pernotmvit,
    CAST("PERMVIT" AS BIGINT) AS permvit,
    "STATENAME" AS statename,
    CAST("DAYNAME" AS BIGINT) AS dayname,
    "MONTHNAME" AS monthname,
    "DAY_WEEKNAME" AS day_weekname,
    "HOURNAME" AS hourname,
    "MINUTENAME" AS minutename,
    "NHSNAME" AS nhsname,
    "ROUTENAME" AS routename,
    CAST("RUR_URB" AS BIGINT) AS rur_urb,
    "RUR_URBNAME" AS rur_urbname,
    CAST("FUNC_SYS" AS BIGINT) AS func_sys,
    "FUNC_SYSNAME" AS func_sysname,
    CAST("RD_OWNER" AS BIGINT) AS rd_owner,
    "RD_OWNERNAME" AS rd_ownername,
    "MILEPTNAME" AS mileptname,
    "LATITUDENAME" AS latitudename,
    "LONGITUDNAME" AS longitudname,
    "SP_JURNAME" AS sp_jurname,
    "HARM_EVNAME" AS harm_evname,
    "MAN_COLLNAME" AS man_collname,
    "RELJCT1NAME" AS reljct1name,
    "RELJCT2NAME" AS reljct2name,
    "TYP_INTNAME" AS typ_intname,
    "WRK_ZONENAME" AS wrk_zonename,
    "REL_ROADNAME" AS rel_roadname,
    "LGT_CONDNAME" AS lgt_condname,
    "WEATHER1NAME" AS weather1name,
    "WEATHER2NAME" AS weather2name,
    "WEATHERNAME" AS weathername,
    "SCH_BUSNAME" AS sch_busname,
    "RAILNAME" AS railname,
    "NOT_HOURNAME" AS not_hourname,
    "NOT_MINNAME" AS not_minname,
    "ARR_HOURNAME" AS arr_hourname,
    "ARR_MINNAME" AS arr_minname,
    "HOSP_HRNAME" AS hosp_hrname,
    "HOSP_MNNAME" AS hosp_mnname,
    "CF1NAME" AS cf1name,
    "CF2NAME" AS cf2name,
    "CF3NAME" AS cf3name,
    "COUNTYNAME" AS countyname,
    "CITYNAME" AS cityname,
    "case_year"
FROM "nhtsa-fars-accident"
