-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "id_fundo",
    "cnpj",
    "cnpj_basico",
    "denominacao_social",
    strptime("data_registro", '%Y-%m-%d')::DATE AS data_registro,
    strptime("data_constituicao", '%Y-%m-%d')::DATE AS data_constituicao,
    "codigo_cvm",
    strptime("data_cancelamento", '%Y-%m-%d')::DATE AS data_cancelamento,
    "situacao",
    strptime("data_inicio_situacao", '%Y-%m-%d')::DATE AS data_inicio_situacao,
    strptime("data_inicio_atividade", '%Y-%m-%d')::DATE AS data_inicio_atividade,
    strptime("data_inicio_exercicio", '%Y-%m-%d')::DATE AS data_inicio_exercicio,
    strptime("data_fim_exercicio", '%Y-%m-%d')::DATE AS data_fim_exercicio,
    "classe",
    strptime("data_inicio_classe", '%Y-%m-%d')::DATE AS data_inicio_classe,
    "tipo_rentabilidade",
    "tipo_condominio",
    "indicador_fundo_cotas",
    "indicador_fundo_exclusivo",
    "indicador_tributacao_longo_prazo",
    "publico_alvo",
    "indicador_entidade_investimento",
    "taxa_perfomarnce",
    "informacoes_adicionais_taxa_performance",
    "taxa_administracao",
    "informacoes_adicionais_taxa_administracao",
    "valor_patrimonio_liquido",
    strptime("data_patrimonio_liquido", '%Y-%m-%d')::DATE AS data_patrimonio_liquido,
    "nome_diretor",
    "cnpj_administrador",
    "cnpj_basico_administrador",
    "nome_administrador",
    "indicador_pessoa_fisica_ou_juridica",
    "cpf_cnpj_gestor",
    "nome_gestor",
    "cnpj_auditor",
    "cnpj_basico_auditor",
    "nome_auditor",
    "cnpj_custodiante",
    "cnpj_basico_custodiante",
    "nome_custodiante",
    "cnpj_controlador",
    "cnpj_basico_controlador",
    "nome_controlador",
    "indicador_aplicacao_total_recursos_exterior"
FROM "base-dos-dados-br-cvm-fi--documentos-informacao-cadastral"
