-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "ano",
    "mes",
    "sigla_uf",
    "imposto_importacao",
    "imposto_exportacao",
    "ipi_fumo",
    "ipi_bebidas",
    "ipi_automoveis",
    "ipi_importacoes",
    "ipi_outros",
    "irpf",
    "irpj_entidades_financeiras",
    "irpj_demais_empresas",
    "irrf_rendimentos_trabalho",
    "irrf_rendimentos_capital",
    "irrf_remessas_exterior",
    "irrf_outros_rendimentos",
    "iof",
    "itr",
    "ipmf",
    "cpmf",
    "cofins",
    "cofins_entidades_financeiras",
    "cofins_demais_empresas",
    "pis_pasep",
    "pis_pasep_entidades_financeiras",
    "pis_pasep_demais_empresas",
    "csll",
    "csll_entidades_financeiras",
    "csll_demais_empresas",
    "cide_combustiveis_parcela_nao_dedutivel",
    "cide_combustiveis",
    "cpsss_1",
    "cpsss_2",
    "contribuicao_fundaf",
    "refis",
    "paes",
    "retencoes_fonte",
    "pagamento_unificado",
    "outras_receitas_rfb",
    "demais_receitas",
    "receita_previdenciaria",
    "receita_previdenciaria_propria",
    "receita_previdenciaria_demais",
    "receitas_outros_orgaos"
FROM "base-dos-dados-br-rf-arrecadacao--uf"
