-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "numero_processo",
    "numero_registro_oferta",
    "tipo_oferta",
    "tipo_componente_oferta_mista",
    "tipo_ativo",
    "cnpj_emissor",
    "nome_emissor",
    "cnpj_lider",
    "nome_lider",
    "nome_vendedor",
    "cnpj_ofertante",
    "nome_ofertante",
    "rito_oferta",
    "modalidade_oferta",
    "modalidade_registro",
    "modalidade_dispensa_registro",
    strptime("data_abertura_processo", '%Y-%m-%d')::DATE AS data_abertura_processo,
    strptime("data_protocolo", '%Y-%m-%d')::DATE AS data_protocolo,
    strptime("data_dispensa_oferta", '%Y-%m-%d')::DATE AS data_dispensa_oferta,
    strptime("data_registro_oferta", '%Y-%m-%d')::DATE AS data_registro_oferta,
    strptime("data_inicio_oferta", '%Y-%m-%d')::DATE AS data_inicio_oferta,
    strptime("data_encerramento_oferta", '%Y-%m-%d')::DATE AS data_encerramento_oferta,
    "emissao",
    "classe_ativo",
    "serie",
    "especie_ativo",
    "forma_ativo",
    strptime("data_emissao", '%Y-%m-%d')::DATE AS data_emissao,
    strptime("data_vencimento", '%Y-%m-%d')::DATE AS data_vencimento,
    "quantidade_sem_lote_suplementar",
    "quantidade_no_lote_suplementar",
    "quantidade_total",
    "preco_unitario",
    "valor_total",
    "oferta_inicial",
    "oferta_incentivo_fiscal",
    "oferta_regime_fiduciario",
    "atualizacao_monetaria",
    "juros",
    "projeto_audiovisual",
    "tipo_societario_emissor",
    "tipo_fundo_investimento",
    "ultimo_comunicado",
    strptime("data_comunicado", '%Y-%m-%d')::DATE AS data_comunicado
FROM "base-dos-dados-br-cvm-oferta-publica-distribuicao--dia"
