-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "ano",
    "mes",
    "id_upp",
    "upp",
    "hom_doloso",
    "lesao_corp_morte",
    "latrocinio",
    "hom_por_interv_policial",
    "tentat_hom",
    "lesao_corp_dolosa",
    "estupro",
    "hom_culposo",
    "lesao_corp_culposa",
    "roubo_comercio",
    "roubo_residencia",
    "roubo_veiculo",
    "roubo_carga",
    "roubo_transeunte",
    "roubo_em_coletivo",
    "roubo_banco",
    "roubo_cx_eletronico",
    "roubo_celular",
    "roubo_conducao_saque",
    "total_roubos",
    "furto_veiculos",
    "total_furtos",
    "sequestro",
    "extorsao",
    "sequestro_relampago",
    "estelionato",
    "apreensao_drogas",
    "recuperacao_veiculos",
    "armas_apreendidas",
    "cump_mandado_prisao",
    "ocorr_flagrante",
    "ameaca",
    "pessoas_desaparecidas",
    "encontro_cadaver",
    "encontro_ossada",
    "pol_militares_mortos_serv",
    "pol_civis_mortos_serv",
    "registro_ocorrencias"
FROM "base-dos-dados-br-isp-estatisticas-seguranca--evolucao-mensal-upp"
