"""Static catalog data for the EPI connector — the entity union plus the
mapping from indicator id to its display name and its CSV file inside the
State of Working America Data Library ZIP. Data, not logic."""

ENTITY_IDS = [
    'acs_hhincome',
    'annual_wage_ssa',
    'ceo_pay_ratio',
    'hourly_wage_gap_black_white',
    'hourly_wage_gap_gender',
    'hourly_wage_gap_hispanic_white',
    'hourly_wage_mean',
    'hourly_wage_median',
    'hourly_wage_payroll',
    'hourly_wage_percentile_ratios',
    'hourly_wage_percentiles',
    'hourly_wage_premium_college',
    'labor_force_annual_hours',
    'labor_force_emp',
    'labor_force_lf',
    'labor_force_lt_unemp',
    'labor_force_multjobs',
    'labor_force_payroll',
    'labor_force_pt',
    'labor_force_pt_econ',
    'labor_force_under_emp',
    'labor_force_unemp',
    'minimum_wage_levels',
    'population_civilian',
    'population_econ_insecure',
    'population_working_age',
    'poverty_opm_acs',
    'poverty_opm_cps',
    'poverty_spm',
    'price_indexes',
    'price_inflation',
    'productivity_growth',
    'productivity_levels',
    'union_members',
    'union_members_historical',
    'union_wage_gaps',
    'weekly_wage_gap_teacher',
]

# indicator id -> display name (the `indicator` column value inside the CSV)
INDICATOR_NAMES = {
    'acs_hhincome': 'Median household income',
    'annual_wage_ssa': 'Annual wages for select wage groups',
    'ceo_pay_ratio': 'CEO pay ratio',
    'hourly_wage_gap_black_white': 'Black-white wage gap',
    'hourly_wage_gap_gender': 'Gender wage gap',
    'hourly_wage_gap_hispanic_white': 'Hispanic-white wage gap',
    'hourly_wage_mean': 'Hourly wage, average',
    'hourly_wage_median': 'Hourly wage, median',
    'hourly_wage_payroll': 'Hourly earnings by industry',
    'hourly_wage_percentile_ratios': 'Hourly wage percentile ratios',
    'hourly_wage_percentiles': 'Hourly wage percentiles',
    'hourly_wage_premium_college': 'College wage premium',
    'labor_force_annual_hours': 'Time at work',
    'labor_force_emp': 'Employment by demographics',
    'labor_force_lf': 'Labor force participation',
    'labor_force_lt_unemp': 'Long-term unemployment',
    'labor_force_multjobs': 'Multiple jobs',
    'labor_force_payroll': 'Employment by industry (CES)',
    'labor_force_pt': 'Part-time employment',
    'labor_force_pt_econ': 'Part-time for economic reasons',
    'labor_force_under_emp': 'Underemployment',
    'labor_force_unemp': 'Unemployment',
    'minimum_wage_levels': 'Minimum wage',
    'population_civilian': 'Civilian population',
    'population_econ_insecure': 'Economically insecure population',
    'population_working_age': 'Working age population',
    'poverty_opm_acs': 'Official poverty (ACS)',
    'poverty_opm_cps': 'Official poverty (CPS)',
    'poverty_spm': 'Supplemental poverty',
    'price_indexes': 'Price indexes',
    'price_inflation': 'Inflation rates',
    'productivity_growth': 'Productivity and pay indexes',
    'productivity_levels': 'Productivity and pay levels',
    'union_members': 'Union membership',
    'union_members_historical': 'Historical union membership',
    'union_wage_gaps': 'Union wage premium',
    'weekly_wage_gap_teacher': 'Teacher pay gap',
}

# indicator id -> CSV filename inside epi_swa_data_library.zip
CSV_FILENAMES = {
    'acs_hhincome': 'median_household_income.csv',
    'annual_wage_ssa': 'annual_wages_for_select_wage_groups.csv',
    'ceo_pay_ratio': 'ceo_pay_ratio.csv',
    'hourly_wage_gap_black_white': 'black_white_wage_gap.csv',
    'hourly_wage_gap_gender': 'gender_wage_gap.csv',
    'hourly_wage_gap_hispanic_white': 'hispanic_white_wage_gap.csv',
    'hourly_wage_mean': 'hourly_wage_average.csv',
    'hourly_wage_median': 'hourly_wage_median.csv',
    'hourly_wage_payroll': 'hourly_earnings_by_industry.csv',
    'hourly_wage_percentile_ratios': 'hourly_wage_percentile_ratios.csv',
    'hourly_wage_percentiles': 'hourly_wage_percentiles.csv',
    'hourly_wage_premium_college': 'college_wage_premium.csv',
    'labor_force_annual_hours': 'time_at_work.csv',
    'labor_force_emp': 'employment_by_demographics.csv',
    'labor_force_lf': 'labor_force_participation.csv',
    'labor_force_lt_unemp': 'long_term_unemployment.csv',
    'labor_force_multjobs': 'multiple_jobs.csv',
    'labor_force_payroll': 'employment_by_industry_ces.csv',
    'labor_force_pt': 'part_time_employment.csv',
    'labor_force_pt_econ': 'part_time_for_economic_reasons.csv',
    'labor_force_under_emp': 'underemployment.csv',
    'labor_force_unemp': 'unemployment.csv',
    'minimum_wage_levels': 'minimum_wage.csv',
    'population_civilian': 'civilian_population.csv',
    'population_econ_insecure': 'economically_insecure_population.csv',
    'population_working_age': 'working_age_population.csv',
    'poverty_opm_acs': 'official_poverty_acs.csv',
    'poverty_opm_cps': 'official_poverty_cps.csv',
    'poverty_spm': 'supplemental_poverty.csv',
    'price_indexes': 'price_indexes.csv',
    'price_inflation': 'inflation_rates.csv',
    'productivity_growth': 'productivity_and_pay_indexes.csv',
    'productivity_levels': 'productivity_and_pay_levels.csv',
    'union_members': 'union_membership.csv',
    'union_members_historical': 'historical_union_membership.csv',
    'union_wage_gaps': 'union_wage_premium.csv',
    'weekly_wage_gap_teacher': 'teacher_pay_gap.csv',
}
