-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "iso3",
    "country",
    CAST("a1_court_recognized_human" AS BIGINT) AS a1_court_recognized_human,
    CAST("a1_court_recognized_human_1" AS BIGINT) AS a1_court_recognized_human_1,
    CAST("a1_drinking_water_as_a_human" AS BIGINT) AS a1_drinking_water_as_a_human,
    CAST("a1_drinking_water_as_a_human_1" AS BIGINT) AS a1_drinking_water_as_a_human_1,
    CAST("a1_drinking_water_as_a_human_2" AS BIGINT) AS a1_drinking_water_as_a_human_2,
    CAST("a1_sanitation_as_a_human" AS BIGINT) AS a1_sanitation_as_a_human,
    CAST("a1_sanitation_as_a_human_1" AS BIGINT) AS a1_sanitation_as_a_human_1,
    CAST("a1_sanitation_as_a_human_2" AS BIGINT) AS a1_sanitation_as_a_human_2,
    CAST("a2_has_national_development" AS BIGINT) AS a2_has_national_development,
    CAST("a2_ndp_addresses_drinking" AS BIGINT) AS a2_ndp_addresses_drinking,
    CAST("a2_ndp_addresses_sanitation" AS BIGINT) AS a2_ndp_addresses_sanitation,
    CAST("a2_ndp_end_year" AS BIGINT) AS a2_ndp_end_year,
    CAST("a2_ndp_start_year" AS BIGINT) AS a2_ndp_start_year,
    "a2_timeframe_for_development",
    CAST("a3_drinking_water_surveillance" AS BIGINT) AS a3_drinking_water_surveillance,
    CAST("a3_drinking_water_surveillance_1" AS BIGINT) AS a3_drinking_water_surveillance_1,
    CAST("a3_has_rural_drinking_water" AS BIGINT) AS a3_has_rural_drinking_water,
    CAST("a3_has_rural_national_drinking" AS BIGINT) AS a3_has_rural_national_drinking,
    CAST("a3_has_urban_drinking_water" AS BIGINT) AS a3_has_urban_drinking_water,
    CAST("a3_has_urban_national_drinking" AS BIGINT) AS a3_has_urban_national_drinking,
    CAST("a3_implementation_of_climate" AS DOUBLE) AS a3_implementation_of_climate,
    "a3_name_and_year_of_drinking",
    "a3_name_and_year_of_drinking_1",
    "a3_name_and_year_of_sanitation",
    "a3_name_and_year_of",
    CAST("a3_national_planning" AS BIGINT) AS a3_national_planning,
    CAST("a3_national_standards_or" AS BIGINT) AS a3_national_standards_or,
    CAST("a3_roles_and_responsibilities" AS BIGINT) AS a3_roles_and_responsibilities,
    CAST("a3_roles_and_responsibilities_1" AS BIGINT) AS a3_roles_and_responsibilities_1,
    CAST("a3_ww_surveillance" AS BIGINT) AS a3_ww_surveillance,
    CAST("a3_wwt_standards_for_faecal" AS BIGINT) AS a3_wwt_standards_for_faecal,
    CAST("a3_wwt_standards_for_onsite" AS BIGINT) AS a3_wwt_standards_for_onsite,
    CAST("a3_wwt_standards_for_safe" AS BIGINT) AS a3_wwt_standards_for_safe,
    CAST("a3_wwt_standards_for" AS BIGINT) AS a3_wwt_standards_for,
    CAST("a5_implementation_plan_status" AS DOUBLE) AS a5_implementation_plan_status,
    CAST("a5_implementation_plan_status_1" AS DOUBLE) AS a5_implementation_plan_status_1,
    CAST("a5_implementation_plan_status_2" AS DOUBLE) AS a5_implementation_plan_status_2,
    CAST("a5_implementation_plan_status_3" AS DOUBLE) AS a5_implementation_plan_status_3,
    CAST("a5_implementation_plan_status_4" AS DOUBLE) AS a5_implementation_plan_status_4,
    CAST("a5_implementation_plan_status_5" AS DOUBLE) AS a5_implementation_plan_status_5,
    CAST("a5_policy_status_rural" AS DOUBLE) AS a5_policy_status_rural,
    CAST("a5_policy_status_rural_1" AS DOUBLE) AS a5_policy_status_rural_1,
    CAST("a5_policy_status_urban" AS DOUBLE) AS a5_policy_status_urban,
    CAST("a5_policy_status_urban_1" AS DOUBLE) AS a5_policy_status_urban_1,
    CAST("a5_policy_status_wash_in" AS DOUBLE) AS a5_policy_status_wash_in,
    CAST("a5_policy_plans_address_access" AS BIGINT) AS a5_policy_plans_address_access,
    CAST("a5_policy_plans_address" AS BIGINT) AS a5_policy_plans_address,
    CAST("a5_policy_plans_address_1" AS BIGINT) AS a5_policy_plans_address_1,
    CAST("a5_policy_plans_address_hand" AS BIGINT) AS a5_policy_plans_address_hand,
    CAST("a5_policy_plans_address_2" AS BIGINT) AS a5_policy_plans_address_2,
    CAST("a5_policy_plans_address_risks" AS BIGINT) AS a5_policy_plans_address_risks,
    CAST("a5_policy_plans_address_safe" AS BIGINT) AS a5_policy_plans_address_safe,
    CAST("a5_rural_drinking_water_policy" AS BIGINT) AS a5_rural_drinking_water_policy,
    CAST("a5_rural_sanitation_policy" AS BIGINT) AS a5_rural_sanitation_policy,
    CAST("a5_urban_drinking_water_policy" AS BIGINT) AS a5_urban_drinking_water_policy,
    CAST("a5_urban_sanitation_policy" AS BIGINT) AS a5_urban_sanitation_policy,
    CAST("a5_wash_in_health_care" AS DOUBLE) AS a5_wash_in_health_care,
    "a6_lead_ministry_drinking",
    "a6_lead_ministry_hygiene",
    "a6_lead_ministry_sanitation",
    CAST("a7_latest_value_for_the" AS DOUBLE) AS a7_latest_value_for_the,
    CAST("a7_latest_value_for_the_1" AS BIGINT) AS a7_latest_value_for_the_1,
    CAST("a7_latest_value_for_the_2" AS DOUBLE) AS a7_latest_value_for_the_2,
    CAST("a7_latest_value_for_the_3" AS BIGINT) AS a7_latest_value_for_the_3,
    CAST("a7_target_value_national" AS DOUBLE) AS a7_target_value_national,
    CAST("a7_target_value_national_1" AS DOUBLE) AS a7_target_value_national_1,
    CAST("a7_target_year_national" AS BIGINT) AS a7_target_year_national,
    CAST("a7_target_year_national_1" AS BIGINT) AS a7_target_year_national_1,
    CAST("a12_mechanisms_to_coordinate" AS DOUBLE) AS a12_mechanisms_to_coordinate,
    "a12_name_of_formal",
    "a12_stakeholder_that_leads",
    CAST("survey_cycle" AS BIGINT) AS survey_cycle,
    "pa_s",
    CAST("a1_a_o_de_reconocimiento" AS BIGINT) AS a1_a_o_de_reconocimiento,
    CAST("a1_a_o_de_reconocimiento_1" AS BIGINT) AS a1_a_o_de_reconocimiento_1,
    CAST("a1_el_agua_potable_como" AS BIGINT) AS a1_el_agua_potable_como,
    CAST("a1_el_agua_potable_como_un" AS BIGINT) AS a1_el_agua_potable_como_un,
    CAST("a1_saneamiento_como_derecho" AS BIGINT) AS a1_saneamiento_como_derecho,
    CAST("a1_saneamiento_como_un_derecho" AS BIGINT) AS a1_saneamiento_como_un_derecho,
    CAST("a1_tribunal_reconoci_el" AS BIGINT) AS a1_tribunal_reconoci_el,
    CAST("a1_tribunal_reconoci_los" AS BIGINT) AS a1_tribunal_reconoci_los,
    CAST("a2_a_o_de_finalizaci_del" AS BIGINT) AS a2_a_o_de_finalizaci_del,
    CAST("a2_a_o_de_inicio_del_plan" AS BIGINT) AS a2_a_o_de_inicio_del_plan,
    CAST("a2_plan_de_desarrollo_que" AS BIGINT) AS a2_plan_de_desarrollo_que,
    CAST("a2_plan_de_desarrollo_que_1" AS BIGINT) AS a2_plan_de_desarrollo_que_1,
    "a2_plazo_de_tiempo_vigente",
    CAST("a2_tiene_un_plan_de_desarrollo" AS BIGINT) AS a2_tiene_un_plan_de_desarrollo,
    CAST("a3_est_ndares_de_wwt_para" AS BIGINT) AS a3_est_ndares_de_wwt_para,
    CAST("a3_estandares_o_directrices" AS BIGINT) AS a3_estandares_o_directrices,
    CAST("a3_funciones_y" AS BIGINT) AS a3_funciones_y,
    CAST("a3_funciones_y_1" AS BIGINT) AS a3_funciones_y_1,
    CAST("a3_implementaci_n_de_enfoques" AS DOUBLE) AS a3_implementaci_n_de_enfoques,
    CAST("a3_la_planificaci_n_nacional" AS BIGINT) AS a3_la_planificaci_n_nacional,
    "a3_nombre_y_a_o_de_est_ndares",
    "a3_nombre_y_a_o_de_est_ndares_1",
    "a3_nombre_y_a_o_de_los",
    "a3_nombre_y_a_o_de_saneamiento",
    CAST("a3_normas_de_wwt_para_lodo" AS BIGINT) AS a3_normas_de_wwt_para_lodo,
    CAST("a3_normas_de_wwt_para" AS BIGINT) AS a3_normas_de_wwt_para,
    CAST("a3_normas_de_wwt_para_1" AS BIGINT) AS a3_normas_de_wwt_para_1,
    CAST("a3_requisitos_de_vigilancia" AS BIGINT) AS a3_requisitos_de_vigilancia,
    CAST("a3_requisitos_de_vigilancia_1" AS BIGINT) AS a3_requisitos_de_vigilancia_1,
    CAST("a3_requisitos_de_vigilancia_2" AS BIGINT) AS a3_requisitos_de_vigilancia_2,
    CAST("a3_tiene_est_ndares_de" AS BIGINT) AS a3_tiene_est_ndares_de,
    CAST("a3_tiene_est_ndares_de_1" AS BIGINT) AS a3_tiene_est_ndares_de_1,
    CAST("a3_tiene_est_ndares_nacionales" AS BIGINT) AS a3_tiene_est_ndares_nacionales,
    CAST("a3_tiene_est_ndares_nacionales_1" AS BIGINT) AS a3_tiene_est_ndares_nacionales_1,
    CAST("a5_estado_de_la_pol_tica" AS DOUBLE) AS a5_estado_de_la_pol_tica,
    CAST("a5_estado_de_la_pol_tica_1" AS DOUBLE) AS a5_estado_de_la_pol_tica_1,
    CAST("a5_estado_de_la_pol_tica_2" AS DOUBLE) AS a5_estado_de_la_pol_tica_2,
    CAST("a5_estado_de_la_pol_tica_3" AS DOUBLE) AS a5_estado_de_la_pol_tica_3,
    CAST("a5_estado_de_la_pol_tica_4" AS DOUBLE) AS a5_estado_de_la_pol_tica_4,
    CAST("a5_estado_de_la_pol_tica_5" AS DOUBLE) AS a5_estado_de_la_pol_tica_5,
    CAST("a5_estado_del_plan_de_aplicaci" AS DOUBLE) AS a5_estado_del_plan_de_aplicaci,
    CAST("a5_estado_del_plan_de_aplicaci_1" AS DOUBLE) AS a5_estado_del_plan_de_aplicaci_1,
    CAST("a5_estado_del_plan_de" AS DOUBLE) AS a5_estado_del_plan_de,
    CAST("a5_estado_del_plan_de_1" AS DOUBLE) AS a5_estado_del_plan_de_1,
    CAST("a5_estado_del_plan_de_2" AS DOUBLE) AS a5_estado_del_plan_de_2,
    CAST("a5_estado_del_plan_de_3" AS DOUBLE) AS a5_estado_del_plan_de_3,
    CAST("a5_pol_tica_planes_que_aborda" AS BIGINT) AS a5_pol_tica_planes_que_aborda,
    CAST("a5_pol_tica_planes_que_aborda_1" AS BIGINT) AS a5_pol_tica_planes_que_aborda_1,
    CAST("a5_pol_tica_planes_que_abordan" AS BIGINT) AS a5_pol_tica_planes_que_abordan,
    CAST("a5_pol_tica_planes_que_abordan_1" AS BIGINT) AS a5_pol_tica_planes_que_abordan_1,
    CAST("a5_pol_tica_planes_que_abordan_2" AS BIGINT) AS a5_pol_tica_planes_que_abordan_2,
    CAST("a5_pol_tica_planes_que_abordan_3" AS BIGINT) AS a5_pol_tica_planes_que_abordan_3,
    CAST("a5_pol_tica_planes_que_abordan_4" AS BIGINT) AS a5_pol_tica_planes_que_abordan_4,
    CAST("a5_pol_tica_planes_que_abordan_5" AS BIGINT) AS a5_pol_tica_planes_que_abordan_5,
    CAST("a5_pol_tica_planes_que_abordan_6" AS BIGINT) AS a5_pol_tica_planes_que_abordan_6,
    CAST("a5_pol_tica_planes_que_abordan_7" AS BIGINT) AS a5_pol_tica_planes_que_abordan_7,
    CAST("a5_pol_tica_planes_que" AS BIGINT) AS a5_pol_tica_planes_que,
    "a6_ministerio_responsable",
    "a6_ministerio_responsable_1",
    "a6_ministerio_responsable_2",
    CAST("a7_a_o_objetivo_agua_potable" AS BIGINT) AS a7_a_o_objetivo_agua_potable,
    CAST("a7_a_o_objetivo_saneamiento" AS BIGINT) AS a7_a_o_objetivo_saneamiento,
    CAST("a7_ltimo_a_o_para_los" AS BIGINT) AS a7_ltimo_a_o_para_los,
    CAST("a7_ltimo_a_o_para_los_1" AS BIGINT) AS a7_ltimo_a_o_para_los_1,
    CAST("a7_ltimo_valor_para_los" AS DOUBLE) AS a7_ltimo_valor_para_los,
    CAST("a7_ltimo_valor_para_los_1" AS DOUBLE) AS a7_ltimo_valor_para_los_1,
    CAST("a7_valor_objetivo_agua_potable" AS DOUBLE) AS a7_valor_objetivo_agua_potable,
    CAST("a7_valor_objetivo_saneamiento" AS DOUBLE) AS a7_valor_objetivo_saneamiento,
    CAST("a12_mecanismos_de_coordinaci" AS DOUBLE) AS a12_mecanismos_de_coordinaci,
    "a12_nombre_del_mecanismo",
    "a12_parte_interesada_que",
    CAST("a_o_de_encuestas" AS BIGINT) AS a_o_de_encuestas,
    "source_resource"
FROM "idb-olas-simplified-glaas-wash-governance"
