-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "pais",
    "aux_region",
    "aux_tamano_empresa",
    "aux_actividad",
    "aux_sector",
    "q1",
    "q2",
    "q3",
    "q4_1",
    "q4_2",
    "q5",
    "q6_1",
    "q6_2",
    "q6_3",
    "q6_4",
    "q6_5",
    "q6_6",
    "q6_7",
    "q7",
    "q8",
    "q8_1",
    "q8_2",
    "q9",
    "q10",
    "q11",
    "q11_1",
    "q12",
    "q13",
    "q14",
    "q15",
    "q16",
    "q17",
    "q17_1",
    "q18",
    "q19",
    "q20",
    "q20_1",
    "q20_2",
    "q20_3",
    "q20_4",
    "q21",
    "q21_1",
    "q22",
    "q23",
    "q24",
    CAST("q25" AS BIGINT) AS q25,
    "q26",
    "q27",
    "q27_1",
    "source_resource"
FROM "idb-survey-of-exporting-firms-in-latin-america-and-the-caribbean-understanding-"
