-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("id" AS BIGINT) AS id,
    "country_name",
    "country_code",
    CAST("weight_r1" AS DOUBLE) AS weight_r1,
    CAST("weight_pop_r1" AS DOUBLE) AS weight_pop_r1,
    CAST("weight_panel" AS DOUBLE) AS weight_panel,
    CAST("weight_pop_panel" AS DOUBLE) AS weight_pop_panel,
    CAST("pop" AS DOUBLE) AS pop,
    CAST("country_factor" AS DOUBLE) AS country_factor,
    "survey_rounds_participated",
    "recordeddate",
    "genero_r1",
    CAST("edad_r1" AS BIGINT) AS edad_r1,
    "educ",
    "estcivil",
    CAST("nrhogar" AS BIGINT) AS nrhogar,
    CAST("nrhogar_antes" AS BIGINT) AS nrhogar_antes,
    "hayninhos",
    "ninos_5",
    CAST("nrninhos" AS BIGINT) AS nrninhos,
    CAST("matriculados" AS BIGINT) AS matriculados,
    "esc_publica",
    CAST("grado" AS BIGINT) AS grado,
    "haymayores",
    "diasmercado",
    "lugarmercado",
    "comprotodo",
    "nocompra_pan",
    "nocompra_vegetal",
    "nocompra_carne",
    "nocompra_envasados",
    "nocompra_bebidas",
    "nocompra_limpieza",
    "nocompra_medicinas",
    "nocompra_otro",
    "nrnegocios",
    "esperarfila",
    "subaprecios",
    "hambre",
    "menos_saludable",
    "vivienda",
    "probvivienda",
    "probvivienda_prox",
    "ayuda_alquiler",
    "sufialimento",
    "sufirecursos",
    "gasto_emergencia",
    CAST("monto_gasto" AS DOUBLE) AS monto_gasto,
    CAST("pre_cash" AS BOOLEAN) AS pre_cash,
    CAST("new_cash" AS BOOLEAN) AS new_cash,
    "coima",
    "tiene_banco",
    "tiene_tarjdebito",
    "tiene_segsaludpub",
    "tiene_segsaludpriv",
    "recibeprestamos",
    "darprestamos",
    "remesas_enero",
    CAST("remesas_origen" AS BIGINT) AS remesas_origen,
    "remesas_persona",
    "recibio_remesas",
    "lm_perdioempleo",
    "lm_cerronegocio_gob",
    "lm_cerronegocio_dem",
    "lm_asistmedica",
    "lm_perdioingrarriendo",
    "lm_dejoasistencia",
    CAST("lm_freq" AS BIGINT) AS lm_freq,
    "recibio_ayudaemp",
    "compromiso_futurotrabajo",
    "empleo_formal",
    "actividad_empleado",
    "actividad_negocio",
    "actividad_estudio",
    "trabajocasa",
    CAST("diastrabajo" AS BIGINT) AS diastrabajo,
    CAST("horastrabajo" AS BIGINT) AS horastrabajo,
    "sector",
    "redujo_ingreso_r1",
    "ingreso_jan2020_r1",
    "ingreso_apr2020_r1",
    "retorno_ingreso_r1",
    "sintoma_ninguno",
    "sintoma_garganta",
    "sintoma_gripe",
    "sintoma_sarpullido",
    "sintoma_fiebre",
    "sintoma_tos",
    CAST("conoce_sintomas" AS DOUBLE) AS conoce_sintomas,
    "infectados_sinsintomas",
    "sinsintomas_contagiar",
    "visito_trabajo",
    "visito_hospital",
    "visito_mercado",
    "visito_banco",
    "visito_amigos",
    "visito_familiares",
    "visito_ejercitar",
    "visito_iglesia",
    CAST("comotransmite" AS BIGINT) AS comotransmite,
    "sabe_comotransmite",
    "distsoc",
    "recom_trabajo",
    "recom_hospital",
    "recom_mercado",
    "recom_banco",
    "recom_amigos",
    "recom_familiares",
    "recom_ejercicio",
    "recom_iglesia",
    "haceds_hogar",
    "haceds_vecinos",
    "haceds_jovenes",
    "haceds_mayores",
    "haceds_otropais",
    "haceds_emplmercados",
    "medios_noti_redessociales",
    "medios_noti_chat",
    "medios_noti_periodicos",
    "medios_noti_tv",
    "medios_noti_radio",
    "medios_covid_redessociales",
    "medios_covid_chat",
    "medios_covid_periodicos",
    "medios_covid_tv",
    "medios_covid_radio",
    "nps_medio_redessoc",
    "nps_medio_sms",
    "nps_medio_periodico",
    "nps_medio_tv",
    "nps_medio_radio",
    "nps_medio_website",
    "nps_medio_otro",
    "s_ps_1",
    "s_ps_2",
    "s_ps_3",
    "s_ps_4",
    "s_ps_5",
    "s_ps_na",
    "s_ps_dk",
    "s_ps_6",
    "s_estado_ps1_ene_abr",
    "s_estado_ps1_may_jul",
    "s_estado_ps1_ago_nov",
    "s_estado_ps2_ene_abr",
    "s_estado_ps2_may_jul",
    "s_estado_ps2_ago_nov",
    "s_estado_ps3_ene_abr",
    "s_estado_ps3_may_jul",
    "s_estado_ps3_ago_nov",
    "s_estado_ps4_ene_abr",
    "s_estado_ps4_may_jul",
    "s_estado_ps4_ago_nov",
    "s_estado_ps5_ene_abr",
    "s_estado_ps5_may_jul",
    "s_estado_ps5_ago_nov",
    "s_estado_ps6_ene_abr",
    "s_estado_ps6_may_jul",
    "s_estado_ps6_ago_nov",
    "s_nopago_ps",
    "s_eleg_no_regis_ps1",
    "s_eleg_no_regis_ps2",
    "s_eleg_no_regis_ps3",
    "s_eleg_no_regis_ps4",
    "s_eleg_no_regis_ps5",
    "s_eleg_no_regis_na",
    "s_eleg_no_regis_dk",
    "s_eleg_no_regis_ps6",
    "s_m1_m4_eleg_no_regis_ps1",
    "s_m5_m7_eleg_no_regis_ps1",
    "s_m8_m11_eleg_no_regis_ps1",
    "s_mdk_eleg_no_regis_ps1",
    "s_m1_m4_eleg_no_regis_ps2",
    "s_m5_m7_eleg_no_regis_ps2",
    "s_m8_m11_eleg_no_regis_ps2",
    "s_mdk_eleg_no_regis_ps2",
    "s_m1_m4_eleg_no_regis_ps3",
    "s_m5_m7_eleg_no_regis_ps3",
    "s_m8_m11_eleg_no_regis_ps3",
    "s_mdk_eleg_no_regis_ps3",
    "s_m1_m4_eleg_no_regis_ps4",
    "s_m5_m7_eleg_no_regis_ps4",
    "s_m8_m11_eleg_no_regis_ps4",
    "s_mdk_eleg_no_regis_ps4",
    "s_m1_m4_eleg_no_regis_ps5",
    "s_m5_m7_eleg_no_regis_ps5",
    "s_m8_m11_eleg_no_regis_ps5",
    "s_mdk_eleg_no_regis_ps5",
    "s_m1_m4_eleg_no_regis_ps6",
    "s_m5_m7_eleg_no_regis_ps6",
    "s_m8_m11_eleg_no_regis_ps6",
    "s_mdk_eleg_no_regis_ps6",
    "s_finan_accs_cb_ene",
    "s_finan_mtransfer",
    CAST("s_finan_accs_cb_oct" AS BIGINT) AS s_finan_accs_cb_oct,
    "s_finan_cb_ene",
    "s_finan_bill_ene",
    "s_finan_no_cb_bill_ene",
    "s_finan_dk_cb_bill_ene",
    "s_finan_cb_oct",
    "s_finan_bill_oct",
    "s_finan_no_cb_bill_oct",
    "s_finan_dk_cb_bill_oct",
    "s_hambre",
    "habits1",
    "habits2",
    "habits3",
    "habits4",
    "asset_casa1",
    "asset_casa1_piso",
    "asset_casa1_pared",
    "asset_casa1_techo",
    "asset_casa1_ambientes",
    "asset_casa1_banos",
    "asset_mudanza",
    "asset_mudanza_m2_m4",
    "asset_mudanza_m5_m7",
    "asset_mudanza_m8_m10",
    "asset_mudanza_dk",
    "asset_casa2",
    "asset_casa2_piso",
    "asset_casa2_pared",
    "asset_casa2_techo",
    "asset_casa2_ambientes",
    CAST("asset_casa2_banos" AS BIGINT) AS asset_casa2_banos,
    CAST("asset_casa3" AS BIGINT) AS asset_casa3,
    "asset_casa3_piso",
    "asset_casa3_pared",
    "asset_casa3_techo",
    "asset_casa3_ambientes",
    "asset_casa3_banos",
    "asset_casa4",
    "asset_casa4_piso",
    "asset_casa4_pared",
    "asset_casa4_techo",
    "asset_casa4_ambientes",
    "asset_casa4_banos",
    "asset_casa1_elect",
    "asset_casa1_basura",
    "asset_casa1_agua",
    "asset_casa1_tv",
    "asset_casa1_internet",
    "asset_casa1_dk_svcios",
    "asset_casa1_cocinar",
    "asset_casa2_elect",
    "asset_casa2_basura",
    "asset_casa2_agua",
    "asset_casa2_tv",
    "asset_casa2_internet",
    "asset_casa2_cocinar_made",
    "asset_casa2_cocinar_carb",
    "asset_casa2_cocinar_quero",
    "asset_casa2_cocinar_gas",
    "asset_casa2_cocinar_elect",
    "asset_casa2_cocinar_dk",
    "asset_casa3_elect",
    "asset_casa3_basura",
    "asset_casa3_agua",
    "asset_casa3_tv",
    "asset_casa3_internet",
    "asset_casa3_cocinar_made",
    "asset_casa3_cocinar_carb",
    "asset_casa3_cocinar_quero",
    "asset_casa3_cocinar_gas",
    "asset_casa3_cocinar_elect",
    "asset_casa3_cocinar_dk",
    "asset_casa4_elect",
    "asset_casa4_basura",
    "asset_casa4_agua",
    "asset_casa4_tv",
    "asset_casa4_internet",
    "asset_casa4_cocinar_made",
    "asset_casa4_cocinar_carb",
    "asset_casa4_cocinar_quero",
    "asset_casa4_cocinar_gas",
    "asset_casa4_cocinar_elect",
    "asset_casa4_cocinar_dk",
    "asset_nhogar_m1_seg",
    "asset_nhogar_m4_seg",
    "asset_nhogar_m7_seg",
    "asset_nhogar_m10_seg",
    "asset_o_carro_ene",
    "asset_o_compu_ene",
    "asset_o_celintel_ene",
    "asset_o_celbasic_ene",
    "asset_o_telfijo_ene",
    "asset_o_nevera_ene",
    "asset_o_lavadora_ene",
    "asset_o_estufa_ene",
    "asset_o_tv_ene",
    "asset_o_dk_ene",
    "asset_b_carro_m2_m11",
    "asset_s_carro_m2_m11",
    "asset_no_bs_carro_m2_m11",
    "asset_b_compu_m2_m11",
    "asset_s_compu_m2_m11",
    "asset_no_bs_compu_m2_m11",
    "asset_b_celintel_m2_m11",
    "asset_s_celintel_m2_m11",
    "asset_no_bs_celintel_m2_m11",
    "asset_b_celbasic_m2_m11",
    "asset_s_celbasic_m2_m11",
    "asset_no_bs_celbasic_m2_m11",
    "asset_b_telfijo_m2_m11",
    "asset_s_telfijo_m2_m11",
    "asset_no_bs_telfijo_m2_m11",
    "asset_b_nevera_m2_m11",
    "asset_s_nevera_m2_m11",
    "asset_no_bs_nevera_m2_m11",
    "asset_b_lavadora_m2_m11",
    "asset_s_lavadora_m2_m11",
    "asset_no_bs_lavadora_m2_m11",
    "asset_b_estufa_m2_m11",
    "asset_s_estufa_m2_m11",
    "asset_no_bs_estufa_m2_m11",
    "asset_b_tv_m2_m11",
    "asset_s_tv_m2_m11",
    "asset_no_bs_tv_m2_m11",
    CAST("asset_b_carro_num" AS BIGINT) AS asset_b_carro_num,
    CAST("asset_b_compu_num" AS BIGINT) AS asset_b_compu_num,
    CAST("asset_b_celintel_num" AS BIGINT) AS asset_b_celintel_num,
    CAST("asset_b_celbasic_num" AS BIGINT) AS asset_b_celbasic_num,
    CAST("asset_b_telfijo_num" AS BIGINT) AS asset_b_telfijo_num,
    CAST("asset_b_nevera_num" AS BIGINT) AS asset_b_nevera_num,
    CAST("asset_b_lavadora_num" AS BIGINT) AS asset_b_lavadora_num,
    CAST("asset_b_estufa_num" AS BIGINT) AS asset_b_estufa_num,
    CAST("asset_b_tv_num" AS BIGINT) AS asset_b_tv_num,
    CAST("asset_b_carro_mes" AS BIGINT) AS asset_b_carro_mes,
    CAST("asset_b_compu_mes" AS BIGINT) AS asset_b_compu_mes,
    CAST("asset_b_celintel_mes" AS BIGINT) AS asset_b_celintel_mes,
    CAST("asset_b_celbasic_mes" AS BIGINT) AS asset_b_celbasic_mes,
    CAST("asset_b_telfijo_mes" AS BIGINT) AS asset_b_telfijo_mes,
    CAST("asset_b_nevera_mes" AS BIGINT) AS asset_b_nevera_mes,
    CAST("asset_b_lavadora_mes" AS BIGINT) AS asset_b_lavadora_mes,
    CAST("asset_b_estufa_mes" AS BIGINT) AS asset_b_estufa_mes,
    CAST("asset_b_tv_mes" AS BIGINT) AS asset_b_tv_mes,
    CAST("asset_s_carro_num" AS BIGINT) AS asset_s_carro_num,
    CAST("asset_s_compu_num" AS BIGINT) AS asset_s_compu_num,
    CAST("asset_s_celintel_num" AS BIGINT) AS asset_s_celintel_num,
    CAST("asset_s_celbasic_num" AS BIGINT) AS asset_s_celbasic_num,
    CAST("asset_s_telfijo_num" AS BIGINT) AS asset_s_telfijo_num,
    CAST("asset_s_nevera_num" AS BIGINT) AS asset_s_nevera_num,
    CAST("asset_s_lavadora_num" AS BIGINT) AS asset_s_lavadora_num,
    CAST("asset_s_estufa_num" AS BIGINT) AS asset_s_estufa_num,
    CAST("asset_s_tv_num" AS BIGINT) AS asset_s_tv_num,
    CAST("asset_s_carro_mes" AS BIGINT) AS asset_s_carro_mes,
    CAST("asset_s_compu_mes" AS BIGINT) AS asset_s_compu_mes,
    CAST("asset_s_celintel_mes" AS BIGINT) AS asset_s_celintel_mes,
    CAST("asset_s_celbasic_mes" AS BIGINT) AS asset_s_celbasic_mes,
    CAST("asset_s_telfijo_mes" AS BIGINT) AS asset_s_telfijo_mes,
    CAST("asset_s_nevera_mes" AS BIGINT) AS asset_s_nevera_mes,
    CAST("asset_s_lavadora_mes" AS BIGINT) AS asset_s_lavadora_mes,
    CAST("asset_s_estufa_mes" AS BIGINT) AS asset_s_estufa_mes,
    CAST("asset_s_tv_mes" AS BIGINT) AS asset_s_tv_mes,
    "redist1_1",
    "redist1_2",
    "redist1_3",
    "redist2_1",
    "redist2_2",
    "redist2_3",
    "covidpolicy_1",
    "covidpolicy_2",
    "covidpolicy_3",
    "covidpolicy_4",
    "labor1_nhogar",
    "labor1_nhogar_mayores",
    "labor3_tbjo_emp_ene",
    "labor3_tbjo_pneg_ene",
    "labor3_tbjo_fam_ene",
    "labor3_educ_ene",
    "labor4_ss_ene",
    "labor5_contrato_ene",
    "labor6_tbjo_emp_abr",
    "labor6_tbjo_emp_jul",
    "labor6_tbjo_emp_oct",
    "labor6_tbjo_pneg_abr",
    "labor6_tbjo_pneg_jul",
    "labor6_tbjo_pneg_oct",
    "labor6_tbjo_fam_abr",
    "labor6_tbjo_fam_jul",
    "labor6_tbjo_fam_oct",
    "labor6_educ_abr",
    "labor6_educ_jul",
    "labor6_educ_oct",
    "labor12_tbjo_emp_sp",
    "labor12_tbjo_pneg_sp",
    "labor12_tbjo_fam_sp",
    "labor12_educ_sp",
    "labor13_b_tbjo",
    "labor13_b_tbjo_mh",
    "labor13a_r2",
    "labor13a_r3",
    "labor13a_r4",
    "labor13a_r5",
    "labor13a_r6",
    "labor13a_r7",
    "labor13a_r1",
    CAST("labor14_nh_tbjo_ene" AS BIGINT) AS labor14_nh_tbjo_ene,
    CAST("labor15_nh_cto_ene" AS BIGINT) AS labor15_nh_cto_ene,
    CAST("labor16a_nh_tbjo_abr" AS BIGINT) AS labor16a_nh_tbjo_abr,
    CAST("labor16b_nh_tbjo_jul" AS BIGINT) AS labor16b_nh_tbjo_jul,
    CAST("labor16c_nh_tbjo_oct" AS BIGINT) AS labor16c_nh_tbjo_oct,
    CAST("labor16d_nh_tbjo_sp" AS BIGINT) AS labor16d_nh_tbjo_sp,
    "labor17_accidente",
    "labor17_clinica",
    "labor17_muerte",
    "labor17_f_svcios",
    "labor17_dk",
    "labor17_na",
    "labor18_pn_num",
    "labor19_pn_num_abr",
    "labor19_pn_num_jul",
    "labor19_pn_num_oct",
    "labor19_pn_num_sp",
    "labor20_nnegocio",
    "labor21_nn_mes",
    "labor22_tnegocio",
    "labor23_anegocio",
    "labor24_s1",
    "labor24_s2",
    "labor24_s3",
    "labor24_s4",
    "labor24_s5",
    "labor24_s6",
    "labor24_s7",
    "labor25_feq_c1",
    "labor25_feq_c2",
    "labor25_feq_c3",
    "labor25_feq_c4",
    "labor25_feq_c5",
    "diaedu1",
    "diaedu3",
    "diaedu4",
    "diaedu5",
    "diapan1",
    "diapan2",
    "diapan3",
    "diaedu2_1",
    "diaedu2_2",
    "genero_r2",
    "edad_r2",
    "ingreso_jan2020_r2",
    "ingreso_apr2020_r2",
    "ingreso_jul2020_r2",
    "ingreso_oct2020_r2",
    "source_resource"
FROM "idb-second-round-of-coronavirus-idb-cornell-survey-and-panel-data-2020"
