-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("idhabitus" AS BIGINT) AS idhabitus,
    CAST("persona" AS BIGINT) AS persona,
    CAST("prov" AS BIGINT) AS prov,
    CAST("cant" AS BIGINT) AS cant,
    CAST("parr" AS BIGINT) AS parr,
    CAST("ciudad" AS BIGINT) AS ciudad,
    "area",
    CAST("bl" AS BIGINT) AS bl,
    CAST("w1" AS BIGINT) AS w1,
    CAST("w2" AS BIGINT) AS w2,
    CAST("w3" AS BIGINT) AS w3,
    CAST("w4" AS BIGINT) AS w4,
    CAST("panel" AS BIGINT) AS panel,
    "treatment",
    "quint_selben",
    "DRaircon0" AS draircon0,
    "DRbike0" AS drbike0,
    "DRblender0" AS drblender0,
    "DRbwtv0" AS drbwtv0,
    "DRcar0" AS drcar0,
    "DRcolortv0" AS drcolortv0,
    "DRcomputer0" AS drcomputer0,
    "DRfan0" AS drfan0,
    "DRfridge0" AS drfridge0,
    "DRiron0" AS driron0,
    "DRmixer0" AS drmixer0,
    "DRmotorc0" AS drmotorc0,
    "DRoven0" AS droven0,
    "DRradio0" AS drradio0,
    "DRsewing0" AS drsewing0,
    "DRstereo0" AS drstereo0,
    "DRstove0" AS drstove0,
    "DRstovepl0" AS drstovepl0,
    "DRtypewr0" AS drtypewr0,
    "DRvhsdvd0" AS drvhsdvd0,
    "DRwaffle0" AS drwaffle0,
    "DRwasher0" AS drwasher0,
    CAST("NDRaircon0" AS BIGINT) AS ndraircon0,
    CAST("NDRbike0" AS BIGINT) AS ndrbike0,
    CAST("NDRblender0" AS BIGINT) AS ndrblender0,
    CAST("NDRbwtv0" AS BIGINT) AS ndrbwtv0,
    CAST("NDRcar0" AS BIGINT) AS ndrcar0,
    CAST("NDRcolortv0" AS BIGINT) AS ndrcolortv0,
    CAST("NDRcomputer0" AS BIGINT) AS ndrcomputer0,
    CAST("NDRfan0" AS BIGINT) AS ndrfan0,
    CAST("NDRfridge0" AS BIGINT) AS ndrfridge0,
    CAST("NDRiron0" AS BIGINT) AS ndriron0,
    CAST("NDRmixer0" AS BIGINT) AS ndrmixer0,
    CAST("NDRmotorc0" AS BIGINT) AS ndrmotorc0,
    CAST("NDRoven0" AS BIGINT) AS ndroven0,
    CAST("NDRradio0" AS BIGINT) AS ndrradio0,
    CAST("NDRsewing0" AS BIGINT) AS ndrsewing0,
    CAST("NDRstereo0" AS BIGINT) AS ndrstereo0,
    CAST("NDRstove0" AS BIGINT) AS ndrstove0,
    CAST("NDRstovepl0" AS BIGINT) AS ndrstovepl0,
    CAST("NDRtypewr0" AS BIGINT) AS ndrtypewr0,
    CAST("NDRvhsdvd0" AS BIGINT) AS ndrvhsdvd0,
    CAST("NDRwaffle0" AS BIGINT) AS ndrwaffle0,
    CAST("NDRwasher0" AS BIGINT) AS ndrwasher0,
    "DRblender2" AS drblender2,
    "DRcar2" AS drcar2,
    "DRcell2" AS drcell2,
    "DRcolortv2" AS drcolortv2,
    "DRcomputer2" AS drcomputer2,
    "DRfridge2" AS drfridge2,
    "DRiron2" AS driron2,
    "DRmicrowave2" AS drmicrowave2,
    "DRmixer2" AS drmixer2,
    "DRphone2" AS drphone2,
    "DRstereo2" AS drstereo2,
    "DRstove2" AS drstove2,
    "DRvhsdvd2" AS drvhsdvd2,
    "DRwasher2" AS drwasher2,
    CAST("NDRblender2" AS BIGINT) AS ndrblender2,
    CAST("NDRcar2" AS BIGINT) AS ndrcar2,
    CAST("NDRcell2" AS BIGINT) AS ndrcell2,
    CAST("NDRcolortv2" AS BIGINT) AS ndrcolortv2,
    CAST("NDRcomputer2" AS BIGINT) AS ndrcomputer2,
    CAST("NDRfridge2" AS BIGINT) AS ndrfridge2,
    CAST("NDRiron2" AS BIGINT) AS ndriron2,
    CAST("NDRmicrowave2" AS BIGINT) AS ndrmicrowave2,
    CAST("NDRmixer2" AS BIGINT) AS ndrmixer2,
    CAST("NDRphone2" AS BIGINT) AS ndrphone2,
    CAST("NDRstereo2" AS BIGINT) AS ndrstereo2,
    CAST("NDRstove2" AS BIGINT) AS ndrstove2,
    CAST("NDRvhsdvd2" AS BIGINT) AS ndrvhsdvd2,
    CAST("NDRwasher2" AS BIGINT) AS ndrwasher2,
    "Hgarbage0" AS hgarbage0,
    "Hlights0" AS hlights0,
    "Hwater0" AS hwater0,
    "Hshower0" AS hshower0,
    "Htoilet0" AS htoilet0,
    "Hfuel0" AS hfuel0,
    "Hgarbage2" AS hgarbage2,
    "Hlights2" AS hlights2,
    "Hwater2" AS hwater2,
    "Hshower2" AS hshower2,
    "Htoilet2" AS htoilet2,
    "Hfuel2" AS hfuel2,
    "Hheat2" AS hheat2,
    "Hgas2" AS hgas2,
    "Hroof0" AS hroof0,
    "Hwalls0" AS hwalls0,
    "Hfloor0" AS hfloor0,
    "Hroof1" AS hroof1,
    "Hwalls1" AS hwalls1,
    "Hfloor1" AS hfloor1,
    "Hroof2" AS hroof2,
    "Hwalls2" AS hwalls2,
    "Hfloor2" AS hfloor2,
    CAST("Hbedrooms0" AS BIGINT) AS hbedrooms0,
    CAST("Hbedrooms2" AS BIGINT) AS hbedrooms2,
    CAST("Hrooms0" AS BIGINT) AS hrooms0,
    CAST("Hrooms2" AS BIGINT) AS hrooms2,
    "Htenure0" AS htenure0,
    "Htenure2" AS htenure2,
    "Htype0" AS htype0,
    "Htype2" AS htype2,
    "Hfarm0" AS hfarm0,
    CAST("Hfarm2" AS BIGINT) AS hfarm2,
    "Hfarmten0" AS hfarmten0,
    "Hfarmten2" AS hfarmten2,
    CAST("Haltitude0" AS BIGINT) AS haltitude0,
    CAST("Efood2" AS DOUBLE) AS efood2,
    CAST("Enfood2" AS DOUBLE) AS enfood2,
    CAST("Epcexp2" AS DOUBLE) AS epcexp2,
    CAST("Erent2" AS DOUBLE) AS erent2,
    CAST("Eschool2" AS DOUBLE) AS eschool2,
    CAST("Etotexp2" AS DOUBLE) AS etotexp2,
    CAST("Eutil2" AS DOUBLE) AS eutil2,
    CAST("ln_pcexp0_hat1" AS DOUBLE) AS ln_pcexp0_hat1,
    CAST("ln_pcexp0_hat2" AS DOUBLE) AS ln_pcexp0_hat2,
    CAST("ln_totexp0_hat1" AS DOUBLE) AS ln_totexp0_hat1,
    CAST("ln_totexp0_hat2" AS DOUBLE) AS ln_totexp0_hat2,
    "Csex" AS csex,
    "Crelate0" AS crelate0,
    "Crelate1" AS crelate1,
    "Crelate2" AS crelate2,
    CAST("Cagemo0" AS BIGINT) AS cagemo0,
    CAST("Cagemo1" AS BIGINT) AS cagemo1,
    CAST("Cagemo2" AS BIGINT) AS cagemo2,
    CAST("Cagemo3" AS BIGINT) AS cagemo3,
    CAST("Cagemo4" AS BIGINT) AS cagemo4,
    "Cbio0" AS cbio0,
    "Cbio1" AS cbio1,
    "Cbio2" AS cbio2,
    "Cdisable0" AS cdisable0,
    "Clanguage0" AS clanguage0,
    "Clanguage1" AS clanguage1,
    "Clanguage2" AS clanguage2,
    "Clit0" AS clit0,
    "Clit1" AS clit1,
    "Chighgrade1" AS chighgrade1,
    CAST("Chighgrade2" AS BIGINT) AS chighgrade2,
    CAST("Cesc3" AS BIGINT) AS cesc3,
    CAST("Cesc4" AS BIGINT) AS cesc4,
    "Cinschool2" AS cinschool2,
    CAST("Cinschool3" AS BIGINT) AS cinschool3,
    CAST("Cinschool4" AS BIGINT) AS cinschool4,
    "Mrelate0" AS mrelate0,
    "Mrelate1" AS mrelate1,
    "Mrelate2" AS mrelate2,
    "Cmomhome0" AS cmomhome0,
    "Cmomhome1" AS cmomhome1,
    "Cmomhome2" AS cmomhome2,
    CAST("Cmomhome3" AS BIGINT) AS cmomhome3,
    CAST("Cmomhome4" AS BIGINT) AS cmomhome4,
    "Cmomwhynot0" AS cmomwhynot0,
    "Cmomwhynot1" AS cmomwhynot1,
    "Cmomwhynot2" AS cmomwhynot2,
    "Cmomwhynot3" AS cmomwhynot3,
    "Cmomwhynot4" AS cmomwhynot4,
    CAST("Cmomdead0" AS BIGINT) AS cmomdead0,
    CAST("Cmomdead1" AS BIGINT) AS cmomdead1,
    CAST("Cmomdead2" AS BIGINT) AS cmomdead2,
    CAST("Cmomdead3" AS BIGINT) AS cmomdead3,
    CAST("Cmomdead4" AS BIGINT) AS cmomdead4,
    CAST("Cmommig0" AS BIGINT) AS cmommig0,
    CAST("Cmommig1" AS BIGINT) AS cmommig1,
    CAST("Cmommig2" AS BIGINT) AS cmommig2,
    CAST("Cmommig3" AS BIGINT) AS cmommig3,
    CAST("Cmommig4" AS BIGINT) AS cmommig4,
    CAST("Cmomyrleft0" AS BIGINT) AS cmomyrleft0,
    "Cmomyrleft1" AS cmomyrleft1,
    "Cmomyrleft2" AS cmomyrleft2,
    "Cmomyrleft3" AS cmomyrleft3,
    CAST("Cmomyrleft4" AS BIGINT) AS cmomyrleft4,
    CAST("Medyrs0" AS BIGINT) AS medyrs0,
    CAST("Medyrs1" AS BIGINT) AS medyrs1,
    CAST("Medyrs2" AS BIGINT) AS medyrs2,
    CAST("Medyrs3" AS BIGINT) AS medyrs3,
    CAST("Medyrs4" AS BIGINT) AS medyrs4,
    "Medcat0" AS medcat0,
    "Medcat1" AS medcat1,
    "Medcat2" AS medcat2,
    CAST("Mage0" AS BIGINT) AS mage0,
    CAST("Mage1" AS BIGINT) AS mage1,
    CAST("Mage2" AS BIGINT) AS mage2,
    CAST("Mage3" AS BIGINT) AS mage3,
    CAST("Mage4" AS BIGINT) AS mage4,
    "Mmrd0" AS mmrd0,
    "Mmrd1" AS mmrd1,
    "Mmrd2" AS mmrd2,
    "Mmrd3" AS mmrd3,
    "Mmrd4" AS mmrd4,
    "Mdisable0" AS mdisable0,
    "Mlanguage0" AS mlanguage0,
    "Mlanguage3" AS mlanguage3,
    "Mlanguage4" AS mlanguage4,
    "Mlit0" AS mlit0,
    "Mrace1" AS mrace1,
    "Mrace2" AS mrace2,
    "Mrace3" AS mrace3,
    "Mrace4" AS mrace4,
    "Mworkpay1" AS mworkpay1,
    "Mworkpay2" AS mworkpay2,
    CAST("Mworkpay3" AS BIGINT) AS mworkpay3,
    CAST("Mworkpay4" AS BIGINT) AS mworkpay4,
    CAST("Mpayhrs1" AS BIGINT) AS mpayhrs1,
    CAST("Mpayhrs2" AS BIGINT) AS mpayhrs2,
    CAST("Mpayhrs3" AS BIGINT) AS mpayhrs3,
    CAST("Mpayhrs4" AS BIGINT) AS mpayhrs4,
    "Mworknopay1" AS mworknopay1,
    "Mworknopay2" AS mworknopay2,
    CAST("Mnopayhrs1" AS BIGINT) AS mnopayhrs1,
    CAST("Mnopayhrs2" AS BIGINT) AS mnopayhrs2,
    "Cdadhome0" AS cdadhome0,
    "Cdadhome1" AS cdadhome1,
    "Cdadhome2" AS cdadhome2,
    CAST("Cdadhome3" AS BIGINT) AS cdadhome3,
    "Cdadwhynot0" AS cdadwhynot0,
    "Cdadwhynot1" AS cdadwhynot1,
    "Cdadwhynot2" AS cdadwhynot2,
    CAST("Cdaddead0" AS BIGINT) AS cdaddead0,
    CAST("Cdaddead1" AS BIGINT) AS cdaddead1,
    CAST("Cdaddead2" AS BIGINT) AS cdaddead2,
    CAST("Cdadmig0" AS BIGINT) AS cdadmig0,
    CAST("Cdadmig1" AS BIGINT) AS cdadmig1,
    CAST("Cdadmig2" AS BIGINT) AS cdadmig2,
    "Cdadyrleft0" AS cdadyrleft0,
    "Cdadyrleft1" AS cdadyrleft1,
    "Cdadyrleft2" AS cdadyrleft2,
    CAST("Cdadedyrs0" AS BIGINT) AS cdadedyrs0,
    CAST("Cdadedyrs1" AS BIGINT) AS cdadedyrs1,
    CAST("Cdadedyrs2" AS BIGINT) AS cdadedyrs2,
    "Cdadedcat0" AS cdadedcat0,
    "Cdadedcat1" AS cdadedcat1,
    "Cdadedcat2" AS cdadedcat2,
    CAST("F0t50" AS BIGINT) AS f0t50,
    CAST("F6t140" AS BIGINT) AS f6t140,
    CAST("F15t440" AS BIGINT) AS f15t440,
    CAST("F45t640" AS BIGINT) AS f45t640,
    CAST("F65p0" AS BIGINT) AS f65p0,
    CAST("M0t50" AS BIGINT) AS m0t50,
    CAST("M6t140" AS BIGINT) AS m6t140,
    CAST("M15t440" AS BIGINT) AS m15t440,
    CAST("M45t640" AS BIGINT) AS m45t640,
    CAST("M65p0" AS BIGINT) AS m65p0,
    CAST("F0t51" AS BIGINT) AS f0t51,
    CAST("F6t141" AS BIGINT) AS f6t141,
    CAST("F15t441" AS BIGINT) AS f15t441,
    CAST("F45t641" AS BIGINT) AS f45t641,
    CAST("F65p1" AS BIGINT) AS f65p1,
    CAST("M0t51" AS BIGINT) AS m0t51,
    CAST("M6t141" AS BIGINT) AS m6t141,
    CAST("M15t441" AS BIGINT) AS m15t441,
    CAST("M45t641" AS BIGINT) AS m45t641,
    CAST("M65p1" AS BIGINT) AS m65p1,
    CAST("F0t52" AS BIGINT) AS f0t52,
    CAST("F6t142" AS BIGINT) AS f6t142,
    CAST("F15t442" AS BIGINT) AS f15t442,
    CAST("F45t642" AS BIGINT) AS f45t642,
    CAST("F65p2" AS BIGINT) AS f65p2,
    CAST("M0t52" AS BIGINT) AS m0t52,
    CAST("M6t142" AS BIGINT) AS m6t142,
    CAST("M15t442" AS BIGINT) AS m15t442,
    CAST("M45t642" AS BIGINT) AS m45t642,
    CAST("M65p2" AS BIGINT) AS m65p2,
    CAST("Hmaxed0" AS BIGINT) AS hmaxed0,
    CAST("Hmaxed1" AS BIGINT) AS hmaxed1,
    CAST("Hmaxed2" AS BIGINT) AS hmaxed2,
    CAST("Hmaxed3" AS BIGINT) AS hmaxed3,
    CAST("Hmaxed4" AS BIGINT) AS hmaxed4,
    "Chstat0" AS chstat0,
    "Chstat1" AS chstat1,
    "Chstat2" AS chstat2,
    "Cbedday0" AS cbedday0,
    "Cbedday1" AS cbedday1,
    "Cbedday2" AS cbedday2,
    CAST("Cnbeddays0" AS BIGINT) AS cnbeddays0,
    CAST("Cnbeddays1" AS BIGINT) AS cnbeddays1,
    CAST("Cnbeddays2" AS BIGINT) AS cnbeddays2,
    "Chlthcard0" AS chlthcard0,
    "Chlthcard1" AS chlthcard1,
    "Canyvac0" AS canyvac0,
    "Canyvac1" AS canyvac1,
    CAST("Cnumvac0" AS BIGINT) AS cnumvac0,
    CAST("Cnumvac1" AS BIGINT) AS cnumvac1,
    "Cothvac0" AS cothvac0,
    "Cothvac1" AS cothvac1,
    CAST("Cwherevac0" AS BIGINT) AS cwherevac0,
    CAST("Cwherevac1" AS BIGINT) AS cwherevac1,
    "Chlthins0" AS chlthins0,
    "Chlthins1" AS chlthins1,
    "Chlthins2" AS chlthins2,
    CAST("Chmintravel0" AS BIGINT) AS chmintravel0,
    CAST("Chmintravel1" AS BIGINT) AS chmintravel1,
    CAST("Chmintravel2" AS BIGINT) AS chmintravel2,
    CAST("Chlthvisits0" AS BIGINT) AS chlthvisits0,
    "Chlthwhy0" AS chlthwhy0,
    CAST("Cadjhemo0" AS DOUBLE) AS cadjhemo0,
    CAST("Cadjhemo1" AS DOUBLE) AS cadjhemo1,
    CAST("Cadjhemo2" AS DOUBLE) AS cadjhemo2,
    "Cvac010" AS cvac010,
    "Cvac020" AS cvac020,
    "Cvac030" AS cvac030,
    "Cvac040" AS cvac040,
    "Cvac050" AS cvac050,
    "Cvac060" AS cvac060,
    "Cvac070" AS cvac070,
    "Cvac080" AS cvac080,
    "Cvac090" AS cvac090,
    "Cvac100" AS cvac100,
    "Cvac110" AS cvac110,
    "Cvac120" AS cvac120,
    "Cvac130" AS cvac130,
    "Cvac140" AS cvac140,
    "Cvac150" AS cvac150,
    "Cvac160" AS cvac160,
    "Cvac170" AS cvac170,
    "Cvac180" AS cvac180,
    "Cvac190" AS cvac190,
    "Cvac200" AS cvac200,
    "Cvacbcg0" AS cvacbcg0,
    "Cvacbcg1" AS cvacbcg1,
    "Cvacdpt0" AS cvacdpt0,
    "Cvacdpt1" AS cvacdpt1,
    "Cvachepb0" AS cvachepb0,
    "Cvachepb1" AS cvachepb1,
    "Cvacmal0" AS cvacmal0,
    "Cvacmal1" AS cvacmal1,
    "Cvacsar0" AS cvacsar0,
    "Cvacsar1" AS cvacsar1,
    "Cvacpolio0" AS cvacpolio0,
    "Cvacpolio1" AS cvacpolio1,
    CAST("Cage01gc0" AS BIGINT) AS cage01gc0,
    CAST("Cage02gc0" AS BIGINT) AS cage02gc0,
    CAST("Cage03gc0" AS BIGINT) AS cage03gc0,
    CAST("Cage04gc0" AS BIGINT) AS cage04gc0,
    CAST("Cage05gc0" AS BIGINT) AS cage05gc0,
    CAST("Cage06gc0" AS BIGINT) AS cage06gc0,
    CAST("Cage07gc0" AS BIGINT) AS cage07gc0,
    CAST("Cage08gc0" AS BIGINT) AS cage08gc0,
    CAST("Cage09gc0" AS BIGINT) AS cage09gc0,
    CAST("Cage10gc0" AS BIGINT) AS cage10gc0,
    CAST("Cage11gc0" AS BIGINT) AS cage11gc0,
    CAST("Cage12gc0" AS BIGINT) AS cage12gc0,
    CAST("Cage13gc0" AS BIGINT) AS cage13gc0,
    CAST("Cage14gc0" AS BIGINT) AS cage14gc0,
    CAST("Cage15gc0" AS BIGINT) AS cage15gc0,
    CAST("Cage16gc0" AS BIGINT) AS cage16gc0,
    CAST("Cage17gc0" AS BIGINT) AS cage17gc0,
    CAST("Cage18gc0" AS BIGINT) AS cage18gc0,
    CAST("Cage19gc0" AS BIGINT) AS cage19gc0,
    CAST("Cage20gc0" AS BIGINT) AS cage20gc0,
    CAST("Cage21gc0" AS BIGINT) AS cage21gc0,
    CAST("Cage22gc0" AS BIGINT) AS cage22gc0,
    CAST("Cage23gc0" AS BIGINT) AS cage23gc0,
    CAST("Cage24gc0" AS BIGINT) AS cage24gc0,
    CAST("Cage25gc0" AS BIGINT) AS cage25gc0,
    "Cage26gc0" AS cage26gc0,
    "Cage27gc0" AS cage27gc0,
    "Cage28gc0" AS cage28gc0,
    "Cage29gc0" AS cage29gc0,
    "Cage30gc0" AS cage30gc0,
    CAST("Ckg01gc0" AS DOUBLE) AS ckg01gc0,
    CAST("Ckg02gc0" AS DOUBLE) AS ckg02gc0,
    CAST("Ckg03gc0" AS DOUBLE) AS ckg03gc0,
    CAST("Ckg04gc0" AS DOUBLE) AS ckg04gc0,
    CAST("Ckg05gc0" AS DOUBLE) AS ckg05gc0,
    CAST("Ckg06gc0" AS DOUBLE) AS ckg06gc0,
    CAST("Ckg07gc0" AS DOUBLE) AS ckg07gc0,
    CAST("Ckg08gc0" AS DOUBLE) AS ckg08gc0,
    CAST("Ckg09gc0" AS DOUBLE) AS ckg09gc0,
    CAST("Ckg10gc0" AS DOUBLE) AS ckg10gc0,
    CAST("Ckg11gc0" AS DOUBLE) AS ckg11gc0,
    CAST("Ckg12gc0" AS DOUBLE) AS ckg12gc0,
    CAST("Ckg13gc0" AS DOUBLE) AS ckg13gc0,
    CAST("Ckg14gc0" AS DOUBLE) AS ckg14gc0,
    CAST("Ckg15gc0" AS DOUBLE) AS ckg15gc0,
    "Ckg16gc0" AS ckg16gc0,
    CAST("Ckg17gc0" AS DOUBLE) AS ckg17gc0,
    "Ckg18gc0" AS ckg18gc0,
    CAST("Ckg19gc0" AS DOUBLE) AS ckg19gc0,
    "Ckg20gc0" AS ckg20gc0,
    CAST("Ckg21gc0" AS DOUBLE) AS ckg21gc0,
    CAST("Ckg22gc0" AS DOUBLE) AS ckg22gc0,
    CAST("Ckg23gc0" AS DOUBLE) AS ckg23gc0,
    CAST("Ckg24gc0" AS BIGINT) AS ckg24gc0,
    CAST("Ckg25gc0" AS BIGINT) AS ckg25gc0,
    "Ckg26gc0" AS ckg26gc0,
    "Ckg27gc0" AS ckg27gc0,
    "Ckg28gc0" AS ckg28gc0,
    "Ckg29gc0" AS ckg29gc0,
    "Ckg30gc0" AS ckg30gc0,
    "Cgrthcont0" AS cgrthcont0,
    "Cgrthcont1" AS cgrthcont1,
    "Cgrthcont2" AS cgrthcont2,
    CAST("Cngrthcont0" AS BIGINT) AS cngrthcont0,
    CAST("Cngrthcont1" AS BIGINT) AS cngrthcont1,
    CAST("Cngrthcont2" AS BIGINT) AS cngrthcont2,
    "Cwheregcont0" AS cwheregcont0,
    "Cwheregcont1" AS cwheregcont1,
    "Cwheregcont2" AS cwheregcont2,
    "Cwhogcont0" AS cwhogcont0,
    "Cgotiron0" AS cgotiron0,
    "Cgotiron1" AS cgotiron1,
    CAST("Cgotiron2" AS BIGINT) AS cgotiron2,
    CAST("Cnumiron0" AS BIGINT) AS cnumiron0,
    CAST("Cnumiron1" AS BIGINT) AS cnumiron1,
    CAST("Cnumiron2" AS BIGINT) AS cnumiron2,
    "CgotvitA0" AS cgotvita0,
    "CgotvitA1" AS cgotvita1,
    CAST("CgotvitA2" AS BIGINT) AS cgotvita2,
    CAST("CnumvitA0" AS BIGINT) AS cnumvita0,
    CAST("CnumvitA1" AS BIGINT) AS cnumvita1,
    CAST("CnumvitA2" AS BIGINT) AS cnumvita2,
    "Cfood_bread0" AS cfood_bread0,
    "Cfood_bread1" AS cfood_bread1,
    "Cfood_carrot0" AS cfood_carrot0,
    "Cfood_carrot1" AS cfood_carrot1,
    "Cfood_chard0" AS cfood_chard0,
    "Cfood_chard1" AS cfood_chard1,
    "Cfood_citrus0" AS cfood_citrus0,
    "Cfood_citrus1" AS cfood_citrus1,
    "Cfood_cowv0" AS cfood_cowv0,
    "Cfood_cowv1" AS cfood_cowv1,
    "Cfood_fruit0" AS cfood_fruit0,
    "Cfood_fruit1" AS cfood_fruit1,
    "Cfood_liver0" AS cfood_liver0,
    "Cfood_liver1" AS cfood_liver1,
    CAST("Cnfood_fruit0" AS BIGINT) AS cnfood_fruit0,
    CAST("Cnfood_fruit1" AS BIGINT) AS cnfood_fruit1,
    CAST("Cnfood_liver0" AS BIGINT) AS cnfood_liver0,
    CAST("Cnfood_liver1" AS BIGINT) AS cnfood_liver1,
    CAST("Cnfood_bread0" AS BIGINT) AS cnfood_bread0,
    CAST("Cnfood_bread1" AS BIGINT) AS cnfood_bread1,
    CAST("Cnfood_carrot0" AS BIGINT) AS cnfood_carrot0,
    CAST("Cnfood_carrot1" AS BIGINT) AS cnfood_carrot1,
    CAST("Cnfood_chard0" AS BIGINT) AS cnfood_chard0,
    CAST("Cnfood_chard1" AS BIGINT) AS cnfood_chard1,
    CAST("Cnfood_citrus0" AS BIGINT) AS cnfood_citrus0,
    CAST("Cnfood_citrus1" AS BIGINT) AS cnfood_citrus1,
    CAST("Cnfood_cowv0" AS BIGINT) AS cnfood_cowv0,
    CAST("Cnfood_cowv1" AS BIGINT) AS cnfood_cowv1,
    "Cfood_candy1" AS cfood_candy1,
    "Cfood_cookie1" AS cfood_cookie1,
    "Cfood_fried1" AS cfood_fried1,
    "Cfood_soda1" AS cfood_soda1,
    CAST("Cnfood_candy1" AS BIGINT) AS cnfood_candy1,
    CAST("Cnfood_cookie1" AS BIGINT) AS cnfood_cookie1,
    CAST("Cnfood_fried1" AS BIGINT) AS cnfood_fried1,
    CAST("Cnfood_soda1" AS BIGINT) AS cnfood_soda1,
    "Cbfed0" AS cbfed0,
    "Cbfed1" AS cbfed1,
    "CbfedWN0" AS cbfedwn0,
    CAST("Cbfedmonths0" AS BIGINT) AS cbfedmonths0,
    CAST("Cbfedmonths1" AS BIGINT) AS cbfedmonths1,
    "Cbfedcurr0" AS cbfedcurr0,
    "Cbfedcurr1" AS cbfedcurr1,
    CAST("Cbfedlstnite0" AS BIGINT) AS cbfedlstnite0,
    "Cbfedsugar0" AS cbfedsugar0,
    "Cbfedsolids0" AS cbfedsolids0,
    "Cresp0" AS cresp0,
    "Cresp1" AS cresp1,
    "Cresp2" AS cresp2,
    CAST("Cnresp0" AS BIGINT) AS cnresp0,
    CAST("Cnresp1" AS BIGINT) AS cnresp1,
    CAST("Cnresp2" AS BIGINT) AS cnresp2,
    "Cresptreat0" AS cresptreat0,
    "Cresptreat1" AS cresptreat1,
    CAST("CrespWN0" AS BIGINT) AS crespwn0,
    "Crespwhere0" AS crespwhere0,
    "Crespwhere1" AS crespwhere1,
    "Cdiar0" AS cdiar0,
    "Cdiar1" AS cdiar1,
    "Cdiar2" AS cdiar2,
    CAST("Cndiar0" AS BIGINT) AS cndiar0,
    CAST("Cndiar1" AS BIGINT) AS cndiar1,
    CAST("Cndiar2" AS BIGINT) AS cndiar2,
    "Cdiartreat0" AS cdiartreat0,
    "Cdiartreat1" AS cdiartreat1,
    "Cdiarwhere0" AS cdiarwhere0,
    "Cdiarwhere1" AS cdiarwhere1,
    CAST("CdiarWN0" AS BIGINT) AS cdiarwn0,
    "Cdiar_IVfluids0" AS cdiar_ivfluids0,
    "Cdiar_ORT0" AS cdiar_ort0,
    "Cdiar_antib0" AS cdiar_antib0,
    "Cdiar_dryskin0" AS cdiar_dryskin0,
    "Cdiar_homemade0" AS cdiar_homemade0,
    "Cdiar_liquids0" AS cdiar_liquids0,
    "Cdiar_pedialyte0" AS cdiar_pedialyte0,
    "Cdiar_solids0" AS cdiar_solids0,
    "Cdiar_syrup0" AS cdiar_syrup0,
    "Cdiar_teajuice0" AS cdiar_teajuice0,
    "Chosp0" AS chosp0,
    "Chosp1" AS chosp1,
    CAST("Cnhosp0" AS BIGINT) AS cnhosp0,
    CAST("Cnhosp1" AS BIGINT) AS cnhosp1,
    "Ccond_asthma0" AS ccond_asthma0,
    "Ccond_asthma1" AS ccond_asthma1,
    "Ccond_bronc0" AS ccond_bronc0,
    "Ccond_bronc1" AS ccond_bronc1,
    "Ccond_bronc2" AS ccond_bronc2,
    "Ccond_diab0" AS ccond_diab0,
    "Ccond_diab1" AS ccond_diab1,
    "Ccond_epilep0" AS ccond_epilep0,
    "Ccond_epilep1" AS ccond_epilep1,
    "Ccond_headach0" AS ccond_headach0,
    "Ccond_headach1" AS ccond_headach1,
    "Ccond_headach2" AS ccond_headach2,
    "Ccond_hearing0" AS ccond_hearing0,
    "Ccond_hearing1" AS ccond_hearing1,
    "Ccond_hearing2" AS ccond_hearing2,
    "Ccond_heart0" AS ccond_heart0,
    "Ccond_heart1" AS ccond_heart1,
    "Ccond_retard0" AS ccond_retard0,
    "Ccond_retard1" AS ccond_retard1,
    "Ccond_sight0" AS ccond_sight0,
    "Ccond_sight1" AS ccond_sight1,
    "Ccond_sight2" AS ccond_sight2,
    CAST("Ccond_sight3" AS BIGINT) AS ccond_sight3,
    "Ccond_sinus0" AS ccond_sinus0,
    "CMP0" AS cmp0,
    "CMP1" AS cmp1,
    "CMPWN0" AS cmpwn0,
    "CMP_free0" AS cmp_free0,
    "CMP_ate0" AS cmp_ate0,
    "CMP_ate1" AS cmp_ate1,
    CAST("CMP_ateWN0" AS BIGINT) AS cmp_atewn0,
    "CMP_adults0" AS cmp_adults0,
    "CMP_animals0" AS cmp_animals0,
    "CMP_okids0" AS cmp_okids0,
    "CMP_sibs0" AS cmp_sibs0,
    "Cprogram0" AS cprogram0,
    "Cprogram1" AS cprogram1,
    CAST("Cprogram_days0" AS BIGINT) AS cprogram_days0,
    CAST("Cprogram_days1" AS BIGINT) AS cprogram_days1,
    CAST("Cprogram_hrs0" AS BIGINT) AS cprogram_hrs0,
    CAST("Cprogram_hrs1" AS BIGINT) AS cprogram_hrs1,
    "Cprogram_fd0" AS cprogram_fd0,
    "Cchildcare0" AS cchildcare0,
    "Cchildcare1" AS cchildcare1,
    "Cchildcare2" AS cchildcare2,
    "Cwhodaycare02" AS cwhodaycare02,
    "Cwhodaycare12" AS cwhodaycare12,
    "Cwhodaycare22" AS cwhodaycare22,
    "Cwhodaycare32" AS cwhodaycare32,
    "Cwhodaycare42" AS cwhodaycare42,
    "Cwhodaycare52" AS cwhodaycare52,
    "Cwhichdaycare02" AS cwhichdaycare02,
    "Cwhichdaycare12" AS cwhichdaycare12,
    "Cwhichdaycare22" AS cwhichdaycare22,
    "Cwhichdaycare32" AS cwhichdaycare32,
    "Cwhichdaycare42" AS cwhichdaycare42,
    "Cwhichdaycare52" AS cwhichdaycare52,
    CAST("Cmnthsdaycare02" AS BIGINT) AS cmnthsdaycare02,
    CAST("Cmnthsdaycare12" AS BIGINT) AS cmnthsdaycare12,
    CAST("Cmnthsdaycare22" AS BIGINT) AS cmnthsdaycare22,
    CAST("Cmnthsdaycare32" AS BIGINT) AS cmnthsdaycare32,
    CAST("Cmnthsdaycare42" AS BIGINT) AS cmnthsdaycare42,
    CAST("Cmnthsdaycare52" AS BIGINT) AS cmnthsdaycare52,
    CAST("Cattendnow02" AS BIGINT) AS cattendnow02,
    CAST("Cattendnow12" AS BIGINT) AS cattendnow12,
    CAST("Cattendnow22" AS BIGINT) AS cattendnow22,
    CAST("Cattendnow32" AS BIGINT) AS cattendnow32,
    CAST("Cattendnow42" AS BIGINT) AS cattendnow42,
    CAST("Cattendnow52" AS BIGINT) AS cattendnow52,
    "Cformaldaycare02" AS cformaldaycare02,
    "Cformaldaycare12" AS cformaldaycare12,
    "Cformaldaycare22" AS cformaldaycare22,
    "Cformaldaycare32" AS cformaldaycare32,
    "Cformaldaycare42" AS cformaldaycare42,
    "Cformaldaycare52" AS cformaldaycare52,
    CAST("Cbooks0" AS BIGINT) AS cbooks0,
    CAST("Cbooks1" AS BIGINT) AS cbooks1,
    CAST("Cbooks2" AS BIGINT) AS cbooks2,
    CAST("Cread1" AS BIGINT) AS cread1,
    "Cread2" AS cread2,
    "Creadwho0" AS creadwho0,
    CAST("Creadtime0" AS BIGINT) AS creadtime0,
    CAST("Creadtime1" AS BIGINT) AS creadtime1,
    CAST("Creadtime2" AS BIGINT) AS creadtime2,
    CAST("Mharshtot0" AS BIGINT) AS mharshtot0,
    CAST("Mharshtot1" AS BIGINT) AS mharshtot1,
    CAST("Mharshtot4" AS BIGINT) AS mharshtot4,
    CAST("Mcoldtot0" AS BIGINT) AS mcoldtot0,
    CAST("Mcoldtot1" AS BIGINT) AS mcoldtot1,
    CAST("Mcoldtot4" AS BIGINT) AS mcoldtot4,
    CAST("Mhometot0" AS BIGINT) AS mhometot0,
    CAST("Mhometot1" AS BIGINT) AS mhometot1,
    CAST("Mhometot4" AS BIGINT) AS mhometot4,
    "Cstory1" AS cstory1,
    "Cstory2" AS cstory2,
    "Mpunbelt1" AS mpunbelt1,
    "Mpunslap1" AS mpunslap1,
    "Mpunyell1" AS mpunyell1,
    "Mpunother1" AS mpunother1,
    "Cmhit2" AS cmhit2,
    CAST("Cmnhit2" AS BIGINT) AS cmnhit2,
    "Cmshout2" AS cmshout2,
    CAST("Cmnshout2" AS BIGINT) AS cmnshout2,
    "Cmspank2" AS cmspank2,
    CAST("Cmnspank2" AS BIGINT) AS cmnspank2,
    CAST("Cmnotv2" AS BIGINT) AS cmnotv2,
    CAST("Cmpnsho2" AS BIGINT) AS cmpnsho2,
    CAST("Cmtalk2" AS BIGINT) AS cmtalk2,
    "Cohit2" AS cohit2,
    CAST("Conhit2" AS BIGINT) AS conhit2,
    "Coshout2" AS coshout2,
    CAST("Conshout2" AS BIGINT) AS conshout2,
    "Cospank2" AS cospank2,
    CAST("Conspank2" AS BIGINT) AS conspank2,
    CAST("Conotv2" AS BIGINT) AS conotv2,
    CAST("Copnsho2" AS BIGINT) AS copnsho2,
    CAST("Cotalk2" AS BIGINT) AS cotalk2,
    "FAManswer2" AS famanswer2,
    "FAMcpresent2" AS famcpresent2,
    "FAMforbid2" AS famforbid2,
    "FAMhit2" AS famhit2,
    "FAMhostile2" AS famhostile2,
    "FAMkiss2" AS famkiss2,
    "FAMpositive2" AS fampositive2,
    "FAMpraise2" AS fampraise2,
    "FAMscold2" AS famscold2,
    "FAMshout2" AS famshout2,
    "FAMteach2" AS famteach2,
    "FAMwords2" AS famwords2,
    "Crepeat_ever2" AS crepeat_ever2,
    CAST("Crepeat_initial2" AS BIGINT) AS crepeat_initial2,
    CAST("Crepeat_scnd2" AS BIGINT) AS crepeat_scnd2,
    CAST("Cnrepeat_gr12" AS BIGINT) AS cnrepeat_gr12,
    CAST("Cnrepeat_gr22" AS BIGINT) AS cnrepeat_gr22,
    CAST("Cnrepeat_gr32" AS BIGINT) AS cnrepeat_gr32,
    CAST("Cnrepeat_gr42" AS BIGINT) AS cnrepeat_gr42,
    CAST("Cnrepeat_gr52" AS BIGINT) AS cnrepeat_gr52,
    "Cnrepeat_gr62" AS cnrepeat_gr62,
    "Cnrepeat_gr72" AS cnrepeat_gr72,
    "Cnrepeat_gr82" AS cnrepeat_gr82,
    "Cnrepeat_gr92" AS cnrepeat_gr92,
    "Cabsent2" AS cabsent2,
    "Cwhyabsent2" AS cwhyabsent2,
    CAST("Cnabsent2" AS BIGINT) AS cnabsent2,
    CAST("Ctimeschool2" AS BIGINT) AS ctimeschool2,
    "Chwhelp2" AS chwhelp2,
    CAST("Chelphwline2" AS BIGINT) AS chelphwline2,
    CAST("Ctimehw2" AS BIGINT) AS ctimehw2,
    "Cexp_books2" AS cexp_books2,
    CAST("Cexp_books_amt2" AS BIGINT) AS cexp_books_amt2,
    "Cexp_books_mnth2" AS cexp_books_mnth2,
    "Cexp_books_mnth_amt2" AS cexp_books_mnth_amt2,
    "Cexp_bus2" AS cexp_bus2,
    CAST("Cexp_bus_amt2" AS DOUBLE) AS cexp_bus_amt2,
    "Cexp_other2" AS cexp_other2,
    CAST("Cexp_other_amt2" AS DOUBLE) AS cexp_other_amt2,
    "Cexp_pcommit2" AS cexp_pcommit2,
    CAST("Cexp_pcommit_amt2" AS DOUBLE) AS cexp_pcommit_amt2,
    "Cexp_regis2" AS cexp_regis2,
    CAST("Cexp_regis_amt2" AS BIGINT) AS cexp_regis_amt2,
    "Cexp_regis_mnth2" AS cexp_regis_mnth2,
    CAST("Cexp_regis_mnth_amt2" AS BIGINT) AS cexp_regis_mnth_amt2,
    "Cexp_uniform2" AS cexp_uniform2,
    CAST("Cexp_uniform_amt2" AS BIGINT) AS cexp_uniform_amt2,
    "Cwrk_h2" AS cwrk_h2,
    CAST("Cwrk_h_hrs2" AS BIGINT) AS cwrk_h_hrs2,
    "Cwrk_n2" AS cwrk_n2,
    CAST("Cwrk_n_hrs2" AS BIGINT) AS cwrk_n_hrs2,
    "Cwrk_p2" AS cwrk_p2,
    CAST("Cwrk_p_hrs2" AS BIGINT) AS cwrk_p_hrs2,
    "Cwrk_p_wage2" AS cwrk_p_wage2,
    "Ctvipcomplete0" AS ctvipcomplete0,
    "Ctvipcomplete1" AS ctvipcomplete1,
    "Ctvipcomplete2" AS ctvipcomplete2,
    "Ctvipcomplete3" AS ctvipcomplete3,
    "Ctvipcomplete4" AS ctvipcomplete4,
    "Ctvipwhynot1" AS ctvipwhynot1,
    "Ctvipwhynot2" AS ctvipwhynot2,
    "Ctvipwhynot3" AS ctvipwhynot3,
    "Ctvipwhynot4" AS ctvipwhynot4,
    CAST("Ctviptot0" AS BIGINT) AS ctviptot0,
    CAST("Ctviptot1" AS BIGINT) AS ctviptot1,
    CAST("Ctviptot2" AS BIGINT) AS ctviptot2,
    CAST("Ctviptot3" AS BIGINT) AS ctviptot3,
    CAST("Ctviptot4" AS BIGINT) AS ctviptot4,
    CAST("Cstdtvip0" AS BIGINT) AS cstdtvip0,
    CAST("Cstdtvip1" AS BIGINT) AS cstdtvip1,
    CAST("Cstdtvip2" AS BIGINT) AS cstdtvip2,
    "Ctviptot0_k" AS ctviptot0_k,
    "Ctviptot1_k" AS ctviptot1_k,
    "Ctviptot2_k" AS ctviptot2_k,
    "Ctviptot3_k" AS ctviptot3_k,
    "Ctviptot4_k" AS ctviptot4_k,
    CAST("SANbarn0" AS BIGINT) AS sanbarn0,
    CAST("SANbarn1" AS BIGINT) AS sanbarn1,
    CAST("SANbarn2" AS BIGINT) AS sanbarn2,
    CAST("SANexcr0" AS BIGINT) AS sanexcr0,
    CAST("SANexcr1" AS BIGINT) AS sanexcr1,
    CAST("SANexcr2" AS BIGINT) AS sanexcr2,
    CAST("SANgarb0" AS BIGINT) AS sangarb0,
    CAST("SANgarb1" AS BIGINT) AS sangarb1,
    CAST("SANgarb2" AS BIGINT) AS sangarb2,
    CAST("SANvent0" AS BIGINT) AS sanvent0,
    CAST("SANvent1" AS BIGINT) AS sanvent1,
    CAST("SANvent2" AS BIGINT) AS sanvent2,
    CAST("SANwatr0" AS BIGINT) AS sanwatr0,
    CAST("SANwatr1" AS BIGINT) AS sanwatr1,
    CAST("SANwatr2" AS BIGINT) AS sanwatr2,
    CAST("SANyard0" AS BIGINT) AS sanyard0,
    CAST("SANyard1" AS BIGINT) AS sanyard1,
    CAST("SANyard2" AS BIGINT) AS sanyard2,
    "Chaz0" AS chaz0,
    "Chaz1" AS chaz1,
    "Chaz2" AS chaz2,
    "Cwaz0" AS cwaz0,
    "Cwaz1" AS cwaz1,
    "Cwaz2" AS cwaz2,
    "Cwhz0" AS cwhz0,
    "Cwhz1" AS cwhz1,
    "Cwhz2" AS cwhz2,
    CAST("Cstunted0" AS BIGINT) AS cstunted0,
    CAST("Cstunted1" AS BIGINT) AS cstunted1,
    CAST("Cstunted2" AS BIGINT) AS cstunted2,
    CAST("Cwasted0" AS BIGINT) AS cwasted0,
    CAST("Cwasted1" AS BIGINT) AS cwasted1,
    CAST("Cwasted2" AS BIGINT) AS cwasted2,
    CAST("Cbmi1" AS DOUBLE) AS cbmi1,
    CAST("Cbmi2" AS DOUBLE) AS cbmi2,
    "Cpbcomplete1" AS cpbcomplete1,
    "Cpbcomplete2" AS cpbcomplete2,
    "Cpbwhynot1" AS cpbwhynot1,
    "Cpbwhynot2" AS cpbwhynot2,
    "Cpbint1" AS cpbint1,
    "Cpbint2" AS cpbint2,
    CAST("Cpbavg_dom1" AS DOUBLE) AS cpbavg_dom1,
    CAST("Cpbavg_dom2" AS BIGINT) AS cpbavg_dom2,
    CAST("Cpbavg_nd1" AS DOUBLE) AS cpbavg_nd1,
    CAST("Cpbavg_nd2" AS BIGINT) AS cpbavg_nd2,
    "Cbmcomplete1" AS cbmcomplete1,
    "Cbmwhynot1" AS cbmwhynot1,
    CAST("Cbmscore1" AS BIGINT) AS cbmscore1,
    "Cbmpct1" AS cbmpct1,
    CAST("Cbmallyes1" AS BIGINT) AS cbmallyes1,
    "Cbmint1" AS cbmint1,
    "Cmaccomplete1" AS cmaccomplete1,
    "Cmacwhynot1" AS cmacwhynot1,
    CAST("Cmacscore1" AS BIGINT) AS cmacscore1,
    "Cmacpct1" AS cmacpct1,
    "Cbpicomplete1" AS cbpicomplete1,
    "Cbpiwhynot1" AS cbpiwhynot1,
    "Cbpiint1" AS cbpiint1,
    CAST("Cbpitotal_a1" AS BIGINT) AS cbpitotal_a1,
    CAST("CbpiAggr_a1" AS BIGINT) AS cbpiaggr_a1,
    CAST("CbpiAnx_a1" AS BIGINT) AS cbpianx_a1,
    CAST("CbpiOth_a1" AS BIGINT) AS cbpioth_a1,
    CAST("CSDQtotal3" AS BIGINT) AS csdqtotal3,
    CAST("CSDQtotal4" AS BIGINT) AS csdqtotal4,
    "sdCSDQtotal3" AS sdcsdqtotal3,
    "sdCSDQtotal4" AS sdcsdqtotal4,
    CAST("CSDQemot3" AS BIGINT) AS csdqemot3,
    CAST("CSDQemot4" AS BIGINT) AS csdqemot4,
    "sdCSDQemot3" AS sdcsdqemot3,
    "sdCSDQemot4" AS sdcsdqemot4,
    CAST("CSDQcond3" AS BIGINT) AS csdqcond3,
    CAST("CSDQcond4" AS BIGINT) AS csdqcond4,
    "sdCSDQcond3" AS sdcsdqcond3,
    "sdCSDQcond4" AS sdcsdqcond4,
    CAST("CSDQhyp3" AS BIGINT) AS csdqhyp3,
    CAST("CSDQhyp4" AS BIGINT) AS csdqhyp4,
    "sdCSDQhyp3" AS sdcsdqhyp3,
    "sdCSDQhyp4" AS sdcsdqhyp4,
    CAST("CSDQpprob3" AS BIGINT) AS csdqpprob3,
    CAST("CSDQpprob4" AS BIGINT) AS csdqpprob4,
    "sdCSDQpprob3" AS sdcsdqpprob3,
    "sdCSDQpprob4" AS sdcsdqpprob4,
    CAST("CSDQpros3" AS BIGINT) AS csdqpros3,
    CAST("CSDQpros4" AS BIGINT) AS csdqpros4,
    "sdCSDQpros3" AS sdcsdqpros3,
    "sdCSDQpros4" AS sdcsdqpros4,
    CAST("Ccolypalraw13" AS BIGINT) AS ccolypalraw13,
    CAST("Ccolypalraw23" AS BIGINT) AS ccolypalraw23,
    CAST("Ccolypalraw33" AS BIGINT) AS ccolypalraw33,
    "Ccolypalraw33_k" AS ccolypalraw33_k,
    CAST("CEATQtot3" AS DOUBLE) AS ceatqtot3,
    "sdCEATQtot3" AS sdceatqtot3,
    CAST("CEATQfrust3" AS DOUBLE) AS ceatqfrust3,
    "sdCEATQfrust3" AS sdceatqfrust3,
    CAST("CEATQsurg3" AS DOUBLE) AS ceatqsurg3,
    "sdCEATQsurg3" AS sdceatqsurg3,
    "CWJ1complete1" AS cwj1complete1,
    "CWJ1complete2" AS cwj1complete2,
    "CWJ1complete3" AS cwj1complete3,
    "CWJ1whynot1" AS cwj1whynot1,
    "CWJ1whynot2" AS cwj1whynot2,
    "CWJ1whynot3" AS cwj1whynot3,
    "CWJ1int1" AS cwj1int1,
    "CWJ1int2" AS cwj1int2,
    "CWJ1int3" AS cwj1int3,
    CAST("CWJ1pct1" AS BIGINT) AS cwj1pct1,
    CAST("CWJ1pct2" AS BIGINT) AS cwj1pct2,
    CAST("CWJ1pct3" AS DOUBLE) AS cwj1pct3,
    CAST("CWJ1tot1" AS BIGINT) AS cwj1tot1,
    CAST("CWJ1tot2" AS BIGINT) AS cwj1tot2,
    CAST("CWJ1tot3" AS BIGINT) AS cwj1tot3,
    "CWJ1tot1_k" AS cwj1tot1_k,
    "CWJ1tot2_k" AS cwj1tot2_k,
    "CWJ1tot3_k" AS cwj1tot3_k,
    "CWJ2complete1" AS cwj2complete1,
    "CWJ2whynot1" AS cwj2whynot1,
    "CWJ2int1" AS cwj2int1,
    CAST("CWJ2pct1" AS BIGINT) AS cwj2pct1,
    CAST("CWJ2tot1" AS BIGINT) AS cwj2tot1,
    "CWJ5complete1" AS cwj5complete1,
    "CWJ5complete2" AS cwj5complete2,
    "CWJ5complete3" AS cwj5complete3,
    "CWJ5whynot1" AS cwj5whynot1,
    "CWJ5whynot2" AS cwj5whynot2,
    "CWJ5whynot3" AS cwj5whynot3,
    "CWJ5int1" AS cwj5int1,
    "CWJ5int2" AS cwj5int2,
    "CWJ5int3" AS cwj5int3,
    CAST("CWJ5pct1" AS BIGINT) AS cwj5pct1,
    CAST("CWJ5pct2" AS BIGINT) AS cwj5pct2,
    CAST("CWJ5pctile3" AS DOUBLE) AS cwj5pctile3,
    CAST("CWJ5tot1" AS BIGINT) AS cwj5tot1,
    CAST("CWJ5tot2" AS BIGINT) AS cwj5tot2,
    CAST("CWJ5tot3" AS BIGINT) AS cwj5tot3,
    "CWJ5tot1_k" AS cwj5tot1_k,
    "CWJ5tot2_k" AS cwj5tot2_k,
    "CWJ5tot3_k" AS cwj5tot3_k,
    "Cdmcomplete2" AS cdmcomplete2,
    "Cdmcomplete3" AS cdmcomplete3,
    "Cdmcomplete4" AS cdmcomplete4,
    "Cdmwhynot2" AS cdmwhynot2,
    "Cdmwhynot3" AS cdmwhynot3,
    "Cdmwhynot4" AS cdmwhynot4,
    "Cdmint3" AS cdmint3,
    "Cdmint4" AS cdmint4,
    CAST("Cdm1_tot2" AS BIGINT) AS cdm1_tot2,
    CAST("Cdm1_tot3" AS BIGINT) AS cdm1_tot3,
    CAST("Cdm1_tot4" AS BIGINT) AS cdm1_tot4,
    CAST("Cdm2_tot2" AS BIGINT) AS cdm2_tot2,
    CAST("Cdm2_tot3" AS BIGINT) AS cdm2_tot3,
    CAST("Cdm2_tot4" AS BIGINT) AS cdm2_tot4,
    "Cdmtot2_k" AS cdmtot2_k,
    "Cdmtot3_k" AS cdmtot3_k,
    "Cdmtot4_k" AS cdmtot4_k,
    "CWM6complete2" AS cwm6complete2,
    "CWM6complete3" AS cwm6complete3,
    "CWM6complete4" AS cwm6complete4,
    "CWM6whynot2" AS cwm6whynot2,
    "CWM6whynot3" AS cwm6whynot3,
    "CWM6whynot4" AS cwm6whynot4,
    CAST("CWM6tot2" AS BIGINT) AS cwm6tot2,
    CAST("CWM6tot3" AS BIGINT) AS cwm6tot3,
    CAST("CWM6tot4" AS BIGINT) AS cwm6tot4,
    "CWM6tot2_k" AS cwm6tot2_k,
    "CWM6tot3_k" AS cwm6tot3_k,
    "CWM6tot4_k" AS cwm6tot4_k,
    "CWM18Bcomplete2" AS cwm18bcomplete2,
    "CWM18Bcomplete3" AS cwm18bcomplete3,
    "CWM18Bcomplete4" AS cwm18bcomplete4,
    "CWM18Bwhynot2" AS cwm18bwhynot2,
    "CWM18Bwhynot3" AS cwm18bwhynot3,
    "CWM18Bwhynot4" AS cwm18bwhynot4,
    CAST("CWM18Btot2" AS BIGINT) AS cwm18btot2,
    CAST("CWM18Btot3" AS BIGINT) AS cwm18btot3,
    CAST("CWM18Btot4" AS BIGINT) AS cwm18btot4,
    "CWM18Btot2_k" AS cwm18btot2_k,
    "CWM18Btot3_k" AS cwm18btot3_k,
    "CWM18Btot4_k" AS cwm18btot4_k,
    "CWM1complete2" AS cwm1complete2,
    "CWM1complete3" AS cwm1complete3,
    CAST("CWM1complete4" AS BIGINT) AS cwm1complete4,
    "CWM1whynot2" AS cwm1whynot2,
    "CWM1whynot3" AS cwm1whynot3,
    CAST("CWM1whynot4" AS BIGINT) AS cwm1whynot4,
    CAST("CWM1tot2" AS BIGINT) AS cwm1tot2,
    CAST("CWM1tot3" AS BIGINT) AS cwm1tot3,
    CAST("CWM1tot4" AS BIGINT) AS cwm1tot4,
    "CWM1tot2_k" AS cwm1tot2_k,
    "CWM1tot3_k" AS cwm1tot3_k,
    "CWM1tot4_k" AS cwm1tot4_k,
    "CWM20complete3" AS cwm20complete3,
    "CWM20complete4" AS cwm20complete4,
    "CWM20whynot3" AS cwm20whynot3,
    "CWM20whynot4" AS cwm20whynot4,
    CAST("CWM20tot3" AS BIGINT) AS cwm20tot3,
    CAST("CWM20tot4" AS BIGINT) AS cwm20tot4,
    "CWM20tot3_k" AS cwm20tot3_k,
    "CWM20tot4_k" AS cwm20tot4_k,
    "CWM2complete3" AS cwm2complete3,
    "CWM2complete4" AS cwm2complete4,
    "CWM2whynot3" AS cwm2whynot3,
    "CWM2whynot4" AS cwm2whynot4,
    CAST("CWM2Atot3" AS BIGINT) AS cwm2atot3,
    CAST("CWM2Atot4" AS BIGINT) AS cwm2atot4,
    CAST("CWM2Btot3" AS BIGINT) AS cwm2btot3,
    CAST("CWM2Btot4" AS BIGINT) AS cwm2btot4,
    CAST("CWM2Ctot3" AS BIGINT) AS cwm2ctot3,
    CAST("CWM2Ctot4" AS BIGINT) AS cwm2ctot4,
    CAST("CWM2tot3" AS BIGINT) AS cwm2tot3,
    CAST("CWM2tot4" AS BIGINT) AS cwm2tot4,
    "CWM2tot3_k" AS cwm2tot3_k,
    "CWM2tot4_k" AS cwm2tot4_k,
    "CWM3complete3" AS cwm3complete3,
    "CWM3whynot3" AS cwm3whynot3,
    CAST("CWM3tot3" AS BIGINT) AS cwm3tot3,
    "CWM3tot3_k" AS cwm3tot3_k,
    "CWM10complete3" AS cwm10complete3,
    "CWM10complete4" AS cwm10complete4,
    "CWM10whynot3" AS cwm10whynot3,
    "CWM10whynot4" AS cwm10whynot4,
    CAST("CWM10tot3" AS BIGINT) AS cwm10tot3,
    CAST("CWM10tot4" AS BIGINT) AS cwm10tot4,
    "CWM10tot3_k" AS cwm10tot3_k,
    "CWM10tot4_k" AS cwm10tot4_k,
    "CWM5complete3" AS cwm5complete3,
    "CWM5complete4" AS cwm5complete4,
    "CWM5whynot3" AS cwm5whynot3,
    "CWM5whynot4" AS cwm5whynot4,
    CAST("CWM5tot3" AS BIGINT) AS cwm5tot3,
    CAST("CWM5tot4" AS BIGINT) AS cwm5tot4,
    "CWM5tot3_k" AS cwm5tot3_k,
    "CWM5tot4_k" AS cwm5tot4_k,
    "CWM12complete3" AS cwm12complete3,
    "CWM12complete4" AS cwm12complete4,
    "CWM12whynot3" AS cwm12whynot3,
    "CWM12whynot4" AS cwm12whynot4,
    CAST("CWM12tot3" AS BIGINT) AS cwm12tot3,
    CAST("CWM12tot4" AS BIGINT) AS cwm12tot4,
    "CWM12tot3_k" AS cwm12tot3_k,
    "CWM12tot4_k" AS cwm12tot4_k,
    "Crccomplete3" AS crccomplete3,
    "Crccomplete4" AS crccomplete4,
    "Crcwhynot3" AS crcwhynot3,
    "Crcwhynot4" AS crcwhynot4,
    "Crcint3" AS crcint3,
    "Crcint4" AS crcint4,
    CAST("Crctot3" AS BIGINT) AS crctot3,
    CAST("Crctot4" AS BIGINT) AS crctot4,
    "Crctot3_k" AS crctot3_k,
    "Crctot4_k" AS crctot4_k,
    CAST("Mtvipraw1" AS BIGINT) AS mtvipraw1,
    CAST("Mtvip1" AS BIGINT) AS mtvip1,
    CAST("MladderC1" AS BIGINT) AS mladderc1,
    CAST("MladderC2" AS BIGINT) AS mladderc2,
    CAST("MladderE1" AS BIGINT) AS mladdere1,
    CAST("MladderE2" AS BIGINT) AS mladdere2,
    CAST("Mdeptot0" AS BIGINT) AS mdeptot0,
    CAST("Mcesd1" AS BIGINT) AS mcesd1,
    CAST("Mcesd2" AS BIGINT) AS mcesd2,
    CAST("Mcesd3" AS BIGINT) AS mcesd3,
    CAST("Mcesd4" AS BIGINT) AS mcesd4,
    CAST("Mlivebirths0" AS BIGINT) AS mlivebirths0,
    CAST("Mlivekids0" AS BIGINT) AS mlivekids0,
    "Mdeadkid0" AS mdeadkid0,
    CAST("Mdkyrdied0" AS BIGINT) AS mdkyrdied0,
    CAST("Mdkmndied0" AS BIGINT) AS mdkmndied0,
    "Mdkcough0" AS mdkcough0,
    "Mdkbreath0" AS mdkbreath0,
    CAST("Mdk12months0" AS BIGINT) AS mdk12months0,
    "Msb_abort0" AS msb_abort0,
    CAST("Msb_abortmn0" AS BIGINT) AS msb_abortmn0,
    CAST("Msb_abortyr0" AS BIGINT) AS msb_abortyr0,
    "Mpregnow0" AS mpregnow0,
    "Mpregnow1" AS mpregnow1,
    "Mpregcont0" AS mpregcont0,
    "Mpregcont1" AS mpregcont1,
    CAST("Mpregmonths0" AS BIGINT) AS mpregmonths0,
    "Mpregmonths1" AS mpregmonths1,
    "Mhaspcard0" AS mhaspcard0,
    CAST("Mpregcontnum0" AS BIGINT) AS mpregcontnum0,
    CAST("Mpregcontnum1" AS BIGINT) AS mpregcontnum1,
    "MpregcontwhereR0" AS mpregcontwherer0,
    "Mpregcontwhere1" AS mpregcontwhere1,
    "Mpregcontwho0" AS mpregcontwho0,
    "Mpregcontwho1" AS mpregcontwho1,
    "Mpregcontpay0" AS mpregcontpay0,
    "Mpregcontpay1" AS mpregcontpay1,
    CAST("Mpregcontcost0" AS BIGINT) AS mpregcontcost0,
    "Mpregcontcost1" AS mpregcontcost1,
    CAST("Mpregcontmins0" AS BIGINT) AS mpregcontmins0,
    CAST("Mpregcontmins1" AS BIGINT) AS mpregcontmins1,
    "Mpregtet0" AS mpregtet0,
    "Mpregtet1" AS mpregtet1,
    CAST("Mpregtetnum0" AS BIGINT) AS mpregtetnum0,
    CAST("Mpregtetnum1" AS BIGINT) AS mpregtetnum1,
    "Mpregiron0" AS mpregiron0,
    "Mpregiron1" AS mpregiron1,
    CAST("Mpregironnum0" AS BIGINT) AS mpregironnum0,
    CAST("Mpregironnum1" AS BIGINT) AS mpregironnum1,
    "Mpregfolic0" AS mpregfolic0,
    "Mpregfolic1" AS mpregfolic1,
    CAST("Mpregfolicnum0" AS BIGINT) AS mpregfolicnum0,
    CAST("Mpregfolicnum1" AS BIGINT) AS mpregfolicnum1,
    "Mpregvita0" AS mpregvita0,
    "Mpregvita1" AS mpregvita1,
    CAST("Mpregvitanum0" AS BIGINT) AS mpregvitanum0,
    CAST("Mpregvitanum1" AS BIGINT) AS mpregvitanum1,
    "Mpregcomp0" AS mpregcomp0,
    "Mpregcomp1" AS mpregcomp1,
    "Mcompwhere0" AS mcompwhere0,
    "Mcompwhere1" AS mcompwhere1,
    "Mmatprog0" AS mmatprog0,
    CAST("Mcon01dd0" AS BIGINT) AS mcon01dd0,
    CAST("Mcon01mm0" AS BIGINT) AS mcon01mm0,
    CAST("Mcon01yy0" AS BIGINT) AS mcon01yy0,
    CAST("Mcon01kg0" AS DOUBLE) AS mcon01kg0,
    CAST("Mcon01wp0" AS BIGINT) AS mcon01wp0,
    CAST("Mcon02dd0" AS BIGINT) AS mcon02dd0,
    CAST("Mcon02mm0" AS BIGINT) AS mcon02mm0,
    CAST("Mcon02yy0" AS BIGINT) AS mcon02yy0,
    CAST("Mcon02kg0" AS DOUBLE) AS mcon02kg0,
    CAST("Mcon02wp0" AS BIGINT) AS mcon02wp0,
    CAST("Mcon03dd0" AS BIGINT) AS mcon03dd0,
    CAST("Mcon03mm0" AS BIGINT) AS mcon03mm0,
    CAST("Mcon03yy0" AS BIGINT) AS mcon03yy0,
    CAST("Mcon03kg0" AS DOUBLE) AS mcon03kg0,
    CAST("Mcon03wp0" AS BIGINT) AS mcon03wp0,
    CAST("Mcon04dd0" AS BIGINT) AS mcon04dd0,
    CAST("Mcon04mm0" AS BIGINT) AS mcon04mm0,
    CAST("Mcon04yy0" AS BIGINT) AS mcon04yy0,
    CAST("Mcon04kg0" AS DOUBLE) AS mcon04kg0,
    CAST("Mcon04wp0" AS BIGINT) AS mcon04wp0,
    CAST("Mcon05dd0" AS BIGINT) AS mcon05dd0,
    CAST("Mcon05mm0" AS BIGINT) AS mcon05mm0,
    CAST("Mcon05yy0" AS BIGINT) AS mcon05yy0,
    CAST("Mcon05kg0" AS DOUBLE) AS mcon05kg0,
    CAST("Mcon05wp0" AS BIGINT) AS mcon05wp0,
    CAST("Mcon06dd0" AS BIGINT) AS mcon06dd0,
    CAST("Mcon06mm0" AS BIGINT) AS mcon06mm0,
    CAST("Mcon06yy0" AS BIGINT) AS mcon06yy0,
    CAST("Mcon06kg0" AS DOUBLE) AS mcon06kg0,
    CAST("Mcon06wp0" AS BIGINT) AS mcon06wp0,
    CAST("Mcon07dd0" AS BIGINT) AS mcon07dd0,
    CAST("Mcon07mm0" AS BIGINT) AS mcon07mm0,
    CAST("Mcon07yy0" AS BIGINT) AS mcon07yy0,
    CAST("Mcon07kg0" AS DOUBLE) AS mcon07kg0,
    CAST("Mcon07wp0" AS BIGINT) AS mcon07wp0,
    "Mcon08dd0" AS mcon08dd0,
    "Mcon08mm0" AS mcon08mm0,
    "Mcon08yy0" AS mcon08yy0,
    "Mcon08kg0" AS mcon08kg0,
    "Mcon08wp0" AS mcon08wp0,
    "Mcon09dd0" AS mcon09dd0,
    "Mcon09mm0" AS mcon09mm0,
    "Mcon09yy0" AS mcon09yy0,
    "Mcon09kg0" AS mcon09kg0,
    "Mcon09wp0" AS mcon09wp0,
    "Mcon10dd0" AS mcon10dd0,
    "Mcon10mm0" AS mcon10mm0,
    "Mcon10yy0" AS mcon10yy0,
    "Mcon10kg0" AS mcon10kg0,
    "Mcon10wp0" AS mcon10wp0,
    "Mcon11dd0" AS mcon11dd0,
    "Mcon11mm0" AS mcon11mm0,
    "Mcon11yy0" AS mcon11yy0,
    "Mcon11kg0" AS mcon11kg0,
    "Mcon11wp0" AS mcon11wp0,
    "Mcon12dd0" AS mcon12dd0,
    "Mcon12mm0" AS mcon12mm0,
    "Mcon12yy0" AS mcon12yy0,
    "Mcon12kg0" AS mcon12kg0,
    "Mcon12wp0" AS mcon12wp0,
    "Mprenatal0" AS mprenatal0,
    "Mprenatal1" AS mprenatal1,
    "Mtetanus0" AS mtetanus0,
    "Mtetanus1" AS mtetanus1,
    "MbrthplaceR0" AS mbrthplacer0,
    "Mbrthplace1" AS mbrthplace1,
    "Mwhyhome0" AS mwhyhome0,
    "Mwhyhome1" AS mwhyhome1,
    "Mbrthasst0" AS mbrthasst0,
    "Mbrthasst1" AS mbrthasst1,
    "Mpostnatal0" AS mpostnatal0,
    "Mpostnatal1" AS mpostnatal1,
    "Mpostiron0" AS mpostiron0,
    "Mpostiron1" AS mpostiron1,
    CAST("Mnumiron0" AS BIGINT) AS mnumiron0,
    CAST("Mnumiron1" AS BIGINT) AS mnumiron1,
    "MpostvitA0" AS mpostvita0,
    "MpostvitA1" AS mpostvita1,
    CAST("MnumvitA0" AS BIGINT) AS mnumvita0,
    CAST("MnumvitA1" AS BIGINT) AS mnumvita1,
    "Mbfinfo0" AS mbfinfo0,
    "Mbfinfo1" AS mbfinfo1,
    "MbfinfowhereR0" AS mbfinfowherer0,
    "Mbfinfowhere1" AS mbfinfowhere1,
    "Mbcuse0" AS mbcuse0,
    "Mbctype0" AS mbctype0,
    "Mmibebida0" AS mmibebida0,
    "Mmibebida1" AS mmibebida1,
    CAST("Mmibebidanum0" AS BIGINT) AS mmibebidanum0,
    CAST("Mmibebidanum1" AS BIGINT) AS mmibebidanum1,
    "Mhstat0" AS mhstat0,
    "Mhstat1" AS mhstat1,
    "Mhstat2" AS mhstat2,
    CAST("Mnsickdays0" AS BIGINT) AS mnsickdays0,
    CAST("Mnsickdays1" AS BIGINT) AS mnsickdays1,
    CAST("Mnbeddays0" AS BIGINT) AS mnbeddays0,
    CAST("Mnbeddays1" AS BIGINT) AS mnbeddays1,
    "Mvigact0" AS mvigact0,
    "Mvigact1" AS mvigact1,
    "Mpain0" AS mpain0,
    "Mpain1" AS mpain1,
    "Mmammogram0" AS mmammogram0,
    "Mmammwhynot0" AS mmammwhynot0,
    "MPAPtest0" AS mpaptest0,
    CAST("MPAPday0" AS BIGINT) AS mpapday0,
    CAST("MPAPmonth0" AS BIGINT) AS mpapmonth0,
    CAST("MPAPyear0" AS BIGINT) AS mpapyear0,
    "MPAPresults0" AS mpapresults0,
    "MPAPwhere0" AS mpapwhere0,
    "Manycough0" AS manycough0,
    "Manycough1" AS manycough1,
    "Mbldcough0" AS mbldcough0,
    "Mdrycough0" AS mdrycough0,
    "Mwetcough0" AS mwetcough0,
    "Manydiarr0" AS manydiarr0,
    "Manydiarr1" AS manydiarr1,
    "Mblddiarr0" AS mblddiarr0,
    "Mliqdiarr0" AS mliqdiarr0,
    "Mmucdiarr0" AS mmucdiarr0,
    "Mheadache0" AS mheadache0,
    "Mheadache1" AS mheadache1,
    "Mjointpain0" AS mjointpain0,
    "Mjointpain1" AS mjointpain1,
    "Mskininf0" AS mskininf0,
    "Mskininf1" AS mskininf1,
    "Mstomache0" AS mstomache0,
    "Mstomache1" AS mstomache1,
    "Mtoothache0" AS mtoothache0,
    "Mtoothache1" AS mtoothache1,
    "Mvomit0" AS mvomit0,
    "Mvomit1" AS mvomit1,
    "Meyeinf0" AS meyeinf0,
    "Meyeinf1" AS meyeinf1,
    "Mfastresp0" AS mfastresp0,
    "Mfastresp1" AS mfastresp1,
    "Mfever0" AS mfever0,
    "Mfever1" AS mfever1,
    "Mrunnynose0" AS mrunnynose0,
    "Mrunnynose1" AS mrunnynose1,
    "Mhospeps0" AS mhospeps0,
    "Mhospeps1" AS mhospeps1,
    CAST("Mhospdays0" AS BIGINT) AS mhospdays0,
    CAST("Mhospdays1" AS BIGINT) AS mhospdays1,
    CAST("Madjhemo0" AS DOUBLE) AS madjhemo0,
    CAST("Madjhemo1" AS DOUBLE) AS madjhemo1,
    CAST("Madjhemo2" AS DOUBLE) AS madjhemo2,
    CAST("Manemic0" AS BIGINT) AS manemic0,
    CAST("Manemic1" AS BIGINT) AS manemic1,
    CAST("Manemic2" AS BIGINT) AS manemic2,
    "Mhlthins0" AS mhlthins0,
    "Mhlthins1" AS mhlthins1,
    "Mhlthins2" AS mhlthins2,
    CAST("Mhlthvisits0" AS BIGINT) AS mhlthvisits0,
    "Mhlthvisits1" AS mhlthvisits1,
    "Mhlthwhy0" AS mhlthwhy0,
    "Mhlthwhy1" AS mhlthwhy1,
    "Millmed0" AS millmed0,
    "Millmed1" AS millmed1,
    CAST("Mheight1" AS DOUBLE) AS mheight1,
    CAST("Mheight2" AS DOUBLE) AS mheight2,
    CAST("Mbmi1" AS DOUBLE) AS mbmi1,
    CAST("Mbmi2" AS DOUBLE) AS mbmi2,
    "Mdv_answerwhyn0" AS mdv_answerwhyn0,
    "Mdv_answerwhyn1" AS mdv_answerwhyn1,
    "Mlivehusb0" AS mlivehusb0,
    "Mlivehusb1" AS mlivehusb1,
    "Mdv_answer0" AS mdv_answer0,
    "Mdv_answer1" AS mdv_answer1,
    "Mdv_freetime0" AS mdv_freetime0,
    "Mdv_freetime1" AS mdv_freetime1,
    "Mdv_affection0" AS mdv_affection0,
    "Mdv_affection1" AS mdv_affection1,
    "Mdv_ignore0" AS mdv_ignore0,
    "Mdv_ignore1" AS mdv_ignore1,
    "Mdv_nostudy0" AS mdv_nostudy0,
    "Mdv_nostudy1" AS mdv_nostudy1,
    "Mdv_yell0" AS mdv_yell0,
    "Mdv_yell1" AS mdv_yell1,
    "Mdv_worthless0" AS mdv_worthless0,
    "Mdv_worthless1" AS mdv_worthless1,
    "Mdv_nofriends0" AS mdv_nofriends0,
    "Mdv_nofriends1" AS mdv_nofriends1,
    "Mdv_leave0" AS mdv_leave0,
    "Mdv_leave1" AS mdv_leave1,
    "Mdv_takekids0" AS mdv_takekids0,
    "Mdv_takekids1" AS mdv_takekids1,
    "Mdv_beat0" AS mdv_beat0,
    "Mdv_beat1" AS mdv_beat1,
    "Mdv_beatoften0" AS mdv_beatoften0,
    "Mdv_beatoften1" AS mdv_beatoften1,
    "Mdv_hdrinks0" AS mdv_hdrinks0,
    "Mdv_hdrinks1" AS mdv_hdrinks1,
    "Mdv_help0" AS mdv_help0,
    "Mdv_help1" AS mdv_help1,
    "Mdv_helpwho0" AS mdv_helpwho0,
    "Mdv_helpwho1" AS mdv_helpwho1,
    "Mdv_hcounsel0" AS mdv_hcounsel0,
    "Mdv_hcounsel1" AS mdv_hcounsel1,
    "Mdv_hcourt0" AS mdv_hcourt0,
    "Mdv_hcourt1" AS mdv_hcourt1,
    "Mdv_hhunity0" AS mdv_hhunity0,
    "Mdv_hhunity1" AS mdv_hhunity1,
    "Mdv_hjudpol0" AS mdv_hjudpol0,
    "Mdv_hjudpol1" AS mdv_hjudpol1,
    "Mdv_hother0" AS mdv_hother0,
    "Mdv_hother1" AS mdv_hother1,
    "Mdv_hpolice0" AS mdv_hpolice0,
    "Mdv_hpolice1" AS mdv_hpolice1,
    "Mdv_hprivorg0" AS mdv_hprivorg0,
    "Mdv_hprivorg1" AS mdv_hprivorg1,
    "Mdv_hwomoff0" AS mdv_hwomoff0,
    "Mdv_hwomoff1" AS mdv_hwomoff1,
    "Mdv_hnoinst0" AS mdv_hnoinst0,
    "Mdv_hnoinst1" AS mdv_hnoinst1,
    "Mdv_nhbadexp0" AS mdv_nhbadexp0,
    "Mdv_nhbadexp1" AS mdv_nhbadexp1,
    "Mdv_nhdeserve0" AS mdv_nhdeserve0,
    "Mdv_nhdeserve1" AS mdv_nhdeserve1,
    "Mdv_nhdidntknow0" AS mdv_nhdidntknow0,
    "Mdv_nhdidntknow1" AS mdv_nhdidntknow1,
    "Mdv_nhdivorce0" AS mdv_nhdivorce0,
    "Mdv_nhdivorce1" AS mdv_nhdivorce1,
    "Mdv_nhembarrassed0" AS mdv_nhembarrassed0,
    "Mdv_nhembarrassed1" AS mdv_nhembarrassed1,
    "Mdv_nhhandle0" AS mdv_nhhandle0,
    "Mdv_nhhandle1" AS mdv_nhhandle1,
    "Mdv_nhharmless0" AS mdv_nhharmless0,
    "Mdv_nhharmless1" AS mdv_nhharmless1,
    "Mdv_nhhit0" AS mdv_nhhit0,
    "Mdv_nhhit1" AS mdv_nhhit1,
    "Mdv_nhjustice0" AS mdv_nhjustice0,
    "Mdv_nhjustice1" AS mdv_nhjustice1,
    "Mdv_nhnevagain0" AS mdv_nhnevagain0,
    "Mdv_nhnevagain1" AS mdv_nhnevagain1,
    "Mdv_nhnohurt0" AS mdv_nhnohurt0,
    "Mdv_nhnohurt1" AS mdv_nhnohurt1,
    "Mdv_nhnormal0" AS mdv_nhnormal0,
    "Mdv_nhnormal1" AS mdv_nhnormal1,
    "Mbdh_hrd1" AS mbdh_hrd1,
    "Mbdh_hrd2" AS mbdh_hrd2,
    "Mbdh_cond1" AS mbdh_cond1,
    "Mbdh_condA1" AS mbdh_conda1,
    "Mbdh_condB1" AS mbdh_condb1,
    "Mbdh_rec1" AS mbdh_rec1,
    "Mbdh_rec2" AS mbdh_rec2,
    "Mbdh_rec3" AS mbdh_rec3,
    CAST("Mbdh_rec4" AS BIGINT) AS mbdh_rec4,
    CAST("Mbdh_firstmn1" AS BIGINT) AS mbdh_firstmn1,
    CAST("Mbdh_firstyr1" AS BIGINT) AS mbdh_firstyr1,
    CAST("Mbdh_lastmn1" AS BIGINT) AS mbdh_lastmn1,
    CAST("Mbdh_lastyr1" AS BIGINT) AS mbdh_lastyr1,
    CAST("Mbdh_wait1" AS BIGINT) AS mbdh_wait1,
    "Mspentclothes1" AS mspentclothes1,
    "Mspented1" AS mspented1,
    "Mspentfood1" AS mspentfood1,
    "Mspenthealth1" AS mspenthealth1,
    "Mspenthouse1" AS mspenthouse1,
    "Mspenthusb1" AS mspenthusb1,
    "Mspenttrans1" AS mspenttrans1,
    "Mwhoclothes1" AS mwhoclothes1,
    "Mwhoed1" AS mwhoed1,
    "Mwhofood1" AS mwhofood1,
    "Mwhohealth1" AS mwhohealth1,
    "Mwhohouse1" AS mwhohouse1,
    "Mwhohusb1" AS mwhohusb1,
    "Mwhotrans1" AS mwhotrans1,
    CAST("Mbdh_stop1" AS BIGINT) AS mbdh_stop1,
    "Mbdh_stopyr1" AS mbdh_stopyr1,
    "Mbdh_stopwhy1" AS mbdh_stopwhy1,
    "Mbdh_recoth1" AS mbdh_recoth1,
    "Mbdh_act2" AS mbdh_act2,
    "source_resource"
FROM "idb-ecuador-longitudinal-survey-of-child-health-and-development-rounds-1-5-2003"
