-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "countryname",
    "ifs",
    CAST("year" AS BIGINT) AS year,
    CAST("system" AS BIGINT) AS system,
    CAST("yrsoffc" AS BIGINT) AS yrsoffc,
    CAST("finittrm" AS BIGINT) AS finittrm,
    CAST("yrcurnt" AS BIGINT) AS yrcurnt,
    CAST("multpl" AS BIGINT) AS multpl,
    CAST("military" AS BIGINT) AS military,
    CAST("defmin" AS BIGINT) AS defmin,
    CAST("percent1" AS DOUBLE) AS percent1,
    CAST("percentl" AS DOUBLE) AS percentl,
    CAST("prtyin" AS BIGINT) AS prtyin,
    "execme",
    CAST("execrlc" AS BIGINT) AS execrlc,
    CAST("execnat" AS BIGINT) AS execnat,
    CAST("execrurl" AS BIGINT) AS execrurl,
    CAST("execreg" AS BIGINT) AS execreg,
    CAST("execrel" AS BIGINT) AS execrel,
    CAST("execage" AS BIGINT) AS execage,
    CAST("allhouse" AS BIGINT) AS allhouse,
    "nonchief",
    CAST("totalseats" AS BIGINT) AS totalseats,
    "gov1me",
    CAST("gov1seat" AS BIGINT) AS gov1seat,
    CAST("gov1vote" AS DOUBLE) AS gov1vote,
    CAST("gov1rlc" AS BIGINT) AS gov1rlc,
    CAST("gov1nat" AS BIGINT) AS gov1nat,
    CAST("gov1rurl" AS BIGINT) AS gov1rurl,
    CAST("gov1reg" AS BIGINT) AS gov1reg,
    CAST("gov1rel" AS BIGINT) AS gov1rel,
    CAST("gov1age" AS BIGINT) AS gov1age,
    "gov2me",
    CAST("gov2seat" AS BIGINT) AS gov2seat,
    CAST("gov2vote" AS DOUBLE) AS gov2vote,
    CAST("gov2rlc" AS BIGINT) AS gov2rlc,
    CAST("gov2nat" AS BIGINT) AS gov2nat,
    CAST("gov2rurl" AS BIGINT) AS gov2rurl,
    CAST("gov2reg" AS BIGINT) AS gov2reg,
    CAST("gov2rel" AS BIGINT) AS gov2rel,
    CAST("gov2age" AS BIGINT) AS gov2age,
    "gov3me",
    CAST("gov3seat" AS BIGINT) AS gov3seat,
    CAST("gov3vote" AS DOUBLE) AS gov3vote,
    CAST("gov3rlc" AS BIGINT) AS gov3rlc,
    CAST("gov3nat" AS BIGINT) AS gov3nat,
    CAST("gov3rurl" AS BIGINT) AS gov3rurl,
    CAST("gov3reg" AS BIGINT) AS gov3reg,
    CAST("gov3rel" AS BIGINT) AS gov3rel,
    CAST("gov3age" AS BIGINT) AS gov3age,
    CAST("govoth" AS BIGINT) AS govoth,
    CAST("govothst" AS BIGINT) AS govothst,
    CAST("govothvt" AS DOUBLE) AS govothvt,
    "opp1me",
    CAST("opp1seat" AS BIGINT) AS opp1seat,
    CAST("opp1vote" AS DOUBLE) AS opp1vote,
    CAST("opp1rlc" AS BIGINT) AS opp1rlc,
    CAST("opp1nat" AS BIGINT) AS opp1nat,
    CAST("opp1rurl" AS BIGINT) AS opp1rurl,
    CAST("opp1reg" AS BIGINT) AS opp1reg,
    CAST("opp1rel" AS BIGINT) AS opp1rel,
    CAST("opp1age" AS BIGINT) AS opp1age,
    "opp2me",
    CAST("opp2seat" AS BIGINT) AS opp2seat,
    CAST("opp2vote" AS DOUBLE) AS opp2vote,
    "opp3me",
    CAST("opp3seat" AS BIGINT) AS opp3seat,
    CAST("opp3vote" AS DOUBLE) AS opp3vote,
    CAST("oppoth" AS BIGINT) AS oppoth,
    CAST("oppothst" AS BIGINT) AS oppothst,
    CAST("oppothvt" AS DOUBLE) AS oppothvt,
    CAST("ulprty" AS BIGINT) AS ulprty,
    CAST("numul" AS BIGINT) AS numul,
    CAST("ulvote" AS DOUBLE) AS ulvote,
    CAST("oppmajh" AS BIGINT) AS oppmajh,
    CAST("oppmajs" AS BIGINT) AS oppmajs,
    CAST("dateleg" AS BIGINT) AS dateleg,
    CAST("dateexec" AS BIGINT) AS dateexec,
    CAST("legelec" AS BIGINT) AS legelec,
    CAST("exelec" AS BIGINT) AS exelec,
    CAST("liec" AS DOUBLE) AS liec,
    CAST("eiec" AS DOUBLE) AS eiec,
    CAST("mdmh" AS DOUBLE) AS mdmh,
    CAST("mdms" AS BIGINT) AS mdms,
    CAST("ssh" AS DOUBLE) AS ssh,
    CAST("pluralty" AS BIGINT) AS pluralty,
    CAST("pr" AS BIGINT) AS pr,
    CAST("housesys" AS DOUBLE) AS housesys,
    CAST("thresh" AS BIGINT) AS thresh,
    CAST("dhondt" AS BIGINT) AS dhondt,
    CAST("cl" AS BIGINT) AS cl,
    CAST("select" AS BIGINT) AS select,
    CAST("fraud" AS BIGINT) AS fraud,
    CAST("auton" AS BIGINT) AS auton,
    CAST("muni" AS BIGINT) AS muni,
    CAST("author" AS BIGINT) AS author,
    CAST("stconst" AS BIGINT) AS stconst,
    CAST("gwno" AS BIGINT) AS gwno,
    CAST("Location_1" AS BIGINT) AS location_1,
    "source_resource"
FROM "idb-database-of-political-institutions-2015"
