-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "SECTION_1" AS section_1,
    "pais",
    "pais_enc",
    "D_name" AS d_name,
    CAST("D_code" AS BIGINT) AS d_code,
    "M_code" AS m_code,
    "M_name" AS m_name,
    "R_code" AS r_code,
    "R_name" AS r_name,
    "ronda",
    CAST("c_weight" AS DOUBLE) AS c_weight,
    CAST("LAC_weight" AS DOUBLE) AS lac_weight,
    CAST("UY_weight" AS DOUBLE) AS uy_weight,
    "SECTION_2" AS section_2,
    "int_user_freq",
    "int_user",
    "int_wifi",
    "int_movil",
    "int_datos_insuf",
    "int_ninguno",
    "int_lento_freq",
    "int_lento",
    "int_satisf_nivel",
    "int_satisf",
    "dis_phone",
    "dis_tablet",
    "dis_pc",
    "dis_none",
    "dis_phone_freq",
    "dis_phone_u",
    "dis_tablet_freq",
    "dis_tablet_u",
    "dis_pc_freq",
    "dis_pc_u",
    "dis_smarttv",
    "dis_smarttv_freq",
    "dis_smarttv_u",
    CAST("hab_TOTAL" AS BIGINT) AS hab_total,
    "hab_email",
    "hab_scan",
    "hab_apps",
    "hab_priv",
    "hab_search",
    "hab_trinfo",
    "hab_infrk",
    "SECTION_3" AS section_3,
    "tram_12m",
    "tram12m_1",
    "tram12m_2",
    "tram12m_3",
    "tram12m_4",
    "tram12m_5",
    "tram12m_6",
    "tram12m_7",
    "tram12m_8",
    "tram12m_9",
    "tram12m_10",
    "tram12m_11",
    "tram12m_12",
    "tram12m_otro",
    "tram12m_otro_des",
    "tram_12m_int",
    "tram_12m_pre",
    "tram_12m_tel",
    "tram12m_acceso",
    "tram_acceso_motivo",
    "tram_acceso_motivo_otro_des",
    "tram_prefonline_1",
    "tram_prefonline_2",
    "tram_prefonline_3",
    "tram_prefonline_4",
    "tram_prefonline_5",
    "tram_prefonline_6",
    "tram_prefonline_7",
    "tram_prefonline_8",
    "tram_prefonline_9",
    "tram_prefonline_10",
    "tram_prefonline_11",
    "tram_prefonline_12",
    "tram_prefonline_otro",
    "tram_prefonline_otro_des",
    "tram_prefonline_none",
    "portal_unico",
    "portal_unico_uso12m",
    "portal_tramites",
    "portal_tram_uso12m",
    "tram_tipo",
    "tipo_ssgov_12m",
    "SECTION_4" AS section_4,
    "tram_last",
    "tram_last_otro_des",
    "tram_l_benef",
    "tram_l_benef_else1",
    "tram_l_benef_else2",
    "tram_l_benef_else3",
    "tram_l_benef_else4",
    "tram_l_benef_else5",
    "tram_l_benef_else6",
    "tram_l_benef_elsenone",
    "tram_l_benef_elseotro",
    "tram_l_benef_elseotro_des",
    "tram_l_canal",
    "tram_l_presencial",
    "tram_l_digital",
    "tram_l_telef",
    "tram_l_tramitador",
    "tram_l_canal_otro_des",
    "tram_l_1sttime",
    "tram_l_knwldig",
    "tram_l_dg_ease",
    "tram_l_dg_reqtime",
    "tram_l_pr_visits",
    "tram_l_pr_trvltime",
    "tram_l_pr_transpm",
    "tram_l_pr_transpm_otro_des",
    "tram_l_pr_queuetime",
    CAST("tram_l_pre_total" AS DOUBLE) AS tram_l_pre_total,
    "tram_l_futcanal",
    "tram_l_futcanal_otro_des",
    "tram_l_futdg",
    "tram_l_futdg_otro_des",
    "SECTION_5A" AS section_5a,
    "sld_citasvirtuales",
    "sld_servdig_1",
    "sld_servdig_2",
    "sld_servdig_3",
    "sld_servdig_4",
    "sld_servdig_5",
    "sld_servdig_6",
    "sld_servdig_none",
    "sld_experiencia",
    "SECTION_5B" AS section_5b,
    "empl_uso",
    "empl_vacantes",
    "empl_followup",
    "empl_followup_ch_1",
    "empl_followup_ch_2",
    "empl_followup_ch_3",
    "empl_followup_ch_4",
    "empl_followup_ch_otro",
    "empl_followup_ch_otro_des",
    "SECTION_5C" AS section_5c,
    "edu_hijos",
    "edu_colegio",
    "edu_colegio_otro_des",
    "edu_canal",
    "edu_canal_otro_des",
    "edu_experiencia",
    "edu_barrera_1",
    "edu_barrera_2",
    "edu_barrera_3",
    "edu_barrera_4",
    "edu_barrera_5",
    "edu_barrera_6",
    "edu_barrera_7",
    "edu_barrera_8",
    "edu_barrera_otro",
    "edu_barrera_otro_des",
    "edu_barrera_none",
    "edu_preferencia",
    "SECTION_5D" AS section_5d,
    "seg_kwlg_ch_pers",
    "seg_kwlg_ch_tel",
    "seg_kwlg_ch_web",
    "seg_kwlg_ch_app",
    "seg_kwlg_ch_none",
    "seg_delito",
    "seg_denuncia",
    "seg_dncia_ch_pers",
    "seg_dncia_ch_tel",
    "seg_dncia_ch_dig",
    "seg_experiencia",
    "SECTION_6" AS section_6,
    "cor_contactos",
    "cor_soborno",
    "cor_denuncia",
    "cor_favsexual",
    "SECTION_7" AS section_7,
    "sexo",
    "edad_cat",
    CAST("edad" AS BIGINT) AS edad,
    "etnia_simpl",
    "etnia_simpl_v2",
    "etnia",
    "etnia_otro_des",
    CAST("indigena" AS BIGINT) AS indigena,
    "afrodescendiente",
    "ninguna_etnia",
    "educacion",
    "educacion_raw",
    "rural",
    "ocupacion_simpl",
    "ocupacion",
    "ocupacion_otro_des",
    "discapacidad",
    "discapacidad_1",
    "discapacidad_2",
    "discapacidad_3",
    "discapacidad_4",
    "discapacidad_5",
    "source_resource"
FROM "idb-citizen-survey-on-government-procedures-and-equity"
