-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("COD_CEN" AS BIGINT) AS cod_cen,
    "MODULO" AS modulo,
    CAST("id_nv" AS BIGINT) AS id_nv,
    CAST("Agemon" AS BIGINT) AS agemon,
    CAST("AGE1" AS BIGINT) AS age1,
    CAST("AGE2" AS BIGINT) AS age2,
    CAST("AGE3" AS BIGINT) AS age3,
    CAST("pa_cuentosimag" AS BIGINT) AS pa_cuentosimag,
    CAST("pa_historia" AS BIGINT) AS pa_historia,
    CAST("cor_corporal" AS BIGINT) AS cor_corporal,
    CAST("asqt_av3areas_zscore" AS DOUBLE) AS asqt_av3areas_zscore,
    CAST("edad_madre" AS BIGINT) AS edad_madre,
    CAST("mat_educ_grade" AS BIGINT) AS mat_educ_grade,
    CAST("bothparenthh" AS BIGINT) AS bothparenthh,
    CAST("hhsize" AS BIGINT) AS hhsize,
    CAST("viv_cuartos" AS BIGINT) AS viv_cuartos,
    CAST("assets" AS BIGINT) AS assets,
    CAST("publicwater" AS BIGINT) AS publicwater,
    CAST("publicsewage" AS BIGINT) AS publicsewage,
    CAST("distance_homecenter" AS BIGINT) AS distance_homecenter,
    CAST("Urban" AS BIGINT) AS urban,
    "cui_type",
    CAST("CL_total_average" AS DOUBLE) AS cl_total_average,
    CAST("CL_emocional_average" AS DOUBLE) AS cl_emocional_average,
    CAST("CL_aprendizaje_average" AS DOUBLE) AS cl_aprendizaje_average,
    CAST("CL_2dim_av_zscore" AS DOUBLE) AS cl_2dim_av_zscore,
    CAST("CL_rawscore_p1" AS DOUBLE) AS cl_rawscore_p1,
    CAST("CL_rawscore_p2" AS DOUBLE) AS cl_rawscore_p2,
    CAST("CL_rawscore_p3" AS DOUBLE) AS cl_rawscore_p3,
    CAST("CL_rawscore_p4" AS DOUBLE) AS cl_rawscore_p4,
    CAST("CL_rawscore_p5" AS DOUBLE) AS cl_rawscore_p5,
    CAST("CL_rawscore_p6" AS DOUBLE) AS cl_rawscore_p6,
    CAST("CL_rawscore_p7" AS DOUBLE) AS cl_rawscore_p7,
    CAST("CL_rawscore_p8" AS DOUBLE) AS cl_rawscore_p8,
    CAST("tot_ninos_aula" AS BIGINT) AS tot_ninos_aula,
    CAST("TOT_6_11" AS BIGINT) AS tot_6_11,
    CAST("TOT_12_17" AS BIGINT) AS tot_12_17,
    CAST("TOT_18_23" AS BIGINT) AS tot_18_23,
    CAST("TOT_24_29" AS BIGINT) AS tot_24_29,
    CAST("TOT_30_35" AS BIGINT) AS tot_30_35,
    CAST("TOT_36_m" AS BIGINT) AS tot_36_m,
    CAST("prop_mujer_aula" AS DOUBLE) AS prop_mujer_aula,
    CAST("edad_prom_marzo14" AS DOUBLE) AS edad_prom_marzo14,
    CAST("cui_exp_center" AS DOUBLE) AS cui_exp_center,
    CAST("cui_educ_grade" AS BIGINT) AS cui_educ_grade,
    CAST("at_id" AS BIGINT) AS at_id,
    CAST("at_exp_center" AS DOUBLE) AS at_exp_center,
    CAST("at_educ_grade" AS BIGINT) AS at_educ_grade,
    CAST("C_light" AS BIGINT) AS c_light,
    CAST("C_water" AS BIGINT) AS c_water,
    CAST("C_sewer" AS BIGINT) AS c_sewer,
    CAST("Female" AS BIGINT) AS female,
    CAST("mat_indigenous" AS BIGINT) AS mat_indigenous,
    CAST("viv_piso_notierra" AS BIGINT) AS viv_piso_notierra,
    CAST("perception_caregiver" AS BIGINT) AS perception_caregiver,
    CAST("cui_indigenous" AS BIGINT) AS cui_indigenous,
    CAST("COD_NIN" AS BIGINT) AS cod_nin,
    CAST("ASQ_raw_co" AS BIGINT) AS asq_raw_co,
    CAST("ASQ_raw_fm" AS BIGINT) AS asq_raw_fm,
    CAST("ASQ_raw_pr" AS BIGINT) AS asq_raw_pr,
    CAST("asqt_st_co_kd" AS DOUBLE) AS asqt_st_co_kd,
    CAST("asqt_st_mf_kd" AS DOUBLE) AS asqt_st_mf_kd,
    CAST("asqt_st_rp_kd" AS DOUBLE) AS asqt_st_rp_kd,
    "source_resource"
FROM "idb-data-associated-with-measuring-quality-and-characterizing-cuna-mas-home-vis"
