-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("ID_QUESTIONNAIRE" AS BIGINT) AS id_questionnaire,
    "AR4_DATE_ENQUETE" AS ar4_date_enquete,
    "AR5_HEURE_DEBUT_ENQUETE" AS ar5_heure_debut_enquete,
    "AS_1_NOM_COLLECTEUR_DE_DONNEES" AS as_1_nom_collecteur_de_donnees,
    "AS_1_1_PRENOM_COLLECTEUR_DE_DONNEES" AS as_1_1_prenom_collecteur_de_donnees,
    "AI1_DEPARTEMENT" AS ai1_departement,
    "AI2_COMMUNE" AS ai2_commune,
    "AI3_SECTION_COMMUNALE" AS ai3_section_communale,
    "AI3_SECTION_COM_MLIEU" AS ai3_section_com_mlieu,
    "AI4_LOCALITE" AS ai4_localite,
    "AI5_1_QUARTIER" AS ai5_1_quartier,
    "AI5_2_RUE_ET_NUMERO" AS ai5_2_rue_et_numero,
    "STRATE" AS strate,
    "PROBABILITE_INCLUSION" AS probabilite_inclusion,
    "PONDERATION" AS ponderation,
    CAST("AI_7_TYPE_DE_COMMUNE" AS BIGINT) AS ai_7_type_de_commune,
    "HR1_CODE_INDIVIDU_REPONDANT" AS hr1_code_individu_repondant,
    "IR_1_PR_NOM" AS ir_1_pr_nom,
    "IR_2_NOM" AS ir_2_nom,
    "IR_3_AGE" AS ir_3_age,
    CAST("IR_4_SEXE" AS BIGINT) AS ir_4_sexe,
    CAST("IR_5_RELATION_AVEC_CHEF_MENAGG" AS BIGINT) AS ir_5_relation_avec_chef_menagg,
    "IR_6_NUMERO_DE_TELEPHONE1" AS ir_6_numero_de_telephone1,
    "IR_7_NUMERO_DE_TELEPHONE2" AS ir_7_numero_de_telephone2,
    "IR_8_NUMERO_TELEPHONE_CHEF_FOYER" AS ir_8_numero_telephone_chef_foyer,
    "IR_9_NUMERO_PHONE_VOISIN_MENAGE" AS ir_9_numero_phone_voisin_menage,
    "IR10_TYPE_ECHANTILLON" AS ir10_type_echantillon,
    CAST("IF1_NOMBRE_DE_FAMILLES_VIVANT_DANS_L" AS BIGINT) AS if1_nombre_de_familles_vivant_dans_l,
    "IF2_NOMBRE_DE_PERSONNES_VIVANT_DANS" AS if2_nombre_de_personnes_vivant_dans,
    "IF3_1_NOMBRE_PERSONNES_PAR_MENAGE_1" AS if3_1_nombre_personnes_par_menage_1,
    "IF3_2_NOMBRE_PERSONNES_PAR_MENAGE_2" AS if3_2_nombre_personnes_par_menage_2,
    "IF3_3_NOMBRE_PERSONNES_PAR_MENAGE_3" AS if3_3_nombre_personnes_par_menage_3,
    "IF3_4_NOMBRE_PERSONNES_PAR_MENAGE_4" AS if3_4_nombre_personnes_par_menage_4,
    "IF3_5_NOMBRE_PERSONNES_PAR_MENAGE_5" AS if3_5_nombre_personnes_par_menage_5,
    "IF3_6_NOMBRE_PERSONNES_PAR_MENAGE_6" AS if3_6_nombre_personnes_par_menage_6,
    "IF4_NOMBRE_PERSONNES_FAMIL" AS if4_nombre_personnes_famil,
    CAST("IF5_NOMBRE_D_ENFANTS_DU_CHEF_DE_FOYE" AS BIGINT) AS if5_nombre_d_enfants_du_chef_de_foye,
    "IF6_SITUATION_ENFANTS_DU_CHEF_DE_FOY" AS if6_situation_enfants_du_chef_de_foy,
    "IF7_NBRE_ENFTS_CHEF_FOY_VIV_AUT_MERE" AS if7_nbre_enfts_chef_foy_viv_aut_mere,
    "IF8_NOMBRE_D_ENFANTS_MORTS_DU_CHEF_D" AS if8_nombre_d_enfants_morts_du_chef_d,
    CAST("IF10_NOMBRE_D_ENFANTS_DU_FEMME_DU_CHE" AS BIGINT) AS if10_nombre_d_enfants_du_femme_du_che,
    CAST("IF9_NOMBRE_D_HOMME_DU_FEMME_DE_CHEF" AS BIGINT) AS if9_nombre_d_homme_du_femme_de_chef,
    CAST("IF11_NBRE_ENF_FEMME_CHEF_FOY_FEMM_ACT" AS BIGINT) AS if11_nbre_enf_femme_chef_foy_femm_act,
    CAST("IF12_NOMBRE_D_ENFANTS_MORTS_DU_FEMME" AS BIGINT) AS if12_nombre_d_enfants_morts_du_femme,
    CAST("IF13_NOMBRE_ENFANTS_ENVIE_NE_VIVANT_D" AS BIGINT) AS if13_nombre_enfants_envie_ne_vivant_d,
    "IF14_NOMBRE_D_ENFANT_VIVANT_DU_MENAGE" AS if14_nombre_d_enfant_vivant_du_menage,
    CAST("IF15_ENFANTS_ADOPTES" AS BIGINT) AS if15_enfants_adoptes,
    "HUDSS1_CODE_GPS_MAISON" AS hudss1_code_gps_maison,
    "HUDSS_1_1_LONGITUDE" AS hudss_1_1_longitude,
    "HUDSS_1_2_LATITUDE" AS hudss_1_2_latitude,
    "HUDSS_1_3_NOMBRE_DE_SATELITE1" AS hudss_1_3_nombre_de_satelite1,
    "HUDSS_1_4_PRECISION_MESURE_GPS1" AS hudss_1_4_precision_mesure_gps1,
    "HUDSS_1_5_TEMPS_DE_MESURE1" AS hudss_1_5_temps_de_mesure1,
    "HUDSS_1_6_DISTANCE_POINTS1" AS hudss_1_6_distance_points1,
    "HU1_TYPE_DE_MAISON" AS hu1_type_de_maison,
    "HU1_1_AUTRE_TYPES_DE_MAISON" AS hu1_1_autre_types_de_maison,
    CAST("HU1_2_ETAT_MAISON" AS BIGINT) AS hu1_2_etat_maison,
    CAST("HU2_TOITURE_MAISON" AS BIGINT) AS hu2_toiture_maison,
    "HU2_1_AUTR_TYP_MATERX_TOIT_MAIS" AS hu2_1_autr_typ_materx_toit_mais,
    "HU2_MATERIAUXCONSTRUCTION_MV" AS hu2_materiauxconstruction_mv,
    "HU2_1_AUTR_TYP_MATERX_MUR_MAIU" AS hu2_1_autr_typ_materx_mur_maiu,
    CAST("HU2_MATERCONSTRUCT_PLANCHER" AS BIGINT) AS hu2_materconstruct_plancher,
    "HU2_1_AUTRTYP_MATERX_PLANCH_MAIS" AS hu2_1_autrtyp_materx_planch_mais,
    "HU3_ROUTE_JUSQUA_MAISON" AS hu3_route_jusqua_maison,
    CAST("HA1_NOMBRE_CHAMBRE_MENAGE" AS BIGINT) AS ha1_nombre_chambre_menage,
    CAST("HA2_NOMBRE_CHAMBRE_A_COUCHER" AS BIGINT) AS ha2_nombre_chambre_a_coucher,
    "HA3_MAISON_CUISINE_INDEPENDANTE" AS ha3_maison_cuisine_independante,
    "HA4_MAISON_AVEC_ELECTRICITE" AS ha4_maison_avec_electricite,
    "HA5_NBRE_HRE_ELECTR_J_6_DERN_MOI" AS ha5_nbre_hre_electr_j_6_dern_moi,
    "HA6_SOURCES_LUMIERES_UTILISEET" AS ha6_sources_lumieres_utiliseet,
    CAST("HA6_1_GENERATRICE" AS BIGINT) AS ha6_1_generatrice,
    CAST("HA6_2_INVERTER" AS BIGINT) AS ha6_2_inverter,
    CAST("HA6_3_ENERGIE_SOLAIRE" AS BIGINT) AS ha6_3_energie_solaire,
    CAST("HA6_4_BOUGIE" AS BIGINT) AS ha6_4_bougie,
    CAST("HA6_5_LAMPE_PROPANE" AS BIGINT) AS ha6_5_lampe_propane,
    CAST("HA6_6_LAMPE_RECHARGEABLE" AS BIGINT) AS ha6_6_lampe_rechargeable,
    CAST("HA6_7_ELECTRICITE_PIC" AS BIGINT) AS ha6_7_electricite_pic,
    CAST("HA6_8_EDH" AS BIGINT) AS ha6_8_edh,
    CAST("HA6_9_AUTRE" AS BIGINT) AS ha6_9_autre,
    "HA6_9_1_AUTR_SOURCE_LUMIERE" AS ha6_9_1_autr_source_lumiere,
    "HA7_ENERGIES_UTILISEES_PR_CUISSO" AS ha7_energies_utilisees_pr_cuisso,
    CAST("HA7_1_PROPANE" AS BIGINT) AS ha7_1_propane,
    CAST("HA7_2_KEROSENE" AS BIGINT) AS ha7_2_kerosene,
    CAST("HA7_3_CHARBON" AS BIGINT) AS ha7_3_charbon,
    CAST("HA7_4_BOIS" AS BIGINT) AS ha7_4_bois,
    CAST("HA7_5_ELECTRICITE" AS BIGINT) AS ha7_5_electricite,
    CAST("HA7_6_ELECTRICITE_PIC" AS BIGINT) AS ha7_6_electricite_pic,
    CAST("HA7_7_ELECTRICITE_EDH" AS BIGINT) AS ha7_7_electricite_edh,
    CAST("HA7_8_AUTRES" AS BIGINT) AS ha7_8_autres,
    "HA7_8_1_AUTR_SOURCES_ENERGIE_CUI" AS ha7_8_1_autr_sources_energie_cui,
    "HA8_TYPE_ENERG_PRINCIPAL_CUISSOO" AS ha8_type_energ_principal_cuissoo,
    "HA8_1_AUTR_TYP_ENERGIE_PRINCIP" AS ha8_1_autr_typ_energie_princip,
    "HA9_MENAGE_POSSEDE_EQUIPMNT_VENU" AS ha9_menage_possede_equipmnt_venu,
    "HA9_1_TYPE_EQUIPEMENT_DE_VENTILATION" AS ha9_1_type_equipement_de_ventilation,
    CAST("HA9_1_1_VENTILATEUR_FIXE" AS BIGINT) AS ha9_1_1_ventilateur_fixe,
    CAST("HA9_1_2_VENTILATEUR_MOBILE" AS BIGINT) AS ha9_1_2_ventilateur_mobile,
    CAST("HA9_1_3_CLIMATISEUR" AS BIGINT) AS ha9_1_3_climatiseur,
    "HA10_MAISON_MENAGE_A_SALLE_BAIN" AS ha10_maison_menage_a_salle_bain,
    "HA10_1_SALL_BAIN_PARTAGE_AV_VOIS" AS ha10_1_sall_bain_partage_av_vois,
    "HA11_MENAGE_POSSEDE_LATRINE_U" AS ha11_menage_possede_latrine_u,
    "HA_12_TYPE_LATRINES_MENAGE" AS ha_12_type_latrines_menage,
    "HA12_1AUTRES_TYPES_DE_LATRINES" AS ha12_1autres_types_de_latrines,
    "HA14_HABITUDE_DESTRUCT_DECHETS" AS ha14_habitude_destruct_dechets,
    CAST("HA_14_1_RAMASES_VOIRIE" AS BIGINT) AS ha_14_1_ramases_voirie,
    CAST("HA_14_2_RAMASES_COMPAGNIE_PRIVEE" AS BIGINT) AS ha_14_2_ramases_compagnie_privee,
    CAST("HA_14_3_BRULES" AS BIGINT) AS ha_14_3_brules,
    CAST("HA_14_4_DECHARGES" AS BIGINT) AS ha_14_4_decharges,
    CAST("HA_14_5_JETES_PLEINE_RUE" AS BIGINT) AS ha_14_5_jetes_pleine_rue,
    CAST("HA_14_6_COMPOSTES" AS BIGINT) AS ha_14_6_compostes,
    CAST("HA_14_7_DETRUITS_AUTRES_MOYENS" AS BIGINT) AS ha_14_7_detruits_autres_moyens,
    "HA15_2_EAU_D_USAGE" AS ha15_2_eau_d_usage,
    CAST("HA15_2_1_EAU_INTERIEURE_MAISON_USAGE" AS BIGINT) AS ha15_2_1_eau_interieure_maison_usage,
    CAST("HA15_2_2_EAU_DISTRIBUEE_ENCEINTE_QUARTIER_USAGE" AS BIGINT) AS ha15_2_2_eau_distribuee_enceinte_quartier_usage,
    CAST("HA15_2_3_PUITS_TERRAIN_MAISON_USAGE" AS BIGINT) AS ha15_2_3_puits_terrain_maison_usage,
    CAST("HA15_2_4_PUITS_ENVIRON_USAGE" AS BIGINT) AS ha15_2_4_puits_environ_usage,
    CAST("HA15_2_5_FONTAINE_PUBLIQUE_USAGE" AS BIGINT) AS ha15_2_5_fontaine_publique_usage,
    CAST("HA15_2_6_CAMION_EAU_USAGE" AS BIGINT) AS ha15_2_6_camion_eau_usage,
    CAST("HA15_2_7_EAU_ACHETEE_SCEAU_USAGE" AS BIGINT) AS ha15_2_7_eau_achetee_sceau_usage,
    CAST("HA15_2_8_EAU_EMBOUTEILLEE_USAGE" AS BIGINT) AS ha15_2_8_eau_embouteillee_usage,
    CAST("HA15_2_9_EAU_PLUIE_USAGE" AS BIGINT) AS ha15_2_9_eau_pluie_usage,
    CAST("HA15_2_10_EAU_RIVIERE_USAGE" AS BIGINT) AS ha15_2_10_eau_riviere_usage,
    CAST("HA15_2_11_AUTRES_SOURCES_APPROV_EAU_USAGE" AS BIGINT) AS ha15_2_11_autres_sources_approv_eau_usage,
    "HA15_2_11_1_AUTRES_SOURCE_APPROVISIONNMT_EAU_USAGE" AS ha15_2_11_1_autres_source_approvisionnmt_eau_usage,
    "HA15_2_EAU_POTABLE" AS ha15_2_eau_potable,
    CAST("HA15_2_1_EAU_INTERIEURE_MAISON_POTABLE" AS BIGINT) AS ha15_2_1_eau_interieure_maison_potable,
    CAST("HA15_2_2_EAU_DISTRIBUEE_ENCEINTE_QUARTIER_POTABLE" AS BIGINT) AS ha15_2_2_eau_distribuee_enceinte_quartier_potable,
    CAST("HA15_2_3_PUITS_TERRAIN_MAISON_POTABLE" AS BIGINT) AS ha15_2_3_puits_terrain_maison_potable,
    CAST("HA15_2_4_PUITS_ENVIRON_POTABLE" AS BIGINT) AS ha15_2_4_puits_environ_potable,
    CAST("HA15_2_5_FONTAINE_PUBLIQUE_POTABLE" AS BIGINT) AS ha15_2_5_fontaine_publique_potable,
    CAST("HA15_2_6_CAMION_EAU_POTABLE" AS BIGINT) AS ha15_2_6_camion_eau_potable,
    CAST("HA15_2_7_EAU_ACHETEE_SCEAU_POTABLE" AS BIGINT) AS ha15_2_7_eau_achetee_sceau_potable,
    CAST("HA15_2_8_EAU_EMBOUTEILLEE_POTABLE" AS BIGINT) AS ha15_2_8_eau_embouteillee_potable,
    CAST("HA15_2_9_EAU_PLUIE_POTABLE" AS BIGINT) AS ha15_2_9_eau_pluie_potable,
    CAST("HA15_2_10_EAU_RIVIERE_POTABLE" AS BIGINT) AS ha15_2_10_eau_riviere_potable,
    CAST("HA15_2_11_AUTRES_SOURCES_APPROV_EAU_POTABLE" AS BIGINT) AS ha15_2_11_autres_sources_approv_eau_potable,
    "HA15_2_11_1_AUTRES_SOURCE_APPROVISIONNMT_EAU_POTABLE" AS ha15_2_11_1_autres_source_approvisionnmt_eau_potable,
    CAST("H16_PRESTATAIRE_SERVICE_EN_EAU" AS BIGINT) AS h16_prestataire_service_en_eau,
    CAST("HA16_1_PUBLIQUE" AS BIGINT) AS ha16_1_publique,
    CAST("HA16_2_PRIVE" AS BIGINT) AS ha16_2_prive,
    CAST("HA16_3_AUTRES_INSTITUTIONS" AS BIGINT) AS ha16_3_autres_institutions,
    CAST("HA16_4_NOTRE_MOYEN" AS BIGINT) AS ha16_4_notre_moyen,
    "HA17_STABILITE_APPROVISIONNEMENT" AS ha17_stabilite_approvisionnement,
    "HA18_SOURCE_PRINCIP_EAU_USAGE" AS ha18_source_princip_eau_usage,
    "HA18_1_AUTR_SOUR_PRINCIPL_EAU_US" AS ha18_1_autr_sour_principl_eau_us,
    "HA_19_SOURCE_PRINCIP_EAU_BOISSON" AS ha_19_source_princip_eau_boisson,
    "HA_19_1_AUTRE_SOURCE_PRINCIP_EAU_BOISSON" AS ha_19_1_autre_source_princip_eau_boisson,
    CAST("HA20_1_NOMBRE_RECIPIENT_STOCKAGE" AS BIGINT) AS ha20_1_nombre_recipient_stockage,
    "HA20_2_TYPE_RECIPIENT_STOCK_EAU" AS ha20_2_type_recipient_stock_eau,
    CAST("HA20_2_1_GALLON" AS BIGINT) AS ha20_2_1_gallon,
    CAST("HA20_2_2_RECIPIENT_5_G" AS BIGINT) AS ha20_2_2_recipient_5_g,
    CAST("HA20_2_3_DRUM" AS BIGINT) AS ha20_2_3_drum,
    CAST("HA20_2_4_TANK" AS BIGINT) AS ha20_2_4_tank,
    CAST("HA20_2_5_RESERVOIR" AS BIGINT) AS ha20_2_5_reservoir,
    CAST("HA20_2_6_AUTRES_RECIPIENT" AS BIGINT) AS ha20_2_6_autres_recipient,
    "HA20_2_6_1_AUTRES_TYPES_DE_RECIPIENT" AS ha20_2_6_1_autres_types_de_recipient,
    "HA21_1_HUMIDITE" AS ha21_1_humidite,
    "HA21_1_TRES_FROID" AS ha21_1_tres_froid,
    "HA21_1_TRES_CHAUD" AS ha21_1_tres_chaud,
    "HA21_1_PEU_VENTILE" AS ha21_1_peu_ventile,
    "HA21_1_TRES_SOMBRE" AS ha21_1_tres_sombre,
    "HA21_1_BEAUCOUP_D_INSECTES" AS ha21_1_beaucoup_d_insectes,
    CAST("HA21_1_BEAUCOUPS_DE_RATS_ET_SOURIS" AS BIGINT) AS ha21_1_beaucoups_de_rats_et_souris,
    "HA21_1_FUITE_DANS_LE_TOIT" AS ha21_1_fuite_dans_le_toit,
    "HA24_2_TERRE" AS ha24_2_terre,
    "HA24_2_MAISON" AS ha24_2_maison,
    "HA24_2_BOEUF" AS ha24_2_boeuf,
    "HA24_2_CABRI" AS ha24_2_cabri,
    CAST("HA24_2_MOUTON" AS BIGINT) AS ha24_2_mouton,
    "HA24_2_PORC" AS ha24_2_porc,
    "HA24_2_POULE" AS ha24_2_poule,
    "HA24_2_CANNARD" AS ha24_2_cannard,
    "HA24_2_DINDE" AS ha24_2_dinde,
    "HA24_2_DEPOT_DE_MARCHANDISE" AS ha24_2_depot_de_marchandise,
    "HA24_2_STOCK_AGRICOLE" AS ha24_2_stock_agricole,
    "HA24_1_REFRIGERATEUR" AS ha24_1_refrigerateur,
    "HA24_1_FOU_ELECTRIQUE_PROPANE_KEROSEN" AS ha24_1_fou_electrique_propane_kerosen,
    "HA24_1_MICROWAVE" AS ha24_1_microwave,
    "HA24_1_VENTILATEUR" AS ha24_1_ventilateur,
    "HA24_1_MACHINE_A_LAVER" AS ha24_1_machine_a_laver,
    "HA24_1_ASPIRATEUR" AS ha24_1_aspirateur,
    "HA24_1_BLENDEUR" AS ha24_1_blendeur,
    "HA24_1_RADIO_LECTEUR_CD" AS ha24_1_radio_lecteur_cd,
    "HA24_1_TELEVISEUR" AS ha24_1_televiseur,
    "HA24_1_ANTENNE_PARABOLIQUE" AS ha24_1_antenne_parabolique,
    "HA24_1_LECTEUR_VIDEO_DVD" AS ha24_1_lecteur_video_dvd,
    "HA24_1_CAMERA_PHOTO_VIDEO" AS ha24_1_camera_photo_video,
    "HA24_1_CLIMATISEUR" AS ha24_1_climatiseur,
    "HA24_1_TELEPHONE_ORDINAIRE" AS ha24_1_telephone_ordinaire,
    "HA24_1_CELLULAIRE" AS ha24_1_cellulaire,
    "HA24_1_ORDINATEUR" AS ha24_1_ordinateur,
    "HA24_1_ACCES_INTERNET" AS ha24_1_acces_internet,
    "HA24_1_VOITURE_CAMION" AS ha24_1_voiture_camion,
    "HA24_1_MOTOCYCLETTE" AS ha24_1_motocyclette,
    "HA24_1_BICYCLETTE" AS ha24_1_bicyclette,
    "HA24_1_HORLOGE" AS ha24_1_horloge,
    CAST("HA24_1_LAMPE_KEROSENE" AS BIGINT) AS ha24_1_lampe_kerosene,
    "HA24_1_LAMPE_PROPANE" AS ha24_1_lampe_propane,
    CAST("HA24_1_LIT_MATELAS_BOX" AS BIGINT) AS ha24_1_lit_matelas_box,
    "HA24_1_PANNEAU_SOLAIRE" AS ha24_1_panneau_solaire,
    "HA24_1_GENERATRICE" AS ha24_1_generatrice,
    "HA24_1_INVERTER_ET_BATTERIES" AS ha24_1_inverter_et_batteries,
    "HA24_1_LAVE_VAISSELLE" AS ha24_1_lave_vaisselle,
    "HAO_1_COURANT_ELECTRIQUE" AS hao_1_courant_electrique,
    "HAO_1_COLLECTE_ORDURES_MENAGERES" AS hao_1_collecte_ordures_menageres,
    "HAO_1_APPROVISIONNEMENT_EAU" AS hao_1_approvisionnement_eau,
    "HAO_1_CONDITIONS_DE_LOGEMENT" AS hao_1_conditions_de_logement,
    "HT1_MODE_DE_TENURE_LOGEMENT" AS ht1_mode_de_tenure_logement,
    "HT1_1_AUTRES_MODES_DE_TENURE" AS ht1_1_autres_modes_de_tenure,
    "HT2_PIECES_DETENUES_LA_MAISON" AS ht2_pieces_detenues_la_maison,
    "HT2_2_AUTRES_PIECES_DETENUES" AS ht2_2_autres_pieces_detenues,
    "HT3_MODE_D_ACCES_MAISON" AS ht3_mode_d_acces_maison,
    "HT3_1_AUTRES_MODE_D_ACCES" AS ht3_1_autres_mode_d_acces,
    "HT4_RELATION_TYPE_DE_LOCATAIRE" AS ht4_relation_type_de_locataire,
    "HT4_1_AUTRES_TYPES_DE_LOCATION" AS ht4_1_autres_types_de_location,
    "HT5_1_FREQUENCE_DE_PAIEMENT" AS ht5_1_frequence_de_paiement,
    "HT5_2_COUT_LOGEMENT_EN_GOURDES" AS ht5_2_cout_logement_en_gourdes,
    "HT5_3_COUT_LOGEMENT_EN_DOLARS" AS ht5_3_cout_logement_en_dolars,
    "HT5_4_COUT_ANNUEL_US" AS ht5_4_cout_annuel_us,
    "HT6_COUT_OPPORTUNITE_LOGEMENT" AS ht6_cout_opportunite_logement,
    "HT6_1_UNITE_MONETAIRE" AS ht6_1_unite_monetaire,
    "HT7_AGRANDISSEMNT_LOGEMNT_PRO_FR" AS ht7_agrandissemnt_logemnt_pro_fr,
    "HT8_LOCATION_FERMAGE_A_AUTRUI" AS ht8_location_fermage_a_autrui,
    "HT9_NOMBRE_CHAMBRE_LOUE__AFFERM" AS ht9_nombre_chambre_loue_afferm,
    "HT10_1_COUT_LOYER_EN_DOLLARS" AS ht10_1_cout_loyer_en_dollars,
    "HE1_1_REVENU_VENTE_PRODUIT_PRIQ" AS he1_1_revenu_vente_produit_priq,
    "HE1_2_REVENU_VENTE_SERV_ARTISANC" AS he1_2_revenu_vente_serv_artisanc,
    "HE1_3_REVENU_VENTE_AUTR_SERVICET" AS he1_3_revenu_vente_autr_servicet,
    "HE3_1_ENGAGE_AUTR_PERS_ACT_PERSP" AS he3_1_engage_autr_pers_act_persp,
    "HE3_2_QUANTITE_PERSONNE_EMBAUCHE" AS he3_2_quantite_personne_embauche,
    "HE4_NBRE_JRS_AUTR_TRAV_DERN_MOIS" AS he4_nbre_jrs_autr_trav_dern_mois,
    "HE4_1_NBRE_HRE_MOYEN_TRAVAIL_JR" AS he4_1_nbre_hre_moyen_travail_jr,
    "HE4_2_SALAIRE_JOURNALIER_PAR_PER" AS he4_2_salaire_journalier_par_per,
    "HE4_3_UNITE_MONETAIRE" AS he4_3_unite_monetaire,
    "HE10_POSSEDE_COMPTE_BANC_IFC" AS he10_possede_compte_banc_ifc,
    "HE12_1_INVESTISSEMENT_EN_CAPITAL_DANS_UN_PROJET" AS he12_1_investissement_en_capital_dans_un_projet,
    "HE12_1_RECOURIR_A_UN_TRAITEMENT_MEDICAL_NECESSAIRE" AS he12_1_recourir_a_un_traitement_medical_necessaire,
    "HE12_1_ENVOYER_LES_ENFANTS_A_L_ECOLE" AS he12_1_envoyer_les_enfants_a_l_ecole,
    "HE12_1_ACHETER_DES_MEUBLES_POUR_LA_MAISON" AS he12_1_acheter_des_meubles_pour_la_maison,
    "HE12_1_ACHETER_OU_RECHARGER_LE_TELEPHONE_MOBILE" AS he12_1_acheter_ou_recharger_le_telephone_mobile,
    "HE12_1_ACHETER_DES_VETEMENTS_NEUFS_PLUTOT_QUE_DE_SECONDE_MAIN" AS he12_1_acheter_des_vetements_neufs_plutot_que_de_seconde_main,
    "HE12_1_MANGER_VIANDE_POULET_POISSON_AUMOINS_3_FOIS_SEMAINE" AS he12_1_manger_viande_poulet_poisson_aumoins_3_fois_semaine,
    "HE18_1_APPUYER_DES_ALIMENTS_MOINS_APPRECIES_ET_MOINS_COUTEUX" AS he18_1_appuyer_des_aliments_moins_apprecies_et_moins_couteux,
    "HE18_1_EMPR_NOURRITURE_EMPR_ARGENT_PR_ACHETER_NOURRITURE" AS he18_1_empr_nourriture_empr_argent_pr_acheter_nourriture,
    "HE18_1_ACHAT_NOURRITURE_A_CREDIT" AS he18_1_achat_nourriture_a_credit,
    "HE18_1_COMPTER_SUR_AIDE_PARENTS_OU_AMI_DEHORS_DE_MAISON" AS he18_1_compter_sur_aide_parents_ou_ami_dehors_de_maison,
    "HE18_1_LIMITER_PORTIONS_A_L_HEURE_DES_REPAS" AS he18_1_limiter_portions_a_l_heure_des_repas,
    "HE18_1_DISTRIBUER_ARGENT_MMBRES_MENAGE_PR_ACHETER_ALIMENTS_RUE" AS he18_1_distribuer_argent_mmbres_menage_pr_acheter_aliments_rue,
    "HE18_1_LIM_CONSOM_ADULT_AFIN_ASSURER_ENFANTS_RECOIVENT_PLUS" AS he18_1_lim_consom_adult_afin_assurer_enfants_recoivent_plus,
    "HE18_1_REDUIRE_LE_NOMBRE_DE_REPAS_PRIS_PAR_JOUR" AS he18_1_reduire_le_nombre_de_repas_pris_par_jour,
    "HE18_1_PASSER_DES_JOURNEES_ENTIERES_SANS_MANGER" AS he18_1_passer_des_journees_entieres_sans_manger,
    "HE19_EVOL_SITUAT_RAPP_2011" AS he19_evol_situat_rapp_2011,
    "HE21_NON_SCOLARITE_PROB_ECONOMIQ" AS he21_non_scolarite_prob_economiq,
    "HE22_NON_SCOLAR_PROB_ECONO_DEC11" AS he22_non_scolar_prob_econo_dec11,
    "HE23_ACTMENT_PB_PAYER_TRANSP_SCO" AS he23_actment_pb_payer_transp_sco,
    "HE24_DEC11_PB_PAY_TRANSP_SCO_TRA" AS he24_dec11_pb_pay_transp_sco_tra,
    "HE25_ACTMENT_PROB_PAYER_CELLPHON" AS he25_actment_prob_payer_cellphon,
    "HE26_DEC11_PROB_PAYER_CELLPHON" AS he26_dec11_prob_payer_cellphon,
    CAST("HE27_ACTUELLEMENT__POSSEDE_INTER" AS BIGINT) AS he27_actuellement_possede_inter,
    CAST("HE28_DEC11_POSSEDE_INTERNET" AS BIGINT) AS he28_dec11_possede_internet,
    "source_resource"
FROM "idb-survey-on-living-conditions-and-social-development-in-northern-haiti-lcsds-"
