-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "region_ch",
    "pais_c",
    "pais_anio_c",
    CAST("anio_c" AS BIGINT) AS anio_c,
    CAST("ronda_c" AS BIGINT) AS ronda_c,
    "idpanel",
    CAST("idh_ch" AS BIGINT) AS idh_ch,
    CAST("idp_ci" AS BIGINT) AS idp_ci,
    CAST("factor_ci" AS BIGINT) AS factor_ci,
    "sexo_ci",
    CAST("edad_ci" AS BIGINT) AS edad_ci,
    "edad_tramo_ci",
    "indigena_ci",
    "afrodescendiente_ci",
    "relacion_ci",
    "civil_ci",
    CAST("nhijos_ch" AS BIGINT) AS nhijos_ch,
    "clasehog_ch",
    CAST("nmayores50_ch" AS BIGINT) AS nmayores50_ch,
    CAST("nmayores65_ch" AS BIGINT) AS nmayores65_ch,
    CAST("nmiembros_ch" AS BIGINT) AS nmiembros_ch,
    "nhijosvivos_ci",
    "niveleducativo_ci",
    CAST("aedu_ci" AS BIGINT) AS aedu_ci,
    "analfabet_ci",
    "tituladoeduniv_ci",
    CAST("finanuniver_1_ci" AS BIGINT) AS finanuniver_1_ci,
    CAST("finanuniver_2_ci" AS BIGINT) AS finanuniver_2_ci,
    CAST("finanuniver_3_ci" AS BIGINT) AS finanuniver_3_ci,
    CAST("finanuniver_4_ci" AS BIGINT) AS finanuniver_4_ci,
    "estudia_ci",
    "condocup_ci",
    CAST("pea_ci" AS BIGINT) AS pea_ci,
    "categoinac_ci",
    "inactiv_otros_ci",
    "empleosadic_ci",
    "antiguedad_mes_ci",
    "antiguedad_anio_ci",
    CAST("durades_ci" AS BIGINT) AS durades_ci,
    "anios_trab_ci",
    "categopri_ci",
    "categosec_ci",
    "rama_ci",
    "spublico_ci",
    "tamemp_ci",
    "tipotrabajo_ci",
    "firmocontrato_ci",
    "ocupa_ci",
    "horaspri_ci",
    "motivodejotrab_ci",
    "edad_1ertrab_ci",
    "indemnizacion_ci",
    "condocup_1a_ci",
    "condocup_2a_ci",
    "categoinac_1a_ci",
    "categoinac_2a_ci",
    CAST("antiguedad_mes_1a_ci" AS BIGINT) AS antiguedad_mes_1a_ci,
    CAST("antiguedad_mes_2a_ci" AS BIGINT) AS antiguedad_mes_2a_ci,
    "categopri_1a_ci",
    "categopri_2a_ci",
    "rama_1a_ci",
    "rama_2a_ci",
    "spublico_1a_ci",
    "spublico_2a_ci",
    "tamemp_1a_ci",
    "tamemp_2a_ci",
    "ocupa_1a_ci",
    "ocupa_2a_ci",
    "horaspri_1a_ci",
    "horaspri_2a_ci",
    "cotiza_1a_ci",
    "cotiza_2a_ci",
    "capacita_ci",
    "tematicacap_ci",
    "duracap_ci",
    "utilidadcap_ci",
    "propcap_ci",
    "financap_1_ci",
    "financap_2_ci",
    "financap_3_ci",
    "financap_4_ci",
    "financap_5_ci",
    "financap_6_ci",
    "jornadacap_ci",
    "afiliado_ci",
    "cotiza_ci",
    "basecotizac_ci",
    "cotizamenos_ci",
    "tipopension_1_ci",
    "tipopension_2_ci",
    "tipopension_3_ci",
    "tipopension_4_ci",
    "edadlegaljub_ci",
    "pension_ci",
    "pension_ej_ci",
    "pensionsub_ci",
    "pensionsub_ej_ci",
    "anioscot_ci",
    "densidadcota_ci",
    "pensitrab_ci",
    "razontrab_1_ci",
    "razontrab_2_ci",
    "razontrab_3_ci",
    "razontrab_4_ci",
    "razontrab_5_ci",
    "motivosnocot_ci",
    "retiroexpec_ci",
    "razonesjub_ci",
    "financiarvejez_1_ci",
    "financiarvejez_2_ci",
    "financiarvejez_3_ci",
    "financiarvejez_4_ci",
    "financiarvejez_5_ci",
    "financiarvejez_6_ci",
    "financiarvejez_7_ci",
    "financiarvejez_8_ci",
    "mesjub_ci",
    "aniodejub_ci",
    "progsocial_ch",
    "licenciaembarazo_ci",
    "volviotrab_ci",
    "maternidadtrab_ci",
    "edadpensi_ci",
    CAST("edadpenmuj_ci" AS BIGINT) AS edadpenmuj_ci,
    CAST("edadpenhom_ci" AS BIGINT) AS edadpenhom_ci,
    "conoce_descpen_ci",
    "conoce_calculopen_ci",
    "cambiadoafp_ci",
    CAST("ncambiosafp_ci" AS BIGINT) AS ncambiosafp_ci,
    "motivocambioafp_ci",
    "comisionafp_ci",
    "pcomisionafp_ci",
    "planahorro_ci",
    "cobsegmed_ci",
    "razonnosalud_ci",
    "fuma_ci",
    "cons_ciga_ci",
    "difactiv_1_ci",
    "difactiv_2_ci",
    "difactiv_3_ci",
    "difactiv_4_ci",
    "difactiv_5_ci",
    "difactiv_6_ci",
    "difactiv_7_ci",
    CAST("promcsalud_ci" AS BIGINT) AS promcsalud_ci,
    "discap_ci",
    "tipodiscap_1_ci",
    "tipodiscap_2_ci",
    "tipodiscap_3_ci",
    "tipodiscap_4_ci",
    "tipodiscap_5_ci",
    "tipodiscap_6_ci",
    "tipodiscap_7_ci",
    "diagenferm_1_ci",
    "diagenferm_2_ci",
    "diagenferm_3_ci",
    "diagenferm_4_ci",
    "diagenferm_5_ci",
    "diagenferm_6_ci",
    "diagenferm_7_ci",
    "diagenferm_8_ci",
    "diagenferm_9_ci",
    "diagenferm_10_ci",
    "diagenferm_11_ci",
    "diagenferm_12_ci",
    "mujpapa_ci",
    "mujmamo_ci",
    "hompros_ci",
    "estadoanimo_1_ci",
    "estadoanimo_2_ci",
    "estadoanimo_3_ci",
    "estadoanimo_4_ci",
    "estadoanimo_5_ci",
    "estadoanimo_6_ci",
    "estadoanimo_7_ci",
    "estadoanimo_8_ci",
    "estadoanimo_9_ci",
    "califsalud_ci",
    "casapropia_ch",
    "credhip_ch",
    "deudas_1_ch",
    "deudas_2_ch",
    "deudas_3_ch",
    "deudas_4_ch",
    "deudas_5_ch",
    "deudas_6_ch",
    "deudas_7_ch",
    "deudas_8_ch",
    "deudas_9_ch",
    "deudas_10_ch",
    "propveh_1_ch",
    "propveh_2_ch",
    "propveh_3_ch",
    "propveh_4_ch",
    "conseguirdinero_ci",
    "pconsigue_ci",
    CAST("seguros_1_ci" AS BIGINT) AS seguros_1_ci,
    CAST("seguros_2_ci" AS BIGINT) AS seguros_2_ci,
    CAST("seguros_3_ci" AS BIGINT) AS seguros_3_ci,
    CAST("seguros_4_ci" AS BIGINT) AS seguros_4_ci,
    CAST("seguros_5_ci" AS BIGINT) AS seguros_5_ci,
    CAST("seguros_6_ci" AS BIGINT) AS seguros_6_ci,
    CAST("seguros_7_ci" AS BIGINT) AS seguros_7_ci,
    CAST("ahorros_1_ci" AS BIGINT) AS ahorros_1_ci,
    CAST("ahorros_2_ci" AS BIGINT) AS ahorros_2_ci,
    CAST("ahorros_3_ci" AS BIGINT) AS ahorros_3_ci,
    CAST("ahorros_4_ci" AS BIGINT) AS ahorros_4_ci,
    CAST("ahorros_5_ci" AS BIGINT) AS ahorros_5_ci,
    CAST("ahorros_6_ci" AS BIGINT) AS ahorros_6_ci,
    CAST("ahorros_7_ci" AS BIGINT) AS ahorros_7_ci,
    "electvivi_ci",
    "alcant_ci",
    "accesoagua_ci",
    "probinfraviv_1_ch",
    "probinfraviv_2_ch",
    "probinfraviv_3_ch",
    "probinfraviv_4_ch",
    "probinfraviv_5_ch",
    "probinfraviv_6_ch",
    "probinfraviv_7_ch",
    "probinfraviv_8_ch",
    "probinfraviv_9_ch",
    "probinfraviv_10_ch",
    "probinfraviv_11_ch",
    "probinfraviv_12_ch",
    "probinfraviv_13_ch",
    "piso_ch",
    "techo_ch",
    "paredes_ch",
    "dorm_ch",
    "pbienes_1_ch",
    "pbienes_2_ch",
    "pbienes_3_ch",
    "pbienes_4_ch",
    "pbienes_5_ch",
    "pbienes_6_ch",
    "pbienes_7_ch",
    "pbienes_8_ch",
    "pbienes_9_ch",
    "pbienes_10_ch",
    "pbienes_11_ch",
    "pbienes_12_ch",
    "pbienes_14_ch",
    "pbienes_15_ch",
    "pbienes_13_ch",
    "pbienes_17_ch",
    "pbienes_16_ch",
    "viviprop_ch",
    CAST("ylmpri_qui_ci" AS BIGINT) AS ylmpri_qui_ci,
    CAST("ylmpri_qmean_cte_ci" AS DOUBLE) AS ylmpri_qmean_cte_ci,
    CAST("ylmpri_qmean_ppa_ci" AS DOUBLE) AS ylmpri_qmean_ppa_ci,
    CAST("ylmpri_1a_qui_ci" AS BIGINT) AS ylmpri_1a_qui_ci,
    CAST("ylmpri_1a_qmean_cte_ci" AS DOUBLE) AS ylmpri_1a_qmean_cte_ci,
    CAST("ylmpri_1a_qmean_ppa_ci" AS DOUBLE) AS ylmpri_1a_qmean_ppa_ci,
    CAST("ylmpri_2a_qui_ci" AS BIGINT) AS ylmpri_2a_qui_ci,
    CAST("ylmpri_2a_qmean_cte_ci" AS DOUBLE) AS ylmpri_2a_qmean_cte_ci,
    CAST("ylmpri_2a_qmean_ppa_ci" AS DOUBLE) AS ylmpri_2a_qmean_ppa_ci,
    CAST("ylmsec_qui_ci" AS BIGINT) AS ylmsec_qui_ci,
    CAST("ylmsec_qmean_cte_ci" AS DOUBLE) AS ylmsec_qmean_cte_ci,
    CAST("ylmsec_qmean_ppa_ci" AS DOUBLE) AS ylmsec_qmean_ppa_ci,
    CAST("ylmotros_qui_ci" AS BIGINT) AS ylmotros_qui_ci,
    CAST("ylmotros_qmean_cte_ci" AS DOUBLE) AS ylmotros_qmean_cte_ci,
    CAST("ylmotros_qmean_ppa_ci" AS DOUBLE) AS ylmotros_qmean_ppa_ci,
    CAST("ylm_qui_ci" AS BIGINT) AS ylm_qui_ci,
    CAST("ylm_qmean_cte_ci" AS DOUBLE) AS ylm_qmean_cte_ci,
    CAST("ylm_qmean_ppa_ci" AS DOUBLE) AS ylm_qmean_ppa_ci,
    CAST("ylm_qui_ch" AS BIGINT) AS ylm_qui_ch,
    CAST("ylm_qmean_cte_ch" AS DOUBLE) AS ylm_qmean_cte_ch,
    CAST("ylm_qmean_ppa_ch" AS DOUBLE) AS ylm_qmean_ppa_ch,
    CAST("ypen_1_qui_ci" AS BIGINT) AS ypen_1_qui_ci,
    CAST("ypen_1_qmean_cte_ci" AS DOUBLE) AS ypen_1_qmean_cte_ci,
    CAST("ypen_1_qmean_ppa_ci" AS DOUBLE) AS ypen_1_qmean_ppa_ci,
    CAST("ypen_2_qui_ci" AS BIGINT) AS ypen_2_qui_ci,
    CAST("ypen_2_qmean_cte_ci" AS DOUBLE) AS ypen_2_qmean_cte_ci,
    CAST("ypen_2_qmean_ppa_ci" AS DOUBLE) AS ypen_2_qmean_ppa_ci,
    CAST("ypen_3_qui_ci" AS BIGINT) AS ypen_3_qui_ci,
    CAST("ypen_3_qmean_cte_ci" AS DOUBLE) AS ypen_3_qmean_cte_ci,
    CAST("ypen_3_qmean_ppa_ci" AS DOUBLE) AS ypen_3_qmean_ppa_ci,
    CAST("ypencont_qui_ci" AS BIGINT) AS ypencont_qui_ci,
    CAST("ypencont_qmean_cte_ci" AS DOUBLE) AS ypencont_qmean_cte_ci,
    CAST("ypencont_qmean_ppa_ci" AS DOUBLE) AS ypencont_qmean_ppa_ci,
    CAST("ypensub_qui_ci" AS BIGINT) AS ypensub_qui_ci,
    CAST("ypensub_qmean_cte_ci" AS DOUBLE) AS ypensub_qmean_cte_ci,
    CAST("ypensub_qmean_ppa_ci" AS DOUBLE) AS ypensub_qmean_ppa_ci,
    CAST("ysubhog_1_qui_ch" AS BIGINT) AS ysubhog_1_qui_ch,
    CAST("ysubhog_1_qmean_cte_ch" AS DOUBLE) AS ysubhog_1_qmean_cte_ch,
    CAST("ysubhog_1_qmean_ppa_ch" AS DOUBLE) AS ysubhog_1_qmean_ppa_ch,
    CAST("ysubhog_2_qui_ch" AS BIGINT) AS ysubhog_2_qui_ch,
    CAST("ysubhog_2_qmean_cte_ch" AS DOUBLE) AS ysubhog_2_qmean_cte_ch,
    CAST("ysubhog_2_qmean_ppa_ch" AS DOUBLE) AS ysubhog_2_qmean_ppa_ch,
    CAST("ysubhog_3_qui_ch" AS BIGINT) AS ysubhog_3_qui_ch,
    CAST("ysubhog_3_qmean_cte_ch" AS DOUBLE) AS ysubhog_3_qmean_cte_ch,
    CAST("ysubhog_3_qmean_ppa_ch" AS DOUBLE) AS ysubhog_3_qmean_ppa_ch,
    CAST("ysubhog_4_qui_ch" AS BIGINT) AS ysubhog_4_qui_ch,
    CAST("ysubhog_4_qmean_cte_ch" AS DOUBLE) AS ysubhog_4_qmean_cte_ch,
    CAST("ysubhog_4_qmean_ppa_ch" AS DOUBLE) AS ysubhog_4_qmean_ppa_ch,
    CAST("gastohogar_1_qui_ch" AS BIGINT) AS gastohogar_1_qui_ch,
    CAST("gastohogar_1_qmean_cte_ch" AS DOUBLE) AS gastohogar_1_qmean_cte_ch,
    CAST("gastohogar_1_qmean_ppa_ch" AS DOUBLE) AS gastohogar_1_qmean_ppa_ch,
    CAST("gastohogar_2_qui_ch" AS BIGINT) AS gastohogar_2_qui_ch,
    CAST("gastohogar_2_qmean_cte_ch" AS DOUBLE) AS gastohogar_2_qmean_cte_ch,
    CAST("gastohogar_2_qmean_ppa_ch" AS DOUBLE) AS gastohogar_2_qmean_ppa_ch,
    CAST("gastohogar_3_qui_ch" AS BIGINT) AS gastohogar_3_qui_ch,
    CAST("gastohogar_3_qmean_cte_ch" AS DOUBLE) AS gastohogar_3_qmean_cte_ch,
    CAST("gastohogar_3_qmean_ppa_ch" AS DOUBLE) AS gastohogar_3_qmean_ppa_ch,
    CAST("gastohogar_4_qui_ch" AS BIGINT) AS gastohogar_4_qui_ch,
    CAST("gastohogar_4_qmean_cte_ch" AS DOUBLE) AS gastohogar_4_qmean_cte_ch,
    CAST("gastohogar_4_qmean_ppa_ch" AS DOUBLE) AS gastohogar_4_qmean_ppa_ch,
    CAST("gastohogar_5_qui_ch" AS BIGINT) AS gastohogar_5_qui_ch,
    CAST("gastohogar_5_qmean_cte_ch" AS DOUBLE) AS gastohogar_5_qmean_cte_ch,
    CAST("gastohogar_5_qmean_ppa_ch" AS DOUBLE) AS gastohogar_5_qmean_ppa_ch,
    CAST("vivialq_qui_ch" AS BIGINT) AS vivialq_qui_ch,
    CAST("vivialq_qmean_cte_ch" AS DOUBLE) AS vivialq_qmean_cte_ch,
    CAST("vivialq_qmean_ppa_ch" AS DOUBLE) AS vivialq_qmean_ppa_ch,
    CAST("rentaimp_qui_ch" AS BIGINT) AS rentaimp_qui_ch,
    CAST("rentaimp_qmean_cte_ch" AS DOUBLE) AS rentaimp_qmean_cte_ch,
    CAST("rentaimp_qmean_ppa_ch" AS DOUBLE) AS rentaimp_qmean_ppa_ch,
    CAST("montoindem_qui_ci" AS BIGINT) AS montoindem_qui_ci,
    CAST("montoindem_qmean_cte_ci" AS DOUBLE) AS montoindem_qmean_cte_ci,
    CAST("montoindem_qmean_ppa_ci" AS DOUBLE) AS montoindem_qmean_ppa_ci,
    "source_resource"
FROM "idb-harmonized-longitudinal-social-protection-survey-lsps-database-2016"
