-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "id",
    "year",
    "country",
    "debtccgov",
    "debtcb",
    "totaldebt",
    "gdp",
    "exchangeratencperusd",
    "debt_gdp",
    "domestogdp",
    "exttogdp",
    "officialdebt",
    "totalnonofficialdebt",
    "foreignbanks",
    "dombanks",
    "totalbank",
    "ext_resholders",
    "ext_nonresholders",
    "ext_marketinstrument",
    "int_resholders",
    "int_nonresholders",
    "dom_market",
    "total_mkt",
    "ext_oth",
    "int_oth",
    "tot_oth",
    "offdom",
    "bankdom",
    "mardom",
    "othdom",
    "credtype_int_sumshares",
    "offext",
    "bankext",
    "marext",
    "othext",
    "credtype_ext_sumshares",
    "credtype_total",
    "officialexternaldebt",
    "nonofficialexternaldebt",
    "external",
    "totaldomestic",
    "legandcred_total",
    "legandcred_ext_tot",
    "legandcred_int_tot",
    "for_ext",
    "for_int",
    "dom_ext",
    "dom_int",
    "currandleg_total",
    "totaldebt_short_term_ext",
    "totaldebt_short_term_int",
    "totaldebt_short_term",
    "totaldebt_med_term_ext",
    "totaldebt_med_term_int",
    "totaldebt_med_term",
    "totaldebt_long_term_ext",
    "totaldebt_long_term_int",
    "totaldebt_long_term",
    "avgmat_ext",
    "avgmat_int",
    "avgmat_totaldebt",
    "matandleg_total",
    "short_extcurr",
    "short_intcurr",
    "matandcurr_short_tot",
    "med_extcurr",
    "med_intcurr",
    "matandcurr_med_tot",
    "long_extcurr",
    "long_intcurr",
    "matandcurr_long_tot",
    "matandcurr_tot",
    "avgmat_extcurr",
    "avgmat_intcurr",
    "for_n-i_fr" AS for_n_i_fr,
    "for_n-i_flr" AS for_n_i_flr,
    "for_i_fr",
    "for_i_flr",
    "tot_debt_for",
    "dom_n-i_fr" AS dom_n_i_fr,
    "dom_n-i_flr" AS dom_n_i_flr,
    "dom_i_fr",
    "dom_i_flr",
    "tot_debt_dom",
    "debt_index",
    "debt_nonindex",
    "currandrate_tot",
    "heldby_cb",
    "heldby_others",
    "heldby_tot",
    "Liqassetscg" AS liqassetscg,
    "net_debt_1",
    "crossholding",
    "net_debt_2",
    "reserves",
    "net_debt_3",
    "PPFassets" AS ppfassets,
    "net_debt_4",
    "pay_ppcal_ext",
    "pay_ppal_int",
    "pay_ppal_tot",
    "pay_int_ext",
    "pay_int_int",
    "pay_int_tot",
    "pay_tot_kind",
    "pay_ppal_CB" AS pay_ppal_cb,
    "pay_int_CB" AS pay_int_cb,
    "pay_CB_tot" AS pay_cb_tot,
    "pay_ppal_oth",
    "pay_int_oth",
    "pay_oth_tot",
    "pay_tot_holders",
    "bycurr_debt_for",
    "bycurr_debt_dom",
    "bycurr_debt_index",
    "due_1y_ppal_ext",
    "due_1y_ppal_int",
    "due_1y_ppal_tot",
    "due_1y_int_ext",
    "due_1y_int_int",
    "due_1y_int_tot",
    "due_1y_tot_kind",
    "due_2y_ppal_ext",
    "due_2y_ppal_int",
    "due_2y_ppal_tot",
    "due_2y_int_ext",
    "due_2y_int_int",
    "due_2y_int_tot",
    "due_2y_tot_kind",
    "due_3y_ppal_ext",
    "due_3y_ppal_int",
    "due_3y_ppal_tot",
    "due_3y_int_ext",
    "due_3y_int_int",
    "due_3y_int_tot",
    "due_3y_tot_kind",
    "due_4y_ppal_ext",
    "due_4y_ppal_int",
    "due_4y_ppal_tot",
    "due_4y_int_ext",
    "due_4y_int_int",
    "due_4y_int_tot",
    "due_4y_tot_kind",
    "due_5y_ppal_ext",
    "due_5y_ppal_int",
    "due_5y_ppal_tot",
    "due_5y_int_ext",
    "due_5y_int_int",
    "due_5y_int_tot",
    "due_5y_tot_kind",
    "due_6y_10y_ppal_ext",
    "due_6y_10y_ppal_int",
    "due_6y_10y_ppal_tot",
    "due_6y_10y_int_ext",
    "due_6y_10y_int_int",
    "due_6y_10y_int_tot",
    "due_6y_10y_tot_kind",
    "due_11y_ppal_ext",
    "due_11y_ppal_int",
    "due_11y_ppal_tot",
    "due_11y_int_ext",
    "due_11y_int_int",
    "due_11y_int_tot",
    "due_11y_tot_kind",
    "due_1y_ppal_CB" AS due_1y_ppal_cb,
    "due_1y_int_CB" AS due_1y_int_cb,
    "due_1y_tot_CB" AS due_1y_tot_cb,
    "due_1y_ppal_oth",
    "due_1y_int_oth",
    "due_1y_tot_oth",
    "due_2y_ppal_CB" AS due_2y_ppal_cb,
    "due_2y_int_CB" AS due_2y_int_cb,
    "due_2y_tot_CB" AS due_2y_tot_cb,
    "due_2y_ppal_oth",
    "due_2y_int_oth",
    "due_2y_tot_oth",
    "due_3y_ppal_CB" AS due_3y_ppal_cb,
    "due_3y_int_CB" AS due_3y_int_cb,
    "due_3y_tot_CB" AS due_3y_tot_cb,
    "due_3y_ppal_oth",
    "due_3y_int_oth",
    "due_3y_tot_oth",
    "due_4y_ppal_CB" AS due_4y_ppal_cb,
    "due_4y_int_CB" AS due_4y_int_cb,
    "due_4y_tot_CB" AS due_4y_tot_cb,
    "due_4y_ppal_oth",
    "due_4y_int_oth",
    "due_4y_tot_oth",
    "due_5y_ppal_CB" AS due_5y_ppal_cb,
    "due_5y_int_CB" AS due_5y_int_cb,
    "due_5y_tot_CB" AS due_5y_tot_cb,
    "due_5y_ppal_oth",
    "due_5y_int_oth",
    "due_5y_tot_oth",
    "due_6y_10y_ppal_CB" AS due_6y_10y_ppal_cb,
    "due_6y_10y_int_CB" AS due_6y_10y_int_cb,
    "due_6y_10y_tot_CB" AS due_6y_10y_tot_cb,
    "due_6y_10y_ppal_oth",
    "due_6y_10y_int_oth",
    "due_6y_10y_tot_oth",
    "due_11y_ppal_CB" AS due_11y_ppal_cb,
    "due_11y_int_CB" AS due_11y_int_cb,
    "due_11y_tot_CB" AS due_11y_tot_cb,
    "due_11y_ppal_oth",
    "due_int_oth",
    "due_11y_tot_oth",
    "source_resource"
FROM "idb-latin-america-and-the-caribbean-standardized-public-debt-database-data-as-of-december-2024"
