-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "INTERVIEW_LOC" AS interview_loc,
    "MUNICIP" AS municip,
    CAST("ID_INTERVIEWER_HH" AS BIGINT) AS id_interviewer_hh,
    CAST("ID_SUPERVISOR_HH" AS BIGINT) AS id_supervisor_hh,
    "NUM_WOMAN" AS num_woman,
    CAST("AGE_WOMANSPEC" AS BIGINT) AS age_womanspec,
    "MAR_STATUS" AS mar_status,
    "EDU_WOM" AS edu_wom,
    "INCOME_HOUSE" AS income_house,
    "NUM_CHILDREN" AS num_children,
    CAST("NUM_CHILDRENSPEC" AS BIGINT) AS num_childrenspec,
    "NUM_OTHCHILD" AS num_othchild,
    CAST("NUM_OTHCHILDSPEC" AS BIGINT) AS num_othchildspec,
    "ANY_KIDS_LAST_2_YEARS" AS any_kids_last_2_years,
    CAST("NUM_KIDS_LAST_2_YEARS" AS BIGINT) AS num_kids_last_2_years,
    CAST("KID1_AGESPEC" AS BIGINT) AS kid1_agespec,
    "KID1_DOB" AS kid1_dob,
    "ANC1" AS anc1,
    "ANC_TIMES" AS anc_times,
    CAST("ANC_TIMESSPEC" AS BIGINT) AS anc_timesspec,
    "ANC_SKILLED" AS anc_skilled,
    "DEL_DOC_W1" AS del_doc_w1,
    "DEL_PRONUR_W1" AS del_pronur_w1,
    "DEL_AUXNUR_W1" AS del_auxnur_w1,
    "DEL_LABTECH_W1" AS del_labtech_w1,
    "DEL_MW_W1" AS del_mw_w1,
    "DEL_CHW_W1" AS del_chw_w1,
    "DEL_PHARM_W1" AS del_pharm_w1,
    "DEL_TRAD_W1" AS del_trad_w1,
    "DEL_REL_W1" AS del_rel_w1,
    "DEL_OTH_W1" AS del_oth_w1,
    "DEL_WHERE" AS del_where,
    "BF_EVER1" AS bf_ever1,
    "BF_START1" AS bf_start1,
    CAST("BF_START1HR" AS BIGINT) AS bf_start1hr,
    CAST("BF_START1DAY" AS BIGINT) AS bf_start1day,
    "KID2_AGE" AS kid2_age,
    CAST("KID2_AGESPEC" AS BIGINT) AS kid2_agespec,
    "KID2_DOB" AS kid2_dob,
    "ANC2" AS anc2,
    "ANC2_TIMES" AS anc2_times,
    CAST("ANC2_TIMESSPEC" AS BIGINT) AS anc2_timesspec,
    "ANC2_SKILLED" AS anc2_skilled,
    "DEL_DOC_W2" AS del_doc_w2,
    "DEL_PRONUR_W2" AS del_pronur_w2,
    "DEL_AUXNUR_W2" AS del_auxnur_w2,
    "DEL_LABTECH_W2" AS del_labtech_w2,
    "DEL_MW_W2" AS del_mw_w2,
    "DEL_CHW_W2" AS del_chw_w2,
    "DEL_PHARM_W2" AS del_pharm_w2,
    "DEL_TRAD_W2" AS del_trad_w2,
    "DEL_REL_W2" AS del_rel_w2,
    "DEL_OTH_W2" AS del_oth_w2,
    "DEL2_WHERE" AS del2_where,
    "BF_EVER2" AS bf_ever2,
    "ANY_OKIDS_LAST_2_YEARS" AS any_okids_last_2_years,
    CAST("NUM_OKIDS_LAST_2_YEARS" AS BIGINT) AS num_okids_last_2_years,
    "OTHDEL_DOC_W1" AS othdel_doc_w1,
    "OTHDEL_PRONUR_W1" AS othdel_pronur_w1,
    "OTHDEL_AUXNUR_W1" AS othdel_auxnur_w1,
    "OTHDEL_LABTECH_W1" AS othdel_labtech_w1,
    "OTHDEL_MW_W1" AS othdel_mw_w1,
    "OTHDEL_CHW_W1" AS othdel_chw_w1,
    "OTHDEL_PHARM_W1" AS othdel_pharm_w1,
    "OTHDEL_TRAD_W1" AS othdel_trad_w1,
    "OTHDEL_REL_W1" AS othdel_rel_w1,
    "OTHDEL_OTH_W1" AS othdel_oth_w1,
    "DEL_WHEREOTH" AS del_whereoth,
    "BF_EVER1OTH" AS bf_ever1oth,
    "INT_DANGER" AS int_danger,
    "INT_DANGERNOEAT" AS int_dangernoeat,
    "INT_DANGERLETH" AS int_dangerleth,
    "INT_DANGERBREATH" AS int_dangerbreath,
    "INT_DANGERFEVER" AS int_dangerfever,
    "INT_DANGERCOLD" AS int_dangercold,
    "INT_DANGERDK" AS int_dangerdk,
    "INT_DANGERDTR" AS int_dangerdtr,
    "PREG1_W1" AS preg1_w1,
    "M1_FST_HEARD_W1" AS m1_fst_heard_w1,
    "M2_MST_HEARD_W1" AS m2_mst_heard_w1,
    "M3_IUD_HEARD_W1" AS m3_iud_heard_w1,
    "M4_INJ_HEARD_W1" AS m4_inj_heard_w1,
    "M5_IMP_HEARD_W1" AS m5_imp_heard_w1,
    "M6_OCP_HEARD_W1" AS m6_ocp_heard_w1,
    "M7_CON_HEARD_W1" AS m7_con_heard_w1,
    "M8_FCO_HEARD_W1" AS m8_fco_heard_w1,
    "M9_DIA_HEARD_W1" AS m9_dia_heard_w1,
    "M10_SPO_HEARD_W1" AS m10_spo_heard_w1,
    "M11_LAM_HEARD_W1" AS m11_lam_heard_w1,
    "M12_RHY_HEARD_W1" AS m12_rhy_heard_w1,
    "M13_WDR_HEARD_W1" AS m13_wdr_heard_w1,
    "M14_EMC_HEARD_W1" AS m14_emc_heard_w1,
    "M15_OMO_HEARD_W1" AS m15_omo_heard_w1,
    "M16_OTR_HEARD_W1" AS m16_otr_heard_w1,
    "M1_FST_USENOW_W1" AS m1_fst_usenow_w1,
    "M2_MST_USENOW_W1" AS m2_mst_usenow_w1,
    "M3_IUD_USENOW_W1" AS m3_iud_usenow_w1,
    "M4_INJ_USENOW_W1" AS m4_inj_usenow_w1,
    "M5_IMP_USENOW_W1" AS m5_imp_usenow_w1,
    "M6_OCP_USENOW_W1" AS m6_ocp_usenow_w1,
    "M7_CON_USENOW_W1" AS m7_con_usenow_w1,
    "M8_FCO_USENOW_W1" AS m8_fco_usenow_w1,
    "M9_DIA_USENOW_W1" AS m9_dia_usenow_w1,
    "M10_SPO_USENOW_W1" AS m10_spo_usenow_w1,
    "M11_LAM_USENOW_W1" AS m11_lam_usenow_w1,
    "M12_RHY_USENOW_W1" AS m12_rhy_usenow_w1,
    "M13_WDR_USENOW_W1" AS m13_wdr_usenow_w1,
    "M14_EMC_USENOW_W1" AS m14_emc_usenow_w1,
    "M15_OMO_USENOW_W1" AS m15_omo_usenow_w1,
    "M16_OTR_USENOW_W1" AS m16_otr_usenow_w1,
    "FP_NOUSE_W1" AS fp_nouse_w1,
    "FP_NOUSE_W1UNMAR" AS fp_nouse_w1unmar,
    "FP_NOUSE_W1MAR" AS fp_nouse_w1mar,
    "FP_NOUSE_W1NOSEX" AS fp_nouse_w1nosex,
    "FP_NOUSE_W1VIR" AS fp_nouse_w1vir,
    "FP_NOUSE_W1INFREQ" AS fp_nouse_w1infreq,
    "FP_NOUSE_W1MENO" AS fp_nouse_w1meno,
    "FP_NOUSE_W1HYST" AS fp_nouse_w1hyst,
    "FP_NOUSE_W1INFERT" AS fp_nouse_w1infert,
    "FP_NOUSE_W1CYCLE" AS fp_nouse_w1cycle,
    "FP_NOUSE_W1BF" AS fp_nouse_w1bf,
    "FP_NOUSE_W1RELIG" AS fp_nouse_w1relig,
    "FP_NOUSE_W1OPP" AS fp_nouse_w1opp,
    "FP_NOUSE_W1SPOPP" AS fp_nouse_w1spopp,
    "FP_NOUSE_W1OTHOPP" AS fp_nouse_w1othopp,
    "FP_NOUSE_W1KNOWN" AS fp_nouse_w1known,
    "FP_NOUSE_W1SOURCE" AS fp_nouse_w1source,
    "FP_NOUSE_W1SIDE" AS fp_nouse_w1side,
    "FP_NOUSE_W1FAR" AS fp_nouse_w1far,
    "FP_NOUSE_W1TRANSP" AS fp_nouse_w1transp,
    "FP_NOUSE_W1TRANSPCOST" AS fp_nouse_w1transpcost,
    "FP_NOUSE_W1COST" AS fp_nouse_w1cost,
    "FP_NOUSE_W1NAPREF" AS fp_nouse_w1napref,
    "FP_NOUSE_W1NA" AS fp_nouse_w1na,
    "FP_NOUSE_W1PERS" AS fp_nouse_w1pers,
    "FP_NOUSE_W1TRUST" AS fp_nouse_w1trust,
    "FP_NOUSE_W1UNCOMF" AS fp_nouse_w1uncomf,
    "FP_NOUSE_W1UNNAT" AS fp_nouse_w1unnat,
    "FP_NOUSE_W1NOLIKE" AS fp_nouse_w1nolike,
    "FP_NOUSE_W1PREG" AS fp_nouse_w1preg,
    "FP_NOUSE_W1WANTPR" AS fp_nouse_w1wantpr,
    "FP_NOUSE_W1OTH" AS fp_nouse_w1oth,
    "FP_NOUSE_W1OTHSPEC" AS fp_nouse_w1othspec,
    "FP_NOUSE_W1DK" AS fp_nouse_w1dk,
    "FP_NOUSE_W1DTR" AS fp_nouse_w1dtr,
    CAST("TOTAL_CHILDREN" AS BIGINT) AS total_children,
    "ID_WOMAN" AS id_woman,
    "ID_KID" AS id_kid,
    "KIDS_DOB" AS kids_dob,
    "KIDS_BIO" AS kids_bio,
    "FOOD_BF" AS food_bf,
    "FOOD_OTH" AS food_oth,
    "FOOD_OTH_DRINKS" AS food_oth_drinks,
    "DIARRHEA" AS diarrhea,
    "DIARRHEA_DRINK1" AS diarrhea_drink1,
    "DIARRHEA_DRINK2" AS diarrhea_drink2,
    "DIARRHEA_DRINK3" AS diarrhea_drink3,
    "DIARRHEA4" AS diarrhea4,
    "DIARRHEA_RX1" AS diarrhea_rx1,
    "DIARRHEA_RX2" AS diarrhea_rx2,
    "DIARRHEA_RX3" AS diarrhea_rx3,
    "DIARRHEA_RX4" AS diarrhea_rx4,
    "DIARRHEA_RX5" AS diarrhea_rx5,
    "DIARRHEA_RX11" AS diarrhea_rx11,
    "DIARRHEA_RX12" AS diarrhea_rx12,
    "DIARRHEA_RX13" AS diarrhea_rx13,
    "DIARRHEA_RX14" AS diarrhea_rx14,
    "DIARRHEA_RX15" AS diarrhea_rx15,
    "DIARRHEA_RX6" AS diarrhea_rx6,
    "DIARRHEA_RX7" AS diarrhea_rx7,
    "DIARRHEA_RX8" AS diarrhea_rx8,
    "DIARRHEA_RX9" AS diarrhea_rx9,
    "DIARRHEA_RX10" AS diarrhea_rx10,
    "DIARRHEA_RXOTH" AS diarrhea_rxoth,
    "DIARRHEA_RXDK" AS diarrhea_rxdk,
    "MICRO_CONS" AS micro_cons,
    "MICRO_CONS_NUM" AS micro_cons_num,
    CAST("MICRO_CONS_NUMSPEC" AS BIGINT) AS micro_cons_numspec,
    "WORMS" AS worms,
    "WORMS_TIMES" AS worms_times,
    CAST("WORMS_TIMESSPEC" AS BIGINT) AS worms_timesspec,
    "VACANY" AS vacany,
    "VACANY_BCG" AS vacany_bcg,
    CAST("VACANY_BCGSPEC" AS BIGINT) AS vacany_bcgspec,
    "VACANY_PENTA" AS vacany_penta,
    CAST("VACANY_PENTASPEC" AS BIGINT) AS vacany_pentaspec,
    "VACANY_POLIO" AS vacany_polio,
    CAST("VACANY_POLIOSPEC" AS BIGINT) AS vacany_poliospec,
    "VACANY_DPT" AS vacany_dpt,
    CAST("VACANY_DPTSPEC" AS BIGINT) AS vacany_dptspec,
    "VACANY_MMR" AS vacany_mmr,
    CAST("VACANY_MMRSPEC" AS BIGINT) AS vacany_mmrspec,
    "VACANY_HEPB" AS vacany_hepb,
    CAST("VACANY_HEPBSPEC" AS BIGINT) AS vacany_hepbspec,
    "VACANY_ROTA" AS vacany_rota,
    CAST("VACANY_ROTASPEC" AS BIGINT) AS vacany_rotaspec,
    "VACANY_PNEUM" AS vacany_pneum,
    CAST("VACANY_PNEUMSPEC" AS BIGINT) AS vacany_pneumspec,
    "VACCARD" AS vaccard,
    "VACCARD_BCG" AS vaccard_bcg,
    CAST("VACCARD_BCGSPEC" AS BIGINT) AS vaccard_bcgspec,
    "VACCARD_PENTA" AS vaccard_penta,
    CAST("VACCARD_PENTASPEC" AS BIGINT) AS vaccard_pentaspec,
    "VACCARD_POLIO" AS vaccard_polio,
    CAST("VACCARD_POLIOSPEC" AS BIGINT) AS vaccard_poliospec,
    "VACCARD_DPT" AS vaccard_dpt,
    CAST("VACCARD_DPTSPEC" AS BIGINT) AS vaccard_dptspec,
    "VACCARD_MMR" AS vaccard_mmr,
    CAST("VACCARD_MMRSPEC" AS BIGINT) AS vaccard_mmrspec,
    "VACCARD_HEPB" AS vaccard_hepb,
    CAST("VACCARD_HEPBSPEC" AS BIGINT) AS vaccard_hepbspec,
    "VACCARD_ROTA" AS vaccard_rota,
    CAST("VACCARD_ROTASPEC" AS BIGINT) AS vaccard_rotaspec,
    "VACCARD_PNEUM" AS vaccard_pneum,
    CAST("VACCARD_PNEUMSPEC" AS BIGINT) AS vaccard_pneumspec,
    "source_resource"
FROM "idb-baseline-health-mesoamerica-belize-lqas-survey-2015"
