-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("id_i" AS BIGINT) AS id_i,
    CAST("s1" AS BIGINT) AS s1,
    CAST("s2" AS BIGINT) AS s2,
    CAST("s3" AS BIGINT) AS s3,
    CAST("mujer" AS BIGINT) AS mujer,
    CAST("edad_meses_2" AS BIGINT) AS edad_meses_2,
    CAST("b_meses_c" AS BIGINT) AS b_meses_c,
    CAST("bl_edad_madre" AS BIGINT) AS bl_edad_madre,
    CAST("bl_yeduc_resp" AS BIGINT) AS bl_yeduc_resp,
    CAST("bl_madre_indi_en" AS BIGINT) AS bl_madre_indi_en,
    CAST("bl_madreypadre_en_hog" AS BIGINT) AS bl_madreypadre_en_hog,
    CAST("bl_tamano_hogar" AS BIGINT) AS bl_tamano_hogar,
    CAST("bl_cuartos" AS BIGINT) AS bl_cuartos,
    CAST("bl_assets" AS BIGINT) AS bl_assets,
    CAST("bl_agua_vivienda" AS BIGINT) AS bl_agua_vivienda,
    CAST("bl_serv_higienicos2" AS BIGINT) AS bl_serv_higienicos2,
    CAST("bl_piso_no_tierra" AS BIGINT) AS bl_piso_no_tierra,
    CAST("total_visitas" AS BIGINT) AS total_visitas,
    CAST("Q12_dur_meses" AS BIGINT) AS q12_dur_meses,
    "Q10A" AS q10a,
    CAST("Q10B" AS BIGINT) AS q10b,
    CAST("fci_playactivities_yn" AS BIGINT) AS fci_playactivities_yn,
    CAST("fci_playactivities_yn_FA" AS DOUBLE) AS fci_playactivities_yn_fa,
    CAST("fci_var_playmaterials_yn" AS BIGINT) AS fci_var_playmaterials_yn,
    CAST("fci_var_playmaterials_yn_FA" AS DOUBLE) AS fci_var_playmaterials_yn_fa,
    CAST("Mhometot" AS BIGINT) AS mhometot,
    CAST("kidi_total" AS DOUBLE) AS kidi_total,
    CAST("kidi_total_FA" AS DOUBLE) AS kidi_total_fa,
    CAST("tot_rp_t" AS BIGINT) AS tot_rp_t,
    CAST("tot_co_t" AS BIGINT) AS tot_co_t,
    CAST("tot_mf_t" AS BIGINT) AS tot_mf_t,
    CAST("tot_si_t" AS BIGINT) AS tot_si_t,
    CAST("tot_mg_t" AS BIGINT) AS tot_mg_t,
    CAST("bl_tot_rp_t" AS BIGINT) AS bl_tot_rp_t,
    CAST("bl_tot_co_t" AS BIGINT) AS bl_tot_co_t,
    CAST("bl_tot_mf_t" AS BIGINT) AS bl_tot_mf_t,
    CAST("bl_tot_si_t" AS BIGINT) AS bl_tot_si_t,
    CAST("bl_tot_mg_t" AS BIGINT) AS bl_tot_mg_t,
    CAST("b_pb_cog" AS BIGINT) AS b_pb_cog,
    CAST("b_pb_lr" AS BIGINT) AS b_pb_lr,
    CAST("b_pb_le" AS BIGINT) AS b_pb_le,
    CAST("b_pb_mf" AS BIGINT) AS b_pb_mf,
    CAST("asq_tot_av5scales_kd" AS DOUBLE) AS asq_tot_av5scales_kd,
    CAST("bl_asq_tot_av5scales_kd" AS DOUBLE) AS bl_asq_tot_av5scales_kd,
    CAST("asq_tot_av3scales_kd" AS DOUBLE) AS asq_tot_av3scales_kd,
    CAST("asq_tot_av2scales_kd" AS DOUBLE) AS asq_tot_av2scales_kd,
    CAST("b_st_av4_kd" AS DOUBLE) AS b_st_av4_kd,
    CAST("b_st_avw4_kd" AS DOUBLE) AS b_st_avw4_kd,
    CAST("b_st_avw3_kd" AS DOUBLE) AS b_st_avw3_kd,
    CAST("total_8" AS DOUBLE) AS total_8,
    CAST("total_9" AS DOUBLE) AS total_9,
    CAST("total_10" AS DOUBLE) AS total_10,
    CAST("meanMINUSi_total_8" AS DOUBLE) AS meanminusi_total_8,
    CAST("meanMINUSi_total_9" AS DOUBLE) AS meanminusi_total_9,
    CAST("meanMINUSi_total_10" AS DOUBLE) AS meanminusi_total_10,
    CAST("total_8_r" AS DOUBLE) AS total_8_r,
    CAST("total_9_r" AS DOUBLE) AS total_9_r,
    CAST("total_10_r" AS DOUBLE) AS total_10_r,
    CAST("r_subscale8" AS DOUBLE) AS r_subscale8,
    CAST("r_subscale9" AS DOUBLE) AS r_subscale9,
    CAST("r_subscale10" AS DOUBLE) AS r_subscale10,
    CAST("CODFAC" AS BIGINT) AS codfac,
    CAST("f_edad_anios" AS BIGINT) AS f_edad_anios,
    CAST("f_educ_yrs" AS BIGINT) AS f_educ_yrs,
    CAST("Q7_dur_meses" AS BIGINT) AS q7_dur_meses,
    CAST("Q9_dur" AS BIGINT) AS q9_dur,
    CAST("f_cap_fammes" AS BIGINT) AS f_cap_fammes,
    CAST("f_cap_vismes" AS BIGINT) AS f_cap_vismes,
    CAST("f_exp_ocup_cuna" AS BIGINT) AS f_exp_ocup_cuna,
    CAST("f_exp_cuna_normh" AS BIGINT) AS f_exp_cuna_normh,
    CAST("f_exp_nin3_tiene" AS BIGINT) AS f_exp_nin3_tiene,
    CAST("f_exp_nin_anos" AS DOUBLE) AS f_exp_nin_anos,
    CAST("f_exp_fam_tiene" AS BIGINT) AS f_exp_fam_tiene,
    CAST("f_exp_fam_anos" AS DOUBLE) AS f_exp_fam_anos,
    CAST("f_cap_3anos" AS BIGINT) AS f_cap_3anos,
    "f_cap_cuidado",
    "f_cap_higiene",
    "f_cap_salud",
    "f_cap_alimen",
    "f_cap_desarrollo",
    "f_cap_aprendi",
    CAST("f_cap_recibe" AS BIGINT) AS f_cap_recibe,
    CAST("f_cap_numrecibido" AS BIGINT) AS f_cap_numrecibido,
    CAST("f_cap_vis_at" AS BIGINT) AS f_cap_vis_at,
    CAST("f_cap_at_qui" AS BIGINT) AS f_cap_at_qui,
    CAST("f_cap_at_men" AS BIGINT) AS f_cap_at_men,
    CAST("f_cap_at_bimen" AS BIGINT) AS f_cap_at_bimen,
    CAST("f_estipendo_men" AS BIGINT) AS f_estipendo_men,
    CAST("f_estipendo_bimes" AS BIGINT) AS f_estipendo_bimes,
    CAST("f_estipendo_tri" AS BIGINT) AS f_estipendo_tri,
    CAST("f_kidi_total_2" AS DOUBLE) AS f_kidi_total_2,
    CAST("ubigeo_ccpp" AS BIGINT) AS ubigeo_ccpp,
    CAST("au_tran_min1_h" AS DOUBLE) AS au_tran_min1_h,
    CAST("au_tran_min5_h" AS DOUBLE) AS au_tran_min5_h,
    CAST("au_sal_centp" AS BIGINT) AS au_sal_centp,
    "au_inst_c4p1_3",
    CAST("au_com_ban" AS BIGINT) AS au_com_ban,
    "au_social_c5p1a_3",
    CAST("ubigeo" AS BIGINT) AS ubigeo,
    CAST("m_M500_C_z" AS DOUBLE) AS m_m500_c_z,
    CAST("mean_m_M500_C_z" AS DOUBLE) AS mean_m_m500_c_z,
    CAST("m_M500_M_z" AS DOUBLE) AS m_m500_m_z,
    CAST("mean_m_M500_M_z" AS DOUBLE) AS mean_m_m500_m_z,
    CAST("m_agua_vivienda" AS DOUBLE) AS m_agua_vivienda,
    CAST("m_servicio_h" AS DOUBLE) AS m_servicio_h,
    CAST("m_piso_no_tierra" AS DOUBLE) AS m_piso_no_tierra,
    CAST("m_cuartos" AS DOUBLE) AS m_cuartos,
    CAST("m_assets" AS DOUBLE) AS m_assets,
    CAST("trio_l" AS BIGINT) AS trio_l,
    "source_resource"
FROM "idb-data-associated-with-quality-of-parenting-programs-and-child-development-ou"
