-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "countryname",
    "ifs",
    "year",
    "system",
    CAST("yrsoffc" AS DOUBLE) AS yrsoffc,
    CAST("finittrm" AS DOUBLE) AS finittrm,
    CAST("yrcurnt" AS DOUBLE) AS yrcurnt,
    CAST("multpl" AS DOUBLE) AS multpl,
    CAST("military" AS DOUBLE) AS military,
    CAST("defmin" AS DOUBLE) AS defmin,
    "percent1",
    CAST("percentl" AS DOUBLE) AS percentl,
    CAST("prtyin" AS DOUBLE) AS prtyin,
    "execme",
    "execrlc",
    CAST("execnat" AS DOUBLE) AS execnat,
    CAST("execrurl" AS DOUBLE) AS execrurl,
    CAST("execreg" AS DOUBLE) AS execreg,
    "execrel",
    CAST("execage" AS DOUBLE) AS execage,
    CAST("allhouse" AS DOUBLE) AS allhouse,
    "nonchief",
    "gov1me",
    CAST("gov1seat" AS DOUBLE) AS gov1seat,
    CAST("gov1vote" AS DOUBLE) AS gov1vote,
    "gov1rlc",
    CAST("gov1nat" AS DOUBLE) AS gov1nat,
    CAST("gov1rurl" AS DOUBLE) AS gov1rurl,
    CAST("gov1reg" AS DOUBLE) AS gov1reg,
    "gov1rel",
    CAST("gov1age" AS DOUBLE) AS gov1age,
    "gov2me",
    CAST("gov2seat" AS DOUBLE) AS gov2seat,
    CAST("gov2vote" AS DOUBLE) AS gov2vote,
    "gov2rlc",
    CAST("gov2nat" AS DOUBLE) AS gov2nat,
    CAST("gov2rurl" AS DOUBLE) AS gov2rurl,
    CAST("gov2reg" AS DOUBLE) AS gov2reg,
    "gov2rel",
    CAST("gov2age" AS DOUBLE) AS gov2age,
    "gov3me",
    CAST("gov3seat" AS DOUBLE) AS gov3seat,
    CAST("gov3vote" AS DOUBLE) AS gov3vote,
    "gov3rlc",
    CAST("gov3nat" AS DOUBLE) AS gov3nat,
    CAST("gov3rurl" AS DOUBLE) AS gov3rurl,
    CAST("gov3reg" AS DOUBLE) AS gov3reg,
    "gov3rel",
    CAST("gov3age" AS DOUBLE) AS gov3age,
    CAST("govoth" AS DOUBLE) AS govoth,
    CAST("govothst" AS DOUBLE) AS govothst,
    CAST("govothvt" AS DOUBLE) AS govothvt,
    "opp1me",
    CAST("opp1seat" AS DOUBLE) AS opp1seat,
    CAST("opp1vote" AS DOUBLE) AS opp1vote,
    "opp1rlc",
    CAST("opp1nat" AS DOUBLE) AS opp1nat,
    CAST("opp1rurl" AS DOUBLE) AS opp1rurl,
    CAST("opp1reg" AS DOUBLE) AS opp1reg,
    "opp1rel",
    CAST("opp1age" AS DOUBLE) AS opp1age,
    "opp2me",
    CAST("opp2seat" AS DOUBLE) AS opp2seat,
    CAST("opp2vote" AS DOUBLE) AS opp2vote,
    "opp3me",
    CAST("opp3seat" AS DOUBLE) AS opp3seat,
    CAST("opp3vote" AS DOUBLE) AS opp3vote,
    CAST("oppoth" AS DOUBLE) AS oppoth,
    CAST("oppothst" AS DOUBLE) AS oppothst,
    CAST("oppothvt" AS DOUBLE) AS oppothvt,
    CAST("ulprty" AS DOUBLE) AS ulprty,
    CAST("numul" AS DOUBLE) AS numul,
    CAST("ulvote" AS DOUBLE) AS ulvote,
    CAST("oppmajh" AS DOUBLE) AS oppmajh,
    CAST("oppmajs" AS DOUBLE) AS oppmajs,
    CAST("dateleg" AS DOUBLE) AS dateleg,
    CAST("dateexec" AS DOUBLE) AS dateexec,
    CAST("legelec" AS DOUBLE) AS legelec,
    CAST("exelec" AS DOUBLE) AS exelec,
    CAST("liec" AS DOUBLE) AS liec,
    CAST("eiec" AS DOUBLE) AS eiec,
    CAST("mdmh" AS DOUBLE) AS mdmh,
    CAST("mdms" AS DOUBLE) AS mdms,
    CAST("ssh" AS DOUBLE) AS ssh,
    CAST("pluralty" AS DOUBLE) AS pluralty,
    CAST("pr" AS DOUBLE) AS pr,
    "housesys",
    "sensys",
    CAST("thresh" AS DOUBLE) AS thresh,
    CAST("dhondt" AS DOUBLE) AS dhondt,
    CAST("cl" AS DOUBLE) AS cl,
    "select",
    CAST("fraud" AS DOUBLE) AS fraud,
    CAST("auton" AS DOUBLE) AS auton,
    "muni",
    "state",
    CAST("author" AS DOUBLE) AS author,
    CAST("stconst" AS DOUBLE) AS stconst,
    CAST("gwno" AS DOUBLE) AS gwno,
    CAST("termlimit" AS DOUBLE) AS termlimit,
    CAST("numgov" AS BIGINT) AS numgov,
    CAST("numvote" AS DOUBLE) AS numvote,
    CAST("numopp" AS BIGINT) AS numopp,
    CAST("oppvote" AS DOUBLE) AS oppvote,
    "maj",
    "partyage",
    "herfgov",
    "herfopp",
    "herftot",
    "frac",
    "oppfrac",
    "govfrac",
    "tensys_strict",
    "tensys",
    CAST("checks_lax" AS DOUBLE) AS checks_lax,
    "checks",
    "stabs_strict",
    "stabs",
    "stabns_strict",
    "stabns",
    "tenlong_strict",
    "tenlong",
    "tenshort_strict",
    "tenshort",
    "polariz",
    CAST("numul2" AS DOUBLE) AS numul2,
    CAST("totalseats" AS BIGINT) AS totalseats,
    "source_resource"
FROM "idb-the-database-of-political-institutions-dpi-2023"
