-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "PAIS_TIP" AS pais_tip,
    "DEP" AS dep,
    "MUN" AS mun,
    CAST("NHOGAR" AS BIGINT) AS nhogar,
    CAST("ID_HH" AS BIGINT) AS id_hh,
    CAST("MEMBERNUM_HH" AS BIGINT) AS membernum_hh,
    CAST("DATE_1ST_HH" AS BIGINT) AS date_1st_hh,
    "DATE_1ST_STR_HH" AS date_1st_str_hh,
    CAST("DATE_2ND_HH" AS BIGINT) AS date_2nd_hh,
    "DATE_2ND_STR_HH" AS date_2nd_str_hh,
    CAST("DATE_3RD_HH" AS BIGINT) AS date_3rd_hh,
    "DATE_3RD_STR_HH" AS date_3rd_str_hh,
    CAST("DATE_FINAL_HH" AS BIGINT) AS date_final_hh,
    "DATE_FINAL_STR_HH" AS date_final_str_hh,
    CAST("VISITNUM_HH" AS BIGINT) AS visitnum_hh,
    CAST("INT_DUR_HH" AS BIGINT) AS int_dur_hh,
    "RESULT_V1_HH" AS result_v1_hh,
    "RESULT_V2_HH" AS result_v2_hh,
    "RESULT_V3_HH" AS result_v3_hh,
    "RESULT_HH" AS result_hh,
    "REPLACEMENT_HH" AS replacement_hh,
    CAST("ID_REPLACED_HH" AS BIGINT) AS id_replaced_hh,
    CAST("ID_INTERVIEWER_HH" AS BIGINT) AS id_interviewer_hh,
    CAST("ID_SUPERVISOR_HH" AS BIGINT) AS id_supervisor_hh,
    CAST("DATE_SUP_HH" AS BIGINT) AS date_sup_hh,
    "DATE_SUP_STR_HH" AS date_sup_str_hh,
    CAST("ID_DATAENTRY_HH" AS BIGINT) AS id_dataentry_hh,
    CAST("DATE_ENTRY_HH" AS BIGINT) AS date_entry_hh,
    "DATE_ENTRY_STR_HH" AS date_entry_str_hh,
    CAST("C_INI_HO" AS BIGINT) AS c_ini_ho,
    CAST("C_INI_MI" AS BIGINT) AS c_ini_mi,
    CAST("C_FIN_HO" AS BIGINT) AS c_fin_ho,
    CAST("C_FIN_MI" AS BIGINT) AS c_fin_mi,
    CAST("HH_AGE_MON_01" AS BIGINT) AS hh_age_mon_01,
    "HH_SEX_01" AS hh_sex_01,
    "HH_RELATION_01" AS hh_relation_01,
    "HH_MARITAL_01" AS hh_marital_01,
    "ID_ROSTER_MOM_01" AS id_roster_mom_01,
    "ID_ROSTER_DAD_01" AS id_roster_dad_01,
    "C_COMMENT1_MOD1_01" AS c_comment1_mod1_01,
    "C_COMMENT2_MOD1_01" AS c_comment2_mod1_01,
    "C_COMMENT3_MOD1_01" AS c_comment3_mod1_01,
    CAST("HH_AGE_MON_02" AS BIGINT) AS hh_age_mon_02,
    "HH_SEX_02" AS hh_sex_02,
    "HH_RELATION_02" AS hh_relation_02,
    "HH_MARITAL_02" AS hh_marital_02,
    "ID_ROSTER_MOM_02" AS id_roster_mom_02,
    "ID_ROSTER_DAD_02" AS id_roster_dad_02,
    "C_COMMENT1_MOD1_02" AS c_comment1_mod1_02,
    "C_COMMENT2_MOD1_02" AS c_comment2_mod1_02,
    "C_COMMENT3_MOD1_02" AS c_comment3_mod1_02,
    CAST("HH_AGE_MON_03" AS BIGINT) AS hh_age_mon_03,
    "HH_SEX_03" AS hh_sex_03,
    "HH_RELATION_03" AS hh_relation_03,
    "HH_MARITAL_03" AS hh_marital_03,
    "ID_ROSTER_MOM_03" AS id_roster_mom_03,
    "ID_ROSTER_DAD_03" AS id_roster_dad_03,
    "C_COMMENT1_MOD1_03" AS c_comment1_mod1_03,
    "C_COMMENT2_MOD1_03" AS c_comment2_mod1_03,
    "C_COMMENT3_MOD1_03" AS c_comment3_mod1_03,
    CAST("HH_AGE_MON_04" AS BIGINT) AS hh_age_mon_04,
    "HH_SEX_04" AS hh_sex_04,
    "HH_RELATION_04" AS hh_relation_04,
    "HH_MARITAL_04" AS hh_marital_04,
    "ID_ROSTER_MOM_04" AS id_roster_mom_04,
    "ID_ROSTER_DAD_04" AS id_roster_dad_04,
    "C_COMMENT1_MOD1_04" AS c_comment1_mod1_04,
    "C_COMMENT2_MOD1_04" AS c_comment2_mod1_04,
    "C_COMMENT3_MOD1_04" AS c_comment3_mod1_04,
    CAST("HH_AGE_MON_05" AS BIGINT) AS hh_age_mon_05,
    "HH_SEX_05" AS hh_sex_05,
    "HH_RELATION_05" AS hh_relation_05,
    "HH_MARITAL_05" AS hh_marital_05,
    "ID_ROSTER_MOM_05" AS id_roster_mom_05,
    "ID_ROSTER_DAD_05" AS id_roster_dad_05,
    "C_COMMENT1_MOD1_05" AS c_comment1_mod1_05,
    "C_COMMENT2_MOD1_05" AS c_comment2_mod1_05,
    "C_COMMENT3_MOD1_05" AS c_comment3_mod1_05,
    CAST("HH_AGE_MON_06" AS BIGINT) AS hh_age_mon_06,
    "HH_SEX_06" AS hh_sex_06,
    "HH_RELATION_06" AS hh_relation_06,
    "HH_MARITAL_06" AS hh_marital_06,
    "ID_ROSTER_MOM_06" AS id_roster_mom_06,
    "ID_ROSTER_DAD_06" AS id_roster_dad_06,
    "C_COMMENT1_MOD1_06" AS c_comment1_mod1_06,
    "C_COMMENT2_MOD1_06" AS c_comment2_mod1_06,
    "C_COMMENT3_MOD1_06" AS c_comment3_mod1_06,
    CAST("HH_AGE_MON_07" AS BIGINT) AS hh_age_mon_07,
    "HH_SEX_07" AS hh_sex_07,
    "HH_RELATION_07" AS hh_relation_07,
    "HH_MARITAL_07" AS hh_marital_07,
    "ID_ROSTER_MOM_07" AS id_roster_mom_07,
    "ID_ROSTER_DAD_07" AS id_roster_dad_07,
    "C_COMMENT1_MOD1_07" AS c_comment1_mod1_07,
    "C_COMMENT2_MOD1_07" AS c_comment2_mod1_07,
    "C_COMMENT3_MOD1_07" AS c_comment3_mod1_07,
    CAST("HH_AGE_MON_08" AS BIGINT) AS hh_age_mon_08,
    "HH_SEX_08" AS hh_sex_08,
    "HH_RELATION_08" AS hh_relation_08,
    "HH_MARITAL_08" AS hh_marital_08,
    "ID_ROSTER_MOM_08" AS id_roster_mom_08,
    "ID_ROSTER_DAD_08" AS id_roster_dad_08,
    "C_COMMENT1_MOD1_08" AS c_comment1_mod1_08,
    "C_COMMENT2_MOD1_08" AS c_comment2_mod1_08,
    "C_COMMENT3_MOD1_08" AS c_comment3_mod1_08,
    CAST("HH_AGE_MON_09" AS BIGINT) AS hh_age_mon_09,
    "HH_SEX_09" AS hh_sex_09,
    "HH_RELATION_09" AS hh_relation_09,
    "HH_MARITAL_09" AS hh_marital_09,
    "ID_ROSTER_MOM_09" AS id_roster_mom_09,
    "ID_ROSTER_DAD_09" AS id_roster_dad_09,
    "C_COMMENT1_MOD1_09" AS c_comment1_mod1_09,
    "C_COMMENT2_MOD1_09" AS c_comment2_mod1_09,
    "C_COMMENT3_MOD1_09" AS c_comment3_mod1_09,
    CAST("HH_AGE_MON_10" AS BIGINT) AS hh_age_mon_10,
    "HH_SEX_10" AS hh_sex_10,
    "HH_RELATION_10" AS hh_relation_10,
    "HH_MARITAL_10" AS hh_marital_10,
    "ID_ROSTER_MOM_10" AS id_roster_mom_10,
    "ID_ROSTER_DAD_10" AS id_roster_dad_10,
    "C_COMMENT1_MOD1_10" AS c_comment1_mod1_10,
    "C_COMMENT2_MOD1_10" AS c_comment2_mod1_10,
    "C_COMMENT3_MOD1_10" AS c_comment3_mod1_10,
    CAST("HH_AGE_MON_11" AS BIGINT) AS hh_age_mon_11,
    "HH_SEX_11" AS hh_sex_11,
    "HH_RELATION_11" AS hh_relation_11,
    "HH_MARITAL_11" AS hh_marital_11,
    "ID_ROSTER_MOM_11" AS id_roster_mom_11,
    "ID_ROSTER_DAD_11" AS id_roster_dad_11,
    "C_COMMENT1_MOD1_11" AS c_comment1_mod1_11,
    "C_COMMENT2_MOD1_11" AS c_comment2_mod1_11,
    "C_COMMENT3_MOD1_11" AS c_comment3_mod1_11,
    CAST("HH_AGE_MON_12" AS BIGINT) AS hh_age_mon_12,
    "HH_SEX_12" AS hh_sex_12,
    "HH_RELATION_12" AS hh_relation_12,
    "HH_MARITAL_12" AS hh_marital_12,
    "ID_ROSTER_MOM_12" AS id_roster_mom_12,
    "ID_ROSTER_DAD_12" AS id_roster_dad_12,
    "C_COMMENT1_MOD1_12" AS c_comment1_mod1_12,
    "C_COMMENT2_MOD1_12" AS c_comment2_mod1_12,
    "C_COMMENT3_MOD1_12" AS c_comment3_mod1_12,
    CAST("HH_AGE_MON_13" AS BIGINT) AS hh_age_mon_13,
    "HH_SEX_13" AS hh_sex_13,
    "HH_RELATION_13" AS hh_relation_13,
    "HH_MARITAL_13" AS hh_marital_13,
    "ID_ROSTER_MOM_13" AS id_roster_mom_13,
    "ID_ROSTER_DAD_13" AS id_roster_dad_13,
    "C_COMMENT1_MOD1_13" AS c_comment1_mod1_13,
    "C_COMMENT2_MOD1_13" AS c_comment2_mod1_13,
    "C_COMMENT3_MOD1_13" AS c_comment3_mod1_13,
    CAST("HH_AGE_MON_14" AS BIGINT) AS hh_age_mon_14,
    "HH_SEX_14" AS hh_sex_14,
    "HH_RELATION_14" AS hh_relation_14,
    "HH_MARITAL_14" AS hh_marital_14,
    "ID_ROSTER_MOM_14" AS id_roster_mom_14,
    "ID_ROSTER_DAD_14" AS id_roster_dad_14,
    "C_COMMENT1_MOD1_14" AS c_comment1_mod1_14,
    "C_COMMENT2_MOD1_14" AS c_comment2_mod1_14,
    "C_COMMENT3_MOD1_14" AS c_comment3_mod1_14,
    CAST("HH_AGE_MON_15" AS BIGINT) AS hh_age_mon_15,
    "HH_SEX_15" AS hh_sex_15,
    "HH_RELATION_15" AS hh_relation_15,
    "HH_MARITAL_15" AS hh_marital_15,
    "ID_ROSTER_MOM_15" AS id_roster_mom_15,
    "ID_ROSTER_DAD_15" AS id_roster_dad_15,
    "C_COMMENT1_MOD1_15" AS c_comment1_mod1_15,
    "C_COMMENT2_MOD1_15" AS c_comment2_mod1_15,
    "C_COMMENT3_MOD1_15" AS c_comment3_mod1_15,
    CAST("HH_AGE_MON_16" AS BIGINT) AS hh_age_mon_16,
    "HH_SEX_16" AS hh_sex_16,
    "HH_RELATION_16" AS hh_relation_16,
    "HH_MARITAL_16" AS hh_marital_16,
    "ID_ROSTER_MOM_16" AS id_roster_mom_16,
    "ID_ROSTER_DAD_16" AS id_roster_dad_16,
    "C_COMMENT1_MOD1_16" AS c_comment1_mod1_16,
    "C_COMMENT2_MOD1_16" AS c_comment2_mod1_16,
    "C_COMMENT3_MOD1_16" AS c_comment3_mod1_16,
    CAST("HH_AGE_MON_17" AS BIGINT) AS hh_age_mon_17,
    "HH_SEX_17" AS hh_sex_17,
    "HH_RELATION_17" AS hh_relation_17,
    "HH_MARITAL_17" AS hh_marital_17,
    "ID_ROSTER_MOM_17" AS id_roster_mom_17,
    "ID_ROSTER_DAD_17" AS id_roster_dad_17,
    "C_COMMENT1_MOD1_17" AS c_comment1_mod1_17,
    "C_COMMENT2_MOD1_17" AS c_comment2_mod1_17,
    "C_COMMENT3_MOD1_17" AS c_comment3_mod1_17,
    CAST("HH_AGE_MON_18" AS BIGINT) AS hh_age_mon_18,
    "HH_SEX_18" AS hh_sex_18,
    "HH_RELATION_18" AS hh_relation_18,
    "HH_MARITAL_18" AS hh_marital_18,
    "ID_ROSTER_MOM_18" AS id_roster_mom_18,
    "ID_ROSTER_DAD_18" AS id_roster_dad_18,
    "C_COMMENT1_MOD1_18" AS c_comment1_mod1_18,
    "C_COMMENT2_MOD1_18" AS c_comment2_mod1_18,
    "C_COMMENT3_MOD1_18" AS c_comment3_mod1_18,
    CAST("MEMBERNUM_HH_IHME" AS BIGINT) AS membernum_hh_ihme,
    "HH_SMOKE" AS hh_smoke,
    "HH_WATER" AS hh_water,
    "HH_WATER_LOC" AS hh_water_loc,
    CAST("HH_WATER_TIME" AS BIGINT) AS hh_water_time,
    "HH_WATER_MOD" AS hh_water_mod,
    "HH_WATER_SAFE" AS hh_water_safe,
    "HH_TOILET_TYPE" AS hh_toilet_type,
    "HH_TOILET_SHARE" AS hh_toilet_share,
    CAST("HH_TOILET_SHARENUM" AS BIGINT) AS hh_toilet_sharenum,
    "HH_FUEL" AS hh_fuel,
    "HH_COOK_LOC" AS hh_cook_loc,
    "HH_KITCHEN" AS hh_kitchen,
    CAST("HH_BEDROOMS" AS BIGINT) AS hh_bedrooms,
    "HH_ELEC" AS hh_elec,
    "HH_RADIO" AS hh_radio,
    "HH_TV" AS hh_tv,
    "HH_TEL_MOBILE" AS hh_tel_mobile,
    "HH_TEL_FIXED" AS hh_tel_fixed,
    "HH_REFRIG" AS hh_refrig,
    "HH_WATCH" AS hh_watch,
    "HH_BIKE" AS hh_bike,
    "HH_SCOOTER" AS hh_scooter,
    "HH_ANIMALCART" AS hh_animalcart,
    "HH_CAR" AS hh_car,
    "HH_TRUCK" AS hh_truck,
    "HH_AGLAND" AS hh_agland,
    CAST("HH_AGLAND_AREA" AS DOUBLE) AS hh_agland_area,
    "HH_AGANIMALS" AS hh_aganimals,
    "HH_BANKACCT" AS hh_bankacct,
    CAST("HH_EXP_TOT" AS BIGINT) AS hh_exp_tot,
    "HH_EXP_FOOD_ANY" AS hh_exp_food_any,
    CAST("HH_EXP_FOOD_AMT" AS BIGINT) AS hh_exp_food_amt,
    "HH_EXP_IU_ANY" AS hh_exp_iu_any,
    CAST("HH_EXP_IU_AMT" AS BIGINT) AS hh_exp_iu_amt,
    "HH_EXP_EDU_ANY" AS hh_exp_edu_any,
    CAST("HH_EXP_EDU_AMT" AS BIGINT) AS hh_exp_edu_amt,
    "HH_EXP_HC_OOP_ANY" AS hh_exp_hc_oop_any,
    CAST("HH_EXP_HC_OOP_AMT" AS BIGINT) AS hh_exp_hc_oop_amt,
    "HH_EXP_HC_SOC_ANY" AS hh_exp_hc_soc_any,
    CAST("HH_EXP_HC_SOC_AMT" AS BIGINT) AS hh_exp_hc_soc_amt,
    "HH_EXP_HC_PRIV_ANY" AS hh_exp_hc_priv_any,
    CAST("HH_EXP_HC_PRIV_AMT" AS BIGINT) AS hh_exp_hc_priv_amt,
    "HH_EXP_HC_ACCESS_ANY" AS hh_exp_hc_access_any,
    CAST("HH_EXP_HC_ACCESS_AMT" AS BIGINT) AS hh_exp_hc_access_amt,
    "HH_EXP_OTH_ANY" AS hh_exp_oth_any,
    CAST("HH_EXP_OTH_AMT" AS BIGINT) AS hh_exp_oth_amt,
    "HH_EXP_HC_IPC_ANY" AS hh_exp_hc_ipc_any,
    CAST("HH_EXP_HC_IPC_AMT" AS BIGINT) AS hh_exp_hc_ipc_amt,
    "HH_EXP_HC_IPC_OTH_ANY" AS hh_exp_hc_ipc_oth_any,
    CAST("HH_EXP_HC_IPC_OTH_AMT" AS BIGINT) AS hh_exp_hc_ipc_oth_amt,
    "HH_EXP_HC_OPC_ANY" AS hh_exp_hc_opc_any,
    CAST("HH_EXP_HC_OPC_AMT" AS BIGINT) AS hh_exp_hc_opc_amt,
    "HH_EXP_HC_TRAD_ANY" AS hh_exp_hc_trad_any,
    CAST("HH_EXP_HC_TRAD_AMT" AS BIGINT) AS hh_exp_hc_trad_amt,
    "HH_EXP_HC_DENT_ANY" AS hh_exp_hc_dent_any,
    CAST("HH_EXP_HC_DENT_AMT" AS BIGINT) AS hh_exp_hc_dent_amt,
    "HH_EXP_HC_PHARM_ANY" AS hh_exp_hc_pharm_any,
    CAST("HH_EXP_HC_PHARM_AMT" AS BIGINT) AS hh_exp_hc_pharm_amt,
    "HH_EXP_HC_AIDS_ANY" AS hh_exp_hc_aids_any,
    CAST("HH_EXP_HC_AIDS_AMT" AS BIGINT) AS hh_exp_hc_aids_amt,
    "HH_EXP_HC_TESTS_ANY" AS hh_exp_hc_tests_any,
    CAST("HH_EXP_HC_TESTS_AMT" AS BIGINT) AS hh_exp_hc_tests_amt,
    "HH_EXP_HC_OTH_ANY" AS hh_exp_hc_oth_any,
    CAST("HH_EXP_HC_OTH_AMT" AS BIGINT) AS hh_exp_hc_oth_amt,
    CAST("HH_HC_STAYNUM" AS BIGINT) AS hh_hc_staynum,
    CAST("HH_EXP_HC_IPCYR" AS BIGINT) AS hh_exp_hc_ipcyr,
    "HH_FIN_HC_INCOME_ANY" AS hh_fin_hc_income_any,
    CAST("HH_FIN_HC_INCOME_AMT" AS BIGINT) AS hh_fin_hc_income_amt,
    "HH_FIN_HC_SAVINGS_ANY" AS hh_fin_hc_savings_any,
    CAST("HH_FIN_HC_SAVINGS_AMT" AS BIGINT) AS hh_fin_hc_savings_amt,
    "HH_FIN_HC_INSUR_ANY" AS hh_fin_hc_insur_any,
    CAST("HH_FIN_HC_INSUR_AMT" AS BIGINT) AS hh_fin_hc_insur_amt,
    "HH_FIN_HC_ITEMS_ANY" AS hh_fin_hc_items_any,
    CAST("HH_FIN_HC_ITEMS_AMT" AS BIGINT) AS hh_fin_hc_items_amt,
    "HH_FIN_HC_PROP_ANY" AS hh_fin_hc_prop_any,
    CAST("HH_FIN_HC_PROP_AMT" AS BIGINT) AS hh_fin_hc_prop_amt,
    "HH_FIN_HC_RELATIVE_ANY" AS hh_fin_hc_relative_any,
    CAST("HH_FIN_HC_RELATIVE_AMT" AS BIGINT) AS hh_fin_hc_relative_amt,
    "HH_FIN_HC_LOAN_ANY" AS hh_fin_hc_loan_any,
    CAST("HH_FIN_HC_LOAN_AMT" AS BIGINT) AS hh_fin_hc_loan_amt,
    "HH_FIN_HC_OTH_ANY" AS hh_fin_hc_oth_any,
    CAST("HH_FIN_HC_OTH_AMT" AS BIGINT) AS hh_fin_hc_oth_amt,
    "HH_ECOS_ADDRESS" AS hh_ecos_address,
    CAST("HH_ECOS_TIME_MIN" AS BIGINT) AS hh_ecos_time_min,
    "ECOS_TIMECAT" AS ecos_timecat,
    "wtSEG" AS wtseg,
    CAST("codigo" AS BIGINT) AS codigo,
    CAST("p_selection_hh" AS DOUBLE) AS p_selection_hh,
    CAST("weight_hh" AS DOUBLE) AS weight_hh,
    CAST("p_selection_hhx" AS DOUBLE) AS p_selection_hhx,
    CAST("weight_hhx" AS DOUBLE) AS weight_hhx,
    CAST("seg2" AS BIGINT) AS seg2,
    "source_resource"
FROM "idb-baseline-salud-mesoamerica-el-salvador-household-survey-2015"
