-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("year" AS BIGINT) AS year,
    CAST("per" AS BIGINT) AS per,
    "loc",
    "mun",
    "ent",
    "upm",
    "n_pro_viv",
    CAST("n_hog" AS BIGINT) AS n_hog,
    "HH_ID" AS hh_id,
    "ID" AS id,
    CAST("n_ent" AS BIGINT) AS n_ent,
    CAST("n_ren" AS BIGINT) AS n_ren,
    CAST("year_period" AS BIGINT) AS year_period,
    CAST("yq_c" AS BIGINT) AS yq_c,
    "mun_full",
    CAST("loc_group" AS BIGINT) AS loc_group,
    CAST("sex" AS DOUBLE) AS sex,
    CAST("eda" AS DOUBLE) AS eda,
    "n_hij",
    CAST("anios_esc" AS BIGINT) AS anios_esc,
    CAST("mom" AS BIGINT) AS mom,
    CAST("dad" AS BIGINT) AS dad,
    CAST("gk" AS BIGINT) AS gk,
    CAST("woman" AS BIGINT) AS woman,
    CAST("man" AS BIGINT) AS man,
    CAST("gm" AS BIGINT) AS gm,
    CAST("gd" AS BIGINT) AS gd,
    CAST("gm_m_side" AS DOUBLE) AS gm_m_side,
    CAST("gk_m_u6" AS BIGINT) AS gk_m_u6,
    CAST("max_eda" AS BIGINT) AS max_eda,
    CAST("max_eda_gk" AS BIGINT) AS max_eda_gk,
    CAST("max_eda_gm" AS DOUBLE) AS max_eda_gm,
    CAST("max_eda_gd" AS DOUBLE) AS max_eda_gd,
    CAST("max_eda_gk_3" AS BIGINT) AS max_eda_gk_3,
    CAST("y_le_5" AS BIGINT) AS y_le_5,
    CAST("o_le_5" AS BIGINT) AS o_le_5,
    CAST("gm_le60" AS BIGINT) AS gm_le60,
    CAST("gm_le70" AS BIGINT) AS gm_le70,
    "t_loc",
    CAST("t_gm_max" AS BIGINT) AS t_gm_max,
    CAST("t_gd_max" AS BIGINT) AS t_gd_max,
    CAST("t_mom_max" AS BIGINT) AS t_mom_max,
    CAST("t_gk" AS BIGINT) AS t_gk,
    CAST("t_gk_max" AS BIGINT) AS t_gk_max,
    CAST("t_dad_max" AS BIGINT) AS t_dad_max,
    CAST("t_ind_max" AS BIGINT) AS t_ind_max,
    CAST("t_gm_died" AS BIGINT) AS t_gm_died,
    CAST("t_gd_died" AS BIGINT) AS t_gd_died,
    CAST("t_sec_gen_max" AS BIGINT) AS t_sec_gen_max,
    CAST("t_gk_p1" AS BIGINT) AS t_gk_p1,
    CAST("t_gk_m_p1" AS BIGINT) AS t_gk_m_p1,
    CAST("t_gk_u6_p1" AS BIGINT) AS t_gk_u6_p1,
    CAST("employed" AS BIGINT) AS employed,
    CAST("part_time" AS BIGINT) AS part_time,
    CAST("part_time_t2" AS BIGINT) AS part_time_t2,
    CAST("part_time_t2_p1" AS BIGINT) AS part_time_t2_p1,
    CAST("middle_time" AS BIGINT) AS middle_time,
    CAST("full_time" AS BIGINT) AS full_time,
    CAST("full_time_p1" AS BIGINT) AS full_time_p1,
    CAST("hrsocup" AS DOUBLE) AS hrsocup,
    CAST("ingocup" AS DOUBLE) AS ingocup,
    CAST("ing_x_hrs" AS DOUBLE) AS ing_x_hrs,
    "emp_ppal",
    CAST("any_work" AS BIGINT) AS any_work,
    CAST("any_paidwork" AS BIGINT) AS any_paidwork,
    CAST("edu_max" AS DOUBLE) AS edu_max,
    CAST("eda_cat5" AS BIGINT) AS eda_cat5,
    CAST("inc_f_cat10" AS BIGINT) AS inc_f_cat10,
    CAST("hrsocup_p1" AS DOUBLE) AS hrsocup_p1,
    CAST("ingocup_p1" AS DOUBLE) AS ingocup_p1,
    CAST("n_hij_p1" AS BIGINT) AS n_hij_p1,
    CAST("f_emp_p1" AS BIGINT) AS f_emp_p1,
    CAST("n_624411_p0a5_20" AS DOUBLE) AS n_624411_p0a5_20,
    CAST("n_624412_p0a5_20" AS DOUBLE) AS n_624412_p0a5_20,
    CAST("fac" AS BIGINT) AS fac,
    "merge_denue",
    "merge_mun",
    "merge_eness_format",
    "merge_loc",
    "merge_est",
    CAST("obs_hh" AS BIGINT) AS obs_hh,
    CAST("generations" AS BIGINT) AS generations,
    CAST("time_cuidar" AS DOUBLE) AS time_cuidar,
    CAST("gd_died" AS BIGINT) AS gd_died,
    CAST("gm_died" AS BIGINT) AS gm_died,
    CAST("post_gd_died" AS BIGINT) AS post_gd_died,
    CAST("post_gm_died" AS BIGINT) AS post_gm_died,
    CAST("gm_died_ob1" AS BIGINT) AS gm_died_ob1,
    CAST("gm_died_a1" AS BIGINT) AS gm_died_a1,
    CAST("gm_died_b2" AS BIGINT) AS gm_died_b2,
    CAST("gm_died_a2" AS BIGINT) AS gm_died_a2,
    CAST("gm_died_b3" AS BIGINT) AS gm_died_b3,
    CAST("gm_died_a3" AS BIGINT) AS gm_died_a3,
    CAST("gm_died_b4" AS BIGINT) AS gm_died_b4,
    CAST("gm_died_a4" AS BIGINT) AS gm_died_a4,
    CAST("gd_died_ob1" AS BIGINT) AS gd_died_ob1,
    CAST("gd_died_a1" AS BIGINT) AS gd_died_a1,
    CAST("gd_died_b2" AS BIGINT) AS gd_died_b2,
    CAST("gd_died_a2" AS BIGINT) AS gd_died_a2,
    CAST("gd_died_b3" AS BIGINT) AS gd_died_b3,
    CAST("gd_died_a3" AS BIGINT) AS gd_died_a3,
    CAST("gd_died_b4" AS BIGINT) AS gd_died_b4,
    CAST("gd_died_a4" AS BIGINT) AS gd_died_a4,
    CAST("gm_died_b4_o_le_5_mom" AS BIGINT) AS gm_died_b4_o_le_5_mom,
    CAST("gm_died_b3_o_le_5_mom" AS BIGINT) AS gm_died_b3_o_le_5_mom,
    CAST("gm_died_b2_o_le_5_mom" AS BIGINT) AS gm_died_b2_o_le_5_mom,
    CAST("gm_died_ob1_o_le_5_mom" AS BIGINT) AS gm_died_ob1_o_le_5_mom,
    CAST("gm_died_a1_o_le_5_mom" AS BIGINT) AS gm_died_a1_o_le_5_mom,
    CAST("gm_died_a2_o_le_5_mom" AS BIGINT) AS gm_died_a2_o_le_5_mom,
    CAST("gm_died_a3_o_le_5_mom" AS BIGINT) AS gm_died_a3_o_le_5_mom,
    CAST("gm_died_a4_o_le_5_mom" AS BIGINT) AS gm_died_a4_o_le_5_mom,
    CAST("gm_died_b4_o_le_5" AS BIGINT) AS gm_died_b4_o_le_5,
    CAST("gm_died_b3_o_le_5" AS BIGINT) AS gm_died_b3_o_le_5,
    CAST("gm_died_b2_o_le_5" AS BIGINT) AS gm_died_b2_o_le_5,
    CAST("gm_died_ob1_o_le_5" AS BIGINT) AS gm_died_ob1_o_le_5,
    CAST("gm_died_a1_o_le_5" AS BIGINT) AS gm_died_a1_o_le_5,
    CAST("gm_died_a2_o_le_5" AS BIGINT) AS gm_died_a2_o_le_5,
    CAST("gm_died_a3_o_le_5" AS BIGINT) AS gm_died_a3_o_le_5,
    CAST("gm_died_a4_o_le_5" AS BIGINT) AS gm_died_a4_o_le_5,
    CAST("gd_died_b4_o_le_5" AS BIGINT) AS gd_died_b4_o_le_5,
    CAST("gd_died_b3_o_le_5" AS BIGINT) AS gd_died_b3_o_le_5,
    CAST("gd_died_b2_o_le_5" AS BIGINT) AS gd_died_b2_o_le_5,
    CAST("gd_died_a1_o_le_5" AS BIGINT) AS gd_died_a1_o_le_5,
    CAST("gd_died_a2_o_le_5" AS BIGINT) AS gd_died_a2_o_le_5,
    CAST("gd_died_a3_o_le_5" AS BIGINT) AS gd_died_a3_o_le_5,
    CAST("gd_died_a4_o_le_5" AS BIGINT) AS gd_died_a4_o_le_5,
    CAST("gm_died_b4_mom" AS BIGINT) AS gm_died_b4_mom,
    CAST("gm_died_b3_mom" AS BIGINT) AS gm_died_b3_mom,
    CAST("gm_died_b2_mom" AS BIGINT) AS gm_died_b2_mom,
    CAST("gm_died_ob1_mom" AS BIGINT) AS gm_died_ob1_mom,
    CAST("gm_died_a1_mom" AS BIGINT) AS gm_died_a1_mom,
    CAST("gm_died_a2_mom" AS BIGINT) AS gm_died_a2_mom,
    CAST("gm_died_a3_mom" AS BIGINT) AS gm_died_a3_mom,
    CAST("gm_died_a4_mom" AS BIGINT) AS gm_died_a4_mom,
    CAST("post_gm_died_mom" AS BIGINT) AS post_gm_died_mom,
    CAST("post_gm_died_o_le_5" AS BIGINT) AS post_gm_died_o_le_5,
    CAST("post_gm_died_y_le_5" AS BIGINT) AS post_gm_died_y_le_5,
    CAST("post_gm_died_o_le_5_mom" AS BIGINT) AS post_gm_died_o_le_5_mom,
    CAST("post_gm_died_y_le_5_mom" AS BIGINT) AS post_gm_died_y_le_5_mom,
    CAST("sec_gen" AS BIGINT) AS sec_gen,
    CAST("miss_sex" AS BIGINT) AS miss_sex,
    CAST("pobtot_20_mun" AS BIGINT) AS pobtot_20_mun,
    CAST("pobtot_20_loc" AS DOUBLE) AS pobtot_20_loc,
    CAST("p0a5_20_loc" AS DOUBLE) AS p0a5_20_loc,
    CAST("EI_N_p0a5_20" AS DOUBLE) AS ei_n_p0a5_20,
    CAST("time_cuidar_gm_p1" AS DOUBLE) AS time_cuidar_gm_p1,
    CAST("time_cuidar_gm" AS DOUBLE) AS time_cuidar_gm,
    CAST("as_time_cuidar" AS DOUBLE) AS as_time_cuidar,
    CAST("cuida" AS BIGINT) AS cuida,
    CAST("high_more_p1" AS BIGINT) AS high_more_p1,
    CAST("coll_more_p1" AS BIGINT) AS coll_more_p1,
    CAST("d_gk_m_p1" AS BIGINT) AS d_gk_m_p1,
    CAST("employed_p1" AS BIGINT) AS employed_p1,
    CAST("Z_pago_hora_pr" AS DOUBLE) AS z_pago_hora_pr,
    CAST("Z_pago_hora_pu" AS DOUBLE) AS z_pago_hora_pu,
    CAST("Z_pago_pr" AS DOUBLE) AS z_pago_pr,
    CAST("Z_pago_pu" AS DOUBLE) AS z_pago_pu,
    CAST("Z_pago_hora_es" AS DOUBLE) AS z_pago_hora_es,
    CAST("Z_pago_es" AS DOUBLE) AS z_pago_es,
    CAST("Z_pago_hora_con_es" AS DOUBLE) AS z_pago_hora_con_es,
    CAST("Z_pago_con_es" AS DOUBLE) AS z_pago_con_es,
    "source_resource"
FROM "idb-replication-data-for-grandmothers-and-the-gender-gap-in-the-mexican-labor-m"
