-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("hhid" AS BIGINT) AS hhid,
    CAST("member__id" AS BIGINT) AS member_id,
    CAST("w_ind_r2" AS DOUBLE) AS w_ind_r2,
    CAST("psu" AS BIGINT) AS psu,
    CAST("stratum" AS BIGINT) AS stratum,
    "pl_memid",
    "curmem",
    "rsnlft",
    "dobcmb",
    "sex",
    "memage",
    "agemar",
    "agejan",
    "attbfr",
    "attnow",
    "edulvl",
    "educhn",
    "edumar",
    "wrkexp",
    "pl_wrkmar",
    "pr_wrkmar",
    "wrkmar",
    "mar_isco04",
    "mar_isco04_oth",
    "mar_isco01",
    "maryrs",
    "marnis",
    "marcnt",
    "martel",
    "pl_maywrk",
    "pr_maywrk",
    "maywrk",
    "maysme",
    "maynis",
    "maytel",
    "incact",
    "wrkrtn",
    "avlbl",
    "search",
    "smemar",
    "smemay",
    "stprsn",
    "stprsn_oth",
    "now_isco04",
    "now_isco04_oth",
    "now_isco01",
    "emptyp",
    "sector",
    "sector_oth",
    "nownis",
    "unembf",
    "nowtel",
    "hrsmar",
    "hrsmay",
    "fulpay",
    "source_resource"
FROM "idb-covid-19-household-telephone-survey-in-barbados-round-2-2020"
