-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("nim" AS BIGINT) AS nim,
    CAST("numero_mo_0" AS BIGINT) AS numero_mo_0,
    CAST("numero_mo_1" AS BIGINT) AS numero_mo_1,
    CAST("numero_fa_0" AS BIGINT) AS numero_fa_0,
    CAST("numero_fa_1" AS BIGINT) AS numero_fa_1,
    CAST("id_hh" AS BIGINT) AS id_hh,
    CAST("id_sp" AS BIGINT) AS id_sp,
    "secc",
    CAST("estrato_0" AS BIGINT) AS estrato_0,
    "estrato_1",
    "battery",
    CAST("interviewer_0" AS BIGINT) AS interviewer_0,
    CAST("interviewer_1" AS BIGINT) AS interviewer_1,
    CAST("b_tester" AS BIGINT) AS b_tester,
    CAST("w_tester" AS BIGINT) AS w_tester,
    "date_interview_0",
    "date_interview_1",
    "day_wk_interview_0",
    "day_wk_interview_1",
    "date_bayley",
    "date_asq",
    "date_den",
    "date_mac",
    "date_bat",
    "date_mil",
    "date_tests_1",
    CAST("duration_interview_1" AS BIGINT) AS duration_interview_1,
    CAST("time_tests_1" AS BIGINT) AS time_tests_1,
    CAST("time_tests_break_1" AS BIGINT) AS time_tests_break_1,
    "respondent_1",
    "date_dob",
    CAST("dob_day" AS BIGINT) AS dob_day,
    CAST("dob_mth" AS BIGINT) AS dob_mth,
    CAST("dob_yr" AS BIGINT) AS dob_yr,
    CAST("age_mth_0" AS BIGINT) AS age_mth_0,
    CAST("age_reported_0" AS BIGINT) AS age_reported_0,
    CAST("age_mth_reported_0" AS BIGINT) AS age_mth_reported_0,
    CAST("b_age" AS BIGINT) AS b_age,
    CAST("b_age_mth" AS BIGINT) AS b_age_mth,
    CAST("asq_age_mth" AS BIGINT) AS asq_age_mth,
    CAST("mac_age_mth" AS BIGINT) AS mac_age_mth,
    CAST("den_age_mth" AS BIGINT) AS den_age_mth,
    CAST("bat_age_mth" AS BIGINT) AS bat_age_mth,
    CAST("mil_age_mth" AS BIGINT) AS mil_age_mth,
    CAST("b_age_day" AS BIGINT) AS b_age_day,
    CAST("asq_age_day" AS BIGINT) AS asq_age_day,
    CAST("den_age_day" AS BIGINT) AS den_age_day,
    CAST("mac_age_day" AS BIGINT) AS mac_age_day,
    CAST("bat_age_day" AS BIGINT) AS bat_age_day,
    CAST("mil_age_day" AS BIGINT) AS mil_age_day,
    CAST("age_yr_1" AS BIGINT) AS age_yr_1,
    CAST("age_mth_1" AS BIGINT) AS age_mth_1,
    CAST("age_reported_1" AS BIGINT) AS age_reported_1,
    CAST("w_age_yr_1" AS BIGINT) AS w_age_yr_1,
    CAST("w_age_mth_1" AS BIGINT) AS w_age_mth_1,
    CAST("w_age_day_1" AS BIGINT) AS w_age_day_1,
    CAST("w_age_reported_yr_1" AS BIGINT) AS w_age_reported_yr_1,
    CAST("w_age_reported_mth_1" AS BIGINT) AS w_age_reported_mth_1,
    CAST("w_age_reported_day_1" AS BIGINT) AS w_age_reported_day_1,
    CAST("female" AS BIGINT) AS female,
    CAST("premature" AS BIGINT) AS premature,
    CAST("gest_age" AS BIGINT) AS gest_age,
    CAST("first_child" AS BOOLEAN) AS first_child,
    CAST("birthweight" AS BIGINT) AS birthweight,
    CAST("edu" AS DOUBLE) AS edu,
    CAST("school" AS BIGINT) AS school,
    "grade",
    CAST("age_mo" AS BIGINT) AS age_mo,
    "civil_mo",
    CAST("edu_mo" AS BIGINT) AS edu_mo,
    "edu_cat_mo",
    CAST("edu_mo_0" AS BIGINT) AS edu_mo_0,
    "edu_cat_mo_0",
    CAST("employed_mo" AS BIGINT) AS employed_mo,
    CAST("dom_wk_mo" AS BIGINT) AS dom_wk_mo,
    CAST("retired_mo" AS BIGINT) AS retired_mo,
    CAST("work_mo" AS BIGINT) AS work_mo,
    "status_mo",
    CAST("dead_mo" AS BIGINT) AS dead_mo,
    CAST("absent_mo" AS BIGINT) AS absent_mo,
    CAST("age_fa" AS BIGINT) AS age_fa,
    "civil_fa",
    CAST("edu_fa" AS BIGINT) AS edu_fa,
    "edu_cat_fa",
    CAST("edu_fa_0" AS BIGINT) AS edu_fa_0,
    "edu_cat_fa_0",
    CAST("employed_fa" AS BIGINT) AS employed_fa,
    CAST("dom_wk_fa" AS BIGINT) AS dom_wk_fa,
    CAST("retired_fa" AS BIGINT) AS retired_fa,
    CAST("work_fa" AS BIGINT) AS work_fa,
    "status_fa",
    CAST("dead_fa" AS BIGINT) AS dead_fa,
    CAST("absent_fa" AS BIGINT) AS absent_fa,
    CAST("absent_fa_0" AS BIGINT) AS absent_fa_0,
    CAST("age_hh" AS BIGINT) AS age_hh,
    CAST("female_hh" AS BIGINT) AS female_hh,
    "civil_hh",
    CAST("edu_hh" AS BIGINT) AS edu_hh,
    CAST("employed_hh" AS BIGINT) AS employed_hh,
    CAST("dom_wk_hh" AS BIGINT) AS dom_wk_hh,
    CAST("retired_hh" AS BIGINT) AS retired_hh,
    CAST("work_hh" AS BIGINT) AS work_hh,
    CAST("age_sp" AS BIGINT) AS age_sp,
    CAST("female_sp" AS BIGINT) AS female_sp,
    "civil_sp",
    CAST("edu_sp" AS BIGINT) AS edu_sp,
    CAST("employed_sp" AS BIGINT) AS employed_sp,
    CAST("dom_wk_sp" AS BIGINT) AS dom_wk_sp,
    CAST("retired_sp" AS BIGINT) AS retired_sp,
    CAST("work_sp" AS BIGINT) AS work_sp,
    "house_type_1",
    "homeownership",
    CAST("home_own" AS BIGINT) AS home_own,
    CAST("home_move" AS BOOLEAN) AS home_move,
    CAST("hhsize_0" AS BIGINT) AS hhsize_0,
    CAST("hhsize_1" AS BIGINT) AS hhsize_1,
    CAST("crowding_0" AS DOUBLE) AS crowding_0,
    CAST("crowding_1" AS DOUBLE) AS crowding_1,
    "floors",
    "walls_ext",
    "walls_int",
    "roof",
    CAST("gas" AS BOOLEAN) AS gas,
    CAST("phone" AS BOOLEAN) AS phone,
    CAST("internet" AS BOOLEAN) AS internet,
    CAST("cable_tv" AS BOOLEAN) AS cable_tv,
    CAST("portero" AS BOOLEAN) AS portero,
    "kitchen",
    CAST("kitchen_shared" AS BOOLEAN) AS kitchen_shared,
    CAST("rooms_sleep_nb" AS BIGINT) AS rooms_sleep_nb,
    CAST("living" AS BOOLEAN) AS living,
    CAST("dining" AS BOOLEAN) AS dining,
    CAST("rooms" AS BOOLEAN) AS rooms,
    CAST("rooms_nb" AS BIGINT) AS rooms_nb,
    CAST("studio" AS BOOLEAN) AS studio,
    CAST("windows" AS BOOLEAN) AS windows,
    "windows_nb",
    CAST("garage" AS BOOLEAN) AS garage,
    CAST("balcony" AS BOOLEAN) AS balcony,
    CAST("balcony_nb" AS BIGINT) AS balcony_nb,
    CAST("bathroom_nb" AS BIGINT) AS bathroom_nb,
    CAST("shower" AS BOOLEAN) AS shower,
    CAST("sisben_yr" AS BIGINT) AS sisben_yr,
    "sisben",
    CAST("car" AS BOOLEAN) AS car,
    CAST("car_nb" AS BIGINT) AS car_nb,
    CAST("motorbike" AS BOOLEAN) AS motorbike,
    CAST("motorbike_nb" AS BIGINT) AS motorbike_nb,
    CAST("fridge" AS BOOLEAN) AS fridge,
    CAST("fridge_nb" AS BIGINT) AS fridge_nb,
    CAST("microwave" AS BOOLEAN) AS microwave,
    CAST("washer" AS BOOLEAN) AS washer,
    CAST("drier" AS BOOLEAN) AS drier,
    CAST("boiler" AS BOOLEAN) AS boiler,
    CAST("computer" AS BOOLEAN) AS computer,
    CAST("computer_nb" AS BIGINT) AS computer_nb,
    CAST("dvd" AS BOOLEAN) AS dvd,
    CAST("dvd_nb" AS BIGINT) AS dvd_nb,
    CAST("consola" AS BOOLEAN) AS consola,
    CAST("consola_nb" AS BIGINT) AS consola_nb,
    CAST("smartphone" AS BOOLEAN) AS smartphone,
    CAST("smartphone_nb" AS BIGINT) AS smartphone_nb,
    CAST("flat_tv" AS BOOLEAN) AS flat_tv,
    CAST("flat_tv_nb" AS BIGINT) AS flat_tv_nb,
    CAST("home_theatre" AS BOOLEAN) AS home_theatre,
    CAST("home_theatre_nb" AS BIGINT) AS home_theatre_nb,
    CAST("stereo" AS BOOLEAN) AS stereo,
    CAST("stereo_nb" AS BIGINT) AS stereo_nb,
    CAST("empleada" AS BOOLEAN) AS empleada,
    "empleada_days",
    CAST("floors_quality" AS BIGINT) AS floors_quality,
    CAST("bathroom_shared" AS BIGINT) AS bathroom_shared,
    CAST("bathroom_dnb" AS BIGINT) AS bathroom_dnb,
    CAST("internet_0" AS BOOLEAN) AS internet_0,
    CAST("kitchen_shared_0" AS BOOLEAN) AS kitchen_shared_0,
    CAST("windows_0" AS BOOLEAN) AS windows_0,
    CAST("garage_0" AS BOOLEAN) AS garage_0,
    CAST("car_0" AS BOOLEAN) AS car_0,
    CAST("fridge_0" AS BOOLEAN) AS fridge_0,
    CAST("microwave_0" AS BOOLEAN) AS microwave_0,
    CAST("washer_0" AS BOOLEAN) AS washer_0,
    CAST("boiler_0" AS BOOLEAN) AS boiler_0,
    CAST("computer_0" AS BOOLEAN) AS computer_0,
    CAST("dvd_0" AS BOOLEAN) AS dvd_0,
    CAST("consola_0" AS BOOLEAN) AS consola_0,
    CAST("smartphone_0" AS BOOLEAN) AS smartphone_0,
    CAST("flat_tv_0" AS BOOLEAN) AS flat_tv_0,
    CAST("stereo_0" AS BOOLEAN) AS stereo_0,
    CAST("floors_quality_0" AS BIGINT) AS floors_quality_0,
    CAST("bathroom_shared_0" AS BIGINT) AS bathroom_shared_0,
    CAST("bathroom_dnb_0" AS BIGINT) AS bathroom_dnb_0,
    CAST("home_theatre_0" AS BOOLEAN) AS home_theatre_0,
    CAST("wealth_5p_0" AS DOUBLE) AS wealth_5p_0,
    CAST("wealth_5p_qr_0" AS BIGINT) AS wealth_5p_qr_0,
    CAST("wealth_5p_1" AS DOUBLE) AS wealth_5p_1,
    CAST("wealth_5p_qr_1" AS BIGINT) AS wealth_5p_qr_1,
    "b_infor",
    CAST("b_tot_cog" AS BIGINT) AS b_tot_cog,
    CAST("b_tot_lr" AS BIGINT) AS b_tot_lr,
    CAST("b_tot_le" AS BIGINT) AS b_tot_le,
    CAST("b_tot_mf" AS BIGINT) AS b_tot_mf,
    CAST("b_tot_mg" AS BIGINT) AS b_tot_mg,
    CAST("b_tot_se" AS BIGINT) AS b_tot_se,
    CAST("b_pc_cog" AS BIGINT) AS b_pc_cog,
    CAST("b_pc_lang" AS BIGINT) AS b_pc_lang,
    CAST("b_pc_mot" AS BIGINT) AS b_pc_mot,
    CAST("b_pc_se" AS BIGINT) AS b_pc_se,
    "asq_infor",
    CAST("asq_test" AS BIGINT) AS asq_test,
    CAST("asq_lang" AS BIGINT) AS asq_lang,
    CAST("asq_mf" AS BIGINT) AS asq_mf,
    CAST("asq_mg" AS BIGINT) AS asq_mg,
    CAST("asq_cog" AS BIGINT) AS asq_cog,
    CAST("asq_soc" AS BIGINT) AS asq_soc,
    CAST("asq_lang_tot1" AS BIGINT) AS asq_lang_tot1,
    CAST("asq_mf_tot1" AS BIGINT) AS asq_mf_tot1,
    CAST("asq_mg_tot1" AS BIGINT) AS asq_mg_tot1,
    CAST("asq_cog_tot1" AS BIGINT) AS asq_cog_tot1,
    CAST("asq_soc_tot1" AS BIGINT) AS asq_soc_tot1,
    CAST("asq_tot" AS BIGINT) AS asq_tot,
    CAST("asq_tot_tot1" AS BIGINT) AS asq_tot_tot1,
    "mac_infor",
    CAST("mac_underst1" AS BIGINT) AS mac_underst1,
    CAST("mac_says1" AS BIGINT) AS mac_says1,
    CAST("mac_says2" AS BIGINT) AS mac_says2,
    CAST("mac_le" AS BIGINT) AS mac_le,
    CAST("mac_lr" AS BIGINT) AS mac_lr,
    "den_infor",
    CAST("den_mg" AS BIGINT) AS den_mg,
    CAST("den_lang" AS BIGINT) AS den_lang,
    CAST("den_mf" AS BIGINT) AS den_mf,
    CAST("den_soc" AS BIGINT) AS den_soc,
    CAST("den_tot" AS BIGINT) AS den_tot,
    "bat_infor",
    CAST("bat_adp" AS BIGINT) AS bat_adp,
    CAST("bat_soc" AS BIGINT) AS bat_soc,
    CAST("bat_lang" AS BIGINT) AS bat_lang,
    CAST("bat_mot" AS BIGINT) AS bat_mot,
    CAST("bat_cog" AS BIGINT) AS bat_cog,
    CAST("bat_tot" AS BIGINT) AS bat_tot,
    "mil_infor",
    CAST("mil_tot" AS BIGINT) AS mil_tot,
    CAST("flag_all_b_asq" AS BIGINT) AS flag_all_b_asq,
    CAST("flag_all_b_mac" AS BIGINT) AS flag_all_b_mac,
    CAST("flag_all_b_den" AS BIGINT) AS flag_all_b_den,
    CAST("flag_all_b_bat" AS BIGINT) AS flag_all_b_bat,
    CAST("flag_all_b_mil" AS BIGINT) AS flag_all_b_mil,
    CAST("r_b_st_cog_kd" AS DOUBLE) AS r_b_st_cog_kd,
    CAST("r_b_st_lr_kd" AS DOUBLE) AS r_b_st_lr_kd,
    CAST("r_b_st_le_kd" AS DOUBLE) AS r_b_st_le_kd,
    CAST("r_b_st_mf_kd" AS DOUBLE) AS r_b_st_mf_kd,
    CAST("r_b_st_mg_kd" AS DOUBLE) AS r_b_st_mg_kd,
    CAST("r_b_st_se_kd" AS DOUBLE) AS r_b_st_se_kd,
    CAST("r_asq_st_cog_kd" AS DOUBLE) AS r_asq_st_cog_kd,
    CAST("r_asq_st_lang_kd" AS DOUBLE) AS r_asq_st_lang_kd,
    CAST("r_asq_st_mf_kd" AS DOUBLE) AS r_asq_st_mf_kd,
    CAST("r_asq_st_mg_kd" AS DOUBLE) AS r_asq_st_mg_kd,
    CAST("r_asq_st_soc_kd" AS DOUBLE) AS r_asq_st_soc_kd,
    CAST("r_asq_st_tot_kd" AS DOUBLE) AS r_asq_st_tot_kd,
    CAST("r_asq_st_cog_tot1_kd" AS DOUBLE) AS r_asq_st_cog_tot1_kd,
    CAST("r_asq_st_lang_tot1_kd" AS DOUBLE) AS r_asq_st_lang_tot1_kd,
    CAST("r_asq_st_mf_tot1_kd" AS DOUBLE) AS r_asq_st_mf_tot1_kd,
    CAST("r_asq_st_mg_tot1_kd" AS DOUBLE) AS r_asq_st_mg_tot1_kd,
    CAST("r_asq_st_soc_tot1_kd" AS DOUBLE) AS r_asq_st_soc_tot1_kd,
    CAST("r_asq_st_tot_tot1_kd" AS DOUBLE) AS r_asq_st_tot_tot1_kd,
    CAST("r_den_st_lang_kd" AS DOUBLE) AS r_den_st_lang_kd,
    CAST("r_den_st_mf_kd" AS DOUBLE) AS r_den_st_mf_kd,
    CAST("r_den_st_mg_kd" AS DOUBLE) AS r_den_st_mg_kd,
    CAST("r_den_st_soc_kd" AS DOUBLE) AS r_den_st_soc_kd,
    CAST("r_den_st_tot_kd" AS DOUBLE) AS r_den_st_tot_kd,
    CAST("r_mac_st_lr_kd" AS DOUBLE) AS r_mac_st_lr_kd,
    CAST("r_mac_st_le_kd" AS DOUBLE) AS r_mac_st_le_kd,
    CAST("r_bat_st_soc_kd" AS DOUBLE) AS r_bat_st_soc_kd,
    CAST("r_bat_st_lang_kd" AS DOUBLE) AS r_bat_st_lang_kd,
    CAST("r_bat_st_cog_kd" AS DOUBLE) AS r_bat_st_cog_kd,
    CAST("r_bat_st_tot_kd" AS DOUBLE) AS r_bat_st_tot_kd,
    CAST("r_bat_st_adp_kd" AS DOUBLE) AS r_bat_st_adp_kd,
    CAST("r_bat_st_mot_kd" AS DOUBLE) AS r_bat_st_mot_kd,
    CAST("r_mil_st_tot_kd" AS DOUBLE) AS r_mil_st_tot_kd,
    CAST("weight_0" AS DOUBLE) AS weight_0,
    CAST("height_0" AS DOUBLE) AS height_0,
    CAST("zwei_0" AS DOUBLE) AS zwei_0,
    CAST("zlen_0" AS DOUBLE) AS zlen_0,
    CAST("zbmi_0" AS DOUBLE) AS zbmi_0,
    CAST("zwfl_0" AS DOUBLE) AS zwfl_0,
    CAST("underweight_0" AS BIGINT) AS underweight_0,
    CAST("stunted_0" AS BIGINT) AS stunted_0,
    CAST("wasted_0" AS BIGINT) AS wasted_0,
    CAST("fci_play_a" AS BOOLEAN) AS fci_play_a,
    "fci_play_b",
    CAST("fci_play_c" AS BOOLEAN) AS fci_play_c,
    CAST("fci_play_d" AS BOOLEAN) AS fci_play_d,
    CAST("fci_play_e" AS BOOLEAN) AS fci_play_e,
    CAST("fci_play_f" AS BOOLEAN) AS fci_play_f,
    CAST("fci_play_g" AS BOOLEAN) AS fci_play_g,
    CAST("fci_play_h" AS BOOLEAN) AS fci_play_h,
    "fci_play_i",
    CAST("fci_play_j" AS BOOLEAN) AS fci_play_j,
    CAST("fci_play_k" AS BOOLEAN) AS fci_play_k,
    "fci_books_adults",
    "fci_newspapers",
    "fci_act_a_1",
    "fci_act_b_1",
    "fci_act_c_1",
    "fci_act_d_1",
    "fci_act_e_1",
    "fci_act_f_1",
    "fci_act_g_1",
    CAST("r_fci_mat_0_kd" AS DOUBLE) AS r_fci_mat_0_kd,
    CAST("r_fci_act_0_kd" AS DOUBLE) AS r_fci_act_0_kd,
    CAST("r_fci_0_kd" AS DOUBLE) AS r_fci_0_kd,
    CAST("home_score" AS BIGINT) AS home_score,
    CAST("r_home_score_kd_1" AS DOUBLE) AS r_home_score_kd_1,
    CAST("p1_raw_score" AS BIGINT) AS p1_raw_score,
    CAST("p2_raw_score" AS BIGINT) AS p2_raw_score,
    CAST("p3_raw_score" AS BIGINT) AS p3_raw_score,
    CAST("p4_d_raw_score" AS BIGINT) AS p4_d_raw_score,
    CAST("p4_i_raw_score" AS BIGINT) AS p4_i_raw_score,
    CAST("p4_s_raw_score" AS BIGINT) AS p4_s_raw_score,
    CAST("p4_raw_score" AS BIGINT) AS p4_raw_score,
    CAST("p5_test" AS BIGINT) AS p5_test,
    CAST("p5_raw_score" AS BIGINT) AS p5_raw_score,
    CAST("p6_raw_score" AS BIGINT) AS p6_raw_score,
    CAST("p7_raw_score" AS BIGINT) AS p7_raw_score,
    CAST("p11_raw_score" AS BIGINT) AS p11_raw_score,
    CAST("p12_raw_score" AS BIGINT) AS p12_raw_score,
    CAST("p13_raw_score" AS BIGINT) AS p13_raw_score,
    CAST("wisc_iq" AS BIGINT) AS wisc_iq,
    CAST("r_p1_kd_1" AS DOUBLE) AS r_p1_kd_1,
    CAST("r_p2_kd_1" AS DOUBLE) AS r_p2_kd_1,
    CAST("r_p3_kd_1" AS DOUBLE) AS r_p3_kd_1,
    CAST("r_p4_d_kd_1" AS DOUBLE) AS r_p4_d_kd_1,
    CAST("r_p4_i_kd_1" AS DOUBLE) AS r_p4_i_kd_1,
    CAST("r_p4_s_kd_1" AS DOUBLE) AS r_p4_s_kd_1,
    CAST("r_p4_kd_1" AS DOUBLE) AS r_p4_kd_1,
    CAST("r_p5_kd_1" AS DOUBLE) AS r_p5_kd_1,
    CAST("r_p6_kd_1" AS DOUBLE) AS r_p6_kd_1,
    CAST("r_p7_kd_1" AS DOUBLE) AS r_p7_kd_1,
    CAST("r_p11_kd_1" AS DOUBLE) AS r_p11_kd_1,
    CAST("r_p12_kd_1" AS DOUBLE) AS r_p12_kd_1,
    CAST("r_p13_kd_1" AS DOUBLE) AS r_p13_kd_1,
    CAST("r_wisc_iq_kd_1" AS DOUBLE) AS r_wisc_iq_kd_1,
    CAST("r_a_111213_kd_1" AS DOUBLE) AS r_a_111213_kd_1,
    "source_resource"
FROM "idb-bogota-measurements-predictive-validity-bayley-short-tests-survey-data-2011"
