-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Wide source table with many measured attributes or category columns; avoid summing across columns without checking the upstream definition.
SELECT
    "Number" AS number,
    "Total_Total" AS total_total,
    "Total_AgeGroupofHusband_Years_Below30" AS total_agegroupofhusband_years_below30,
    "Total_AgeGroupofHusband_Years_30_34" AS total_agegroupofhusband_years_30_34,
    "Total_AgeGroupofHusband_Years_35_39" AS total_agegroupofhusband_years_35_39,
    "Total_AgeGroupofHusband_Years_40_44" AS total_agegroupofhusband_years_40_44,
    "Total_AgeGroupofHusband_Years_45_49" AS total_agegroupofhusband_years_45_49,
    "Total_AgeGroupofHusband_Years_50_54" AS total_agegroupofhusband_years_50_54,
    "Total_AgeGroupofHusband_Years_55_59" AS total_agegroupofhusband_years_55_59,
    "Total_AgeGroupofHusband_Years_60_64" AS total_agegroupofhusband_years_60_64,
    "Total_AgeGroupofHusband_Years_65andOver" AS total_agegroupofhusband_years_65andover,
    "BothChinese_Total" AS bothchinese_total,
    "BothChinese_AgeGroupofHusband_Years_Below30" AS bothchinese_agegroupofhusband_years_below30,
    "BothChinese_AgeGroupofHusband_Years_30_34" AS bothchinese_agegroupofhusband_years_30_34,
    "BothChinese_AgeGroupofHusband_Years_35_39" AS bothchinese_agegroupofhusband_years_35_39,
    "BothChinese_AgeGroupofHusband_Years_40_44" AS bothchinese_agegroupofhusband_years_40_44,
    "BothChinese_AgeGroupofHusband_Years_45_49" AS bothchinese_agegroupofhusband_years_45_49,
    "BothChinese_AgeGroupofHusband_Years_50_54" AS bothchinese_agegroupofhusband_years_50_54,
    "BothChinese_AgeGroupofHusband_Years_55_59" AS bothchinese_agegroupofhusband_years_55_59,
    "BothChinese_AgeGroupofHusband_Years_60_64" AS bothchinese_agegroupofhusband_years_60_64,
    "BothChinese_AgeGroupofHusband_Years_65andOver" AS bothchinese_agegroupofhusband_years_65andover,
    "BothMalays_Total" AS bothmalays_total,
    "BothMalays_AgeGroupofHusband_Years_Below30" AS bothmalays_agegroupofhusband_years_below30,
    "BothMalays_AgeGroupofHusband_Years_30_34" AS bothmalays_agegroupofhusband_years_30_34,
    "BothMalays_AgeGroupofHusband_Years_35_39" AS bothmalays_agegroupofhusband_years_35_39,
    "BothMalays_AgeGroupofHusband_Years_40_44" AS bothmalays_agegroupofhusband_years_40_44,
    "BothMalays_AgeGroupofHusband_Years_45_49" AS bothmalays_agegroupofhusband_years_45_49,
    "BothMalays_AgeGroupofHusband_Years_50_54" AS bothmalays_agegroupofhusband_years_50_54,
    "BothMalays_AgeGroupofHusband_Years_55_59" AS bothmalays_agegroupofhusband_years_55_59,
    "BothMalays_AgeGroupofHusband_Years_60_64" AS bothmalays_agegroupofhusband_years_60_64,
    "BothMalays_AgeGroupofHusband_Years_65andOver" AS bothmalays_agegroupofhusband_years_65andover,
    "BothIndians_Total" AS bothindians_total,
    "BothIndians_AgeGroupofHusband_Years_Below30" AS bothindians_agegroupofhusband_years_below30,
    "BothIndians_AgeGroupofHusband_Years_30_34" AS bothindians_agegroupofhusband_years_30_34,
    "BothIndians_AgeGroupofHusband_Years_35_39" AS bothindians_agegroupofhusband_years_35_39,
    "BothIndians_AgeGroupofHusband_Years_40_44" AS bothindians_agegroupofhusband_years_40_44,
    "BothIndians_AgeGroupofHusband_Years_45_49" AS bothindians_agegroupofhusband_years_45_49,
    "BothIndians_AgeGroupofHusband_Years_50_54" AS bothindians_agegroupofhusband_years_50_54,
    "BothIndians_AgeGroupofHusband_Years_55_59" AS bothindians_agegroupofhusband_years_55_59,
    "BothIndians_AgeGroupofHusband_Years_60_64" AS bothindians_agegroupofhusband_years_60_64,
    "BothIndians_AgeGroupofHusband_Years_65andOver" AS bothindians_agegroupofhusband_years_65andover,
    "BothOtherEthnicGroup_Total" AS bothotherethnicgroup_total,
    "BothOtherEthnicGroup_AgeGroupofHusband_Years_Below30" AS bothotherethnicgroup_agegroupofhusband_years_below30,
    "BothOtherEthnicGroup_AgeGroupofHusband_Years_30_34" AS bothotherethnicgroup_agegroupofhusband_years_30_34,
    "BothOtherEthnicGroup_AgeGroupofHusband_Years_35_39" AS bothotherethnicgroup_agegroupofhusband_years_35_39,
    "BothOtherEthnicGroup_AgeGroupofHusband_Years_40_44" AS bothotherethnicgroup_agegroupofhusband_years_40_44,
    "BothOtherEthnicGroup_AgeGroupofHusband_Years_45_49" AS bothotherethnicgroup_agegroupofhusband_years_45_49,
    "BothOtherEthnicGroup_AgeGroupofHusband_Years_50_54" AS bothotherethnicgroup_agegroupofhusband_years_50_54,
    "BothOtherEthnicGroup_AgeGroupofHusband_Years_55_59" AS bothotherethnicgroup_agegroupofhusband_years_55_59,
    "BothOtherEthnicGroup_AgeGroupofHusband_Years_60_64" AS bothotherethnicgroup_agegroupofhusband_years_60_64,
    "BothOtherEthnicGroup_AgeGroupofHusband_Years_65andOver" AS bothotherethnicgroup_agegroupofhusband_years_65andover,
    "Inter_EthnicGroup_Total" AS inter_ethnicgroup_total,
    "Inter_EthnicGroup_AgeGroupofHusband_Years_Below30" AS inter_ethnicgroup_agegroupofhusband_years_below30,
    "Inter_EthnicGroup_AgeGroupofHusband_Years_30_34" AS inter_ethnicgroup_agegroupofhusband_years_30_34,
    "Inter_EthnicGroup_AgeGroupofHusband_Years_35_39" AS inter_ethnicgroup_agegroupofhusband_years_35_39,
    "Inter_EthnicGroup_AgeGroupofHusband_Years_40_44" AS inter_ethnicgroup_agegroupofhusband_years_40_44,
    "Inter_EthnicGroup_AgeGroupofHusband_Years_45_49" AS inter_ethnicgroup_agegroupofhusband_years_45_49,
    "Inter_EthnicGroup_AgeGroupofHusband_Years_50_54" AS inter_ethnicgroup_agegroupofhusband_years_50_54,
    "Inter_EthnicGroup_AgeGroupofHusband_Years_55_59" AS inter_ethnicgroup_agegroupofhusband_years_55_59,
    "Inter_EthnicGroup_AgeGroupofHusband_Years_60_64" AS inter_ethnicgroup_agegroupofhusband_years_60_64,
    "Inter_EthnicGroup_AgeGroupofHusband_Years_65andOver" AS inter_ethnicgroup_agegroupofhusband_years_65andover
FROM "sg-data-d-cadd4d2df56ac4187847648f44ffcb9c"
