-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Wide source table with many measured attributes or category columns; avoid summing across columns without checking the upstream definition.
SELECT
    "Thousands" AS thousands,
    "Total_Total" AS total_total,
    "Total_Manufacturing" AS total_manufacturing,
    "Total_Construction" AS total_construction,
    "Total_Services_Total" AS total_services_total,
    "Total_Services_WholesaleandRetailTrade" AS total_services_wholesaleandretailtrade,
    "Total_Services_TransportationandStorage" AS total_services_transportationandstorage,
    "Total_Services_AccommodationandFoodServices" AS total_services_accommodationandfoodservices,
    "Total_Services_InformationandCommunications" AS total_services_informationandcommunications,
    "Total_Services_FinancialandInsuranceServices" AS total_services_financialandinsuranceservices,
    "Total_Services_RealEstateServices" AS total_services_realestateservices,
    "Total_Services_ProfessionalServices" AS total_services_professionalservices,
    "Total_Services_AdministrativeandSupportServices" AS total_services_administrativeandsupportservices,
    "Total_Services_PublicAdministrationandEducation" AS total_services_publicadministrationandeducation,
    "Total_Services_HealthandSocialServices" AS total_services_healthandsocialservices,
    "Total_Services_Arts_EntertainmentandRecreation" AS total_services_arts_entertainmentandrecreation,
    "Total_Services_OtherCommunity_SocialandPersonalServices" AS total_services_othercommunity_socialandpersonalservices,
    "Total_Others1" AS total_others1,
    "Males_Total" AS males_total,
    "Males_Manufacturing" AS males_manufacturing,
    "Males_Construction" AS males_construction,
    "Males_Services_Total" AS males_services_total,
    "Males_Services_WholesaleandRetailTrade" AS males_services_wholesaleandretailtrade,
    "Males_Services_TransportationandStorage" AS males_services_transportationandstorage,
    "Males_Services_AccommodationandFoodServices" AS males_services_accommodationandfoodservices,
    "Males_Services_InformationandCommunications" AS males_services_informationandcommunications,
    "Males_Services_FinancialandInsuranceServices" AS males_services_financialandinsuranceservices,
    "Males_Services_RealEstateServices" AS males_services_realestateservices,
    "Males_Services_ProfessionalServices" AS males_services_professionalservices,
    "Males_Services_AdministrativeandSupportServices" AS males_services_administrativeandsupportservices,
    "Males_Services_PublicAdministrationandEducation" AS males_services_publicadministrationandeducation,
    "Males_Services_HealthandSocialServices" AS males_services_healthandsocialservices,
    "Males_Services_Arts_EntertainmentandRecreation" AS males_services_arts_entertainmentandrecreation,
    "Males_Services_OtherCommunity_SocialandPersonalServices" AS males_services_othercommunity_socialandpersonalservices,
    "Males_Others1" AS males_others1,
    "Females_Total" AS females_total,
    "Females_Manufacturing" AS females_manufacturing,
    "Females_Construction" AS females_construction,
    "Females_Services_Total" AS females_services_total,
    "Females_Services_WholesaleandRetailTrade" AS females_services_wholesaleandretailtrade,
    "Females_Services_TransportationandStorage" AS females_services_transportationandstorage,
    "Females_Services_AccommodationandFoodServices" AS females_services_accommodationandfoodservices,
    "Females_Services_InformationandCommunications" AS females_services_informationandcommunications,
    "Females_Services_FinancialandInsuranceServices" AS females_services_financialandinsuranceservices,
    "Females_Services_RealEstateServices" AS females_services_realestateservices,
    "Females_Services_ProfessionalServices" AS females_services_professionalservices,
    "Females_Services_AdministrativeandSupportServices" AS females_services_administrativeandsupportservices,
    "Females_Services_PublicAdministrationandEducation" AS females_services_publicadministrationandeducation,
    "Females_Services_HealthandSocialServices" AS females_services_healthandsocialservices,
    "Females_Services_Arts_EntertainmentandRecreation" AS females_services_arts_entertainmentandrecreation,
    "Females_Services_OtherCommunity_SocialandPersonalServices" AS females_services_othercommunity_socialandpersonalservices,
    "Females_Others1" AS females_others1
FROM "sg-data-d-37e165ea55e6ee1ac4d6903e3f524e6f"
