-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Wide source table with many measured attributes or category columns; avoid summing across columns without checking the upstream definition.
SELECT
    "Number" AS number,
    "Total_Total" AS total_total,
    "Total_NoQualification" AS total_noqualification,
    "Total_Primary" AS total_primary,
    "Total_LowerSecondary" AS total_lowersecondary,
    "Total_Secondary" AS total_secondary,
    "Total_UpperSecondary" AS total_uppersecondary,
    "Total_Polytechnic" AS total_polytechnic,
    "Total_OtherDiploma" AS total_otherdiploma,
    "Total_University" AS total_university,
    "Total_Students" AS total_students,
    "Below35Years_Total" AS below35years_total,
    "Below35Years_NoQualification" AS below35years_noqualification,
    "Below35Years_Primary" AS below35years_primary,
    "Below35Years_LowerSecondary" AS below35years_lowersecondary,
    "Below35Years_Secondary" AS below35years_secondary,
    "Below35Years_UpperSecondary" AS below35years_uppersecondary,
    "Below35Years_Polytechnic" AS below35years_polytechnic,
    "Below35Years_OtherDiploma" AS below35years_otherdiploma,
    "Below35Years_University" AS below35years_university,
    "Below35Years_Students" AS below35years_students,
    "35_49Years_Total" AS 35_49years_total,
    "35_49Years_NoQualification" AS 35_49years_noqualification,
    "35_49Years_Primary" AS 35_49years_primary,
    "35_49Years_LowerSecondary" AS 35_49years_lowersecondary,
    "35_49Years_Secondary" AS 35_49years_secondary,
    "35_49Years_UpperSecondary" AS 35_49years_uppersecondary,
    "35_49Years_Polytechnic" AS 35_49years_polytechnic,
    "35_49Years_OtherDiploma" AS 35_49years_otherdiploma,
    "35_49Years_University" AS 35_49years_university,
    "35_49Years_Students" AS 35_49years_students,
    "50_64Years_Total" AS 50_64years_total,
    "50_64Years_NoQualification" AS 50_64years_noqualification,
    "50_64Years_Primary" AS 50_64years_primary,
    "50_64Years_LowerSecondary" AS 50_64years_lowersecondary,
    "50_64Years_Secondary" AS 50_64years_secondary,
    "50_64Years_UpperSecondary" AS 50_64years_uppersecondary,
    "50_64Years_Polytechnic" AS 50_64years_polytechnic,
    "50_64Years_OtherDiploma" AS 50_64years_otherdiploma,
    "50_64Years_University" AS 50_64years_university,
    "50_64Years_Students" AS 50_64years_students,
    "65YearsandOver_Total" AS 65yearsandover_total,
    "65YearsandOver_NoQualification" AS 65yearsandover_noqualification,
    "65YearsandOver_Primary" AS 65yearsandover_primary,
    "65YearsandOver_LowerSecondary" AS 65yearsandover_lowersecondary,
    "65YearsandOver_Secondary" AS 65yearsandover_secondary,
    "65YearsandOver_UpperSecondary" AS 65yearsandover_uppersecondary,
    "65YearsandOver_Polytechnic" AS 65yearsandover_polytechnic,
    "65YearsandOver_OtherDiploma" AS 65yearsandover_otherdiploma,
    "65YearsandOver_University" AS 65yearsandover_university,
    "65YearsandOver_Students" AS 65yearsandover_students
FROM "sg-data-d-086ca134bb9bbfc61276ee62e03c1d08"
