-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Wide source table with many measured attributes or category columns; avoid summing across columns without checking the upstream definition.
SELECT
    "Number" AS number,
    "Total_Total_Total" AS total_total_total,
    "Total_Total_Males" AS total_total_males,
    "Total_Total_Females" AS total_total_females,
    "Total_Chinese_Total" AS total_chinese_total,
    "Total_Chinese_Males" AS total_chinese_males,
    "Total_Chinese_Females" AS total_chinese_females,
    "Total_Malays_Total" AS total_malays_total,
    "Total_Malays_Males" AS total_malays_males,
    "Total_Malays_Females" AS total_malays_females,
    "Total_Indians_Total" AS total_indians_total,
    "Total_Indians_Males" AS total_indians_males,
    "Total_Indians_Females" AS total_indians_females,
    "Total_Others_Total" AS total_others_total,
    "Total_Others_Males" AS total_others_males,
    "Total_Others_Females" AS total_others_females,
    "ChangedJobDuringLast2Years_Total_Total" AS changedjobduringlast2years_total_total,
    "ChangedJobDuringLast2Years_Total_Males" AS changedjobduringlast2years_total_males,
    "ChangedJobDuringLast2Years_Total_Females" AS changedjobduringlast2years_total_females,
    "ChangedJobDuringLast2Years_Chinese_Total" AS changedjobduringlast2years_chinese_total,
    "ChangedJobDuringLast2Years_Chinese_Males" AS changedjobduringlast2years_chinese_males,
    "ChangedJobDuringLast2Years_Chinese_Females" AS changedjobduringlast2years_chinese_females,
    "ChangedJobDuringLast2Years_Malays_Total" AS changedjobduringlast2years_malays_total,
    "ChangedJobDuringLast2Years_Malays_Males" AS changedjobduringlast2years_malays_males,
    "ChangedJobDuringLast2Years_Malays_Females" AS changedjobduringlast2years_malays_females,
    "ChangedJobDuringLast2Years_Indians_Total" AS changedjobduringlast2years_indians_total,
    "ChangedJobDuringLast2Years_Indians_Males" AS changedjobduringlast2years_indians_males,
    "ChangedJobDuringLast2Years_Indians_Females" AS changedjobduringlast2years_indians_females,
    "ChangedJobDuringLast2Years_Others_Total" AS changedjobduringlast2years_others_total,
    "ChangedJobDuringLast2Years_Others_Males" AS changedjobduringlast2years_others_males,
    "ChangedJobDuringLast2Years_Others_Females" AS changedjobduringlast2years_others_females,
    "DidNotChangeJobDuringLast2Years_Total_Total" AS didnotchangejobduringlast2years_total_total,
    "DidNotChangeJobDuringLast2Years_Total_Males" AS didnotchangejobduringlast2years_total_males,
    "DidNotChangeJobDuringLast2Years_Total_Females" AS didnotchangejobduringlast2years_total_females,
    "DidNotChangeJobDuringLast2Years_Chinese_Total" AS didnotchangejobduringlast2years_chinese_total,
    "DidNotChangeJobDuringLast2Years_Chinese_Males" AS didnotchangejobduringlast2years_chinese_males,
    "DidNotChangeJobDuringLast2Years_Chinese_Females" AS didnotchangejobduringlast2years_chinese_females,
    "DidNotChangeJobDuringLast2Years_Malays_Total" AS didnotchangejobduringlast2years_malays_total,
    "DidNotChangeJobDuringLast2Years_Malays_Males" AS didnotchangejobduringlast2years_malays_males,
    "DidNotChangeJobDuringLast2Years_Malays_Females" AS didnotchangejobduringlast2years_malays_females,
    "DidNotChangeJobDuringLast2Years_Indians_Total" AS didnotchangejobduringlast2years_indians_total,
    "DidNotChangeJobDuringLast2Years_Indians_Males" AS didnotchangejobduringlast2years_indians_males,
    "DidNotChangeJobDuringLast2Years_Indians_Females" AS didnotchangejobduringlast2years_indians_females,
    "DidNotChangeJobDuringLast2Years_Others_Total" AS didnotchangejobduringlast2years_others_total,
    "DidNotChangeJobDuringLast2Years_Others_Males" AS didnotchangejobduringlast2years_others_males,
    "DidNotChangeJobDuringLast2Years_Others_Females" AS didnotchangejobduringlast2years_others_females
FROM "sg-data-d-5fbccd74a6f0083c5bbd81131bcab605"
