-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Wide source table with many measured attributes or category columns; avoid summing across columns without checking the upstream definition.
SELECT
    "Number" AS number,
    "Total_Total" AS total_total,
    "Total_HDBDwellings_Total" AS total_hdbdwellings_total,
    "Total_HDBDwellings_1_and2_RoomFlats1" AS total_hdbdwellings_1_and2_roomflats1,
    "Total_HDBDwellings_3_RoomFlats" AS total_hdbdwellings_3_roomflats,
    "Total_HDBDwellings_4_RoomFlats" AS total_hdbdwellings_4_roomflats,
    "Total_HDBDwellings_5_RoomandExecutiveFlats" AS total_hdbdwellings_5_roomandexecutiveflats,
    "Total_CondominiumsandOtherApartments" AS total_condominiumsandotherapartments,
    "Total_LandedProperties" AS total_landedproperties,
    "Total_Others" AS total_others,
    "Chinese_Total" AS chinese_total,
    "Chinese_HDBDwellings_Total" AS chinese_hdbdwellings_total,
    "Chinese_HDBDwellings_1_and2_RoomFlats1" AS chinese_hdbdwellings_1_and2_roomflats1,
    "Chinese_HDBDwellings_3_RoomFlats" AS chinese_hdbdwellings_3_roomflats,
    "Chinese_HDBDwellings_4_RoomFlats" AS chinese_hdbdwellings_4_roomflats,
    "Chinese_HDBDwellings_5_RoomandExecutiveFlats" AS chinese_hdbdwellings_5_roomandexecutiveflats,
    "Chinese_CondominiumsandOtherApartments" AS chinese_condominiumsandotherapartments,
    "Chinese_LandedProperties" AS chinese_landedproperties,
    "Chinese_Others" AS chinese_others,
    "Malays_Total" AS malays_total,
    "Malays_HDBDwellings_Total" AS malays_hdbdwellings_total,
    "Malays_HDBDwellings_1_and2_RoomFlats1" AS malays_hdbdwellings_1_and2_roomflats1,
    "Malays_HDBDwellings_3_RoomFlats" AS malays_hdbdwellings_3_roomflats,
    "Malays_HDBDwellings_4_RoomFlats" AS malays_hdbdwellings_4_roomflats,
    "Malays_HDBDwellings_5_RoomandExecutiveFlats" AS malays_hdbdwellings_5_roomandexecutiveflats,
    "Malays_CondominiumsandOtherApartments" AS malays_condominiumsandotherapartments,
    "Malays_LandedProperties" AS malays_landedproperties,
    "Malays_Others" AS malays_others,
    "Indians_Total" AS indians_total,
    "Indians_HDBDwellings_Total" AS indians_hdbdwellings_total,
    "Indians_HDBDwellings_1_and2_RoomFlats1" AS indians_hdbdwellings_1_and2_roomflats1,
    "Indians_HDBDwellings_3_RoomFlats" AS indians_hdbdwellings_3_roomflats,
    "Indians_HDBDwellings_4_RoomFlats" AS indians_hdbdwellings_4_roomflats,
    "Indians_HDBDwellings_5_RoomandExecutiveFlats" AS indians_hdbdwellings_5_roomandexecutiveflats,
    "Indians_CondominiumsandOtherApartments" AS indians_condominiumsandotherapartments,
    "Indians_LandedProperties" AS indians_landedproperties,
    "Indians_Others" AS indians_others,
    "Others_Total" AS others_total,
    "Others_HDBDwellings_Total" AS others_hdbdwellings_total,
    "Others_HDBDwellings_1_and2_RoomFlats1" AS others_hdbdwellings_1_and2_roomflats1,
    "Others_HDBDwellings_3_RoomFlats" AS others_hdbdwellings_3_roomflats,
    "Others_HDBDwellings_4_RoomFlats" AS others_hdbdwellings_4_roomflats,
    "Others_HDBDwellings_5_RoomandExecutiveFlats" AS others_hdbdwellings_5_roomandexecutiveflats,
    "Others_CondominiumsandOtherApartments" AS others_condominiumsandotherapartments,
    "Others_LandedProperties" AS others_landedproperties,
    "Others_Others" AS others_others
FROM "sg-data-d-d4b64224cbd495be262151787818be05"
