-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Wide source table with many measured attributes or category columns; avoid summing across columns without checking the upstream definition.
SELECT
    "Thousands" AS thousands,
    "Total_Total" AS total_total,
    "Total_NumberOfChildrenBorn_None" AS total_numberofchildrenborn_none,
    "Total_NumberOfChildrenBorn_1Child" AS total_numberofchildrenborn_1child,
    "Total_NumberOfChildrenBorn_2Children" AS total_numberofchildrenborn_2children,
    "Total_NumberOfChildrenBorn_3Children" AS total_numberofchildrenborn_3children,
    "Total_NumberOfChildrenBorn_4Children" AS total_numberofchildrenborn_4children,
    "Total_NumberOfChildrenBorn_5OrMoreChildren" AS total_numberofchildrenborn_5ormorechildren,
    "BelowSecondary_Total" AS belowsecondary_total,
    "BelowSecondary_NumberOfChildrenBorn_None" AS belowsecondary_numberofchildrenborn_none,
    "BelowSecondary_NumberOfChildrenBorn_1Child" AS belowsecondary_numberofchildrenborn_1child,
    "BelowSecondary_NumberOfChildrenBorn_2Children" AS belowsecondary_numberofchildrenborn_2children,
    "BelowSecondary_NumberOfChildrenBorn_3Children" AS belowsecondary_numberofchildrenborn_3children,
    "BelowSecondary_NumberOfChildrenBorn_4Children" AS belowsecondary_numberofchildrenborn_4children,
    "BelowSecondary_NumberOfChildrenBorn_5OrMoreChildren" AS belowsecondary_numberofchildrenborn_5ormorechildren,
    "Secondary_Total" AS secondary_total,
    "Secondary_NumberOfChildrenBorn_None" AS secondary_numberofchildrenborn_none,
    "Secondary_NumberOfChildrenBorn_1Child" AS secondary_numberofchildrenborn_1child,
    "Secondary_NumberOfChildrenBorn_2Children" AS secondary_numberofchildrenborn_2children,
    "Secondary_NumberOfChildrenBorn_3Children" AS secondary_numberofchildrenborn_3children,
    "Secondary_NumberOfChildrenBorn_4Children" AS secondary_numberofchildrenborn_4children,
    "Secondary_NumberOfChildrenBorn_5OrMoreChildren" AS secondary_numberofchildrenborn_5ormorechildren,
    "Post_Secondary_Non_Tertiary_Total" AS post_secondary_non_tertiary_total,
    "Post_Secondary_Non_Tertiary_NumberOfChildrenBorn_None" AS post_secondary_non_tertiary_numberofchildrenborn_none,
    "Post_Secondary_Non_Tertiary_NumberOfChildrenBorn_1Child" AS post_secondary_non_tertiary_numberofchildrenborn_1child,
    "Post_Secondary_Non_Tertiary_NumberOfChildrenBorn_2Children" AS post_secondary_non_tertiary_numberofchildrenborn_2children,
    "Post_Secondary_Non_Tertiary_NumberOfChildrenBorn_3Children" AS post_secondary_non_tertiary_numberofchildrenborn_3children,
    "Post_Secondary_Non_Tertiary_NumberOfChildrenBorn_4Children" AS post_secondary_non_tertiary_numberofchildrenborn_4children,
    "Post_Secondary_Non_Tertiary_NumberOfChildrenBorn_5OrMoreChildre" AS post_secondary_non_tertiary_numberofchildrenborn_5ormorechildre,
    "Diploma1_andProfessionalQualification_Total" AS diploma1_andprofessionalqualification_total,
    "Diploma1_andProfessionalQualification_NumberOfChildrenBorn_None" AS diploma1_andprofessionalqualification_numberofchildrenborn_none,
    "Diploma1_andProfessionalQualification_NumberOfChildrenBorn_1Chi" AS diploma1_andprofessionalqualification_numberofchildrenborn_1chi,
    "Diploma1_andProfessionalQualification_NumberOfChildrenBorn_2Chi" AS diploma1_andprofessionalqualification_numberofchildrenborn_2chi,
    "Diploma1_andProfessionalQualification_NumberOfChildrenBorn_3Chi" AS diploma1_andprofessionalqualification_numberofchildrenborn_3chi,
    "Diploma1_andProfessionalQualification_NumberOfChildrenBorn_4Chi" AS diploma1_andprofessionalqualification_numberofchildrenborn_4chi,
    "Diploma1_andProfessionalQualification_NumberOfChildrenBorn_5OrM" AS diploma1_andprofessionalqualification_numberofchildrenborn_5orm,
    "University_Total" AS university_total,
    "University_NumberOfChildrenBorn_None" AS university_numberofchildrenborn_none,
    "University_NumberOfChildrenBorn_1Child" AS university_numberofchildrenborn_1child,
    "University_NumberOfChildrenBorn_2Children" AS university_numberofchildrenborn_2children,
    "University_NumberOfChildrenBorn_3Children" AS university_numberofchildrenborn_3children,
    "University_NumberOfChildrenBorn_4Children" AS university_numberofchildrenborn_4children,
    "University_NumberOfChildrenBorn_5OrMoreChildren" AS university_numberofchildrenborn_5ormorechildren
FROM "sg-data-d-0b0c61560806d8dbab9fd66b8d29aad9"
