SELECT
    cycle,
    cand_id,
    cand_name,
    cand_pty_aff                              AS cand_party,
    can_office                                AS cand_office,
    can_office_state                          AS cand_office_state,
    can_office_dis                            AS cand_office_district,
    spe_id                                    AS spender_cmte_id,
    spe_nam                                   AS spender_name,
    sup_opp                                   AS support_oppose,
    ele_type                                  AS election_type,
    TRY_CAST(exp_amo AS DOUBLE)               AS amount,
    TRY_STRPTIME(exp_date, '%m/%d/%Y')::DATE  AS expenditure_date,
    TRY_CAST(agg_amo AS DOUBLE)               AS aggregate_amount,
    pur                                       AS purpose,
    pay                                       AS payee,
    TRY_CAST(file_num AS BIGINT)              AS file_num,
    tran_id,
    image_num,
    amndt_ind                                 AS amendment_ind,
    TRY_STRPTIME(receipt_dat, '%m/%d/%Y')::DATE AS receipt_date,
    TRY_CAST(fec_election_yr AS INTEGER)      AS fec_election_yr,
    TRY_STRPTIME(dissem_dt, '%m/%d/%Y')::DATE AS dissemination_date
FROM "fec-independent-expenditures"
WHERE spe_id IS NOT NULL AND spe_id <> ''
