SELECT
    CAST(id AS BIGINT) AS id,
    iso3,
    country,
    geographical_region,
    figure_cause,
    CAST(year AS INTEGER) AS year,
    figure_category,
    figure_unit,
    CAST(reported_figures AS BIGINT) AS reported_figures,
    CAST(total_figures AS BIGINT) AS total_figures,
    violence_type,
    TRY_CAST(start_date AS DATE) AS start_date,
    start_date_accuracy,
    TRY_CAST(end_date AS DATE) AS end_date,
    end_date_accuracy,
    publishers,
    sources,
    sources_type,
    CAST(event_id AS BIGINT) AS event_id,
    event_name,
    event_cause,
    event_main_trigger,
    TRY_CAST(event_start_date AS DATE) AS event_start_date,
    TRY_CAST(event_end_date AS DATE) AS event_end_date,
    is_housing_destruction,
    event_codes,
    locations_name,
    locations_accuracy,
    locations_type,
    displacement_occurred,
    CAST(longitude AS DOUBLE) AS longitude,
    CAST(latitude AS DOUBLE) AS latitude,
    geometry_type
FROM "idmc-disaggregations"
WHERE id IS NOT NULL
