-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: The raw payload mixes frequencies: 60 rows carry `period` in Q1..Q4 (2010-2024) and 44 rows carry `period = 'Annual'` (1981-2024). Only the quarterly rows belong to this table; the published transform filters on them.
-- caution: Values are REAL (constant 2010 basic prices) naira in billions, even though the upstream column names say `gdPatCurrentBasicPrices` / `gdPatCurrentMarketPrices` — the `Current` in those upstream names is a copy-paste artefact of the nominal endpoint and does not describe this table.
-- caution: Quarterly values are the output of that quarter alone (not year-to-date) and are NOT seasonally adjusted, so quarter-on-quarter changes are dominated by Nigeria's agricultural season; compare a quarter with the same quarter of the previous year.
-- caution: The activity columns are a nested hierarchy, not a flat list: `agriculture`, `industry` and `services` each sum their own sub-sectors, and the basic-prices total is the sum of the three. Summing every activity column in a row multiply-counts the sub-sectors.
SELECT
    "id",
    CAST("tyear" AS BIGINT) AS tyear,
    "period",
    CAST("agriculture" AS DOUBLE) AS agriculture,
    CAST("cropProduction" AS DOUBLE) AS cropproduction,
    CAST("livestock" AS DOUBLE) AS livestock,
    CAST("forestry" AS DOUBLE) AS forestry,
    CAST("fishing" AS DOUBLE) AS fishing,
    CAST("industry" AS DOUBLE) AS industry,
    CAST("miningAndQuarrying" AS DOUBLE) AS miningandquarrying,
    CAST("crudePetroleumAndNaturalGas" AS DOUBLE) AS crudepetroleumandnaturalgas,
    CAST("coalMining" AS DOUBLE) AS coalmining,
    CAST("metalOres" AS DOUBLE) AS metalores,
    CAST("quarryingAndOtherMinerals" AS DOUBLE) AS quarryingandotherminerals,
    CAST("manufacturing" AS DOUBLE) AS manufacturing,
    CAST("oilRefining" AS DOUBLE) AS oilrefining,
    CAST("cement" AS DOUBLE) AS cement,
    CAST("foodBeverageAndTobacco" AS DOUBLE) AS foodbeverageandtobacco,
    CAST("textileApparelAndFootwear" AS DOUBLE) AS textileapparelandfootwear,
    CAST("woodAndWoodProducts" AS DOUBLE) AS woodandwoodproducts,
    CAST("pulpPaperAndPaperProducts" AS DOUBLE) AS pulppaperandpaperproducts,
    CAST("chemicalAndPharmaceuticalProducts" AS DOUBLE) AS chemicalandpharmaceuticalproducts,
    CAST("nonMetallicProducts" AS DOUBLE) AS nonmetallicproducts,
    CAST("plasticAndRubberProducts" AS DOUBLE) AS plasticandrubberproducts,
    CAST("electricalAndElectronics" AS DOUBLE) AS electricalandelectronics,
    CAST("basicMetalIronAndSteel" AS DOUBLE) AS basicmetalironandsteel,
    CAST("motorVehiclesAndAssembly" AS DOUBLE) AS motorvehiclesandassembly,
    CAST("otherManufacturing" AS DOUBLE) AS othermanufacturing,
    CAST("electricityGasSteamAndAirCon" AS DOUBLE) AS electricitygassteamandaircon,
    CAST("waterSupplySewageWaste" AS DOUBLE) AS watersupplysewagewaste,
    CAST("construction" AS DOUBLE) AS construction,
    CAST("services" AS DOUBLE) AS services,
    CAST("trade" AS DOUBLE) AS trade,
    CAST("accommodationAndFoodServices" AS DOUBLE) AS accommodationandfoodservices,
    CAST("transportationAndStorage" AS DOUBLE) AS transportationandstorage,
    CAST("roadTransport" AS DOUBLE) AS roadtransport,
    CAST("railTransportAndPipelines" AS DOUBLE) AS railtransportandpipelines,
    CAST("waterTransport" AS DOUBLE) AS watertransport,
    CAST("airTransport" AS DOUBLE) AS airtransport,
    CAST("transportServices" AS DOUBLE) AS transportservices,
    CAST("postAndCourierServices" AS DOUBLE) AS postandcourierservices,
    CAST("informationAndCommunication" AS DOUBLE) AS informationandcommunication,
    CAST("telecommunicationsAndInformationServices" AS DOUBLE) AS telecommunicationsandinformationservices,
    CAST("publishing" AS DOUBLE) AS publishing,
    CAST("motionPicturesSoundRecordingAndMusicProduction" AS DOUBLE) AS motionpicturessoundrecordingandmusicproduction,
    CAST("broadcasting" AS DOUBLE) AS broadcasting,
    CAST("artsEntertainmentAndRecreation" AS DOUBLE) AS artsentertainmentandrecreation,
    CAST("financeAndInsurance" AS DOUBLE) AS financeandinsurance,
    CAST("financialInstitutions" AS DOUBLE) AS financialinstitutions,
    CAST("insurance" AS DOUBLE) AS insurance,
    CAST("realEstate" AS DOUBLE) AS realestate,
    CAST("professionalScientificAndTechnicalServices" AS DOUBLE) AS professionalscientificandtechnicalservices,
    CAST("administrativeAndSupportServicesBusinessServices" AS DOUBLE) AS administrativeandsupportservicesbusinessservices,
    CAST("publicAdministration" AS DOUBLE) AS publicadministration,
    CAST("education" AS DOUBLE) AS education,
    CAST("humanHealthAndSocialServices" AS DOUBLE) AS humanhealthandsocialservices,
    CAST("otherServices" AS DOUBLE) AS otherservices,
    CAST("gdPatCurrentBasicPrices" AS DOUBLE) AS gdpatcurrentbasicprices,
    CAST("netTaxesOnProducts" AS DOUBLE) AS nettaxesonproducts,
    CAST("gdPatCurrentMarketPrices" AS DOUBLE) AS gdpatcurrentmarketprices
FROM "central-bank-of-nigeria-real-gdp-quarterly"
