SELECT
            make_date(TRY_CAST(year AS INTEGER), 12, 31) AS "date",
            TRY_CAST(year AS INTEGER) AS "year",
            TRY_CAST(NULLIF(CAST("extReserve" AS VARCHAR), '') AS DOUBLE) AS "extReserve",
            TRY_CAST(NULLIF(CAST("holdingsSDR" AS VARCHAR), '') AS DOUBLE) AS "holdingsSDR",
            TRY_CAST(NULLIF(CAST("fedGovtSec" AS VARCHAR), '') AS DOUBLE) AS "fedGovtSec",
            TRY_CAST(NULLIF(CAST("rediscount" AS VARCHAR), '') AS DOUBLE) AS "rediscount",
            TRY_CAST(NULLIF(CAST("otherAss" AS VARCHAR), '') AS DOUBLE) AS "otherAss",
            TRY_CAST(NULLIF(CAST("otherSec" AS VARCHAR), '') AS DOUBLE) AS "otherSec",
            TRY_CAST(NULLIF(CAST("exDiff" AS VARCHAR), '') AS DOUBLE) AS "exDiff",
            TRY_CAST(NULLIF(CAST("fixedAss" AS VARCHAR), '') AS DOUBLE) AS "fixedAss",
            TRY_CAST(NULLIF(CAST("totalAss" AS VARCHAR), '') AS DOUBLE) AS "totalAss",
            TRY_CAST(NULLIF(CAST("deposit" AS VARCHAR), '') AS DOUBLE) AS "deposit",
            TRY_CAST(NULLIF(CAST("cbnInst" AS VARCHAR), '') AS DOUBLE) AS "cbnInst",
            TRY_CAST(NULLIF(CAST("cinC" AS VARCHAR), '') AS DOUBLE) AS "cinC",
            TRY_CAST(NULLIF(CAST("imfsdr" AS VARCHAR), '') AS DOUBLE) AS "imfsdr",
            TRY_CAST(NULLIF(CAST("tradeDebt" AS VARCHAR), '') AS DOUBLE) AS "tradeDebt",
            TRY_CAST(NULLIF(CAST("otherFore" AS VARCHAR), '') AS DOUBLE) AS "otherFore",
            TRY_CAST(NULLIF(CAST("otherLia" AS VARCHAR), '') AS DOUBLE) AS "otherLia",
            TRY_CAST(NULLIF(CAST("subLia" AS VARCHAR), '') AS DOUBLE) AS "subLia",
            TRY_CAST(NULLIF(CAST("shareCap" AS VARCHAR), '') AS DOUBLE) AS "shareCap",
            TRY_CAST(NULLIF(CAST("genReserve" AS VARCHAR), '') AS DOUBLE) AS "genReserve",
            TRY_CAST(NULLIF(CAST("assetsRev" AS VARCHAR), '') AS DOUBLE) AS "assetsRev",
            TRY_CAST(NULLIF(CAST("foreignC" AS VARCHAR), '') AS DOUBLE) AS "foreignC",
            TRY_CAST(NULLIF(CAST("resFundInv" AS VARCHAR), '') AS DOUBLE) AS "resFundInv",
            TRY_CAST(NULLIF(CAST("subCapRes" AS VARCHAR), '') AS DOUBLE) AS "subCapRes",
            TRY_CAST(NULLIF(CAST("totalLia" AS VARCHAR), '') AS DOUBLE) AS "totalLia",
            TRY_CAST(NULLIF(CAST("contingent" AS VARCHAR), '') AS DOUBLE) AS "contingent",
            TRY_CAST(NULLIF(CAST("totalIncome" AS VARCHAR), '') AS DOUBLE) AS "totalIncome",
            TRY_CAST(NULLIF(CAST("provisionforDebt" AS VARCHAR), '') AS DOUBLE) AS "provisionforDebt",
            TRY_CAST(NULLIF(CAST("operatnExp" AS VARCHAR), '') AS DOUBLE) AS "operatnExp",
            TRY_CAST(NULLIF(CAST("provision" AS VARCHAR), '') AS DOUBLE) AS "provision",
            TRY_CAST(NULLIF(CAST("exceptional" AS VARCHAR), '') AS DOUBLE) AS "exceptional",
            TRY_CAST(NULLIF(CAST("surplus" AS VARCHAR), '') AS DOUBLE) AS "surplus",
            TRY_CAST(NULLIF(CAST("appro" AS VARCHAR), '') AS DOUBLE) AS "appro",
            TRY_CAST(NULLIF(CAST("transfer" AS VARCHAR), '') AS DOUBLE) AS "transfer",
            TRY_CAST(NULLIF(CAST("surplusFGN" AS VARCHAR), '') AS DOUBLE) AS "surplusFGN",
            TRY_CAST(NULLIF(CAST("totalAppro" AS VARCHAR), '') AS DOUBLE) AS "totalAppro"
        FROM "central-bank-of-nigeria-getallfiveyearstatement"
