SELECT
            try_strptime(CAST("recDate" AS VARCHAR), '%d/%m/%Y')::DATE AS "date",
            TRY_CAST(NULLIF(CAST("opeBal" AS VARCHAR), '') AS DOUBLE) AS "opeBal",
            TRY_CAST(NULLIF(CAST("rediscBills" AS VARCHAR), '') AS DOUBLE) AS "rediscBills",
            TRY_CAST(NULLIF(CAST("slFacility" AS VARCHAR), '') AS DOUBLE) AS "slFacility",
            TRY_CAST(NULLIF(CAST("sdFacility" AS VARCHAR), '') AS DOUBLE) AS "sdFacility",
            TRY_CAST(NULLIF(CAST("repo" AS VARCHAR), '') AS DOUBLE) AS "repo",
            TRY_CAST(NULLIF(CAST("revRepo" AS VARCHAR), '') AS DOUBLE) AS "revRepo",
            TRY_CAST(NULLIF(CAST("omoSales" AS VARCHAR), '') AS DOUBLE) AS "omoSales",
            TRY_CAST(NULLIF(CAST("omoRepay" AS VARCHAR), '') AS DOUBLE) AS "omoRepay",
            TRY_CAST(NULLIF(CAST("pmSales" AS VARCHAR), '') AS DOUBLE) AS "pmSales",
            TRY_CAST(NULLIF(CAST("pmRepay" AS VARCHAR), '') AS DOUBLE) AS "pmRepay",
            TRY_CAST(NULLIF(CAST("crr" AS VARCHAR), '') AS DOUBLE) AS "crr",
            TRY_CAST(NULLIF(CAST("netWdas" AS VARCHAR), '') AS DOUBLE) AS "netWdas",
            TRY_CAST(NULLIF(CAST("statAlloc" AS VARCHAR), '') AS DOUBLE) AS "statAlloc",
            TRY_CAST(NULLIF(CAST("jvCash" AS VARCHAR), '') AS DOUBLE) AS "jvCash",
            TRY_CAST(NULLIF(CAST("netClr" AS VARCHAR), '') AS DOUBLE) AS "netClr",
            TRY_CAST(NULLIF(CAST("ndicPrem" AS VARCHAR), '') AS DOUBLE) AS "ndicPrem",
            TRY_CAST(NULLIF(CAST("oMajor" AS VARCHAR), '') AS DOUBLE) AS "oMajor"
        FROM "central-bank-of-nigeria-getallfinancialdata"
