-- the quarterly slice of the shared GetAllNominalGDP payload (2010-2024); the dedicated GetAllYears* endpoints are empty shells
-- `id` is dropped: it numbers rows across both frequencies and means nothing after the split
-- `gdPatCurrent{Basic,Market}Prices` renamed `gdp_at_{basic,market}_prices`
SELECT
    CAST("period_start_iso" AS DATE) AS quarter_start,
    CAST("tyear" AS BIGINT) AS year,
    NULLIF(TRIM("period"), '') AS quarter,
    TRY_CAST(NULLIF(TRIM("agriculture"), '') AS DOUBLE) AS agriculture,
    TRY_CAST(NULLIF(TRIM("cropProduction"), '') AS DOUBLE) AS crop_production,
    TRY_CAST(NULLIF(TRIM("livestock"), '') AS DOUBLE) AS livestock,
    TRY_CAST(NULLIF(TRIM("forestry"), '') AS DOUBLE) AS forestry,
    TRY_CAST(NULLIF(TRIM("fishing"), '') AS DOUBLE) AS fishing,
    TRY_CAST(NULLIF(TRIM("industry"), '') AS DOUBLE) AS industry,
    TRY_CAST(NULLIF(TRIM("miningAndQuarrying"), '') AS DOUBLE) AS mining_and_quarrying,
    TRY_CAST(NULLIF(TRIM("crudePetroleumAndNaturalGas"), '') AS DOUBLE) AS crude_petroleum_and_natural_gas,
    TRY_CAST(NULLIF(TRIM("coalMining"), '') AS DOUBLE) AS coal_mining,
    TRY_CAST(NULLIF(TRIM("metalOres"), '') AS DOUBLE) AS metal_ores,
    TRY_CAST(NULLIF(TRIM("quarryingAndOtherMinerals"), '') AS DOUBLE) AS quarrying_and_other_minerals,
    TRY_CAST(NULLIF(TRIM("manufacturing"), '') AS DOUBLE) AS manufacturing,
    TRY_CAST(NULLIF(TRIM("oilRefining"), '') AS DOUBLE) AS oil_refining,
    TRY_CAST(NULLIF(TRIM("cement"), '') AS DOUBLE) AS cement,
    TRY_CAST(NULLIF(TRIM("foodBeverageAndTobacco"), '') AS DOUBLE) AS food_beverage_and_tobacco,
    TRY_CAST(NULLIF(TRIM("textileApparelAndFootwear"), '') AS DOUBLE) AS textile_apparel_and_footwear,
    TRY_CAST(NULLIF(TRIM("woodAndWoodProducts"), '') AS DOUBLE) AS wood_and_wood_products,
    TRY_CAST(NULLIF(TRIM("pulpPaperAndPaperProducts"), '') AS DOUBLE) AS pulp_paper_and_paper_products,
    TRY_CAST(NULLIF(TRIM("chemicalAndPharmaceuticalProducts"), '') AS DOUBLE) AS chemical_and_pharmaceutical_products,
    TRY_CAST(NULLIF(TRIM("nonMetallicProducts"), '') AS DOUBLE) AS non_metallic_products,
    TRY_CAST(NULLIF(TRIM("plasticAndRubberProducts"), '') AS DOUBLE) AS plastic_and_rubber_products,
    TRY_CAST(NULLIF(TRIM("electricalAndElectronics"), '') AS DOUBLE) AS electrical_and_electronics,
    TRY_CAST(NULLIF(TRIM("basicMetalIronAndSteel"), '') AS DOUBLE) AS basic_metal_iron_and_steel,
    TRY_CAST(NULLIF(TRIM("motorVehiclesAndAssembly"), '') AS DOUBLE) AS motor_vehicles_and_assembly,
    TRY_CAST(NULLIF(TRIM("otherManufacturing"), '') AS DOUBLE) AS other_manufacturing,
    TRY_CAST(NULLIF(TRIM("electricityGasSteamAndAirCon"), '') AS DOUBLE) AS electricity_gas_steam_and_air_conditioning,
    TRY_CAST(NULLIF(TRIM("waterSupplySewageWaste"), '') AS DOUBLE) AS water_supply_sewerage_and_waste,
    TRY_CAST(NULLIF(TRIM("construction"), '') AS DOUBLE) AS construction,
    TRY_CAST(NULLIF(TRIM("services"), '') AS DOUBLE) AS services,
    TRY_CAST(NULLIF(TRIM("trade"), '') AS DOUBLE) AS trade,
    TRY_CAST(NULLIF(TRIM("accommodationAndFoodServices"), '') AS DOUBLE) AS accommodation_and_food_services,
    TRY_CAST(NULLIF(TRIM("transportationAndStorage"), '') AS DOUBLE) AS transportation_and_storage,
    TRY_CAST(NULLIF(TRIM("roadTransport"), '') AS DOUBLE) AS road_transport,
    TRY_CAST(NULLIF(TRIM("railTransportAndPipelines"), '') AS DOUBLE) AS rail_transport_and_pipelines,
    TRY_CAST(NULLIF(TRIM("waterTransport"), '') AS DOUBLE) AS water_transport,
    TRY_CAST(NULLIF(TRIM("airTransport"), '') AS DOUBLE) AS air_transport,
    TRY_CAST(NULLIF(TRIM("transportServices"), '') AS DOUBLE) AS transport_services,
    TRY_CAST(NULLIF(TRIM("postAndCourierServices"), '') AS DOUBLE) AS post_and_courier_services,
    TRY_CAST(NULLIF(TRIM("informationAndCommunication"), '') AS DOUBLE) AS information_and_communication,
    TRY_CAST(NULLIF(TRIM("telecommunicationsAndInformationServices"), '') AS DOUBLE) AS telecommunications_and_information_services,
    TRY_CAST(NULLIF(TRIM("publishing"), '') AS DOUBLE) AS publishing,
    TRY_CAST(NULLIF(TRIM("motionPicturesSoundRecordingAndMusicProduction"), '') AS DOUBLE) AS motion_pictures_sound_recording_and_music_production,
    TRY_CAST(NULLIF(TRIM("broadcasting"), '') AS DOUBLE) AS broadcasting,
    TRY_CAST(NULLIF(TRIM("artsEntertainmentAndRecreation"), '') AS DOUBLE) AS arts_entertainment_and_recreation,
    TRY_CAST(NULLIF(TRIM("financeAndInsurance"), '') AS DOUBLE) AS finance_and_insurance,
    TRY_CAST(NULLIF(TRIM("financialInstitutions"), '') AS DOUBLE) AS financial_institutions,
    TRY_CAST(NULLIF(TRIM("insurance"), '') AS DOUBLE) AS insurance,
    TRY_CAST(NULLIF(TRIM("realEstate"), '') AS DOUBLE) AS real_estate,
    TRY_CAST(NULLIF(TRIM("professionalScientificAndTechnicalServices"), '') AS DOUBLE) AS professional_scientific_and_technical_services,
    TRY_CAST(NULLIF(TRIM("administrativeAndSupportServicesBusinessServices"), '') AS DOUBLE) AS administrative_and_support_services,
    TRY_CAST(NULLIF(TRIM("publicAdministration"), '') AS DOUBLE) AS public_administration,
    TRY_CAST(NULLIF(TRIM("education"), '') AS DOUBLE) AS education,
    TRY_CAST(NULLIF(TRIM("humanHealthAndSocialServices"), '') AS DOUBLE) AS human_health_and_social_services,
    TRY_CAST(NULLIF(TRIM("otherServices"), '') AS DOUBLE) AS other_services,
    TRY_CAST(NULLIF(TRIM("gdPatCurrentBasicPrices"), '') AS DOUBLE) AS gdp_at_basic_prices,
    TRY_CAST(NULLIF(TRIM("netTaxesOnProducts"), '') AS DOUBLE) AS net_taxes_on_products,
    TRY_CAST(NULLIF(TRIM("gdPatCurrentMarketPrices"), '') AS DOUBLE) AS gdp_at_market_prices
FROM "central-bank-of-nigeria-nominal-gdp-quarterly"
WHERE "period" <> 'Annual'
