SELECT
            CASE WHEN TRY_CAST(tmonth AS INTEGER) BETWEEN 1 AND 12 THEN make_date(TRY_CAST(tyear AS INTEGER), TRY_CAST(tmonth AS INTEGER), 1) WHEN TRY_CAST(tyear AS INTEGER) BETWEEN 1900 AND 2100 THEN make_date(TRY_CAST(tyear AS INTEGER), 12, 31) ELSE NULL END AS "date",
            NULLIF(CAST("period" AS VARCHAR), '') AS "period",
            TRY_CAST(NULLIF(CAST("moneySupply_M3" AS VARCHAR), '') AS DOUBLE) AS "moneySupply_M3",
            TRY_CAST(NULLIF(CAST("cbnBills" AS VARCHAR), '') AS DOUBLE) AS "cbnBills",
            TRY_CAST(NULLIF(CAST("moneySupply_M2" AS VARCHAR), '') AS DOUBLE) AS "moneySupply_M2",
            TRY_CAST(NULLIF(CAST("quasiMoney" AS VARCHAR), '') AS DOUBLE) AS "quasiMoney",
            TRY_CAST(NULLIF(CAST("narrowMoney" AS VARCHAR), '') AS DOUBLE) AS "narrowMoney",
            TRY_CAST(NULLIF(CAST("currencyOutsideBanks" AS VARCHAR), '') AS DOUBLE) AS "currencyOutsideBanks",
            TRY_CAST(NULLIF(CAST("demandDeposits" AS VARCHAR), '') AS DOUBLE) AS "demandDeposits",
            TRY_CAST(NULLIF(CAST("netForeignAssets" AS VARCHAR), '') AS DOUBLE) AS "netForeignAssets",
            TRY_CAST(NULLIF(CAST("netDomesticAssets" AS VARCHAR), '') AS DOUBLE) AS "netDomesticAssets",
            TRY_CAST(NULLIF(CAST("netDomesticCredit" AS VARCHAR), '') AS DOUBLE) AS "netDomesticCredit",
            TRY_CAST(NULLIF(CAST("creditToGovernment" AS VARCHAR), '') AS DOUBLE) AS "creditToGovernment",
            TRY_CAST(NULLIF(CAST("creditToGovernmentFed" AS VARCHAR), '') AS DOUBLE) AS "creditToGovernmentFed",
            TRY_CAST(NULLIF(CAST("mirrorAccounts" AS VARCHAR), '') AS DOUBLE) AS "mirrorAccounts",
            TRY_CAST(NULLIF(CAST("creditToPrivateSector" AS VARCHAR), '') AS DOUBLE) AS "creditToPrivateSector",
            TRY_CAST(NULLIF(CAST("otherAssetsNet" AS VARCHAR), '') AS DOUBLE) AS "otherAssetsNet",
            TRY_CAST(NULLIF(CAST("baseMoney" AS VARCHAR), '') AS DOUBLE) AS "baseMoney",
            TRY_CAST(NULLIF(CAST("currencyInCirculation" AS VARCHAR), '') AS DOUBLE) AS "currencyInCirculation",
            TRY_CAST(NULLIF(CAST("bankReserves" AS VARCHAR), '') AS DOUBLE) AS "bankReserves",
            TRY_CAST(NULLIF(CAST("specialInterventionReserves" AS VARCHAR), '') AS DOUBLE) AS "specialInterventionReserves"
        FROM "central-bank-of-nigeria-getallmoneyandcreditstats"
