-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Rows include multiple geographic levels, from countries and regions to local authorities; filter geography before aggregating across regions.
SELECT
    "region_slug",
    "region_name",
    strptime("ref_month", '%Y-%m')::DATE AS ref_month,
    "ref_date",
    "averagePrice" AS average_price,
    "averagePriceCash" AS average_price_cash,
    "averagePriceDetached" AS average_price_detached,
    "averagePriceExistingProperty" AS average_price_existing_property,
    "averagePriceFirstTimeBuyer" AS average_price_first_time_buyer,
    "averagePriceFlatMaisonette" AS average_price_flat_maisonette,
    "averagePriceFormerOwnerOccupier" AS average_price_former_owner_occupier,
    "averagePriceMortgage" AS average_price_mortgage,
    "averagePriceNewBuild" AS average_price_new_build,
    "averagePriceSA" AS average_price_sa,
    "averagePriceSemiDetached" AS average_price_semi_detached,
    "averagePriceTerraced" AS average_price_terraced,
    "housePriceIndex" AS house_price_index,
    "housePriceIndexCash" AS house_price_index_cash,
    "housePriceIndexDetached" AS house_price_index_detached,
    "housePriceIndexExistingProperty" AS house_price_index_existing_property,
    "housePriceIndexFirstTimeBuyer" AS house_price_index_first_time_buyer,
    "housePriceIndexFlatMaisonette" AS house_price_index_flat_maisonette,
    "housePriceIndexFormerOwnerOccupier" AS house_price_index_former_owner_occupier,
    "housePriceIndexMortgage" AS house_price_index_mortgage,
    "housePriceIndexNewBuild" AS house_price_index_new_build,
    "housePriceIndexSA" AS house_price_index_sa,
    "housePriceIndexSemiDetached" AS house_price_index_semi_detached,
    "housePriceIndexTerraced" AS house_price_index_terraced,
    "percentageAnnualChange" AS percentage_annual_change,
    "percentageAnnualChangeCash" AS percentage_annual_change_cash,
    "percentageAnnualChangeDetached" AS percentage_annual_change_detached,
    "percentageAnnualChangeExistingProperty" AS percentage_annual_change_existing_property,
    "percentageAnnualChangeFirstTimeBuyer" AS percentage_annual_change_first_time_buyer,
    "percentageAnnualChangeFlatMaisonette" AS percentage_annual_change_flat_maisonette,
    "percentageAnnualChangeFormerOwnerOccupier" AS percentage_annual_change_former_owner_occupier,
    "percentageAnnualChangeMortgage" AS percentage_annual_change_mortgage,
    "percentageAnnualChangeNewBuild" AS percentage_annual_change_new_build,
    "percentageAnnualChangeSemiDetached" AS percentage_annual_change_semi_detached,
    "percentageAnnualChangeTerraced" AS percentage_annual_change_terraced,
    "percentageChange" AS percentage_change,
    "percentageChangeCash" AS percentage_change_cash,
    "percentageChangeDetached" AS percentage_change_detached,
    "percentageChangeExistingProperty" AS percentage_change_existing_property,
    "percentageChangeFirstTimeBuyer" AS percentage_change_first_time_buyer,
    "percentageChangeFlatMaisonette" AS percentage_change_flat_maisonette,
    "percentageChangeFormerOwnerOccupier" AS percentage_change_former_owner_occupier,
    "percentageChangeMortgage" AS percentage_change_mortgage,
    "percentageChangeNewBuild" AS percentage_change_new_build,
    "percentageChangeSemiDetached" AS percentage_change_semi_detached,
    "percentageChangeTerraced" AS percentage_change_terraced,
    "salesVolume" AS sales_volume,
    "salesVolumeCash" AS sales_volume_cash,
    "salesVolumeExistingProperty" AS sales_volume_existing_property,
    "salesVolumeMortgage" AS sales_volume_mortgage,
    "salesVolumeNewBuild" AS sales_volume_new_build
FROM "hm-land-registry-ukhpi"
