-- WS_CBS_PUB: one row per (series_key, time_period) observation.
-- Raw already carries typed obs_value / period_start and split code+label
-- dimension columns, so this is a projection plus the missing-observation gate.
SELECT
    "series_key",
    "freq",
    "freq_label",
    "l_measure",
    "l_measure_label",
    "l_rep_cty",
    "l_rep_cty_label",
    "cbs_bank_type",
    "cbs_bank_type_label",
    "cbs_basis",
    "cbs_basis_label",
    "l_position",
    "l_position_label",
    "l_instr",
    "l_instr_label",
    "rem_maturity",
    "rem_maturity_label",
    "curr_type_book",
    "curr_type_book_label",
    "l_cp_sector",
    "l_cp_sector_label",
    "l_cp_country",
    "l_cp_country_label",
    "time_period",
    "period_start",
    "obs_value",
    "decimals",
    "unit_measure",
    "unit_mult",
    "time_format",
    "collection",
    "org_visibility",
    "availability",
    "title_grp",
    "obs_status",
    "obs_conf",
    "obs_pre_break"
FROM "bis-ws-cbs-pub"
WHERE obs_value IS NOT NULL
