-- WS_CPP: one row per (series_key, time_period) observation.
-- Raw already carries typed obs_value / period_start and split code+label
-- dimension columns, so this is a projection plus the missing-observation gate.
SELECT
    "series_key",
    "freq",
    "freq_label",
    "ref_area",
    "ref_area_label",
    "covered_area",
    "covered_area_label",
    "re_type",
    "re_type_label",
    "re_vintage",
    "re_vintage_label",
    "compiling_org",
    "compiling_org_label",
    "priced_unit",
    "priced_unit_label",
    "adjust_coded",
    "adjust_coded_label",
    "time_period",
    "period_start",
    "obs_value",
    "collection",
    "time_format",
    "availability",
    "breaks",
    "collection_detail",
    "coverage",
    "data_comp",
    "decimals",
    "doc_method",
    "measure_detail",
    "meta_update",
    "publications",
    "title_grp",
    "title_grp_compl",
    "title_grp_nat",
    "unit_measure",
    "unit_mult",
    "obs_conf",
    "obs_pre_break",
    "obs_status"
FROM "bis-ws-cpp"
WHERE obs_value IS NOT NULL
