-- WS_CPMI_CASHLESS: one row per (series_key, time_period) observation.
-- Raw already carries typed obs_value / period_start and split code+label
-- dimension columns, so this is a projection plus the missing-observation gate.
SELECT
    "series_key",
    "freq",
    "freq_label",
    "rep_cty",
    "rep_cty_label",
    "measure",
    "measure_label",
    "instrument_type",
    "instrument_type_label",
    "direction",
    "direction_label",
    "terminal_loc",
    "terminal_loc_label",
    "card_iss_loc",
    "card_iss_loc_label",
    "dev_state_tech",
    "dev_state_tech_label",
    "terminal_type",
    "terminal_type_label",
    "card_fct",
    "card_fct_label",
    "paymt_speed",
    "paymt_speed_label",
    "issuer_or_onus",
    "issuer_or_onus_label",
    "time_period",
    "period_start",
    "obs_value",
    "unit_mult",
    "unit_measure",
    "title",
    "time_format",
    "table",
    "decimals",
    "comment_ts",
    "collection",
    "availability",
    "old_table",
    "obs_status",
    "obs_pre_break",
    "obs_conf",
    "comment_obs"
FROM "bis-ws-cpmi-cashless"
WHERE obs_value IS NOT NULL
