-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: TRADHIST combines trade flows with historical gravity covariates and source flags; reverse country-pair directions are distinct.
SELECT
    "iso_o",
    "iso_d",
    "year",
    "FLOW" AS flow,
    "FLOW_0" AS flow_0,
    "SOURCE_TF" AS source_tf,
    "GDP_o" AS gdp_o,
    "SOURCE_GDP_o" AS source_gdp_o,
    "GDP_d" AS gdp_d,
    "SOURCE_GDP_d" AS source_gdp_d,
    "SH_PRIM_o" AS sh_prim_o,
    "SOURCE_SH_PRIM_o" AS source_sh_prim_o,
    "SH_SECD_o" AS sh_secd_o,
    "SOURCE_SH_SECD_o" AS source_sh_secd_o,
    "SH_PRIM_d" AS sh_prim_d,
    "SOURCE_SH_PRIM_d" AS source_sh_prim_d,
    "SH_SECD_d" AS sh_secd_d,
    "SOURCE_SH_SECD_d" AS source_sh_secd_d,
    "POP_o" AS pop_o,
    "POP_d" AS pop_d,
    "SOURCE_POP_o" AS source_pop_o,
    "SOURCE_POP_d" AS source_pop_d,
    "IPTOT_o" AS iptot_o,
    "SOURCE_IPTOT_o" AS source_iptot_o,
    "IPTOT_d" AS iptot_d,
    "SOURCE_IPTOT_d" AS source_iptot_d,
    "XPTOT_o" AS xptot_o,
    "SOURCE_XPTOT_o" AS source_xptot_o,
    "XPTOT_d" AS xptot_d,
    "SOURCE_XPTOT_d" AS source_xptot_d,
    "BITARIFF" AS bitariff,
    "TARIFF_o" AS tariff_o,
    "SOURCE_TARIFF_o" AS source_tariff_o,
    "TARIFF_d" AS tariff_d,
    "SOURCE_TARIFF_d" AS source_tariff_d,
    "Distw" AS distw,
    "Dist_coord" AS dist_coord,
    "Dist_o" AS dist_o,
    "Dist_d" AS dist_d,
    "SeaDist_SHRT" AS seadist_shrt,
    "SeaDist_2CST" AS seadist_2cst,
    "Comlang" AS comlang,
    "Contig" AS contig,
    "Curcol" AS curcol,
    "Metro" AS metro,
    "Colo" AS colo,
    "Curcol_o" AS curcol_o,
    "Curcol_d" AS curcol_d,
    "Evercol" AS evercol,
    "XCH_RATE_o" AS xch_rate_o,
    "SOURCE_XCH_o" AS source_xch_o,
    "XCH_RATE_d" AS xch_rate_d,
    "SOURCE_XCH_d" AS source_xch_d,
    "CONTI_o" AS conti_o,
    "CONTI_d" AS conti_d,
    "REGIO_o" AS regio_o,
    "REGIO_d" AS regio_d,
    "OECD_o" AS oecd_o,
    "OECD_d" AS oecd_d,
    "EU_o" AS eu_o,
    "EU_d" AS eu_d,
    "GATT_o" AS gatt_o,
    "GATT_d" AS gatt_d
FROM "cepii-tradhist"
