-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: ProdComp combines several legacy workbooks and sheets with different base years and index definitions; filter by source_file and source_sheet.
SELECT
    "Copyright CEPII" AS copyright_cepii,
    "Unnamed: 1" AS unnamed_1,
    "Unnamed: 2" AS unnamed_2,
    "Unnamed: 3" AS unnamed_3,
    "Unnamed: 4" AS unnamed_4,
    "Unnamed: 5" AS unnamed_5,
    "source_file",
    "source_sheet",
    "NACE" AS nace,
    "Common Basket" AS common_basket,
    "Final UVR" AS final_uvr,
    "Unnamed: 6" AS unnamed_6,
    "Unnamed: 7" AS unnamed_7,
    "Unnamed: 8" AS unnamed_8,
    "Price" AS price,
    "Unnamed: 10" AS unnamed_10,
    "Turnover (million  €)" AS turnover_million,
    "Unnamed: 12" AS unnamed_12,
    "Unnamed: 13" AS unnamed_13,
    "Value added  (million €)" AS value_added_million,
    "Unnamed: 15" AS unnamed_15,
    "Unnamed: 16" AS unnamed_16,
    "Unnamed: 17" AS unnamed_17,
    "Unnamed: 18" AS unnamed_18,
    "Persons engaged" AS persons_engaged,
    "Unnamed: 20" AS unnamed_20,
    "Unnamed: 21" AS unnamed_21,
    "Annual average hours worked" AS annual_average_hours_worked,
    "Unnamed: 23" AS unnamed_23,
    "Unnamed: 24" AS unnamed_24,
    "Total hours worked  (million)" AS total_hours_worked_million,
    "Unnamed: 26" AS unnamed_26,
    "Unnamed: 27" AS unnamed_27,
    "Labour compensation per employee (€)" AS labour_compensation_per_employee,
    "Unnamed: 29" AS unnamed_29,
    "Unnamed: 30" AS unnamed_30,
    "Unnamed: 31" AS unnamed_31,
    "Labour compensation (persons engaged)" AS labour_compensation_persons_engaged,
    "Unnamed: 33" AS unnamed_33,
    "Unnamed: 34" AS unnamed_34,
    "Unnamed: 35" AS unnamed_35,
    "Labour compensation per hour" AS labour_compensation_per_hour,
    "Unnamed: 37" AS unnamed_37,
    "Unnamed: 38" AS unnamed_38,
    "Unnamed: 39" AS unnamed_39,
    "Productivity level per person engaged" AS productivity_level_per_person_engaged,
    "Unnamed: 41" AS unnamed_41,
    "Unnamed: 42" AS unnamed_42,
    "Unnamed: 43" AS unnamed_43,
    "Productivity level per hour" AS productivity_level_per_hour,
    "Unnamed: 45" AS unnamed_45,
    "Unnamed: 46" AS unnamed_46,
    "Unnamed: 47" AS unnamed_47,
    "Unit Labour Cost" AS unit_labour_cost,
    "Unnamed: 49" AS unnamed_49,
    "Turnover (million €)" AS turnover_million_2,
    "Value added  (million PLN or €)" AS value_added_million_pln_or,
    "Value added  (million GBP or €)" AS value_added_million_gbp_or,
    "ISO" AS iso,
    "Level" AS level,
    "RVU (UMN/FRF)" AS rvu_umn_frf,
    "TCH (UMN/FRF)" AS tch_umn_frf,
    "RVU/TCH_nominal" AS rvu_tch_nominal,
    "VA" AS va,
    "L" AS l,
    "H" AS h,
    "LH" AS lh,
    "VA/L" AS va_l,
    "VA/LH" AS va_lh,
    "Variable" AS variable,
    "1980",
    "1981",
    "1982",
    "1983",
    "1984",
    "1985",
    "1986",
    "1987",
    "1988",
    "1989",
    "1990",
    "1991",
    "1992",
    "1993",
    "1994",
    "1995",
    "1996",
    "1997",
    "1998",
    "1999",
    "2000",
    "2001",
    "CHELEM-CD-ROM Extraction 25.11.2003" AS chelem_cd_rom_extraction_25_11_2003,
    "Unnamed: 9" AS unnamed_9,
    "Unnamed: 11" AS unnamed_11,
    "Unnamed: 14" AS unnamed_14,
    "Unnamed: 19" AS unnamed_19,
    "Unnamed: 22" AS unnamed_22
FROM "cepii-prodcomp"
