SELECT
    CAST("FREQ" AS VARCHAR) AS "FREQ",
    CAST("FWT" AS VARCHAR) AS "FWT",
    CAST("ENAME" AS VARCHAR) AS "ENAME",
    CAST("TIME_PERIOD" AS VARCHAR) AS "TIME_PERIOD",
    TRY_CAST("OBS_VALUE" AS DOUBLE) AS "OBS_VALUE"
FROM "canadian-centre-for-energy-information-ca1:df-skwells-summary"
WHERE OBS_VALUE IS NOT NULL
  AND TRY_CAST(OBS_VALUE AS DOUBLE) IS NOT NULL
