SELECT
    CAST("FREQ" AS VARCHAR) AS "FREQ",
    CAST("CON_36100460_DIM1" AS VARCHAR) AS "CON_36100460_DIM1",
    CAST("CON_36100460_DIM2" AS VARCHAR) AS "CON_36100460_DIM2",
    CAST("TIME_PERIOD" AS VARCHAR) AS "TIME_PERIOD",
    TRY_CAST("OBS_VALUE" AS DOUBLE) AS "OBS_VALUE",
    CAST("CONF_STATUS" AS VARCHAR) AS "CONF_STATUS",
    CAST("OBS_STATUS" AS VARCHAR) AS "OBS_STATUS",
    CAST("QUALITY" AS VARCHAR) AS "QUALITY",
    CAST("UNIT_MEASURE" AS VARCHAR) AS "UNIT_MEASURE",
    CAST("UNIT_MULT" AS VARCHAR) AS "UNIT_MULT",
    CAST("DGUID" AS VARCHAR) AS "DGUID",
    CAST("VECTOR" AS VARCHAR) AS "VECTOR",
    CAST("DECIMALS" AS VARCHAR) AS "DECIMALS"
FROM "canadian-centre-for-energy-information-stc:df-36100460"
WHERE OBS_VALUE IS NOT NULL
  AND TRY_CAST(OBS_VALUE AS DOUBLE) IS NOT NULL
