SELECT * EXCLUDE (DATAFLOW)
       REPLACE (TRY_CAST(OBS_VALUE AS DOUBLE) AS OBS_VALUE)
FROM "canadian-centre-for-energy-information-ccei:black-carbon"
WHERE OBS_VALUE IS NOT NULL
  AND TRY_CAST(OBS_VALUE AS DOUBLE) IS NOT NULL
