-- WPP2024 demographic indicators (Medium/standard projection variant).
-- Published only for the Medium (standard) projection variant.
SELECT
    CAST(LocID AS BIGINT) AS location_id,
    Location AS location_name,
    NULLIF(TRIM(ISO3_code), '') AS iso3,
    NULLIF(TRIM(LocTypeName), '') AS location_type,
    CAST(Time AS BIGINT) AS year,
    CAST(TPopulation1Jan AS DOUBLE) AS population_jan1,
    CAST(TPopulation1July AS DOUBLE) AS population_july1,
    CAST(TPopulationMale1July AS DOUBLE) AS population_male_july1,
    CAST(TPopulationFemale1July AS DOUBLE) AS population_female_july1,
    CAST(PopDensity AS DOUBLE) AS population_density,
    CAST(PopSexRatio AS DOUBLE) AS sex_ratio,
    CAST(MedianAgePop AS DOUBLE) AS median_age,
    CAST(NatChange AS DOUBLE) AS natural_change,
    CAST(NatChangeRT AS DOUBLE) AS natural_change_rate,
    CAST(PopChange AS DOUBLE) AS population_change,
    CAST(PopGrowthRate AS DOUBLE) AS population_growth_rate,
    CAST(DoublingTime AS DOUBLE) AS doubling_time,
    CAST(Births AS DOUBLE) AS births,
    CAST(Births1519 AS DOUBLE) AS births_age15_19,
    CAST(CBR AS DOUBLE) AS crude_birth_rate,
    CAST(TFR AS DOUBLE) AS total_fertility_rate,
    CAST(NRR AS DOUBLE) AS net_reproduction_rate,
    CAST(MAC AS DOUBLE) AS mean_age_childbearing,
    CAST(SRB AS DOUBLE) AS sex_ratio_at_birth,
    CAST(Deaths AS DOUBLE) AS deaths,
    CAST(DeathsMale AS DOUBLE) AS deaths_male,
    CAST(DeathsFemale AS DOUBLE) AS deaths_female,
    CAST(CDR AS DOUBLE) AS crude_death_rate,
    CAST(LEx AS DOUBLE) AS life_expectancy_birth,
    CAST(LExMale AS DOUBLE) AS life_expectancy_birth_male,
    CAST(LExFemale AS DOUBLE) AS life_expectancy_birth_female,
    CAST(LE15 AS DOUBLE) AS life_expectancy_age15,
    CAST(LE15Male AS DOUBLE) AS life_expectancy_age15_male,
    CAST(LE15Female AS DOUBLE) AS life_expectancy_age15_female,
    CAST(LE65 AS DOUBLE) AS life_expectancy_age65,
    CAST(LE65Male AS DOUBLE) AS life_expectancy_age65_male,
    CAST(LE65Female AS DOUBLE) AS life_expectancy_age65_female,
    CAST(LE80 AS DOUBLE) AS life_expectancy_age80,
    CAST(LE80Male AS DOUBLE) AS life_expectancy_age80_male,
    CAST(LE80Female AS DOUBLE) AS life_expectancy_age80_female,
    CAST(InfantDeaths AS DOUBLE) AS infant_deaths,
    CAST(IMR AS DOUBLE) AS infant_mortality_rate,
    CAST(LBsurvivingAge1 AS DOUBLE) AS births_surviving_age1,
    CAST(Under5Deaths AS DOUBLE) AS under5_deaths,
    CAST(Q5 AS DOUBLE) AS under5_mortality,
    CAST(Q0040 AS DOUBLE) AS mortality_0_40,
    CAST(Q0040Male AS DOUBLE) AS mortality_0_40_male,
    CAST(Q0040Female AS DOUBLE) AS mortality_0_40_female,
    CAST(Q0060 AS DOUBLE) AS mortality_0_60,
    CAST(Q0060Male AS DOUBLE) AS mortality_0_60_male,
    CAST(Q0060Female AS DOUBLE) AS mortality_0_60_female,
    CAST(Q1550 AS DOUBLE) AS mortality_15_50,
    CAST(Q1550Male AS DOUBLE) AS mortality_15_50_male,
    CAST(Q1550Female AS DOUBLE) AS mortality_15_50_female,
    CAST(Q1560 AS DOUBLE) AS mortality_15_60,
    CAST(Q1560Male AS DOUBLE) AS mortality_15_60_male,
    CAST(Q1560Female AS DOUBLE) AS mortality_15_60_female,
    CAST(NetMigrations AS DOUBLE) AS net_migration,
    CAST(CNMR AS DOUBLE) AS net_migration_rate
FROM "un-population-division-demographic-indicators"
WHERE LocID IS NOT NULL AND Variant = 'Medium'
