-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Published as a full Socrata snapshot table; no stable row key was asserted during schema-only profiling.
SELECT
    "proj_num",
    "capital_plan",
    "loaddate",
    "plan_rev_keys",
    "plan_rev_display_keys",
    "agency_code",
    "category",
    "element",
    "project",
    "mega_project",
    "agency_name",
    "category_description",
    "element_description",
    "proj_description",
    "scope_objective",
    "phase",
    "needs_code",
    "original_budget",
    "latest_approved_budget",
    "current_budget",
    "original_budget_vs_current_budget",
    "lastest_approved_budget_vs_current_budget",
    "scope_change",
    "overall_scope_change",
    "original_start_mm",
    "original_start_yyyy",
    "current_start_mm",
    "current_start_yyyy",
    "original_completion_mm",
    "original_completion_yyyy",
    "current_completion_mm",
    "current_completion_yyyy",
    "milestone_design_start_mm",
    "milestone_design_start_yyyy",
    "milestone_design_completion_mm",
    "milestone_design_completion_yyyy",
    "milestone_construction_start_mm",
    "milestone_construction_start_yyyy",
    "milestone_construction_completion_mm",
    "milestone_construction_completion_yyyy",
    "percentage_complete",
    "location_indicator",
    "ada_flag",
    "resiliency_flag"
FROM "mta-open-data-ehz8-ag3n"
