-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Published as a full Socrata snapshot table; no stable row key was asserted during schema-only profiling.
SELECT
    "recorded_date",
    "progress",
    "duration_in_seconds",
    "finished",
    "response_id",
    "how_old_are_you",
    "which_of_the_following_would",
    "where_did_you_use_navilens",
    "at_which_subway_station_did",
    "overall_how_satisfied_are",
    "overall_how_satisfied_are_1",
    "have_you_used_navilens_in",
    "how_satisfied_are_you_with",
    "to_what_extent_do_you_agree",
    "to_what_extent_do_you_agree_1",
    "to_what_extent_do_you_agree_2",
    "to_what_extent_do_you_agree_3",
    "to_what_extent_do_you_agree_4",
    "to_what_extent_do_you_agree_5",
    "to_what_extent_do_you_agree_6",
    "to_what_extent_do_you_agree_7",
    "how_likely_are_you_to",
    "would_you_like_to_have_more",
    "have_you_used_any_other",
    "which_other_wayfinding_how",
    "which_other_wayfinding_how_1",
    "which_of_these_wayfinding",
    "which_of_these_wayfinding_1",
    "is_there_anything_else_about",
    "where_did_you_use_navilens_1",
    "at_which_subway_station_did_1",
    "overall_how_satisfied_are_2",
    "overall_how_satisfied_are_3",
    "have_you_used_navilens_go",
    "how_satisfied_are_you_with_1",
    "to_what_extent_do_you_agree_8",
    "to_what_extent_do_you_agree_9",
    "to_what_extent_do_you_agree_10",
    "to_what_extent_do_you_agree_11",
    "to_what_extent_do_you_agree_12",
    "to_what_extent_do_you_agree_13",
    "to_what_extent_do_you_agree_14",
    "to_what_extent_do_you_agree_15",
    "how_likely_are_you_to_1",
    "would_you_like_to_have_more_1",
    "have_you_used_any_other_1",
    "what_other_wayfinding_travel",
    "what_other_wayfinding_travel_1",
    "which_of_these_wayfinding_2",
    "which_of_these_wayfinding_3",
    "is_there_anything_else_about_1",
    "in_a_typical_week_how_often",
    "are_you_currently_an_access",
    "do_you_identify_as_having",
    "do_you_identify_as_having_1"
FROM "mta-open-data-q2wi-uth2"
