SELECT
  CAST(postcode AS VARCHAR) AS postcode,
  TRY_CAST(REPLACE(count_taxable_income_or_loss, ',', '') AS BIGINT) AS count_taxable_income_or_loss,
  TRY_CAST(REPLACE(average_taxable_income_or_loss, ',', '') AS BIGINT) AS average_taxable_income_or_loss,
  TRY_CAST(REPLACE(median_taxable_income_or_loss, ',', '') AS BIGINT) AS median_taxable_income_or_loss,
  TRY_CAST(REPLACE(count_salary_and_wages, ',', '') AS BIGINT) AS count_salary_and_wages,
  TRY_CAST(REPLACE(average_salary_and_wages, ',', '') AS BIGINT) AS average_salary_and_wages,
  TRY_CAST(REPLACE(median_salary_and_wages, ',', '') AS BIGINT) AS median_salary_and_wages,
  TRY_CAST(REPLACE(count_net_rent, ',', '') AS BIGINT) AS count_net_rent,
  TRY_CAST(REPLACE(average_net_rent, ',', '') AS BIGINT) AS average_net_rent,
  TRY_CAST(REPLACE(median_net_rent, ',', '') AS BIGINT) AS median_net_rent,
  TRY_CAST(REPLACE(count_total_income_or_loss, ',', '') AS BIGINT) AS count_total_income_or_loss,
  TRY_CAST(REPLACE(average_total_income_or_loss, ',', '') AS BIGINT) AS average_total_income_or_loss,
  TRY_CAST(REPLACE(median_total_income_or_loss, ',', '') AS BIGINT) AS median_total_income_or_loss,
  TRY_CAST(REPLACE(count_total_deductions, ',', '') AS BIGINT) AS count_total_deductions,
  TRY_CAST(REPLACE(average_total_deductions, ',', '') AS BIGINT) AS average_total_deductions,
  TRY_CAST(REPLACE(median_total_deductions, ',', '') AS BIGINT) AS median_total_deductions,
  TRY_CAST(REPLACE(count_total_business_income, ',', '') AS BIGINT) AS count_total_business_income,
  TRY_CAST(REPLACE(average_total_business_income, ',', '') AS BIGINT) AS average_total_business_income,
  TRY_CAST(REPLACE(median_total_business_income, ',', '') AS BIGINT) AS median_total_business_income,
  TRY_CAST(REPLACE(count_total_business_expenses, ',', '') AS BIGINT) AS count_total_business_expenses,
  TRY_CAST(REPLACE(average_total_business_expenses, ',', '') AS BIGINT) AS average_total_business_expenses,
  TRY_CAST(REPLACE(median_total_business_expenses, ',', '') AS BIGINT) AS median_total_business_expenses,
  TRY_CAST(REPLACE(count_net_tax, ',', '') AS BIGINT) AS count_net_tax,
  TRY_CAST(REPLACE(average_net_tax, ',', '') AS BIGINT) AS average_net_tax,
  TRY_CAST(REPLACE(median_net_tax, ',', '') AS BIGINT) AS median_net_tax,
  TRY_CAST(REPLACE(count_super_total_accounts_balance, ',', '') AS BIGINT) AS count_super_total_accounts_balance,
  TRY_CAST(REPLACE(average_super_total_accounts_balance, ',', '') AS BIGINT) AS average_super_total_accounts_balance,
  TRY_CAST(REPLACE(median_super_total_accounts_balance, ',', '') AS BIGINT) AS median_super_total_accounts_balance,
  CAST(income_year AS VARCHAR) AS income_year
FROM "ato-taxation-statistics--individuals-table-28"
