# DARES Opendatasoft dataset ids (the entity union from rank).
# Copied from data/sources/dares/work/entity_union.json — data, not logic.
ENTITY_IDS = [
    "dares_defm_age_detaille_mens",
    "dares_defm_age_detaille_trim",
    "dares_defm_communales-brutes",
    "dares_defm_entrees_stage_formation_mens",
    "dares_defm_entrees_stages_formation_trim",
    "dares_defm_flux_france_region_brut_mens",
    "dares_defm_flux_france_region_brut_trim",
    "dares_defm_flux_france_region_cvs_mens",
    "dares_defm_flux_france_region_cvs_trim",
    "dares_defm_stock_france_brut_mens",
    "dares_defm_stock_france_brut_trim",
    "dares_defm_stock_france_cvs",
    "dares_defm_stock_france_cvs_trim",
    "dares_defm_stock_region_cvs_trim",
    "dares_defm_stock_regions_brut_mens",
    "dares_defm_stock_regions_brut_trim",
    "dares_defm_stock_regions_cvs-cjo_mens",
    "dares_defm_zone_emploi_mens",
    "dares_defm_zoneeemploi_brut_trim",
    "dares_emploivacants_brut_emploisoccupes",
    "dares_emploivacants_brut_emploisvacants",
    "dares_emploivacants_cvs_emploisoccupes",
    "dares_emploivacants_cvs_emploisvacants",
    "dares_emploivacants_cvs_typevacance",
    "dares_jint_1975-2004",
    "dares_jint_depuis2005",
    "dares_offres_collectees_satisfaites_france_travail_brutes_mens",
    "dares_offres_collectees_satisfaites_france_travail_brutes_trim",
    "dares_offres_collectees_satisfaites_france_travail_cvs-cjo_mens",
    "dares_offres_collectees_satisfaites_france_travail_cvs-cjo_trim",
    "dares_tempspartiel_annuelles",
    "dares_tempspartiel_detail_annuelles",
]
