-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "RespondentID" AS respondentid,
    "In your own words, what would you call the part of the country you live in now?" AS in_your_own_words_what_would_you_call_the_part_of_the_country_you_live_in_now,
    "How much, if at all, do you personally identify as a Midwesterner?" AS how_much_if_at_all_do_you_personally_identify_as_a_midwesterner,
    "C3" AS c3,
    "_1" AS "1",
    "_2" AS "2",
    "Which of the following states do you consider part of the Midwest? Please select all that apply. " AS which_of_the_following_states_do_you_consider_part_of_the_midwest_please_select_all_that_apply,
    "_3" AS "3",
    "_4" AS "4",
    "_5" AS "5",
    "_6" AS "6",
    "_7" AS "7",
    "_8" AS "8",
    "_9" AS "9",
    "_10" AS "10",
    "_11" AS "11",
    "_12" AS "12",
    "_13" AS "13",
    "_14" AS "14",
    "_15" AS "15",
    "_16" AS "16",
    "_17" AS "17",
    "_18" AS "18",
    "_19" AS "19",
    "_20" AS "20",
    "_21" AS "21",
    "In what ZIP code is your home located? (enter 5-digit ZIP code; for example, 00544 or 94305)" AS in_what_zip_code_is_your_home_located_enter_5_digit_zip_code_for_example_00544_or_94305,
    "Gender" AS gender,
    "_22" AS "22",
    "Age" AS age,
    "_23" AS "23",
    "_24" AS "24",
    "_25" AS "25",
    "_26" AS "26",
    "Household Income" AS household_income,
    "_27" AS "27",
    "_28" AS "28",
    "_29" AS "29",
    "_30" AS "30",
    "Education" AS education,
    "_31" AS "31",
    "_32" AS "32",
    "_33" AS "33",
    "_34" AS "34",
    "Location (Census Region)" AS location_census_region,
    "_35" AS "35",
    "_36" AS "36",
    "_37" AS "37",
    "_38" AS "38",
    "_39" AS "39",
    "_40" AS "40",
    "_41" AS "41",
    "_42" AS "42"
FROM "fivethirtyeight-region-survey-midwest"
