-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "RespondentID" AS respondentid,
    "Generally speaking, how would you rate your level of knowledgeÊof cuisines from different parts of the world?" AS generally_speaking_how_would_you_rate_your_level_of_knowledge_of_cuisines_from_different_parts_of_the_world,
    "How much, if at all, are you interested in cuisines from different parts of the world?" AS how_much_if_at_all_are_you_interested_in_cuisines_from_different_parts_of_the_world,
    "Please rate how much you like the traditional cuisine of Algeria:" AS please_rate_how_much_you_like_the_traditional_cuisine_of_algeria,
    "Please rate how much you like the traditional cuisine of Argentina." AS please_rate_how_much_you_like_the_traditional_cuisine_of_argentina,
    "Please rate how much you like the traditional cuisine ofÊAustralia." AS please_rate_how_much_you_like_the_traditional_cuisine_of_australia,
    "Please rate how much you like the traditional cuisine of Belgium." AS please_rate_how_much_you_like_the_traditional_cuisine_of_belgium,
    "Please rate how much you like the traditional cuisine of Bosnia and Herzegovina." AS please_rate_how_much_you_like_the_traditional_cuisine_of_bosnia_and_herzegovina,
    "Please rate how much you like the traditional cuisine of Brazil." AS please_rate_how_much_you_like_the_traditional_cuisine_of_brazil,
    "Please rate how much you like the traditional cuisine of Cameroon." AS please_rate_how_much_you_like_the_traditional_cuisine_of_cameroon,
    "Please rate how much you like the traditional cuisine of Chile." AS please_rate_how_much_you_like_the_traditional_cuisine_of_chile,
    "Please rate how much you like the traditional cuisine of Colombia." AS please_rate_how_much_you_like_the_traditional_cuisine_of_colombia,
    "Please rate how much you like the traditional cuisine of Costa Rica." AS please_rate_how_much_you_like_the_traditional_cuisine_of_costa_rica,
    "Please rate how much you like the traditional cuisine of Croatia." AS please_rate_how_much_you_like_the_traditional_cuisine_of_croatia,
    "Please rate how much you like the traditional cuisine of Ecuador." AS please_rate_how_much_you_like_the_traditional_cuisine_of_ecuador,
    "Please rate how much you like the traditional cuisine of England." AS please_rate_how_much_you_like_the_traditional_cuisine_of_england,
    "Please rate how much you like the traditional cuisine of France." AS please_rate_how_much_you_like_the_traditional_cuisine_of_france,
    "Please rate how much you like the traditional cuisine of Germany." AS please_rate_how_much_you_like_the_traditional_cuisine_of_germany,
    "Please rate how much you like the traditional cuisine of Ghana." AS please_rate_how_much_you_like_the_traditional_cuisine_of_ghana,
    "Please rate how much you like the traditional cuisine of Greece." AS please_rate_how_much_you_like_the_traditional_cuisine_of_greece,
    "Please rate how much you like the traditional cuisine of Honduras." AS please_rate_how_much_you_like_the_traditional_cuisine_of_honduras,
    "Please rate how much you like the traditional cuisine of Iran." AS please_rate_how_much_you_like_the_traditional_cuisine_of_iran,
    "Please rate how much you like the traditional cuisine of Italy." AS please_rate_how_much_you_like_the_traditional_cuisine_of_italy,
    "Please rate how much you like the traditional cuisine of Ivory Coast." AS please_rate_how_much_you_like_the_traditional_cuisine_of_ivory_coast,
    "Please rate how much you like the traditional cuisine of Japan." AS please_rate_how_much_you_like_the_traditional_cuisine_of_japan,
    "Please rate how much you like the traditional cuisine of Mexico." AS please_rate_how_much_you_like_the_traditional_cuisine_of_mexico,
    "Please rate how much you like the traditional cuisine of the Netherlands." AS please_rate_how_much_you_like_the_traditional_cuisine_of_the_netherlands,
    "Please rate how much you like the traditional cuisine of Nigeria." AS please_rate_how_much_you_like_the_traditional_cuisine_of_nigeria,
    "Please rate how much you like the traditional cuisine of Portugal." AS please_rate_how_much_you_like_the_traditional_cuisine_of_portugal,
    "Please rate how much you like the traditional cuisine of Russia." AS please_rate_how_much_you_like_the_traditional_cuisine_of_russia,
    "Please rate how much you like the traditional cuisine of South Korea." AS please_rate_how_much_you_like_the_traditional_cuisine_of_south_korea,
    "Please rate how much you like the traditional cuisine of Spain." AS please_rate_how_much_you_like_the_traditional_cuisine_of_spain,
    "Please rate how much you like the traditional cuisine of Switzerland." AS please_rate_how_much_you_like_the_traditional_cuisine_of_switzerland,
    "Please rate how much you like the traditional cuisine of United States." AS please_rate_how_much_you_like_the_traditional_cuisine_of_united_states,
    "Please rate how much you like the traditional cuisine of Uruguay." AS please_rate_how_much_you_like_the_traditional_cuisine_of_uruguay,
    "Please rate how much you like the traditional cuisine of China." AS please_rate_how_much_you_like_the_traditional_cuisine_of_china,
    "Please rate how much you like the traditional cuisine of India." AS please_rate_how_much_you_like_the_traditional_cuisine_of_india,
    "Please rate how much you like the traditional cuisine of Thailand." AS please_rate_how_much_you_like_the_traditional_cuisine_of_thailand,
    "Please rate how much you like the traditional cuisine of Turkey." AS please_rate_how_much_you_like_the_traditional_cuisine_of_turkey,
    "Please rate how much you like the traditional cuisine of Cuba." AS please_rate_how_much_you_like_the_traditional_cuisine_of_cuba,
    "Please rate how much you like the traditional cuisine of Ethiopia." AS please_rate_how_much_you_like_the_traditional_cuisine_of_ethiopia,
    "Please rate how much you like the traditional cuisine of Vietnam." AS please_rate_how_much_you_like_the_traditional_cuisine_of_vietnam,
    "Please rate how much you like the traditional cuisine of Ireland." AS please_rate_how_much_you_like_the_traditional_cuisine_of_ireland,
    "Gender" AS gender,
    "Age" AS age,
    "Household Income" AS household_income,
    "Education" AS education,
    "Location (Census Region)" AS location_census_region
FROM "fivethirtyeight-food-world-cup-food-world-cup-data"
