-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "RespondentID" AS respondentid,
    "Do you celebrate Thanksgiving?" AS do_you_celebrate_thanksgiving,
    "What is typically the main dish at your Thanksgiving dinner?" AS what_is_typically_the_main_dish_at_your_thanksgiving_dinner,
    "What is typically the main dish at your Thanksgiving dinner? - Other (please specify)" AS what_is_typically_the_main_dish_at_your_thanksgiving_dinner_other_please_specify,
    "How is the main dish typically cooked?" AS how_is_the_main_dish_typically_cooked,
    "How is the main dish typically cooked? - Other (please specify)" AS how_is_the_main_dish_typically_cooked_other_please_specify,
    "What kind of stuffing/dressing do you typically have?" AS what_kind_of_stuffing_dressing_do_you_typically_have,
    "What kind of stuffing/dressing do you typically have? - Other (please specify)" AS what_kind_of_stuffing_dressing_do_you_typically_have_other_please_specify,
    "What type of cranberry saucedo you typically have?" AS what_type_of_cranberry_saucedo_you_typically_have,
    "What type of cranberry saucedo you typically have? - Other (please specify)" AS what_type_of_cranberry_saucedo_you_typically_have_other_please_specify,
    "Do you typically have gravy?" AS do_you_typically_have_gravy,
    "Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Brussel sprouts" AS which_of_these_side_dishes_aretypically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_brussel_sprouts,
    "Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Carrots" AS which_of_these_side_dishes_aretypically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_carrots,
    "Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cauliflower" AS which_of_these_side_dishes_aretypically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_cauliflower,
    "Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Corn" AS which_of_these_side_dishes_aretypically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_corn,
    "Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Cornbread" AS which_of_these_side_dishes_aretypically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_cornbread,
    "Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Fruit salad" AS which_of_these_side_dishes_aretypically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_fruit_salad,
    "Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Green beans/green bean casserole" AS which_of_these_side_dishes_aretypically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_green_beans_green_bean_casserole,
    "Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Macaroni and cheese" AS which_of_these_side_dishes_aretypically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_macaroni_and_cheese,
    "Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Mashed potatoes" AS which_of_these_side_dishes_aretypically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_mashed_potatoes,
    "Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Rolls/biscuits" AS which_of_these_side_dishes_aretypically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_rolls_biscuits,
    "Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Squash" AS which_of_these_side_dishes_aretypically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_squash,
    "Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Vegetable salad" AS which_of_these_side_dishes_aretypically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_vegetable_salad,
    "Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Yams/sweet potato casserole" AS which_of_these_side_dishes_aretypically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_yams_sweet_potato_casserole,
    "Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)" AS which_of_these_side_dishes_aretypically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_other_please_specify,
    "Which of these side dishes aretypically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)_1" AS which_of_these_side_dishes_aretypically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_other_please_specify_1,
    "Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Apple" AS which_type_of_pie_is_typically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_apple,
    "Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Buttermilk" AS which_type_of_pie_is_typically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_buttermilk,
    "Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Cherry" AS which_type_of_pie_is_typically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_cherry,
    "Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Chocolate" AS which_type_of_pie_is_typically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_chocolate,
    "Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Coconut cream" AS which_type_of_pie_is_typically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_coconut_cream,
    "Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Key lime" AS which_type_of_pie_is_typically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_key_lime,
    "Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Peach" AS which_type_of_pie_is_typically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_peach,
    "Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pecan" AS which_type_of_pie_is_typically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_pecan,
    "Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Pumpkin" AS which_type_of_pie_is_typically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_pumpkin,
    "Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Sweet Potato" AS which_type_of_pie_is_typically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_sweet_potato,
    "Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - None" AS which_type_of_pie_is_typically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_none,
    "Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)" AS which_type_of_pie_is_typically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_other_please_specify,
    "Which type of pie is typically served at your Thanksgiving dinner? Please select all that apply. - Other (please specify)_1" AS which_type_of_pie_is_typically_served_at_your_thanksgiving_dinner_please_select_all_that_apply_other_please_specify_1,
    "Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Apple cobbler" AS which_of_these_desserts_do_you_typically_have_at_thanksgiving_dinner_please_select_all_that_apply_apple_cobbler,
    "Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Blondies" AS which_of_these_desserts_do_you_typically_have_at_thanksgiving_dinner_please_select_all_that_apply_blondies,
    "Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Brownies" AS which_of_these_desserts_do_you_typically_have_at_thanksgiving_dinner_please_select_all_that_apply_brownies,
    "Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Carrot cake" AS which_of_these_desserts_do_you_typically_have_at_thanksgiving_dinner_please_select_all_that_apply_carrot_cake,
    "Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cheesecake" AS which_of_these_desserts_do_you_typically_have_at_thanksgiving_dinner_please_select_all_that_apply_cheesecake,
    "Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Cookies" AS which_of_these_desserts_do_you_typically_have_at_thanksgiving_dinner_please_select_all_that_apply_cookies,
    "Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Fudge" AS which_of_these_desserts_do_you_typically_have_at_thanksgiving_dinner_please_select_all_that_apply_fudge,
    "Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Ice cream" AS which_of_these_desserts_do_you_typically_have_at_thanksgiving_dinner_please_select_all_that_apply_ice_cream,
    "Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Peach cobbler" AS which_of_these_desserts_do_you_typically_have_at_thanksgiving_dinner_please_select_all_that_apply_peach_cobbler,
    "Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - None" AS which_of_these_desserts_do_you_typically_have_at_thanksgiving_dinner_please_select_all_that_apply_none,
    "Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify)" AS which_of_these_desserts_do_you_typically_have_at_thanksgiving_dinner_please_select_all_that_apply_other_please_specify,
    "Which of these desserts do you typically have at Thanksgiving dinner? Please select all that apply.   - Other (please specify)_1" AS which_of_these_desserts_do_you_typically_have_at_thanksgiving_dinner_please_select_all_that_apply_other_please_specify_1,
    "Do you typically pray before or after the Thanksgiving meal?" AS do_you_typically_pray_before_or_after_the_thanksgiving_meal,
    "How far will you travel for Thanksgiving?" AS how_far_will_you_travel_for_thanksgiving,
    "Will you watch any of the following programs on Thanksgiving? Please select all that apply. - Macy's Parade" AS will_you_watch_any_of_the_following_programs_on_thanksgiving_please_select_all_that_apply_macy_s_parade,
    "What's the age cutoff at your ""kids' table"" at Thanksgiving?" AS what_s_the_age_cutoff_at_your_kids_table_at_thanksgiving,
    "Have you ever tried to meet up with hometown friends on Thanksgiving night?" AS have_you_ever_tried_to_meet_up_with_hometown_friends_on_thanksgiving_night,
    "Have you ever attended a ""Friendsgiving?""" AS have_you_ever_attended_a_friendsgiving,
    "Will you shop any Black Friday sales on Thanksgiving Day?" AS will_you_shop_any_black_friday_sales_on_thanksgiving_day,
    "Do you work in retail?" AS do_you_work_in_retail,
    "Will you employer make you work on Black Friday?" AS will_you_employer_make_you_work_on_black_friday,
    "How would you describe where you live?" AS how_would_you_describe_where_you_live,
    "Age" AS age,
    "What is your gender?" AS what_is_your_gender,
    "How much total combined money did all members of your HOUSEHOLD earn last year?" AS how_much_total_combined_money_did_all_members_of_your_household_earn_last_year,
    "US Region" AS us_region
FROM "fivethirtyeight-thanksgiving-2015-thanksgiving-2015-poll-data"
