-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Dyad termination rows can repeat dyad episode identifiers across annual dyad attributes; do not treat dyad_id plus episode fields as unique.
SELECT
    "dyad_id",
    "conflict_id",
    "location",
    "side_a",
    "side_a_id",
    "side_a_2nd",
    "side_b",
    "side_b_id",
    "side_b_2nd",
    "incompatibility",
    "territory_name",
    "year",
    "intensity_level",
    "type_of_conflict",
    "start_date",
    "start_prec",
    "start_date2",
    "start_prec2",
    "gwno_a",
    "gwno_a_2nd",
    "gwno_b",
    "gwno_b_2nd",
    "gwno_loc",
    "region",
    "type_of_conflict2",
    "d_epid",
    "d_epno",
    "d_ep_startyear",
    "d_epterm",
    "d_outcome",
    "d_ep_endyear",
    "d_ependdate",
    "d_ependprec",
    "d_ep_durcount",
    "d_ep_dur",
    "d_cfiredate",
    "d_peagdate",
    "version"
FROM "ucdp-term-dyad"
