-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "row_id",
    "conflict_name",
    "conflict_id",
    "country_id",
    "incompatibility",
    "dyad_name",
    "dyad_id",
    "unclear_dyad",
    "monadic_event",
    "intensity",
    strptime("start_event", '%m/%d/%Y')::DATE AS start_event,
    strptime("end_event", '%m/%d/%Y')::DATE AS end_event,
    "temporal_precision",
    "source",
    "third_states_no",
    "third_igo_no",
    "third_other",
    "third_faith_based",
    "third_name",
    "third_id1",
    "third_id2",
    "third_id3",
    "third_id4",
    "third_id5",
    "third_id6",
    "third_id7",
    "third_id8",
    "third_id9",
    "third_id10",
    "third_id11",
    "third_id12",
    "third_id13",
    "third_id14",
    "third_id15",
    "third_id16",
    "third_id17",
    "third_id18",
    "third_id19",
    "third_id20",
    "third_total",
    "warring_party",
    "type_of_talks",
    "talks_incompatibility",
    "talks_conflict_behavior",
    "talks_other",
    "talks_unknown",
    "good_office",
    "fact_finding",
    "permanent_observers",
    "peacekeeping"
FROM "ucdp-mic"
