-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Primary election law attributes are state-by-state policy records; compare states within a consistent election-year or policy-period context.
SELECT
    "state",
    CAST("istate" AS BIGINT) AS istate,
    CAST("year" AS BIGINT) AS year,
    "ppr.date" AS ppr_date,
    "ppd.date" AS ppd_date,
    "r.p.dels" AS r_p_dels,
    "d.p.dels" AS d_p_dels,
    "pcr.date" AS pcr_date,
    "pcd.date" AS pcd_date,
    "r.c.dels" AS r_c_dels,
    "d.c.dels" AS d_c_dels,
    "convr.date" AS convr_date,
    "convd.date" AS convd_date,
    "opr.date" AS opr_date,
    "opd.date" AS opd_date,
    "prro.date" AS prro_date,
    "pdro.date" AS pdro_date,
    "p.ev1.date" AS p_ev1_date,
    "p.ev0.date" AS p_ev0_date,
    "p.reg0.date" AS p_reg0_date,
    "p.np1.date" AS p_np1_date,
    "p.np0.date" AS p_np0_date,
    "prf.date" AS prf_date,
    "pdf.date" AS pdf_date,
    "g.date" AS g_date,
    "gro.date" AS gro_date,
    "g.ev1.date" AS g_ev1_date,
    "g.ev0.date" AS g_ev0_date,
    "g.reg0.date" AS g_reg0_date,
    "sd.reg" AS sd_reg,
    "OPT1" AS opt1,
    "OPT2" AS opt2,
    "OPT3" AS opt3,
    "OPT4" AS opt4,
    "PPT2" AS ppt2,
    "vtr.reg" AS vtr_reg,
    "ge.enf" AS ge_enf,
    "pp.enf" AS pp_enf,
    "op.enf" AS op_enf,
    "convention",
    "private.choice" AS private_choice,
    "party.reg" AS party_reg,
    "change.partyreg" AS change_partyreg,
    "party.choice" AS party_choice,
    "primary.runoff" AS primary_runoff,
    "crossfile",
    "CQ.comments" AS cq_comments,
    "comments"
FROM "mit-election-lab-dvn-5r7tan"
