-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "_udise_report_code" AS udise_report_code,
    "_udise_report_id" AS udise_report_id,
    CAST("_udise_year_id" AS BIGINT) AS udise_year_id,
    "ger_elementary_all",
    "ger_secondary_boy_st",
    "ger_upper_primary_girl",
    "ger_elementary_all_sc",
    "ger_elementary_girl",
    "ger_higher_secondary_boy",
    "ger_upper_primary_girl_sc",
    "ger_upper_primary_boy_st",
    "ger_secondary_boy",
    "ger_higher_secondary_girl_sc",
    "ger_higher_secondary_all_st",
    "ger_upper_primary_all_st",
    "ger_higher_secondary_boy_sc",
    "ger_upper_primary_girl_st",
    "ger_higher_secondary_girl_st",
    "state_id",
    "ger_primary_all_sc",
    "ger_upper_primary_boy_sc",
    "ger_elementary_boy",
    "ger_secondary_girl",
    "ger_secondary_girl_sc",
    "ger_higher_secondary_boy_st",
    "ger_upper_primary_all_sc",
    "ger_primary_all",
    "ger_elementary_girl_st",
    "ger_secondary_all_sc",
    "ger_upper_primary_boy",
    "ger_elementary_boy_st",
    "ger_higher_secondary_all",
    "ger_primary_all_st",
    "ger_primary_boy_st",
    "ger_primary_girl_st",
    "ger_secondary_girl_st",
    "ger_primary_girl",
    "ger_elementary_girl_sc",
    "ger_secondary_all",
    "ger_upper_primary_all",
    "ger_secondary_boy_sc",
    "location_name",
    "ger_elementary_all_st",
    "ger_secondary_all_st",
    "ger_primary_boy",
    "ger_primary_girl_sc",
    "ger_higher_secondary_girl",
    "ger_primary_boy_sc",
    "ger_elementary_boy_sc",
    "ger_higher_secondary_all_sc"
FROM "udise-r101"
