-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: This report is a wide UDISE+ cross-tab with no verified row key in the raw profile; treat rows as report records and filter the relevant dimensions before aggregating values.
SELECT
    "_udise_report_code" AS udise_report_code,
    "_udise_report_id" AS udise_report_id,
    CAST("_udise_year_id" AS BIGINT) AS udise_year_id,
    "upper_pri_boy_c6_c8_current_rptr",
    "pri_boy_c1_c5_previous",
    "pri_c2_c6_current",
    "upper_pri_girl_c6_c8_current_rptr",
    "pri_girl_c1_c5_current_rptr",
    "upper_pri_boy_c7_c9_current",
    "secondary_boy_c10_c11_current",
    "secondary_boy_c9_c10_previous",
    "secondary_c10_c11_current",
    "pri_girl_c2_c6_current",
    "pri_c1_c5_current_rptr",
    "secondary_girl_c9_c10_previous",
    "pri_boy_c2_c6_current_rptr",
    "secondary_girl_c10_c11_current",
    "secondary_c10_c11_current_rptr",
    "secondary_girl_c9_c10_current_rptr",
    "pri_girl_c1_c5_previous",
    "pri_c2_c6_current_rptr",
    "secondary_boy_c9_c10_current_rptr",
    "caste_id",
    "pri_boy_c1_c5_current_rptr",
    "upper_pri_girl_c6_c8_previous",
    "secondary_boy_c10_c11_current_rptr",
    "upper_pri_c7_c9_current_fresh",
    "upper_pri_c7_c9_current_rptr",
    "upper_pri_c6_c8_previous",
    "secondary_c9_c10_previous",
    "secondary_boy_c10_c11_current_fresh",
    "upper_pri_girl_c7_c9_current_fresh",
    "upper_pri_boy_c7_c9_current_fresh",
    "secondary_girl_c10_c11_current_fresh",
    "pri_boy_c2_c6_current",
    "secondary_c10_c11_current_fresh",
    "pri_boy_c2_c6_current_fresh",
    "pri_girl_c2_c6_current_fresh",
    "secondary_girl_c10_c11_current_rptr",
    "secondary_c9_c10_current_rptr",
    "location_name",
    "caste_name",
    "pri_c2_c6_current_fresh",
    "upper_pri_c6_c8_current_rptr",
    "pri_c1_c5_previous",
    "upper_pri_girl_c7_c9_current",
    "upper_pri_boy_c7_c9_current_rptr",
    "upper_pri_girl_c7_c9_current_rptr",
    "upper_pri_boy_c6_c8_previous",
    "pri_girl_c2_c6_current_rptr",
    "upper_pri_c7_c9_current"
FROM "udise-r115"
