-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "_udise_report_code" AS udise_report_code,
    "_udise_report_id" AS udise_report_id,
    CAST("_udise_year_id" AS BIGINT) AS udise_year_id,
    "category_name",
    "total_enrol",
    "upper_primary_b",
    "upper_primary_g",
    "higher_secondary_b",
    "loc_name",
    "higher_secondary_g",
    "c10_g",
    "cpp",
    "sch_type_name",
    "c12_g",
    "upper_primary_total",
    "c12_b",
    "c1",
    "c2",
    "c10_b",
    "c3",
    "c4",
    "c7_g",
    "secondary_g",
    "c5",
    "location_name",
    "c6",
    "c9_g",
    "c7",
    "c9_b",
    "c3_g",
    "c8",
    "c9",
    "c5_g",
    "c5_b",
    "c7_b",
    "secondary_b",
    "c1_g",
    "c1_b",
    "c3_b",
    "sch_mgmt_name",
    "c11",
    "c10",
    "total_pre_enrol",
    "c12",
    "secondary_total",
    "primary_b",
    "primary_g",
    "cpp_b",
    "c11_g",
    "total_g",
    "total_pre_b",
    "higher_secondary_total",
    "year_id",
    "total_b",
    "item_name",
    "cpp_g",
    "c11_b",
    "c8_g",
    "c4_g",
    "c8_b",
    "c6_g",
    "c4_b",
    "c2_g",
    "total_pre_g",
    "c6_b",
    "primary_total",
    "c2_b"
FROM "udise-r141"
