-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: This report is a wide UDISE+ cross-tab with no verified row key in the raw profile; treat rows as report records and filter the relevant dimensions before aggregating values.
SELECT
    "_udise_report_code" AS udise_report_code,
    "_udise_report_id" AS udise_report_id,
    CAST("_udise_year_id" AS BIGINT) AS udise_year_id,
    "c11",
    "c10",
    "c12",
    "c10_g",
    "c11_g",
    "item_id",
    "c12_g",
    "item_name",
    "c11_b",
    "c12_b",
    "c1",
    "c10_b",
    "c2",
    "c8_g",
    "c3",
    "c7_g",
    "c4",
    "c5",
    "location_name",
    "c9_g",
    "c6",
    "c4_g",
    "c9_b",
    "c7",
    "c3_g",
    "c8_b",
    "c8",
    "c6_g",
    "c9",
    "c5_g",
    "c5_b",
    "c4_b",
    "c2_g",
    "c7_b",
    "c1_g",
    "c6_b",
    "c1_b",
    "c3_b",
    "c2_b"
FROM "udise-r135"
