-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "_udise_report_code" AS udise_report_code,
    "_udise_report_id" AS udise_report_id,
    CAST("_udise_year_id" AS BIGINT) AS udise_year_id,
    "upperprimaryonlytotal",
    "highersecondaryonlytotal",
    "primaryandupperprimarytotal",
    "primaryupperprimaym_qual",
    "primaryupperprimary_qual",
    "primaryonlym",
    "preprimaryonlym",
    "primaryftotal",
    "primaryonlyf",
    "secondaryonlym",
    "highersecondaryftotal",
    "secondaryandhighersecondarym",
    "preprimaryprimarytotal",
    "primaryonlytotal",
    "preprimarymtotal",
    "preprimarytotal",
    "upperprimarymtotal",
    "highersecondarymtotal",
    "upperprimaryonlyf",
    "secondaryonlyf",
    "secondaryandhighersecondaryf",
    "upperprimaryonlym",
    "preprimaryprimaryf",
    "upperprimarytotal",
    "upperprimaryandsecondarym",
    "highersecondarytotal",
    "highersecondaryonlyf",
    "primarymtotal",
    "preprimaryprimarym",
    "preprimaryftotal",
    "highersecondaryonlym",
    "upperprimaryftotal",
    "secondaryftotal",
    "preprimaryonlyf",
    "preprimaryonlytotal",
    "upperprimaryandsecondarytotal",
    "location_name",
    "secondarytotal",
    "primaryandupperprimaryf",
    "secondaryonlytotal",
    "primaryupperprimaryf_qual",
    "primaryandupperprimarym",
    "upperprimaryandsecondaryf",
    "secondaryandhighersecondarytotal",
    "primarytotal",
    "secondarymtotal"
FROM "udise-r99"
