-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "SALARIES_MGT" AS salaries_mgt,
    CAST("SALARIES_FLIGHT" AS DOUBLE) AS salaries_flight,
    "SALARIES_MAINT" AS salaries_maint,
    "SALARIES_TRAFFIC" AS salaries_traffic,
    "SALARIES_OTHER" AS salaries_other,
    CAST("SALARIES" AS DOUBLE) AS salaries,
    "BENEFITS_PERSONNEL" AS benefits_personnel,
    CAST("BENEFITS_PENSIONS" AS DOUBLE) AS benefits_pensions,
    CAST("BENEFITS_PAYROLL" AS DOUBLE) AS benefits_payroll,
    CAST("BENEFITS" AS DOUBLE) AS benefits,
    CAST("SALARIES_BENEFITS" AS DOUBLE) AS salaries_benefits,
    CAST("AIRCRAFT_FUEL" AS DOUBLE) AS aircraft_fuel,
    "MAINT_MATERIAL" AS maint_material,
    "FOOD" AS food,
    "OTHER_MATERIALS" AS other_materials,
    CAST("MATERIALS_TOTAL" AS DOUBLE) AS materials_total,
    "ADVERTISING" AS advertising,
    CAST("COMMUNICATION" AS DOUBLE) AS communication,
    CAST("INSURANCE" AS DOUBLE) AS insurance,
    "OUTSIDE_EQUIP" AS outside_equip,
    "COMMISIONS_PAX" AS commisions_pax,
    "COMMISSIONS_CARGO" AS commissions_cargo,
    CAST("OTHER_SERVICES" AS DOUBLE) AS other_services,
    CAST("SERVICES_TOTAL" AS DOUBLE) AS services_total,
    "LANDING_FEES" AS landing_fees,
    "RENTALS" AS rentals,
    CAST("DEPRECIATION" AS DOUBLE) AS depreciation,
    "AMORTIZATION" AS amortization,
    "OTHER" AS other,
    "TRANS_EXPENSE" AS trans_expense,
    "OP_EXPENSE" AS op_expense,
    CAST("AIRLINE_ID" AS BIGINT) AS airline_id,
    "UNIQUE_CARRIER" AS unique_carrier,
    "UNIQUE_CARRIER_NAME" AS unique_carrier_name,
    "CARRIER" AS carrier,
    "CARRIER_NAME" AS carrier_name,
    "UNIQUE_CARRIER_ENTITY" AS unique_carrier_entity,
    "REGION" AS region,
    CAST("CARRIER_GROUP_NEW" AS BIGINT) AS carrier_group_new,
    CAST("CARRIER_GROUP" AS BIGINT) AS carrier_group,
    CAST("YEAR" AS BIGINT) AS year,
    CAST("QUARTER" AS BIGINT) AS quarter,
    "obs_date",
    "obs_year",
    "obs_period"
FROM "bts-fme"
