-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("YEAR" AS BIGINT) AS year,
    CAST("QUARTER" AS BIGINT) AS quarter,
    CAST("MONTH" AS BIGINT) AS month,
    CAST("AIRLINE_ID" AS BIGINT) AS airline_id,
    "UNIQUE_CARRIER" AS unique_carrier,
    "CARRIER" AS carrier,
    "CARRIER_NAME" AS carrier_name,
    CAST("CARRIER_GROUP_NEW" AS BIGINT) AS carrier_group_new,
    CAST("SALA_GALLONS" AS DOUBLE) AS sala_gallons,
    CAST("SDOM_GALLONS" AS DOUBLE) AS sdom_gallons,
    CAST("SDOMT_GALLONS" AS DOUBLE) AS sdomt_gallons,
    CAST("SATL_GALLONS" AS DOUBLE) AS satl_gallons,
    CAST("SPAC_GALLONS" AS DOUBLE) AS spac_gallons,
    CAST("SLAT_GALLONS" AS DOUBLE) AS slat_gallons,
    CAST("SINT_GALLONS" AS DOUBLE) AS sint_gallons,
    CAST("TS_GALLONS" AS DOUBLE) AS ts_gallons,
    CAST("NALA_GALLONS" AS DOUBLE) AS nala_gallons,
    CAST("NDOM_GALLONS" AS DOUBLE) AS ndom_gallons,
    CAST("NDOMT_GALLONS" AS DOUBLE) AS ndomt_gallons,
    CAST("NATL_GALLONS" AS DOUBLE) AS natl_gallons,
    CAST("NPAC_GALLONS" AS DOUBLE) AS npac_gallons,
    CAST("NLAT_GALLONS" AS DOUBLE) AS nlat_gallons,
    CAST("MAC_GALLONS" AS DOUBLE) AS mac_gallons,
    CAST("NINT_GALLONS" AS DOUBLE) AS nint_gallons,
    CAST("TN_GALLONS" AS DOUBLE) AS tn_gallons,
    CAST("TDOMT_GALLONS" AS DOUBLE) AS tdomt_gallons,
    CAST("TINT_GALLONS" AS DOUBLE) AS tint_gallons,
    CAST("TOTAL_GALLONS" AS DOUBLE) AS total_gallons,
    CAST("SALA_COST" AS DOUBLE) AS sala_cost,
    CAST("SDOM_COST" AS DOUBLE) AS sdom_cost,
    CAST("SDOMT_COST" AS DOUBLE) AS sdomt_cost,
    CAST("SATL_COST" AS DOUBLE) AS satl_cost,
    CAST("SPAC_COST" AS DOUBLE) AS spac_cost,
    CAST("SLAT_COST" AS DOUBLE) AS slat_cost,
    CAST("SINT_COST" AS DOUBLE) AS sint_cost,
    CAST("TS_COST" AS DOUBLE) AS ts_cost,
    CAST("NALA_COST" AS DOUBLE) AS nala_cost,
    CAST("NDOM_COST" AS DOUBLE) AS ndom_cost,
    CAST("NDOMT_COST" AS DOUBLE) AS ndomt_cost,
    CAST("NATL_COST" AS DOUBLE) AS natl_cost,
    CAST("NPAC_COST" AS DOUBLE) AS npac_cost,
    CAST("NLAT_COST" AS DOUBLE) AS nlat_cost,
    CAST("MAC_COST" AS DOUBLE) AS mac_cost,
    CAST("NINT_COST" AS DOUBLE) AS nint_cost,
    CAST("TN_COST" AS DOUBLE) AS tn_cost,
    CAST("TDOMT_COST" AS DOUBLE) AS tdomt_cost,
    CAST("TINT_COST" AS DOUBLE) AS tint_cost,
    CAST("TOTAL_COST" AS DOUBLE) AS total_cost,
    "obs_date",
    "obs_year",
    "obs_period"
FROM "bts-fmh"
