-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "CASH" AS cash,
    "NOTES_ACC_REC_NET" AS notes_acc_rec_net,
    "CURR_ASSETS_OTH" AS curr_assets_oth,
    "CURR_ASSETS" AS curr_assets,
    "PROP_EQUIP_OWNED" AS prop_equip_owned,
    "DEPR_PROP_EQUIP" AS depr_prop_equip,
    "PROP_EQUIP_CAP_LS" AS prop_equip_cap_ls,
    "AMORT_PR_EQ_CAP_LS" AS amort_pr_eq_cap_ls,
    "PROP_EQUIP" AS prop_equip,
    "ASSETS_OTHER" AS assets_other,
    CAST("ASSETS" AS DOUBLE) AS assets,
    "NOTES_ACC_PAYABLE" AS notes_acc_payable,
    "ACCRUED_TAXES" AS accrued_taxes,
    "CURR_LIAB_OTHER" AS curr_liab_other,
    "CURR_LIABILITIES" AS curr_liabilities,
    "LONG_TERM_DEBT" AS long_term_debt,
    "OTH_LIABILITIES" AS oth_liabilities,
    "DEFERRED_CREDITS" AS deferred_credits,
    "PF_EQUITY" AS pf_equity,
    "PF_SHARES_NUM" AS pf_shares_num,
    "COM_EQUITY" AS com_equity,
    "COM_SHARES_NUM" AS com_shares_num,
    "PAID_IN_CAPITAL" AS paid_in_capital,
    "RET_EARNINGS" AS ret_earnings,
    "SH_HLD_EQUITY" AS sh_hld_equity,
    "TREAS_STOCK" AS treas_stock,
    "SH_HLD_EQUITY_NET" AS sh_hld_equity_net,
    CAST("LIAB_SH_HLD_EQUITY" AS DOUBLE) AS liab_sh_hld_equity,
    "AIRLINE_ID" AS airline_id,
    "UNIQUE_CARRIER" AS unique_carrier,
    "UNIQUE_CARRIER_NAME" AS unique_carrier_name,
    "CARRIER" AS carrier,
    "CARRIER_NAME" AS carrier_name,
    "UNIQUE_CARRIER_ENTITY" AS unique_carrier_entity,
    "REGION" AS region,
    "CARRIER_GROUP_NEW" AS carrier_group_new,
    "CARRIER_GROUP" AS carrier_group,
    CAST("YEAR" AS BIGINT) AS year,
    CAST("QUARTER" AS BIGINT) AS quarter,
    "obs_date",
    "obs_year",
    "obs_period"
FROM "bts-flf"
