-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "PILOT_FLY_OPS" AS pilot_fly_ops,
    "OTH_FLT_FLY_OPS" AS oth_flt_fly_ops,
    "TRAIN_FLY_OPS" AS train_fly_ops,
    "PERS_EXP_FLY_OPS" AS pers_exp_fly_ops,
    "PRO_FLY_OPS" AS pro_fly_ops,
    "INTERCHG_FLY_OPS" AS interchg_fly_ops,
    "FUEL_FLY_OPS" AS fuel_fly_ops,
    "OIL_FLY_OPS" AS oil_fly_ops,
    "RENTAL_FLY_OPS" AS rental_fly_ops,
    "OTHER_FLY_OPS" AS other_fly_ops,
    "INS_FLY_OPS" AS ins_fly_ops,
    "BENEFITS_FLY_OPS" AS benefits_fly_ops,
    "INCIDENT_FLY_OPS" AS incident_fly_ops,
    "PAY_TAX_FLY_OPS" AS pay_tax_fly_ops,
    "OTH_TAX_FLY_OPS" AS oth_tax_fly_ops,
    "OTHER_EXP_FLY_OPS" AS other_exp_fly_ops,
    "TOT_FLY_OPS" AS tot_fly_ops,
    "AIRFRAME_LABOR" AS airframe_labor,
    "ENGINE_LABOR" AS engine_labor,
    "AIRFRAME_REPAIR" AS airframe_repair,
    "ENGINE_REPAIRS" AS engine_repairs,
    "INTERCHG_CHARG" AS interchg_charg,
    "AIRFRAME_MATERIALS" AS airframe_materials,
    "ENGINE_MATERIALS" AS engine_materials,
    "AIRFRAME_ALLOW" AS airframe_allow,
    "AIRFRAME_OVERHAULS" AS airframe_overhauls,
    "ENGINE_ALLOW" AS engine_allow,
    "ENGINE_OVERHAULS" AS engine_overhauls,
    "TOT_DIR_MAINT" AS tot_dir_maint,
    "AP_MT_BURDEN" AS ap_mt_burden,
    "TOT_FLT_MAINT_MEMO" AS tot_flt_maint_memo,
    "NET_OBSOL_PARTS" AS net_obsol_parts,
    "AIRFRAME_DEP" AS airframe_dep,
    "ENGINE_DEP" AS engine_dep,
    "PARTS_DEP" AS parts_dep,
    "ENG_PARTS_DEP" AS eng_parts_dep,
    "OTH_FLT_EQUIP_DEP" AS oth_flt_equip_dep,
    "OTH_FLT_EQUIP_DEP_GRP_I" AS oth_flt_equip_dep_grp_i,
    "FLT_EQUIP_A_EXP" AS flt_equip_a_exp,
    "FLY_OPS_EXP_I_A" AS fly_ops_exp_i_a,
    "TOT_AIR_OP_EXPENSES" AS tot_air_op_expenses,
    "DEV_N_PREOP_EXP" AS dev_n_preop_exp,
    "OTH_INTANGIBLES" AS oth_intangibles,
    "EQUIP_N_HANGAR_DEP" AS equip_n_hangar_dep,
    "G_PROP_DEP" AS g_prop_dep,
    "CAP_LEASES_DEP" AS cap_leases_dep,
    "TOTAL_AIR_HOURS" AS total_air_hours,
    "AIR_DAYS_ASSIGN" AS air_days_assign,
    "AIR_FUELS_ISSUED" AS air_fuels_issued,
    CAST("AIRCRAFT_CONFIG" AS BIGINT) AS aircraft_config,
    CAST("AIRCRAFT_GROUP" AS BIGINT) AS aircraft_group,
    CAST("AIRCRAFT_TYPE" AS BIGINT) AS aircraft_type,
    CAST("AIRLINE_ID" AS BIGINT) AS airline_id,
    "UNIQUE_CARRIER" AS unique_carrier,
    "UNIQUE_CARRIER_NAME" AS unique_carrier_name,
    "CARRIER" AS carrier,
    "CARRIER_NAME" AS carrier_name,
    "UNIQUE_CARRIER_ENTITY" AS unique_carrier_entity,
    "REGION" AS region,
    CAST("CARRIER_GROUP_NEW" AS BIGINT) AS carrier_group_new,
    CAST("CARRIER_GROUP" AS BIGINT) AS carrier_group,
    CAST("YEAR" AS BIGINT) AS year,
    CAST("QUARTER" AS BIGINT) AS quarter,
    "obs_date",
    "obs_year",
    "obs_period"
FROM "bts-fmk"
