-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("YEAR" AS BIGINT) AS year,
    CAST("QUARTER" AS BIGINT) AS quarter,
    CAST("MONTH" AS BIGINT) AS month,
    CAST("AIRLINE_ID" AS BIGINT) AS airline_id,
    "UNIQUE_CARRIER" AS unique_carrier,
    "UNIQUE_CARRIER_NAME" AS unique_carrier_name,
    "UNIQUE_CARRIER_ENTITY" AS unique_carrier_entity,
    "REGION" AS region,
    "CARRIER" AS carrier,
    "CARRIER_NAME" AS carrier_name,
    CAST("CARRIER_GROUP" AS BIGINT) AS carrier_group,
    CAST("CARRIER_GROUP_NEW" AS BIGINT) AS carrier_group_new,
    "SERVICE_CLASS" AS service_class,
    "REV_PAX_ENP_110" AS rev_pax_enp_110,
    "REV_PAX_MILES_140" AS rev_pax_miles_140,
    "REV_PAX_MILES_COACH" AS rev_pax_miles_coach,
    "REV_PAX_MILES_FIRST" AS rev_pax_miles_first,
    "NON_REV_PAX_MILES" AS non_rev_pax_miles,
    "REV_TON_MILES_240" AS rev_ton_miles_240,
    "REV_TON_MILES_FREIGHT_247" AS rev_ton_miles_freight_247,
    "REV_TON_MILES_PAX_241" AS rev_ton_miles_pax_241,
    "REV_TON_MILES_USPR_MAIL" AS rev_ton_miles_uspr_mail,
    "REV_TON_MILES_USNONPR_MAIL" AS rev_ton_miles_usnonpr_mail,
    "REV_TON_MILES_MAIL_249" AS rev_ton_miles_mail_249,
    "REV_TON_MILES_FOREIGN_MAIL" AS rev_ton_miles_foreign_mail,
    "REV_TON_MILES_EXPRESS_MAIL" AS rev_ton_miles_express_mail,
    "NON_REV_TON_MILES" AS non_rev_ton_miles,
    "AVL_TON_MILES_280" AS avl_ton_miles_280,
    "AVL_SEAT_MILES_320" AS avl_seat_miles_320,
    "AVL_SEAT_MILES_FIRST" AS avl_seat_miles_first,
    "AVL_SEAT_MILES_COACH" AS avl_seat_miles_coach,
    "REV_ACRFT_MILES_FLOWN_410" AS rev_acrft_miles_flown_410,
    "REV_ACRFT_MILES_SCH_430" AS rev_acrft_miles_sch_430,
    "REV_ACRFT_MILES_SCH_COMPLETED" AS rev_acrft_miles_sch_completed,
    "REV_ACRFT_DEP_PERF_510" AS rev_acrft_dep_perf_510,
    "REV_ACRFT_HRS_AIRBORNE_610" AS rev_acrft_hrs_airborne_610,
    "ACRFT_HRS_RAMPTORAMP_630" AS acrft_hrs_ramptoramp_630,
    "obs_date",
    "obs_year",
    "obs_period"
FROM "bts-fjh"
