-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("AIR_OP_EXPENSE" AS DOUBLE) AS air_op_expense,
    "FL_ATT_EXPENSE" AS fl_att_expense,
    "FOOD_EXPENSE" AS food_expense,
    "OTH_IN_FL_EXPENSE" AS oth_in_fl_expense,
    "PAX_SVC_EXPENSE" AS pax_svc_expense,
    "LINE_SVC_EXPENSE" AS line_svc_expense,
    CAST("CONTROL_EXPENSE" AS DOUBLE) AS control_expense,
    CAST("LANDING_FEES" AS DOUBLE) AS landing_fees,
    CAST("AIR_SVC_EXPENSE" AS DOUBLE) AS air_svc_expense,
    "TRAFFIC_EXP_PAX" AS traffic_exp_pax,
    CAST("TRAFFIC_EXP_CARGO" AS DOUBLE) AS traffic_exp_cargo,
    "TRAFFIC_EXP_OTH" AS traffic_exp_oth,
    CAST("TRAFFIC_EXPENSE" AS DOUBLE) AS traffic_expense,
    "RES_EXP_PAX" AS res_exp_pax,
    CAST("RES_EXP_CARGO" AS DOUBLE) AS res_exp_cargo,
    "RES_EXP_OTH" AS res_exp_oth,
    CAST("RES_EXPENSE" AS DOUBLE) AS res_expense,
    "AD_EXP_PAX" AS ad_exp_pax,
    "AD_EXP_CARGO" AS ad_exp_cargo,
    "AD_EXP_INST" AS ad_exp_inst,
    CAST("AD_EXPENSE" AS DOUBLE) AS ad_expense,
    CAST("ADMIN_EXPENSE" AS DOUBLE) AS admin_expense,
    "DEPR_EXP_MAINT" AS depr_exp_maint,
    "AMORTIZATION" AS amortization,
    CAST("TRANSPORT_EXP" AS DOUBLE) AS transport_exp,
    CAST("TOTAL_OP_EXPENSE" AS DOUBLE) AS total_op_expense,
    CAST("MAINT_PROP_EQUIP" AS DOUBLE) AS maint_prop_equip,
    CAST("DEPR_PROP_EQUIP" AS DOUBLE) AS depr_prop_equip,
    CAST("MAINT_DEPR" AS DOUBLE) AS maint_depr,
    CAST("SVC_SALES_OP_EXP" AS DOUBLE) AS svc_sales_op_exp,
    CAST("AIRLINE_ID" AS BIGINT) AS airline_id,
    "UNIQUE_CARRIER" AS unique_carrier,
    "UNIQUE_CARRIER_NAME" AS unique_carrier_name,
    "CARRIER" AS carrier,
    "CARRIER_NAME" AS carrier_name,
    "UNIQUE_CARRIER_ENTITY" AS unique_carrier_entity,
    "REGION" AS region,
    CAST("CARRIER_GROUP_NEW" AS BIGINT) AS carrier_group_new,
    CAST("CARRIER_GROUP" AS BIGINT) AS carrier_group,
    CAST("YEAR" AS BIGINT) AS year,
    CAST("QUARTER" AS BIGINT) AS quarter,
    "obs_date",
    "obs_year",
    "obs_period"
FROM "bts-fkl"
