-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "archive_member",
    "row_number",
    "LEA_STATE" AS lea_state,
    "LEA_STATE_NAME" AS lea_state_name,
    "LEAID" AS leaid,
    "LEA_NAME" AS lea_name,
    "LEA_ADDRESS" AS lea_address,
    "LEA_CITY" AS lea_city,
    "LEA_ZIP" AS lea_zip,
    "CJJ" AS cjj,
    "LEA_DISTED_IND" AS lea_disted_ind,
    "LEA_DISTEDENR_HI_M" AS lea_distedenr_hi_m,
    "LEA_DISTEDENR_HI_F" AS lea_distedenr_hi_f,
    "LEA_DISTEDENR_AM_M" AS lea_distedenr_am_m,
    "LEA_DISTEDENR_AM_F" AS lea_distedenr_am_f,
    "LEA_DISTEDENR_AS_M" AS lea_distedenr_as_m,
    "LEA_DISTEDENR_AS_F" AS lea_distedenr_as_f,
    "LEA_DISTEDENR_HP_M" AS lea_distedenr_hp_m,
    "LEA_DISTEDENR_HP_F" AS lea_distedenr_hp_f,
    "LEA_DISTEDENR_BL_M" AS lea_distedenr_bl_m,
    "LEA_DISTEDENR_BL_F" AS lea_distedenr_bl_f,
    "LEA_DISTEDENR_WH_M" AS lea_distedenr_wh_m,
    "LEA_DISTEDENR_WH_F" AS lea_distedenr_wh_f,
    "LEA_DISTEDENR_TR_M" AS lea_distedenr_tr_m,
    "LEA_DISTEDENR_TR_F" AS lea_distedenr_tr_f,
    "TOT_DISTEDENR_M" AS tot_distedenr_m,
    "TOT_DISTEDENR_F" AS tot_distedenr_f,
    "LEA_DISTEDENR_LEP_M" AS lea_distedenr_lep_m,
    "LEA_DISTEDENR_LEP_F" AS lea_distedenr_lep_f,
    "LEA_DISTEDENR_IDEA_M" AS lea_distedenr_idea_m,
    "LEA_DISTEDENR_IDEA_F" AS lea_distedenr_idea_f,
    "LEA_HSE_IND" AS lea_hse_ind,
    "LEA_HSEPART_HI_M" AS lea_hsepart_hi_m,
    "LEA_HSEPART_HI_F" AS lea_hsepart_hi_f,
    "LEA_HSEPART_AM_M" AS lea_hsepart_am_m,
    "LEA_HSEPART_AM_F" AS lea_hsepart_am_f,
    "LEA_HSEPART_AS_M" AS lea_hsepart_as_m,
    "LEA_HSEPART_AS_F" AS lea_hsepart_as_f,
    "LEA_HSEPART_HP_M" AS lea_hsepart_hp_m,
    "LEA_HSEPART_HP_F" AS lea_hsepart_hp_f,
    "LEA_HSEPART_BL_M" AS lea_hsepart_bl_m,
    "LEA_HSEPART_BL_F" AS lea_hsepart_bl_f,
    "LEA_HSEPART_WH_M" AS lea_hsepart_wh_m,
    "LEA_HSEPART_WH_F" AS lea_hsepart_wh_f,
    "LEA_HSEPART_TR_M" AS lea_hsepart_tr_m,
    "LEA_HSEPART_TR_F" AS lea_hsepart_tr_f,
    "TOT_HSEPART_M" AS tot_hsepart_m,
    "TOT_HSEPART_F" AS tot_hsepart_f,
    "LEA_HSEPART_LEP_M" AS lea_hsepart_lep_m,
    "LEA_HSEPART_LEP_F" AS lea_hsepart_lep_f,
    "LEA_HSEPART_IDEA_M" AS lea_hsepart_idea_m,
    "LEA_HSEPART_IDEA_F" AS lea_hsepart_idea_f
FROM "u-s-department-of-education-civil-rights-data-collection-crdc-for-the-2017-18-school-year"
