-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "sheet_name",
    "row_number",
    "This sortable and filterable list consists of institutions of higher education (IHE) that currently hold an open grant under AANAPISI and AANAPISI-F programs and/or meet the Title III definition of an AANAPISI in Fiscal Year 2023. Being a current grantee or meeting the definition does not automatically make the IHE eligible for new program funding. The IHE should consult with the program office responsible for the specific grant program. Additionally, while an institution may be identified on multiple lists in this document, there are statutory requirements that may prohibit an institution’s grant participation between one or more of the programs." AS this_sortable_and_filterable_list_consists_of_institutions_of_higher_education_ihe_that_currently_hold_an_open_grant_under_aanapisi_and_aanapisi_f_programs_and_or_meet_the_title_iii_definition_of_an_aanapisi_in_fiscal_year_2023_being_a_current_grantee_or_meeting_the_definition_does_not_automatically_make_the_ihe_eligible_for_new_program_funding_the_ihe_should_consult_with_the_program_office_responsible_for_the_specific_grant_program_additionally_while_an_institution_may_be_identified_on_multiple_lists_in_this_document_there_are_statutory_requirements_that_may_prohibit_an_institution_s_grant_participation_between_one_or_more_of_the_programs,
    "Unnamed: 1" AS unnamed_1,
    "Unnamed: 2" AS unnamed_2,
    "Unnamed: 3" AS unnamed_3,
    "Unnamed: 4" AS unnamed_4,
    "Unnamed: 5" AS unnamed_5,
    "Unnamed: 6" AS unnamed_6,
    "Note: Institutions may appear in more than one list." AS note_institutions_may_appear_in_more_than_one_list,
    "Unnamed: 8" AS unnamed_8,
    "Unnamed: 9" AS unnamed_9,
    "Unnamed: 10" AS unnamed_10,
    "This sortable and filterable list consists of institutions of higher education (IHE) that currently hold an open grant under ANNH and ANNH-F programs and/or meet the Title III definition of an ANNH in Fiscal Year 2023. Being a current grantee or meeting the definition does not automatically make the IHE eligible for new program funding. The IHE should consult with the program office responsible for the specific grant program. Additionally, while an institution may be identified on multiple lists in this document, there are statutory requirements that may prohibit an institution’s grant participation between one or more of the programs." AS this_sortable_and_filterable_list_consists_of_institutions_of_higher_education_ihe_that_currently_hold_an_open_grant_under_annh_and_annh_f_programs_and_or_meet_the_title_iii_definition_of_an_annh_in_fiscal_year_2023_being_a_current_grantee_or_meeting_the_definition_does_not_automatically_make_the_ihe_eligible_for_new_program_funding_the_ihe_should_consult_with_the_program_office_responsible_for_the_specific_grant_program_additionally_while_an_institution_may_be_identified_on_multiple_lists_in_this_document_there_are_statutory_requirements_that_may_prohibit_an_institution_s_grant_participation_between_one_or_more_of_the_programs,
    "This sortable and filterable list consists of institutions of higher education (IHE) that currently hold an open grant under HSI, HSI-STEM, and PPOHA programs and/or meet the Title V definition of an HSI in Fiscal Year 2023. Being a current grantee or meeting the definition does not automatically make the IHE eligible for new program funding. The IHE should consult with the program office responsible for the specific grant program. Additionally, while an institution may be identified on multiple lists in this document, there are statutory requirements that may prohibit an institution’s grant participation between one or more of the programs." AS this_sortable_and_filterable_list_consists_of_institutions_of_higher_education_ihe_that_currently_hold_an_open_grant_under_hsi_hsi_stem_and_ppoha_programs_and_or_meet_the_title_v_definition_of_an_hsi_in_fiscal_year_2023_being_a_current_grantee_or_meeting_the_definition_does_not_automatically_make_the_ihe_eligible_for_new_program_funding_the_ihe_should_consult_with_the_program_office_responsible_for_the_specific_grant_program_additionally_while_an_institution_may_be_identified_on_multiple_lists_in_this_document_there_are_statutory_requirements_that_may_prohibit_an_institution_s_grant_participation_between_one_or_more_of_the_programs,
    "Unnamed: 11" AS unnamed_11,
    "This sortable and filterable list consists of institutions of higher education (IHE) that currently hold an open grant under NASNTI and NASNTI-F programs and/or meet the Title III definition of a NASNTI in Fiscal Year 2023. Being a current grantee or meeting the definition does not automatically make the IHE eligible for new program funding. The IHE should consult with the program office responsible for the specific grant program. Additionally, while an institution may be identified on multiple lists in this document, there are statutory requirements that may prohibit an institution’s grant participation between one or more of the programs." AS this_sortable_and_filterable_list_consists_of_institutions_of_higher_education_ihe_that_currently_hold_an_open_grant_under_nasnti_and_nasnti_f_programs_and_or_meet_the_title_iii_definition_of_a_nasnti_in_fiscal_year_2023_being_a_current_grantee_or_meeting_the_definition_does_not_automatically_make_the_ihe_eligible_for_new_program_funding_the_ihe_should_consult_with_the_program_office_responsible_for_the_specific_grant_program_additionally_while_an_institution_may_be_identified_on_multiple_lists_in_this_document_there_are_statutory_requirements_that_may_prohibit_an_institution_s_grant_participation_between_one_or_more_of_the_programs,
    "This sortable and filterable list consists of institutions of higher education (IHE) that currently hold an open grant under PBI and PBI-F programs and/or partially meet the Title III definition of a PBI in Fiscal Year 2023. Being a current grantee or meeting the definition does not automatically make the IHE eligible for new program funding. The IHE should consult with the program office responsible for the specific grant program. Additionally, while an institution may be identified on multiple lists in this document, there are statutory requirements that may prohibit an institution’s grant participation between one or more of the programs." AS this_sortable_and_filterable_list_consists_of_institutions_of_higher_education_ihe_that_currently_hold_an_open_grant_under_pbi_and_pbi_f_programs_and_or_partially_meet_the_title_iii_definition_of_a_pbi_in_fiscal_year_2023_being_a_current_grantee_or_meeting_the_definition_does_not_automatically_make_the_ihe_eligible_for_new_program_funding_the_ihe_should_consult_with_the_program_office_responsible_for_the_specific_grant_program_additionally_while_an_institution_may_be_identified_on_multiple_lists_in_this_document_there_are_statutory_requirements_that_may_prohibit_an_institution_s_grant_participation_between_one_or_more_of_the_programs,
    "Unnamed: 7" AS unnamed_7,
    "PLEASE NOTE: The PBI program requires additional data during the pre-award period to ensure that all PBI requirements are met. The preliminary lists only looks at two PBI requirements. Institutions that are on this list are not guaranteed to receive PBI funding. Additional data should be collected based on the statutory requirements." AS please_note_the_pbi_program_requires_additional_data_during_the_pre_award_period_to_ensure_that_all_pbi_requirements_are_met_the_preliminary_lists_only_looks_at_two_pbi_requirements_institutions_that_are_on_this_list_are_not_guaranteed_to_receive_pbi_funding_additional_data_should_be_collected_based_on_the_statutory_requirements,
    "Unnamed: 0" AS unnamed_0,
    "2023 HBCU/HBGIs = 101" AS 2023_hbcu_hbgis_101,
    "2023 TCCUs = 35" AS 2023_tccus_35,
    "This sortable and filterable list consists of institutions of higher education (IHE) that currently hold an open grant under SIP programs and/or meet the Title III definition of an eligible institution in Fiscal Year 2023. Being a current grantee or meeting the definition does not automatically make the IHE eligible for new program funding. The IHE should consult with the program office responsible for the specific grant program. Additionally, while an institution may be identified on multiple lists in this document, there are statutory requirements that may prohibit an institution’s grant participation between one or more of the programs." AS this_sortable_and_filterable_list_consists_of_institutions_of_higher_education_ihe_that_currently_hold_an_open_grant_under_sip_programs_and_or_meet_the_title_iii_definition_of_an_eligible_institution_in_fiscal_year_2023_being_a_current_grantee_or_meeting_the_definition_does_not_automatically_make_the_ihe_eligible_for_new_program_funding_the_ihe_should_consult_with_the_program_office_responsible_for_the_specific_grant_program_additionally_while_an_institution_may_be_identified_on_multiple_lists_in_this_document_there_are_statutory_requirements_that_may_prohibit_an_institution_s_grant_participation_between_one_or_more_of_the_programs,
    "Pending an institution of higher education meets the requirements for Titles III, V, and VII eligibility, the following could still happen." AS pending_an_institution_of_higher_education_meets_the_requirements_for_titles_iii_v_and_vii_eligibility_the_following_could_still_happen,
    "Unnamed: 12" AS unnamed_12,
    "Unnamed: 13" AS unnamed_13,
    "Unnamed: 14" AS unnamed_14,
    "Unnamed: 15" AS unnamed_15,
    "Unnamed: 16" AS unnamed_16,
    "Unnamed: 17" AS unnamed_17,
    "Unnamed: 18" AS unnamed_18,
    "Unnamed: 19" AS unnamed_19,
    "Unnamed: 20" AS unnamed_20,
    "Unnamed: 21" AS unnamed_21,
    "Unnamed: 22" AS unnamed_22,
    "Unnamed: 23" AS unnamed_23,
    "PLEASE NOTE: The PBI program requires additional data during the pre-award period to ensure that all PBI requirements are met. The prelimary lists only looks at two PBI requirements." AS please_note_the_pbi_program_requires_additional_data_during_the_pre_award_period_to_ensure_that_all_pbi_requirements_are_met_the_prelimary_lists_only_looks_at_two_pbi_requirements,
    "Yes = 100" AS yes_100,
    "Yes = 35" AS yes_35,
    "Eligibility Code" AS eligibility_code,
    "Unnamed: 24" AS unnamed_24,
    "Unnamed: 25" AS unnamed_25,
    "Unnamed: 26" AS unnamed_26,
    "Unnamed: 27" AS unnamed_27,
    "Unnamed: 28" AS unnamed_28,
    "Unnamed: 29" AS unnamed_29,
    "Unnamed: 30" AS unnamed_30,
    "Unnamed: 31" AS unnamed_31,
    "Unnamed: 32" AS unnamed_32,
    "Unnamed: 33" AS unnamed_33,
    "Unnamed: 34" AS unnamed_34,
    "Unnamed: 35" AS unnamed_35,
    "Unnamed: 36" AS unnamed_36,
    "Unnamed: 37" AS unnamed_37,
    "Unnamed: 38" AS unnamed_38,
    "Unnamed: 39" AS unnamed_39,
    "Unnamed: 40" AS unnamed_40,
    "Unnamed: 41" AS unnamed_41,
    "Unnamed: 42" AS unnamed_42,
    "Unnamed: 43" AS unnamed_43,
    "Unnamed: 44" AS unnamed_44,
    "Unnamed: 45" AS unnamed_45,
    "Unnamed: 46" AS unnamed_46,
    "Unnamed: 47" AS unnamed_47,
    "Unnamed: 48" AS unnamed_48,
    "Unnamed: 49" AS unnamed_49,
    "Unnamed: 50" AS unnamed_50,
    "Unnamed: 51" AS unnamed_51,
    "Unnamed: 52" AS unnamed_52,
    "Unnamed: 53" AS unnamed_53,
    "_subsets_record_type" AS subsets_record_type,
    "error",
    "State" AS state,
    "Title III and Title V Eligible Institutions" AS title_iii_and_title_v_eligible_institutions,
    "City" AS city
FROM "u-s-department-of-education-request-for-designation-as-an-eligible-institution-and-waiver-of-the-non-federal-cost-shar-a210f"
