-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "archive_member",
    "row_number",
    "100654",
    "Alabama A & M University" AS alabama_a_m_university,
    "4900 Meridian Street" AS 4900_meridian_street,
    "Normal" AS normal,
    "AL" AS al,
    "35762",
    "01",
    "01089",
    "Madison County" AS madison_county,
    "12",
    "34.783368" AS 34_783368,
    "-86.568502" AS 86_568502,
    "26620",
    "Huntsville, AL" AS huntsville_al,
    "1",
    "290",
    "Huntsville-Decatur, AL" AS huntsville_decatur_al,
    "N" AS n,
    "N.1" AS n_1,
    "0105",
    "01019",
    "01007",
    "2019-2020" AS 2019_2020,
    "sheet_name",
    "UNITID" AS unitid,
    "NAME" AS name,
    "STREET" AS street,
    "CITY" AS city,
    "STATE" AS state,
    "ZIP" AS zip,
    "STFIP" AS stfip,
    "CNTY" AS cnty,
    "NMCNTY" AS nmcnty,
    "LOCALE" AS locale,
    "LAT" AS lat,
    "LON" AS lon,
    "CBSA" AS cbsa,
    "NMCBSA" AS nmcbsa,
    "CBSATYPE" AS cbsatype,
    "CSA" AS csa,
    "NMCSA" AS nmcsa,
    "NECTA" AS necta,
    "NMNECTA" AS nmnecta,
    "CD" AS cd,
    "SLDL" AS sldl,
    "SLDU" AS sldu,
    "SCHOOLYEAR" AS schoolyear,
    "X" AS x,
    "Y" AS y,
    "OBJECTID" AS objectid
FROM "u-s-department-of-education-postsecondary-school-locations-2019-20"
