-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "sheet_name",
    "row_number",
    "FY 2019 SIP Awardees" AS fy_2019_sip_awardees,
    "Unnamed: 1" AS unnamed_1,
    "Unnamed: 2" AS unnamed_2,
    "84.031A" AS 84_031a,
    "Unnamed: 3" AS unnamed_3,
    "Unnamed: 4" AS unnamed_4,
    "Unnamed: 5" AS unnamed_5,
    "84.031F" AS 84_031f,
    "Unnamed: 7" AS unnamed_7,
    "Unnamed: 8" AS unnamed_8,
    "Unnamed: 9" AS unnamed_9,
    "Unnamed: 6" AS unnamed_6,
    "Unnamed: 10" AS unnamed_10,
    "Unnamed: 11" AS unnamed_11,
    "Unnamed: 12" AS unnamed_12,
    "Award #" AS award,
    "Title III Part A Institution" AS title_iii_part_a_institution,
    "State" AS state,
    "FY 2016 Awards" AS fy_2016_awards,
    "Institution" AS institution,
    "FY 2015 Award" AS fy_2015_award,
    "Year 2" AS year_2,
    "Year 3" AS year_3,
    "Year 4" AS year_4,
    "Year 5" AS year_5,
    "Fiscal Year" AS fiscal_year,
    "Schedule No" AS schedule_no,
    "PO" AS po,
    "CFDA/Subprogram" AS cfda_subprogram,
    "Action Type" AS action_type,
    "Funding Status" AS funding_status,
    "Rank" AS rank,
    "PR Award Number" AS pr_award_number,
    "Average Raw Score" AS average_raw_score,
    "Average Standard Score" AS average_standard_score,
    "FY 2014 Funds" AS fy_2014_funds,
    "PR Number" AS pr_number,
    "Title III Part A Grantee" AS title_iii_part_a_grantee,
    "FY 2012 Award" AS fy_2012_award,
    "Unnamed: 0" AS unnamed_0,
    "PR NUMBER_1" AS pr_number_1,
    "GRANTEE" AS grantee,
    "STATE_1" AS state_1,
    "FY 2011 AWARD" AS fy_2011_award
FROM "u-s-department-of-education-awards-title-iii-part-a-programs-strengthening-institutions-ab4ae"
