-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "sheet_name",
    "row_number",
    "AE" AS ae,
    "AFNORTH HIGH SCHOOL" AS afnorth_high_school,
    "APO" AS apo,
    "09703",
    "AP" AS ap,
    "AEIS" AS aeis,
    "96367",
    "AS" AS as,
    "AUA ELEMENTARY SCHOOL" AS aua_elementary_school,
    "PAGO PAGO" AS pago_pago,
    "96799",
    "GU" AS gu,
    "ADACAO ELEMENTARY" AS adacao_elementary,
    "HAGATNA" AS hagatna,
    "96932",
    "MP" AS mp,
    "CHACHA OCEAN VIEW MIDDLE SCHOOL" AS chacha_ocean_view_middle_school,
    "SAIPAN" AS saipan,
    "96950",
    "PR" AS pr,
    "ACADEMIA MARIA REINA" AS academia_maria_reina,
    "SAN JUAN" AS san_juan,
    "00921",
    "Unnamed: 0" AS unnamed_0,
    "Unnamed: 1" AS unnamed_1,
    "Unnamed: 2" AS unnamed_2,
    "AL" AS al,
    "AC MOORE ELEMENTARY SCHOOL" AS ac_moore_elementary_school,
    "ATMORE" AS atmore,
    "36502",
    "AK" AS ak,
    "ALASKA GATEWAY REAA #16" AS alaska_gateway_reaa_16,
    "TOK" AS tok,
    "99780",
    "AZ" AS az,
    "AAEC EARLY COLLEGE HIGHSCHOOL" AS aaec_early_college_highschool,
    "PHOENIX" AS phoenix,
    "85042",
    "AR" AS ar,
    "ACADEMIES OF WEST MEMPHIS" AS academies_of_west_memphis,
    "WEST MEMPHIS" AS west_memphis,
    "72301",
    "CA" AS ca,
    "107TH STREET ELEMENTARY" AS 107th_street_elementary,
    "LOS ANGELES" AS los_angeles,
    "90003",
    "CO" AS co,
    "ACADEMY INTERNATIONAL ELEMENTARY SCHOOL" AS academy_international_elementary_school,
    "COLORADO SPRINGS" AS colorado_springs,
    "80918",
    "CT" AS ct,
    "ABRAHAM PIERSON SCHOOL" AS abraham_pierson_school,
    "CLINTON" AS clinton,
    "06413",
    "DE" AS de,
    "ALL SAINTS CATHOLIC SCHOOL" AS all_saints_catholic_school,
    "ELSMERE" AS elsmere,
    "19805",
    "DC" AS dc,
    "BROOKLAND MIDDLE SCHOOL" AS brookland_middle_school,
    "WASHINGTON" AS washington,
    "20017",
    "FL" AS fl,
    "A BEKA ACADEMY" AS a_beka_academy,
    "PENSACOLA" AS pensacola,
    "32503",
    "GA" AS ga,
    "AARON COHN MIDDLE SCHOOL" AS aaron_cohn_middle_school,
    "MIDLAND" AS midland,
    "31820",
    "HI" AS hi,
    "AHUIMANU ELEMENTARY" AS ahuimanu_elementary,
    "KANEOHU" AS kaneohu,
    "96744",
    "State" AS state,
    "School" AS school,
    "City" AS city,
    "Postal Code" AS postal_code,
    "Gold Qty" AS gold_qty,
    "Silver Qty" AS silver_qty
FROM "u-s-department-of-education-2017-awards-presidents-education-awards-program"
