-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "sheet_name",
    "row_number",
    "SPD CODE" AS spd_code,
    "School Participation Division" AS school_participation_division,
    "OPE ID" AS ope_id,
    "Institution Name" AS institution_name,
    "City" AS city,
    "ST" AS st,
    "ELIG" AS elig,
    "Close Date" AS close_date,
    "Link to FPRD" AS link_to_fprd,
    "PRN" AS prn,
    "REVIEW YR" AS review_yr,
    "REVIEW AWARD YR1" AS review_award_yr1,
    "REVIEW AWARD YR2" AS review_award_yr2,
    "REVIEW AWARD YR3" AS review_award_yr3,
    "FPRD Date" AS fprd_date,
    "EDL Date" AS edl_date,
    "FPRD/EDL Date" AS fprd_edl_date,
    "QTR EDL/FPRD Issued" AS qtr_edl_fprd_issued,
    "2113",
    "2431",
    "2113 or 2431" AS 2113_or_2431,
    "Final Audit Determinations (FADs)" AS final_audit_determinations_fads,
    "Unnamed: 1" AS unnamed_1,
    "Unnamed: 2" AS unnamed_2,
    "Unnamed: 3" AS unnamed_3,
    "Unnamed: 4" AS unnamed_4,
    "Unnamed: 5" AS unnamed_5,
    "Unnamed: 6" AS unnamed_6,
    "Unnamed: 7" AS unnamed_7,
    "Unnamed: 8" AS unnamed_8,
    "Unnamed: 9" AS unnamed_9,
    "FPRDs Summary by Month for the FY 2020 Date as of 08-03-2020" AS fprds_summary_by_month_for_the_fy_2020_date_as_of_08_03_2020,
    "Unnamed: 10" AS unnamed_10,
    "Unnamed: 11" AS unnamed_11,
    "Unnamed: 12" AS unnamed_12,
    "Unnamed: 13" AS unnamed_13,
    "Unnamed: 14" AS unnamed_14,
    "Unnamed: 15" AS unnamed_15,
    "Unnamed: 16" AS unnamed_16,
    "Final Program Review Determinations (FPRDs)" AS final_program_review_determinations_fprds,
    "Unnamed: 0" AS unnamed_0,
    "Clery Findings" AS clery_findings,
    "FPRDs Summary by Month for the FY 2019 Date as of 10-02-2019" AS fprds_summary_by_month_for_the_fy_2019_date_as_of_10_02_2019,
    "Audit Information" AS audit_information,
    "Program Reviews Summary by Month for the FY 2018 Date as of 11-05-2018" AS program_reviews_summary_by_month_for_the_fy_2018_date_as_of_11_05_2018,
    "Program Reviews" AS program_reviews,
    "File Location" AS file_location,
    "FIRSTSCHOOL NAME" AS firstschool_name,
    "INSTITUTION NAME_1" AS institution_name_1,
    "OPEID" AS opeid,
    "CITY_1" AS city_1,
    "STATE" AS state,
    "Program Review Control Number" AS program_review_control_number,
    "YEAR(S) REVIEWED" AS year_s_reviewed,
    "Fiscal Year Issued" AS fiscal_year_issued,
    "SCHOOL NAME" AS school_name,
    "Part 86: 2431" AS part_86_2431,
    "Count of Notes 12-27-13" AS count_of_notes_12_27_13,
    "Clery" AS clery,
    "Notes 12-27-13" AS notes_12_27_13,
    "Notes 12-30-13" AS notes_12_30_13
FROM "u-s-department-of-education-program-reviews"
