-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "sheet_name",
    "row_number",
    "FOIA Annual Report Raw Data for the period 10/01/2017 to 09/30/2018" AS foia_annual_report_raw_data_for_the_period_10_01_2017_to_09_30_2018,
    "Unnamed: 1" AS unnamed_1,
    "Unnamed: 2" AS unnamed_2,
    "Unnamed: 3" AS unnamed_3,
    "Unnamed: 4" AS unnamed_4,
    "Unnamed: 5" AS unnamed_5,
    "Unnamed: 6" AS unnamed_6,
    "Unnamed: 7" AS unnamed_7,
    "Unnamed: 8" AS unnamed_8,
    "Unnamed: 9" AS unnamed_9,
    "Unnamed: 10" AS unnamed_10,
    "Unnamed: 11" AS unnamed_11,
    "Unnamed: 12" AS unnamed_12,
    "Unnamed: 13" AS unnamed_13,
    "Unnamed: 14" AS unnamed_14,
    "Unnamed: 15" AS unnamed_15,
    "Unnamed: 16" AS unnamed_16,
    "Unnamed: 17" AS unnamed_17,
    "Unnamed: 18" AS unnamed_18,
    "Unnamed: 19" AS unnamed_19,
    "Unnamed: 20" AS unnamed_20,
    "Unnamed: 21" AS unnamed_21,
    "Unnamed: 22" AS unnamed_22,
    "Unnamed: 23" AS unnamed_23,
    "Unnamed: 24" AS unnamed_24,
    "Unnamed: 25" AS unnamed_25,
    "Unnamed: 26" AS unnamed_26,
    "Unnamed: 27" AS unnamed_27,
    "Unnamed: 28" AS unnamed_28,
    "Unnamed: 29" AS unnamed_29,
    "Action Office" AS action_office,
    "Request Number" AS request_number,
    "Request Type" AS request_type,
    "Multi-Track Type" AS multi_track_type,
    "Request Status" AS request_status,
    "Original Received Date" AS original_received_date,
    "Received Date" AS received_date,
    "Perfected Date" AS perfected_date,
    "Closed Date" AS closed_date,
    "Target Date" AS target_date,
    "Amended Date" AS amended_date,
    "Request Age" AS request_age,
    "Processed Days" AS processed_days,
    "Days Allowed" AS days_allowed,
    "Days on Hold" AS days_on_hold,
    "Final Disposition" AS final_disposition,
    "Reportable Other Code" AS reportable_other_code,
    "Exemptions Applied" AS exemptions_applied,
    "Exemption 3 Statutes" AS exemption_3_statutes,
    "Case Citation" AS case_citation,
    "Is Backlogged" AS is_backlogged,
    "Is Expedite Requested" AS is_expedite_requested,
    "Expedite Start Date" AS expedite_start_date,
    "Expedite End Date" AS expedite_end_date,
    "Number of Days to Adjudicate" AS number_of_days_to_adjudicate,
    "Expedite Status" AS expedite_status,
    "Is Fee Waiver Requested" AS is_fee_waiver_requested,
    "Fee Waiver Start Date" AS fee_waiver_start_date,
    "Fee Waiver End Date" AS fee_waiver_end_date,
    "Number of Days to Adjudicate.1" AS number_of_days_to_adjudicate_1,
    "Fee Waiver Status" AS fee_waiver_status,
    "Fees Collected" AS fees_collected,
    "Is This A Consultation? (Y/N)" AS is_this_a_consultation_y_n,
    "Department of Education FOIA Annual Report Raw Data for the period 10/01/2015 to 09/30/2016" AS department_of_education_foia_annual_report_raw_data_for_the_period_10_01_2015_to_09_30_2016
FROM "u-s-department-of-education-freedom-of-information-act-foia-annual-reports-office-of-management"
