-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "archive_member",
    "row_number",
    "SCHOOL_YEAR" AS school_year,
    "FIPST" AS fipst,
    "STATENAME" AS statename,
    "ST" AS st,
    "LEA_NAME" AS lea_name,
    "STATE_AGENCY_NO" AS state_agency_no,
    "UNION" AS union,
    "ST_LEAID" AS st_leaid,
    "LEAID" AS leaid,
    "MSTREET1" AS mstreet1,
    "MSTREET2" AS mstreet2,
    "MSTREET3" AS mstreet3,
    "MCITY" AS mcity,
    "MSTATE" AS mstate,
    "MZIP" AS mzip,
    "MZIP4" AS mzip4,
    "LSTREET1" AS lstreet1,
    "LSTREET2" AS lstreet2,
    "LSTREET3" AS lstreet3,
    "LCITY" AS lcity,
    "LSTATE" AS lstate,
    "LZIP" AS lzip,
    "LZIP4" AS lzip4,
    "PHONE" AS phone,
    "WEBSITE" AS website,
    "SY_STATUS" AS sy_status,
    "SY_STATUS_TEXT" AS sy_status_text,
    "UPDATED_STATUS" AS updated_status,
    "UPDATED_STATUS_TEXT" AS updated_status_text,
    "EFFECTIVE_DATE" AS effective_date,
    "LEA_TYPE" AS lea_type,
    "LEA_TYPE_TEXT" AS lea_type_text,
    "OUT_OF_STATE_FLAG" AS out_of_state_flag,
    "CHARTER_LEA" AS charter_lea,
    "CHARTER_LEA_TEXT" AS charter_lea_text,
    "NOGRADES" AS nogrades,
    "G_PK_OFFERED" AS g_pk_offered,
    "G_KG_OFFERED" AS g_kg_offered,
    "G_1_OFFERED" AS g_1_offered,
    "G_2_OFFERED" AS g_2_offered,
    "G_3_OFFERED" AS g_3_offered,
    "G_4_OFFERED" AS g_4_offered,
    "G_5_OFFERED" AS g_5_offered,
    "G_6_OFFERED" AS g_6_offered,
    "G_7_OFFERED" AS g_7_offered,
    "G_8_OFFERED" AS g_8_offered,
    "G_9_OFFERED" AS g_9_offered,
    "G_10_OFFERED" AS g_10_offered,
    "G_11_OFFERED" AS g_11_offered,
    "G_12_OFFERED" AS g_12_offered,
    "G_13_OFFERED" AS g_13_offered,
    "G_UG_OFFERED" AS g_ug_offered,
    "G_AE_OFFERED" AS g_ae_offered,
    "GSLO" AS gslo,
    "GSHI" AS gshi,
    "LEVEL" AS level,
    "IGOFFERED" AS igoffered,
    "OPERATIONAL_SCHOOLS" AS operational_schools,
    "GRADE" AS grade,
    "RACE_ETHNICITY" AS race_ethnicity,
    "SEX" AS sex,
    "STUDENT_COUNT" AS student_count,
    "TOTAL_INDICATOR" AS total_indicator,
    "DMS_FLAG" AS dms_flag
FROM "u-s-department-of-education-common-core-of-data-ccd-district-nonfiscal-data-files-and-documentation-2018-19-12070"
