-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "row_number",
    "X" AS x,
    "Y" AS y,
    "OBJECTID" AS objectid,
    "NCESSCH" AS ncessch,
    "SURVYEAR" AS survyear,
    "STABR" AS stabr,
    "LEAID" AS leaid,
    "ST_LEAID" AS st_leaid,
    "LEA_NAME" AS lea_name,
    "SCH_NAME" AS sch_name,
    "LSTREET1" AS lstreet1,
    "LSTREET2" AS lstreet2,
    "LCITY" AS lcity,
    "LSTATE" AS lstate,
    "LZIP" AS lzip,
    "LZIP4" AS lzip4,
    "PHONE" AS phone,
    "CHARTER_TEXT" AS charter_text,
    "MAGNET_TEXT" AS magnet_text,
    "VIRTUAL" AS virtual,
    "GSLO" AS gslo,
    "GSHI" AS gshi,
    "SCHOOL_LEVEL" AS school_level,
    "TITLEI" AS titlei,
    "STITLEI" AS stitlei,
    "STATUS" AS status,
    "SCHOOL_TYPE_TEXT" AS school_type_text,
    "SY_STATUS_TEXT" AS sy_status_text,
    "ULOCALE" AS ulocale,
    "NMCNTY" AS nmcnty,
    "TOTFRL" AS totfrl,
    "FRELCH" AS frelch,
    "REDLCH" AS redlch,
    "PK" AS pk,
    "KG" AS kg,
    "G01" AS g01,
    "G02" AS g02,
    "G03" AS g03,
    "G04" AS g04,
    "G05" AS g05,
    "G06" AS g06,
    "G07" AS g07,
    "G08" AS g08,
    "G09" AS g09,
    "G10" AS g10,
    "G11" AS g11,
    "G12" AS g12,
    "G13" AS g13,
    "UG" AS ug,
    "AE" AS ae,
    "TOTMENROL" AS totmenrol,
    "TOTFENROL" AS totfenrol,
    "TOTAL" AS total,
    "MEMBER" AS member,
    "FTE" AS fte,
    "STUTERATIO" AS stuteratio,
    "AMALM" AS amalm,
    "AMALF" AS amalf,
    "AM" AS am,
    "ASALM" AS asalm,
    "ASALF" AS asalf,
    "AS" AS as,
    "BLALM" AS blalm,
    "BLALF" AS blalf,
    "BL" AS bl,
    "HPALM" AS hpalm,
    "HPALF" AS hpalf,
    "HP" AS hp,
    "HIALM" AS hialm,
    "HIALF" AS hialf,
    "HI" AS hi,
    "TRALM" AS tralm,
    "TRALF" AS tralf,
    "TR" AS tr,
    "WHALM" AS whalm,
    "WHALF" AS whalf,
    "WH" AS wh,
    "LATCOD" AS latcod,
    "LONCOD" AS loncod
FROM "u-s-department-of-education-public-school-characteristics-2018-19-c7cf3"
