-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "sheet_name",
    "row_number",
    "Institution Code (six-digit OPEID)" AS institution_code_six_digit_opeid,
    "Institution Name" AS institution_name,
    "City" AS city,
    "State" AS state,
    "Zip" AS zip,
    "Institution Type" AS institution_type,
    "CIP Code" AS cip_code,
    "CIP Name" AS cip_name,
    "Credential Level" AS credential_level,
    "Official Program Pass/Zone/Fail" AS official_program_pass_zone_fail,
    "Official Appeal Decision" AS official_appeal_decision,
    "Appeal Status" AS appeal_status,
    "Debt-to-Earnings Annual Rate" AS debt_to_earnings_annual_rate,
    "Debt-to-Earnings Annual Rate Numerator" AS debt_to_earnings_annual_rate_numerator,
    "Debt-to-Earnings Annual Rate Denominator" AS debt_to_earnings_annual_rate_denominator,
    "Debt-to-Earnings Annual Rate Pass/Fail/Zone" AS debt_to_earnings_annual_rate_pass_fail_zone,
    "Debt-to-Earnings Discretionary Income Rate" AS debt_to_earnings_discretionary_income_rate,
    "Debt-to-Earnings Discretionary Income Rate Numerator" AS debt_to_earnings_discretionary_income_rate_numerator,
    "Debt-to-Earnings Discretionary Income Rate Denominator" AS debt_to_earnings_discretionary_income_rate_denominator,
    "Debt-to-Earnings Discretionary Income Rate Pass/Fail/Zone" AS debt_to_earnings_discretionary_income_rate_pass_fail_zone,
    "Debt-to-Earnings Transitional Rate" AS debt_to_earnings_transitional_rate,
    "Debt-to-Earnings Transitional Rate Numerator" AS debt_to_earnings_transitional_rate_numerator,
    "Debt-to-Earnings Transitional Rate Denominator" AS debt_to_earnings_transitional_rate_denominator,
    "Debt-to-Earnings Transitional Rate Pass/Fail/Zone" AS debt_to_earnings_transitional_rate_pass_fail_zone,
    "Debt-to-Earnings Transitional Discretionary Income Rate" AS debt_to_earnings_transitional_discretionary_income_rate,
    "Debt-to-Earnings Transitional Discretionary Income Rate Numerator" AS debt_to_earnings_transitional_discretionary_income_rate_numerator,
    "Debt-to-Earnings Transitional Discretionary Income Rate Denominator" AS debt_to_earnings_transitional_discretionary_income_rate_denominator,
    "Debt-to-Earnings Transitional Discretionary Income Rate Pass/Fail/Zone" AS debt_to_earnings_transitional_discretionary_income_rate_pass_fail_zone,
    "Mean Annual Earnings From SSA" AS mean_annual_earnings_from_ssa,
    "Median Annual Earnings from SSA" AS median_annual_earnings_from_ssa,
    "OPEID" AS opeid,
    "Institution Type and Control" AS institution_type_and_control,
    "Credential Level Code" AS credential_level_code,
    "CIP Code Program Name" AS cip_code_program_name,
    "Verified Student Count" AS verified_student_count,
    "Median SSA Earnings Amount" AS median_ssa_earnings_amount,
    "Mean SSA Earnings Amount" AS mean_ssa_earnings_amount
FROM "u-s-department-of-education-gainful-employment-ae757"
