-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "archive_member",
    "sheet_name",
    "row_number",
    "TABLE 24" AS table_24,
    "Unnamed: 1" AS unnamed_1,
    "Unnamed: 2" AS unnamed_2,
    "Unnamed: 3" AS unnamed_3,
    "Unnamed: 4" AS unnamed_4,
    "Unnamed: 5" AS unnamed_5,
    "Unnamed: 6" AS unnamed_6,
    "Unnamed: 7" AS unnamed_7,
    "TABLE 1" AS table_1,
    "TABLE 2-A" AS table_2_a,
    "Unnamed: 8" AS unnamed_8,
    "Unnamed: 9" AS unnamed_9,
    "Unnamed: 10" AS unnamed_10,
    "TABLE 3-A" AS table_3_a,
    "TABLE 4-A" AS table_4_a,
    "TABLE 5-A" AS table_5_a,
    "TABLE 6-A" AS table_6_a,
    "TABLE 7-A" AS table_7_a,
    "TABLE 8-A" AS table_8_a,
    "TABLE 9-A" AS table_9_a,
    "Table 10-A" AS table_10_a,
    "TABLE 11-A" AS table_11_a,
    "TABLE 11-B" AS table_11_b,
    "TABLE 11-C" AS table_11_c,
    "TABLE 13" AS table_13,
    "Unnamed: 11" AS unnamed_11,
    "Unnamed: 12" AS unnamed_12,
    "Unnamed: 13" AS unnamed_13,
    "TABLE 14" AS table_14,
    "TABLE 15" AS table_15,
    "TABLE 16" AS table_16,
    "TABLE 17" AS table_17,
    "TABLE 18 A" AS table_18_a,
    "TABLE 19" AS table_19,
    "TABLE 20" AS table_20,
    "TABLE 21-A" AS table_21_a,
    "TABLE 22" AS table_22,
    "TABLE 23" AS table_23,
    "Table 2-A - ALL RECIPIENTS" AS table_2_a_all_recipients,
    "Table 2-B - DEPENDENT RECIPIENTS" AS table_2_b_dependent_recipients,
    "Table 2-C - INDEPENDENT RECIPIENTS" AS table_2_c_independent_recipients,
    "TABLE 3-B" AS table_3_b,
    "TABLE 3-C" AS table_3_c,
    "TABLE 4-B" AS table_4_b,
    "TABLE 4-C" AS table_4_c,
    "TABLE 5-B" AS table_5_b,
    "TABLE 5-C" AS table_5_c,
    "TABLE 6-B" AS table_6_b,
    "TABLE 6-C" AS table_6_c,
    "Table 7-A - ALL RECIPIENTS" AS table_7_a_all_recipients,
    "Table 7-B - DEPENDENT RECIPIENTS" AS table_7_b_dependent_recipients,
    "Table 7-C - INDEPENDENT RECIPIENTS" AS table_7_c_independent_recipients,
    "Table 8-A - ALL RECIPIENTS" AS table_8_a_all_recipients,
    "Table 8-B - DEPENDENT RECIPIENTS" AS table_8_b_dependent_recipients,
    "Table 8-C - INDEPENDENT RECIPIENTS" AS table_8_c_independent_recipients,
    "TABLE 9-B" AS table_9_b,
    "TABLE 9-C" AS table_9_c,
    "TABLE 10-A_1" AS table_10_a_1,
    "TABLE 10-B" AS table_10_b,
    "TABLE 10-C" AS table_10_c,
    "TABLE 12" AS table_12,
    "TABLE 18-A" AS table_18_a_2,
    "TABLE 18-B" AS table_18_b,
    "TABLE 18-C" AS table_18_c,
    "TABLE 21-B" AS table_21_b,
    "TABLE 21-C" AS table_21_c,
    "Unnamed: 0" AS unnamed_0,
    "TABLE 2-A - ALL RECIPIENTS_1" AS table_2_a_all_recipients_1,
    "TABLE 3-A - ALL RECIPIENTS" AS table_3_a_all_recipients,
    "TABLE 4-A - ALL RECIPIENTS" AS table_4_a_all_recipients,
    "TABLE 5-A - ALL RECIPIENTS" AS table_5_a_all_recipients,
    "TABLE 6-A - ALL RECIPIENTS" AS table_6_a_all_recipients,
    "TABLE 7-A - ALL RECIPIENTS_1" AS table_7_a_all_recipients_1,
    "TABLE 8-A - ALL RECIPIENTS_1" AS table_8_a_all_recipients_1,
    "TABLE 9-A - ALL RECIPIENTS" AS table_9_a_all_recipients,
    "TABLE 10-A - ALL RECIPIENTS" AS table_10_a_all_recipients,
    "TABLE 11-A - ALL RECIPIENTS" AS table_11_a_all_recipients,
    "TABLE 14 - ALL RECIPIENTS" AS table_14_all_recipients,
    "Unnamed: 14" AS unnamed_14,
    "Unnamed: 15" AS unnamed_15,
    "TABLE 15 - ALL APPLICANTS" AS table_15_all_applicants,
    "TABLE 16 - ALL VERIFIED RECIPIENTS" AS table_16_all_verified_recipients,
    "TABLE 17 - ALL APPLICANTS" AS table_17_all_applicants,
    "TABLE 18-A - ALL RECIPIENTS" AS table_18_a_all_recipients,
    "TABLE 20 - ALL INSTITUTIONS" AS table_20_all_institutions,
    "TABLE 21-A - ALL RECIPIENTS" AS table_21_a_all_recipients,
    "TABLE 36" AS table_36,
    "1 TABLE 2A" AS 1_table_2a,
    "Table 2-A - All Recipients_2" AS table_2_a_all_recipients_2,
    "DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS" AS distribution_of_federal_pell_grant_recipients,
    "1 TABLE 5A" AS 1_table_5a,
    "1 TABLE 6A" AS 1_table_6a,
    "1 TABLE 7A" AS 1_table_7a,
    "1 TABLE 8A" AS 1_table_8a,
    "1 TABLE 9A" AS 1_table_9a,
    "TABLE 15 - ALL RECIPIENTS" AS table_15_all_recipients,
    "Unnamed: 16" AS unnamed_16,
    "Unnamed: 17" AS unnamed_17,
    "Unnamed: 18" AS unnamed_18,
    "Unnamed: 19" AS unnamed_19,
    "Unnamed: 20" AS unnamed_20,
    "Unnamed: 21" AS unnamed_21,
    "Unnamed: 22" AS unnamed_22,
    "TABLE 25-A - DEPENDENT APPLICANTS" AS table_25_a_dependent_applicants,
    "TABLE 26-A - DEPENDENT RECIPIENTS" AS table_26_a_dependent_recipients,
    "TABLE 27-A - DEPENDENT RECIPIENTS" AS table_27_a_dependent_recipients,
    "TABLE 28-A - DEPENDENT RECIPIENTS" AS table_28_a_dependent_recipients,
    "TABLE 29-A - DEPENDENT RECIPIENTS" AS table_29_a_dependent_recipients,
    "TABLE 30" AS table_30,
    "TABLE 31" AS table_31,
    "TABLE 32" AS table_32,
    "TABLE 33" AS table_33,
    "TABLE 34" AS table_34,
    "TABLE 35 - ALL APPLICANTS" AS table_35_all_applicants,
    "TABLE 24-A" AS table_24_a,
    "TABLE 25-A" AS table_25_a,
    "TABLE 26-A" AS table_26_a,
    "TABLE -29" AS table_29,
    "column_8",
    "TABLE 27" AS table_27,
    "Table 7-A_1" AS table_7_a_1,
    "Table 7-B" AS table_7_b,
    "Table 7-C" AS table_7_c,
    "TABLE 8-B" AS table_8_b,
    "TABLE 8-C" AS table_8_c,
    "TABLE 16-A" AS table_16_a,
    "TABLE 16-B" AS table_16_b,
    "TABLE 16-C" AS table_16_c,
    "TABLE 17-A" AS table_17_a,
    "TABLE 17-B" AS table_17_b,
    "TABLE 17-C" AS table_17_c,
    "TABLE 21" AS table_21,
    "TABLE 22-A" AS table_22_a,
    "TABLE 25-B" AS table_25_b,
    "TABLE 25-C" AS table_25_c,
    "TABLE 26" AS table_26,
    "Table 1 - Page 1" AS table_1_page_1,
    "Table 1 - Page 2" AS table_1_page_2
FROM "u-s-department-of-education-federal-pell-grant-program-data-books-1990-91-1999-00-7c1f9"
