-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "archive_member",
    "sheet_name",
    "row_number",
    "TABLE 27" AS table_27,
    "Unnamed: 1" AS unnamed_1,
    "Unnamed: 2" AS unnamed_2,
    "Unnamed: 3" AS unnamed_3,
    "Unnamed: 4" AS unnamed_4,
    "Unnamed: 5" AS unnamed_5,
    "Unnamed: 6" AS unnamed_6,
    "Unnamed: 7" AS unnamed_7,
    "Unnamed: 8" AS unnamed_8,
    "Unnamed: 9" AS unnamed_9,
    "Unnamed: 10" AS unnamed_10,
    "Unnamed: 11" AS unnamed_11,
    "Table 1 - Page 1" AS table_1_page_1,
    "Table 1 - Page 2" AS table_1_page_2,
    "TABLE 2-A" AS table_2_a,
    "TABLE 3-A" AS table_3_a,
    "TABLE 4-A" AS table_4_a,
    "TABLE 5-A" AS table_5_a,
    "TABLE 5-B" AS table_5_b,
    "TABLE 5-C" AS table_5_c,
    "TABLE 6-A" AS table_6_a,
    "TABLE 6-B" AS table_6_b,
    "TABLE 6-C" AS table_6_c,
    "Table 7-A" AS table_7_a,
    "Table 7-B" AS table_7_b,
    "Table 7-C" AS table_7_c,
    "TABLE 8-A" AS table_8_a,
    "TABLE 8-B" AS table_8_b,
    "TABLE 8-C" AS table_8_c,
    "TABLE 9-A" AS table_9_a,
    "TABLE 9-B" AS table_9_b,
    "TABLE 9-C" AS table_9_c,
    "TABLE 10-A" AS table_10_a,
    "TABLE 10-B" AS table_10_b,
    "TABLE 10-C" AS table_10_c,
    "TABLE 11" AS table_11,
    "Unnamed: 12" AS unnamed_12,
    "TABLE 12" AS table_12,
    "TABLE 13" AS table_13,
    "TABLE 14" AS table_14,
    "TABLE 15-A" AS table_15_a,
    "TABLE 16-A" AS table_16_a,
    "TABLE 17-A" AS table_17_a,
    "Unnamed: 0" AS unnamed_0,
    "TABLE 19" AS table_19,
    "TABLE 20" AS table_20,
    "TABLE 21-A" AS table_21_a,
    "TABLE 22" AS table_22,
    "TABLE 23" AS table_23,
    "TABLE 24-A" AS table_24_a,
    "TABLE 24-B" AS table_24_b,
    "TABLE 24-C" AS table_24_c,
    "TABLE 25-A" AS table_25_a,
    "TABLE 25-B" AS table_25_b,
    "TABLE 25-C" AS table_25_c,
    "TABLE 26" AS table_26,
    "Table 2-A - ALL RECIPIENTS" AS table_2_a_all_recipients,
    "Table 2-B - DEPENDENT RECIPIENTS" AS table_2_b_dependent_recipients,
    "Table 2-C - INDEPENDENT RECIPIENTS" AS table_2_c_independent_recipients,
    "TABLE 3-B" AS table_3_b,
    "TABLE 3-C" AS table_3_c,
    "TABLE 4-B" AS table_4_b,
    "TABLE 4-C" AS table_4_c,
    "TABLE 15-B" AS table_15_b,
    "TABLE 15-C" AS table_15_c,
    "TABLE 16-B" AS table_16_b,
    "TABLE 16-C" AS table_16_c,
    "TABLE 17-B" AS table_17_b,
    "TABLE 17-C" AS table_17_c,
    "TABLE 18" AS table_18,
    "TABLE 21-B" AS table_21_b,
    "TABLE 21-C" AS table_21_c,
    "TABLE 15" AS table_15,
    "TABLE 16" AS table_16,
    "TABLE 20-A" AS table_20_a,
    "TABLE 20-B" AS table_20_b,
    "TABLE 20-C" AS table_20_c,
    "TABLE 19-A" AS table_19_a,
    "TABLE 19-B" AS table_19_b,
    "TABLE 19-C" AS table_19_c,
    "TABLE 24" AS table_24,
    "TABLE 17" AS table_17,
    "TABLE 18-A" AS table_18_a,
    "TABLE 18-B" AS table_18_b,
    "TABLE 18-C" AS table_18_c,
    "TABLE 22-A" AS table_22_a,
    "TABLE 22-B" AS table_22_b,
    "TABLE 22-C" AS table_22_c,
    "Table 1" AS table_1,
    "TABLE 14-A" AS table_14_a,
    "TABLE 14-B" AS table_14_b,
    "TABLE 14-C" AS table_14_c,
    "TABLE 21" AS table_21
FROM "u-s-department-of-education-federal-pell-grant-program-data-books-1980-81-1989-90-c05cc"
