-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "sheet_name",
    "row_number",
    "Table— Number of SSI recipients aged 10–17, by state or other area and age, December 2012" AS table_number_of_ssi_recipients_aged_10_17_by_state_or_other_area_and_age_december_2012,
    "Unnamed: 1" AS unnamed_1,
    "Unnamed: 2" AS unnamed_2,
    "Unnamed: 3" AS unnamed_3,
    "Unnamed: 4" AS unnamed_4,
    "Unnamed: 5" AS unnamed_5,
    "Unnamed: 6" AS unnamed_6,
    "Unnamed: 7" AS unnamed_7,
    "Unnamed: 8" AS unnamed_8,
    "Unnamed: 9" AS unnamed_9,
    "Unnamed: 10" AS unnamed_10,
    "Unnamed: 11" AS unnamed_11,
    "Alabama" AS alabama,
    "Alaska" AS alaska,
    "Arizona" AS arizona,
    "Arkansas" AS arkansas,
    "California" AS california,
    "Colorado" AS colorado,
    "Connecticut" AS connecticut,
    "Delaware" AS delaware,
    "Florida" AS florida,
    "Georgia" AS georgia,
    "Hawaii" AS hawaii,
    "Idaho" AS idaho,
    "Illinois" AS illinois,
    "Indiana" AS indiana,
    "Iowa" AS iowa,
    "Kansas" AS kansas,
    "Kentucky" AS kentucky,
    "Louisiana" AS louisiana,
    "Maine" AS maine,
    "Maryland" AS maryland,
    "Massachusetts" AS massachusetts,
    "Michigan" AS michigan,
    "Minnesota" AS minnesota,
    "Mississippi" AS mississippi,
    "Missouri" AS missouri,
    "Montana" AS montana,
    "Nebraska" AS nebraska,
    "Nevada" AS nevada,
    "New Hampshire" AS new_hampshire,
    "New Jersey" AS new_jersey,
    "New Mexico" AS new_mexico,
    "New York" AS new_york,
    "North Carolina" AS north_carolina,
    "North Dakota" AS north_dakota,
    "Ohio" AS ohio,
    "Oklahoma" AS oklahoma,
    "Oregon" AS oregon,
    "Pennsylvania" AS pennsylvania,
    "Rhode Island" AS rhode_island,
    "South Carolina" AS south_carolina,
    "South Dakota" AS south_dakota,
    "Tennessee" AS tennessee,
    "Texas" AS texas,
    "Utah" AS utah,
    "Vermont" AS vermont,
    "Virginia" AS virginia,
    "Washington" AS washington,
    "West Virginia" AS west_virginia,
    "Wisconsin" AS wisconsin,
    "Wyoming" AS wyoming
FROM "u-s-department-of-education-promise-promoting-readiness-of-minors-in-supplemental-security-income-7ae39"
