-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "archive_member",
    "sheet_name",
    "row_number",
    "Table documentation for the IPEDS Access database, 2017-18" AS table_documentation_for_the_ipeds_access_database_2017_18,
    "Unnamed: 1" AS unnamed_1,
    "Unnamed: 2" AS unnamed_2,
    "Unnamed: 3" AS unnamed_3,
    "Unnamed: 4" AS unnamed_4,
    "Unnamed: 5" AS unnamed_5,
    "Unnamed: 6" AS unnamed_6,
    "Unnamed: 7" AS unnamed_7,
    "Unnamed: 8" AS unnamed_8,
    "Unnamed: 9" AS unnamed_9,
    "SurveyOrder" AS surveyorder,
    "SurveyNumber" AS surveynumber,
    "Survey" AS survey,
    "YearCoverage" AS yearcoverage,
    "TableName" AS tablename,
    "Tablenumber" AS tablenumber,
    "TableTitle" AS tabletitle,
    "Description" AS description,
    "Release" AS release,
    "Release date" AS release_date,
    "varNumber" AS varnumber,
    "varOrder" AS varorder,
    "varName" AS varname,
    "imputationvar",
    "varTitle" AS vartitle,
    "DataType" AS datatype,
    "fieldWidth" AS fieldwidth,
    "format",
    "multiRecord" AS multirecord,
    "hasRV" AS hasrv,
    "fileNumber" AS filenumber,
    "sectionnumber",
    "longDescription" AS longdescription,
    "varSource" AS varsource,
    "filetitle",
    "sectionTitle" AS sectiontitle,
    "Codevalue" AS codevalue,
    "Frequency" AS frequency,
    "Percent" AS percent,
    "valueOrder" AS valueorder,
    "valueLabel" AS valuelabel,
    "Table" AS table,
    "Metadata variable" AS metadata_variable
FROM "u-s-department-of-education-ipeds-access-database-2017-18-554ec"
