-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "sheet_name",
    "row_number",
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - ALABAMA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_alabama,
    "Unnamed: 1" AS unnamed_1,
    "Unnamed: 2" AS unnamed_2,
    "Unnamed: 3" AS unnamed_3,
    "Unnamed: 4" AS unnamed_4,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - ALASKA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_alaska,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - ARIZONA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_arizona,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - ARKANSAS" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_arkansas,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - CALIFORNIA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_california,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - COLORADO" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_colorado,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - CONNECTICUT" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_connecticut,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - DELAWARE" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_delaware,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - DISTRICT OF COLUMBIA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_district_of_columbia,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - FLORIDA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_florida,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - GEORGIA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_georgia,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - HAWAII" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_hawaii,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - IDAHO" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_idaho,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - ILLINOIS" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_illinois,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - INDIANA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_indiana,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - IOWA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_iowa,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - KANSAS" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_kansas,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - KENTUCKY" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_kentucky,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - LOUISIANA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_louisiana,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - MAINE" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_maine,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - MARYLAND" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_maryland,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - MASSACHUSETTS" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_massachusetts,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - MICHIGAN" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_michigan,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - MINNESOTA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_minnesota,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - MISSISSIPPI" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_mississippi,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - MISSOURI" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_missouri,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - MONTANA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_montana,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - NEBRASKA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_nebraska,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - NEVADA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_nevada,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - NEW HAMPSHIRE" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_new_hampshire,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - NEW JERSEY" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_new_jersey,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - NEW MEXICO" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_new_mexico,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - NEW YORK" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_new_york,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - NORTH CAROLINA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_north_carolina,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - NORTH DAKOTA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_north_dakota,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - OHIO" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_ohio,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - OKLAHOMA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_oklahoma,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - OREGON" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_oregon,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - PENNSYLVANIA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_pennsylvania,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - PUERTO RICO" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_puerto_rico,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - RHODE ISLAND" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_rhode_island,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - SOUTH CAROLINA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_south_carolina,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - SOUTH DAKOTA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_south_dakota,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - TENNESSEE" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_tennessee,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - TEXAS" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_texas,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - UTAH" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_utah,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - VERMONT" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_vermont,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - VIRGINIA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_virginia,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - WASHINGTON" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_washington,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - WEST VIRGINIA" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_west_virginia,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - WISCONSIN" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_wisconsin,
    "Fiscal Year 2010 Title I Grants to Local Educational Agencies - WYOMING" AS fiscal_year_2010_title_i_grants_to_local_educational_agencies_wyoming
FROM "u-s-department-of-education-esea-title-i-lea-allocationsfy-2010"
