-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "sheet_name",
    "row_number",
    "Alabama" AS alabama,
    "Unnamed: 1" AS unnamed_1,
    "Unnamed: 2" AS unnamed_2,
    "Unnamed: 3" AS unnamed_3,
    "Unnamed: 4" AS unnamed_4,
    "Unnamed: 5" AS unnamed_5,
    "Unnamed: 6" AS unnamed_6,
    "Unnamed: 7" AS unnamed_7,
    "Unnamed: 8" AS unnamed_8,
    "Unnamed: 9" AS unnamed_9,
    "Unnamed: 10" AS unnamed_10,
    "Unnamed: 11" AS unnamed_11,
    "Unnamed: 12" AS unnamed_12,
    "Unnamed: 13" AS unnamed_13,
    "Unnamed: 14" AS unnamed_14,
    "Unnamed: 15" AS unnamed_15,
    "Unnamed: 16" AS unnamed_16,
    "Unnamed: 17" AS unnamed_17,
    "Unnamed: 18" AS unnamed_18,
    "Unnamed: 19" AS unnamed_19,
    "Unnamed: 20" AS unnamed_20,
    "Unnamed: 21" AS unnamed_21,
    "Part B Compliance Matrix: 2014" AS part_b_compliance_matrix_2014,
    "Part B Compliance Matrix" AS part_b_compliance_matrix,
    "Alaska" AS alaska,
    "American Samoa" AS american_samoa,
    "Arizona" AS arizona,
    "Arkansas" AS arkansas,
    "BIE" AS bie,
    "California" AS california,
    "Colorado" AS colorado,
    "Connecticut" AS connecticut,
    "District of Columbia" AS district_of_columbia,
    "Delaware" AS delaware,
    "Federated States of Micronesia" AS federated_states_of_micronesia,
    "Florida" AS florida,
    "Georgia" AS georgia,
    "Guam" AS guam,
    "Hawaii" AS hawaii,
    "Idaho" AS idaho,
    "Illinois" AS illinois,
    "Indiana" AS indiana,
    "Iowa" AS iowa,
    "Kansas" AS kansas,
    "Kentucky" AS kentucky,
    "Louisiana" AS louisiana,
    "Maine" AS maine,
    "Marshall Islands" AS marshall_islands,
    "Maryland" AS maryland,
    "Massachusetts" AS massachusetts,
    "Michigan" AS michigan,
    "Minnesota" AS minnesota,
    "Mississippi" AS mississippi,
    "Missouri" AS missouri,
    "Montana" AS montana,
    "Nebraska" AS nebraska,
    "Nevada" AS nevada,
    "New Hampshire" AS new_hampshire,
    "New Jersey" AS new_jersey,
    "New Mexico" AS new_mexico,
    "New York" AS new_york,
    "North Carolina" AS north_carolina,
    "North Dakota" AS north_dakota,
    "CNMI" AS cnmi,
    "Ohio" AS ohio,
    "Oklahoma" AS oklahoma,
    "Oregon" AS oregon,
    "Palau" AS palau,
    "Pennsylvania" AS pennsylvania,
    "Puerto Rico" AS puerto_rico,
    "Rhode Island" AS rhode_island,
    "South Carolina" AS south_carolina,
    "South Dakota" AS south_dakota,
    "Tennessee" AS tennessee,
    "Texas" AS texas,
    "Utah" AS utah,
    "UTAH_1" AS utah_1,
    "Vermont" AS vermont,
    "Virgin Islands" AS virgin_islands,
    "Virginia" AS virginia,
    "Washington" AS washington,
    "West Virginia" AS west_virginia,
    "Wisconsin" AS wisconsin,
    "Wyoming" AS wyoming
FROM "u-s-department-of-education-part-b-state-performance-plans-and-annual-performance-report"
