-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "archive_member",
    "row_number",
    "SCHOOL_YEAR" AS school_year,
    "FIPST" AS fipst,
    "STATENAME" AS statename,
    "ST" AS st,
    "SEA_NAME" AS sea_name,
    "STATE_AGENCY_NO" AS state_agency_no,
    "MSTREET1" AS mstreet1,
    "MSTREET2" AS mstreet2,
    "MSTREET3" AS mstreet3,
    "MCITY" AS mcity,
    "MSTATE" AS mstate,
    "MZIP" AS mzip,
    "MZIP4" AS mzip4,
    "LSTREET1" AS lstreet1,
    "LSTREET2" AS lstreet2,
    "LSTREET3" AS lstreet3,
    "LCITY" AS lcity,
    "LSTATE" AS lstate,
    "LZIP" AS lzip,
    "LZIP4" AS lzip4,
    "PHONE" AS phone,
    "WEBSITE" AS website,
    "G_13_OFFERED" AS g_13_offered,
    "G_UG_OFFERED" AS g_ug_offered,
    "UG_TCH_OFFERED" AS ug_tch_offered,
    "OPERATIONAL_SCHOOLS" AS operational_schools,
    "OPERATIONAL_LEAS" AS operational_leas,
    "GRADE" AS grade,
    "RACE_ETHNICITY" AS race_ethnicity,
    "SEX" AS sex,
    "STUDENT_COUNT" AS student_count,
    "TOTAL_INDICATOR" AS total_indicator,
    "DMS_FLAG" AS dms_flag,
    "STAFF" AS staff,
    "STAFF_COUNT" AS staff_count
FROM "u-s-department-of-education-common-core-of-data-ccd-state-nonfiscal-data-files-and-documentation-2018-19-c43ae"
