-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "archive_member",
    "sheet_name",
    "row_number",
    "Unnamed: 0" AS unnamed_0,
    "TABLE 1 FEDERAL PELL GRANT PROGRAM SUMMARY STATISTICS FOR CROSS-YEAR REFERENCE" AS table_1_federal_pell_grant_program_summary_statistics_for_cross_year_reference,
    "Unnamed: 2" AS unnamed_2,
    "Unnamed: 3" AS unnamed_3,
    "Unnamed: 4" AS unnamed_4,
    "Unnamed: 5" AS unnamed_5,
    "Unnamed: 6" AS unnamed_6,
    "Unnamed: 7" AS unnamed_7,
    "Unnamed: 8" AS unnamed_8,
    "Unnamed: 9" AS unnamed_9,
    "Unnamed: 10" AS unnamed_10,
    "TABLE 1 FEDERAL PELL GRANT PROGRAM SUMMARY STATISTICS FOR CROSS-YEAR REFERENCE.1" AS table_1_federal_pell_grant_program_summary_statistics_for_cross_year_reference_1,
    "Unnamed: 12" AS unnamed_12,
    "Unnamed: 13" AS unnamed_13,
    "Unnamed: 14" AS unnamed_14,
    "Unnamed: 15" AS unnamed_15,
    "Unnamed: 16" AS unnamed_16,
    "Unnamed: 17" AS unnamed_17,
    "Unnamed: 18" AS unnamed_18,
    "Unnamed: 19" AS unnamed_19,
    "Unnamed: 20" AS unnamed_20,
    "TABLE 1 FEDERAL PELL GRANT PROGRAM SUMMARY STATISTICS FOR CROSS-YEAR REFERENCE.2" AS table_1_federal_pell_grant_program_summary_statistics_for_cross_year_reference_2,
    "Unnamed: 22" AS unnamed_22,
    "Unnamed: 23" AS unnamed_23,
    "Unnamed: 24" AS unnamed_24,
    "Unnamed: 25" AS unnamed_25,
    "Unnamed: 26" AS unnamed_26,
    "Unnamed: 27" AS unnamed_27,
    "Unnamed: 28" AS unnamed_28,
    "Unnamed: 29" AS unnamed_29,
    "Unnamed: 30" AS unnamed_30,
    "TABLE 1 FEDERAL PELL GRANT PROGRAM SUMMARY STATISTICS FOR CROSS-YEAR REFERENCE.3" AS table_1_federal_pell_grant_program_summary_statistics_for_cross_year_reference_3,
    "Unnamed: 32" AS unnamed_32,
    "Unnamed: 33" AS unnamed_33,
    "Unnamed: 34" AS unnamed_34,
    "Unnamed: 35" AS unnamed_35,
    "Unnamed: 36" AS unnamed_36,
    "Unnamed: 37" AS unnamed_37,
    "Unnamed: 38" AS unnamed_38,
    "Unnamed: 39" AS unnamed_39,
    "Unnamed: 40" AS unnamed_40,
    "TABLE 10A DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND NET ASSET LEVEL ALL RECIPIENTS - AWARD YEAR 2012-2013" AS table_10a_distribution_of_federal_pell_grant_recipients_by_family_income_and_net_asset_level_all_recipients_award_year_2012_2013,
    "Unnamed: 1" AS unnamed_1,
    "Unnamed: 11" AS unnamed_11,
    "TABLE 10B DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND NET ASSET LEVEL DEPENDENT RECIPIENTS - AWARD YEAR 2012-2013" AS table_10b_distribution_of_federal_pell_grant_recipients_by_family_income_and_net_asset_level_dependent_recipients_award_year_2012_2013,
    "TABLE 10C DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND NET ASSET LEVEL INDEPENDENT RECIPIENTS WITHOUT DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_10c_distribution_of_federal_pell_grant_recipients_by_family_income_and_net_asset_level_independent_recipients_without_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 10D DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND NET ASSET LEVEL INDEPENDENT RECIPIENTS WITH DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_10d_distribution_of_federal_pell_grant_recipients_by_family_income_and_net_asset_level_independent_recipients_with_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 11A DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY AGE AND FAMILY INCOME ALL RECIPIENTS - AWARD YEAR 2012-2013" AS table_11a_distribution_of_federal_pell_grant_recipients_by_age_and_family_income_all_recipients_award_year_2012_2013,
    "TABLE 11B DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY AGE AND FAMILY INCOME DEPENDENT RECIPIENTS - AWARD YEAR 2012-2013" AS table_11b_distribution_of_federal_pell_grant_recipients_by_age_and_family_income_dependent_recipients_award_year_2012_2013,
    "TABLE 11C DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY AGE AND FAMILY INCOME INDEPENDENT RECIPIENTS WITHOUT DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_11c_distribution_of_federal_pell_grant_recipients_by_age_and_family_income_independent_recipients_without_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 11D DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY AGE AND FAMILY INCOME INDEPENDENT RECIPIENTS WITH DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_11d_distribution_of_federal_pell_grant_recipients_by_age_and_family_income_independent_recipients_with_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 12 DISTRIBUTION OF TITLE IV AND PELL GRANT APPLICANTS BY ELIGIBILITY STATUS AND INCOME RANGE AWARD YEAR 2012-2013" AS table_12_distribution_of_title_iv_and_pell_grant_applicants_by_eligibility_status_and_income_range_award_year_2012_2013,
    "TABLE 13 FEDERAL PELL GRANT RECIPIENT ENROLLMENT STATUS BY TYPE AND CONTROL OF INSTITUTION ALL RECIPIENTS - AWARD YEAR 2012-2013" AS table_13_federal_pell_grant_recipient_enrollment_status_by_type_and_control_of_institution_all_recipients_award_year_2012_2013,
    "TABLE 14 SUMMARY STATISTICS FOR FEDERAL PELL GRANT APPLICANT PROFESSIONAL JUDGMENT FILERS ALL APPLICANTS - AWARD YEAR 2012-2013" AS table_14_summary_statistics_for_federal_pell_grant_applicant_professional_judgment_filers_all_applicants_award_year_2012_2013,
    "TABLE 15 DISTRIBUTION OF VERIFIED FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND GRANT LEVEL ALL VERIFIED RECIPIENTS - AWARD YEAR 2012-2013" AS table_15_distribution_of_verified_federal_pell_grant_recipients_by_family_income_and_grant_level_all_verified_recipients_award_year_2012_2013,
    "Unnamed: 21" AS unnamed_21,
    "TABLE 16 SUMMARY STATISTICS BY APPLICATION TYPE ALL APPLICANTS - AWARD YEAR 2012-2013" AS table_16_summary_statistics_by_application_type_all_applicants_award_year_2012_2013,
    "TABLE 17A DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND APPLICATION TYPE ALL RECIPIENTS - AWARD YEAR 2012-2013" AS table_17a_distribution_of_federal_pell_grant_recipients_by_family_income_and_application_type_all_recipients_award_year_2012_2013,
    "TABLE 17B DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND APPLICATION TYPE DEPENDENT RECIPIENTS - AWARD YEAR 2012-2013" AS table_17b_distribution_of_federal_pell_grant_recipients_by_family_income_and_application_type_dependent_recipients_award_year_2012_2013,
    "TABLE 17C DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND APPLICATION TYPE INDEPENDENT RECIPIENTS WITHOUT DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_17c_distribution_of_federal_pell_grant_recipients_by_family_income_and_application_type_independent_recipients_without_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 17D DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND APPLICATION TYPE INDEPENDENT RECIPIENTS WITH DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_17d_distribution_of_federal_pell_grant_recipients_by_family_income_and_application_type_independent_recipients_with_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 18 SUMMARY STATISTICS BY TYPE AND CONTROL OF INSTITUTION AWARD YEAR 2012-2013" AS table_18_summary_statistics_by_type_and_control_of_institution_award_year_2012_2013,
    "TABLE 19 FEDERAL PELL GRANT EXPENDITURES, RECIPIENTS, AND AVERAGE GRANT BY TYPE AND CONTROL OF INSTITUTION ALL INSTITUTIONS - AWARD YEAR 2012-2013" AS table_19_federal_pell_grant_expenditures_recipients_and_average_grant_by_type_and_control_of_institution_all_institutions_award_year_2012_2013,
    "TABLE 2A DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EXPECTED FAMILY CONTRIBUTION AND FAMILY INCOME ALL RECIPIENTS - AWARD YEAR 2012-2013" AS table_2a_distribution_of_federal_pell_grant_recipients_by_expected_family_contribution_and_family_income_all_recipients_award_year_2012_2013,
    "TABLE 2A DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EXPECTED FAMILY CONTRIBUTION AND FAMILY INCOME DEPENDENT RECIPIENTS - AWARD YEAR 2012-2013" AS table_2a_distribution_of_federal_pell_grant_recipients_by_expected_family_contribution_and_family_income_dependent_recipients_award_year_2012_2013,
    "TABLE 2C DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EXPECTED FAMILY CONTRIBUTION AND FAMILY INCOME INDEPENDENT RECIPIENTS WITHOUT DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_2c_distribution_of_federal_pell_grant_recipients_by_expected_family_contribution_and_family_income_independent_recipients_without_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 2D DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EXPECTED FAMILY CONTRIBUTION AND FAMILY INCOME INDEPENDENT RECIPIENTS WITH DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_2d_distribution_of_federal_pell_grant_recipients_by_expected_family_contribution_and_family_income_independent_recipients_with_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 20A DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS AND AVERAGE GRANT BY GRANT LEVEL AND TYPE AND CONTROL OF INSTITUTION ALL RECIPIENTS - AWARD YEAR 2012-2013" AS table_20a_distribution_of_federal_pell_grant_recipients_and_average_grant_by_grant_level_and_type_and_control_of_institution_all_recipients_award_year_2012_2013,
    "TABLE 20B DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS AND AVERAGE GRANT BY GRANT LEVEL AND TYPE AND CONTROL OF INSTITUTION DEPENDENT RECIPIENTS - AWARD YEAR 2012-2013" AS table_20b_distribution_of_federal_pell_grant_recipients_and_average_grant_by_grant_level_and_type_and_control_of_institution_dependent_recipients_award_year_2012_2013,
    "TABLE 20C DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS AND AVERAGE GRANT BY GRANT LEVEL AND TYPE AND CONTROL OF INSTITUTION INDEPENDENT RECIPIENTS WITHOUT DEPENDENTS OTHER THAN SPOUSE - AWARD YEAR 2012-2013" AS table_20c_distribution_of_federal_pell_grant_recipients_and_average_grant_by_grant_level_and_type_and_control_of_institution_independent_recipients_without_dependents_other_than_spouse_award_year_2012_2013,
    "TABLE 20D DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS AND AVERAGE GRANT BY GRANT LEVEL AND TYPE AND CONTROL OF INSTITUTION INDEPENDENT RECIPIENTS WITH DEPENDENTS OTHER THAN SPOUSE - AWARD YEAR 2012-2013" AS table_20d_distribution_of_federal_pell_grant_recipients_and_average_grant_by_grant_level_and_type_and_control_of_institution_independent_recipients_with_dependents_other_than_spouse_award_year_2012_2013,
    "TABLE 21 DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY STATE AND CONTROL OF INSTITUTION AWARD YEAR 2012-2013" AS table_21_distribution_of_federal_pell_grant_recipients_by_state_and_control_of_institution_award_year_2012_2013,
    "TABLE 22 DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY STATE OF LEGAL RESIDENCE AND CONTROL OF INSTITUTION AWARD YEAR 2012-2013" AS table_22_distribution_of_federal_pell_grant_recipients_by_state_of_legal_residence_and_control_of_institution_award_year_2012_2013,
    "TABLE 23 DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY TYPE AND CONTROL OF INSTITUTION AND FORMULA TYPE AWARD YEAR 2012-2013" AS table_23_distribution_of_federal_pell_grant_recipients_by_type_and_control_of_institution_and_formula_type_award_year_2012_2013,
    "TABLE 3A DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND GRANT LEVEL ALL RECIPIENTS - AWARD YEAR 2012-2013" AS table_3a_distribution_of_federal_pell_grant_recipients_by_family_income_and_grant_level_all_recipients_award_year_2012_2013,
    "TABLE 3B DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND GRANT LEVEL DEPENDENT RECIPIENTS - AWARD YEAR 2012-2013" AS table_3b_distribution_of_federal_pell_grant_recipients_by_family_income_and_grant_level_dependent_recipients_award_year_2012_2013,
    "TABLE 3C DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND GRANT LEVEL INDEPENDENT WITHOUT DEPENDENTS RECIPIENTS - AWARD YEAR 2012-2013" AS table_3c_distribution_of_federal_pell_grant_recipients_by_family_income_and_grant_level_independent_without_dependents_recipients_award_year_2012_2013,
    "TABLE 3D DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND GRANT LEVEL INDEPENDENT WITH DEPENDENTS - AWARD YEAR 2012-2013" AS table_3d_distribution_of_federal_pell_grant_recipients_by_family_income_and_grant_level_independent_with_dependents_award_year_2012_2013,
    "TABLE 4A DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EXPECTED FAMILY CONTRIBUTION AND GRANT LEVEL ALL RECIPIENTS - AWARD YEAR 2012-2013" AS table_4a_distribution_of_federal_pell_grant_recipients_by_expected_family_contribution_and_grant_level_all_recipients_award_year_2012_2013,
    "TABLE 4B DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EXPECTED FAMILY CONTRIBUTION AND GRANT LEVEL DEPENDENT RECIPIENTS - AWARD YEAR 2012-2013" AS table_4b_distribution_of_federal_pell_grant_recipients_by_expected_family_contribution_and_grant_level_dependent_recipients_award_year_2012_2013,
    "TABLE 4C DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EXPECTED FAMILY CONTRIBUTION AND GRANT LEVEL INDEPENDENT RECIPIENTS WITHOUT DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_4c_distribution_of_federal_pell_grant_recipients_by_expected_family_contribution_and_grant_level_independent_recipients_without_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 4D DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EXPECTED FAMILY CONTRIBUTION AND GRANT LEVEL INDEPENDENT RECIPIENTS WITH DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_4d_distribution_of_federal_pell_grant_recipients_by_expected_family_contribution_and_grant_level_independent_recipients_with_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 5A DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EXPECTED FAMILY CONTRIBUTION AND TYPE AND CONTROL OF INSTITUTION ALL RECIPIENTS - AWARD YEAR 2012-2013" AS table_5a_distribution_of_federal_pell_grant_recipients_by_expected_family_contribution_and_type_and_control_of_institution_all_recipients_award_year_2012_2013,
    "TABLE 5B DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EXPECTED FAMILY CONTRIBUTION AND TYPE AND CONTROL OF INSTITUTION DEPENDENT RECIPIENTS - AWARD YEAR 2012-2013" AS table_5b_distribution_of_federal_pell_grant_recipients_by_expected_family_contribution_and_type_and_control_of_institution_dependent_recipients_award_year_2012_2013,
    "TABLE 5C DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EXPECTED FAMILY CONTRIBUTION AND TYPE AND CONTROL OF INSTITUTION INDEPENDENT RECIPIENTS WITHOUT DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_5c_distribution_of_federal_pell_grant_recipients_by_expected_family_contribution_and_type_and_control_of_institution_independent_recipients_without_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 5D DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EXPECTED FAMILY CONTRIBUTION AND TYPE AND CONTROL OF INSTITUTION INDEPENDENT RECIPIENTS WITH DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_5d_distribution_of_federal_pell_grant_recipients_by_expected_family_contribution_and_type_and_control_of_institution_independent_recipients_with_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 6A DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND TYPE AND CONTROL OF INSTITUTION ALL RECIPIENTS - AWARD YEAR 2012-2013" AS table_6a_distribution_of_federal_pell_grant_recipients_by_family_income_and_type_and_control_of_institution_all_recipients_award_year_2012_2013,
    "TABLE 6B DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND TYPE AND CONTROL OF INSTITUTION DEPENDENT RECIPIENTS - AWARD YEAR 2012-2013" AS table_6b_distribution_of_federal_pell_grant_recipients_by_family_income_and_type_and_control_of_institution_dependent_recipients_award_year_2012_2013,
    "TABLE 6C DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND TYPE AND CONTROL OF INSTITUTION INDEPENDENT RECIPIENTS WITHOUT DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_6c_distribution_of_federal_pell_grant_recipients_by_family_income_and_type_and_control_of_institution_independent_recipients_without_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 6D DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND TYPE AND CONTROL OF INSTITUTION INDEPENDENT RECIPIENTS WITH DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_6d_distribution_of_federal_pell_grant_recipients_by_family_income_and_type_and_control_of_institution_independent_recipients_with_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 7A DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EXPECTED FAMILY CONTRIBUTION AND EDUCATIONAL COST ALL RECIPIENTS - AWARD YEAR 2012-2013" AS table_7a_distribution_of_federal_pell_grant_recipients_by_expected_family_contribution_and_educational_cost_all_recipients_award_year_2012_2013,
    "TABLE 7B DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EXPECTED FAMILY CONTRIBUTION AND EDUCATIONAL COST DEPENDENT RECIPIENTS - AWARD YEAR 2012-2013" AS table_7b_distribution_of_federal_pell_grant_recipients_by_expected_family_contribution_and_educational_cost_dependent_recipients_award_year_2012_2013,
    "TABLE 7C DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EXPECTED FAMILY CONTRIBUTION AND EDUCATIONAL COST INDEPENDENT RECIPIENTS WITHOUT DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_7c_distribution_of_federal_pell_grant_recipients_by_expected_family_contribution_and_educational_cost_independent_recipients_without_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 7D DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EXPECTED FAMILY CONTRIBUTION AND EDUCATIONAL COST INDEPENDENT RECIPIENTS WITH DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_7d_distribution_of_federal_pell_grant_recipients_by_expected_family_contribution_and_educational_cost_independent_recipients_with_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 8A DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND EDUCATIONAL COST ALL RECIPIENTS - AWARD YEAR 2012-2013" AS table_8a_distribution_of_federal_pell_grant_recipients_by_family_income_and_educational_cost_all_recipients_award_year_2012_2013,
    "TABLE 8B DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND EDUCATIONAL COST DEPENDENT RECIPIENTS - AWARD YEAR 2012-2013" AS table_8b_distribution_of_federal_pell_grant_recipients_by_family_income_and_educational_cost_dependent_recipients_award_year_2012_2013,
    "TABLE 8C DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND EDUCATIONAL COST INDEPENDENT RECIPIENTS WITHOUT DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_8c_distribution_of_federal_pell_grant_recipients_by_family_income_and_educational_cost_independent_recipients_without_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 8D DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY FAMILY INCOME AND EDUCATIONAL COST INDEPENDENT RECIPIENTS WITH DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_8d_distribution_of_federal_pell_grant_recipients_by_family_income_and_educational_cost_independent_recipients_with_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 9A DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EDUCATIONAL COST AND GRANT LEVEL ALL RECIPIENTS - AWARD YEAR 2012-2013" AS table_9a_distribution_of_federal_pell_grant_recipients_by_educational_cost_and_grant_level_all_recipients_award_year_2012_2013,
    "TABLE 9B DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EDUCATIONAL COST AND GRANT LEVEL DEPENDENT RECIPIENTS - AWARD YEAR 2012-2013" AS table_9b_distribution_of_federal_pell_grant_recipients_by_educational_cost_and_grant_level_dependent_recipients_award_year_2012_2013,
    "TABLE 9C DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EDUCATIONAL COST AND GRANT LEVEL INDEPENDENT RECIPIENTS WITHOUT DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_9c_distribution_of_federal_pell_grant_recipients_by_educational_cost_and_grant_level_independent_recipients_without_dependents_other_than_a_spouse_award_year_2012_2013,
    "TABLE 9D DISTRIBUTION OF FEDERAL PELL GRANT RECIPIENTS BY EDUCATIONAL COST AND GRANT LEVEL INDEPENDENT RECIPIENTS WITH DEPENDENTS OTHER THAN A SPOUSE - AWARD YEAR 2012-2013" AS table_9d_distribution_of_federal_pell_grant_recipients_by_educational_cost_and_grant_level_independent_recipients_with_dependents_other_than_a_spouse_award_year_2012_2013
FROM "u-s-department-of-education-2012-2013-federal-pell-grant-program-end-of-year-report-b0faa"
