-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "archive_member",
    "sheet_name",
    "row_number",
    "Table of Contents" AS table_of_contents,
    "Unnamed: 1" AS unnamed_1,
    "Unnamed: 2" AS unnamed_2,
    "Unnamed: 3" AS unnamed_3,
    "Unnamed: 4" AS unnamed_4,
    "Unnamed: 5" AS unnamed_5,
    "Unnamed: 6" AS unnamed_6,
    "Unnamed: 7" AS unnamed_7,
    "Unnamed: 8" AS unnamed_8,
    "Federal Supplemental Educational Opportunity Grant Program" AS federal_supplemental_educational_opportunity_grant_program,
    "Federal Work-Study Program" AS federal_work_study_program,
    "Federal Perkins Loan Program" AS federal_perkins_loan_program,
    "Unnamed: 9" AS unnamed_9,
    "Number of Institutions" AS number_of_institutions,
    "Comparison of Campus-Based Allocations" AS comparison_of_campus_based_allocations,
    "Campus-Based Allocations" AS campus_based_allocations,
    "Distribution of Campus-Based Allocations" AS distribution_of_campus_based_allocations,
    "Distribution of Federal Supplemental Educational Opportunity Grant Program Allocations" AS distribution_of_federal_supplemental_educational_opportunity_grant_program_allocations,
    "Unnamed: 10" AS unnamed_10,
    "Distribution of Federal Work-Study Program Allocations" AS distribution_of_federal_work_study_program_allocations,
    "Distribution of Federal Perkins Loan Program - Authorized Level of Expenditures" AS distribution_of_federal_perkins_loan_program_authorized_level_of_expenditures,
    "Campus-Based Programs" AS campus_based_programs,
    "FSEOG Fiscal Data" AS fseog_fiscal_data,
    "Unnamed: 11" AS unnamed_11,
    "Unnamed: 12" AS unnamed_12,
    "FWS Fiscal Data" AS fws_fiscal_data,
    "Job Location and Development Program" AS job_location_and_development_program,
    "JLD Fiscal Data" AS jld_fiscal_data,
    "Federal Work-Study Students Employed in" AS federal_work_study_students_employed_in,
    "Federal Work-Study Students Employed as" AS federal_work_study_students_employed_as,
    "Federal Work-Study Students" AS federal_work_study_students,
    "Federal Work-Study" AS federal_work_study,
    "Unnamed: 13" AS unnamed_13,
    "Unnamed: 14" AS unnamed_14,
    "Unnamed: 15" AS unnamed_15,
    "Unnamed: 16" AS unnamed_16,
    "Unnamed: 17" AS unnamed_17,
    "Unnamed: 18" AS unnamed_18,
    "Unnamed: 19" AS unnamed_19,
    "Distribution of Awards in the Campus-Based Programs" AS distribution_of_awards_in_the_campus_based_programs,
    "Distribution of Campus-Based Programs" AS distribution_of_campus_based_programs,
    "FSEOG Awards and Recipients for 2009-10 - U.S. Totals" AS fseog_awards_and_recipients_for_2009_10_u_s_totals,
    "Federal Supplemental Educational Opportunity Grant" AS federal_supplemental_educational_opportunity_grant,
    "FWS Awards and Recipients for 2009-10 - U.S. Totals" AS fws_awards_and_recipients_for_2009_10_u_s_totals,
    "Unnamed: 20" AS unnamed_20,
    "Unnamed: 21" AS unnamed_21,
    "Federal Perkins Loan Awards and Recipients for 2009-10 - U.S. Totals" AS federal_perkins_loan_awards_and_recipients_for_2009_10_u_s_totals
FROM "u-s-department-of-education-federal-campus-based-programs-data-book-2011-26660"
