-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "archive_member",
    "row_number",
    "0100002",
    "Alabama Youth Services" AS alabama_youth_services,
    "01",
    "1000 Industrial School Road" AS 1000_industrial_school_road,
    "Mt Meigs" AS mt_meigs,
    "AL" AS al,
    "36057",
    "01.1" AS 01_1,
    "01101",
    "Montgomery County" AS montgomery_county,
    "32.376397" AS 32_376397,
    "-86.084642" AS 86_084642,
    "33860",
    "Montgomery, AL" AS montgomery_al,
    "1",
    "388",
    "Montgomery-Selma-Alexander City, AL" AS montgomery_selma_alexander_city_al,
    "N" AS n,
    "N.1" AS n_1,
    "0103",
    "01075",
    "01025",
    "2020-2021" AS 2020_2021,
    "41",
    "-2" AS 2,
    "-2.1" AS 2_1,
    "-2.2" AS 2_2,
    "-2.3" AS 2_3,
    "-2.4" AS 2_4,
    "-2.5" AS 2_5,
    "-2.6" AS 2_6,
    "-2.7" AS 2_7,
    "-2.8" AS 2_8,
    "-2.9" AS 2_9,
    "-2.10" AS 2_10,
    "-2.11" AS 2_11,
    "sheet_name",
    "LEAID" AS leaid,
    "NAME" AS name,
    "OPSTFIPS" AS opstfips,
    "STREET" AS street,
    "CITY" AS city,
    "STATE" AS state,
    "ZIP" AS zip,
    "STFIP" AS stfip,
    "CNTY" AS cnty,
    "NMCNTY" AS nmcnty,
    "LAT" AS lat,
    "LON" AS lon,
    "CBSA" AS cbsa,
    "NMCBSA" AS nmcbsa,
    "CBSATYPE" AS cbsatype,
    "CSA" AS csa,
    "NMCSA" AS nmcsa,
    "NECTA" AS necta,
    "NMNECTA" AS nmnecta,
    "CD" AS cd,
    "SLDL" AS sldl,
    "SLDU" AS sldu,
    "SCHOOLYEAR" AS schoolyear,
    "LOCALE" AS locale,
    "PCT_CITY11" AS pct_city11,
    "PCT_CITY12" AS pct_city12,
    "PCT_CITY13" AS pct_city13,
    "PCT_SUB21" AS pct_sub21,
    "PCT_SUB22" AS pct_sub22,
    "PCT_SUB23" AS pct_sub23,
    "PCT_TOWN31" AS pct_town31,
    "PCT_TOWN32" AS pct_town32,
    "PCT_TOWN33" AS pct_town33,
    "PCT_RURAL41" AS pct_rural41,
    "PCT_RURAL42" AS pct_rural42,
    "PCT_RURAL43" AS pct_rural43
FROM "u-s-department-of-education-school-district-office-locations-2020-21-a7546"
