-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "sheet_name",
    "row_number",
    "State Name" AS state_name,
    "State Code" AS state_code,
    "Career Services Participants Served" AS career_services_participants_served,
    "Career Services Participants Exited" AS career_services_participants_exited,
    "Career Services Funds Expended" AS career_services_funds_expended,
    "Career Services Cost Per Served" AS career_services_cost_per_served,
    "Training Services Participants Served" AS training_services_participants_served,
    "Training Services Participants Exited" AS training_services_participants_exited,
    "Training Services Funds Expended" AS training_services_funds_expended,
    "Training Services Cost Per Served" AS training_services_cost_per_served,
    "Percent enrolled in more than one core program" AS percent_enrolled_in_more_than_one_core_program,
    "STATE NAME_1" AS state_name_1,
    "STATE CODE_1" AS state_code_1,
    "Total Statewide: Total Participants Served" AS total_statewide_total_participants_served,
    "Total Statewide: Total Participants Exited" AS total_statewide_total_participants_exited,
    "Total Statewide, Target: Employment Q2 Number" AS total_statewide_target_employment_q2_number,
    "Total Statewide, Target: Employment Q2 Rate" AS total_statewide_target_employment_q2_rate,
    "Total Statewide, Target: Employment Q4 Number" AS total_statewide_target_employment_q4_number,
    "Total Statewide, Target: Employment Q4 Rate" AS total_statewide_target_employment_q4_rate,
    "Total Statewide, Target: Median Earnings" AS total_statewide_target_median_earnings,
    "Total Statewide, Target: Credential Number" AS total_statewide_target_credential_number,
    "Total Statewide, Target: Credential Rate" AS total_statewide_target_credential_rate,
    "Total Statewide, Target: Measurable Skills Number" AS total_statewide_target_measurable_skills_number,
    "Total Statewide, Target: Measurable Skills Rate" AS total_statewide_target_measurable_skills_rate,
    "Total Statewide, Actual: Employment Q2 Number" AS total_statewide_actual_employment_q2_number,
    "Total Statewide, Actual: Employment Q2 Rate" AS total_statewide_actual_employment_q2_rate,
    "Total Statewide, Actual: Employment Q4 Number" AS total_statewide_actual_employment_q4_number,
    "Total Statewide, Actual: Employment Q4 Rate" AS total_statewide_actual_employment_q4_rate,
    "Total Statewide, Actual: Median Earnings" AS total_statewide_actual_median_earnings,
    "Total Statewide, Actual: Credential Number" AS total_statewide_actual_credential_number,
    "Total Statewide, Actual: Credential Rate" AS total_statewide_actual_credential_rate,
    "Total Statewide, Actual: Measurable Skills Number" AS total_statewide_actual_measurable_skills_number,
    "Total Statewide, Actual: Measurable Skills Rate" AS total_statewide_actual_measurable_skills_rate,
    "Sex, Female: Total Participants Served" AS sex_female_total_participants_served,
    "Sex, Female: Total Participants Exited" AS sex_female_total_participants_exited,
    "Sex, Female: Employment Q2 Number" AS sex_female_employment_q2_number,
    "Sex, Female: Employment Q2 Rate" AS sex_female_employment_q2_rate,
    "Sex, Female: Employment Q4 Number" AS sex_female_employment_q4_number,
    "Sex, Female: Employment Q4 Rate" AS sex_female_employment_q4_rate,
    "Sex, Female: Median Earnings" AS sex_female_median_earnings,
    "Sex, Female: Credential Number" AS sex_female_credential_number,
    "Sex, Female: Credential Rate" AS sex_female_credential_rate,
    "Sex, Female: Measurable Skills Number" AS sex_female_measurable_skills_number,
    "Sex, Female: Measurable Skills Rate" AS sex_female_measurable_skills_rate,
    "Sex, Male: Total Participants Served" AS sex_male_total_participants_served,
    "Sex, Male: Total Participants Exited" AS sex_male_total_participants_exited,
    "Sex, Male: Employment Q2 Number" AS sex_male_employment_q2_number,
    "Sex, Male: Employment Q2 Rate" AS sex_male_employment_q2_rate,
    "Sex, Male: Employment Q4 Number" AS sex_male_employment_q4_number,
    "Sex, Male: Employment Q4 Rate" AS sex_male_employment_q4_rate,
    "Sex, Male: Median Earnings" AS sex_male_median_earnings,
    "Sex, Male: Credential Number" AS sex_male_credential_number,
    "Sex, Male: Credential Rate" AS sex_male_credential_rate,
    "Sex, Male: Measurable Skills Number" AS sex_male_measurable_skills_number,
    "Sex, Male: Measurable Skills Rate" AS sex_male_measurable_skills_rate,
    "Age, Younger than 16: Total Participants Served" AS age_younger_than_16_total_participants_served,
    "Age, Younger than 16: Total Participants Exited" AS age_younger_than_16_total_participants_exited,
    "Age, Younger than 16: Employment Q2 Number" AS age_younger_than_16_employment_q2_number,
    "Age, Younger than 16: Employment Q2 Rate" AS age_younger_than_16_employment_q2_rate,
    "Age, Younger than 16: Employment Q4 Number" AS age_younger_than_16_employment_q4_number,
    "Age, Younger than 16: Employment Q4 Rate" AS age_younger_than_16_employment_q4_rate,
    "Age, Younger than 16: Median Earnings" AS age_younger_than_16_median_earnings,
    "Age, Younger than 16: Credential Number" AS age_younger_than_16_credential_number,
    "Age, Younger than 16: Credential Rate" AS age_younger_than_16_credential_rate,
    "Age, Younger than 16: Measurable Skills Number" AS age_younger_than_16_measurable_skills_number,
    "Age, Younger than 16: Measurable Skills Rate" AS age_younger_than_16_measurable_skills_rate,
    "Age, 16 to 18: Total Participants Served" AS age_16_to_18_total_participants_served,
    "Age, 16 to 18: Total Participants Exited" AS age_16_to_18_total_participants_exited,
    "Age, 16 to 18: Employment Q2 Number" AS age_16_to_18_employment_q2_number,
    "Age, 16 to 18: Employment Q2 Rate" AS age_16_to_18_employment_q2_rate,
    "Age, 16 to 18: Employment Q4 Number" AS age_16_to_18_employment_q4_number,
    "Age, 16 to 18: Employment Q4 Rate" AS age_16_to_18_employment_q4_rate,
    "Age, 16 to 18: Median Earnings" AS age_16_to_18_median_earnings,
    "Age, 16 to 18: Credential Number" AS age_16_to_18_credential_number,
    "Age, 16 to 18: Credential Rate" AS age_16_to_18_credential_rate,
    "Age, 16 to 18: Measurable Skills Number" AS age_16_to_18_measurable_skills_number,
    "Age, 16 to 18: Measurable Skills Rate" AS age_16_to_18_measurable_skills_rate,
    "Age, 19 to 24: Total Participants Served" AS age_19_to_24_total_participants_served,
    "Age, 19 to 24: Total Participants Exited" AS age_19_to_24_total_participants_exited,
    "Age, 19 to 24: Employment Q2 Number" AS age_19_to_24_employment_q2_number,
    "Age, 19 to 24: Employment Q2 Rate" AS age_19_to_24_employment_q2_rate,
    "Age, 19 to 24: Employment Q4 Number" AS age_19_to_24_employment_q4_number,
    "Age, 19 to 24: Employment Q4 Rate" AS age_19_to_24_employment_q4_rate,
    "Age, 19 to 24: Median Earnings" AS age_19_to_24_median_earnings,
    "Age, 19 to 24: Credential Number" AS age_19_to_24_credential_number,
    "Age, 19 to 24: Credential Rate" AS age_19_to_24_credential_rate,
    "Age, 19 to 24: Measurable Skills Number" AS age_19_to_24_measurable_skills_number,
    "Age, 19 to 24: Measurable Skills Rate" AS age_19_to_24_measurable_skills_rate,
    "Age, 25 to 44: Total Participants Served" AS age_25_to_44_total_participants_served,
    "Age, 25 to 44: Total Participants Exited" AS age_25_to_44_total_participants_exited,
    "Age, 25 to 44: Employment Q2 Number" AS age_25_to_44_employment_q2_number,
    "Age, 25 to 44: Employment Q2 Rate" AS age_25_to_44_employment_q2_rate,
    "Age, 25 to 44: Employment Q4 Number" AS age_25_to_44_employment_q4_number,
    "Age, 25 to 44: Employment Q4 Rate" AS age_25_to_44_employment_q4_rate,
    "Age, 25 to 44: Median Earnings" AS age_25_to_44_median_earnings,
    "Age, 25 to 44: Credential Number" AS age_25_to_44_credential_number,
    "Age, 25 to 44: Credential Rate" AS age_25_to_44_credential_rate,
    "Age, 25 to 44: Measurable Skills Number" AS age_25_to_44_measurable_skills_number,
    "Age, 25 to 44: Measurable Skills Rate" AS age_25_to_44_measurable_skills_rate,
    "Age, 45 to 54: Total Participants Served" AS age_45_to_54_total_participants_served,
    "Age, 45 to 54: Total Participants Exited" AS age_45_to_54_total_participants_exited,
    "Age, 45 to 54: Employment Q2 Number" AS age_45_to_54_employment_q2_number,
    "Age, 45 to 54: Employment Q2 Rate" AS age_45_to_54_employment_q2_rate,
    "Age, 45 to 54: Employment Q4 Number" AS age_45_to_54_employment_q4_number,
    "Age, 45 to 54: Employment Q4 Rate" AS age_45_to_54_employment_q4_rate,
    "Age, 45 to 54: Median Earnings" AS age_45_to_54_median_earnings,
    "Age, 45 to 54: Credential Number" AS age_45_to_54_credential_number,
    "Age, 45 to 54: Credential Rate" AS age_45_to_54_credential_rate,
    "Age, 45 to 54: Measurable Skills Number" AS age_45_to_54_measurable_skills_number,
    "Age, 45 to 54: Measurable Skills Rate" AS age_45_to_54_measurable_skills_rate,
    "Age, 55 to 59 Total Participants Served" AS age_55_to_59_total_participants_served,
    "Age, 55 to 59 Total Participants Exited" AS age_55_to_59_total_participants_exited,
    "Age, 55 to 59 Employment Q2 Number" AS age_55_to_59_employment_q2_number,
    "Age, 55 to 59 Employment Q2 Rate" AS age_55_to_59_employment_q2_rate,
    "Age, 55 to 59 Employment Q4 Number" AS age_55_to_59_employment_q4_number,
    "Age, 55 to 59 Employment Q4 Rate" AS age_55_to_59_employment_q4_rate,
    "Age, 55 to 59 Median Earnings" AS age_55_to_59_median_earnings,
    "Age, 55 to 59 Credential Number" AS age_55_to_59_credential_number,
    "Age, 55 to 59 Credential Rate" AS age_55_to_59_credential_rate,
    "Age, 55 to 59 Measurable Skills Number" AS age_55_to_59_measurable_skills_number,
    "Age, 55 to 59 Measurable Skills Rate" AS age_55_to_59_measurable_skills_rate,
    "Age, 60 and older Total Participants Served" AS age_60_and_older_total_participants_served,
    "Age, 60 and older Total Participants Exited" AS age_60_and_older_total_participants_exited,
    "Age, 60 and older Employment Q2 Number" AS age_60_and_older_employment_q2_number,
    "Age, 60 and older Employment Q2 Rate" AS age_60_and_older_employment_q2_rate,
    "Age, 60 and older Employment Q4 Number" AS age_60_and_older_employment_q4_number,
    "Age, 60 and older Employment Q4 Rate" AS age_60_and_older_employment_q4_rate,
    "Age, 60 and older Median Earnings" AS age_60_and_older_median_earnings,
    "Age, 60 and older Credential Number" AS age_60_and_older_credential_number,
    "Age, 60 and older Credential Rate" AS age_60_and_older_credential_rate,
    "Age, 60 and older Measurable Skills Number" AS age_60_and_older_measurable_skills_number,
    "Age, 60 and older Measurable Skills Rate" AS age_60_and_older_measurable_skills_rate,
    "Ethnicity/Race, American Indian/Alaskan Native: Total Participants Served" AS ethnicity_race_american_indian_alaskan_native_total_participants_served,
    "Ethnicity/Race, American Indian/Alaskan Native: Total Participants Exited" AS ethnicity_race_american_indian_alaskan_native_total_participants_exited,
    "Ethnicity/Race, American Indian/Alaskan Native: Employment Q2 Number" AS ethnicity_race_american_indian_alaskan_native_employment_q2_number,
    "Ethnicity/Race, American Indian/Alaskan Native: Employment Q2 Rate" AS ethnicity_race_american_indian_alaskan_native_employment_q2_rate,
    "Ethnicity/Race, American Indian/Alaskan Native: Employment Q4 Number" AS ethnicity_race_american_indian_alaskan_native_employment_q4_number,
    "Ethnicity/Race, American Indian/Alaskan Native: Employment Q4 Rate" AS ethnicity_race_american_indian_alaskan_native_employment_q4_rate,
    "Ethnicity/Race, American Indian/Alaskan Native: Median Earnings" AS ethnicity_race_american_indian_alaskan_native_median_earnings,
    "Ethnicity/Race, American Indian/Alaskan Native: Credential Number" AS ethnicity_race_american_indian_alaskan_native_credential_number,
    "Ethnicity/Race, American Indian/Alaskan Native: Credential Rate" AS ethnicity_race_american_indian_alaskan_native_credential_rate,
    "Ethnicity/Race, American Indian/Alaskan Native: Measurable Skills Number" AS ethnicity_race_american_indian_alaskan_native_measurable_skills_number,
    "Ethnicity/Race, American Indian/Alaskan Native: Measurable Skills Rate" AS ethnicity_race_american_indian_alaskan_native_measurable_skills_rate,
    "Ethnicity/Race, Asian: Total Participants Served" AS ethnicity_race_asian_total_participants_served,
    "Ethnicity/Race, Asian: Total Participants Exited" AS ethnicity_race_asian_total_participants_exited,
    "Ethnicity/Race, Asian: Employment Q2 Number" AS ethnicity_race_asian_employment_q2_number,
    "Ethnicity/Race, Asian: Employment Q2 Rate" AS ethnicity_race_asian_employment_q2_rate,
    "Ethnicity/Race, Asian: Employment Q4 Number" AS ethnicity_race_asian_employment_q4_number,
    "Ethnicity/Race, Asian: Employment Q4 Rate" AS ethnicity_race_asian_employment_q4_rate,
    "Ethnicity/Race, Asian: Median Earnings" AS ethnicity_race_asian_median_earnings,
    "Ethnicity/Race, Asian: Credential Number" AS ethnicity_race_asian_credential_number,
    "Ethnicity/Race, Asian: Credential Rate" AS ethnicity_race_asian_credential_rate,
    "Ethnicity/Race, Asian: Measurable Skills Number" AS ethnicity_race_asian_measurable_skills_number,
    "Ethnicity/Race, Asian: Measurable Skills Rate" AS ethnicity_race_asian_measurable_skills_rate,
    "Ethnicity/Race, Black/African American: Total Participants Served" AS ethnicity_race_black_african_american_total_participants_served,
    "Ethnicity/Race, Black/African American: Total Participants Exited" AS ethnicity_race_black_african_american_total_participants_exited,
    "Ethnicity/Race, Black/African American: Employment Q2 Number" AS ethnicity_race_black_african_american_employment_q2_number,
    "Ethnicity/Race, Black/African American: Employment Q2 Rate" AS ethnicity_race_black_african_american_employment_q2_rate,
    "Ethnicity/Race, Black/African American: Employment Q4 Number" AS ethnicity_race_black_african_american_employment_q4_number,
    "Ethnicity/Race, Black/African American: Employment Q4 Rate" AS ethnicity_race_black_african_american_employment_q4_rate,
    "Ethnicity/Race, Black/African American: Median Earnings" AS ethnicity_race_black_african_american_median_earnings,
    "Ethnicity/Race, Black/African American: Credential Number" AS ethnicity_race_black_african_american_credential_number,
    "Ethnicity/Race, Black/African American: Credential Rate" AS ethnicity_race_black_african_american_credential_rate,
    "Ethnicity/Race, Black/African American: Measurable Skills Number" AS ethnicity_race_black_african_american_measurable_skills_number,
    "Ethnicity/Race, Black/African American: Measurable Skills Rate" AS ethnicity_race_black_african_american_measurable_skills_rate,
    "Ethnicity/Race, Hispanic/Latino: Total Participants Served" AS ethnicity_race_hispanic_latino_total_participants_served,
    "Ethnicity/Race, Hispanic/Latino: Total Participants Exited" AS ethnicity_race_hispanic_latino_total_participants_exited,
    "Ethnicity/Race, Hispanic/Latino: Employment Q2 Number" AS ethnicity_race_hispanic_latino_employment_q2_number,
    "Ethnicity/Race, Hispanic/Latino: Employment Q2 Rate" AS ethnicity_race_hispanic_latino_employment_q2_rate,
    "Ethnicity/Race, Hispanic/Latino: Employment Q4 Number" AS ethnicity_race_hispanic_latino_employment_q4_number,
    "Ethnicity/Race, Hispanic/Latino: Employment Q4 Rate" AS ethnicity_race_hispanic_latino_employment_q4_rate,
    "Ethnicity/Race, Hispanic/Latino: Median Earnings" AS ethnicity_race_hispanic_latino_median_earnings,
    "Ethnicity/Race, Hispanic/Latino: Credential Number" AS ethnicity_race_hispanic_latino_credential_number,
    "Ethnicity/Race, Hispanic/Latino: Credential Rate" AS ethnicity_race_hispanic_latino_credential_rate,
    "Ethnicity/Race, Hispanic/Latino: Measurable Skills Number" AS ethnicity_race_hispanic_latino_measurable_skills_number,
    "Ethnicity/Race, Hispanic/Latino: Measurable Skills Rate" AS ethnicity_race_hispanic_latino_measurable_skills_rate,
    "Ethnicity/Race, Native Hawaiian/Pacific Islander: Total Participants Served" AS ethnicity_race_native_hawaiian_pacific_islander_total_participants_served,
    "Ethnicity/Race, Native Hawaiian/Pacific Islander: Total Participants Exited" AS ethnicity_race_native_hawaiian_pacific_islander_total_participants_exited,
    "Ethnicity/Race, Native Hawaiian/Pacific Islander: Employment Q2 Number" AS ethnicity_race_native_hawaiian_pacific_islander_employment_q2_number,
    "Ethnicity/Race, Native Hawaiian/Pacific Islander: Employment Q2 Rate" AS ethnicity_race_native_hawaiian_pacific_islander_employment_q2_rate,
    "Ethnicity/Race, Native Hawaiian/Pacific Islander: Employment Q4 Number" AS ethnicity_race_native_hawaiian_pacific_islander_employment_q4_number,
    "Ethnicity/Race, Native Hawaiian/Pacific Islander: Employment Q4 Rate" AS ethnicity_race_native_hawaiian_pacific_islander_employment_q4_rate,
    "Ethnicity/Race, Native Hawaiian/Pacific Islander: Median Earnings" AS ethnicity_race_native_hawaiian_pacific_islander_median_earnings,
    "Ethnicity/Race, Native Hawaiian/Pacific Islander: Credential Number" AS ethnicity_race_native_hawaiian_pacific_islander_credential_number,
    "Ethnicity/Race, Native Hawaiian/Pacific Islander: Credential Rate" AS ethnicity_race_native_hawaiian_pacific_islander_credential_rate,
    "Ethnicity/Race, Native Hawaiian/Pacific Islander: Measurable Skills Number" AS ethnicity_race_native_hawaiian_pacific_islander_measurable_skills_number,
    "Ethnicity/Race, Native Hawaiian/Pacific Islander: Measurable Skills Rate" AS ethnicity_race_native_hawaiian_pacific_islander_measurable_skills_rate,
    "Ethnicity/Race, White: Total Participants Served" AS ethnicity_race_white_total_participants_served,
    "Ethnicity/Race, White: Total Participants Exited" AS ethnicity_race_white_total_participants_exited,
    "Ethnicity/Race, White: Employment Q2 Number" AS ethnicity_race_white_employment_q2_number,
    "Ethnicity/Race, White: Employment Q2 Rate" AS ethnicity_race_white_employment_q2_rate,
    "Ethnicity/Race, White: Employment Q4 Number" AS ethnicity_race_white_employment_q4_number,
    "Ethnicity/Race, White: Employment Q4 Rate" AS ethnicity_race_white_employment_q4_rate,
    "Ethnicity/Race, White: Median Earnings" AS ethnicity_race_white_median_earnings,
    "Ethnicity/Race, White: Credential Number" AS ethnicity_race_white_credential_number,
    "Ethnicity/Race, White: Credential Rate" AS ethnicity_race_white_credential_rate,
    "Ethnicity/Race, White: Measurable Skills Number" AS ethnicity_race_white_measurable_skills_number,
    "Ethnicity/Race, White: Measurable Skills Rate" AS ethnicity_race_white_measurable_skills_rate,
    "Ethnicity/Race, More Than One Race: Total Participants Served" AS ethnicity_race_more_than_one_race_total_participants_served,
    "Ethnicity/Race, More Than One Race: Total Participants Exited" AS ethnicity_race_more_than_one_race_total_participants_exited,
    "Ethnicity/Race, More Than One Race: Employment Q2 Number" AS ethnicity_race_more_than_one_race_employment_q2_number,
    "Ethnicity/Race, More Than One Race: Employment Q2 Rate" AS ethnicity_race_more_than_one_race_employment_q2_rate,
    "Ethnicity/Race, More Than One Race: Employment Q4 Number" AS ethnicity_race_more_than_one_race_employment_q4_number,
    "Ethnicity/Race, More Than One Race: Employment Q4 Rate" AS ethnicity_race_more_than_one_race_employment_q4_rate,
    "Ethnicity/Race, More Than One Race: Median Earnings" AS ethnicity_race_more_than_one_race_median_earnings,
    "Ethnicity/Race, More Than One Race: Credential Number" AS ethnicity_race_more_than_one_race_credential_number,
    "Ethnicity/Race, More Than One Race: Credential Rate" AS ethnicity_race_more_than_one_race_credential_rate,
    "Ethnicity/Race, More Than One Race: Measurable Skills Number" AS ethnicity_race_more_than_one_race_measurable_skills_number,
    "Ethnicity/Race, More Than One Race: Measurable Skills Rate" AS ethnicity_race_more_than_one_race_measurable_skills_rate,
    "Displaced Homemakers: Total Participant Number" AS displaced_homemakers_total_participant_number,
    "Displaced Homemakers: Total Participants Served" AS displaced_homemakers_total_participants_served,
    "Displaced Homemakers: Employment Q2 Number" AS displaced_homemakers_employment_q2_number,
    "Displaced Homemakers: Employment Q2 Rate" AS displaced_homemakers_employment_q2_rate,
    "Displaced Homemakers: Employment Q4 Number" AS displaced_homemakers_employment_q4_number,
    "Displaced Homemakers: Employment Q4 Rate" AS displaced_homemakers_employment_q4_rate,
    "Displaced Homemakers: Median Earnings" AS displaced_homemakers_median_earnings,
    "Displaced Homemakers: Credential Number" AS displaced_homemakers_credential_number,
    "Displaced Homemakers: Credential Rate" AS displaced_homemakers_credential_rate,
    "Displaced Homemakers: Measurable Skills Number" AS displaced_homemakers_measurable_skills_number,
    "Displaced Homemakers: Measurable Skills Rate" AS displaced_homemakers_measurable_skills_rate,
    "English Language Learners: Total Participants served" AS english_language_learners_total_participants_served,
    "English Language Learners: Total Participants Exited" AS english_language_learners_total_participants_exited,
    "English Language Learners: Employment Q2 Number" AS english_language_learners_employment_q2_number,
    "English Language Learners: Employment Q2 Rate" AS english_language_learners_employment_q2_rate,
    "English Language Learners: Employment Q4 Number" AS english_language_learners_employment_q4_number,
    "English Language Learners: Employment Q4 Rate" AS english_language_learners_employment_q4_rate,
    "English Language Learners: Median Earnings" AS english_language_learners_median_earnings,
    "English Language Learners: Credential Number" AS english_language_learners_credential_number,
    "English Language Learners: Credential Rate" AS english_language_learners_credential_rate,
    "English Language Learners: Measurable Skills Number" AS english_language_learners_measurable_skills_number,
    "English Language Learners: Measurable Skills Rate" AS english_language_learners_measurable_skills_rate,
    "Exhausting TANF within 2 years: Total Participants Served" AS exhausting_tanf_within_2_years_total_participants_served,
    "Exhausting TANF within 2 years: Total Participants Exited" AS exhausting_tanf_within_2_years_total_participants_exited,
    "Exhausting TANF within 2 years: Employment Q2 Number" AS exhausting_tanf_within_2_years_employment_q2_number,
    "Exhausting TANF within 2 years: Employment Q2 Rate" AS exhausting_tanf_within_2_years_employment_q2_rate,
    "Exhausting TANF within 2 years: Employment Q4 Number" AS exhausting_tanf_within_2_years_employment_q4_number,
    "Exhausting TANF within 2 years: Employment Q4 Rate" AS exhausting_tanf_within_2_years_employment_q4_rate,
    "Exhausting TANF within 2 years: Median Earnings" AS exhausting_tanf_within_2_years_median_earnings,
    "Exhausting TANF within 2 years: Credential Number" AS exhausting_tanf_within_2_years_credential_number,
    "Exhausting TANF within 2 years: Credential Rate" AS exhausting_tanf_within_2_years_credential_rate,
    "Exhausting TANF within 2 years: Measurable Skills Number" AS exhausting_tanf_within_2_years_measurable_skills_number,
    "Exhausting TANF within 2 years: Measurable Skills Rate" AS exhausting_tanf_within_2_years_measurable_skills_rate,
    "Ex-offenders: Total Participants Served" AS ex_offenders_total_participants_served,
    "Ex-offenders: Total Participants Exited" AS ex_offenders_total_participants_exited,
    "Ex-offenders: Employment Q2 Number" AS ex_offenders_employment_q2_number,
    "Ex-offenders: Employment Q2 Rate" AS ex_offenders_employment_q2_rate,
    "Ex-offenders: Employment Q4 Number" AS ex_offenders_employment_q4_number,
    "Ex-offenders: Employment Q4 Rate" AS ex_offenders_employment_q4_rate,
    "Ex-offenders: Median Earnings" AS ex_offenders_median_earnings,
    "Ex-offenders: Credential Number" AS ex_offenders_credential_number,
    "Ex-offenders: Credential Rate" AS ex_offenders_credential_rate,
    "Ex-offenders: Measurable Skills Number" AS ex_offenders_measurable_skills_number,
    "Ex-offenders: Measurable Skills Rate" AS ex_offenders_measurable_skills_rate,
    "Homeless Individuals/Runaway Youth: Total Participants Served" AS homeless_individuals_runaway_youth_total_participants_served,
    "Homeless Individuals/Runaway Youth: Total Participants Exited" AS homeless_individuals_runaway_youth_total_participants_exited,
    "Homeless Individuals/Runaway Youth: Employment Q2 Number" AS homeless_individuals_runaway_youth_employment_q2_number,
    "Homeless Individuals/Runaway Youth: Employment Q2 Rate" AS homeless_individuals_runaway_youth_employment_q2_rate,
    "Homeless Individuals/Runaway Youth: Employment Q4 Number" AS homeless_individuals_runaway_youth_employment_q4_number,
    "Homeless Individuals/Runaway Youth: Employment Q4 Rate" AS homeless_individuals_runaway_youth_employment_q4_rate,
    "Homeless Individuals/Runaway Youth: Median Earnings" AS homeless_individuals_runaway_youth_median_earnings,
    "Homeless Individuals/Runaway Youth: Credential Number" AS homeless_individuals_runaway_youth_credential_number,
    "Homeless Individuals/Runaway Youth: Credential Rate" AS homeless_individuals_runaway_youth_credential_rate,
    "Homeless Individuals/Runaway Youth: Measurable Skills Number" AS homeless_individuals_runaway_youth_measurable_skills_number,
    "Homeless Individuals/Runaway Youth: Measurable Skills Rate" AS homeless_individuals_runaway_youth_measurable_skills_rate,
    "Long-term Unemployed: Total Participants Served" AS long_term_unemployed_total_participants_served,
    "Long-term Unemployed: Total Participants Exited" AS long_term_unemployed_total_participants_exited,
    "Long-term Unemployed: Employment Q2 Number" AS long_term_unemployed_employment_q2_number,
    "Long-term Unemployed: Employment Q2 Rate" AS long_term_unemployed_employment_q2_rate,
    "Long-term Unemployed: Employment Q4 Number" AS long_term_unemployed_employment_q4_number,
    "Long-term Unemployed: Employment Q4 Rate" AS long_term_unemployed_employment_q4_rate,
    "Long-term Unemployed: Median Earnings" AS long_term_unemployed_median_earnings,
    "Long-term Unemployed: Credential Number" AS long_term_unemployed_credential_number,
    "Long-term Unemployed: Credential Rate" AS long_term_unemployed_credential_rate,
    "Long-term Unemployed: Measurable Skills Number" AS long_term_unemployed_measurable_skills_number,
    "Long-term Unemployed: Measurable Skills Rate" AS long_term_unemployed_measurable_skills_rate,
    "Low-Income Individuals: Total Participants Served" AS low_income_individuals_total_participants_served,
    "Low-Income Individuals: Total Participants Exited" AS low_income_individuals_total_participants_exited,
    "Low-Income Individuals: Employment Q2 Number" AS low_income_individuals_employment_q2_number,
    "Low-Income Individuals: Employment Q2 Rate" AS low_income_individuals_employment_q2_rate,
    "Low-Income Individuals: Employment Q4 Number" AS low_income_individuals_employment_q4_number,
    "Low-Income Individuals: Employment Q4 Rate" AS low_income_individuals_employment_q4_rate,
    "Low-Income Individuals: Median Earnings" AS low_income_individuals_median_earnings,
    "Low-Income Individuals: Credential Number" AS low_income_individuals_credential_number,
    "Low-Income Individuals: Credential Rate" AS low_income_individuals_credential_rate,
    "Low-Income Individuals: Measurable Skills Number" AS low_income_individuals_measurable_skills_number,
    "Low-Income Individuals: Measurable Skills Rate" AS low_income_individuals_measurable_skills_rate,
    "Migrant and Seasonal Farmworkers: Total Participants Served" AS migrant_and_seasonal_farmworkers_total_participants_served,
    "Migrant and Seasonal Farmworkers: Total Participants Exited" AS migrant_and_seasonal_farmworkers_total_participants_exited,
    "Migrant and Seasonal Farmworkers: Employment Q2 Number" AS migrant_and_seasonal_farmworkers_employment_q2_number,
    "Migrant and Seasonal Farmworkers: Employment Q2 Rate" AS migrant_and_seasonal_farmworkers_employment_q2_rate,
    "Migrant and Seasonal Farmworkers: Employment Q4 Number" AS migrant_and_seasonal_farmworkers_employment_q4_number,
    "Migrant and Seasonal Farmworkers: Employment Q4 Rate" AS migrant_and_seasonal_farmworkers_employment_q4_rate,
    "Migrant and Seasonal Farmworkers: Median Earnings" AS migrant_and_seasonal_farmworkers_median_earnings,
    "Migrant and Seasonal Farmworkers: Credential Number" AS migrant_and_seasonal_farmworkers_credential_number,
    "Migrant and Seasonal Farmworkers: Credential Rate" AS migrant_and_seasonal_farmworkers_credential_rate,
    "Migrant and Seasonal Farmworkers: Measurable Skills Number" AS migrant_and_seasonal_farmworkers_measurable_skills_number,
    "Migrant and Seasonal Farmworkers: Measurable Skills Rate" AS migrant_and_seasonal_farmworkers_measurable_skills_rate,
    "Individuals with Disabilities: Total Participants Served" AS individuals_with_disabilities_total_participants_served,
    "Individuals with Disabilities: Total Participants Exited" AS individuals_with_disabilities_total_participants_exited,
    "Individuals with Disabilities: Employment Q2 Number" AS individuals_with_disabilities_employment_q2_number,
    "Individuals with Disabilities: Employment Q2 Rate" AS individuals_with_disabilities_employment_q2_rate,
    "Individuals with Disabilities: Employment Q4 Number" AS individuals_with_disabilities_employment_q4_number,
    "Individuals with Disabilities: Employment Q4 Rate" AS individuals_with_disabilities_employment_q4_rate,
    "Individuals with Disabilities: Median Earnings" AS individuals_with_disabilities_median_earnings,
    "Individuals with Disabilities: Credential Number" AS individuals_with_disabilities_credential_number,
    "Individuals with Disabilities: Credential Rate" AS individuals_with_disabilities_credential_rate,
    "Individuals with Disabilities: Measurable Skills Number" AS individuals_with_disabilities_measurable_skills_number,
    "Individuals with Disabilities: Measurable Skills Rate" AS individuals_with_disabilities_measurable_skills_rate,
    "Single Parents: Total Participants Served" AS single_parents_total_participants_served,
    "Single Parents: Total Participants Exited" AS single_parents_total_participants_exited,
    "Single Parents: Employment Q2 Number" AS single_parents_employment_q2_number,
    "Single Parents: Employment Q2 Rate" AS single_parents_employment_q2_rate,
    "Single Parents: Employment Q4 Number" AS single_parents_employment_q4_number,
    "Single Parents: Employment Q4 Rate" AS single_parents_employment_q4_rate,
    "Single Parents: Median Earnings" AS single_parents_median_earnings,
    "Single Parents: Credential Number" AS single_parents_credential_number,
    "Single Parents: Credential Rate" AS single_parents_credential_rate,
    "Single Parents: Measurable Skills Number" AS single_parents_measurable_skills_number,
    "Single Parents: Measurable Skills Rate" AS single_parents_measurable_skills_rate,
    "Youth in foster care or aged out of system: Total Participants Served" AS youth_in_foster_care_or_aged_out_of_system_total_participants_served,
    "Youth in foster care or aged out of system: Total Participants Exited" AS youth_in_foster_care_or_aged_out_of_system_total_participants_exited,
    "Youth in foster care or aged out of system: Employment Q2 Number" AS youth_in_foster_care_or_aged_out_of_system_employment_q2_number,
    "Youth in foster care or aged out of system: Employment Q2 Rate" AS youth_in_foster_care_or_aged_out_of_system_employment_q2_rate,
    "Youth in foster care or aged out of system: Employment Q4 Number" AS youth_in_foster_care_or_aged_out_of_system_employment_q4_number,
    "Youth in foster care or aged out of system: Employment Q4 Rate" AS youth_in_foster_care_or_aged_out_of_system_employment_q4_rate,
    "Youth in foster care or aged out of system: Median Earnings" AS youth_in_foster_care_or_aged_out_of_system_median_earnings,
    "Youth in foster care or aged out of system: Credential Number" AS youth_in_foster_care_or_aged_out_of_system_credential_number,
    "Youth in foster care or aged out of system: Credential Rate" AS youth_in_foster_care_or_aged_out_of_system_credential_rate,
    "Youth in foster care or aged out of system: Measurable Skills Number" AS youth_in_foster_care_or_aged_out_of_system_measurable_skills_number,
    "Youth in foster care or aged out of system: Measurable Skills Rate" AS youth_in_foster_care_or_aged_out_of_system_measurable_skills_rate,
    "Educational Functioning Level Gain: Total Skills Gain" AS educational_functioning_level_gain_total_skills_gain,
    "Secondary School Diploma \Total Skills Gain" AS secondary_school_diploma_total_skills_gain,
    "Secondary/Postsecondary Transcript Total Skills Gain" AS secondary_postsecondary_transcript_total_skills_gain,
    "Training Milestone Total Skills Gain" AS training_milestone_total_skills_gain,
    "Skills Progression Total Skills Gain" AS skills_progression_total_skills_gain,
    "Unnamed: 79" AS unnamed_79,
    "Unnamed: 80" AS unnamed_80,
    "Unnamed: 81" AS unnamed_81,
    "Unnamed: 82" AS unnamed_82,
    "Unnamed: 83" AS unnamed_83,
    "Unnamed: 84" AS unnamed_84,
    "Unnamed: 85" AS unnamed_85,
    "Unnamed: 86" AS unnamed_86,
    "Unnamed: 87" AS unnamed_87,
    "Unnamed: 88" AS unnamed_88,
    "Unnamed: 89" AS unnamed_89,
    "Unnamed: 90" AS unnamed_90,
    "Unnamed: 91" AS unnamed_91,
    "Unnamed: 92" AS unnamed_92,
    "Unnamed: 93" AS unnamed_93,
    "Unnamed: 94" AS unnamed_94,
    "Unnamed: 95" AS unnamed_95,
    "Unnamed: 96" AS unnamed_96,
    "Unnamed: 97" AS unnamed_97,
    "Unnamed: 98" AS unnamed_98,
    "Unnamed: 99" AS unnamed_99,
    "Unnamed: 100" AS unnamed_100
FROM "u-s-department-of-education-rsa-py2017-and-py2018-workforce-innovation-and-opportunity-act-wioa-annual-reports-6c781"
