-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "sheet_name",
    "row_number",
    "Unnamed: 0" AS unnamed_0,
    "Unnamed: 1" AS unnamed_1,
    "Unnamed: 2" AS unnamed_2,
    "Unnamed: 3" AS unnamed_3,
    "Unnamed: 4" AS unnamed_4,
    "Unnamed: 5" AS unnamed_5,
    "Unnamed: 6" AS unnamed_6,
    "Unnamed: 7" AS unnamed_7,
    "Unnamed: 8" AS unnamed_8,
    "Unnamed: 9" AS unnamed_9,
    "Unnamed: 10" AS unnamed_10,
    "Unnamed: 11" AS unnamed_11,
    "Unnamed: 12" AS unnamed_12,
    "Unnamed: 13" AS unnamed_13,
    "Unnamed: 14" AS unnamed_14,
    "Unnamed: 15" AS unnamed_15,
    "Unnamed: 16" AS unnamed_16,
    "Unnamed: 17" AS unnamed_17,
    "Unnamed: 18" AS unnamed_18,
    "Unnamed: 19" AS unnamed_19,
    "Unnamed: 20" AS unnamed_20,
    "Unnamed: 21" AS unnamed_21,
    "Unnamed: 22" AS unnamed_22,
    "Unnamed: 23" AS unnamed_23,
    "Unnamed: 24" AS unnamed_24,
    "column_6",
    "FFELP -- LOAN VOLUME (COMMITMENTS) BY GUARANTY AGENCY -- 12-MONTHS OF FY2005 AND FY2004" AS ffelp_loan_volume_commitments_by_guaranty_agency_12_months_of_fy2005_and_fy2004,
    "FEDERAL FAMILY EDUCATION LOAN PROGRAM (FFELP) -- ANNUAL AND CUMULATIVE COMMITMENTS-FY66--FY2005" AS federal_family_education_loan_program_ffelp_annual_and_cumulative_commitments_fy66_fy2005,
    "FEDERAL FAMILY EDUCATION LOAN PROGRAMS (FFELP) LOAN VOLUME FOR 12-MONTHS OF FY2005 & 2004" AS federal_family_education_loan_programs_ffelp_loan_volume_for_12_months_of_fy2005_2004,
    "FFELP -- LOAN VOLUME (COMMITMENTS) BY GUARANTY AGENCY -- 12-MONTHS OF FY2004 AND FY2003" AS ffelp_loan_volume_commitments_by_guaranty_agency_12_months_of_fy2004_and_fy2003,
    "FEDERAL FAMILY EDUCATION LOAN PROGRAMS (FFEL) LOAN VOLUME FOR 12-MONTHS OF FY2004 & 2003" AS federal_family_education_loan_programs_ffel_loan_volume_for_12_months_of_fy2004_2003,
    "FFELP -- LOAN VOLUME (COMMITMENTS) BY GUARANTY AGENCY -- 1ST 9-MONTHS OF FY2003 AND FY2002" AS ffelp_loan_volume_commitments_by_guaranty_agency_1st_9_months_of_fy2003_and_fy2002,
    "FEDERAL FAMILY EDUCATION LOAN PROGRAMS (FFEL) LOAN VOLUME FOR FIRST 9-MONTHS OF FY2003 & 2002" AS federal_family_education_loan_programs_ffel_loan_volume_for_first_9_months_of_fy2003_2002,
    "archive_member",
    "FEDERAL FAMILY EDUCATION LOAN PROGRAM -- LOAN VOLUME (COMMITMENTS) BY GUARANTY AGENCY" AS federal_family_education_loan_program_loan_volume_commitments_by_guaranty_agency,
    "Unnamed: 25" AS unnamed_25,
    "Unnamed: 26" AS unnamed_26,
    "Unnamed: 27" AS unnamed_27,
    "Unnamed: 28" AS unnamed_28,
    "Unnamed: 29" AS unnamed_29,
    "Unnamed: 30" AS unnamed_30,
    "subq1 - subsidized loans, 1st quarter" AS subq1_subsidized_loans_1st_quarter,
    "LOANTYPE" AS loantype,
    "MONTH" AS month,
    "NUMLOANS" AS numloans,
    "TOTALLOANS" AS totalloans,
    "NOTE" AS note,
    "WILLIAM D. FORD DIRECT LOAN PROGRAM" AS william_d_ford_direct_loan_program,
    "STATE" AS state,
    "DIRECT STAFFORD LOANS SUBSIDIZED -- LOAN VOLUME (COMMITMENTS) BY STATE" AS direct_stafford_loans_subsidized_loan_volume_commitments_by_state,
    "DIRECT STAFFORD LOANS UNSUBSIDIZED -- LOAN VOLUME (COMMITMENTS) BY STATE" AS direct_stafford_loans_unsubsidized_loan_volume_commitments_by_state,
    "DIRECT STAFFORD LOANS PLUS -- LOAN VOLUME (COMMITMENTS) BY STATE" AS direct_stafford_loans_plus_loan_volume_commitments_by_state,
    "DIRECT STAFFORD LOANS -- LOAN VOLUME (COMMITMENTS) BY STATE" AS direct_stafford_loans_loan_volume_commitments_by_state
FROM "u-s-department-of-education-ope-loan-volume-updates-8bbd5"
