-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Catalog-level dataset may contain mixed measures, geography levels, or reporting periods; inspect column definitions before aggregating.
SELECT
    "package_id",
    "package_title",
    "resource_id",
    "resource_name",
    "resource_format",
    "resource_position",
    "archive_member",
    "sheet_name",
    "row_number",
    "LEA_STATE" AS lea_state,
    "LEAID" AS leaid,
    "LEA_NAME" AS lea_name,
    "LEA_ADDRESS" AS lea_address,
    "LEA_CITY" AS lea_city,
    "LEA_ZIP" AS lea_zip,
    "CJJ" AS cjj,
    "LEA_ENR" AS lea_enr,
    "LEA_SCHOOLS" AS lea_schools,
    "LEA_CRCOORD_SEX_IND" AS lea_crcoord_sex_ind,
    "LEA_CRCOORD_RAC_IND" AS lea_crcoord_rac_ind,
    "LEA_CRCOORD_DIS_IND" AS lea_crcoord_dis_ind,
    "LEA_CRCOORD_SEX_FN" AS lea_crcoord_sex_fn,
    "LEA_CRCOORD_SEX_LN" AS lea_crcoord_sex_ln,
    "LEA_CRCOORD_SEX_PH" AS lea_crcoord_sex_ph,
    "LEA_CRCOORD_SEX_EM" AS lea_crcoord_sex_em,
    "LEA_CRCOORD_RAC_FN" AS lea_crcoord_rac_fn,
    "LEA_CRCOORD_RAC_LN" AS lea_crcoord_rac_ln,
    "LEA_CRCOORD_RAC_PH" AS lea_crcoord_rac_ph,
    "LEA_CRCOORD_RAC_EM" AS lea_crcoord_rac_em,
    "LEA_CRCOORD_DIS_FN" AS lea_crcoord_dis_fn,
    "LEA_CRCOORD_DIS_LN" AS lea_crcoord_dis_ln,
    "LEA_CRCOORD_DIS_PH" AS lea_crcoord_dis_ph,
    "LEA_CRCOORD_DIS_EM" AS lea_crcoord_dis_em,
    "LEA_DESEGPLAN" AS lea_desegplan,
    "LEA_HBPOLICY_IND" AS lea_hbpolicy_ind,
    "LEA_HBPOLICYURL_IND" AS lea_hbpolicyurl_ind,
    "LEA_HBPOLICY_URL" AS lea_hbpolicy_url,
    "LEA_ECE_IND" AS lea_ece_ind,
    "LEA_ECE_NONIDEA" AS lea_ece_nonidea,
    "LEA_PS_IND" AS lea_ps_ind,
    "LEA_PS_FULLDAYFREE" AS lea_ps_fulldayfree,
    "LEA_PS_FULLDAYCOST" AS lea_ps_fulldaycost,
    "LEA_PS_PARTDAYFREE" AS lea_ps_partdayfree,
    "LEA_PS_PARTDAYCOST" AS lea_ps_partdaycost,
    "LEA_PSENR_NONIDEA_A3" AS lea_psenr_nonidea_a3,
    "LEA_PSENR_NONIDEA_A4" AS lea_psenr_nonidea_a4,
    "LEA_PSENR_NONIDEA_A5" AS lea_psenr_nonidea_a5,
    "LEA_PSELIG_ALL" AS lea_pselig_all,
    "LEA_PSELIG_IDEA" AS lea_pselig_idea,
    "LEA_PSELIG_TITLEI" AS lea_pselig_titlei,
    "LEA_PSELIG_LOWINC" AS lea_pselig_lowinc,
    "LEA_KG_IND" AS lea_kg_ind,
    "LEA_KG_FULLDAYFREE" AS lea_kg_fulldayfree,
    "LEA_KG_FULLDAYCOST" AS lea_kg_fulldaycost,
    "LEA_KG_PARTDAYFREE" AS lea_kg_partdayfree,
    "LEA_KG_PARTDAYCOST" AS lea_kg_partdaycost,
    "DSO_LEA_DESEGPLAN" AS dso_lea_desegplan,
    "Field Name" AS field_name,
    "Field Description" AS field_description,
    "LEA_DISTED_IND" AS lea_disted_ind
FROM "u-s-department-of-education-civil-rights-data-collection-crdc-2013-14"
