-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "c0",
    "Wheat" AS "wheat",
    "Rye" AS "rye",
    "Oats" AS "oats",
    "Barley" AS "barley",
    "Wheat_2" AS "wheat_2",
    "Rye_2" AS "rye_2",
    "Oats_2" AS "oats_2",
    "Barley_2" AS "barley_2",
    "using wheat" AS "using_wheat",
    "Wheat_3" AS "wheat_3",
    "Rye_3" AS "rye_3",
    "Oats_3" AS "oats_3",
    "Barley_3" AS "barley_3",
    "Wheat_4" AS "wheat_4",
    "Rye_4" AS "rye_4",
    "Oats_4" AS "oats_4",
    "Barley_4" AS "barley_4",
    "Wheat_5" AS "wheat_5",
    "Rye_5" AS "rye_5",
    "Oats_5" AS "oats_5",
    "Barley_5" AS "barley_5",
    "Wheat_6" AS "wheat_6",
    "Rye_6" AS "rye_6",
    "Oats_6" AS "oats_6",
    "Barley_6" AS "barley_6",
    "c26",
    "for some years)" AS "for_some_years",
    "to 1766, then" AS "to_1766_then",
    "Peas" AS "peas",
    "c3",
    "Peas_2" AS "peas_2",
    "Potatoes" AS "potatoes",
    "Wheaten" AS "wheaten",
    "Fine" AS "fine",
    "Coarse" AS "coarse",
    "Wine" AS "wine",
    "Beer" AS "beer",
    "Vodka" AS "vodka",
    "Coffee" AS "coffee",
    "Wine_2" AS "wine_2",
    "Beer_2" AS "beer_2",
    "Vodka_2" AS "vodka_2",
    "Wine_3" AS "wine_3",
    "Beer_3" AS "beer_3",
    "Vodka_3" AS "vodka_3",
    "Wine_4" AS "wine_4",
    "Wine_5" AS "wine_5",
    "Beer_4" AS "beer_4",
    "Vodka (I)" AS "vodka_i",
    "Vodka (II)" AS "vodka_ii",
    "Wine_6" AS "wine_6",
    "Wine_7" AS "wine_7",
    "Salt" AS "salt",
    "Sugar" AS "sugar",
    "Pepper" AS "pepper",
    "Saffron" AS "saffron",
    "Salt_2" AS "salt_2",
    "Sugar_2" AS "sugar_2",
    "g/k" AS "g_k",
    "Ag/k" AS "ag_k",
    "Butter" AS "butter",
    "per 60 eggs" AS "per_60_eggs",
    "1704",
    "360",
    "120",
    "4.5" AS "4_5",
    "40.32" AS "40_32",
    "3.3185185185185184" AS "3_3185185185185184",
    "Linen" AS "linen",
    "Woolen cl" AS "woolen_cl",
    "Linen_2" AS "linen_2",
    "Woolen cl_2" AS "woolen_cl_2",
    "Canvas" AS "canvas",
    "Woolen cloth" AS "woolen_cloth",
    "Canvas/" AS "canvas_2",
    "Wollen cloth/" AS "wollen_cloth",
    "c10",
    "c11",
    "c12",
    "g/f" AS "g_f",
    "g/w" AS "g_w",
    "Ag/f" AS "ag_f",
    "Ag/w" AS "ag_w",
    "gAg/kilogram" AS "gag_kilogram",
    "Ag/m^3" AS "ag_m_3",
    "Ag/m^3_2" AS "ag_m_3_2",
    "Ag/100 kg" AS "ag_100_kg",
    "Ag/hl" AS "ag_hl",
    "Hard" AS "hard",
    "Soft" AS "soft",
    "Coal" AS "coal",
    "c14",
    "c15",
    "c16",
    "c17",
    "1000 bricks" AS "1000_bricks",
    "60 nails" AS "60_nails",
    "1000 nails" AS "1000_nails",
    "60 nails_2" AS "60_nails_2",
    "1000 nails_2" AS "1000_nails_2",
    "1701",
    "16",
    "1.81" AS "1_81",
    "c4",
    "36.2" AS "36_2"
FROM "gpih-lviv-prices-1701-1914"
