-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS sheet,
    "For 1578-1700, the monetary and financial system fell into c" AS for_1578_1700_the_monetary_and_financial_system_fell_into_c,
    "c1",
    "1505",
    "0.753" AS 0_753,
    "1535",
    "0.77" AS 0_77,
    "1565",
    "0.77_2" AS 0_77_2,
    "c8",
    "1595",
    "0.675" AS 0_675,
    "1625",
    "0.286" AS 0_286,
    "c13",
    "1655",
    "0.27" AS 0_27,
    "Russo-" AS russo,
    "1685",
    "0.124" AS 0_124,
    "c0",
    "Wheat" AS wheat,
    "Rye" AS rye,
    "Oats" AS oats,
    "Barley" AS barley,
    "Peas" AS peas,
    "Wheat_2" AS wheat_2,
    "Rye_2" AS rye_2,
    "Oats_2" AS oats_2,
    "Barley_2" AS barley_2,
    "Peas_2" AS peas_2,
    "Wheat_3" AS wheat_3,
    "Rye_3" AS rye_3,
    "Oats_3" AS oats_3,
    "Barley_3" AS barley_3,
    "Peas (assume dry)" AS peas_assume_dry,
    "Wine" AS wine,
    "Beer" AS beer,
    "Wine_2" AS wine_2,
    "Beer_2" AS beer_2,
    "c5",
    "1502",
    "(Starts 1601.)" AS starts_1601,
    "(Starts 1581.)" AS starts_1581,
    "(Starts 1593.)" AS starts_1593,
    "Linen" AS linen,
    "Woolen (I)" AS woolen_i,
    "Woolen (II)" AS woolen_ii,
    "Linen_2" AS linen_2,
    "Woolen (I)_2" AS woolen_i_2,
    "Woolen (II)_2" AS woolen_ii_2,
    "Wax" AS wax,
    "Firewood" AS firewood,
    "Wax_2" AS wax_2,
    "Firewood_2" AS firewood_2,
    "1000 bricks" AS 1000_bricks,
    "60 lath nails" AS 60_lath_nails,
    "Paper" AS paper,
    "Paper_2" AS paper_2,
    "(Assuming 20 libra = 480 sheets = 1 ream)" AS assuming_20_libra_480_sheets_1_ream,
    "c4"
FROM "gpih-lviv-prices-1500-1700"
