-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS sheet,
    "Year" AS year,
    "Total" AS total,
    "Income & wealth" AS income_wealth,
    "Consumption" AS consumption,
    "Trade" AS trade,
    "Resources" AS resources,
    "Total_2" AS total_2,
    "Education" AS education,
    "Health" AS health,
    "Pensions" AS pensions,
    "Public works" AS public_works,
    "Military" AS military,
    "Debt" AS debt,
    "Administration" AS administration,
    "millions of pesos" AS millions_of_pesos,
    "Total_3" AS total_3,
    "Income & wealth_2" AS income_wealth_2,
    "Consumption_2" AS consumption_2,
    "Trade_2" AS trade_2,
    "Resources_2" AS resources_2,
    "Total_4" AS total_4,
    "Education_2" AS education_2,
    "Health_2" AS health_2,
    "Pensions_2" AS pensions_2,
    "Public works_2" AS public_works_2,
    "Military_2" AS military_2,
    "Debt_2" AS debt_2,
    "Administration_2" AS administration_2,
    "Total_5" AS total_5,
    "Income & wealth_3" AS income_wealth_3,
    "Consumption_3" AS consumption_3,
    "Trade_3" AS trade_3,
    "Resources_3" AS resources_3,
    "Total_6" AS total_6,
    "Education_3" AS education_3,
    "Health_3" AS health_3,
    "Pensions_3" AS pensions_3,
    "Public works_3" AS public_works_3,
    "Military_3" AS military_3,
    "Debt_3" AS debt_3,
    "Administration_3" AS administration_3,
    "Year_2" AS year_2,
    "Educ" AS educ,
    "salud",
    "pensiones",
    "c45",
    "Quintile" AS quintile,
    "education_1",
    "education_2_1",
    "University" AS university,
    "on average" AS on_average,
    "care"
FROM "gpih-colombia-central-gov-t-budgets-1901-2013-5nov2014"
