-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "1701",
    "16",
    "26.75" AS "26_75",
    "27.25" AS "27_25",
    "1.808" AS "1_808",
    "c5",
    "c6",
    "3.0225" AS "3_0225",
    "3.0775" AS "3_0775",
    "0.113" AS "0_113",
    "2.94" AS "2_94",
    "3.16" AS "3_16",
    "3.16_2" AS "3_16_2",
    "3.05" AS "3_05",
    "3.0775_2" AS "3_0775_2",
    "1701_2",
    "2034",
    "c17",
    "c0",
    "3",
    "4 (%)" AS "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "15",
    "Above" AS "above",
    "loans",
    "rate",
    "d'État" AS "d_tat",
    "c16",
    "not newly negotiated loans." AS "not_newly_negotiated_loans",
    "beginning",
    "ending",
    "Median year" AS "median_year",
    "sq. sazen" AS "sq_sazen",
    "sq. meters" AS "sq_meters",
    "hectare",
    "Per house" AS "per_house",
    "Per abode" AS "per_abode"
FROM "gpih-lviv-wages-int-realty-1701-1914"
