-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS sheet,
    "1877",
    "93.049" AS 93_049,
    "96.12" AS 96_12,
    "3",
    "11.7" AS 11_7,
    "0.19875" AS 0_19875,
    "c0",
    "Rice" AS rice,
    "Wheat" AS wheat,
    "Soybenas" AS soybenas,
    "Salt" AS salt,
    "Soy" AS soy,
    "Sake" AS sake,
    "Tea" AS tea,
    "Tobacco" AS tobacco,
    "Beef" AS beef,
    "(white, for.)" AS white_for,
    "(cotton)" AS cotton,
    "(for.)" AS for,
    "Coal" AS coal,
    "(Japanese)" AS japanese,
    "Oilcake" AS oilcake,
    "Charcoal" AS charcoal,
    "Barley" AS barley,
    "Rye" AS rye,
    "per",
    "c20",
    "Rice_2" AS rice_2,
    "Wheat_2" AS wheat_2,
    "Soybeans" AS soybeans,
    "Salt_2" AS salt_2,
    "Soy_2" AS soy_2,
    "Sake_2" AS sake_2,
    "Tea_2" AS tea_2,
    "Tobacco_2" AS tobacco_2,
    "Beef_2" AS beef_2,
    "(white, for.)_2" AS white_for_2,
    "(cotton)_2" AS cotton_2,
    "(for.)_2" AS for_2,
    "Coal_2" AS coal_2,
    "(Japanese)_2" AS japanese_2,
    "Oilcake_2" AS oilcake_2,
    "Charcoal_2" AS charcoal_2,
    "Barley_2" AS barley_2,
    "Rye_2" AS rye_2,
    "series on grams of" AS series_on_grams_of,
    "Carpenter" AS carpenter,
    "Plasterer" AS plasterer,
    "Mason" AS mason,
    "Bricklayer" AS bricklayer,
    "cutter",
    "(male)" AS male,
    "(female)" AS female,
    "(male)_2" AS male_2,
    "(female)_2" AS female_2,
    "(male)_3" AS male_3,
    "(female)_3" AS female_3,
    "(per month)" AS per_month,
    "(per month)_2" AS per_month_2,
    "yen",
    "c15",
    "Carpenter_2" AS carpenter_2,
    "Plasterer_2" AS plasterer_2,
    "Mason_2" AS mason_2,
    "Bricklayer_2" AS bricklayer_2,
    "cutter_2",
    "(male)_4" AS male_4,
    "(female)_4" AS female_4,
    "(male)_5" AS male_5,
    "(female)_5" AS female_5,
    "(male)_6" AS male_6,
    "(female)_6" AS female_6,
    "(per month)_3" AS per_month_3,
    "(per month)_4" AS per_month_4,
    "(per day)" AS per_day,
    "(per day)_2" AS per_day_2
FROM "gpih-japan-1885-1926"
