-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "Salaires" AS "salaires",
    "Wages" AS "wages",
    "misc, 90-94." AS "misc_90_94",
    "misc, 223ff" AS "misc_223ff",
    "misc, 372ff" AS "misc_372ff",
    "misc, 261ff" AS "misc_261ff",
    "misc, 443ff" AS "misc_443ff",
    "misc, 64ff" AS "misc_64ff",
    "112-114," AS "112_114",
    "Salaires minimaux en Irak et an Égypte, 8th c - 15th c, real" AS "salaires_minimaux_en_irak_et_an_gypte_8th_c_15th_c_real",
    "Year" AS "year",
    "c1",
    "Per Dinar*" AS "per_dinar",
    "Dinar" AS "dinar",
    "Dirham" AS "dirham",
    "Per Dinar" AS "per_dinar_2",
    "Dirhams Fulus" AS "dirhams_fulus",
    "Dinar_2" AS "dinar_2",
    "c8",
    "per irdabb" AS "per_irdabb",
    "per irdabb_2" AS "per_irdabb_2",
    "per gram of gold" AS "per_gram_of_gold",
    "Date as Noted" AS "date_as_noted",
    "Month" AS "month",
    "Monetary Unit" AS "monetary_unit",
    "Per" AS "per",
    "Low Wage" AS "low_wage",
    "Average Wage" AS "average_wage",
    "High Wage" AS "high_wage",
    "Low Wage_2" AS "low_wage_2",
    "Average Wage_2" AS "average_wage_2",
    "Ave. daily wage" AS "ave_daily_wage",
    "High Wage_2" AS "high_wage_2",
    "Comment" AS "comment",
    "Date as noted_1" AS "date_as_noted_1",
    "Monetary unit_1" AS "monetary_unit_1",
    "Low price" AS "low_price",
    "middle price" AS "middle_price",
    "High price" AS "high_price",
    "about price" AS "about_price",
    "gold? Silver?" AS "gold_silver",
    "Low price_2" AS "low_price_2",
    "middle price_2" AS "middle_price_2",
    "High price_2" AS "high_price_2",
    "Year_2" AS "year_2",
    "Per Dinar_2" AS "per_dinar_2_2",
    "Dirham_2" AS "dirham_2",
    "Year_3" AS "year_3",
    "Low price_3" AS "low_price_3",
    "middle price_3" AS "middle_price_3",
    "High price_3" AS "high_price_3",
    "c23",
    "Low Price_1" AS "low_price_1",
    "Average Price" AS "average_price",
    "High Price_1" AS "high_price_1",
    "Low Price_2_1" AS "low_price_2_1",
    "Average Price_2" AS "average_price_2",
    "High Price_2_1" AS "high_price_2_1",
    "Low Price_3_1" AS "low_price_3_1",
    "Average Price_3" AS "average_price_3",
    "High Price_3_1" AS "high_price_3_1",
    "Comment_2" AS "comment_2",
    "c20",
    "price",
    "price_2",
    "price_3",
    "price_4",
    "price_5",
    "price_6",
    "Middle price_1" AS "middle_price_1",
    "Middle price_2_1" AS "middle_price_2_1",
    "as noted" AS "as_noted",
    "Monetary Units" AS "monetary_units",
    "per dinar_1" AS "per_dinar_1",
    "dinar_1",
    "dinar_2_1",
    "Basis" AS "basis",
    "barley",
    "barley_2",
    "of beef" AS "of_beef",
    "per dinar_2_1" AS "per_dinar_2_1",
    "per dinar_3" AS "per_dinar_3",
    "Low" AS "low",
    "Average" AS "average",
    "High" AS "high",
    "Date as Noted_2" AS "date_as_noted_2",
    "Month_2" AS "month_2",
    "Monetary Unit_2" AS "monetary_unit_2",
    "Date as Noted_3" AS "date_as_noted_3",
    "Month_3" AS "month_3",
    "Monetary Unit_3" AS "monetary_unit_3",
    "Comment_3" AS "comment_3",
    "cinnamon",
    "Colombino" AS "colombino",
    "Average Price_4" AS "average_price_4",
    "High Price_4" AS "high_price_4",
    "c16",
    "Beledi" AS "beledi",
    "Micchino" AS "micchino",
    "Colombino_2" AS "colombino_2",
    "Alexandrian" AS "alexandrian",
    "Persian" AS "persian",
    "Alexandrian_2" AS "alexandrian_2",
    "Persian_2" AS "persian_2",
    "20 quires" AS "20_quires",
    "20 quires_2" AS "20_quires_2",
    "per kilogram" AS "per_kilogram",
    "c10"
FROM "gpih-egypt-1250-1517"
