-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS sheet,
    "Year" AS year,
    "wage",
    "basket",
    "basket_2",
    "wage_2",
    "wage_3",
    "wage_4",
    "basket_3",
    "basket_4",
    "wage_5",
    "wage_6",
    "wage_7",
    "basket_5",
    "wage_8",
    "wage_9",
    "basket_6",
    "basket_7",
    "wage_10",
    "wage_11",
    "Given" AS given,
    "Adjusted, resp" AS adjusted_resp,
    "Adjusted, BB" AS adjusted_bb,
    "basket_8",
    "basket_9",
    "wage_12",
    "wage_13",
    "England" AS england,
    "bread(kg)" AS bread_kg,
    "oatmeal(kg)" AS oatmeal_kg,
    "beans(kg)" AS beans_kg,
    "peas(kg)" AS peas_kg,
    "meat(kg)" AS meat_kg,
    "butter(kg)" AS butter_kg,
    "cheese(kg)" AS cheese_kg,
    "eggs",
    "beer(liters)" AS beer_liters,
    "total cals" AS total_cals,
    "total protein" AS total_protein,
    "protein sources" AS protein_sources,
    "main grain cals" AS main_grain_cals,
    "oats(kg)" AS oats_kg,
    "beans(liter)" AS beans_liter,
    "peas(liters)" AS peas_liters,
    "linen(m)" AS linen_m,
    "candles(liters)" AS candles_liters,
    "lamp oil(liters)" AS lamp_oil_liters,
    "soap(kg)" AS soap_kg,
    "c18",
    "c19",
    "c20",
    "c0",
    "day of male" AS day_of_male,
    "kilo of" AS kilo_of,
    "liter of" AS liter_of,
    "liter of_2" AS liter_of_2,
    "liter of_3" AS liter_of_3,
    "kilo of_2" AS kilo_of_2,
    "kilo of_3" AS kilo_of_3,
    "kilo of_4" AS kilo_of_4,
    "dozen",
    "liter of_4" AS liter_of_4,
    "meter of" AS meter_of,
    "liter of_5" AS liter_of_5,
    "liter of_6" AS liter_of_6,
    "kilo of_5" AS kilo_of_5,
    "respectable",
    "bare bones" AS bare_bones,
    "Basket_1" AS basket_1,
    "Florence" AS florence,
    "Milan" AS milan,
    "Venice" AS venice,
    "Rome" AS rome,
    "Florence_2" AS florence_2,
    "Milan_2" AS milan_2,
    "bread",
    "beans",
    "meat",
    "butter",
    "cheese",
    "egg",
    "cooking oil" AS cooking_oil,
    "rice",
    "sugar",
    "barley",
    "millet",
    "rye",
    "maize",
    "wine",
    "soap",
    "linen",
    "candles",
    "oil/lighting" AS oil_lighting,
    "charcoal",
    "firewood",
    "quantities:" AS quantities,
    "Impute Missing: Prices relative to bread, per --" AS impute_missing_prices_relative_to_bread_per,
    "c31",
    "c32",
    "c33",
    "c34",
    "c35",
    "c36",
    "c37",
    "c38",
    "c39",
    "c40",
    "172",
    "30",
    "3",
    "2",
    "5",
    "2.6" AS 2_6,
    "0",
    "incomplete",
    "missing",
    "complete",
    "60.3" AS 60_3,
    "63.5" AS 63_5,
    "63.5_2" AS 63_5_2,
    "10",
    "10_2",
    "3_2",
    "2_2",
    "5_2",
    "2.6_2" AS 2_6_2,
    "0_2",
    "incomplete_2",
    "missing_2",
    "weights",
    "60.2" AS 60_2,
    "63.2" AS 63_2,
    "63.2_2" AS 63_2_2,
    "20",
    "3_3",
    "2_3",
    "5_3",
    "2.6_3" AS 2_6_3,
    "0_3",
    "incomplete_3",
    "% missing" AS missing_3,
    "weights added" AS weights_added,
    "<-- barebones" AS barebones,
    "CPI" AS cpi,
    "CPI_2" AS cpi_2,
    "CPI_3" AS cpi_3,
    "CPI_4" AS cpi_4,
    "CPI_5" AS cpi_5,
    "CPI_6" AS cpi_6,
    "dwage",
    "dwage_2",
    "dwage_3",
    "dwage_4",
    "dwage_5",
    "dwage_6",
    "dwage_7",
    "SR" AS sr,
    "SR_2" AS sr_2,
    "SR_3" AS sr_3,
    "SR_4" AS sr_4,
    "SR_5" AS sr_5,
    "SR_6" AS sr_6,
    "average",
    "Beijing" AS beijing,
    "kilo of_6" AS kilo_of_6,
    "kilo of_7" AS kilo_of_7,
    "kilo of_8" AS kilo_of_8,
    "kilo of_9" AS kilo_of_9,
    "kilo of_10" AS kilo_of_10,
    "kilo of_11" AS kilo_of_11,
    "kilo of_12" AS kilo_of_12,
    "kilo of_13" AS kilo_of_13,
    "BTU of" AS btu_of,
    "respectability",
    "barebones" AS barebones_2,
    "c1",
    "Imperial" AS imperial,
    "soybeans",
    "& other" AS other,
    "fish",
    "oil",
    "sake",
    "oil_2",
    "Japan" AS japan,
    "Japan_2" AS japan_2
FROM "gpih-japanese-wages"
