-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "Commodity:" AS "commodity",
    "Garbanzo" AS "garbanzo",
    "Corn" AS "corn",
    "Rice" AS "rice",
    "Flour" AS "flour",
    "Potato" AS "potato",
    "Garbanzo_2" AS "garbanzo_2",
    "Corn_2" AS "corn_2",
    "Rice_2" AS "rice_2",
    "Flour_2" AS "flour_2",
    "Potato_2" AS "potato_2",
    "Garbanzo_3" AS "garbanzo_3",
    "Corn_3" AS "corn_3",
    "Rice_3" AS "rice_3",
    "Flour_3" AS "flour_3",
    "Potato_3" AS "potato_3",
    "Beef" AS "beef",
    "c2",
    "Beef_2" AS "beef_2",
    "Beef_3" AS "beef_3",
    "Wine" AS "wine",
    "Milk" AS "milk",
    "Wine_2" AS "wine_2",
    "Milk_2" AS "milk_2",
    "Wine_3" AS "wine_3",
    "Milk_3" AS "milk_3",
    "Wood" AS "wood",
    "Wood_2" AS "wood_2",
    "Wood_3" AS "wood_3",
    "Salt" AS "salt",
    "Sugar" AS "sugar",
    "Cacao" AS "cacao",
    "Butter" AS "butter",
    "Honey" AS "honey",
    "Soap" AS "soap",
    "Lard" AS "lard",
    "Salt_2" AS "salt_2",
    "Sugar_2" AS "sugar_2",
    "Cacao_2" AS "cacao_2",
    "Butter_2" AS "butter_2",
    "Honey_2" AS "honey_2",
    "Soap_2" AS "soap_2",
    "Lard_2" AS "lard_2",
    "Salt_3" AS "salt_3",
    "Sugar_3" AS "sugar_3",
    "Cacao_3" AS "cacao_3",
    "Butter_3" AS "butter_3",
    "Honey_3" AS "honey_3",
    "Soap_3" AS "soap_3",
    "Lard_3" AS "lard_3",
    "1635",
    "1",
    "3.195125" AS "3_195125"
FROM "gpih-colombia-1635-1809"
