-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
SELECT
    "__sheet__" AS "sheet",
    "Commodity:" AS "commodity",
    "Flour" AS "flour",
    "Corn" AS "corn",
    "Beans" AS "beans",
    "Wheat" AS "wheat",
    "Flour_2" AS "flour_2",
    "Corn_2" AS "corn_2",
    "Beans_2" AS "beans_2",
    "Wheat_2" AS "wheat_2",
    "Flour_3" AS "flour_3",
    "Corn_3" AS "corn_3",
    "Beans_3" AS "beans_3",
    "Wheat_3" AS "wheat_3",
    "Soap" AS "soap",
    "Wax" AS "wax",
    "Lard" AS "lard",
    "Tallow" AS "tallow",
    "Oil" AS "oil",
    "Soap_2" AS "soap_2",
    "Wax_2" AS "wax_2",
    "Lard_2" AS "lard_2",
    "Tallow_2" AS "tallow_2",
    "Oil_2" AS "oil_2",
    "Soap_3" AS "soap_3",
    "Wax_3" AS "wax_3",
    "Lard_3" AS "lard_3",
    "Tallow_3" AS "tallow_3",
    "Oil_3" AS "oil_3",
    "Cow" AS "cow",
    "Ram" AS "ram",
    "Cow_2" AS "cow_2",
    "Ram_2" AS "ram_2",
    "Wine" AS "wine",
    "Vinegar" AS "vinegar",
    "Wine_2" AS "wine_2",
    "Vinegar_2" AS "vinegar_2",
    "Wine_3" AS "wine_3",
    "Vinegar_3" AS "vinegar_3",
    "Cotton" AS "cotton",
    "Cotton cloth" AS "cotton_cloth",
    "Wool" AS "wool",
    "Woolen cloth" AS "woolen_cloth",
    "Goat leather" AS "goat_leather",
    "Cotton_2" AS "cotton_2",
    "Cotton cloth_2" AS "cotton_cloth_2",
    "Wool_2" AS "wool_2",
    "Woolen cloth_2" AS "woolen_cloth_2",
    "Goat leather_2" AS "goat_leather_2",
    "Cotton_3" AS "cotton_3",
    "Cotton cloth_3" AS "cotton_cloth_3",
    "Wool_3" AS "wool_3",
    "Woolen cloth_3" AS "woolen_cloth_3",
    "Goat leather_3" AS "goat_leather_3",
    "Salt" AS "salt",
    "Sugar" AS "sugar",
    "Tobacco" AS "tobacco",
    "Yerba" AS "yerba",
    "Iron" AS "iron",
    "Paper" AS "paper",
    "Pepper" AS "pepper",
    "Gunpowder" AS "gunpowder",
    "Salt_2" AS "salt_2",
    "Sugar_2" AS "sugar_2",
    "Tobacco_2" AS "tobacco_2",
    "Yerba_2" AS "yerba_2",
    "Iron_2" AS "iron_2",
    "Paper_2" AS "paper_2",
    "Pepper_2" AS "pepper_2",
    "Gunpowder_2" AS "gunpowder_2",
    "Salt_3" AS "salt_3",
    "Sugar_3" AS "sugar_3",
    "Tobacco_3" AS "tobacco_3",
    "Yerba_3" AS "yerba_3",
    "Iron_3" AS "iron_3",
    "Paper_3" AS "paper_3",
    "Pepper_3" AS "pepper_3",
    "Gunpowder_3" AS "gunpowder_3"
FROM "gpih-cordoba-1711-1762"
