-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "Peter Lindert" AS "peter_lindert",
    "c1",
    "Deriving property totals for 1798 and 1800:" AS "deriving_property_totals_for_1798_and_1800",
    "c3",
    "c4",
    "c5",
    "c6",
    "c7",
    "State" AS "state",
    "dwellings",
    "$" AS "column",
    "¢" AS "column_2",
    "dwelling",
    "Acres" AS "acres",
    "Perches" AS "perches",
    "Sq. feet" AS "sq_feet",
    "Acres_2" AS "acres_2",
    "Perches_2" AS "perches_2",
    "Sq. feet_2" AS "sq_feet_2",
    "acres_1",
    "and Soltow" AS "and_soltow",
    "$_2" AS "2",
    "¢_2" AS "2_2",
    "per acre" AS "per_acre",
    "all ages" AS "all_ages",
    "or disability" AS "or_disability",
    "taxation",
    "(1989, p. 255)" AS "1989_p_255",
    "Males 10+" AS "males_10",
    "Females 10+" AS "females_10",
    "slaves",
    "c24",
    "houses",
    "houses_2",
    "Acres_3" AS "acres_3",
    "Perches_3" AS "perches_3",
    "Sq. feet_3" AS "sq_feet_3",
    "acres_2_1",
    "houses_3",
    "houses_4",
    "Acres_4" AS "acres_4",
    "Perches_4" AS "perches_4",
    "Sq. feet_4" AS "sq_feet_4",
    "acres_3_1",
    "per Pitkin" AS "per_pitkin",
    "Soltow ($)" AS "soltow",
    "dwelling_2",
    "$_3" AS "3",
    "¢_3" AS "3_2",
    "Value/acre" AS "value_acre",
    "Number" AS "number",
    "Value $" AS "value",
    "¢_4" AS "4",
    "Val/house" AS "val_house",
    "Number_2" AS "number_2",
    "Value $_2" AS "value_2",
    "¢_5" AS "5",
    "Val/house_2" AS "val_house_2",
    "Number_3" AS "number_3",
    "Value $_3" AS "value_3",
    "¢_6" AS "6",
    "Val/house_3" AS "val_house_3",
    "Number_4" AS "number_4",
    "Value $_4" AS "value_4",
    "¢_7" AS "7",
    "Val/house_4" AS "val_house_4",
    "Number_5" AS "number_5",
    "Value $_5" AS "value_5",
    "¢_8" AS "8",
    "Val/house_5" AS "val_house_5",
    "Number_6" AS "number_6",
    "Value $_6" AS "value_6",
    "¢_9" AS "9",
    "Val/house_6" AS "val_house_6",
    "Number_7" AS "number_7",
    "Value $_7" AS "value_7",
    "¢_10" AS "10",
    "Val/house_7" AS "val_house_7",
    "Number_8" AS "number_8",
    "Value $_8" AS "value_8",
    "¢_11" AS "11",
    "Val/house_8" AS "val_house_8",
    "Number_9" AS "number_9",
    "Value $_9" AS "value_9",
    "¢_12" AS "12",
    "Val/house_9" AS "val_house_9",
    "Total" AS "total",
    "classes",
    "Difference" AS "difference",
    "Total_2" AS "total_2",
    "classes_2",
    "Difference_2" AS "difference_2",
    "Notes" AS "notes",
    "States" AS "states",
    "No. of Acres" AS "no_of_acres",
    "Valuation" AS "valuation",
    "Valuation_2" AS "valuation_2",
    "Numbers" AS "numbers",
    "Lands" AS "lands",
    "Dwelling-houses" AS "dwelling_houses",
    "Slaves_1" AS "slaves_1",
    "$/acre" AS "acre",
    "$/dwelling" AS "dwelling_3",
    "land",
    "(NB: per slave of any age)" AS "nb_per_slave_of_any_age",
    "under $100" AS "under_100",
    "Ratio" AS "ratio",
    "under $100_2" AS "under_100_2",
    "over $100" AS "over_100",
    "Ratio_2" AS "ratio_2",
    "c0",
    "(4) Adjusting for under-assessment of realty and slave count" AS "4_adjusting_for_under_assessment_of_realty_and_slave_count",
    "c2",
    "c8",
    "c9",
    "c10",
    "income $" AS "income",
    "6% return" AS "6_return",
    "at 6% return" AS "at_6_return",
    "income" AS "income_2",
    "income_2" AS "income_2_2",
    "slaves 10-up" AS "slaves_10_up",
    "slaves 10-up_2" AS "slaves_10_up_2",
    "earnings",
    "product",
    "product_2",
    "slaves**" AS "slaves_2",
    "by Wolcott" AS "by_wolcott",
    "states, 1800" AS "states_1800",
    "states, 1800_2" AS "states_1800_2",
    "asessed val)" AS "asessed_val",
    "states, 1800_3" AS "states_1800_3",
    "asessed val)_2" AS "asessed_val_2",
    "just like the North" AS "just_like_the_north",
    "Variant a" AS "variant_a",
    "Variant b" AS "variant_b",
    "Variant c" AS "variant_c",
    "slaves 10-up_3" AS "slaves_10_up_3",
    "slaves 10-up_4" AS "slaves_10_up_4",
    "Variant a_2" AS "variant_a_2",
    "Variant b_2" AS "variant_b_2",
    "Variant c_2" AS "variant_c_2",
    "Variant d" AS "variant_d",
    "Variant a_3" AS "variant_a_3",
    "Variant b_3" AS "variant_b_3",
    "Variant c_3" AS "variant_c_3",
    "Variant d_2" AS "variant_d_2",
    "and slaves" AS "and_slaves",
    "and slaves_2" AS "and_slaves_2",
    "plus real estate" AS "plus_real_estate",
    "plus real estate_2" AS "plus_real_estate_2",
    "(1000s)" AS "1000s",
    "(1000s)_2" AS "1000s_2",
    "Variant a_4" AS "variant_a_4",
    "Variant b_4" AS "variant_b_4",
    "Variant c_4" AS "variant_c_4",
    "Variant a_5" AS "variant_a_5",
    "Variant b_5" AS "variant_b_5",
    "Variant c_5" AS "variant_c_5",
    "and ""South a""" AS "and_south_a",
    "and South b" AS "and_south_b",
    "and ""South a""_2" AS "and_south_a_2",
    "and South b_2" AS "and_south_b_2",
    "and South c" AS "and_south_c",
    "and South d" AS "and_south_d",
    "and ""South a""_3" AS "and_south_a_3",
    "and South b_3" AS "and_south_b_3",
    "and ""South a""_4" AS "and_south_a_4",
    "and South b_4" AS "and_south_b_4",
    "and South c_2" AS "and_south_c_2",
    "and South d_2" AS "and_south_d_2",
    "c58",
    "c59",
    "c60",
    "c61",
    "c62"
FROM "gpih-tables-locked-property-totals-1798-1800"
