-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "c0",
    "lower range" AS "lower_range",
    "upper range" AS "upper_range",
    "average( w/ interp.)" AS "average_w_interp",
    "Commodity:" AS "commodity",
    "Wheat (L)" AS "wheat_l",
    "Wheat (D)" AS "wheat_d",
    "Wheat (H)" AS "wheat_h",
    "Wheat (S)" AS "wheat_s",
    "Rye (D)" AS "rye_d",
    "Rye (H)" AS "rye_h",
    "Barley" AS "barley",
    "Oats" AS "oats",
    "Wheat (L)_2" AS "wheat_l_2",
    "Wheat (D)_2" AS "wheat_d_2",
    "Wheat (H)_2" AS "wheat_h_2",
    "Wheat (S)_2" AS "wheat_s_2",
    "Rye (D)_2" AS "rye_d_2",
    "Rye (H)_2" AS "rye_h_2",
    "Barley_2" AS "barley_2",
    "Oats_2" AS "oats_2",
    "Silver grams" AS "silver_grams",
    "Wheat (L)_3" AS "wheat_l_3",
    "Wheat (D)_3" AS "wheat_d_3",
    "Wheat (H)_3" AS "wheat_h_3",
    "Wheat (S)_3" AS "wheat_s_3",
    "Rye (D)_3" AS "rye_d_3",
    "Rye (H)_3" AS "rye_h_3",
    "Barley_3" AS "barley_3",
    "Oats_3" AS "oats_3",
    "Peas" AS "peas",
    "c2",
    "Peas_2" AS "peas_2",
    "Peas_3" AS "peas_3",
    "Salt Beef" AS "salt_beef",
    "Bacon" AS "bacon",
    "Lamb (s)" AS "lamb_s",
    "Herring (a)" AS "herring_a",
    "Stockfish" AS "stockfish",
    "Salt Beef_2" AS "salt_beef_2",
    "Bacon_2" AS "bacon_2",
    "Lamb (s)_2" AS "lamb_s_2",
    "Herring (a)_2" AS "herring_a_2",
    "Stockfish_2" AS "stockfish_2",
    "Salt Beef_3" AS "salt_beef_3",
    "Bacon_3" AS "bacon_3",
    "Lamb (s)_3" AS "lamb_s_3",
    "Herring (a)_3" AS "herring_a_3",
    "Stockfish_3" AS "stockfish_3",
    "Butter" AS "butter",
    "Butter (S)" AS "butter_s",
    "Cheese" AS "cheese",
    "Eggs" AS "eggs",
    "Cheese (H)" AS "cheese_h",
    "Butter_2" AS "butter_2",
    "Butter (S)_2" AS "butter_s_2",
    "Cheese_2" AS "cheese_2",
    "Eggs_2" AS "eggs_2",
    "Cheese (H)_2" AS "cheese_h_2",
    "Butter_3" AS "butter_3",
    "Butter (S)_3" AS "butter_s_3",
    "Cheese_3" AS "cheese_3",
    "Eggs_3" AS "eggs_3",
    "Cheese (H)_3" AS "cheese_h_3",
    "Salt" AS "salt",
    "Salt_2" AS "salt_2",
    "Salt_3" AS "salt_3",
    "Oil (t)" AS "oil_t",
    "Charcoal" AS "charcoal",
    "Firewood" AS "firewood",
    "Peat" AS "peat",
    "Tallow" AS "tallow",
    "Oil (t)_2" AS "oil_t_2",
    "Charcoal_2" AS "charcoal_2",
    "Firewood_2" AS "firewood_2",
    "Peat_2" AS "peat_2",
    "Tallow_2" AS "tallow_2",
    "Oil (t)_3" AS "oil_t_3",
    "Charcoal_3" AS "charcoal_3",
    "Firewood_3" AS "firewood_3",
    "Peat_3" AS "peat_3",
    "Tallow_3" AS "tallow_3",
    "Wine (F)" AS "wine_f",
    "Brandy (F)" AS "brandy_f",
    "Wine (F)_2" AS "wine_f_2",
    "Brandy (F)_2" AS "brandy_f_2",
    "Wine (F)_3" AS "wine_f_3",
    "Brandy (F)_3" AS "brandy_f_3",
    "Soap (s)" AS "soap_s",
    "Soap (s)_2" AS "soap_s_2",
    "Soap (s)_3" AS "soap_s_3"
FROM "gpih-copenhagen-p-1712-1800"
