-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "North Dvina" AS "north_dvina",
    "Hellie file" AS "hellie_file",
    "place",
    "c0",
    "Hellie" AS "hellie",
    "Mironov" AS "mironov",
    "Mironov_2" AS "mironov_2",
    "Hellie_2" AS "hellie_2",
    "Mironov_3" AS "mironov_3",
    "Hellie_3" AS "hellie_3",
    "Notes" AS "notes",
    "by PL" AS "by_pl",
    "name",
    "code",
    "page",
    "name_2",
    "code_2",
    "title, inst'n" AS "title_inst_n",
    "code_3",
    "Sex" AS "sex",
    "transaction",
    "code_4",
    "or document" AS "or_document",
    "code_5",
    "English" AS "english",
    "Russian" AS "russian",
    "Month" AS "month",
    "Date" AS "date",
    "English_2" AS "english_2",
    "Russian_2" AS "russian_2",
    "code_6",
    "Russian_3" AS "russian_3",
    "of units" AS "of_units",
    "paid",
    "Russian_4" AS "russian_4",
    "unit",
    "voz",
    "name, notes" AS "name_notes",
    "code_7",
    "name_3",
    "code_8",
    "c29",
    "c30"
FROM "gpih-russia-firewood-p-1606-1871"
