-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS sheet,
    "c0",
    "Rice" AS rice,
    "Soybeans" AS soybeans,
    "Soya" AS soya,
    "silver per" AS silver_per,
    "Rice_2" AS rice_2,
    "Soybeans_2" AS soybeans_2,
    "Soya_2" AS soya_2,
    "Pine" AS pine,
    "Candles" AS candles,
    "Coal" AS coal,
    "Pine_2" AS pine_2,
    "Candles_2" AS candles_2,
    "Coal_2" AS coal_2,
    "per tan" AS per_tan,
    "per shaku" AS per_shaku,
    "per tan_2" AS per_tan_2,
    "per tan_3" AS per_tan_3,
    "LENGTH" AS length,
    "per square m." AS per_square_m,
    "per meter" AS per_meter,
    "per square m._2" AS per_square_m_2,
    "per square m._3" AS per_square_m_3,
    "Salt" AS salt,
    "Vinegar" AS vinegar,
    "Tea" AS tea,
    "Oil" AS oil,
    "Sake" AS sake,
    "Japanese" AS japanese,
    "Japanese_2" AS japanese_2,
    "jo per" AS jo_per,
    "Japanese_3" AS japanese_3,
    "Japanese_4" AS japanese_4,
    "Japanese_5" AS japanese_5,
    "Japanese_6" AS japanese_6,
    "Salt_2" AS salt_2,
    "Vinegar_2" AS vinegar_2,
    "Tea_2" AS tea_2,
    "Oil_2" AS oil_2,
    "Sake_2" AS sake_2,
    "Japanese_7" AS japanese_7,
    "Japanese_8" AS japanese_8,
    "Japanese_9" AS japanese_9,
    "Japanese_10" AS japanese_10,
    "Japanese_11" AS japanese_11,
    "Japanese_12" AS japanese_12,
    "(25.568 gramos en plata pura) = 8 monme de Chogin." AS 25_568_gramos_en_plata_pura_8_monme_de_chogin,
    "c2",
    "c3",
    "(This implies 3.196 grams of silver per monme de chogin.)" AS this_implies_3_196_grams_of_silver_per_monme_de_chogin
FROM "gpih-osaka-1600-1650"
