-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS sheet,
    "Commodity" AS commodity,
    "Grain" AS grain,
    "Wine" AS wine,
    "Veal" AS veal,
    "Beef" AS beef,
    "Mutton" AS mutton,
    "Eggs" AS eggs,
    "Sugar" AS sugar,
    "Candles" AS candles,
    "Firewood" AS firewood,
    "Mortar" AS mortar,
    "Cloth (white coat/ gown)" AS cloth_white_coat_gown,
    "Cloth (sacking)" AS cloth_sacking,
    "Grain_2" AS grain_2,
    "Wine_2" AS wine_2,
    "Veal_2" AS veal_2,
    "Beef_2" AS beef_2,
    "Mutton_2" AS mutton_2,
    "Eggs_2" AS eggs_2,
    "Sugar_2" AS sugar_2,
    "Candles_2" AS candles_2,
    "Firewood_2" AS firewood_2,
    "Mortar_2" AS mortar_2,
    "Cloth (white coat/ gown)_2" AS cloth_white_coat_gown_2,
    "Cloth (sacking)_2" AS cloth_sacking_2,
    "Grain_3" AS grain_3,
    "Wine_3" AS wine_3,
    "Veal_3" AS veal_3,
    "Beef_3" AS beef_3,
    "Mutton_3" AS mutton_3,
    "Eggs_3" AS eggs_3,
    "Sugar_3" AS sugar_3,
    "Candles_3" AS candles_3,
    "Firewood_3" AS firewood_3,
    "Mortar_3" AS mortar_3,
    "Cloth (white coat/ gown)_3" AS cloth_white_coat_gown_3,
    "Cloth (sacking)_3" AS cloth_sacking_3,
    "c37",
    "Occupation:" AS occupation,
    "Mason" AS mason,
    "Laborer - unskilled" AS laborer_unskilled,
    "Laborer - agricultural" AS laborer_agricultural,
    "Mason_2" AS mason_2,
    "Laborer - unskilled_2" AS laborer_unskilled_2,
    "Laborer - agricultural_2" AS laborer_agricultural_2
FROM "gpih-italy-florence-1520-1621"
