-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS sheet,
    "Currency:" AS currency,
    "Real - Theoretical Content" AS real_theoretical_content,
    "Vellón de Andalucía" AS vell_n_de_andaluc_a,
    "Vellón de Castilla la Nueva" AS vell_n_de_castilla_la_nueva,
    "Vellón de Castilla la Vieja" AS vell_n_de_castilla_la_vieja,
    "Sueldo de Cataluña*" AS sueldo_de_catalu_a,
    "Sueldo de Valencia" AS sueldo_de_valencia,
    "Sueldo de Mallorca" AS sueldo_de_mallorca,
    "Commodity:" AS commodity,
    "Wheat" AS wheat,
    "Wheat_2" AS wheat_2,
    "Wheat_3" AS wheat_3,
    "Flour" AS flour,
    "Rice" AS rice,
    "Beef" AS beef,
    "Wine" AS wine,
    "Oil" AS oil,
    "Sugar" AS sugar,
    "Eggs" AS eggs,
    "Wheat_4" AS wheat_4,
    "Wheat_5" AS wheat_5,
    "Wheat_6" AS wheat_6,
    "Flour_2" AS flour_2,
    "Rice_2" AS rice_2,
    "Beef_2" AS beef_2,
    "Wine_2" AS wine_2,
    "Oil_2" AS oil_2,
    "Sugar_2" AS sugar_2,
    "Eggs_2" AS eggs_2,
    "Wheat *" AS wheat_7,
    "Wheat_7" AS wheat_7_2,
    "Wheat_8" AS wheat_8,
    "Wheat_9" AS wheat_9,
    "Flour_3" AS flour_3,
    "Rice_3" AS rice_3,
    "Beef_3" AS beef_3,
    "Wine_3" AS wine_3,
    "Oil_3" AS oil_3,
    "Sugar_3" AS sugar_3,
    "Eggs_3" AS eggs_3,
    "Charcoal" AS charcoal,
    "Paper" AS paper,
    "Soap" AS soap,
    "Charcoal_2" AS charcoal_2,
    "Paper_2" AS paper_2,
    "Soap_2" AS soap_2,
    "Charcoal_3" AS charcoal_3,
    "Paper_3" AS paper_3,
    "Soap_3" AS soap_3,
    "Occupation:" AS occupation,
    "Bricklayer - Master" AS bricklayer_master,
    "Bricklayer" AS bricklayer,
    "Unskilled laborer" AS unskilled_laborer,
    "Bricklayer - Master_2" AS bricklayer_master_2,
    "Bricklayer_2" AS bricklayer_2,
    "Unskilled laborer_2" AS unskilled_laborer_2
FROM "gpih-cataluna-1494-1808"
