-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "Commodity" AS "commodity",
    "Olive oil" AS "olive_oil",
    "Rice" AS "rice",
    "Wheat" AS "wheat",
    "Barley" AS "barley",
    "Millet" AS "millet",
    "Rye" AS "rye",
    "Olive oil_2" AS "olive_oil_2",
    "Rice_2" AS "rice_2",
    "Wheat_2" AS "wheat_2",
    "Barley_2" AS "barley_2",
    "Millet_2" AS "millet_2",
    "Rye_2" AS "rye_2",
    "Olive oil_3" AS "olive_oil_3",
    "Rice_3" AS "rice_3",
    "Wheat_3" AS "wheat_3",
    "Barley_3" AS "barley_3",
    "Millet_3" AS "millet_3",
    "Rye_3" AS "rye_3",
    "Wheat_4" AS "wheat_4",
    "Barley_4" AS "barley_4",
    "Millet_4" AS "millet_4",
    "Rye_4" AS "rye_4",
    "Corn" AS "corn",
    "(fired)" AS "fired",
    "(non-fired)" AS "non_fired",
    "Hens" AS "hens",
    "Mutton" AS "mutton",
    "Beer" AS "beer",
    "Firewood" AS "firewood",
    "Lin (flax/linen?)" AS "lin_flax_linen",
    "Daily" AS "daily",
    "Corn_2" AS "corn_2",
    "(fired)_2" AS "fired_2",
    "(non-fired)_2" AS "non_fired_2",
    "Hens_2" AS "hens_2",
    "Mutton_2" AS "mutton_2",
    "Beer_2" AS "beer_2",
    "Firewood_2" AS "firewood_2",
    "Lin (flax/linen?)_2" AS "lin_flax_linen_2",
    "Daily_2" AS "daily_2",
    "Corn_3" AS "corn_3",
    "(fired)_3" AS "fired_3",
    "(non-fired)_3" AS "non_fired_3",
    "Hens_3" AS "hens_3",
    "Mutton_3" AS "mutton_3",
    "Beer_3" AS "beer_3",
    "Firewood_3" AS "firewood_3",
    "Lin (flax/linen?)_3" AS "lin_flax_linen_3",
    "Daily_3" AS "daily_3",
    "Corn_4" AS "corn_4",
    "Wheat (late)" AS "wheat_late",
    "Wine" AS "wine",
    "Wax" AS "wax",
    "Wheat (late)_2" AS "wheat_late_2",
    "Wine_2" AS "wine_2",
    "Wax_2" AS "wax_2",
    "Wheat (late)_3" AS "wheat_late_3",
    "Wine_3" AS "wine_3",
    "Wax_3" AS "wax_3",
    "c0",
    "c1",
    "c2",
    "10/1769" AS "10_1769",
    "11/1769-" AS "11_1769",
    "10/1769-" AS "10_1769_2",
    "1/772-" AS "1_772",
    "10/1769_2" AS "10_1769_2_2",
    "11/1769-_2" AS "11_1769_2",
    "10/1769-_2" AS "10_1769_2_3",
    "1/1772-" AS "1_1772",
    "4",
    "1750",
    "45.46875" AS "45_46875",
    "1750_2",
    "45.61" AS "45_61",
    "0.9122" AS "0_9122",
    "8.766242" AS "8_766242",
    "0.021915605" AS "0_021915605"
FROM "gpih-portugal-1750-1855"
