-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "c0",
    "Good" AS "good",
    "Rye" AS "rye",
    "Barley" AS "barley",
    "Oats" AS "oats",
    "Wheat" AS "wheat",
    "Peas" AS "peas",
    "Butter" AS "butter",
    "Butter_2" AS "butter_2",
    "Cheese" AS "cheese",
    "Milk" AS "milk",
    "Beer" AS "beer",
    "Vodka (""Eau-de-vie"")" AS "vodka_eau_de_vie",
    "Beef" AS "beef",
    "Beef_2" AS "beef_2",
    "Cow" AS "cow",
    "Veal" AS "veal",
    "Pork" AS "pork",
    "Horse" AS "horse",
    "Mutton" AS "mutton",
    "Mutton_2" AS "mutton_2",
    "Lard" AS "lard",
    "Grease/fat" AS "grease_fat",
    "Sugar" AS "sugar",
    "Tallow (""Loj"")" AS "tallow_loj",
    "Eggs" AS "eggs",
    "Rice" AS "rice",
    "Herring" AS "herring",
    "Firewood" AS "firewood",
    "Firewood_2" AS "firewood_2",
    "Firewood (Pine)" AS "firewood_pine",
    "Firewood (Beech)" AS "firewood_beech",
    "Firewood (oak)" AS "firewood_oak",
    "Candles" AS "candles",
    "Soap (""Savon noir"")" AS "soap_savon_noir",
    "Wax" AS "wax",
    "Wax_2" AS "wax_2",
    "White Drapery" AS "white_drapery",
    "Grey Drapery" AS "grey_drapery",
    "Barley_2" AS "barley_2",
    "Wheat_2" AS "wheat_2",
    "Rye_2" AS "rye_2",
    "Peas_2" AS "peas_2",
    "Butter_3" AS "butter_3",
    "Butter_4" AS "butter_4",
    "Cheese_2" AS "cheese_2",
    "Beer_2" AS "beer_2",
    "Beef_3" AS "beef_3",
    "Beef_4" AS "beef_4",
    "Cow_2" AS "cow_2",
    "Veal_2" AS "veal_2",
    "Pork_2" AS "pork_2",
    "Horse_2" AS "horse_2",
    "Mutton_3" AS "mutton_3",
    "Mutton_4" AS "mutton_4",
    "Lard_2" AS "lard_2",
    "Grease/Fat_1" AS "grease_fat_1",
    "Sugar_2" AS "sugar_2",
    "Tallow (""Loj"")_2" AS "tallow_loj_2",
    "Eggs_2" AS "eggs_2",
    "Rice_2" AS "rice_2",
    "Herring_2" AS "herring_2",
    "Firewood_3" AS "firewood_3",
    "Firewood_4" AS "firewood_4",
    "Firewood (pine)_1" AS "firewood_pine_1",
    "Firewood (sazen)" AS "firewood_sazen",
    "Firewood (oak)_2" AS "firewood_oak_2",
    "Candles_2" AS "candles_2",
    "Wax_3" AS "wax_3",
    "Wax_4" AS "wax_4",
    "White Drapery_2" AS "white_drapery_2",
    "Grey Drapery_2" AS "grey_drapery_2",
    "Wage" AS "wage",
    "Rye_3" AS "rye_3",
    "Bread" AS "bread",
    "Bread_2" AS "bread_2",
    "Beans" AS "beans",
    "Meat" AS "meat",
    "Butter_5" AS "butter_5",
    "Cheese_3" AS "cheese_3",
    "Eggs_3" AS "eggs_3",
    "Herring_3" AS "herring_3",
    "Rice_3" AS "rice_3",
    "Sugar_3" AS "sugar_3",
    "Beer_3" AS "beer_3",
    "Soap" AS "soap",
    "Grey Drapery_3" AS "grey_drapery_3",
    "Linen" AS "linen",
    "Candles_3" AS "candles_3",
    "Oil/light" AS "oil_light",
    "Wood (hard)" AS "wood_hard",
    "Wood (soft)" AS "wood_soft",
    "Linen (Munich)" AS "linen_munich",
    "Fuel (BTUs)" AS "fuel_btus",
    "NEW CPI" AS "new_cpi",
    "Source" AS "source",
    "[1], [2]" AS "1_2",
    "[1], [2]_2" AS "1_2_2",
    "[2]" AS "2",
    "[1], [2]_3" AS "1_2_3",
    "1502",
    "c1",
    "c2",
    "c3",
    "[1]:" AS "1",
    "Pelc, J., Ceny w Gdansk w XVI i XVII wieku (Lwow, 1937)." AS "pelc_j_ceny_w_gdansk_w_xvi_i_xvii_wieku_lwow_1937",
    "c6"
FROM "gpih-allen-gdansk-1501-1914"
