-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "Commodity:" AS "commodity",
    "Corn" AS "corn",
    "Wheat" AS "wheat",
    "Salt" AS "salt",
    "Beef" AS "beef",
    "Pork" AS "pork",
    "Bacon" AS "bacon",
    "Coffee" AS "coffee",
    "Tea" AS "tea",
    "Butter" AS "butter",
    "Flour" AS "flour",
    "Sugar" AS "sugar",
    "Pepper" AS "pepper",
    "Allspice & Ginger" AS "allspice_ginger",
    "Whiskey" AS "whiskey",
    "Corn_2" AS "corn_2",
    "Wheat_2" AS "wheat_2",
    "Salt_2" AS "salt_2",
    "Beef_2" AS "beef_2",
    "Pork_2" AS "pork_2",
    "Bacon_2" AS "bacon_2",
    "Coffee_2" AS "coffee_2",
    "Tea_2" AS "tea_2",
    "Butter_2" AS "butter_2",
    "Flour_2" AS "flour_2",
    "Sugar_2" AS "sugar_2",
    "Pepper_2" AS "pepper_2",
    "Allspice & Ginger_2" AS "allspice_ginger_2",
    "Whiskey_2" AS "whiskey_2",
    "Corn_3" AS "corn_3",
    "Wheat_3" AS "wheat_3",
    "Salt_3" AS "salt_3",
    "Beef_3" AS "beef_3",
    "Pork_3" AS "pork_3",
    "Bacon_3" AS "bacon_3",
    "Coffee_3" AS "coffee_3",
    "Tea_3" AS "tea_3",
    "Butter_3" AS "butter_3",
    "Flour_3" AS "flour_3",
    "Sugar_3" AS "sugar_3",
    "Pepper_3" AS "pepper_3",
    "Allspice & Ginger_3" AS "allspice_ginger_3",
    "Whiskey_3" AS "whiskey_3",
    "Occupation:" AS "occupation",
    "Laborer" AS "laborer",
    "c2",
    "c3",
    "Laborer_2" AS "laborer_2",
    "Year" AS "year",
    "Index" AS "index",
    "0.3583" AS "0_3583",
    "31.103" AS "31_103",
    "c4"
FROM "gpih-west-virginia-1788-1860"
