-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "c0",
    "Good" AS "good",
    "Wheat" AS "wheat",
    "c3",
    "Barley" AS "barley",
    "c5",
    "Oats" AS "oats",
    "c7",
    "Rye" AS "rye",
    "c9",
    "Beef" AS "beef",
    "c11",
    "Peas" AS "peas",
    "c13",
    "Cheese" AS "cheese",
    "c15",
    "Cheese_2" AS "cheese_2",
    "c17",
    "Eggs" AS "eggs",
    "c19",
    "Eggs_2" AS "eggs_2",
    "Eggs_3" AS "eggs_3",
    "Wax" AS "wax",
    "Wax_2" AS "wax_2",
    "c24",
    "Candles" AS "candles",
    "c26",
    "Candles_2" AS "candles_2",
    "Charcoal" AS "charcoal",
    "c29",
    "Charcoal_2" AS "charcoal_2",
    "c31",
    "Fagots" AS "fagots",
    "c33",
    "Firewood" AS "firewood",
    "c35",
    "Herring" AS "herring",
    "c37",
    "White Herring" AS "white_herring",
    "c39",
    "Oil" AS "oil",
    "c41",
    "Honey" AS "honey",
    "c43",
    "Coal" AS "coal",
    "Rice" AS "rice",
    "Salted Cod" AS "salted_cod",
    "Stockfish" AS "stockfish",
    "Soap" AS "soap",
    "Shirting" AS "shirting",
    "Linen & Canvas" AS "linen_canvas",
    "Cloth" AS "cloth",
    "Cloth_2" AS "cloth_2",
    "Cloth_3" AS "cloth_3",
    "Broad Cloth" AS "broad_cloth",
    "Cloth_4" AS "cloth_4",
    "Blue Cloth" AS "blue_cloth",
    "Bread" AS "bread",
    "Beans" AS "beans",
    "Beef_2" AS "beef_2",
    "Beer" AS "beer",
    "Sugar" AS "sugar",
    "Butter" AS "butter",
    "Cheese_3" AS "cheese_3",
    "c64",
    "c65",
    "c66",
    "Wheat_2" AS "wheat_2",
    "Bread_2" AS "bread_2",
    "Cloth_5" AS "cloth_5",
    "Linen & Canvas_2" AS "linen_canvas_2",
    "Beans_2" AS "beans_2",
    "Beef_3" AS "beef_3",
    "Beer_2" AS "beer_2",
    "Candles_3" AS "candles_3",
    "Sugar_2" AS "sugar_2",
    "Butter_2" AS "butter_2",
    "Cheese_4" AS "cheese_4",
    "Eggs_4" AS "eggs_4",
    "Herring_2" AS "herring_2",
    "Stockfish_2" AS "stockfish_2",
    "Salted Cod_2" AS "salted_cod_2",
    "Oil_2" AS "oil_2",
    "Soap_2" AS "soap_2",
    "Rice_2" AS "rice_2",
    "Coal_2" AS "coal_2",
    "Charcoal_3" AS "charcoal_3",
    "Faggots" AS "faggots",
    "Charcoal_4" AS "charcoal_4",
    "Bread (predicted)" AS "bread_predicted",
    "Bread_3" AS "bread_3",
    "Beans_3" AS "beans_3",
    "Meat" AS "meat",
    "Butter_3" AS "butter_3",
    "Cheese_5" AS "cheese_5",
    "Eggs_5" AS "eggs_5",
    "Herring_3" AS "herring_3",
    "Rice_3" AS "rice_3",
    "Sugar_3" AS "sugar_3",
    "Beer_3" AS "beer_3",
    "Soap_3" AS "soap_3",
    "Linen" AS "linen",
    "Candles_4" AS "candles_4",
    "Oil/light" AS "oil_light",
    "Charcoal_5" AS "charcoal_5",
    "Coal_3" AS "coal_3",
    "Faggot" AS "faggot",
    "Charcoal_6" AS "charcoal_6",
    "Coal_4" AS "coal_4",
    "c109",
    "CPI" AS "cpi",
    "NEW CPI" AS "new_cpi",
    "NEW CPI_2" AS "new_cpi_2",
    "NEW CPI_3" AS "new_cpi_3",
    "Curreny/units" AS "curreny_units",
    "Pence/Day" AS "pence_day",
    "Pence/Day_2" AS "pence_day_2",
    "Pence/Day_3" AS "pence_day_3",
    "Pence/Day_4" AS "pence_day_4",
    "Pence/Day_5" AS "pence_day_5",
    "Ratio" AS "ratio",
    "Ratio_2" AS "ratio_2",
    "Pence/Day_6" AS "pence_day_6",
    "Pence/Day_7" AS "pence_day_7",
    "Grams Ag/Day" AS "grams_ag_day",
    "Grams Ag/Day_2" AS "grams_ag_day_2",
    "Grams Ag/Day_3" AS "grams_ag_day_3",
    "Grams Ag/Day_4" AS "grams_ag_day_4",
    "Grams Ag/Day_5" AS "grams_ag_day_5",
    "1261",
    "c1",
    "21.3" AS "21_3",
    "1.3505868544600939" AS "1_3505868544600939",
    "[1]:" AS "1",
    "The silver prices of the Pound Sterling, used for comparison" AS "the_silver_prices_of_the_pound_sterling_used_for_comparison"
FROM "gpih-allen-london-south-eng-1259-1914"
