-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS sheet,
    "Commodity:" AS commodity,
    "Corn" AS corn,
    "Wheat" AS wheat,
    "Oats" AS oats,
    "Rye" AS rye,
    "Salt" AS salt,
    "Beef" AS beef,
    "Pork" AS pork,
    "Bacon" AS bacon,
    "Butter" AS butter,
    "Sugar" AS sugar,
    "Whiskey" AS whiskey,
    "Rum" AS rum,
    "Corn_2" AS corn_2,
    "Wheat_2" AS wheat_2,
    "Oats_2" AS oats_2,
    "Rye_2" AS rye_2,
    "Salt_2" AS salt_2,
    "Beef_2" AS beef_2,
    "Pork_2" AS pork_2,
    "Bacon_2" AS bacon_2,
    "Butter_2" AS butter_2,
    "Sugar_2" AS sugar_2,
    "Whiskey_2" AS whiskey_2,
    "Rum_2" AS rum_2,
    "silver per" AS silver_per,
    "Corn_3" AS corn_3,
    "Wheat_3" AS wheat_3,
    "Oats_3" AS oats_3,
    "Rye_3" AS rye_3,
    "Salt_3" AS salt_3,
    "Beef_3" AS beef_3,
    "Pork_3" AS pork_3,
    "Bacon_3" AS bacon_3,
    "Butter_3" AS butter_3,
    "Sugar_3" AS sugar_3,
    "Whiskey_3" AS whiskey_3,
    "Rum_3" AS rum_3,
    "Unit:" AS unit,
    "month",
    "month_2",
    "month_3",
    "day",
    "day_2",
    "day_3",
    "Maryland" AS maryland,
    "Pennsylvania" AS pennsylvania,
    "Massachusetts" AS massachusetts,
    "day_4",
    "day_5",
    """day"" = month/26" AS day_month_26,
    "month_4",
    "month_5",
    "month_6",
    "Location:" AS location,
    "Delaware" AS delaware,
    "c3",
    "Maryland_2" AS maryland_2,
    "Maryland_3" AS maryland_3,
    "1752",
    "74.25545231642795" AS 74_25545231642795,
    "70.71947839659805" AS 70_71947839659805,
    "27.84579461866048" AS 27_84579461866048,
    "1801",
    "24.78787688483261" AS 24_78787688483261,
    "from",
    "to"
FROM "gpih-maryland-1752-1856"
