-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS sheet,
    "Orig. row" AS orig_row,
    "1772 Tax List Matched with 1775 Constables Return, Last name" AS 1772_tax_list_matched_with_1775_constables_return_last_name,
    "First name" AS first_name,
    "Gender 1=male; 2=female" AS gender_1_male_2_female,
    "B.G. Smith occupation code" AS b_g_smith_occupation_code,
    "Lindert-Williamson occupation code" AS lindert_williamson_occupation_code,
    "Ward (Tax List)" AS ward_tax_list,
    "(Caution: Under-assessment; see Smith 1984, 1990) Tax Assess" AS caution_under_assessment_see_smith_1984_1990_tax_assess,
    "Home Ownership 0=owned; 1=not owned; 9= unknown" AS home_ownership_0_owned_1_not_owned_9_unknown,
    "Slaves # (Tax List)" AS slaves_tax_list,
    "Indentured Servants # (Tax List)" AS indentured_servants_tax_list,
    "Poor? (Institutional aid)" AS poor_institutional_aid,
    "Poor, binary (= 1 if any aid)" AS poor_binary_1_if_any_aid,
    "Ward (Constables Returns)" AS ward_constables_returns,
    "Occupation (Constables returns)" AS occupation_constables_returns,
    "Inmates in Household (Constables Returns)" AS inmates_in_household_constables_returns,
    "Servants # in Household (constables returns)" AS servants_in_household_constables_returns,
    "Children # (Constables)" AS children_constables,
    "Age Youngest Child (e.g. 10 = 1.0 years)" AS age_youngest_child_e_g_10_1_0_years,
    "Age Oldest Child (e.g. 10 = 1.0 years" AS age_oldest_child_e_g_10_1_0_years,
    "Slaves # (Constables returns)" AS slaves_constables_returns,
    "Property merging notes." AS property_merging_notes,
    "Likely number of children 16 and over" AS likely_number_of_children_16_and_over,
    "Potential size of free labor force over 16" AS potential_size_of_free_labor_force_over_16,
    "c23",
    "c24",
    "Total no." AS total_no,
    "Of which," AS of_which,
    "Smith's" AS smith_s,
    "c3",
    "Candidates for merging properties into the same owner = Peop" AS candidates_for_merging_properties_into_the_same_owner_peop,
    "Code" AS code,
    "Name" AS name,
    "Male" AS male,
    "Female" AS female,
    "included in LW codes*" AS included_in_lw_codes,
    "LW codes* (repeated, condensed)" AS lw_codes_repeated_condensed,
    "Male occ" AS male_occ,
    "Female occ" AS female_occ,
    "Smith Code" AS smith_code,
    "Smith description" AS smith_description,
    "Male_2" AS male_2,
    "Female_2" AS female_2,
    "Total" AS total,
    "Merged properties into the same owner -- done with people wi" AS merged_properties_into_the_same_owner_done_with_people_wi,
    "c11",
    "occupational category" AS occupational_category,
    "c1",
    "LW Code" AS lw_code,
    "total_1",
    "share",
    "re-grouped" AS re_grouped,
    "B.G. Smith" AS b_g_smith,
    "Philadelphia" AS philadelphia
FROM "gpih-philadelphia-occ-s-1772-b-g-smith"
