-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "Commodity:" AS "commodity",
    "Wheat" AS "wheat",
    "Barley" AS "barley",
    "Common red wine" AS "common_red_wine",
    "Veal" AS "veal",
    "Beef" AS "beef",
    "Firewood" AS "firewood",
    "Cloth ""basso""" AS "cloth_basso",
    "Cloth ""alto""" AS "cloth_alto",
    "Candles" AS "candles",
    "Bricks" AS "bricks",
    "Tiles" AS "tiles",
    "Lime" AS "lime",
    "Sugar" AS "sugar",
    "Rice" AS "rice",
    "Agric. laborer" AS "agric_laborer",
    "Wheat_2" AS "wheat_2",
    "Barley_2" AS "barley_2",
    "Common red wine_2" AS "common_red_wine_2",
    "Veal_2" AS "veal_2",
    "Beef_2" AS "beef_2",
    "Firewood_2" AS "firewood_2",
    "Cloth ""basso""_2" AS "cloth_basso_2",
    "Cloth ""alto""_2" AS "cloth_alto_2",
    "Candles_2" AS "candles_2",
    "Bricks_2" AS "bricks_2",
    "Tiles_2" AS "tiles_2",
    "Lime_2" AS "lime_2",
    "Sugar_2" AS "sugar_2",
    "Rice_2" AS "rice_2",
    "Wheat_3" AS "wheat_3",
    "Barley_3" AS "barley_3",
    "Common red wine_3" AS "common_red_wine_3",
    "Veal_3" AS "veal_3",
    "Beef_3" AS "beef_3",
    "Firewood_3" AS "firewood_3",
    "Cloth ""basso""_3" AS "cloth_basso_3",
    "Cloth ""alto""_3" AS "cloth_alto_3",
    "Candles_3" AS "candles_3",
    "Bricks_3" AS "bricks_3",
    "Tiles_3" AS "tiles_3",
    "Lime_3" AS "lime_3",
    "Sugar_3" AS "sugar_3",
    "Rice_3" AS "rice_3",
    "Occupation:" AS "occupation",
    "Master Mason" AS "master_mason",
    "Unskilled mason" AS "unskilled_mason",
    "Carpenter" AS "carpenter",
    "Agricultural laborer" AS "agricultural_laborer",
    "Master Mason_2" AS "master_mason_2",
    "Unskilled mason_2" AS "unskilled_mason_2",
    "Carpenter_2" AS "carpenter_2",
    "Agricultural laborer_2" AS "agricultural_laborer_2",
    "TEMPLATE" AS "template",
    "Currency:" AS "currency",
    "Scudo d'oro Modenese" AS "scudo_d_oro_modenese",
    "Ducatone Milanese" AS "ducatone_milanese",
    "Doppia di Spagna" AS "doppia_di_spagna",
    "Zecchino d'oro Veneziano" AS "zecchino_d_oro_veneziano",
    "Scudo d'oro" AS "scudo_d_oro",
    "Soldi" AS "soldi"
FROM "gpih-italy-modena-to-1705"
