-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "place",
    "place2",
    "year",
    "date or note" AS "date_or_note",
    "month",
    "Column1" AS "column1",
    "Column2" AS "column2",
    "сколько человек" AS "column",
    "объем работы" AS "column_2",
    "специальность (speciality)" AS "speciality",
    "gender",
    "industry",
    "Column5" AS "column5",
    "skilled vs unskilled" AS "skilled_vs_unskilled",
    "profession",
    "estate",
    "вид контракта" AS "column_3",
    "type of contract" AS "type_of_contract",
    "сумма в рублях (total rubles)" AS "total_rubles",
    "wage per day" AS "wage_per_day",
    "сomments" AS "omments",
    "дело (source)" AS "source",
    "Column3" AS "column3",
    "Column4" AS "column4",
    "Column42" AS "column42",
    "date",
    "месяц" AS "column_4",
    "Month_1" AS "month_1",
    "город" AS "column_5",
    "City" AS "city",
    "продукт" AS "column_6",
    "Commodity" AS "commodity",
    "Subcategory" AS "subcategory",
    "уточнение1" AS "1",
    "уточнение2" AS "2",
    "уточнение3" AS "3",
    "уточнение4" AS "4",
    "уточнение5" AS "5",
    "уточнение6" AS "6",
    "уточнение7" AS "7",
    "уточнение8" AS "8",
    "уточнение9" AS "9",
    "уточнение10" AS "10",
    "source" AS "source_2",
    "measures",
    "Цена1" AS "1_2",
    "measures2",
    "Source4" AS "source4",
    "page",
    "Source2" AS "source2",
    "page2",
    "source3",
    "page3",
    "name of the person who entered the data (if empty check z)" AS "name_of_the_person_who_entered_the_data_if_empty_check_z",
    CAST("c31" AS BIGINT) AS "c31"
FROM "gpih-moscow-wage-and-price-detailed-data-1553-1851"
