-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "c0",
    "Good" AS "good",
    "Wheat" AS "wheat",
    "White Bread" AS "white_bread",
    "Brown Bread" AS "brown_bread",
    "Rye" AS "rye",
    "Barley" AS "barley",
    "Oats" AS "oats",
    "Beef" AS "beef",
    "Mutton" AS "mutton",
    "Herring" AS "herring",
    "Rice" AS "rice",
    "Peas" AS "peas",
    "Soap" AS "soap",
    "Sugar" AS "sugar",
    "Olive Oil" AS "olive_oil",
    "Honey" AS "honey",
    "Cheese (plain)" AS "cheese_plain",
    "Milk" AS "milk",
    "Eggs" AS "eggs",
    "Butter" AS "butter",
    "Wine" AS "wine",
    "Wood (hard)" AS "wood_hard",
    "Wood (soft)" AS "wood_soft",
    "Fagots" AS "fagots",
    "Charcoal" AS "charcoal",
    "Beer" AS "beer",
    "Drapery" AS "drapery",
    "Drapery_2" AS "drapery_2",
    "Drapery_3" AS "drapery_3",
    "Linen" AS "linen",
    "Wheat_2" AS "wheat_2",
    "Rye_2" AS "rye_2",
    "Barley_2" AS "barley_2",
    "Oats_2" AS "oats_2",
    "Bread (white)" AS "bread_white",
    "Bread (brown)" AS "bread_brown",
    "Drapery_4" AS "drapery_4",
    "Drapery_5" AS "drapery_5",
    "Drapery_6" AS "drapery_6",
    "Beef_2" AS "beef_2",
    "Mutton_2" AS "mutton_2",
    "Herring_2" AS "herring_2",
    "Rice_2" AS "rice_2",
    "Peas_2" AS "peas_2",
    "Soap_2" AS "soap_2",
    "Sugar_2" AS "sugar_2",
    "Olive Oil_2" AS "olive_oil_2",
    "Honey_2" AS "honey_2",
    "Cheese (plain)_2" AS "cheese_plain_2",
    "Milk_2" AS "milk_2",
    "Eggs_2" AS "eggs_2",
    "Butter_2" AS "butter_2",
    "Wine_2" AS "wine_2",
    "Wood (hard)_2" AS "wood_hard_2",
    "Wood (soft)_2" AS "wood_soft_2",
    "Fagots_2" AS "fagots_2",
    "Charcoal_2" AS "charcoal_2",
    "Beer_2" AS "beer_2",
    "Candle" AS "candle",
    "Linen_2" AS "linen_2",
    "c61",
    "Bread" AS "bread",
    "Beans" AS "beans",
    "Meat" AS "meat",
    "Butter_3" AS "butter_3",
    "Cheese" AS "cheese",
    "Eggs_3" AS "eggs_3",
    "Herring_3" AS "herring_3",
    "Oil/cook" AS "oil_cook",
    "Rice_3" AS "rice_3",
    "Sugar_3" AS "sugar_3",
    "Beer_3" AS "beer_3",
    "Wine_3" AS "wine_3",
    "Soap_3" AS "soap_3",
    "Wool" AS "wool",
    "Linen_3" AS "linen_3",
    "Candles" AS "candles",
    "Oil/light" AS "oil_light",
    "Charcoal_3" AS "charcoal_3",
    "Wood (hard)_3" AS "wood_hard_3",
    "Wood (soft)_3" AS "wood_soft_3",
    "Fagot" AS "fagot",
    "Firewood/Charcoal" AS "firewood_charcoal",
    "Charcoal_4" AS "charcoal_4",
    "Cheese (Gruyere)" AS "cheese_gruyere",
    "NEW CPI" AS "new_cpi",
    "NEW CPI_2" AS "new_cpi_2",
    "Source" AS "source",
    "[1]" AS "1",
    "[1]_2" AS "1_2",
    "[1]_3" AS "1_3",
    "[1]_4" AS "1_4",
    "[1]_5" AS "1_5"
FROM "gpih-allen-strasbourg-1313-1875"
