-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "Farm" AS "farm",
    "Farm labor" AS "farm_labor",
    "monthly",
    "10.85" AS "10_85",
    "yes; board" AS "yes_board",
    "5.425" AS "5_425",
    "16.275" AS "16_275",
    "195.29999999999998" AS "195_29999999999998",
    "HSUS (2006) Ba 4234" AS "hsus_2006_ba_4234",
    "See 1860 Farm sheet for ""board""." AS "see_1860_farm_sheet_for_board",
    "c0",
    "Occupation" AS "occupation",
    "time unit" AS "time_unit",
    "wage ($)" AS "wage",
    "In kind payments?" AS "in_kind_payments",
    "In kind ($)" AS "in_kind",
    "Total Wage ($)" AS "total_wage",
    "Annual Earnings" AS "annual_earnings",
    "Source" AS "source",
    "Notes" AS "notes",
    "Rural Non-Farm" AS "rural_non_farm",
    "cash wage ($)" AS "cash_wage",
    "Total wage ($)_1" AS "total_wage_1",
    "United States" AS "united_states",
    "free farm labor" AS "free_farm_labor",
    "yes: board" AS "yes_board_2",
    "Lebergott (1964: Table A-23, p. 539)." AS "lebergott_1964_table_a_23_p_539",
    "We assume ""board"" means room and board = 50% of the cash wag" AS "we_assume_board_means_room_and_board_50_of_the_cash_wag",
    "c10",
    "Rural" AS "rural",
    "male",
    "101.96" AS "101_96",
    "yes",
    "50.98" AS "50_98",
    "5.998" AS "5_998",
    "0.49983333333333335" AS "0_49983333333333335",
    "101.96_2" AS "101_96_2",
    "50.98_2" AS "50_98_2",
    "152.94" AS "152_94",
    "297.15" AS "297_15",
    "301.515" AS "301_515",
    "Winter" AS "winter",
    "Summer" AS "summer",
    "Total" AS "total",
    "Male_1" AS "male_1",
    "Female" AS "female",
    "F/M" AS "f_m",
    "ave",
    "Male_2" AS "male_2",
    "Female_2" AS "female_2",
    "Male_3" AS "male_3",
    "Female_3" AS "female_3",
    "F/M_2" AS "f_m_2",
    "Male_4" AS "male_4",
    "Female_4" AS "female_4",
    "Urban Female wts" AS "urban_female_wts",
    "NE" AS "ne",
    "NC" AS "nc",
    "S" AS "s",
    "other",
    "Rural Female wts" AS "rural_female_wts",
    "NE_2" AS "ne_2",
    "NC_2" AS "nc_2",
    "S_2" AS "s_2",
    "other_2",
    "JGW May 9 2013" AS "jgw_may_9_2013",
    "c1",
    "c2",
    "JGW May 18, 2013" AS "jgw_may_18_2013",
    "Construction" AS "construction",
    "0.0173" AS "0_0173",
    "c3",
    "Annual Mining" AS "annual_mining",
    "coal",
    "iron",
    "copper",
    "coal+iron" AS "coal_iron",
    "coal+copper" AS "coal_copper",
    "iron+copper" AS "iron_copper",
    "all 3" AS "all_3",
    "quarrying",
    "c9"
FROM "gpih-wage-data-summary-1850-12sept13"
