-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS sheet,
    "Year" AS year,
    "per kg loaf" AS per_kg_loaf,
    "per kg" AS per_kg,
    "per kg_2" AS per_kg_2,
    "per kg_3" AS per_kg_3,
    "per kg_4" AS per_kg_4,
    "per kg_5" AS per_kg_5,
    "Year 31 Dec" AS year_31_dec,
    "Wheat" AS wheat,
    "Maize" AS maize,
    "Barley" AS barley,
    "Oats" AS oats,
    "Flour" AS flour,
    "Bread" AS bread,
    "Potatoes" AS potatoes,
    "Poultry" AS poultry,
    "Eggs" AS eggs,
    "Cheese" AS cheese,
    "Butter" AS butter,
    "silver per" AS silver_per,
    "Wheat_2" AS wheat_2,
    "Maize_2" AS maize_2,
    "Barley_2" AS barley_2,
    "Oats_2" AS oats_2,
    "Flour_2" AS flour_2,
    "Bread_2" AS bread_2,
    "Potatoes_2" AS potatoes_2,
    "Poultry_2" AS poultry_2,
    "Eggs_2" AS eggs_2,
    "Cheese_2" AS cheese_2,
    "Butter_2" AS butter_2,
    "pound Sterling" AS pound_sterling,
    "pound Sterling_2" AS pound_sterling_2,
    "pound Sterling_3" AS pound_sterling_3,
    "pound Sterling_4" AS pound_sterling_4,
    "pound Sterling_5" AS pound_sterling_5,
    "pound Sterling_6" AS pound_sterling_6,
    "pound Sterling_7" AS pound_sterling_7,
    "pound Sterling_8" AS pound_sterling_8,
    "pound Sterling_9" AS pound_sterling_9,
    "pound Sterling_10" AS pound_sterling_10,
    "pound Sterling_11" AS pound_sterling_11,
    "pound Sterling_12" AS pound_sterling_12,
    "pound Sterling_13" AS pound_sterling_13,
    "pound Sterling_14" AS pound_sterling_14,
    "Year (Dec 31)" AS year_dec_31,
    "NSWa" AS nswa,
    "NSWb" AS nswb,
    "Vica" AS vica,
    "Vicb" AS vicb,
    "Qlda" AS qlda,
    "SAa" AS saa
FROM "gpih-ns-wales-food-p-w-1818-1983"
