-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "c0",
    "Good" AS "good",
    "Rye" AS "rye",
    "Oats" AS "oats",
    "Wheat" AS "wheat",
    "Rye_2" AS "rye_2",
    "Barley" AS "barley",
    "Oats_2" AS "oats_2",
    "Peas" AS "peas",
    "Wheat_2" AS "wheat_2",
    "Rye_3" AS "rye_3",
    "Barley_2" AS "barley_2",
    "Oats_3" AS "oats_3",
    "Rye_4" AS "rye_4",
    "Wheat_3" AS "wheat_3",
    "Tallow" AS "tallow",
    "Butter" AS "butter",
    "English Cloth" AS "english_cloth",
    """Scharlach""" AS "scharlach",
    "Linen" AS "linen",
    "Linen_2" AS "linen_2",
    """Barchent""" AS "barchent",
    "Drill" AS "drill",
    "Rice" AS "rice",
    "Herring" AS "herring",
    "Stockfish" AS "stockfish",
    "Beer" AS "beer",
    "Oil" AS "oil",
    "Beef" AS "beef",
    "Rye_5" AS "rye_5",
    "Wheat_4" AS "wheat_4",
    "Rye_6" AS "rye_6",
    "Barley_3" AS "barley_3",
    "Peas_2" AS "peas_2",
    "Wheat_5" AS "wheat_5",
    "Rye_7" AS "rye_7",
    "Barley_4" AS "barley_4",
    "Tallow_2" AS "tallow_2",
    "Butter_2" AS "butter_2",
    "English Cloth_2" AS "english_cloth_2",
    """Scharlach""_2" AS "scharlach_2",
    "Linen_3" AS "linen_3",
    "Linen_4" AS "linen_4",
    """Barchent""_2" AS "barchent_2",
    "Drill_2" AS "drill_2",
    "Rice_2" AS "rice_2",
    "Herring_2" AS "herring_2",
    "Stockfish_2" AS "stockfish_2",
    "Beer_2" AS "beer_2",
    "Oil_2" AS "oil_2",
    "Beef_2" AS "beef_2",
    "c51",
    "Barley_5" AS "barley_5",
    "Wage" AS "wage",
    "Rye_8" AS "rye_8",
    "Bread" AS "bread",
    "Beans" AS "beans",
    "Beef_3" AS "beef_3",
    "Butter_3" AS "butter_3",
    "Cheese" AS "cheese",
    "Eggs" AS "eggs",
    "Beer_3" AS "beer_3",
    "Soap" AS "soap",
    "Linen_5" AS "linen_5",
    "Candles" AS "candles",
    "Oil/light" AS "oil_light",
    "Wood/Charcoal" AS "wood_charcoal",
    "Charcoal" AS "charcoal",
    "NEW CPI" AS "new_cpi",
    "NEW CPI_2" AS "new_cpi_2",
    "Source" AS "source",
    "[1]" AS "1",
    "[1]_2" AS "1_2",
    "[1]_3" AS "1_3",
    "[1]_4" AS "1_4",
    "[1]_5" AS "1_5",
    "[1]_6" AS "1_6",
    "[1]_7" AS "1_7",
    "[1]_8" AS "1_8",
    "[1]_9" AS "1_9",
    "[1]_10" AS "1_10",
    "1402",
    "c1",
    "26.7" AS "26_7",
    "2.44" AS "2_44",
    "11.22" AS "11_22",
    "0.273768" AS "0_273768",
    "[1]:" AS "1_11",
    "Elsas, M.J., Umriss einer Geschichte der Preise und Löhne in" AS "elsas_m_j_umriss_einer_geschichte_der_preise_und_l_hne_in",
    "c8"
FROM "gpih-allen-munich-1400-1914"
