-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS sheet,
    "c0",
    "Total" AS total,
    "Primier" AS primier,
    "Second" AS second,
    "Enseignt" AS enseignt,
    "Other" AS other,
    "Total_2" AS total_2,
    "Primier_2" AS primier_2,
    "Second_2" AS second_2,
    "Enseignt_2" AS enseignt_2,
    "Other_2" AS other_2,
    "Total_3" AS total_3,
    "Primier_3" AS primier_3,
    "Second_3" AS second_3,
    "Enseignt_3" AS enseignt_3,
    "Other_3" AS other_3,
    "Total_4" AS total_4,
    "Primier_4" AS primier_4,
    "Second_4" AS second_4,
    "Enseignt_4" AS enseignt_4,
    "Other_4" AS other_4,
    "(millions)" AS millions,
    "(mn old fr)" AS mn_old_fr,
    "(bill new fr)" AS bill_new_fr,
    "(bill new fr)_2" AS bill_new_fr_2,
    "(bill. Euros)" AS bill_euros,
    "Total_5" AS total_5,
    "Primier_5" AS primier_5,
    "Second_5" AS second_5,
    "Enseignt_5" AS enseignt_5,
    "Other_5" AS other_5,
    "Total_6" AS total_6,
    "Unesco" AS unesco,
    "Primier_6" AS primier_6,
    "Second_6" AS second_6,
    "Supérieur" AS sup_rieur,
    "Other_6" AS other_6,
    "Total_7" AS total_7,
    "Primier_7" AS primier_7,
    "Second_7" AS second_7,
    "Enseignt_6" AS enseignt_6,
    "Other_7" AS other_7,
    "1820",
    "0.14499866155081645" AS 0_14499866155081645,
    "0.07807620237351656" AS 0_07807620237351656,
    "0.011153743196216653" AS 0_011153743196216653,
    "Year" AS year,
    "ménages" AS m_nages,
    "communes",
    "départments" AS d_partments,
    "l'état" AS l_tat,
    "other admin's" AS other_admin_s,
    "Year_2" AS year_2,
    "ménages_2" AS m_nages_2,
    "& communes" AS communes_2,
    "& départments" AS d_partments_2,
    "& other" AS other_8,
    "total_1"
FROM "gpih-france-educ-exp-1820-2009a"
