-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: GPIH workbooks are heterogeneous academic spreadsheets; rows can mix sheets, measures, units, places, or aggregation levels from the source workbook. Inspect the table columns before summing or comparing values across rows.
-- caution: No stable row key was verified from the raw workbook profile, so this table is modeled as keyless pass-through data.
SELECT
    "__sheet__" AS "sheet",
    "no." AS "no",
    "rural",
    "Groups" AS "groups",
    "Group definition" AS "group_definition",
    "c4",
    "England" AS "england",
    "Colonies" AS "colonies",
    "South" AS "south",
    "Colonies_2" AS "colonies_2",
    "England_2" AS "england_2",
    "Colonies_3" AS "colonies_3",
    "South_2" AS "south_2",
    "Colonies_4" AS "colonies_4",
    "c13",
    "England_3" AS "england_3",
    "Colonies_5" AS "colonies_5",
    "South_3" AS "south_3",
    "Colonies_6" AS "colonies_6",
    "England_4" AS "england_4",
    "Colonies_7" AS "colonies_7",
    "South_4" AS "south_4",
    "Colonies_8" AS "colonies_8",
    "c22",
    "England_5" AS "england_5",
    "Colonies_9" AS "colonies_9",
    "South_5" AS "south_5",
    "Colonies_10" AS "colonies_10",
    "c27",
    "England_6" AS "england_6",
    "Colonies_11" AS "colonies_11",
    "South_6" AS "south_6",
    "Colonies_12" AS "colonies_12",
    "England_7" AS "england_7",
    "Colonies_13" AS "colonies_13",
    "South_7" AS "south_7",
    "Colonies_14" AS "colonies_14",
    "c36",
    "England_8" AS "england_8",
    "Colonies_15" AS "colonies_15",
    "South_8" AS "south_8",
    "Colonies_16" AS "colonies_16",
    "c41",
    "All" AS "all",
    "c1",
    "Gini =" AS "gini",
    "0.4367836993579704" AS "0_4367836993579704",
    "$" AS "column",
    "c5",
    "Gini =_2" AS "gini_2",
    "0.39950730405499335" AS "0_39950730405499335",
    "$_2" AS "2"
FROM "gpih-tables-locked-american-social-table-1774"
