-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: This is an anonymized case line list for a concluded outbreak; dates describe case lifecycle and record maintenance events rather than a uniform observation period.
SELECT
    CAST("ID" AS BIGINT) AS id,
    "Pathogen" AS pathogen,
    "Case_status" AS case_status,
    "Location_District" AS location_district,
    "Country" AS country,
    "Age" AS age,
    "Gender" AS gender,
    "Occupation" AS occupation,
    "Healthcare_worker" AS healthcare_worker,
    "Symptoms" AS symptoms,
    "Date_onset" AS date_onset,
    "Date_confirmation" AS date_confirmation,
    "Confirmation_method" AS confirmation_method,
    "Previous_infection" AS previous_infection,
    "Co_infection" AS co_infection,
    "Pre_existing_condition" AS pre_existing_condition,
    "Pregnancy_status" AS pregnancy_status,
    "Vaccination" AS vaccination,
    "Vaccine_name" AS vaccine_name,
    "Vaccine_date" AS vaccine_date,
    "Vaccine_side_effects" AS vaccine_side_effects,
    "Date_of_first_consult" AS date_of_first_consult,
    "Hospitalised" AS hospitalised,
    "Reason_for_hospitalization" AS reason_for_hospitalization,
    "Date_hospitalisation" AS date_hospitalisation,
    "Date_discharge_hospital" AS date_discharge_hospital,
    "Intensive_care (Y/N/NA)" AS intensive_care_y_n_na,
    "Date_admission_ICU" AS date_admission_icu,
    "Date_discharge_ICU" AS date_discharge_icu,
    "Home_monitoring (Y/N/NA)" AS home_monitoring_y_n_na,
    "Isolated (Y/N/NA)" AS isolated_y_n_na,
    "Date_isolation" AS date_isolation,
    "Outcome" AS outcome,
    "Date_Death" AS date_death,
    "Date_Recovered" AS date_recovered,
    "Contact_with_case" AS contact_with_case,
    CAST("Contact_ID" AS BIGINT) AS contact_id,
    "Contact_setting" AS contact_setting,
    "Contact_setting_other" AS contact_setting_other,
    "Contact_animal" AS contact_animal,
    "Contact_comment" AS contact_comment,
    "Transmission" AS transmission,
    "Travel_history (Y/N/NA)" AS travel_history_y_n_na,
    "Travel_history_entry" AS travel_history_entry,
    "Travel_history_start" AS travel_history_start,
    "Travel_history_location" AS travel_history_location,
    "Travel_history_country" AS travel_history_country,
    "Genomica_Metadata" AS genomica_metadata,
    "Accession Number" AS accession_number,
    "Source" AS source,
    "Source_II" AS source_ii,
    "Date_entry" AS date_entry,
    "Date_last_modified" AS date_last_modified,
    "Source_III" AS source_iii,
    "Source_IV" AS source_iv,
    "Source_V" AS source_v,
    "Source_VI" AS source_vi,
    "col_58"
FROM "global-health-ebola-uganda-2022"
