-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("REG_CODE" AS VARCHAR) AS reg_code,
    CAST("REG_LIBELLE" AS VARCHAR) AS reg_libelle,
    CAST("DEP_CODE" AS VARCHAR) AS dep_code,
    CAST("DEP_LIBELLE" AS VARCHAR) AS dep_libelle,
    CAST("COMM" AS VARCHAR) AS comm,
    CAST("NUM_PA" AS VARCHAR) AS num_pa,
    CAST("ETAT_PA" AS BIGINT) AS etat_pa,
    CAST("DATE_REELLE_AUTORISATION" AS DATE) AS date_reelle_autorisation,
    CAST("DATE_REELLE_DOC" AS DATE) AS date_reelle_doc,
    CAST("DATE_REELLE_DAACT" AS DATE) AS date_reelle_daact,
    CAST("AN_DEPOT" AS BIGINT) AS an_depot,
    CAST("DR_DEPOT" AS VARCHAR) AS dr_depot,
    strptime("DPC_AUT", '%Y-%m')::DATE AS dpc_aut,
    strptime("DPC_DOC", '%Y-%m')::DATE AS dpc_doc,
    strptime("DPC_DERN", '%Y-%m')::DATE AS dpc_dern,
    CAST("APE_DEM" AS VARCHAR) AS ape_dem,
    CAST("CJ_DEM" AS BIGINT) AS cj_dem,
    CAST("DENOM_DEM" AS VARCHAR) AS denom_dem,
    CAST("SIREN_DEM" AS VARCHAR) AS siren_dem,
    CAST("SIRET_DEM" AS VARCHAR) AS siret_dem,
    CAST("CODPOST_DEM" AS VARCHAR) AS codpost_dem,
    CAST("LOCALITE_DEM" AS VARCHAR) AS localite_dem,
    CAST("REC_ARCHI" AS BOOLEAN) AS rec_archi,
    CAST("ADR_NUM_TER" AS VARCHAR) AS adr_num_ter,
    CAST("ADR_LIBVOIE_TER" AS VARCHAR) AS adr_libvoie_ter,
    CAST("ADR_LIEUDIT_TER" AS VARCHAR) AS adr_lieudit_ter,
    CAST("ADR_LOCALITE_TER" AS VARCHAR) AS adr_localite_ter,
    CAST("ADR_CODPOST_TER" AS VARCHAR) AS adr_codpost_ter,
    CAST("SEC_CADASTRE1" AS VARCHAR) AS sec_cadastre1,
    CAST("NUM_CADASTRE1" AS VARCHAR) AS num_cadastre1,
    CAST("SEC_CADASTRE2" AS VARCHAR) AS sec_cadastre2,
    CAST("NUM_CADASTRE2" AS VARCHAR) AS num_cadastre2,
    CAST("SEC_CADASTRE3" AS VARCHAR) AS sec_cadastre3,
    CAST("NUM_CADASTRE3" AS VARCHAR) AS num_cadastre3,
    CAST("SUPERFICIE_TERRAIN" AS BIGINT) AS superficie_terrain,
    CAST("ZONE_OP" AS BIGINT) AS zone_op
FROM "sdes-96883f50-538b-41f9-a059-c6eb97e6a23a"
