-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "_entity_id" AS entity_id,
    "_source_type" AS source_type,
    "_socrata_dataset_id" AS socrata_dataset_id,
    "legislative_district",
    CAST("total_population_2010" AS BIGINT) AS total_population_2010,
    CAST("population_of_one_race_2010" AS BIGINT) AS population_of_one_race_2010,
    CAST("white_alone_2010" AS BIGINT) AS white_alone_2010,
    CAST("black_or_african_american_alone_2010" AS BIGINT) AS black_or_african_american_alone_2010,
    CAST("american_indian_and_alaska_native_alone_2010" AS BIGINT) AS american_indian_and_alaska_native_alone_2010,
    CAST("asian_alone_2010" AS BIGINT) AS asian_alone_2010,
    CAST("native_hawaiian_and_other_pacific_islander_alone_2010" AS BIGINT) AS native_hawaiian_and_other_pacific_islander_alone_2010,
    CAST("some_other_race_alone_2010" AS BIGINT) AS some_other_race_alone_2010,
    CAST("population_of_two_or_more_races_2010" AS BIGINT) AS population_of_two_or_more_races_2010,
    CAST("hispanic_or_latino_of_any_race_2010" AS BIGINT) AS hispanic_or_latino_of_any_race_2010,
    CAST("not_hispanic_or_latino_2010" AS BIGINT) AS not_hispanic_or_latino_2010,
    CAST("population_of_one_race_not_hispanic_or_latino_2010" AS BIGINT) AS population_of_one_race_not_hispanic_or_latino_2010,
    CAST("white_alone_not_hispanic_or_latino_2010" AS BIGINT) AS white_alone_not_hispanic_or_latino_2010,
    CAST("black_or_african_american_alone_not_hispanic_or_latino_2010" AS BIGINT) AS black_or_african_american_alone_not_hispanic_or_latino_2010,
    CAST("american_indian_and_alaska_native_alone_not_hispanic_or_latino_2010" AS BIGINT) AS american_indian_and_alaska_native_alone_not_hispanic_or_latino_2010,
    CAST("asian_alone_not_hispanic_or_latino_2010" AS BIGINT) AS asian_alone_not_hispanic_or_latino_2010,
    CAST("native_hawaiian_and_other_pacific_islander_alone_not_hispanic_or_latino_2010" AS BIGINT) AS native_hawaiian_and_other_pacific_islander_alone_not_hispanic_or_latino_2010,
    CAST("some_other_race_alone_not_hispanic_or_latino_2010" AS BIGINT) AS some_other_race_alone_not_hispanic_or_latino_2010,
    CAST("population_of_two_or_more_races_not_hispanic_or_latino_2010" AS BIGINT) AS population_of_two_or_more_races_not_hispanic_or_latino_2010,
    CAST("total_population_over_18_2010" AS BIGINT) AS total_population_over_18_2010,
    CAST("population_of_one_race_over_18_2010" AS BIGINT) AS population_of_one_race_over_18_2010,
    CAST("white_alone_over_18_2010" AS BIGINT) AS white_alone_over_18_2010,
    CAST("black_or_african_american_alone_over_18_2010" AS BIGINT) AS black_or_african_american_alone_over_18_2010,
    CAST("american_indian_and_alaska_native_alone_over_18_2010" AS BIGINT) AS american_indian_and_alaska_native_alone_over_18_2010,
    CAST("asian_alone_over_18_2010" AS BIGINT) AS asian_alone_over_18_2010,
    CAST("native_hawaiian_and_other_pacific_islander_alone_over_18_2010" AS BIGINT) AS native_hawaiian_and_other_pacific_islander_alone_over_18_2010,
    CAST("some_other_race_alone_over_18_2010" AS BIGINT) AS some_other_race_alone_over_18_2010,
    CAST("population_of_two_or_more_races_over_18_2010" AS BIGINT) AS population_of_two_or_more_races_over_18_2010,
    CAST("hispanic_or_latino_of_any_race_over_18_2010" AS BIGINT) AS hispanic_or_latino_of_any_race_over_18_2010,
    CAST("not_hispanic_or_latino_over_18_2010" AS BIGINT) AS not_hispanic_or_latino_over_18_2010,
    CAST("population_of_one_race_not_hispanic_or_latino_over_18_2010" AS BIGINT) AS population_of_one_race_not_hispanic_or_latino_over_18_2010,
    CAST("white_alone_not_hispanic_or_latino_over_18_2010" AS BIGINT) AS white_alone_not_hispanic_or_latino_over_18_2010,
    CAST("black_or_african_american_alone_not_hispanic_or_latino_over_18_2010" AS BIGINT) AS black_or_african_american_alone_not_hispanic_or_latino_over_18_2010,
    CAST("american_indian_and_alaska_native_alone_not_hispanic_or_latino_over_18_2010" AS BIGINT) AS american_indian_and_alaska_native_alone_not_hispanic_or_latino_over_18_2010,
    CAST("asian_alone_not_hispanic_or_latino_over_18_2010" AS BIGINT) AS asian_alone_not_hispanic_or_latino_over_18_2010,
    CAST("native_hawaiian_and_other_pacific_islander_alone_not_hispanic_or_latino_over_18_2010" AS BIGINT) AS native_hawaiian_and_other_pacific_islander_alone_not_hispanic_or_latino_over_18_2010,
    CAST("some_other_race_alone_not_hispanic_or_latino_over_18_2010" AS BIGINT) AS some_other_race_alone_not_hispanic_or_latino_over_18_2010,
    CAST("population_of_two_or_more_races_not_hispanic_or_latino_over_18_2010" AS BIGINT) AS population_of_two_or_more_races_not_hispanic_or_latino_over_18_2010
FROM "washington-ofm-socrata-di4y-k8za"
