-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("UNITID" AS BIGINT) AS unitid,
    "LEXP100K" AS lexp100k,
    CAST("LCOLELYN" AS BIGINT) AS lcolelyn,
    "XLPBOOKS" AS xlpbooks,
    "LPBOOKS" AS lpbooks,
    "XLEBOOKS" AS xlebooks,
    CAST("LEBOOKS" AS BIGINT) AS lebooks,
    "XLEDATAB" AS xledatab,
    CAST("LEDATAB" AS BIGINT) AS ledatab,
    "XLPMEDIA" AS xlpmedia,
    "LPMEDIA" AS lpmedia,
    "XLEMEDIA" AS xlemedia,
    CAST("LEMEDIA" AS BIGINT) AS lemedia,
    "XLPSERIA" AS xlpseria,
    "LPSERIA" AS lpseria,
    "XLESERIA" AS xleseria,
    "LESERIA" AS leseria,
    "XLPCOLLC" AS xlpcollc,
    "LPCLLCT" AS lpcllct,
    "XLECOLLC" AS xlecollc,
    CAST("LECLLCT" AS BIGINT) AS lecllct,
    "XLTCLLCT" AS xltcllct,
    "LTCLLCT" AS ltcllct,
    "XLPCRCLT" AS xlpcrclt,
    "LPCRCLT" AS lpcrclt,
    "XLECRCLT" AS xlecrclt,
    CAST("LECRCLT" AS BIGINT) AS lecrclt,
    "XLTCRCLT" AS xltcrclt,
    "LTCRCLT" AS ltcrclt,
    "LILLDYN" AS lilldyn,
    "XLILLDPR" AS xlilldpr,
    "LILLDPR" AS lilldpr,
    "XLILLDRC" AS xlilldrc,
    "LILLDRC" AS lilldrc,
    "LILSYN" AS lilsyn,
    "XLSTOTAL" AS xlstotal,
    "LSTOTAL" AS lstotal,
    "XLSLIBRN" AS xlslibrn,
    "LSLIBRN" AS lslibrn,
    "XLSOPROF" AS xlsoprof,
    "LSOPROF" AS lsoprof,
    "XLSOPAID" AS xlsopaid,
    "LSOPAID" AS lsopaid,
    "XLSSTAST" AS xlsstast,
    "LSSTAST" AS lsstast,
    "XLBRANCH" AS xlbranch,
    "LBRANCH" AS lbranch,
    "XSALWAG" AS xsalwag,
    "LSALWAG" AS lsalwag,
    CAST("LFRNGBYN" AS BIGINT) AS lfrngbyn,
    "XLFRNGBN" AS xlfrngbn,
    "LFRNGBN" AS lfrngbn,
    "XLEXMSBB" AS xlexmsbb,
    "LEXMSBB" AS lexmsbb,
    "XLEXMSCS" AS xlexmscs,
    "LEXMSCS" AS lexmscs,
    "XLEXMSOT" AS xlexmsot,
    "LEXMSOT" AS lexmsot,
    "XLEXMSTL" AS xlexmstl,
    "LEXMSTL" AS lexmstl,
    "XLEXOMPS" AS xlexomps,
    "LEXOMPS" AS lexomps,
    "XLEXOMOT" AS xlexomot,
    "LEXOMOT" AS lexomot,
    "XLEXOMTL" AS xlexomtl,
    "LEXOMTL" AS lexomtl,
    "XLEXPTOT" AS xlexptot,
    "LEXPTOT" AS lexptot,
    "LSWMSOM" AS lswmsom,
    "year"
FROM "nces-ipeds-al"
