-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("UNITID" AS BIGINT) AS unitid,
    "INSTNM" AS instnm,
    "IALIAS" AS ialias,
    "ADDR" AS addr,
    "CITY" AS city,
    "STABBR" AS stabbr,
    "ZIP" AS zip,
    CAST("FIPS" AS BIGINT) AS fips,
    CAST("OBEREG" AS BIGINT) AS obereg,
    "CHFNM" AS chfnm,
    "CHFTITLE" AS chftitle,
    "GENTELE" AS gentele,
    "EIN" AS ein,
    "UEIS" AS ueis,
    "OPEID" AS opeid,
    CAST("OPEFLAG" AS BIGINT) AS opeflag,
    "WEBADDR" AS webaddr,
    "ADMINURL" AS adminurl,
    "FAIDURL" AS faidurl,
    "APPLURL" AS applurl,
    "NPRICURL" AS npricurl,
    "VETURL" AS veturl,
    "ATHURL" AS athurl,
    "DISAURL" AS disaurl,
    CAST("SECTOR" AS BIGINT) AS sector,
    CAST("ICLEVEL" AS BIGINT) AS iclevel,
    CAST("CONTROL" AS BIGINT) AS control,
    CAST("HLOFFER" AS BIGINT) AS hloffer,
    CAST("UGOFFER" AS BIGINT) AS ugoffer,
    CAST("GROFFER" AS BIGINT) AS groffer,
    "HDEGOFR1" AS hdegofr1,
    CAST("DEGGRANT" AS BIGINT) AS deggrant,
    CAST("HBCU" AS BIGINT) AS hbcu,
    CAST("HOSPITAL" AS BIGINT) AS hospital,
    CAST("MEDICAL" AS BIGINT) AS medical,
    CAST("TRIBAL" AS BIGINT) AS tribal,
    CAST("LOCALE" AS BIGINT) AS locale,
    CAST("OPENPUBL" AS BIGINT) AS openpubl,
    "ACT" AS act,
    "NEWID" AS newid,
    CAST("DEATHYR" AS BIGINT) AS deathyr,
    "CLOSEDAT" AS closedat,
    CAST("CYACTIVE" AS BIGINT) AS cyactive,
    CAST("POSTSEC" AS BIGINT) AS postsec,
    CAST("PSEFLAG" AS BIGINT) AS pseflag,
    CAST("PSET4FLG" AS BIGINT) AS pset4flg,
    "RPTMTH" AS rptmth,
    "INSTCAT" AS instcat,
    "C00CARNEGIE" AS c00carnegie,
    "C21BASIC" AS c21basic,
    "CARNEGIEIC" AS carnegieic,
    "CARNEGIESAEC" AS carnegiesaec,
    "CARNEGIERSCH" AS carnegiersch,
    "CARNEGIESIZE" AS carnegiesize,
    "CARNEGIEALF" AS carnegiealf,
    "CARNEGIEAPM" AS carnegieapm,
    "CARNEGIEGPM" AS carnegiegpm,
    "LANDGRNT" AS landgrnt,
    "INSTSIZE" AS instsize,
    "F1SYSTYP" AS f1systyp,
    "F1SYSNAM" AS f1sysnam,
    "F1SYSCOD" AS f1syscod,
    "CBSA" AS cbsa,
    "CBSATYPE" AS cbsatype,
    "CSA" AS csa,
    "COUNTYCD" AS countycd,
    "COUNTYNM" AS countynm,
    "CNGDSTCD" AS cngdstcd,
    "LONGITUD" AS longitud,
    "LATITUDE" AS latitude,
    "DFRCGID" AS dfrcgid,
    "DFRCUSCG" AS dfrcuscg,
    "year"
FROM "nces-ipeds-hd"
