-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("UNITID" AS BIGINT) AS unitid,
    CAST("FTE12MN" AS BIGINT) AS fte12mn,
    CAST("UNDUP" AS BIGINT) AS undup,
    CAST("UNDUPUG" AS BIGINT) AS undupug,
    "E12FT" AS e12ft,
    "E12PT" AS e12pt,
    CAST("E12UG1ST" AS BIGINT) AS e12ug1st,
    CAST("E12UGTRN" AS BIGINT) AS e12ugtrn,
    CAST("E12UGCNT" AS BIGINT) AS e12ugcnt,
    CAST("E12UGNDG" AS BIGINT) AS e12ugndg,
    CAST("E12GRAD" AS BIGINT) AS e12grad,
    CAST("E12UGFT" AS BIGINT) AS e12ugft,
    CAST("E12UG1SFT" AS BIGINT) AS e12ug1sft,
    CAST("E12UGTRFT" AS BIGINT) AS e12ugtrft,
    CAST("E12UGCNFT" AS BIGINT) AS e12ugcnft,
    CAST("E12UGNDFT" AS BIGINT) AS e12ugndft,
    "E12GRADFT" AS e12gradft,
    CAST("E12UGPT" AS BIGINT) AS e12ugpt,
    CAST("E12UG1SPT" AS BIGINT) AS e12ug1spt,
    CAST("E12UGTRPT" AS BIGINT) AS e12ugtrpt,
    CAST("E12UGCNPT" AS BIGINT) AS e12ugcnpt,
    CAST("E12UGNDPT" AS BIGINT) AS e12ugndpt,
    "E12GRADPT" AS e12gradpt,
    CAST("PCTE12AN" AS BIGINT) AS pcte12an,
    CAST("PCTE12AS" AS BIGINT) AS pcte12as,
    CAST("PCTE12BK" AS BIGINT) AS pcte12bk,
    CAST("PCTE12HS" AS BIGINT) AS pcte12hs,
    CAST("PCTE12NH" AS BIGINT) AS pcte12nh,
    CAST("PCTE12WH" AS BIGINT) AS pcte12wh,
    CAST("PCTE122M" AS BIGINT) AS pcte122m,
    CAST("PCTE12UN" AS BIGINT) AS pcte12un,
    CAST("PCTE12NR" AS BIGINT) AS pcte12nr,
    CAST("PCTE12W" AS BIGINT) AS pcte12w,
    "PCTE12UGAN" AS pcte12ugan,
    "PCTE12UGAS" AS pcte12ugas,
    "PCTE12UGBK" AS pcte12ugbk,
    "PCTE12UGHS" AS pcte12ughs,
    "PCTE12UGNH" AS pcte12ugnh,
    "PCTE12UGWH" AS pcte12ugwh,
    "PCTE12UG2M" AS pcte12ug2m,
    "PCTE12UGUN" AS pcte12ugun,
    "PCTE12UGNR" AS pcte12ugnr,
    "PCTE12UGW" AS pcte12ugw,
    "PCTE12GRADAN" AS pcte12gradan,
    "PCTE12GRADAS" AS pcte12gradas,
    "PCTE12GRADBK" AS pcte12gradbk,
    "PCTE12GRADHS" AS pcte12gradhs,
    "PCTE12GRADNH" AS pcte12gradnh,
    "PCTE12GRADWH" AS pcte12gradwh,
    "PCTE12GRAD2M" AS pcte12grad2m,
    "PCTE12GRADUN" AS pcte12gradun,
    "PCTE12GRADNR" AS pcte12gradnr,
    "PCTE12GRADW" AS pcte12gradw,
    CAST("PCTE12DEEXC" AS BIGINT) AS pcte12deexc,
    CAST("PCTE12DESOM" AS BIGINT) AS pcte12desom,
    CAST("PCTE12DENON" AS BIGINT) AS pcte12denon,
    "PCTE12UGDEEXC" AS pcte12ugdeexc,
    "PCTE12UGDESOM" AS pcte12ugdesom,
    "PCTE12UGDENON" AS pcte12ugdenon,
    "PCTE12GRADDEEXC" AS pcte12graddeexc,
    "PCTE12GRADDESOM" AS pcte12graddesom,
    "PCTE12GRADDENON" AS pcte12graddenon,
    "year"
FROM "nces-ipeds-drvef12"
