-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("UNITID" AS BIGINT) AS unitid,
    CAST("PSGRTYPE" AS BIGINT) AS psgrtype,
    "XPGREVCT" AS xpgrevct,
    CAST("PGREVCT" AS BIGINT) AS pgrevct,
    "XPGEXCLU" AS xpgexclu,
    CAST("PGEXCLU" AS BIGINT) AS pgexclu,
    "XPGADJCT" AS xpgadjct,
    CAST("PGADJCT" AS BIGINT) AS pgadjct,
    "XPGCMBAC" AS xpgcmbac,
    "PGCMBAC" AS pgcmbac,
    "XPGCMOBA" AS xpgcmoba,
    "PGCMOBA" AS pgcmoba,
    "XPGCMTOT" AS xpgcmtot,
    CAST("PGCMTOT" AS BIGINT) AS pgcmtot,
    "XSSREVCT" AS xssrevct,
    CAST("SSREVCT" AS BIGINT) AS ssrevct,
    "XSSEXCLU" AS xssexclu,
    CAST("SSEXCLU" AS BIGINT) AS ssexclu,
    "XSSADJCT" AS xssadjct,
    CAST("SSADJCT" AS BIGINT) AS ssadjct,
    "XSSCMBAC" AS xsscmbac,
    "SSCMBAC" AS sscmbac,
    "XSSCMOBA" AS xsscmoba,
    "SSCMOBA" AS sscmoba,
    "XSSCMTOT" AS xsscmtot,
    CAST("SSCMTOT" AS BIGINT) AS sscmtot,
    "XNRREVCT" AS xnrrevct,
    CAST("NRREVCT" AS BIGINT) AS nrrevct,
    "XNREXCLU" AS xnrexclu,
    CAST("NREXCLU" AS BIGINT) AS nrexclu,
    "XNRADJCT" AS xnradjct,
    CAST("NRADJCT" AS BIGINT) AS nradjct,
    "XNRCMBAC" AS xnrcmbac,
    "NRCMBAC" AS nrcmbac,
    "XNRCMOBA" AS xnrcmoba,
    "NRCMOBA" AS nrcmoba,
    "XNRCMTOT" AS xnrcmtot,
    CAST("NRCMTOT" AS BIGINT) AS nrcmtot,
    "XTTREVCT" AS xttrevct,
    CAST("TTREVCT" AS BIGINT) AS ttrevct,
    "XTTEXCLU" AS xttexclu,
    CAST("TTEXCLU" AS BIGINT) AS ttexclu,
    "XTTADJCT" AS xttadjct,
    CAST("TTADJCT" AS BIGINT) AS ttadjct,
    "XTTCMBAC" AS xttcmbac,
    "TTCMBAC" AS ttcmbac,
    "XTTCMOBA" AS xttcmoba,
    "TTCMOBA" AS ttcmoba,
    "XTTCMTOT" AS xttcmtot,
    CAST("TTCMTOT" AS BIGINT) AS ttcmtot,
    "year"
FROM "nces-ipeds-gr-pell-ssl"
