-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("UNITID" AS BIGINT) AS unitid,
    "XEYTOTLT" AS xeytotlt,
    CAST("EFYTOTLT" AS BIGINT) AS efytotlt,
    "XEYTOTLM" AS xeytotlm,
    CAST("EFYTOTLM" AS BIGINT) AS efytotlm,
    "XEYTOTLW" AS xeytotlw,
    CAST("EFYTOTLW" AS BIGINT) AS efytotlw,
    "XEFYAIAT" AS xefyaiat,
    CAST("EFYAIANT" AS BIGINT) AS efyaiant,
    "XEFYAIAM" AS xefyaiam,
    CAST("EFYAIANM" AS BIGINT) AS efyaianm,
    "XEFYAIAW" AS xefyaiaw,
    CAST("EFYAIANW" AS BIGINT) AS efyaianw,
    "XEFYASIT" AS xefyasit,
    CAST("EFYASIAT" AS BIGINT) AS efyasiat,
    "XEFYASIM" AS xefyasim,
    CAST("EFYASIAM" AS BIGINT) AS efyasiam,
    "XEFYASIW" AS xefyasiw,
    CAST("EFYASIAW" AS BIGINT) AS efyasiaw,
    "XEFYBKAT" AS xefybkat,
    CAST("EFYBKAAT" AS BIGINT) AS efybkaat,
    "XEFYBKAM" AS xefybkam,
    CAST("EFYBKAAM" AS BIGINT) AS efybkaam,
    "XEFYBKAW" AS xefybkaw,
    CAST("EFYBKAAW" AS BIGINT) AS efybkaaw,
    "XEFYHIST" AS xefyhist,
    CAST("EFYHISPT" AS BIGINT) AS efyhispt,
    "XEFYHISM" AS xefyhism,
    CAST("EFYHISPM" AS BIGINT) AS efyhispm,
    "XEFYHISW" AS xefyhisw,
    CAST("EFYHISPW" AS BIGINT) AS efyhispw,
    "XEFYNHPT" AS xefynhpt,
    CAST("EFYNHPIT" AS BIGINT) AS efynhpit,
    "XEFYNHPM" AS xefynhpm,
    CAST("EFYNHPIM" AS BIGINT) AS efynhpim,
    "XEFYNHPW" AS xefynhpw,
    CAST("EFYNHPIW" AS BIGINT) AS efynhpiw,
    "XEFYWHIT" AS xefywhit,
    CAST("EFYWHITT" AS BIGINT) AS efywhitt,
    "XEFYWHIM" AS xefywhim,
    CAST("EFYWHITM" AS BIGINT) AS efywhitm,
    "XEFYWHIW" AS xefywhiw,
    CAST("EFYWHITW" AS BIGINT) AS efywhitw,
    "XEFY2MOT" AS xefy2mot,
    CAST("EFY2MORT" AS BIGINT) AS efy2mort,
    "XEFY2MOM" AS xefy2mom,
    CAST("EFY2MORM" AS BIGINT) AS efy2morm,
    "XEFY2MOW" AS xefy2mow,
    CAST("EFY2MORW" AS BIGINT) AS efy2morw,
    "XEYUNKNT" AS xeyunknt,
    CAST("EFYUNKNT" AS BIGINT) AS efyunknt,
    "XEYUNKNM" AS xeyunknm,
    CAST("EFYUNKNM" AS BIGINT) AS efyunknm,
    "XEYUNKNW" AS xeyunknw,
    CAST("EFYUNKNW" AS BIGINT) AS efyunknw,
    "XEYNRALT" AS xeynralt,
    CAST("EFYNRALT" AS BIGINT) AS efynralt,
    "XEYNRALM" AS xeynralm,
    CAST("EFYNRALM" AS BIGINT) AS efynralm,
    "XEYNRALW" AS xeynralw,
    CAST("EFYNRALW" AS BIGINT) AS efynralw,
    "year"
FROM "nces-ipeds-effy-hs"
