-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("UNITID" AS BIGINT) AS unitid,
    CAST("ARANK" AS BIGINT) AS arank,
    "XSAINSTT" AS xsainstt,
    "SAINSTT" AS sainstt,
    "XSAINSTM" AS xsainstm,
    "SAINSTM" AS sainstm,
    "XSAINSTW" AS xsainstw,
    "SAINSTW" AS sainstw,
    "XSA_9MCT" AS xsa_9mct,
    "SA_9MCT" AS sa_9mct,
    "XSA_9MCM" AS xsa_9mcm,
    "SA_9MCM" AS sa_9mcm,
    "XSA_9MCW" AS xsa_9mcw,
    "SA_9MCW" AS sa_9mcw,
    "XSATOTLT" AS xsatotlt,
    CAST("SATOTLT" AS BIGINT) AS satotlt,
    "XSATOTLM" AS xsatotlm,
    CAST("SATOTLM" AS BIGINT) AS satotlm,
    "XSATOTLW" AS xsatotlw,
    CAST("SATOTLW" AS BIGINT) AS satotlw,
    "XSA09MCT" AS xsa09mct,
    "SA09MCT" AS sa09mct,
    "XSA09MCM" AS xsa09mcm,
    "SA09MCM" AS sa09mcm,
    "XSA09MCW" AS xsa09mcw,
    "SA09MCW" AS sa09mcw,
    "XSA10MCT" AS xsa10mct,
    "SA10MCT" AS sa10mct,
    "XSA10MCM" AS xsa10mcm,
    "SA10MCM" AS sa10mcm,
    "XSA10MCW" AS xsa10mcw,
    "SA10MCW" AS sa10mcw,
    "XSA11MCT" AS xsa11mct,
    "SA11MCT" AS sa11mct,
    "XSA11MCM" AS xsa11mcm,
    "SA11MCM" AS sa11mcm,
    "XSA11MCW" AS xsa11mcw,
    "SA11MCW" AS sa11mcw,
    "XSA12MCT" AS xsa12mct,
    "SA12MCT" AS sa12mct,
    "XSA12MCM" AS xsa12mcm,
    "SA12MCM" AS sa12mcm,
    "XSA12MCW" AS xsa12mcw,
    "SA12MCW" AS sa12mcw,
    "XSAOUTLT" AS xsaoutlt,
    CAST("SAOUTLT" AS BIGINT) AS saoutlt,
    "XSAOUTLM" AS xsaoutlm,
    CAST("SAOUTLM" AS BIGINT) AS saoutlm,
    "XSAOUTLW" AS xsaoutlw,
    CAST("SAOUTLW" AS BIGINT) AS saoutlw,
    "XSA09MOT" AS xsa09mot,
    "SA09MOT" AS sa09mot,
    "XSA09MOM" AS xsa09mom,
    "SA09MOM" AS sa09mom,
    "XSA09MOW" AS xsa09mow,
    "SA09MOW" AS sa09mow,
    "XSA10MOT" AS xsa10mot,
    "SA10MOT" AS sa10mot,
    "XSA10MOM" AS xsa10mom,
    "SA10MOM" AS sa10mom,
    "XSA10MOW" AS xsa10mow,
    "SA10MOW" AS sa10mow,
    "XSA11MOT" AS xsa11mot,
    "SA11MOT" AS sa11mot,
    "XSA11MOM" AS xsa11mom,
    "SA11MOM" AS sa11mom,
    "XSA11MOW" AS xsa11mow,
    "SA11MOW" AS sa11mow,
    "XSA12MOT" AS xsa12mot,
    "SA12MOT" AS sa12mot,
    "XSA12MOM" AS xsa12mom,
    "SA12MOM" AS sa12mom,
    "XSA12MOW" AS xsa12mow,
    "SA12MOW" AS sa12mow,
    "XSAEQ9OT" AS xsaeq9ot,
    "SAEQ9OT" AS saeq9ot,
    "XSAEQ9OM" AS xsaeq9om,
    "SAEQ9OM" AS saeq9om,
    "XSAEQ9OW" AS xsaeq9ow,
    "SAEQ9OW" AS saeq9ow,
    "XSAEQ9AT" AS xsaeq9at,
    "SAEQ9AT" AS saeq9at,
    "XSAEQ9AM" AS xsaeq9am,
    "SAEQ9AM" AS saeq9am,
    "XSAEQ9AW" AS xsaeq9aw,
    "SAEQ9AW" AS saeq9aw,
    "XSA09MAT" AS xsa09mat,
    "SA09MAT" AS sa09mat,
    "XSA09MAM" AS xsa09mam,
    "SA09MAM" AS sa09mam,
    "XSA09MAW" AS xsa09maw,
    "SA09MAW" AS sa09maw,
    "XSA10MAT" AS xsa10mat,
    "SA10MAT" AS sa10mat,
    "XSA10MAM" AS xsa10mam,
    "SA10MAM" AS sa10mam,
    "XSA10MAW" AS xsa10maw,
    "SA10MAW" AS sa10maw,
    "XSA11MAT" AS xsa11mat,
    "SA11MAT" AS sa11mat,
    "XSA11MAM" AS xsa11mam,
    "SA11MAM" AS sa11mam,
    "XSA11MAW" AS xsa11maw,
    "SA11MAW" AS sa11maw,
    "XSA12MAT" AS xsa12mat,
    "SA12MAT" AS sa12mat,
    "XSA12MAM" AS xsa12mam,
    "SA12MAM" AS sa12mam,
    "XSA12MAW" AS xsa12maw,
    "SA12MAW" AS sa12maw,
    "year"
FROM "nces-ipeds-sal-is"
