-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("UNITID" AS BIGINT) AS unitid,
    "XCSTOTLT" AS xcstotlt,
    CAST("CSTOTLT" AS BIGINT) AS cstotlt,
    "XCSTOTLM" AS xcstotlm,
    CAST("CSTOTLM" AS BIGINT) AS cstotlm,
    "XCSTOTLW" AS xcstotlw,
    CAST("CSTOTLW" AS BIGINT) AS cstotlw,
    "XCSAIANT" AS xcsaiant,
    CAST("CSAIANT" AS BIGINT) AS csaiant,
    "XCSAIANM" AS xcsaianm,
    CAST("CSAIANM" AS BIGINT) AS csaianm,
    "XCSAIANW" AS xcsaianw,
    CAST("CSAIANW" AS BIGINT) AS csaianw,
    "XCSASIAT" AS xcsasiat,
    CAST("CSASIAT" AS BIGINT) AS csasiat,
    "XCSASIAM" AS xcsasiam,
    CAST("CSASIAM" AS BIGINT) AS csasiam,
    "XCSASIAW" AS xcsasiaw,
    CAST("CSASIAW" AS BIGINT) AS csasiaw,
    "XCSBKAAT" AS xcsbkaat,
    CAST("CSBKAAT" AS BIGINT) AS csbkaat,
    "XCSBKAAM" AS xcsbkaam,
    CAST("CSBKAAM" AS BIGINT) AS csbkaam,
    "XCSBKAAW" AS xcsbkaaw,
    CAST("CSBKAAW" AS BIGINT) AS csbkaaw,
    "XCSHISPT" AS xcshispt,
    CAST("CSHISPT" AS BIGINT) AS cshispt,
    "XCSHISPM" AS xcshispm,
    CAST("CSHISPM" AS BIGINT) AS cshispm,
    "XCSHISPW" AS xcshispw,
    CAST("CSHISPW" AS BIGINT) AS cshispw,
    "XCSNHPIT" AS xcsnhpit,
    CAST("CSNHPIT" AS BIGINT) AS csnhpit,
    "XCSNHPIM" AS xcsnhpim,
    CAST("CSNHPIM" AS BIGINT) AS csnhpim,
    "XCSNHPIW" AS xcsnhpiw,
    CAST("CSNHPIW" AS BIGINT) AS csnhpiw,
    "XCSWHITT" AS xcswhitt,
    CAST("CSWHITT" AS BIGINT) AS cswhitt,
    "XCSWHITM" AS xcswhitm,
    CAST("CSWHITM" AS BIGINT) AS cswhitm,
    "XCSWHITW" AS xcswhitw,
    CAST("CSWHITW" AS BIGINT) AS cswhitw,
    "XCS2MORT" AS xcs2mort,
    CAST("CS2MORT" AS BIGINT) AS cs2mort,
    "XCS2MORM" AS xcs2morm,
    CAST("CS2MORM" AS BIGINT) AS cs2morm,
    "XCS2MORW" AS xcs2morw,
    CAST("CS2MORW" AS BIGINT) AS cs2morw,
    "XCSUNKNT" AS xcsunknt,
    CAST("CSUNKNT" AS BIGINT) AS csunknt,
    "XCSUNKNM" AS xcsunknm,
    CAST("CSUNKNM" AS BIGINT) AS csunknm,
    "XCSUNKNW" AS xcsunknw,
    CAST("CSUNKNW" AS BIGINT) AS csunknw,
    "XCSNRALT" AS xcsnralt,
    CAST("CSNRALT" AS BIGINT) AS csnralt,
    "XCSNRALM" AS xcsnralm,
    CAST("CSNRALM" AS BIGINT) AS csnralm,
    "XCSNRALW" AS xcsnralw,
    CAST("CSNRALW" AS BIGINT) AS csnralw,
    "XCSGUUGU" AS xcsguugu,
    "CSGUUGUN" AS csguugun,
    "XCSGUUGA" AS xcsguuga,
    "CSGUUGAG" AS csguugag,
    "XCSGUUGT" AS xcsguugt,
    "CSGUUGTT" AS csguugtt,
    "XCSGUGUN" AS xcsgugun,
    "CSGUGUN" AS csgugun,
    "XCSGUGAG" AS xcsgugag,
    "CSGUGAG" AS csgugag,
    "XCSGUGTT" AS xcsgugtt,
    "CSGUGTOT" AS csgugtot,
    "XCSGUTTUN" AS xcsguttun,
    "CSGUTOTUN" AS csgutotun,
    "XCSGUTTAG" AS xcsguttag,
    "CSGUTOTAG" AS csgutotag,
    "XCSGUTOT" AS xcsgutot,
    "CSGUTOT" AS csgutot,
    "XCSGUKN" AS xcsgukn,
    "CSGUKN" AS csgukn,
    "year"
FROM "nces-ipeds-c-b"
