-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "SectorBranchesSIC2008" AS sectorbranchessic2008,
    "Periods" AS periods,
    "Employee_1" AS employee_1,
    "EmployedPerson_2" AS employedperson_2,
    "Employee_3" AS employee_3,
    "EmployedPerson_4" AS employedperson_4,
    "Total_5" AS total_5,
    "NetTurnover_6" AS netturnover_6,
    "OtherRevenues_7" AS otherrevenues_7,
    "Total_8" AS total_8,
    "Total_9" AS total_9,
    "Total_10" AS total_10,
    "InitialStockOfRawAndAuxiliaryMater_11" AS initialstockofrawandauxiliarymater_11,
    "PurchasedRawAndAuxiliaryMaterials_12" AS purchasedrawandauxiliarymaterials_12,
    "ClosingStockRawAndAuxiliaryMat_13" AS closingstockrawandauxiliarymat_13,
    "Total_14" AS total_14,
    "InitialStockOfCommodities_15" AS initialstockofcommodities_15,
    "PurchasedCommodities_16" AS purchasedcommodities_16,
    "ClosingStockOfCommodities_17" AS closingstockofcommodities_17,
    "PaymentsToSubcontractors_18" AS paymentstosubcontractors_18,
    "PurchaseValueNotElsewhereClassified_19" AS purchasevaluenotelsewhereclassified_19,
    "Total_20" AS total_20,
    "GrossWagesAndSalaries_21" AS grosswagesandsalaries_21,
    "Total_22" AS total_22,
    "EmployerPaidSocialInsurancePremiums_23" AS employerpaidsocialinsurancepremiums_23,
    "OtherSocialInsuranceCosts_24" AS othersocialinsurancecosts_24,
    "PensionAndEarlyRetirementPremiums_25" AS pensionandearlyretirementpremiums_25,
    "OtherPersonnelCosts_26" AS otherpersonnelcosts_26,
    "Total_27" AS total_27,
    "CostsOfEnergyUse_28" AS costsofenergyuse_28,
    "HousingCosts_29" AS housingcosts_29,
    "EquipmentAndInventoryCosts_30" AS equipmentandinventorycosts_30,
    "TransportCosts_31" AS transportcosts_31,
    "SalesCosts_32" AS salescosts_32,
    "CommunicationCosts_33" AS communicationcosts_33,
    "CostsOfOtherServices_34" AS costsofotherservices_34,
    "OtherLiabilities_35" AS otherliabilities_35,
    "DepreciationFixedAssets_36" AS depreciationfixedassets_36,
    "OperatingResults_37" AS operatingresults_37,
    "NetFinancialIncome_38" AS netfinancialincome_38,
    "BalanceOfProvisions_39" AS balanceofprovisions_39,
    "NetExtraordinaryIncome_40" AS netextraordinaryincome_40,
    "PreTaxResults_41" AS pretaxresults_41,
    "SectorBranchesSIC2008_label" AS sectorbranchessic2008_label,
    "Periods_label" AS periods_label
FROM "cbs-netherlands-81156eng"
