-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "RegioS" AS regios,
    "Perioden" AS perioden,
    "TotaleOppervlakte_1" AS totaleoppervlakte_1,
    "TotaalVerkeersterrein_2" AS totaalverkeersterrein_2,
    "Spoorterrein_3" AS spoorterrein_3,
    "Wegverkeersterrein_4" AS wegverkeersterrein_4,
    "Vliegveld_5" AS vliegveld_5,
    "TotaalBebouwdTerrein_6" AS totaalbebouwdterrein_6,
    "Woonterrein_7" AS woonterrein_7,
    "TerreinVoorDetailhandelEnHoreca_8" AS terreinvoordetailhandelenhoreca_8,
    "TerreinVoorOpenbareVoorzieningen_9" AS terreinvooropenbarevoorzieningen_9,
    "TerreinVoorSociaalCultureleVoorz_10" AS terreinvoorsociaalculturelevoorz_10,
    "Bedrijventerrein_11" AS bedrijventerrein_11,
    "TotaalSemiBebouwdTerrein_12" AS totaalsemibebouwdterrein_12,
    "Stortplaats_13" AS stortplaats_13,
    "Wrakkenopslagplaats_14" AS wrakkenopslagplaats_14,
    "Begraafplaats_15" AS begraafplaats_15,
    "Delfstofwinplaats_16" AS delfstofwinplaats_16,
    "Bouwterrein_17" AS bouwterrein_17,
    "SemiVerhardOverigTerrein_18" AS semiverhardoverigterrein_18,
    "TotaalRecreatieterrein_19" AS totaalrecreatieterrein_19,
    "ParkEnPlantsoen_20" AS parkenplantsoen_20,
    "Sportterrein_21" AS sportterrein_21,
    "Volkstuin_22" AS volkstuin_22,
    "DagrecreatiefTerrein_23" AS dagrecreatiefterrein_23,
    "VerblijfsrecreatiefTerrein_24" AS verblijfsrecreatiefterrein_24,
    "TotaalAgrarischTerrein_25" AS totaalagrarischterrein_25,
    "TerreinVoorGlastuinbouw_26" AS terreinvoorglastuinbouw_26,
    "OverigAgrarischTerrein_27" AS overigagrarischterrein_27,
    "TotaalBosEnOpenNatuurlijkTerrein_28" AS totaalbosenopennatuurlijkterrein_28,
    "Bos_29" AS bos_29,
    "OpenDroogNatuurlijkTerrein_30" AS opendroognatuurlijkterrein_30,
    "OpenNatNatuurlijkTerrein_31" AS opennatnatuurlijkterrein_31,
    "TotaalBinnenwater_32" AS totaalbinnenwater_32,
    "IJsselmeerMarkermeer_33" AS ijsselmeermarkermeer_33,
    "AfgeslotenZeearm_34" AS afgeslotenzeearm_34,
    "RijnEnMaas_35" AS rijnenmaas_35,
    "Randmeer_36" AS randmeer_36,
    "Spaarbekken_37" AS spaarbekken_37,
    "RecreatiefBinnenwater_38" AS recreatiefbinnenwater_38,
    "BinnenwaterVoorDelfstofwinning_39" AS binnenwatervoordelfstofwinning_39,
    "VloeiEnOfSlibveld_40" AS vloeienofslibveld_40,
    "OverigBinnenwater_41" AS overigbinnenwater_41,
    "TotaalBuitenwater_42" AS totaalbuitenwater_42,
    "WaddenzeeEemsDollard_43" AS waddenzeeeemsdollard_43,
    "Oosterschelde_44" AS oosterschelde_44,
    "Westerschelde_45" AS westerschelde_45,
    "Noordzee_46" AS noordzee_46,
    "RegioS_label" AS regios_label,
    "Perioden_label" AS perioden_label
FROM "cbs-netherlands-70262ned"
