-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "Perioden" AS perioden,
    "TotaalBedrijfsopbrengsten_1" AS totaalbedrijfsopbrengsten_1,
    "NettoOmzet_2" AS nettoomzet_2,
    "TotaalOverigeBedrijfsopbrengsten_3" AS totaaloverigebedrijfsopbrengsten_3,
    "Subsidies_4" AS subsidies_4,
    "NietEerderGenoemdeBedrijfsopbrengsten_5" AS nieteerdergenoemdebedrijfsopbrengsten_5,
    "TotaalBedrijfskosten_6" AS totaalbedrijfskosten_6,
    "TotaalArbeidskosten_7" AS totaalarbeidskosten_7,
    "LonenEnSalarissen_8" AS lonenensalarissen_8,
    "Pensioenlasten_9" AS pensioenlasten_9,
    "SocialeLasten_10" AS socialelasten_10,
    "AfschrijvingenOpVasteActiva_11" AS afschrijvingenopvasteactiva_11,
    "TotaalOverigeBedrijfskosten_12" AS totaaloverigebedrijfskosten_12,
    "TotaalOverigePersoneelskosten_13" AS totaaloverigepersoneelskosten_13,
    "KostenUitzendkrachtenEnOverigeInleen_14" AS kostenuitzendkrachtenenoverigeinleen_14,
    "NietEerderGenoemdePersoneelskosten_15" AS nieteerdergenoemdepersoneelskosten_15,
    "NietEerderGenoemdeBedrijfskosten_16" AS nieteerdergenoemdebedrijfskosten_16,
    "Bedrijfsresultaat_17" AS bedrijfsresultaat_17,
    "SaldoBijzWaardevermeerderingVermind_18" AS saldobijzwaardevermeerderingvermind_18,
    "FinancieelResultaat_19" AS financieelresultaat_19,
    "VrijvalVoorzieningen_20" AS vrijvalvoorzieningen_20,
    "ToevoegingenVoorzieningen_21" AS toevoegingenvoorzieningen_21,
    "SaldoVoorzieningen_22" AS saldovoorzieningen_22,
    "IncidenteelResultaat_23" AS incidenteelresultaat_23,
    "ResultaatVoorBelastingen_24" AS resultaatvoorbelastingen_24,
    "TotaalWerkzamePersonen_25" AS totaalwerkzamepersonen_25,
    "Werknemers_26" AS werknemers_26,
    "OverigeWerkzamePersonen_27" AS overigewerkzamepersonen_27,
    "TotaalArbeidsjarenWerkzamePersonen_28" AS totaalarbeidsjarenwerkzamepersonen_28,
    "ArbeidsjarenWerknemers_29" AS arbeidsjarenwerknemers_29,
    "ArbeidsjarenOverigeWerkzamePersonen_30" AS arbeidsjarenoverigewerkzamepersonen_30,
    "ArbodienstOfArbodeskundige_31" AS arbodienstofarbodeskundige_31,
    "ArboAdviesbureau_32" AS arboadviesbureau_32,
    "ReIntegratiebedrijf_33" AS reintegratiebedrijf_33,
    "Anders_34" AS anders_34,
    "TotaalNettoOmzet_35" AS totaalnettoomzet_35,
    "BedrijvenEnInstellingen_36" AS bedrijveneninstellingen_36,
    "Overheid_37" AS overheid_37,
    "Particulieren_38" AS particulieren_38,
    "PersonenBegeleidDoorReIntegratiebedr_39" AS personenbegeleiddoorreintegratiebedr_39,
    "Perioden_label" AS perioden_label
FROM "cbs-netherlands-81201ned"
