-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "Perioden" AS perioden,
    "TotaalHuwelijkssluitingen_1" AS totaalhuwelijkssluitingen_1,
    "HuwelijkssluitingenRelatief_2" AS huwelijkssluitingenrelatief_2,
    "TussenManEnVrouw_3" AS tussenmanenvrouw_3,
    "TussenMannen_4" AS tussenmannen_4,
    "TussenVrouwen_5" AS tussenvrouwen_5,
    "TotaalMannen_6" AS totaalmannen_6,
    "Ongehuwd_7" AS ongehuwd_7,
    "Partnerschap_8" AS partnerschap_8,
    "Verweduwd_9" AS verweduwd_9,
    "Gescheiden_10" AS gescheiden_10,
    "TotaalVrouwen_11" AS totaalvrouwen_11,
    "Ongehuwd_12" AS ongehuwd_12,
    "Partnerschap_13" AS partnerschap_13,
    "Verweduwd_14" AS verweduwd_14,
    "Gescheiden_15" AS gescheiden_15,
    "TotaalMannen_16" AS totaalmannen_16,
    "Ongehuwd_17" AS ongehuwd_17,
    "Partnerschap_18" AS partnerschap_18,
    "Verweduwd_19" AS verweduwd_19,
    "Gescheiden_20" AS gescheiden_20,
    "TotaalVrouwen_21" AS totaalvrouwen_21,
    "Ongehuwd_22" AS ongehuwd_22,
    "Partnerschap_23" AS partnerschap_23,
    "Verweduwd_24" AS verweduwd_24,
    "Gescheiden_25" AS gescheiden_25,
    "TotaalMannen_26" AS totaalmannen_26,
    "Ongehuwd_27" AS ongehuwd_27,
    "Partnerschap_28" AS partnerschap_28,
    "Verweduwd_29" AS verweduwd_29,
    "Gescheiden_30" AS gescheiden_30,
    "TotaalVrouwen_31" AS totaalvrouwen_31,
    "Ongehuwd_32" AS ongehuwd_32,
    "Partnerschap_33" AS partnerschap_33,
    "Verweduwd_34" AS verweduwd_34,
    "Gescheiden_35" AS gescheiden_35,
    "TotaalAantalHuwelijken_36" AS totaalaantalhuwelijken_36,
    "EenHuwelijken_37" AS eenhuwelijken_37,
    "TweeOfMeerHuwelijken_38" AS tweeofmeerhuwelijken_38,
    "TotaalAantalHuwelijken_39" AS totaalaantalhuwelijken_39,
    "EenHuwelijken_40" AS eenhuwelijken_40,
    "TweeOfMeerHuwelijken_41" AS tweeofmeerhuwelijken_41,
    "TotaalPartnerschapsregistraties_42" AS totaalpartnerschapsregistraties_42,
    "TotaalPartnerschapsregistratiesRela_43" AS totaalpartnerschapsregistratiesrela_43,
    "TussenManEnVrouw_44" AS tussenmanenvrouw_44,
    "TussenMannen_45" AS tussenmannen_45,
    "TussenVrouwen_46" AS tussenvrouwen_46,
    "TotaalNieuwGeslotenPartnerschappen_47" AS totaalnieuwgeslotenpartnerschappen_47,
    "TussenManEnVrouw_48" AS tussenmanenvrouw_48,
    "TussenMannen_49" AS tussenmannen_49,
    "TussenVrouwen_50" AS tussenvrouwen_50,
    "TotaalHuwelijkenOmgezetInPartners_51" AS totaalhuwelijkenomgezetinpartners_51,
    "TussenManEnVrouw_52" AS tussenmanenvrouw_52,
    "TussenMannen_53" AS tussenmannen_53,
    "TussenVrouwen_54" AS tussenvrouwen_54,
    "Perioden_label" AS perioden_label
FROM "cbs-netherlands-37772ned"
