-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "BedrijfsklassenSBI2008" AS bedrijfsklassensbi2008,
    "Perioden" AS perioden,
    "TotaalBedrijfsopbrengsten_1" AS totaalbedrijfsopbrengsten_1,
    "NettoOmzet_2" AS nettoomzet_2,
    "TotaalOverigeBedrijfsopbrengsten_3" AS totaaloverigebedrijfsopbrengsten_3,
    "Subsidies_4" AS subsidies_4,
    "NietEerderGenoemdeBedrijfsopbrengsten_5" AS nieteerdergenoemdebedrijfsopbrengsten_5,
    "TotaalBedrijfskosten_6" AS totaalbedrijfskosten_6,
    "TotaalArbeidskosten_7" AS totaalarbeidskosten_7,
    "LonenEnSalarissen_8" AS lonenensalarissen_8,
    "Pensioenlasten_9" AS pensioenlasten_9,
    "SocialeLasten_10" AS socialelasten_10,
    "AfschrijvingenOpVasteActiva_11" AS afschrijvingenopvasteactiva_11,
    "TotaalOverigeBedrijfskosten_12" AS totaaloverigebedrijfskosten_12,
    "TotaalOverigePersoneelskosten_13" AS totaaloverigepersoneelskosten_13,
    "KostenUitzendkrachtenEnOverigeInleen_14" AS kostenuitzendkrachtenenoverigeinleen_14,
    "NietEerderGenoemdePersoneelskosten_15" AS nieteerdergenoemdepersoneelskosten_15,
    "NietEerderGenoemdeBedrijfskosten_16" AS nieteerdergenoemdebedrijfskosten_16,
    "Bedrijfsresultaat_17" AS bedrijfsresultaat_17,
    "SaldoBijzWaardevermeerderingVermind_18" AS saldobijzwaardevermeerderingvermind_18,
    "FinancieelResultaat_19" AS financieelresultaat_19,
    "VrijvalVoorzieningen_20" AS vrijvalvoorzieningen_20,
    "ToevoegingenVoorzieningen_21" AS toevoegingenvoorzieningen_21,
    "SaldoVoorzieningen_22" AS saldovoorzieningen_22,
    "IncidenteelResultaat_23" AS incidenteelresultaat_23,
    "ResultaatVoorBelastingen_24" AS resultaatvoorbelastingen_24,
    "TotaalWerkzamePersonen_25" AS totaalwerkzamepersonen_25,
    "Werknemers_26" AS werknemers_26,
    "OverigeWerkzamePersonen_27" AS overigewerkzamepersonen_27,
    "TotaalArbeidsjarenWerkzamePersonen_28" AS totaalarbeidsjarenwerkzamepersonen_28,
    "ArbeidsjarenWerknemers_29" AS arbeidsjarenwerknemers_29,
    "ArbeidsjarenOverigeWerkzamePersonen_30" AS arbeidsjarenoverigewerkzamepersonen_30,
    "Vrijwilligers_31" AS vrijwilligers_31,
    "TotaalBedrijvenNaarActiviteit_32" AS totaalbedrijvennaaractiviteit_32,
    "Peuteropvang_33" AS peuteropvang_33,
    "Kinderdagopvang_34" AS kinderdagopvang_34,
    "BuitenEnNaschoolseOpvang_35" AS buitenennaschoolseopvang_35,
    "Gastouderopvang_36" AS gastouderopvang_36,
    "WelzijnswerkVoorOuderen_37" AS welzijnswerkvoorouderen_37,
    "LokaalWelzijnswerk_38" AS lokaalwelzijnswerk_38,
    "MaatschappelijkWerk_39" AS maatschappelijkwerk_39,
    "OverigeActiviteiten_40" AS overigeactiviteiten_40,
    "BeschikbarePlaatsen_41" AS beschikbareplaatsen_41,
    "GeplaatstePeuters_42" AS geplaatstepeuters_42,
    "BeschikbarePlaatsen_43" AS beschikbareplaatsen_43,
    "GeplaatsteKinderen_44" AS geplaatstekinderen_44,
    "BeschikbarePlaatsen_45" AS beschikbareplaatsen_45,
    "GeplaatsteKinderen_46" AS geplaatstekinderen_46,
    "KindkoppelingenGastouderbureaus_47" AS kindkoppelingengastouderbureaus_47,
    "BedrijfsklassenSBI2008_label" AS bedrijfsklassensbi2008_label,
    "Perioden_label" AS perioden_label
FROM "cbs-netherlands-81278ned"
