-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "Periods" AS periods,
    "TotalMarriages_1" AS totalmarriages_1,
    "MarriagesRelative_2" AS marriagesrelative_2,
    "BetweenManAndWoman_3" AS betweenmanandwoman_3,
    "BetweenMen_4" AS betweenmen_4,
    "BetweenWomen_5" AS betweenwomen_5,
    "TotalMen_6" AS totalmen_6,
    "NeverMarried_7" AS nevermarried_7,
    "Partnership_8" AS partnership_8,
    "Widowed_9" AS widowed_9,
    "Divorced_10" AS divorced_10,
    "TotalWomen_11" AS totalwomen_11,
    "NeverMarried_12" AS nevermarried_12,
    "Partnership_13" AS partnership_13,
    "Widowed_14" AS widowed_14,
    "Divorced_15" AS divorced_15,
    "TotalMen_16" AS totalmen_16,
    "NeverMarried_17" AS nevermarried_17,
    "Partnership_18" AS partnership_18,
    "Widowed_19" AS widowed_19,
    "Divorced_20" AS divorced_20,
    "TotalWomen_21" AS totalwomen_21,
    "NeverMarried_22" AS nevermarried_22,
    "Partnership_23" AS partnership_23,
    "Widowed_24" AS widowed_24,
    "Divorced_25" AS divorced_25,
    "TotalMen_26" AS totalmen_26,
    "NeverMarried_27" AS nevermarried_27,
    "Partnership_28" AS partnership_28,
    "Widowed_29" AS widowed_29,
    "Divorced_30" AS divorced_30,
    "TotalWomen_31" AS totalwomen_31,
    "NeverMarried_32" AS nevermarried_32,
    "Partnership_33" AS partnership_33,
    "Widowed_34" AS widowed_34,
    "Divorced_35" AS divorced_35,
    "TotalMarriages_36" AS totalmarriages_36,
    "OneMarriage_37" AS onemarriage_37,
    "TwoOrMoreMarriages_38" AS twoormoremarriages_38,
    "TotalMarriages_39" AS totalmarriages_39,
    "OneMarriage_40" AS onemarriage_40,
    "TwoOrMoreMarriages_41" AS twoormoremarriages_41,
    "TotalPartnershipRegistrations_42" AS totalpartnershipregistrations_42,
    "PartnershipRegistrationsRelative_43" AS partnershipregistrationsrelative_43,
    "BetweenManAndWoman_44" AS betweenmanandwoman_44,
    "BetweenMen_45" AS betweenmen_45,
    "BetweenWomen_46" AS betweenwomen_46,
    "TotalNewPartnershipRegistrations_47" AS totalnewpartnershipregistrations_47,
    "BetweenManAndWoman_48" AS betweenmanandwoman_48,
    "BetweenMen_49" AS betweenmen_49,
    "BetweenWomen_50" AS betweenwomen_50,
    "TotalMarriagesChangedIntoAPartne_51" AS totalmarriageschangedintoapartne_51,
    "BetweenManAndWoman_52" AS betweenmanandwoman_52,
    "BetweenMen_53" AS betweenmen_53,
    "BetweenWomen_54" AS betweenwomen_54,
    "Periods_label" AS periods_label
FROM "cbs-netherlands-37772eng"
