-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "projectid",
    "fuel",
    "startstate_province",
    "startprefecture_district",
    "endstate_province",
    "countriesorareas",
    "wiki",
    "pipelinename",
    "segmentname",
    "status",
    "owner",
    "parent",
    "ownerentityids",
    "proposalyear",
    "constructionyear",
    "diameter",
    "diameterunits",
    "startyear1",
    "startyear2",
    "startyear3",
    "cancelledyear",
    "delaytype",
    "stopyear",
    "shelvedyear",
    "capacity",
    "capacityunits",
    "capacityboed",
    "lengthknown",
    "lengthknownunits",
    "lengthknownkm",
    "lengthestimatekm",
    "lengthmergedkm",
    "fuelsource",
    "startlocation",
    "startcountryorarea",
    "startsubregion",
    "startregion",
    "endlocation",
    "endprefecture_district",
    "endcountryorarea",
    "costusd",
    "endregion",
    "costeuro",
    "otherlanguageprimarypipelinename",
    "endsubregion",
    "routetype",
    "routeaccuracy",
    "cost",
    "costunits",
    "lastupdated"
FROM "gem-global-energy-monitor-oil-pipeline-tracker"
