-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "gem_plant_id",
    "plant_name_english",
    "plant_name_other_language",
    "other_plant_names_english",
    "other_plant_names_other_language",
    "owner",
    "owner_other_language",
    "owner_gem_entity_id",
    "owner_permid",
    "soe_status",
    "parent_english",
    "parent_gem_entity_id",
    "parent_permid",
    "location_address",
    "location_address_other_language",
    "municipality",
    "subnational_unit",
    "country_area",
    "region",
    "coordinates",
    "coordinate_accuracy",
    "gem_wiki_page",
    "plant_age",
    "announced_date",
    "construction_date",
    "start_date",
    "pre_retirement_announcement_date",
    "idled_date",
    "retired_date",
    "ferronickel_capacity_ttpa",
    "sinter_plant_capacity_ttpa",
    "coking_plant_capacity_ttpa",
    "pelletizing_plant_capacity_ttpa",
    "category_steel_product",
    "steel_products",
    "steel_sector_end_users",
    "workforce_size",
    "iso_14001",
    "iso_50001",
    "responsiblesteel_certification",
    "main_production_equipment",
    "power_source",
    "iron_ore_source",
    "met_coal_source"
FROM "gem-global-energy-monitor-iron-steel-plant-tracker"
