-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "projectid",
    "unitid",
    "country_area",
    "wiki",
    "terminalname",
    "unitname",
    "facilitytype",
    "fuel",
    "status",
    "othernames",
    "localnames",
    "language",
    "owner",
    "owner_gem_entity_id",
    "parent",
    "parent_gem_entity_id",
    "parenthqcountry",
    "operator",
    "capacity",
    "capacityunits",
    "capacityinmtpa",
    "capacityinbcm_y",
    "totimportlngterminalcapacityinmtpa",
    "totimportlngterminalcapacityinbcm_y",
    "totexportlngterminalcapacityinmtpa",
    "totexportlngterminalcapacityinbcm_y",
    "proposalyear",
    "proposalmonth",
    "constructionyear",
    "constructionmonth",
    "originalplannedstartyear",
    "latestplannedstartyear",
    "actualstartyear",
    "actualstartmonth",
    "actualstartyear2",
    "actualstartyear3",
    "shelvedyear",
    "cancelledyear",
    "stopyear",
    "plannedstopyear",
    "shelvedcancelledstatustype",
    "tempfacility",
    CAST("importexportonly" AS BOOLEAN) AS importexportonly,
    "location",
    "region",
    "subregion",
    "prefecture_district",
    "state_province",
    "latitude",
    "longitude",
    "accuracy",
    "associatedterminals",
    "powerplantssupplied",
    "cost",
    "costunits",
    "costusd",
    "totknownterminalcostsusd",
    "fidstatus",
    "fidyear",
    "financing",
    CAST("offshore" AS BOOLEAN) AS offshore,
    CAST("floating" AS BOOLEAN) AS floating,
    "floatingvesselname",
    "vesselowner",
    "vesseloperator",
    CAST("lh2" AS BOOLEAN) AS lh2,
    CAST("nh3" AS BOOLEAN) AS nh3,
    CAST("syntheticlng" AS BOOLEAN) AS syntheticlng,
    CAST("retrofitproposed" AS BOOLEAN) AS retrofitproposed,
    CAST("altfuelprelimagreement" AS BOOLEAN) AS altfuelprelimagreement,
    CAST("altfuelcallmarketinterest" AS BOOLEAN) AS altfuelcallmarketinterest,
    CAST("ccs" AS BOOLEAN) AS ccs,
    "lastupdated"
FROM "gem-global-energy-monitor-lng-terminal-tracker"
