-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: This integrated registry intentionally overlaps technology-specific GEM trackers and no stable unique row grain was verified; avoid summing it together with the individual tracker tables without deduplication rules.
SELECT
    "type",
    "country_area",
    "subregion",
    "region",
    "plant_project_name",
    "unit_phase_name",
    "plant_project_name_local",
    "plant_project_name_other",
    "capacity_mw",
    "status",
    "start_year",
    "retired_year",
    "technology",
    "capacity_rating_solar_only",
    "associated_storage",
    "fuel_combustion_only",
    "fuel_classification_oil_gas_only",
    "equipment_manufacturer_model_oil_gas_only",
    "hydrogen_production",
    "hydrogen_capable",
    "data_center_ppa_geothermal_only",
    "country_area_1_hydropower_only",
    "country_area_2_hydropower_only",
    "country_area_1_capacity_mw_hydropower_only",
    "country_area_2_capacity_mw_hydropower_only",
    "river_watercourse_hydropower_only",
    "operator_s",
    "owner_s",
    "owner_s_gem_entity_id",
    "parent_s",
    "parent_s_gem_entity_id",
    "chp",
    "ccs",
    "conversion_replacement",
    "unit_conversion_year",
    "conversion_from_replacement_of_fuel",
    "conversion_from_replacement_of_gem_unit_id",
    "conversion_to_fuel",
    "conversion_to_gem_unit_id",
    "captive_industry_type",
    "captive_industry_use",
    "captive_non_industry_use",
    "latitude",
    "longitude",
    "location_accuracy",
    "city",
    "local_area_taluk_county",
    "major_area_prefecture_district",
    "subnational_unit_state_province",
    "gem_location_id",
    "gem_unit_phase_id",
    "gem_wiki_url"
FROM "gem-global-energy-monitor-integrated-power-tracker"
