-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "gem_unit_phase_id",
    "gem_location_id",
    "country_area",
    "wiki_url",
    "plant_name",
    "unit_name",
    "plant_name_other",
    "plant_name_local",
    "owner",
    "owner_gem_entity_id",
    "parent",
    "parent_gem_entity_id",
    "capacity_mw",
    "status",
    "start_year",
    "retired_year",
    "planned_retirement",
    "coal_phaseout_year",
    "net_zero_year",
    "combustion_technology",
    "coal_type",
    "coal_source",
    "conversion_to_fuel",
    "conversion_to_gem_unit_id",
    "alternate_fuel",
    "location",
    "local_area_taluk_county",
    "major_area_prefecture_district",
    "subnational_unit_province_state",
    "subregion",
    "region",
    "latitude",
    "longitude",
    "location_accuracy",
    "permits",
    "permit_date",
    "permit_parsed",
    "captive",
    "captive_industry_use",
    "captive_residential_use",
    "chp",
    "capacity_factor",
    "plant_age_years",
    "heat_rate_btu_per_kwh",
    "emission_factor_kg_of_co2_per_tj",
    "annual_co2_million_tonnes_annum",
    "remaining_plant_lifetime_years",
    "lifetime_co2_million_tonnes",
    "china_capacity_payment_recipient"
FROM "gem-global-energy-monitor-coal-plant-tracker"
