SELECT
    TRY_CAST("id" AS BIGINT) AS "id",
    TRY_CAST("date_created" AS TIMESTAMP) AS "date_created",
    TRY_CAST("date_modified" AS TIMESTAMP) AS "date_modified",
    TRY_CAST("date_completed" AS TIMESTAMP) AS "date_completed",
    TRY_CAST("fjc_id" AS BIGINT) AS "fjc_id",
    "slug",
    "name_first",
    "name_middle",
    "name_last",
    "name_suffix",
    TRY_CAST("date_dob" AS DATE) AS "date_dob",
    "date_granularity_dob",
    TRY_CAST("date_dod" AS DATE) AS "date_dod",
    "date_granularity_dod",
    "dob_city",
    "dob_state",
    "dob_country",
    "dod_city",
    "dod_state",
    "dod_country",
    "gender",
    "religion",
    "ftm_total_received",
    "ftm_eid",
    "has_photo",
    TRY_CAST("is_alias_of_id" AS BIGINT) AS "is_alias_of_id"
FROM "courtlistener-people-db-people"
