SELECT
    TRY_CAST("id" AS BIGINT) AS "id",
    TRY_CAST("date_created" AS TIMESTAMP) AS "date_created",
    TRY_CAST("date_modified" AS TIMESTAMP) AS "date_modified",
    "position_type",
    "job_title",
    "sector",
    "organization_name",
    "location_city",
    "location_state",
    TRY_CAST("date_nominated" AS DATE) AS "date_nominated",
    TRY_CAST("date_elected" AS DATE) AS "date_elected",
    TRY_CAST("date_recess_appointment" AS DATE) AS "date_recess_appointment",
    TRY_CAST("date_referred_to_judicial_committee" AS DATE) AS "date_referred_to_judicial_committee",
    TRY_CAST("date_judicial_committee_action" AS DATE) AS "date_judicial_committee_action",
    "judicial_committee_action",
    TRY_CAST("date_hearing" AS DATE) AS "date_hearing",
    TRY_CAST("date_confirmation" AS DATE) AS "date_confirmation",
    TRY_CAST("date_start" AS DATE) AS "date_start",
    "date_granularity_start",
    TRY_CAST("date_termination" AS DATE) AS "date_termination",
    "termination_reason",
    "date_granularity_termination",
    TRY_CAST("date_retirement" AS DATE) AS "date_retirement",
    "nomination_process",
    "vote_type",
    "voice_vote",
    TRY_CAST("votes_yes" AS BIGINT) AS "votes_yes",
    TRY_CAST("votes_no" AS BIGINT) AS "votes_no",
    TRY_CAST("votes_yes_percent" AS DOUBLE) AS "votes_yes_percent",
    TRY_CAST("votes_no_percent" AS DOUBLE) AS "votes_no_percent",
    "how_selected",
    "has_inferred_values",
    TRY_CAST("appointer_id" AS BIGINT) AS "appointer_id",
    "court_id",
    TRY_CAST("person_id" AS BIGINT) AS "person_id",
    TRY_CAST("predecessor_id" AS BIGINT) AS "predecessor_id",
    TRY_CAST("school_id" AS BIGINT) AS "school_id",
    TRY_CAST("supervisor_id" AS BIGINT) AS "supervisor_id"
FROM "courtlistener-people-db-positions"
