SELECT
    TRY_CAST("id" AS BIGINT) AS "id",
    TRY_CAST("date_created" AS TIMESTAMP) AS "date_created",
    TRY_CAST("date_modified" AS TIMESTAMP) AS "date_modified",
    "dataset_source",
    "office",
    "docket_number",
    "origin",
    TRY_CAST("date_filed" AS DATE) AS "date_filed",
    "jurisdiction",
    "nature_of_suit",
    "title",
    "section",
    "subsection",
    "diversity_of_residence",
    "class_action",
    TRY_CAST("monetary_demand" AS DOUBLE) AS "monetary_demand",
    "county_of_residence",
    "arbitration_at_filing",
    "arbitration_at_termination",
    "multidistrict_litigation_docket_number",
    "plaintiff",
    "defendant",
    TRY_CAST("date_transfer" AS DATE) AS "date_transfer",
    "transfer_office",
    "transfer_docket_number",
    "transfer_origin",
    TRY_CAST("date_terminated" AS DATE) AS "date_terminated",
    "termination_class_action_status",
    "procedural_progress",
    "disposition",
    "nature_of_judgement",
    TRY_CAST("amount_received" AS DOUBLE) AS "amount_received",
    "judgment",
    "pro_se",
    TRY_CAST("year_of_tape" AS BIGINT) AS "year_of_tape",
    "nature_of_offense",
    "version",
    "circuit_id",
    "district_id"
FROM "courtlistener-fjc-integrated-database"
