# Entity union for blockchain-com-charts — copied from
# data/sources/blockchain-com-charts/work/entity_union.json.
# Each id is a Blockchain.com Charts API slug; one published time series per slug.
ENTITY_IDS = [
    "avg-block-size",
    "avg-confirmation-time",
    "blocks-size",
    "cost-per-transaction",
    "cost-per-transaction-percent",
    "difficulty",
    "estimated-transaction-volume",
    "estimated-transaction-volume-usd",
    "hash-rate",
    "market-cap",
    "market-price",
    "median-confirmation-time",
    "mempool-count",
    "mempool-growth",
    "mempool-size",
    "miners-revenue",
    "my-wallet-n-users",
    "n-transactions",
    "n-transactions-excluding-popular",
    "n-transactions-per-block",
    "n-transactions-total",
    "n-unique-addresses",
    "output-volume",
    "total-bitcoins",
    "trade-volume",
    "transaction-fees",
    "transaction-fees-usd",
    "transactions-per-second",
    "utxo-count",
]
