SELECT
    TRY_CAST(obs_date AS TIMESTAMP)             AS obs_date,
    CAST(comet_id AS BIGINT)                    AS comet_id,
    comet_name,
    comet_fullname,
    comet_mpc_name,
    comet_icq_name,
    obs_type,
    observer_icq_name,
    observer_first_name,
    observer_last_name,
    observer_association,
    observer_country,
    TRY_CAST(magnitude AS DOUBLE)              AS magnitude,
    TRY_CAST(magnitude_error AS DOUBLE)        AS magnitude_error,
    comet_visibility,
    obs_method_key,
    obs_method_name,
    ref_catalog_key,
    TRY_CAST(instrument_aperture AS DOUBLE)    AS instrument_aperture,
    TRY_CAST(instrument_focal_ratio AS DOUBLE) AS instrument_focal_ratio,
    TRY_CAST(instrument_power AS DOUBLE)       AS instrument_power,
    instrument_type_key,
    TRY_CAST(coma_diameter AS DOUBLE)          AS coma_diameter,
    TRY_CAST(coma_dc AS DOUBLE)                AS coma_dc,
    TRY_CAST(tail_length AS DOUBLE)            AS tail_length,
    tail_length_unit,
    TRY_CAST(tail_pa AS DOUBLE)                AS tail_pa,
    camera_type_key,
    chip_type_key,
    software_type_key,
    icq_reference,
    extinction,
    TRY_CAST(integration_time AS DOUBLE)       AS integration_time,
    TRY_CAST(date_added AS TIMESTAMP)          AS date_added
FROM "cobs-observations"
WHERE obs_date IS NOT NULL AND comet_id IS NOT NULL
