-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Suspended games can resume at a different site or date, so play-level site and date should be used when analyzing individual events.
SELECT
    "gid",
    "event",
    "inning",
    CAST("top_bot" AS BIGINT) AS top_bot,
    CAST("vis_home" AS BIGINT) AS vis_home,
    "site",
    "batteam",
    "pitteam",
    CAST("score_v" AS BIGINT) AS score_v,
    CAST("score_h" AS BIGINT) AS score_h,
    "batter",
    "pitcher",
    "lp",
    "bat_f",
    "bathand",
    "pithand",
    "balls",
    "strikes",
    "count",
    "pitches",
    "nump",
    CAST("pa" AS BIGINT) AS pa,
    CAST("ab" AS BIGINT) AS ab,
    CAST("single" AS BIGINT) AS single,
    CAST("double" AS BIGINT) AS double,
    CAST("triple" AS BIGINT) AS triple,
    CAST("hr" AS BIGINT) AS hr,
    CAST("sh" AS BIGINT) AS sh,
    CAST("sf" AS BIGINT) AS sf,
    CAST("hbp" AS BIGINT) AS hbp,
    CAST("walk" AS BIGINT) AS walk,
    CAST("k" AS BIGINT) AS k,
    CAST("xi" AS BIGINT) AS xi,
    CAST("roe" AS BIGINT) AS roe,
    CAST("fc" AS BIGINT) AS fc,
    CAST("othout" AS BIGINT) AS othout,
    CAST("noout" AS BIGINT) AS noout,
    CAST("oth" AS BIGINT) AS oth,
    CAST("bip" AS BIGINT) AS bip,
    CAST("bunt" AS BIGINT) AS bunt,
    CAST("ground" AS BIGINT) AS ground,
    CAST("fly" AS BIGINT) AS fly,
    CAST("line" AS BIGINT) AS line,
    CAST("iw" AS BIGINT) AS iw,
    CAST("gdp" AS BIGINT) AS gdp,
    CAST("othdp" AS BIGINT) AS othdp,
    CAST("tp" AS BIGINT) AS tp,
    CAST("fle" AS BIGINT) AS fle,
    CAST("wp" AS BIGINT) AS wp,
    CAST("pb" AS BIGINT) AS pb,
    CAST("bk" AS BIGINT) AS bk,
    CAST("oa" AS BIGINT) AS oa,
    CAST("di" AS BIGINT) AS di,
    CAST("sb2" AS BIGINT) AS sb2,
    CAST("sb3" AS BIGINT) AS sb3,
    CAST("sbh" AS BIGINT) AS sbh,
    CAST("cs2" AS BIGINT) AS cs2,
    CAST("cs3" AS BIGINT) AS cs3,
    CAST("csh" AS BIGINT) AS csh,
    CAST("pko1" AS BIGINT) AS pko1,
    CAST("pko2" AS BIGINT) AS pko2,
    CAST("pko3" AS BIGINT) AS pko3,
    CAST("k_safe" AS BIGINT) AS k_safe,
    CAST("e1" AS BIGINT) AS e1,
    CAST("e2" AS BIGINT) AS e2,
    CAST("e3" AS BIGINT) AS e3,
    CAST("e4" AS BIGINT) AS e4,
    CAST("e5" AS BIGINT) AS e5,
    CAST("e6" AS BIGINT) AS e6,
    CAST("e7" AS BIGINT) AS e7,
    CAST("e8" AS BIGINT) AS e8,
    CAST("e9" AS BIGINT) AS e9,
    CAST("outs_pre" AS BIGINT) AS outs_pre,
    CAST("outs_post" AS BIGINT) AS outs_post,
    "br1_pre",
    "br2_pre",
    "br3_pre",
    "br1_post",
    "br2_post",
    "br3_post",
    "lob_id1",
    "lob_id2",
    "lob_id3",
    "pr1_pre",
    "pr2_pre",
    "pr3_pre",
    "pr1_post",
    "pr2_post",
    "pr3_post",
    "run_b",
    "run1",
    "run2",
    "run3",
    "prun_b",
    "prun1",
    "prun2",
    "prun3",
    CAST("ur_b" AS BIGINT) AS ur_b,
    CAST("ur1" AS BIGINT) AS ur1,
    CAST("ur2" AS BIGINT) AS ur2,
    CAST("ur3" AS BIGINT) AS ur3,
    CAST("rbi_b" AS BIGINT) AS rbi_b,
    CAST("rbi1" AS BIGINT) AS rbi1,
    CAST("rbi2" AS BIGINT) AS rbi2,
    CAST("rbi3" AS BIGINT) AS rbi3,
    CAST("runs" AS BIGINT) AS runs,
    CAST("rbi" AS BIGINT) AS rbi,
    CAST("er" AS BIGINT) AS er,
    CAST("tur" AS BIGINT) AS tur,
    "l1",
    "l2",
    "l3",
    "l4",
    "l5",
    "l6",
    "l7",
    "l8",
    "l9",
    CAST("lf1" AS BIGINT) AS lf1,
    CAST("lf2" AS BIGINT) AS lf2,
    CAST("lf3" AS BIGINT) AS lf3,
    CAST("lf4" AS BIGINT) AS lf4,
    CAST("lf5" AS BIGINT) AS lf5,
    CAST("lf6" AS BIGINT) AS lf6,
    CAST("lf7" AS BIGINT) AS lf7,
    CAST("lf8" AS BIGINT) AS lf8,
    CAST("lf9" AS BIGINT) AS lf9,
    "f2",
    "f3",
    "f4",
    "f5",
    "f6",
    "f7",
    "f8",
    "f9",
    CAST("po0" AS BIGINT) AS po0,
    CAST("po1" AS BIGINT) AS po1,
    CAST("po2" AS BIGINT) AS po2,
    CAST("po3" AS BIGINT) AS po3,
    CAST("po4" AS BIGINT) AS po4,
    CAST("po5" AS BIGINT) AS po5,
    CAST("po6" AS BIGINT) AS po6,
    CAST("po7" AS BIGINT) AS po7,
    CAST("po8" AS BIGINT) AS po8,
    CAST("po9" AS BIGINT) AS po9,
    CAST("a1" AS BIGINT) AS a1,
    CAST("a2" AS BIGINT) AS a2,
    CAST("a3" AS BIGINT) AS a3,
    CAST("a4" AS BIGINT) AS a4,
    CAST("a5" AS BIGINT) AS a5,
    CAST("a6" AS BIGINT) AS a6,
    CAST("a7" AS BIGINT) AS a7,
    CAST("a8" AS BIGINT) AS a8,
    CAST("a9" AS BIGINT) AS a9,
    "fseq",
    "batout1",
    CAST("batout2" AS BIGINT) AS batout2,
    CAST("batout3" AS BIGINT) AS batout3,
    CAST("brout_b" AS BIGINT) AS brout_b,
    CAST("brout1" AS BIGINT) AS brout1,
    CAST("brout2" AS BIGINT) AS brout2,
    CAST("brout3" AS BIGINT) AS brout3,
    CAST("firstf" AS BIGINT) AS firstf,
    "loc",
    "hittype",
    CAST("dpopp" AS BIGINT) AS dpopp,
    "pivot",
    CAST("pn" AS BIGINT) AS pn,
    "umphome",
    "ump1b",
    "ump2b",
    "ump3b",
    "umplf",
    "umprf",
    strptime("date", '%Y%m%d')::DATE AS date,
    "gametype",
    "pbp"
FROM "retrosheet-plays"
