SELECT
    strptime("date", '%Y-%m-%d')::DATE AS date,
    "manu_cap_ex_di",
    "oth_cap_ex_di" AS other_cap_ex_di,
    "total_cap_ex_di",
    "manu_conditions_di",
    "oth_conditions_di" AS other_conditions_di,
    "total_conditions_di",
    "manu_employment_di",
    "oth_employment_di" AS other_employment_di,
    "total_employment_di",
    "manu_expect_cond_di",
    "oth_expect_cond_di" AS other_expect_cond_di,
    "total_expect_cond_di",
    "manu_expect_costs_di",
    "oth_expect_costs_di" AS other_expect_costs_di,
    "total_expect_costs_di",
    "manu_expect_employment_di",
    "oth_expect_employment_di" AS other_expect_employment_di,
    "total_expect_employment_di",
    "manu_nonlabor_costs_di",
    "oth_nonlabor_costs_di" AS other_nonlabor_costs_di,
    "total_nonlabor_costs_di",
    "manu_prices_di",
    "oth_prices_di" AS other_prices_di,
    "total_prices_di",
    "manu_wages_di",
    "oth_wages_di" AS other_wages_di,
    "total_wages_di"
FROM "cleveland-fed-sorce-sorce-web-data"
