-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Expert responses are scoped to Russian oblasts; aggregate only after choosing whether the region, election, or respondent is the intended level of analysis.
SELECT
    "expert",
    "oblast",
    "election",
    "year",
    "Winner" AS winner,
    "STATEDATA" AS statedata,
    "popul",
    "grppc",
    "urbanpopulation",
    "ginicoeff",
    "OVERALLINTEGRITY" AS overallintegrity,
    "PEIIndexp" AS peiindexp,
    "PEIIndexi" AS peiindexi,
    "rating",
    "LAWS" AS laws,
    "lawsunfair",
    "lawsunfair2",
    "favoredincumbent",
    "favoredincumbent2",
    "citizens",
    "citizens2",
    "laws0",
    "lawsi",
    "PROCEDURES" AS procedures,
    "managed",
    "votinginfo",
    "fairofficials",
    "legalelections",
    "procedures0",
    "proceduresi",
    "BOUNDARIES" AS boundaries,
    "bdiscrim",
    "bdiscrim2",
    "bfavored",
    "bfavored2",
    "bimpartial",
    "boundaries0",
    "boundariesi",
    "VOTERREGISTRATION" AS voterregistration,
    "reglisted",
    "reglisted2",
    "reginaccurate",
    "reginaccurate2",
    "ineligible",
    "ineligible2",
    "votereg",
    "voteregi",
    "PARTYREGISTRATION" AS partyregistration,
    "oppprevent",
    "oppprevent2",
    "womenopp",
    "minorityopp",
    "leaderselect",
    "leaderselect2",
    "rallies",
    "rallies2",
    "partyreg",
    "partyregi",
    "MEDIACOVERAGE" AS mediacoverage,
    "newspapers",
    "tv",
    "tv2",
    "fairaccess",
    "faircoverage",
    "socialmedia",
    "media",
    "mediai",
    "CAMPAIGNFINANCE" AS campaignfinance,
    "subsidies",
    "donations",
    "accounts",
    "rich",
    "rich2",
    "resources",
    "resources2",
    "finance",
    "financei",
    "VOTINGPROCESS" AS votingprocess,
    "violence",
    "violence2",
    "fraudulent",
    "fraudulent2",
    "easy",
    "choice",
    "postal",
    "disabled",
    "expats",
    "internet",
    "voting",
    "votingi",
    "VOTECOUNT" AS votecount,
    "secure",
    "delay",
    "faircount",
    "intlmonitors",
    "intlmonitors2",
    "domesticmonitors",
    "domesticmonitors2",
    "count",
    "counti",
    "VOTINGRESULTS" AS votingresults,
    "challenged",
    "challenged2",
    "protestspeace",
    "protestspeace2",
    "protestsviolent",
    "protestsviolent2",
    "disputes",
    "results",
    "resultsi",
    "ELECTIONAUTHORITIES" AS electionauthorities,
    "impartial",
    "info",
    "scrutiny",
    "performance",
    "EMBs" AS embs,
    "EMBsi" AS embsi,
    "GENERALQUESTIONS" AS generalquestions,
    "familiarity",
    "important",
    "ORGCONFIDENCE" AS orgconfidence,
    "courts",
    "government",
    "parliament",
    "armedforces",
    "police",
    "electoralauth",
    "television",
    "press",
    "parties",
    "BACKGROUND" AS background,
    "employment",
    "public",
    "university",
    "nonprofit",
    "agency",
    "private",
    "occupation",
    "agegroup",
    "sex",
    "education",
    "born",
    "lived",
    "candidate",
    "rep",
    "activist",
    "ngo",
    "voted",
    "norole",
    "monitor",
    "monitorint",
    "official",
    "citizen",
    "supported",
    "leftrightscale",
    "difficulty",
    "VIGNETTES" AS vignettes,
    "vignetteA" AS vignettea,
    "vignetteB" AS vignetteb,
    "vignetteC" AS vignettec,
    "EXTRA" AS extra,
    "inducementLDPR" AS inducementldpr,
    "inducementCPRF" AS inducementcprf,
    "inducementJR" AS inducementjr,
    "inducementUR" AS inducementur,
    "inducementCR" AS inducementcr,
    "inducementPR" AS inducementpr,
    "inducementPP" AS inducementpp,
    "inducementHOM" AS inducementhom,
    "inducementYAB" AS inducementyab,
    "inducementGRE" AS inducementgre,
    "inducementPAR" AS inducementpar,
    "promiseLDPR" AS promiseldpr,
    "promiseCPRF" AS promisecprf,
    "promiseJR" AS promisejr,
    "promiseUR" AS promiseur,
    "promiseCR" AS promisecr,
    "promisePR" AS promisepr,
    "promisePP" AS promisepp,
    "promiseHOM" AS promisehom,
    "promiseYAB" AS promiseyab,
    "promiseGRE" AS promisegre,
    "promisePAR" AS promisepar,
    "checvotLDPR" AS checvotldpr,
    "checvotCPRF" AS checvotcprf,
    "checvotJR" AS checvotjr,
    "checvotUR" AS checvotur,
    "checvotCR" AS checvotcr,
    "checvotPR" AS checvotpr,
    "checvotPP" AS checvotpp,
    "checvotHOM" AS checvothom,
    "checvotYAB" AS checvotyab,
    "checvotGRE" AS checvotgre,
    "checvotPAR" AS checvotpar,
    "elecmech",
    "elecopport",
    "elecivil",
    "elecvehicle",
    "elecompeti",
    "elecunity"
FROM "electoral-integrity-project-pei-russia-expert"
