-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Rows are state-level aggregates for a single Mexican election study, not a national time series.
SELECT
    "estado",
    "election",
    "year",
    "STATEDATA" AS statedata,
    "Eleccin" AS eleccin,
    "Ganador" AS ganador,
    "participation",
    "population",
    "GDP" AS gdp,
    "GDPpc" AS gdppc,
    "contacted",
    "numresponses",
    "responserate",
    "OVERALLINTEGRITY" AS overallintegrity,
    "PEIIndexp" AS peiindexp,
    "PEIIndexp_lci" AS peiindexp_lci,
    "PEIIndexp_hci" AS peiindexp_hci,
    "PEIIndexi" AS peiindexi,
    "PEIIndexi_lci" AS peiindexi_lci,
    "PEIIndexi_hci" AS peiindexi_hci,
    "PEIIndex_rank" AS peiindex_rank,
    "PEItype" AS peitype,
    "rating",
    "rating_lci",
    "rating_hci",
    "LAWS" AS laws,
    "lawsunfair",
    "lawsunfair2",
    "favoredincumbent",
    "favoredincumbent2",
    "citizens",
    "citizens2",
    "laws0",
    "lawsi",
    "PROCEDURES" AS procedures,
    "managed",
    "votinginfo",
    "fairofficials",
    "legalelections",
    "procedures0",
    "proceduresi",
    "BOUNDARIES" AS boundaries,
    "bdiscrim",
    "bdiscrim2",
    "bfavored",
    "bfavored2",
    "bimpartial",
    "boundaries0",
    "boundariesi",
    "VOTERREGISTRATION" AS voterregistration,
    "reglisted",
    "reglisted2",
    "reginaccurate",
    "reginaccurate2",
    "ineligible",
    "ineligible2",
    "votereg",
    "voteregi",
    "PARTYREGISTRATION" AS partyregistration,
    "oppprevent",
    "oppprevent2",
    "womenopp",
    "minorityopp",
    "leaderselect",
    "leaderselect2",
    "rallies",
    "rallies2",
    "partyreg",
    "partyregi",
    "MEDIACOVERAGE" AS mediacoverage,
    "newspapers",
    "tv",
    "tv2",
    "fairaccess",
    "faircoverage",
    "socialmedia",
    "media",
    "mediai",
    "CAMPAIGNFINANCE" AS campaignfinance,
    "subsidies",
    "donations",
    "accounts",
    "rich",
    "rich2",
    "resources",
    "resources2",
    "finance",
    "financei",
    "VOTINGPROCESS" AS votingprocess,
    "violence",
    "violence2",
    "fraudulent",
    "fraudulent2",
    "easy",
    "choice",
    "postal",
    "disabled",
    "expats",
    "internet",
    "voting",
    "votingi",
    "VOTECOUNT" AS votecount,
    "secure",
    "delay",
    "faircount",
    "intlmonitors",
    "intlmonitors2",
    "domesticmonitors",
    "domesticmonitors2",
    "count",
    "counti",
    "VOTINGRESULTS" AS votingresults,
    "challenged",
    "challenged2",
    "protestspeace",
    "protestspeace2",
    "protestsviolent",
    "protestsviolent2",
    "disputes",
    "results",
    "resultsi",
    "ELECTIONAUTHORITIES" AS electionauthorities,
    "impartial",
    "info",
    "scrutiny",
    "performance",
    "EMBs" AS embs,
    "EMBsi" AS embsi,
    "GENERALQUESTIONS" AS generalquestions,
    "familiarity",
    "important",
    "ORGCONFIDENCE" AS orgconfidence,
    "courts",
    "gobernador",
    "localdips",
    "armyforces",
    "statepolice",
    "localelecauth",
    "statetv",
    "statepress",
    "stateparties",
    "BACKGROUND" AS background,
    "employment",
    "public",
    "university",
    "nonprofit",
    "agency",
    "private",
    "occupation",
    "agegroup",
    "sex",
    "education",
    "born",
    "lived",
    "candidate",
    "rep",
    "activist",
    "ngo",
    "voted",
    "norole",
    "natelecmonitor",
    "elecofficial",
    "citizen",
    "supported",
    "leftrightscale",
    "VIGNETTES" AS vignettes,
    "vignetteA" AS vignettea,
    "vignetteB" AS vignetteb,
    "vignetteC" AS vignettec,
    "EXTRA" AS extra,
    "inflorgcrime",
    "inflamenaza",
    "inflfinanciamiento",
    "orgcrimpart",
    "orgcrimdecvoter",
    "orgcrimmunic",
    "STATEPOLITICS" AS statepolitics,
    "votePAN" AS votepan,
    "voteperPAN" AS voteperpan,
    "votePRI" AS votepri,
    "voteperPRI" AS voteperpri,
    "votePRD" AS voteprd,
    "voteperPRD" AS voteperprd,
    "votePRDPAN" AS voteprdpan,
    "voteperPRDPAN" AS voteperprdpan,
    "votePVEM" AS votepvem,
    "voteperPVEM" AS voteperpvem,
    "voteMorena" AS votemorena,
    "voteperMorena" AS votepermorena,
    "voteMC" AS votemc,
    "voteperMC" AS votepermc,
    "voteNA" AS votena,
    "voteperNA" AS voteperna,
    "votePES" AS votepes,
    "voteperPES" AS voteperpes,
    "votePT" AS votept,
    "voteperPT" AS voteperpt,
    "votePT_MC_Morena" AS votept_mc_morena,
    "voteperPT_MC_Morena" AS voteperpt_mc_morena,
    "votePH" AS voteph,
    "voteperPH" AS voteperph,
    "voteIndep" AS voteindep,
    "voteperIndep" AS voteperindep,
    "voteLocalpart" AS votelocalpart,
    "voteperLocalpart" AS voteperlocalpart,
    "voteNonregvote" AS votenonregvote,
    "voteperNonregvote" AS votepernonregvote,
    "voteNullvotes" AS votenullvotes,
    "voteperNullvotes" AS votepernullvotes,
    "voteValidvotes" AS votevalidvotes,
    "voteTotal" AS votetotal,
    "nominalist",
    "homicides",
    "homicides100m",
    "pubspending",
    "nummunicip",
    "nummunpartgob",
    "popgobparty",
    "poppergobparty",
    "sizecongress",
    "numdipgob",
    "numdipgobcoal",
    "unemployment",
    "urbanpopstate",
    "poverty",
    "moderpoverty",
    "extrempoverty",
    "localresources",
    "genpartfund",
    "genpartfundpc",
    "yearprevlocelec",
    "ganadort1",
    "votePANt1" AS votepant1,
    "voteperPANt1" AS voteperpant1,
    "votePRIt1" AS voteprit1,
    "voteperPRIt1" AS voteperprit1,
    "votePRDt1" AS voteprdt1,
    "voteperPRDt1" AS voteperprdt1,
    "votePRDPANt1" AS voteprdpant1,
    "voteperPRDPANt1" AS voteperprdpant1,
    "votePVEMt1" AS votepvemt1,
    "voteperPVEMt1" AS voteperpvemt1,
    "voteMorenat1" AS votemorenat1,
    "voteperMorenat1" AS votepermorenat1,
    "voteMCt1" AS votemct1,
    "voteperMCt1" AS votepermct1,
    "voteNAt1" AS votenat1,
    "voteperNAt1" AS votepernat1,
    "votePESt1" AS votepest1,
    "voteperPESt1" AS voteperpest1,
    "votePTt1" AS voteptt1,
    "voteperPTt1" AS voteperptt1,
    "votePT_MC_Morenat1" AS votept_mc_morenat1,
    "voteperPT_MC_Morenat1" AS voteperpt_mc_morenat1,
    "votePHt1" AS votepht1,
    "voteperPHt1" AS voteperpht1,
    "voteIndept1" AS voteindept1,
    "voteperIndept1" AS voteperindept1,
    "voteLocalpartt1" AS votelocalpartt1,
    "voteperLocalpartt1" AS voteperlocalpartt1,
    "voteNonregvotet1" AS votenonregvotet1,
    "voteperNonregvotet1" AS votepernonregvotet1,
    "voteNullvotest1" AS votenullvotest1,
    "voteperNullvotest1" AS votepernullvotest1,
    "voteValidvotest1" AS votevalidvotest1,
    "voteTotalt1" AS votetotalt1,
    "nominalistt1",
    "participationt1",
    "populationt1",
    "GDPt1" AS gdpt1,
    "GDPpct1" AS gdppct1,
    "homicidest1",
    "homicides100mt1",
    "pubspendingt1",
    "nummunicipt1",
    "nummunpartgobt1",
    "popgobpartyt1",
    "poppergobpartyt1",
    "sizecongresst1",
    "numdipgobt1",
    "numdipgobcoalt1",
    "unemploymentt1",
    "urbanpopstatet1",
    "povertyt1",
    "moderpovertyt1",
    "extrempovertyt1",
    "localresourcest1",
    "genpartfundt1",
    "genpartfundpct1"
FROM "electoral-integrity-project-pei-mexico-state"
