-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Rows are state-level aggregates for the 2018 US study, not a multi-year state panel.
SELECT
    "state",
    "stateabbr",
    "statecode",
    "election",
    "year",
    "wave",
    "numresponses",
    "contacted",
    "responserate",
    "OVERALLINTEGRITY" AS overallintegrity,
    "PEIIndexp" AS peiindexp,
    "PEIIndexp_lci" AS peiindexp_lci,
    "PEIIndexp_hci" AS peiindexp_hci,
    "PEIIndexi" AS peiindexi,
    "PEIIndexi_lci" AS peiindexi_lci,
    "PEIIndexi_hci" AS peiindexi_hci,
    "PEIIndex_rank" AS peiindex_rank,
    "PEItype" AS peitype,
    "ratingstate",
    "ratingstate_lci",
    "ratingstate_hci",
    "ratingcountry",
    "ratingcountry_lci",
    "ratingcountry_hci",
    "LAWS" AS laws,
    "lawsunfair",
    "lawsunfair2",
    "favoredincumbent",
    "favoredincumbent2",
    "citizens",
    "citizens2",
    "laws_1",
    "lawsi",
    "PROCEDURES" AS procedures,
    "managed",
    "votinginfo",
    "fairofficials",
    "legalelections",
    "procedures_1",
    "proceduresi",
    "BOUNDARIES" AS boundaries,
    "bdiscrim",
    "bdiscrim2",
    "bfavored",
    "bfavored2",
    "bimpartial",
    "boundaries_1",
    "boundariesi",
    "VOTERREGISTRATION" AS voterregistration,
    "reglisted",
    "reglisted2",
    "reginaccurate",
    "reginaccurate2",
    "ineligible",
    "ineligible2",
    "votereg",
    "voteregi",
    "PARTYREGISTRATION" AS partyregistration,
    "oppprevent",
    "oppprevent2",
    "womenopp",
    "minorityopp",
    "leaderselect",
    "leaderselect2",
    "rallies",
    "rallies2",
    "partyreg",
    "partyregi",
    "MEDIACOVERAGE" AS mediacoverage,
    "newspapers",
    "tv",
    "tv2",
    "fairaccess",
    "faircoverage",
    "socialmedia",
    "media",
    "mediai",
    "CAMPAIGNFINANCE" AS campaignfinance,
    "subsidies",
    "donations",
    "accounts",
    "rich",
    "rich2",
    "resources",
    "resources2",
    "finance",
    "financei",
    "VOTINGPROCESS" AS votingprocess,
    "violence",
    "violence2",
    "fraudulent",
    "fraudulent2",
    "easy",
    "choice",
    "postal",
    "disabled",
    "expats",
    "internet",
    "voting",
    "votingi",
    "VOTECOUNT" AS votecount,
    "secure",
    "delay",
    "faircount",
    "intlmonitors",
    "intlmonitors2",
    "domesticmonitors",
    "domesticmonitors2",
    "count",
    "counti",
    "VOTINGRESULTS" AS votingresults,
    "challenged",
    "challenged2",
    "protestspeace",
    "protestspeace2",
    "protestsviolent",
    "protestsviolent2",
    "disputes",
    "results",
    "resultsi",
    "ELECTIONAUTHORITIES" AS electionauthorities,
    "impartial",
    "info",
    "scrutiny",
    "performance",
    "EMBs" AS embs,
    "EMBsi" AS embsi,
    "GENERALQUESTIONS" AS generalquestions,
    "familiarity",
    "important",
    "ORGCONFIDENCE" AS orgconfidence,
    "courts",
    "government",
    "parliament",
    "police",
    "electoralauth",
    "BACKGROUND" AS background,
    "employment",
    "public",
    "university",
    "nonprofit",
    "agency",
    "private",
    "occupation",
    "agegroup",
    "sex",
    "education",
    "born",
    "lived",
    "rep",
    "candidate",
    "activist",
    "monitor",
    "monitorint",
    "ngo",
    "voted",
    "norole",
    "official",
    "citizen",
    "supported",
    "leftrightscale",
    "partyid",
    "difficulty",
    "VIGNETTES" AS vignettes,
    "vignetteA" AS vignettea,
    "vignetteB" AS vignetteb,
    "vignetteC" AS vignettec,
    "EXTRA" AS extra,
    "rigged",
    "rigged2",
    "machinesaccurate",
    "recordssecure",
    "waited",
    "waited2",
    "multiple",
    "multiple2",
    "regrestrictive",
    "regrestrictive2",
    "obsintimidate",
    "obsintimidate2",
    "popularwill",
    "timely",
    "disinformation",
    "disinformation2",
    "hack",
    "hack2",
    "meddle",
    "meddle2",
    "countdispute",
    "countdispute2",
    "illegalvote",
    "illegalvote2",
    "legalcount",
    "votersuppress",
    "votersuppress2",
    "design",
    "candidatethreat",
    "candidatethreat2",
    "sufficient",
    "audit",
    "SUBFIELD" AS subfield,
    "elections",
    "ampol",
    "statepol",
    "comparative",
    "inter",
    "polcomm",
    "theory",
    "publicadmin",
    "publicpol",
    "methods",
    "socio"
FROM "electoral-integrity-project-pei-us-2018-state"
