-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Rows are state-level aggregates for the 2016 US study, not a multi-year state panel.
SELECT
    "state",
    "stateabbr",
    "statecode",
    "election",
    "year",
    "wave",
    "numresponses",
    "contacted",
    "responserate",
    "overallintegrity",
    "PEIIndexp" AS peiindexp,
    "PEIIndexp_lci" AS peiindexp_lci,
    "PEIIndexp_hci" AS peiindexp_hci,
    "PEIIndexi" AS peiindexi,
    "PEIIndexi_lci" AS peiindexi_lci,
    "PEIIndexi_hci" AS peiindexi_hci,
    "PEIIndex_rank" AS peiindex_rank,
    "PEItype" AS peitype,
    "ratingstate",
    "ratingstate_lci",
    "ratingstate_hci",
    "ratingcountry",
    "ratingcountry_lci",
    "ratingcountry_hci",
    "laws",
    "lawsunfair",
    "lawsunfair2",
    "favoredincumbent",
    "favoredincumbent2",
    "citizens",
    "citizens2",
    "laws.1" AS laws_1,
    "lawsi",
    "procedures",
    "managed",
    "votinginfo",
    "fairofficials",
    "legalelections",
    "procedures.1" AS procedures_1,
    "proceduresi",
    "boundaries",
    "bdiscrim",
    "bdiscrim2",
    "bfavored",
    "bfavored2",
    "bimpartial",
    "boundaries.1" AS boundaries_1,
    "boundariesi",
    "voterregistration",
    "reglisted",
    "reglisted2",
    "reginaccurate",
    "reginaccurate2",
    "ineligible",
    "ineligible2",
    "votereg",
    "voteregi",
    "partyregistration",
    "oppprevent",
    "oppprevent2",
    "womenopp",
    "minorityopp",
    "leaderselect",
    "leaderselect2",
    "rallies",
    "rallies2",
    "partyreg",
    "partyregi",
    "mediacoverage",
    "newspapers",
    "tv",
    "tv2",
    "fairaccess",
    "faircoverage",
    "socialmedia",
    "media",
    "mediai",
    "campaignfinance",
    "subsidies",
    "donations",
    "accounts",
    "rich",
    "rich2",
    "resources",
    "resources2",
    "finance",
    "financei",
    "votingprocess",
    "violence",
    "violence2",
    "fraudulent",
    "fraudulent2",
    "easy",
    "choice",
    "postal",
    "disabled",
    "expats",
    "internet",
    "voting",
    "votingi",
    "votecount",
    "secure",
    "delay",
    "faircount",
    "intlmonitors",
    "intlmonitors2",
    "domesticmonitors",
    "domesticmonitors2",
    "count",
    "counti",
    "votingresults",
    "challenged",
    "challenged2",
    "protestspeace",
    "protestspeace2",
    "protestsviolent",
    "protestsviolent2",
    "disputes",
    "results",
    "resultsi",
    "electionauthorities",
    "impartial",
    "info",
    "scrutiny",
    "performance",
    "EMBs" AS embs,
    "EMBsi" AS embsi,
    "generalquestions",
    "familiarity",
    "important",
    "orgconfidence",
    "courts",
    "government",
    "parliament",
    "police",
    "electoralauth",
    "background",
    "employment",
    "public",
    "university",
    "nonprofit",
    "agency",
    "private",
    "occupation",
    "agegroup",
    "sex",
    "education",
    "born",
    "lived",
    "rep",
    "candidate",
    "activist",
    "monitor",
    "ngo",
    "voted",
    "norole",
    "official",
    "citizen",
    "supported",
    "leftrightscale",
    "difficulty",
    "vignettes",
    "vignetteA" AS vignettea,
    "vignetteB" AS vignetteb,
    "vignetteC" AS vignettec,
    "extra",
    "rigged",
    "rigged2",
    "machinesaccurate",
    "recordssecure",
    "waited",
    "waited2",
    "multiple",
    "multiple2",
    "regrestrictive",
    "regrestrictive2",
    "obsintimidate",
    "obsintimidate2",
    "popularwill",
    "timely",
    "subfield",
    "elections",
    "ampol",
    "statepol",
    "comparative",
    "inter",
    "polcomm",
    "theory",
    "publicadmin",
    "publicpol",
    "methods",
    "socio"
FROM "electoral-integrity-project-pei-us-2016-state"
