-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Expert-level UK microdata exposes no stable respondent identifier, so rows should be treated as individual survey records without a declared key.
-- caution: The table is a wide expert-response file with question responses and PEI scores; aggregate only after choosing the intended level of analysis.
SELECT
    "election",
    "OVERALLINTEGRITY" AS overallintegrity,
    "PEI_add_original_m" AS pei_add_original_m,
    "PEI_add_original" AS pei_add_original,
    "PEI_add_new_m" AS pei_add_new_m,
    "PEI_add_new" AS pei_add_new,
    "PEI_concept_m" AS pei_concept_m,
    "PEI_contestation_m" AS pei_contestation_m,
    "PEI_participation_m" AS pei_participation_m,
    "PEI_deliberation_m" AS pei_deliberation_m,
    "PEI_adjudication_m" AS pei_adjudication_m,
    "PEI_concept" AS pei_concept,
    "PEI_contestation" AS pei_contestation,
    "PEI_participation" AS pei_participation,
    "PEI_deliberation" AS pei_deliberation,
    "PEI_adjudication" AS pei_adjudication,
    "rating",
    "LAWS" AS laws,
    "lawsunfair",
    "lawsunfair2",
    "favoredincumbent",
    "favoredincumbent2",
    "citizens",
    "citizens2",
    "certainty",
    "changes",
    "equal",
    "enfranchised",
    "laws_1",
    "laws_m",
    "laws_new",
    "laws_new_m",
    "PROCEDURES" AS procedures,
    "managed",
    "votinginfo",
    "fairofficials",
    "legalelections",
    "procedures_1",
    "procedures_m",
    "procedures_new",
    "procedures_new_m",
    "BOUNDARIES" AS boundaries,
    "bdiscrim",
    "bdiscrim2",
    "bfavored",
    "bfavored2",
    "bimpartial",
    "boundaries_1",
    "boundaries_m",
    "boundaries_new",
    "boundaries_new_m",
    "VOTERREGISTRATION" AS voterregistration,
    "reglisted",
    "reglisted2",
    "reginaccurate",
    "reginaccurate2",
    "ineligible",
    "ineligible2",
    "unlikelyreg",
    "unlikelyreg2",
    "votereg",
    "votereg_m",
    "voterreg_new",
    "voterreg_new_m",
    "PARTYREGISTRATION" AS partyregistration,
    "oppprevent",
    "oppprevent2",
    "womenopp",
    "minorityopp",
    "leaderselect",
    "leaderselect2",
    "rallies",
    "rallies2",
    "equalopp",
    "partytargeted",
    "partytargeted2",
    "partyreg",
    "partyreg_m",
    "partyreg_new",
    "partyreg_new_m",
    "MEDIACOVERAGE" AS mediacoverage,
    "balanced",
    "tv",
    "tv2",
    "fairaccess",
    "faircoverage",
    "socialmedia",
    "disinformation",
    "disinformation2",
    "deliberation",
    "media",
    "media_m",
    "media_new",
    "media_new_m",
    "CAMPAIGNFINANCE" AS campaignfinance,
    "subsidies",
    "donations",
    "accounts",
    "rich",
    "rich2",
    "resources",
    "resources2",
    "bribed",
    "bribed2",
    "finance",
    "finance_m",
    "finance_new",
    "finance_new_m",
    "VOTINGPROCESS" AS votingprocess,
    "violence",
    "violence2",
    "fraudulent",
    "fraudulent2",
    "easy",
    "choice",
    "disabled",
    "expats",
    "internet",
    "gaps",
    "gaps2",
    "encouraged",
    "identification",
    "identification2",
    "voting",
    "voting_m",
    "voting_new",
    "voting_new_m",
    "VOTECOUNT" AS votecount,
    "secure",
    "delay",
    "faircount",
    "intlmonitors",
    "intlmonitors2",
    "domesticmonitors",
    "domesticmonitors2",
    "count",
    "count_m",
    "count_new",
    "count_new_m",
    "VOTINGRESULTS" AS votingresults,
    "challenged",
    "challenged2",
    "protestspeace",
    "protestspeace2",
    "protestsviolent",
    "protestsviolent2",
    "disputes",
    "effective",
    "results",
    "results_m",
    "results_new",
    "results_new_m",
    "ELECTIONAUTHORITIES" AS electionauthorities,
    "impartial",
    "info",
    "scrutiny",
    "performance",
    "targeted",
    "targeted2",
    "EMBs" AS embs,
    "EMBs_m" AS embs_m,
    "EMBs_new" AS embs_new,
    "EMBs_new_m" AS embs_new_m,
    "GENERALQUESTIONS" AS generalquestions,
    "familiarity",
    "ORGCONFIDENCE" AS orgconfidence,
    "courts",
    "government",
    "parliament",
    "armedforces",
    "electoralauth",
    "BACKGROUND" AS background,
    "employment",
    "public",
    "university",
    "nonprofit",
    "agency",
    "private",
    "occupation",
    "agegroup",
    "sex",
    "education",
    "born",
    "lived",
    "candidate",
    "rep",
    "activist",
    "ngo",
    "voted",
    "norole",
    "monitor",
    "monitorint",
    "official",
    "citizen",
    "leftrightscale",
    "difficulty"
FROM "electoral-integrity-project-pei-uk-expert"
