SELECT
    match_id,
    team_type,
    gender,
    season,
    TRY_STRPTIME(start_date, '%Y/%m/%d')::DATE        AS start_date,
    TRY_STRPTIME(end_date, '%Y/%m/%d')::DATE          AS end_date,
    event,
    match_type,
    TRY_CAST(NULLIF(match_number, '')   AS INTEGER)   AS match_number,
    TRY_CAST(NULLIF(overs, '')          AS INTEGER)   AS overs,
    TRY_CAST(NULLIF(balls_per_over, '') AS INTEGER)   AS balls_per_over,
    venue,
    city,
    team1,
    team2,
    toss_winner,
    toss_decision,
    player_of_match,
    winner,
    TRY_CAST(NULLIF(winner_runs, '')    AS INTEGER)   AS winner_runs,
    TRY_CAST(NULLIF(winner_wickets, '') AS INTEGER)   AS winner_wickets,
    method,
    outcome
FROM "cricsheet-matches"
WHERE match_id IS NOT NULL
