-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "change_date",
    CAST("crash_id" AS BIGINT) AS crash_id,
    "report_state",
    "report_number",
    strptime("report_date", '%Y%m%d')::DATE AS report_date,
    "report_time",
    CAST("report_seq_no" AS BIGINT) AS report_seq_no,
    CAST("dot_number" AS BIGINT) AS dot_number,
    "ci_status_code",
    strptime("final_status_date", '%Y%m%d')::DATE AS final_status_date,
    "location",
    "city_code",
    "city",
    "state",
    "county_code",
    "truck_bus_ind",
    CAST("trafficway_id" AS BIGINT) AS trafficway_id,
    CAST("access_control_id" AS BIGINT) AS access_control_id,
    CAST("road_surface_condition_id" AS BIGINT) AS road_surface_condition_id,
    CAST("cargo_body_type_id" AS BIGINT) AS cargo_body_type_id,
    CAST("gvw_rating_id" AS BIGINT) AS gvw_rating_id,
    "vehicle_identification_number",
    "vehicle_license_number",
    "vehicle_lic_state",
    "vehicle_hazmat_placard",
    CAST("weather_condition_id" AS BIGINT) AS weather_condition_id,
    CAST("vehicle_configuration_id" AS BIGINT) AS vehicle_configuration_id,
    CAST("light_condition_id" AS BIGINT) AS light_condition_id,
    "hazmat_released",
    "agency",
    "vehicles_in_accident",
    CAST("fatalities" AS BIGINT) AS fatalities,
    CAST("injuries" AS BIGINT) AS injuries,
    "tow_away",
    "federal_recordable",
    "state_recordable",
    "snet_version_number",
    CAST("snet_sequence_id" AS BIGINT) AS snet_sequence_id,
    "transaction_code",
    "transaction_date",
    "upload_first_byte",
    "upload_dot_number",
    "upload_search_indicator",
    "upload_date",
    "add_date",
    CAST("crash_carrier_id" AS BIGINT) AS crash_carrier_id,
    "crash_carrier_name",
    "crash_carrier_street",
    "crash_carrier_city",
    "crash_carrier_city_code",
    "crash_carrier_state",
    "crash_carrier_zip_code",
    "crash_colonia",
    CAST("docket_number" AS BIGINT) AS docket_number,
    "crash_carrier_interstate",
    CAST("no_id_flag" AS BIGINT) AS no_id_flag,
    "state_number",
    "state_issuing_number",
    "crash_event_seq_id_desc"
FROM "u-s-department-of-transportation-aayw-vxb3"
