-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No stable row key was verified in the raw profile; use this table as a source snapshot rather than assuming row identity across runs.
SELECT
    "iyr",
    "imo",
    "railroad",
    "incdtno",
    "typpers",
    "jobcode",
    "natinj",
    "location",
    "ifatal",
    "occode",
    "tcode",
    "age",
    CAST("daysabs" AS DOUBLE) AS daysabs,
    CAST("daysres" AS DOUBLE) AS daysres,
    "dummy",
    "state",
    "typrr",
    "dummy1",
    CAST("region" AS BIGINT) AS region,
    "dummy2",
    CAST("narrlen" AS DOUBLE) AS narrlen,
    "casfatal",
    "cas57",
    "cas54",
    CAST("dummy3" AS BIGINT) AS dummy3,
    "day",
    CAST("year4" AS BIGINT) AS year4,
    CAST("timehr" AS DOUBLE) AS timehr,
    CAST("timemin" AS DOUBLE) AS timemin,
    "ampm",
    "county",
    "cntycd",
    "stcnty",
    "alcohol",
    "drug",
    "phyact",
    "loca",
    "locb",
    "locc",
    "event",
    "tools",
    "injcaus",
    "hzmexpos",
    "terminat",
    "narr1",
    "narr2",
    "narr3",
    "coverdata",
    CAST("latitude" AS DOUBLE) AS latitude,
    CAST("longitud" AS DOUBLE) AS longitud
FROM "u-s-department-of-transportation-kuvg-3uwp"
