-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No stable row key was verified in the raw profile; use this table as a source snapshot rather than assuming row identity across runs.
SELECT
    "ntd_id",
    "state_parent_ntd_id",
    "agency_name",
    "division_department",
    "doing_business_as",
    "reporter_type",
    "reporting_module",
    "organization_type",
    "reported_by_ntd_id",
    "reported_by_name",
    "public_sponsor",
    "subrecipient_type",
    CAST("fy_end_date" AS TIMESTAMP) AS fy_end_date,
    CAST("original_due_date" AS TIMESTAMP) AS original_due_date,
    "address_line_1",
    "address_line_2",
    CAST("p_o_box" AS BIGINT) AS p_o_box,
    "city",
    "state",
    CAST("zip_code" AS BIGINT) AS zip_code,
    CAST("zip_code_ext" AS BIGINT) AS zip_code_ext,
    CAST("region" AS BIGINT) AS region,
    "url",
    CAST("fta_recipient_id" AS BIGINT) AS fta_recipient_id,
    "ueid",
    CAST("service_area_sq_miles" AS BIGINT) AS service_area_sq_miles,
    CAST("service_area_pop" AS BIGINT) AS service_area_pop,
    "primary_uza_uace_code",
    "uza_name",
    "tribal_area_name",
    CAST("population" AS BIGINT) AS population,
    CAST("density" AS DOUBLE) AS density,
    CAST("sq_miles" AS DOUBLE) AS sq_miles,
    CAST("voms_do" AS BIGINT) AS voms_do,
    CAST("voms_pt" AS BIGINT) AS voms_pt,
    CAST("total_voms" AS BIGINT) AS total_voms,
    CAST("volunteer_drivers" AS BIGINT) AS volunteer_drivers,
    CAST("personal_vehicles" AS BIGINT) AS personal_vehicles,
    "tam_tier",
    CAST("number_of_state_counties" AS BIGINT) AS number_of_state_counties,
    CAST("number_of_counties_with" AS BIGINT) AS number_of_counties_with,
    "state_admin_funds_expended",
    "street_address_geo_reference"
FROM "u-s-department-of-transportation-ccvf-fykn"
