-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No stable row key was verified in the raw profile; use this table as a source snapshot rather than assuming row identity across runs.
SELECT
    "the_geom",
    CAST("year_recor" AS BIGINT) AS year_recor,
    CAST("state_code" AS BIGINT) AS state_code,
    "route_id",
    CAST("begin_poin" AS DOUBLE) AS begin_poin,
    CAST("end_point" AS DOUBLE) AS end_point,
    CAST("aadt" AS BIGINT) AS aadt,
    CAST("aadt_conbi" AS BIGINT) AS aadt_conbi,
    CAST("aadt_singl" AS BIGINT) AS aadt_singl,
    CAST("access_con" AS BIGINT) AS access_con,
    CAST("at_grade_o" AS BIGINT) AS at_grade_o,
    CAST("base_thick" AS DOUBLE) AS base_thick,
    CAST("base_type" AS BIGINT) AS base_type,
    CAST("counter_pe" AS BIGINT) AS counter_pe,
    CAST("county_cod" AS BIGINT) AS county_cod,
    CAST("cracking_p" AS DOUBLE) AS cracking_p,
    CAST("curves_a" AS DOUBLE) AS curves_a,
    CAST("curves_b" AS DOUBLE) AS curves_b,
    CAST("curves_c" AS DOUBLE) AS curves_c,
    CAST("curves_d" AS DOUBLE) AS curves_d,
    CAST("curves_e" AS DOUBLE) AS curves_e,
    CAST("curves_f" AS DOUBLE) AS curves_f,
    CAST("dir_factor" AS DOUBLE) AS dir_factor,
    CAST("f_system" AS BIGINT) AS f_system,
    CAST("facility_t" AS BIGINT) AS facility_t,
    CAST("faulting" AS DOUBLE) AS faulting,
    CAST("future_aad" AS BIGINT) AS future_aad,
    CAST("future_a_1" AS BIGINT) AS future_a_1,
    CAST("future_fac" AS BIGINT) AS future_fac,
    CAST("future_f_1" AS BIGINT) AS future_f_1,
    CAST("grades_a" AS DOUBLE) AS grades_a,
    CAST("grades_b" AS DOUBLE) AS grades_b,
    CAST("grades_c" AS DOUBLE) AS grades_c,
    CAST("grades_d" AS DOUBLE) AS grades_d,
    CAST("grades_e" AS DOUBLE) AS grades_e,
    CAST("grades_f" AS DOUBLE) AS grades_f,
    CAST("hov_lanes" AS BIGINT) AS hov_lanes,
    CAST("hov_type" AS BIGINT) AS hov_type,
    CAST("iri" AS BIGINT) AS iri,
    CAST("iri_year" AS BIGINT) AS iri_year,
    CAST("k_factor" AS DOUBLE) AS k_factor,
    CAST("lane_width" AS BIGINT) AS lane_width,
    CAST("last_overl" AS DOUBLE) AS last_overl,
    CAST("median_typ" AS BIGINT) AS median_typ,
    CAST("median_wid" AS BIGINT) AS median_wid,
    CAST("nhs" AS BIGINT) AS nhs,
    CAST("nhs_year" AS BIGINT) AS nhs_year,
    CAST("number_sig" AS BIGINT) AS number_sig,
    CAST("ownership" AS BIGINT) AS ownership,
    CAST("pct_green_" AS DOUBLE) AS pct_green,
    CAST("pct_pass_s" AS DOUBLE) AS pct_pass_s,
    CAST("pct_peak_c" AS DOUBLE) AS pct_peak_c,
    CAST("pct_peak_s" AS DOUBLE) AS pct_peak_s,
    CAST("peak_capac" AS BIGINT) AS peak_capac,
    CAST("peak_lanes" AS BIGINT) AS peak_lanes,
    CAST("peak_parki" AS BIGINT) AS peak_parki,
    CAST("psr" AS DOUBLE) AS psr,
    CAST("route_numb" AS BIGINT) AS route_numb,
    "route_nu_1",
    CAST("route_qual" AS BIGINT) AS route_qual,
    CAST("route_sign" AS BIGINT) AS route_sign,
    CAST("rutting" AS DOUBLE) AS rutting,
    CAST("shoulder_t" AS BIGINT) AS shoulder_t,
    CAST("shoulder_w" AS BIGINT) AS shoulder_w,
    CAST("shoulder_1" AS BIGINT) AS shoulder_1,
    CAST("signal_typ" AS BIGINT) AS signal_typ,
    CAST("speed_limi" AS BIGINT) AS speed_limi,
    CAST("stop_signs" AS BIGINT) AS stop_signs,
    CAST("strahnet" AS BIGINT) AS strahnet,
    CAST("structure_" AS BIGINT) AS structure,
    CAST("surface_ty" AS BIGINT) AS surface_ty,
    CAST("terrain_ty" AS BIGINT) AS terrain_ty,
    CAST("thickness_" AS DOUBLE) AS thickness,
    CAST("thickness1" AS DOUBLE) AS thickness1,
    CAST("through_la" AS BIGINT) AS through_la,
    CAST("toll_charg" AS BIGINT) AS toll_charg,
    "toll_id",
    CAST("toll_type" AS BIGINT) AS toll_type,
    CAST("truck" AS BIGINT) AS truck,
    CAST("truck_year" AS BIGINT) AS truck_year,
    CAST("turn_lanes" AS BIGINT) AS turn_lanes,
    CAST("turn_lan_1" AS BIGINT) AS turn_lan_1,
    CAST("urban_code" AS BIGINT) AS urban_code,
    "widening_o",
    CAST("widening_p" AS BIGINT) AS widening_p,
    CAST("expansion_" AS DOUBLE) AS expansion,
    CAST("year_last_" AS BIGINT) AS year_last,
    CAST("year_last1" AS BIGINT) AS year_last1,
    "sample_id",
    CAST("is_sample" AS BIGINT) AS is_sample,
    CAST("shape_leng" AS DOUBLE) AS shape_leng
FROM "u-s-department-of-transportation-ccjq-w54n"
