-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "mcs150_date",
    strptime("add_date", '%Y%m%d')::DATE AS add_date,
    "status_code",
    CAST("dot_number" AS BIGINT) AS dot_number,
    CAST("dun_bradstreet_no" AS BIGINT) AS dun_bradstreet_no,
    "phy_omc_region",
    "safety_inv_terr",
    "carrier_operation",
    CAST("business_org_id" AS BIGINT) AS business_org_id,
    CAST("mcs150_mileage" AS BIGINT) AS mcs150_mileage,
    CAST("mcs150_mileage_year" AS BIGINT) AS mcs150_mileage_year,
    CAST("mcs151_mileage" AS BIGINT) AS mcs151_mileage,
    CAST("total_cars" AS BIGINT) AS total_cars,
    CAST("mcs150_update_code_id" AS BIGINT) AS mcs150_update_code_id,
    "prior_revoke_flag",
    CAST("prior_revoke_dot_number" AS BIGINT) AS prior_revoke_dot_number,
    "phone",
    "fax",
    "cell_phone",
    "company_officer_1",
    "company_officer_2",
    "business_org_desc",
    CAST("truck_units" AS BIGINT) AS truck_units,
    CAST("power_units" AS BIGINT) AS power_units,
    CAST("bus_units" AS BIGINT) AS bus_units,
    "fleetsize",
    CAST("review_id" AS BIGINT) AS review_id,
    CAST("recordable_crash_rate" AS DOUBLE) AS recordable_crash_rate,
    "mail_nationality_indicator",
    "phy_nationality_indicator",
    "phy_barrio",
    "mail_barrio",
    "carship",
    "docket1prefix",
    CAST("docket1" AS BIGINT) AS docket1,
    "docket2prefix",
    CAST("docket2" AS BIGINT) AS docket2,
    "docket3prefix",
    CAST("docket3" AS BIGINT) AS docket3,
    "pointnum",
    CAST("total_intrastate_drivers" AS BIGINT) AS total_intrastate_drivers,
    CAST("mcsipstep" AS BIGINT) AS mcsipstep,
    strptime("mcsipdate", '%Y%m%d')::DATE AS mcsipdate,
    "hm_ind",
    CAST("interstate_beyond_100_miles" AS BIGINT) AS interstate_beyond_100_miles,
    CAST("interstate_within_100_miles" AS BIGINT) AS interstate_within_100_miles,
    CAST("intrastate_beyond_100_miles" AS BIGINT) AS intrastate_beyond_100_miles,
    CAST("intrastate_within_100_miles" AS BIGINT) AS intrastate_within_100_miles,
    CAST("total_cdl" AS BIGINT) AS total_cdl,
    CAST("total_drivers" AS BIGINT) AS total_drivers,
    CAST("avg_drivers_leased_per_month" AS BIGINT) AS avg_drivers_leased_per_month,
    "classdef",
    "legal_name",
    "dba_name",
    "phy_street",
    "phy_city",
    "phy_country",
    "phy_state",
    "phy_zip",
    "phy_cnty",
    "carrier_mailing_street",
    "carrier_mailing_state",
    "carrier_mailing_city",
    "carrier_mailing_country",
    "carrier_mailing_zip",
    "carrier_mailing_cnty",
    strptime("carrier_mailing_und_date", '%Y%m%d')::DATE AS carrier_mailing_und_date,
    CAST("driver_inter_total" AS BIGINT) AS driver_inter_total,
    "email_address",
    "review_type",
    strptime("review_date", '%Y%m%d')::DATE AS review_date,
    "safety_rating",
    strptime("safety_rating_date", '%Y%m%d')::DATE AS safety_rating_date,
    "undeliv_phy",
    "crgo_genfreight",
    "crgo_household",
    "crgo_metalsheet",
    "crgo_motoveh",
    "crgo_drivetow",
    "crgo_logpole",
    "crgo_bldgmat",
    "crgo_mobilehome",
    "crgo_machlrg",
    "crgo_produce",
    "crgo_liqgas",
    "crgo_intermodal",
    "crgo_passengers",
    "crgo_oilfield",
    "crgo_livestock",
    "crgo_grainfeed",
    "crgo_coalcoke",
    "crgo_meat",
    "crgo_garbage",
    "crgo_usmail",
    "crgo_chem",
    "crgo_drybulk",
    "crgo_coldfood",
    "crgo_beverages",
    "crgo_paperprod",
    "crgo_utility",
    "crgo_farmsupp",
    "crgo_construct",
    "crgo_waterwell",
    "crgo_cargoothr",
    "crgo_cargoothr_desc",
    CAST("owntruck" AS BIGINT) AS owntruck,
    CAST("owntract" AS BIGINT) AS owntract,
    CAST("owntrail" AS BIGINT) AS owntrail,
    CAST("owncoach" AS BIGINT) AS owncoach,
    CAST("ownschool_1_8" AS BIGINT) AS ownschool_1_8,
    CAST("ownschool_9_15" AS BIGINT) AS ownschool_9_15,
    CAST("ownschool_16" AS BIGINT) AS ownschool_16,
    CAST("ownbus_16" AS BIGINT) AS ownbus_16,
    CAST("ownvan_1_8" AS BIGINT) AS ownvan_1_8,
    CAST("ownvan_9_15" AS BIGINT) AS ownvan_9_15,
    CAST("ownlimo_1_8" AS BIGINT) AS ownlimo_1_8,
    CAST("ownlimo_9_15" AS BIGINT) AS ownlimo_9_15,
    CAST("ownlimo_16" AS BIGINT) AS ownlimo_16,
    CAST("trmtruck" AS BIGINT) AS trmtruck,
    CAST("trmtract" AS BIGINT) AS trmtract,
    CAST("trmtrail" AS BIGINT) AS trmtrail,
    CAST("trmcoach" AS BIGINT) AS trmcoach,
    CAST("trmschool_1_8" AS BIGINT) AS trmschool_1_8,
    CAST("trmschool_9_15" AS BIGINT) AS trmschool_9_15,
    CAST("trmschool_16" AS BIGINT) AS trmschool_16,
    CAST("trmbus_16" AS BIGINT) AS trmbus_16,
    CAST("trmvan_1_8" AS BIGINT) AS trmvan_1_8,
    CAST("trmvan_9_15" AS BIGINT) AS trmvan_9_15,
    CAST("trmlimo_1_8" AS BIGINT) AS trmlimo_1_8,
    CAST("trmlimo_9_15" AS BIGINT) AS trmlimo_9_15,
    CAST("trmlimo_16" AS BIGINT) AS trmlimo_16,
    CAST("trptruck" AS BIGINT) AS trptruck,
    CAST("trptract" AS BIGINT) AS trptract,
    CAST("trptrail" AS BIGINT) AS trptrail,
    CAST("trpcoach" AS BIGINT) AS trpcoach,
    CAST("trpschool_1_8" AS BIGINT) AS trpschool_1_8,
    CAST("trpschool_9_15" AS BIGINT) AS trpschool_9_15,
    CAST("trpschool_16" AS BIGINT) AS trpschool_16,
    CAST("trpbus_16" AS BIGINT) AS trpbus_16,
    CAST("trpvan_1_8" AS BIGINT) AS trpvan_1_8,
    CAST("trpvan_9_15" AS BIGINT) AS trpvan_9_15,
    CAST("trplimo_1_8" AS BIGINT) AS trplimo_1_8,
    CAST("trplimo_9_15" AS BIGINT) AS trplimo_9_15,
    CAST("trplimo_16" AS BIGINT) AS trplimo_16,
    "docket1_status_code",
    "docket2_status_code",
    "docket3_status_code"
FROM "u-s-department-of-transportation-az4n-8mr2"
