-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No stable row key was verified in the raw profile; use this table as a source snapshot rather than assuming row identity across runs.
SELECT
    CAST("year" AS BIGINT) AS year,
    CAST("state_code" AS BIGINT) AS state_code,
    CAST("is_metric" AS BIGINT) AS is_metric,
    CAST("county_code" AS BIGINT) AS county_code,
    "section_id",
    CAST("is_sample" AS BIGINT) AS is_sample,
    CAST("is_donut" AS BIGINT) AS is_donut,
    CAST("is_grouped" AS BIGINT) AS is_grouped,
    "lrs_id",
    CAST("begin_lrs" AS DOUBLE) AS begin_lrs,
    CAST("end_lrs" AS DOUBLE) AS end_lrs,
    CAST("rural_urban" AS BIGINT) AS rural_urban,
    CAST("sampling_tech" AS BIGINT) AS sampling_tech,
    CAST("urban_code" AS BIGINT) AS urban_code,
    CAST("nonatt_code" AS BIGINT) AS nonatt_code,
    CAST("f_system" AS BIGINT) AS f_system,
    CAST("gf_system" AS BIGINT) AS gf_system,
    CAST("nhs" AS BIGINT) AS nhs,
    CAST("unbuilt_facility" AS BIGINT) AS unbuilt_facility,
    "inter_route_number",
    CAST("route_signing" AS BIGINT) AS route_signing,
    CAST("route_qualifier" AS BIGINT) AS route_qualifier,
    "route_number",
    CAST("ownership" AS BIGINT) AS ownership,
    CAST("special_systems" AS BIGINT) AS special_systems,
    CAST("type_facility" AS BIGINT) AS type_facility,
    CAST("truck_route" AS BIGINT) AS truck_route,
    CAST("toll" AS BIGINT) AS toll,
    CAST("section__length" AS DOUBLE) AS section_length,
    CAST("donut_volume_group" AS BIGINT) AS donut_volume_group,
    CAST("std_volume_group" AS BIGINT) AS std_volume_group,
    CAST("aadt" AS BIGINT) AS aadt,
    CAST("through_lanes" AS BIGINT) AS through_lanes,
    CAST("iri" AS BIGINT) AS iri,
    CAST("psr" AS DOUBLE) AS psr,
    CAST("hov" AS BIGINT) AS hov,
    CAST("surv_a" AS BIGINT) AS surv_a,
    CAST("surv_b" AS BIGINT) AS surv_b,
    CAST("surv_c" AS BIGINT) AS surv_c,
    CAST("surv_d" AS BIGINT) AS surv_d,
    CAST("surv_e" AS BIGINT) AS surv_e,
    CAST("surv_f" AS BIGINT) AS surv_f,
    CAST("surv_g" AS BIGINT) AS surv_g,
    CAST("surv_h" AS BIGINT) AS surv_h,
    CAST("surv_i" AS BIGINT) AS surv_i
FROM "u-s-department-of-transportation-w95q-6nqw"
