-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No stable row key was verified in the raw profile; use this table as a source snapshot rather than assuming row identity across runs.
SELECT
    "agency",
    "_5_digit_ntd_id" AS 5_digit_ntd_id,
    "reporter_type",
    "organization_type",
    "city",
    "state",
    CAST("report_year" AS BIGINT) AS report_year,
    CAST("agency_voms" AS BIGINT) AS agency_voms,
    "mode",
    "mode_name",
    "type_of_service",
    CAST("mode_voms" AS BIGINT) AS mode_voms,
    "mode_voms_questionable",
    "primary_uza_code",
    "primary_uza_name",
    CAST("primary_uza_area_sq_miles" AS DOUBLE) AS primary_uza_area_sq_miles,
    CAST("primary_uza_population" AS BIGINT) AS primary_uza_population,
    CAST("service_area_sq_miles" AS BIGINT) AS service_area_sq_miles,
    CAST("service_area_population" AS BIGINT) AS service_area_population,
    "time_period",
    "time_service_begins",
    "time_service_ends",
    CAST("actual_vehicles_passenger_car_miles" AS BIGINT) AS actual_vehicles_passenger_car_miles,
    "vehicle_miles_questionable",
    CAST("actual_vehicles_passenger_car_revenue_miles" AS BIGINT) AS actual_vehicles_passenger_car_revenue_miles,
    "vehicle_revenue_miles_questionable",
    CAST("actual_vehicles_passenger_deadhead_miles" AS BIGINT) AS actual_vehicles_passenger_deadhead_miles,
    "deadhead_miles_questionable",
    CAST("scheduled_vehicles_passenger_car_revenue_miles" AS BIGINT) AS scheduled_vehicles_passenger_car_revenue_miles,
    "scheduled_revenue_miles_questionable",
    CAST("actual_vehicles_passenger_car_hours" AS BIGINT) AS actual_vehicles_passenger_car_hours,
    "vehicle_hours_questionable",
    CAST("actual_vehicles_passenger_car_revenue_hours" AS BIGINT) AS actual_vehicles_passenger_car_revenue_hours,
    "vehicle_revenue_hours_questionable",
    CAST("actual_vehicles_passenger_car_deadhead_hours" AS BIGINT) AS actual_vehicles_passenger_car_deadhead_hours,
    "deadhead_hours_questionable",
    CAST("charter_service_hours" AS BIGINT) AS charter_service_hours,
    CAST("school_bus_hours" AS BIGINT) AS school_bus_hours,
    CAST("trains_in_operation" AS BIGINT) AS trains_in_operation,
    "trains_in_operation_questionable",
    CAST("train_miles" AS BIGINT) AS train_miles,
    "train_miles_questionable",
    CAST("train_revenue_miles" AS BIGINT) AS train_revenue_miles,
    "train_revenue_miles_questionable",
    CAST("train_deadhead_miles" AS BIGINT) AS train_deadhead_miles,
    CAST("train_hours" AS BIGINT) AS train_hours,
    "train_hours_questionable",
    CAST("train_revenue_hours" AS BIGINT) AS train_revenue_hours,
    "train_revenue_hours_questionable",
    CAST("train_deadhead_hours" AS BIGINT) AS train_deadhead_hours,
    CAST("unlinked_passenger_trips_upt" AS BIGINT) AS unlinked_passenger_trips_upt,
    "unlinked_passenger_trips_questionable",
    CAST("ada_upt" AS BIGINT) AS ada_upt,
    CAST("sponsored_service_upt" AS BIGINT) AS sponsored_service_upt,
    CAST("passenger_miles" AS BIGINT) AS passenger_miles,
    "passenger_miles_questionable",
    CAST("directional_route_miles" AS DOUBLE) AS directional_route_miles,
    "directional_route_miles_questionable",
    CAST("brt_non_statutory_mixed_traffic" AS DOUBLE) AS brt_non_statutory_mixed_traffic,
    CAST("mixed_traffic_right_of_way" AS DOUBLE) AS mixed_traffic_right_of_way,
    CAST("days_of_service_operated" AS BIGINT) AS days_of_service_operated,
    CAST("days_not_operated_strikes" AS BIGINT) AS days_not_operated_strikes,
    CAST("days_not_operated_emergencies" AS BIGINT) AS days_not_operated_emergencies,
    CAST("average_speed" AS DOUBLE) AS average_speed,
    "average_speed_questionable",
    "average_passenger_trip_length_aptl_" AS average_passenger_trip_length_aptl,
    "aptl_questionable",
    CAST("passengers_per_hour" AS BIGINT) AS passengers_per_hour,
    "passengers_per_hour_questionable"
FROM "u-s-department-of-transportation-wwdp-t4re"
