-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "the_geom",
    CAST("objectid" AS BIGINT) AS objectid,
    "crossing",
    "effdate",
    CAST("edate" AS BIGINT) AS edate,
    CAST("reason" AS BIGINT) AS reason,
    CAST("statecode" AS BIGINT) AS statecode,
    CAST("countycode" AS BIGINT) AS countycode,
    "stcyfips",
    "citycd",
    CAST("type" AS BIGINT) AS type,
    "railroad",
    "rrdiv",
    "rrsubdiv",
    "highway",
    "street",
    "ttstn",
    "milepost",
    CAST("typexing" AS BIGINT) AS typexing,
    CAST("posxing" AS BIGINT) AS posxing,
    CAST("prvcat" AS BIGINT) AS prvcat,
    CAST("prvind" AS BIGINT) AS prvind,
    "prvsign",
    CAST("init" AS BIGINT) AS init,
    CAST("latitude" AS DOUBLE) AS latitude,
    CAST("longitud" AS DOUBLE) AS longitud,
    CAST("llsource" AS BIGINT) AS llsource,
    CAST("whistban" AS BIGINT) AS whistban,
    "rrcont",
    "polcont",
    "inv_link",
    "acc_link",
    "ttstnnam",
    CAST("xpurpose" AS BIGINT) AS xpurpose,
    "operatingrailroadcode",
    "operatingrailroadtype",
    CAST("daythru" AS BIGINT) AS daythru,
    CAST("nghtthru" AS BIGINT) AS nghtthru,
    CAST("maintrk" AS BIGINT) AS maintrk,
    CAST("sidingtrk" AS BIGINT) AS sidingtrk,
    CAST("yardtrk" AS BIGINT) AS yardtrk,
    CAST("transittrk" AS BIGINT) AS transittrk,
    CAST("industrytrk" AS BIGINT) AS industrytrk,
    CAST("othrtrk" AS BIGINT) AS othrtrk,
    CAST("wdcode" AS BIGINT) AS wdcode,
    CAST("revisiondate" AS TIMESTAMP) AS revisiondate,
    CAST("lastupdated" AS TIMESTAMP) AS lastupdated,
    CAST("crossingclosed" AS BIGINT) AS crossingclosed,
    "aadt",
    "aadtyear",
    "statename",
    "stateab",
    "countyname",
    "cityname"
FROM "u-s-department-of-transportation-nw2s-ygjq"
