-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("dot_number" AS BIGINT) AS dot_number,
    "legal_name",
    "dba_name",
    "carrier_operation",
    CAST("hm_flag" AS BOOLEAN) AS hm_flag,
    CAST("pc_flag" AS BOOLEAN) AS pc_flag,
    "phy_street",
    "phy_city",
    "phy_state",
    "phy_zip",
    "phy_country",
    "mailing_street",
    "mailing_city",
    "mailing_state",
    "mailing_zip",
    "mailing_country",
    "telephone",
    "fax",
    "email_address",
    "mcs150_date",
    CAST("mcs150_mileage" AS BIGINT) AS mcs150_mileage,
    CAST("mcs150_mileage_year" AS BIGINT) AS mcs150_mileage_year,
    "add_date",
    "oic_state",
    CAST("nbr_power_unit" AS BIGINT) AS nbr_power_unit,
    CAST("driver_total" AS BIGINT) AS driver_total,
    CAST("recent_mileage" AS BIGINT) AS recent_mileage,
    CAST("recent_mileage_year" AS BIGINT) AS recent_mileage_year,
    CAST("vmt_source_id" AS BIGINT) AS vmt_source_id,
    CAST("private_only" AS BOOLEAN) AS private_only,
    CAST("authorized_for_hire" AS BOOLEAN) AS authorized_for_hire,
    CAST("exempt_for_hire" AS BOOLEAN) AS exempt_for_hire,
    CAST("private_property" AS BOOLEAN) AS private_property,
    CAST("private_passenger_business" AS BOOLEAN) AS private_passenger_business,
    CAST("private_passenger_nonbusiness" AS BOOLEAN) AS private_passenger_nonbusiness,
    CAST("migrant" AS BOOLEAN) AS migrant,
    CAST("us_mail" AS BOOLEAN) AS us_mail,
    CAST("federal_government" AS BOOLEAN) AS federal_government,
    CAST("state_government" AS BOOLEAN) AS state_government,
    CAST("local_government" AS BOOLEAN) AS local_government,
    CAST("indian_tribe" AS BOOLEAN) AS indian_tribe,
    "op_other"
FROM "u-s-department-of-transportation-kjg3-diqy"
