-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("aadt" AS BIGINT) AS aadt,
    CAST("aadt_combination" AS BIGINT) AS aadt_combination,
    CAST("aadt_d" AS TIMESTAMP) AS aadt_d,
    CAST("aadt_single_unit" AS BIGINT) AS aadt_single_unit,
    CAST("access_control" AS BIGINT) AS access_control,
    CAST("at_grade_other" AS BIGINT) AS at_grade_other,
    CAST("base_thickness" AS BIGINT) AS base_thickness,
    CAST("base_type" AS BIGINT) AS base_type,
    CAST("begin_point" AS DOUBLE) AS begin_point,
    CAST("counter_peak_lanes" AS BIGINT) AS counter_peak_lanes,
    CAST("county_id" AS BIGINT) AS county_id,
    CAST("cracking_percent" AS DOUBLE) AS cracking_percent,
    CAST("cracking_percent_d" AS TIMESTAMP) AS cracking_percent_d,
    CAST("curves_a" AS DOUBLE) AS curves_a,
    CAST("curves_b" AS DOUBLE) AS curves_b,
    CAST("curves_c" AS DOUBLE) AS curves_c,
    CAST("curves_d" AS DOUBLE) AS curves_d,
    CAST("curves_e" AS DOUBLE) AS curves_e,
    CAST("curves_f" AS DOUBLE) AS curves_f,
    CAST("dir_factor" AS BIGINT) AS dir_factor,
    CAST("dir_through_lanes" AS BIGINT) AS dir_through_lanes,
    CAST("end_point" AS DOUBLE) AS end_point,
    CAST("facility_type" AS BIGINT) AS facility_type,
    CAST("faulting" AS DOUBLE) AS faulting,
    strptime("faulting_d", '%Y-%m-%d')::DATE AS faulting_d,
    CAST("future_aadt_year" AS TIMESTAMP) AS future_aadt_year,
    CAST("f_system" AS BIGINT) AS f_system,
    CAST("future_aadt" AS BIGINT) AS future_aadt,
    CAST("grades_a" AS DOUBLE) AS grades_a,
    CAST("grades_b" AS DOUBLE) AS grades_b,
    CAST("grades_c" AS DOUBLE) AS grades_c,
    CAST("grades_d" AS DOUBLE) AS grades_d,
    CAST("grades_e" AS DOUBLE) AS grades_e,
    CAST("grades_f" AS DOUBLE) AS grades_f,
    CAST("iri" AS DOUBLE) AS iri,
    CAST("iri_d" AS TIMESTAMP) AS iri_d,
    CAST("is_restricted" AS BOOLEAN) AS is_restricted,
    CAST("k_factor" AS BIGINT) AS k_factor,
    CAST("lane_width" AS BIGINT) AS lane_width,
    CAST("last_overlay_thickness" AS DOUBLE) AS last_overlay_thickness,
    CAST("maintenance_operations" AS BIGINT) AS maintenance_operations,
    CAST("managed_lanes" AS BIGINT) AS managed_lanes,
    CAST("managed_lanes_type" AS BIGINT) AS managed_lanes_type,
    CAST("median_type" AS BIGINT) AS median_type,
    CAST("median_width" AS BIGINT) AS median_width,
    CAST("nhfn" AS BIGINT) AS nhfn,
    CAST("nhs" AS BIGINT) AS nhs,
    CAST("nn" AS BIGINT) AS nn,
    CAST("number_signals" AS BIGINT) AS number_signals,
    CAST("ownership" AS BIGINT) AS ownership,
    CAST("pct_dh_combination" AS DOUBLE) AS pct_dh_combination,
    CAST("pct_dh_single_unit" AS DOUBLE) AS pct_dh_single_unit,
    CAST("pct_green_time" AS BIGINT) AS pct_green_time,
    CAST("pct_pass_sight" AS BIGINT) AS pct_pass_sight,
    CAST("peak_lanes" AS BIGINT) AS peak_lanes,
    CAST("peak_parking" AS BIGINT) AS peak_parking,
    CAST("psr" AS DOUBLE) AS psr,
    strptime("psr_d", '%Y-%m-%d')::DATE AS psr_d,
    "route_id",
    CAST("route_number" AS BIGINT) AS route_number,
    CAST("route_qualifier" AS BIGINT) AS route_qualifier,
    CAST("route_signing" AS BIGINT) AS route_signing,
    CAST("rutting" AS DOUBLE) AS rutting,
    CAST("rutting_d" AS TIMESTAMP) AS rutting_d,
    "routename",
    "sample_id",
    CAST("shoulder_type" AS BIGINT) AS shoulder_type,
    CAST("shoulder_width_l" AS BIGINT) AS shoulder_width_l,
    CAST("shoulder_width_r" AS BIGINT) AS shoulder_width_r,
    CAST("signal_type" AS BIGINT) AS signal_type,
    CAST("soil_type" AS BIGINT) AS soil_type,
    CAST("speed_limit" AS BIGINT) AS speed_limit,
    CAST("srid" AS BIGINT) AS srid,
    CAST("stop_signs" AS BIGINT) AS stop_signs,
    CAST("strahnet_type" AS BIGINT) AS strahnet_type,
    CAST("structure_type" AS BIGINT) AS structure_type,
    CAST("surface_type" AS BIGINT) AS surface_type,
    CAST("sectionlength" AS DOUBLE) AS sectionlength,
    CAST("shapeid" AS BIGINT) AS shapeid,
    CAST("stateid" AS BIGINT) AS stateid,
    CAST("terrain_type" AS BIGINT) AS terrain_type,
    CAST("thickness_flexible" AS DOUBLE) AS thickness_flexible,
    CAST("thickness_rigid" AS DOUBLE) AS thickness_rigid,
    CAST("through_lanes" AS BIGINT) AS through_lanes,
    CAST("toll_id" AS BIGINT) AS toll_id,
    CAST("travel_time_code" AS BIGINT) AS travel_time_code,
    CAST("turn_lanes_l" AS BIGINT) AS turn_lanes_l,
    CAST("turn_lanes_r" AS BIGINT) AS turn_lanes_r,
    CAST("urban_id" AS BIGINT) AS urban_id,
    "widening_obstacle",
    CAST("widening_potential" AS BIGINT) AS widening_potential,
    CAST("year_last_construction" AS TIMESTAMP) AS year_last_construction,
    CAST("year_last_improvement" AS TIMESTAMP) AS year_last_improvement,
    CAST("year_record" AS BIGINT) AS year_record,
    "line"
FROM "u-s-department-of-transportation-42um-tgh5"
