-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No stable row key was verified in the raw profile; use this table as a source snapshot rather than assuming row identity across runs.
SELECT
    "the_geom",
    "placeid",
    "yearplaceid",
    "city",
    "state",
    "citystate",
    CAST("year" AS BIGINT) AS year,
    CAST("month" AS BIGINT) AS month,
    "docksuspended",
    "dockclosed",
    "docklesssuspended",
    "docklessclosed",
    "scootersuspended",
    "scooterclosed",
    CAST("dockid" AS DOUBLE) AS dockid,
    CAST("stationct" AS BIGINT) AS stationct,
    CAST("stationct_pct" AS DOUBLE) AS stationct_pct,
    CAST("stationct_bin" AS BIGINT) AS stationct_bin,
    CAST("dockct" AS BIGINT) AS dockct,
    "docknm",
    "docknmsuspended",
    CAST("docklessct" AS BIGINT) AS docklessct,
    CAST("docklessct_bin" AS BIGINT) AS docklessct_bin,
    "docklessnm",
    "docklessnmsuspended",
    CAST("scooterct" AS BIGINT) AS scooterct,
    CAST("scooterct_bin" AS BIGINT) AS scooterct_bin,
    "scooternm",
    "scooternmsuspended",
    CAST("lat" AS DOUBLE) AS lat,
    CAST("lon" AS DOUBLE) AS lon,
    "type",
    CAST("suspscooterct" AS BIGINT) AS suspscooterct,
    CAST("closedscooterct" AS BIGINT) AS closedscooterct,
    CAST("suspdocklessct" AS BIGINT) AS suspdocklessct,
    CAST("closeddocklessct" AS BIGINT) AS closeddocklessct,
    CAST("closeddockct" AS BIGINT) AS closeddockct,
    CAST("suspdockct" AS BIGINT) AS suspdockct,
    "docknotes",
    "docklessnotes",
    "scooternotes",
    "docksuspendednotes",
    "docklesssuspendednotes",
    "scootersuspendednotes",
    "dockclosednotes",
    "docklessclosednotes",
    "scooterclosednotes"
FROM "u-s-department-of-transportation-8cjz-h8bz"
