-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "change_date",
    CAST("inspection_id" AS BIGINT) AS inspection_id,
    CAST("dot_number" AS BIGINT) AS dot_number,
    "report_state",
    "report_number",
    strptime("insp_date", '%Y%m%d')::DATE AS insp_date,
    "insp_start_time",
    "insp_end_time",
    strptime("registration_date", '%Y%m%d')::DATE AS registration_date,
    "region",
    "ci_status_code",
    "location",
    "location_desc",
    "county_code_state",
    "county_code",
    CAST("insp_level_id" AS BIGINT) AS insp_level_id,
    "service_center",
    CAST("census_source_id" AS BIGINT) AS census_source_id,
    "insp_facility",
    "shipper_name",
    "shipping_paper_number",
    "cargo_tank",
    "hazmat_placard_req",
    "snet_version_number",
    "snet_search_date",
    "alcohol_control_sub",
    "drug_intrdctn_search",
    CAST("drug_intrdctn_arrests" AS BIGINT) AS drug_intrdctn_arrests,
    "size_weight_enf",
    "traffic_enf",
    "local_enf_jurisdiction",
    "pen_cen_match",
    "final_status_date",
    "post_acc_ind",
    CAST("gross_comb_veh_wt" AS BIGINT) AS gross_comb_veh_wt,
    CAST("viol_total" AS BIGINT) AS viol_total,
    CAST("oos_total" AS BIGINT) AS oos_total,
    CAST("driver_viol_total" AS BIGINT) AS driver_viol_total,
    CAST("driver_oos_total" AS BIGINT) AS driver_oos_total,
    CAST("vehicle_viol_total" AS BIGINT) AS vehicle_viol_total,
    CAST("vehicle_oos_total" AS BIGINT) AS vehicle_oos_total,
    CAST("hazmat_viol_total" AS BIGINT) AS hazmat_viol_total,
    CAST("hazmat_oos_total" AS BIGINT) AS hazmat_oos_total,
    CAST("snet_sequence_id" AS BIGINT) AS snet_sequence_id,
    "transaction_code",
    "transaction_date",
    "upload_date",
    CAST("upload_first_byte" AS BIGINT) AS upload_first_byte,
    "upload_dot_number",
    "upload_search_indicator",
    "census_search_date",
    "snet_input_date",
    "source_office",
    "mcmis_add_date",
    "insp_carrier_name",
    "insp_carrier_street",
    "insp_carrier_city",
    "insp_carrier_state",
    "insp_carrier_zip_code",
    "insp_colonia",
    CAST("docket_number" AS BIGINT) AS docket_number,
    "insp_interstate",
    "insp_carrier_state_id"
FROM "u-s-department-of-transportation-fx4q-ay7w"
