-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No stable row key was verified in the raw profile; use this table as a source snapshot rather than assuming row identity across runs.
SELECT
    "carrier",
    CAST("year" AS BIGINT) AS year,
    CAST("reporting_month" AS TIMESTAMP) AS reporting_month,
    CAST("total_departures" AS BIGINT) AS total_departures,
    CAST("total_passengers" AS BIGINT) AS total_passengers,
    CAST("total_seats" AS BIGINT) AS total_seats,
    CAST("total_load_factor" AS DOUBLE) AS total_load_factor,
    CAST("total_passengers_flight" AS DOUBLE) AS total_passengers_flight,
    CAST("total_seats_flight" AS BIGINT) AS total_seats_flight,
    CAST("total_distance_flight_sm" AS BIGINT) AS total_distance_flight_sm,
    CAST("total_distance_passenger" AS BIGINT) AS total_distance_passenger,
    CAST("total_payload_lbs" AS BIGINT) AS total_payload_lbs,
    CAST("total_freight_lbs" AS BIGINT) AS total_freight_lbs,
    CAST("total_mail_lbs" AS BIGINT) AS total_mail_lbs,
    CAST("domestic_departures" AS BIGINT) AS domestic_departures,
    CAST("domestic_passengers" AS BIGINT) AS domestic_passengers,
    CAST("domestic_seats" AS BIGINT) AS domestic_seats,
    CAST("domestic_load_factor" AS DOUBLE) AS domestic_load_factor,
    CAST("domestic_passengers_flight" AS DOUBLE) AS domestic_passengers_flight,
    CAST("domestic_seats_flight" AS BIGINT) AS domestic_seats_flight,
    CAST("domestic_distance_flight" AS BIGINT) AS domestic_distance_flight,
    CAST("domestic_distance_passenger" AS BIGINT) AS domestic_distance_passenger,
    CAST("domestic_payload_lbs" AS BIGINT) AS domestic_payload_lbs,
    CAST("domestic_freight_lbs" AS BIGINT) AS domestic_freight_lbs,
    CAST("domestic_mail_lbs" AS BIGINT) AS domestic_mail_lbs,
    CAST("outbound_international" AS BIGINT) AS outbound_international,
    CAST("outbound_international_1" AS BIGINT) AS outbound_international_1,
    CAST("outbound_international_seats" AS BIGINT) AS outbound_international_seats,
    CAST("outbound_international_load" AS DOUBLE) AS outbound_international_load,
    CAST("outbound_international_2" AS DOUBLE) AS outbound_international_2,
    CAST("outbound_international_seats_1" AS BIGINT) AS outbound_international_seats_1,
    CAST("outbound_international_3" AS BIGINT) AS outbound_international_3,
    CAST("outbound_international_4" AS BIGINT) AS outbound_international_4,
    CAST("outbound_international_payload" AS BIGINT) AS outbound_international_payload,
    CAST("outbound_international_freight" AS BIGINT) AS outbound_international_freight,
    CAST("outbound_international_mail" AS BIGINT) AS outbound_international_mail,
    CAST("inbound_international" AS BIGINT) AS inbound_international,
    CAST("inbound_international_1" AS BIGINT) AS inbound_international_1,
    CAST("inbound_international_seats" AS BIGINT) AS inbound_international_seats,
    CAST("inbound_international_load" AS DOUBLE) AS inbound_international_load,
    CAST("inbound_international_2" AS DOUBLE) AS inbound_international_2,
    CAST("inbound_international_seats_1" AS BIGINT) AS inbound_international_seats_1,
    CAST("inbound_international_distance" AS BIGINT) AS inbound_international_distance,
    CAST("inbound_international_distance_1" AS BIGINT) AS inbound_international_distance_1,
    CAST("inbound_international_payload" AS BIGINT) AS inbound_international_payload,
    CAST("inbound_international_freight" AS BIGINT) AS inbound_international_freight,
    CAST("inbound_international_mail" AS BIGINT) AS inbound_international_mail
FROM "u-s-department-of-transportation-q4tb-tbff"
