-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    CAST("geoid" AS BIGINT) AS geoid,
    CAST("fips_state" AS BIGINT) AS fips_state,
    CAST("fips_county" AS BIGINT) AS fips_county,
    "st_code",
    "ctyname",
    CAST("spatial_id" AS BIGINT) AS spatial_id,
    "microtypeid",
    CAST("microtype" AS BIGINT) AS microtype,
    "geotype",
    CAST("broadband" AS BIGINT) AS broadband,
    CAST("pollutant_count" AS BIGINT) AS pollutant_count,
    CAST("pct_ag_land" AS DOUBLE) AS pct_ag_land,
    CAST("pct_water" AS DOUBLE) AS pct_water,
    CAST("dev_intensity" AS DOUBLE) AS dev_intensity,
    CAST("circuity_avg" AS DOUBLE) AS circuity_avg,
    CAST("dead_end_proportion" AS DOUBLE) AS dead_end_proportion,
    CAST("intersection_density_km" AS DOUBLE) AS intersection_density_km,
    CAST("self_loop_proportion" AS DOUBLE) AS self_loop_proportion,
    CAST("street_density_km" AS DOUBLE) AS street_density_km,
    CAST("street_length_avg" AS DOUBLE) AS street_length_avg,
    CAST("pct_jobs_manuf" AS DOUBLE) AS pct_jobs_manuf,
    CAST("pct_jobs_mining" AS DOUBLE) AS pct_jobs_mining,
    CAST("avg_iri" AS DOUBLE) AS avg_iri,
    CAST("pct_controlf" AS DOUBLE) AS pct_controlf,
    CAST("pct_controlp" AS DOUBLE) AS pct_controlp,
    CAST("pct_aadt_combi" AS DOUBLE) AS pct_aadt_combi,
    CAST("aadt_combi_per_lm" AS DOUBLE) AS aadt_combi_per_lm,
    CAST("lane_miles_sqkm" AS DOUBLE) AS lane_miles_sqkm,
    CAST("pop_density" AS DOUBLE) AS pop_density,
    CAST("job_density" AS DOUBLE) AS job_density,
    CAST("road_grade" AS DOUBLE) AS road_grade,
    CAST("lanemeters_per_capita" AS DOUBLE) AS lanemeters_per_capita,
    CAST("jobs_housing_bal" AS DOUBLE) AS jobs_housing_bal,
    CAST("pct_hiway" AS DOUBLE) AS pct_hiway,
    CAST("pct_local_roads" AS DOUBLE) AS pct_local_roads,
    CAST("pct_mid_roads" AS DOUBLE) AS pct_mid_roads,
    CAST("pct_trips_bin1" AS DOUBLE) AS pct_trips_bin1,
    CAST("pct_trips_bin2" AS DOUBLE) AS pct_trips_bin2,
    CAST("pct_trips_bin3" AS DOUBLE) AS pct_trips_bin3,
    CAST("pct_trips_bin4" AS DOUBLE) AS pct_trips_bin4,
    CAST("sink_mag" AS DOUBLE) AS sink_mag,
    CAST("emp_centers" AS BIGINT) AS emp_centers,
    CAST("hhi_normalized" AS DOUBLE) AS hhi_normalized,
    CAST("pct_microtype_1" AS DOUBLE) AS pct_microtype_1
FROM "u-s-department-of-transportation-guuc-d2rv"
