-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "quarter",
    CAST("nhcci" AS DOUBLE) AS nhcci,
    CAST("nhcci_seasonally_adjusted" AS DOUBLE) AS nhcci_seasonally_adjusted,
    CAST("grp9_pct_change_grading" AS DOUBLE) AS grp9_pct_change_grading,
    CAST("grp9_pct_change_bridge" AS DOUBLE) AS grp9_pct_change_bridge,
    CAST("grp9_pct_change_asphalt" AS DOUBLE) AS grp9_pct_change_asphalt,
    CAST("grp9_pct_change_concrete" AS DOUBLE) AS grp9_pct_change_concrete,
    CAST("grp9_pct_change_base_stone" AS DOUBLE) AS grp9_pct_change_base_stone,
    CAST("grp9_pct_change_drainage" AS DOUBLE) AS grp9_pct_change_drainage,
    CAST("grp9_pct_change_traffic" AS DOUBLE) AS grp9_pct_change_traffic,
    CAST("grp9_pct_change_electrical" AS DOUBLE) AS grp9_pct_change_electrical,
    CAST("grp9_pct_change_utilities" AS DOUBLE) AS grp9_pct_change_utilities,
    CAST("grp13_pct_change_grading" AS DOUBLE) AS grp13_pct_change_grading,
    CAST("grp13_pct_change_bridge" AS DOUBLE) AS grp13_pct_change_bridge,
    CAST("grp13_pct_change_asphalt" AS DOUBLE) AS grp13_pct_change_asphalt,
    CAST("grp13_pct_change_concrete" AS DOUBLE) AS grp13_pct_change_concrete,
    CAST("grp13_pct_change_base_stone" AS DOUBLE) AS grp13_pct_change_base_stone,
    CAST("grp13_pct_change_drainage" AS DOUBLE) AS grp13_pct_change_drainage,
    CAST("grp13_pct_change_traffic" AS DOUBLE) AS grp13_pct_change_traffic,
    CAST("grp13_pct_change_erosion" AS DOUBLE) AS grp13_pct_change_erosion,
    CAST("grp13_pct_change_clearing" AS DOUBLE) AS grp13_pct_change_clearing,
    CAST("grp13_pct_change_electrical" AS DOUBLE) AS grp13_pct_change_electrical,
    CAST("grp13_pct_change_structures" AS DOUBLE) AS grp13_pct_change_structures,
    CAST("grp13_pct_change_utility" AS DOUBLE) AS grp13_pct_change_utility,
    CAST("grp13_pct_change_equipment" AS DOUBLE) AS grp13_pct_change_equipment,
    CAST("grp25_pct_change_grading" AS DOUBLE) AS grp25_pct_change_grading,
    CAST("grp25_pct_change_bridge" AS DOUBLE) AS grp25_pct_change_bridge,
    CAST("grp25_pct_change_asphalt" AS DOUBLE) AS grp25_pct_change_asphalt,
    CAST("grp25_pct_change_concrete" AS DOUBLE) AS grp25_pct_change_concrete,
    CAST("grp25_pct_change_concrete_1" AS DOUBLE) AS grp25_pct_change_concrete_1,
    CAST("grp25_pct_change_concrete_2" AS DOUBLE) AS grp25_pct_change_concrete_2,
    CAST("grp25_pct_change_base_stone" AS DOUBLE) AS grp25_pct_change_base_stone,
    CAST("grp25_pct_change_drainage_pipe" AS DOUBLE) AS grp25_pct_change_drainage_pipe,
    CAST("grp25_pct_change_drainage_inlets" AS DOUBLE) AS grp25_pct_change_drainage_inlets,
    CAST("grp25_pct_change_underdrain" AS DOUBLE) AS grp25_pct_change_underdrain,
    CAST("grp25_pct_change_traffic" AS DOUBLE) AS grp25_pct_change_traffic,
    CAST("grp25_pct_change_guard_rail" AS DOUBLE) AS grp25_pct_change_guard_rail,
    CAST("grp25_pct_change_fencing" AS DOUBLE) AS grp25_pct_change_fencing,
    CAST("grp25_pct_change_signs" AS DOUBLE) AS grp25_pct_change_signs,
    CAST("grp25_pct_change_striping" AS DOUBLE) AS grp25_pct_change_striping,
    CAST("grp25_pct_change_clearing" AS DOUBLE) AS grp25_pct_change_clearing,
    CAST("grp25_pct_change_equipment" AS DOUBLE) AS grp25_pct_change_equipment,
    CAST("grp25_pct_change_grassing" AS DOUBLE) AS grp25_pct_change_grassing,
    CAST("grp25_pct_change_erosion" AS DOUBLE) AS grp25_pct_change_erosion,
    CAST("grp25_pct_change_retaining" AS DOUBLE) AS grp25_pct_change_retaining,
    CAST("grp25_pct_change_misc_stone" AS DOUBLE) AS grp25_pct_change_misc_stone,
    CAST("grp25_pct_change_painting" AS DOUBLE) AS grp25_pct_change_painting,
    CAST("grp25_pct_change_buildings" AS DOUBLE) AS grp25_pct_change_buildings,
    CAST("grp25_pct_change_electrical" AS DOUBLE) AS grp25_pct_change_electrical,
    CAST("grp25_pct_change_utility" AS DOUBLE) AS grp25_pct_change_utility
FROM "u-s-department-of-transportation-r94d-n4f9"
