-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No stable row key was verified in the raw profile; use this table as a source snapshot rather than assuming row identity across runs.
SELECT
    "agency",
    "city",
    "state",
    "ntd_id",
    "organization_type",
    "reporter_type",
    CAST("report_year" AS BIGINT) AS report_year,
    "uace_code",
    "uza_name",
    CAST("primary_uza_population" AS BIGINT) AS primary_uza_population,
    CAST("agency_voms" AS BIGINT) AS agency_voms,
    "mode",
    "mode_name",
    "type_of_service",
    CAST("mode_voms" AS BIGINT) AS mode_voms,
    CAST("at_grade_ballast_including" AS DOUBLE) AS at_grade_ballast_including,
    "at_grade_ballast_including_1",
    CAST("at_grade_in_street_embedded" AS DOUBLE) AS at_grade_in_street_embedded,
    "at_grade_in_street_embedded_1",
    CAST("elevated_retained_fill" AS DOUBLE) AS elevated_retained_fill,
    "elevated_retained_fill_q",
    CAST("elevated_concrete" AS DOUBLE) AS elevated_concrete,
    "elevated_concrete_q",
    CAST("elevated_steel_viaduct_or" AS DOUBLE) AS elevated_steel_viaduct_or,
    "elevated_steel_viaduct_or_1",
    CAST("below_grade_retained_cut" AS DOUBLE) AS below_grade_retained_cut,
    "below_grade_retained_cut_1",
    CAST("below_grade_cut_and_cover" AS DOUBLE) AS below_grade_cut_and_cover,
    "below_grade_cut_and_cover_1",
    CAST("below_grade_bored_or_blasted" AS DOUBLE) AS below_grade_bored_or_blasted,
    "below_grade_bored_or_blasted_1",
    CAST("below_grade_submerged_tube" AS DOUBLE) AS below_grade_submerged_tube,
    "below_grade_submerged_tube_1",
    CAST("total_track_miles" AS DOUBLE) AS total_track_miles,
    "total_track_miles_q",
    CAST("single_turnout" AS BIGINT) AS single_turnout,
    "single_turnout_q",
    CAST("grade_crossings" AS BIGINT) AS grade_crossings,
    "grade_crossings_q",
    CAST("single_crossover" AS BIGINT) AS single_crossover,
    "single_crossover_q",
    CAST("double_crossover" AS BIGINT) AS double_crossover,
    "double_crossover_q",
    CAST("lapped_turnout" AS BIGINT) AS lapped_turnout,
    "lapped_turnout_q",
    CAST("slip_switch" AS BIGINT) AS slip_switch,
    "slip_switch_q",
    CAST("rail_crossings" AS BIGINT) AS rail_crossings,
    "rail_crossings_q",
    CAST("exclusive_fixed_guideway" AS DOUBLE) AS exclusive_fixed_guideway,
    "exclusive_fixed_guideway_1",
    CAST("exclusive_high_intensity" AS DOUBLE) AS exclusive_high_intensity,
    "exclusive_high_intensity_1",
    CAST("controlled_access_high" AS DOUBLE) AS controlled_access_high,
    "controlled_access_high_1",
    CAST("total_miles" AS DOUBLE) AS total_miles
FROM "u-s-department-of-transportation-fzbb-f6kc"
