-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No stable row key was verified in the raw profile; use this table as a source snapshot rather than assuming row identity across runs.
SELECT
    CAST("operator_id" AS BIGINT) AS operator_id,
    "operator_name",
    "op_strcity",
    "op_strzip",
    "url",
    "op_country",
    CAST("ticket_revenue" AS DOUBLE) AS ticket_revenue,
    CAST("private_contract_revenue" AS DOUBLE) AS private_contract_revenue,
    CAST("advertising_revenue" AS DOUBLE) AS advertising_revenue,
    CAST("public_contract_revenue" AS DOUBLE) AS public_contract_revenue,
    CAST("federal_funding_revenue" AS DOUBLE) AS federal_funding_revenue,
    CAST("state_funding_revenue" AS DOUBLE) AS state_funding_revenue,
    CAST("local_funding_revenue" AS DOUBLE) AS local_funding_revenue,
    CAST("federal_state_local" AS BIGINT) AS federal_state_local,
    CAST("pub_fund_type_1" AS BIGINT) AS pub_fund_type_1,
    "pub_fund_source_1",
    "pub_fund_prog_1",
    CAST("pub_fund_type_2" AS BIGINT) AS pub_fund_type_2,
    "pub_fund_source_2",
    "pub_fund_prog_2",
    CAST("pub_fund_type_3" AS BIGINT) AS pub_fund_type_3,
    "pub_fund_source_3",
    "pub_fund_prog_3",
    CAST("pub_fund_type_4" AS BIGINT) AS pub_fund_type_4,
    "pub_fund_source_4",
    "pub_fund_prog_4",
    CAST("pub_fund_type_5" AS BIGINT) AS pub_fund_type_5,
    "pub_fund_source_5",
    "pub_fund_prog_5",
    CAST("pub_fund_type_6" AS BIGINT) AS pub_fund_type_6,
    "pub_fund_source_6",
    "pub_fund_prog_6",
    CAST("pub_fund_type_7" AS BIGINT) AS pub_fund_type_7,
    "pub_fund_source_7",
    "pub_fund_prog_7",
    CAST("pub_fund_type_8" AS BIGINT) AS pub_fund_type_8,
    "pub_fund_source_8",
    "pub_fund_prog_8",
    CAST("surveyyear" AS BIGINT) AS surveyyear,
    CAST("segment_id" AS BIGINT) AS segment_id,
    CAST("seg_length" AS DOUBLE) AS seg_length,
    CAST("average_trip_time" AS BIGINT) AS average_trip_time,
    CAST("season_start_month" AS BIGINT) AS season_start_month,
    CAST("season_start_day" AS BIGINT) AS season_start_day,
    CAST("season_end_month" AS BIGINT) AS season_end_month,
    CAST("season_end_day" AS BIGINT) AS season_end_day,
    CAST("route_rates_regulated" AS BIGINT) AS route_rates_regulated,
    "route_rate_regulator",
    CAST("passengers" AS BIGINT) AS passengers,
    CAST("vehicles" AS BIGINT) AS vehicles,
    CAST("avg_daily_brd_pax" AS BIGINT) AS avg_daily_brd_pax,
    CAST("avg_daily_brd_veh" AS BIGINT) AS avg_daily_brd_veh,
    CAST("vessel1_id" AS BIGINT) AS vessel1_id,
    "vessel1_name",
    CAST("vessel2_id" AS BIGINT) AS vessel2_id,
    "vessel2_name",
    CAST("vessel3_id" AS BIGINT) AS vessel3_id,
    "vessel3_name",
    "segment_name",
    CAST("seg_terminal1_id" AS BIGINT) AS seg_terminal1_id,
    CAST("seg_terminal2_id" AS BIGINT) AS seg_terminal2_id,
    CAST("seg_type" AS BIGINT) AS seg_type,
    CAST("serves_nps" AS BIGINT) AS serves_nps,
    "terminal_name1",
    "term_city1",
    "term_state1",
    "term_country1",
    "location_1",
    CAST("parking1" AS BIGINT) AS parking1,
    CAST("local_bus1" AS BIGINT) AS local_bus1,
    CAST("intercity_bus1" AS BIGINT) AS intercity_bus1,
    CAST("local_rail1" AS BIGINT) AS local_rail1,
    CAST("intercity_rail1" AS BIGINT) AS intercity_rail1,
    CAST("terminal_ownership1" AS BIGINT) AS terminal_ownership1,
    CAST("terminal_operation1" AS BIGINT) AS terminal_operation1,
    "terminal_name2",
    "term_city2",
    "term_state2",
    "term_country2",
    "location_2",
    CAST("parking2" AS BIGINT) AS parking2,
    CAST("local_bus2" AS BIGINT) AS local_bus2,
    CAST("intercity_bus2" AS BIGINT) AS intercity_bus2,
    CAST("local_rail2" AS BIGINT) AS local_rail2,
    CAST("intercity_rail2" AS BIGINT) AS intercity_rail2,
    CAST("terminal_ownership2" AS BIGINT) AS terminal_ownership2,
    CAST("terminal_operation2" AS BIGINT) AS terminal_operation2,
    CAST("mainhorsepowerahead" AS BIGINT) AS mainhorsepowerahead,
    CAST("mainhorsepowerastern" AS BIGINT) AS mainhorsepowerastern,
    CAST("hullmaterial" AS BIGINT) AS hullmaterial,
    CAST("hullshape" AS BIGINT) AS hullshape,
    CAST("propulsiontype" AS BIGINT) AS propulsiontype,
    CAST("selfpropindicator" AS BIGINT) AS selfpropindicator,
    "vessel_owned_by",
    "vessel_operated_by",
    CAST("uscg_number1" AS BIGINT) AS uscg_number1,
    CAST("in_service1" AS BIGINT) AS in_service1,
    CAST("carries_passengers1" AS BIGINT) AS carries_passengers1,
    CAST("carries_vehicles1" AS BIGINT) AS carries_vehicles1,
    CAST("carries_freight1" AS BIGINT) AS carries_freight1,
    CAST("passenger_capacity1" AS BIGINT) AS passenger_capacity1,
    CAST("vehicle_capacity1" AS BIGINT) AS vehicle_capacity1,
    CAST("fuel_type1" AS BIGINT) AS fuel_type1,
    "fuel_other1",
    CAST("typical_speed1" AS DOUBLE) AS typical_speed1,
    CAST("year_built1" AS BIGINT) AS year_built1,
    CAST("registered_breadth1" AS DOUBLE) AS registered_breadth1,
    CAST("registered_depth1" AS DOUBLE) AS registered_depth1,
    CAST("registered_length1" AS DOUBLE) AS registered_length1,
    CAST("registered_gross_tons1" AS BIGINT) AS registered_gross_tons1,
    CAST("registered_net_tons1" AS BIGINT) AS registered_net_tons1,
    CAST("vessel_ownership1" AS BIGINT) AS vessel_ownership1,
    CAST("vessel_operation1" AS BIGINT) AS vessel_operation1,
    CAST("fuel_mileage1" AS DOUBLE) AS fuel_mileage1,
    CAST("ada_accessible1" AS BIGINT) AS ada_accessible1,
    CAST("engine_lifespan1" AS BIGINT) AS engine_lifespan1,
    CAST("census_year_miles1" AS BIGINT) AS census_year_miles1,
    CAST("uscg_number2" AS BIGINT) AS uscg_number2,
    CAST("in_service2" AS BIGINT) AS in_service2,
    CAST("carries_passengers2" AS BIGINT) AS carries_passengers2,
    CAST("carries_vehicles2" AS BIGINT) AS carries_vehicles2,
    CAST("carries_freight2" AS BIGINT) AS carries_freight2,
    CAST("passenger_capacity2" AS BIGINT) AS passenger_capacity2,
    CAST("vehicle_capacity2" AS BIGINT) AS vehicle_capacity2,
    CAST("fuel_type2" AS BIGINT) AS fuel_type2,
    "fuel_other2",
    CAST("typical_speed2" AS DOUBLE) AS typical_speed2,
    CAST("year_built2" AS BIGINT) AS year_built2,
    CAST("registered_breadth2" AS DOUBLE) AS registered_breadth2,
    CAST("registered_depth2" AS DOUBLE) AS registered_depth2,
    CAST("registered_length2" AS DOUBLE) AS registered_length2,
    CAST("registered_gross_tons2" AS BIGINT) AS registered_gross_tons2,
    CAST("registered_net_tons2" AS BIGINT) AS registered_net_tons2,
    CAST("vessel_ownership2" AS BIGINT) AS vessel_ownership2,
    CAST("vessel_operation2" AS BIGINT) AS vessel_operation2,
    CAST("fuel_mileage2" AS DOUBLE) AS fuel_mileage2,
    CAST("ada_accessible2" AS BIGINT) AS ada_accessible2,
    CAST("engine_lifespan2" AS BIGINT) AS engine_lifespan2,
    CAST("census_year_miles2" AS BIGINT) AS census_year_miles2,
    CAST("uscg_number3" AS BIGINT) AS uscg_number3,
    CAST("in_service3" AS BIGINT) AS in_service3,
    CAST("carries_passengers3" AS BIGINT) AS carries_passengers3,
    CAST("carries_vehicles3" AS BIGINT) AS carries_vehicles3,
    CAST("carries_freight3" AS BIGINT) AS carries_freight3,
    CAST("passenger_capacity3" AS BIGINT) AS passenger_capacity3,
    CAST("vehicle_capacity3" AS BIGINT) AS vehicle_capacity3,
    CAST("fuel_type3" AS BIGINT) AS fuel_type3,
    "fuel_other3",
    CAST("typical_speed3" AS BIGINT) AS typical_speed3,
    CAST("year_built3" AS BIGINT) AS year_built3,
    CAST("registered_breadth3" AS DOUBLE) AS registered_breadth3,
    CAST("registered_depth3" AS DOUBLE) AS registered_depth3,
    CAST("registered_length3" AS DOUBLE) AS registered_length3,
    CAST("registered_gross_tons3" AS BIGINT) AS registered_gross_tons3,
    CAST("registered_net_tons3" AS BIGINT) AS registered_net_tons3,
    CAST("vessel_ownership3" AS BIGINT) AS vessel_ownership3,
    CAST("vessel_operation3" AS BIGINT) AS vessel_operation3,
    CAST("fuel_mileage3" AS DOUBLE) AS fuel_mileage3,
    CAST("ada_accessible3" AS BIGINT) AS ada_accessible3,
    CAST("engine_lifespan3" AS BIGINT) AS engine_lifespan3,
    CAST("census_year_miles3" AS BIGINT) AS census_year_miles3
FROM "u-s-department-of-transportation-5kxy-j6hw"
