-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No stable row key was verified in the raw profile; use this table as a source snapshot rather than assuming row identity across runs.
SELECT
    CAST("tmstp_epoch" AS BIGINT) AS tmstp_epoch,
    CAST("tmstp_utc" AS TIMESTAMP) AS tmstp_utc,
    CAST("date_utc" AS TIMESTAMP) AS date_utc,
    "rsu_locations",
    "temp_id",
    CAST("msg_count" AS BIGINT) AS msg_count,
    CAST("sec_mark" AS BIGINT) AS sec_mark,
    CAST("latitude" AS BIGINT) AS latitude,
    CAST("longitude" AS BIGINT) AS longitude,
    CAST("elevation" AS BIGINT) AS elevation,
    CAST("heading" AS BIGINT) AS heading,
    CAST("speed" AS BIGINT) AS speed,
    "transmission_state",
    CAST("lateral_acceleration" AS BIGINT) AS lateral_acceleration,
    CAST("longitudinal_acceleration" AS BIGINT) AS longitudinal_acceleration,
    CAST("vertical_acceleration" AS BIGINT) AS vertical_acceleration,
    CAST("yaw_rate" AS BIGINT) AS yaw_rate,
    CAST("semi_major_axis_orientation" AS BIGINT) AS semi_major_axis_orientation,
    CAST("semi_major_axis_accuracy" AS BIGINT) AS semi_major_axis_accuracy,
    CAST("semi_minor_axis_accuracy" AS BIGINT) AS semi_minor_axis_accuracy,
    CAST("steering_wheel_angle" AS BIGINT) AS steering_wheel_angle,
    "abs_status",
    "auxiliary_brake_status",
    "brake_boost_status",
    "scs_status",
    "traction_control_status",
    CAST("wheel_brakes_flags" AS BIGINT) AS wheel_brakes_flags,
    CAST("brake_unavailable" AS BOOLEAN) AS brake_unavailable,
    CAST("brake_left_front" AS BOOLEAN) AS brake_left_front,
    CAST("brake_left_rear" AS BOOLEAN) AS brake_left_rear,
    CAST("brake_right_front" AS BOOLEAN) AS brake_right_front,
    CAST("brake_right_rear" AS BOOLEAN) AS brake_right_rear,
    CAST("vehicle_length" AS BIGINT) AS vehicle_length,
    CAST("vehicle_width" AS BIGINT) AS vehicle_width,
    CAST("vehicle_classification" AS BIGINT) AS vehicle_classification,
    "vehicle_role",
    "vehicle_fuel_type",
    "vehicle_hpms_type",
    CAST("vehicle_key_type" AS BIGINT) AS vehicle_key_type,
    CAST("vehicle_height" AS BIGINT) AS vehicle_height,
    CAST("vehicle_mass" AS BIGINT) AS vehicle_mass,
    CAST("vehicle_bumper_front" AS BIGINT) AS vehicle_bumper_front,
    CAST("vehicle_bumper_rear" AS BIGINT) AS vehicle_bumper_rear,
    CAST("air_pressure" AS BIGINT) AS air_pressure,
    CAST("air_temp" AS BIGINT) AS air_temp,
    CAST("front_wiper_rate" AS BIGINT) AS front_wiper_rate,
    "front_wiper_status",
    CAST("friction" AS BIGINT) AS friction,
    "is_raining",
    "precip_situation",
    CAST("rain_rate" AS BIGINT) AS rain_rate,
    CAST("road_friction" AS BIGINT) AS road_friction,
    CAST("solar_radiation" AS BIGINT) AS solar_radiation,
    "exterior_lights_flags",
    CAST("low_beam_headlights" AS BOOLEAN) AS low_beam_headlights,
    CAST("high_beam_headlights" AS BOOLEAN) AS high_beam_headlights,
    CAST("left_turn_signal" AS BOOLEAN) AS left_turn_signal,
    CAST("right_turn_signal" AS BOOLEAN) AS right_turn_signal,
    CAST("hazard_lights" AS BOOLEAN) AS hazard_lights,
    CAST("automatic_light_control" AS BOOLEAN) AS automatic_light_control,
    CAST("daytime_running_lights" AS BOOLEAN) AS daytime_running_lights,
    CAST("fog_lights" AS BOOLEAN) AS fog_lights,
    CAST("parking_lights" AS BOOLEAN) AS parking_lights,
    "safety_events_flags",
    CAST("event_hazard_lights" AS BOOLEAN) AS event_hazard_lights,
    CAST("event_intersection_violation" AS BOOLEAN) AS event_intersection_violation,
    CAST("event_abs_violation" AS BOOLEAN) AS event_abs_violation,
    CAST("event_traction_control_loss" AS BOOLEAN) AS event_traction_control_loss,
    CAST("event_stability_control" AS BOOLEAN) AS event_stability_control,
    CAST("event_hazardous_materials" AS BOOLEAN) AS event_hazardous_materials,
    CAST("event_reserved_1" AS BOOLEAN) AS event_reserved_1,
    CAST("event_hard_braking" AS BOOLEAN) AS event_hard_braking,
    CAST("event_lights_changed" AS BOOLEAN) AS event_lights_changed,
    CAST("event_wipers_changed" AS BOOLEAN) AS event_wipers_changed,
    CAST("event_flat_tire" AS BOOLEAN) AS event_flat_tire,
    CAST("event_disabled_vehicle" AS BOOLEAN) AS event_disabled_vehicle,
    CAST("event_airbag" AS BOOLEAN) AS event_airbag,
    "emergency_events_flags",
    "emergency_unavailable",
    "emergency_response",
    "emergency_lights_active",
    "emergency_sound_active",
    "non_emergency_lights_active",
    "non_emergency_sound_active",
    "disabled_vehicle_status",
    "type_event",
    "vehiclealerts_events_not",
    "vehiclealerts_lightbar_use",
    "vehiclealerts_multi",
    "vehiclealerts_siren_use",
    "vehiclealerts_not_used",
    "trailers_connection_pivot",
    "trailers_connection_pivots",
    "trailers_connection_pivot_1",
    "trailers_not_used",
    "trailers_length",
    "trailers_height",
    "trailers_width",
    "trailers_isdolly",
    "trailers_front_pivot_angle",
    "trailers_front_pivot_offset",
    "trailers_front_pivots",
    "trailers_position_offset",
    "trailers_position_offset_1",
    "trailers_rear_pivot_angle",
    "trailers_rear_pivot_offset",
    "trailers_rear_pivots",
    CAST("pathprediction_confidence" AS BIGINT) AS pathprediction_confidence,
    CAST("pathprediction_radiusofcurve" AS BIGINT) AS pathprediction_radiusofcurve,
    "pathhistory_crumbdata",
    "pathhistory_currgnss_status",
    "currgnss_status_unavailable",
    "currgnss_status_ishealthy",
    "currgnss_status_ismonitored",
    "currgnss_status",
    "currgnss_status_apdop_of",
    "currgnss_status_inview_of",
    "currgnss_status_1",
    "currgnss_status_2",
    CAST("decoded_bytes" AS DOUBLE) AS decoded_bytes
FROM "u-s-department-of-transportation-ev64-jn8c"
