-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No stable row key was verified in the raw profile; use this table as a source snapshot rather than assuming row identity across runs.
SELECT
    "the_geom",
    CAST("year_recor" AS BIGINT) AS year_recor,
    CAST("state_code" AS BIGINT) AS state_code,
    "route_id",
    CAST("begin_poin" AS DOUBLE) AS begin_poin,
    CAST("end_point" AS DOUBLE) AS end_point,
    CAST("route_numb" AS BIGINT) AS route_numb,
    "route_name",
    CAST("route_qual" AS BIGINT) AS route_qual,
    CAST("route_sign" AS BIGINT) AS route_sign,
    CAST("f_system" AS BIGINT) AS f_system,
    CAST("facility_t" AS BIGINT) AS facility_t,
    CAST("urban_code" AS BIGINT) AS urban_code,
    CAST("nhs" AS BIGINT) AS nhs,
    CAST("strahnet" AS BIGINT) AS strahnet,
    CAST("ownership" AS BIGINT) AS ownership,
    CAST("truck" AS BIGINT) AS truck,
    CAST("through_la" AS BIGINT) AS through_la,
    CAST("peak_lanes" AS BIGINT) AS peak_lanes,
    CAST("counter_pe" AS BIGINT) AS counter_pe,
    CAST("shoulder_t" AS BIGINT) AS shoulder_t,
    CAST("shoulder_w" AS BIGINT) AS shoulder_w,
    CAST("shoulder_1" AS BIGINT) AS shoulder_1,
    CAST("lane_width" AS BIGINT) AS lane_width,
    CAST("median_typ" AS BIGINT) AS median_typ,
    CAST("median_wid" AS BIGINT) AS median_wid,
    CAST("access_con" AS BIGINT) AS access_con,
    "widening_o",
    CAST("widening_p" AS BIGINT) AS widening_p,
    CAST("hov_lanes" AS BIGINT) AS hov_lanes,
    CAST("hov_type" AS BIGINT) AS hov_type,
    CAST("speed_limi" AS BIGINT) AS speed_limi,
    CAST("toll_charg" AS BIGINT) AS toll_charg,
    "toll_id",
    CAST("toll_type" AS BIGINT) AS toll_type,
    CAST("aadt" AS BIGINT) AS aadt,
    CAST("aadt_combi" AS BIGINT) AS aadt_combi,
    CAST("aadt_singl" AS BIGINT) AS aadt_singl,
    "pct_peak_c",
    CAST("pct_peak_s" AS DOUBLE) AS pct_peak_s,
    "k_factor",
    CAST("dir_factor" AS DOUBLE) AS dir_factor,
    CAST("iri" AS BIGINT) AS iri,
    CAST("psr" AS DOUBLE) AS psr,
    CAST("surface_ty" AS BIGINT) AS surface_ty,
    CAST("cracking_p" AS DOUBLE) AS cracking_p,
    CAST("faulting" AS DOUBLE) AS faulting,
    "rutting",
    CAST("structure_" AS BIGINT) AS structure,
    "year_last_" AS year_last,
    "year_last1",
    CAST("is_sample" AS BIGINT) AS is_sample,
    "sample_id",
    CAST("expansion_" AS DOUBLE) AS expansion,
    "national_r",
    CAST("shape_leng" AS DOUBLE) AS shape_leng
FROM "u-s-department-of-transportation-buwj-ggyf"
