-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "the_geom",
    "placeid",
    "yearplaceid",
    "city",
    "state",
    "citystate",
    CAST("year" AS BIGINT) AS year,
    CAST("asofdate" AS BIGINT) AS asofdate,
    "dockid",
    CAST("dockct" AS DOUBLE) AS dockct,
    CAST("stationct_pct" AS DOUBLE) AS stationct_pct,
    CAST("stationct_bin" AS DOUBLE) AS stationct_bin,
    "docknm",
    CAST("docklessct" AS DOUBLE) AS docklessct,
    CAST("dockless_bin" AS DOUBLE) AS dockless_bin,
    "docklessnm",
    CAST("scooterct" AS DOUBLE) AS scooterct,
    CAST("scooter_bin" AS DOUBLE) AS scooter_bin,
    "scooternm",
    "type",
    CAST("lat" AS DOUBLE) AS lat,
    CAST("lon" AS DOUBLE) AS lon,
    "fips",
    "datedocklaunch",
    "datedockclosed",
    "datescooterlaunch",
    "datescooterend",
    "datedocklesslaunch",
    "datedocklessend",
    "docknotes",
    "notesdockless",
    "notesscooter",
    CAST("scooterct_jul" AS BIGINT) AS scooterct_jul,
    CAST("dockct_jul" AS BIGINT) AS dockct_jul,
    "docklessnm_jul",
    "scooternm_jul",
    "docknm_jul",
    CAST("docklessct_jul" AS BIGINT) AS docklessct_jul,
    "datedocklaunch_jul",
    "datedockclosed_jul",
    "datescooterlaunch_jul",
    "datescooterend_jul",
    "datedocklesslaunch_jul",
    "datedocklessend_jul",
    "docknotes_jul",
    "notesdockless_jul",
    "notesscooter_jul",
    "dockid_jul",
    "type_jul"
FROM "u-s-department-of-transportation-cqdc-cm7d"
