-- caution: Hydrological summary fields describe long-term station-level characteristics
-- from the catalogue, not time-series discharge observations.
SELECT
    CAST(grdc_no AS BIGINT)                       AS grdc_no,
    TRY_CAST(wmo_reg AS INTEGER)                  AS wmo_region,
    TRY_CAST(sub_reg AS INTEGER)                  AS sub_region,
    river,
    station,
    country,
    nat_id,
    CAST(ds_stat_no AS VARCHAR)                   AS downstream_station_no,
    CAST(lat AS DOUBLE)                           AS latitude,
    CAST("long" AS DOUBLE)                        AS longitude,
    NULLIF(TRY_CAST(area AS DOUBLE), -999)        AS catchment_area_km2,
    NULLIF(TRY_CAST(altitude AS DOUBLE), -999)    AS altitude_m,
    TRY_CAST(d_start AS INTEGER)                  AS daily_start_year,
    TRY_CAST(d_end AS INTEGER)                    AS daily_end_year,
    TRY_CAST(d_yrs AS DOUBLE)                     AS daily_years,
    TRY_CAST(d_miss AS DOUBLE)                    AS daily_missing_pct,
    TRY_CAST(m_start AS INTEGER)                  AS monthly_start_year,
    TRY_CAST(m_end AS INTEGER)                    AS monthly_end_year,
    TRY_CAST(m_yrs AS DOUBLE)                     AS monthly_years,
    TRY_CAST(m_miss AS DOUBLE)                    AS monthly_missing_pct,
    TRY_CAST(t_start AS INTEGER)                  AS record_start_year,
    TRY_CAST(t_end AS INTEGER)                    AS record_end_year,
    TRY_CAST(t_yrs AS DOUBLE)                     AS record_years,
    TRY_CAST(lta_discharge AS DOUBLE)             AS lta_discharge_m3s,
    TRY_CAST(r_volume_yr AS DOUBLE)               AS runoff_volume_km3_yr,
    TRY_CAST(r_height_yr AS DOUBLE)               AS runoff_height_mm_yr,
    NULLIF(TRY_CAST(provider_id AS INTEGER), -999) AS provider_id,
    TRY_CAST(l_im_yr AS INTEGER)                  AS last_import_year,
    timeseries_type,
    region_name,
    subregion_name,
    ocean,
    river_basin
FROM "grdc-station-catalogue"
WHERE grdc_no IS NOT NULL
