# Clio Infra indicator file stems (the entity union, rank-active subsets).
# Each maps to https://clio-infra.eu/data/<stem>_Compact.xlsx
# Copied from data/sources/clio-infra/work/entity_union.json
FILE_STEMS = [
    'AluminiumProduction',
    'ArmedConflicts(International)',
    'Armedconflicts(Internal)',
    'AverageYearsofEducation',
    'BauxiteProduction',
    'Biodiversity-naturalness',
    'BookTitlesperCapita',
    'CO2EmissionsperCapita',
    'CattleperCapita',
    'CompetitivenessofExecutiveRecruitment(XRCOMP)',
    'CompetitivenessofParticipations(PARCOMP)',
    'CompositeMeasureofWellbeing',
    'CopperProduction',
    'CroplandperCapita',
    'EducationalInequalityGiniCoefficient',
    'ExchangeRatestoUKPound',
    'ExchangeRatestoUSDollar',
    'ExecutiveConstraints(XCONST)',
    'FemalelifeexpectancyatBirth',
    'GDPperCapita',
    'Gender-equalInheritance',
    'GenderEqualityYearsofEducation',
    'GenderEqualityofNumeracy',
    'GlobalExtremePovertyCostofBasicNeeds',
    'GlobalExtremePovertyDollaraDay',
    'GlobalHunger',
    'GoatsperCapita',
    'GoldProduction',
    'GoldStandard',
    'Height',
    'HeightGini',
    'HistoricalGenderEqualityIndex',
    'HomicideRates',
    'IncomeInequality',
    'InfantMortality',
    'Inflation',
    'IronOreProduction',
    'LabourersRealWage',
    'LatentDemocracyVariable',
    'LeadProduction',
    'LifeExpectancyatBirth(Total)',
    'Long-TermGovernmentBondYield',
    'MalelifeExpectancyatBirth',
    'ManganeseProduction',
    'NickelProduction',
    'NumberofDaysLostinLabourDisputes',
    'NumberofLabourDisputes',
    'NumberofWorkersInvolvedinLabourDisputes',
    'Numeracy(Total)',
    'OpennessofExecutiveRecruitment(XROPEN)',
    'PastureperCapita',
    'PigsperCapita',
    'PoliticalCompetition',
    'PoliticalParticipation',
    'Polity2Index',
    'Polyarchy',
    'RegulationofChiefExecutiveRecruitment(XRREG)',
    'RegulationofParticipation(PARREG)',
    'SO2EmissionsperCapita',
    'SexRatio',
    'ShareofWomeninParliament',
    'SheepperCapita',
    'SilverProduction',
    'SocialSpending',
    'TinProduction',
    'TotalCO2Emissions',
    'TotalCattle',
    'TotalCropland',
    'TotalGrossCentralGovernmentDebtasaPercentageofGDP',
    'TotalNumberofGoats',
    'TotalNumberofPigs',
    'TotalNumberofSheep',
    'TotalPasture',
    'TotalPopulation',
    'TotalSO2Emissions',
    'TotalUrbanPopulation',
    'TungstenProduction',
    'UnifiedDemocracyScores(UDS)',
    'UniversitiesFounded',
    'UrbanizationRatio',
    'WealthDecadalGinis',
    'WealthTop10percentshare',
    'WealthTotal',
    'WealthYearlyGinis',
    'Workingweekinmanufacturing',
    'ZincProduction',
]


def asset_id(file_stem: str) -> str:
    return (
        "clio-infra-"
        + file_stem.lower()
        .replace("_", "-")
        .replace("(", "-")
        .replace(")", "")
    )


ASSET_TO_STEM = {asset_id(stem): stem for stem in FILE_STEMS}
ENTITY_IDS = list(ASSET_TO_STEM)
