-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Wide consumer spending table; columns encode spending category and sometimes income segment, so compare like-named measures rather than summing across all spend_* columns.
SELECT
    "year",
    "month",
    "day_endofmonth",
    "statefips",
    "freq",
    "spend_aap",
    "spend_s_aap",
    "spend_acf",
    "spend_s_acf",
    "spend_aer",
    "spend_s_aer",
    "spend_all",
    "spend_s_all",
    "spend_apg",
    "spend_s_apg",
    "spend_durables",
    "spend_s_durables",
    "spend_gen",
    "spend_s_gen",
    "spend_grf",
    "spend_s_grf",
    "spend_hcs",
    "spend_s_hcs",
    "spend_hic",
    "spend_s_hic",
    "spend_inpersonmisc",
    "spend_s_inpersonmisc",
    "spend_nondurables",
    "spend_s_nondurables",
    "spend_remoteservices",
    "spend_s_remoteservices",
    "spend_sgh",
    "spend_s_sgh",
    "spend_tws",
    "spend_s_tws",
    "spend_all_incmiddle",
    "spend_s_all_incmiddle",
    "spend_all_q1",
    "spend_s_all_q1",
    "spend_all_q2",
    "spend_s_all_q2",
    "spend_all_q3",
    "spend_s_all_q3",
    "spend_all_q4",
    "spend_s_all_q4",
    "spend_inperson",
    "spend_s_inperson",
    "spend_retail_no_grocery",
    "spend_s_retail_no_grocery",
    "spend_retail_w_grocery",
    "spend_s_retail_w_grocery",
    "provisional"
FROM "opportunity-insights-tracker-affinity-state-monthly"
