-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: This is a wide power-system time-series table; each country, bidding-zone, technology, and measure column is a separate series at fifteen minute resolution.
SELECT
    "utc_timestamp",
    "cet_cest_timestamp",
    "AT_load_actual_entsoe_transparency" AS at_load_actual_entsoe_transparency,
    "AT_load_forecast_entsoe_transparency" AS at_load_forecast_entsoe_transparency,
    "AT_price_day_ahead" AS at_price_day_ahead,
    "AT_solar_generation_actual" AS at_solar_generation_actual,
    "AT_wind_onshore_generation_actual" AS at_wind_onshore_generation_actual,
    "BE_load_actual_entsoe_transparency" AS be_load_actual_entsoe_transparency,
    "BE_load_forecast_entsoe_transparency" AS be_load_forecast_entsoe_transparency,
    "DE_load_actual_entsoe_transparency" AS de_load_actual_entsoe_transparency,
    "DE_load_forecast_entsoe_transparency" AS de_load_forecast_entsoe_transparency,
    "DE_solar_capacity" AS de_solar_capacity,
    "DE_solar_generation_actual" AS de_solar_generation_actual,
    "DE_solar_profile" AS de_solar_profile,
    "DE_wind_capacity" AS de_wind_capacity,
    "DE_wind_generation_actual" AS de_wind_generation_actual,
    "DE_wind_profile" AS de_wind_profile,
    "DE_wind_offshore_capacity" AS de_wind_offshore_capacity,
    "DE_wind_offshore_generation_actual" AS de_wind_offshore_generation_actual,
    "DE_wind_offshore_profile" AS de_wind_offshore_profile,
    "DE_wind_onshore_capacity" AS de_wind_onshore_capacity,
    "DE_wind_onshore_generation_actual" AS de_wind_onshore_generation_actual,
    "DE_wind_onshore_profile" AS de_wind_onshore_profile,
    "DE_50hertz_load_actual_entsoe_transparency" AS de_50hertz_load_actual_entsoe_transparency,
    "DE_50hertz_load_forecast_entsoe_transparency" AS de_50hertz_load_forecast_entsoe_transparency,
    "DE_50hertz_solar_generation_actual" AS de_50hertz_solar_generation_actual,
    "DE_50hertz_wind_generation_actual" AS de_50hertz_wind_generation_actual,
    "DE_50hertz_wind_offshore_generation_actual" AS de_50hertz_wind_offshore_generation_actual,
    "DE_50hertz_wind_onshore_generation_actual" AS de_50hertz_wind_onshore_generation_actual,
    "DE_LU_load_actual_entsoe_transparency" AS de_lu_load_actual_entsoe_transparency,
    "DE_LU_load_forecast_entsoe_transparency" AS de_lu_load_forecast_entsoe_transparency,
    "DE_LU_solar_generation_actual" AS de_lu_solar_generation_actual,
    "DE_LU_wind_generation_actual" AS de_lu_wind_generation_actual,
    "DE_LU_wind_offshore_generation_actual" AS de_lu_wind_offshore_generation_actual,
    "DE_LU_wind_onshore_generation_actual" AS de_lu_wind_onshore_generation_actual,
    "DE_amprion_load_actual_entsoe_transparency" AS de_amprion_load_actual_entsoe_transparency,
    "DE_amprion_load_forecast_entsoe_transparency" AS de_amprion_load_forecast_entsoe_transparency,
    "DE_amprion_solar_generation_actual" AS de_amprion_solar_generation_actual,
    "DE_amprion_wind_onshore_generation_actual" AS de_amprion_wind_onshore_generation_actual,
    "DE_tennet_load_actual_entsoe_transparency" AS de_tennet_load_actual_entsoe_transparency,
    "DE_tennet_load_forecast_entsoe_transparency" AS de_tennet_load_forecast_entsoe_transparency,
    "DE_tennet_solar_generation_actual" AS de_tennet_solar_generation_actual,
    "DE_tennet_wind_generation_actual" AS de_tennet_wind_generation_actual,
    "DE_tennet_wind_offshore_generation_actual" AS de_tennet_wind_offshore_generation_actual,
    "DE_tennet_wind_onshore_generation_actual" AS de_tennet_wind_onshore_generation_actual,
    "DE_transnetbw_load_actual_entsoe_transparency" AS de_transnetbw_load_actual_entsoe_transparency,
    "DE_transnetbw_load_forecast_entsoe_transparency" AS de_transnetbw_load_forecast_entsoe_transparency,
    "DE_transnetbw_solar_generation_actual" AS de_transnetbw_solar_generation_actual,
    "DE_transnetbw_wind_onshore_generation_actual" AS de_transnetbw_wind_onshore_generation_actual,
    "HU_load_actual_entsoe_transparency" AS hu_load_actual_entsoe_transparency,
    "HU_load_forecast_entsoe_transparency" AS hu_load_forecast_entsoe_transparency,
    "HU_solar_generation_actual" AS hu_solar_generation_actual,
    "HU_wind_onshore_generation_actual" AS hu_wind_onshore_generation_actual,
    "LU_load_actual_entsoe_transparency" AS lu_load_actual_entsoe_transparency,
    "LU_load_forecast_entsoe_transparency" AS lu_load_forecast_entsoe_transparency,
    "NL_load_actual_entsoe_transparency" AS nl_load_actual_entsoe_transparency,
    "NL_load_forecast_entsoe_transparency" AS nl_load_forecast_entsoe_transparency,
    "NL_solar_generation_actual" AS nl_solar_generation_actual,
    "NL_wind_generation_actual" AS nl_wind_generation_actual,
    "NL_wind_offshore_generation_actual" AS nl_wind_offshore_generation_actual,
    "NL_wind_onshore_generation_actual" AS nl_wind_onshore_generation_actual
FROM "open-power-system-data-time-series--time-series-15min-singleindex"
