-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: This is a wide meter-reading table: each value column is a distinct meter or site series at hourly resolution.
SELECT
    "utc_timestamp",
    "cet_cest_timestamp",
    "DE_KN_industrial1_grid_import" AS de_kn_industrial1_grid_import,
    "DE_KN_industrial1_pv_1" AS de_kn_industrial1_pv_1,
    "DE_KN_industrial1_pv_2" AS de_kn_industrial1_pv_2,
    "DE_KN_industrial2_grid_import" AS de_kn_industrial2_grid_import,
    "DE_KN_industrial2_pv" AS de_kn_industrial2_pv,
    "DE_KN_industrial2_storage_charge" AS de_kn_industrial2_storage_charge,
    "DE_KN_industrial2_storage_decharge" AS de_kn_industrial2_storage_decharge,
    "DE_KN_industrial3_area_offices" AS de_kn_industrial3_area_offices,
    "DE_KN_industrial3_area_room_1" AS de_kn_industrial3_area_room_1,
    "DE_KN_industrial3_area_room_2" AS de_kn_industrial3_area_room_2,
    "DE_KN_industrial3_area_room_3" AS de_kn_industrial3_area_room_3,
    "DE_KN_industrial3_area_room_4" AS de_kn_industrial3_area_room_4,
    "DE_KN_industrial3_compressor" AS de_kn_industrial3_compressor,
    "DE_KN_industrial3_cooling_aggregate" AS de_kn_industrial3_cooling_aggregate,
    "DE_KN_industrial3_cooling_pumps" AS de_kn_industrial3_cooling_pumps,
    "DE_KN_industrial3_dishwasher" AS de_kn_industrial3_dishwasher,
    "DE_KN_industrial3_ev" AS de_kn_industrial3_ev,
    "DE_KN_industrial3_grid_import" AS de_kn_industrial3_grid_import,
    "DE_KN_industrial3_machine_1" AS de_kn_industrial3_machine_1,
    "DE_KN_industrial3_machine_2" AS de_kn_industrial3_machine_2,
    "DE_KN_industrial3_machine_3" AS de_kn_industrial3_machine_3,
    "DE_KN_industrial3_machine_4" AS de_kn_industrial3_machine_4,
    "DE_KN_industrial3_machine_5" AS de_kn_industrial3_machine_5,
    "DE_KN_industrial3_pv_facade" AS de_kn_industrial3_pv_facade,
    "DE_KN_industrial3_pv_roof" AS de_kn_industrial3_pv_roof,
    "DE_KN_industrial3_refrigerator" AS de_kn_industrial3_refrigerator,
    "DE_KN_industrial3_ventilation" AS de_kn_industrial3_ventilation,
    "DE_KN_public1_grid_import" AS de_kn_public1_grid_import,
    "DE_KN_public2_grid_import" AS de_kn_public2_grid_import,
    "DE_KN_residential1_dishwasher" AS de_kn_residential1_dishwasher,
    "DE_KN_residential1_freezer" AS de_kn_residential1_freezer,
    "DE_KN_residential1_grid_import" AS de_kn_residential1_grid_import,
    "DE_KN_residential1_heat_pump" AS de_kn_residential1_heat_pump,
    "DE_KN_residential1_pv" AS de_kn_residential1_pv,
    "DE_KN_residential1_washing_machine" AS de_kn_residential1_washing_machine,
    "DE_KN_residential2_circulation_pump" AS de_kn_residential2_circulation_pump,
    "DE_KN_residential2_dishwasher" AS de_kn_residential2_dishwasher,
    "DE_KN_residential2_freezer" AS de_kn_residential2_freezer,
    "DE_KN_residential2_grid_import" AS de_kn_residential2_grid_import,
    "DE_KN_residential2_washing_machine" AS de_kn_residential2_washing_machine,
    "DE_KN_residential3_circulation_pump" AS de_kn_residential3_circulation_pump,
    "DE_KN_residential3_dishwasher" AS de_kn_residential3_dishwasher,
    "DE_KN_residential3_freezer" AS de_kn_residential3_freezer,
    "DE_KN_residential3_grid_export" AS de_kn_residential3_grid_export,
    "DE_KN_residential3_grid_import" AS de_kn_residential3_grid_import,
    "DE_KN_residential3_pv" AS de_kn_residential3_pv,
    "DE_KN_residential3_refrigerator" AS de_kn_residential3_refrigerator,
    "DE_KN_residential3_washing_machine" AS de_kn_residential3_washing_machine,
    "DE_KN_residential4_dishwasher" AS de_kn_residential4_dishwasher,
    "DE_KN_residential4_ev" AS de_kn_residential4_ev,
    "DE_KN_residential4_freezer" AS de_kn_residential4_freezer,
    "DE_KN_residential4_grid_export" AS de_kn_residential4_grid_export,
    "DE_KN_residential4_grid_import" AS de_kn_residential4_grid_import,
    "DE_KN_residential4_heat_pump" AS de_kn_residential4_heat_pump,
    "DE_KN_residential4_pv" AS de_kn_residential4_pv,
    "DE_KN_residential4_refrigerator" AS de_kn_residential4_refrigerator,
    "DE_KN_residential4_washing_machine" AS de_kn_residential4_washing_machine,
    "DE_KN_residential5_dishwasher" AS de_kn_residential5_dishwasher,
    "DE_KN_residential5_grid_import" AS de_kn_residential5_grid_import,
    "DE_KN_residential5_refrigerator" AS de_kn_residential5_refrigerator,
    "DE_KN_residential5_washing_machine" AS de_kn_residential5_washing_machine,
    "DE_KN_residential6_circulation_pump" AS de_kn_residential6_circulation_pump,
    "DE_KN_residential6_dishwasher" AS de_kn_residential6_dishwasher,
    "DE_KN_residential6_freezer" AS de_kn_residential6_freezer,
    "DE_KN_residential6_grid_export" AS de_kn_residential6_grid_export,
    "DE_KN_residential6_grid_import" AS de_kn_residential6_grid_import,
    "DE_KN_residential6_pv" AS de_kn_residential6_pv,
    "DE_KN_residential6_washing_machine" AS de_kn_residential6_washing_machine,
    "interpolated"
FROM "open-power-system-data-household-data--household-data-60min-singleindex"
