-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: This is a wide coded panel with many constitutional-characteristic variables; rows are distinguished by country, year, event type, and weighting group, so do not treat country-year alone as unique.
SELECT
    CAST("cowcode" AS BIGINT) AS cowcode,
    "country",
    CAST("year" AS BIGINT) AS year,
    CAST("wg" AS BIGINT) AS wg,
    CAST("sample_deviation_type" AS BIGINT) AS sample_deviation_type,
    CAST("syst" AS BIGINT) AS syst,
    CAST("systid" AS BIGINT) AS systid,
    CAST("systyear" AS BIGINT) AS systyear,
    CAST("evnt" AS BIGINT) AS evnt,
    CAST("evntid" AS BIGINT) AS evntid,
    CAST("evntyear" AS BIGINT) AS evntyear,
    CAST("evnttype" AS BIGINT) AS evnttype,
    CAST("multiple" AS BIGINT) AS multiple,
    CAST("c_inforce" AS BIGINT) AS c_inforce,
    CAST("coding_available" AS BIGINT) AS coding_available,
    CAST("coding_imputed" AS BIGINT) AS coding_imputed,
    CAST("imputed_evntid" AS BIGINT) AS imputed_evntid,
    CAST("imputed_evntyear" AS BIGINT) AS imputed_evntyear,
    CAST("imputation_type" AS BIGINT) AS imputation_type,
    CAST("source" AS BIGINT) AS source,
    "source_article",
    "source_comments",
    CAST("langsrce" AS BIGINT) AS langsrce,
    "langsrce_article",
    "langsrce_comments",
    CAST("translat" AS BIGINT) AS translat,
    "translat_article",
    "translat_comments",
    CAST("doctit" AS BIGINT) AS doctit,
    "doctit_article",
    "doctit_comments",
    CAST("model" AS BIGINT) AS model,
    "model_article",
    "model_comments",
    CAST("length" AS BIGINT) AS length,
    "length_article",
    "length_comments",
    CAST("docs" AS BIGINT) AS docs,
    "docs_article",
    "docs_comments",
    CAST("tranprov" AS BIGINT) AS tranprov,
    "tranprov_article",
    "tranprov_comments",
    CAST("preamble" AS BIGINT) AS preamble,
    "preamble_article",
    "preamble_comments",
    CAST("preambw" AS BIGINT) AS preambw,
    "preambw_article",
    "preambw_comments",
    CAST("rightsw" AS BIGINT) AS rightsw,
    "rightsw_article",
    "rightsw_comments",
    CAST("rghtwrds" AS BIGINT) AS rghtwrds,
    "rghtwrds_article",
    "rghtwrds_comments",
    CAST("colony" AS BIGINT) AS colony,
    "colony_article",
    "colony_comments",
    CAST("colrule" AS BIGINT) AS colrule,
    "colrule_article",
    "colrule_comments",
    CAST("indcon" AS BIGINT) AS indcon,
    "indcon_article",
    "indcon_comments",
    "region_article",
    "region_comments",
    CAST("region" AS BIGINT) AS region,
    "regions",
    "regions_article",
    "regions_comments",
    CAST("prevcond" AS BIGINT) AS prevcond,
    "prevcond_article",
    "prevcond_comments",
    CAST("truthcom" AS BIGINT) AS truthcom,
    "truthcom_article",
    "truthcom_comments",
    CAST("prevlead" AS BIGINT) AS prevlead,
    "prevlead_article",
    "prevlead_comments",
    CAST("democ" AS BIGINT) AS democ,
    "democ_article",
    "democ_comments",
    CAST("demonum" AS BIGINT) AS demonum,
    "demonum_article",
    "demonum_comments",
    CAST("oath" AS BIGINT) AS oath,
    "oath_article",
    "oath_comments",
    CAST("socialsm" AS BIGINT) AS socialsm,
    "socialsm_article",
    "socialsm_comments",
    CAST("market" AS BIGINT) AS market,
    "market_article",
    "market_comments",
    CAST("forinves" AS BIGINT) AS forinves,
    "forinves_article",
    "forinves_comments",
    CAST("fortrad" AS BIGINT) AS fortrad,
    "fortrad_article",
    "fortrad_comments",
    CAST("dignity" AS BIGINT) AS dignity,
    "dignity_article",
    "dignity_comments",
    CAST("god" AS BIGINT) AS god,
    "god_article",
    "god_comments",
    CAST("figures" AS BIGINT) AS figures,
    "figures_article",
    "figures_comments",
    CAST("solid" AS BIGINT) AS solid,
    "solid_article",
    "solid_comments",
    CAST("overthrw" AS BIGINT) AS overthrw,
    "overthrw_article",
    "overthrw_comments",
    CAST("terr" AS BIGINT) AS terr,
    "terr_article",
    "terr_comments",
    CAST("capital" AS BIGINT) AS capital,
    "capital_article",
    "capital_comments",
    CAST("anthem" AS BIGINT) AS anthem,
    "anthem_article",
    "anthem_comments",
    CAST("flag" AS BIGINT) AS flag,
    "flag_article",
    "flag_comments",
    CAST("motto" AS BIGINT) AS motto,
    "motto_article",
    "motto_comments",
    CAST("amend" AS BIGINT) AS amend,
    "amend_article",
    "amend_comments",
    CAST("unamend" AS BIGINT) AS unamend,
    "unamend_article",
    "unamend_comments",
    CAST("amndprop_1" AS BIGINT) AS amndprop_1,
    CAST("amndprop_2" AS BIGINT) AS amndprop_2,
    CAST("amndprop_3" AS BIGINT) AS amndprop_3,
    CAST("amndprop_4" AS BIGINT) AS amndprop_4,
    CAST("amndprop_5" AS BIGINT) AS amndprop_5,
    CAST("amndprop_6" AS BIGINT) AS amndprop_6,
    CAST("amndprop_7" AS BIGINT) AS amndprop_7,
    CAST("amndprop_8" AS BIGINT) AS amndprop_8,
    CAST("amndprop_9" AS BIGINT) AS amndprop_9,
    CAST("amndprop_10" AS BIGINT) AS amndprop_10,
    CAST("amndprop_96" AS BIGINT) AS amndprop_96,
    CAST("amndprop_98" AS BIGINT) AS amndprop_98,
    "amndprop_article",
    "amndprop_comments",
    CAST("amndappr_1" AS BIGINT) AS amndappr_1,
    CAST("amndappr_2" AS BIGINT) AS amndappr_2,
    CAST("amndappr_3" AS BIGINT) AS amndappr_3,
    CAST("amndappr_4" AS BIGINT) AS amndappr_4,
    CAST("amndappr_5" AS BIGINT) AS amndappr_5,
    CAST("amndappr_6" AS BIGINT) AS amndappr_6,
    CAST("amndappr_7" AS BIGINT) AS amndappr_7,
    CAST("amndappr_8" AS BIGINT) AS amndappr_8,
    CAST("amndappr_96" AS BIGINT) AS amndappr_96,
    CAST("amndappr_98" AS BIGINT) AS amndappr_98,
    "amndappr_article",
    "amndappr_comments",
    CAST("amndamaj" AS BIGINT) AS amndamaj,
    "amndamaj_article",
    "amndamaj_comments",
    CAST("amndapct" AS BIGINT) AS amndapct,
    "amndapct_article",
    "amndapct_comments",
    CAST("execindp" AS BIGINT) AS execindp,
    "execindp_article",
    "execindp_comments",
    CAST("execnum" AS BIGINT) AS execnum,
    "execnum_article",
    "execnum_comments",
    CAST("hoshog" AS BIGINT) AS hoshog,
    "hoshog_article",
    "hoshog_comments",
    CAST("hosid" AS BIGINT) AS hosid,
    "hosid_article",
    "hosid_comments",
    CAST("hogid" AS BIGINT) AS hogid,
    "hogid_article",
    "hogid_comments",
    "hosname",
    "hosname_article",
    "hosname_comments",
    CAST("hoselect" AS BIGINT) AS hoselect,
    "hoselect_article",
    "hoselect_comments",
    CAST("hoselsys" AS BIGINT) AS hoselsys,
    "hoselsys_article",
    "hoselsys_comments",
    "hosterm",
    "hosterm_article",
    "hosterm_comments",
    CAST("hosterml" AS BIGINT) AS hosterml,
    "hosterml_article",
    "hosterml_comments",
    CAST("hosage" AS BIGINT) AS hosage,
    "hosage_article",
    "hosage_comments",
    CAST("hosrest_1" AS BIGINT) AS hosrest_1,
    CAST("hosrest_2" AS BIGINT) AS hosrest_2,
    CAST("hosrest_3" AS BIGINT) AS hosrest_3,
    CAST("hosrest_4" AS BIGINT) AS hosrest_4,
    CAST("hosrest_5" AS BIGINT) AS hosrest_5,
    CAST("hosrest_6" AS BIGINT) AS hosrest_6,
    CAST("hosrest_7" AS BIGINT) AS hosrest_7,
    CAST("hosrest_8" AS BIGINT) AS hosrest_8,
    CAST("hosrest_9" AS BIGINT) AS hosrest_9,
    CAST("hosrest_10" AS BIGINT) AS hosrest_10,
    CAST("hosrest_11" AS BIGINT) AS hosrest_11,
    CAST("hosrest_90" AS BIGINT) AS hosrest_90,
    CAST("hosrest_96" AS BIGINT) AS hosrest_96,
    CAST("hosrest_98" AS BIGINT) AS hosrest_98,
    "hosrest_article",
    "hosrest_comments",
    CAST("hosdiss" AS BIGINT) AS hosdiss,
    "hosdiss_article",
    "hosdiss_comments",
    CAST("hosdcond_1" AS BIGINT) AS hosdcond_1,
    CAST("hosdcond_2" AS BIGINT) AS hosdcond_2,
    CAST("hosdcond_3" AS BIGINT) AS hosdcond_3,
    CAST("hosdcond_4" AS BIGINT) AS hosdcond_4,
    CAST("hosdcond_5" AS BIGINT) AS hosdcond_5,
    CAST("hosdcond_90" AS BIGINT) AS hosdcond_90,
    CAST("hosdcond_96" AS BIGINT) AS hosdcond_96,
    CAST("hosdcond_98" AS BIGINT) AS hosdcond_98,
    "hosdcond_article",
    "hosdcond_comments",
    CAST("hospdiss_1" AS BIGINT) AS hospdiss_1,
    CAST("hospdiss_2" AS BIGINT) AS hospdiss_2,
    CAST("hospdiss_3" AS BIGINT) AS hospdiss_3,
    CAST("hospdiss_4" AS BIGINT) AS hospdiss_4,
    CAST("hospdiss_5" AS BIGINT) AS hospdiss_5,
    CAST("hospdiss_6" AS BIGINT) AS hospdiss_6,
    CAST("hospdiss_7" AS BIGINT) AS hospdiss_7,
    CAST("hospdiss_8" AS BIGINT) AS hospdiss_8,
    CAST("hospdiss_9" AS BIGINT) AS hospdiss_9,
    CAST("hospdiss_90" AS BIGINT) AS hospdiss_90,
    CAST("hospdiss_96" AS BIGINT) AS hospdiss_96,
    CAST("hospdiss_98" AS BIGINT) AS hospdiss_98,
    "hospdiss_article",
    "hospdiss_comments",
    CAST("hosadiss_1" AS BIGINT) AS hosadiss_1,
    CAST("hosadiss_2" AS BIGINT) AS hosadiss_2,
    CAST("hosadiss_3" AS BIGINT) AS hosadiss_3,
    CAST("hosadiss_4" AS BIGINT) AS hosadiss_4,
    CAST("hosadiss_5" AS BIGINT) AS hosadiss_5,
    CAST("hosadiss_6" AS BIGINT) AS hosadiss_6,
    CAST("hosadiss_7" AS BIGINT) AS hosadiss_7,
    CAST("hosadiss_8" AS BIGINT) AS hosadiss_8,
    CAST("hosadiss_9" AS BIGINT) AS hosadiss_9,
    CAST("hosadiss_10" AS BIGINT) AS hosadiss_10,
    CAST("hosadiss_90" AS BIGINT) AS hosadiss_90,
    CAST("hosadiss_96" AS BIGINT) AS hosadiss_96,
    CAST("hosadiss_98" AS BIGINT) AS hosadiss_98,
    "hosadiss_article",
    "hosadiss_comments",
    CAST("hossucc" AS BIGINT) AS hossucc,
    "hossucc_article",
    "hossucc_comments",
    CAST("hosimm" AS BIGINT) AS hosimm,
    "hosimm_article",
    "hosimm_comments",
    CAST("hosstaff" AS BIGINT) AS hosstaff,
    "hosstaff_article",
    "hosstaff_comments",
    CAST("hosdec" AS BIGINT) AS hosdec,
    "hosdec_article",
    "hosdec_comments",
    CAST("hosdecim" AS BIGINT) AS hosdecim,
    "hosdecim_article",
    "hosdecim_comments",
    CAST("hosdecex" AS BIGINT) AS hosdecex,
    "hosdecex_article",
    "hosdecex_comments",
    CAST("hospard" AS BIGINT) AS hospard,
    "hospard_article",
    "hospard_comments",
    CAST("hogname" AS BIGINT) AS hogname,
    "hogname_article",
    "hogname_comments",
    CAST("hogelect" AS BIGINT) AS hogelect,
    "hogelect_article",
    "hogelect_comments",
    "hogterm",
    "hogterm_article",
    "hogterm_comments",
    CAST("hogterml" AS BIGINT) AS hogterml,
    "hogterml_article",
    "hogterml_comments",
    CAST("hogage" AS BIGINT) AS hogage,
    "hogage_article",
    "hogage_comments",
    CAST("hoglegr" AS BIGINT) AS hoglegr,
    "hoglegr_article",
    "hoglegr_comments",
    CAST("hogrest_1" AS BIGINT) AS hogrest_1,
    CAST("hogrest_2" AS BIGINT) AS hogrest_2,
    CAST("hogrest_3" AS BIGINT) AS hogrest_3,
    CAST("hogrest_4" AS BIGINT) AS hogrest_4,
    CAST("hogrest_5" AS BIGINT) AS hogrest_5,
    CAST("hogrest_6" AS BIGINT) AS hogrest_6,
    CAST("hogrest_7" AS BIGINT) AS hogrest_7,
    CAST("hogrest_8" AS BIGINT) AS hogrest_8,
    CAST("hogrest_9" AS BIGINT) AS hogrest_9,
    CAST("hogrest_10" AS BIGINT) AS hogrest_10,
    CAST("hogrest_11" AS BIGINT) AS hogrest_11,
    CAST("hogrest_90" AS BIGINT) AS hogrest_90,
    CAST("hogrest_96" AS BIGINT) AS hogrest_96,
    CAST("hogrest_98" AS BIGINT) AS hogrest_98,
    "hogrest_article",
    "hogrest_comments",
    CAST("hogdiss" AS BIGINT) AS hogdiss,
    "hogdiss_article",
    "hogdiss_comments",
    CAST("hogdcond_1" AS BIGINT) AS hogdcond_1,
    CAST("hogdcond_2" AS BIGINT) AS hogdcond_2,
    CAST("hogdcond_3" AS BIGINT) AS hogdcond_3,
    CAST("hogdcond_4" AS BIGINT) AS hogdcond_4,
    CAST("hogdcond_5" AS BIGINT) AS hogdcond_5,
    CAST("hogdcond_90" AS BIGINT) AS hogdcond_90,
    CAST("hogdcond_96" AS BIGINT) AS hogdcond_96,
    CAST("hogdcond_98" AS BIGINT) AS hogdcond_98,
    "hogdcond_article",
    "hogdcond_comments",
    CAST("hogpdiss_1" AS BIGINT) AS hogpdiss_1,
    CAST("hogpdiss_2" AS BIGINT) AS hogpdiss_2,
    CAST("hogpdiss_3" AS BIGINT) AS hogpdiss_3,
    CAST("hogpdiss_4" AS BIGINT) AS hogpdiss_4,
    CAST("hogpdiss_5" AS BIGINT) AS hogpdiss_5,
    CAST("hogpdiss_6" AS BIGINT) AS hogpdiss_6,
    CAST("hogpdiss_7" AS BIGINT) AS hogpdiss_7,
    CAST("hogpdiss_8" AS BIGINT) AS hogpdiss_8,
    CAST("hogpdiss_9" AS BIGINT) AS hogpdiss_9,
    CAST("hogpdiss_90" AS BIGINT) AS hogpdiss_90,
    CAST("hogpdiss_96" AS BIGINT) AS hogpdiss_96,
    CAST("hogpdiss_98" AS BIGINT) AS hogpdiss_98,
    "hogpdiss_article",
    "hogpdiss_comments",
    CAST("hogadiss_1" AS BIGINT) AS hogadiss_1,
    CAST("hogadiss_2" AS BIGINT) AS hogadiss_2,
    CAST("hogadiss_3" AS BIGINT) AS hogadiss_3,
    CAST("hogadiss_4" AS BIGINT) AS hogadiss_4,
    CAST("hogadiss_5" AS BIGINT) AS hogadiss_5,
    CAST("hogadiss_6" AS BIGINT) AS hogadiss_6,
    CAST("hogadiss_7" AS BIGINT) AS hogadiss_7,
    CAST("hogadiss_8" AS BIGINT) AS hogadiss_8,
    CAST("hogadiss_90" AS BIGINT) AS hogadiss_90,
    CAST("hogadiss_96" AS BIGINT) AS hogadiss_96,
    CAST("hogadiss_98" AS BIGINT) AS hogadiss_98,
    "hogadiss_article",
    "hogadiss_comments",
    CAST("hogsucc" AS BIGINT) AS hogsucc,
    "hogsucc_article",
    "hogsucc_comments",
    CAST("hogimm" AS BIGINT) AS hogimm,
    "hogimm_article",
    "hogimm_comments",
    CAST("hogdec" AS BIGINT) AS hogdec,
    "hogdec_article",
    "hogdec_comments",
    CAST("hogdecim" AS BIGINT) AS hogdecim,
    "hogdecim_article",
    "hogdecim_comments",
    CAST("hogdecex" AS BIGINT) AS hogdecex,
    "hogdecex_article",
    "hogdecex_comments",
    CAST("hogpard" AS BIGINT) AS hogpard,
    "hogpard_article",
    "hogpard_comments",
    CAST("depexec" AS BIGINT) AS depexec,
    "depexec_article",
    "depexec_comments",
    "depname",
    "depname_article",
    "depname_comments",
    CAST("depsel" AS BIGINT) AS depsel,
    "depsel_article",
    "depsel_comments",
    CAST("depnom_1" AS BIGINT) AS depnom_1,
    CAST("depnom_2" AS BIGINT) AS depnom_2,
    CAST("depnom_3" AS BIGINT) AS depnom_3,
    CAST("depnom_4" AS BIGINT) AS depnom_4,
    CAST("depnom_5" AS BIGINT) AS depnom_5,
    CAST("depnom_6" AS BIGINT) AS depnom_6,
    CAST("depnom_7" AS BIGINT) AS depnom_7,
    CAST("depnom_90" AS BIGINT) AS depnom_90,
    CAST("depnom_96" AS BIGINT) AS depnom_96,
    CAST("depnom_98" AS BIGINT) AS depnom_98,
    "depnom_article",
    "depnom_comments",
    CAST("depapp_1" AS BIGINT) AS depapp_1,
    CAST("depapp_2" AS BIGINT) AS depapp_2,
    CAST("depapp_3" AS BIGINT) AS depapp_3,
    CAST("depapp_4" AS BIGINT) AS depapp_4,
    CAST("depapp_5" AS BIGINT) AS depapp_5,
    CAST("depapp_6" AS BIGINT) AS depapp_6,
    CAST("depapp_7" AS BIGINT) AS depapp_7,
    CAST("depapp_90" AS BIGINT) AS depapp_90,
    CAST("depapp_96" AS BIGINT) AS depapp_96,
    CAST("depapp_98" AS BIGINT) AS depapp_98,
    "depapp_article",
    "depapp_comments",
    CAST("cabinet" AS BIGINT) AS cabinet,
    "cabinet_article",
    "cabinet_comments",
    CAST("cabappt_1" AS BIGINT) AS cabappt_1,
    CAST("cabappt_2" AS BIGINT) AS cabappt_2,
    CAST("cabappt_3" AS BIGINT) AS cabappt_3,
    CAST("cabappt_4" AS BIGINT) AS cabappt_4,
    CAST("cabappt_5" AS BIGINT) AS cabappt_5,
    CAST("cabappt_90" AS BIGINT) AS cabappt_90,
    CAST("cabappt_96" AS BIGINT) AS cabappt_96,
    CAST("cabappt_98" AS BIGINT) AS cabappt_98,
    "cabappt_article",
    "cabappt_comments",
    CAST("cabappr_1" AS BIGINT) AS cabappr_1,
    CAST("cabappr_2" AS BIGINT) AS cabappr_2,
    CAST("cabappr_3" AS BIGINT) AS cabappr_3,
    CAST("cabappr_4" AS BIGINT) AS cabappr_4,
    CAST("cabappr_5" AS BIGINT) AS cabappr_5,
    CAST("cabappr_6" AS BIGINT) AS cabappr_6,
    CAST("cabappr_7" AS BIGINT) AS cabappr_7,
    CAST("cabappr_90" AS BIGINT) AS cabappr_90,
    CAST("cabappr_96" AS BIGINT) AS cabappr_96,
    CAST("cabappr_98" AS BIGINT) AS cabappr_98,
    "cabappr_article",
    "cabappr_comments",
    CAST("cabcoll" AS BIGINT) AS cabcoll,
    "cabcoll_article",
    "cabcoll_comments",
    CAST("cabdiss_1" AS BIGINT) AS cabdiss_1,
    CAST("cabdiss_2" AS BIGINT) AS cabdiss_2,
    CAST("cabdiss_3" AS BIGINT) AS cabdiss_3,
    CAST("cabdiss_4" AS BIGINT) AS cabdiss_4,
    CAST("cabdiss_5" AS BIGINT) AS cabdiss_5,
    CAST("cabdiss_6" AS BIGINT) AS cabdiss_6,
    CAST("cabdiss_7" AS BIGINT) AS cabdiss_7,
    CAST("cabdiss_8" AS BIGINT) AS cabdiss_8,
    CAST("cabdiss_90" AS BIGINT) AS cabdiss_90,
    CAST("cabdiss_96" AS BIGINT) AS cabdiss_96,
    CAST("cabdiss_98" AS BIGINT) AS cabdiss_98,
    "cabdiss_article",
    "cabdiss_comments",
    CAST("cabage" AS BIGINT) AS cabage,
    "cabage_article",
    "cabage_comments",
    CAST("cabrestl" AS BIGINT) AS cabrestl,
    "cabrestl_article",
    "cabrestl_comments",
    CAST("cabrestm_1" AS BIGINT) AS cabrestm_1,
    CAST("cabrestm_2" AS BIGINT) AS cabrestm_2,
    CAST("cabrestm_3" AS BIGINT) AS cabrestm_3,
    CAST("cabrestm_4" AS BIGINT) AS cabrestm_4,
    CAST("cabrestm_5" AS BIGINT) AS cabrestm_5,
    CAST("cabrestm_6" AS BIGINT) AS cabrestm_6,
    CAST("cabrestm_7" AS BIGINT) AS cabrestm_7,
    CAST("cabrestm_8" AS BIGINT) AS cabrestm_8,
    CAST("cabrestm_9" AS BIGINT) AS cabrestm_9,
    CAST("cabrestm_90" AS BIGINT) AS cabrestm_90,
    CAST("cabrestm_96" AS BIGINT) AS cabrestm_96,
    CAST("cabrestm_98" AS BIGINT) AS cabrestm_98,
    "cabrestm_article",
    "cabrestm_comments",
    CAST("atgen" AS BIGINT) AS atgen,
    "atgen_article",
    "atgen_comments",
    CAST("agnom_1" AS BIGINT) AS agnom_1,
    CAST("agnom_2" AS BIGINT) AS agnom_2,
    CAST("agnom_3" AS BIGINT) AS agnom_3,
    CAST("agnom_4" AS BIGINT) AS agnom_4,
    CAST("agnom_5" AS BIGINT) AS agnom_5,
    CAST("agnom_6" AS BIGINT) AS agnom_6,
    CAST("agnom_7" AS BIGINT) AS agnom_7,
    CAST("agnom_90" AS BIGINT) AS agnom_90,
    CAST("agnom_96" AS BIGINT) AS agnom_96,
    CAST("agnom_98" AS BIGINT) AS agnom_98,
    "agnom_article",
    "agnom_comments",
    CAST("agap_1" AS BIGINT) AS agap_1,
    CAST("agap_2" AS BIGINT) AS agap_2,
    CAST("agap_3" AS BIGINT) AS agap_3,
    CAST("agap_4" AS BIGINT) AS agap_4,
    CAST("agap_5" AS BIGINT) AS agap_5,
    CAST("agap_6" AS BIGINT) AS agap_6,
    CAST("agap_7" AS BIGINT) AS agap_7,
    CAST("agap_90" AS BIGINT) AS agap_90,
    CAST("agap_96" AS BIGINT) AS agap_96,
    CAST("agap_98" AS BIGINT) AS agap_98,
    "agap_article",
    "agap_comments",
    "agterm",
    "agterm_article",
    "agterm_comments",
    CAST("agterml" AS BIGINT) AS agterml,
    "agterml_article",
    "agterml_comments",
    CAST("agage" AS BIGINT) AS agage,
    "agage_article",
    "agage_comments",
    CAST("agres_1" AS BIGINT) AS agres_1,
    CAST("agres_2" AS BIGINT) AS agres_2,
    CAST("agres_3" AS BIGINT) AS agres_3,
    CAST("agres_4" AS BIGINT) AS agres_4,
    CAST("agres_5" AS BIGINT) AS agres_5,
    CAST("agres_6" AS BIGINT) AS agres_6,
    CAST("agres_7" AS BIGINT) AS agres_7,
    CAST("agres_8" AS BIGINT) AS agres_8,
    CAST("agres_9" AS BIGINT) AS agres_9,
    CAST("agres_90" AS BIGINT) AS agres_90,
    CAST("agres_96" AS BIGINT) AS agres_96,
    CAST("agres_98" AS BIGINT) AS agres_98,
    "agres_article",
    "agres_comments",
    CAST("em" AS BIGINT) AS em,
    "em_article",
    "em_comments",
    CAST("emdecl" AS BIGINT) AS emdecl,
    "emdecl_article",
    "emdecl_comments",
    CAST("emappr_1" AS BIGINT) AS emappr_1,
    CAST("emappr_2" AS BIGINT) AS emappr_2,
    CAST("emappr_3" AS BIGINT) AS emappr_3,
    CAST("emappr_4" AS BIGINT) AS emappr_4,
    CAST("emappr_5" AS BIGINT) AS emappr_5,
    CAST("emappr_6" AS BIGINT) AS emappr_6,
    CAST("emappr_7" AS BIGINT) AS emappr_7,
    CAST("emappr_8" AS BIGINT) AS emappr_8,
    CAST("emappr_90" AS BIGINT) AS emappr_90,
    CAST("emappr_96" AS BIGINT) AS emappr_96,
    CAST("emappr_98" AS BIGINT) AS emappr_98,
    "emappr_article",
    "emappr_comments",
    CAST("emcond_1" AS BIGINT) AS emcond_1,
    CAST("emcond_2" AS BIGINT) AS emcond_2,
    CAST("emcond_3" AS BIGINT) AS emcond_3,
    CAST("emcond_4" AS BIGINT) AS emcond_4,
    CAST("emcond_5" AS BIGINT) AS emcond_5,
    CAST("emcond_6" AS BIGINT) AS emcond_6,
    CAST("emcond_90" AS BIGINT) AS emcond_90,
    CAST("emcond_96" AS BIGINT) AS emcond_96,
    CAST("emcond_98" AS BIGINT) AS emcond_98,
    "emcond_article",
    "emcond_comments",
    CAST("emrights" AS BIGINT) AS emrights,
    "emrights_article",
    "emrights_comments",
    CAST("emother_1" AS BIGINT) AS emother_1,
    CAST("emother_2" AS BIGINT) AS emother_2,
    CAST("emother_3" AS BIGINT) AS emother_3,
    CAST("emother_4" AS BIGINT) AS emother_4,
    CAST("emother_5" AS BIGINT) AS emother_5,
    CAST("emother_90" AS BIGINT) AS emother_90,
    CAST("emother_96" AS BIGINT) AS emother_96,
    CAST("emother_98" AS BIGINT) AS emother_98,
    "emother_article",
    "emother_comments",
    CAST("legisl" AS BIGINT) AS legisl,
    "legisl_article",
    "legisl_comments",
    CAST("housenum" AS BIGINT) AS housenum,
    "housenum_article",
    "housenum_comments",
    CAST("legjoint" AS BIGINT) AS legjoint,
    "legjoint_article",
    "legjoint_comments",
    "lhname",
    "lhname_article",
    "lhname_comments",
    CAST("lhlead" AS BIGINT) AS lhlead,
    "lhlead_article",
    "lhlead_comments",
    "lhseats",
    "lhseats_article",
    "lhseats_comments",
    CAST("lhlegis" AS BIGINT) AS lhlegis,
    "lhlegis_article",
    "lhlegis_comments",
    CAST("lhselect_1" AS BIGINT) AS lhselect_1,
    CAST("lhselect_2" AS BIGINT) AS lhselect_2,
    CAST("lhselect_3" AS BIGINT) AS lhselect_3,
    CAST("lhselect_90" AS BIGINT) AS lhselect_90,
    CAST("lhselect_96" AS BIGINT) AS lhselect_96,
    CAST("lhselect_98" AS BIGINT) AS lhselect_98,
    "lhselect_article",
    "lhselect_comments",
    CAST("lhcohort" AS BIGINT) AS lhcohort,
    "lhcohort_article",
    "lhcohort_comments",
    CAST("lhelsys" AS BIGINT) AS lhelsys,
    "lhelsys_article",
    "lhelsys_comments",
    CAST("lhage" AS BIGINT) AS lhage,
    "lhage_article",
    "lhage_comments",
    CAST("lhrest_1" AS BIGINT) AS lhrest_1,
    CAST("lhrest_2" AS BIGINT) AS lhrest_2,
    CAST("lhrest_3" AS BIGINT) AS lhrest_3,
    CAST("lhrest_4" AS BIGINT) AS lhrest_4,
    CAST("lhrest_5" AS BIGINT) AS lhrest_5,
    CAST("lhrest_6" AS BIGINT) AS lhrest_6,
    CAST("lhrest_7" AS BIGINT) AS lhrest_7,
    CAST("lhrest_8" AS BIGINT) AS lhrest_8,
    CAST("lhrest_9" AS BIGINT) AS lhrest_9,
    CAST("lhrest_90" AS BIGINT) AS lhrest_90,
    CAST("lhrest_96" AS BIGINT) AS lhrest_96,
    CAST("lhrest_98" AS BIGINT) AS lhrest_98,
    "lhrest_article",
    "lhrest_comments",
    CAST("lhterm" AS BIGINT) AS lhterm,
    "lhterm_article",
    "lhterm_comments",
    CAST("lhtrmlim" AS BIGINT) AS lhtrmlim,
    "lhtrmlim_article",
    "lhtrmlim_comments",
    CAST("lhquota" AS BIGINT) AS lhquota,
    "lhquota_article",
    "lhquota_comments",
    CAST("lhquotad_1" AS BIGINT) AS lhquotad_1,
    CAST("lhquotad_2" AS BIGINT) AS lhquotad_2,
    CAST("lhquotad_3" AS BIGINT) AS lhquotad_3,
    CAST("lhquotad_4" AS BIGINT) AS lhquotad_4,
    CAST("lhquotad_5" AS BIGINT) AS lhquotad_5,
    CAST("lhquotad_96" AS BIGINT) AS lhquotad_96,
    CAST("lhquotad_98" AS BIGINT) AS lhquotad_98,
    "lhquotad_article",
    "lhquotad_comments",
    "uhname",
    "uhname_article",
    "uhname_comments",
    CAST("uhlead" AS BIGINT) AS uhlead,
    "uhlead_article",
    "uhlead_comments",
    "uhseats",
    "uhseats_article",
    "uhseats_comments",
    CAST("uhlegisl" AS BIGINT) AS uhlegisl,
    "uhlegisl_article",
    "uhlegisl_comments",
    CAST("uhselect_1" AS BIGINT) AS uhselect_1,
    CAST("uhselect_2" AS BIGINT) AS uhselect_2,
    CAST("uhselect_3" AS BIGINT) AS uhselect_3,
    CAST("uhselect_90" AS BIGINT) AS uhselect_90,
    CAST("uhselect_96" AS BIGINT) AS uhselect_96,
    CAST("uhselect_98" AS BIGINT) AS uhselect_98,
    "uhselect_article",
    "uhselect_comments",
    CAST("uhcohort" AS BIGINT) AS uhcohort,
    "uhcohort_article",
    "uhcohort_comments",
    CAST("uhelsys" AS BIGINT) AS uhelsys,
    "uhelsys_article",
    "uhelsys_comments",
    CAST("uhage" AS BIGINT) AS uhage,
    "uhage_article",
    "uhage_comments",
    CAST("uhrest_1" AS BIGINT) AS uhrest_1,
    CAST("uhrest_2" AS BIGINT) AS uhrest_2,
    CAST("uhrest_3" AS BIGINT) AS uhrest_3,
    CAST("uhrest_4" AS BIGINT) AS uhrest_4,
    CAST("uhrest_5" AS BIGINT) AS uhrest_5,
    CAST("uhrest_6" AS BIGINT) AS uhrest_6,
    CAST("uhrest_7" AS BIGINT) AS uhrest_7,
    CAST("uhrest_8" AS BIGINT) AS uhrest_8,
    CAST("uhrest_9" AS BIGINT) AS uhrest_9,
    CAST("uhrest_90" AS BIGINT) AS uhrest_90,
    CAST("uhrest_96" AS BIGINT) AS uhrest_96,
    CAST("uhrest_98" AS BIGINT) AS uhrest_98,
    "uhrest_article",
    "uhrest_comments",
    "uhterm",
    "uhterm_article",
    "uhterm_comments",
    CAST("uhtrmlim" AS BIGINT) AS uhtrmlim,
    "uhtrmlim_article",
    "uhtrmlim_comments",
    CAST("uhquota" AS BIGINT) AS uhquota,
    "uhquota_article",
    "uhquota_comments",
    CAST("uhquotad_1" AS BIGINT) AS uhquotad_1,
    CAST("uhquotad_2" AS BIGINT) AS uhquotad_2,
    CAST("uhquotad_3" AS BIGINT) AS uhquotad_3,
    CAST("uhquotad_4" AS BIGINT) AS uhquotad_4,
    CAST("uhquotad_5" AS BIGINT) AS uhquotad_5,
    CAST("uhquotad_96" AS BIGINT) AS uhquotad_96,
    CAST("uhquotad_98" AS BIGINT) AS uhquotad_98,
    "uhquotad_article",
    "uhquotad_comments",
    CAST("legdiss" AS BIGINT) AS legdiss,
    "legdiss_article",
    "legdiss_comments",
    CAST("remleg" AS BIGINT) AS remleg,
    "remleg_article",
    "remleg_comments",
    CAST("rempro_1" AS BIGINT) AS rempro_1,
    CAST("rempro_2" AS BIGINT) AS rempro_2,
    CAST("rempro_3" AS BIGINT) AS rempro_3,
    CAST("rempro_4" AS BIGINT) AS rempro_4,
    CAST("rempro_5" AS BIGINT) AS rempro_5,
    CAST("rempro_6" AS BIGINT) AS rempro_6,
    CAST("rempro_7" AS BIGINT) AS rempro_7,
    CAST("rempro_90" AS BIGINT) AS rempro_90,
    CAST("rempro_96" AS BIGINT) AS rempro_96,
    CAST("rempro_98" AS BIGINT) AS rempro_98,
    "rempro_article",
    "rempro_comments",
    CAST("legrep" AS BIGINT) AS legrep,
    "legrep_article",
    "legrep_comments",
    CAST("immunity" AS BIGINT) AS immunity,
    "immunity_article",
    "immunity_comments",
    CAST("intexec" AS BIGINT) AS intexec,
    "intexec_article",
    "intexec_comments",
    CAST("invexe" AS BIGINT) AS invexe,
    "invexe_article",
    "invexe_comments",
    CAST("leg_in_1" AS BIGINT) AS leg_in_1,
    CAST("leg_in_2" AS BIGINT) AS leg_in_2,
    CAST("leg_in_3" AS BIGINT) AS leg_in_3,
    CAST("leg_in_4" AS BIGINT) AS leg_in_4,
    CAST("leg_in_5" AS BIGINT) AS leg_in_5,
    CAST("leg_in_6" AS BIGINT) AS leg_in_6,
    CAST("leg_in_7" AS BIGINT) AS leg_in_7,
    CAST("leg_in_96" AS BIGINT) AS leg_in_96,
    CAST("leg_in_98" AS BIGINT) AS leg_in_98,
    "leg_in_article",
    "leg_in_comments",
    CAST("legsupr" AS BIGINT) AS legsupr,
    "legsupr_article",
    "legsupr_comments",
    CAST("legapp" AS BIGINT) AS legapp,
    "legapp_article",
    "legapp_comments",
    CAST("legappdf" AS BIGINT) AS legappdf,
    "legappdf_article",
    "legappdf_comments",
    CAST("legapppt" AS BIGINT) AS legapppt,
    "legapppt_article",
    "legapppt_comments",
    CAST("override" AS BIGINT) AS override,
    "override_article",
    "override_comments",
    CAST("overwho" AS BIGINT) AS overwho,
    "overwho_article",
    "overwho_comments",
    CAST("overpct" AS BIGINT) AS overpct,
    "overpct_article",
    "overpct_comments",
    CAST("specleg_1" AS BIGINT) AS specleg_1,
    CAST("specleg_2" AS BIGINT) AS specleg_2,
    CAST("specleg_3" AS BIGINT) AS specleg_3,
    CAST("specleg_4" AS BIGINT) AS specleg_4,
    CAST("specleg_5" AS BIGINT) AS specleg_5,
    CAST("specleg_96" AS BIGINT) AS specleg_96,
    CAST("specleg_98" AS BIGINT) AS specleg_98,
    "specleg_article",
    "specleg_comments",
    CAST("attend" AS BIGINT) AS attend,
    "attend_article",
    "attend_comments",
    CAST("exsess_1" AS BIGINT) AS exsess_1,
    CAST("exsess_2" AS BIGINT) AS exsess_2,
    CAST("exsess_3" AS BIGINT) AS exsess_3,
    CAST("exsess_4" AS BIGINT) AS exsess_4,
    CAST("exsess_5" AS BIGINT) AS exsess_5,
    CAST("exsess_6" AS BIGINT) AS exsess_6,
    CAST("exsess_96" AS BIGINT) AS exsess_96,
    CAST("exsess_98" AS BIGINT) AS exsess_98,
    "exsess_article",
    "exsess_comments",
    CAST("profleg" AS BIGINT) AS profleg,
    "profleg_article",
    "profleg_comments",
    CAST("assets" AS BIGINT) AS assets,
    "assets_article",
    "assets_comments",
    CAST("income_1" AS BIGINT) AS income_1,
    CAST("income_2" AS BIGINT) AS income_2,
    CAST("income_3" AS BIGINT) AS income_3,
    CAST("income_4" AS BIGINT) AS income_4,
    CAST("income_5" AS BIGINT) AS income_5,
    CAST("income_6" AS BIGINT) AS income_6,
    CAST("income_7" AS BIGINT) AS income_7,
    CAST("income_8" AS BIGINT) AS income_8,
    CAST("income_90" AS BIGINT) AS income_90,
    CAST("income_96" AS BIGINT) AS income_96,
    CAST("income_98" AS BIGINT) AS income_98,
    "income_article",
    "income_comments",
    CAST("pubmeet" AS BIGINT) AS pubmeet,
    "pubmeet_article",
    "pubmeet_comments",
    CAST("pubmin" AS BIGINT) AS pubmin,
    "pubmin_article",
    "pubmin_comments",
    CAST("recvote" AS BIGINT) AS recvote,
    "recvote_article",
    "recvote_comments",
    CAST("quorum" AS BIGINT) AS quorum,
    "quorum_article",
    "quorum_comments",
    "quorumw",
    "quorumw_article",
    "quorumw_comments",
    CAST("commit" AS BIGINT) AS commit,
    "commit_article",
    "commit_comments",
    CAST("levjud" AS BIGINT) AS levjud,
    "levjud_article",
    "levjud_comments",
    CAST("judcrts_1" AS BIGINT) AS judcrts_1,
    CAST("judcrts_2" AS BIGINT) AS judcrts_2,
    CAST("judcrts_3" AS BIGINT) AS judcrts_3,
    CAST("judcrts_4" AS BIGINT) AS judcrts_4,
    CAST("judcrts_5" AS BIGINT) AS judcrts_5,
    CAST("judcrts_6" AS BIGINT) AS judcrts_6,
    CAST("judcrts_7" AS BIGINT) AS judcrts_7,
    CAST("judcrts_8" AS BIGINT) AS judcrts_8,
    CAST("judcrts_9" AS BIGINT) AS judcrts_9,
    CAST("judcrts_96" AS BIGINT) AS judcrts_96,
    CAST("judcrts_98" AS BIGINT) AS judcrts_98,
    "judcrts_article",
    "judcrts_comments",
    CAST("judind" AS BIGINT) AS judind,
    "judind_article",
    "judind_comments",
    CAST("judprec" AS BIGINT) AS judprec,
    "judprec_article",
    "judprec_comments",
    CAST("judfin" AS BIGINT) AS judfin,
    "judfin_article",
    "judfin_comments",
    "supname",
    "supname_article",
    "supname_comments",
    CAST("hocop" AS BIGINT) AS hocop,
    "hocop_article",
    "hocop_comments",
    CAST("hocopw_1" AS BIGINT) AS hocopw_1,
    CAST("hocopw_2" AS BIGINT) AS hocopw_2,
    CAST("hocopw_3" AS BIGINT) AS hocopw_3,
    CAST("hocopw_4" AS BIGINT) AS hocopw_4,
    CAST("hocopw_5" AS BIGINT) AS hocopw_5,
    CAST("hocopw_96" AS BIGINT) AS hocopw_96,
    CAST("hocopw_98" AS BIGINT) AS hocopw_98,
    "hocopw_article",
    "hocopw_comments",
    CAST("chiefnom_1" AS BIGINT) AS chiefnom_1,
    CAST("chiefnom_2" AS BIGINT) AS chiefnom_2,
    CAST("chiefnom_3" AS BIGINT) AS chiefnom_3,
    CAST("chiefnom_4" AS BIGINT) AS chiefnom_4,
    CAST("chiefnom_5" AS BIGINT) AS chiefnom_5,
    CAST("chiefnom_6" AS BIGINT) AS chiefnom_6,
    CAST("chiefnom_7" AS BIGINT) AS chiefnom_7,
    CAST("chiefnom_90" AS BIGINT) AS chiefnom_90,
    CAST("chiefnom_96" AS BIGINT) AS chiefnom_96,
    CAST("chiefnom_98" AS BIGINT) AS chiefnom_98,
    "chiefnom_article",
    "chiefnom_comments",
    CAST("chiefap_1" AS BIGINT) AS chiefap_1,
    CAST("chiefap_2" AS BIGINT) AS chiefap_2,
    CAST("chiefap_3" AS BIGINT) AS chiefap_3,
    CAST("chiefap_4" AS BIGINT) AS chiefap_4,
    CAST("chiefap_5" AS BIGINT) AS chiefap_5,
    CAST("chiefap_6" AS BIGINT) AS chiefap_6,
    CAST("chiefap_7" AS BIGINT) AS chiefap_7,
    CAST("chiefap_90" AS BIGINT) AS chiefap_90,
    CAST("chiefap_96" AS BIGINT) AS chiefap_96,
    CAST("chiefap_98" AS BIGINT) AS chiefap_98,
    "chiefap_article",
    "chiefap_comments",
    "chfterm",
    "chfterm_article",
    "chfterm_comments",
    CAST("chftrmnm" AS BIGINT) AS chftrmnm,
    "chftrmnm_article",
    "chftrmnm_comments",
    CAST("chfage" AS BIGINT) AS chfage,
    "chfage_article",
    "chfage_comments",
    CAST("chfres_1" AS BIGINT) AS chfres_1,
    CAST("chfres_2" AS BIGINT) AS chfres_2,
    CAST("chfres_3" AS BIGINT) AS chfres_3,
    CAST("chfres_4" AS BIGINT) AS chfres_4,
    CAST("chfres_5" AS BIGINT) AS chfres_5,
    CAST("chfres_6" AS BIGINT) AS chfres_6,
    CAST("chfres_7" AS BIGINT) AS chfres_7,
    CAST("chfres_8" AS BIGINT) AS chfres_8,
    CAST("chfres_9" AS BIGINT) AS chfres_9,
    CAST("chfres_10" AS BIGINT) AS chfres_10,
    CAST("chfres_90" AS BIGINT) AS chfres_90,
    CAST("chfres_96" AS BIGINT) AS chfres_96,
    CAST("chfres_98" AS BIGINT) AS chfres_98,
    "chfres_article",
    "chfres_comments",
    CAST("supnom_1" AS BIGINT) AS supnom_1,
    CAST("supnom_2" AS BIGINT) AS supnom_2,
    CAST("supnom_3" AS BIGINT) AS supnom_3,
    CAST("supnom_4" AS BIGINT) AS supnom_4,
    CAST("supnom_5" AS BIGINT) AS supnom_5,
    CAST("supnom_6" AS BIGINT) AS supnom_6,
    CAST("supnom_7" AS BIGINT) AS supnom_7,
    CAST("supnom_90" AS BIGINT) AS supnom_90,
    CAST("supnom_96" AS BIGINT) AS supnom_96,
    CAST("supnom_98" AS BIGINT) AS supnom_98,
    "supnom_article",
    "supnom_comments",
    CAST("supap_1" AS BIGINT) AS supap_1,
    CAST("supap_2" AS BIGINT) AS supap_2,
    CAST("supap_3" AS BIGINT) AS supap_3,
    CAST("supap_4" AS BIGINT) AS supap_4,
    CAST("supap_5" AS BIGINT) AS supap_5,
    CAST("supap_6" AS BIGINT) AS supap_6,
    CAST("supap_7" AS BIGINT) AS supap_7,
    CAST("supap_90" AS BIGINT) AS supap_90,
    CAST("supap_96" AS BIGINT) AS supap_96,
    CAST("supap_98" AS BIGINT) AS supap_98,
    "supap_article",
    "supap_comments",
    CAST("supterm" AS BIGINT) AS supterm,
    "supterm_article",
    "supterm_comments",
    CAST("suptermn" AS BIGINT) AS suptermn,
    "suptermn_article",
    "suptermn_comments",
    CAST("supage" AS BIGINT) AS supage,
    "supage_article",
    "supage_comments",
    CAST("supres_1" AS BIGINT) AS supres_1,
    CAST("supres_2" AS BIGINT) AS supres_2,
    CAST("supres_3" AS BIGINT) AS supres_3,
    CAST("supres_4" AS BIGINT) AS supres_4,
    CAST("supres_5" AS BIGINT) AS supres_5,
    CAST("supres_6" AS BIGINT) AS supres_6,
    CAST("supres_7" AS BIGINT) AS supres_7,
    CAST("supres_8" AS BIGINT) AS supres_8,
    CAST("supres_9" AS BIGINT) AS supres_9,
    CAST("supres_10" AS BIGINT) AS supres_10,
    CAST("supres_90" AS BIGINT) AS supres_90,
    CAST("supres_96" AS BIGINT) AS supres_96,
    CAST("supres_98" AS BIGINT) AS supres_98,
    "supres_article",
    "supres_comments",
    "ordname",
    "ordname_article",
    "ordname_comments",
    CAST("ordnom_1" AS BIGINT) AS ordnom_1,
    CAST("ordnom_2" AS BIGINT) AS ordnom_2,
    CAST("ordnom_3" AS BIGINT) AS ordnom_3,
    CAST("ordnom_4" AS BIGINT) AS ordnom_4,
    CAST("ordnom_5" AS BIGINT) AS ordnom_5,
    CAST("ordnom_6" AS BIGINT) AS ordnom_6,
    CAST("ordnom_7" AS BIGINT) AS ordnom_7,
    CAST("ordnom_90" AS BIGINT) AS ordnom_90,
    CAST("ordnom_96" AS BIGINT) AS ordnom_96,
    CAST("ordnom_98" AS BIGINT) AS ordnom_98,
    "ordnom_article",
    "ordnom_comments",
    CAST("ordap_1" AS BIGINT) AS ordap_1,
    CAST("ordap_2" AS BIGINT) AS ordap_2,
    CAST("ordap_3" AS BIGINT) AS ordap_3,
    CAST("ordap_4" AS BIGINT) AS ordap_4,
    CAST("ordap_5" AS BIGINT) AS ordap_5,
    CAST("ordap_6" AS BIGINT) AS ordap_6,
    CAST("ordap_7" AS BIGINT) AS ordap_7,
    CAST("ordap_90" AS BIGINT) AS ordap_90,
    CAST("ordap_96" AS BIGINT) AS ordap_96,
    CAST("ordap_98" AS BIGINT) AS ordap_98,
    "ordap_article",
    "ordap_comments",
    "ordterm",
    "ordterm_article",
    "ordterm_comments",
    CAST("ordterml" AS BIGINT) AS ordterml,
    "ordterml_article",
    "ordterml_comments",
    CAST("ordage" AS BIGINT) AS ordage,
    "ordage_article",
    "ordage_comments",
    CAST("ordres_1" AS BIGINT) AS ordres_1,
    CAST("ordres_2" AS BIGINT) AS ordres_2,
    CAST("ordres_3" AS BIGINT) AS ordres_3,
    CAST("ordres_4" AS BIGINT) AS ordres_4,
    CAST("ordres_5" AS BIGINT) AS ordres_5,
    CAST("ordres_6" AS BIGINT) AS ordres_6,
    CAST("ordres_7" AS BIGINT) AS ordres_7,
    CAST("ordres_8" AS BIGINT) AS ordres_8,
    CAST("ordres_9" AS BIGINT) AS ordres_9,
    CAST("ordres_10" AS BIGINT) AS ordres_10,
    CAST("ordres_90" AS BIGINT) AS ordres_90,
    CAST("ordres_96" AS BIGINT) AS ordres_96,
    CAST("ordres_98" AS BIGINT) AS ordres_98,
    "ordres_article",
    "ordres_comments",
    CAST("adnom_1" AS BIGINT) AS adnom_1,
    CAST("adnom_2" AS BIGINT) AS adnom_2,
    CAST("adnom_3" AS BIGINT) AS adnom_3,
    CAST("adnom_4" AS BIGINT) AS adnom_4,
    CAST("adnom_5" AS BIGINT) AS adnom_5,
    CAST("adnom_6" AS BIGINT) AS adnom_6,
    CAST("adnom_7" AS BIGINT) AS adnom_7,
    CAST("adnom_90" AS BIGINT) AS adnom_90,
    CAST("adnom_96" AS BIGINT) AS adnom_96,
    CAST("adnom_98" AS BIGINT) AS adnom_98,
    "adnom_article",
    "adnom_comments",
    CAST("adap_1" AS BIGINT) AS adap_1,
    CAST("adap_2" AS BIGINT) AS adap_2,
    CAST("adap_3" AS BIGINT) AS adap_3,
    CAST("adap_4" AS BIGINT) AS adap_4,
    CAST("adap_5" AS BIGINT) AS adap_5,
    CAST("adap_6" AS BIGINT) AS adap_6,
    CAST("adap_7" AS BIGINT) AS adap_7,
    CAST("adap_90" AS BIGINT) AS adap_90,
    CAST("adap_96" AS BIGINT) AS adap_96,
    CAST("adap_98" AS BIGINT) AS adap_98,
    "adap_article",
    "adap_comments",
    "adterm",
    "adterm_article",
    "adterm_comments",
    CAST("adtermn" AS BIGINT) AS adtermn,
    "adtermn_article",
    "adtermn_comments",
    CAST("adage" AS BIGINT) AS adage,
    "adage_article",
    "adage_comments",
    CAST("adres_1" AS BIGINT) AS adres_1,
    CAST("adres_2" AS BIGINT) AS adres_2,
    CAST("adres_3" AS BIGINT) AS adres_3,
    CAST("adres_4" AS BIGINT) AS adres_4,
    CAST("adres_5" AS BIGINT) AS adres_5,
    CAST("adres_6" AS BIGINT) AS adres_6,
    CAST("adres_7" AS BIGINT) AS adres_7,
    CAST("adres_8" AS BIGINT) AS adres_8,
    CAST("adres_9" AS BIGINT) AS adres_9,
    CAST("adres_10" AS BIGINT) AS adres_10,
    CAST("adres_90" AS BIGINT) AS adres_90,
    CAST("adres_96" AS BIGINT) AS adres_96,
    CAST("adres_98" AS BIGINT) AS adres_98,
    "adres_article",
    "adres_comments",
    CAST("illadmin" AS BIGINT) AS illadmin,
    "illadmin_article",
    "illadmin_comments",
    CAST("connom_1" AS BIGINT) AS connom_1,
    CAST("connom_2" AS BIGINT) AS connom_2,
    CAST("connom_3" AS BIGINT) AS connom_3,
    CAST("connom_4" AS BIGINT) AS connom_4,
    CAST("connom_5" AS BIGINT) AS connom_5,
    CAST("connom_6" AS BIGINT) AS connom_6,
    CAST("connom_7" AS BIGINT) AS connom_7,
    CAST("connom_90" AS BIGINT) AS connom_90,
    CAST("connom_96" AS BIGINT) AS connom_96,
    CAST("connom_98" AS BIGINT) AS connom_98,
    "connom_article",
    "connom_comments",
    CAST("conap_1" AS BIGINT) AS conap_1,
    CAST("conap_2" AS BIGINT) AS conap_2,
    CAST("conap_3" AS BIGINT) AS conap_3,
    CAST("conap_4" AS BIGINT) AS conap_4,
    CAST("conap_5" AS BIGINT) AS conap_5,
    CAST("conap_6" AS BIGINT) AS conap_6,
    CAST("conap_7" AS BIGINT) AS conap_7,
    CAST("conap_90" AS BIGINT) AS conap_90,
    CAST("conap_96" AS BIGINT) AS conap_96,
    CAST("conap_98" AS BIGINT) AS conap_98,
    "conap_article",
    "conap_comments",
    CAST("conrem" AS BIGINT) AS conrem,
    "conrem_article",
    "conrem_comments",
    "conterm",
    "conterm_article",
    "conterm_comments",
    CAST("conlim" AS BIGINT) AS conlim,
    "conlim_article",
    "conlim_comments",
    CAST("conage" AS BIGINT) AS conage,
    "conage_article",
    "conage_comments",
    CAST("conres_1" AS BIGINT) AS conres_1,
    CAST("conres_2" AS BIGINT) AS conres_2,
    CAST("conres_3" AS BIGINT) AS conres_3,
    CAST("conres_4" AS BIGINT) AS conres_4,
    CAST("conres_5" AS BIGINT) AS conres_5,
    CAST("conres_6" AS BIGINT) AS conres_6,
    CAST("conres_7" AS BIGINT) AS conres_7,
    CAST("conres_8" AS BIGINT) AS conres_8,
    CAST("conres_9" AS BIGINT) AS conres_9,
    CAST("conres_10" AS BIGINT) AS conres_10,
    CAST("conres_90" AS BIGINT) AS conres_90,
    CAST("conres_96" AS BIGINT) AS conres_96,
    CAST("conres_98" AS BIGINT) AS conres_98,
    "conres_article",
    "conres_comments",
    CAST("conpow_1" AS BIGINT) AS conpow_1,
    CAST("conpow_2" AS BIGINT) AS conpow_2,
    CAST("conpow_3" AS BIGINT) AS conpow_3,
    CAST("conpow_4" AS BIGINT) AS conpow_4,
    CAST("conpow_5" AS BIGINT) AS conpow_5,
    CAST("conpow_6" AS BIGINT) AS conpow_6,
    CAST("conpow_90" AS BIGINT) AS conpow_90,
    CAST("conpow_96" AS BIGINT) AS conpow_96,
    CAST("conpow_98" AS BIGINT) AS conpow_98,
    "conpow_article",
    "conpow_comments",
    CAST("concop" AS BIGINT) AS concop,
    "concop_article",
    "concop_comments",
    CAST("concopw_1" AS BIGINT) AS concopw_1,
    CAST("concopw_2" AS BIGINT) AS concopw_2,
    CAST("concopw_3" AS BIGINT) AS concopw_3,
    CAST("concopw_4" AS BIGINT) AS concopw_4,
    CAST("concopw_5" AS BIGINT) AS concopw_5,
    CAST("concopw_90" AS BIGINT) AS concopw_90,
    CAST("concopw_96" AS BIGINT) AS concopw_96,
    CAST("concopw_98" AS BIGINT) AS concopw_98,
    "concopw_article",
    "concopw_comments",
    CAST("interp_1" AS BIGINT) AS interp_1,
    CAST("interp_2" AS BIGINT) AS interp_2,
    CAST("interp_3" AS BIGINT) AS interp_3,
    CAST("interp_4" AS BIGINT) AS interp_4,
    CAST("interp_5" AS BIGINT) AS interp_5,
    CAST("interp_6" AS BIGINT) AS interp_6,
    CAST("interp_7" AS BIGINT) AS interp_7,
    CAST("interp_90" AS BIGINT) AS interp_90,
    CAST("interp_96" AS BIGINT) AS interp_96,
    CAST("interp_98" AS BIGINT) AS interp_98,
    "interp_article",
    "interp_comments",
    CAST("unconper" AS BIGINT) AS unconper,
    "unconper_article",
    "unconper_comments",
    CAST("challeg_1" AS BIGINT) AS challeg_1,
    CAST("challeg_2" AS BIGINT) AS challeg_2,
    CAST("challeg_3" AS BIGINT) AS challeg_3,
    CAST("challeg_4" AS BIGINT) AS challeg_4,
    CAST("challeg_5" AS BIGINT) AS challeg_5,
    CAST("challeg_6" AS BIGINT) AS challeg_6,
    CAST("challeg_7" AS BIGINT) AS challeg_7,
    CAST("challeg_8" AS BIGINT) AS challeg_8,
    CAST("challeg_9" AS BIGINT) AS challeg_9,
    CAST("challeg_90" AS BIGINT) AS challeg_90,
    CAST("challeg_96" AS BIGINT) AS challeg_96,
    CAST("challeg_98" AS BIGINT) AS challeg_98,
    "challeg_article",
    "challeg_comments",
    CAST("chalstag" AS BIGINT) AS chalstag,
    "chalstag_article",
    "chalstag_comments",
    CAST("amparo" AS BIGINT) AS amparo,
    "amparo_article",
    "amparo_comments",
    CAST("jrem" AS BIGINT) AS jrem,
    "jrem_article",
    "jrem_comments",
    CAST("jremcon_1" AS BIGINT) AS jremcon_1,
    CAST("jremcon_2" AS BIGINT) AS jremcon_2,
    CAST("jremcon_3" AS BIGINT) AS jremcon_3,
    CAST("jremcon_4" AS BIGINT) AS jremcon_4,
    CAST("jremcon_5" AS BIGINT) AS jremcon_5,
    CAST("jremcon_90" AS BIGINT) AS jremcon_90,
    CAST("jremcon_96" AS BIGINT) AS jremcon_96,
    CAST("jremcon_98" AS BIGINT) AS jremcon_98,
    "jremcon_article",
    "jremcon_comments",
    CAST("jrempro_1" AS BIGINT) AS jrempro_1,
    CAST("jrempro_2" AS BIGINT) AS jrempro_2,
    CAST("jrempro_3" AS BIGINT) AS jrempro_3,
    CAST("jrempro_4" AS BIGINT) AS jrempro_4,
    CAST("jrempro_5" AS BIGINT) AS jrempro_5,
    CAST("jrempro_6" AS BIGINT) AS jrempro_6,
    CAST("jrempro_7" AS BIGINT) AS jrempro_7,
    CAST("jrempro_8" AS BIGINT) AS jrempro_8,
    CAST("jrempro_9" AS BIGINT) AS jrempro_9,
    CAST("jrempro_90" AS BIGINT) AS jrempro_90,
    CAST("jrempro_96" AS BIGINT) AS jrempro_96,
    CAST("jrempro_98" AS BIGINT) AS jrempro_98,
    "jrempro_article",
    "jrempro_comments",
    CAST("jremap_1" AS BIGINT) AS jremap_1,
    CAST("jremap_2" AS BIGINT) AS jremap_2,
    CAST("jremap_3" AS BIGINT) AS jremap_3,
    CAST("jremap_4" AS BIGINT) AS jremap_4,
    CAST("jremap_5" AS BIGINT) AS jremap_5,
    CAST("jremap_6" AS BIGINT) AS jremap_6,
    CAST("jremap_7" AS BIGINT) AS jremap_7,
    CAST("jremap_90" AS BIGINT) AS jremap_90,
    CAST("jremap_96" AS BIGINT) AS jremap_96,
    CAST("jremap_98" AS BIGINT) AS jremap_98,
    "jremap_article",
    "jremap_comments",
    CAST("judsal" AS BIGINT) AS judsal,
    "judsal_article",
    "judsal_comments",
    CAST("judretir" AS BIGINT) AS judretir,
    "judretir_article",
    "judretir_comments",
    CAST("fedunit" AS BIGINT) AS fedunit,
    "fedunit_article",
    "fedunit_comments",
    CAST("federal_1" AS BIGINT) AS federal_1,
    CAST("federal_2" AS BIGINT) AS federal_2,
    CAST("federal_3" AS BIGINT) AS federal_3,
    CAST("federal_96" AS BIGINT) AS federal_96,
    CAST("federal_98" AS BIGINT) AS federal_98,
    "federal_article",
    "federal_comments",
    CAST("fedsep" AS BIGINT) AS fedsep,
    "fedsep_article",
    "fedsep_comments",
    CAST("fedrev" AS BIGINT) AS fedrev,
    "fedrev_article",
    "fedrev_comments",
    CAST("seccess" AS BIGINT) AS seccess,
    "seccess_article",
    "seccess_comments",
    CAST("access" AS BIGINT) AS access,
    "access_article",
    "access_comments",
    CAST("indpolgr_1" AS BIGINT) AS indpolgr_1,
    CAST("indpolgr_2" AS BIGINT) AS indpolgr_2,
    CAST("indpolgr_3" AS BIGINT) AS indpolgr_3,
    CAST("indpolgr_4" AS BIGINT) AS indpolgr_4,
    CAST("indpolgr_5" AS BIGINT) AS indpolgr_5,
    CAST("indpolgr_6" AS BIGINT) AS indpolgr_6,
    CAST("indpolgr_7" AS BIGINT) AS indpolgr_7,
    CAST("indpolgr_90" AS BIGINT) AS indpolgr_90,
    CAST("indpolgr_96" AS BIGINT) AS indpolgr_96,
    CAST("indpolgr_98" AS BIGINT) AS indpolgr_98,
    "indpolgr_article",
    "indpolgr_comments",
    CAST("indcit" AS BIGINT) AS indcit,
    "indcit_article",
    "indcit_comments",
    CAST("part" AS BIGINT) AS part,
    "part_article",
    "part_comments",
    CAST("partrght" AS BIGINT) AS partrght,
    "partrght_article",
    "partrght_comments",
    CAST("partprf" AS BIGINT) AS partprf,
    "partprf_article",
    "partprf_comments",
    CAST("partprh" AS BIGINT) AS partprh,
    "partprh_article",
    "partprh_comments",
    CAST("partunco_1" AS BIGINT) AS partunco_1,
    CAST("partunco_2" AS BIGINT) AS partunco_2,
    CAST("partunco_3" AS BIGINT) AS partunco_3,
    CAST("partunco_4" AS BIGINT) AS partunco_4,
    CAST("partunco_5" AS BIGINT) AS partunco_5,
    CAST("partunco_6" AS BIGINT) AS partunco_6,
    CAST("partunco_90" AS BIGINT) AS partunco_90,
    CAST("partunco_96" AS BIGINT) AS partunco_96,
    CAST("partunco_98" AS BIGINT) AS partunco_98,
    "partunco_article",
    "partunco_comments",
    CAST("initiat" AS BIGINT) AS initiat,
    "initiat_article",
    "initiat_comments",
    CAST("initiatp_1" AS BIGINT) AS initiatp_1,
    CAST("initiatp_2" AS BIGINT) AS initiatp_2,
    CAST("initiatp_3" AS BIGINT) AS initiatp_3,
    CAST("initiatp_90" AS BIGINT) AS initiatp_90,
    CAST("initiatp_96" AS BIGINT) AS initiatp_96,
    CAST("initiatp_98" AS BIGINT) AS initiatp_98,
    "initiatp_article",
    "initiatp_comments",
    CAST("referen" AS BIGINT) AS referen,
    "referen_article",
    "referen_comments",
    CAST("referenp_1" AS BIGINT) AS referenp_1,
    CAST("referenp_2" AS BIGINT) AS referenp_2,
    CAST("referenp_3" AS BIGINT) AS referenp_3,
    CAST("referenp_4" AS BIGINT) AS referenp_4,
    CAST("referenp_5" AS BIGINT) AS referenp_5,
    CAST("referenp_6" AS BIGINT) AS referenp_6,
    CAST("referenp_7" AS BIGINT) AS referenp_7,
    CAST("referenp_8" AS BIGINT) AS referenp_8,
    CAST("referenp_9" AS BIGINT) AS referenp_9,
    CAST("referenp_90" AS BIGINT) AS referenp_90,
    CAST("referenp_96" AS BIGINT) AS referenp_96,
    CAST("referenp_98" AS BIGINT) AS referenp_98,
    "referenp_article",
    "referenp_comments",
    CAST("voteres" AS BIGINT) AS voteres,
    "voteres_article",
    "voteres_comments",
    CAST("votemin" AS BIGINT) AS votemin,
    "votemin_article",
    "votemin_comments",
    CAST("votelim_1" AS BIGINT) AS votelim_1,
    CAST("votelim_2" AS BIGINT) AS votelim_2,
    CAST("votelim_3" AS BIGINT) AS votelim_3,
    CAST("votelim_4" AS BIGINT) AS votelim_4,
    CAST("votelim_5" AS BIGINT) AS votelim_5,
    CAST("votelim_6" AS BIGINT) AS votelim_6,
    CAST("votelim_7" AS BIGINT) AS votelim_7,
    CAST("votelim_8" AS BIGINT) AS votelim_8,
    CAST("votelim_9" AS BIGINT) AS votelim_9,
    CAST("votelim_10" AS BIGINT) AS votelim_10,
    CAST("votelim_11" AS BIGINT) AS votelim_11,
    CAST("votelim_12" AS BIGINT) AS votelim_12,
    CAST("votelim_13" AS BIGINT) AS votelim_13,
    CAST("votelim_14" AS BIGINT) AS votelim_14,
    CAST("votelim_15" AS BIGINT) AS votelim_15,
    CAST("votelim_90" AS BIGINT) AS votelim_90,
    CAST("votelim_96" AS BIGINT) AS votelim_96,
    CAST("votelim_98" AS BIGINT) AS votelim_98,
    "votelim_article",
    "votelim_comments",
    CAST("voteun" AS BIGINT) AS voteun,
    "voteun_article",
    "voteun_comments",
    CAST("oversght" AS BIGINT) AS oversght,
    "oversght_article",
    "oversght_comments",
    CAST("ecnom_1" AS BIGINT) AS ecnom_1,
    CAST("ecnom_2" AS BIGINT) AS ecnom_2,
    CAST("ecnom_3" AS BIGINT) AS ecnom_3,
    CAST("ecnom_4" AS BIGINT) AS ecnom_4,
    CAST("ecnom_5" AS BIGINT) AS ecnom_5,
    CAST("ecnom_6" AS BIGINT) AS ecnom_6,
    CAST("ecnom_7" AS BIGINT) AS ecnom_7,
    CAST("ecnom_90" AS BIGINT) AS ecnom_90,
    CAST("ecnom_96" AS BIGINT) AS ecnom_96,
    CAST("ecnom_98" AS BIGINT) AS ecnom_98,
    "ecnom_article",
    "ecnom_comments",
    CAST("ecap_1" AS BIGINT) AS ecap_1,
    CAST("ecap_2" AS BIGINT) AS ecap_2,
    CAST("ecap_3" AS BIGINT) AS ecap_3,
    CAST("ecap_4" AS BIGINT) AS ecap_4,
    CAST("ecap_5" AS BIGINT) AS ecap_5,
    CAST("ecap_6" AS BIGINT) AS ecap_6,
    CAST("ecap_7" AS BIGINT) AS ecap_7,
    CAST("ecap_90" AS BIGINT) AS ecap_90,
    CAST("ecap_96" AS BIGINT) AS ecap_96,
    CAST("ecap_98" AS BIGINT) AS ecap_98,
    "ecap_article",
    "ecap_comments",
    "ecterm",
    "ecterm_article",
    "ecterm_comments",
    CAST("ecterml" AS BIGINT) AS ecterml,
    "ecterml_article",
    "ecterml_comments",
    CAST("ecage" AS BIGINT) AS ecage,
    "ecage_article",
    "ecage_comments",
    CAST("ecres_1" AS BIGINT) AS ecres_1,
    CAST("ecres_2" AS BIGINT) AS ecres_2,
    CAST("ecres_3" AS BIGINT) AS ecres_3,
    CAST("ecres_4" AS BIGINT) AS ecres_4,
    CAST("ecres_5" AS BIGINT) AS ecres_5,
    CAST("ecres_6" AS BIGINT) AS ecres_6,
    CAST("ecres_7" AS BIGINT) AS ecres_7,
    CAST("ecres_8" AS BIGINT) AS ecres_8,
    CAST("ecres_9" AS BIGINT) AS ecres_9,
    CAST("ecres_90" AS BIGINT) AS ecres_90,
    CAST("ecres_96" AS BIGINT) AS ecres_96,
    CAST("ecres_98" AS BIGINT) AS ecres_98,
    "ecres_article",
    "ecres_comments",
    CAST("compvote" AS BIGINT) AS compvote,
    "compvote_article",
    "compvote_comments",
    CAST("freeelec" AS BIGINT) AS freeelec,
    "freeelec_article",
    "freeelec_comments",
    CAST("electsch" AS BIGINT) AS electsch,
    "electsch_article",
    "electsch_comments",
    CAST("camppubf" AS BIGINT) AS camppubf,
    "camppubf_article",
    "camppubf_comments",
    CAST("electfin" AS BIGINT) AS electfin,
    "electfin_article",
    "electfin_comments",
    CAST("electsam" AS BIGINT) AS electsam,
    "electsam_article",
    "electsam_comments",
    CAST("census" AS BIGINT) AS census,
    "census_article",
    "census_comments",
    CAST("ombuds" AS BIGINT) AS ombuds,
    "ombuds_article",
    "ombuds_comments",
    CAST("bank" AS BIGINT) AS bank,
    "bank_article",
    "bank_comments",
    CAST("bankgoal" AS BIGINT) AS bankgoal,
    "bankgoal_article",
    "bankgoal_comments",
    CAST("medcom" AS BIGINT) AS medcom,
    "medcom_article",
    "medcom_comments",
    CAST("jc" AS BIGINT) AS jc,
    "jc_article",
    "jc_comments",
    CAST("cc" AS BIGINT) AS cc,
    "cc_article",
    "cc_comments",
    CAST("civil" AS BIGINT) AS civil,
    "civil_article",
    "civil_comments",
    CAST("hr" AS BIGINT) AS hr,
    "hr_article",
    "hr_comments",
    CAST("exinst" AS BIGINT) AS exinst,
    "exinst_article",
    "exinst_comments",
    "exinst1",
    "exinst1_article",
    "exinst1_comments",
    CAST("intlaw" AS BIGINT) AS intlaw,
    "intlaw_article",
    "intlaw_comments",
    CAST("custlaw" AS BIGINT) AS custlaw,
    "custlaw_article",
    "custlaw_comments",
    CAST("custlaw2" AS BIGINT) AS custlaw2,
    "custlaw2_article",
    "custlaw2_comments",
    CAST("intorgs" AS BIGINT) AS intorgs,
    "intorgs_article",
    "intorgs_comments",
    CAST("headforn" AS BIGINT) AS headforn,
    "headforn_article",
    "headforn_comments",
    CAST("war_1" AS BIGINT) AS war_1,
    CAST("war_2" AS BIGINT) AS war_2,
    CAST("war_3" AS BIGINT) AS war_3,
    CAST("war_4" AS BIGINT) AS war_4,
    CAST("war_5" AS BIGINT) AS war_5,
    CAST("war_6" AS BIGINT) AS war_6,
    CAST("war_7" AS BIGINT) AS war_7,
    CAST("war_8" AS BIGINT) AS war_8,
    CAST("war_90" AS BIGINT) AS war_90,
    CAST("war_96" AS BIGINT) AS war_96,
    CAST("war_98" AS BIGINT) AS war_98,
    "war_article",
    "war_comments",
    CAST("warap" AS BIGINT) AS warap,
    "warap_article",
    "warap_comments",
    CAST("treat" AS BIGINT) AS treat,
    "treat_article",
    "treat_comments",
    CAST("treatini_1" AS BIGINT) AS treatini_1,
    CAST("treatini_2" AS BIGINT) AS treatini_2,
    CAST("treatini_3" AS BIGINT) AS treatini_3,
    CAST("treatini_4" AS BIGINT) AS treatini_4,
    CAST("treatini_5" AS BIGINT) AS treatini_5,
    CAST("treatini_6" AS BIGINT) AS treatini_6,
    CAST("treatini_90" AS BIGINT) AS treatini_90,
    CAST("treatini_96" AS BIGINT) AS treatini_96,
    CAST("treatini_98" AS BIGINT) AS treatini_98,
    "treatini_article",
    "treatini_comments",
    CAST("treatap_1" AS BIGINT) AS treatap_1,
    CAST("treatap_2" AS BIGINT) AS treatap_2,
    CAST("treatap_3" AS BIGINT) AS treatap_3,
    CAST("treatap_4" AS BIGINT) AS treatap_4,
    CAST("treatap_5" AS BIGINT) AS treatap_5,
    CAST("treatap_6" AS BIGINT) AS treatap_6,
    CAST("treatap_90" AS BIGINT) AS treatap_90,
    CAST("treatap_96" AS BIGINT) AS treatap_96,
    CAST("treatap_98" AS BIGINT) AS treatap_98,
    "treatap_article",
    "treatap_comments",
    CAST("treatrvw" AS BIGINT) AS treatrvw,
    "treatrvw_article",
    "treatrvw_comments",
    CAST("treatst" AS BIGINT) AS treatst,
    "treatst_article",
    "treatst_comments",
    CAST("provwork" AS BIGINT) AS provwork,
    "provwork_article",
    "provwork_comments",
    CAST("provhlth" AS BIGINT) AS provhlth,
    "provhlth_article",
    "provhlth_comments",
    CAST("cultrght" AS BIGINT) AS cultrght,
    "cultrght_article",
    "cultrght_comments",
    CAST("buildsoc" AS BIGINT) AS buildsoc,
    "buildsoc_article",
    "buildsoc_comments",
    CAST("taxes" AS BIGINT) AS taxes,
    "taxes_article",
    "taxes_comments",
    CAST("milserv" AS BIGINT) AS milserv,
    "milserv_article",
    "milserv_comments",
    CAST("work" AS BIGINT) AS work,
    "work_article",
    "work_comments",
    CAST("prtyduty" AS BIGINT) AS prtyduty,
    CAST("prtyduty_article" AS DOUBLE) AS prtyduty_article,
    "prtyduty_comments",
    CAST("tradeun" AS BIGINT) AS tradeun,
    "tradeun_article",
    "tradeun_comments",
    CAST("jury" AS BIGINT) AS jury,
    "jury_article",
    "jury_comments",
    CAST("grjury" AS BIGINT) AS grjury,
    "grjury_article",
    "grjury_comments",
    CAST("vicright" AS BIGINT) AS vicright,
    "vicright_article",
    "vicright_comments",
    CAST("excrim" AS BIGINT) AS excrim,
    "excrim_article",
    "excrim_comments",
    CAST("evidence" AS BIGINT) AS evidence,
    "evidence_article",
    "evidence_comments",
    CAST("prerel" AS BIGINT) AS prerel,
    "prerel_article",
    "prerel_comments",
    CAST("habcorp" AS BIGINT) AS habcorp,
    "habcorp_article",
    "habcorp_comments",
    CAST("wolaw" AS BIGINT) AS wolaw,
    "wolaw_article",
    "wolaw_comments",
    CAST("rghtapp" AS BIGINT) AS rghtapp,
    "rghtapp_article",
    "rghtapp_comments",
    CAST("prisonrg" AS BIGINT) AS prisonrg,
    "prisonrg_article",
    "prisonrg_comments",
    CAST("cappun" AS BIGINT) AS cappun,
    "cappun_article",
    "cappun_comments",
    CAST("corppun" AS BIGINT) AS corppun,
    "corppun_article",
    "corppun_comments",
    CAST("dueproc" AS BIGINT) AS dueproc,
    "dueproc_article",
    "dueproc_comments",
    CAST("examwit" AS BIGINT) AS examwit,
    "examwit_article",
    "examwit_comments",
    CAST("expost" AS BIGINT) AS expost,
    "expost_article",
    "expost_comments",
    CAST("falseimp" AS BIGINT) AS falseimp,
    "falseimp_article",
    "falseimp_comments",
    CAST("fairtri" AS BIGINT) AS fairtri,
    "fairtri_article",
    "fairtri_comments",
    CAST("speedtri" AS BIGINT) AS speedtri,
    "speedtri_article",
    "speedtri_comments",
    CAST("pubtri" AS BIGINT) AS pubtri,
    "pubtri_article",
    "pubtri_comments",
    CAST("presinoc" AS BIGINT) AS presinoc,
    "presinoc_article",
    "presinoc_comments",
    CAST("trilang" AS BIGINT) AS trilang,
    "trilang_article",
    "trilang_comments",
    CAST("juvenile" AS BIGINT) AS juvenile,
    "juvenile_article",
    "juvenile_comments",
    CAST("doubjep" AS BIGINT) AS doubjep,
    "doubjep_article",
    "doubjep_comments",
    CAST("miranda" AS BIGINT) AS miranda,
    "miranda_article",
    "miranda_comments",
    CAST("couns" AS BIGINT) AS couns,
    "couns_article",
    "couns_comments",
    CAST("counscos" AS BIGINT) AS counscos,
    "counscos_article",
    "counscos_comments",
    CAST("debtors" AS BIGINT) AS debtors,
    "debtors_article",
    "debtors_comments",
    CAST("bankrupt" AS BIGINT) AS bankrupt,
    "bankrupt_article",
    "bankrupt_comments",
    CAST("nat" AS BIGINT) AS nat,
    "nat_article",
    "nat_comments",
    CAST("natcit" AS BIGINT) AS natcit,
    "natcit_article",
    "natcit_comments",
    CAST("citrev_1" AS BIGINT) AS citrev_1,
    CAST("citrev_2" AS BIGINT) AS citrev_2,
    CAST("citrev_3" AS BIGINT) AS citrev_3,
    CAST("citrev_4" AS BIGINT) AS citrev_4,
    CAST("citrev_90" AS BIGINT) AS citrev_90,
    CAST("citrev_96" AS BIGINT) AS citrev_96,
    CAST("citrev_98" AS BIGINT) AS citrev_98,
    "citrev_article",
    "citrev_comments",
    CAST("citren" AS BIGINT) AS citren,
    "citren_article",
    "citren_comments",
    CAST("citdep" AS BIGINT) AS citdep,
    "citdep_article",
    "citdep_comments",
    CAST("resenex" AS BIGINT) AS resenex,
    "resenex_article",
    "resenex_comments",
    CAST("rulelaw" AS BIGINT) AS rulelaw,
    "rulelaw_article",
    "rulelaw_comments",
    CAST("equal" AS BIGINT) AS equal,
    "equal_article",
    "equal_comments",
    CAST("equalgr_1" AS BIGINT) AS equalgr_1,
    CAST("equalgr_2" AS BIGINT) AS equalgr_2,
    CAST("equalgr_3" AS BIGINT) AS equalgr_3,
    CAST("equalgr_4" AS BIGINT) AS equalgr_4,
    CAST("equalgr_5" AS BIGINT) AS equalgr_5,
    CAST("equalgr_6" AS BIGINT) AS equalgr_6,
    CAST("equalgr_7" AS BIGINT) AS equalgr_7,
    CAST("equalgr_8" AS BIGINT) AS equalgr_8,
    CAST("equalgr_9" AS BIGINT) AS equalgr_9,
    CAST("equalgr_10" AS BIGINT) AS equalgr_10,
    CAST("equalgr_11" AS BIGINT) AS equalgr_11,
    CAST("equalgr_12" AS BIGINT) AS equalgr_12,
    CAST("equalgr_13" AS BIGINT) AS equalgr_13,
    CAST("equalgr_14" AS BIGINT) AS equalgr_14,
    CAST("equalgr_15" AS BIGINT) AS equalgr_15,
    CAST("equalgr_16" AS BIGINT) AS equalgr_16,
    CAST("equalgr_90" AS BIGINT) AS equalgr_90,
    CAST("equalgr_96" AS BIGINT) AS equalgr_96,
    CAST("equalgr_98" AS BIGINT) AS equalgr_98,
    "equalgr_article",
    "equalgr_comments",
    CAST("rightres_1" AS BIGINT) AS rightres_1,
    CAST("rightres_2" AS BIGINT) AS rightres_2,
    CAST("rightres_3" AS BIGINT) AS rightres_3,
    CAST("rightres_4" AS BIGINT) AS rightres_4,
    CAST("rightres_5" AS BIGINT) AS rightres_5,
    CAST("rightres_6" AS BIGINT) AS rightres_6,
    CAST("rightres_7" AS BIGINT) AS rightres_7,
    CAST("rightres_8" AS BIGINT) AS rightres_8,
    CAST("rightres_90" AS BIGINT) AS rightres_90,
    CAST("rightres_96" AS BIGINT) AS rightres_96,
    CAST("rightres_98" AS BIGINT) AS rightres_98,
    "rightres_article",
    "rightres_comments",
    CAST("binding" AS BIGINT) AS binding,
    "binding_article",
    "binding_comments",
    CAST("infoacc" AS BIGINT) AS infoacc,
    "infoacc_article",
    "infoacc_comments",
    CAST("infoaccw" AS BIGINT) AS infoaccw,
    "infoaccw_article",
    "infoaccw_comments",
    CAST("libel" AS BIGINT) AS libel,
    "libel_article",
    "libel_comments",
    CAST("offrel" AS BIGINT) AS offrel,
    "offrel_article",
    "offrel_comments",
    CAST("offrelw" AS BIGINT) AS offrelw,
    "offrelw_article",
    "offrelw_comments",
    CAST("freerel" AS BIGINT) AS freerel,
    "freerel_article",
    "freerel_comments",
    CAST("rellaw_1" AS BIGINT) AS rellaw_1,
    CAST("rellaw_2" AS BIGINT) AS rellaw_2,
    CAST("rellaw_3" AS BIGINT) AS rellaw_3,
    CAST("rellaw_90" AS BIGINT) AS rellaw_90,
    CAST("rellaw_96" AS BIGINT) AS rellaw_96,
    CAST("rellaw_98" AS BIGINT) AS rellaw_98,
    "rellaw_article",
    "rellaw_comments",
    CAST("rellawv" AS BIGINT) AS rellawv,
    "rellawv_article",
    "rellawv_comments",
    CAST("seprel" AS BIGINT) AS seprel,
    "seprel_article",
    "seprel_comments",
    CAST("reltax" AS BIGINT) AS reltax,
    "reltax_article",
    "reltax_comments",
    CAST("exprop" AS BIGINT) AS exprop,
    "exprop_article",
    "exprop_comments",
    CAST("exprcomp" AS BIGINT) AS exprcomp,
    "exprcomp_article",
    "exprcomp_comments",
    CAST("expcond_1" AS BIGINT) AS expcond_1,
    CAST("expcond_2" AS BIGINT) AS expcond_2,
    CAST("expcond_3" AS BIGINT) AS expcond_3,
    CAST("expcond_4" AS BIGINT) AS expcond_4,
    CAST("expcond_5" AS BIGINT) AS expcond_5,
    CAST("expcond_6" AS BIGINT) AS expcond_6,
    CAST("expcond_7" AS BIGINT) AS expcond_7,
    CAST("expcond_90" AS BIGINT) AS expcond_90,
    CAST("expcond_96" AS BIGINT) AS expcond_96,
    CAST("expcond_98" AS BIGINT) AS expcond_98,
    "expcond_article",
    "expcond_comments",
    CAST("explim_1" AS BIGINT) AS explim_1,
    CAST("explim_2" AS BIGINT) AS explim_2,
    CAST("explim_3" AS BIGINT) AS explim_3,
    CAST("explim_4" AS BIGINT) AS explim_4,
    CAST("explim_90" AS BIGINT) AS explim_90,
    CAST("explim_96" AS BIGINT) AS explim_96,
    CAST("explim_98" AS BIGINT) AS explim_98,
    "explim_article",
    "explim_comments",
    CAST("socecon" AS BIGINT) AS socecon,
    "socecon_article",
    "socecon_comments",
    CAST("remuner" AS BIGINT) AS remuner,
    "remuner_article",
    "remuner_comments",
    CAST("jointrde" AS BIGINT) AS jointrde,
    "jointrde_article",
    "jointrde_comments",
    CAST("strike" AS BIGINT) AS strike,
    "strike_article",
    "strike_comments",
    CAST("leisure" AS BIGINT) AS leisure,
    "leisure_article",
    "leisure_comments",
    CAST("standliv" AS BIGINT) AS standliv,
    "standliv_article",
    "standliv_comments",
    CAST("transfer" AS BIGINT) AS transfer,
    "transfer_article",
    "transfer_comments",
    CAST("testate" AS BIGINT) AS testate,
    "testate_article",
    "testate_comments",
    CAST("inherit" AS BIGINT) AS inherit,
    "inherit_article",
    "inherit_comments",
    CAST("intprop_1" AS BIGINT) AS intprop_1,
    CAST("intprop_2" AS BIGINT) AS intprop_2,
    CAST("intprop_3" AS BIGINT) AS intprop_3,
    CAST("intprop_4" AS BIGINT) AS intprop_4,
    CAST("intprop_90" AS BIGINT) AS intprop_90,
    CAST("intprop_96" AS BIGINT) AS intprop_96,
    CAST("intprop_98" AS BIGINT) AS intprop_98,
    "intprop_article",
    "intprop_comments",
    CAST("busines" AS BIGINT) AS busines,
    "busines_article",
    "busines_comments",
    CAST("conright" AS BIGINT) AS conright,
    "conright_article",
    "conright_comments",
    CAST("socsec" AS BIGINT) AS socsec,
    "socsec_article",
    "socsec_comments",
    CAST("finsup_1" AS BIGINT) AS finsup_1,
    CAST("finsup_2" AS BIGINT) AS finsup_2,
    CAST("finsup_3" AS BIGINT) AS finsup_3,
    CAST("finsup_4" AS BIGINT) AS finsup_4,
    CAST("finsup_90" AS BIGINT) AS finsup_90,
    CAST("finsup_96" AS BIGINT) AS finsup_96,
    CAST("finsup_98" AS BIGINT) AS finsup_98,
    "finsup_article",
    "finsup_comments",
    CAST("proprght" AS BIGINT) AS proprght,
    "proprght_article",
    "proprght_comments",
    CAST("freecomp" AS BIGINT) AS freecomp,
    "freecomp_article",
    "freecomp_comments",
    CAST("scifree" AS BIGINT) AS scifree,
    "scifree_article",
    "scifree_comments",
    CAST("occupate" AS BIGINT) AS occupate,
    "occupate_article",
    "occupate_comments",
    CAST("safework" AS BIGINT) AS safework,
    "safework_article",
    "safework_comments",
    CAST("childwrk" AS BIGINT) AS childwrk,
    "childwrk_article",
    "childwrk_comments",
    CAST("shelter" AS BIGINT) AS shelter,
    "shelter_article",
    "shelter_comments",
    CAST("marriage" AS BIGINT) AS marriage,
    "marriage_article",
    "marriage_comments",
    CAST("samesexm" AS BIGINT) AS samesexm,
    "samesexm_article",
    "samesexm_comments",
    CAST("fndfam" AS BIGINT) AS fndfam,
    "fndfam_article",
    "fndfam_comments",
    CAST("matequal" AS BIGINT) AS matequal,
    "matequal_article",
    "matequal_comments",
    CAST("childpro" AS BIGINT) AS childpro,
    "childpro_article",
    "childpro_comments",
    CAST("civmar" AS BIGINT) AS civmar,
    "civmar_article",
    "civmar_comments",
    CAST("selfdet" AS BIGINT) AS selfdet,
    "selfdet_article",
    "selfdet_comments",
    CAST("healthr" AS BIGINT) AS healthr,
    "healthr_article",
    "healthr_comments",
    CAST("healthf" AS BIGINT) AS healthf,
    "healthf_article",
    "healthf_comments",
    CAST("life" AS BIGINT) AS life,
    "life_article",
    "life_comments",
    CAST("slave" AS BIGINT) AS slave,
    "slave_article",
    "slave_comments",
    CAST("torture" AS BIGINT) AS torture,
    "torture_article",
    "torture_comments",
    CAST("cruelty" AS BIGINT) AS cruelty,
    "cruelty_article",
    "cruelty_comments",
    CAST("privacy" AS BIGINT) AS privacy,
    "privacy_article",
    "privacy_comments",
    CAST("freemove" AS BIGINT) AS freemove,
    "freemove_article",
    "freemove_comments",
    CAST("opinion" AS BIGINT) AS opinion,
    "opinion_article",
    "opinion_comments",
    CAST("express" AS BIGINT) AS express,
    "express_article",
    "express_comments",
    CAST("petition" AS BIGINT) AS petition,
    "petition_article",
    "petition_comments",
    CAST("censor" AS BIGINT) AS censor,
    "censor_article",
    "censor_comments",
    CAST("press" AS BIGINT) AS press,
    "press_article",
    "press_comments",
    CAST("intrght_1" AS BIGINT) AS intrght_1,
    CAST("intrght_2" AS BIGINT) AS intrght_2,
    CAST("intrght_3" AS BIGINT) AS intrght_3,
    CAST("intrght_4" AS BIGINT) AS intrght_4,
    CAST("intrght_5" AS BIGINT) AS intrght_5,
    CAST("intrght_6" AS BIGINT) AS intrght_6,
    CAST("intrght_7" AS BIGINT) AS intrght_7,
    CAST("intrght_8" AS BIGINT) AS intrght_8,
    CAST("intrght_9" AS BIGINT) AS intrght_9,
    CAST("intrght_96" AS BIGINT) AS intrght_96,
    CAST("intrght_98" AS BIGINT) AS intrght_98,
    "intrght_article",
    "intrght_comments",
    CAST("assem" AS BIGINT) AS assem,
    "assem_article",
    "assem_comments",
    CAST("assoc" AS BIGINT) AS assoc,
    "assoc_article",
    "assoc_comments",
    CAST("inalrght" AS BIGINT) AS inalrght,
    "inalrght_article",
    "inalrght_comments",
    CAST("devlpers" AS BIGINT) AS devlpers,
    "devlpers_article",
    "devlpers_comments",
    CAST("nomil" AS BIGINT) AS nomil,
    "nomil_article",
    "nomil_comments",
    CAST("asylum" AS BIGINT) AS asylum,
    "asylum_article",
    "asylum_comments",
    CAST("arms" AS BIGINT) AS arms,
    "arms_article",
    "arms_comments",
    CAST("env" AS BIGINT) AS env,
    "env_article",
    "env_comments",
    CAST("envref_1" AS BIGINT) AS envref_1,
    CAST("envref_2" AS BIGINT) AS envref_2,
    CAST("envref_3" AS BIGINT) AS envref_3,
    CAST("envref_4" AS BIGINT) AS envref_4,
    CAST("envref_90" AS BIGINT) AS envref_90,
    CAST("envref_96" AS BIGINT) AS envref_96,
    CAST("envref_98" AS BIGINT) AS envref_98,
    "envref_article",
    "envref_comments",
    CAST("envpart_1" AS BIGINT) AS envpart_1,
    CAST("envpart_2" AS BIGINT) AS envpart_2,
    CAST("envpart_3" AS BIGINT) AS envpart_3,
    CAST("envpart_4" AS BIGINT) AS envpart_4,
    CAST("envpart_5" AS BIGINT) AS envpart_5,
    CAST("envpart_6" AS BIGINT) AS envpart_6,
    CAST("envpart_7" AS BIGINT) AS envpart_7,
    CAST("envpart_8" AS BIGINT) AS envpart_8,
    CAST("envpart_9" AS BIGINT) AS envpart_9,
    CAST("envpart_10" AS BIGINT) AS envpart_10,
    CAST("envpart_11" AS BIGINT) AS envpart_11,
    CAST("envpart_12" AS BIGINT) AS envpart_12,
    CAST("envpart_13" AS BIGINT) AS envpart_13,
    CAST("envpart_90" AS BIGINT) AS envpart_90,
    CAST("envpart_96" AS BIGINT) AS envpart_96,
    CAST("envpart_98" AS BIGINT) AS envpart_98,
    "envpart_article",
    "envpart_comments",
    CAST("resrce" AS BIGINT) AS resrce,
    "resrce_article",
    "resrce_comments",
    CAST("resrces_1" AS BIGINT) AS resrces_1,
    CAST("resrces_2" AS BIGINT) AS resrces_2,
    CAST("resrces_3" AS BIGINT) AS resrces_3,
    CAST("resrces_4" AS BIGINT) AS resrces_4,
    CAST("resrces_5" AS BIGINT) AS resrces_5,
    CAST("resrces_6" AS BIGINT) AS resrces_6,
    CAST("resrces_7" AS BIGINT) AS resrces_7,
    CAST("resrces_8" AS BIGINT) AS resrces_8,
    CAST("resrces_9" AS BIGINT) AS resrces_9,
    CAST("resrces_10" AS BIGINT) AS resrces_10,
    CAST("resrces_90" AS BIGINT) AS resrces_90,
    CAST("resrces_96" AS BIGINT) AS resrces_96,
    CAST("resrces_98" AS BIGINT) AS resrces_98,
    "resrces_article",
    "resrces_comments",
    CAST("artists" AS BIGINT) AS artists,
    "artists_article",
    "artists_comments",
    CAST("artspec_1" AS BIGINT) AS artspec_1,
    CAST("artspec_2" AS BIGINT) AS artspec_2,
    CAST("artspec_3" AS BIGINT) AS artspec_3,
    CAST("artspec_90" AS BIGINT) AS artspec_90,
    CAST("artspec_96" AS BIGINT) AS artspec_96,
    CAST("artspec_98" AS BIGINT) AS artspec_98,
    "artspec_article",
    "artspec_comments",
    CAST("science" AS BIGINT) AS science,
    "science_article",
    "science_comments",
    CAST("telecom" AS BIGINT) AS telecom,
    "telecom_article",
    "telecom_comments",
    CAST("radio" AS BIGINT) AS radio,
    "radio_article",
    "radio_comments",
    CAST("tv" AS BIGINT) AS tv,
    "tv_article",
    "tv_comments",
    CAST("govmed" AS BIGINT) AS govmed,
    "govmed_article",
    "govmed_comments",
    CAST("medmark_1" AS BIGINT) AS medmark_1,
    CAST("medmark_2" AS BIGINT) AS medmark_2,
    CAST("medmark_3" AS BIGINT) AS medmark_3,
    CAST("medmark_4" AS BIGINT) AS medmark_4,
    CAST("medmark_5" AS BIGINT) AS medmark_5,
    CAST("medmark_6" AS BIGINT) AS medmark_6,
    CAST("medmark_7" AS BIGINT) AS medmark_7,
    CAST("medmark_90" AS BIGINT) AS medmark_90,
    CAST("medmark_96" AS BIGINT) AS medmark_96,
    CAST("medmark_98" AS BIGINT) AS medmark_98,
    "medmark_article",
    "medmark_comments",
    CAST("military" AS BIGINT) AS military,
    "military_article",
    "military_comments",
    CAST("comchief" AS BIGINT) AS comchief,
    "comchief_article",
    "comchief_comments",
    CAST("terror" AS BIGINT) AS terror,
    "terror_article",
    "terror_comments",
    CAST("econplan" AS BIGINT) AS econplan,
    "econplan_article",
    "econplan_comments",
    CAST("ethincl" AS BIGINT) AS ethincl,
    "ethincl_article",
    "ethincl_comments",
    CAST("opgroup" AS BIGINT) AS opgroup,
    "opgroup_article",
    "opgroup_comments",
    CAST("lang" AS BIGINT) AS lang,
    "lang_article",
    "lang_comments",
    "langoffw",
    "langoffw_article",
    "langoffw_comments",
    "langnatw",
    "langnatw_article",
    "langnatw_comments",
    CAST("langprot" AS BIGINT) AS langprot,
    "langprot_article",
    "langprot_comments",
    CAST("educate" AS BIGINT) AS educate,
    "educate_article",
    "educate_comments",
    CAST("edcomp" AS BIGINT) AS edcomp,
    "edcomp_article",
    "edcomp_comments",
    CAST("edcompl" AS BIGINT) AS edcompl,
    "edcompl_article",
    "edcompl_comments",
    CAST("edfree" AS BIGINT) AS edfree,
    "edfree_article",
    "edfree_comments",
    CAST("edfreel" AS BIGINT) AS edfreel,
    "edfreel_article",
    "edfreel_comments",
    CAST("acfree" AS BIGINT) AS acfree,
    "acfree_article",
    "acfree_comments",
    CAST("achighed" AS BIGINT) AS achighed,
    "achighed_article",
    "achighed_comments"
FROM "comparative-constitutions-project-ccp-cnc"
