"""Dataset-id selections for the insee connector.

These lists name which datasets/entities the connector pulls. They are data, not
logic, so they live here instead of being hardcoded in the node module(s).
"""


ENTITY_IDS = [
    "DD_CNA_AGREGATS", "DD_CNA_APU", "DD_CNA_BRANCHES", "DD_CNA_CONSO_MENAGES_COICOP",
    "DD_CNA_CONSO_MENAGES_PRODUITS", "DD_CNA_ECH_EXT", "DD_CNA_PATRIMOINE", "DD_CNA_PATRIMOINE_BRANCHES",
    "DD_CNA_REBS", "DD_CNA_SUT", "DD_CNA_TEE", "DD_EEC_ANNUEL",
    "DD_EEC_SERIES", "DS_ANTIPOL", "DS_BPE", "DS_BPE_EDUCATION",
    "DS_BPE_EVOLUTION", "DS_BPE_SPORT_CULTURE", "DS_BTS_SAL_EQTP_SEX_AGE", "DS_BTS_SAL_EQTP_SEX_PCS",
    "DS_CNT_CB", "DS_CNT_CSI", "DS_CNT_OPERATIONS", "DS_CNT_PIB_EQB_RF",
    "DS_COEFF_EURO_FRANC", "DS_COMPTES_REGIONAUX", "DS_DECES_MORTALITE_SERIES", "DS_DERA_PRIVE_ANNUEL",
    "DS_DERA_PRIVE_SERIES_LONGUES", "DS_DERA_PUBLIC_ANNUEL", "DS_DERA_PUBLIC_SERIES_LONGUES", "DS_EACEI",
    "DS_EC_DECES", "DS_EC_NAIS", "DS_ELECTORAL", "DS_ENQPAT_DET",
    "DS_ENQPAT_TRANSM", "DS_ERFS_NON_RETROPOLE", "DS_ERFS_RETROPOLE", "DS_ESTIMATION_POPULATION",
    "DS_ETAT_CIVIL_DECES_COMMUNES", "DS_ETAT_CIVIL_NAIS_COMMUNES", "DS_FILOSOFI_CC", "DS_FILOSOFI_SAGE_LOG_TP_NIVVIE",
    "DS_FLORES_A5", "DS_FLORES_A88", "DS_FLORES_ECONOMIC_SPHERE", "DS_FLORES_PE",
    "DS_ICA", "DS_IPCH", "DS_IPC_IND_CAT", "DS_IPC_PM",
    "DS_IPC_PRINC", "DS_MAR_PACS_DIV_SERIES", "DS_NAISSANCES_FECONDITE_SERIES", "DS_NAT_SDG",
    "DS_PARC_LOGEMENTS_SERIES", "DS_POPULATIONS_HISTORIQUES", "DS_POPULATIONS_REFERENCE", "DS_POP_STRUCT_SERIES",
    "DS_PRENOM", "DS_RP_ACTIVITE_PRINC", "DS_RP_DIPLOMES_PRINC", "DS_RP_EDUCATION",
    "DS_RP_EDUCATION_PRINC", "DS_RP_EMPLOI_LR_COMP", "DS_RP_EMPLOI_LR_PRINC", "DS_RP_EMPLOI_LT_COMP",
    "DS_RP_EMPLOI_LT_PRINC", "DS_RP_FAMILLE_COMP", "DS_RP_LOGEMENT_COMP", "DS_RP_LOGEMENT_COMPL",
    "DS_RP_LOGEMENT_DOM_PRINC", "DS_RP_LOGEMENT_PRINC", "DS_RP_MENAGES_COMP", "DS_RP_MENAGES_PRINC",
    "DS_RP_MIGRES_PRINC", "DS_RP_NAVETTES_PRINC", "DS_RP_POPULATION_COMP", "DS_RP_POPULATION_PRINC",
    "DS_RP_SERIE_HISTORIQUE", "DS_RP_TD_ACTIVITE_ACTIVITYEMPFORM_COMP", "DS_RP_TD_ACTIVITE_AGED_PRINC", "DS_RP_TD_ACTIVITE_AGEEMPFORMD_COMP",
    "DS_RP_TD_ACTIVITE_AGEQEMPFORMR_COMP", "DS_RP_TD_ACTIVITE_PCSACTIVITY_COMP", "DS_RP_TD_DIPLOMES_PRINC", "DS_RP_TD_EDUCATION_PRINC",
    "DS_RP_TD_EMPLOI_LT_AGEEMPFORM_COMP", "DS_RP_TD_EMPLOI_LT_EMPFORMACTIVITY_COMP", "DS_RP_TD_EMPLOI_LT_EMPFORMWKTIME_COMP", "DS_RP_TD_EMPLOI_LT_PCSACTIVITY_COMP",
    "DS_RP_TD_FAMILLE_AGEENF_COMP", "DS_RP_TD_FAMILLE_NBENF_COMP", "DS_RP_TD_IMMI_AGESEXEMPSTA_PRINC", "DS_RP_TD_IMMI_AGESEXPCS_COMP",
    "DS_RP_TD_IMMI_AGESEX_PAYSNAISS_D_PRINC", "DS_RP_TD_IMMI_AGESEX_PAYSNAISS_R_PRINC", "DS_RP_TD_IMMI_EMPSTASEX_PAYSNAISS_R_PRINC", "DS_RP_TD_IMMI_PCSSEX_PAYSNAISS_R_COMP",
    "DS_RP_TD_LOGEMENT_AGE_PRINC", "DS_RP_TD_LOGEMENT_PCS_COMP", "DS_RP_TD_MENAGES_EMPSTA_COMP", "DS_RP_TD_MENAGES_FST_COMP",
    "DS_RP_TD_MENAGES_NOC_COMP", "DS_RP_TD_MENAGES_PCS_COMP", "DS_RP_TD_MENAGES_TPH_COMP", "DS_RP_TD_MIGRES_COMP",
    "DS_RP_TD_MIGRES_PRINC", "DS_RP_TD_NAT_AGESEXEMPSTA_PRINC", "DS_RP_TD_NAT_AGESEXPCS_COMP", "DS_RP_TD_NAT_AGESEX_PRINC",
    "DS_RP_TD_NAVETTES_PCSACTIVITY_COMP", "DS_RP_TD_NAVETTES_SEXAGE_COMP", "DS_RP_TD_NAVETTES_SEXTRANSPORT_COMP", "DS_RP_TD_POPULATION_AGECOUPLECIVILSEX_PRINC",
    "DS_RP_TD_POPULATION_AGEHARSEX_PRINC", "DS_RP_TD_POPULATION_AGESEX_PRINC", "DS_RP_TD_POPULATION_PCSAGESEX_COMP", "DS_SIDE_CREA_DEP_REG_NAT",
    "DS_SIDE_CREA_EI", "DS_SIDE_CREA_ENT_COM", "DS_SIDE_CREA_ENT_DEP_REG_NAT_CJ", "DS_SIDE_CREA_ENT_SERIES",
    "DS_SIDE_CREA_ETAB_COM", "DS_SIDE_EQDEMO_A10", "DS_SIDE_EQDEMO_A21", "DS_SIDE_STOCKS_A21",
    "DS_SIDE_STOCKS_EI", "DS_SIDE_STOCKS_ET_COM", "DS_SIDE_STOCKS_UL_COM", "DS_SOCIAL_ECONOMY",
    "DS_SRCV_CONFIANCE", "DS_SRCV_PMS", "DS_SRCV_SATISFACTION", "DS_SUIVI_DDE_TOUR",
    "DS_TICE", "DS_TICM_EQUIPEMENT", "DS_TICM_PRATIQUES", "DS_TOUR_CAP",
    "DS_TOUR_FREQ",
]
