"""Dataset-id selections for the insee connector.

These lists name which datasets/entities the connector pulls. They are data, not
logic, so they live here instead of being hardcoded in the node module(s), and are
imported back as e.g. ``from constants import ENTITY_IDS``.

This file sits outside ``nodes/`` on purpose: ``load_nodes`` only scans ``nodes/``,
so it is never treated as a node module, and the runner puts ``src/`` on the path
so the import resolves at validation and at runtime.
"""


ENTITY_IDS = [
    "DD_CNA_AGREGATS", "DD_CNA_APU", "DD_CNA_BRANCHES", "DD_CNA_CONSO_MENAGES_COICOP",
    "DD_CNA_CONSO_MENAGES_PRODUITS", "DD_CNA_ECH_EXT", "DD_CNA_PATRIMOINE",
    "DD_CNA_PATRIMOINE_BRANCHES", "DD_CNA_REBS", "DD_CNA_SUT", "DD_CNA_TEE",
    "DD_EEC_ANNUEL", "DD_EEC_SERIES", "DS_BPE", "DS_BPE_EDUCATION", "DS_BPE_EVOLUTION",
    "DS_BPE_SPORT_CULTURE", "DS_BTS_SAL_EQTP_SEX_AGE", "DS_BTS_SAL_EQTP_SEX_PCS",
    "DS_CNT_CB", "DS_CNT_CSI", "DS_CNT_OPERATIONS", "DS_CNT_PIB_EQB_RF",
    "DS_COMPTES_REGIONAUX", "DS_DECES_MORTALITE_SERIES", "DS_DERA_PRIVE_ANNUEL",
    "DS_DERA_PRIVE_SERIES_LONGUES", "DS_DERA_PUBLIC_ANNUEL", "DS_DERA_PUBLIC_SERIES_LONGUES",
    "DS_EACEI", "DS_EC_DECES", "DS_EC_NAIS", "DS_ELECTORAL", "DS_ERFS_CHAMP_CONST_SL",
    "DS_ERFS_INDIVIDU", "DS_ERFS_INDIVIDU_SL", "DS_ERFS_MENAGE", "DS_ERFS_MENAGE_SL",
    "DS_ESTIMATION_POPULATION", "DS_ETAT_CIVIL_DECES_COMMUNES", "DS_ETAT_CIVIL_NAIS_COMMUNES",
    "DS_FILOSOFI_CC", "DS_FILOSOFI_SAGE_LOG_TP_NIVVIE", "DS_FLORES_A17", "DS_FLORES_A38",
    "DS_FLORES_A5", "DS_FLORES_A88", "DS_FLORES_ECONOMIC_SPHERE", "DS_FLORES_PE", "DS_ICA",
    "DS_IPCH", "DS_IPC_IND_CAT", "DS_IPC_PM", "DS_IPC_PRINC", "DS_MAR_PACS_DIV_SERIES",
    "DS_NAISSANCES_FECONDITE_SERIES", "DS_NAT_SDG", "DS_POPULATIONS_HISTORIQUES",
    "DS_POPULATIONS_REFERENCE", "DS_POP_STRUCT_SERIES", "DS_PRENOM", "DS_RP_ACTIVITE_PRINC",
    "DS_RP_DIPLOMES_PRINC", "DS_RP_EDUCATION", "DS_RP_EMPLOI_LR_COMP", "DS_RP_EMPLOI_LR_PRINC",
    "DS_RP_EMPLOI_LT_COMP", "DS_RP_EMPLOI_LT_PRINC", "DS_RP_FAMILLE_COMP", "DS_RP_LOGEMENT_COMPL",
    "DS_RP_LOGEMENT_DOM_PRINC", "DS_RP_LOGEMENT_PRINC", "DS_RP_MENAGES_COMP", "DS_RP_MENAGES_PRINC",
    "DS_RP_MIGRES_PRINC", "DS_RP_NAVETTES_PRINC", "DS_RP_POPULATION_COMP", "DS_RP_POPULATION_PRINC",
    "DS_RP_SERIE_HISTORIQUE", "DS_SIDE_CREA_DEP_REG_NAT", "DS_SIDE_CREA_EI", "DS_SIDE_CREA_ENT_COM",
    "DS_SIDE_CREA_ENT_DEP_REG_NAT_CJ", "DS_SIDE_CREA_ENT_SERIES", "DS_SIDE_CREA_ETAB_COM",
    "DS_SIDE_EQDEMO_A10", "DS_SIDE_EQDEMO_A21", "DS_SIDE_STOCKS_A21", "DS_SIDE_STOCKS_EI",
    "DS_SIDE_STOCKS_ET_COM", "DS_SIDE_STOCKS_UL_COM", "DS_SRCV_PMS", "DS_SRCV_SATISFACTION",
    "DS_TICE", "DS_TICM_EQUIPEMENT", "DS_TICM_PRATIQUES", "DS_TOUR_CAP", "DS_TOUR_FREQ",
]
