-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: This table unions country-level, region-level, and questionnaire metadata extracts; many identifier columns are only populated for one extract type.
-- caution: Filter to one _source_file before interpreting country, region, gender, variable, or response-category fields.
SELECT
    "Year" AS year,
    "Region" AS region,
    "Country" AS country,
    "Internet_Penetration" AS internet_penetration,
    "Gender" AS gender,
    "a1_agree",
    "a1_neutral",
    "a1_disagree",
    "a2_opps_other",
    "a3_yes",
    "a3_no",
    "a4",
    "a5_r",
    "a6_r_city",
    "a6_r_noncity",
    "b1_hours_work",
    "b2_self",
    "b3_dependent",
    "b3_fullyindependent",
    "b4_agree",
    "b4_neutral",
    "b4_disagree",
    "b5_man_other",
    "b6_wage",
    "b6_non_wage",
    "b7_full",
    "b7_limited",
    "b8",
    "b9",
    "b10_yes",
    "b10_no",
    "c1_care",
    "c1a_all",
    "c1a_occasionally",
    "c1b_spouse",
    "c1b_nonspouse",
    "c1c_hours_care",
    "c1d_increase",
    "c1d_same",
    "c1d_decrease",
    "c2_animals",
    "c2_business",
    "c2_clean",
    "c2_cook",
    "c2_farm",
    "c2_hhmanage",
    "c2_none",
    "c2_other",
    "c2_shop",
    "c2_water_fuel",
    "c2a_no",
    "c2a_yes",
    "c2b_spouse",
    "c2c_hours_chores",
    "c2d_increase",
    "c2d_same",
    "c2d_decrease",
    "c3_agree",
    "c3_neutral",
    "c3_disagree",
    "c4_housewife_other",
    "d0",
    "d1",
    "d4_computer",
    "d4_home",
    "d4_land",
    "d4_none",
    "d4_phone",
    "d4_vehicle",
    "d5_agree",
    "d5_neutral",
    "d5_disagree",
    "d6_health",
    "d6_isolate",
    "d6_job",
    "d6_medical",
    "d6_migrate",
    "d6_none",
    "d6_other",
    "d6_personal",
    "d6_school",
    "d6_transport",
    "d6_wait",
    "d7_bored",
    "d7_food",
    "d7_health",
    "d7_info",
    "d7_loan",
    "d7_money",
    "d7_none",
    "d7_stuck",
    "d7_work",
    "_source_file" AS source_file,
    "Variable" AS variable,
    "Variable Label" AS variable_label,
    "Response Category" AS response_category,
    "Notes" AS notes,
    "Important information about this dataset" AS important_information_about_this_dataset
FROM "meta-survey-on-gender-equality-at-home"
