-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Rows are unioned from many spending-moratoria CSV resources with schema drift; similar approval, amount, grade, and activity fields can be split across year-specific columns.
-- caution: Use `resource_name` and `resource_last_modified` to identify the source period or file before aggregating.
SELECT
    "resource_name",
    "resource_id",
    "resource_last_modified",
    "source_url",
    "row_index",
    CAST("aa_ao" AS BIGINT) AS aa_ao,
    "activity",
    "activity_type",
    "alb",
    "amount",
    "approval",
    "approval_date",
    "approval_month",
    "approved",
    "arms_length_body",
    "basis_for",
    "basis_for_exception",
    "basis_for_expenditure",
    "basis_for_expenditure_approval",
    "case_description",
    "case_name",
    "civil_service_grade_fte",
    "civil_service_grade_full_time_equivalent",
    "civil_service_grade_headcount",
    "col_0",
    "col_10",
    "col_11",
    "col_12",
    "col_13",
    "col_14",
    "col_15",
    "col_16",
    "col_17",
    "col_18",
    "col_19",
    "col_20",
    "col_21",
    "col_29",
    "col_30",
    "col_31",
    "col_32",
    "col_33",
    "col_34",
    "col_6",
    "col_7",
    "col_8",
    "col_9",
    "control",
    "control_type",
    "controls_entry_stage",
    "date",
    "date_of",
    "date_of_approval",
    "date_of_update",
    "decision",
    "decision_sent_to_department",
    "department",
    "department_organisation_name",
    "departmernt",
    "dept",
    "description",
    "description_notes_for_minister",
    "eo",
    CAST("grade_6_7" AS BIGINT) AS grade_6_7,
    CAST("grade_fte" AS BIGINT) AS grade_fte,
    CAST("grade_fte_1" AS BIGINT) AS grade_fte_1,
    CAST("grade_fte_2" AS BIGINT) AS grade_fte_2,
    CAST("grade_fte_3" AS BIGINT) AS grade_fte_3,
    CAST("grade_headcount_aa_ao" AS BIGINT) AS grade_headcount_aa_ao,
    CAST("grade_headcount_eo" AS BIGINT) AS grade_headcount_eo,
    CAST("grade_headcount_grade6_7" AS BIGINT) AS grade_headcount_grade6_7,
    CAST("grade_headcount_heo_seo" AS BIGINT) AS grade_headcount_heo_seo,
    "heo_seo",
    "hmg_ref",
    "hmg_ref_no",
    "hmg_ref_number",
    "lead_control",
    "minister_sub_date",
    "moratorium",
    "organisation",
    "organisation_name",
    CAST("other" AS BIGINT) AS other,
    "owning_dept_alb_department",
    "project_name",
    "project_name_activity",
    "property",
    "property_department",
    "property_name",
    "reference_number",
    "requested_value",
    "requirement_description",
    CAST("scs_level" AS BIGINT) AS scs_level,
    CAST("scs_level_fte" AS BIGINT) AS scs_level_fte,
    CAST("scs_level_headcount_scs_level" AS BIGINT) AS scs_level_headcount_scs_level,
    "site",
    "status_decision_result",
    "title",
    "tool_ref",
    "total",
    "total_1",
    CAST("total_approvals_fte" AS BIGINT) AS total_approvals_fte,
    "total_approvals_full_time_equivalent",
    "total_approvals_headcount",
    CAST("total_exemptions_headcount" AS BIGINT) AS total_exemptions_headcount,
    "total_value",
    "total_value_1",
    "total_value_apporved",
    "total_value_approved",
    CAST("total_value_approved_0" AS BIGINT) AS total_value_approved_0,
    "total_value_approved_m",
    "total_value_approved_revised_value",
    "total_value_requested",
    "total_value_requested_m",
    CAST("unknown_other" AS BIGINT) AS unknown_other,
    CAST("unknown_other_headcount" AS BIGINT) AS unknown_other_headcount,
    "value",
    "value_approved",
    "value_excluding_vat",
    "value_requested"
FROM "uk-dwp-exceptions-to-government-moratoria-department-work-and-pensions"
