-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: This table combines different ministerial disclosure types such as meetings, gifts, hospitality, and travel; filter to the applicable populated columns before counting events.
-- caution: Rows are unioned from many CSV resources whose headers changed over time, so equivalent names and dates can appear in multiple columns.
SELECT
    "resource_name",
    "resource_id",
    "resource_last_modified",
    "source_url",
    "row_index",
    "accompanied_by_guest",
    "accompanied_by_spouse_family_member_s_or_friend",
    "accompanied_by_spouse_family_member_s_or_friend_at_public_expense",
    "accompanied_by_spouse_partner_at_public_expense",
    "col_5",
    "cost_of_private_jet_or_raf_plane_hire_if_relevant",
    "date",
    "date_gift_given",
    "date_of_hospitality",
    "date_of_meeting",
    "date_s_of_trip",
    "destination",
    "end_date",
    "end_date_of_trip",
    "gift",
    "given_or_received",
    "individual_or_organisation_that_offered_hospitality",
    "minister",
    "mode_of_transport",
    "mode_of_transport_no_32_the_royal_squadron_or_other_raf_or_charter_or_eurostar",
    "mode_s_of_transport",
    "name",
    "name_of_external_organisation",
    "name_of_individual_or_organisation",
    "name_of_organisation",
    "name_of_organisation_or_individual",
    "name_of_organisation_or_individual_if_a_media_proprietor_senior_exec_or_editor",
    "nmae",
    "no_32_the_royal_squadron_or_other_raf_or_charter_or_eurostar",
    "number_of_officials_accompanying_minister_where_non_scheduled_travel_is_used",
    "number_of_officials_accompanying_ministers_where_non_scheduled_travel_is_used",
    "number_of_officials_who_accompanied_minister_if_non_scheduled_travel_was_used",
    "number_of_officials_who_accompanied_minister_if_non_shceduled_travel_was_used",
    "number_of_officials_who_accompanied_the_minister_if_non_scheduled_flight_was_taken",
    "outcome_received_gifts_only",
    "pdf_1_6",
    "person_or_organisation_that_offered_hospitality",
    "purpose_of_meeting",
    "purpose_of_trip",
    "start_date",
    "start_date_of_trip",
    "subtotal_of_all_travel_costs_including_any_non_scheduled_raf_flights",
    "subtotal_of_associated_costs_for_minister_only_including_all_visas_accommodation_meals_etc",
    "to",
    "total_cost",
    "total_cost_for_minister_only_including_all_visas_accommodation_travel_meals_etc",
    "total_cost_including_travel_and_accommodation_of_minister_only",
    "type_of_hospitality_received",
    "value",
    "who_gift_was_given_to_or_received_from"
FROM "uk-dwp-ministerial-data-dwp"
