-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No stable row identifier was verified for this upstream table; treat rows as source observations and avoid assuming uniqueness without applying source-specific dimensions.
SELECT
    "source_member",
    CAST("KRAJ" AS BIGINT) AS kraj,
    CAST("OKRES" AS BIGINT) AS okres,
    CAST("CPOU" AS BIGINT) AS cpou,
    CAST("ORP" AS BIGINT) AS orp,
    CAST("OBEC" AS BIGINT) AS obec,
    "NAZEVOBCE" AS nazevobce,
    CAST("OBVOD" AS BIGINT) AS obvod,
    CAST("MINOKRSEK1" AS BIGINT) AS minokrsek1,
    CAST("MAXOKRSEK1" AS BIGINT) AS maxokrsek1,
    CAST("MINOKRSEK2" AS BIGINT) AS minokrsek2,
    CAST("MAXOKRSEK2" AS BIGINT) AS maxokrsek2,
    CAST("MINOKRSEK3" AS BIGINT) AS minokrsek3,
    CAST("MAXOKRSEK3" AS BIGINT) AS maxokrsek3,
    CAST("MINOKRSEK4" AS BIGINT) AS minokrsek4,
    CAST("MAXOKRSEK4" AS BIGINT) AS maxokrsek4,
    CAST("MINOKRSEK5" AS BIGINT) AS minokrsek5,
    CAST("MAXOKRSEK5" AS BIGINT) AS maxokrsek5,
    CAST("MINOKRSEK6" AS BIGINT) AS minokrsek6,
    CAST("MAXOKRSEK6" AS BIGINT) AS maxokrsek6,
    CAST("MINOKRSEK7" AS BIGINT) AS minokrsek7,
    CAST("MAXOKRSEK7" AS BIGINT) AS maxokrsek7,
    CAST("MINOKRSEK8" AS BIGINT) AS minokrsek8,
    CAST("MAXOKRSEK8" AS BIGINT) AS maxokrsek8,
    CAST("MINOKRSEK9" AS BIGINT) AS minokrsek9,
    CAST("MAXOKRSEK9" AS BIGINT) AS maxokrsek9,
    CAST("MINOKRSE10" AS BIGINT) AS minokrse10,
    CAST("MAXOKRSE10" AS BIGINT) AS maxokrse10,
    CAST("OBEC_PREZ" AS BIGINT) AS obec_prez,
    "NAZEV_OBV" AS nazev_obv,
    CAST("PRVNI_VO" AS BIGINT) AS prvni_vo,
    "PLATNOST" AS platnost,
    CAST("VSTRANA" AS BIGINT) AS vstrana,
    "NAZEVCELK" AS nazevcelk,
    "NAZEV_STRV" AS nazev_strv,
    "ZKRATKAV30" AS zkratkav30,
    "ZKRATKAV8" AS zkratkav8,
    CAST("POCSTR_SLO" AS BIGINT) AS pocstr_slo,
    "SLOZENI" AS slozeni,
    "ZKRATKA_OF" AS zkratka_of,
    "TYPVS" AS typvs,
    "PLNYNAZEV" AS plnynazev,
    CAST("NSTRANA" AS BIGINT) AS nstrana,
    "NAZEV_STRN" AS nazev_strn,
    "ZKRATKAN30" AS zkratkan30,
    "ZKRATKAN8" AS zkratkan8,
    CAST("PSTRANA" AS BIGINT) AS pstrana,
    "NAZEV_STRP" AS nazev_strp,
    "ZKRATKAP30" AS zkratkap30,
    "ZKRATKAP8" AS zkratkap8,
    CAST("NUMNUTS" AS BIGINT) AS numnuts,
    "NUTS" AS nuts,
    "NAZEVNUTS" AS nazevnuts,
    CAST("KODCIS" AS BIGINT) AS kodcis,
    CAST("CHODNOTA" AS BIGINT) AS chodnota
FROM "czech-statistical-office-se2018cis"
