-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_resource",
    "source_file",
    "TABLE_ID" AS table_id,
    "CODIGO" AS codigo,
    "ESCUELA" AS escuela,
    "REGION" AS region,
    "DISTRITO" AS distrito,
    "MUNICIPIO_ESCOLAR" AS municipio_escolar,
    "DIRECCION_FISICA" AS direccion_fisica,
    "DIRECCION_MUNICIPIO" AS direccion_municipio,
    "DIRECCION_ESTADO" AS direccion_estado,
    "DIRECCION_ZIPCODE" AS direccion_zipcode,
    "GEOLOCALIZACION" AS geolocalizacion,
    "TELEFONO" AS telefono,
    "FAX" AS fax,
    "DIRECTOR" AS director,
    "ZONA" AS zona,
    "OPERACIONAL_2018-2019" AS operacional_2018_2019,
    "NIVEL_ORIGINAL" AS nivel_original,
    "GRADOS_ORIGINAL" AS grados_original,
    "GRADOS_POSTERIOR" AS grados_posterior,
    "MATRICULA_TOTAL" AS matricula_total,
    CAST("GRADO_INFANT" AS BIGINT) AS grado_infant,
    CAST("GRADO_TODDLER" AS BIGINT) AS grado_toddler,
    CAST("GRADO_PK" AS BIGINT) AS grado_pk,
    CAST("GRADO_PKE" AS BIGINT) AS grado_pke,
    CAST("GRADO_PKM" AS BIGINT) AS grado_pkm,
    CAST("GRADO_K" AS BIGINT) AS grado_k,
    CAST("GRADO_1" AS BIGINT) AS grado_1,
    CAST("GRADO_2" AS BIGINT) AS grado_2,
    CAST("GRADO_3" AS BIGINT) AS grado_3,
    CAST("GRADO_4" AS BIGINT) AS grado_4,
    CAST("GRADO_5" AS BIGINT) AS grado_5,
    CAST("GRADO_6" AS BIGINT) AS grado_6,
    CAST("GRADO_SGE" AS BIGINT) AS grado_sge,
    CAST("GRADO_7" AS BIGINT) AS grado_7,
    CAST("GRADO_8" AS BIGINT) AS grado_8,
    CAST("GRADO_9" AS BIGINT) AS grado_9,
    CAST("GRADO_SGI" AS BIGINT) AS grado_sgi,
    CAST("GRADO_10" AS BIGINT) AS grado_10,
    CAST("GRADO_11" AS BIGINT) AS grado_11,
    CAST("GRADO_12" AS BIGINT) AS grado_12,
    CAST("GRADO_SGS" AS BIGINT) AS grado_sgs,
    "ESPAÑOL_[PROFICIENTE+AVANZADO]" AS espa_ol_proficiente_avanzado,
    "ESPAÑOL_PRE-BÁSICO" AS espa_ol_pre_b_sico,
    "ESPAÑOL_BÁSICO" AS espa_ol_b_sico,
    "ESPAÑOL_PROFICIENTE" AS espa_ol_proficiente,
    "ESPAÑOL_AVANZADO" AS espa_ol_avanzado,
    "MATEMÁTICAS_[PROFICIENTE+AVANZADO]" AS matem_ticas_proficiente_avanzado,
    "MATEMÁTICAS_PRE-BÁSICO" AS matem_ticas_pre_b_sico,
    "MATEMÁTICAS_BÁSICO" AS matem_ticas_b_sico,
    "MATEMÁTICAS_PROFICIENTE" AS matem_ticas_proficiente,
    "MATEMÁTICAS_AVANZADO" AS matem_ticas_avanzado,
    "INGLÉS_[PROFICIENTE+AVANZADO]" AS ingl_s_proficiente_avanzado,
    "INGLÉS_PRE-BÁSICO" AS ingl_s_pre_b_sico,
    "INGLÉS_BÁSICO" AS ingl_s_b_sico,
    "INGLÉS_PROFICIENTE" AS ingl_s_proficiente,
    "INGLÉS_AVANZADO" AS ingl_s_avanzado,
    "BAJO_NIVEL_POBREZA" AS bajo_nivel_pobreza
FROM "instituto-de-estad-sticas-de-puerto-rico-directorio-comprensivo-de-escuelas-publicas-puerto-rico-2018"
