-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_resource",
    "source_file",
    "name",
    "description",
    "coordinates",
    "Serial_Num" AS serial_num,
    CAST("Season" AS BIGINT) AS season,
    CAST("Num" AS BIGINT) AS num,
    "Basin" AS basin,
    "Sub_basin" AS sub_basin,
    CAST("ISO_time" AS TIMESTAMP) AS iso_time,
    "Nature" AS nature,
    CAST("wmo_wind" AS DOUBLE) AS wmo_wind,
    CAST("wmo_pres" AS DOUBLE) AS wmo_pres,
    "Center" AS center,
    CAST("wmo_wind_%" AS DOUBLE) AS wmo_wind_2,
    CAST("wmo_pres_%" AS DOUBLE) AS wmo_pres_2,
    "Track_type" AS track_type,
    "basin_1",
    "HDA_grade" AS hda_grade,
    CAST("HDA_wind" AS DOUBLE) AS hda_wind,
    CAST("HDA_pres" AS DOUBLE) AS hda_pres,
    "TD9_grade" AS td9_grade,
    CAST("TD9_wind" AS DOUBLE) AS td9_wind,
    CAST("TD9_pres" AS DOUBLE) AS td9_pres,
    "REU_grade" AS reu_grade,
    CAST("REU_wind" AS DOUBLE) AS reu_wind,
    CAST("REU_pres" AS DOUBLE) AS reu_pres,
    "ATC_grade" AS atc_grade,
    CAST("ATC_wind" AS DOUBLE) AS atc_wind,
    CAST("ATC_pres" AS DOUBLE) AS atc_pres,
    "MLC_grade" AS mlc_grade,
    CAST("MLC_wind" AS DOUBLE) AS mlc_wind,
    CAST("MLC_pres" AS DOUBLE) AS mlc_pres,
    "DSS_grade" AS dss_grade,
    CAST("DSS_wind" AS DOUBLE) AS dss_wind,
    CAST("DSS_pres" AS DOUBLE) AS dss_pres,
    "DSI_grade" AS dsi_grade,
    CAST("DSI_wind" AS DOUBLE) AS dsi_wind,
    CAST("DSI_pres" AS DOUBLE) AS dsi_pres,
    "BOM_grade" AS bom_grade,
    CAST("BOM_wind" AS DOUBLE) AS bom_wind,
    CAST("BOM_pres" AS DOUBLE) AS bom_pres,
    "DSA_grade" AS dsa_grade,
    CAST("DSA_wind" AS DOUBLE) AS dsa_wind,
    CAST("DSA_pres" AS DOUBLE) AS dsa_pres,
    "JTS_grade" AS jts_grade,
    CAST("JTS_wind" AS DOUBLE) AS jts_wind,
    CAST("JTS_pres" AS DOUBLE) AS jts_pres,
    "JTW_grade" AS jtw_grade,
    CAST("JTW_wind" AS DOUBLE) AS jtw_wind,
    CAST("JTW_pres" AS DOUBLE) AS jtw_pres,
    "TD5_grade" AS td5_grade,
    CAST("TD5_wind" AS DOUBLE) AS td5_wind,
    CAST("TD5_pres" AS DOUBLE) AS td5_pres,
    "DSW_grade" AS dsw_grade,
    CAST("DSW_wind" AS DOUBLE) AS dsw_wind,
    CAST("DSW_pres" AS DOUBLE) AS dsw_pres,
    "JTI_grade" AS jti_grade,
    CAST("JTI_wind" AS DOUBLE) AS jti_wind,
    CAST("JTI_pres" AS DOUBLE) AS jti_pres,
    "CMA_grade" AS cma_grade,
    CAST("CMA_wind" AS DOUBLE) AS cma_wind,
    CAST("CMA_pres" AS DOUBLE) AS cma_pres,
    "HDE_grade" AS hde_grade,
    CAST("HDE_wind" AS DOUBLE) AS hde_wind,
    CAST("HDE_pres" AS DOUBLE) AS hde_pres,
    "JTE_grade" AS jte_grade,
    CAST("JTE_wind" AS DOUBLE) AS jte_wind,
    CAST("JTE_pres" AS DOUBLE) AS jte_pres,
    "DSE_grade" AS dse_grade,
    CAST("DSE_wind" AS DOUBLE) AS dse_wind,
    CAST("DSE_pres" AS DOUBLE) AS dse_pres,
    "JTC_grade" AS jtc_grade,
    CAST("JTC_wind" AS DOUBLE) AS jtc_wind,
    CAST("JTC_pres" AS DOUBLE) AS jtc_pres,
    "JMA_grade" AS jma_grade,
    CAST("JMA_wind" AS DOUBLE) AS jma_wind,
    CAST("JMA_pres" AS DOUBLE) AS jma_pres,
    "NEU_grade" AS neu_grade,
    CAST("NEU_wind" AS DOUBLE) AS neu_wind,
    CAST("NEU_pres" AS DOUBLE) AS neu_pres,
    "HKO_grade" AS hko_grade,
    CAST("HKO_wind" AS DOUBLE) AS hko_wind,
    CAST("HKO_pres" AS DOUBLE) AS hko_pres,
    "CPH_grade" AS cph_grade,
    CAST("CPH_wind" AS DOUBLE) AS cph_wind,
    CAST("CPH_pres" AS DOUBLE) AS cph_pres,
    "NZ_grade" AS nz_grade,
    CAST("NZ_wind" AS DOUBLE) AS nz_wind,
    CAST("NZ_pres" AS DOUBLE) AS nz_pres,
    "IMD_grade" AS imd_grade,
    CAST("IMD_wind" AS DOUBLE) AS imd_wind,
    CAST("IMD_pres" AS DOUBLE) AS imd_pres,
    "NAD_grade" AS nad_grade,
    CAST("NAD_wind" AS DOUBLE) AS nad_wind,
    CAST("NAD_pres" AS DOUBLE) AS nad_pres,
    CAST("REU_rmw" AS BIGINT) AS reu_rmw,
    CAST("REU_wr1_ne" AS BIGINT) AS reu_wr1_ne,
    CAST("REU_wr1_se" AS BIGINT) AS reu_wr1_se,
    CAST("REU_wr1_sw" AS BIGINT) AS reu_wr1_sw,
    CAST("REU_wr1_nw" AS BIGINT) AS reu_wr1_nw,
    CAST("REU_wr2_ne" AS BIGINT) AS reu_wr2_ne,
    CAST("REU_wr2_se" AS BIGINT) AS reu_wr2_se,
    CAST("REU_wr2_sw" AS BIGINT) AS reu_wr2_sw,
    CAST("REU_wr2_nw" AS BIGINT) AS reu_wr2_nw,
    CAST("BOM_hurrad" AS BIGINT) AS bom_hurrad,
    CAST("BOM_galrad" AS BIGINT) AS bom_galrad,
    CAST("BOM_eye" AS BIGINT) AS bom_eye,
    CAST("BOM_roci" AS BIGINT) AS bom_roci,
    CAST("ATC_rmw" AS BIGINT) AS atc_rmw,
    CAST("ATC_poci" AS BIGINT) AS atc_poci,
    CAST("ATC_roci" AS BIGINT) AS atc_roci,
    CAST("ATC_eye" AS BIGINT) AS atc_eye,
    CAST("ATC_w34_r1" AS BIGINT) AS atc_w34_r1,
    CAST("ATC_w34_r2" AS BIGINT) AS atc_w34_r2,
    CAST("ATC_w34_r3" AS BIGINT) AS atc_w34_r3,
    CAST("ATC_w34_r4" AS BIGINT) AS atc_w34_r4,
    CAST("ATC_w50_r1" AS BIGINT) AS atc_w50_r1,
    CAST("ATC_w50_r2" AS BIGINT) AS atc_w50_r2,
    CAST("ATC_w50_r3" AS BIGINT) AS atc_w50_r3,
    CAST("ATC_w50_r4" AS BIGINT) AS atc_w50_r4,
    CAST("ATC_w64_r1" AS BIGINT) AS atc_w64_r1,
    CAST("ATC_w64_r2" AS BIGINT) AS atc_w64_r2,
    CAST("ATC_w64_r3" AS BIGINT) AS atc_w64_r3,
    CAST("ATC_w64_r4" AS BIGINT) AS atc_w64_r4,
    CAST("JMA_dir50" AS BIGINT) AS jma_dir50,
    CAST("JMA_long50" AS BIGINT) AS jma_long50,
    CAST("JMA_shrt50" AS BIGINT) AS jma_shrt50,
    CAST("JMA_dir30" AS BIGINT) AS jma_dir30,
    CAST("JMA_long30" AS BIGINT) AS jma_long30,
    CAST("JMA_shrt30" AS BIGINT) AS jma_shrt30,
    CAST("JTX_rmw" AS BIGINT) AS jtx_rmw,
    CAST("JTX_poci" AS BIGINT) AS jtx_poci,
    CAST("JTX_roci" AS BIGINT) AS jtx_roci,
    CAST("JTX_eye" AS BIGINT) AS jtx_eye,
    CAST("JTX_w34_r1" AS BIGINT) AS jtx_w34_r1,
    CAST("JTX_w34_r2" AS BIGINT) AS jtx_w34_r2,
    CAST("JTX_w34_r3" AS BIGINT) AS jtx_w34_r3,
    CAST("JTX_w34_r4" AS BIGINT) AS jtx_w34_r4,
    CAST("JTX_w50_r1" AS BIGINT) AS jtx_w50_r1,
    CAST("JTX_w50_r2" AS BIGINT) AS jtx_w50_r2,
    CAST("JTX_w50_r3" AS BIGINT) AS jtx_w50_r3,
    CAST("JTX_w50_r4" AS BIGINT) AS jtx_w50_r4,
    CAST("JTX_w64_r1" AS BIGINT) AS jtx_w64_r1,
    CAST("JTX_w64_r2" AS BIGINT) AS jtx_w64_r2,
    CAST("JTX_w64_r3" AS BIGINT) AS jtx_w64_r3,
    CAST("JTX_w64_r4" AS BIGINT) AS jtx_w64_r4,
    CAST("year" AS BIGINT) AS year,
    CAST("month" AS BIGINT) AS month,
    CAST("day" AS BIGINT) AS day,
    CAST("hour" AS BIGINT) AS hour,
    CAST("min" AS BIGINT) AS min,
    CAST("value" AS DOUBLE) AS value
FROM "instituto-de-estad-sticas-de-puerto-rico-huracanes"
