-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_resource",
    "source_file",
    CAST("DATAYEAR" AS BIGINT) AS datayear,
    CAST("TABFLAG" AS BIGINT) AS tabflag,
    CAST("RECTYPE" AS BIGINT) AS rectype,
    CAST("RESTATUS" AS BIGINT) AS restatus,
    CAST("PLDEL" AS BIGINT) AS pldel,
    CAST("PLDEL2" AS BIGINT) AS pldel2,
    CAST("FATTND" AS BIGINT) AS fattnd,
    CAST("FATTNDR" AS BIGINT) AS fattndr,
    CAST("REGNOCC" AS BIGINT) AS regnocc,
    CAST("DIVOCC" AS BIGINT) AS divocc,
    CAST("STSUBOCC" AS BIGINT) AS stsubocc,
    CAST("STFETEXP" AS BIGINT) AS stfetexp,
    CAST("STATEFET" AS BIGINT) AS statefet,
    "CNTYFET" AS cntyfet,
    CAST("STOCCFIP" AS BIGINT) AS stoccfip,
    "CNTOCFIP" AS cntocfip,
    CAST("CNTOCPOP" AS BIGINT) AS cntocpop,
    CAST("REGNRES" AS BIGINT) AS regnres,
    CAST("DIVRES" AS BIGINT) AS divres,
    CAST("STSUBRES" AS BIGINT) AS stsubres,
    "STRESEXP" AS stresexp,
    "STATERES" AS stateres,
    "CNTYRES" AS cntyres,
    "CITYRES" AS cityres,
    "CITRSPOP" AS citrspop,
    "METRORES" AS metrores,
    "STRESFIP" AS stresfip,
    "CNTYRFIP" AS cntyrfip,
    "PLACEFIP" AS placefip,
    "CMSA" AS cmsa,
    "SMSARFIP" AS smsarfip,
    "CNTRSPOP" AS cntrspop,
    "R1" AS r1,
    CAST("MAGERFLG" AS BIGINT) AS magerflg,
    CAST("MAGEIMP" AS BIGINT) AS mageimp,
    CAST("DMAGE" AS BIGINT) AS dmage,
    "MAGE12" AS mage12,
    CAST("MAGE8" AS BIGINT) AS mage8,
    CAST("ORMOTH" AS BIGINT) AS ormoth,
    CAST("ORRACEM" AS BIGINT) AS orracem,
    "MRACEIMP" AS mraceimp,
    CAST("MRACE" AS BIGINT) AS mrace,
    CAST("MRACE3" AS BIGINT) AS mrace3,
    "DMEDUC" AS dmeduc,
    CAST("MEDUC6" AS BIGINT) AS meduc6,
    "DMARIMP" AS dmarimp,
    CAST("DMAR" AS BIGINT) AS dmar,
    CAST("DMAGERPT" AS BIGINT) AS dmagerpt,
    "R2" AS r2,
    "NLBNL" AS nlbnl,
    "NLBND" AS nlbnd,
    "NOTERM" AS noterm,
    "LBOIMPF" AS lboimpf,
    "DLIVORD" AS dlivord,
    CAST("LIVORD9" AS BIGINT) AS livord9,
    "TBOIMP" AS tboimp,
    "DTOTORD" AS dtotord,
    CAST("TOTORD9" AS BIGINT) AS totord9,
    "R3" AS r3,
    "MONPRE" AS monpre,
    CAST("MPRE6" AS BIGINT) AS mpre6,
    CAST("MPRE5" AS BIGINT) AS mpre5,
    "NPREVIST" AS nprevist,
    "NPREV12" AS nprev12,
    "LMPMON" AS lmpmon,
    "LMPDAY" AS lmpday,
    CAST("LMPYR" AS BIGINT) AS lmpyr,
    "LLBMON" AS llbmon,
    CAST("LLBYR" AS BIGINT) AS llbyr,
    "DISLLB" AS disllb,
    "ISLLB1O" AS isllb1o,
    "R4" AS r4,
    "FDOBIMP" AS fdobimp,
    "R5" AS r5,
    CAST("FAGERFLG" AS BIGINT) AS fagerflg,
    CAST("DFAGE" AS BIGINT) AS dfage,
    "FAGE11" AS fage11,
    CAST("ORFATH" AS BIGINT) AS orfath,
    CAST("ORRACEF" AS BIGINT) AS orracef,
    CAST("FRACE" AS BIGINT) AS frace,
    CAST("FRACE4" AS BIGINT) AS frace4,
    "DFEDUC" AS dfeduc,
    CAST("FEDUC6" AS BIGINT) AS feduc6,
    CAST("DFAGERPT" AS BIGINT) AS dfagerpt,
    "R6" AS r6,
    "FDODMIMP" AS fdodmimp,
    "R7" AS r7,
    "DELMON" AS delmon,
    "R8" AS r8,
    CAST("DELYR" AS BIGINT) AS delyr,
    CAST("WEEKDAY" AS BIGINT) AS weekday,
    CAST("GESTESTM" AS BIGINT) AS gestestm,
    CAST("GESTIMP" AS BIGINT) AS gestimp,
    CAST("DGESTAT" AS BIGINT) AS dgestat,
    "GESTAT12" AS gestat12,
    CAST("GESTAT5" AS BIGINT) AS gestat5,
    CAST("FSEXIMP" AS BIGINT) AS fseximp,
    CAST("FSEX" AS BIGINT) AS fsex,
    "R9" AS r9,
    "DBIRWT" AS dbirwt,
    "BIRWT14" AS birwt14,
    CAST("BIRWT4" AS BIGINT) AS birwt4,
    CAST("PLURIMP" AS BIGINT) AS plurimp,
    CAST("DPLURAL" AS BIGINT) AS dplural,
    CAST("CLINGEST" AS BIGINT) AS clingest,
    "R10" AS r10,
    CAST("VAGINAL" AS BIGINT) AS vaginal,
    CAST("VBAC" AS BIGINT) AS vbac,
    CAST("PRIMAC" AS BIGINT) AS primac,
    CAST("REPEAC" AS BIGINT) AS repeac,
    CAST("FORCEP" AS BIGINT) AS forcep,
    CAST("VACUUM" AS BIGINT) AS vacuum,
    CAST("HYSTER" AS BIGINT) AS hyster,
    CAST("DELMETH6" AS BIGINT) AS delmeth6,
    CAST("ANEMIA" AS BIGINT) AS anemia,
    CAST("CARDIAC" AS BIGINT) AS cardiac,
    CAST("LUNG" AS BIGINT) AS lung,
    CAST("DIABETES" AS BIGINT) AS diabetes,
    CAST("HERPES" AS BIGINT) AS herpes,
    CAST("HYDRA" AS BIGINT) AS hydra,
    CAST("HEMO" AS BIGINT) AS hemo,
    CAST("CHYPER" AS BIGINT) AS chyper,
    CAST("PHYPER" AS BIGINT) AS phyper,
    CAST("ECLAMP" AS BIGINT) AS eclamp,
    CAST("INCERVIX" AS BIGINT) AS incervix,
    CAST("PRE4000" AS BIGINT) AS pre4000,
    CAST("PRETERM" AS BIGINT) AS preterm,
    CAST("RENAL" AS BIGINT) AS renal,
    CAST("RH" AS BIGINT) AS rh,
    CAST("UTERINE" AS BIGINT) AS uterine,
    CAST("OTHERMR" AS BIGINT) AS othermr,
    CAST("TOBACCO" AS BIGINT) AS tobacco,
    "CIGAR" AS cigar,
    CAST("ALCOHOL" AS BIGINT) AS alcohol,
    "DRINK" AS drink,
    CAST("DRINK5" AS BIGINT) AS drink5,
    "WTGAIN" AS wtgain,
    CAST("WTGAIN8" AS BIGINT) AS wtgain8,
    CAST("AMNIO" AS BIGINT) AS amnio,
    CAST("MONITOR" AS BIGINT) AS monitor,
    CAST("INDUCT" AS BIGINT) AS induct,
    CAST("STIMULA" AS BIGINT) AS stimula,
    CAST("TOCOL" AS BIGINT) AS tocol,
    CAST("ULTRAS" AS BIGINT) AS ultras,
    CAST("OTHEROB" AS BIGINT) AS otherob,
    CAST("FEBRILE" AS BIGINT) AS febrile,
    CAST("MECONIUM" AS BIGINT) AS meconium,
    CAST("RUPTURE" AS BIGINT) AS rupture,
    CAST("ABRUPTIO" AS BIGINT) AS abruptio,
    CAST("PREPLACE" AS BIGINT) AS preplace,
    CAST("EXCEBLD" AS BIGINT) AS excebld,
    CAST("SEIZURE" AS BIGINT) AS seizure,
    CAST("PRECIP" AS BIGINT) AS precip,
    CAST("PROLONG" AS BIGINT) AS prolong,
    CAST("DYSFUNC" AS BIGINT) AS dysfunc,
    CAST("BREECH" AS BIGINT) AS breech,
    CAST("CEPHALO" AS BIGINT) AS cephalo,
    CAST("CORD" AS BIGINT) AS cord,
    CAST("ANESTHE" AS BIGINT) AS anesthe,
    CAST("DISTRESS" AS BIGINT) AS distress,
    CAST("OTHERLB" AS BIGINT) AS otherlb,
    CAST("ANEN" AS BIGINT) AS anen,
    CAST("SPINA" AS BIGINT) AS spina,
    CAST("HYDRO" AS BIGINT) AS hydro,
    CAST("MICROCE" AS BIGINT) AS microce,
    CAST("NERVOUS" AS BIGINT) AS nervous,
    CAST("HEART" AS BIGINT) AS heart,
    CAST("CIRCUL" AS BIGINT) AS circul,
    CAST("RECTAL" AS BIGINT) AS rectal,
    CAST("TRACHEO" AS BIGINT) AS tracheo,
    CAST("OMPHALO" AS BIGINT) AS omphalo,
    CAST("GASTRO" AS BIGINT) AS gastro,
    CAST("GENITAL" AS BIGINT) AS genital,
    CAST("RENALAGE" AS BIGINT) AS renalage,
    CAST("UROGEN" AS BIGINT) AS urogen,
    CAST("CLEFTLP" AS BIGINT) AS cleftlp,
    CAST("ADACTYLY" AS BIGINT) AS adactyly,
    CAST("CLUBFOOT" AS BIGINT) AS clubfoot,
    CAST("HERNIA" AS BIGINT) AS hernia,
    CAST("MUSCULO" AS BIGINT) AS musculo,
    CAST("DOWNS" AS BIGINT) AS downs,
    CAST("CHROMO" AS BIGINT) AS chromo,
    CAST("OTHERCON" AS BIGINT) AS othercon,
    "R11" AS r11,
    CAST("GESTALL" AS BIGINT) AS gestall,
    CAST("ORIGM" AS BIGINT) AS origm,
    CAST("ORIGF" AS BIGINT) AS origf,
    CAST("EDUCM" AS BIGINT) AS educm,
    CAST("EDUCF" AS BIGINT) AS educf,
    CAST("LLBF" AS BIGINT) AS llbf,
    CAST("DMARF" AS BIGINT) AS dmarf,
    CAST("DATELMP" AS BIGINT) AS datelmp,
    CAST("PNCF" AS BIGINT) AS pncf,
    CAST("PNVF" AS BIGINT) AS pnvf,
    CAST("GESTE" AS BIGINT) AS geste,
    CAST("DELMETRF" AS BIGINT) AS delmetrf,
    CAST("MEDRSK" AS BIGINT) AS medrsk,
    CAST("TOBUSE" AS BIGINT) AS tobuse,
    CAST("CIGARSF" AS BIGINT) AS cigarsf,
    CAST("ALCUSE" AS BIGINT) AS alcuse,
    CAST("DRINKSF" AS BIGINT) AS drinksf,
    CAST("WTGN" AS BIGINT) AS wtgn,
    CAST("OBSTRC" AS BIGINT) AS obstrc,
    CAST("CLABOR" AS BIGINT) AS clabor,
    CAST("CONGAN" AS BIGINT) AS congan,
    CAST("UCF" AS BIGINT) AS ucf,
    CAST("PLURALF" AS BIGINT) AS pluralf,
    "R12" AS r12,
    CAST("ALLGOCC" AS BIGINT) AS allgocc,
    "R13" AS r13,
    "SMSARES" AS smsares,
    "POPSMAS" AS popsmas
FROM "instituto-de-estad-sticas-de-puerto-rico-mortalidad-fetal"
