-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_resource",
    "source_file",
    "month",
    CAST("Todas las entidades" AS BIGINT) AS todas_las_entidades,
    CAST("Entidades de la Oficina del Gobernador" AS BIGINT) AS entidades_de_la_oficina_del_gobernador,
    CAST("Departamentos y Agencias" AS BIGINT) AS departamentos_y_agencias,
    CAST("Corporaciones publicas" AS BIGINT) AS corporaciones_publicas,
    CAST("Otras entidades" AS BIGINT) AS otras_entidades,
    CAST("Rama Legislativa" AS BIGINT) AS rama_legislativa,
    CAST("Entidades municipales" AS BIGINT) AS entidades_municipales,
    CAST("Rama Judicial" AS BIGINT) AS rama_judicial,
    CAST("Oficina del Contralor" AS BIGINT) AS oficina_del_contralor,
    CAST("Departamento de Agricultura" AS BIGINT) AS departamento_de_agricultura,
    CAST("Departamento de Estado" AS BIGINT) AS departamento_de_estado,
    CAST("Departamento de Hacienda" AS BIGINT) AS departamento_de_hacienda,
    CAST("Departamento de Educacion" AS BIGINT) AS departamento_de_educacion,
    CAST("Consejo General de Educacion" AS BIGINT) AS consejo_general_de_educacion,
    CAST("Departamento de la Vivienda" AS BIGINT) AS departamento_de_la_vivienda,
    CAST("Administracion de la Industria y el Deporte Hipico" AS BIGINT) AS administracion_de_la_industria_y_el_deporte_hipico,
    CAST("Administracion de Fomento Cooperativo" AS BIGINT) AS administracion_de_fomento_cooperativo,
    CAST("Departamento de Recreacion y Deportes" AS BIGINT) AS departamento_de_recreacion_y_deportes,
    CAST("Administracion de Reglamentos y Permisos" AS BIGINT) AS administracion_de_reglamentos_y_permisos,
    CAST("Oficina del Comisionado de Asuntos Municipales" AS BIGINT) AS oficina_del_comisionado_de_asuntos_municipales,
    CAST("Agencia Estatal para Manejo de Emergencias y Admi de Desastres" AS BIGINT) AS agencia_estatal_para_manejo_de_emergencias_y_admi_de_desastres,
    CAST("Comision Estatal de Elecciones" AS BIGINT) AS comision_estatal_de_elecciones,
    CAST("Comision Industrial" AS BIGINT) AS comision_industrial,
    CAST("Oficina de la Procuradora de las Mujeres" AS BIGINT) AS oficina_de_la_procuradora_de_las_mujeres,
    CAST("Comision para Ventilar Querellas Municipales" AS BIGINT) AS comision_para_ventilar_querellas_municipales,
    CAST("Guardia Nacional" AS BIGINT) AS guardia_nacional,
    CAST("Junta de Apelaciones sobre Construcciones y Lotificaciones" AS BIGINT) AS junta_de_apelaciones_sobre_construcciones_y_lotificaciones,
    CAST("Junta de Planificacion" AS BIGINT) AS junta_de_planificacion,
    CAST("Junta de Relaciones del Trabajo" AS BIGINT) AS junta_de_relaciones_del_trabajo,
    CAST("Sistema de Retiro para Maestros" AS BIGINT) AS sistema_de_retiro_para_maestros,
    CAST("Oficina de Gerencia y Presupuesto" AS BIGINT) AS oficina_de_gerencia_y_presupuesto,
    CAST("Ofic Capacitacion Asesoramiento Asuntos Laborales y Admi de RH" AS BIGINT) AS ofic_capacitacion_asesoramiento_asuntos_laborales_y_admi_de_rh,
    CAST("Comision Apelativa del Sist de Admi de RH del Servicio Publico" AS BIGINT) AS comision_apelativa_del_sist_de_admi_de_rh_del_servicio_publico,
    CAST("Oficina del Comisionado de Seguros" AS BIGINT) AS oficina_del_comisionado_de_seguros,
    CAST("Oficina del Gobernador" AS BIGINT) AS oficina_del_gobernador,
    CAST("Oficina del Inspector de Cooperativas" AS BIGINT) AS oficina_del_inspector_de_cooperativas,
    CAST("Policia" AS BIGINT) AS policia,
    CAST("Colegio Universitario de Justicia Criminal" AS BIGINT) AS colegio_universitario_de_justicia_criminal,
    CAST("Cuerpo de Bomberos" AS BIGINT) AS cuerpo_de_bomberos,
    CAST("Oficina del Comisionado de Instituciones Financieras" AS BIGINT) AS oficina_del_comisionado_de_instituciones_financieras,
    CAST("Oficina del Procurador de las Personas con Impedimentos" AS BIGINT) AS oficina_del_procurador_de_las_personas_con_impedimentos,
    CAST("Comision Permanente de los Sistemas de Retiro" AS BIGINT) AS comision_permanente_de_los_sistemas_de_retiro,
    CAST("Oficina de Asuntos de la Juventud" AS BIGINT) AS oficina_de_asuntos_de_la_juventud,
    CAST("Oficina del Procurador de las Personas de Edad Avanzada" AS BIGINT) AS oficina_del_procurador_de_las_personas_de_edad_avanzada,
    CAST("Junta de Calidad Ambiental" AS BIGINT) AS junta_de_calidad_ambiental,
    CAST("Oficina Estatal de Conservacion Historica" AS BIGINT) AS oficina_estatal_de_conservacion_historica,
    CAST("Consejo de Desarrollo Ocupacional y Recursos Humanos" AS BIGINT) AS consejo_de_desarrollo_ocupacional_y_recursos_humanos,
    CAST("Comision de Relaciones del Trabajo del Servicio Publico" AS BIGINT) AS comision_de_relaciones_del_trabajo_del_servicio_publico,
    CAST("Oficina Central de Comunicaciones" AS BIGINT) AS oficina_central_de_comunicaciones,
    CAST("Oficina del Procurador del Veterano" AS BIGINT) AS oficina_del_procurador_del_veterano,
    CAST("Cuerpo de Emergencias Medicas" AS BIGINT) AS cuerpo_de_emergencias_medicas,
    CAST("Ofic Coordi Gen para Financiamiento Socioecon y la Autogestion" AS BIGINT) AS ofic_coordi_gen_para_financiamiento_socioecon_y_la_autogestion,
    CAST("Comision Conjunta sobre Informes Especiales del Contralor" AS BIGINT) AS comision_conjunta_sobre_informes_especiales_del_contralor,
    CAST("Departamento de Correccion y Rehabilitacion" AS BIGINT) AS departamento_de_correccion_y_rehabilitacion,
    CAST("Administracion de Correccion" AS BIGINT) AS administracion_de_correccion,
    CAST("Administracion de Seguros de Salud de Puerto Rico" AS BIGINT) AS administracion_de_seguros_de_salud_de_puerto_rico,
    CAST("Administracion de Servicios Medicos" AS BIGINT) AS administracion_de_servicios_medicos,
    CAST("Administracion de Servicios Generales" AS BIGINT) AS administracion_de_servicios_generales,
    CAST("Autoridad de Conservacion y Desarrollo de Culebra" AS BIGINT) AS autoridad_de_conservacion_y_desarrollo_de_culebra,
    CAST("Comision de Investigacion, Procesamiento y Apelacion" AS BIGINT) AS comision_de_investigacion_procesamiento_y_apelacion,
    CAST("Comision de Servicio Publico" AS BIGINT) AS comision_de_servicio_publico,
    CAST("Corporacion de Empresas de Adiestramiento y Trabajo" AS BIGINT) AS corporacion_de_empresas_de_adiestramiento_y_trabajo,
    CAST("Corp de Industrias de Ciegos, Personas Mentalmente Retardadas" AS BIGINT) AS corp_de_industrias_de_ciegos_personas_mentalmente_retardadas,
    CAST("Corporacion del Centro Cardiovascular de PR y el Caribe" AS BIGINT) AS corporacion_del_centro_cardiovascular_de_pr_y_el_caribe,
    CAST("Departamento de Asuntos del Consumidor" AS BIGINT) AS departamento_de_asuntos_del_consumidor,
    CAST("Departamento de Justicia" AS BIGINT) AS departamento_de_justicia,
    CAST("Departamento de Recursos Naturales y Ambientales" AS BIGINT) AS departamento_de_recursos_naturales_y_ambientales,
    CAST("Departamento de Salud" AS BIGINT) AS departamento_de_salud,
    CAST("Salud Correccional" AS BIGINT) AS salud_correccional,
    CAST("Admi de Servicios de Salud Mental y Contra la Adiccion" AS BIGINT) AS admi_de_servicios_de_salud_mental_y_contra_la_adiccion,
    CAST("Oficina de la Procuradora del Paciente" AS BIGINT) AS oficina_de_la_procuradora_del_paciente,
    CAST("Departamento de la Familia" AS BIGINT) AS departamento_de_la_familia,
    CAST("Admi para el Cuidado y Desarrollo Integral de la Niñez" AS BIGINT) AS admi_para_el_cuidado_y_desarrollo_integral_de_la_ni_ez,
    CAST("Administracion de Desarrollo Socioeconomico de la Familia" AS BIGINT) AS administracion_de_desarrollo_socioeconomico_de_la_familia,
    CAST("Administracion para el Sustento de Menores" AS BIGINT) AS administracion_para_el_sustento_de_menores,
    CAST("Administracion de Rehabilitacion Vocacional" AS BIGINT) AS administracion_de_rehabilitacion_vocacional,
    CAST("Administracion de Familias y Niños" AS BIGINT) AS administracion_de_familias_y_ni_os,
    CAST("Administracion de Instituciones Juveniles" AS BIGINT) AS administracion_de_instituciones_juveniles,
    CAST("Departamento del Trabajo y Recursos Humanos" AS BIGINT) AS departamento_del_trabajo_y_recursos_humanos,
    CAST("Admi para Adiestramiento de Futuros Empresarios y Trabajadores" AS BIGINT) AS admi_para_adiestramiento_de_futuros_empresarios_y_trabajadores,
    CAST("Departamento de Transportacion y Obras Publicas" AS BIGINT) AS departamento_de_transportacion_y_obras_publicas,
    CAST("Administracion de Asuntos Federales de Puerto Rico" AS BIGINT) AS administracion_de_asuntos_federales_de_puerto_rico,
    CAST("Instituto de Ciencias Forenses" AS BIGINT) AS instituto_de_ciencias_forenses,
    CAST("Junta de Libertad Bajo Palabra" AS BIGINT) AS junta_de_libertad_bajo_palabra,
    CAST("Oficina de Servicios con Antelacion al Juicio" AS BIGINT) AS oficina_de_servicios_con_antelacion_al_juicio,
    CAST("Corporacion de Puerto Rico para la Difusion Publica" AS BIGINT) AS corporacion_de_puerto_rico_para_la_difusion_publica,
    CAST("Junta Reglamentadora de Telecomunicaciones" AS BIGINT) AS junta_reglamentadora_de_telecomunicaciones,
    CAST("Compañia de Parques Nacionales" AS BIGINT) AS compa_ia_de_parques_nacionales,
    CAST("Autoridad de Desperdicios Solidos" AS BIGINT) AS autoridad_de_desperdicios_solidos,
    CAST("Administracion de Terrenos" AS BIGINT) AS administracion_de_terrenos,
    CAST("Consejo de Educacion" AS BIGINT) AS consejo_de_educacion,
    CAST("Compañia de Comercio y Exportacion" AS BIGINT) AS compa_ia_de_comercio_y_exportacion,
    CAST("Administracion de Servicios y Desarrollo Agropecuario" AS BIGINT) AS administracion_de_servicios_y_desarrollo_agropecuario,
    CAST("Corporacion para el Desarrollo Rural de Puerto Rico" AS BIGINT) AS corporacion_para_el_desarrollo_rural_de_puerto_rico,
    CAST("Administracion del Derecho al Trabajo" AS BIGINT) AS administracion_del_derecho_al_trabajo,
    CAST("Autoridad de Carreteras y Transportacion" AS BIGINT) AS autoridad_de_carreteras_y_transportacion,
    CAST("Autoridad Metropolitana de Autobuses" AS BIGINT) AS autoridad_metropolitana_de_autobuses,
    CAST("Autoridad de Transporte Maritimo" AS BIGINT) AS autoridad_de_transporte_maritimo,
    CAST("Compañia de Turismo" AS BIGINT) AS compa_ia_de_turismo,
    CAST("Compañia de Fomento Industrial" AS BIGINT) AS compa_ia_de_fomento_industrial,
    CAST("Departamento de Desarrollo Economico y Comercio" AS BIGINT) AS departamento_de_desarrollo_economico_y_comercio,
    CAST("Instituto de Cultura Puertorriqueña" AS BIGINT) AS instituto_de_cultura_puertorrique_a,
    CAST("Corporacion de las Artes Musicales" AS BIGINT) AS corporacion_de_las_artes_musicales,
    CAST("Corporacion del Centro de Bellas Artes Luis A. Ferre" AS BIGINT) AS corporacion_del_centro_de_bellas_artes_luis_a_ferre,
    CAST("Corporacion del Conservatorio de Musica" AS BIGINT) AS corporacion_del_conservatorio_de_musica,
    CAST("Escuela de Artes Plasticas" AS BIGINT) AS escuela_de_artes_plasticas,
    CAST("Corp para Desarr de Artes, Ciencias e Industria Cinematografica" AS BIGINT) AS corp_para_desarr_de_artes_ciencias_e_industria_cinematografica,
    CAST("Compañia Desarrollo Integral de la Peninsula de Cantera" AS BIGINT) AS compa_ia_desarrollo_integral_de_la_peninsula_de_cantera,
    CAST("Junta de Gobierno del Servicio 9-1-1" AS BIGINT) AS junta_de_gobierno_del_servicio_9_1_1,
    CAST("Corp Publica para la Supervision y Seguros de Cooperativas" AS BIGINT) AS corp_publica_para_la_supervision_y_seguros_de_cooperativas,
    CAST("Patronato de Ponce" AS BIGINT) AS patronato_de_ponce,
    CAST("Admi de Sist de Retiro de Empleados del Gobierno y Judicatura" AS BIGINT) AS admi_de_sist_de_retiro_de_empleados_del_gobierno_y_judicatura,
    CAST("Fideicomiso Institucional de la Guardia Nacional" AS BIGINT) AS fideicomiso_institucional_de_la_guardia_nacional,
    CAST("Oficina de Etica Gubernamental" AS BIGINT) AS oficina_de_etica_gubernamental,
    CAST("Centro de Recaudacion de Ingresos Municipales" AS BIGINT) AS centro_de_recaudacion_de_ingresos_municipales,
    CAST("Oficina para Asuntos de Seguridad Publica" AS BIGINT) AS oficina_para_asuntos_de_seguridad_publica,
    CAST("Instituto de Estadisticas de Puerto Rico" AS BIGINT) AS instituto_de_estadisticas_de_puerto_rico,
    CAST("Camara de Representantes" AS BIGINT) AS camara_de_representantes,
    CAST("Comision Especial Conjunta sobre Donativos Legislativos" AS BIGINT) AS comision_especial_conjunta_sobre_donativos_legislativos,
    CAST("Oficina de Servicios Legislativos" AS BIGINT) AS oficina_de_servicios_legislativos,
    CAST("Superintendencia del Capitolio" AS BIGINT) AS superintendencia_del_capitolio,
    CAST("Senado" AS BIGINT) AS senado,
    CAST("Comision de Derechos Civiles" AS BIGINT) AS comision_de_derechos_civiles,
    CAST("Comision para la Seguridad en el Transito" AS BIGINT) AS comision_para_la_seguridad_en_el_transito,
    CAST("Panel sobre el Fiscal Especial Independiente" AS BIGINT) AS panel_sobre_el_fiscal_especial_independiente,
    CAST("Oficina del Procurador del Ciudadano" AS BIGINT) AS oficina_del_procurador_del_ciudadano,
    CAST("Oficina de Administracion de los Tribunales" AS BIGINT) AS oficina_de_administracion_de_los_tribunales,
    CAST("Autoridad de Tierras de Puerto Rico" AS BIGINT) AS autoridad_de_tierras_de_puerto_rico,
    CAST("Autoridad de Acueductos y Alcantarillados" AS BIGINT) AS autoridad_de_acueductos_y_alcantarillados,
    CAST("UPR en Rio Piedras" AS BIGINT) AS upr_en_rio_piedras,
    CAST("UPR en Mayagüez" AS BIGINT) AS upr_en_mayag_ez,
    CAST("UPR - Recinto de Ciencias Medicas" AS BIGINT) AS upr_recinto_de_ciencias_medicas,
    CAST("Estacion Experimental Agricola - UPR" AS BIGINT) AS estacion_experimental_agricola_upr,
    CAST("Servicio de Extension Agricola UPR" AS BIGINT) AS servicio_de_extension_agricola_upr,
    CAST("UPR en Cayey" AS BIGINT) AS upr_en_cayey,
    CAST("UPR en Humacao" AS BIGINT) AS upr_en_humacao,
    CAST("UPR en Aguadilla" AS BIGINT) AS upr_en_aguadilla,
    CAST("UPR en Arecibo" AS BIGINT) AS upr_en_arecibo,
    CAST("UPR en Bayamon" AS BIGINT) AS upr_en_bayamon,
    CAST("UPR en Ponce" AS BIGINT) AS upr_en_ponce,
    CAST("UPR en Carolina" AS BIGINT) AS upr_en_carolina,
    CAST("UPR - Administracion Central" AS BIGINT) AS upr_administracion_central,
    CAST("UPR en Utuado" AS BIGINT) AS upr_en_utuado,
    CAST("Centro Comprensivo de Cancer de la UPR" AS BIGINT) AS centro_comprensivo_de_cancer_de_la_upr,
    CAST("Autoridad de Energia Electrica" AS BIGINT) AS autoridad_de_energia_electrica,
    CAST("Admi de Compensaciones por Accidentes de Automoviles" AS BIGINT) AS admi_de_compensaciones_por_accidentes_de_automoviles,
    CAST("Banco Gubernamental de Fomento" AS BIGINT) AS banco_gubernamental_de_fomento,
    CAST("Banco de Desarrollo Economico" AS BIGINT) AS banco_de_desarrollo_economico,
    CAST("Autoridad para el Financiamiento de la Infraestructura" AS BIGINT) AS autoridad_para_el_financiamiento_de_la_infraestructura,
    CAST("Corporacion de Seguros Agricolas" AS BIGINT) AS corporacion_de_seguros_agricolas,
    CAST("Autoridad de los Puertos" AS BIGINT) AS autoridad_de_los_puertos,
    CAST("Autoridad del Puerto de las Americas" AS BIGINT) AS autoridad_del_puerto_de_las_americas,
    CAST("Autoridad de Edificios Publicos" AS BIGINT) AS autoridad_de_edificios_publicos,
    CAST("Autoridad del Distrito del Centro de Convenciones" AS BIGINT) AS autoridad_del_distrito_del_centro_de_convenciones,
    CAST("Corporacion del Fondo del Seguro del Estado" AS BIGINT) AS corporacion_del_fondo_del_seguro_del_estado,
    CAST("Autoridad para el Financiamiento de la Vivienda" AS BIGINT) AS autoridad_para_el_financiamiento_de_la_vivienda,
    CAST("Centro de Diabetes para Puerto Rico" AS BIGINT) AS centro_de_diabetes_para_puerto_rico,
    CAST("Comision de Practicaje" AS BIGINT) AS comision_de_practicaje,
    CAST("Adjuntas" AS BIGINT) AS adjuntas,
    CAST("Aguada" AS BIGINT) AS aguada,
    CAST("Aguadilla" AS BIGINT) AS aguadilla,
    CAST("Aguas Buenas" AS BIGINT) AS aguas_buenas,
    CAST("Aibonito" AS BIGINT) AS aibonito,
    CAST("Añasco" AS BIGINT) AS a_asco,
    CAST("Arecibo" AS BIGINT) AS arecibo,
    CAST("Arroyo" AS BIGINT) AS arroyo,
    CAST("Barceloneta" AS BIGINT) AS barceloneta,
    CAST("Barranquitas" AS BIGINT) AS barranquitas,
    CAST("Bayamon" AS BIGINT) AS bayamon,
    CAST("Cabo Rojo" AS BIGINT) AS cabo_rojo,
    CAST("Caguas" AS BIGINT) AS caguas,
    CAST("Camuy" AS BIGINT) AS camuy,
    CAST("Canovanas" AS BIGINT) AS canovanas,
    CAST("Carolina" AS BIGINT) AS carolina,
    CAST("Cataño" AS BIGINT) AS cata_o,
    CAST("Cayey" AS BIGINT) AS cayey,
    CAST("Ceiba" AS BIGINT) AS ceiba,
    CAST("Ciales" AS BIGINT) AS ciales,
    CAST("Cidra" AS BIGINT) AS cidra,
    CAST("Coamo" AS BIGINT) AS coamo,
    CAST("Comerio" AS BIGINT) AS comerio,
    CAST("Corozal" AS BIGINT) AS corozal,
    CAST("Culebra" AS BIGINT) AS culebra,
    CAST("Dorado" AS BIGINT) AS dorado,
    CAST("Fajardo" AS BIGINT) AS fajardo,
    CAST("Florida" AS BIGINT) AS florida,
    CAST("Guanica" AS BIGINT) AS guanica,
    CAST("Guayama" AS BIGINT) AS guayama,
    CAST("Guayanilla" AS BIGINT) AS guayanilla,
    CAST("Guaynabo" AS BIGINT) AS guaynabo,
    CAST("Gurabo" AS BIGINT) AS gurabo,
    CAST("Hatillo" AS BIGINT) AS hatillo,
    CAST("Hormigueros" AS BIGINT) AS hormigueros,
    CAST("Humacao" AS BIGINT) AS humacao,
    CAST("Isabela" AS BIGINT) AS isabela,
    CAST("Jayuya" AS BIGINT) AS jayuya,
    CAST("Juana Diaz" AS BIGINT) AS juana_diaz,
    CAST("Juncos" AS BIGINT) AS juncos,
    CAST("Lajas" AS BIGINT) AS lajas,
    CAST("Lares" AS BIGINT) AS lares,
    CAST("Las Marias" AS BIGINT) AS las_marias,
    CAST("Las Piedras" AS BIGINT) AS las_piedras,
    CAST("Loiza" AS BIGINT) AS loiza,
    CAST("Luquillo" AS BIGINT) AS luquillo,
    CAST("Manati" AS BIGINT) AS manati,
    CAST("Maricao" AS BIGINT) AS maricao,
    CAST("Maunabo" AS BIGINT) AS maunabo,
    CAST("Mayagüez" AS BIGINT) AS mayag_ez,
    CAST("Moca" AS BIGINT) AS moca,
    CAST("Morovis" AS BIGINT) AS morovis,
    CAST("Naguabo" AS BIGINT) AS naguabo,
    CAST("Naranjito" AS BIGINT) AS naranjito,
    CAST("Orocovis" AS BIGINT) AS orocovis,
    CAST("Patillas" AS BIGINT) AS patillas,
    CAST("Peñuelas" AS BIGINT) AS pe_uelas,
    CAST("Ponce" AS BIGINT) AS ponce,
    CAST("Quebradillas" AS BIGINT) AS quebradillas,
    CAST("Rincon" AS BIGINT) AS rincon,
    CAST("Rio Grande" AS BIGINT) AS rio_grande,
    CAST("Sabana Grande" AS BIGINT) AS sabana_grande,
    CAST("Salinas" AS BIGINT) AS salinas,
    CAST("San German" AS BIGINT) AS san_german,
    CAST("San Juan" AS BIGINT) AS san_juan,
    CAST("San Lorenzo" AS BIGINT) AS san_lorenzo,
    CAST("San Sebastian" AS BIGINT) AS san_sebastian,
    CAST("Santa Isabel" AS BIGINT) AS santa_isabel,
    CAST("Toa Alta" AS BIGINT) AS toa_alta,
    CAST("Toa Baja" AS BIGINT) AS toa_baja,
    CAST("Trujillo Alto" AS BIGINT) AS trujillo_alto,
    CAST("Utuado" AS BIGINT) AS utuado,
    CAST("Vega Alta" AS BIGINT) AS vega_alta,
    CAST("Vega Baja" AS BIGINT) AS vega_baja,
    CAST("Vieques" AS BIGINT) AS vieques,
    CAST("Villalba" AS BIGINT) AS villalba,
    CAST("Yabucoa" AS BIGINT) AS yabucoa,
    CAST("Yauco" AS BIGINT) AS yauco,
    CAST("Corporacion para el Desarrollo Economico de Ceiba" AS BIGINT) AS corporacion_para_el_desarrollo_economico_de_ceiba,
    CAST("Corporacion para el Desarrollo del Viejo San Juan" AS BIGINT) AS corporacion_para_el_desarrollo_del_viejo_san_juan,
    CAST("Corporacion para el Desarrollo de Vivienda de Toa Baja, C.D." AS BIGINT) AS corporacion_para_el_desarrollo_de_vivienda_de_toa_baja_c_d,
    CAST("Corporacion para el Desarrollo Economico de Trujillo Alto" AS BIGINT) AS corporacion_para_el_desarrollo_economico_de_trujillo_alto,
    CAST("Corporacion para el Desarrollo Economico y Vivienda de Vieques" AS BIGINT) AS corporacion_para_el_desarrollo_economico_y_vivienda_de_vieques,
    CAST("Corporacion para el Desarrollo de la Vivienda de Bayamon, C.D." AS BIGINT) AS corporacion_para_el_desarrollo_de_la_vivienda_de_bayamon_c_d,
    CAST("Corporacion para el Desarrollo de la Salud de Bayamon" AS BIGINT) AS corporacion_para_el_desarrollo_de_la_salud_de_bayamon,
    CAST("Corp para el Desarrollo de las Bellas Artes de Guaynabo, C.D." AS BIGINT) AS corp_para_el_desarrollo_de_las_bellas_artes_de_guaynabo_c_d,
    CAST("Desarrollo Integral del Sur" AS BIGINT) AS desarrollo_integral_del_sur,
    CAST("Area Local de Desarrollo Laboral de Bayamon - Comerio" AS BIGINT) AS area_local_de_desarrollo_laboral_de_bayamon_comerio,
    CAST("Area Local de Desarrollo Laboral de Caguas - Guayama" AS BIGINT) AS area_local_de_desarrollo_laboral_de_caguas_guayama,
    CAST("Area Local de Desarrollo Laboral de Carolina" AS BIGINT) AS area_local_de_desarrollo_laboral_de_carolina,
    CAST("Area Local de Desarrollo Laboral de Guaynabo - Toa Baja" AS BIGINT) AS area_local_de_desarrollo_laboral_de_guaynabo_toa_baja,
    CAST("Area Local de Desarrollo Laboral de San Juan" AS BIGINT) AS area_local_de_desarrollo_laboral_de_san_juan,
    CAST("Area Local de Desarrollo Laboral de la Montaña" AS BIGINT) AS area_local_de_desarrollo_laboral_de_la_monta_a,
    CAST("Area Local de Desarrollo Laboral de Manati - Dorado" AS BIGINT) AS area_local_de_desarrollo_laboral_de_manati_dorado,
    CAST("Area Local de Desarrollo Laboral de Mayagüez - Las Marias" AS BIGINT) AS area_local_de_desarrollo_laboral_de_mayag_ez_las_marias,
    CAST("Area Local de Desarrollo Laboral de Norte - Central" AS BIGINT) AS area_local_de_desarrollo_laboral_de_norte_central,
    CAST("Area Local de Desarrollo Laboral del Noreste" AS BIGINT) AS area_local_de_desarrollo_laboral_del_noreste,
    CAST("Area Local de Desarrollo Laboral del Noroeste" AS BIGINT) AS area_local_de_desarrollo_laboral_del_noroeste,
    CAST("Area Local de Desarrollo Laboral del Sureste" AS BIGINT) AS area_local_de_desarrollo_laboral_del_sureste,
    CAST("Area Local de Desarrollo Laboral del Suroeste" AS BIGINT) AS area_local_de_desarrollo_laboral_del_suroeste,
    CAST("Area Local de Desarrollo Laboral Surcentral" AS BIGINT) AS area_local_de_desarrollo_laboral_surcentral,
    CAST("Corp para Desarrollo del Centro Ponceño de Autismo" AS BIGINT) AS corp_para_desarrollo_del_centro_ponce_o_de_autismo,
    CAST("Corp para el Desarrollo Recreativo del Castillo del Niño" AS BIGINT) AS corp_para_el_desarrollo_recreativo_del_castillo_del_ni_o,
    CAST("Corporacion del Proyecto Enlace del Caño Martin Peña" AS BIGINT) AS corporacion_del_proyecto_enlace_del_ca_o_martin_pe_a,
    CAST("Corporacion para las Artes Escenico-Musicales" AS BIGINT) AS corporacion_para_las_artes_escenico_musicales,
    CAST("Corporacion de la Orquesta Sinfonica" AS BIGINT) AS corporacion_de_la_orquesta_sinfonica,
    CAST("Autoridad para el Redesarrollo Local de Roosevelt Roads" AS BIGINT) AS autoridad_para_el_redesarrollo_local_de_roosevelt_roads,
    CAST("Oficina de Exencion Contributiva Industrial" AS BIGINT) AS oficina_de_exencion_contributiva_industrial,
    CAST("Comision de Desarrollo Cooperativo" AS BIGINT) AS comision_de_desarrollo_cooperativo,
    CAST("Autoridad para las Alianzas Publico-Privadas" AS BIGINT) AS autoridad_para_las_alianzas_publico_privadas,
    CAST("Administracion para el Desarrollo de Empresas Agropecuarias" AS BIGINT) AS administracion_para_el_desarrollo_de_empresas_agropecuarias,
    CAST("Comision Apelativa del Servicio Publico" AS BIGINT) AS comision_apelativa_del_servicio_publico,
    CAST("Junta Revisora de Permisos y Uso de Terrenos" AS BIGINT) AS junta_revisora_de_permisos_y_uso_de_terrenos,
    CAST("Oficina del Inspector General de Permisos" AS BIGINT) AS oficina_del_inspector_general_de_permisos,
    CAST("Oficina de Gerencia de Permisos" AS BIGINT) AS oficina_de_gerencia_de_permisos,
    CAST("Oficina del Inspector General del Gobierno" AS BIGINT) AS oficina_del_inspector_general_del_gobierno,
    CAST("Administracion de Desarrollo Laboral" AS BIGINT) AS administracion_de_desarrollo_laboral,
    CAST("Oficina del Contralor Electoral" AS BIGINT) AS oficina_del_contralor_electoral,
    CAST("Administracion de Vivienda Publica" AS BIGINT) AS administracion_de_vivienda_publica,
    CAST("Servicios Medicos Universitarios, Inc." AS BIGINT) AS servicios_medicos_universitarios_inc,
    CAST("Oficina Estatal de Politica Publica Energetica" AS BIGINT) AS oficina_estatal_de_politica_publica_energetica,
    CAST("Autoridad de Transporte Integrado" AS BIGINT) AS autoridad_de_transporte_integrado,
    CAST("Oficina del Bosque Modelo" AS BIGINT) AS oficina_del_bosque_modelo,
    CAST("Autoridad de Asesoria Financiera y Agencia Fiscal" AS BIGINT) AS autoridad_de_asesoria_financiera_y_agencia_fiscal,
    CAST("Defensoria de las Personas con Impedimentos" AS BIGINT) AS defensoria_de_las_personas_con_impedimentos,
    CAST("Autoridad del Puerto de Ponce" AS BIGINT) AS autoridad_del_puerto_de_ponce,
    CAST("Oficina Independiente de Proteccion al Consumidor" AS BIGINT) AS oficina_independiente_de_proteccion_al_consumidor
FROM "instituto-de-estad-sticas-de-puerto-rico-estadisticas-de-puestos-ocupados-en-gobierno-indicadores-pr"
