-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_resource",
    "source_file",
    CAST("matchs" AS BIGINT) AS matchs,
    "idnumber",
    CAST("biryr" AS BIGINT) AS biryr,
    CAST("resstatb" AS BIGINT) AS resstatb,
    CAST("brstate" AS BIGINT) AS brstate,
    CAST("stoccfipb" AS BIGINT) AS stoccfipb,
    CAST("cntocfipb" AS BIGINT) AS cntocfipb,
    "stresfipb",
    "cntyrfpb",
    "plres",
    CAST("mageflg" AS BIGINT) AS mageflg,
    CAST("dmage" AS BIGINT) AS dmage,
    CAST("mager8" AS BIGINT) AS mager8,
    CAST("ormoth" AS BIGINT) AS ormoth,
    CAST("orracem" AS BIGINT) AS orracem,
    CAST("mraceimp" AS BIGINT) AS mraceimp,
    "mrace",
    CAST("mrace3" AS BIGINT) AS mrace3,
    "dmeduc",
    CAST("meduc6" AS BIGINT) AS meduc6,
    CAST("dmarimp" AS BIGINT) AS dmarimp,
    CAST("dmar" AS BIGINT) AS dmar,
    "mplbir",
    CAST("mplbirr" AS BIGINT) AS mplbirr,
    "dtotord",
    "dlivord",
    "mompre",
    CAST("mpre5" AS BIGINT) AS mpre5,
    "nprevist",
    CAST("adequacy" AS BIGINT) AS adequacy,
    "r1",
    CAST("fageflg" AS BIGINT) AS fageflg,
    CAST("dface" AS BIGINT) AS dface,
    CAST("orfath" AS BIGINT) AS orfath,
    CAST("orracef" AS BIGINT) AS orracef,
    "frace",
    CAST("pldel" AS BIGINT) AS pldel,
    CAST("birattnd" AS BIGINT) AS birattnd,
    "r2",
    CAST("getestm" AS BIGINT) AS getestm,
    CAST("clingest" AS BIGINT) AS clingest,
    CAST("gestimp" AS BIGINT) AS gestimp,
    CAST("gestat" AS BIGINT) AS gestat,
    "gestat10",
    "cseximp",
    CAST("csex" AS BIGINT) AS csex,
    CAST("biwif" AS BIGINT) AS biwif,
    "dbirwt",
    "biirwt12",
    CAST("birwt4" AS BIGINT) AS birwt4,
    "plurimp",
    CAST("dpliral" AS BIGINT) AS dpliral,
    "fmaps",
    CAST("vaginal" AS BIGINT) AS vaginal,
    CAST("vbac" AS BIGINT) AS vbac,
    CAST("primac" AS BIGINT) AS primac,
    CAST("repeac" AS BIGINT) AS repeac,
    CAST("forcep" AS BIGINT) AS forcep,
    CAST("vacuum" AS BIGINT) AS vacuum,
    "r3",
    CAST("delmeth5" AS BIGINT) AS delmeth5,
    CAST("mrflag" AS BIGINT) AS mrflag,
    CAST("anemia" AS BIGINT) AS anemia,
    CAST("cardiac" AS BIGINT) AS cardiac,
    CAST("lung" AS BIGINT) AS lung,
    CAST("diabetes" AS BIGINT) AS diabetes,
    CAST("herpes" AS BIGINT) AS herpes,
    CAST("hydra" AS BIGINT) AS hydra,
    CAST("hemo" AS BIGINT) AS hemo,
    CAST("chyper" AS BIGINT) AS chyper,
    CAST("phyper" AS BIGINT) AS phyper,
    CAST("eclamp" AS BIGINT) AS eclamp,
    CAST("incervix" AS BIGINT) AS incervix,
    CAST("pre4000" AS BIGINT) AS pre4000,
    CAST("preterm" AS BIGINT) AS preterm,
    CAST("renal" AS BIGINT) AS renal,
    CAST("rh" AS BIGINT) AS rh,
    CAST("uterine" AS BIGINT) AS uterine,
    CAST("othermr" AS BIGINT) AS othermr,
    CAST("tobacco" AS BIGINT) AS tobacco,
    "cigar",
    CAST("cigar6" AS BIGINT) AS cigar6,
    CAST("alcohol" AS BIGINT) AS alcohol,
    "drink",
    CAST("drink5" AS BIGINT) AS drink5,
    "wtgain",
    CAST("wtgain9" AS BIGINT) AS wtgain9,
    CAST("obfalg" AS BIGINT) AS obfalg,
    CAST("amnio" AS BIGINT) AS amnio,
    CAST("monitor" AS BIGINT) AS monitor,
    CAST("incduct" AS BIGINT) AS incduct,
    CAST("stimula" AS BIGINT) AS stimula,
    CAST("tocol" AS BIGINT) AS tocol,
    CAST("ultras" AS BIGINT) AS ultras,
    CAST("otherob" AS BIGINT) AS otherob,
    CAST("fbflag" AS BIGINT) AS fbflag,
    CAST("febrile" AS BIGINT) AS febrile,
    CAST("meconium" AS BIGINT) AS meconium,
    CAST("rupture" AS BIGINT) AS rupture,
    CAST("abrptio" AS BIGINT) AS abrptio,
    CAST("preplace" AS BIGINT) AS preplace,
    CAST("excebld" AS BIGINT) AS excebld,
    CAST("seizure" AS BIGINT) AS seizure,
    CAST("precip" AS BIGINT) AS precip,
    CAST("prolong" AS BIGINT) AS prolong,
    CAST("dysfunc" AS BIGINT) AS dysfunc,
    CAST("breech" AS BIGINT) AS breech,
    CAST("cephalo" AS BIGINT) AS cephalo,
    CAST("cord" AS BIGINT) AS cord,
    CAST("anesthe" AS BIGINT) AS anesthe,
    CAST("distress" AS BIGINT) AS distress,
    CAST("otherlb" AS BIGINT) AS otherlb,
    CAST("nbflag" AS BIGINT) AS nbflag,
    CAST("nanemia" AS BIGINT) AS nanemia,
    CAST("injury" AS BIGINT) AS injury,
    CAST("alcosyn" AS BIGINT) AS alcosyn,
    CAST("hyaline" AS BIGINT) AS hyaline,
    CAST("meconsyn" AS BIGINT) AS meconsyn,
    CAST("venl30" AS BIGINT) AS venl30,
    CAST("ven30m" AS BIGINT) AS ven30m,
    CAST("nseiz" AS BIGINT) AS nseiz,
    CAST("otherab" AS BIGINT) AS otherab,
    CAST("cgflag" AS BIGINT) AS cgflag,
    CAST("anen" AS BIGINT) AS anen,
    CAST("spina" AS BIGINT) AS spina,
    CAST("hydro" AS BIGINT) AS hydro,
    CAST("microce" AS BIGINT) AS microce,
    CAST("nervous" AS BIGINT) AS nervous,
    CAST("heart" AS BIGINT) AS heart,
    CAST("circul" AS BIGINT) AS circul,
    CAST("rectal" AS BIGINT) AS rectal,
    CAST("tracheo" AS BIGINT) AS tracheo,
    CAST("omphalo" AS BIGINT) AS omphalo,
    CAST("gastro" AS BIGINT) AS gastro,
    CAST("genital" AS BIGINT) AS genital,
    CAST("renalge" AS BIGINT) AS renalge,
    CAST("urogen" AS BIGINT) AS urogen,
    CAST("cleftp" AS BIGINT) AS cleftp,
    CAST("adactyly" AS BIGINT) AS adactyly,
    CAST("clubfoot" AS BIGINT) AS clubfoot,
    CAST("hernia" AS BIGINT) AS hernia,
    CAST("musculo" AS BIGINT) AS musculo,
    CAST("downs" AS BIGINT) AS downs,
    CAST("chromo" AS BIGINT) AS chromo,
    CAST("othercon" AS BIGINT) AS othercon,
    CAST("origm" AS BIGINT) AS origm,
    CAST("origf" AS BIGINT) AS origf,
    CAST("educm" AS BIGINT) AS educm,
    CAST("r4" AS BIGINT) AS r4,
    CAST("geste" AS BIGINT) AS geste,
    "r5",
    CAST("fmaprsf" AS BIGINT) AS fmaprsf,
    CAST("delmetre" AS BIGINT) AS delmetre,
    CAST("medrsk" AS BIGINT) AS medrsk,
    CAST("tobuse" AS BIGINT) AS tobuse,
    CAST("alcuse" AS BIGINT) AS alcuse,
    CAST("wtgn" AS BIGINT) AS wtgn,
    CAST("obstrc" AS BIGINT) AS obstrc,
    CAST("clabor" AS BIGINT) AS clabor,
    CAST("abnml" AS BIGINT) AS abnml,
    CAST("congan" AS BIGINT) AS congan,
    CAST("apiflag" AS BIGINT) AS apiflag,
    "cdobmimp",
    "birmon",
    "r6",
    CAST("weekdayb" AS BIGINT) AS weekdayb,
    CAST("r7" AS BIGINT) AS r7,
    "aged",
    CAST("ager5" AS BIGINT) AS ager5,
    CAST("accidpl" AS BIGINT) AS accidpl,
    "ucod",
    "ucodr130",
    "recwt",
    "eanum",
    "entity1",
    "entity2",
    "entity3",
    "entity4",
    "entity5",
    "entity6",
    "entity7",
    "entity8",
    "entity9",
    "entity10",
    "entity11",
    CAST("entity12" AS BIGINT) AS entity12,
    "entity13",
    "entity14",
    "entity15",
    "entity16",
    "entity17",
    "entity18",
    "entity19",
    "entity20",
    "ranum",
    "record1",
    "record2",
    "record3",
    "record4",
    "record5",
    "record6",
    "record7",
    "record8",
    "record9",
    "record10",
    CAST("record11" AS BIGINT) AS record11,
    "record12",
    "record13",
    "record14",
    "record15",
    "record16",
    "record17",
    "record18",
    "record19",
    "record20",
    CAST("resstatd" AS BIGINT) AS resstatd,
    CAST("drstate" AS BIGINT) AS drstate,
    CAST("stoccfipd" AS BIGINT) AS stoccfipd,
    CAST("cntocfipd" AS BIGINT) AS cntocfipd,
    "stresfipd",
    "cntyrfpd",
    "plresd",
    CAST("hospd" AS BIGINT) AS hospd,
    CAST("dthyr" AS BIGINT) AS dthyr,
    "dthmon",
    "r8",
    CAST("weekdayd" AS BIGINT) AS weekdayd,
    "r9"
FROM "instituto-de-estad-sticas-de-puerto-rico-mortalidad-infantil-cohortes"
