-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_resource",
    "source_file",
    CAST("DATAYEAR" AS BIGINT) AS datayear,
    CAST("RECTYPE" AS BIGINT) AS rectype,
    CAST("RESTATUS" AS BIGINT) AS restatus,
    CAST("RECWT" AS BIGINT) AS recwt,
    CAST("PLDEL" AS BIGINT) AS pldel,
    CAST("PLDEL3" AS BIGINT) AS pldel3,
    CAST("BIRATTND" AS BIGINT) AS birattnd,
    CAST("REGNOCC" AS BIGINT) AS regnocc,
    CAST("DIVOCC" AS BIGINT) AS divocc,
    CAST("STSUBOCC" AS BIGINT) AS stsubocc,
    CAST("STNATEXP" AS BIGINT) AS stnatexp,
    CAST("STATENAT" AS BIGINT) AS statenat,
    "CNTYNAT" AS cntynat,
    CAST("STOCCFIP" AS BIGINT) AS stoccfip,
    "CNTOCFIP" AS cntocfip,
    CAST("CNTOCPOP" AS BIGINT) AS cntocpop,
    CAST("REGNRES" AS BIGINT) AS regnres,
    CAST("DIVRES" AS BIGINT) AS divres,
    CAST("STSUBRES" AS BIGINT) AS stsubres,
    "STRESEXP" AS stresexp,
    "STATERES" AS stateres,
    "CNTYRES" AS cntyres,
    "CITYRES" AS cityres,
    "CITRSPOP" AS citrspop,
    "METRORES" AS metrores,
    "STRESFIP" AS stresfip,
    "CNTYRFIP" AS cntyrfip,
    "PLACEFIP" AS placefip,
    "CMSA" AS cmsa,
    "SMSARFIP" AS smsarfip,
    "CNTRSPOP" AS cntrspop,
    "R1A" AS r1a,
    CAST("MAGERFLG" AS BIGINT) AS magerflg,
    CAST("MAGEIMP" AS BIGINT) AS mageimp,
    CAST("DMAGE" AS BIGINT) AS dmage,
    "MAGE36" AS mage36,
    "MAGE12" AS mage12,
    CAST("MAGE8" AS BIGINT) AS mage8,
    CAST("ORMOTH" AS BIGINT) AS ormoth,
    CAST("ORRACEM" AS BIGINT) AS orracem,
    CAST("MRACEIMP" AS BIGINT) AS mraceimp,
    "MRACE" AS mrace,
    CAST("MRACE3" AS BIGINT) AS mrace3,
    "DMEDUC" AS dmeduc,
    CAST("MEDUC6" AS BIGINT) AS meduc6,
    CAST("DMARIMP" AS BIGINT) AS dmarimp,
    CAST("DMAR" AS BIGINT) AS dmar,
    "MPLBIR" AS mplbir,
    CAST("MPLBIRR" AS BIGINT) AS mplbirr,
    CAST("DMAGERPT" AS BIGINT) AS dmagerpt,
    CAST("ADEQUACY" AS BIGINT) AS adequacy,
    "NLBNL" AS nlbnl,
    "NLBND" AS nlbnd,
    "NOTERM" AS noterm,
    "DLIVORD" AS dlivord,
    CAST("LIVORD9" AS BIGINT) AS livord9,
    "DTOTORD" AS dtotord,
    CAST("TOTORD9" AS BIGINT) AS totord9,
    "MONPRE" AS monpre,
    CAST("MPRE6" AS BIGINT) AS mpre6,
    CAST("MPRE5" AS BIGINT) AS mpre5,
    "NPREVIS" AS nprevis,
    "NPREV12" AS nprev12,
    "LMPMON" AS lmpmon,
    "LMPDAY" AS lmpday,
    CAST("LMPYR" AS BIGINT) AS lmpyr,
    "R8" AS r8,
    CAST("BWIMP" AS BIGINT) AS bwimp,
    "Imputed_birthweight" AS imputed_birthweight,
    "R2" AS r2,
    CAST("FAGERFLG" AS BIGINT) AS fagerflg,
    CAST("DFAGE" AS BIGINT) AS dfage,
    "FAGE11" AS fage11,
    CAST("ORFATH" AS BIGINT) AS orfath,
    CAST("ORRACEF" AS BIGINT) AS orracef,
    "FRACE" AS frace,
    CAST("FRACE4" AS BIGINT) AS frace4,
    CAST("R2A" AS BIGINT) AS r2a,
    CAST("DFAGERPT" AS BIGINT) AS dfagerpt,
    "FRACEIMP" AS fraceimp,
    "R3" AS r3,
    "CDOBMIMP" AS cdobmimp,
    "RB" AS rb,
    "BIRMON" AS birmon,
    "RC" AS rc,
    CAST("BIRYR" AS BIGINT) AS biryr,
    CAST("WEEKDAY" AS BIGINT) AS weekday,
    CAST("GESTESTM" AS BIGINT) AS gestestm,
    CAST("GESTIMP" AS BIGINT) AS gestimp,
    CAST("DGESTAT" AS BIGINT) AS dgestat,
    "GESTAT10" AS gestat10,
    CAST("GESTAT3" AS BIGINT) AS gestat3,
    "CSEXIMP" AS cseximp,
    CAST("CSEX" AS BIGINT) AS csex,
    "RD" AS rd,
    "DBIRWT" AS dbirwt,
    "BIRWT12" AS birwt12,
    CAST("BIRWT4" AS BIGINT) AS birwt4,
    CAST("PLURIMP" AS BIGINT) AS plurimp,
    CAST("DPLURAL" AS BIGINT) AS dplural,
    CAST("R6" AS BIGINT) AS r6,
    "FMAPS" AS fmaps,
    CAST("FMAPSR" AS BIGINT) AS fmapsr,
    CAST("CLINGEST" AS BIGINT) AS clingest,
    "R4" AS r4,
    CAST("VAGINAL" AS BIGINT) AS vaginal,
    CAST("VBAC" AS BIGINT) AS vbac,
    CAST("PRIMAC" AS BIGINT) AS primac,
    CAST("REPEAC" AS BIGINT) AS repeac,
    CAST("FORCEP" AS BIGINT) AS forcep,
    CAST("VACUUM" AS BIGINT) AS vacuum,
    "R5" AS r5,
    CAST("DELMETH5" AS BIGINT) AS delmeth5,
    CAST("ANEMIA" AS BIGINT) AS anemia,
    CAST("CARDIAC" AS BIGINT) AS cardiac,
    CAST("LUNG" AS BIGINT) AS lung,
    CAST("DIABETES" AS BIGINT) AS diabetes,
    CAST("HERPES" AS BIGINT) AS herpes,
    CAST("HYDRA" AS BIGINT) AS hydra,
    CAST("HEMO" AS BIGINT) AS hemo,
    CAST("CHYPER" AS BIGINT) AS chyper,
    CAST("PHYPER" AS BIGINT) AS phyper,
    CAST("ECLAMP" AS BIGINT) AS eclamp,
    CAST("INCERVIX" AS BIGINT) AS incervix,
    CAST("PRE4000" AS BIGINT) AS pre4000,
    CAST("PRETERM" AS BIGINT) AS preterm,
    CAST("RENAL" AS BIGINT) AS renal,
    CAST("RH" AS BIGINT) AS rh,
    CAST("UTERINE" AS BIGINT) AS uterine,
    CAST("OTHERMR" AS BIGINT) AS othermr,
    CAST("TOBACCO" AS BIGINT) AS tobacco,
    "CIGAR" AS cigar,
    CAST("CIGAR6" AS BIGINT) AS cigar6,
    CAST("ALCOHOL" AS BIGINT) AS alcohol,
    "DRINK" AS drink,
    CAST("DRINK5" AS BIGINT) AS drink5,
    "WTGAIN" AS wtgain,
    CAST("WTGAIN9" AS BIGINT) AS wtgain9,
    CAST("AMNIO" AS BIGINT) AS amnio,
    CAST("MONITOR" AS BIGINT) AS monitor,
    CAST("INDUCT" AS BIGINT) AS induct,
    CAST("STIMULA" AS BIGINT) AS stimula,
    CAST("TOCOL" AS BIGINT) AS tocol,
    CAST("ULTRAS" AS BIGINT) AS ultras,
    CAST("OTHEROB" AS BIGINT) AS otherob,
    CAST("FEBRILE" AS BIGINT) AS febrile,
    CAST("MECONIUM" AS BIGINT) AS meconium,
    CAST("RUPTURE" AS BIGINT) AS rupture,
    CAST("ABRUPTIO" AS BIGINT) AS abruptio,
    CAST("PREPLACE" AS BIGINT) AS preplace,
    CAST("EXCEBLD" AS BIGINT) AS excebld,
    CAST("SEIZURE" AS BIGINT) AS seizure,
    CAST("PRECIP" AS BIGINT) AS precip,
    CAST("PROLONG" AS BIGINT) AS prolong,
    CAST("DYSFUNC" AS BIGINT) AS dysfunc,
    CAST("BREECH" AS BIGINT) AS breech,
    CAST("CEPHALO" AS BIGINT) AS cephalo,
    CAST("CORD" AS BIGINT) AS cord,
    CAST("ANESTHE" AS BIGINT) AS anesthe,
    CAST("DISTRESS" AS BIGINT) AS distress,
    CAST("OTHERLB" AS BIGINT) AS otherlb,
    CAST("NANEMIA" AS BIGINT) AS nanemia,
    CAST("INJURY" AS BIGINT) AS injury,
    CAST("ALCOSYN" AS BIGINT) AS alcosyn,
    CAST("HYALINE" AS BIGINT) AS hyaline,
    CAST("MECONSYN" AS BIGINT) AS meconsyn,
    CAST("VENL30" AS BIGINT) AS venl30,
    CAST("VEN30M" AS BIGINT) AS ven30m,
    CAST("NSEIZ" AS BIGINT) AS nseiz,
    CAST("OTHERAB" AS BIGINT) AS otherab,
    CAST("ANEN" AS BIGINT) AS anen,
    CAST("SPINA" AS BIGINT) AS spina,
    CAST("HYDRO" AS BIGINT) AS hydro,
    CAST("MICROCE" AS BIGINT) AS microce,
    CAST("NERVOUS" AS BIGINT) AS nervous,
    CAST("HEART" AS BIGINT) AS heart,
    CAST("CIRCUL" AS BIGINT) AS circul,
    CAST("RECTAL" AS BIGINT) AS rectal,
    CAST("TRACHEO" AS BIGINT) AS tracheo,
    CAST("OMPHALO" AS BIGINT) AS omphalo,
    CAST("GASTRO" AS BIGINT) AS gastro,
    CAST("GENITAL" AS BIGINT) AS genital,
    CAST("RENALAGE" AS BIGINT) AS renalage,
    CAST("UROGEN" AS BIGINT) AS urogen,
    CAST("CLEFTLP" AS BIGINT) AS cleftlp,
    CAST("ADACTYLY" AS BIGINT) AS adactyly,
    CAST("CLUBFOOT" AS BIGINT) AS clubfoot,
    CAST("HERNIA" AS BIGINT) AS hernia,
    CAST("MUSCULO" AS BIGINT) AS musculo,
    CAST("DOWNS" AS BIGINT) AS downs,
    CAST("CHROMO" AS BIGINT) AS chromo,
    CAST("OTHERCON" AS BIGINT) AS othercon,
    CAST("ORIGM" AS BIGINT) AS origm,
    CAST("ORIGF" AS BIGINT) AS origf,
    CAST("EDUCM" AS BIGINT) AS educm,
    CAST("EDUCF" AS BIGINT) AS educf,
    CAST("GESTE" AS BIGINT) AS geste,
    CAST("R6A" AS BIGINT) AS r6a,
    CAST("FMAPSRF" AS BIGINT) AS fmapsrf,
    CAST("DELMETRF" AS BIGINT) AS delmetrf,
    CAST("MEDRSK" AS BIGINT) AS medrsk,
    CAST("TOBUSE" AS BIGINT) AS tobuse,
    CAST("ALCUSE" AS BIGINT) AS alcuse,
    CAST("WTGN" AS BIGINT) AS wtgn,
    CAST("OBSTRC" AS BIGINT) AS obstrc,
    CAST("CLABOR" AS BIGINT) AS clabor,
    CAST("ABNML" AS BIGINT) AS abnml,
    CAST("CONGAN" AS BIGINT) AS congan,
    CAST("R6b" AS BIGINT) AS r6b,
    CAST("EDUCSMSA" AS BIGINT) AS educsmsa,
    CAST("APIFLAG" AS BIGINT) AS apiflag,
    CAST("R7" AS BIGINT) AS r7,
    "SMSARES" AS smsares,
    "POPSMAS" AS popsmas
FROM "instituto-de-estad-sticas-de-puerto-rico-nacimientos"
