-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_resource",
    "source_file",
    CAST("seqno" AS BIGINT) AS seqno,
    CAST("@_state" AS BIGINT) AS state,
    CAST("@_geostr" AS BIGINT) AS geostr,
    CAST("@_denstr2" AS BIGINT) AS denstr2,
    CAST("precall" AS BIGINT) AS precall,
    CAST("secscrfl" AS BIGINT) AS secscrfl,
    CAST("repnum" AS BIGINT) AS repnum,
    CAST("repdepth" AS BIGINT) AS repdepth,
    CAST("fmonth" AS BIGINT) AS fmonth,
    CAST("idate" AS BIGINT) AS idate,
    CAST("imonth" AS BIGINT) AS imonth,
    CAST("iday" AS BIGINT) AS iday,
    CAST("iyear" AS BIGINT) AS iyear,
    CAST("intvid" AS BIGINT) AS intvid,
    CAST("dispcode" AS BIGINT) AS dispcode,
    CAST("@_psu" AS BIGINT) AS psu,
    CAST("nattmpts" AS BIGINT) AS nattmpts,
    CAST("nrecsel" AS BIGINT) AS nrecsel,
    CAST("nrecstr" AS DOUBLE) AS nrecstr,
    CAST("ctelenum" AS BIGINT) AS ctelenum,
    CAST("pvtresd1" AS BIGINT) AS pvtresd1,
    "colghous",
    CAST("stateres" AS BIGINT) AS stateres,
    CAST("cellfon3" AS BIGINT) AS cellfon3,
    "ladult",
    CAST("numadult" AS BIGINT) AS numadult,
    CAST("nummen" AS BIGINT) AS nummen,
    CAST("numwomen" AS BIGINT) AS numwomen,
    CAST("ctelnum1" AS BIGINT) AS ctelnum1,
    CAST("cellfon2" AS BIGINT) AS cellfon2,
    CAST("cadult" AS BIGINT) AS cadult,
    CAST("pvtresd2" AS BIGINT) AS pvtresd2,
    CAST("cclghous" AS BIGINT) AS cclghous,
    CAST("cstate" AS BIGINT) AS cstate,
    CAST("rspstate" AS BIGINT) AS rspstate,
    CAST("landline" AS BIGINT) AS landline,
    CAST("hhadult" AS BIGINT) AS hhadult,
    CAST("genhlth" AS BIGINT) AS genhlth,
    CAST("physhlth" AS BIGINT) AS physhlth,
    CAST("menthlth" AS BIGINT) AS menthlth,
    CAST("poorhlth" AS BIGINT) AS poorhlth,
    CAST("hlthpln1" AS BIGINT) AS hlthpln1,
    CAST("persdoc2" AS BIGINT) AS persdoc2,
    "medcost",
    CAST("checkup1" AS BIGINT) AS checkup1,
    "bphigh4",
    CAST("bpmeds" AS BIGINT) AS bpmeds,
    CAST("bloodcho" AS BIGINT) AS bloodcho,
    CAST("cholchk" AS BIGINT) AS cholchk,
    CAST("toldhi2" AS BIGINT) AS toldhi2,
    "cvdinfr4",
    "cvdcrhd4",
    "cvdstrk3",
    CAST("asthma3" AS BIGINT) AS asthma3,
    CAST("asthnow" AS BIGINT) AS asthnow,
    CAST("chcscncr" AS BIGINT) AS chcscncr,
    CAST("chcocncr" AS BIGINT) AS chcocncr,
    "chccopd1",
    CAST("havarth3" AS BIGINT) AS havarth3,
    "addepev2",
    "chckidny",
    "diabete3",
    CAST("diabage2" AS BIGINT) AS diabage2,
    "sex",
    CAST("age" AS BIGINT) AS age,
    CAST("hispanc3" AS BIGINT) AS hispanc3,
    CAST("mrace1" AS BIGINT) AS mrace1,
    CAST("orace3" AS BIGINT) AS orace3,
    "marital",
    CAST("educa" AS BIGINT) AS educa,
    "renthom1",
    CAST("ctycode1" AS BIGINT) AS ctycode1,
    CAST("zipcode" AS BIGINT) AS zipcode,
    CAST("numhhol2" AS BIGINT) AS numhhol2,
    CAST("numphon2" AS BIGINT) AS numphon2,
    CAST("cpdemo1" AS BIGINT) AS cpdemo1,
    CAST("veteran3" AS BIGINT) AS veteran3,
    "employ1",
    CAST("children" AS BIGINT) AS children,
    CAST("income2" AS BIGINT) AS income2,
    CAST("internet" AS BIGINT) AS internet,
    CAST("weight2" AS BIGINT) AS weight2,
    CAST("height3" AS BIGINT) AS height3,
    CAST("pregnant" AS BIGINT) AS pregnant,
    "qlactlm2",
    "useequip",
    CAST("blind" AS BIGINT) AS blind,
    CAST("decide" AS BIGINT) AS decide,
    "diffwalk",
    CAST("diffdres" AS BIGINT) AS diffdres,
    CAST("diffalon" AS BIGINT) AS diffalon,
    CAST("smoke100" AS BIGINT) AS smoke100,
    CAST("smokday2" AS BIGINT) AS smokday2,
    CAST("stopsmk2" AS BIGINT) AS stopsmk2,
    CAST("lastsmk2" AS BIGINT) AS lastsmk2,
    CAST("usenow3" AS BIGINT) AS usenow3,
    CAST("alcday5" AS BIGINT) AS alcday5,
    CAST("avedrnk2" AS BIGINT) AS avedrnk2,
    CAST("drnk3ge5" AS BIGINT) AS drnk3ge5,
    CAST("maxdrnks" AS BIGINT) AS maxdrnks,
    CAST("fruitju1" AS BIGINT) AS fruitju1,
    CAST("fruit1" AS BIGINT) AS fruit1,
    CAST("fvbeans" AS BIGINT) AS fvbeans,
    CAST("fvgreen" AS BIGINT) AS fvgreen,
    CAST("fvorang" AS BIGINT) AS fvorang,
    CAST("vegetab1" AS BIGINT) AS vegetab1,
    CAST("exerany2" AS BIGINT) AS exerany2,
    CAST("exract11" AS BIGINT) AS exract11,
    CAST("exeroft1" AS BIGINT) AS exeroft1,
    CAST("exerhmm1" AS BIGINT) AS exerhmm1,
    CAST("exract21" AS BIGINT) AS exract21,
    CAST("exeroft2" AS BIGINT) AS exeroft2,
    CAST("exerhmm2" AS BIGINT) AS exerhmm2,
    CAST("strength" AS BIGINT) AS strength,
    CAST("lmtjoin3" AS BIGINT) AS lmtjoin3,
    CAST("arthdis2" AS BIGINT) AS arthdis2,
    CAST("arthsocl" AS BIGINT) AS arthsocl,
    CAST("joinpain" AS BIGINT) AS joinpain,
    CAST("seatbelt" AS BIGINT) AS seatbelt,
    CAST("flushot6" AS BIGINT) AS flushot6,
    CAST("flshtmy2" AS BIGINT) AS flshtmy2,
    CAST("imfvplac" AS BIGINT) AS imfvplac,
    CAST("pneuvac3" AS BIGINT) AS pneuvac3,
    CAST("hivtst6" AS BIGINT) AS hivtst6,
    CAST("hivtstd3" AS BIGINT) AS hivtstd3,
    CAST("whrtst10" AS BIGINT) AS whrtst10,
    CAST("wtchsalt" AS BIGINT) AS wtchsalt,
    CAST("longwtch" AS BIGINT) AS longwtch,
    CAST("dradvise" AS BIGINT) AS dradvise,
    CAST("qstver" AS BIGINT) AS qstver,
    CAST("qstlang" AS BIGINT) AS qstlang,
    CAST("cati_rn" AS BIGINT) AS cati_rn,
    CAST("cati_rg" AS BIGINT) AS cati_rg,
    CAST("cati_sr" AS BIGINT) AS cati_sr,
    "cpcounty",
    "exactot1",
    "exactot2",
    CAST("@_region" AS BIGINT) AS region,
    CAST("@_impage" AS BIGINT) AS impage,
    CAST("@_imprace" AS BIGINT) AS imprace,
    CAST("@_impnph" AS BIGINT) AS impnph,
    CAST("@_impcty" AS BIGINT) AS impcty,
    CAST("@_impeduc" AS BIGINT) AS impeduc,
    CAST("@_impmrtl" AS BIGINT) AS impmrtl,
    CAST("@_imphome" AS BIGINT) AS imphome,
    CAST("o_state" AS BIGINT) AS o_state,
    CAST("orgseqno" AS BIGINT) AS orgseqno,
    CAST("@_dualuse" AS BIGINT) AS dualuse,
    "@_dualcor" AS dualcor,
    CAST("@_llcpm01" AS BIGINT) AS llcpm01,
    CAST("@_llcpm02" AS BIGINT) AS llcpm02,
    CAST("@_llcpm03" AS BIGINT) AS llcpm03,
    CAST("@_llcpm04" AS BIGINT) AS llcpm04,
    CAST("@_llcpm05" AS BIGINT) AS llcpm05,
    CAST("@_llcpm06" AS BIGINT) AS llcpm06,
    CAST("@_llcpm07" AS BIGINT) AS llcpm07,
    CAST("@_llcpm08" AS BIGINT) AS llcpm08,
    CAST("@_llcpm09" AS BIGINT) AS llcpm09,
    CAST("@_llcpm10" AS BIGINT) AS llcpm10,
    CAST("@_llcpm11" AS BIGINT) AS llcpm11,
    CAST("@_llcpm12" AS BIGINT) AS llcpm12,
    CAST("@_llcpm13" AS BIGINT) AS llcpm13,
    CAST("@_llcpm14" AS BIGINT) AS llcpm14,
    CAST("@_llcpm15" AS BIGINT) AS llcpm15,
    CAST("@_llcpm16" AS BIGINT) AS llcpm16,
    CAST("@_llcpwt" AS DOUBLE) AS llcpwt,
    "@_lcm01v1" AS lcm01v1,
    "@_lcm02v1" AS lcm02v1,
    "@_lcm03v1" AS lcm03v1,
    "@_lcm04v1" AS lcm04v1,
    "@_lcm05v1" AS lcm05v1,
    "@_lcm06v1" AS lcm06v1,
    "@_lcm07v1" AS lcm07v1,
    "@_lcm08v1" AS lcm08v1,
    "@_lcm09v1" AS lcm09v1,
    "@_lcm10v1" AS lcm10v1,
    "@_lcm11v1" AS lcm11v1,
    "@_lcm12v1" AS lcm12v1,
    "@_lcpwtv1" AS lcpwtv1,
    "@_lcm01v2" AS lcm01v2,
    "@_lcm02v2" AS lcm02v2,
    "@_lcm03v2" AS lcm03v2,
    "@_lcm04v2" AS lcm04v2,
    "@_lcm05v2" AS lcm05v2,
    "@_lcm06v2" AS lcm06v2,
    "@_lcm07v2" AS lcm07v2,
    "@_lcm08v2" AS lcm08v2,
    "@_lcm09v2" AS lcm09v2,
    "@_lcm10v2" AS lcm10v2,
    "@_lcm11v2" AS lcm11v2,
    "@_lcm12v2" AS lcm12v2,
    "@_lcpwtv2" AS lcpwtv2,
    "@_lcm01v3" AS lcm01v3,
    "@_lcm02v3" AS lcm02v3,
    "@_lcm03v3" AS lcm03v3,
    "@_lcm04v3" AS lcm04v3,
    "@_lcm05v3" AS lcm05v3,
    "@_lcm06v3" AS lcm06v3,
    "@_lcm07v3" AS lcm07v3,
    "@_lcm08v3" AS lcm08v3,
    "@_lcm09v3" AS lcm09v3,
    "@_lcm10v3" AS lcm10v3,
    "@_lcm11v3" AS lcm11v3,
    "@_lcm12v3" AS lcm12v3,
    "@_lcpwtv3" AS lcpwtv3,
    "@_rfhlth" AS rfhlth,
    CAST("@_hcvu651" AS BIGINT) AS hcvu651,
    "@_rfhype5" AS rfhype5,
    CAST("@_cholchk" AS BIGINT) AS cholchk_2,
    "@_rfchol" AS rfchol,
    "@_michd" AS michd,
    CAST("@_ltasth1" AS BIGINT) AS ltasth1,
    "@_casthm1" AS casthm1,
    CAST("@_asthms1" AS BIGINT) AS asthms1,
    "@_drdxar1" AS drdxar1,
    CAST("mracorg1" AS BIGINT) AS mracorg1,
    CAST("mracasc1" AS BIGINT) AS mracasc1,
    CAST("@_prace1" AS BIGINT) AS prace1,
    CAST("@_mrace1" AS BIGINT) AS mrace1_2,
    CAST("@_m_race" AS BIGINT) AS m_race,
    CAST("@_hispanc" AS BIGINT) AS hispanc,
    CAST("@_race" AS BIGINT) AS race,
    CAST("@_raceg21" AS BIGINT) AS raceg21,
    CAST("@_racegr3" AS BIGINT) AS racegr3,
    CAST("@_race_g1" AS BIGINT) AS race_g1,
    "@_ageg5yr" AS ageg5yr,
    CAST("@_age65yr" AS BIGINT) AS age65yr,
    CAST("@_age80" AS BIGINT) AS age80,
    "@_age_g" AS age_g,
    CAST("htin4" AS BIGINT) AS htin4,
    CAST("htm4" AS BIGINT) AS htm4,
    CAST("wtkg3" AS BIGINT) AS wtkg3,
    CAST("@_bmi5" AS BIGINT) AS bmi5,
    "@_bmi5cat" AS bmi5cat,
    "@_rfbmi5" AS rfbmi5,
    "@_chldcnt" AS chldcnt,
    "@_educag" AS educag,
    "@_incomg" AS incomg,
    "@_smoker3" AS smoker3,
    "@_rfsmok3" AS rfsmok3,
    CAST("drnkany5" AS BIGINT) AS drnkany5,
    CAST("drocdy3" AS BIGINT) AS drocdy3,
    "@_rfbing5" AS rfbing5,
    CAST("@_drnkwek" AS BIGINT) AS drnkwek,
    "@_rfdrhv5" AS rfdrhv5,
    CAST("ftjuda1" AS BIGINT) AS ftjuda1,
    CAST("frutda1" AS BIGINT) AS frutda1,
    CAST("beanday" AS BIGINT) AS beanday,
    CAST("grenday" AS BIGINT) AS grenday,
    CAST("orngday" AS BIGINT) AS orngday,
    CAST("vegeda1" AS BIGINT) AS vegeda1,
    CAST("@_misfrtn" AS BIGINT) AS misfrtn,
    CAST("@_misvegn" AS BIGINT) AS misvegn,
    CAST("@_frtresp" AS BIGINT) AS frtresp,
    CAST("@_vegresp" AS BIGINT) AS vegresp,
    CAST("@_frutsum" AS BIGINT) AS frutsum,
    CAST("@_vegesum" AS BIGINT) AS vegesum,
    "@_frtlt1" AS frtlt1,
    "@_veglt1" AS veglt1,
    CAST("@_frt16" AS BIGINT) AS frt16,
    CAST("@_veg23" AS BIGINT) AS veg23,
    CAST("@_fruitex" AS BIGINT) AS fruitex,
    CAST("@_vegetex" AS BIGINT) AS vegetex,
    CAST("@_totinda" AS BIGINT) AS totinda,
    CAST("metvl11" AS BIGINT) AS metvl11,
    CAST("metvl21" AS BIGINT) AS metvl21,
    CAST("maxvo2" AS BIGINT) AS maxvo2,
    CAST("fc60" AS BIGINT) AS fc60,
    CAST("actin11" AS BIGINT) AS actin11,
    CAST("actin21" AS BIGINT) AS actin21,
    CAST("padur1" AS BIGINT) AS padur1,
    CAST("padur2" AS BIGINT) AS padur2,
    CAST("pafreq1" AS BIGINT) AS pafreq1,
    CAST("pafreq2" AS BIGINT) AS pafreq2,
    CAST("@_minac11" AS BIGINT) AS minac11,
    CAST("@_minac21" AS BIGINT) AS minac21,
    CAST("strfreq" AS BIGINT) AS strfreq,
    CAST("pamiss1" AS BIGINT) AS pamiss1,
    CAST("pamin11" AS BIGINT) AS pamin11,
    CAST("pamin21" AS BIGINT) AS pamin21,
    CAST("pa1min" AS BIGINT) AS pa1min,
    CAST("pavig11" AS BIGINT) AS pavig11,
    CAST("pavig21" AS BIGINT) AS pavig21,
    CAST("pa1vigm" AS BIGINT) AS pa1vigm,
    CAST("@_pacat1" AS BIGINT) AS pacat1,
    CAST("@_paindx1" AS BIGINT) AS paindx1,
    CAST("@_pa150r2" AS BIGINT) AS pa150r2,
    CAST("@_pa300r2" AS BIGINT) AS pa300r2,
    CAST("@_pa30021" AS BIGINT) AS pa30021,
    CAST("@_pastrng" AS BIGINT) AS pastrng,
    CAST("@_parec1" AS BIGINT) AS parec1,
    CAST("@_pastae1" AS BIGINT) AS pastae1,
    CAST("@_lmtact1" AS BIGINT) AS lmtact1,
    CAST("@_lmtwrk1" AS BIGINT) AS lmtwrk1,
    CAST("@_lmtscl1" AS BIGINT) AS lmtscl1,
    CAST("@_rfseat2" AS BIGINT) AS rfseat2,
    CAST("@_rfseat3" AS BIGINT) AS rfseat3,
    CAST("@_flshot6" AS BIGINT) AS flshot6,
    CAST("@_pneumo2" AS BIGINT) AS pneumo2,
    CAST("@_aidtst3" AS BIGINT) AS aidtst3,
    CAST("seqno_A" AS BIGINT) AS seqno_a,
    CAST("@_ststr" AS BIGINT) AS ststr,
    "sa1",
    "sa2",
    "sa3",
    "sa4",
    "sa5",
    "sa6",
    "sa7",
    "sa8",
    CAST("ponderacion" AS DOUBLE) AS ponderacion,
    CAST("ponderacion1" AS DOUBLE) AS ponderacion1,
    CAST("ponderacion2" AS DOUBLE) AS ponderacion2,
    CAST("ponderacion3" AS DOUBLE) AS ponderacion3,
    "r@_ageg5yr" AS r_ageg5yr,
    "remploy1",
    CAST("rchildren" AS BIGINT) AS rchildren,
    "consumofru",
    "frutaxdia",
    "consumoveg",
    "vegexdia",
    CAST("r@_bmi5" AS DOUBLE) AS r_bmi5,
    CAST("ctycode2" AS BIGINT) AS ctycode2,
    CAST("ctycode3" AS BIGINT) AS ctycode3,
    CAST("ctycode4" AS BIGINT) AS ctycode4,
    CAST("ctycode5" AS BIGINT) AS ctycode5,
    CAST("ctycode6" AS BIGINT) AS ctycode6,
    CAST("ctycode7" AS BIGINT) AS ctycode7,
    CAST("ctycode8" AS BIGINT) AS ctycode8,
    CAST("ctycode9" AS BIGINT) AS ctycode9,
    CAST("ctycode10" AS BIGINT) AS ctycode10,
    CAST("ctycode11" AS BIGINT) AS ctycode11,
    CAST("ctycode12" AS BIGINT) AS ctycode12,
    CAST("ctycode13" AS BIGINT) AS ctycode13,
    CAST("ctycode14" AS BIGINT) AS ctycode14,
    CAST("ctycode15" AS BIGINT) AS ctycode15,
    CAST("ctycode16" AS BIGINT) AS ctycode16,
    CAST("ctycode17" AS BIGINT) AS ctycode17,
    CAST("ctycode18" AS BIGINT) AS ctycode18,
    CAST("ctycode19" AS BIGINT) AS ctycode19,
    CAST("ctycode20" AS BIGINT) AS ctycode20,
    CAST("ctycode21" AS BIGINT) AS ctycode21,
    CAST("ctycode22" AS BIGINT) AS ctycode22,
    CAST("ctycode23" AS BIGINT) AS ctycode23,
    CAST("ctycode24" AS BIGINT) AS ctycode24,
    CAST("ctycode25" AS BIGINT) AS ctycode25,
    CAST("ctycode26" AS BIGINT) AS ctycode26,
    CAST("ctycode27" AS BIGINT) AS ctycode27,
    CAST("ctycode28" AS BIGINT) AS ctycode28,
    CAST("ctycode29" AS BIGINT) AS ctycode29,
    CAST("ctycode30" AS BIGINT) AS ctycode30,
    CAST("ctycode31" AS BIGINT) AS ctycode31,
    CAST("ctycode32" AS BIGINT) AS ctycode32,
    CAST("ctycode33" AS BIGINT) AS ctycode33,
    CAST("ctycode34" AS BIGINT) AS ctycode34,
    CAST("ctycode35" AS BIGINT) AS ctycode35,
    CAST("ctycode36" AS BIGINT) AS ctycode36,
    CAST("ctycode37" AS BIGINT) AS ctycode37,
    CAST("ctycode38" AS BIGINT) AS ctycode38,
    CAST("ctycode39" AS BIGINT) AS ctycode39,
    CAST("ctycode40" AS BIGINT) AS ctycode40,
    CAST("ctycode41" AS BIGINT) AS ctycode41,
    CAST("ctycode42" AS BIGINT) AS ctycode42,
    CAST("ctycode43" AS BIGINT) AS ctycode43,
    CAST("ctycode44" AS BIGINT) AS ctycode44,
    CAST("ctycode45" AS BIGINT) AS ctycode45,
    CAST("ctycode46" AS BIGINT) AS ctycode46,
    CAST("ctycode47" AS BIGINT) AS ctycode47,
    CAST("ctycode48" AS BIGINT) AS ctycode48,
    CAST("ctycode49" AS BIGINT) AS ctycode49,
    "rfrutaxdia",
    "rvegexdia",
    "rsa1",
    "rsa2",
    "rsa3",
    "rsa5",
    "rsa6",
    CAST("fss" AS BIGINT) AS fss,
    "fssindex",
    CAST("PHYSR" AS BIGINT) AS physr,
    CAST("MENTR" AS BIGINT) AS mentr,
    CAST("PORHLTHR" AS BIGINT) AS porhlthr,
    CAST("SUMDAYS" AS BIGINT) AS sumdays,
    CAST("UNHLTH" AS BIGINT) AS unhlth,
    "MENTDIST" AS mentdist,
    CAST("hlthy" AS BIGINT) AS hlthy,
    "rPHYSR" AS rphysr,
    "rPORHLTHR" AS rporhlthr,
    "filter_$" AS filter,
    "rfssindex",
    "Region6" AS region6,
    CAST("bmi" AS DOUBLE) AS bmi,
    "CVDall" AS cvdall,
    "CVDINFCor" AS cvdinfcor,
    "GRUPOS_EDAD" AS grupos_edad,
    "APRESION" AS apresion,
    "INGRESO" AS ingreso,
    "DIABETEYN" AS diabeteyn,
    "GRUP_EDAD" AS grup_edad,
    "INGRESO_2CAT" AS ingreso_2cat,
    "G_EDAD_2CAT" AS g_edad_2cat,
    "Educa_2cat" AS educa_2cat,
    "RENTHOM1_2cat" AS renthom1_2cat
FROM "instituto-de-estad-sticas-de-puerto-rico-encuesta-seguridad-alimentaria-2015"
