-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_resource",
    "source_file",
    "V_PCS_PERMIT_FACILITIES.NPDES" AS v_pcs_permit_facilities_npdes,
    "V_PCS_PERMIT_FACILITIES.INACTIVE_CODE" AS v_pcs_permit_facilities_inactive_code,
    strptime("V_PCS_PERMIT_FACILITIES.INACTIVE_DATE", '%Y-%m-%d')::DATE AS v_pcs_permit_facilities_inactive_date,
    "V_PCS_PERMIT_FACILITIES.LATITUDE" AS v_pcs_permit_facilities_latitude,
    "V_PCS_PERMIT_FACILITIES.LONGITUDE" AS v_pcs_permit_facilities_longitude,
    "V_PCS_PERMIT_FACILITIES.LOC_STREET_1" AS v_pcs_permit_facilities_loc_street_1,
    "V_PCS_PERMIT_FACILITIES.LOC_STREET_2" AS v_pcs_permit_facilities_loc_street_2,
    "V_PCS_PERMIT_FACILITIES.LOC_CITY" AS v_pcs_permit_facilities_loc_city,
    "V_PCS_PERMIT_FACILITIES.LOC_STATE" AS v_pcs_permit_facilities_loc_state,
    strptime("V_PCS_PERMIT_FACILITIES.PERMIT_EXPIRED_DATE", '%Y-%m-%d')::DATE AS v_pcs_permit_facilities_permit_expired_date,
    strptime("V_PCS_PERMIT_FACILITIES.PERMIT_ISSUED_DATE", '%Y-%m-%d')::DATE AS v_pcs_permit_facilities_permit_issued_date,
    "V_PCS_PERMIT_FACILITIES.TYPE_OF_PERMIT_ISSUED" AS v_pcs_permit_facilities_type_of_permit_issued,
    "Code Expansion for Type of Permit Issued" AS code_expansion_for_type_of_permit_issued,
    "V_PCS_PERMIT_FACILITIES.FLOW_RATE" AS v_pcs_permit_facilities_flow_rate,
    "V_PCS_PERMIT_FACILITIES.INDUSTRY_CLASS" AS v_pcs_permit_facilities_industry_class,
    "Code Expansion for Industrial Classification" AS code_expansion_for_industrial_classification,
    "V_PCS_PERMIT_FACILITIES.MAJOR_DISCHARGE_INDICATOR" AS v_pcs_permit_facilities_major_discharge_indicator,
    "V_PCS_PERMIT_FACILITIES.MILEAGE_IND" AS v_pcs_permit_facilities_mileage_ind,
    "V_PCS_PERMIT_FACILITIES.RECEIVING_WATERS" AS v_pcs_permit_facilities_receiving_waters,
    "V_PCS_PERMIT_FACILITIES.RECVNG_STREAM_CLASS_CODE" AS v_pcs_permit_facilities_recvng_stream_class_code,
    "Code Expansion for Receiving Stream Classification Code" AS code_expansion_for_receiving_stream_classification_code,
    CAST("V_PCS_PERMIT_FACILITIES.RIVER_BASIN" AS BIGINT) AS v_pcs_permit_facilities_river_basin,
    "Code Expansion for River Basin" AS code_expansion_for_river_basin,
    "V_PCS_PERMIT_FACILITIES.STREAM_SEGMENT" AS v_pcs_permit_facilities_stream_segment,
    "V_PCS_PERMIT_FACILITIES.TYPE_OF_OWNERSHIP" AS v_pcs_permit_facilities_type_of_ownership,
    "Code Expansion for Type of Ownership" AS code_expansion_for_type_of_ownership,
    CAST("V_PCS_PERMIT_FACILITIES.USGS_HYDRO_BASIN_CODE" AS BIGINT) AS v_pcs_permit_facilities_usgs_hydro_basin_code,
    "Code Expansion for USGS Water Basin Code" AS code_expansion_for_usgs_water_basin_code,
    "PCS_EFFL_LIM_CONCENTR.CONC_AVG_LIMIT" AS pcs_effl_lim_concentr_conc_avg_limit,
    "PCS_EFFL_LIM_CONCENTR.CONC_MAX_LIMIT" AS pcs_effl_lim_concentr_conc_max_limit,
    "PCS_EFFL_LIM_CONCENTR.CONC_UNIT_CODE" AS pcs_effl_lim_concentr_conc_unit_code,
    "Code Expansion for Unit Code for Concentration" AS code_expansion_for_unit_code_for_concentration,
    "PCS_EFFL_LIM_QTY.QTY_AVG_LIMIT" AS pcs_effl_lim_qty_qty_avg_limit,
    "PCS_EFFL_LIM_QTY.QTY_MAX_LIMIT" AS pcs_effl_lim_qty_qty_max_limit,
    "PCS_EFFL_LIM_QTY.QTY_UNIT_CODE" AS pcs_effl_lim_qty_qty_unit_code,
    "PCS_DMR_MEASUREMENT.CONCENTR_AVG" AS pcs_dmr_measurement_concentr_avg,
    "PCS_DMR_MEASUREMENT.CONCENTR_MAX" AS pcs_dmr_measurement_concentr_max,
    "PCS_DMR_MEASUREMENT.CONCENTR_MIN" AS pcs_dmr_measurement_concentr_min,
    "PCS_DMR_MEASUREMENT.QTY_AVG" AS pcs_dmr_measurement_qty_avg,
    "PCS_DMR_MEASUREMENT.QTY_MAX" AS pcs_dmr_measurement_qty_max,
    "PCS_DMR_MEASUREMENT.QUANTITY_UNIT_CODE" AS pcs_dmr_measurement_quantity_unit_code,
    "Code Expansion for Quantity Unit Code" AS code_expansion_for_quantity_unit_code
FROM "instituto-de-estad-sticas-de-puerto-rico-pcs-icis"
