-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_resource",
    "source_file",
    CAST("As of Year" AS BIGINT) AS as_of_year,
    CAST("Respondent ID" AS BIGINT) AS respondent_id,
    CAST("Agency Code" AS BIGINT) AS agency_code,
    CAST("Loan Type" AS BIGINT) AS loan_type,
    CAST("Property Type" AS BIGINT) AS property_type,
    CAST("Loan Purpose" AS BIGINT) AS loan_purpose,
    CAST("Occupancy" AS BIGINT) AS occupancy,
    CAST("Loan Amount (000s)" AS BIGINT) AS loan_amount_000s,
    "Preapproval" AS preapproval,
    CAST("Action Type" AS BIGINT) AS action_type,
    CAST("MSA/MD" AS BIGINT) AS msa_md,
    CAST("State Code" AS BIGINT) AS state_code,
    CAST("County Code" AS BIGINT) AS county_code,
    "Census Tract Number" AS census_tract_number,
    CAST("Applicant Ethnicity" AS BIGINT) AS applicant_ethnicity,
    CAST("Co Applicant Ethnicity" AS BIGINT) AS co_applicant_ethnicity,
    CAST("Applicant Race 1" AS BIGINT) AS applicant_race_1,
    CAST("Applicant Race 2" AS BIGINT) AS applicant_race_2,
    "Applicant Race 3" AS applicant_race_3,
    "Applicant Race 4" AS applicant_race_4,
    "Applicant Race 5" AS applicant_race_5,
    CAST("Co Applicant Race 1" AS BIGINT) AS co_applicant_race_1,
    CAST("Co Applicant Race 2" AS BIGINT) AS co_applicant_race_2,
    "Co Applicant Race 3" AS co_applicant_race_3,
    "Co Applicant Race 4" AS co_applicant_race_4,
    "Co Applicant Race 5" AS co_applicant_race_5,
    CAST("Applicant Sex" AS BIGINT) AS applicant_sex,
    CAST("Co Applicant Sex" AS BIGINT) AS co_applicant_sex,
    "Applicant Income (000s)" AS applicant_income_000s,
    CAST("Purchaser Type" AS BIGINT) AS purchaser_type,
    CAST("Denial Reason 1" AS BIGINT) AS denial_reason_1,
    CAST("Denial Reason 2" AS BIGINT) AS denial_reason_2,
    CAST("Denial Reason 3" AS BIGINT) AS denial_reason_3,
    "Rate Spread" AS rate_spread,
    "HOEPA Status" AS hoepa_status,
    CAST("Lien Status" AS BIGINT) AS lien_status,
    CAST("Edit Status" AS BIGINT) AS edit_status,
    CAST("Sequence Number" AS BIGINT) AS sequence_number,
    "Population" AS population,
    "Minority Population %" AS minority_population,
    "HUD Median Family Income" AS hud_median_family_income,
    "Tract to MSA/MD Income %" AS tract_to_msa_md_income,
    "Number of Owner occupied units" AS number_of_owner_occupied_units,
    "Number of 1-to4-Family units" AS number_of_1_to4_family_units,
    CAST("Application Date Prior 2004 Flag" AS BIGINT) AS application_date_prior_2004_flag
FROM "instituto-de-estad-sticas-de-puerto-rico-seguros-de-hipotecas"
