-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_resource",
    "source_file",
    "R0" AS r0,
    CAST("BIRYR" AS BIGINT) AS biryr,
    CAST("RESSTATB" AS BIGINT) AS resstatb,
    CAST("BRSTATE" AS BIGINT) AS brstate,
    CAST("STOCCFIPB" AS BIGINT) AS stoccfipb,
    CAST("CNTOCFIPB" AS BIGINT) AS cntocfipb,
    "STRESFIPB" AS stresfipb,
    "CNTYRFPB" AS cntyrfpb,
    "PLRES" AS plres,
    CAST("MAGEFLG" AS BIGINT) AS mageflg,
    CAST("DMAGE" AS BIGINT) AS dmage,
    CAST("MAGER8" AS BIGINT) AS mager8,
    CAST("ORMOTH" AS BIGINT) AS ormoth,
    CAST("ORRACEM" AS BIGINT) AS orracem,
    CAST("MRACEIMP" AS BIGINT) AS mraceimp,
    "MRACE" AS mrace,
    CAST("MRACE3" AS BIGINT) AS mrace3,
    "DMEDUC" AS dmeduc,
    CAST("MEDUC6" AS BIGINT) AS meduc6,
    CAST("DMARIMP" AS BIGINT) AS dmarimp,
    CAST("DMAR" AS BIGINT) AS dmar,
    "MPLBIR" AS mplbir,
    CAST("MPLBIRR" AS BIGINT) AS mplbirr,
    "DTOTORD" AS dtotord,
    "DLIVORD" AS dlivord,
    "MONPRE" AS monpre,
    CAST("MPRE5" AS BIGINT) AS mpre5,
    "NPREVIST" AS nprevist,
    CAST("ADEQUACY" AS BIGINT) AS adequacy,
    "R1" AS r1,
    CAST("FAGERFLG" AS BIGINT) AS fagerflg,
    CAST("DFAGE" AS BIGINT) AS dfage,
    CAST("ORFATH" AS BIGINT) AS orfath,
    CAST("ORRACEF" AS BIGINT) AS orracef,
    "FRACE" AS frace,
    CAST("PLDEL" AS BIGINT) AS pldel,
    CAST("BIRATTND" AS BIGINT) AS birattnd,
    CAST("R2" AS BIGINT) AS r2,
    CAST("GESTESTM" AS BIGINT) AS gestestm,
    CAST("CLINGEST" AS BIGINT) AS clingest,
    CAST("GESTIMP" AS BIGINT) AS gestimp,
    CAST("GESTAT" AS BIGINT) AS gestat,
    "GESTAT10" AS gestat10,
    "CSEXIMP" AS cseximp,
    CAST("CSEX" AS BIGINT) AS csex,
    CAST("BWIF" AS BIGINT) AS bwif,
    "DBIRWT" AS dbirwt,
    "BIRWT12" AS birwt12,
    CAST("BIRWT4" AS BIGINT) AS birwt4,
    "PLURIMP" AS plurimp,
    CAST("DPLURAL" AS BIGINT) AS dplural,
    "FMAPS" AS fmaps,
    CAST("VAGINAL" AS BIGINT) AS vaginal,
    CAST("VBAC" AS BIGINT) AS vbac,
    CAST("PRIMAC" AS BIGINT) AS primac,
    CAST("REPEAC" AS BIGINT) AS repeac,
    CAST("FORCEP" AS BIGINT) AS forcep,
    CAST("VACUUM" AS BIGINT) AS vacuum,
    "R3" AS r3,
    CAST("DELMETH5" AS BIGINT) AS delmeth5,
    CAST("MRFLAG" AS BIGINT) AS mrflag,
    CAST("ANEMIA" AS BIGINT) AS anemia,
    CAST("CARDIAC" AS BIGINT) AS cardiac,
    CAST("LUNG" AS BIGINT) AS lung,
    CAST("DIABETES" AS BIGINT) AS diabetes,
    CAST("HERPES" AS BIGINT) AS herpes,
    CAST("HYDRA" AS BIGINT) AS hydra,
    CAST("HEMO" AS BIGINT) AS hemo,
    CAST("CHYPER" AS BIGINT) AS chyper,
    CAST("PHYPER" AS BIGINT) AS phyper,
    CAST("ECLAMP" AS BIGINT) AS eclamp,
    CAST("INCERVIX" AS BIGINT) AS incervix,
    CAST("PRE4000" AS BIGINT) AS pre4000,
    CAST("PRETERM" AS BIGINT) AS preterm,
    CAST("RENAL" AS BIGINT) AS renal,
    CAST("RH" AS BIGINT) AS rh,
    CAST("UTERINE" AS BIGINT) AS uterine,
    CAST("OTHERMR" AS BIGINT) AS othermr,
    CAST("TOBACCO" AS BIGINT) AS tobacco,
    "CIGAR" AS cigar,
    CAST("CIGAR6" AS BIGINT) AS cigar6,
    CAST("ALCOHOL" AS BIGINT) AS alcohol,
    "DRINK" AS drink,
    CAST("DRINK5" AS BIGINT) AS drink5,
    "WTGAIN" AS wtgain,
    CAST("WTGAIN9" AS BIGINT) AS wtgain9,
    CAST("OBFLAG" AS BIGINT) AS obflag,
    CAST("AMNIO" AS BIGINT) AS amnio,
    CAST("MONITOR" AS BIGINT) AS monitor,
    CAST("INDUCT" AS BIGINT) AS induct,
    CAST("STIMULA" AS BIGINT) AS stimula,
    CAST("TOCOL" AS BIGINT) AS tocol,
    CAST("ULTRAS" AS BIGINT) AS ultras,
    CAST("OTHEROB" AS BIGINT) AS otherob,
    CAST("FBFLAG" AS BIGINT) AS fbflag,
    CAST("FEBRILE" AS BIGINT) AS febrile,
    CAST("MECONIUM" AS BIGINT) AS meconium,
    CAST("RUPTURE" AS BIGINT) AS rupture,
    CAST("ABRUPTIO" AS BIGINT) AS abruptio,
    CAST("PREPLACE" AS BIGINT) AS preplace,
    CAST("EXCEBLD" AS BIGINT) AS excebld,
    CAST("SEIZURE" AS BIGINT) AS seizure,
    CAST("PRECIP" AS BIGINT) AS precip,
    CAST("PROLONG" AS BIGINT) AS prolong,
    CAST("DYSFUNC" AS BIGINT) AS dysfunc,
    CAST("BREECH" AS BIGINT) AS breech,
    CAST("CEPHALO" AS BIGINT) AS cephalo,
    CAST("CORD" AS BIGINT) AS cord,
    CAST("ANESTHE" AS BIGINT) AS anesthe,
    CAST("DISTRESS" AS BIGINT) AS distress,
    CAST("OTHERLB" AS BIGINT) AS otherlb,
    CAST("NBFLAG" AS BIGINT) AS nbflag,
    CAST("NANEMIA" AS BIGINT) AS nanemia,
    CAST("INJURY" AS BIGINT) AS injury,
    CAST("ALCOSYN" AS BIGINT) AS alcosyn,
    CAST("HYALINE" AS BIGINT) AS hyaline,
    CAST("MECONSYN" AS BIGINT) AS meconsyn,
    CAST("VENL30" AS BIGINT) AS venl30,
    CAST("VEN30M" AS BIGINT) AS ven30m,
    CAST("NSEIZ" AS BIGINT) AS nseiz,
    CAST("OTHERAB" AS BIGINT) AS otherab,
    CAST("CGFLAG" AS BIGINT) AS cgflag,
    CAST("ANEN" AS BIGINT) AS anen,
    CAST("SPINA" AS BIGINT) AS spina,
    CAST("HYDRO" AS BIGINT) AS hydro,
    CAST("MICROCE" AS BIGINT) AS microce,
    CAST("NERVOUS" AS BIGINT) AS nervous,
    CAST("HEART" AS BIGINT) AS heart,
    CAST("CIRCUL" AS BIGINT) AS circul,
    CAST("RECTAL" AS BIGINT) AS rectal,
    CAST("TRACHEO" AS BIGINT) AS tracheo,
    CAST("OMPHALO" AS BIGINT) AS omphalo,
    CAST("GASTRO" AS BIGINT) AS gastro,
    CAST("GENITAL" AS BIGINT) AS genital,
    CAST("RENALAGE" AS BIGINT) AS renalage,
    CAST("UROGEN" AS BIGINT) AS urogen,
    CAST("CLEFTLP" AS BIGINT) AS cleftlp,
    CAST("ADACTYLY" AS BIGINT) AS adactyly,
    CAST("CLUBFOOT" AS BIGINT) AS clubfoot,
    CAST("HERNIA" AS BIGINT) AS hernia,
    CAST("MUSCULO" AS BIGINT) AS musculo,
    CAST("DOWNS" AS BIGINT) AS downs,
    CAST("CHROMO" AS BIGINT) AS chromo,
    CAST("OTHERCON" AS BIGINT) AS othercon,
    CAST("ORIGM" AS BIGINT) AS origm,
    CAST("ORIGF" AS BIGINT) AS origf,
    CAST("EDUCM" AS BIGINT) AS educm,
    "R4" AS r4,
    CAST("GESTE" AS BIGINT) AS geste,
    "R5" AS r5,
    CAST("FMAPSRF" AS BIGINT) AS fmapsrf,
    CAST("DELMETRF" AS BIGINT) AS delmetrf,
    CAST("MEDRSK" AS BIGINT) AS medrsk,
    CAST("TOBUSE" AS BIGINT) AS tobuse,
    CAST("ALCUSE" AS BIGINT) AS alcuse,
    CAST("WTGN" AS BIGINT) AS wtgn,
    CAST("OBSTRC" AS BIGINT) AS obstrc,
    CAST("CLABOR" AS BIGINT) AS clabor,
    CAST("ABNML" AS BIGINT) AS abnml,
    CAST("CONGAN" AS BIGINT) AS congan,
    CAST("API_FLAG" AS BIGINT) AS api_flag,
    "CDOBMIMP" AS cdobmimp,
    "BIRMON" AS birmon,
    "R6" AS r6,
    CAST("WEEKDAYB" AS BIGINT) AS weekdayb,
    "FLGND" AS flgnd,
    "AGED" AS aged,
    CAST("AGER5" AS BIGINT) AS ager5,
    CAST("ACCIDPL" AS BIGINT) AS accidpl,
    "UCOD" AS ucod,
    "UCODR130" AS ucodr130,
    CAST("RECWT" AS DOUBLE) AS recwt,
    "Reserved_Positions" AS reserved_positions,
    "EANUM" AS eanum,
    "ENTITY1" AS entity1,
    "ENTITY2" AS entity2,
    "ENTITY3" AS entity3,
    "ENTITY4" AS entity4,
    "ENTITY5" AS entity5,
    "ENTITY6" AS entity6,
    "ENTITY7" AS entity7,
    "ENTITY8" AS entity8,
    "ENTITY9" AS entity9,
    "ENTITY10" AS entity10,
    "ENTITY11" AS entity11,
    CAST("ENTITY12" AS BIGINT) AS entity12,
    "ENTITY13" AS entity13,
    "ENTITY14" AS entity14,
    "ENTITY15" AS entity15,
    "ENTITY16" AS entity16,
    "ENTITY17" AS entity17,
    "ENTITY18" AS entity18,
    "ENTITY19" AS entity19,
    "ENTITY20" AS entity20,
    "RANUM" AS ranum,
    "RECORD1" AS record1,
    "RECORD2" AS record2,
    "RECORD3" AS record3,
    "RECORD4" AS record4,
    "RECORD5" AS record5,
    "RECORD6" AS record6,
    "RECORD7" AS record7,
    "RECORD8" AS record8,
    "RECORD9" AS record9,
    "RECORD10" AS record10,
    CAST("RECORD11" AS BIGINT) AS record11,
    "RECORD12" AS record12,
    "RECORD13" AS record13,
    "RECORD14" AS record14,
    "RECORD15" AS record15,
    "RECORD16" AS record16,
    "RECORD17" AS record17,
    "RECORD18" AS record18,
    "RECORD19" AS record19,
    "RECORD20" AS record20,
    CAST("RESSTATD" AS BIGINT) AS resstatd,
    CAST("DRSTATE" AS BIGINT) AS drstate,
    CAST("STOCCFIPD" AS BIGINT) AS stoccfipd,
    CAST("CNTOCFIPD" AS BIGINT) AS cntocfipd,
    "STRESFIPD" AS stresfipd,
    "CNTYRFPD" AS cntyrfpd,
    "PLRESb" AS plresb,
    CAST("HOSPD" AS BIGINT) AS hospd,
    CAST("DTHYR" AS BIGINT) AS dthyr,
    "DTHMON" AS dthmon,
    "R9" AS r9,
    CAST("WEEKDAYD" AS BIGINT) AS weekdayd,
    "R10" AS r10
FROM "instituto-de-estad-sticas-de-puerto-rico-mortalidad-infantil-periodo"
