-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_resource",
    "source_file",
    CAST("YEAR" AS BIGINT) AS year,
    "TRI_FACILITY_ID" AS tri_facility_id,
    CAST("FRS_ID" AS BIGINT) AS frs_id,
    "FACILITY_NAME" AS facility_name,
    "STREET_ADDRESS" AS street_address,
    "CITY" AS city,
    "COUNTY" AS county,
    "ST" AS st,
    "ZIP" AS zip,
    "BIA_CODE" AS bia_code,
    "TRIBE" AS tribe,
    CAST("LATITUDE" AS DOUBLE) AS latitude,
    CAST("LONGITUDE" AS DOUBLE) AS longitude,
    "FEDERAL_FACILITY" AS federal_facility,
    CAST("INDUSTRY_SECTOR_CODE" AS BIGINT) AS industry_sector_code,
    "INDUSTRY_SECTOR" AS industry_sector,
    "PRIMARY_SIC" AS primary_sic,
    "SIC_2" AS sic_2,
    "SIC_3" AS sic_3,
    "SIC_4" AS sic_4,
    "SIC_5" AS sic_5,
    "SIC_6" AS sic_6,
    CAST("PRIMARY_NAICS" AS BIGINT) AS primary_naics,
    CAST("NAICS_2" AS BIGINT) AS naics_2,
    CAST("NAICS_3" AS BIGINT) AS naics_3,
    "NAICS_4" AS naics_4,
    "NAICS_5" AS naics_5,
    "NAICS_6" AS naics_6,
    CAST("DOC_CTRL_NUM" AS BIGINT) AS doc_ctrl_num,
    "CHEMICAL" AS chemical,
    "CAS_#/COMPOUND_ID" AS cas_compound_id,
    CAST("SRS_ID" AS BIGINT) AS srs_id,
    "CLEAR_AIR_ACT_CHEMICAL" AS clear_air_act_chemical,
    "CLASSIFICATION" AS classification,
    "METAL" AS metal,
    CAST("METAL_CATEGORY" AS BIGINT) AS metal_category,
    "CARCINOGEN" AS carcinogen,
    "FORM_TYPE" AS form_type,
    "UNIT_OF_MEASURE" AS unit_of_measure,
    CAST("5.1_FUGITIVE_AIR" AS BIGINT) AS 5_1_fugitive_air,
    CAST("5.2_STACK_AIR" AS BIGINT) AS 5_2_stack_air,
    CAST("5.3_WATER" AS BIGINT) AS 5_3_water,
    CAST("5.4_UNDERGROUND" AS BIGINT) AS 5_4_underground,
    CAST("5.4.1_UNDERGROUND_CLASS_I" AS BIGINT) AS 5_4_1_underground_class_i,
    "5.4.2_UNDERGROUND_CLASS_II-V" AS 5_4_2_underground_class_ii_v,
    CAST("5.5.1_LANDFILLS" AS BIGINT) AS 5_5_1_landfills,
    CAST("5.5.1A_RCRA_C_LANDFILLS" AS DOUBLE) AS 5_5_1a_rcra_c_landfills,
    CAST("5.5.1B_OTHER_LANDFILLS" AS BIGINT) AS 5_5_1b_other_landfills,
    CAST("5.5.2_LAND_TREATMENT" AS BIGINT) AS 5_5_2_land_treatment,
    CAST("5.5.3_SURFACE_IMPOUNDMENT" AS BIGINT) AS 5_5_3_surface_impoundment,
    CAST("5.5.3A_RCRA_C_SURFACE_IMP." AS BIGINT) AS 5_5_3a_rcra_c_surface_imp,
    CAST("5.5.3B_Other_SURFACE_IMP." AS BIGINT) AS 5_5_3b_other_surface_imp,
    CAST("5.5.4_OTHER_DISPOSAL" AS BIGINT) AS 5_5_4_other_disposal,
    CAST("ON-SITE_RELEASE_TOTAL" AS BIGINT) AS on_site_release_total,
    CAST("6.1_POTW-TRANSFERS_FOR_RELEASE" AS BIGINT) AS 6_1_potw_transfers_for_release,
    CAST("6.1_POTW-TRANSFERS_FOR_TREATM." AS BIGINT) AS 6_1_potw_transfers_for_treatm,
    CAST("6.1_POTW-TOTAL_TRANSFERS" AS BIGINT) AS 6_1_potw_total_transfers,
    CAST("6.2_M10" AS DOUBLE) AS 6_2_m10,
    CAST("6.2_M41" AS BIGINT) AS 6_2_m41,
    "6.2_M62" AS 6_2_m62,
    CAST("6.2_M71" AS DOUBLE) AS 6_2_m71,
    CAST("6.2_M81" AS BIGINT) AS 6_2_m81,
    CAST("6.2_M82" AS DOUBLE) AS 6_2_m82,
    CAST("6.2_M72" AS BIGINT) AS 6_2_m72,
    CAST("6.2_M63" AS BIGINT) AS 6_2_m63,
    CAST("6.2_M66" AS BIGINT) AS 6_2_m66,
    "6.2_M67" AS 6_2_m67,
    CAST("6.2_M64" AS BIGINT) AS 6_2_m64,
    "6.2_M65" AS 6_2_m65,
    "6.2_M73" AS 6_2_m73,
    CAST("6.2_M79" AS BIGINT) AS 6_2_m79,
    CAST("6.2_M90" AS DOUBLE) AS 6_2_m90,
    "6.2_M94" AS 6_2_m94,
    CAST("6.2_M99" AS BIGINT) AS 6_2_m99,
    CAST("OFF-SITE_RELEASE_TOTAL" AS BIGINT) AS off_site_release_total,
    CAST("6.2_M20" AS BIGINT) AS 6_2_m20,
    CAST("6.2_M24" AS DOUBLE) AS 6_2_m24,
    CAST("6.2_M26" AS DOUBLE) AS 6_2_m26,
    CAST("6.2_M28" AS BIGINT) AS 6_2_m28,
    CAST("6.2_M93" AS BIGINT) AS 6_2_m93,
    CAST("OFF-SITE_RECYCLED_TOTAL" AS DOUBLE) AS off_site_recycled_total,
    "6.2_M56" AS 6_2_m56,
    CAST("6.2_M92" AS BIGINT) AS 6_2_m92,
    "OFF-SITE_RECOVERY_TOTAL" AS off_site_recovery_total,
    CAST("6.2_M40" AS DOUBLE) AS 6_2_m40,
    CAST("6.2_M50" AS BIGINT) AS 6_2_m50,
    CAST("6.2_M54" AS DOUBLE) AS 6_2_m54,
    CAST("6.2_M61" AS BIGINT) AS 6_2_m61,
    CAST("6.2_M69" AS BIGINT) AS 6_2_m69,
    CAST("6.2_M95" AS DOUBLE) AS 6_2_m95,
    CAST("OFF-SITE_TREATED_TOTAL" AS BIGINT) AS off_site_treated_total,
    CAST("TOTAL_RELEASES" AS BIGINT) AS total_releases,
    CAST("8.1_RELEASES" AS BIGINT) AS 8_1_releases,
    CAST("8.1A_ON-SITE_CONTAINED_REL." AS BIGINT) AS 8_1a_on_site_contained_rel,
    "8.1B_ON-SITE_OTHER_RELEASES" AS 8_1b_on_site_other_releases,
    "8.1C_OFF-SITE_CONTAINED_REL." AS 8_1c_off_site_contained_rel,
    "8.1D_OFF-SITE_OTHER_RELEASES" AS 8_1d_off_site_other_releases,
    CAST("8.2_ENERGY_RECOVERY_ON-SITE" AS BIGINT) AS 8_2_energy_recovery_on_site,
    CAST("8.3_ENERGY_RECOVERY_OFF-SITE" AS BIGINT) AS 8_3_energy_recovery_off_site,
    CAST("8.4_RECYCLING_ON-SITE" AS BIGINT) AS 8_4_recycling_on_site,
    CAST("8.5_RECYCLING_OFF-SITE" AS DOUBLE) AS 8_5_recycling_off_site,
    CAST("8.6_TREATMENT_ON-SITE" AS BIGINT) AS 8_6_treatment_on_site,
    CAST("8.7_TREATMENT_OFF-SITE" AS DOUBLE) AS 8_7_treatment_off_site,
    CAST("PROD._WASTE_(8.1_THRU_8.7)" AS DOUBLE) AS prod_waste_8_1_thru_8_7,
    CAST("8.8_ONE-TIME_RELEASE" AS BIGINT) AS 8_8_one_time_release,
    "PROD_RATIO_OR_ACTIVITY" AS prod_ratio_or_activity,
    "8.9_PRODUCTION_RATIO" AS 8_9_production_ratio,
    "PARENT_COMPANY_NAME" AS parent_company_name,
    "PARENT_COMPANY_DB_NUMBER" AS parent_company_db_number,
    "SYS_STSITSSXSOLCHJPSAF7486K4RV" AS sys_stsitssxsolchjpsaf7486k4rv,
    "SYS_STSWGMX8O#197_NPUKVK#S5$QM" AS sys_stswgmx8o_197_npukvk_s5_qm,
    "col_111"
FROM "instituto-de-estad-sticas-de-puerto-rico-tri"
