-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_resource",
    "source_file",
    CAST("ID" AS BIGINT) AS id,
    "Start time" AS start_time,
    "Completion time" AS completion_time,
    "Email" AS email,
    "Name" AS name,
    "Fecha de realización de encuesta" AS fecha_de_realizaci_n_de_encuesta,
    "Nombre del Municipio" AS nombre_del_municipio,
    "Número de teléfono municipio" AS n_mero_de_tel_fono_municipio,
    "Nombre de la Biblioteca" AS nombre_de_la_biblioteca,
    "Dirección Física" AS direcci_n_f_sica,
    "Dirección Postal" AS direcci_n_postal,
    "Correo electrónico" AS correo_electr_nico,
    "Número de teléfono BIBLIOTECA" AS n_mero_de_tel_fono_biblioteca,
    "Número de alterno" AS n_mero_de_alterno,
    "Cantidad de bibliotecas satélites por municipio" AS cantidad_de_bibliotecas_sat_lites_por_municipio,
    "Población atendida en la biblioteca:" AS poblaci_n_atendida_en_la_biblioteca,
    "Entidad encargada de la Biblioteca" AS entidad_encargada_de_la_biblioteca,
    "Presupuesto operacional de la biblioteca proviene del gobierno" AS presupuesto_operacional_de_la_biblioteca_proviene_del_gobierno,
    "Mencione otras subvenciones, donativos y formas de ayuda que recibe la biblioteca" AS otras_subvenciones_donativos_ayuda_biblioteca,
    "¿La biblioteca tiene asignado un presupuesto?" AS la_biblioteca_tiene_asignado_un_presupuesto,
    "El presupuesto anual de la biblioteca es" AS el_presupuesto_anual_de_la_biblioteca_es,
    "Parte de ese presupuesto va dirigido a tecnología" AS parte_de_ese_presupuesto_va_dirigido_a_tecnolog_a,
    "Cantidad: (pregunta anterior)" AS cantidad_pregunta_anterior,
    "Nombre de la persona encargada de la biblioteca" AS nombre_de_la_persona_encargada_de_la_biblioteca,
    "Puesto de la persona encargada de la biblioteca" AS puesto_de_la_persona_encargada_de_la_biblioteca,
    "Preparación académica de la persona encargada de la biblioteca" AS preparaci_n_acad_mica_de_la_persona_encargada_de_la_biblioteca,
    "Tipo de contrato de la persona encargada" AS tipo_de_contrato_de_la_persona_encargada,
    "Años de servicio en bibliotecas:" AS a_os_de_servicio_en_bibliotecas,
    "Años en el puesto actual" AS a_os_en_el_puesto_actual,
    "Cantidad de Bibliotecarios" AS cantidad_de_bibliotecarios,
    "Cantidad de Bibliotecarios Auxiliares" AS cantidad_de_bibliotecarios_auxiliares,
    "Cantidad de Ayudantes de Bibliotecas" AS cantidad_de_ayudantes_de_bibliotecas,
    "Cantidad de Personal Secretarial" AS cantidad_de_personal_secretarial,
    "Cantidad de Personal de Mantenimiento" AS cantidad_de_personal_de_mantenimiento,
    "Cantidad de otro Personal" AS cantidad_de_otro_personal,
    "Participación del encargado de la biblioteca en acts. de educación continua:" AS encargado_participa_educacion_continua,
    "Participación del otro persona de la biblioteca en acts. de educación continua:" AS otro_personal_participa_educacion_continua,
    "Llevan registro de usuarios" AS llevan_registro_de_usuarios,
    CAST("¿De llevarlo cual es el año de la información más reciente?" AS BIGINT) AS de_llevarlo_cual_es_el_a_o_de_la_informaci_n_m_s_reciente,
    "Cantidad de usuarios anuales" AS cantidad_de_usuarios_anuales,
    "Servicios que ofrece la biblioteca" AS servicios_que_ofrece_la_biblioteca,
    "¿La Biblioteca tiene conexión a internet?" AS la_biblioteca_tiene_conexi_n_a_internet,
    "Tipo de conexión de internet" AS tipo_de_conexi_n_de_internet,
    "Servicios relacionados a orientación sobre tecnología" AS servicios_relacionados_a_orientaci_n_sobre_tecnolog_a,
    "Cantidad de computadoras (desktop)" AS cantidad_de_computadoras_desktop,
    "¿Se hacen préstamos de computadoras en la biblioteca?" AS se_hacen_pr_stamos_de_computadoras_en_la_biblioteca,
    "Cantidad de laptops" AS cantidad_de_laptops,
    "¿Se hacen préstamos de laptops en la biblioteca?" AS se_hacen_pr_stamos_de_laptops_en_la_biblioteca,
    "¿Se hacen préstamos de laptops en la casa?" AS se_hacen_pr_stamos_de_laptops_en_la_casa,
    "Cantidad de tableta" AS cantidad_de_tableta,
    "¿Se hacen préstamos de tabletas en la biblioteca?" AS se_hacen_pr_stamos_de_tabletas_en_la_biblioteca,
    "¿Se hacen préstamos de tabletas en la casa?" AS se_hacen_pr_stamos_de_tabletas_en_la_casa,
    "Cantidad de impresoras" AS cantidad_de_impresoras,
    "¿Se hacen préstamos de impresora en la biblioteca?" AS se_hacen_pr_stamos_de_impresora_en_la_biblioteca,
    "Cantidad de teléfonos" AS cantidad_de_tel_fonos,
    "¿Se hacen préstamos de teléfonos en la biblioteca?" AS se_hacen_pr_stamos_de_tel_fonos_en_la_biblioteca,
    "Cantidad de escáners" AS cantidad_de_esc_ners,
    "¿Se hacen préstamos de escáner en la biblioteca?" AS se_hacen_pr_stamos_de_esc_ner_en_la_biblioteca,
    "Cantidad de proyectores" AS cantidad_de_proyectores,
    "¿Se hacen préstamos de proyectores en la biblioteca?" AS se_hacen_pr_stamos_de_proyectores_en_la_biblioteca,
    "Otro equipo:" AS otro_equipo,
    "¿Tienen colección de libros?" AS tienen_colecci_n_de_libros,
    "En la colección tienen" AS en_la_colecci_n_tienen,
    "¿Catalogan y/o clasifican el material de la colección?" AS catalogan_y_o_clasifican_el_material_de_la_colecci_n,
    "¿Qué sistema de catalogación utilizan?" AS qu_sistema_de_catalogaci_n_utilizan,
    "¿Tienen catálogo en línea?" AS tienen_cat_logo_en_l_nea,
    "Programa que utilizan para catálogo en línea:" AS programa_que_utilizan_para_cat_logo_en_l_nea,
    "¿Tienen archivo vertical?" AS tienen_archivo_vertical,
    "¿Qué información tienen en el archivo vertical?" AS qu_informaci_n_tienen_en_el_archivo_vertical,
    "¿Cuántas bibliotecas escolares disponibles hay en su municipio?" AS cu_ntas_bibliotecas_escolares_disponibles_hay_en_su_municipio,
    "¿Mantiene contacto con los maestros bibliotecarios?" AS mantiene_contacto_con_los_maestros_bibliotecarios,
    "Además de los servicios básicos, ¿ofrece otros a la comunidad?" AS adem_s_de_los_servicios_b_sicos_ofrece_otros_a_la_comunidad,
    "¿Ofrecen servicios que se adapten a las necesidades de la comunidad con diversidad funcional?" AS ofrece_servicios_diversidad_funcional,
    "¿Cuáles?" AS cu_les,
    "¿Tiene la biblioteca acuerdos o proyecto colaborativos con otras bibliotecas?" AS acuerdos_colaborativos_otras_bibliotecas,
    "¿Qué necesidades u obstáculos enfrenta la biblioteca para cumplir con misión?" AS necesidades_obstaculos_mision,
    "¿Que tipo de apoyo le gustaría recibir de la Biblioteca Nacional de Puerto Rico?" AS apoyo_deseado_biblioteca_nacional
FROM "instituto-de-estad-sticas-de-puerto-rico-bibliotecas-municipales"
