-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_resource",
    "source_file",
    "Gender" AS gender,
    CAST("Age" AS BIGINT) AS age,
    "AgeUnit" AS ageunit,
    CAST("BirthDate_Year" AS BIGINT) AS birthdate_year,
    "BirthPlace" AS birthplace,
    "TimeOfResidenceInPR (Value)" AS timeofresidenceinpr_value,
    "TimeOfResidenceInPR (Unit)" AS timeofresidenceinpr_unit,
    "ResidencePlace" AS residenceplace,
    "Citizenship" AS citizenship,
    "Veteran?" AS veteran,
    "MaritalStatus" AS maritalstatus,
    "FatherBirthPlace" AS fatherbirthplace,
    "MotherBirthPlace" AS motherbirthplace,
    "DeathPlace" AS deathplace,
    "MunicipalityDeathPlace" AS municipalitydeathplace,
    "DeathFacility" AS deathfacility,
    "OtherDeathFacility" AS otherdeathfacility,
    CAST("TimeSpentOnFacility (Value)" AS BIGINT) AS timespentonfacility_value,
    "TimeSpentOnFacility (Unit)" AS timespentonfacility_unit,
    CAST("DeathDate_Year" AS BIGINT) AS deathdate_year,
    CAST("DeathDate_Month" AS BIGINT) AS deathdate_month,
    "DeathTimeHour" AS deathtimehour,
    "DeathTimeMinutes" AS deathtimeminutes,
    "DeathTimeAMPM" AS deathtimeampm,
    "OrganDonor?" AS organdonor,
    "DeathCause_I (ID)" AS deathcause_i_id,
    "DeathCause_I (Desription)" AS deathcause_i_desription,
    "DeathCause_II (ID)" AS deathcause_ii_id,
    "DeathCause_II (Desription)" AS deathcause_ii_desription,
    "DeathCause_III (ID)" AS deathcause_iii_id,
    "DeathCause_III (Desription)" AS deathcause_iii_desription,
    "DeathCause_IV (ID)" AS deathcause_iv_id,
    "DeathCause_IV (Desription)" AS deathcause_iv_desription,
    "DeathCause_V (ID)" AS deathcause_v_id,
    "DeathCause_V (Desription)" AS deathcause_v_desription,
    "DeathCause_VI (ID)" AS deathcause_vi_id,
    "DeathCause_VI (Desription)" AS deathcause_vi_desription,
    "DeathCause_VII (ID)" AS deathcause_vii_id,
    "DeathCause_VII (Desription)" AS deathcause_vii_desription,
    "DeathCause_VIII (ID)" AS deathcause_viii_id,
    "DeathCause_VIII (Desription)" AS deathcause_viii_desription,
    "DeathCause_IX (ID)" AS deathcause_ix_id,
    "DeathCause_IX (Desription)" AS deathcause_ix_desription,
    "DeathCause_X (ID)" AS deathcause_x_id,
    "DeathCause_X (Desription)" AS deathcause_x_desription,
    "Autopsy?" AS autopsy,
    "TypeOfDeath" AS typeofdeath,
    "InjuryDate" AS injurydate,
    CAST("InjuryDate_Year" AS BIGINT) AS injurydate_year,
    CAST("InjuryDate_Month" AS BIGINT) AS injurydate_month,
    CAST("InjuryDate_Day" AS BIGINT) AS injurydate_day,
    CAST("InjuryTimeHour" AS BIGINT) AS injurytimehour,
    CAST("InjuryTimeMinutes" AS BIGINT) AS injurytimeminutes,
    "InjuryTimeAMPM" AS injurytimeampm,
    "InjuryPlace" AS injuryplace,
    "InjuryAtWork" AS injuryatwork,
    "Education" AS education,
    "Occupation" AS occupation,
    "Industry" AS industry,
    "OccupationYears" AS occupationyears,
    "Embalmed?" AS embalmed,
    "TypeOfFuneral" AS typeoffuneral,
    CAST("FuneralDate_Year" AS BIGINT) AS funeraldate_year,
    "AcmeUnderlyingCauseCode" AS acmeunderlyingcausecode,
    "ACMEUnderlyingCauseDescription" AS acmeunderlyingcausedescription
FROM "instituto-de-estad-sticas-de-puerto-rico-defunciones-registradas"
