-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_resource",
    "source_file",
    CAST("STFIPS" AS BIGINT) AS stfips,
    CAST("Region" AS BIGINT) AS region,
    "ITEM8" AS item8,
    CAST("ITEM5A" AS BIGINT) AS item5a,
    CAST("ITEM5B" AS BIGINT) AS item5b,
    CAST("ITEM5C" AS BIGINT) AS item5c,
    CAST("ITEM5D" AS BIGINT) AS item5d,
    CAST("ITEM5E" AS BIGINT) AS item5e,
    CAST("ITEM2" AS BIGINT) AS item2,
    CAST("ITEM3" AS BIGINT) AS item3,
    CAST("ITEM4" AS BIGINT) AS item4,
    "ITEM6A" AS item6a,
    "ITEM6B" AS item6b,
    "ITEM7" AS item7,
    "ITEM9" AS item9,
    CAST("ITEM10" AS DOUBLE) AS item10,
    CAST("ITEM11" AS DOUBLE) AS item11,
    CAST("ITEM12" AS BIGINT) AS item12,
    CAST("ITEM13A" AS BIGINT) AS item13a,
    CAST("ITEM13B" AS BIGINT) AS item13b,
    CAST("ITEM16" AS DOUBLE) AS item16,
    CAST("ITEM17" AS DOUBLE) AS item17,
    CAST("ITEM19" AS BIGINT) AS item19,
    CAST("ITEM20" AS BIGINT) AS item20,
    CAST("ITEM21" AS BIGINT) AS item21,
    CAST("ITEM22" AS BIGINT) AS item22,
    CAST("ITEM26" AS BIGINT) AS item26,
    CAST("ITEM27" AS BIGINT) AS item27,
    CAST("ITEM28A" AS BIGINT) AS item28a,
    CAST("ITEM28B" AS BIGINT) AS item28b,
    CAST("ITEM29" AS BIGINT) AS item29,
    CAST("ITEM30" AS BIGINT) AS item30,
    CAST("ITEM31" AS BIGINT) AS item31,
    CAST("ITEM32" AS DOUBLE) AS item32,
    CAST("ITEM33" AS BIGINT) AS item33,
    CAST("ITEM34" AS BIGINT) AS item34,
    CAST("ITEM35" AS BIGINT) AS item35,
    CAST("ITEM36A" AS BIGINT) AS item36a,
    CAST("ITEM36B" AS BIGINT) AS item36b,
    CAST("ITEM36C" AS BIGINT) AS item36c,
    CAST("ITEM36D" AS BIGINT) AS item36d,
    CAST("ITEM37" AS BIGINT) AS item37,
    CAST("ITEM38" AS BIGINT) AS item38,
    CAST("ITEM39" AS DOUBLE) AS item39,
    CAST("ITEM40" AS DOUBLE) AS item40,
    "ITEM41" AS item41,
    CAST("ITEM42A" AS BIGINT) AS item42a,
    CAST("ITEM42B" AS BIGINT) AS item42b,
    CAST("ITEM43A" AS BIGINT) AS item43a,
    CAST("ITEM43B" AS BIGINT) AS item43b,
    CAST("ITEM44A" AS BIGINT) AS item44a,
    CAST("ITEM44B" AS BIGINT) AS item44b,
    CAST("ITEM45" AS BIGINT) AS item45,
    CAST("ITEM46" AS BIGINT) AS item46,
    CAST("ITEM47" AS DOUBLE) AS item47,
    CAST("ITEM48" AS DOUBLE) AS item48,
    CAST("ITEM49" AS DOUBLE) AS item49,
    CAST("ITEM50A" AS DOUBLE) AS item50a,
    CAST("ITEM50B" AS DOUBLE) AS item50b,
    CAST("ITEM51" AS DOUBLE) AS item51,
    CAST("ITEM52" AS DOUBLE) AS item52,
    CAST("ITEM53" AS DOUBLE) AS item53,
    "ITEM54A" AS item54a,
    CAST("ITEM54B" AS DOUBLE) AS item54b,
    "ITEM55A" AS item55a,
    CAST("ITEM55B" AS DOUBLE) AS item55b,
    CAST("ITEM56" AS DOUBLE) AS item56,
    "ITEM58" AS item58,
    "ITEM59" AS item59,
    "ITEM60" AS item60,
    CAST("ITEM61" AS BIGINT) AS item61,
    "ITEM62" AS item62,
    CAST("ITEM63" AS BIGINT) AS item63,
    CAST("ITEM64" AS DOUBLE) AS item64,
    CAST("ITEM65" AS BIGINT) AS item65,
    CAST("ITEM66" AS DOUBLE) AS item66,
    CAST("ITEM67" AS BIGINT) AS item67,
    "ITEM68" AS item68,
    "ITEM69" AS item69,
    CAST("ITEM70" AS BIGINT) AS item70,
    CAST("ITEM71" AS BIGINT) AS item71,
    CAST("ITEM72" AS BIGINT) AS item72,
    CAST("ITEM75A" AS BIGINT) AS item75a,
    CAST("ITEM75B" AS BIGINT) AS item75b,
    CAST("ITEM76" AS DOUBLE) AS item76,
    CAST("ITEM90" AS BIGINT) AS item90,
    CAST("ITEM91" AS BIGINT) AS item91,
    "ITEM92A" AS item92a,
    "ITEM92B" AS item92b,
    "ITEM92C" AS item92c,
    CAST("ITEM93A" AS BIGINT) AS item93a,
    CAST("ITEM93B" AS BIGINT) AS item93b,
    CAST("ITEM93C" AS BIGINT) AS item93c,
    CAST("ITEM94" AS BIGINT) AS item94,
    CAST("ITEM95" AS BIGINT) AS item95,
    CAST("ITEM96" AS BIGINT) AS item96,
    CAST("ITEM97" AS BIGINT) AS item97,
    CAST("ITEM98A" AS BIGINT) AS item98a,
    CAST("ITEM98B" AS BIGINT) AS item98b,
    "ITEM99" AS item99,
    CAST("ITEM100" AS BIGINT) AS item100,
    "ITEM101" AS item101,
    CAST("ITEM102" AS BIGINT) AS item102,
    "ITEM103" AS item103,
    CAST("ITEM104" AS BIGINT) AS item104,
    CAST("ITEM105" AS BIGINT) AS item105,
    CAST("ITEM106" AS BIGINT) AS item106,
    CAST("ITEM107" AS BIGINT) AS item107,
    CAST("ITEM108A" AS BIGINT) AS item108a,
    CAST("ITEM108B" AS BIGINT) AS item108b,
    CAST("ITEM108C" AS BIGINT) AS item108c,
    CAST("ITEM109" AS BIGINT) AS item109,
    CAST("ITEM110" AS BIGINT) AS item110,
    CAST("ITEM111" AS BIGINT) AS item111,
    "ITEM112" AS item112,
    CAST("ITEM113" AS BIGINT) AS item113,
    CAST("ITEM114" AS BIGINT) AS item114,
    CAST("ITEM115" AS BIGINT) AS item115,
    CAST("ITEM116" AS DOUBLE) AS item116,
    "FED_AGENCY" AS fed_agency,
    CAST("STAT" AS BIGINT) AS stat,
    "SR1" AS sr1,
    CAST("SR2" AS BIGINT) AS sr2,
    CAST("EXTRA" AS BIGINT) AS extra,
    "STATUS" AS status,
    "DATE" AS date,
    CAST("LONGDD" AS DOUBLE) AS longdd,
    CAST("LATDD" AS DOUBLE) AS latdd
FROM "instituto-de-estad-sticas-de-puerto-rico-national-bridge-inventory"
