-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_resource",
    "source_file",
    "Trade" AS trade,
    CAST("Year" AS BIGINT) AS year,
    CAST("Month" AS BIGINT) AS month,
    CAST("Commodity_Code" AS BIGINT) AS commodity_code,
    "Commodity_Short_Name" AS commodity_short_name,
    "Commodity_description" AS commodity_description,
    CAST("cty_code" AS BIGINT) AS cty_code,
    "Country" AS country,
    "SubCountry_Code" AS subcountry_code,
    "district",
    "DistrictDesc" AS districtdesc,
    "district_posh",
    "DistrictPoshDesc" AS districtposhdesc,
    CAST("data" AS BIGINT) AS data,
    "sitc",
    "SITC_Short_Desc" AS sitc_short_desc,
    "SITC_Long_Desc" AS sitc_long_desc,
    "naics",
    "NAICS_description" AS naics_description,
    "end_use_i",
    "end_use_e",
    "hts_desc",
    "unit_1",
    CAST("qty_1" AS BIGINT) AS qty_1,
    "unit_2",
    CAST("qty_2" AS BIGINT) AS qty_2,
    CAST("ves_val_mo" AS BIGINT) AS ves_val_mo,
    CAST("ves_wgt_mo" AS BIGINT) AS ves_wgt_mo,
    CAST("cards_mo" AS BIGINT) AS cards_mo,
    CAST("air_val_mo" AS BIGINT) AS air_val_mo,
    CAST("air_wgt_mo" AS BIGINT) AS air_wgt_mo,
    CAST("dut_val_mo" AS BIGINT) AS dut_val_mo,
    CAST("cal_dut_mo" AS BIGINT) AS cal_dut_mo,
    CAST("con_cha_mo" AS BIGINT) AS con_cha_mo,
    CAST("con_cif_mo" AS BIGINT) AS con_cif_mo,
    CAST("gen_val_mo" AS BIGINT) AS gen_val_mo,
    CAST("gen_cha_mo" AS BIGINT) AS gen_cha_mo,
    CAST("gen_cif_mo" AS BIGINT) AS gen_cif_mo,
    CAST("air_cha_mo" AS BIGINT) AS air_cha_mo,
    CAST("ves_cha_mo" AS BIGINT) AS ves_cha_mo,
    CAST("cnt_cha_mo" AS BIGINT) AS cnt_cha_mo,
    "rev_data"
FROM "instituto-de-estad-sticas-de-puerto-rico-comercio-externo"
