-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Current inventory can contain multiple records per crossing/reporting context; filter to the intended status or revision fields before treating crossing identifiers as unique locations.
SELECT
    CAST("revisiondate" AS TIMESTAMP) AS revisiondate,
    "railroadcode",
    "railroadname",
    CAST("reportingagencytypecode" AS BIGINT) AS reportingagencytypecode,
    "reportingagencytype",
    CAST("reasoncode" AS BIGINT) AS reasoncode,
    "reasondescription",
    "crossingid",
    "crossingidsuffix",
    "reportingagencycode",
    "reportingagencyname",
    "statecode",
    "statename",
    "countycode",
    "countyname",
    CAST("innearcode" AS BIGINT) AS innearcode,
    "innear",
    "citycode",
    "cityname",
    "citydescription",
    "street",
    "blocknumber",
    "highwayname",
    "separatetrack",
    "separatetrackrailroad1",
    "separatetrackrailroad2",
    "separatetrackrailroad3",
    "separatetrackrailroad4",
    "sametrack",
    "sametrackrailroad1",
    "sametrackrailroad2",
    "sametrackrailroad3",
    "sametrackrailroad4",
    "railroaddivision",
    "railroadsubdivision",
    "branchname",
    "railroadmilepostprefix",
    "railroadmilepostnumber",
    "railroadmilepostsuffix",
    "linesegment",
    "nearesttimetablestation",
    "timetablestation",
    "parentrailroadcode",
    "crossingownercode",
    CAST("crossingtypecode" AS BIGINT) AS crossingtypecode,
    "crossingtype",
    CAST("crossingpurposecode" AS BIGINT) AS crossingpurposecode,
    "crossingpurpose",
    CAST("crossingpositioncode" AS BIGINT) AS crossingpositioncode,
    "crossingposition",
    "publicaccess",
    "typeoftrainserviceids",
    CAST("typeoftrainserviceid1" AS BIGINT) AS typeoftrainserviceid1,
    "typeoftrainservice1",
    CAST("typeoftrainserviceid2" AS BIGINT) AS typeoftrainserviceid2,
    "typeoftrainservice2",
    CAST("typeoftrainserviceid3" AS BIGINT) AS typeoftrainserviceid3,
    "typeoftrainservice3",
    CAST("typeoftrainserviceid4" AS BIGINT) AS typeoftrainserviceid4,
    "typeoftrainservice4",
    CAST("typeoftrainserviceid5" AS BIGINT) AS typeoftrainserviceid5,
    "typeoftrainservice5",
    CAST("typeoftrainserviceid6" AS BIGINT) AS typeoftrainserviceid6,
    "typeoftrainservice6",
    "ltpassengertrainperday",
    CAST("numberpassengertrainperday" AS BIGINT) AS numberpassengertrainperday,
    CAST("developmenttypecode" AS BIGINT) AS developmenttypecode,
    "developmenttype",
    "adjacentcrossing",
    "adjacentcrossingnumber",
    CAST("whistlebancode" AS BIGINT) AS whistlebancode,
    "whistleban",
    strptime("whistledate", '%Y-%m-%d')::DATE AS whistledate,
    "hsrcorridoridsuffix",
    "hsrcorridorid",
    "latitude",
    "longitude",
    CAST("latlongsourcecode" AS BIGINT) AS latlongsourcecode,
    "latlongsource",
    "railroadnarrativebase",
    "railroadnarrative",
    "statenarrativebase",
    "statenarrative",
    "emergencytelephonenumber",
    "railroadcontacttelephonenumber",
    "statecontacttelephonenumber",
    CAST("totaldaylightthrutrains" AS BIGINT) AS totaldaylightthrutrains,
    CAST("totalnighttimethrutrains" AS BIGINT) AS totalnighttimethrutrains,
    CAST("totalswitchingtrains" AS BIGINT) AS totalswitchingtrains,
    CAST("totaltransittrains" AS BIGINT) AS totaltransittrains,
    CAST("movementsperdaycode" AS BIGINT) AS movementsperdaycode,
    "movementsperday",
    CAST("trainsperweek" AS BIGINT) AS trainsperweek,
    CAST("trainsperyear" AS BIGINT) AS trainsperyear,
    CAST("maximumtimetablespeed" AS BIGINT) AS maximumtimetablespeed,
    CAST("minimumspeedrangeovercrossing" AS BIGINT) AS minimumspeedrangeovercrossing,
    CAST("maximumspeedrangeovercrossing" AS BIGINT) AS maximumspeedrangeovercrossing,
    CAST("numberofmaintracks" AS BIGINT) AS numberofmaintracks,
    CAST("numberofsidingtracks" AS BIGINT) AS numberofsidingtracks,
    CAST("numberofyardtracks" AS BIGINT) AS numberofyardtracks,
    CAST("numberoftransittracks" AS BIGINT) AS numberoftransittracks,
    CAST("numberofindustrytracks" AS BIGINT) AS numberofindustrytracks,
    CAST("othertrack" AS BIGINT) AS othertrack,
    "othertrackdescription",
    "traindetectionids",
    CAST("traindetectionid1" AS BIGINT) AS traindetectionid1,
    "traindetection1",
    CAST("traindetectionid2" AS BIGINT) AS traindetectionid2,
    "traindetection2",
    CAST("traindetectionid3" AS BIGINT) AS traindetectionid3,
    "traindetection3",
    "tracksignaled",
    "eventrecorder",
    "remotehealthmonitoring",
    "signsorsignals",
    CAST("numbercrossbuckassemblies" AS BIGINT) AS numbercrossbuckassemblies,
    CAST("numberstopsigns" AS BIGINT) AS numberstopsigns,
    CAST("numberyieldsigns" AS BIGINT) AS numberyieldsigns,
    "advancewarnings",
    CAST("advancewarning1" AS BIGINT) AS advancewarning1,
    "advancewarningtext1",
    CAST("advancewarning2" AS BIGINT) AS advancewarning2,
    "advancewarningtext2",
    CAST("advancewarning3" AS BIGINT) AS advancewarning3,
    "advancewarningtext3",
    CAST("advancewarning4" AS BIGINT) AS advancewarning4,
    "advancewarningtext4",
    CAST("advancewarning5" AS BIGINT) AS advancewarning5,
    "advancewarningtext5",
    CAST("advancewarning6" AS BIGINT) AS advancewarning6,
    "advancewarningtext6",
    CAST("advancewarning7" AS BIGINT) AS advancewarning7,
    "advancewarningtext7",
    CAST("countadvw10_1" AS BIGINT) AS countadvw10_1,
    CAST("countadvw10_2" AS BIGINT) AS countadvw10_2,
    CAST("countadvw10_3" AS BIGINT) AS countadvw10_3,
    CAST("countadvw10_4" AS BIGINT) AS countadvw10_4,
    CAST("countadvw10_11" AS BIGINT) AS countadvw10_11,
    CAST("countadvw10_12" AS BIGINT) AS countadvw10_12,
    "lowgroundclearancesigns",
    CAST("numberlowgroundclearancesigns" AS BIGINT) AS numberlowgroundclearancesigns,
    "pavementmarkingids",
    CAST("pavementmarkingid1" AS BIGINT) AS pavementmarkingid1,
    "pavementmarking1",
    CAST("pavementmarkingid2" AS BIGINT) AS pavementmarkingid2,
    "pavementmarking2",
    CAST("pavementmarkingid3" AS BIGINT) AS pavementmarkingid3,
    "pavementmarking3",
    CAST("pavementmarkingid4" AS BIGINT) AS pavementmarkingid4,
    "pavementmarking4",
    CAST("channeldevicemediancode" AS BIGINT) AS channeldevicemediancode,
    "channeldevicemedian",
    "exemptsigns",
    "enssigndisplayed",
    "othermutcdsigns",
    CAST("numberothermutcdsigns1" AS BIGINT) AS numberothermutcdsigns1,
    "othermutcdsignstype1",
    "othermutcdsignstypetext1",
    CAST("numberothermutcdsigns2" AS BIGINT) AS numberothermutcdsigns2,
    "othermutcdsignstype2",
    "othermutcdsignstypetext2",
    CAST("numberothermutcdsigns3" AS BIGINT) AS numberothermutcdsigns3,
    "othermutcdsignstype3",
    "othermutcdsignstypetext3",
    "privatecrossingsigns",
    "ledenhancedsigns",
    CAST("countroadwaygatearms" AS BIGINT) AS countroadwaygatearms,
    CAST("countpedestriangatearms" AS BIGINT) AS countpedestriangatearms,
    "gateconfigurationcode",
    "gateconfiguration",
    "gateconfigurationtypecode",
    "gateconfigurationtype",
    CAST("countcantileveroverlane" AS BIGINT) AS countcantileveroverlane,
    CAST("countcantilevernolane" AS BIGINT) AS countcantilevernolane,
    "cantileveredtypestructurecode",
    "cantileveredtypestructure",
    CAST("countmastmountedflashinglight" AS BIGINT) AS countmastmountedflashinglight,
    "mastmountedflashinglightcode",
    "mastmountedflashinglighttype",
    "mastmountedflashingbacklight",
    "mastmountedflashingsidelight",
    CAST("countflashinglightpair" AS BIGINT) AS countflashinglightpair,
    "installationdateactivewa",
    "waysidehorn",
    "installationdatewaysidehorn",
    "highwaytrafficsignal",
    CAST("numberofbells" AS BIGINT) AS numberofbells,
    CAST("nontrainactivewarningcode" AS BIGINT) AS nontrainactivewarningcode,
    "nontrainactivewarning",
    CAST("countotherflashinglights" AS BIGINT) AS countotherflashinglights,
    "otherflashinglightstype",
    "nearbyhighwaytrafficsignals",
    "hwytrafficsgnlinterconncode",
    "hwytrafficsgnlinterconn",
    "hwytrafficsgnlprecode",
    "hwytrafficsgnlpre",
    "highwaytrafficpresignals",
    CAST("stoplinedistance" AS BIGINT) AS stoplinedistance,
    CAST("storagedistance" AS BIGINT) AS storagedistance,
    "highwaymonitoringdevicescode",
    "highwaymonitoringdevices",
    "trafficlane",
    CAST("trafficlanetypecode" AS BIGINT) AS trafficlanetypecode,
    "trafficlanetypedescription",
    "highwaypaved",
    "trackrundownstreet",
    "crossingilluminated",
    "crossingsurfaceinstalldate",
    CAST("crossingsurfacewidth" AS BIGINT) AS crossingsurfacewidth,
    CAST("crossingsurfacelength" AS BIGINT) AS crossingsurfacelength,
    "crossingsurfaceids",
    CAST("crossingsurfaceid1" AS BIGINT) AS crossingsurfaceid1,
    "crossingsurfacedescription1",
    "crossingsurfaceid2",
    "crossingsurfacedescription2",
    "crossingsurfaceid3",
    "crossingsurfacedescription3",
    "othercrossingsurface",
    "highwaynear",
    CAST("intersectingroadwaydistance" AS BIGINT) AS intersectingroadwaydistance,
    CAST("smallestcrossinganglecode" AS BIGINT) AS smallestcrossinganglecode,
    "smallestcrossingangle",
    "compower",
    "highwaysystemcode",
    "highwaysystem",
    CAST("roadatcrossingcode" AS BIGINT) AS roadatcrossingcode,
    "roadatcrossing",
    CAST("roadatcrossingtypecode" AS BIGINT) AS roadatcrossingtypecode,
    "roadatcrossingtype",
    "crossingonstatehighwaysystem",
    CAST("highwayspeedlimit" AS BIGINT) AS highwayspeedlimit,
    "highwayspeedlimittypecode",
    "highwayspeedlimittype",
    "linearreferencingsystemrouteid",
    "linearrefsystemmilepost",
    CAST("annualaveragedailytrafficcount" AS BIGINT) AS annualaveragedailytrafficcount,
    CAST("annualaveragedailytrafficyear" AS BIGINT) AS annualaveragedailytrafficyear,
    "estimatedpercenttrucks",
    "schoolbusroute",
    CAST("schoolbusaveragecount" AS BIGINT) AS schoolbusaveragecount,
    "emergencyservicesroute",
    "ccmqzid",
    "thrrequestno",
    "reporttype",
    "crossingclosed",
    "reportstatus",
    CAST("agencyid" AS BIGINT) AS agencyid,
    "reporting_railroad_class",
    "reporting_railroad_smt_grouping",
    "reporting_parent_railroad_code",
    "reporting_parent_railroad_name",
    "reporting_railroad_holding_company",
    "wdcode",
    "multipleformsfiled",
    "geocoded_lat_long",
    "url",
    "reporting_railroad_individual_class",
    "reporting_railroad_passenger",
    "reporting_railroad_commuter",
    "reporting_railroad_switching_terminal",
    "reporting_railroad_tourist",
    "reporting_railroad_freight",
    "reporting_railroad_short_line"
FROM "fra-m2f8-22s6"
