-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: This source-form extract uses legacy FRA source fields; do not combine it with the curated Form 57 incident table without reconciling duplicate report concepts.
SELECT
    "amtrak",
    "iyr",
    "imo",
    "railroad",
    "incdtno",
    "iyr2",
    "imo2",
    "rr2",
    "incdtno2",
    "iyr3",
    "imo3",
    "rr3",
    "incdtno3",
    "dummy1",
    CAST("casinjrr" AS DOUBLE) AS casinjrr,
    "gxid",
    "year",
    "month",
    "day",
    CAST("timehr" AS DOUBLE) AS timehr,
    CAST("timemin" AS DOUBLE) AS timemin,
    "ampm",
    "station",
    "county",
    "state",
    CAST("region" AS BIGINT) AS region,
    "dummy2",
    "city",
    "highway",
    "vehspd",
    "typveh",
    "vehdir",
    CAST("position" AS BIGINT) AS position,
    "rrequip",
    "rrcar",
    CAST("typacc" AS BIGINT) AS typacc,
    CAST("hazard" AS BIGINT) AS hazard,
    CAST("temp" AS DOUBLE) AS temp,
    CAST("visiblty" AS BIGINT) AS visiblty,
    CAST("weather" AS BIGINT) AS weather,
    "typeq",
    CAST("typtrk" AS BIGINT) AS typtrk,
    "trkname",
    "trkclas",
    CAST("nbrlocos" AS DOUBLE) AS nbrlocos,
    CAST("nbrcars" AS DOUBLE) AS nbrcars,
    "trnspd",
    "typspd",
    "trndir",
    "signal",
    "locwarn",
    CAST("warnsig" AS BIGINT) AS warnsig,
    CAST("lights" AS BIGINT) AS lights,
    CAST("standveh" AS BIGINT) AS standveh,
    "train2",
    CAST("motorist" AS BIGINT) AS motorist,
    CAST("view" AS BIGINT) AS view,
    CAST("vehdmg" AS DOUBLE) AS vehdmg,
    CAST("driver" AS BIGINT) AS driver,
    CAST("inveh" AS BIGINT) AS inveh,
    CAST("totkld" AS DOUBLE) AS totkld,
    CAST("totinj" AS DOUBLE) AS totinj,
    CAST("totocc" AS DOUBLE) AS totocc,
    CAST("incdrpt" AS BIGINT) AS incdrpt,
    CAST("jointcd" AS BIGINT) AS jointcd,
    "typrr",
    CAST("dummy3" AS BIGINT) AS dummy3,
    CAST("caskldrr" AS DOUBLE) AS caskldrr,
    "dummy4",
    "crossing",
    CAST("narrlen" AS DOUBLE) AS narrlen,
    "dummy5",
    CAST("year4" AS BIGINT) AS year4,
    "division",
    "public",
    "cntycd",
    "stcnty",
    CAST("hzmrlsed" AS BIGINT) AS hzmrlsed,
    "hzmname",
    "hzmqnty",
    "hzmmeas",
    "sigwarnx",
    "whisban",
    "drivage",
    "drivgen",
    "pleontrn",
    "ssb1",
    "ssb2",
    CAST("userkld" AS DOUBLE) AS userkld,
    CAST("userinj" AS DOUBLE) AS userinj,
    CAST("rrempkld" AS DOUBLE) AS rrempkld,
    CAST("rrempinj" AS DOUBLE) AS rrempinj,
    CAST("passkld" AS DOUBLE) AS passkld,
    CAST("passinj" AS DOUBLE) AS passinj,
    "narr1",
    "narr2",
    "narr3",
    "narr4",
    "narr5",
    "subdiv",
    "roadcond",
    CAST("videot" AS BIGINT) AS videot,
    CAST("videou" AS BIGINT) AS videou
FROM "fra-icqf-xf4w"
