-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: This six-year view is a windowed view of the Form 54 accident data and should not be added to full Form 54 tables without de-duplication.
SELECT
    "reportingrailroadcode",
    "reportingrailroadname",
    CAST("year" AS BIGINT) AS year,
    "accidentnumber",
    "url",
    CAST("accidentyear" AS BIGINT) AS accidentyear,
    "accidentmonth",
    "otherrailroadcode",
    "otherrailroadname",
    "otheraccidentnumber",
    CAST("otheraccidentyear" AS BIGINT) AS otheraccidentyear,
    "otheraccidentmonth",
    "maintenancerailroadcode",
    "maintenancerailroadname",
    "maintenanceaccidentnumber",
    CAST("maintenanceaccidentyear" AS BIGINT) AS maintenanceaccidentyear,
    "maintenanceaccidentmonth",
    "gxid",
    "day",
    CAST("date" AS TIMESTAMP) AS date,
    "time",
    "accident_type_code",
    "accidenttype",
    CAST("hazmatcars" AS BIGINT) AS hazmatcars,
    CAST("hazmatcarsdamaged" AS BIGINT) AS hazmatcarsdamaged,
    CAST("hazmatreleasedcars" AS BIGINT) AS hazmatreleasedcars,
    CAST("personsevacuated" AS BIGINT) AS personsevacuated,
    "subdivision",
    "divisioncode",
    "division",
    "station",
    "milepost",
    "statecode",
    "stateabbr",
    "statename",
    CAST("countycode" AS BIGINT) AS countycode,
    "countyname",
    CAST("district" AS BIGINT) AS district,
    CAST("temperature" AS DOUBLE) AS temperature,
    CAST("visibility_code" AS BIGINT) AS visibility_code,
    "visibility",
    CAST("weather_condition_code" AS BIGINT) AS weather_condition_code,
    "weathercondition",
    CAST("track_type_code" AS BIGINT) AS track_type_code,
    "tracktype",
    "trackname",
    "trackclass",
    "trackdensity",
    "train_direction_code",
    "traindirection",
    "equipment_type_code",
    "equipmenttype",
    "equipmentattended",
    "trainnumber",
    CAST("trainspeed" AS BIGINT) AS trainspeed,
    "recordedestimatedspeed",
    CAST("maximumspeed" AS BIGINT) AS maximumspeed,
    CAST("grosstonnage" AS BIGINT) AS grosstonnage,
    CAST("signalization_code" AS BIGINT) AS signalization_code,
    "signalization",
    "method_of_operation_code",
    "methodofoperation",
    "adjunct_code_1",
    "adjunctname1",
    "adjunct_code_2",
    "adjunctname2",
    "adjunct_code_3",
    "adjunctname3",
    "remote_control_locomotive_code",
    "remotecontrollocomotive",
    "firstcarinitials",
    "firstcarnumber",
    CAST("firstcarposition" AS BIGINT) AS firstcarposition,
    "firstcarloaded",
    "causingcarinitials",
    "causingcarnumber",
    CAST("causingcarposition" AS BIGINT) AS causingcarposition,
    "causingcarloaded",
    CAST("positivealcoholtests" AS BIGINT) AS positivealcoholtests,
    CAST("positivedrugtests" AS BIGINT) AS positivedrugtests,
    "passengerstransported",
    CAST("headendlocomotives" AS BIGINT) AS headendlocomotives,
    CAST("midtrainmanuallocomotives" AS BIGINT) AS midtrainmanuallocomotives,
    CAST("midtrainremotelocomotives" AS BIGINT) AS midtrainremotelocomotives,
    CAST("rearendmanuallocomotives" AS BIGINT) AS rearendmanuallocomotives,
    CAST("rearendremotelocomotives" AS BIGINT) AS rearendremotelocomotives,
    CAST("derailedheadendlocomotives" AS BIGINT) AS derailedheadendlocomotives,
    CAST("derailedmidtrainmanuallo" AS BIGINT) AS derailedmidtrainmanuallo,
    CAST("derailedmidtrainremotelo" AS BIGINT) AS derailedmidtrainremotelo,
    CAST("derailedrearendmanualloc" AS BIGINT) AS derailedrearendmanualloc,
    CAST("derailedrearendremoteloc" AS BIGINT) AS derailedrearendremoteloc,
    CAST("loadedfreightcars" AS BIGINT) AS loadedfreightcars,
    CAST("loadedpassengercars" AS BIGINT) AS loadedpassengercars,
    CAST("emptyfreightcars" AS BIGINT) AS emptyfreightcars,
    CAST("emptypassengercars" AS BIGINT) AS emptypassengercars,
    CAST("cabooses" AS BIGINT) AS cabooses,
    CAST("derailedloadedfreightcars" AS BIGINT) AS derailedloadedfreightcars,
    CAST("derailedloadedpassengercars" AS BIGINT) AS derailedloadedpassengercars,
    CAST("derailedemptyfreightcars" AS BIGINT) AS derailedemptyfreightcars,
    CAST("derailedemptypassengercars" AS BIGINT) AS derailedemptypassengercars,
    CAST("derailedcabooses" AS BIGINT) AS derailedcabooses,
    CAST("equipmentdamagecost" AS BIGINT) AS equipmentdamagecost,
    CAST("trackdamagecost" AS BIGINT) AS trackdamagecost,
    CAST("totaldamagecost" AS BIGINT) AS totaldamagecost,
    "primaryaccidentcausecode",
    "primaryaccidentcause",
    "contributingaccidentcausecode",
    "contributingaccidentcause",
    "accidentcausecode",
    "accidentcause",
    CAST("engineersonduty" AS BIGINT) AS engineersonduty,
    CAST("firemenonduty" AS BIGINT) AS firemenonduty,
    CAST("conductorsonduty" AS BIGINT) AS conductorsonduty,
    CAST("brakemenonduty" AS BIGINT) AS brakemenonduty,
    CAST("hoursengineersonduty" AS BIGINT) AS hoursengineersonduty,
    CAST("minutesengineersonduty" AS BIGINT) AS minutesengineersonduty,
    CAST("hoursconductorsonduty" AS BIGINT) AS hoursconductorsonduty,
    CAST("minutesconductorsonduty" AS BIGINT) AS minutesconductorsonduty,
    CAST("railroademployeeskilled" AS BIGINT) AS railroademployeeskilled,
    CAST("railroademployeesinjured" AS BIGINT) AS railroademployeesinjured,
    CAST("passengerskilled" AS BIGINT) AS passengerskilled,
    CAST("passengersinjured" AS BIGINT) AS passengersinjured,
    CAST("otherskilled" AS BIGINT) AS otherskilled,
    CAST("othersinjured" AS BIGINT) AS othersinjured,
    CAST("reportingrailroadfatalitiesfor55a" AS BIGINT) AS reportingrailroadfatalitiesfor55a,
    CAST("reportingrailroadinjuriesfor55a" AS BIGINT) AS reportingrailroadinjuriesfor55a,
    CAST("totalpersonskilled" AS BIGINT) AS totalpersonskilled,
    CAST("totalpersonsinjured" AS BIGINT) AS totalpersonsinjured,
    CAST("totalkilledform54" AS BIGINT) AS totalkilledform54,
    CAST("totalinjuredform54" AS BIGINT) AS totalinjuredform54,
    "specialstudy1",
    "specialstudy2",
    CAST("latitude" AS DOUBLE) AS latitude,
    CAST("longitude" AS DOUBLE) AS longitude,
    "narrative",
    "jointtracktype",
    "jointtrackclass",
    "classcode",
    "class",
    CAST("jointcd" AS BIGINT) AS jointcd,
    "incidentkey",
    "reportkey",
    "reporting_railroad_class",
    "reporting_railroad_smt_grouping",
    "reporting_parent_railroad_code",
    "reporting_parent_railroad_name",
    "reporting_railroad_holding_company",
    "reporting_railroad_individual_class",
    "reporting_railroad_passenger",
    "reporting_railroad_commuter",
    "reporting_railroad_switching_terminal",
    "reporting_railroad_tourist",
    "reporting_railroad_freight",
    "reporting_railroad_short_line",
    "location"
FROM "fra-jm8x-ccxs"
