-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "id",
    "agricultureStructureIndicator" AS agriculturestructureindicator,
    "asOfDate" AS asofdate,
    "basementEnclosureCrawlspaceType" AS basementenclosurecrawlspacetype,
    "policyCount" AS policycount,
    "crsClassificationCode" AS crsclassificationcode,
    "dateOfLoss" AS dateofloss,
    "elevatedBuildingIndicator" AS elevatedbuildingindicator,
    "elevationCertificateIndicator" AS elevationcertificateindicator,
    "elevationDifference" AS elevationdifference,
    "baseFloodElevation" AS basefloodelevation,
    "ratedFloodZone" AS ratedfloodzone,
    "houseWorship" AS houseworship,
    "locationOfContents" AS locationofcontents,
    "lowestAdjacentGrade" AS lowestadjacentgrade,
    "lowestFloorElevation" AS lowestfloorelevation,
    "numberOfFloorsInTheInsuredBuilding" AS numberoffloorsintheinsuredbuilding,
    "nonProfitIndicator" AS nonprofitindicator,
    "obstructionType" AS obstructiontype,
    "occupancyType" AS occupancytype,
    "originalConstructionDate" AS originalconstructiondate,
    "originalNBDate" AS originalnbdate,
    "amountPaidOnBuildingClaim" AS amountpaidonbuildingclaim,
    "amountPaidOnContentsClaim" AS amountpaidoncontentsclaim,
    "amountPaidOnIncreasedCostOfComplianceClaim" AS amountpaidonincreasedcostofcomplianceclaim,
    "postFIRMConstructionIndicator" AS postfirmconstructionindicator,
    "rateMethod" AS ratemethod,
    "smallBusinessIndicatorBuilding" AS smallbusinessindicatorbuilding,
    "totalBuildingInsuranceCoverage" AS totalbuildinginsurancecoverage,
    "totalContentsInsuranceCoverage" AS totalcontentsinsurancecoverage,
    "yearOfLoss" AS yearofloss,
    "primaryResidenceIndicator" AS primaryresidenceindicator,
    "buildingDamageAmount" AS buildingdamageamount,
    "buildingDeductibleCode" AS buildingdeductiblecode,
    "netBuildingPaymentAmount" AS netbuildingpaymentamount,
    "buildingPropertyValue" AS buildingpropertyvalue,
    "causeOfDamage" AS causeofdamage,
    "condominiumCoverageTypeCode" AS condominiumcoveragetypecode,
    "contentsDamageAmount" AS contentsdamageamount,
    "contentsDeductibleCode" AS contentsdeductiblecode,
    "netContentsPaymentAmount" AS netcontentspaymentamount,
    "contentsPropertyValue" AS contentspropertyvalue,
    "disasterAssistanceCoverageRequired" AS disasterassistancecoveragerequired,
    "eventDesignationNumber" AS eventdesignationnumber,
    "ficoNumber" AS ficonumber,
    "floodCharacteristicsIndicator" AS floodcharacteristicsindicator,
    "floodWaterDuration" AS floodwaterduration,
    "floodproofedIndicator" AS floodproofedindicator,
    "floodEvent" AS floodevent,
    "iccCoverage" AS icccoverage,
    "netIccPaymentAmount" AS neticcpaymentamount,
    "nfipRatedCommunityNumber" AS nfipratedcommunitynumber,
    "nfipCommunityNumberCurrent" AS nfipcommunitynumbercurrent,
    "nfipCommunityName" AS nfipcommunityname,
    "nonPaymentReasonContents" AS nonpaymentreasoncontents,
    "nonPaymentReasonBuilding" AS nonpaymentreasonbuilding,
    "numberOfUnits" AS numberofunits,
    "buildingReplacementCost" AS buildingreplacementcost,
    "contentsReplacementCost" AS contentsreplacementcost,
    "replacementCostBasis" AS replacementcostbasis,
    "stateOwnedIndicator" AS stateownedindicator,
    "waterDepth" AS waterdepth,
    "floodZoneCurrent" AS floodzonecurrent,
    "buildingDescriptionCode" AS buildingdescriptioncode,
    "rentalPropertyIndicator" AS rentalpropertyindicator,
    "state",
    "reportedCity" AS reportedcity,
    "reportedZipCode" AS reportedzipcode,
    "countyCode" AS countycode,
    "censusTract" AS censustract,
    "censusBlockGroupFips" AS censusblockgroupfips,
    "latitude",
    "longitude"
FROM "fema-fimanfipclaims"
