-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_file",
    "row_number",
    CAST("year" AS BIGINT) AS year,
    "stufe_des_steuerbaren_umsatzes",
    "politischer_bezirk_ebene_1",
    "rechtsform",
    "number_of_vat_assessments_entities",
    "entity_count_turnover_within_the_scope_of_vat",
    "turnover_within_the_scope_of_vat_eur",
    "fallzahl_ums_tze_f_r_die_die_steuerschuld_auf_den_leistungsempf_nger_bergegangen_ist",
    "ums_tze_f_r_die_die_steuerschuld_auf_den_leistungsempf_nger_bergegangen_ist_eur",
    "entity_count_turnover_free_of_vat",
    "turnover_free_of_vat_eur",
    "entity_count_turnover_free_of_vat_from_extra_eu_exports",
    "turnover_free_of_vat_from_extra_eu_exports_eur",
    "entity_count_turnover_free_of_vat_from_intra_eu_exports",
    "turnover_free_of_vat_from_intra_eu_exports_eur",
    "entity_count_other_exemptions_from_vat",
    "other_exemptions_from_vat_eur",
    "entity_count_deductable_input_vat_total",
    "deductable_input_vat_total_eur",
    "entity_count_turnover_subject_to_vat",
    "turnover_subject_to_vat_eur",
    "entity_count_turnover_subject_to_vat_at_20",
    "turnover_subject_to_vat_at_20_eur",
    "entity_count_turnover_subject_to_vat_at_10",
    "turnover_subject_to_vat_at_10_eur",
    "entity_count_turnover_subject_to_vat_at_13",
    "turnover_subject_to_vat_at_13_eur",
    "entity_count_gross_value_added_tax",
    "gross_value_added_tax_eur",
    "entity_count_intra_eu_imports_subject_to_vat_total",
    "intra_eu_imports_subject_to_vat_total_eur",
    "entity_count_intra_eu_imports_subject_to_vat_at_20",
    "intra_eu_imports_subject_to_vat_at_20_eur",
    "entity_count_intra_eu_imports_subject_to_vat_at_10",
    "intra_eu_imports_subject_to_vat_at_10_eur",
    "entity_count_balance_of_debits_and_credits",
    "balance_of_debits_and_credits_eur"
FROM "statistics-austria-ogd--steuer-ust-ust-2"
