-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_file",
    "row_number",
    "time",
    "producer_price_index_2021_100_in_total",
    "mining_and_quarrying_b",
    "manufactured_products_c",
    "electricity_gas_steam_and_air_conditioning_d",
    "water_supply_except_sewerage_waste_management_and_remediation_services_e",
    "coal_and_lignite_05",
    "crude_petroleum_and_natural_gas_06",
    "metal_ores_07",
    "other_mining_and_quarrying_products_08",
    "mining_support_services_09",
    "food_products_10",
    "beverages_11",
    "tobacco_products_12",
    "textiles_13",
    "wearing_apparel_14",
    "leather_and_related_products_15",
    "wood_and_of_products_of_wood_and_cork_exc_furniture_articles_of_straw_and_plaiting_materials_16",
    "paper_and_paper_products_17",
    "printing_and_reproduction_of_recorded_media_18",
    "coke_and_refinded_petroleum_products_19",
    "chemicals_and_chemical_products_20",
    "basic_pharmaceutical_products_and_pharmaceutical_preparations_21",
    "rubber_and_plastic_products_22",
    "other_non_metallic_mineral_products_23",
    "basic_metals_24",
    "fabricated_metal_products_exc_machinery_a_equipment_25",
    "computer_electronic_and_optical_products_26",
    "electrical_equipment_27",
    "machinery_and_equipment_n_e_c_28",
    "motor_vehicles_trailers_and_semi_trailers_29",
    "other_transport_equipment_30",
    "furniture_31",
    "other_manufacturing_goods_32",
    "repair_and_installation_services_of_machinery_and_equipment_33",
    "electricity_gas_steam_and_air_conditioning_35",
    "natural_water_water_treatment_and_supply_services_36"
FROM "statistics-austria-ogd-epi2021cpa15-epi-2021-oecpa-1"
