-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_file",
    "row_number",
    "reporting_period",
    "origin_4",
    "index_of_new_orders_in_total",
    "manufacturing_c",
    "construction_f",
    "construction_buildings_f_hb",
    "construction_civil_engineering_f_tb",
    "intermediate_goods_a",
    "capital_goods_b",
    "durable_consumer_goods_cd",
    "non_durable_consumer_goods_cn",
    "consumer_goods_cd_cn",
    "total_without_construction_and_energy_b_c",
    "total_without_energy_b_c_f",
    "total_without_construction_b_c_d_e",
    "total_1_b_c_d_and_f_without_353_bcdf",
    "total_2_b_to_d_without_353_bcd1",
    "total_4_07_to_09_10_to_18_20_to_33_bc1",
    "total_5_07_to_09_13_to_18_20_to_33_bc2",
    "mig_consumergoods_kg_10_11_12_106_109_cdcn1",
    "manufacture_of_textiles_and_wearing_apparel_x2",
    "manufacture_of_paper_and_paper_products_and_reproduction_of_recorded_media_x3",
    "manufacture_of_chemicals_and_chemical_products_and_basic_pharmaceutical_products_and_pharmaceutical_preparations_x4",
    "manufacture_of_basic_metals_and_fabricated_metal_products_except_machinery_and_equipment_x5",
    "manufacture_of_computer_electronic_and_optical_products_and_electrical_equipment_x6",
    "manufacture_of_motor_vehicles_trailers_and_semi_trailers_and_other_transport_equipment_x7",
    "manufacture_of_textiles_13",
    "manufacture_of_wearing_apparel_14",
    "manufacture_of_paper_and_paper_products_17",
    "manufact_of_chemicals_and_chem_products_20",
    "manuf_o_basic_pharm_prod_a_pharm_prepar_21",
    "manufacture_of_basic_metals_24",
    "man_o_fabricat_metal_prod_exc_mach_a_equ_25",
    "manuf_o_computer_electronic_a_opt_prod_26",
    "manufacture_of_electrical_equipment_27",
    "manufact_of_machinery_a_equipment_n_e_c_28",
    "man_o_motor_veh_trailers_a_semi_trail_29",
    "manufacture_of_oth_transport_equipment_30",
    "construction_of_buildings_41",
    "civil_engineering_42",
    "specialised_construction_activities_43"
FROM "statistics-austria-ogd-kjiauftragseingangsindex2021-kjid2021-aegi-1"
