-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_file",
    "row_number",
    "time_section",
    "industries_nace_and_size_classes",
    "all_enterprises_with_technological_innovations",
    "enterprises_with_technological_innovations_in_house_r_d",
    "enterprises_with_technological_innovations_in_house_r_d_as_of_all_enterprises" AS entrprss_tchnlgcl_innvtns_in_hs_r_d_as_of_all_entrprss,
    "enterprises_with_technological_innovations_external_r_d",
    "enterprises_with_technological_innovations_external_r_d_as_of_all_enterprises" AS entrprss_tchnlgcl_innvtns_extrnl_r_d_as_of_all_entrprss,
    "enterprises_with_technological_innovations_acquisition_of_machinery_equipment" AS entrprss_tchnlgcl_innvtns_acqstn_of_mchnry_eqpmnt,
    "enterprises_with_technological_innovations_acquisition_of_machinery_equipment_as_of_all_enterprises" AS entrprss_tchnlgcl_innvtns_acqstn_of_mchnry_eqpmnt_as_of_all_entr,
    "enterprises_with_technological_innovations_acquisition_of_external_knowledge" AS entrprss_tchnlgcl_innvtns_acqstn_of_extrnl_knwldg,
    "enterprises_with_technological_innovations_acquisition_of_external_knowledge_as_of_all_enterprises" AS entrprss_tchnlgcl_innvtns_acqstn_of_extrnl_knwldg_as_of_all_entr,
    "enterprises_with_technological_innovations_training_for_innovative_activities" AS entrprss_tchnlgcl_innvtns_trnng_fr_innvtv_actvts,
    "enterprises_with_technological_innovations_training_for_innovative_activities_as_of_all_enterprises" AS entrprss_tchnlgcl_innvtns_trnng_fr_innvtv_actvts_as_of_all_entrp,
    "enterprises_with_technological_innovations_market_introduction_of_innovations" AS entrprss_tchnlgcl_innvtns_mrkt_intrdctn_of_innvtns,
    "enterprises_with_technological_innovations_market_introduction_of_innovations_as_of_all_enterprises" AS entrprss_tchnlgcl_innvtns_mrkt_intrdctn_of_innvtns_as_of_all_ent,
    "enterprises_with_technological_innovations_design",
    "enterprises_with_technological_innovations_design_as_of_all_enterprises" AS entrprss_tchnlgcl_innvtns_dsgn_as_of_all_entrprss,
    "enterprises_with_technological_innovations_other_innov_activities" AS enterprises_technological_innovations_other_innov_activities,
    "enterprises_with_technological_innovations_other_innov_activities_as_of_all_enterprises" AS entrprss_tchnlgcl_innvtns_othr_innv_actvts_as_of_all_entrprss,
    "total_innovation_expenditure_in_1_000_euro",
    "innovation_expenditure_in_1_000_euro_in_house_r_d",
    "innovation_expenditure_in_1_000_euro_external_r_d",
    "innovation_expenditure_in_1_000_euro_acquisition_of_machinery_equipment_software_buildings" AS innvtn_expndtr_in_1_000_er_acqstn_of_mchnry_eqpmnt_sftwr_bldngs,
    "innovation_expenditure_in_1_000_euro_acquisition_of_external_knowledge" AS innvtn_expndtr_in_1_000_er_acqstn_of_extrnl_knwldg,
    "innovation_expenditure_in_1_000_euro_other_innovation_expenditure" AS innvtn_expndtr_in_1_000_er_othr_innvtn_expndtr
FROM "statistics-austria-ogd-innov005-cis-005-unt-innovation-1"
