-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "source_file",
    "row_number",
    CAST("year_starting_1995" AS BIGINT) AS year_starting_1995,
    "federal_provices",
    "total_area_km",
    "population_annual_average",
    "private_households",
    "r_d_intensity_in_of_gdp",
    "employed_persons_ilo_definition",
    "employment_rate_15_64_y_ilo_definition",
    "unemployed_ilo_definition",
    "umemployment_rate_ilo_definition",
    "compensation_of_employees_national_accounts_concept_in_eur_million",
    "compensation_of_employees_per_employee_national_accounts_concept_in_eur",
    "gross_regional_product_nominal_in_eur_million",
    "gross_regional_product_nominal_per_inhabitant_in_eur",
    "gross_value_added_at_basic_prices_current_prices_in_eur_million",
    "gross_value_added_of_agriculture_and_forestry_in_eur_million",
    "disposable_income_of_private_households_in_eur_million",
    "disposable_income_of_private_households_per_inhabitant_in_eur",
    "number_of_industrial_establishments_nace_rev_1_1_c_e",
    "industrial_establishments_per_1_000_inhabitants_nace_rev_1_1_c_e",
    "employed_persons_in_industry_nace_rev_1_1_c_e",
    "gross_value_added_at_basic_price_industry_nace_rev_1_1_c_e_nominal_in_eur_million",
    "number_of_industrial_establishments_nace_rev_2_b_e",
    "industrial_establishments_per_1_000_inhabitants_nace_rev_2_b_e",
    "employed_persons_in_industry_nace_rev_2_b_e",
    "gross_value_added_at_basic_prices_industry_nace_rev_2_b_e_current_prices_in_eur_million",
    "number_of_construction_establishments_nace_rev_1_1_f",
    "construction_establishments_per_1_000_inhabitants_nace_rev_1_1_f",
    "employed_persons_in_construction_nace_rev_1_1_f",
    "gross_value_added_at_basic_price_construction_nace_rev_1_1_f_nominal_in_eur_million",
    "number_of_construction_establishments_nace_rev_2_f",
    "construction_establishments_per_1_000_inhabitants_nace_rev_2",
    "employed_persons_in_construction_nace_rev_2_f",
    "gross_value_added_at_basic_prices_construction_nace_rev_2_f_current_prices_in_million_eur",
    "number_of_trade_establishments_nace_rev_1_1_g",
    "trade_establishments_per_1_000_inhabitants_nace_rev_1_1_g",
    "employed_persons_in_trade_nace_rev_1_1_g",
    "gross_value_added_at_basic_price_trade_nace_rev_1_1_g_nominal_in_million_eur",
    "number_of_trade_establishments_nace_rev_2_g",
    "trade_establishments_per_1_000_inhabitants_nace_rev_2_g",
    "employed_persons_in_trade_nace_rev_2_g",
    "gross_value_added_at_basic_prices_trade_nace_rev_2_g_current_prices_in_eur_million",
    "overnight_stays",
    "accomodation_facilities",
    "average_duration_of_stay_in_nights",
    "average_accommodation_capacity_based_on_beds",
    "tourism_intensity_per_inhabitant_based_on_overnight_stays",
    "imports_in_1_000_eur",
    "exports_in_1_000_eur",
    "balance_of_foreign_trade_in_1_000_eur"
FROM "statistics-austria-ogd-watlas2-watlas-2"
