-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "record_date",
    CAST(NULLIF("row_index_nbr", 'null') AS BIGINT) AS row_index_nbr,
    CAST(NULLIF("net_offset_cnt", 'null') AS BIGINT) AS net_offset_cnt,
    CAST(NULLIF("net_offset_amt", 'null') AS DOUBLE) AS net_offset_amt,
    "mixed_stream",
    "state_or_agency",
    "month_nm",
    "agency_full_cd_nm",
    CAST(NULLIF("net_dms_fee_amt", 'null') AS DOUBLE) AS net_dms_fee_amt,
    CAST(NULLIF("cycle_nbr", 'null') AS BIGINT) AS cycle_nbr,
    CAST(NULLIF("cycle", 'null') AS BIGINT) AS cycle,
    "cycle_end_dt",
    "cycle_start_dt",
    "agency_nm",
    "agency_id",
    "agency",
    "agency_site",
    "agency_site_cd",
    "agency_site_id",
    "payment_category",
    "payment_type_cd",
    "payment_agency_nm",
    "payment_type",
    "payment_source",
    "debt_category",
    "payment_agency_id",
    "sent_to_acct_dt",
    CAST(NULLIF("fiscal_year", 'null') AS BIGINT) AS fiscal_year,
    "fiscal_month",
    CAST(NULLIF("offset_cnt", 'null') AS BIGINT) AS offset_cnt,
    CAST(NULLIF("offset_amt", 'null') AS DOUBLE) AS offset_amt,
    CAST(NULLIF("reversal_cnt", 'null') AS BIGINT) AS reversal_cnt,
    CAST(NULLIF("reversal_amt", 'null') AS DOUBLE) AS reversal_amt,
    "state_cd",
    "reversal_requestor",
    "payment_source_cd",
    CAST(NULLIF("record_fiscal_year", 'null') AS BIGINT) AS record_fiscal_year,
    CAST(NULLIF("record_fiscal_quarter", 'null') AS BIGINT) AS record_fiscal_quarter,
    CAST(NULLIF("record_calendar_year", 'null') AS BIGINT) AS record_calendar_year,
    CAST(NULLIF("record_calendar_quarter", 'null') AS BIGINT) AS record_calendar_quarter,
    "record_calendar_month",
    "record_calendar_day"
FROM "us-treasury-fiscal-data-v1-debt-treasury-offset-program"
