-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "hh_id",
    "is_complete",
    "num_trips",
    "person_id",
    "person_num",
    "is_participant",
    "day_id",
    "day_num",
    "travel_date",
    "travel_dow",
    "hh_day_complete",
    "num_complete_trip_surveys",
    "summary_complete",
    "begin_day",
    "end_day",
    "no_travel_1",
    "no_travel_2",
    "no_travel_3",
    "no_travel_4",
    "no_travel_5",
    "no_travel_6",
    "no_travel_7",
    "no_travel_8",
    "no_travel_11",
    "no_travel_12",
    "no_travel_13",
    "no_travel_99",
    "delivery_2",
    "delivery_4",
    "delivery_5",
    "delivery_6",
    "delivery_7",
    "delivery_8",
    "delivery_9",
    "delivery_996",
    "shop_online",
    "telecommute_time",
    "day_weight_zonal",
    "day_weight_citywide"
FROM "nyc-open-data-naav-ygga"
