-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "data_os_of_date",
    "geography_type",
    "geography",
    "programtype",
    "female_count",
    "female_percentage",
    "male_count",
    "male_percentage",
    "not_sure_count",
    "not_sure_percentage",
    "x_not_male_or_female_count",
    "x_not_male_or_female_percentage",
    "another_gender_count",
    "another_gender_percentage",
    "decline_to_answer_count",
    "decline_to_answer_percentage",
    "do_not_understand_the_question_count",
    "do_not_understand_the_question_percentage",
    "female_gender_identity_count",
    "female_gender_identity_percentage",
    "gender_nonconforming_count",
    "gender_nonconforming_percentage",
    "male_gender_identity_count",
    "male_gender_identity_percentage",
    "multigender_identity_count",
    "multigender_identity_percentage",
    "nonbinary_not_female_or_male_count",
    "nonbinary_not_female_or_male_percentage",
    "not_sure_gender_identity_count",
    "not_sure_gender_identity_percentage",
    "two_spirit_native_americanfirst_nations_count",
    "two_spirit_native_americanfirst_nations_percentage",
    "american_indian_or_alaskan_native_count",
    "american_indian_or_alaskan_native_percentage",
    "asian_count",
    "asian_percentage",
    "black_or_african_american_count",
    "black_or_african_american_percentage",
    "middle_eastern_and_north_african_count",
    "middle_eastern_and_north_african_percentage",
    "multirace_count",
    "multirace_percentage",
    "native_hawaiian_or_other_pacific_islander_count",
    "native_hawaiian_or_other_pacific_islander_percentage",
    "other_count",
    "other_percentage",
    "white_or_caucasian_count",
    "white_or_caucasian_percentage",
    "hispanic_or_latinoa_count",
    "hispanic_or_latinoa_percentage",
    "not_hispanic_or_latinoa_count",
    "not_hispanic_or_latinoa_percentage"
FROM "nyc-open-data-k9kq-67vm"
