-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "job_filing_number",
    "work_permit",
    "sequence_number",
    "filing_reason",
    "house_no",
    "street_name",
    "borough",
    "lot",
    "bin",
    "block",
    "c_b_no",
    "aptcondo_nos",
    "work_on_floor",
    "work_type",
    "permittees_license_type",
    "applicant_license",
    "applicant_first_name",
    "applicant_middle_name",
    "applicant_last_name",
    "applicant_business_name",
    "applicant_business_address",
    "filing_representative_first_name",
    "filing_representative_middle_initial",
    "filing_representative_last_name",
    "filing_representative_business_name",
    "approved_date",
    "issued_date",
    "expired_date",
    "job_description",
    "estimated_job_costs",
    "owner_business_name",
    "owner_name",
    "owner_street_address",
    "owner_city",
    "owner_state",
    "owner_zip_code",
    "permit_status",
    "tracking_number",
    "zip_code",
    "latitude",
    "longitude",
    "community_board",
    "council_district",
    "bbl",
    "census_tract_2020",
    "neighborhood_tabulation_area_nta_2020"
FROM "nyc-open-data-rbx6-tga4"
