-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "report_year",
    "agency_name",
    "digital_amplification_advertised_agency_data_in_a_public_email_newsletter_at_least_twice_per_year",
    "digital_amplification_advertised_nyc_open_data_on_your_agencys_website",
    "digital_amplification_sent_at_least_one_tweet_per_month_about_your_agencys_existing_open_data_assets",
    "digital_amplification_tweeted_whenever_a_new_open_data_asset_is_published",
    "event_engagement_produced_a_curriculum_to_be_used_to_engage_an_audience_around_your_agencys_open_data_assets_at_a_public_event",
    "event_engagement_produced_your_own_event_to_discuss_your_agencys_open_data_assets_this_could_be_a_1_hour_workshop_a_24_hour_hackathon_or_something_else",
    "public_speaking_identified_someone_from_your_agency_to_speak_about_your_agencys_open_data_assets_at_an_event_as_a_part_of_open_data_week",
    "public_speaking_presented_about_your_agencys_open_data_assets_in_an_academic_or_school_environment",
    "public_speaking_shared_open_data_swag_and_informational_onepager_with_your_community_engagement_liaisons_to_share_at_your_agencys_existing_community_touchpoints",
    "public_speaking_spoke_at_a_partners_event_in_nyc_about_your_agencys_open_data_assets_eg_community_boards",
    "public_speaking_spoke_at_an_event_hosted_by_your_agency_about_your_agencys_open_data_assets",
    "storytelling_added_a_project_made_by_your_agency_to_the_nyc_open_data_project_gallery",
    "storytelling_included_your_agencys_open_data_commitments_in_a_report_published_by_your_agency",
    "storytelling_posted_about_your_agencys_open_data_assets_on_your_agencys_facebook_or_linkedin_channels",
    "storytelling_published_a_blog_post_about_your_agencys_open_data_assets",
    "storytelling_published_a_video_describing_your_agencys_data_assets_or_a_recent_data_asset_release",
    "usercentered_research_developed_and_convened_a_focus_group_or_advisory_council_of_users_of_your_agencys_open_data_to_learn_more_about_how_they_use_your_data_assets_and_to_request_feedback",
    "usercentered_research_engaged_a_professional_internally_or_externally_to_develop_user_personas_and_better_engage_your_users",
    "other_civic_engagement_activity_not_listed",
    "notes_on_other_civic_engagement_activities_if_applicable"
FROM "nyc-open-data-keb3-v9xt"
