-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "queens_condominium_property_boroblocklot",
    "queens_condominium_property_condo_section",
    "queens_condominium_property_address",
    "borough",
    "postcode",
    "latitude",
    "longitude",
    "community_board",
    "council_district",
    "census_tract",
    "bin",
    "bbl",
    "nta",
    "queens_condominium_property_neighborhood",
    "queens_condominium_property_building_classification",
    "queens_condominium_property_total_units",
    "queens_condominium_property_year_built",
    "queens_condominium_property_gross_sqft",
    "queens_condominium_property_est_gross_income",
    "queens_condominium_property_gross_income_per_sqft",
    "queens_condominium_property_full_market_value",
    "queens_condominium_property_market_value_per_sqft",
    "comparable_rental_1_boroblocklot",
    "comparable_rental_1_address",
    "comparable_rental_1_neighborhood",
    "comparable_rental_1_building_classification",
    "comparable_rental_1_total_units",
    "comparable_rental_1_year_built",
    "comparable_rental_1_gross_sqft",
    "comparable_rental_1_est_gross_income",
    "comparable_rental_1_gross_income_per_sqft",
    "comparable_rental_1_full_market_value",
    "comparable_rental_1_market_value_per_sqft",
    "comparable_rental_1_dist_from_coop_in_miles",
    "comparable_rental_2_boroblocklot",
    "comparable_rental_2_address",
    "comparable_rental_2_neighborhood",
    "comparable_rental_2_building_classification",
    "comparable_rental_2_total_units",
    "comparable_rental_2_year_built",
    "comparable_rental_2_gross_sqft",
    "comparable_rental_2_est_gross_income",
    "comparable_rental_2_gross_income_per_sqft",
    "comparable_rental_2_full_market_value",
    "comparable_rental_2_market_value_per_sqft",
    "comparable_rental_2_dist_from_coop_in_miles"
FROM "nyc-open-data-m59i-mqex"
