-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "project_name",
    "project_received_date",
    "project_id_number_op",
    "project_description",
    "impacted_park_ids",
    "impacted_park_names",
    "address_or_intersection",
    "borough",
    "multisite_project",
    "sponsoring_entity",
    "primary_scope_of_work",
    "impacted_parks_divisions",
    "park_impact_type",
    "contract_value_op",
    "current_phase",
    "scoping_initiatedkickoff_op",
    "scoping_response_due_date_op",
    "design_consultant_op",
    "pdc_approval_required",
    "preliminary_pdc_approval",
    "final_pdc_approval",
    "mass_mailing_1_received_date",
    "mass_mailing_2_received_date",
    "mass_mailing_3_received_date",
    "design_completion_date_op",
    "construction_manager_op",
    "construction_manager_company_op",
    "construction_kickoff",
    "expected_construction_end_date_op",
    strptime("actual_construction_end_date_op", '%d/%m/%Y')::DATE AS actual_construction_end_date_op,
    "contractor_for_construction_permit_firm_name",
    "construction_permit_request_received_date",
    "construction_permit_id",
    "latest_site_visit",
    "forestry_permit_status",
    "forestry_permit_id_number",
    "construction_permit_special_conditions",
    "borough_approval_date",
    "permit_issuance_date",
    "permit_start_date",
    "original_permit_expiration_date",
    "latest_permit_extensionamendment_request_date",
    "latest_permit_extensionamendment_issuance_date",
    "latest_permit_expiration_date",
    "permit_amendment_content",
    "exploratory_permit_id",
    "substantial_completion_date",
    "final_inspection_date",
    "latest_inspection_site_visit",
    "punchlist_generated",
    "conditional_letter_issued",
    "final_acceptance_of_park_by_borough",
    "final_acceptance_letter_date",
    "created",
    "modified",
    "coordinates"
FROM "nyc-open-data-wye7-nyek"
