-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "year_published",
    "puma",
    "borough",
    "neighborhoods",
    "cd",
    "_join" AS join,
    "nyc_poverty_rate",
    "median_income",
    "perc_white",
    "perc_black",
    "perc_asian",
    "perc_other",
    "perc_hispanic",
    "goal",
    "goalname",
    "goalfullname",
    "totaloutcome",
    "goalrank",
    "indexscore",
    "scorerank",
    "ind1",
    "ind1outcome",
    "ind1rank",
    "ind1definition",
    "ind2",
    "ind2outcome",
    "ind2rank",
    "ind2definition",
    "ind3",
    "ind3outcome",
    "ind3rank",
    "ind3definition",
    "ind4",
    "ind4outcome",
    "ind4rank",
    "ind4definition",
    "ind5",
    "ind5outcome",
    "ind5rank",
    "ind5definition",
    "ind6",
    "ind6outcome",
    "ind6rank",
    "ind6definition",
    "ind7",
    "ind7outcome",
    "ind7rank",
    "ind7definition",
    "ind8",
    "ind8outcome",
    "ind8rank",
    "ind8definition"
FROM "nyc-open-data-r3dx-pew9"
