-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "_program" AS program,
    "statecity_section8_flag",
    "total_families",
    "total_female_headed_families",
    "total_male_headed_families",
    "total_population",
    "average_family_size",
    "total_minors_under_18",
    "average_minors_per_family",
    "total_minors_as_percent_of_population",
    "all_average_total_gross_income",
    "all_average_gross_rent",
    "total_hoh_62_years_and_over",
    "total_hoh_62_years_and_over_as_percent_of_families",
    "total_female_headed_hoh_62_years_and_over",
    "total_male_headed_hoh_62_years_and_over",
    "total_elderly_single_person_families",
    "total_elderly_population",
    "total_62_years_and_over_as_percent_of_population",
    "total_families_on_welfare",
    "total_families_on_welfare_and_hoh_elderly",
    "total_families_on_full_welfare",
    "total_families_on_welfare_as_percent_of_families",
    "total_single_parentgrandparent_families_with_minors",
    "total_female_headed_single_parentgrandparent_with_minors",
    "total_male_headed_single_parentgrandparent_with_minors",
    "total_single_parentgrandparent_families_on_welfare",
    "total_single_parentgrandparent_with_minors_as_of_families",
    "total_families_1_or_more_employed",
    "total_families_1_or_more_employed_as_percent_of_families",
    "total_families_2nd_adult_employed",
    "all_families_average_years_in_public_housing",
    "residents_under_4",
    "residents_4_to_5",
    "residents_6_to_9",
    "residents_10_to_13",
    "residents_14_to_17",
    "residents_18_to_20",
    "residents_21_to_49",
    "residents_50_to_61",
    "residents_62_plus",
    "total_fixed_income_families",
    "total_fixed_income_families_as_percent_of_families"
FROM "nyc-open-data-5r5y-pvs3"
