-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "election",
    "officecd",
    "recipid",
    "canclass",
    "recipname",
    "committee",
    "filing",
    "schedule",
    "pageno",
    "sequenceno",
    "refno",
    "date",
    "refunddate",
    "_name" AS name,
    "c_code",
    "strno",
    "strname",
    "apartment",
    "boroughcd",
    "city",
    "state",
    "zip",
    "occupation",
    "empname",
    "empstrno",
    "empstrname",
    "empcity",
    "empstate",
    "amnt",
    "matchamnt",
    "prevamnt",
    "pay_method",
    "intermno",
    "intermname",
    "intstrno",
    "intstrnm",
    "intaptno",
    "intcity",
    "intst",
    "intzip",
    "intempname",
    "intempstno",
    "intempstnm",
    "intempcity",
    "intempst",
    "intoccupa",
    "purposecd",
    "exemptcd",
    "adjtypecd",
    "rr_ind",
    "seg_ind",
    "int_c_code"
FROM "nyc-open-data-kgzj-pjna"
