-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "dbn",
    "students_received_surveys",
    "school_name",
    "principal",
    "enrollment",
    "school_type",
    "parent_academic_expectations_score",
    "student_academic_expectations_score",
    "teacher_academic_expectations_score",
    "academic_expectations_score",
    "parent_communication_score",
    "student_communication_score",
    "teacher_communication_score",
    "communication_score",
    "parent_engagement_score",
    "student_engagement_score",
    "teacher_engagement_score",
    "engagement_score",
    "parent_safety_and_respect_score",
    "student_safety_and_respect_score",
    "teacher_safety_and_respect_score",
    "safety_and_respect_score",
    "parent_horizon_academic_expectations_score",
    "student_horizon_academic_expectations_score",
    "teacher_horizon_academic_expectations_score",
    "horizion_academic_expectations_score",
    "parent_horizon_communication_score",
    "student_horizon_communication_score",
    "teacher_horizon_communication_score",
    "horizion_communication_score",
    "parent_horizon_engagement_score",
    "student_horizon_engagement_score",
    "teacher_horizon_engagement_score",
    "horizion_engagement_score",
    "parent_horizon_safety_and_respect_score",
    "student_horizon_safety_and_respect_score",
    "teacher_horizon_safety_and_respect_score",
    "horizion_safety_and_respect_score"
FROM "nyc-open-data-ms9y-qe37"
