-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "calendar_year",
    "object_identification_number",
    "oversight_agency",
    "operator_name",
    "status",
    "location_name",
    "state",
    "borough",
    "postcode",
    "address_street",
    "full_location_address",
    "full_location_phone_number",
    "latitude",
    "longitude",
    "wireline_dwn",
    "wireline_up",
    "wifi_dwn",
    "wifi_up",
    "workstation_number",
    "target_population",
    "digital_literacy_support_staff",
    "mon_hours",
    "tue_hours",
    "wed_hours",
    "thu_hours",
    "fri_hours",
    "sat_hours",
    "sun_hours",
    "language_access",
    "wheelchair_accessible",
    "wheelchair_access_notes",
    "assistive_technology",
    "technology_related_courses",
    "productivity_tools_ex_using_word_excel_powerpoint_adobe_acrobat_etc",
    "job_readiness_ex_resume_help_job_search_etc",
    "education_ex_personal_growth_k12_supports_reading_research_etc",
    "creative_expression_ex_making_art_videos_blogs_websites_etc",
    "media_and_entertainment_ex_consuming_producing_etc",
    "certifications_ex_in_software_in_housing_in_professional_areas_etc",
    "digital_literacy",
    "digital_media_and_creativity",
    "telehealth_skills",
    "advanced_tech_skills",
    "general_tech_help",
    "device_loaning",
    "device_loaned",
    "type_of_device_available",
    "access_requirements",
    "access_notes",
    "url",
    "community_district",
    "council_district",
    "bin",
    "bbl",
    "census_tract_2020",
    "neighborhood_tabulation_area_nta_2020",
    "_location" AS location
FROM "nyc-open-data-sejx-2gn3"
