-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "download_pdf_report",
    "license_number",
    "industry_sector",
    "base_does_business_as",
    "base_name",
    "serving_areas",
    "year_base_opened",
    "green_taxi_service",
    "on_demand_service",
    "book_ahead_service",
    "phone",
    "website",
    "email",
    "booking_app",
    "_24_hours" AS 24_hours,
    "_2015_honor_roll_drivers" AS 2015_honor_roll_drivers,
    "_2015_honor_roll_base" AS 2015_honor_roll_base,
    "hosted_vision_zero_training",
    "vehicle_safety_technology_used",
    "base_provides_safety_training",
    "fatal_crashes",
    "fatal_crash_details",
    "injury_crashes_per_vehicle",
    "sector_average_injury_crashes_per_vehicle",
    "vehicle_safety_violations_per_vehicle",
    "sector_average_vehicle_safety_violations_per_vehicle",
    "base_safety_violations_per_vehicle",
    "sector_average_base_safety_violations_per_vehicle",
    "affiliated_vehicles",
    "average_vehicle_age",
    "sector_average_average_vehicle_age",
    "percent_hybrid_altfuel_vehicles",
    "percent_wheelchair_accessible_vehicles",
    "top_vehicle_models_1",
    "top_vehicle_models_2",
    "top_vehicle_models_3",
    "top_vehicle_models_4",
    "top_vehicle_models_5",
    "address",
    "latitude",
    "longitude",
    "_location" AS location,
    "postcode",
    "borough",
    "community_board",
    "council_district",
    "census_tract",
    "bin",
    "bbl",
    "nta"
FROM "nyc-open-data-ph7v-u5f3"
