-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "uniqueid",
    "inspectionid",
    "inspectiondate",
    "businessname",
    "typeofbusiness",
    "borough",
    "_location" AS location,
    "question1",
    "question2",
    "_2option1" AS 2option1,
    "_2option2" AS 2option2,
    "_2ticketnumber" AS 2ticketnumber,
    "_2novcode" AS 2novcode,
    "_2novnumber" AS 2novnumber,
    "question3",
    "_3option1" AS 3option1,
    "_3option2" AS 3option2,
    "_3ticketnumber" AS 3ticketnumber,
    "_3novcode" AS 3novcode,
    "_3novnumber" AS 3novnumber,
    "question4",
    "_4option1" AS 4option1,
    "_4option2" AS 4option2,
    "_4option3" AS 4option3,
    "_4option4" AS 4option4,
    "_4option5" AS 4option5,
    "_4option6" AS 4option6,
    "_4ticketnumber" AS 4ticketnumber,
    "_4novcode" AS 4novcode,
    "_4novnumber" AS 4novnumber,
    "question5",
    "_5option1" AS 5option1,
    "_5option2" AS 5option2,
    "_5option3" AS 5option3,
    "_5option4" AS 5option4,
    "_5option5" AS 5option5,
    "_5option6" AS 5option6,
    "_5option7" AS 5option7,
    "_5ticketnumber" AS 5ticketnumber,
    "_5novcode" AS 5novcode,
    "_5novnumber" AS 5novnumber,
    "complaintnumber",
    "postcode",
    "latitude",
    "longitude",
    "community_board",
    "council_district",
    "bin",
    "bbl",
    "census_tract_2020",
    "neighborhood_tabulation_area_nta_2020"
FROM "nyc-open-data-tg3t-nh4h"
