-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "nys_wms_rejection_code",
    "type_of_government_assistance",
    "calendar_year",
    "date",
    "total",
    "_1824" AS 1824,
    "_2544" AS 2544,
    "_4564" AS 4564,
    "_65" AS 65,
    "cd_01",
    "cd_02",
    "cd_03",
    "cd_04",
    "cd_05",
    "cd_06",
    "cd_07",
    "cd_08",
    "cd_09",
    "cd_10",
    "cd_11",
    "cd_12",
    "cd_13",
    "cd_14",
    "cd_15",
    "cd_16",
    "cd_17",
    "cd_18",
    "cd_19",
    "cd_20",
    "cd_21",
    "cd_22",
    "cd_23",
    "cd_24",
    "cd_25",
    "cd_26",
    "cd_27",
    "cd_28",
    "cd_29",
    "cd_30",
    "cd_31",
    "cd_32",
    "cd_33",
    "cd_34",
    "cd_35",
    "cd_36",
    "cd_37",
    "cd_38",
    "cd_39",
    "cd_40",
    "cd_41",
    "cd_42",
    "cd_43",
    "cd_44",
    "cd_45",
    "cd_46",
    "cd_47",
    "cd_48",
    "cd_49",
    "cd_50",
    "cd_51",
    "unknown_cd",
    "african_american",
    "asian",
    "caucasian",
    "hispanic",
    "multiethnic",
    "native_american",
    "pacific_islander",
    "unknown_race",
    "female",
    "male",
    "has_limited_english_proficiency_yes",
    "has_limited_english_proficiency_no",
    "has_reasonable_accommodation_yes",
    "has_reasonable_accommodation_no"
FROM "nyc-open-data-g6pg-qint"
