-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "fiscal_year",
    "ats_system_code",
    "location_code",
    "location_name",
    "beds_number",
    "managed_by_name",
    "location_type_description",
    "location_category_description",
    "grades_text",
    "grades_final_text",
    "open_date",
    "status_descriptions",
    "primary_building_code",
    "primary_address_line_1",
    "state_code",
    "x_coordinate",
    "y_coordinate",
    "community_district",
    "council_district",
    "census_tract",
    "borough_block_lot",
    "nta",
    "nta_name",
    "principal_name",
    "principal_title",
    "principal_phone_number",
    "fax_number",
    "geographical_district_code",
    "admin_district_location_code",
    "administrative_district_name",
    "community_school_sup_name",
    "field_support_center_name",
    "field_support_center_leader_name",
    "school_support_team_name",
    "school_support_team_leader_name",
    "highschool_network_location_code",
    "highschool_network_name",
    "highschool_network_superintendent",
    "location_1"
FROM "nyc-open-data-ahjc-fdu3"
