-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "the_geom",
    "facname",
    "addressnum",
    "streetname",
    "address",
    "city",
    "zipcode",
    "factype",
    "facsubgrp",
    "facgroup",
    "facdomain",
    "servarea",
    "opname",
    "opabbrev",
    "optype",
    "overagency",
    "overabbrev",
    "overlevel",
    "capacity",
    "captype",
    "boro",
    "bin",
    "bbl",
    "latitude",
    "longitude",
    "xcoord",
    "ycoord",
    "cd",
    "nta2010",
    "nta2020",
    "council",
    "ct2010",
    "ct2020",
    "borocode",
    "schooldist",
    "policeprct",
    "datasource",
    "uid"
FROM "nyc-open-data-67g2-p84d"
