-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "police_precinctgeographic_location",
    "location_type",
    "shootings",
    "overall_dv",
    "population",
    "rate_population",
    "shooting_rate",
    "overall_dv_rate",
    "actual_shootings_white",
    "expected_shootings_white",
    "actual_shootings_black",
    "expected_shootings_black",
    "actual_shootings_asian_pi",
    "expected_shootings_asian_pi",
    "actual_shootings_american_indian_an",
    "expected_shootings_american_indian_an",
    "actual_shootings_other",
    "expected_shootings_other",
    "actual_dirs_white",
    "expected_dirs_white",
    "actual_dirs_black",
    "expected_dirs_black",
    "actual_dirs_asian_pi",
    "expected_dirs_asian_pi",
    "actual_dirs_american_indian_an",
    "expected_dirs_american_indian_an",
    "actual_dirs_other",
    "expected_dirs_other",
    "nyc_population_white",
    "nyc_population_black",
    "nyc_population_asian_pi",
    "nyc_population_american_indian_an",
    "nyc_population_other",
    "actual_shootings_male",
    "expected_shootings_male",
    "actual_shootings_female",
    "expected_shootings_female",
    "actual_dir_male",
    "expected_dirs_male",
    "actual_dirs_female",
    "expected_dirs_female",
    "nyc_population_male",
    "nyc_population_female"
FROM "nyc-open-data-rvmf-4sg6"
