-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "_month" AS month,
    "dhs_bld_id",
    "shelter_name_all",
    "landlord",
    "borough",
    "facility_type",
    "capacity",
    "highpriority_closed_monthly_dob",
    "highpriority_new_monthly_dob",
    "highpriority_open_monthly_dob",
    "highpriority_closed_monthly_hpd",
    "highpriority_new_monthly_hpd",
    "highpriority_open_monthly_hpd",
    "highpriority_closed_monthly_fdny",
    "highpriority_new_monthly_fdny",
    "highpriority_open_monthly_fdny",
    "highpriority_closed_monthly_dohmh",
    "highpriority_new_monthly_dohmh",
    "highpriority_open_monthly_dohmh",
    "mediumpriority_closed_monthly_dob",
    "mediumpriority_new_monthly_dob",
    "mediumpriority_open_monthly_dob",
    "mediumpriority_closed_monthly_hpd",
    "mediumpriority_new_monthly_hpd",
    "mediumpriority_open_monthly_hpd",
    "mediumpriority_closed_monthly_fdny",
    "mediumpriority_new_monthly_fdny",
    "mediumpriority_open_monthly_fdny",
    "mediumpriority_closed_monthly_dohmh",
    "mediumpriority_new_monthly_dohmh",
    "mediumpriority_open_monthly_dohmh",
    "lowestpriority_closed_monthly_dob",
    "lowestpriority_new_monthly_dob",
    "lowestpriority_open_monthly_dob",
    "lowestpriority_closed_monthly_hpd",
    "lowestpriority_new_monthly_hpd",
    "lowestpriority_open_monthly_hpd",
    "lowestpriority_closed_monthly_fdny",
    "lowestpriority_new_monthly_fdny",
    "lowestpriority_open_monthly_fdny",
    "lowestpriority_closed_monthly_dohmh",
    "lowestpriority_new_monthly_dohmh",
    "lowestpriority_open_monthly_dohmh",
    "commissionerorder_closed_monthly_dob",
    "commissionerorder_new_monthly_dob",
    "commissionerorder_open_monthly_dob",
    "commissionerorder_closed_monthly_hpd",
    "commissionerorder_new_monthly_hpd",
    "commissionerorder_open_monthly_hpd",
    "commissionerorder_closed_monthly_fdny",
    "commissionerorder_new_monthly_fdny",
    "commissionerorder_open_monthly_fdny",
    "commissionerorder_closed_monthly_dohmh",
    "commissionerorder_new_monthly_dohmh",
    "commissionerorder_open_monthly_dohmh"
FROM "nyc-open-data-dvaj-b7yx"
