-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "bin",
    "borough",
    "zip",
    "house_num",
    "street_name",
    "block",
    "lot",
    "reporting_year",
    "tank_num",
    "inspection_by_firm",
    "inspection_performed",
    "inspection_date",
    "gi_req_internal_structure",
    "gi_result_internal_structure",
    "gi_req_external_structure",
    "gi_result_external_structure",
    "gi_req_overflow_pipes",
    "gi_result_overflow_pipes",
    "gi_req_access_ladders",
    "gi_result_access_ladders",
    "gi_req_air_vents",
    "gi_result_air_vents",
    "gi_req_roof_access",
    "gi_result_roof_access",
    "si_req_sediment",
    "si_result_sediment",
    "si_req_biological_growth",
    "si_result_biological_growth",
    "si_req_debris_insects",
    "si_result_debris_insects",
    "si_req_rodent_bird",
    "si_result_rodent_bird",
    "sample_collected",
    "lab_name",
    "nys_certified",
    "analytes",
    "coliform",
    "ecoli",
    "meet_standards",
    "latitude",
    "longitude",
    "community_board",
    "council_district",
    "census_tract",
    "bbl",
    "nta",
    "batch_date"
FROM "nyc-open-data-gjm4-k24g"
