-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "project_id",
    "project_name",
    "project_start_date",
    "project_completion_date",
    "building_id",
    "number",
    "street",
    "borough",
    "postcode",
    "bbl",
    "bin",
    "community_board",
    "council_district",
    "census_tract",
    "nta_neighborhood_tabulation_area",
    "latitude",
    "longitude",
    "latitude_internal",
    "longitude_internal",
    "building_completion_date",
    "reporting_construction_type",
    "extended_affordability_only",
    "prevailing_wage_status",
    "extremely_low_income_units",
    "very_low_income_units",
    "low_income_units",
    "moderate_income_units",
    "middle_income_units",
    "other_income_units",
    "studio_units",
    "_1br_units" AS 1br_units,
    "_2br_units" AS 2br_units,
    "_3br_units" AS 3br_units,
    "_4br_units" AS 4br_units,
    "_5br_units" AS 5br_units,
    "_6br_units" AS 6br_units,
    "unknownbr_units",
    "counted_rental_units",
    "counted_homeownership_units",
    "all_counted_units",
    "total_units"
FROM "nyc-open-data-hg8x-zxpr"
