-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "site_id",
    "program_code",
    "program_name",
    "program_type",
    "enrollment",
    "daily_start_time",
    "length_of_prek_day",
    "early_dropoff_available",
    "late_pickup_available",
    "meals",
    "playspace",
    "dual_language",
    "collaborative_teachers_survey_percent_positive",
    "supportive_environment_survey_percent_positive",
    "effective_school_leadership_survey_percent_positive",
    "strong_familycommunity_ties_survey_percent_positive",
    "trust_survey_percent_positive",
    "survey_number_of_guardian_responses",
    "survey_guardian_response_rate",
    "class_most_recent_assessment_year",
    "class_emotional_support_score",
    "class_emotional_support_rating",
    "class_classroom_organization_score",
    "class_classroom_organization_rating",
    "class_instructional_support_score",
    "class_instructional_support_rating",
    "ecers_most_recent_assessment_year",
    "ecers_observation_average_score",
    "ecers_observation_average_rating",
    "ecers_language_reasoning_score",
    "ecers_language_reasoning_rating",
    "ecers_interaction_score",
    "ecers_interaction_rating",
    "ecers_activities_score",
    "ecers_activities_rating",
    "ecers_personal_care_routines_score",
    "ecers_personal_care_routines_rating",
    "ecers_space_and_furnishings_score",
    "ecers_space_and_furnishings_rating",
    "ecers_program_structure_score",
    "ecers_program_structure_rating",
    "quality_review_date_of_review",
    "quality_review_how_well_do_teachers_work_with_each_other",
    "address_1",
    "address_2"
FROM "nyc-open-data-nfkx-wd79"
