-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "tree_dbh",
    "cen_year",
    "the_geom",
    "address",
    "tree_loc",
    "pit_type",
    "soil_lvl",
    "status",
    "spc_latin",
    "spc_common",
    "vert_other",
    "vert_pgrd",
    "vert_tgrd",
    "vert_wall",
    "horz_blck",
    "horz_grate",
    "horz_plant",
    "horz_other",
    "sidw_crack",
    "sidw_raise",
    "wire_htap",
    "wire_prime",
    "wire_2nd",
    "wire_other",
    "inf_canopy",
    "inf_guard",
    "inf_wires",
    "inf_paving",
    "inf_outlet",
    "inf_shoes",
    "inf_lights",
    "inf_other",
    "trunk_dmg",
    "zipcode",
    "zip_city",
    "cb_num",
    "borocode",
    "boroname",
    "cncldist",
    "st_senate",
    "nta",
    "st_assem",
    "nta_name",
    "boro_ct",
    "state",
    "latitude",
    "longitude",
    "x_sp",
    "y_sp"
FROM "nyc-open-data-urik-ndeg"
