-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "site_id",
    "provider_id",
    "program_id",
    "contract_id",
    "agency_name",
    "bbl",
    "bin",
    "community_board",
    "council_district",
    "latitude",
    "longitude",
    "nta",
    "census_tract",
    "catchment_type",
    "catchment_zone",
    "catchment_intersection_1",
    "catchment_intersection_2",
    "fixed_address",
    "address_1",
    "address_2",
    "borough",
    "city",
    "state",
    "postcode",
    "site_name",
    "site_budget",
    "notes",
    "accepts_dropins",
    "language_taxonomy",
    "service_taxonomy",
    "population_taxonomy",
    "service_setting_taxonomy",
    "bp_category",
    "bp_population",
    "capacity",
    "capacity_units",
    "serves_food",
    "catchment_description",
    "state_senate_district",
    "state_assembly_district"
FROM "nyc-open-data-y9si-s7ab"
