-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "mailed_date",
    "borocode",
    "block",
    "lot",
    "ease",
    "address_1",
    "address_2",
    "address_3",
    "city_state_zip",
    "country",
    "tax_class",
    "bld_class",
    "original_market_value",
    "original_assessed_value",
    "original_exemption",
    "original_transitional_assessed_value",
    "original_transitional_exemption",
    "original_taxable_value",
    "revised_market_value",
    "revised_assessed_value",
    "revised_exemption",
    "revised_transitional_assessed_value",
    "revised_transitional_exemption",
    "revised_taxable_value",
    "rc_1",
    "rc2",
    "rc3",
    "rc4",
    "rc5",
    "borough",
    "postcode",
    "latitude",
    "longitude",
    "community_board",
    "council_district",
    "census_tract",
    "bin",
    "bbl",
    "nta"
FROM "nyc-open-data-8vgb-zm6e"
