-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "license_nbr",
    "lic_status",
    "business_name",
    "business_name2",
    "building",
    "street",
    "city",
    "state",
    "zip",
    "swc_type",
    "swc_sq_ft",
    "swc_tables",
    "swc_chairs",
    "dohmh",
    "final_x",
    "final_y",
    "community_district",
    "city_council_district",
    "cd_url",
    "app_id",
    "app_swc_type",
    "app_sq_ft",
    "app_tables",
    "app_chairs",
    "app_status",
    "app_status_date",
    "expiration_date",
    "app_too_date",
    "submit_date",
    "intake",
    "intake_dd",
    "dpqa",
    "send_package_dd",
    "cp",
    "cp_dd",
    "cb",
    "cb_dd",
    "hearing",
    "hearing_dd",
    "hearing_public",
    "hearing_public_dd",
    "cc",
    "cc_dd",
    "moo",
    "moo_dd",
    "issuance",
    "issuance_dd"
FROM "nyc-open-data-qcdj-rwhu"
