-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "dbn",
    "school_name",
    "_year" AS year,
    "total_enrollment",
    "grade_pk",
    "grade_k",
    "grade_1",
    "grade_2",
    "grade_3",
    "grade_4",
    "grade_5",
    "grade_6",
    "grade_7",
    "grade_8",
    "grade_9",
    "grade_10",
    "grade_11",
    "grade_12",
    "female",
    "female_1",
    "male",
    "male_1",
    "asian",
    "asian_1",
    "black",
    "black_1",
    "hispanic",
    "hispanic_1",
    "other",
    "other_1",
    "white",
    "white_1",
    "students_with_disabilities",
    "students_with_disabilities_1",
    "english_language_learners",
    "english_language_learners_1",
    "poverty",
    "poverty_1"
FROM "nyc-open-data-8mzw-jfss"
