-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "school_year",
    "beds_code",
    "school_name",
    "district_name",
    "school_type",
    "enrollment",
    "homicide_with_weapons",
    "homicide_without_weapons",
    "forcible_sex_offenses_with_weapons",
    "forcible_sex_offenses_without_weapons",
    "other_sex_offenses_with_weapons",
    "other_sex_offenses_without_weapons",
    "robbery_with_weapons",
    "robbery_without_weapons",
    "assault_with_serious_physical_injury_with_weapons",
    "assault_with_serious_physical_injury_without_weapons",
    "arson_with_weapons",
    "kidnapping_with_weapons",
    "kidnapping_without_weapons",
    "assault_with_physical_injury_with_weapons",
    "assault_with_physical_injury_without_weapons",
    "reckless_endangerment_with_weapons",
    "reckless_endangerment_without_weapons",
    "minor_altercations_with_weapons",
    "minor_altercations_without_weapons",
    "intimidation_harassment_menacing_or_bullying_with_weapons",
    "intimidation_harassment_menacing_or_bullying_without_weapons",
    "burglary_with_weapons",
    "burglary_without_weapons",
    "criminal_mischief_with_weapons",
    "criminal_mischief_without_weapons",
    "larceny_or_other_theft_with_weapons",
    "larceny_or_other_theft_without_weapons",
    "bomb_threat",
    "false_alarm",
    "riot_with_weapons",
    "riot_without_weapons",
    "weapon_possessionthrough_screening",
    "weapon_possession_under_other_circumstances",
    "drug_possession",
    "alcohol_possession",
    "other_disruptive",
    "county",
    "needresource_category",
    "grade_organization"
FROM "nyc-open-data-fpci-ws56"
