-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "accessible",
    "adult_baseball",
    "adult_football",
    "adult_softball",
    "basketball",
    "bocce",
    "borough",
    "communityboard",
    "councildistrict",
    "cricket",
    "department",
    "dimensions",
    "featurestatus",
    "field_lighted",
    "field_number",
    "flagfootball",
    "frisbee",
    "gispropnum",
    "handball",
    "hockey",
    "kickball",
    "lacrosse",
    "ll_baseb_12andunder",
    "ll_baseb_13andolder",
    "ll_softball",
    "maintenanceagreement",
    "netball",
    "nonregulation_soccer",
    "precinct",
    "primary_sport",
    "pickleball",
    "regulation_soccer",
    "rugby",
    "starea",
    "stlength",
    "surface_type",
    "_system" AS system,
    "tennis",
    "track_and_field",
    "t_ball",
    "volleyball",
    "wheelchairfootball",
    "youth_football",
    "zipcode",
    "the_geom"
FROM "nyc-open-data-9wwi-sb8x"
