-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "projectcode",
    "groupowner",
    "locationdescription",
    "borough",
    "projectstatus",
    "nextstep",
    "dateadded",
    "bctsnum",
    "ccunum",
    "requestorletterreplydate",
    "cbletterrequestdate",
    "cbletterrecieveddate",
    "oldsign",
    "newsign",
    "markingsdate",
    "installationdate",
    "secondstudycode",
    "closeddate",
    "speedcushion",
    "requestdate",
    "requestortype",
    "segmentid",
    "onstreet",
    "fromstreet",
    "tostreet",
    "geoboroughname",
    "lionkey",
    "fromlatitude",
    "fromlongitude",
    "tolatitude",
    "tolongitude",
    "oft",
    "cb",
    "segmentstatus",
    "segmentstatusdescription",
    "denialreason",
    "numsrproposed",
    "trafficdirection",
    "trafficdirectiondesc",
    "oldsign1",
    "newsign1",
    "oldsign2",
    "newsign2"
FROM "nyc-open-data-9n6h-pt9g"
