-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "entity_name",
    "entity_role",
    "street_address",
    "suiteapartment_number",
    "state",
    "city",
    "postcode",
    "country",
    "ownerofficer_first_name",
    "ownerofficer_last_name",
    "individuals_role",
    "individuals_title",
    "officer_equivalent",
    "ownerofficer_2_first_name",
    "ownerofficer_2_last_name",
    "individual_role_2",
    "individual_title_2",
    "officer_equivalent_2",
    "ownerofficer_3_first_name",
    "ownerofficer_3_last_name",
    "individual_role_3",
    "individual_title_3",
    "officer_equivalent_3",
    "ownerofficer_4_first_name",
    "ownerofficer_4_last_name",
    "individual_role_4",
    "individual_title_4",
    "officer_equivalent_4",
    "ownerofficer_5_first_name",
    "ownerofficer_5_last_name",
    "individual_role_5",
    "individual_title_5",
    "officer_equivalent_5",
    "borough",
    "latitude",
    "longitude",
    "bin",
    "bbl",
    "community_board",
    "council_district",
    "census_tract",
    "nta"
FROM "nyc-open-data-9s68-zggy"
