-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "tr6_no",
    "control_no",
    "filing_type",
    "_cycle" AS cycle,
    "bin",
    "house_no",
    "street_name",
    "borough",
    "block",
    "lot",
    "sequence_no",
    "submitted_on",
    "current_status",
    "qewi_name",
    "qewi_bus_name",
    "qewi_bus_street_name",
    "qewi_city",
    "qewi_state",
    "qewi_zip",
    "qewi_nys_lic_no",
    "owner_name",
    "owner_bus_name",
    "owner_bus_street_name",
    "owner_city",
    "owner_zip",
    "owner_state",
    "filing_date",
    "filing_status",
    "prior_cycle_filing_date",
    "prior_status",
    "field_inspection_completed_date",
    "qewi_signed_date",
    "late_filing_amt",
    "failure_to_file_amt",
    "failure_to_correct_amt",
    "_comments" AS comments,
    "exterior_wall_types",
    "exterior_wall_type_other_description",
    "exterior_wall_materials",
    "exterior_wall_material_other_description"
FROM "nyc-open-data-xubg-57si"
