-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "visit_year",
    "foreign_born",
    "us_born",
    "total_fjc_client",
    "fjc_fb_visit_bronx",
    "fjc_fb_visit_brooklyn",
    "fjc_fb_visit_manhattan",
    "fjc_fb_visit_queens",
    "fjc_fb_visit_staten_island",
    "fb_age_under_18",
    "fb_age_18_24",
    "fb_age_25_39",
    "fb_age_40_49",
    "fb_age_50_59",
    "fb_age_over_60",
    "fb_lang_spanish",
    "fb_lang_english",
    "fb_lang_mandarin",
    "fb_lang_russian",
    "fb_lang_arabic",
    "fb_lang_bengali",
    "fb_lang_french",
    "fb_country_mexico",
    "fb_country_dominican_repub",
    "fb_country_jamaica",
    "fb_country_ecuador",
    "fb_country_china",
    "fb_country_honduras",
    "fb_country_guyana",
    "fb_country_colombia",
    "fb_country_trin_tobago",
    "fb_country_bangladesh",
    "fb_relationship_dating",
    "fb_relationship_spouse",
    "fb_relationship_ex_dating",
    "fb_relationship_ex_spouse",
    "fb_relationship_child_common",
    "fb_relationship_living_together",
    "fb_acquaintance_stranger",
    "fb_parent_child",
    "fb_other_family",
    "fb_boy_girlfriend",
    "fb_services_risk_assessment_counseling",
    "fb_services_safety_planning",
    "fb_services_civil_legal_asst",
    "fb_services_perm_housing",
    "fb_services_practical_assistance",
    "fb_country_bx_dominican_republic",
    "fb_country_bx_mexico",
    "fb_country_bx_honduras",
    "fb_country_bx_jamaica",
    "fb_country_bx_ecuador",
    "fb_country_bk_mexico",
    "fb_country_bk_jamaica",
    "fb_country_bk_dominican_republic",
    "fb_country_bk_china",
    "fb_country_bk_haiti",
    "fb_country_mn_dominican_republic",
    "fb_country_mn_mexico",
    "fb_country_mn_china",
    "fb_country_mn_columbia",
    "fb_country_mn_honduras",
    "fb_country_qn_mexico",
    "fb_country_qn_ecuador",
    "fb_country_qn_colombia",
    "fb_country_qn_jamaica",
    "fb_country_qn_dominican_republic",
    "fb_country_si_mexico",
    "fb_country_si_jamaica",
    "fb_country_si_dominican_republic",
    "fb_country_si_eygpt",
    "fb_country_si_honduras",
    "diff_fb_avg_visits",
    "diff_us_avg_visits",
    "diff_fb__less_hs" AS diff_fb_less_hs,
    "diff_us__less_hs" AS diff_us_less_hs,
    "diff_fb__employed" AS diff_fb_employed,
    "diff_us__employed" AS diff_us_employed,
    "diff_fb__disability" AS diff_fb_disability,
    "diff_us__disability" AS diff_us_disability,
    "diff_fb__shelter" AS diff_fb_shelter,
    "diff_us__shelter" AS diff_us_shelter,
    "diff_fb__shelter_hom" AS diff_fb_shelter_hom,
    "diff_us__shelter_hom" AS diff_us_shelter_hom,
    "diff_fb__shelter_dv" AS diff_fb_shelter_dv,
    "diff_us__shelter_dv" AS diff_us_shelter_dv,
    "diff_fb__heard_fjc" AS diff_fb_heard_fjc,
    "diff_us__heard_fjc" AS diff_us_heard_fjc,
    "diff_fb__open_fam_ct" AS diff_fb_open_fam_ct,
    "diff_us__open_fam_ct" AS diff_us_open_fam_ct,
    "diff_fb__police_call" AS diff_fb_police_call,
    "diff_us__police_call" AS diff_us_police_call,
    "diff_fb__open_crim_ct" AS diff_fb_open_crim_ct,
    "diff_us__open_crim_ct" AS diff_us_open_crim_ct,
    "diff_fb__group_counseling" AS diff_fb_group_counseling,
    "diff_us__group_counseling" AS diff_us_group_counseling,
    "diff_fb__spouse_relationship" AS diff_fb_spouse_relationship,
    "diff_us__spouse_relationship" AS diff_us_spouse_relationship
FROM "nyc-open-data-wr2n-ag8h"
