-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "borough_block_lot",
    "street_address",
    "postcode",
    "borough",
    "utility",
    "building_manager",
    "_owner" AS owner,
    "owner_address",
    "owner_telephone",
    "dep_boiler_application",
    "_6_deadline" AS 6_deadline,
    "boiler_model",
    "of_identical_boilers",
    "boiler_capacity_gross_btu",
    "boiler_installation_date",
    "boiler_age_range",
    "est_retirement_year",
    "burner_model",
    "primary_fuel",
    "total_gallons_high",
    "total_gallons_low",
    "total_mmbtu_high",
    "total_mmbtu_low",
    "greener_greater_buildings",
    "ggb_deadline",
    "building_type",
    "council_district",
    "community_board",
    "bldg_sqft",
    "of_bldgs",
    "of_floors",
    "of_res_units",
    "total_units",
    "year_built",
    "condo",
    "coop",
    "latitude",
    "longitude",
    "census_tract",
    "bin",
    "bbl",
    "nta"
FROM "nyc-open-data-8isn-pgv3"
