-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "organizationname",
    "brooklyn",
    "bronx",
    "manhattan",
    "queens",
    "staten_island",
    "fax",
    "phone",
    "url",
    "nourl",
    "description",
    "outsideloc",
    "outsidelocdesc",
    "aging",
    "antidiscrimination_human_rights",
    "arts_culture",
    "business",
    "child_care_parent_information",
    "community_service_volunteerism",
    "counseling_support_groups",
    "disabilities",
    "domestic_violence",
    "education",
    "employment_job_training",
    "health",
    "homelessness",
    "housing",
    "immigration",
    "legal_services",
    "lesbian_gay_bisexual_andor_transgender",
    "personal_finance_financial_education",
    "professional_association",
    "veterans_military_families",
    "victim_services",
    "womens_groups",
    "youth_services",
    "faithbased_organization",
    "foundation",
    "is_registered_with_the_attorney_generals_office",
    "new_york_city_agency",
    "none_of_the_above",
    "nonprofit",
    "_comments" AS comments,
    "other_government_organization",
    "published",
    "location_1",
    "borough",
    "latitude",
    "longitude",
    "community_board",
    "city_council",
    "census_tract",
    "bin",
    "bbl",
    "nta",
    "address1",
    "address2",
    "city",
    "postcode"
FROM "nyc-open-data-pqg4-dm6b"
