-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "the_geom",
    "wpaa_id",
    "_name" AS name,
    "construction_status",
    "chair_certification_date",
    "cpc_approval_date",
    "maintained_by",
    "summary_of_wpaa",
    "restrictive_declaration_link",
    "cpc_report_link",
    "supplemental_public_access_area",
    "total_wpaa_area",
    "zoning_application_portal_zap_link",
    "hours_of_operation",
    "adjacent_waterway",
    "shore_public_walkway_area",
    "shore_public_walkway_linear_feet",
    "activity_volleyball_court",
    "activity_basketball_court",
    "activity_fishing",
    "activity_boatinginwater_access",
    "activity_tot_playground",
    "activity_splash_feature",
    "activity_other_recreational",
    "activity_swimming",
    "feature_promenade",
    "feature_seating_lawn",
    "feature_pier",
    "feature_wetlandnatural_edge",
    "feature_dog_run",
    "feature_educational_or_interpretive_signs",
    "feature_public_restroom",
    "feature_shade_structure",
    "feature_outdoor_art",
    "feature_food_or_beverage_concessions",
    "feature_group_seating",
    "shape_length",
    "shape_area"
FROM "nyc-open-data-388s-pnvc"
