-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "bronx_cooperatives_comparable_properties_boroblocklot",
    "bronx_cooperatives_comparable_properties_address",
    "borough",
    "postcode",
    "latitude",
    "longitude",
    "community_board",
    "community_council",
    "census_tract",
    "bin",
    "bbl",
    "nta",
    "bronx_cooperatives_comparable_properties_neighborhood",
    "bronx_cooperatives_comparable_properties_building_classification",
    "bronx_cooperatives_comparable_properties_total_units",
    "bronx_cooperatives_comparable_properties_year_built",
    "bronx_cooperatives_comparable_properties_gross_sqft",
    "bronx_cooperatives_comparable_properties_est_gross_income",
    "bronx_cooperatives_comparable_properties_gross_income_per_sqft",
    "bronx_cooperatives_comparable_properties_full_market_value",
    "bronx_cooperatives_comparable_properties_market_value_per_sqft",
    "comparable_rental_1_boroblocklot",
    "comparable_rental_1_address",
    "comparable_rental_1_neighborhood",
    "comparable_rental_1_building_classification",
    "comparable_rental_1_total_units",
    "comparable_rental_1_year_built",
    "comparable_rental_1_gross_sqft",
    "comparable_rental_1_est_gross_income",
    "comparable_rental_1_gross_income_per_sqft",
    "comparable_rental_1_full_market_value",
    "comparable_rental_1_market_value_per_sqft",
    "comparable_rental_1_dist_from_coop_in_miles",
    "comparable_rental_2_boroblocklot",
    "comparable_rental_2_address",
    "comparable_rental_2_neighborhood",
    "comparable_rental_2_building_classification",
    "comparable_rental_2_total_units",
    "comparable_rental_2_year_built",
    "comparable_rental_2_gross_sqft",
    "comparable_rental_2_est_gross_income",
    "comparable_rental_2_gross_income_per_sqft",
    "comparable_rental_2_full_market_value",
    "comparable_rental_2_market_value_per_sqft",
    "comparable_rental_2_dist_from_coop_in_miles"
FROM "nyc-open-data-gahm-hu5h"
