-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "dbn",
    "location_name",
    "location_category",
    "administrative_district",
    "_0k_removals" AS 0k_removals,
    "_0k_principal" AS 0k_principal,
    "_0k_superintendent" AS 0k_superintendent,
    "_0k_expulsions" AS 0k_expulsions,
    "_01_removals" AS 01_removals,
    "_01_principal" AS 01_principal,
    "_01_superintendent" AS 01_superintendent,
    "_01_expulsions" AS 01_expulsions,
    "_02_removals" AS 02_removals,
    "_02_principal" AS 02_principal,
    "_02_superintendent" AS 02_superintendent,
    "_02_expulsions" AS 02_expulsions,
    "_03_removals" AS 03_removals,
    "_03_principal" AS 03_principal,
    "_03_superintendent" AS 03_superintendent,
    "_03_expulsions" AS 03_expulsions,
    "_04_removals" AS 04_removals,
    "_04_principal" AS 04_principal,
    "_04_superintendent" AS 04_superintendent,
    "_04_expulsions" AS 04_expulsions,
    "_05_removals" AS 05_removals,
    "_05_principal" AS 05_principal,
    "_05_superintendent" AS 05_superintendent,
    "_05_expulsions" AS 05_expulsions,
    "_06_removals" AS 06_removals,
    "_06_principal" AS 06_principal,
    "_06_superintendent" AS 06_superintendent,
    "_06_expulsions" AS 06_expulsions,
    "_07_removals" AS 07_removals,
    "_07_principal" AS 07_principal,
    "_07_superintendent" AS 07_superintendent,
    "_07_expulsions" AS 07_expulsions,
    "_08_removals" AS 08_removals,
    "_08_principal" AS 08_principal,
    "_08_superintendent" AS 08_superintendent,
    "_08_expulsions" AS 08_expulsions,
    "_09_removals" AS 09_removals,
    "_09_principal" AS 09_principal,
    "_09_superintendent" AS 09_superintendent,
    "_09_expulsions" AS 09_expulsions,
    "_10_removals" AS 10_removals,
    "_10_principal" AS 10_principal,
    "_10_superintendent" AS 10_superintendent,
    "_10_expulsions" AS 10_expulsions,
    "_11_removals" AS 11_removals,
    "_11_principal" AS 11_principal,
    "_11_superintendent" AS 11_superintendent,
    "_11_expulsions" AS 11_expulsions,
    "_12_removals" AS 12_removals,
    "_12_principal" AS 12_principal,
    "_12_superintendent" AS 12_superintendent,
    "_12_expulsions" AS 12_expulsions
FROM "nyc-open-data-29bv-qqsy"
