-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "dbn",
    "location_name",
    "location_category",
    "administrative_district",
    "_5_removals" AS 5_removals,
    "_5_principal" AS 5_principal,
    "_5_superintendent" AS 5_superintendent,
    "_5_expulsions" AS 5_expulsions,
    "_6_removals" AS 6_removals,
    "_6_principal" AS 6_principal,
    "_6_superintendent" AS 6_superintendent,
    "_6_expulsions" AS 6_expulsions,
    "_7_removals" AS 7_removals,
    "_7_principal" AS 7_principal,
    "_7_superintendent" AS 7_superintendent,
    "_7_expulsions" AS 7_expulsions,
    "_8_removals" AS 8_removals,
    "_8_principal" AS 8_principal,
    "_8_superintendent" AS 8_superintendent,
    "_8_expulsions" AS 8_expulsions,
    "_9_removals" AS 9_removals,
    "_9_principal" AS 9_principal,
    "_9_superintendent" AS 9_superintendent,
    "_9_expulsions" AS 9_expulsions,
    "_10_removals" AS 10_removals,
    "_10_principal" AS 10_principal,
    "_10_superintendent" AS 10_superintendent,
    "_10_expulsions" AS 10_expulsions,
    "_11_removals" AS 11_removals,
    "_11_principal" AS 11_principal,
    "_11_superintendent" AS 11_superintendent,
    "_11_expulsions" AS 11_expulsions,
    "_12_removals" AS 12_removals,
    "_12_principal" AS 12_principal,
    "_12_superintendent" AS 12_superintendent,
    "_12_expulsions" AS 12_expulsions,
    "_13_removals" AS 13_removals,
    "_13_principal" AS 13_principal,
    "_13_superintendent" AS 13_superintendent,
    "_13_expulsions" AS 13_expulsions,
    "_14_removals" AS 14_removals,
    "_14_principal" AS 14_principal,
    "_14_superintendent" AS 14_superintendent,
    "_14_expulsions" AS 14_expulsions,
    "_15_removals" AS 15_removals,
    "_15_principal" AS 15_principal,
    "_15_superintendent" AS 15_superintendent,
    "_15_expulsions" AS 15_expulsions,
    "_16_removals" AS 16_removals,
    "_16_principal" AS 16_principal,
    "_16_superintendent" AS 16_superintendent,
    "_16_expulsions" AS 16_expulsions,
    "_17_removals" AS 17_removals,
    "_17_principal" AS 17_principal,
    "_17_superintendent" AS 17_superintendent,
    "_17_expulsions" AS 17_expulsions,
    "_18_removals" AS 18_removals,
    "_18_principal" AS 18_principal,
    "_18_superintendent" AS 18_superintendent,
    "_18_expulsions" AS 18_expulsions,
    "_19_removals" AS 19_removals,
    "_19_principal" AS 19_principal,
    "_19_superintendent" AS 19_superintendent,
    "_19_expulsions" AS 19_expulsions,
    "_20_removals" AS 20_removals,
    "_20_principal" AS 20_principal,
    "_20_superintendent" AS 20_superintendent,
    "_20_expulsions" AS 20_expulsions,
    "_21_removals" AS 21_removals,
    "_21_principal" AS 21_principal,
    "_21_superintendent" AS 21_superintendent,
    "_21_expulsions" AS 21_expulsions,
    "_22_removals" AS 22_removals,
    "_22_principal" AS 22_principal,
    "_22_superintendent" AS 22_superintendent,
    "_22_expulsions" AS 22_expulsions
FROM "nyc-open-data-r5p4-2qap"
