-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "siteid",
    "inspectionid",
    "inpectiondate",
    "_location" AS location,
    "question1",
    "question2",
    "_2option1" AS 2option1,
    "_2option2" AS 2option2,
    "_2option3" AS 2option3,
    "_2option4" AS 2option4,
    "_2option5" AS 2option5,
    "_2option6" AS 2option6,
    "_2ticketnumber" AS 2ticketnumber,
    "_2bikeidnumber" AS 2bikeidnumber,
    "_2multipleinstances" AS 2multipleinstances,
    "_2ticketcomments" AS 2ticketcomments,
    "question3",
    "_3option1" AS 3option1,
    "_3option2" AS 3option2,
    "_3option3" AS 3option3,
    "_3option4" AS 3option4,
    "_3ticketnumber" AS 3ticketnumber,
    "_3ticketcomments" AS 3ticketcomments,
    "question4",
    "_4option1" AS 4option1,
    "_4option2" AS 4option2,
    "_4option3" AS 4option3,
    "_4option4" AS 4option4,
    "_4ticketnumber" AS 4ticketnumber,
    "_4ticketcomments" AS 4ticketcomments,
    "question5",
    "question6",
    "question7",
    "question8",
    "_8option1" AS 8option1,
    "_8option2" AS 8option2,
    "_8option3" AS 8option3,
    "_8ticketnumber" AS 8ticketnumber,
    "_8bikeidnumber" AS 8bikeidnumber,
    "_8ticketcomments" AS 8ticketcomments,
    "question9",
    "question10"
FROM "nyc-open-data-5uei-swth"
