-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "_year" AS year,
    "comm_dist__boro" AS comm_dist_boro,
    "comm_district",
    "fam_dir",
    "fam_fel_assault",
    "dv_fel_assault",
    "fam_rape",
    "dv_rape",
    "dir_family_total",
    "dir_fam_rel_child",
    "dir_fam_rel_parent",
    "dir_fam_rel_othrelative",
    "fel_aslt_fam_total",
    "fel_aslt_rel_child",
    "fel_aslt_rel_parent",
    "fel_aslt_rel_othrelative",
    "fel_rape_fam_total",
    "fel_rape_rel_child",
    "fel_rape_rel_parent",
    "fel_rape_rel_othrelative",
    "fam_homicide_total",
    "fam_hom_rel_child",
    "fam_hom_rel_parent",
    "fam_hom_rel_oth",
    "fam_hom_rel_unkn",
    "fam_hom_sex_female",
    "fam_hom_sex_male",
    "fam_hom_prior_dir_yes",
    "fam_hom_prior_dir_no",
    "fam_hom_meth_blunt",
    "fam_hom_meth_sharpe",
    "fam_hom_meth_firearm",
    "ipv_hom_sex_female",
    "ipv_hom_sex_male",
    "ipv_hom_prior_dir_yes",
    "ipv_hom_prior_dir_no",
    "ipv_hom_meth_blunt",
    "ipv_hom_meth_sharpe",
    "ipv_hom_meth_firearm",
    "ipv_hom_meth_oth",
    "fjc_fam_client",
    "fjc_fam_client_ser_safplan",
    "fjc_fam_client_ser_counseling",
    "fjc_fam_client_ser_civleg",
    "fjc_fam_client_ser_permhous",
    "fjc_fam_client_ser_childcounsel"
FROM "nyc-open-data-uhw3-ky8e"
