-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: No stable row identifier was verified in the raw table; treat rows as source records rather than mergeable observations.
SELECT
    "col_0" AS dimension_0,
    "col_1" AS dimension_1,
    "col_2" AS dimension_2,
    "col_3" AS dimension_3,
    strptime("col_4", '%m/%d/%Y')::DATE AS dimension_4,
    "col_5" AS dimension_5,
    "col_6" AS dimension_6,
    "col_7" AS dimension_7,
    "col_8" AS dimension_8,
    "col_9" AS dimension_9,
    "col_10" AS dimension_10,
    "col_11" AS dimension_11,
    "col_12" AS dimension_12,
    "col_13" AS dimension_13,
    "col_14" AS dimension_14,
    "col_15" AS dimension_15,
    "col_16" AS dimension_16,
    "col_17" AS dimension_17,
    "col_18" AS dimension_18,
    "col_19" AS dimension_19,
    "col_20" AS dimension_20,
    "col_21" AS dimension_21,
    "col_22" AS dimension_22,
    "col_23" AS dimension_23,
    "col_24" AS dimension_24,
    "col_25" AS dimension_25,
    "col_26" AS dimension_26,
    "col_27" AS dimension_27,
    "col_28" AS dimension_28,
    "col_29" AS dimension_29,
    "col_30" AS dimension_30,
    "col_31" AS dimension_31,
    "col_32" AS dimension_32,
    "col_33" AS dimension_33,
    strptime("col_34", '%m/%d/%Y')::DATE AS dimension_34,
    "col_35" AS dimension_35,
    "col_36" AS dimension_36,
    "col_37" AS dimension_37,
    "col_38" AS dimension_38,
    "col_39" AS dimension_39,
    "col_40" AS dimension_40,
    "col_41" AS dimension_41,
    "col_42" AS dimension_42,
    "col_43" AS dimension_43,
    "col_44" AS dimension_44,
    "col_45" AS dimension_45,
    "col_46" AS dimension_46,
    "col_47" AS dimension_47,
    "col_48" AS dimension_48,
    "col_49" AS dimension_49
FROM "rosstat-7708234640-stpetersburgleningradregions"
