"""ILO (ILOSTAT) connector.

Source: the ILOSTAT bulk download facility, served by the rplumber API at
rplumber.ilo.org. One gzipped tidy-CSV file per indicator-frequency dataset
(the entity union). Mechanism: bulk_csv (per-entity), chosen by research —
https://rplumber.ilo.org/data/indicator?id=<ID>&format=.csv.gz .

Fetch shape: stateless full re-pull. Each indicator file is small (thousands
to a few hundred thousand rows) and the whole corpus re-fetches in minutes, so
we overwrite every run and pick up revisions/late corrections for free — no
watermark, cursor, or maintain branch. (The data endpoint exposes no since/
cursor filter anyway; the TOC's last.update is the only delta signal and that
is the maintain step's concern, not ours.)

Schema handling: every data file is long-format with stable column NAMES but a
varying SET — ref_area, source, indicator, [sex], classif1[, classif2], time,
obs_value, obs_status, plus footnote-code columns. The `sex` dimension gets its
own column whenever SEX is part of the indicator's classification; the other
(at most two) dimensions land in classif1/classif2. The fetch normalizes every
file onto one fixed parquet schema (absent columns -> null), which keeps the raw
layer parquet-safe across all assets. Each per-indicator transform then selects
exactly the dimension columns that indicator actually uses (from ENTITY_META,
derived from the collect catalog's `classification`) and derives a DATE from the
period string per the indicator's frequency (A/Q/M, the id suffix). Footnote
columns are dropped — they are opaque code references without the dictionaries.
"""
import csv
import gzip
import io

import pyarrow as pa

from subsets_utils import (
    NodeSpec,
    SqlNodeSpec,
    get,
    save_raw_parquet,
    transient_retry,
)

DATA_URL = "https://rplumber.ilo.org/data/indicator"

# Fixed superset schema. Every indicator file maps onto these columns; columns
# the file lacks are written null. A stable, explicit schema is the contract
# that makes parquet safe for all 1416 independent assets.
RAW_SCHEMA = pa.schema([
    ("ref_area", pa.string()),
    ("source", pa.string()),
    ("indicator", pa.string()),
    ("sex", pa.string()),
    ("classif1", pa.string()),
    ("classif2", pa.string()),
    ("time_period", pa.string()),
    ("obs_value", pa.float64()),
    ("obs_status", pa.string()),
])


def _entity_from_node(node_id: str) -> str:
    """ilo-une-tune-sex-age-nb-a -> UNE_TUNE_SEX_AGE_NB_A (inverse of the id rule)."""
    return node_id.removeprefix("ilo-").upper().replace("-", "_")


def _to_float(v):
    if v is None or v == "":
        return None
    try:
        return float(v)
    except ValueError:
        return None


@transient_retry()
def _fetch_csv_gz(entity_id: str) -> bytes:
    resp = get(
        DATA_URL,
        params={"id": entity_id, "format": ".csv.gz"},
        timeout=(10.0, 180.0),
    )
    resp.raise_for_status()
    return gzip.decompress(resp.content)


def fetch_one(node_id: str) -> None:
    asset = node_id  # the runtime passes the spec id; it IS the asset name
    entity_id = _entity_from_node(node_id)
    text = _fetch_csv_gz(entity_id).decode("utf-8-sig")
    reader = csv.DictReader(io.StringIO(text))

    ref_area, source, indicator = [], [], []
    sex, classif1, classif2 = [], [], []
    time_period, obs_value, obs_status = [], [], []
    for row in reader:
        ref_area.append(row.get("ref_area"))
        source.append(row.get("source"))
        indicator.append(row.get("indicator"))
        sex.append(row.get("sex"))
        classif1.append(row.get("classif1"))
        classif2.append(row.get("classif2"))
        time_period.append(row.get("time"))
        obs_value.append(_to_float(row.get("obs_value")))
        obs_status.append(row.get("obs_status"))

    table = pa.table(
        {
            "ref_area": pa.array(ref_area, pa.string()),
            "source": pa.array(source, pa.string()),
            "indicator": pa.array(indicator, pa.string()),
            "sex": pa.array(sex, pa.string()),
            "classif1": pa.array(classif1, pa.string()),
            "classif2": pa.array(classif2, pa.string()),
            "time_period": pa.array(time_period, pa.string()),
            "obs_value": pa.array(obs_value, pa.float64()),
            "obs_status": pa.array(obs_status, pa.string()),
        },
        schema=RAW_SCHEMA,
    )
    save_raw_parquet(table, asset)


from constants import ENTITY_IDS

# id -> (has_sex, n_classif); drives which dimension columns each transform selects
ENTITY_META = {
    'CCF_XOXR_CUR_RT_A': (0, 1),
    'CCF_XPPP_CUR_RT_A': (0, 1),
    'CLD_2POP_SEX_AGE_NB_A': (1, 1),
    'CLD_TPOP_SEX_AGE_GEO_NB_A': (1, 2),
    'CLD_TPOP_SEX_AGE_NB_A': (1, 1),
    'CLD_TPOP_SEX_AGE_STU_NB_A': (1, 2),
    'CLD_XCHL_SEX_AGE_ECO_NB_A': (1, 2),
    'CLD_XCHL_SEX_AGE_GEO_NB_A': (1, 2),
    'CLD_XCHL_SEX_AGE_GEO_RT_A': (1, 2),
    'CLD_XCHL_SEX_AGE_NB_A': (1, 1),
    'CLD_XCHL_SEX_AGE_RT_A': (1, 1),
    'CLD_XCHL_SEX_AGE_STE_NB_A': (1, 2),
    'CLD_XCHL_SEX_AGE_STU_NB_A': (1, 2),
    'CLD_XCHL_SEX_AGE_STU_RT_A': (1, 2),
    'CLD_XGPB_SEX_AGE_GEO_NB_A': (1, 2),
    'CLD_XGPB_SEX_AGE_GEO_RT_A': (1, 2),
    'CLD_XGPB_SEX_AGE_NB_A': (1, 1),
    'CLD_XGPB_SEX_AGE_RT_A': (1, 1),
    'CLD_XGPB_SEX_AGE_STU_NB_A': (1, 2),
    'CLD_XGPB_SEX_AGE_STU_RT_A': (1, 2),
    'CLD_XHAZ_SEX_AGE_ECO_NB_A': (1, 2),
    'CLD_XHAZ_SEX_AGE_GEO_NB_A': (1, 2),
    'CLD_XHAZ_SEX_AGE_GEO_RT_A': (1, 2),
    'CLD_XHAZ_SEX_AGE_NB_A': (1, 1),
    'CLD_XHAZ_SEX_AGE_RT_A': (1, 1),
    'CLD_XHAZ_SEX_AGE_STE_NB_A': (1, 2),
    'CLD_XHAZ_SEX_AGE_STU_NB_A': (1, 2),
    'CLD_XHAZ_SEX_AGE_STU_RT_A': (1, 2),
    'CLD_XSNA_SEX_AGE_ECO_NB_A': (1, 2),
    'CLD_XSNA_SEX_AGE_GEO_NB_A': (1, 2),
    'CLD_XSNA_SEX_AGE_GEO_RT_A': (1, 2),
    'CLD_XSNA_SEX_AGE_NB_A': (1, 1),
    'CLD_XSNA_SEX_AGE_RT_A': (1, 1),
    'CLD_XSNA_SEX_AGE_STE_NB_A': (1, 2),
    'CLD_XSNA_SEX_AGE_STU_NB_A': (1, 2),
    'CLD_XSNA_SEX_AGE_STU_RT_A': (1, 2),
    'CPI_NCPD_COI_RT_M': (0, 1),
    'CPI_NCPD_COI_RT_Q': (0, 1),
    'CPI_NCYR_COI_RT_A': (0, 1),
    'CPI_NCYR_COI_RT_M': (0, 1),
    'CPI_NCYR_COI_RT_Q': (0, 1),
    'CPI_NWGT_COI_RT_A': (0, 1),
    'CPI_XCPI_COI_RT_A': (0, 1),
    'CPI_XCPI_COI_RT_M': (0, 1),
    'CPI_XCPI_COI_RT_Q': (0, 1),
    'EAP_2EAP_SEX_AGE_NB_A': (1, 1),
    'EAP_2WAP_SEX_AGE_RT_A': (1, 1),
    'EAP_3EAP_SEX_AGE_DSB_NB_A': (1, 2),
    'EAP_3EAP_SEX_AGE_EDU_NB_A': (1, 2),
    'EAP_3EAP_SEX_AGE_GEO_NB_A': (1, 2),
    'EAP_3EAP_SEX_AGE_STU_NB_A': (1, 2),
    'EAP_3WAP_SEX_AGE_DSB_RT_A': (1, 2),
    'EAP_3WAP_SEX_AGE_EDU_RT_A': (1, 2),
    'EAP_3WAP_SEX_AGE_GEO_RT_A': (1, 2),
    'EAP_3WAP_SEX_AGE_STU_RT_A': (1, 2),
    'EAP_5EAP_SEX_AGE_NB_A': (1, 1),
    'EAP_5EAP_SEX_AGE_NB_Q': (1, 1),
    'EAP_5WAP_SEX_AGE_RT_A': (1, 1),
    'EAP_5WAP_SEX_AGE_RT_Q': (1, 1),
    'EAP_DWA1_SEX_AGE_RT_M': (1, 1),
    'EAP_DWA1_SEX_AGE_RT_Q': (1, 1),
    'EAP_DWAP_SEX_AGE_CBR_RT_A': (1, 2),
    'EAP_DWAP_SEX_AGE_CCT_RT_A': (1, 2),
    'EAP_DWAP_SEX_AGE_DSB_RT_A': (1, 2),
    'EAP_DWAP_SEX_AGE_DSB_RT_Q': (1, 2),
    'EAP_DWAP_SEX_AGE_EDU_RT_A': (1, 2),
    'EAP_DWAP_SEX_AGE_EDU_RT_M': (1, 2),
    'EAP_DWAP_SEX_AGE_EDU_RT_Q': (1, 2),
    'EAP_DWAP_SEX_AGE_GEO_RT_A': (1, 2),
    'EAP_DWAP_SEX_AGE_GEO_RT_M': (1, 2),
    'EAP_DWAP_SEX_AGE_GEO_RT_Q': (1, 2),
    'EAP_DWAP_SEX_AGE_MTS_RT_A': (1, 2),
    'EAP_DWAP_SEX_AGE_MTS_RT_Q': (1, 2),
    'EAP_DWAP_SEX_AGE_RT_A': (1, 1),
    'EAP_DWAP_SEX_AGE_RT_M': (1, 1),
    'EAP_DWAP_SEX_AGE_RT_Q': (1, 1),
    'EAP_DWAP_SEX_DSB_RT_A': (1, 1),
    'EAP_DWAP_SEX_DSB_RT_Q': (1, 1),
    'EAP_DWAP_SEX_EDU_CBR_RT_A': (1, 2),
    'EAP_DWAP_SEX_EDU_CCT_RT_A': (1, 2),
    'EAP_DWAP_SEX_EDU_DSB_RT_A': (1, 2),
    'EAP_DWAP_SEX_EDU_GEO_RT_A': (1, 2),
    'EAP_DWAP_SEX_EDU_GEO_RT_Q': (1, 2),
    'EAP_DWAP_SEX_EDU_MTS_RT_A': (1, 2),
    'EAP_DWAP_SEX_EDU_MTS_RT_Q': (1, 2),
    'EAP_DWAP_SEX_EDU_RT_A': (1, 1),
    'EAP_DWAP_SEX_EDU_RT_M': (1, 1),
    'EAP_DWAP_SEX_EDU_RT_Q': (1, 1),
    'EAP_DWAP_SEX_GEO_DSB_RT_A': (1, 2),
    'EAP_DWAP_SEX_GEO_MTS_RT_A': (1, 2),
    'EAP_DWAP_SEX_GEO_MTS_RT_Q': (1, 2),
    'EAP_DWAP_SEX_GEO_RT_A': (1, 1),
    'EAP_DWAP_SEX_GEO_RT_Q': (1, 1),
    'EAP_DWAP_SEX_MTS_DSB_RT_A': (1, 2),
    'EAP_DWAP_SEX_MTS_DSB_RT_Q': (1, 2),
    'EAP_DWAP_SEX_MTS_RT_A': (1, 1),
    'EAP_DWAP_SEX_MTS_RT_M': (1, 1),
    'EAP_DWAP_SEX_MTS_RT_Q': (1, 1),
    'EAP_TEA1_SEX_AGE_NB_M': (1, 1),
    'EAP_TEA1_SEX_AGE_NB_Q': (1, 1),
    'EAP_TEAP_SEX_AGE_CBR_NB_A': (1, 2),
    'EAP_TEAP_SEX_AGE_CCT_NB_A': (1, 2),
    'EAP_TEAP_SEX_AGE_DSB_NB_A': (1, 2),
    'EAP_TEAP_SEX_AGE_DSB_NB_Q': (1, 2),
    'EAP_TEAP_SEX_AGE_EDU_NB_A': (1, 2),
    'EAP_TEAP_SEX_AGE_EDU_NB_M': (1, 2),
    'EAP_TEAP_SEX_AGE_EDU_NB_Q': (1, 2),
    'EAP_TEAP_SEX_AGE_GEO_NB_A': (1, 2),
    'EAP_TEAP_SEX_AGE_GEO_NB_M': (1, 2),
    'EAP_TEAP_SEX_AGE_GEO_NB_Q': (1, 2),
    'EAP_TEAP_SEX_AGE_MTS_NB_A': (1, 2),
    'EAP_TEAP_SEX_AGE_MTS_NB_Q': (1, 2),
    'EAP_TEAP_SEX_AGE_NB_A': (1, 1),
    'EAP_TEAP_SEX_AGE_NB_M': (1, 1),
    'EAP_TEAP_SEX_AGE_NB_Q': (1, 1),
    'EAP_TEAP_SEX_DSB_NB_A': (1, 1),
    'EAP_TEAP_SEX_DSB_NB_Q': (1, 1),
    'EAP_TEAP_SEX_EDU_CBR_NB_A': (1, 2),
    'EAP_TEAP_SEX_EDU_CCT_NB_A': (1, 2),
    'EAP_TEAP_SEX_EDU_DSB_NB_A': (1, 2),
    'EAP_TEAP_SEX_EDU_GEO_NB_A': (1, 2),
    'EAP_TEAP_SEX_EDU_GEO_NB_Q': (1, 2),
    'EAP_TEAP_SEX_EDU_MTS_NB_A': (1, 2),
    'EAP_TEAP_SEX_EDU_MTS_NB_Q': (1, 2),
    'EAP_TEAP_SEX_EDU_NB_A': (1, 1),
    'EAP_TEAP_SEX_EDU_NB_M': (1, 1),
    'EAP_TEAP_SEX_EDU_NB_Q': (1, 1),
    'EAP_TEAP_SEX_GEO_DSB_NB_A': (1, 2),
    'EAP_TEAP_SEX_GEO_MTS_NB_A': (1, 2),
    'EAP_TEAP_SEX_GEO_MTS_NB_Q': (1, 2),
    'EAP_TEAP_SEX_GEO_NB_A': (1, 1),
    'EAP_TEAP_SEX_GEO_NB_Q': (1, 1),
    'EAP_TEAP_SEX_MTS_DSB_NB_A': (1, 2),
    'EAP_TEAP_SEX_MTS_DSB_NB_Q': (1, 2),
    'EAP_TEAP_SEX_MTS_NB_A': (1, 1),
    'EAP_TEAP_SEX_MTS_NB_M': (1, 1),
    'EAP_TEAP_SEX_MTS_NB_Q': (1, 1),
    'EAR_CHRA_SEX_CUR_NB_A': (1, 1),
    'EAR_CHRA_SEX_NB_A': (1, 0),
    'EAR_CMTA_SEX_CUR_NB_A': (1, 1),
    'EAR_CMTA_SEX_NB_A': (1, 0),
    'EAR_EHRA_SEX_AGE_CUR_NB_A': (1, 2),
    'EAR_EHRA_SEX_AGE_NB_A': (1, 1),
    'EAR_EHRA_SEX_AGE_NB_M': (1, 1),
    'EAR_EHRA_SEX_AGE_NB_Q': (1, 1),
    'EAR_EHRA_SEX_CUR_NB_A': (1, 1),
    'EAR_EHRA_SEX_DSB_CUR_NB_A': (1, 2),
    'EAR_EHRA_SEX_DSB_NB_A': (1, 1),
    'EAR_EHRA_SEX_DSB_NB_Q': (1, 1),
    'EAR_EHRA_SEX_ECO_CUR_NB_A': (1, 2),
    'EAR_EHRA_SEX_ECO_NB_A': (1, 1),
    'EAR_EHRA_SEX_ECO_NB_M': (1, 1),
    'EAR_EHRA_SEX_ECO_NB_Q': (1, 1),
    'EAR_EHRA_SEX_EDU_CUR_NB_A': (1, 2),
    'EAR_EHRA_SEX_EDU_NB_A': (1, 1),
    'EAR_EHRA_SEX_EDU_NB_Q': (1, 1),
    'EAR_EHRA_SEX_GEO_CUR_NB_A': (1, 2),
    'EAR_EHRA_SEX_GEO_NB_A': (1, 1),
    'EAR_EHRA_SEX_GEO_NB_Q': (1, 1),
    'EAR_EHRA_SEX_IND_CUR_NB_A': (1, 2),
    'EAR_EHRA_SEX_IND_NB_A': (1, 1),
    'EAR_EHRA_SEX_MTS_CUR_NB_A': (1, 2),
    'EAR_EHRA_SEX_MTS_NB_A': (1, 1),
    'EAR_EHRA_SEX_MTS_NB_Q': (1, 1),
    'EAR_EHRA_SEX_NB_A': (1, 0),
    'EAR_EHRA_SEX_NB_M': (1, 0),
    'EAR_EHRA_SEX_NB_Q': (1, 0),
    'EAR_EHRA_SEX_OCU_CUR_NB_A': (1, 2),
    'EAR_EHRA_SEX_OCU_NB_A': (1, 1),
    'EAR_EHRA_SEX_OCU_NB_M': (1, 1),
    'EAR_EHRA_SEX_OCU_NB_Q': (1, 1),
    'EAR_EHRG_SEX_AGE_NB_A': (1, 1),
    'EAR_EHRG_SEX_DSB_NB_A': (1, 1),
    'EAR_EHRG_SEX_ECO_NB_A': (1, 1),
    'EAR_EHRG_SEX_EDU_NB_A': (1, 1),
    'EAR_EHRG_SEX_GEO_NB_A': (1, 1),
    'EAR_EHRG_SEX_MTS_NB_A': (1, 1),
    'EAR_EHRG_SEX_NB_A': (1, 0),
    'EAR_EHRG_SEX_OCU_NB_A': (1, 1),
    'EAR_EHRM_SEX_AGE_CUR_NB_A': (1, 2),
    'EAR_EHRM_SEX_AGE_NB_A': (1, 1),
    'EAR_EHRM_SEX_CUR_NB_A': (1, 1),
    'EAR_EHRM_SEX_DSB_CUR_NB_A': (1, 2),
    'EAR_EHRM_SEX_DSB_NB_A': (1, 1),
    'EAR_EHRM_SEX_ECO_CUR_NB_A': (1, 2),
    'EAR_EHRM_SEX_ECO_NB_A': (1, 1),
    'EAR_EHRM_SEX_EDU_CUR_NB_A': (1, 2),
    'EAR_EHRM_SEX_EDU_NB_A': (1, 1),
    'EAR_EHRM_SEX_GEO_CUR_NB_A': (1, 2),
    'EAR_EHRM_SEX_GEO_NB_A': (1, 1),
    'EAR_EHRM_SEX_MTS_CUR_NB_A': (1, 2),
    'EAR_EHRM_SEX_MTS_NB_A': (1, 1),
    'EAR_EHRM_SEX_NB_A': (1, 0),
    'EAR_EHRM_SEX_OCU_CUR_NB_A': (1, 2),
    'EAR_EHRM_SEX_OCU_NB_A': (1, 1),
    'EAR_EMTA_SEX_AGE_CUR_NB_A': (1, 2),
    'EAR_EMTA_SEX_AGE_NB_A': (1, 1),
    'EAR_EMTA_SEX_AGE_NB_M': (1, 1),
    'EAR_EMTA_SEX_AGE_NB_Q': (1, 1),
    'EAR_EMTA_SEX_CBR_CUR_NB_A': (1, 2),
    'EAR_EMTA_SEX_CBR_NB_A': (1, 1),
    'EAR_EMTA_SEX_CCT_CUR_NB_A': (1, 2),
    'EAR_EMTA_SEX_CCT_NB_A': (1, 1),
    'EAR_EMTA_SEX_CUR_NB_A': (1, 1),
    'EAR_EMTA_SEX_DSB_CUR_NB_A': (1, 2),
    'EAR_EMTA_SEX_DSB_NB_A': (1, 1),
    'EAR_EMTA_SEX_DSB_NB_Q': (1, 1),
    'EAR_EMTA_SEX_ECO_CUR_NB_A': (1, 2),
    'EAR_EMTA_SEX_ECO_NB_A': (1, 1),
    'EAR_EMTA_SEX_ECO_NB_M': (1, 1),
    'EAR_EMTA_SEX_ECO_NB_Q': (1, 1),
    'EAR_EMTA_SEX_EDU_CUR_NB_A': (1, 2),
    'EAR_EMTA_SEX_EDU_NB_A': (1, 1),
    'EAR_EMTA_SEX_EDU_NB_Q': (1, 1),
    'EAR_EMTA_SEX_GEO_CUR_NB_A': (1, 2),
    'EAR_EMTA_SEX_GEO_NB_A': (1, 1),
    'EAR_EMTA_SEX_GEO_NB_Q': (1, 1),
    'EAR_EMTA_SEX_IND_CUR_NB_A': (1, 2),
    'EAR_EMTA_SEX_IND_NB_A': (1, 1),
    'EAR_EMTA_SEX_MTS_CUR_NB_A': (1, 2),
    'EAR_EMTA_SEX_MTS_NB_A': (1, 1),
    'EAR_EMTA_SEX_MTS_NB_Q': (1, 1),
    'EAR_EMTA_SEX_NB_A': (1, 0),
    'EAR_EMTA_SEX_NB_M': (1, 0),
    'EAR_EMTA_SEX_NB_Q': (1, 0),
    'EAR_EMTA_SEX_OCU_CUR_NB_A': (1, 2),
    'EAR_EMTA_SEX_OCU_NB_A': (1, 1),
    'EAR_EMTA_SEX_OCU_NB_M': (1, 1),
    'EAR_EMTA_SEX_OCU_NB_Q': (1, 1),
    'EAR_EMTG_SEX_AGE_NB_A': (1, 1),
    'EAR_EMTG_SEX_DSB_NB_A': (1, 1),
    'EAR_EMTG_SEX_ECO_NB_A': (1, 1),
    'EAR_EMTG_SEX_EDU_NB_A': (1, 1),
    'EAR_EMTG_SEX_GEO_NB_A': (1, 1),
    'EAR_EMTG_SEX_MTS_NB_A': (1, 1),
    'EAR_EMTG_SEX_NB_A': (1, 0),
    'EAR_EMTG_SEX_OCU_NB_A': (1, 1),
    'EAR_EMTM_SEX_AGE_CUR_NB_A': (1, 2),
    'EAR_EMTM_SEX_AGE_NB_A': (1, 1),
    'EAR_EMTM_SEX_CUR_NB_A': (1, 1),
    'EAR_EMTM_SEX_DSB_CUR_NB_A': (1, 2),
    'EAR_EMTM_SEX_DSB_NB_A': (1, 1),
    'EAR_EMTM_SEX_ECO_CUR_NB_A': (1, 2),
    'EAR_EMTM_SEX_ECO_NB_A': (1, 1),
    'EAR_EMTM_SEX_EDU_CUR_NB_A': (1, 2),
    'EAR_EMTM_SEX_EDU_NB_A': (1, 1),
    'EAR_EMTM_SEX_GEO_CUR_NB_A': (1, 2),
    'EAR_EMTM_SEX_GEO_NB_A': (1, 1),
    'EAR_EMTM_SEX_MTS_CUR_NB_A': (1, 2),
    'EAR_EMTM_SEX_MTS_NB_A': (1, 1),
    'EAR_EMTM_SEX_NB_A': (1, 0),
    'EAR_EMTM_SEX_OCU_CUR_NB_A': (1, 2),
    'EAR_EMTM_SEX_OCU_NB_A': (1, 1),
    'EAR_GGAP_OCU_RT_A': (0, 1),
    'EAR_INEE_CUR_NB_A': (0, 1),
    'EAR_INEE_NOC_NB_A': (1, 2),
    'EAR_PHRA_SEX_CUR_NB_A': (1, 1),
    'EAR_PHRA_SEX_NB_A': (1, 0),
    'EAR_PMTA_SEX_CUR_NB_A': (1, 1),
    'EAR_PMTA_SEX_NB_A': (1, 0),
    'EAR_SHRA_SEX_CUR_NB_A': (1, 1),
    'EAR_SHRA_SEX_NB_A': (1, 0),
    'EAR_SMTA_SEX_CUR_NB_A': (1, 1),
    'EAR_SMTA_SEX_NB_A': (1, 0),
    'EAR_XFLS_NOC_RT_A': (1, 2),
    'EAR_XTLP_SEX_RT_A': (1, 0),
    'EES_3EES_SEX_AGE_JBC_NB_A': (1, 2),
    'EES_CARE_SEX_INS_NB_A': (1, 1),
    'EES_CARE_SEX_JBC_NB_A': (1, 1),
    'EES_PUBL_SEX_JBC_NB_A': (1, 1),
    'EES_STEM_SEX_INS_NB_A': (1, 1),
    'EES_STEM_SEX_JBC_NB_A': (1, 1),
    'EES_TEES_AGE_EC2_NB_A': (0, 2),
    'EES_TEES_AGE_OC2_NB_A': (0, 2),
    'EES_TEES_ECO_OCU_NB_A': (0, 2),
    'EES_TEES_ECO_OCU_NB_Q': (0, 2),
    'EES_TEES_SEX_AGE_DSB_NB_A': (1, 2),
    'EES_TEES_SEX_AGE_DSB_NB_Q': (1, 2),
    'EES_TEES_SEX_AGE_ECO_NB_A': (1, 2),
    'EES_TEES_SEX_AGE_ECO_NB_Q': (1, 2),
    'EES_TEES_SEX_AGE_EDU_NB_A': (1, 2),
    'EES_TEES_SEX_AGE_EDU_NB_M': (1, 2),
    'EES_TEES_SEX_AGE_EDU_NB_Q': (1, 2),
    'EES_TEES_SEX_AGE_GEO_NB_A': (1, 2),
    'EES_TEES_SEX_AGE_GEO_NB_Q': (1, 2),
    'EES_TEES_SEX_AGE_INS_NB_A': (1, 2),
    'EES_TEES_SEX_AGE_INS_NB_Q': (1, 2),
    'EES_TEES_SEX_AGE_JBC_NB_A': (1, 2),
    'EES_TEES_SEX_AGE_JBC_NB_Q': (1, 2),
    'EES_TEES_SEX_AGE_MTS_NB_A': (1, 2),
    'EES_TEES_SEX_AGE_MTS_NB_Q': (1, 2),
    'EES_TEES_SEX_AGE_NB_A': (1, 1),
    'EES_TEES_SEX_AGE_NB_M': (1, 1),
    'EES_TEES_SEX_AGE_NB_Q': (1, 1),
    'EES_TEES_SEX_AGE_OCU_NB_A': (1, 2),
    'EES_TEES_SEX_AGE_OCU_NB_Q': (1, 2),
    'EES_TEES_SEX_DSB_NB_A': (1, 1),
    'EES_TEES_SEX_DSB_NB_Q': (1, 1),
    'EES_TEES_SEX_EC2_NB_A': (1, 1),
    'EES_TEES_SEX_ECO_DSB_NB_A': (1, 2),
    'EES_TEES_SEX_ECO_EDU_NB_A': (1, 2),
    'EES_TEES_SEX_ECO_EDU_NB_Q': (1, 2),
    'EES_TEES_SEX_ECO_EST_NB_A': (1, 2),
    'EES_TEES_SEX_ECO_EST_NB_Q': (1, 2),
    'EES_TEES_SEX_ECO_GEO_NB_A': (1, 2),
    'EES_TEES_SEX_ECO_INS_NB_A': (1, 2),
    'EES_TEES_SEX_ECO_INS_NB_M': (1, 2),
    'EES_TEES_SEX_ECO_INS_NB_Q': (1, 2),
    'EES_TEES_SEX_ECO_MTS_NB_A': (1, 2),
    'EES_TEES_SEX_ECO_MTS_NB_Q': (1, 2),
    'EES_TEES_SEX_ECO_NB_A': (1, 1),
    'EES_TEES_SEX_ECO_NB_M': (1, 1),
    'EES_TEES_SEX_ECO_NB_Q': (1, 1),
    'EES_TEES_SEX_EDU_DSB_NB_A': (1, 2),
    'EES_TEES_SEX_EDU_GEO_NB_A': (1, 2),
    'EES_TEES_SEX_EDU_GEO_NB_Q': (1, 2),
    'EES_TEES_SEX_EDU_MTS_NB_A': (1, 2),
    'EES_TEES_SEX_EDU_MTS_NB_Q': (1, 2),
    'EES_TEES_SEX_EDU_NB_A': (1, 1),
    'EES_TEES_SEX_EDU_NB_M': (1, 1),
    'EES_TEES_SEX_EDU_NB_Q': (1, 1),
    'EES_TEES_SEX_EST_DSB_NB_A': (1, 2),
    'EES_TEES_SEX_EST_DSB_NB_Q': (1, 2),
    'EES_TEES_SEX_EST_GEO_NB_A': (1, 2),
    'EES_TEES_SEX_EST_GEO_NB_Q': (1, 2),
    'EES_TEES_SEX_EST_MTS_NB_A': (1, 2),
    'EES_TEES_SEX_EST_MTS_NB_Q': (1, 2),
    'EES_TEES_SEX_EST_NB_A': (1, 1),
    'EES_TEES_SEX_EST_NB_M': (1, 1),
    'EES_TEES_SEX_EST_NB_Q': (1, 1),
    'EES_TEES_SEX_GEO_DSB_NB_A': (1, 2),
    'EES_TEES_SEX_GEO_DSB_NB_Q': (1, 2),
    'EES_TEES_SEX_GEO_MTS_NB_A': (1, 2),
    'EES_TEES_SEX_GEO_MTS_NB_Q': (1, 2),
    'EES_TEES_SEX_GEO_NB_A': (1, 1),
    'EES_TEES_SEX_GEO_NB_Q': (1, 1),
    'EES_TEES_SEX_HOW_NB_A': (1, 1),
    'EES_TEES_SEX_HOW_NB_Q': (1, 1),
    'EES_TEES_SEX_IFL_EC2_NB_A': (1, 2),
    'EES_TEES_SEX_IFL_ECO_NB_A': (1, 2),
    'EES_TEES_SEX_IFL_ECO_NB_Q': (1, 2),
    'EES_TEES_SEX_IFL_EDU_NB_A': (1, 2),
    'EES_TEES_SEX_IFL_EDU_NB_Q': (1, 2),
    'EES_TEES_SEX_IFL_GEO_NB_A': (1, 2),
    'EES_TEES_SEX_IFL_GEO_NB_Q': (1, 2),
    'EES_TEES_SEX_IFL_INS_NB_A': (1, 2),
    'EES_TEES_SEX_IFL_INS_NB_Q': (1, 2),
    'EES_TEES_SEX_IFL_MTS_NB_A': (1, 2),
    'EES_TEES_SEX_IFL_MTS_NB_Q': (1, 2),
    'EES_TEES_SEX_IFL_OCU_NB_A': (1, 2),
    'EES_TEES_SEX_IFL_OCU_NB_Q': (1, 2),
    'EES_TEES_SEX_IND_JBC_NB_A': (1, 2),
    'EES_TEES_SEX_INS_DSB_NB_A': (1, 2),
    'EES_TEES_SEX_INS_DSB_NB_Q': (1, 2),
    'EES_TEES_SEX_INS_GEO_NB_A': (1, 2),
    'EES_TEES_SEX_INS_GEO_NB_Q': (1, 2),
    'EES_TEES_SEX_INS_MTS_NB_A': (1, 2),
    'EES_TEES_SEX_INS_MTS_NB_Q': (1, 2),
    'EES_TEES_SEX_INS_NB_A': (1, 1),
    'EES_TEES_SEX_INS_NB_Q': (1, 1),
    'EES_TEES_SEX_MJH_NB_A': (1, 1),
    'EES_TEES_SEX_MJH_NB_Q': (1, 1),
    'EES_TEES_SEX_MTS_DSB_NB_A': (1, 2),
    'EES_TEES_SEX_MTS_DSB_NB_Q': (1, 2),
    'EES_TEES_SEX_MTS_NB_A': (1, 1),
    'EES_TEES_SEX_MTS_NB_M': (1, 1),
    'EES_TEES_SEX_MTS_NB_Q': (1, 1),
    'EES_TEES_SEX_OC2_NB_A': (1, 1),
    'EES_TEES_SEX_OCU_DSB_NB_A': (1, 2),
    'EES_TEES_SEX_OCU_EDU_NB_A': (1, 2),
    'EES_TEES_SEX_OCU_EDU_NB_Q': (1, 2),
    'EES_TEES_SEX_OCU_EST_NB_A': (1, 2),
    'EES_TEES_SEX_OCU_EST_NB_Q': (1, 2),
    'EES_TEES_SEX_OCU_GEO_NB_A': (1, 2),
    'EES_TEES_SEX_OCU_INS_NB_A': (1, 2),
    'EES_TEES_SEX_OCU_INS_NB_Q': (1, 2),
    'EES_TEES_SEX_OCU_MTS_NB_A': (1, 2),
    'EES_TEES_SEX_OCU_MTS_NB_Q': (1, 2),
    'EES_TEES_SEX_OCU_NB_A': (1, 1),
    'EES_TEES_SEX_OCU_NB_M': (1, 1),
    'EES_TEES_SEX_OCU_NB_Q': (1, 1),
    'EES_XPLV_SEX_RT_A': (1, 0),
    'EES_XTMP_SEX_RT_A': (1, 0),
    'EIP_2EET_SEX_NB_A': (1, 0),
    'EIP_2EET_SEX_RT_A': (1, 0),
    'EIP_2EIP_SEX_AGE_NB_A': (1, 1),
    'EIP_2JOB_SEX_NB_A': (1, 0),
    'EIP_2JOB_SEX_RT_A': (1, 0),
    'EIP_2PLF_SEX_NB_A': (1, 0),
    'EIP_2PLF_SEX_RT_A': (1, 0),
    'EIP_2WAP_SEX_AGE_RT_A': (1, 1),
    'EIP_3DIS_SEX_AGE_GEO_NB_A': (1, 2),
    'EIP_3EIP_SEX_AGE_DSB_NB_A': (1, 2),
    'EIP_3EIP_SEX_AGE_EDU_NB_A': (1, 2),
    'EIP_3EIP_SEX_AGE_GEO_NB_A': (1, 2),
    'EIP_3EIP_SEX_AGE_STU_NB_A': (1, 2),
    'EIP_3WAP_SEX_AGE_DSB_RT_A': (1, 2),
    'EIP_3WAP_SEX_AGE_EDU_RT_A': (1, 2),
    'EIP_3WAP_SEX_AGE_GEO_RT_A': (1, 2),
    'EIP_3WAP_SEX_AGE_STU_RT_A': (1, 2),
    'EIP_5EET_SEX_NB_A': (1, 0),
    'EIP_5EET_SEX_NB_Q': (1, 0),
    'EIP_5EET_SEX_RT_A': (1, 0),
    'EIP_5EET_SEX_RT_Q': (1, 0),
    'EIP_5EIP_SEX_AGE_NB_A': (1, 1),
    'EIP_5EIP_SEX_AGE_NB_Q': (1, 1),
    'EIP_5PLF_SEX_AGE_NB_A': (1, 1),
    'EIP_5PLF_SEX_AGE_NB_Q': (1, 1),
    'EIP_5WAP_SEX_AGE_RT_A': (1, 1),
    'EIP_5WAP_SEX_AGE_RT_Q': (1, 1),
    'EIP_DWAP_SEX_AGE_CBR_RT_A': (1, 2),
    'EIP_DWAP_SEX_AGE_CCT_RT_A': (1, 2),
    'EIP_DWAP_SEX_AGE_DSB_RT_A': (1, 2),
    'EIP_DWAP_SEX_AGE_EDU_RT_A': (1, 2),
    'EIP_DWAP_SEX_AGE_EDU_RT_Q': (1, 2),
    'EIP_DWAP_SEX_AGE_GEO_RT_A': (1, 2),
    'EIP_DWAP_SEX_AGE_GEO_RT_Q': (1, 2),
    'EIP_DWAP_SEX_AGE_MTS_RT_A': (1, 2),
    'EIP_DWAP_SEX_AGE_MTS_RT_Q': (1, 2),
    'EIP_DWAP_SEX_AGE_RT_A': (1, 1),
    'EIP_DWAP_SEX_AGE_RT_M': (1, 1),
    'EIP_DWAP_SEX_AGE_RT_Q': (1, 1),
    'EIP_DWAP_SEX_DSB_RT_A': (1, 1),
    'EIP_DWAP_SEX_EDU_CBR_RT_A': (1, 2),
    'EIP_DWAP_SEX_EDU_CCT_RT_A': (1, 2),
    'EIP_DWAP_SEX_EDU_DSB_RT_A': (1, 2),
    'EIP_DWAP_SEX_EDU_GEO_RT_A': (1, 2),
    'EIP_DWAP_SEX_EDU_GEO_RT_Q': (1, 2),
    'EIP_DWAP_SEX_EDU_MTS_RT_A': (1, 2),
    'EIP_DWAP_SEX_EDU_MTS_RT_Q': (1, 2),
    'EIP_DWAP_SEX_EDU_RT_A': (1, 1),
    'EIP_DWAP_SEX_EDU_RT_Q': (1, 1),
    'EIP_DWAP_SEX_GEO_DSB_RT_A': (1, 2),
    'EIP_DWAP_SEX_GEO_MTS_RT_A': (1, 2),
    'EIP_DWAP_SEX_GEO_MTS_RT_Q': (1, 2),
    'EIP_DWAP_SEX_GEO_RT_A': (1, 1),
    'EIP_DWAP_SEX_GEO_RT_Q': (1, 1),
    'EIP_DWAP_SEX_MTS_DSB_RT_A': (1, 2),
    'EIP_DWAP_SEX_MTS_RT_A': (1, 1),
    'EIP_DWAP_SEX_MTS_RT_Q': (1, 1),
    'EIP_NEET_SEX_AGE_NB_A': (1, 1),
    'EIP_NEET_SEX_AGE_RT_A': (1, 1),
    'EIP_NEET_SEX_CBR_NB_A': (1, 1),
    'EIP_NEET_SEX_CBR_RT_A': (1, 1),
    'EIP_NEET_SEX_CCT_RT_A': (1, 1),
    'EIP_NEET_SEX_DSB_NB_A': (1, 1),
    'EIP_NEET_SEX_DSB_RT_A': (1, 1),
    'EIP_NEET_SEX_EDU_NB_A': (1, 1),
    'EIP_NEET_SEX_EDU_RT_A': (1, 1),
    'EIP_NEET_SEX_GEO_NB_A': (1, 1),
    'EIP_NEET_SEX_GEO_RT_A': (1, 1),
    'EIP_NEET_SEX_MTS_NB_A': (1, 1),
    'EIP_NEET_SEX_MTS_RT_A': (1, 1),
    'EIP_NEET_SEX_NB_A': (1, 0),
    'EIP_NEET_SEX_NB_Q': (1, 0),
    'EIP_NEET_SEX_RT_A': (1, 0),
    'EIP_NEET_SEX_RT_Q': (1, 0),
    'EIP_RCAR_SEX_AGE_RT_A': (1, 1),
    'EIP_RCAR_SEX_EDU_RT_A': (1, 1),
    'EIP_RCAR_SEX_GEO_RT_A': (1, 1),
    'EIP_RCAR_SEX_RT_A': (1, 0),
    'EIP_TEIP_SEX_AGE_CBR_NB_A': (1, 2),
    'EIP_TEIP_SEX_AGE_CCT_NB_A': (1, 2),
    'EIP_TEIP_SEX_AGE_DSB_NB_A': (1, 2),
    'EIP_TEIP_SEX_AGE_EDU_NB_A': (1, 2),
    'EIP_TEIP_SEX_AGE_EDU_NB_Q': (1, 2),
    'EIP_TEIP_SEX_AGE_GEO_NB_A': (1, 2),
    'EIP_TEIP_SEX_AGE_GEO_NB_Q': (1, 2),
    'EIP_TEIP_SEX_AGE_MTS_NB_A': (1, 2),
    'EIP_TEIP_SEX_AGE_MTS_NB_Q': (1, 2),
    'EIP_TEIP_SEX_AGE_NB_A': (1, 1),
    'EIP_TEIP_SEX_AGE_NB_M': (1, 1),
    'EIP_TEIP_SEX_AGE_NB_Q': (1, 1),
    'EIP_TEIP_SEX_DSB_NB_A': (1, 1),
    'EIP_TEIP_SEX_EDU_CBR_NB_A': (1, 2),
    'EIP_TEIP_SEX_EDU_CCT_NB_A': (1, 2),
    'EIP_TEIP_SEX_EDU_DSB_NB_A': (1, 2),
    'EIP_TEIP_SEX_EDU_GEO_NB_A': (1, 2),
    'EIP_TEIP_SEX_EDU_GEO_NB_Q': (1, 2),
    'EIP_TEIP_SEX_EDU_MTS_NB_A': (1, 2),
    'EIP_TEIP_SEX_EDU_MTS_NB_Q': (1, 2),
    'EIP_TEIP_SEX_EDU_NB_A': (1, 1),
    'EIP_TEIP_SEX_EDU_NB_Q': (1, 1),
    'EIP_TEIP_SEX_GEO_DSB_NB_A': (1, 2),
    'EIP_TEIP_SEX_GEO_MTS_NB_A': (1, 2),
    'EIP_TEIP_SEX_GEO_MTS_NB_Q': (1, 2),
    'EIP_TEIP_SEX_GEO_NB_A': (1, 1),
    'EIP_TEIP_SEX_GEO_NB_Q': (1, 1),
    'EIP_TEIP_SEX_MTS_DSB_NB_A': (1, 2),
    'EIP_TEIP_SEX_MTS_NB_A': (1, 1),
    'EIP_TEIP_SEX_MTS_NB_Q': (1, 1),
    'EIP_WDIS_SEX_AGE_EDU_NB_A': (1, 2),
    'EIP_WDIS_SEX_AGE_EDU_NB_Q': (1, 2),
    'EIP_WDIS_SEX_AGE_GEO_NB_A': (1, 2),
    'EIP_WDIS_SEX_AGE_GEO_NB_Q': (1, 2),
    'EIP_WDIS_SEX_AGE_MTS_NB_A': (1, 2),
    'EIP_WDIS_SEX_AGE_MTS_NB_Q': (1, 2),
    'EIP_WDIS_SEX_AGE_NB_A': (1, 1),
    'EIP_WDIS_SEX_AGE_NB_Q': (1, 1),
    'EIP_WDIS_SEX_EDU_GEO_NB_A': (1, 2),
    'EIP_WDIS_SEX_EDU_GEO_NB_Q': (1, 2),
    'EIP_WDIS_SEX_EDU_MTS_NB_A': (1, 2),
    'EIP_WDIS_SEX_EDU_MTS_NB_Q': (1, 2),
    'EIP_WDIS_SEX_EDU_NB_A': (1, 1),
    'EIP_WDIS_SEX_EDU_NB_Q': (1, 1),
    'EIP_WDIS_SEX_GEO_MTS_NB_A': (1, 2),
    'EIP_WDIS_SEX_GEO_MTS_NB_Q': (1, 2),
    'EIP_WDIS_SEX_GEO_NB_A': (1, 1),
    'EIP_WDIS_SEX_GEO_NB_Q': (1, 1),
    'EIP_WDIS_SEX_MTS_NB_A': (1, 1),
    'EIP_WDIS_SEX_MTS_NB_Q': (1, 1),
    'EIP_XJOB_SEX_NB_A': (1, 0),
    'EIP_XJOB_SEX_NB_Q': (1, 0),
    'EIP_XJOB_SEX_RT_A': (1, 0),
    'EIP_XJOB_SEX_RT_Q': (1, 0),
    'EIP_XPLF_SEX_AGE_EDU_NB_A': (1, 2),
    'EIP_XPLF_SEX_AGE_EDU_NB_Q': (1, 2),
    'EIP_XPLF_SEX_AGE_GEO_NB_A': (1, 2),
    'EIP_XPLF_SEX_AGE_GEO_NB_Q': (1, 2),
    'EIP_XPLF_SEX_AGE_MTS_NB_A': (1, 2),
    'EIP_XPLF_SEX_AGE_MTS_NB_Q': (1, 2),
    'EIP_XPLF_SEX_AGE_NB_A': (1, 1),
    'EIP_XPLF_SEX_AGE_NB_Q': (1, 1),
    'EIP_XPLF_SEX_EDU_GEO_NB_A': (1, 2),
    'EIP_XPLF_SEX_EDU_GEO_NB_Q': (1, 2),
    'EIP_XPLF_SEX_EDU_MTS_NB_A': (1, 2),
    'EIP_XPLF_SEX_EDU_MTS_NB_Q': (1, 2),
    'EIP_XPLF_SEX_EDU_NB_A': (1, 1),
    'EIP_XPLF_SEX_EDU_NB_Q': (1, 1),
    'EIP_XPLF_SEX_GEO_MTS_NB_A': (1, 2),
    'EIP_XPLF_SEX_GEO_MTS_NB_Q': (1, 2),
    'EIP_XPLF_SEX_GEO_NB_A': (1, 1),
    'EIP_XPLF_SEX_GEO_NB_Q': (1, 1),
    'EIP_XPLF_SEX_MTS_NB_A': (1, 1),
    'EIP_XPLF_SEX_MTS_NB_Q': (1, 1),
    'EIP_XPLF_SEX_NB_A': (1, 0),
    'EIP_XPLF_SEX_NB_Q': (1, 0),
    'EIP_XPLF_SEX_RT_A': (1, 0),
    'EMP_2EMP_AGE_STE_NB_A': (0, 2),
    'EMP_2EMP_SEX_AGE_CLA_NB_A': (1, 2),
    'EMP_2EMP_SEX_AGE_NB_A': (1, 1),
    'EMP_2EMP_SEX_ECO_NB_A': (1, 1),
    'EMP_2EMP_SEX_OCU_NB_A': (1, 1),
    'EMP_2EMP_SEX_STE_NB_A': (1, 1),
    'EMP_2FTE_SEX_JBF_NB_A': (1, 1),
    'EMP_2IFL_SEX_NB_A': (1, 0),
    'EMP_2IFL_SEX_RT_A': (1, 0),
    'EMP_2TRU_SEX_AGE_NB_A': (1, 1),
    'EMP_2TRU_SEX_AGE_RT_A': (1, 1),
    'EMP_2WAP_SEX_AGE_RT_A': (1, 1),
    'EMP_3EMP_SEX_AGE_DSB_NB_A': (1, 2),
    'EMP_3EMP_SEX_AGE_ECO_NB_A': (1, 2),
    'EMP_3EMP_SEX_AGE_EDU_NB_A': (1, 2),
    'EMP_3EMP_SEX_AGE_GAI_NB_A': (1, 2),
    'EMP_3EMP_SEX_AGE_GEO_NB_A': (1, 2),
    'EMP_3EMP_SEX_AGE_HOW_NB_A': (1, 2),
    'EMP_3EMP_SEX_AGE_JBT_NB_A': (1, 2),
    'EMP_3EMP_SEX_AGE_OCU_NB_A': (1, 2),
    'EMP_3EMP_SEX_AGE_STE_NB_A': (1, 2),
    'EMP_3EMP_SEX_AGE_STU_NB_A': (1, 2),
    'EMP_3TRU_SEX_AGE_GEO_NB_A': (1, 2),
    'EMP_3TRU_SEX_AGE_GEO_RT_A': (1, 2),
    'EMP_3WAP_SEX_AGE_DSB_RT_A': (1, 2),
    'EMP_3WAP_SEX_AGE_EDU_RT_A': (1, 2),
    'EMP_3WAP_SEX_AGE_GEO_RT_A': (1, 2),
    'EMP_3WAP_SEX_AGE_STU_RT_A': (1, 2),
    'EMP_5EMP_SEX_AGE_NB_A': (1, 1),
    'EMP_5EMP_SEX_AGE_NB_Q': (1, 1),
    'EMP_5EMP_SEX_ECO_NB_A': (1, 1),
    'EMP_5EMP_SEX_ECO_NB_Q': (1, 1),
    'EMP_5EMP_SEX_OC2_NB_A': (1, 1),
    'EMP_5EMP_SEX_OC2_NB_Q': (1, 1),
    'EMP_5EMP_SEX_OCU_NB_A': (1, 1),
    'EMP_5EMP_SEX_OCU_NB_Q': (1, 1),
    'EMP_5EMP_SEX_STE_NB_A': (1, 1),
    'EMP_5NIF_SEX_AGE_NB_A': (1, 1),
    'EMP_5NIF_SEX_AGE_RT_A': (1, 1),
    'EMP_5NIF_SEX_ECO_RT_A': (1, 1),
    'EMP_5PIF_SEX_AGE_NB_A': (1, 1),
    'EMP_5PIF_SEX_AGE_RT_A': (1, 1),
    'EMP_5TRU_SEX_AGE_NB_A': (1, 1),
    'EMP_5TRU_SEX_AGE_NB_Q': (1, 1),
    'EMP_5TRU_SEX_AGE_RT_A': (1, 1),
    'EMP_5TRU_SEX_AGE_RT_Q': (1, 1),
    'EMP_5WAP_SEX_AGE_RT_A': (1, 1),
    'EMP_5WAP_SEX_AGE_RT_Q': (1, 1),
    'EMP_CARE_SEX_AGE_NB_A': (1, 1),
    'EMP_CARE_SEX_EC2_NB_A': (1, 1),
    'EMP_CARE_SEX_ECO_NB_A': (1, 1),
    'EMP_CARE_SEX_EDU_NB_A': (1, 1),
    'EMP_CARE_SEX_JBT_NB_A': (1, 1),
    'EMP_CARE_SEX_OC2_NB_A': (1, 1),
    'EMP_CARE_SEX_OCU_NB_A': (1, 1),
    'EMP_CARE_SEX_STE_NB_A': (1, 1),
    'EMP_DWA1_SEX_AGE_RT_M': (1, 1),
    'EMP_DWA1_SEX_AGE_RT_Q': (1, 1),
    'EMP_DWAP_SEX_AGE_CBR_RT_A': (1, 2),
    'EMP_DWAP_SEX_AGE_CCT_RT_A': (1, 2),
    'EMP_DWAP_SEX_AGE_DSB_RT_A': (1, 2),
    'EMP_DWAP_SEX_AGE_DSB_RT_Q': (1, 2),
    'EMP_DWAP_SEX_AGE_EDU_RT_A': (1, 2),
    'EMP_DWAP_SEX_AGE_EDU_RT_M': (1, 2),
    'EMP_DWAP_SEX_AGE_EDU_RT_Q': (1, 2),
    'EMP_DWAP_SEX_AGE_GEO_RT_A': (1, 2),
    'EMP_DWAP_SEX_AGE_GEO_RT_Q': (1, 2),
    'EMP_DWAP_SEX_AGE_MTS_RT_A': (1, 2),
    'EMP_DWAP_SEX_AGE_MTS_RT_Q': (1, 2),
    'EMP_DWAP_SEX_AGE_RT_A': (1, 1),
    'EMP_DWAP_SEX_AGE_RT_M': (1, 1),
    'EMP_DWAP_SEX_AGE_RT_Q': (1, 1),
    'EMP_DWAP_SEX_DSB_RT_A': (1, 1),
    'EMP_DWAP_SEX_DSB_RT_Q': (1, 1),
    'EMP_DWAP_SEX_EDU_CBR_RT_A': (1, 2),
    'EMP_DWAP_SEX_EDU_CCT_RT_A': (1, 2),
    'EMP_DWAP_SEX_EDU_DSB_RT_A': (1, 2),
    'EMP_DWAP_SEX_EDU_GEO_RT_A': (1, 2),
    'EMP_DWAP_SEX_EDU_GEO_RT_Q': (1, 2),
    'EMP_DWAP_SEX_EDU_MTS_RT_A': (1, 2),
    'EMP_DWAP_SEX_EDU_MTS_RT_Q': (1, 2),
    'EMP_DWAP_SEX_EDU_RT_A': (1, 1),
    'EMP_DWAP_SEX_EDU_RT_M': (1, 1),
    'EMP_DWAP_SEX_EDU_RT_Q': (1, 1),
    'EMP_DWAP_SEX_GEO_DSB_RT_A': (1, 2),
    'EMP_DWAP_SEX_GEO_MTS_RT_A': (1, 2),
    'EMP_DWAP_SEX_GEO_MTS_RT_Q': (1, 2),
    'EMP_DWAP_SEX_GEO_RT_A': (1, 1),
    'EMP_DWAP_SEX_GEO_RT_Q': (1, 1),
    'EMP_DWAP_SEX_MTS_DSB_RT_A': (1, 2),
    'EMP_DWAP_SEX_MTS_DSB_RT_Q': (1, 2),
    'EMP_DWAP_SEX_MTS_RT_A': (1, 1),
    'EMP_DWAP_SEX_MTS_RT_M': (1, 1),
    'EMP_DWAP_SEX_MTS_RT_Q': (1, 1),
    'EMP_NIFL_AGE_OC2_NB_A': (0, 2),
    'EMP_NIFL_AGE_OC2_RT_A': (0, 2),
    'EMP_NIFL_ECO_OCU_NB_A': (0, 2),
    'EMP_NIFL_ECO_OCU_RT_A': (0, 2),
    'EMP_NIFL_SEX_AGE_ECO_NB_A': (1, 2),
    'EMP_NIFL_SEX_AGE_ECO_RT_A': (1, 2),
    'EMP_NIFL_SEX_AGE_JBT_NB_A': (1, 2),
    'EMP_NIFL_SEX_AGE_JBT_RT_A': (1, 2),
    'EMP_NIFL_SEX_AGE_NB_A': (1, 1),
    'EMP_NIFL_SEX_AGE_OCU_NB_A': (1, 2),
    'EMP_NIFL_SEX_AGE_OCU_RT_A': (1, 2),
    'EMP_NIFL_SEX_AGE_RT_A': (1, 1),
    'EMP_NIFL_SEX_ECO_NB_A': (1, 1),
    'EMP_NIFL_SEX_ECO_RT_A': (1, 1),
    'EMP_NIFL_SEX_IND_NB_A': (1, 1),
    'EMP_NIFL_SEX_IND_RT_A': (1, 1),
    'EMP_NIFL_SEX_NB_A': (1, 0),
    'EMP_NIFL_SEX_OC2_NB_A': (1, 1),
    'EMP_NIFL_SEX_OC2_RT_A': (1, 1),
    'EMP_NIFL_SEX_OCU_NB_A': (1, 1),
    'EMP_NIFL_SEX_OCU_RT_A': (1, 1),
    'EMP_NIFL_SEX_RT_A': (1, 0),
    'EMP_NIFL_SEX_STE_NB_A': (1, 1),
    'EMP_NIFL_SEX_STE_RT_A': (1, 1),
    'EMP_PIFL_AGE_OC2_NB_A': (0, 2),
    'EMP_PIFL_AGE_OC2_RT_A': (0, 2),
    'EMP_PIFL_ECO_OCU_NB_A': (0, 2),
    'EMP_PIFL_ECO_OCU_RT_A': (0, 2),
    'EMP_PIFL_SEX_AGE_ECO_NB_A': (1, 2),
    'EMP_PIFL_SEX_AGE_ECO_RT_A': (1, 2),
    'EMP_PIFL_SEX_AGE_JBT_NB_A': (1, 2),
    'EMP_PIFL_SEX_AGE_JBT_RT_A': (1, 2),
    'EMP_PIFL_SEX_AGE_NB_A': (1, 1),
    'EMP_PIFL_SEX_AGE_OCU_NB_A': (1, 2),
    'EMP_PIFL_SEX_AGE_OCU_RT_A': (1, 2),
    'EMP_PIFL_SEX_AGE_RT_A': (1, 1),
    'EMP_PIFL_SEX_ECO_NB_A': (1, 1),
    'EMP_PIFL_SEX_ECO_RT_A': (1, 1),
    'EMP_PIFL_SEX_NB_A': (1, 0),
    'EMP_PIFL_SEX_OC2_NB_A': (1, 1),
    'EMP_PIFL_SEX_OC2_RT_A': (1, 1),
    'EMP_PIFL_SEX_OCU_NB_A': (1, 1),
    'EMP_PIFL_SEX_OCU_RT_A': (1, 1),
    'EMP_PIFL_SEX_RT_A': (1, 0),
    'EMP_PIFL_SEX_STE_NB_A': (1, 1),
    'EMP_PIFL_SEX_STE_RT_A': (1, 1),
    'EMP_PTER_SEX_RT_A': (1, 0),
    'EMP_PUBL_SEX_AGE_NB_A': (1, 1),
    'EMP_PUBL_SEX_EC2_NB_A': (1, 1),
    'EMP_PUBL_SEX_ECO_NB_A': (1, 1),
    'EMP_PUBL_SEX_EDU_NB_A': (1, 1),
    'EMP_PUBL_SEX_HOW_NB_A': (1, 1),
    'EMP_PUBL_SEX_JBT_NB_A': (1, 1),
    'EMP_PUBL_SEX_MTS_NB_A': (1, 1),
    'EMP_PUBL_SEX_OC2_NB_A': (1, 1),
    'EMP_PUBL_SEX_OCU_NB_A': (1, 1),
    'EMP_PUBL_SEX_STE_NB_A': (1, 1),
    'EMP_TEM1_SEX_AGE_NB_M': (1, 1),
    'EMP_TEM1_SEX_AGE_NB_Q': (1, 1),
    'EMP_TEM1_SEX_ECO_NB_M': (1, 1),
    'EMP_TEM1_SEX_ECO_NB_Q': (1, 1),
    'EMP_TEMP_AGE_EC2_NB_A': (0, 2),
    'EMP_TEMP_AGE_OC2_NB_A': (0, 2),
    'EMP_TEMP_AGE_STE_NB_A': (0, 2),
    'EMP_TEMP_ECO_OCU_NB_A': (0, 2),
    'EMP_TEMP_ECO_OCU_NB_Q': (0, 2),
    'EMP_TEMP_SEX_AGE_CBR_NB_A': (1, 2),
    'EMP_TEMP_SEX_AGE_CCT_NB_A': (1, 2),
    'EMP_TEMP_SEX_AGE_DSB_NB_A': (1, 2),
    'EMP_TEMP_SEX_AGE_DSB_NB_Q': (1, 2),
    'EMP_TEMP_SEX_AGE_ECO_NB_A': (1, 2),
    'EMP_TEMP_SEX_AGE_ECO_NB_Q': (1, 2),
    'EMP_TEMP_SEX_AGE_EDU_NB_A': (1, 2),
    'EMP_TEMP_SEX_AGE_EDU_NB_M': (1, 2),
    'EMP_TEMP_SEX_AGE_EDU_NB_Q': (1, 2),
    'EMP_TEMP_SEX_AGE_GEO_NB_A': (1, 2),
    'EMP_TEMP_SEX_AGE_GEO_NB_M': (1, 2),
    'EMP_TEMP_SEX_AGE_GEO_NB_Q': (1, 2),
    'EMP_TEMP_SEX_AGE_INS_NB_A': (1, 2),
    'EMP_TEMP_SEX_AGE_INS_NB_Q': (1, 2),
    'EMP_TEMP_SEX_AGE_JBT_NB_A': (1, 2),
    'EMP_TEMP_SEX_AGE_JBT_NB_M': (1, 2),
    'EMP_TEMP_SEX_AGE_JBT_NB_Q': (1, 2),
    'EMP_TEMP_SEX_AGE_MTS_NB_A': (1, 2),
    'EMP_TEMP_SEX_AGE_MTS_NB_Q': (1, 2),
    'EMP_TEMP_SEX_AGE_NB_A': (1, 1),
    'EMP_TEMP_SEX_AGE_NB_M': (1, 1),
    'EMP_TEMP_SEX_AGE_NB_Q': (1, 1),
    'EMP_TEMP_SEX_AGE_OCU_NB_A': (1, 2),
    'EMP_TEMP_SEX_AGE_OCU_NB_Q': (1, 2),
    'EMP_TEMP_SEX_AGE_STE_NB_A': (1, 2),
    'EMP_TEMP_SEX_AGE_STE_NB_Q': (1, 2),
    'EMP_TEMP_SEX_CAR_NB_A': (1, 1),
    'EMP_TEMP_SEX_DSB_NB_A': (1, 1),
    'EMP_TEMP_SEX_DSB_NB_Q': (1, 1),
    'EMP_TEMP_SEX_EC2_NB_A': (1, 1),
    'EMP_TEMP_SEX_ECO_CBR_NB_A': (1, 2),
    'EMP_TEMP_SEX_ECO_CCT_NB_A': (1, 2),
    'EMP_TEMP_SEX_ECO_DSB_NB_A': (1, 2),
    'EMP_TEMP_SEX_ECO_EDU_NB_A': (1, 2),
    'EMP_TEMP_SEX_ECO_EDU_NB_Q': (1, 2),
    'EMP_TEMP_SEX_ECO_EST_NB_A': (1, 2),
    'EMP_TEMP_SEX_ECO_EST_NB_Q': (1, 2),
    'EMP_TEMP_SEX_ECO_GEO_NB_A': (1, 2),
    'EMP_TEMP_SEX_ECO_INS_NB_A': (1, 2),
    'EMP_TEMP_SEX_ECO_INS_NB_M': (1, 2),
    'EMP_TEMP_SEX_ECO_INS_NB_Q': (1, 2),
    'EMP_TEMP_SEX_ECO_MJH_NB_A': (1, 2),
    'EMP_TEMP_SEX_ECO_MJH_NB_Q': (1, 2),
    'EMP_TEMP_SEX_ECO_MTS_NB_A': (1, 2),
    'EMP_TEMP_SEX_ECO_MTS_NB_Q': (1, 2),
    'EMP_TEMP_SEX_ECO_NB_A': (1, 1),
    'EMP_TEMP_SEX_ECO_NB_M': (1, 1),
    'EMP_TEMP_SEX_ECO_NB_Q': (1, 1),
    'EMP_TEMP_SEX_EDU_CBR_NB_A': (1, 2),
    'EMP_TEMP_SEX_EDU_CCT_NB_A': (1, 2),
    'EMP_TEMP_SEX_EDU_DSB_NB_A': (1, 2),
    'EMP_TEMP_SEX_EDU_EC2_NB_A': (1, 2),
    'EMP_TEMP_SEX_EDU_GEO_NB_A': (1, 2),
    'EMP_TEMP_SEX_EDU_GEO_NB_Q': (1, 2),
    'EMP_TEMP_SEX_EDU_MTS_NB_A': (1, 2),
    'EMP_TEMP_SEX_EDU_MTS_NB_Q': (1, 2),
    'EMP_TEMP_SEX_EDU_NB_A': (1, 1),
    'EMP_TEMP_SEX_EDU_NB_M': (1, 1),
    'EMP_TEMP_SEX_EDU_NB_Q': (1, 1),
    'EMP_TEMP_SEX_EST_DSB_NB_A': (1, 2),
    'EMP_TEMP_SEX_EST_EC2_NB_A': (1, 2),
    'EMP_TEMP_SEX_EST_GEO_NB_A': (1, 2),
    'EMP_TEMP_SEX_EST_GEO_NB_Q': (1, 2),
    'EMP_TEMP_SEX_EST_MTS_NB_A': (1, 2),
    'EMP_TEMP_SEX_EST_MTS_NB_Q': (1, 2),
    'EMP_TEMP_SEX_EST_NB_A': (1, 1),
    'EMP_TEMP_SEX_EST_NB_Q': (1, 1),
    'EMP_TEMP_SEX_GAI_NB_A': (1, 1),
    'EMP_TEMP_SEX_GAI_NB_Q': (1, 1),
    'EMP_TEMP_SEX_GEO_DSB_NB_A': (1, 2),
    'EMP_TEMP_SEX_GEO_MTS_NB_A': (1, 2),
    'EMP_TEMP_SEX_GEO_MTS_NB_Q': (1, 2),
    'EMP_TEMP_SEX_GEO_NB_A': (1, 1),
    'EMP_TEMP_SEX_GEO_NB_Q': (1, 1),
    'EMP_TEMP_SEX_HOW_DSB_NB_A': (1, 2),
    'EMP_TEMP_SEX_HOW_DSB_NB_Q': (1, 2),
    'EMP_TEMP_SEX_HOW_EDU_NB_A': (1, 2),
    'EMP_TEMP_SEX_HOW_EDU_NB_Q': (1, 2),
    'EMP_TEMP_SEX_HOW_GEO_NB_A': (1, 2),
    'EMP_TEMP_SEX_HOW_GEO_NB_Q': (1, 2),
    'EMP_TEMP_SEX_HOW_MTS_NB_A': (1, 2),
    'EMP_TEMP_SEX_HOW_MTS_NB_Q': (1, 2),
    'EMP_TEMP_SEX_HOW_NB_A': (1, 1),
    'EMP_TEMP_SEX_HOW_NB_Q': (1, 1),
    'EMP_TEMP_SEX_IFL_ECO_NB_A': (1, 2),
    'EMP_TEMP_SEX_IFL_JBT_NB_A': (1, 2),
    'EMP_TEMP_SEX_IFL_OCU_NB_A': (1, 2),
    'EMP_TEMP_SEX_IND_CBR_NB_A': (1, 2),
    'EMP_TEMP_SEX_IND_CCT_NB_A': (1, 2),
    'EMP_TEMP_SEX_IND_DSB_NB_A': (1, 2),
    'EMP_TEMP_SEX_IND_EDU_NB_A': (1, 2),
    'EMP_TEMP_SEX_IND_EST_NB_A': (1, 2),
    'EMP_TEMP_SEX_IND_GEO_NB_A': (1, 2),
    'EMP_TEMP_SEX_IND_INS_NB_A': (1, 2),
    'EMP_TEMP_SEX_IND_NB_A': (1, 1),
    'EMP_TEMP_SEX_IND_OCU_NB_A': (1, 2),
    'EMP_TEMP_SEX_IND_STE_NB_A': (1, 2),
    'EMP_TEMP_SEX_INS_DSB_NB_A': (1, 2),
    'EMP_TEMP_SEX_INS_DSB_NB_Q': (1, 2),
    'EMP_TEMP_SEX_INS_GEO_NB_A': (1, 2),
    'EMP_TEMP_SEX_INS_GEO_NB_Q': (1, 2),
    'EMP_TEMP_SEX_INS_MTS_NB_A': (1, 2),
    'EMP_TEMP_SEX_INS_MTS_NB_Q': (1, 2),
    'EMP_TEMP_SEX_INS_NB_A': (1, 1),
    'EMP_TEMP_SEX_INS_NB_Q': (1, 1),
    'EMP_TEMP_SEX_MJH_DSB_NB_A': (1, 2),
    'EMP_TEMP_SEX_MJH_DSB_NB_Q': (1, 2),
    'EMP_TEMP_SEX_MJH_EDU_NB_A': (1, 2),
    'EMP_TEMP_SEX_MJH_EDU_NB_Q': (1, 2),
    'EMP_TEMP_SEX_MJH_GEO_NB_A': (1, 2),
    'EMP_TEMP_SEX_MJH_GEO_NB_Q': (1, 2),
    'EMP_TEMP_SEX_MJH_MTS_NB_A': (1, 2),
    'EMP_TEMP_SEX_MJH_MTS_NB_Q': (1, 2),
    'EMP_TEMP_SEX_MJH_NB_A': (1, 1),
    'EMP_TEMP_SEX_MJH_NB_Q': (1, 1),
    'EMP_TEMP_SEX_MTS_DSB_NB_A': (1, 2),
    'EMP_TEMP_SEX_MTS_DSB_NB_Q': (1, 2),
    'EMP_TEMP_SEX_MTS_NB_A': (1, 1),
    'EMP_TEMP_SEX_MTS_NB_M': (1, 1),
    'EMP_TEMP_SEX_MTS_NB_Q': (1, 1),
    'EMP_TEMP_SEX_OC2_NB_A': (1, 1),
    'EMP_TEMP_SEX_OCU_CBR_NB_A': (1, 2),
    'EMP_TEMP_SEX_OCU_CCT_NB_A': (1, 2),
    'EMP_TEMP_SEX_OCU_DSB_NB_A': (1, 2),
    'EMP_TEMP_SEX_OCU_EC2_NB_A': (1, 2),
    'EMP_TEMP_SEX_OCU_EDU_NB_A': (1, 2),
    'EMP_TEMP_SEX_OCU_EDU_NB_Q': (1, 2),
    'EMP_TEMP_SEX_OCU_EST_NB_A': (1, 2),
    'EMP_TEMP_SEX_OCU_EST_NB_Q': (1, 2),
    'EMP_TEMP_SEX_OCU_GEO_NB_A': (1, 2),
    'EMP_TEMP_SEX_OCU_INS_NB_A': (1, 2),
    'EMP_TEMP_SEX_OCU_INS_NB_Q': (1, 2),
    'EMP_TEMP_SEX_OCU_MJH_NB_A': (1, 2),
    'EMP_TEMP_SEX_OCU_MJH_NB_Q': (1, 2),
    'EMP_TEMP_SEX_OCU_MTS_NB_A': (1, 2),
    'EMP_TEMP_SEX_OCU_MTS_NB_Q': (1, 2),
    'EMP_TEMP_SEX_OCU_NB_A': (1, 1),
    'EMP_TEMP_SEX_OCU_NB_M': (1, 1),
    'EMP_TEMP_SEX_OCU_NB_Q': (1, 1),
    'EMP_TEMP_SEX_SKN_CBR_NB_A': (1, 2),
    'EMP_TEMP_SEX_SKN_CCT_NB_A': (1, 2),
    'EMP_TEMP_SEX_SKN_DSB_NB_A': (1, 2),
    'EMP_TEMP_SEX_SKN_ECO_NB_A': (1, 2),
    'EMP_TEMP_SEX_SKN_EDU_NB_A': (1, 2),
    'EMP_TEMP_SEX_SKN_GEO_NB_A': (1, 2),
    'EMP_TEMP_SEX_SKN_IFL_NB_A': (1, 2),
    'EMP_TEMP_SEX_SKN_MTS_NB_A': (1, 2),
    'EMP_TEMP_SEX_SKN_STE_NB_A': (1, 2),
    'EMP_TEMP_SEX_SKS_CBR_NB_A': (1, 2),
    'EMP_TEMP_SEX_SKS_CCT_NB_A': (1, 2),
    'EMP_TEMP_SEX_SKS_ECO_NB_A': (1, 2),
    'EMP_TEMP_SEX_SKS_GEO_NB_A': (1, 2),
    'EMP_TEMP_SEX_SKS_IFL_NB_A': (1, 2),
    'EMP_TEMP_SEX_SKS_MTS_NB_A': (1, 2),
    'EMP_TEMP_SEX_SKS_STE_NB_A': (1, 2),
    'EMP_TEMP_SEX_STE_CBR_NB_A': (1, 2),
    'EMP_TEMP_SEX_STE_CCT_NB_A': (1, 2),
    'EMP_TEMP_SEX_STE_DSB_NB_A': (1, 2),
    'EMP_TEMP_SEX_STE_EC2_NB_A': (1, 2),
    'EMP_TEMP_SEX_STE_ECO_NB_A': (1, 2),
    'EMP_TEMP_SEX_STE_ECO_NB_Q': (1, 2),
    'EMP_TEMP_SEX_STE_EDU_NB_A': (1, 2),
    'EMP_TEMP_SEX_STE_EST_NB_A': (1, 2),
    'EMP_TEMP_SEX_STE_EST_NB_Q': (1, 2),
    'EMP_TEMP_SEX_STE_GEO_NB_A': (1, 2),
    'EMP_TEMP_SEX_STE_INS_NB_A': (1, 2),
    'EMP_TEMP_SEX_STE_INS_NB_Q': (1, 2),
    'EMP_TEMP_SEX_STE_MJH_NB_A': (1, 2),
    'EMP_TEMP_SEX_STE_MTS_NB_A': (1, 2),
    'EMP_TEMP_SEX_STE_MTS_NB_Q': (1, 2),
    'EMP_TEMP_SEX_STE_NB_A': (1, 1),
    'EMP_TEMP_SEX_STE_NB_M': (1, 1),
    'EMP_TEMP_SEX_STE_NB_Q': (1, 1),
    'EMP_TEMP_SEX_STE_OCU_NB_A': (1, 2),
    'EMP_TEMP_SEX_STE_OCU_NB_Q': (1, 2),
    'EMP_XFRB_SEX_CBR_NB_A': (1, 1),
    'EMP_XPSE_GOV_NB_A': (0, 1),
    'EMP_XTRU_SEX_AGE_EDU_NB_A': (1, 2),
    'EMP_XTRU_SEX_AGE_EDU_NB_Q': (1, 2),
    'EMP_XTRU_SEX_AGE_EDU_RT_A': (1, 2),
    'EMP_XTRU_SEX_AGE_EDU_RT_Q': (1, 2),
    'EMP_XTRU_SEX_AGE_GEO_NB_A': (1, 2),
    'EMP_XTRU_SEX_AGE_GEO_RT_A': (1, 2),
    'EMP_XTRU_SEX_AGE_MTS_NB_A': (1, 2),
    'EMP_XTRU_SEX_AGE_MTS_NB_Q': (1, 2),
    'EMP_XTRU_SEX_AGE_MTS_RT_A': (1, 2),
    'EMP_XTRU_SEX_AGE_MTS_RT_Q': (1, 2),
    'EMP_XTRU_SEX_AGE_NB_A': (1, 1),
    'EMP_XTRU_SEX_AGE_NB_M': (1, 1),
    'EMP_XTRU_SEX_AGE_NB_Q': (1, 1),
    'EMP_XTRU_SEX_AGE_RT_A': (1, 1),
    'EMP_XTRU_SEX_AGE_RT_M': (1, 1),
    'EMP_XTRU_SEX_AGE_RT_Q': (1, 1),
    'EMP_XTRU_SEX_DSB_NB_A': (1, 1),
    'EMP_XTRU_SEX_DSB_RT_A': (1, 1),
    'EMP_XTRU_SEX_EDU_GEO_NB_A': (1, 2),
    'EMP_XTRU_SEX_EDU_GEO_RT_A': (1, 2),
    'EMP_XTRU_SEX_EDU_MTS_NB_A': (1, 2),
    'EMP_XTRU_SEX_EDU_MTS_NB_Q': (1, 2),
    'EMP_XTRU_SEX_EDU_MTS_RT_A': (1, 2),
    'EMP_XTRU_SEX_EDU_MTS_RT_Q': (1, 2),
    'EMP_XTRU_SEX_EDU_NB_A': (1, 1),
    'EMP_XTRU_SEX_EDU_NB_Q': (1, 1),
    'EMP_XTRU_SEX_EDU_RT_A': (1, 1),
    'EMP_XTRU_SEX_EDU_RT_Q': (1, 1),
    'EMP_XTRU_SEX_GEO_MTS_NB_A': (1, 2),
    'EMP_XTRU_SEX_GEO_MTS_RT_A': (1, 2),
    'EMP_XTRU_SEX_GEO_NB_A': (1, 1),
    'EMP_XTRU_SEX_GEO_RT_A': (1, 1),
    'EMP_XTRU_SEX_MTS_NB_A': (1, 1),
    'EMP_XTRU_SEX_MTS_NB_Q': (1, 1),
    'EMP_XTRU_SEX_MTS_RT_A': (1, 1),
    'EMP_XTRU_SEX_MTS_RT_Q': (1, 1),
    'EMP_XTRU_SEX_NB_A': (1, 0),
    'EMP_XTRU_SEX_NB_Q': (1, 0),
    'EMP_XTRU_SEX_RT_A': (1, 0),
    'EMP_XTRU_SEX_RT_Q': (1, 0),
    'GDP_205U_NOC_NB_A': (1, 2),
    'GDP_211P_NOC_NB_A': (1, 2),
    'GDP_2HRW_NOC_NB_A': (1, 2),
    'GDP_2TOT_NOC_NB_A': (1, 2),
    'GED_2LFP_SEX_HHT_NB_A': (1, 1),
    'GED_2LFP_SEX_HHT_RT_A': (1, 1),
    'GED_PEAR_SEX_HHT_CHL_NB_A': (1, 2),
    'GED_PEAR_SEX_HHT_GEO_NB_A': (1, 2),
    'GED_PEPR_SEX_HHT_CHL_RT_A': (1, 2),
    'GED_PEPR_SEX_HHT_GEO_RT_A': (1, 2),
    'GED_PHOW_SEX_HHT_CHL_NB_A': (1, 2),
    'GED_PHOW_SEX_HHT_GEO_NB_A': (1, 2),
    'GED_PLFP_SEX_HHT_CHL_RT_A': (1, 2),
    'GED_PLFP_SEX_HHT_GEO_RT_A': (1, 2),
    'GED_PLFP_SEX_HHT_RT_A': (1, 1),
    'GED_TWAP_HHT_NB_A': (0, 1),
    'GED_XLU1_SEX_HHT_CHL_RT_A': (1, 2),
    'GED_XLU1_SEX_HHT_GEO_RT_A': (1, 2),
    'GED_XLU2_SEX_HHT_CHL_RT_A': (1, 2),
    'GED_XLU2_SEX_HHT_GEO_RT_A': (1, 2),
    'GED_XLU3_SEX_HHT_CHL_RT_A': (1, 2),
    'GED_XLU3_SEX_HHT_GEO_RT_A': (1, 2),
    'GED_XLU4_SEX_HHT_CHL_RT_A': (1, 2),
    'GED_XLU4_SEX_HHT_GEO_RT_A': (1, 2),
    'HOW_2EMP_SEX_NB_A': (1, 0),
    'HOW_2TDP_SEX_RT_A': (1, 0),
    'HOW_2TOT_SEX_NB_A': (1, 0),
    'HOW_CARE_SEX_NB_A': (1, 0),
    'HOW_EARE_SEX_NB_A': (1, 0),
    'HOW_PUBE_SEX_NB_A': (1, 0),
    'HOW_PUBL_SEX_NB_A': (1, 0),
    'HOW_STEE_SEX_NB_A': (1, 0),
    'HOW_STEM_SEX_NB_A': (1, 0),
    'HOW_TEMP_AGE_EC2_NB_A': (0, 2),
    'HOW_TEMP_AGE_OC2_NB_A': (0, 2),
    'HOW_TEMP_ECO_OCU_NB_A': (0, 2),
    'HOW_TEMP_ECO_OCU_NB_Q': (0, 2),
    'HOW_TEMP_SEX_AGE_ECO_NB_A': (1, 2),
    'HOW_TEMP_SEX_AGE_ECO_NB_Q': (1, 2),
    'HOW_TEMP_SEX_AGE_INS_NB_A': (1, 2),
    'HOW_TEMP_SEX_AGE_INS_NB_Q': (1, 2),
    'HOW_TEMP_SEX_AGE_JBT_NB_A': (1, 2),
    'HOW_TEMP_SEX_AGE_JBT_NB_M': (1, 2),
    'HOW_TEMP_SEX_AGE_JBT_NB_Q': (1, 2),
    'HOW_TEMP_SEX_AGE_NB_A': (1, 1),
    'HOW_TEMP_SEX_AGE_NB_M': (1, 1),
    'HOW_TEMP_SEX_AGE_NB_Q': (1, 1),
    'HOW_TEMP_SEX_AGE_OCU_NB_A': (1, 2),
    'HOW_TEMP_SEX_AGE_OCU_NB_Q': (1, 2),
    'HOW_TEMP_SEX_EC2_NB_A': (1, 1),
    'HOW_TEMP_SEX_ECO_DSB_NB_A': (1, 2),
    'HOW_TEMP_SEX_ECO_EDU_NB_A': (1, 2),
    'HOW_TEMP_SEX_ECO_EDU_NB_Q': (1, 2),
    'HOW_TEMP_SEX_ECO_EST_NB_A': (1, 2),
    'HOW_TEMP_SEX_ECO_EST_NB_Q': (1, 2),
    'HOW_TEMP_SEX_ECO_GEO_NB_A': (1, 2),
    'HOW_TEMP_SEX_ECO_INS_NB_A': (1, 2),
    'HOW_TEMP_SEX_ECO_INS_NB_M': (1, 2),
    'HOW_TEMP_SEX_ECO_INS_NB_Q': (1, 2),
    'HOW_TEMP_SEX_ECO_MTS_NB_A': (1, 2),
    'HOW_TEMP_SEX_ECO_MTS_NB_Q': (1, 2),
    'HOW_TEMP_SEX_ECO_NB_A': (1, 1),
    'HOW_TEMP_SEX_ECO_NB_M': (1, 1),
    'HOW_TEMP_SEX_ECO_NB_Q': (1, 1),
    'HOW_TEMP_SEX_EST_DSB_NB_A': (1, 2),
    'HOW_TEMP_SEX_EST_DSB_NB_Q': (1, 2),
    'HOW_TEMP_SEX_EST_GEO_NB_A': (1, 2),
    'HOW_TEMP_SEX_EST_GEO_NB_Q': (1, 2),
    'HOW_TEMP_SEX_EST_MTS_NB_A': (1, 2),
    'HOW_TEMP_SEX_EST_MTS_NB_Q': (1, 2),
    'HOW_TEMP_SEX_EST_NB_A': (1, 1),
    'HOW_TEMP_SEX_EST_NB_M': (1, 1),
    'HOW_TEMP_SEX_EST_NB_Q': (1, 1),
    'HOW_TEMP_SEX_IND_NB_A': (1, 1),
    'HOW_TEMP_SEX_INS_DSB_NB_A': (1, 2),
    'HOW_TEMP_SEX_INS_DSB_NB_Q': (1, 2),
    'HOW_TEMP_SEX_INS_GEO_NB_A': (1, 2),
    'HOW_TEMP_SEX_INS_GEO_NB_Q': (1, 2),
    'HOW_TEMP_SEX_INS_MTS_NB_A': (1, 2),
    'HOW_TEMP_SEX_INS_MTS_NB_Q': (1, 2),
    'HOW_TEMP_SEX_INS_NB_A': (1, 1),
    'HOW_TEMP_SEX_INS_NB_Q': (1, 1),
    'HOW_TEMP_SEX_NB_A': (1, 0),
    'HOW_TEMP_SEX_NB_M': (1, 0),
    'HOW_TEMP_SEX_NB_Q': (1, 0),
    'HOW_TEMP_SEX_OC2_NB_A': (1, 1),
    'HOW_TEMP_SEX_OCU_DSB_NB_A': (1, 2),
    'HOW_TEMP_SEX_OCU_EDU_NB_A': (1, 2),
    'HOW_TEMP_SEX_OCU_EDU_NB_Q': (1, 2),
    'HOW_TEMP_SEX_OCU_EST_NB_A': (1, 2),
    'HOW_TEMP_SEX_OCU_EST_NB_Q': (1, 2),
    'HOW_TEMP_SEX_OCU_GEO_NB_A': (1, 2),
    'HOW_TEMP_SEX_OCU_INS_NB_A': (1, 2),
    'HOW_TEMP_SEX_OCU_INS_NB_Q': (1, 2),
    'HOW_TEMP_SEX_OCU_MTS_NB_A': (1, 2),
    'HOW_TEMP_SEX_OCU_MTS_NB_Q': (1, 2),
    'HOW_TEMP_SEX_OCU_NB_A': (1, 1),
    'HOW_TEMP_SEX_OCU_NB_M': (1, 1),
    'HOW_TEMP_SEX_OCU_NB_Q': (1, 1),
    'HOW_UEES_SEX_NB_A': (1, 0),
    'HOW_UEMP_SEX_NB_A': (1, 0),
    'HOW_XEES_AGE_EC2_NB_A': (0, 2),
    'HOW_XEES_AGE_OC2_NB_A': (0, 2),
    'HOW_XEES_ECO_OCU_NB_A': (0, 2),
    'HOW_XEES_ECO_OCU_NB_Q': (0, 2),
    'HOW_XEES_SEX_AGE_ECO_NB_A': (1, 2),
    'HOW_XEES_SEX_AGE_ECO_NB_Q': (1, 2),
    'HOW_XEES_SEX_AGE_INS_NB_A': (1, 2),
    'HOW_XEES_SEX_AGE_INS_NB_Q': (1, 2),
    'HOW_XEES_SEX_AGE_JBC_NB_A': (1, 2),
    'HOW_XEES_SEX_AGE_JBC_NB_M': (1, 2),
    'HOW_XEES_SEX_AGE_JBC_NB_Q': (1, 2),
    'HOW_XEES_SEX_AGE_NB_A': (1, 1),
    'HOW_XEES_SEX_AGE_NB_M': (1, 1),
    'HOW_XEES_SEX_AGE_NB_Q': (1, 1),
    'HOW_XEES_SEX_AGE_OCU_NB_A': (1, 2),
    'HOW_XEES_SEX_AGE_OCU_NB_Q': (1, 2),
    'HOW_XEES_SEX_CBR_NB_A': (1, 1),
    'HOW_XEES_SEX_CCT_NB_A': (1, 1),
    'HOW_XEES_SEX_DSB_NB_A': (1, 1),
    'HOW_XEES_SEX_DSB_NB_Q': (1, 1),
    'HOW_XEES_SEX_EC2_NB_A': (1, 1),
    'HOW_XEES_SEX_ECO_DSB_NB_A': (1, 2),
    'HOW_XEES_SEX_ECO_EDU_NB_A': (1, 2),
    'HOW_XEES_SEX_ECO_EDU_NB_Q': (1, 2),
    'HOW_XEES_SEX_ECO_EST_NB_A': (1, 2),
    'HOW_XEES_SEX_ECO_EST_NB_Q': (1, 2),
    'HOW_XEES_SEX_ECO_GEO_NB_A': (1, 2),
    'HOW_XEES_SEX_ECO_INS_NB_A': (1, 2),
    'HOW_XEES_SEX_ECO_INS_NB_M': (1, 2),
    'HOW_XEES_SEX_ECO_INS_NB_Q': (1, 2),
    'HOW_XEES_SEX_ECO_MTS_NB_A': (1, 2),
    'HOW_XEES_SEX_ECO_MTS_NB_Q': (1, 2),
    'HOW_XEES_SEX_ECO_NB_A': (1, 1),
    'HOW_XEES_SEX_ECO_NB_M': (1, 1),
    'HOW_XEES_SEX_ECO_NB_Q': (1, 1),
    'HOW_XEES_SEX_EDU_NB_A': (1, 1),
    'HOW_XEES_SEX_EDU_NB_Q': (1, 1),
    'HOW_XEES_SEX_EST_DSB_NB_A': (1, 2),
    'HOW_XEES_SEX_EST_DSB_NB_Q': (1, 2),
    'HOW_XEES_SEX_EST_GEO_NB_A': (1, 2),
    'HOW_XEES_SEX_EST_GEO_NB_Q': (1, 2),
    'HOW_XEES_SEX_EST_MTS_NB_A': (1, 2),
    'HOW_XEES_SEX_EST_MTS_NB_Q': (1, 2),
    'HOW_XEES_SEX_EST_NB_A': (1, 1),
    'HOW_XEES_SEX_EST_NB_M': (1, 1),
    'HOW_XEES_SEX_EST_NB_Q': (1, 1),
    'HOW_XEES_SEX_GEO_NB_A': (1, 1),
    'HOW_XEES_SEX_GEO_NB_Q': (1, 1),
    'HOW_XEES_SEX_INS_DSB_NB_A': (1, 2),
    'HOW_XEES_SEX_INS_DSB_NB_Q': (1, 2),
    'HOW_XEES_SEX_INS_GEO_NB_A': (1, 2),
    'HOW_XEES_SEX_INS_GEO_NB_Q': (1, 2),
    'HOW_XEES_SEX_INS_MTS_NB_A': (1, 2),
    'HOW_XEES_SEX_INS_MTS_NB_Q': (1, 2),
    'HOW_XEES_SEX_INS_NB_A': (1, 1),
    'HOW_XEES_SEX_INS_NB_Q': (1, 1),
    'HOW_XEES_SEX_MTS_NB_A': (1, 1),
    'HOW_XEES_SEX_MTS_NB_Q': (1, 1),
    'HOW_XEES_SEX_NB_A': (1, 0),
    'HOW_XEES_SEX_NB_M': (1, 0),
    'HOW_XEES_SEX_NB_Q': (1, 0),
    'HOW_XEES_SEX_OC2_NB_A': (1, 1),
    'HOW_XEES_SEX_OCU_DSB_NB_A': (1, 2),
    'HOW_XEES_SEX_OCU_EDU_NB_A': (1, 2),
    'HOW_XEES_SEX_OCU_EDU_NB_Q': (1, 2),
    'HOW_XEES_SEX_OCU_EST_NB_A': (1, 2),
    'HOW_XEES_SEX_OCU_EST_NB_Q': (1, 2),
    'HOW_XEES_SEX_OCU_GEO_NB_A': (1, 2),
    'HOW_XEES_SEX_OCU_INS_NB_A': (1, 2),
    'HOW_XEES_SEX_OCU_INS_NB_Q': (1, 2),
    'HOW_XEES_SEX_OCU_MTS_NB_A': (1, 2),
    'HOW_XEES_SEX_OCU_MTS_NB_Q': (1, 2),
    'HOW_XEES_SEX_OCU_NB_A': (1, 1),
    'HOW_XEES_SEX_OCU_NB_M': (1, 1),
    'HOW_XEES_SEX_OCU_NB_Q': (1, 1),
    'INJ_DAYS_ECO_NB_A': (0, 1),
    'INJ_DAYS_SEX_MIG_NB_A': (1, 1),
    'INJ_FATL_ECO_NB_A': (0, 1),
    'INJ_FATL_ECO_RT_A': (0, 1),
    'INJ_FATL_SEX_MIG_NB_A': (1, 1),
    'INJ_FATL_SEX_MIG_RT_A': (1, 1),
    'INJ_NFTL_ECO_NB_A': (0, 1),
    'INJ_NFTL_ECO_RT_A': (0, 1),
    'INJ_NFTL_INJ_ECO_NB_A': (0, 2),
    'INJ_NFTL_SEX_INJ_MIG_NB_A': (1, 2),
    'INJ_NFTL_SEX_MIG_NB_A': (1, 1),
    'INJ_NFTL_SEX_MIG_RT_A': (1, 1),
    'INJ_WORK_ECO_NB_A': (0, 1),
    'INJ_WORK_SEX_MIG_NB_A': (1, 1),
    'LAC_XEES_CUR_NB_A': (0, 1),
    'LAC_XEES_ECO_CUR_NB_A': (0, 2),
    'LAC_XEES_ECO_NB_A': (0, 1),
    'LAC_XEES_NOC_NB_A': (1, 2),
    'LAI_VIST_NOC_NB_A': (1, 2),
    'LAI_WOPL_NOC_NB_A': (1, 2),
    'LAP_2FTM_NOC_RT_A': (1, 2),
    'LAP_2GDP_NOC_RT_A': (1, 2),
    'LAP_2LID_QTL_RT_A': (0, 1),
    'LUU_2LU2_SEX_AGE_RT_A': (1, 1),
    'LUU_2LU2_SEX_RT_A': (1, 0),
    'LUU_2LU3_SEX_RT_A': (1, 0),
    'LUU_2LU4_SEX_NB_A': (1, 0),
    'LUU_2LU4_SEX_RT_A': (1, 0),
    'LUU_2LUX_SEX_NB_A': (1, 0),
    'LUU_2LUX_SEX_RT_A': (1, 0),
    'LUU_5LU2_SEX_AGE_RT_A': (1, 1),
    'LUU_5LU2_SEX_AGE_RT_Q': (1, 1),
    'LUU_5LU3_SEX_AGE_RT_A': (1, 1),
    'LUU_5LU3_SEX_AGE_RT_Q': (1, 1),
    'LUU_5LU4_SEX_AGE_RT_A': (1, 1),
    'LUU_5LU4_SEX_AGE_RT_Q': (1, 1),
    'LUU_XLU2_SEX_AGE_EDU_RT_A': (1, 2),
    'LUU_XLU2_SEX_AGE_EDU_RT_Q': (1, 2),
    'LUU_XLU2_SEX_AGE_GEO_RT_A': (1, 2),
    'LUU_XLU2_SEX_AGE_MTS_RT_A': (1, 2),
    'LUU_XLU2_SEX_AGE_MTS_RT_Q': (1, 2),
    'LUU_XLU2_SEX_AGE_RT_A': (1, 1),
    'LUU_XLU2_SEX_AGE_RT_M': (1, 1),
    'LUU_XLU2_SEX_AGE_RT_Q': (1, 1),
    'LUU_XLU2_SEX_DSB_RT_A': (1, 1),
    'LUU_XLU2_SEX_EDU_GEO_RT_A': (1, 2),
    'LUU_XLU2_SEX_EDU_MTS_RT_A': (1, 2),
    'LUU_XLU2_SEX_EDU_MTS_RT_Q': (1, 2),
    'LUU_XLU2_SEX_EDU_RT_A': (1, 1),
    'LUU_XLU2_SEX_EDU_RT_Q': (1, 1),
    'LUU_XLU2_SEX_GEO_MTS_RT_A': (1, 2),
    'LUU_XLU2_SEX_GEO_RT_A': (1, 1),
    'LUU_XLU2_SEX_MTS_RT_A': (1, 1),
    'LUU_XLU2_SEX_MTS_RT_Q': (1, 1),
    'LUU_XLU3_SEX_AGE_EDU_RT_A': (1, 2),
    'LUU_XLU3_SEX_AGE_EDU_RT_Q': (1, 2),
    'LUU_XLU3_SEX_AGE_GEO_RT_A': (1, 2),
    'LUU_XLU3_SEX_AGE_GEO_RT_Q': (1, 2),
    'LUU_XLU3_SEX_AGE_MTS_RT_A': (1, 2),
    'LUU_XLU3_SEX_AGE_MTS_RT_Q': (1, 2),
    'LUU_XLU3_SEX_AGE_RT_A': (1, 1),
    'LUU_XLU3_SEX_AGE_RT_Q': (1, 1),
    'LUU_XLU3_SEX_EDU_GEO_RT_A': (1, 2),
    'LUU_XLU3_SEX_EDU_GEO_RT_Q': (1, 2),
    'LUU_XLU3_SEX_EDU_MTS_RT_A': (1, 2),
    'LUU_XLU3_SEX_EDU_MTS_RT_Q': (1, 2),
    'LUU_XLU3_SEX_EDU_RT_A': (1, 1),
    'LUU_XLU3_SEX_EDU_RT_Q': (1, 1),
    'LUU_XLU3_SEX_GEO_MTS_RT_A': (1, 2),
    'LUU_XLU3_SEX_GEO_MTS_RT_Q': (1, 2),
    'LUU_XLU3_SEX_GEO_RT_A': (1, 1),
    'LUU_XLU3_SEX_GEO_RT_Q': (1, 1),
    'LUU_XLU3_SEX_MTS_RT_A': (1, 1),
    'LUU_XLU3_SEX_MTS_RT_Q': (1, 1),
    'LUU_XLU3_SEX_RT_A': (1, 0),
    'LUU_XLU3_SEX_RT_Q': (1, 0),
    'LUU_XLU4_SEX_AGE_EDU_RT_A': (1, 2),
    'LUU_XLU4_SEX_AGE_EDU_RT_Q': (1, 2),
    'LUU_XLU4_SEX_AGE_GEO_RT_A': (1, 2),
    'LUU_XLU4_SEX_AGE_MTS_RT_A': (1, 2),
    'LUU_XLU4_SEX_AGE_MTS_RT_Q': (1, 2),
    'LUU_XLU4_SEX_AGE_RT_A': (1, 1),
    'LUU_XLU4_SEX_AGE_RT_Q': (1, 1),
    'LUU_XLU4_SEX_EDU_GEO_RT_A': (1, 2),
    'LUU_XLU4_SEX_EDU_MTS_RT_A': (1, 2),
    'LUU_XLU4_SEX_EDU_MTS_RT_Q': (1, 2),
    'LUU_XLU4_SEX_EDU_RT_A': (1, 1),
    'LUU_XLU4_SEX_EDU_RT_Q': (1, 1),
    'LUU_XLU4_SEX_GEO_MTS_RT_A': (1, 2),
    'LUU_XLU4_SEX_GEO_RT_A': (1, 1),
    'LUU_XLU4_SEX_MTS_RT_A': (1, 1),
    'LUU_XLU4_SEX_MTS_RT_Q': (1, 1),
    'LUU_XLU4_SEX_NB_A': (1, 0),
    'LUU_XLU4_SEX_NB_M': (1, 0),
    'LUU_XLU4_SEX_NB_Q': (1, 0),
    'LUU_XLU4_SEX_RT_A': (1, 0),
    'LUU_XLU4_SEX_RT_Q': (1, 0),
    'LUU_XLUX_SEX_NB_A': (1, 0),
    'LUU_XLUX_SEX_NB_Q': (1, 0),
    'LUU_XLUX_SEX_RT_A': (1, 0),
    'LUU_XLUX_SEX_RT_Q': (1, 0),
    'POP_2LDR_NOC_RT_A': (1, 2),
    'POP_2POP_SEX_NB_A': (1, 0),
    'POP_2WAP_SEX_AGE_NB_A': (1, 1),
    'POP_3VET_SEX_AGE_NB_A': (1, 1),
    'POP_3WAP_SEX_AGE_DSB_NB_A': (1, 2),
    'POP_3WAP_SEX_AGE_EDU_NB_A': (1, 2),
    'POP_3WAP_SEX_AGE_GEO_NB_A': (1, 2),
    'POP_3WAP_SEX_AGE_LMS_NB_A': (1, 2),
    'POP_3WAP_SEX_AGE_STU_NB_A': (1, 2),
    'POP_3WAP_SEX_AGE_TRA_NB_A': (1, 2),
    'POP_3WAP_SEX_AGE_TRS_NB_A': (1, 2),
    'POP_3WAP_SEX_EDU_TRA_NB_A': (1, 2),
    'POP_3WAP_SEX_EDU_TRS_NB_A': (1, 2),
    'POP_3WAP_SEX_GEO_TRA_NB_A': (1, 2),
    'POP_3WAP_SEX_GEO_TRS_NB_A': (1, 2),
    'POP_3WBL_SEX_WBL_NB_A': (1, 1),
    'POP_3WBL_SEX_WBL_RT_A': (1, 1),
    'POP_XFLB_SEX_CBR_NB_A': (1, 1),
    'POP_XFLB_SEX_EDU_NB_A': (1, 1),
    'POP_XFLC_SEX_CCT_NB_A': (1, 1),
    'POP_XFRB_SEX_CBR_NB_A': (1, 1),
    'POP_XFRC_SEX_CCT_NB_A': (1, 1),
    'POP_XVET_SEX_AGE_NB_A': (1, 1),
    'POP_XVET_SEX_EDU_NB_A': (1, 1),
    'POP_XWAP_SEX_AGE_CBR_NB_A': (1, 2),
    'POP_XWAP_SEX_AGE_CCT_NB_A': (1, 2),
    'POP_XWAP_SEX_AGE_DSB_NB_A': (1, 2),
    'POP_XWAP_SEX_AGE_DSB_NB_Q': (1, 2),
    'POP_XWAP_SEX_AGE_EDU_NB_A': (1, 2),
    'POP_XWAP_SEX_AGE_EDU_NB_M': (1, 2),
    'POP_XWAP_SEX_AGE_EDU_NB_Q': (1, 2),
    'POP_XWAP_SEX_AGE_GEO_NB_A': (1, 2),
    'POP_XWAP_SEX_AGE_GEO_NB_M': (1, 2),
    'POP_XWAP_SEX_AGE_GEO_NB_Q': (1, 2),
    'POP_XWAP_SEX_AGE_LMS_NB_A': (1, 2),
    'POP_XWAP_SEX_AGE_LMS_NB_M': (1, 2),
    'POP_XWAP_SEX_AGE_LMS_NB_Q': (1, 2),
    'POP_XWAP_SEX_AGE_MTS_NB_A': (1, 2),
    'POP_XWAP_SEX_AGE_MTS_NB_Q': (1, 2),
    'POP_XWAP_SEX_AGE_NB_A': (1, 1),
    'POP_XWAP_SEX_AGE_NB_M': (1, 1),
    'POP_XWAP_SEX_AGE_NB_Q': (1, 1),
    'POP_XWAP_SEX_DSB_LMS_NB_A': (1, 2),
    'POP_XWAP_SEX_DSB_LMS_NB_Q': (1, 2),
    'POP_XWAP_SEX_DSB_NB_A': (1, 1),
    'POP_XWAP_SEX_DSB_NB_Q': (1, 1),
    'POP_XWAP_SEX_EDU_CBR_NB_A': (1, 2),
    'POP_XWAP_SEX_EDU_CCT_NB_A': (1, 2),
    'POP_XWAP_SEX_EDU_DSB_NB_A': (1, 2),
    'POP_XWAP_SEX_EDU_GEO_NB_A': (1, 2),
    'POP_XWAP_SEX_EDU_GEO_NB_Q': (1, 2),
    'POP_XWAP_SEX_EDU_LMS_NB_A': (1, 2),
    'POP_XWAP_SEX_EDU_LMS_NB_M': (1, 2),
    'POP_XWAP_SEX_EDU_LMS_NB_Q': (1, 2),
    'POP_XWAP_SEX_EDU_MTS_NB_A': (1, 2),
    'POP_XWAP_SEX_EDU_MTS_NB_Q': (1, 2),
    'POP_XWAP_SEX_EDU_NB_A': (1, 1),
    'POP_XWAP_SEX_EDU_NB_M': (1, 1),
    'POP_XWAP_SEX_EDU_NB_Q': (1, 1),
    'POP_XWAP_SEX_GEO_DSB_NB_A': (1, 2),
    'POP_XWAP_SEX_GEO_DSB_NB_Q': (1, 2),
    'POP_XWAP_SEX_GEO_LMS_NB_A': (1, 2),
    'POP_XWAP_SEX_GEO_LMS_NB_M': (1, 2),
    'POP_XWAP_SEX_GEO_LMS_NB_Q': (1, 2),
    'POP_XWAP_SEX_GEO_MTS_NB_A': (1, 2),
    'POP_XWAP_SEX_GEO_MTS_NB_Q': (1, 2),
    'POP_XWAP_SEX_GEO_NB_A': (1, 1),
    'POP_XWAP_SEX_GEO_NB_M': (1, 1),
    'POP_XWAP_SEX_GEO_NB_Q': (1, 1),
    'POP_XWAP_SEX_LMS_NB_A': (1, 1),
    'POP_XWAP_SEX_LMS_NB_M': (1, 1),
    'POP_XWAP_SEX_LMS_NB_Q': (1, 1),
    'POP_XWAP_SEX_MTS_DSB_NB_A': (1, 2),
    'POP_XWAP_SEX_MTS_DSB_NB_Q': (1, 2),
    'POP_XWAP_SEX_MTS_LMS_NB_A': (1, 2),
    'POP_XWAP_SEX_MTS_LMS_NB_M': (1, 2),
    'POP_XWAP_SEX_MTS_LMS_NB_Q': (1, 2),
    'POP_XWAP_SEX_MTS_NB_A': (1, 1),
    'POP_XWAP_SEX_MTS_NB_M': (1, 1),
    'POP_XWAP_SEX_MTS_NB_Q': (1, 1),
    'POP_XWBL_SEX_AGE_WBL_NB_A': (1, 2),
    'POP_XWBL_SEX_AGE_WBL_RT_A': (1, 2),
    'POP_XWBL_SEX_EDU_WBL_NB_A': (1, 2),
    'SDG_0111_SEX_AGE_RT_A': (1, 1),
    'SDG_0131_SEX_SOC_RT_A': (1, 1),
    'SDG_0552_NOC_RT_A': (1, 2),
    'SDG_0821_NOC_RT_A': (1, 2),
    'SDG_0831_SEX_ECO_RT_A': (1, 1),
    'SDG_0851_SEX_OCU_NB_A': (1, 1),
    'SDG_0852_SEX_AGE_RT_A': (1, 1),
    'SDG_0852_SEX_DSB_RT_A': (1, 1),
    'SDG_0861_SEX_RT_A': (1, 0),
    'SDG_0882_NOC_RT_A': (1, 2),
    'SDG_08B1_NOC_NB_A': (1, 2),
    'SDG_0922_NOC_RT_A': (1, 2),
    'SDG_1041_NOC_RT_A': (1, 2),
    'SDG_A871_SEX_AGE_RT_A': (1, 1),
    'SDG_B552_NOC_RT_A': (1, 2),
    'SDG_B821_NOC_RT_A': (1, 2),
    'SDG_B831_SEX_ECO_RT_A': (1, 1),
    'SDG_B852_SEX_AGE_RT_A': (1, 1),
    'SDG_B852_SEX_DSB_RT_A': (1, 1),
    'SDG_B871_SEX_AGE_RT_A': (1, 1),
    'SDG_B922_NOC_RT_A': (1, 2),
    'SDG_F881_SEX_MIG_RT_A': (1, 1),
    'SDG_N881_SEX_MIG_RT_A': (1, 1),
    'SDG_T552_NOC_RT_A': (1, 2),
    'SDG_U552_NOC_RT_A': (1, 2),
    'STR_DAYS_ECO_NB_A': (0, 1),
    'STR_DAYS_ECO_RT_A': (0, 1),
    'STR_TSTR_ECO_NB_A': (0, 1),
    'STR_WORK_ECO_NB_A': (0, 1),
    'UNE_2EAP_SEX_AGE_RT_A': (1, 1),
    'UNE_2UNE_SEX_AGE_NB_A': (1, 1),
    'UNE_3EAP_SEX_AGE_DSB_RT_A': (1, 2),
    'UNE_3EAP_SEX_AGE_EDU_RT_A': (1, 2),
    'UNE_3EAP_SEX_AGE_GEO_RT_A': (1, 2),
    'UNE_3EAP_SEX_AGE_STU_RT_A': (1, 2),
    'UNE_3UNE_SEX_AGE_CAT_NB_A': (1, 2),
    'UNE_3UNE_SEX_AGE_DSB_NB_A': (1, 2),
    'UNE_3UNE_SEX_AGE_DUR_NB_A': (1, 2),
    'UNE_3UNE_SEX_AGE_EDU_NB_A': (1, 2),
    'UNE_3UNE_SEX_AGE_GEO_NB_A': (1, 2),
    'UNE_3UNE_SEX_AGE_STU_NB_A': (1, 2),
    'UNE_3WAP_SEX_AGE_DSB_RT_A': (1, 2),
    'UNE_3WAP_SEX_AGE_EDU_RT_A': (1, 2),
    'UNE_3WAP_SEX_AGE_GEO_RT_A': (1, 2),
    'UNE_3WAP_SEX_AGE_STU_RT_A': (1, 2),
    'UNE_5EAP_SEX_AGE_RT_A': (1, 1),
    'UNE_5EAP_SEX_AGE_RT_Q': (1, 1),
    'UNE_5EAP_SEX_DSB_RT_A': (1, 1),
    'UNE_5EAP_SEX_DSB_RT_Q': (1, 1),
    'UNE_5UNE_SEX_AGE_NB_A': (1, 1),
    'UNE_5UNE_SEX_AGE_NB_Q': (1, 1),
    'UNE_DEA1_SEX_AGE_RT_M': (1, 1),
    'UNE_DEA1_SEX_AGE_RT_Q': (1, 1),
    'UNE_DEAP_SEX_AGE_CBR_RT_A': (1, 2),
    'UNE_DEAP_SEX_AGE_CCT_RT_A': (1, 2),
    'UNE_DEAP_SEX_AGE_DSB_RT_A': (1, 2),
    'UNE_DEAP_SEX_AGE_DSB_RT_Q': (1, 2),
    'UNE_DEAP_SEX_AGE_EDU_RT_A': (1, 2),
    'UNE_DEAP_SEX_AGE_EDU_RT_M': (1, 2),
    'UNE_DEAP_SEX_AGE_EDU_RT_Q': (1, 2),
    'UNE_DEAP_SEX_AGE_GEO_RT_A': (1, 2),
    'UNE_DEAP_SEX_AGE_GEO_RT_M': (1, 2),
    'UNE_DEAP_SEX_AGE_GEO_RT_Q': (1, 2),
    'UNE_DEAP_SEX_AGE_MTS_RT_A': (1, 2),
    'UNE_DEAP_SEX_AGE_MTS_RT_Q': (1, 2),
    'UNE_DEAP_SEX_AGE_RT_A': (1, 1),
    'UNE_DEAP_SEX_AGE_RT_M': (1, 1),
    'UNE_DEAP_SEX_AGE_RT_Q': (1, 1),
    'UNE_DEAP_SEX_DSB_RT_A': (1, 1),
    'UNE_DEAP_SEX_DSB_RT_Q': (1, 1),
    'UNE_DEAP_SEX_EDU_CBR_RT_A': (1, 2),
    'UNE_DEAP_SEX_EDU_CCT_RT_A': (1, 2),
    'UNE_DEAP_SEX_EDU_DSB_RT_A': (1, 2),
    'UNE_DEAP_SEX_EDU_GEO_RT_A': (1, 2),
    'UNE_DEAP_SEX_EDU_GEO_RT_Q': (1, 2),
    'UNE_DEAP_SEX_EDU_MTS_RT_A': (1, 2),
    'UNE_DEAP_SEX_EDU_MTS_RT_Q': (1, 2),
    'UNE_DEAP_SEX_EDU_RT_A': (1, 1),
    'UNE_DEAP_SEX_EDU_RT_M': (1, 1),
    'UNE_DEAP_SEX_EDU_RT_Q': (1, 1),
    'UNE_DEAP_SEX_GEO_DSB_RT_A': (1, 2),
    'UNE_DEAP_SEX_GEO_MTS_RT_A': (1, 2),
    'UNE_DEAP_SEX_GEO_MTS_RT_Q': (1, 2),
    'UNE_DEAP_SEX_GEO_RT_A': (1, 1),
    'UNE_DEAP_SEX_GEO_RT_Q': (1, 1),
    'UNE_DEAP_SEX_MTS_DSB_RT_A': (1, 2),
    'UNE_DEAP_SEX_MTS_DSB_RT_Q': (1, 2),
    'UNE_DEAP_SEX_MTS_RT_A': (1, 1),
    'UNE_DEAP_SEX_MTS_RT_M': (1, 1),
    'UNE_DEAP_SEX_MTS_RT_Q': (1, 1),
    'UNE_PUNE_SEX_ECO_EDU_NB_A': (1, 2),
    'UNE_PUNE_SEX_ECO_NB_A': (1, 1),
    'UNE_PUNE_SEX_OCU_EDU_NB_A': (1, 2),
    'UNE_PUNE_SEX_OCU_NB_A': (1, 1),
    'UNE_TUN1_SEX_AGE_DUR_NB_Q': (1, 2),
    'UNE_TUN1_SEX_AGE_NB_M': (1, 1),
    'UNE_TUN1_SEX_AGE_NB_Q': (1, 1),
    'UNE_TUNE_SEX_AGE_CBR_NB_A': (1, 2),
    'UNE_TUNE_SEX_AGE_CCT_NB_A': (1, 2),
    'UNE_TUNE_SEX_AGE_DSB_NB_A': (1, 2),
    'UNE_TUNE_SEX_AGE_DSB_NB_Q': (1, 2),
    'UNE_TUNE_SEX_AGE_DUR_NB_A': (1, 2),
    'UNE_TUNE_SEX_AGE_DUR_NB_M': (1, 2),
    'UNE_TUNE_SEX_AGE_DUR_NB_Q': (1, 2),
    'UNE_TUNE_SEX_AGE_EDU_NB_A': (1, 2),
    'UNE_TUNE_SEX_AGE_EDU_NB_M': (1, 2),
    'UNE_TUNE_SEX_AGE_EDU_NB_Q': (1, 2),
    'UNE_TUNE_SEX_AGE_GEO_NB_A': (1, 2),
    'UNE_TUNE_SEX_AGE_GEO_NB_M': (1, 2),
    'UNE_TUNE_SEX_AGE_GEO_NB_Q': (1, 2),
    'UNE_TUNE_SEX_AGE_MTS_NB_A': (1, 2),
    'UNE_TUNE_SEX_AGE_MTS_NB_Q': (1, 2),
    'UNE_TUNE_SEX_AGE_NB_A': (1, 1),
    'UNE_TUNE_SEX_AGE_NB_M': (1, 1),
    'UNE_TUNE_SEX_AGE_NB_Q': (1, 1),
    'UNE_TUNE_SEX_CAT_NB_A': (1, 1),
    'UNE_TUNE_SEX_CAT_NB_Q': (1, 1),
    'UNE_TUNE_SEX_DSB_NB_A': (1, 1),
    'UNE_TUNE_SEX_DSB_NB_Q': (1, 1),
    'UNE_TUNE_SEX_DUR_GEO_NB_A': (1, 2),
    'UNE_TUNE_SEX_DUR_MTS_NB_A': (1, 2),
    'UNE_TUNE_SEX_EDU_CBR_NB_A': (1, 2),
    'UNE_TUNE_SEX_EDU_CCT_NB_A': (1, 2),
    'UNE_TUNE_SEX_EDU_DSB_NB_A': (1, 2),
    'UNE_TUNE_SEX_EDU_GEO_NB_A': (1, 2),
    'UNE_TUNE_SEX_EDU_GEO_NB_Q': (1, 2),
    'UNE_TUNE_SEX_EDU_MTS_NB_A': (1, 2),
    'UNE_TUNE_SEX_EDU_MTS_NB_Q': (1, 2),
    'UNE_TUNE_SEX_EDU_NB_A': (1, 1),
    'UNE_TUNE_SEX_EDU_NB_M': (1, 1),
    'UNE_TUNE_SEX_EDU_NB_Q': (1, 1),
    'UNE_TUNE_SEX_GEO_DSB_NB_A': (1, 2),
    'UNE_TUNE_SEX_GEO_MTS_NB_A': (1, 2),
    'UNE_TUNE_SEX_GEO_MTS_NB_Q': (1, 2),
    'UNE_TUNE_SEX_GEO_NB_A': (1, 1),
    'UNE_TUNE_SEX_GEO_NB_Q': (1, 1),
    'UNE_TUNE_SEX_MTS_DSB_NB_A': (1, 2),
    'UNE_TUNE_SEX_MTS_DSB_NB_Q': (1, 2),
    'UNE_TUNE_SEX_MTS_NB_A': (1, 1),
    'UNE_TUNE_SEX_MTS_NB_M': (1, 1),
    'UNE_TUNE_SEX_MTS_NB_Q': (1, 1),
}


DOWNLOAD_SPECS = [
    NodeSpec(
        id=f"ilo-{eid.lower().replace('_', '-')}",
        fn=fetch_one,
        kind="download",
    )
    for eid in ENTITY_IDS
]


def _date_expr(freq: str) -> str:
    """DuckDB expression turning the period string into the period-start DATE.
    TRY_CAST so a stray malformed period yields a null date rather than failing
    the whole node."""
    if freq == "Q":  # e.g. 2025Q3
        return (
            "make_date(TRY_CAST(substr(time_period, 1, 4) AS INTEGER), "
            "(TRY_CAST(substr(time_period, 6, 1) AS INTEGER) - 1) * 3 + 1, 1)"
        )
    if freq == "M":  # e.g. 2016M04
        return (
            "make_date(TRY_CAST(substr(time_period, 1, 4) AS INTEGER), "
            "TRY_CAST(substr(time_period, 6, 2) AS INTEGER), 1)"
        )
    # Annual (and any fallback): e.g. 2011
    return "make_date(TRY_CAST(substr(time_period, 1, 4) AS INTEGER), 1, 1)"


def _transform_sql(dep_id: str, entity_id: str) -> str:
    has_sex, n_classif = ENTITY_META.get(entity_id, (1, 2))
    freq = entity_id.rsplit("_", 1)[-1]
    dims = []
    if has_sex:
        dims.append("sex")
    if n_classif >= 1:
        dims.append("classif1")
    if n_classif >= 2:
        dims.append("classif2")
    dim_lines = "".join(f"            {d},\n" for d in dims)
    return (
        "\n        SELECT\n"
        f"            {_date_expr(freq)} AS date,\n"
        "            time_period,\n"
        "            ref_area,\n"
        "            source,\n"
        f"{dim_lines}"
        "            obs_value\n"
        f'        FROM "{dep_id}"\n'
        "        WHERE obs_value IS NOT NULL\n"
        "          AND time_period IS NOT NULL\n"
    )


def _transform_key(entity_id: str) -> tuple:
    # The published grain is the full dimensional combination of the ILOSTAT
    # long series: ref_area x source x period, plus exactly the dimension
    # columns this indicator carries (mirrors _transform_sql's dim selection).
    has_sex, n_classif = ENTITY_META.get(entity_id, (1, 2))
    dims = []
    if has_sex:
        dims.append("sex")
    if n_classif >= 1:
        dims.append("classif1")
    if n_classif >= 2:
        dims.append("classif2")
    return ("ref_area", "source", "time_period", *dims)


TRANSFORM_SPECS = [
    SqlNodeSpec(
        id=f"{s.id}-transform",
        deps=[s.id],
        sql=_transform_sql(s.id, eid),
        key=_transform_key(eid),
        temporal="date",
    )
    for s, eid in zip(DOWNLOAD_SPECS, ENTITY_IDS)
]
