-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "Field of study" AS field_of_study,
    "All employed - Total - Number" AS all_employed_total_number,
    "All employed - Total - SE" AS all_employed_total_se,
    "All employed - Male - Number" AS all_employed_male_number,
    "All employed - Male - SE" AS all_employed_male_se,
    "All employed - Female - Number" AS all_employed_female_number,
    "All employed - Female - SE" AS all_employed_female_se,
    "Hispanic or Latinoa - Total - Number" AS hispanic_or_latinoa_total_number,
    "Hispanic or Latinoa - Total - SE" AS hispanic_or_latinoa_total_se,
    "Hispanic or Latinoa - Male - Number" AS hispanic_or_latinoa_male_number,
    "Hispanic or Latinoa - Male - SE" AS hispanic_or_latinoa_male_se,
    "Hispanic or Latinoa - Female - Number" AS hispanic_or_latinoa_female_number,
    "Hispanic or Latinoa - Female - SE" AS hispanic_or_latinoa_female_se,
    "Not Hispanic or Latinob - American Indian or Alaska Native - Total - Number" AS not_hispanic_or_latinob_american_indian_or_alaska_native_total_number,
    "Not Hispanic or Latinob - American Indian or Alaska Native - Total - SE" AS not_hispanic_or_latinob_american_indian_or_alaska_native_total_se,
    "Not Hispanic or Latinob - American Indian or Alaska Native - Male - Number" AS not_hispanic_or_latinob_american_indian_or_alaska_native_male_number,
    "Not Hispanic or Latinob - American Indian or Alaska Native - Male - SE" AS not_hispanic_or_latinob_american_indian_or_alaska_native_male_se,
    "Not Hispanic or Latinob - American Indian or Alaska Native - Female - Number" AS not_hispanic_or_latinob_american_indian_or_alaska_native_female_number,
    "Not Hispanic or Latinob - American Indian or Alaska Native - Female - SE" AS not_hispanic_or_latinob_american_indian_or_alaska_native_female_se,
    "Not Hispanic or Latinob - Asian - Total - Number" AS not_hispanic_or_latinob_asian_total_number,
    "Not Hispanic or Latinob - Asian - Total - SE" AS not_hispanic_or_latinob_asian_total_se,
    "Not Hispanic or Latinob - Asian - Male - Number" AS not_hispanic_or_latinob_asian_male_number,
    "Not Hispanic or Latinob - Asian - Male - SE" AS not_hispanic_or_latinob_asian_male_se,
    "Not Hispanic or Latinob - Asian - Female - Number" AS not_hispanic_or_latinob_asian_female_number,
    "Not Hispanic or Latinob - Asian - Female - SE" AS not_hispanic_or_latinob_asian_female_se,
    "Not Hispanic or Latinob - Black or African American - Total - Number" AS not_hispanic_or_latinob_black_or_african_american_total_number,
    "Not Hispanic or Latinob - Black or African American - Total - SE" AS not_hispanic_or_latinob_black_or_african_american_total_se,
    "Not Hispanic or Latinob - Black or African American - Male - Number" AS not_hispanic_or_latinob_black_or_african_american_male_number,
    "Not Hispanic or Latinob - Black or African American - Male - SE" AS not_hispanic_or_latinob_black_or_african_american_male_se,
    "Not Hispanic or Latinob - Black or African American - Female - Number" AS not_hispanic_or_latinob_black_or_african_american_female_number,
    "Not Hispanic or Latinob - Black or African American - Female - SE" AS not_hispanic_or_latinob_black_or_african_american_female_se,
    "Not Hispanic or Latinob - White - Total - Number" AS not_hispanic_or_latinob_white_total_number,
    "Not Hispanic or Latinob - White - Total - SE" AS not_hispanic_or_latinob_white_total_se,
    "Not Hispanic or Latinob - White - Male - Number" AS not_hispanic_or_latinob_white_male_number,
    "Not Hispanic or Latinob - White - Male - SE" AS not_hispanic_or_latinob_white_male_se,
    "Not Hispanic or Latinob - White - Female - Number" AS not_hispanic_or_latinob_white_female_number,
    "Not Hispanic or Latinob - White - Female - SE" AS not_hispanic_or_latinob_white_female_se,
    "Not Hispanic or Latinob - Other racec - Total - Number" AS not_hispanic_or_latinob_other_racec_total_number,
    "Not Hispanic or Latinob - Other racec - Total - SE" AS not_hispanic_or_latinob_other_racec_total_se,
    "Not Hispanic or Latinob - Other racec - Male - Number" AS not_hispanic_or_latinob_other_racec_male_number,
    "Not Hispanic or Latinob - Other racec - Male - SE" AS not_hispanic_or_latinob_other_racec_male_se,
    "Not Hispanic or Latinob - Other racec - Female - Number" AS not_hispanic_or_latinob_other_racec_female_number,
    "Not Hispanic or Latinob - Other racec - Female - SE" AS not_hispanic_or_latinob_other_racec_female_se
FROM "ncses-nsf25321-tab008"
