-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: National accounts include annual and quarterly frequencies plus multiple account, sector, instrument, price, and transformation dimensions; filter frequency and accounting dimensions before comparing or aggregating.
SELECT
    "DATAFLOW" AS dataflow,
    "FREQ" AS freq,
    "ADJUSTMENT" AS adjustment,
    "REF_AREA" AS ref_area,
    "COUNTERPART_AREA" AS counterpart_area,
    "REF_SECTOR" AS ref_sector,
    "COUNTERPART_SECTOR" AS counterpart_sector,
    "ACCOUNTING_ENTRY" AS accounting_entry,
    "STO" AS sto,
    "INSTR_ASSET" AS instr_asset,
    "ACTIVITY" AS activity,
    "EXPENDITURE" AS expenditure,
    "UNIT_MEASURE" AS unit_measure,
    "PRICES" AS prices,
    "TRANSFORMATION" AS transformation,
    "TIME_PERIOD" AS time_period,
    CAST("OBS_VALUE" AS BIGINT) AS obs_value,
    "OBS_STATUS" AS obs_status,
    "CONF_STATUS" AS conf_status,
    "COMMENT_OBS" AS comment_obs,
    "EMBARGO_DATE" AS embargo_date,
    "REF_PERIOD_DETAIL" AS ref_period_detail,
    "REPYEARSTART" AS repyearstart,
    "REPYEAREND" AS repyearend,
    "TIME_FORMAT" AS time_format,
    "TIME_PER_COLLECT" AS time_per_collect,
    CAST("REF_YEAR_PRICE" AS BIGINT) AS ref_year_price,
    CAST("DECIMALS" AS BIGINT) AS decimals,
    "TABLE_IDENTIFIER" AS table_identifier,
    "TITLE" AS title,
    "TITLE_COMPL" AS title_compl,
    CAST("UNIT_MULT" AS BIGINT) AS unit_mult,
    "LAST_UPDATE" AS last_update,
    "COMPILING_ORG" AS compiling_org,
    "COMMENT_DSET" AS comment_dset,
    "COMMENT_TS" AS comment_ts,
    "PRE_BREAK_VALUE" AS pre_break_value,
    "DATA_COMP" AS data_comp,
    "CURRENCY" AS currency,
    "DISS_ORG" AS diss_org
FROM "undata-na-main"
