-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Rows are monthly employment snapshot records rather than a unique dimensional cube; aggregate only after filtering to the intended source_year, source_month, source_version, and workforce dimensions.
-- caution: Several code columns have companion label columns in the same table; preserve both when grouping so source code systems remain auditable.
SELECT
    "accession_category",
    "accession_category_code",
    "age_bracket",
    "agency",
    "agency_code",
    "agency_subelement",
    "agency_subelement_code",
    "annualized_adjusted_basic_pay",
    "appointment_not_to_exceed_date",
    "appointment_type",
    "appointment_type_code",
    "bargaining_unit",
    "bargaining_unit_code",
    "bargaining_unit_status",
    "cfo_act_agency_indicator",
    "consolidated_statistical_area",
    "consolidated_statistical_area_code",
    "core_based_statistical_area",
    "core_based_statistical_area_code",
    CAST("count" AS BIGINT) AS count,
    "department",
    "department_code",
    "drp_indicator",
    "duty_station_city",
    "duty_station_code",
    "duty_station_country",
    "duty_station_country_code",
    "duty_station_county",
    "duty_station_county_code",
    "duty_station_state",
    "duty_station_state_abbreviation",
    "duty_station_state_code",
    "duty_station_state_country_territory_code",
    "education_level",
    "education_level_bracket",
    "education_level_code",
    "flsa_category",
    "flsa_category_code",
    "grade",
    CAST("length_of_service_years" AS DOUBLE) AS length_of_service_years,
    "locality_pay_area",
    "locality_pay_area_code",
    "nsftp_indicator",
    "occupational_category",
    "occupational_category_code",
    "occupational_group",
    "occupational_group_code",
    "occupational_series",
    "occupational_series_code",
    "pathways_group",
    "pay_basis",
    "pay_basis_code",
    "pay_plan",
    "pay_plan_code",
    "personnel_action_effective_date_yyyymm",
    "personnel_office_identifier_code",
    "position_occupied",
    "position_occupied_code",
    strptime("service_computation_date_leave", '%Y-%m-%d')::DATE AS service_computation_date_leave,
    "separation_category",
    "separation_category_code",
    CAST("snapshot_yyyymm" AS BIGINT) AS snapshot_yyyymm,
    "stem_occupation",
    "stem_occupation_type",
    "step_or_rate_type",
    "step_or_rate_type_code",
    "supervisory_status",
    "supervisory_status_code",
    "tenure",
    "tenure_code",
    "veteran_indicator",
    "work_schedule",
    "work_schedule_code",
    "source_family",
    "source_filename",
    CAST("source_publish_date" AS TIMESTAMP) AS source_publish_date,
    "source_year",
    "source_month",
    "source_version"
FROM "opm-employment"
