-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "din_instante",
    "nom_tipopatamar",
    "id_subsistema",
    "nom_subsistema",
    "nom_usina",
    "cod_usinaplanejamento",
    "ceg",
    CAST("val_proggeracao" AS DOUBLE) AS val_proggeracao,
    CAST("val_progordemmerito" AS DOUBLE) AS val_progordemmerito,
    CAST("val_progordemdemeritoref" AS DOUBLE) AS val_progordemdemeritoref,
    CAST("val_progordemdemeritoacimadainflex" AS DOUBLE) AS val_progordemdemeritoacimadainflex,
    CAST("val_proginflexibilidade" AS DOUBLE) AS val_proginflexibilidade,
    CAST("val_proginflexembutmerito" AS DOUBLE) AS val_proginflexembutmerito,
    CAST("val_proginflexpura" AS DOUBLE) AS val_proginflexpura,
    CAST("val_prograzaoeletrica" AS DOUBLE) AS val_prograzaoeletrica,
    CAST("val_proggarantiaenergetica" AS DOUBLE) AS val_proggarantiaenergetica,
    CAST("val_proggfom" AS DOUBLE) AS val_proggfom,
    CAST("val_progreposicaoperdas" AS DOUBLE) AS val_progreposicaoperdas,
    CAST("val_progexportacao" AS DOUBLE) AS val_progexportacao,
    CAST("val_progreservapotencia" AS DOUBLE) AS val_progreservapotencia,
    CAST("val_proggsub" AS DOUBLE) AS val_proggsub,
    "val_progunitcommitment",
    CAST("val_progconstrainedoff" AS DOUBLE) AS val_progconstrainedoff,
    "val_proginflexibilidadedessem",
    CAST("val_verifgeracao" AS DOUBLE) AS val_verifgeracao,
    CAST("val_verifordemmerito" AS DOUBLE) AS val_verifordemmerito,
    CAST("val_verifordemdemeritoacimadainflex" AS DOUBLE) AS val_verifordemdemeritoacimadainflex,
    CAST("val_verifinflexibilidade" AS DOUBLE) AS val_verifinflexibilidade,
    CAST("val_verifinflexembutmerito" AS DOUBLE) AS val_verifinflexembutmerito,
    CAST("val_verifinflexpura" AS DOUBLE) AS val_verifinflexpura,
    CAST("val_verifrazaoeletrica" AS DOUBLE) AS val_verifrazaoeletrica,
    CAST("val_verifgarantiaenergetica" AS DOUBLE) AS val_verifgarantiaenergetica,
    CAST("val_verifgfom" AS DOUBLE) AS val_verifgfom,
    CAST("val_verifreposicaoperdas" AS DOUBLE) AS val_verifreposicaoperdas,
    CAST("val_verifexportacao" AS DOUBLE) AS val_verifexportacao,
    "val_fdexp",
    CAST("val_verifreservapotencia" AS DOUBLE) AS val_verifreservapotencia,
    CAST("val_atendsatisfatoriorpo" AS DOUBLE) AS val_atendsatisfatoriorpo,
    CAST("val_verifgsub" AS DOUBLE) AS val_verifgsub,
    "val_verifunitcommitment",
    CAST("val_verifconstrainedoff" AS DOUBLE) AS val_verifconstrainedoff,
    "tip_restricaoeletrica",
    CAST("val_progdisponibilidade" AS DOUBLE) AS val_progdisponibilidade,
    CAST("val_geracaodespachada" AS DOUBLE) AS val_geracaodespachada,
    "nom_combustivel",
    "dsc_tpmotivorestricao",
    CAST("din_publicacao" AS TIMESTAMP) AS din_publicacao
FROM "ons-brazil-geracao-termica-despacho-2"
