-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
SELECT
    "region",
    "ancienne_region",
    "ape",
    "secteur_na88",
    "secteur_na38",
    "secteur_na17",
    "grand_secteur_d_activite",
    "code_region",
    "code_ancienne_region",
    "code_ape",
    "nombre_d_etablissements_2006",
    "effectifs_salaries_2006",
    "nombre_d_etablissements_2007",
    "effectifs_salaries_2007",
    "nombre_d_etablissements_2008",
    "effectifs_salaries_2008",
    "nombre_d_etablissements_2009",
    "effectifs_salaries_2009",
    "nombre_d_etablissements_2010",
    "effectifs_salaries_2010",
    "nombre_d_etablissements_2011",
    "effectifs_salaries_2011",
    "nombre_d_etablissements_2012",
    "effectifs_salaries_2012",
    "nombre_d_etablissements_2013",
    "effectifs_salaries_2013",
    "nombre_d_etablissements_2014",
    "effectifs_salaries_2014",
    "nombre_d_etablissements_2015",
    "effectifs_salaries_2015",
    "nombre_d_etablissements_2016",
    "effectifs_salaries_2016",
    "nombre_d_etablissements_2017",
    "effectifs_salaries_2017",
    "nombre_d_etablissements_2018",
    "effectifs_salaries_2018",
    "nombre_d_etablissements_2019",
    "effectifs_salaries_2019",
    "nombre_d_etablissements_2020",
    "effectifs_salaries_2020",
    "nombre_d_etablissements_2021",
    "effectifs_salaries_2021",
    "nombre_d_etablissements_2022",
    "effectifs_salaries_2022",
    "nombre_d_etablissements_2023",
    "effectifs_salaries_2023",
    "nombre_d_etablissements_2024",
    "effectifs_salaries_2024",
    "nombre_d_etablissements_2025",
    "effectifs_salaries_2025"
FROM "urssaf-nombre-detablissements-employeurs-et-effectifs-salaries-du-secteur-prive-par-reg"
