columns:
  - name: "CNTR_CODE"
    type: VARCHAR
  - name: "FID"
    type: VARCHAR
  - name: "geometry_60M_3857"
    type: VARCHAR
  - name: "id"
    type: VARCHAR
  - name: "LEVL_CODE"
    type: VARCHAR
  - name: "NUTS_ID"
    type: VARCHAR
  - name: "NUTS_NAME"
    type: VARCHAR
