SELECT
    CAST("catalogueCode" AS VARCHAR) AS "catalogueCode",
    CAST("countryCode" AS VARCHAR) AS "countryCode",
    CAST("featureCode" AS VARCHAR) AS "featureCode",
    CAST("measureAdditionalInfo" AS VARCHAR) AS "measureAdditionalInfo",
    CAST("measureCode" AS VARCHAR) AS "measureCode",
    CAST("measureImpactToDetails" AS VARCHAR) AS "measureImpactToDetails",
    CAST("measureImpactToId" AS VARCHAR) AS "measureImpactToId",
    CAST("measureLocation" AS VARCHAR) AS "measureLocation",
    CAST("measureName" AS VARCHAR) AS "measureName",
    CAST("measureNatureId" AS VARCHAR) AS "measureNatureId",
    CAST("measureOriginId" AS VARCHAR) AS "measureOriginId",
    CAST("measurePurpose" AS VARCHAR) AS "measurePurpose",
    CAST("measureResponse" AS VARCHAR) AS "measureResponse",
    CAST("measureStatusId" AS VARCHAR) AS "measureStatusId",
    CAST("pressureCode" AS VARCHAR) AS "pressureCode",
    CAST("pressureName" AS VARCHAR) AS "pressureName",
    CAST("pressureType" AS VARCHAR) AS "pressureType",
    CAST("ranking" AS VARCHAR) AS "ranking",
    CAST("recommendedMeasureTypeE02AndOrE03" AS VARCHAR) AS "recommendedMeasureTypeE02AndOrE03",
    CAST("season" AS VARCHAR) AS "season",
    CAST("sectorId" AS VARCHAR) AS "sectorId",
    CAST("spatialScopeId" AS VARCHAR) AS "spatialScopeId",
    CAST("subUnit" AS VARCHAR) AS "subUnit",
    CAST("useOrActivityId" AS VARCHAR) AS "useOrActivityId",
    CAST("waterBodyCategoryId" AS VARCHAR) AS "waterBodyCategoryId"
FROM "european-environment-agency-wise-shippingsports-measures.bd-2013-2018"
