SELECT
    CAST("bathingWaterIdentifier" AS VARCHAR) AS "bathingWaterIdentifier",
    CAST("escherichiaColiStatus" AS VARCHAR) AS "escherichiaColiStatus",
    CAST("escherichiaColiValue" AS VARCHAR) AS "escherichiaColiValue",
    CAST("intestinalEnterococciStatus" AS VARCHAR) AS "intestinalEnterococciStatus",
    CAST("intestinalEnterococciValue" AS VARCHAR) AS "intestinalEnterococciValue",
    CAST("metadata_beginLifeSpanVersion" AS VARCHAR) AS "metadata_beginLifeSpanVersion",
    CAST("metadata_endLifeSpanVersion" AS VARCHAR) AS "metadata_endLifeSpanVersion",
    CAST("metadata_observationStatus" AS VARCHAR) AS "metadata_observationStatus",
    CAST("metadata_replacedBy" AS VARCHAR) AS "metadata_replacedBy",
    CAST("metadata_replaces" AS VARCHAR) AS "metadata_replaces",
    CAST("metadata_statements" AS VARCHAR) AS "metadata_statements",
    CAST("metadata_statusCode" AS VARCHAR) AS "metadata_statusCode",
    CAST("metadata_statusDate" AS VARCHAR) AS "metadata_statusDate",
    CAST("metadata_versionId" AS VARCHAR) AS "metadata_versionId",
    CAST("remarks" AS VARCHAR) AS "remarks",
    CAST("sampleDate" AS VARCHAR) AS "sampleDate",
    CAST("sampleStatus" AS VARCHAR) AS "sampleStatus",
    CAST("season" AS VARCHAR) AS "season",
    CAST("UID" AS VARCHAR) AS "UID"
FROM "european-environment-agency-wise-bwd.timeseries-monitoringresult"
