SELECT
    CAST("countryCode" AS VARCHAR) AS "countryCode",
    CAST("countryName" AS VARCHAR) AS "countryName",
    CAST("created" AS VARCHAR) AS "created",
    CAST("creatorElectronicMailAddress" AS VARCHAR) AS "creatorElectronicMailAddress",
    CAST("creatorOrganisationName" AS VARCHAR) AS "creatorOrganisationName",
    CAST("description" AS VARCHAR) AS "description",
    CAST("euFloodsUnitOfManagementCode" AS VARCHAR) AS "euFloodsUnitOfManagementCode",
    CAST("language" AS VARCHAR) AS "language",
    CAST("license" AS VARCHAR) AS "license",
    CAST("metadata_beginLifeSpanVersion" AS VARCHAR) AS "metadata_beginLifeSpanVersion",
    CAST("metadata_endLifeSpanVersion" AS VARCHAR) AS "metadata_endLifeSpanVersion",
    CAST("metadata_observationStatus" AS VARCHAR) AS "metadata_observationStatus",
    CAST("metadata_replacedBy" AS VARCHAR) AS "metadata_replacedBy",
    CAST("metadata_replaces" AS VARCHAR) AS "metadata_replaces",
    CAST("metadata_statements" AS VARCHAR) AS "metadata_statements",
    CAST("metadata_statusCode" AS VARCHAR) AS "metadata_statusCode",
    CAST("metadata_statusDate" AS VARCHAR) AS "metadata_statusDate",
    CAST("metadata_versionId" AS VARCHAR) AS "metadata_versionId",
    CAST("reportingStructuredData" AS VARCHAR) AS "reportingStructuredData",
    CAST("rights" AS VARCHAR) AS "rights",
    CAST("rightsHolder" AS VARCHAR) AS "rightsHolder",
    CAST("title" AS VARCHAR) AS "title",
    CAST("UID" AS VARCHAR) AS "UID"
FROM "european-environment-agency-wise-floods.floodriskmanagementplans-dcmetadata"
