SELECT
    CAST("BATAEL" AS VARCHAR) AS "BATAEL",
    CAST("BATAELAcceptedDate" AS VARCHAR) AS "BATAELAcceptedDate",
    CAST("BATAELName" AS VARCHAR) AS "BATAELName",
    CAST("BATAELStatus" AS VARCHAR) AS "BATAELStatus",
    CAST("conclusionName" AS VARCHAR) AS "conclusionName",
    CAST("conclusionStatus" AS VARCHAR) AS "conclusionStatus",
    CAST("countryCode" AS VARCHAR) AS "countryCode",
    CAST("Derogated from - to" AS VARCHAR) AS "Derogated from - to",
    CAST("Description" AS VARCHAR) AS "Description",
    CAST("endDate" AS VARCHAR) AS "endDate",
    CAST("entityStatus" AS VARCHAR) AS "entityStatus",
    CAST("euregReportingYear" AS VARCHAR) AS "euregReportingYear",
    CAST("facilityInspireId" AS VARCHAR) AS "facilityInspireId",
    CAST("installationInspireId" AS VARCHAR) AS "installationInspireId",
    CAST("operatingSince_" AS VARCHAR) AS "operatingSince_",
    CAST("permitAvailable" AS VARCHAR) AS "permitAvailable",
    CAST("permitingAuthority" AS VARCHAR) AS "permitingAuthority",
    CAST("permitUpdated" AS VARCHAR) AS "permitUpdated",
    CAST("regulatedActivities" AS VARCHAR) AS "regulatedActivities",
    CAST("seveso" AS VARCHAR) AS "seveso",
    CAST("siteInspireId" AS VARCHAR) AS "siteInspireId",
    CAST("siteName" AS VARCHAR) AS "siteName",
    CAST("startDate" AS VARCHAR) AS "startDate"
FROM "european-environment-agency-ied.browse9header-old"
