SELECT
    CAST("Af1 (m2)" AS VARCHAR) AS "Af1 (m2)",
    CAST("Af2 (m2)" AS VARCHAR) AS "Af2 (m2)",
    CAST("Af3 (m2)" AS VARCHAR) AS "Af3 (m2)",
    CAST("At1 (mm)" AS VARCHAR) AS "At1 (mm)",
    CAST("At2 (mm)" AS VARCHAR) AS "At2 (mm)",
    CAST("Cn" AS VARCHAR) AS "Cn",
    CAST("Cr" AS VARCHAR) AS "Cr",
    CAST("Ct" AS VARCHAR) AS "Ct",
    CAST("Dam (kg)" AS VARCHAR) AS "Dam (kg)",
    CAST("De" AS VARCHAR) AS "De",
    CAST("Ec (cm3)" AS VARCHAR) AS "Ec (cm3)",
    CAST("Enedc (g/km)" AS VARCHAR) AS "Enedc (g/km)",
    CAST("Ep (KW)" AS VARCHAR) AS "Ep (KW)",
    CAST("Ernedc (g/km)" AS VARCHAR) AS "Ernedc (g/km)",
    CAST("Erwltp (g/km)" AS VARCHAR) AS "Erwltp (g/km)",
    CAST("Ewltp_Final (g/km)" AS VARCHAR) AS "Ewltp_Final (g/km)",
    CAST("Ewltp_MS (g/km)" AS VARCHAR) AS "Ewltp_MS (g/km)",
    CAST("Ewltp_OEM (g/km)" AS VARCHAR) AS "Ewltp_OEM (g/km)",
    CAST("Fm" AS VARCHAR) AS "Fm",
    CAST("Ft" AS VARCHAR) AS "Ft",
    CAST("ID" AS VARCHAR) AS "ID",
    CAST("IT" AS VARCHAR) AS "IT",
    CAST("M (kg)" AS VARCHAR) AS "M (kg)",
    CAST("MAN" AS VARCHAR) AS "MAN",
    CAST("Mb (kg)" AS VARCHAR) AS "Mb (kg)",
    CAST("Mf (kg)" AS VARCHAR) AS "Mf (kg)",
    CAST("Mh" AS VARCHAR) AS "Mh",
    CAST("Mk" AS VARCHAR) AS "Mk",
    CAST("Mmon (kg)" AS VARCHAR) AS "Mmon (kg)",
    CAST("MMS" AS VARCHAR) AS "MMS",
    CAST("MP" AS VARCHAR) AS "MP",
    CAST("MS" AS VARCHAR) AS "MS",
    CAST("Mt (kg)" AS VARCHAR) AS "Mt (kg)",
    CAST("MvL (kg)" AS VARCHAR) AS "MvL (kg)",
    CAST("R" AS VARCHAR) AS "R",
    CAST("RR (kg/t)" AS VARCHAR) AS "RR (kg/t)",
    CAST("status" AS VARCHAR) AS "status",
    CAST("T" AS VARCHAR) AS "T",
    CAST("TAN" AS VARCHAR) AS "TAN",
    CAST("TPMLM (kg)" AS VARCHAR) AS "TPMLM (kg)",
    CAST("Va" AS VARCHAR) AS "Va",
    CAST("Ve" AS VARCHAR) AS "Ve",
    CAST("version_file" AS VARCHAR) AS "version_file",
    CAST("Vf" AS VARCHAR) AS "Vf",
    CAST("VFN" AS VARCHAR) AS "VFN",
    CAST("W (mm)" AS VARCHAR) AS "W (mm)",
    CAST("year" AS VARCHAR) AS "year",
    CAST("Z (Wh/km)" AS VARCHAR) AS "Z (Wh/km)",
    CAST("Zr" AS VARCHAR) AS "Zr"
FROM "european-environment-agency-co2emission.co2vans-2020fv18"
