columns:
  - name: "Country"
    type: VARCHAR
  - name: "NUTS_CODE"
    type: VARCHAR
  - name: "position"
    type: VARCHAR
  - name: "Unit"
    type: VARCHAR
  - name: "value"
    type: VARCHAR
  - name: "wood_product"
    type: VARCHAR
  - name: "Year"
    type: VARCHAR
