SELECT
    CAST("countryCode" AS VARCHAR) AS "countryCode",
    CAST("countryGroup" AS VARCHAR) AS "countryGroup",
    CAST("countryName" AS VARCHAR) AS "countryName",
    CAST("eeaIndicator" AS VARCHAR) AS "eeaIndicator",
    CAST("matrixDissolved" AS VARCHAR) AS "matrixDissolved",
    CAST("matrixTotal" AS VARCHAR) AS "matrixTotal",
    CAST("matrixTotalOrDissolved" AS VARCHAR) AS "matrixTotalOrDissolved",
    CAST("maxGapLongTimeSeries" AS VARCHAR) AS "maxGapLongTimeSeries",
    CAST("maxGapShortTimeSeries" AS VARCHAR) AS "maxGapShortTimeSeries",
    CAST("maxYear" AS VARCHAR) AS "maxYear",
    CAST("meanValue" AS VARCHAR) AS "meanValue",
    CAST("minYear" AS VARCHAR) AS "minYear",
    CAST("monitoringSiteIdentifier" AS VARCHAR) AS "monitoringSiteIdentifier",
    CAST("monitoringSiteIdentifierScheme" AS VARCHAR) AS "monitoringSiteIdentifierScheme",
    CAST("monitoringSiteStatusCode" AS VARCHAR) AS "monitoringSiteStatusCode",
    CAST("numberOfYears" AS VARCHAR) AS "numberOfYears",
    CAST("resultUom" AS VARCHAR) AS "resultUom",
    CAST("seriesSpan" AS VARCHAR) AS "seriesSpan",
    CAST("seriesUID" AS VARCHAR) AS "seriesUID",
    CAST("stdevValue" AS VARCHAR) AS "stdevValue",
    CAST("waterBodyCategory" AS VARCHAR) AS "waterBodyCategory"
FROM "european-environment-agency-wise-indicators.aggregateddata-summary"
