SELECT
    CAST("confidentialityStatus" AS VARCHAR) AS "confidentialityStatus",
    CAST("countryCode" AS VARCHAR) AS "countryCode",
    CAST("lat" AS VARCHAR) AS "lat",
    CAST("lon" AS VARCHAR) AS "lon",
    CAST("monitoringSiteIdentifier" AS VARCHAR) AS "monitoringSiteIdentifier",
    CAST("monitoringSiteIdentifierScheme" AS VARCHAR) AS "monitoringSiteIdentifierScheme",
    CAST("monitoringSiteName" AS VARCHAR) AS "monitoringSiteName",
    CAST("naturalAWBHMWB" AS VARCHAR) AS "naturalAWBHMWB",
    CAST("rbdIdentifier" AS VARCHAR) AS "rbdIdentifier",
    CAST("rbdIdentifierScheme" AS VARCHAR) AS "rbdIdentifierScheme",
    CAST("rbdName" AS VARCHAR) AS "rbdName",
    CAST("reservoir" AS VARCHAR) AS "reservoir",
    CAST("specialisedZoneType" AS VARCHAR) AS "specialisedZoneType",
    CAST("statusCode" AS VARCHAR) AS "statusCode",
    CAST("subUnitIdentifier" AS VARCHAR) AS "subUnitIdentifier",
    CAST("subUnitIdentifierScheme" AS VARCHAR) AS "subUnitIdentifierScheme",
    CAST("subUnitName" AS VARCHAR) AS "subUnitName",
    CAST("surfaceWaterBodyTypeCode" AS VARCHAR) AS "surfaceWaterBodyTypeCode",
    CAST("thematicIdIdentifier" AS VARCHAR) AS "thematicIdIdentifier",
    CAST("thematicIdIdentifierScheme" AS VARCHAR) AS "thematicIdIdentifierScheme",
    CAST("waterBodyIdentifier" AS VARCHAR) AS "waterBodyIdentifier",
    CAST("waterBodyIdentifierScheme" AS VARCHAR) AS "waterBodyIdentifierScheme",
    CAST("waterBodyName" AS VARCHAR) AS "waterBodyName"
FROM "european-environment-agency-wise-soe.waterbase-s-wise-spatialobject-deriveddata"
