SELECT
    CAST("countryCode" AS VARCHAR) AS "countryCode",
    CAST("countryGroup" AS VARCHAR) AS "countryGroup",
    CAST("countryName" AS VARCHAR) AS "countryName",
    CAST("cvDrinkingWaterValueRange" AS VARCHAR) AS "cvDrinkingWaterValueRange",
    CAST("cvDrinkingWaterValueUnit" AS VARCHAR) AS "cvDrinkingWaterValueUnit",
    CAST("cvIndustryValueRange" AS VARCHAR) AS "cvIndustryValueRange",
    CAST("cvIndustryValueUnit" AS VARCHAR) AS "cvIndustryValueUnit",
    CAST("cvIrrigationValueRange" AS VARCHAR) AS "cvIrrigationValueRange",
    CAST("cvIrrigationValueUnit" AS VARCHAR) AS "cvIrrigationValueUnit",
    CAST("cvOtherDescription" AS VARCHAR) AS "cvOtherDescription",
    CAST("cvOtherValueRange" AS VARCHAR) AS "cvOtherValueRange",
    CAST("cvOtherValueUnit" AS VARCHAR) AS "cvOtherValueUnit",
    CAST("cYear" AS VARCHAR) AS "cYear",
    CAST("euRBDCode" AS VARCHAR) AS "euRBDCode",
    CAST("fileUrl" AS VARCHAR) AS "fileUrl",
    CAST("hasDescriptiveData" AS VARCHAR) AS "hasDescriptiveData",
    CAST("pollutantIndicatorCode" AS VARCHAR) AS "pollutantIndicatorCode",
    CAST("pollutantIndicatorCodeOther" AS VARCHAR) AS "pollutantIndicatorCodeOther",
    CAST("rbdArea" AS VARCHAR) AS "rbdArea",
    CAST("rbdName" AS VARCHAR) AS "rbdName",
    CAST("startingPointTrendReversal" AS VARCHAR) AS "startingPointTrendReversal",
    CAST("thresholdDerivedFromCV" AS VARCHAR) AS "thresholdDerivedFromCV",
    CAST("thresholdValueRange" AS VARCHAR) AS "thresholdValueRange",
    CAST("thresholdValueScale" AS VARCHAR) AS "thresholdValueScale",
    CAST("thresholdValueUnit" AS VARCHAR) AS "thresholdValueUnit"
FROM "european-environment-agency-wise-wfd.gwmet-thresholdvalue"
