columns:
  - name: "PrimaryCount"
    type: VARCHAR
  - name: "ReportedPeriod"
    type: VARCHAR
  - name: "rptMStateKey"
    type: VARCHAR
  - name: "SecondaryCount"
    type: VARCHAR
  - name: "TertiaryCount"
    type: VARCHAR
  - name: "uwwCodes"
    type: VARCHAR
