SELECT
    CAST("countryCode" AS VARCHAR) AS "countryCode",
    CAST("countryGroup" AS VARCHAR) AS "countryGroup",
    CAST("countryName" AS VARCHAR) AS "countryName",
    CAST("cYear" AS VARCHAR) AS "cYear",
    CAST("euRBDCode" AS VARCHAR) AS "euRBDCode",
    CAST("fileUrl" AS VARCHAR) AS "fileUrl",
    CAST("hasDescriptiveData" AS VARCHAR) AS "hasDescriptiveData",
    CAST("iRBMPIssuesChemical" AS VARCHAR) AS "iRBMPIssuesChemical",
    CAST("iRBMPIssuesNutrient" AS VARCHAR) AS "iRBMPIssuesNutrient",
    CAST("iRBMPIssuesOther" AS VARCHAR) AS "iRBMPIssuesOther",
    CAST("iRBMPIssuesOtherHydromorphological" AS VARCHAR) AS "iRBMPIssuesOtherHydromorphological",
    CAST("iRBMPIssuesRiverContinuity" AS VARCHAR) AS "iRBMPIssuesRiverContinuity",
    CAST("iRBMPIssuesSediment" AS VARCHAR) AS "iRBMPIssuesSediment",
    CAST("pomCoOrdinationArt5SWMI" AS VARCHAR) AS "pomCoOrdinationArt5SWMI",
    CAST("pomCoOrdinationFinancial" AS VARCHAR) AS "pomCoOrdinationFinancial",
    CAST("pomCoOrdinationIRBMPPoM" AS VARCHAR) AS "pomCoOrdinationIRBMPPoM",
    CAST("pomCoOrdinationJointVision" AS VARCHAR) AS "pomCoOrdinationJointVision",
    CAST("pomCoOrdinationLinks" AS VARCHAR) AS "pomCoOrdinationLinks",
    CAST("pomCoOrdinationRoofReport" AS VARCHAR) AS "pomCoOrdinationRoofReport",
    CAST("pomCoOrdinationSectors" AS VARCHAR) AS "pomCoOrdinationSectors",
    CAST("pomCoOrdinationTransparency" AS VARCHAR) AS "pomCoOrdinationTransparency",
    CAST("rbdArea" AS VARCHAR) AS "rbdArea",
    CAST("rbdName" AS VARCHAR) AS "rbdName"
FROM "european-environment-agency-wise-wfd.rbmppom-coord"
