SELECT
    CAST("AveragePayload" AS VARCHAR) AS "AveragePayload",
    CAST("Bw" AS VARCHAR) AS "Bw",
    CAST("ClassOfHybrid" AS VARCHAR) AS "ClassOfHybrid",
    CAST("CodeForBodyworkSpecPurpVeh" AS VARCHAR) AS "CodeForBodyworkSpecPurpVeh",
    CAST("CryptHashManufacturerRecord" AS VARCHAR) AS "CryptHashManufacturerRecord",
    CAST("Electric" AS VARCHAR) AS "Electric",
    CAST("FT" AS VARCHAR) AS "FT",
    CAST("Hybrid" AS VARCHAR) AS "Hybrid",
    CAST("ID" AS VARCHAR) AS "ID",
    CAST("MaximumSpeed" AS VARCHAR) AS "MaximumSpeed",
    CAST("Mh" AS VARCHAR) AS "Mh",
    CAST("Mh_msv" AS VARCHAR) AS "Mh_msv",
    CAST("Mk" AS VARCHAR) AS "Mk",
    CAST("MS" AS VARCHAR) AS "MS",
    CAST("NumberOfAxles" AS VARCHAR) AS "NumberOfAxles",
    CAST("NumberOfPoweredAxles" AS VARCHAR) AS "NumberOfPoweredAxles",
    CAST("RegistrationDate" AS VARCHAR) AS "RegistrationDate",
    CAST("RegistrationDateClean" AS VARCHAR) AS "RegistrationDateClean",
    CAST("SpecificCO2Emissions" AS VARCHAR) AS "SpecificCO2Emissions",
    CAST("StageOfCompletionCode" AS VARCHAR) AS "StageOfCompletionCode",
    CAST("TechnPermMaxLadenMass" AS VARCHAR) AS "TechnPermMaxLadenMass",
    CAST("vehicle_id" AS VARCHAR) AS "vehicle_id",
    CAST("VehicleCategoryCode" AS VARCHAR) AS "VehicleCategoryCode"
FROM "european-environment-agency-co2emission.hdv-2023-memberstate-vehicle"
