columns:
  - name: "alternative"
    type: VARCHAR
  - name: "book_title"
    type: VARCHAR
  - name: "comment"
    type: VARCHAR
    description: "Comment."
  - name: "created"
    type: VARCHAR
  - name: "editor"
    type: VARCHAR
  - name: "id_dc"
    type: VARCHAR
    description: "ID - Primary Key."
  - name: "isbn"
    type: VARCHAR
  - name: "journal_issue"
    type: VARCHAR
  - name: "journal_title"
    type: VARCHAR
  - name: "publisher"
    type: VARCHAR
  - name: "reference"
    type: VARCHAR
    description: "Legal reference. Reference to other DC Index in this same table."
  - name: "source"
    type: VARCHAR
  - name: "title"
    type: VARCHAR
  - name: "url"
    type: VARCHAR
