columns:
  - name: "country"
    type: VARCHAR
  - name: "forest_above_ground"
    type: VARCHAR
  - name: "forest_below_ground"
    type: VARCHAR
  - name: "forest_deadwood"
    type: VARCHAR
  - name: "NUTS_CODE"
    type: VARCHAR
  - name: "units"
    type: VARCHAR
  - name: "year"
    type: VARCHAR
