SELECT
    CAST("capacity_recover" AS VARCHAR) AS "capacity_recover",
    CAST("category_EU28" AS VARCHAR) AS "category_EU28",
    CAST("category_EU28PLUS" AS VARCHAR) AS "category_EU28PLUS",
    CAST("confidence_assessment" AS VARCHAR) AS "confidence_assessment",
    CAST("conservation_management" AS VARCHAR) AS "conservation_management",
    CAST("EU28_trend_quality" AS VARCHAR) AS "EU28_trend_quality",
    CAST("EU28_trend_quantity" AS VARCHAR) AS "EU28_trend_quantity",
    CAST("EU28PLUS_trend_quality" AS VARCHAR) AS "EU28PLUS_trend_quality",
    CAST("EU28PLUS_trend_quantity" AS VARCHAR) AS "EU28PLUS_trend_quantity",
    CAST("habitat_unique_id" AS VARCHAR) AS "habitat_unique_id",
    CAST("map_description" AS VARCHAR) AS "map_description",
    CAST("occurrence_ext_EU28_AOO" AS VARCHAR) AS "occurrence_ext_EU28_AOO",
    CAST("occurrence_ext_EU28_area_km2" AS VARCHAR) AS "occurrence_ext_EU28_area_km2",
    CAST("occurrence_ext_EU28_comment" AS VARCHAR) AS "occurrence_ext_EU28_comment",
    CAST("occurrence_ext_EU28_EOO" AS VARCHAR) AS "occurrence_ext_EU28_EOO",
    CAST("occurrence_ext_EU28PLUS_AOO" AS VARCHAR) AS "occurrence_ext_EU28PLUS_AOO",
    CAST("occurrence_ext_EU28PLUS_area_km2" AS VARCHAR) AS "occurrence_ext_EU28PLUS_area_km2",
    CAST("occurrence_ext_EU28PLUS_comment" AS VARCHAR) AS "occurrence_ext_EU28PLUS_comment",
    CAST("occurrence_ext_EU28PLUS_EOO" AS VARCHAR) AS "occurrence_ext_EU28PLUS_EOO",
    CAST("overall_criteria_EU28" AS VARCHAR) AS "overall_criteria_EU28",
    CAST("overall_criteria_EU28_plus" AS VARCHAR) AS "overall_criteria_EU28_plus",
    CAST("pressures_and_threats" AS VARCHAR) AS "pressures_and_threats",
    CAST("synthesis" AS VARCHAR) AS "synthesis"
FROM "european-environment-agency-eunis.habitat-redlist-status"
