columns:
  - name: "code_2000"
    type: VARCHAR
    description: "Natura 2000 code for the species."
  - name: "id_eunis"
    type: VARCHAR
    description: "EUNIS ID for the species."
  - name: "link"
    type: VARCHAR
    description: "Web link URL."
  - name: "linktext"
    type: VARCHAR
    description: "Web link text."
