columns:
  - name: "countryCode"
    type: VARCHAR
  - name: "countryName"
    type: VARCHAR
  - name: "creationDate"
    type: VARCHAR
  - name: "dataflowDeadlineDate"
    type: VARCHAR
  - name: "dataflowDescription"
    type: VARCHAR
  - name: "dataflowId"
    type: VARCHAR
  - name: "dataflowIsOpen"
    type: VARCHAR
  - name: "dataflowName"
    type: VARCHAR
  - name: "dataProviderId"
    type: VARCHAR
  - name: "dateReleased"
    type: VARCHAR
  - name: "deliveryOrder"
    type: VARCHAR
  - name: "eeaGroup"
    type: VARCHAR
  - name: "eurostatGroup"
    type: VARCHAR
  - name: "isBeforeDeadline"
    type: VARCHAR
  - name: "isLastDelivery"
    type: VARCHAR
  - name: "isReleased"
    type: VARCHAR
  - name: "obligationDisclaimerText"
    type: VARCHAR
  - name: "obligationId"
    type: VARCHAR
  - name: "obligationScope"
    type: VARCHAR
  - name: "releaseOrCreationDate"
    type: VARCHAR
  - name: "statusOfDelivery"
    type: VARCHAR
