columns:
  - name: "Abstract_Line"
    type: VARCHAR
  - name: "Id"
    type: VARCHAR
  - name: "Language"
    type: VARCHAR
  - name: "Signatory"
    type: VARCHAR
  - name: "Title"
    type: VARCHAR
