columns:
  - name: "article_14_4_ConsiderationOfClimateChangeConsidered"
    type: VARCHAR
    description: "Required.\r\nChoose from the 'YesNo' codelist values.\r\nHas climate change been taken into consideration in the review of the PFRA?."
  - name: "article_14_4_ConsiderationOfClimateChangeNotConsideredExplan"
    type: VARCHAR
    description: "Max length: 1000 characters.\r\nConditional.\r\nIf 'No' is selected from enumeration list, provide an explanation as to why this was the case."
  - name: "article_2_1_SewageSystemsExcluded"
    type: VARCHAR
    description: "Required.\r\nChoose from the 'YesNo' codelist values.\r\nState whether floods from sewage systems have been excluded as a source of flooding."
  - name: "article_4_2_a_MapsAvailable"
    type: VARCHAR
    description: "Required.\r\nChoose from the 'YesNo' codelist values.\r\nMap(s) according to Article 4.2(a) (to be coordinated with WFD reporting), including topography and land use."
  - name: "article_4_2_a_MapsDescription"
    type: VARCHAR
    description: "Max length: 1000 characters.\r\nConditional.\r\nProvide a reason/description if 'Article4.2(a)Maps' is set to 'No'."
  - name: "article_4_2_b_PastAdverseConsequencesCriteriaOther"
    type: VARCHAR
    description: "Max length: 1000 characters.\r\nConditional.\r\nIf 'Other' is selected from enumeration list, provide a description of what other criteria (there may be several 'other' criteria) have been used to define past floods with significant adverse impacts, with likelihood of repetition."
  - name: "article_4_2_b_PastAdverseConsequencesExpertJudgementDescript"
    type: VARCHAR
    description: "Max length: 1000 characters.\r\nOptional."
  - name: "article_4_2_b_PastAdverseConsequencesReference"
    type: VARCHAR
    description: "Required.\r\nProvide document(s) or link(s) to the methodology and criteria used to identify and assess floods that occurred in the past and their past adverse consequences (including whether such consequences would be 'significant') and whether the likelihood of such floods remains relevant.\r\nMore than one option can be selected. If more than one, values need to be separated by a semicolon followed by a whitespace. e.g., \"value1; value2; value3\"."
  - name: "article_4_2_c_SignificantAdverseConsequencesCriteriaOther"
    type: VARCHAR
    description: "Max length: 1000 characters.\r\nConditional.\r\nIf 'Other' is selected from enumeration list, provide a description of what other criteria (there may be several 'other' criteria) have been used to define significant past floods (without known significant adverse impacts) with likelihood for significant adverse consequences in the future."
  - name: "article_4_2_c_SignificantAdverseConsequencesExpertJudgementD"
    type: VARCHAR
    description: "Max length: 1000 characters.\r\nConditional.\r\nif 'Expert Judgement' has been selected from enumeration list, provide a brief description as to how expert judgement was used to define past floods (without known significant adverse impacts) with likelihood for significant adverse consequences in the future."
  - name: "article_4_2_d_PotentialAdverseConsequencesCriteriaOther"
    type: VARCHAR
    description: "Max length: 1000 characters.\r\nConditional.\r\nIf 'Other' is selected from enumeration list, provide a description of what other criteria (there may be several 'other' criteria) have been used to define adverse consequences of future floods."
  - name: "article_4_2_d_PotentialAdverseConsequencesExpertJudgementDes"
    type: VARCHAR
    description: "Max length: 1000 characters.\r\nConditional.\r\nIf 'Expert Judgement' is selected from enumeration list, provide a brief description as to how expert judgement was used to define potential adverse consequences of future floods."
  - name: "article_4_3_InternationalInformationExchangeNoInformationExc"
    type: VARCHAR
    description: "Max length: 1000 characters.\r\nConditional.\r\nIf 'No information exchange' is selected from enumeration list, provide an explanation as to why this was the case."
  - name: "article_4_3_InternationalInformationExchangeOther"
    type: VARCHAR
    description: "Max length: 1000 characters.\r\nConditional.\r\nIf 'Other' is selected from enumeration list, provide a description of what other mechanisms of international information exchange have been used."
  - name: "countryCode"
    type: VARCHAR
    description: "Unique 2 character ISO Code for the EU Member State."
  - name: "countryName"
    type: VARCHAR
    description: "Name for the EU Member State."
  - name: "euFloodsUnitOfManagementCode"
    type: VARCHAR
    description: "Max length: 42 characters.\r\nRequired.\r\nUnique EU code for the Unit of Management or WFD River Basin District following the WISE identifier syntax. Add the two-letter ISO Country code to the Member State unique id - up to 42 characters in total."
  - name: "metadata_beginLifeSpanVersion"
    type: VARCHAR
    description: "Data management attribute: Timestamp when the feature or record was created. In case of reported data, it is the release date and time of the respective data delivery."
  - name: "metadata_statusCode"
    type: VARCHAR
    description: "Data management attribute: Status of the feature or record regarding its registration."
  - name: "metadata_versionId"
    type: VARCHAR
    description: "Data management attribute: Unique metadata identifier of version of the feature or record. URL that points either to the source of the reported data or to a page providing information on the data origin."
  - name: "url"
    type: VARCHAR
    description: "Optional.\r\nURL for integration of your own internet-based information."
