SELECT
    CAST("bqeCategoryCW" AS VARCHAR) AS "bqeCategoryCW",
    CAST("bqeCategoryLW" AS VARCHAR) AS "bqeCategoryLW",
    CAST("bqeCategoryRW" AS VARCHAR) AS "bqeCategoryRW",
    CAST("bqeCategoryTW" AS VARCHAR) AS "bqeCategoryTW",
    CAST("bqeCode" AS VARCHAR) AS "bqeCode",
    CAST("bqeMethodName" AS VARCHAR) AS "bqeMethodName",
    CAST("bqePercentageOfTypes" AS VARCHAR) AS "bqePercentageOfTypes",
    CAST("bqeSensitivityImpactAcidification" AS VARCHAR) AS "bqeSensitivityImpactAcidification",
    CAST("bqeSensitivityImpactChemical" AS VARCHAR) AS "bqeSensitivityImpactChemical",
    CAST("bqeSensitivityImpactHydrological" AS VARCHAR) AS "bqeSensitivityImpactHydrological",
    CAST("bqeSensitivityImpactMorphological" AS VARCHAR) AS "bqeSensitivityImpactMorphological",
    CAST("bqeSensitivityImpactNutrients" AS VARCHAR) AS "bqeSensitivityImpactNutrients",
    CAST("bqeSensitivityImpactOrganic" AS VARCHAR) AS "bqeSensitivityImpactOrganic",
    CAST("bqeSensitivityImpactOther" AS VARCHAR) AS "bqeSensitivityImpactOther",
    CAST("bqeSensitivityImpactSaline" AS VARCHAR) AS "bqeSensitivityImpactSaline",
    CAST("bqeSensitivityImpactTemperature" AS VARCHAR) AS "bqeSensitivityImpactTemperature",
    CAST("countryCode" AS VARCHAR) AS "countryCode",
    CAST("countryGroup" AS VARCHAR) AS "countryGroup",
    CAST("countryName" AS VARCHAR) AS "countryName",
    CAST("cYear" AS VARCHAR) AS "cYear",
    CAST("euRBDCode" AS VARCHAR) AS "euRBDCode",
    CAST("fileUrl" AS VARCHAR) AS "fileUrl",
    CAST("hasDescriptiveData" AS VARCHAR) AS "hasDescriptiveData",
    CAST("rbdArea" AS VARCHAR) AS "rbdArea",
    CAST("rbdName" AS VARCHAR) AS "rbdName"
FROM "european-environment-agency-wise-wfd.swmet-bqemethod-bqesensitivityimpactother"
