SELECT
    CAST("catalogueCode" AS VARCHAR) AS "catalogueCode",
    CAST("country" AS VARCHAR) AS "country",
    CAST("D1" AS VARCHAR) AS "D1",
    CAST("D10" AS VARCHAR) AS "D10",
    CAST("D11" AS VARCHAR) AS "D11",
    CAST("D2" AS VARCHAR) AS "D2",
    CAST("D3" AS VARCHAR) AS "D3",
    CAST("D4" AS VARCHAR) AS "D4",
    CAST("D5" AS VARCHAR) AS "D5",
    CAST("D6" AS VARCHAR) AS "D6",
    CAST("D7" AS VARCHAR) AS "D7",
    CAST("D8" AS VARCHAR) AS "D8",
    CAST("D9" AS VARCHAR) AS "D9",
    CAST("measureImpactTo" AS VARCHAR) AS "measureImpactTo",
    CAST("measureImpactToDetails" AS VARCHAR) AS "measureImpactToDetails",
    CAST("measureName" AS VARCHAR) AS "measureName",
    CAST("measureNature" AS VARCHAR) AS "measureNature",
    CAST("measureOrigin" AS VARCHAR) AS "measureOrigin",
    CAST("sector" AS VARCHAR) AS "sector",
    CAST("spatialScope" AS VARCHAR) AS "spatialScope",
    CAST("status" AS VARCHAR) AS "status",
    CAST("useOrActivity" AS VARCHAR) AS "useOrActivity",
    CAST("waterBodyCategory" AS VARCHAR) AS "waterBodyCategory"
FROM "european-environment-agency-wise-shippingsports-measures.vw-master"
