SELECT
    CAST("Activity" AS VARCHAR) AS "Activity",
    CAST("Address" AS VARCHAR) AS "Address",
    CAST("Country" AS VARCHAR) AS "Country",
    CAST("CountryCode" AS VARCHAR) AS "CountryCode",
    CAST("eprtrReportingYear" AS VARCHAR) AS "eprtrReportingYear",
    CAST("euregReportingYear" AS VARCHAR) AS "euregReportingYear",
    CAST("Facility" AS VARCHAR) AS "Facility",
    CAST("FacilityId" AS VARCHAR) AS "FacilityId",
    CAST("gmlId" AS VARCHAR) AS "gmlId",
    CAST("identifier" AS VARCHAR) AS "identifier",
    CAST("installationCountryCode" AS VARCHAR) AS "installationCountryCode",
    CAST("installationPartName" AS VARCHAR) AS "installationPartName",
    CAST("localId" AS VARCHAR) AS "localId",
    CAST("mediumCode" AS VARCHAR) AS "mediumCode",
    CAST("permittedCapacityHazardous" AS VARCHAR) AS "permittedCapacityHazardous",
    CAST("permittedCapacityNonHazardous" AS VARCHAR) AS "permittedCapacityNonHazardous",
    CAST("plantType" AS VARCHAR) AS "plantType",
    CAST("Postal Code" AS VARCHAR) AS "Postal Code",
    CAST("totalNominalCapacityAnyWaste" AS VARCHAR) AS "totalNominalCapacityAnyWaste",
    CAST("totalPollutantQuantityKg" AS VARCHAR) AS "totalPollutantQuantityKg",
    CAST("totalRatedThermalInput" AS VARCHAR) AS "totalRatedThermalInput",
    CAST("Town/Village" AS VARCHAR) AS "Town/Village"
FROM "european-environment-agency-ied.tableau-analysis1-2-table"
