SELECT
    CAST("CountryCode" AS VARCHAR) AS "CountryCode",
    CAST("rcaArt58DateDesign" AS VARCHAR) AS "rcaArt58DateDesign",
    CAST("rcaArt58DateDesign_original" AS VARCHAR) AS "rcaArt58DateDesign_original",
    CAST("rcaBeginLife" AS VARCHAR) AS "rcaBeginLife",
    CAST("rcaBeginLife_original" AS VARCHAR) AS "rcaBeginLife_original",
    CAST("rcaCode" AS VARCHAR) AS "rcaCode",
    CAST("rcaDateArt54" AS VARCHAR) AS "rcaDateArt54",
    CAST("rcaDateArt54_original" AS VARCHAR) AS "rcaDateArt54_original",
    CAST("rcaDateArt58" AS VARCHAR) AS "rcaDateArt58",
    CAST("rcaDateArt58_original" AS VARCHAR) AS "rcaDateArt58_original",
    CAST("rcaEndLife" AS VARCHAR) AS "rcaEndLife",
    CAST("rcaEndLife_original" AS VARCHAR) AS "rcaEndLife_original",
    CAST("rcaEnvDom" AS VARCHAR) AS "rcaEnvDom",
    CAST("rcaHyperlink" AS VARCHAR) AS "rcaHyperlink",
    CAST("rcaName" AS VARCHAR) AS "rcaName",
    CAST("rcaParameterM" AS VARCHAR) AS "rcaParameterM",
    CAST("rcaParameterN" AS VARCHAR) AS "rcaParameterN",
    CAST("rcaParameterOther" AS VARCHAR) AS "rcaParameterOther",
    CAST("rcaParameterP" AS VARCHAR) AS "rcaParameterP",
    CAST("rcaRemarks" AS VARCHAR) AS "rcaRemarks",
    CAST("rcaSpZTyp" AS VARCHAR) AS "rcaSpZTyp",
    CAST("rcaZtype" AS VARCHAR) AS "rcaZtype",
    CAST("ReceivingAreas_SAMainId" AS VARCHAR) AS "ReceivingAreas_SAMainId",
    CAST("repCode" AS VARCHAR) AS "repCode"
FROM "european-environment-agency-wise-uwwtd.t-receivingareas-samain"
