SELECT
    CAST("countryCode" AS VARCHAR) AS "countryCode",
    CAST("countryGroup" AS VARCHAR) AS "countryGroup",
    CAST("countryName" AS VARCHAR) AS "countryName",
    CAST("cYear" AS VARCHAR) AS "cYear",
    CAST("euRBDCode" AS VARCHAR) AS "euRBDCode",
    CAST("fileUrl" AS VARCHAR) AS "fileUrl",
    CAST("hasDescriptiveData" AS VARCHAR) AS "hasDescriptiveData",
    CAST("psAnalyticalMethod" AS VARCHAR) AS "psAnalyticalMethod",
    CAST("psAnalyticalMethodBAT" AS VARCHAR) AS "psAnalyticalMethodBAT",
    CAST("psCategoryCW" AS VARCHAR) AS "psCategoryCW",
    CAST("psCategoryLW" AS VARCHAR) AS "psCategoryLW",
    CAST("psCategoryRW" AS VARCHAR) AS "psCategoryRW",
    CAST("psCategoryTeW" AS VARCHAR) AS "psCategoryTeW",
    CAST("psCategoryTW" AS VARCHAR) AS "psCategoryTW",
    CAST("psCode" AS VARCHAR) AS "psCode",
    CAST("psMatrix" AS VARCHAR) AS "psMatrix",
    CAST("psScale" AS VARCHAR) AS "psScale",
    CAST("psStandardsUsed" AS VARCHAR) AS "psStandardsUsed",
    CAST("psStandardType" AS VARCHAR) AS "psStandardType",
    CAST("psStatusAssessment" AS VARCHAR) AS "psStatusAssessment",
    CAST("psUnit" AS VARCHAR) AS "psUnit",
    CAST("psValue" AS VARCHAR) AS "psValue",
    CAST("rbdArea" AS VARCHAR) AS "rbdArea",
    CAST("rbdName" AS VARCHAR) AS "rbdName",
    CAST("uPBT" AS VARCHAR) AS "uPBT"
FROM "european-environment-agency-wise-wfd.swmet-swprioritysubstance"
