SELECT
    CAST("additionalTreeCover" AS VARCHAR) AS "additionalTreeCover",
    CAST("averageTreeCover" AS VARCHAR) AS "averageTreeCover",
    CAST("broadleavedTypeTreeNumber" AS VARCHAR) AS "broadleavedTypeTreeNumber",
    CAST("coniferTypeTreeNumber" AS VARCHAR) AS "coniferTypeTreeNumber",
    CAST("countriesTotalNumber" AS VARCHAR) AS "countriesTotalNumber",
    CAST("countriesTotalNumberCitizens" AS VARCHAR) AS "countriesTotalNumberCitizens",
    CAST("countriesTotalNumberOrganizations" AS VARCHAR) AS "countriesTotalNumberOrganizations",
    CAST("mixedTypeTreeNumber" AS VARCHAR) AS "mixedTypeTreeNumber",
    CAST("organisationsEuTotalNumber" AS VARCHAR) AS "organisationsEuTotalNumber",
    CAST("organisationsUniqueTotalNumber" AS VARCHAR) AS "organisationsUniqueTotalNumber",
    CAST("parcelAgriculturalAreaTypeLandNumber" AS VARCHAR) AS "parcelAgriculturalAreaTypeLandNumber",
    CAST("parcelAlongInfrastructureCorridorsTypeLandNumber" AS VARCHAR) AS "parcelAlongInfrastructureCorridorsTypeLandNumber",
    CAST("parcelForestAreaTypeLandNumber" AS VARCHAR) AS "parcelForestAreaTypeLandNumber",
    CAST("parcelMixedOwnershipNumber" AS VARCHAR) AS "parcelMixedOwnershipNumber",
    CAST("parcelOthersTypeLandNumber" AS VARCHAR) AS "parcelOthersTypeLandNumber",
    CAST("parcelPrivateOwnershipNumber" AS VARCHAR) AS "parcelPrivateOwnershipNumber",
    CAST("parcelPublicOwnershipNumber" AS VARCHAR) AS "parcelPublicOwnershipNumber",
    CAST("parcelTotalNumber" AS VARCHAR) AS "parcelTotalNumber",
    CAST("parcelUrbanPeriUrbanAreaTypeLandNumber" AS VARCHAR) AS "parcelUrbanPeriUrbanAreaTypeLandNumber",
    CAST("pledgesTotalNumber" AS VARCHAR) AS "pledgesTotalNumber",
    CAST("treesTotalNumber" AS VARCHAR) AS "treesTotalNumber",
    CAST("treesTotalNumberCitizens" AS VARCHAR) AS "treesTotalNumberCitizens",
    CAST("treesTotalNumberCitizensNonEu" AS VARCHAR) AS "treesTotalNumberCitizensNonEu",
    CAST("treesTotalNumberNonEu" AS VARCHAR) AS "treesTotalNumberNonEu",
    CAST("treesTotalNumberOrganizations" AS VARCHAR) AS "treesTotalNumberOrganizations",
    CAST("treesTotalNumberOrganizationsNonEu" AS VARCHAR) AS "treesTotalNumberOrganizationsNonEu"
FROM "european-environment-agency-mapmytree.v-eu-tree-counter"
