columns:
  - name: "country"
    type: VARCHAR
  - name: "group_type"
    type: VARCHAR
  - name: "group_value"
    type: VARCHAR
  - name: "NUTS_CODE"
    type: VARCHAR
  - name: "order_group"
    type: VARCHAR
  - name: "units"
    type: VARCHAR
  - name: "year"
    type: VARCHAR
