SELECT
    CAST("chemicalMonitoring" AS VARCHAR) AS "chemicalMonitoring",
    CAST("countryCode" AS VARCHAR) AS "countryCode",
    CAST("countryGroup" AS VARCHAR) AS "countryGroup",
    CAST("countryName" AS VARCHAR) AS "countryName",
    CAST("cYear" AS VARCHAR) AS "cYear",
    CAST("depth" AS VARCHAR) AS "depth",
    CAST("ecologicalMonitoring" AS VARCHAR) AS "ecologicalMonitoring",
    CAST("euMonitoringSiteCode" AS VARCHAR) AS "euMonitoringSiteCode",
    CAST("euProgrammeCode" AS VARCHAR) AS "euProgrammeCode",
    CAST("euRBDCode" AS VARCHAR) AS "euRBDCode",
    CAST("euSubUnitCode" AS VARCHAR) AS "euSubUnitCode",
    CAST("fileUrl" AS VARCHAR) AS "fileUrl",
    CAST("hasDescriptiveData" AS VARCHAR) AS "hasDescriptiveData",
    CAST("investigativeMonitoring" AS VARCHAR) AS "investigativeMonitoring",
    CAST("monitoringSiteName" AS VARCHAR) AS "monitoringSiteName",
    CAST("operationalMonitoring" AS VARCHAR) AS "operationalMonitoring",
    CAST("quantitativeMonitoring" AS VARCHAR) AS "quantitativeMonitoring",
    CAST("rbdArea" AS VARCHAR) AS "rbdArea",
    CAST("rbdName" AS VARCHAR) AS "rbdName",
    CAST("subUnitName" AS VARCHAR) AS "subUnitName",
    CAST("surveillanceMonitoring" AS VARCHAR) AS "surveillanceMonitoring",
    CAST("waterBodyCategory" AS VARCHAR) AS "waterBodyCategory",
    CAST("waterBodyCode" AS VARCHAR) AS "waterBodyCode",
    CAST("waterBodyName" AS VARCHAR) AS "waterBodyName",
    CAST("wellSpring" AS VARCHAR) AS "wellSpring",
    CAST("wiseEvolutionType" AS VARCHAR) AS "wiseEvolutionType"
FROM "european-environment-agency-wise-wfd.monitoring-monitoringsite-euprogrammecode"
