SELECT
    CAST("Country" AS VARCHAR) AS "Country",
    CAST("FORES_AREA" AS VARCHAR) AS "FORES_AREA",
    CAST("NUTS_CODE" AS VARCHAR) AS "NUTS_CODE",
    CAST("OTHER_L" AS VARCHAR) AS "OTHER_L",
    CAST("OTHER_WL" AS VARCHAR) AS "OTHER_WL",
    CAST("PERC_FOREST" AS VARCHAR) AS "PERC_FOREST",
    CAST("TOTAL_AREA" AS VARCHAR) AS "TOTAL_AREA",
    CAST("YEAR" AS VARCHAR) AS "YEAR"
FROM "european-environment-agency-fise.nfi-forest-area"
