SELECT
    CAST(DATA_OSS AS TIMESTAMP)::DATE AS date,
    CUBEID AS series_key,
    TRY_CAST(VALORE AS DOUBLE) AS value,
    * EXCLUDE (DATA_OSS, CUBEID, VALORE)
FROM "bank-of-italy-tsdpt020"
WHERE TRY_CAST(VALORE AS DOUBLE) IS NOT NULL
  AND DATA_OSS IS NOT NULL
