-- compiled by `hardened compile-transforms` from the measured model
-- profiles (model/tables + columns). Faithful pass-through: verified
-- pure casts only, no data fixes. Regenerate after model-verify;
-- durable edits belong in the model stage, not here.
-- caution: Each row is a person-level death record; incident-level counts can differ when multiple people are killed on the same date or in the same event.
SELECT
    "name",
    "age",
    "gender",
    "race",
    "victim_image",
    "date",
    "street_address",
    "city",
    "state",
    "zip",
    "county",
    "agency_responsible",
    "ori",
    "use_of_force",
    "circumstances",
    "disposition_official",
    "officer_charged",
    "news_urls",
    "signs_of_mental_illness",
    "allegedly_armed_with",
    "wapo_threat_level",
    "threat_perception",
    "flee",
    "incident_footage",
    "encounter_type",
    "initial_reason",
    "call_for_service",
    "officer_names",
    "officer_races",
    "officer_known_past_shootings",
    "off_duty_killing",
    "wapo_id",
    "mpv_id",
    "fe_id",
    "geography",
    "tract",
    "urban_rural_uspsai",
    "urban_rural_nchs",
    CAST("hhincome_median_census_tract" AS HUGEINT) AS "hhincome_median_census_tract",
    "latitude",
    "longitude",
    "pop_total_census_tract",
    "pop_white_census_tract",
    "pop_black_census_tract",
    "pop_native_american_census_tract",
    "pop_asian_census_tract",
    "pop_pacific_islander_census_tract",
    "pop_other_multiple_census_tract",
    "pop_hispanic_census_tract",
    "congressional_district_113",
    "congressperson_lastname",
    "congressperson_firstname",
    "congressperson_party",
    "prosecutor_head",
    "prosecutor_race",
    "prosecutor_gender",
    "prosecutor_party",
    "prosecutor_term",
    "prosecutor_in_court",
    "prosecutor_special",
    "independent_investigation",
    "prosecutor_url"
FROM "mapping-police-violence-mapping-police-violence-killings"
