SELECT
    name,
    TRY_CAST(age AS INTEGER)                              AS age,
    gender,
    race,
    CAST(date AS DATE)                                    AS date,
    street_address,
    city,
    state,
    zip,
    county,
    agency_responsible,
    ori,
    cause_of_death,
    circumstances,
    disposition_official,
    officer_charged,
    signs_of_mental_illness,
    allegedly_armed,
    wapo_armed,
    wapo_threat_level,
    wapo_flee,
    wapo_body_camera,
    TRY_CAST(wapo_id AS BIGINT)                           AS wapo_id,
    off_duty_killing,
    geography,
    TRY_CAST(mpv_id AS BIGINT)                            AS mpv_id,
    TRY_CAST(fe_id AS BIGINT)                             AS fe_id,
    encounter_type,
    initial_reason,
    officer_names,
    officer_races,
    officer_known_past_shootings,
    call_for_service,
    TRY_CAST(tract AS BIGINT)                             AS tract,
    urban_rural_uspsai,
    urban_rural_nchs,
    TRY_CAST(hhincome_median_census_tract AS BIGINT)     AS hhincome_median_census_tract,
    TRY_CAST(latitude AS DOUBLE)                          AS latitude,
    TRY_CAST(longitude AS DOUBLE)                         AS longitude,
    TRY_CAST(pop_total_census_tract AS BIGINT)           AS pop_total_census_tract,
    TRY_CAST(pop_white_census_tract AS DOUBLE)           AS pop_white_census_tract,
    TRY_CAST(pop_black_census_tract AS DOUBLE)           AS pop_black_census_tract,
    TRY_CAST(pop_native_american_census_tract AS DOUBLE) AS pop_native_american_census_tract,
    TRY_CAST(pop_asian_census_tract AS DOUBLE)           AS pop_asian_census_tract,
    TRY_CAST(pop_pacific_islander_census_tract AS DOUBLE) AS pop_pacific_islander_census_tract,
    TRY_CAST(pop_other_multiple_census_tract AS DOUBLE)  AS pop_other_multiple_census_tract,
    TRY_CAST(pop_hispanic_census_tract AS DOUBLE)        AS pop_hispanic_census_tract,
    congressional_district_113,
    congressperson_lastname,
    congressperson_firstname,
    congressperson_party,
    prosecutor_head,
    prosecutor_race,
    prosecutor_gender,
    prosecutor_party,
    prosecutor_term,
    prosecutor_in_court,
    prosecutor_special,
    independent_investigation,
    prosecutor_url
FROM "mapping-police-violence-mapping-police-violence-killings"
WHERE mpv_id IS NOT NULL
